import {expect,test} from "bun:test";
import Ajv from "ajv/dist/2020";
import {Database} from "bun:sqlite";
import fixture from "./🔣️.json";
import schema from "./🧬️schema/🔣️.json";
import {ArtifactSqliteProjection,artifactSqliteTables} from "../../🧩️artifact/🟦️.ts";
import {sqliteOperation} from "../../🟦️.ts";
const quote=(name:string)=>'"'+name.replaceAll('"','""')+'"';
const sql=fixture.tableNames.map(name=>`CREATE TABLE ${quote(name)} (id INTEGER PRIMARY KEY,payload TEXT)`).join(';');
test('closed checked index collision contract has independent Map and SQLite answers',()=>{
 const validate=new Ajv({strict:true}).compile(schema);expect(validate(fixture)).toBe(true);expect(validate({...fixture,extra:0})).toBe(false);
 const index=new Map(fixture.tableNames.map((name,index)=>[name,index]));for(let i=0;i<fixture.lookupNames.length;i++)expect(index.get(fixture.lookupNames[i]!)??null).toBe(fixture.lookupIndices[i]);
 const hash=(name:string)=>{let value=fixture.hash.offset;for(const code of name){const n=code.charCodeAt(0);value=Math.imul(value^(n>=65&&n<=90?n+32:n),fixture.hash.prime)>>>0;}return value&fixture.hash.mask;};for(const name of fixture.tableNames)expect(hash(name)).toBe(fixture.hash.collisionBucket);
 expect(new Uint32Array(fixture.capacity).byteLength).toBe(fixture.tableSlotBytes);
 const db=new Database(':memory:');try{db.exec(sql);for(let i=0;i<fixture.tableNames.length;i++)db.query(`INSERT INTO ${quote(fixture.tableNames[i]!)} VALUES (1,?)`).run(String(i));for(let i=0;i<fixture.tableNames.length;i++)expect(db.query(`SELECT payload FROM ${quote(fixture.tableNames[i]!)} WHERE id=1`).get()).toEqual({payload:String(i)});}finally{db.close();}
 for(const group of fixture.groups){const actual=fixture.rows.map((row,index)=>({row,index})).filter(v=>v.row.parent===group.parent).sort((a,b)=>a.row.ordinal-b.row.ordinal).map(v=>v.index);expect(actual).toEqual(group.positions);}
});
for(const direction of ['projection','reconstruction'] as const)test('actual supplied checked table slots exact short cumulative '+direction,async()=>{
 const plain=await ArtifactSqliteProjection.create(sql);for(let i=0;i<fixture.tableNames.length;i++)await plain.insert(fixture.tableNames[i]!,[String(i)]);const expected=await plain.finish();
 const run=async(operation:ReturnType<typeof sqliteOperation>)=>{if(direction==='reconstruction')return artifactSqliteTables({...expected,tables:[...expected.tables].reverse()},sql,operation);const projection=await ArtifactSqliteProjection.create(sql,operation);for(let i=0;i<fixture.tableNames.length;i++)await projection.insert(fixture.tableNames[i]!,[String(i)]);return projection.finish();};
 const probe=sqliteOperation();const result=await run(probe);expect(probe.ownedBytes).toBeGreaterThanOrEqual(fixture.tableSlotBytes);expect(result).toEqual(direction==='projection'?expected:expected.tables.map(table=>table.rows));
 const exact=sqliteOperation({maxAllocationBytes:probe.ownedBytes});expect(await run(exact)).toEqual(result);expect(exact.remainingBytes()).toBe(0);await expect(run(exact)).rejects.toMatchObject({kind:'ownershipLimit'});
 await expect(run(sqliteOperation({maxAllocationBytes:probe.ownedBytes-1}))).rejects.toMatchObject({kind:'ownershipLimit'});
 const twice=sqliteOperation({maxAllocationBytes:probe.ownedBytes*2});expect(await run(twice)).toEqual(result);expect(await run(twice)).toEqual(result);expect(twice.remainingBytes()).toBe(0);await expect(run(twice)).rejects.toMatchObject({kind:'ownershipLimit'});
});

import {ArtifactSqliteTableIndex} from "../../🧩️artifact/🗂️table/🟦️.ts";
for(const exact of[true,false])test('direct table index complete literal names '+exact,async()=>{const part=fixture.directSeam,names=exact?part.exactNames:part.foldNames,queries=exact?part.exactQueries:part.foldQueries,positions=exact?part.exactPositions:part.foldPositions;const operation=sqliteOperation(),index=await ArtifactSqliteTableIndex.create(names.map(name=>({name})),operation,exact),oracle=new Map(names.map((name,index)=>[exact?name:name.replace(/[A-Z]/g,c=>c.toLowerCase()),index]));for(let i=0;i<queries.length;i++){const key=exact?queries[i]!:queries[i]!.replace(/[A-Z]/g,c=>c.toLowerCase());expect(oracle.get(key)??-1).toBe(positions[i]);expect(await index.find(queries[i]!)).toBe(positions[i]);}});
for(const specimen of fixture.directSeam.duplicateCases)test('direct table index refuses duplicate comparison '+specimen.exact,async()=>{await expect(ArtifactSqliteTableIndex.create(specimen.names.map(name=>({name})),sqliteOperation(),specimen.exact)).rejects.toMatchObject({kind:'invalidValue'});});
test('direct table index exact slot byte budget and cumulative caller',async()=>{const names=fixture.tableNames.map(name=>({name})),bytes=fixture.tableSlotBytes;for(const maximum of[0,bytes-1])await expect(ArtifactSqliteTableIndex.create(names,sqliteOperation({maxAllocationBytes:maximum}))).rejects.toMatchObject({kind:'ownershipLimit'});const exact=sqliteOperation({maxAllocationBytes:bytes});expect(await(await ArtifactSqliteTableIndex.create(names,exact)).find('q')).toBe(2);expect(exact.ownedBytes).toBe(bytes);await expect(ArtifactSqliteTableIndex.create(names,exact)).rejects.toMatchObject({kind:'ownershipLimit'});const twice=sqliteOperation({maxAllocationBytes:bytes*2});for(let i=0;i<2;i++)expect(await(await ArtifactSqliteTableIndex.create(names,twice)).find('i')).toBe(1);expect(twice.ownedBytes).toBe(bytes*2);await expect(ArtifactSqliteTableIndex.create(names,twice)).rejects.toMatchObject({kind:'ownershipLimit'});});
test('direct table index materialized collision lookup cancellation',async()=>{const part=fixture.directSeam,abort=new AbortController();let armed=false,reached=false;const operation=sqliteOperation({signal:abort.signal,onProgress:event=>{if(armed&&operation.ownedBytes>0&&event.phase==='indexTables'&&event.completed===part.probeFrontier&&event.total===part.collisionSlots){reached=true;abort.abort();}}}),index=await ArtifactSqliteTableIndex.create(part.collisionNames.map(name=>({name})),operation);expect(operation.ownedBytes).toBe(part.collisionSlots*4);armed=true;await expect(index.find(part.collisionNames.at(-1)!)).rejects.toMatchObject({kind:'canceled'});expect(reached).toBe(true);expect(operation.ownedBytes).toBe(part.collisionSlots*4);});
test('direct table index materialized long literal lookup cancellation',async()=>{const part=fixture.directSeam,name=part.longUnit.repeat(part.longRepeat),abort=new AbortController();let armed=false,reached=false;const operation=sqliteOperation({signal:abort.signal,onProgress:event=>{if(armed&&operation.ownedBytes>0&&event.phase==='indexTables'&&event.completed===part.nameFrontier&&event.completed<event.total){reached=true;abort.abort();}}}),index=await ArtifactSqliteTableIndex.create([{name}],operation);armed=true;await expect(index.find(name)).rejects.toMatchObject({kind:'canceled'});expect(reached).toBe(true);});
test('direct table index checked size refuses before mapping impossible census',async()=>{let mapped=false;const hostile=new Proxy([] as {name:string}[],{get(target,key,receiver){if(key==='length')return fixture.directSeam.overflowLength;if(key==='map')return()=>{mapped=true;throw new Error('forbidden census materialization');};return Reflect.get(target,key,receiver);}}),operation=sqliteOperation({maxTables:fixture.directSeam.overflowLength});await expect(ArtifactSqliteTableIndex.create(hostile,operation)).rejects.toMatchObject({kind:'workLimit'});expect(mapped).toBe(false);expect(operation.ownedBytes).toBe(0);});

test('direct literal Unicode and quoted index names independently match SQLite',()=>{const names=fixture.directSeam.foldNames.filter(name=>!name.includes('\0')),db=new Database(':memory:');const quoted=(name:string)=>'"'+name.replaceAll('"','""')+'"';try{for(let i=0;i<names.length;i++){db.exec(`CREATE TABLE ${quoted(names[i]!)} (payload TEXT)`);db.query(`INSERT INTO ${quoted(names[i]!)} VALUES (?)`).run(String(i));}for(let i=0;i<names.length;i++)expect(db.query(`SELECT payload FROM ${quoted(names[i]!.replace(/[A-Z]/g,c=>c.toLowerCase()))}`).get()).toEqual({payload:String(i)});}finally{db.close();}});

import backingLimits from "../🔢️backing-limits/🔣️.json";
import backingLimitSchema from "../🔢️backing-limits/🧬️schema/🔣️.json";
test('closed half-load storage boundary refuses before borrowed census traversal',async()=>{
 const validate=new Ajv({strict:true}).compile(backingLimitSchema);expect(validate(backingLimits)).toBe(true);expect(validate({...backingLimits,extra:1})).toBe(false);
 expect(BigInt(backingLimits.maximumHalfLoadEntries)*2n).toBe(BigInt(backingLimits.maximumSlots));expect(BigInt(backingLimits.firstImpossibleEntries)*2n>BigInt(backingLimits.maximumSlots)).toBe(true);
 let traversed=false;const hostile=new Proxy([],{get(target,key,receiver){if(key==='length')return backingLimits.firstImpossibleEntries;if(key==='map'||key===Symbol.iterator)return()=>{traversed=true;throw new Error('forbidden impossible census traversal');};return Reflect.get(target,key,receiver);}});
 const operation=sqliteOperation({maxTables:backingLimits.firstImpossibleEntries});await expect(ArtifactSqliteTableIndex.create(hostile as any,operation)).rejects.toMatchObject({kind:backingLimits.refusal});expect(traversed).toBe(false);expect(operation.ownedBytes).toBe(backingLimits.expectedOwnedBytes);
});
