/** 🔲️ Explicit regular two-dimensional constraints and per-command point coordinates. */
import type{Grid2dSnapshot,WfcColor,WfcPoint2,WfcPathSegment,WfcVectorPath,WfcTile2d,WfcTileMedia2d,WfcDirection2d,WfcAdjacencyRule2d,WfcPinnedCell2d,WfcCell2d}from"../../../🧬️schema/📸️snapshot/🟦️.ts";
import{ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteDocument,artifactSqliteInteger,artifactSqliteText,artifactSqliteBoolean,artifactSqliteCheckpoint,artifactSqliteOrderedRowsControlled,type ArtifactSqliteOptions}from"../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {encodeIeee754Cells,readBinary64,ieee754IsNull} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import {type Binary64} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts";
import type{SqliteDatabase,SqliteRow}from"../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
export const WFC_GRID2D_SQLITE_SCHEMA=`CREATE TABLE wfc_grid2d_document (
 id INTEGER PRIMARY KEY CHECK(id=1), schema_id TEXT NOT NULL, seed TEXT NOT NULL,
 width INTEGER NOT NULL CHECK(width BETWEEN 0 AND 4294967295), height INTEGER NOT NULL CHECK(height BETWEEN 0 AND 4294967295),
 cell_width REAL, cell_height REAL, periodic_x INTEGER NOT NULL CHECK(periodic_x IN (0,1)), periodic_y INTEGER NOT NULL CHECK(periodic_y IN (0,1)),
 cell_width_ieee754_bits INTEGER NOT NULL, cell_width_numeric_class TEXT NOT NULL CHECK(cell_width_numeric_class IN ('finite','positiveInfinity','negativeInfinity','nan')),
 cell_height_ieee754_bits INTEGER NOT NULL, cell_height_numeric_class TEXT NOT NULL CHECK(cell_height_numeric_class IN ('finite','positiveInfinity','negativeInfinity','nan'))
);
CREATE TABLE wfc_grid2d_tile (
 id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid2d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), authored_id TEXT NOT NULL, label TEXT, weight REAL,
 media_kind TEXT NOT NULL CHECK(media_kind IN ('bitmap','vector','image')),
 weight_ieee754_bits INTEGER NOT NULL, weight_numeric_class TEXT NOT NULL CHECK(weight_numeric_class IN ('finite','positiveInfinity','negativeInfinity','nan'))
);
CREATE TABLE wfc_grid2d_bitmap (
 id INTEGER PRIMARY KEY REFERENCES wfc_grid2d_tile(id), width INTEGER NOT NULL CHECK(width BETWEEN 0 AND 4294967295), height INTEGER NOT NULL CHECK(height BETWEEN 0 AND 4294967295), storage_kind TEXT NOT NULL CHECK(storage_kind IN ('indices','literal'))
);
CREATE TABLE wfc_grid2d_palette (
 id INTEGER PRIMARY KEY, bitmap_id INTEGER NOT NULL REFERENCES wfc_grid2d_bitmap(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0),
 red INTEGER NOT NULL CHECK(red BETWEEN 0 AND 4294967295), green INTEGER NOT NULL CHECK(green BETWEEN 0 AND 4294967295), blue INTEGER NOT NULL CHECK(blue BETWEEN 0 AND 4294967295), alpha INTEGER NOT NULL CHECK(alpha BETWEEN 0 AND 4294967295)
);
CREATE TABLE wfc_grid2d_vector (id INTEGER PRIMARY KEY REFERENCES wfc_grid2d_tile(id));
CREATE TABLE wfc_grid2d_path (
 id INTEGER PRIMARY KEY, vector_id INTEGER NOT NULL REFERENCES wfc_grid2d_vector(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), stroke_width REAL,
 stroke_width_ieee754_bits INTEGER NOT NULL, stroke_width_numeric_class TEXT NOT NULL CHECK(stroke_width_numeric_class IN ('finite','positiveInfinity','negativeInfinity','nan'))
);
CREATE TABLE wfc_grid2d_path_color (
 id INTEGER PRIMARY KEY, path_id INTEGER NOT NULL REFERENCES wfc_grid2d_path(id), role TEXT NOT NULL CHECK(role IN ('fill','stroke')),
 red INTEGER NOT NULL CHECK(red BETWEEN 0 AND 4294967295), green INTEGER NOT NULL CHECK(green BETWEEN 0 AND 4294967295), blue INTEGER NOT NULL CHECK(blue BETWEEN 0 AND 4294967295), alpha INTEGER NOT NULL CHECK(alpha BETWEEN 0 AND 4294967295)
);
CREATE TABLE wfc_grid2d_segment (
 id INTEGER PRIMARY KEY, path_id INTEGER NOT NULL REFERENCES wfc_grid2d_path(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0),
 kind TEXT NOT NULL CHECK(kind IN ('moveTo','lineTo','quadTo','cubicTo','close')),
 to_x REAL, to_y REAL, control1_x REAL, control1_y REAL, control2_x REAL, control2_y REAL,
 to_x_ieee754_bits INTEGER, to_x_numeric_class TEXT, to_y_ieee754_bits INTEGER, to_y_numeric_class TEXT,
 control1_x_ieee754_bits INTEGER, control1_x_numeric_class TEXT, control1_y_ieee754_bits INTEGER, control1_y_numeric_class TEXT,
 control2_x_ieee754_bits INTEGER, control2_x_numeric_class TEXT, control2_y_ieee754_bits INTEGER, control2_y_numeric_class TEXT
);
CREATE TABLE wfc_grid2d_image (
 id INTEGER PRIMARY KEY REFERENCES wfc_grid2d_tile(id), child_id TEXT NOT NULL, artifact_id TEXT NOT NULL, artifact_kind TEXT NOT NULL, standard TEXT NOT NULL, subset TEXT NOT NULL
);
CREATE TABLE wfc_grid2d_rule (
 id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid2d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), authored_id TEXT NOT NULL,
 tile_a_id TEXT NOT NULL, tile_b_id TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('LEFT','RIGHT','TOP','BOTTOM')), allowed INTEGER NOT NULL CHECK(allowed IN (0,1))
);
CREATE TABLE wfc_grid2d_pin (
 id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid2d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0),
 x INTEGER NOT NULL CHECK(x BETWEEN 0 AND 4294967295), y INTEGER NOT NULL CHECK(y BETWEEN 0 AND 4294967295), tile_id TEXT NOT NULL
);
CREATE TABLE wfc_grid2d_mask (
 id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid2d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0),
 x INTEGER NOT NULL CHECK(x BETWEEN 0 AND 4294967295), y INTEGER NOT NULL CHECK(y BETWEEN 0 AND 4294967295)
);
CREATE TABLE wfc_grid2d_bitmap_pixel (
 id INTEGER PRIMARY KEY, bitmap_id INTEGER NOT NULL REFERENCES wfc_grid2d_bitmap(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), palette_index INTEGER NOT NULL CHECK(palette_index BETWEEN 0 AND 255)
);
CREATE TABLE wfc_grid2d_bitmap_literal_scalar (
 id INTEGER PRIMARY KEY, bitmap_id INTEGER NOT NULL REFERENCES wfc_grid2d_bitmap(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), scalar_text TEXT NOT NULL
);

`;
const DOCUMENT=[{index:5,width:64},{index:6,width:64}]as const,WEIGHT=[{index:5,width:64}]as const,PATH=[{index:3,width:64}]as const,SEGMENT=[{index:4,width:64},{index:5,width:64},{index:6,width:64},{index:7,width:64},{index:8,width:64},{index:9,width:64}]as const;
function unsigned(v:number):bigint{if(!Number.isInteger(v)||v<0||v>4294967295)throw Error('grid2d unsigned32 differs');return BigInt(v);}
function word(r:SqliteRow,i:number):number{const n=artifactSqliteInteger(r,i);if(n<0n||n>4294967295n)throw Error('grid2d unsigned32 differs');return Number(n);}
function flag(v:boolean):bigint{if(typeof v!=='boolean')throw Error('grid2d boolean differs');return v?1n:0n;}
function identity(r:SqliteRow,n:number):void{if(r.rowid<=0n||r.values.length!==n||artifactSqliteInteger(r,0)!==r.rowid)throw Error('grid2d identity or field count differs');}
async function groups(rows:readonly SqliteRow[],owners:ReadonlySet<bigint>,n:number,o:ArtifactSqliteOptions):Promise<Map<bigint,SqliteRow[]>>{const map=new Map<bigint,SqliteRow[]>(),ids=new Set<bigint>();for(let i=0;i<rows.length;i++){const r=rows[i]!;identity(r,n);if(ids.has(r.rowid))throw Error('duplicate grid2d entity identity');ids.add(r.rowid);const owner=artifactSqliteInteger(r,1);if(!owners.has(owner))throw Error('grid2d relationship has unknown owner');let group=map.get(owner);if(!group)map.set(owner,group=[]);group.push(r);if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,rows.length);}return map;}
async function media(rows:readonly SqliteRow[],owners:ReadonlySet<bigint>,n:number,o:ArtifactSqliteOptions):Promise<Map<bigint,SqliteRow>>{const map=new Map<bigint,SqliteRow>();for(let i=0;i<rows.length;i++){const r=rows[i]!;identity(r,n);if(!owners.has(r.rowid)||map.has(r.rowid))throw Error('grid2d media wrong-kind or unknown owner');map.set(r.rowid,r);if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,rows.length);}if(map.size!==owners.size)throw Error('grid2d media ownership incomplete');return map;}
function colorCells(c:WfcColor):bigint[]{return[unsigned(c.r),unsigned(c.g),unsigned(c.b),unsigned(c.a)];}
function color(r:SqliteRow,i:number):WfcColor{return{r:word(r,i),g:word(r,i+1),b:word(r,i+2),a:word(r,i+3)};}
function point(r:SqliteRow,i:number):WfcPoint2{return{x:readBinary64(r,i,SEGMENT),y:readBinary64(r,i+1,SEGMENT)};}
/** 📤️ Stores the authored grid without imposing solver or image-renderer validation. */
export async function grid2dSnapshotToSqliteDatabase(s:Grid2dSnapshot,o:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const p=await ArtifactSqliteProjection.create(WFC_GRID2D_SQLITE_SCHEMA,o);if(typeof s.seed!=='bigint'||s.seed<0n||s.seed>18446744073709551615n)throw Error('grid2d seed exceeds unsigned64');p.checkRowsAdditional(1+s.tiles.length+s.rules.length+s.pinned.length+s.masked.length);await p.insert('wfc_grid2d_document',encodeIeee754Cells([0n,s.schema,s.seed.toString(),unsigned(s.width),unsigned(s.height),s.cellWidth,s.cellHeight,flag(s.periodicX),flag(s.periodicY)],DOCUMENT).slice(1),1n);
 for(let i=0;i<s.tiles.length;i++){const t=s.tiles[i]!;const id=await p.insert('wfc_grid2d_tile',encodeIeee754Cells([0n,1n,BigInt(i),t.id,t.label??null,t.weight,t.media.kind],WEIGHT).slice(1));switch(t.media.kind){case'bitmap':{const m=t.media;p.checkRowsAdditional(1+m.palette.length);await projectBitmapPixels(p,BITMAP_TABLES,id,unsigned(m.width),unsigned(m.height),m.pixels,o);for(let j=0;j<m.palette.length;j++)await p.insert('wfc_grid2d_palette',[id,BigInt(j),...colorCells(m.palette[j]!)]);break;}case'image':{const child=t.media.child,target=child.target;await p.insert('wfc_grid2d_image',[child.childId,target.artifactId,target.dialect.artifactKind,target.dialect.standard,target.dialect.subset],id);break;}case'vector':{const paths=t.media.paths;p.checkRowsAdditional(1+paths.length);await p.insert('wfc_grid2d_vector',[],id);for(let j=0;j<paths.length;j++){const path=paths[j]!;p.checkRowsAdditional(path.segments.length+(path.fill?1:0)+(path.stroke?1:0));const pathId=await p.insert('wfc_grid2d_path',encodeIeee754Cells([0n,id,BigInt(j),path.strokeWidth],PATH).slice(1));if(path.fill)await p.insert('wfc_grid2d_path_color',[pathId,'fill',...colorCells(path.fill)]);if(path.stroke)await p.insert('wfc_grid2d_path_color',[pathId,'stroke',...colorCells(path.stroke)]);for(let k=0;k<path.segments.length;k++){const v=path.segments[k]!;let to:WfcPoint2|undefined,c1:WfcPoint2|undefined,c2:WfcPoint2|undefined;switch(v.kind){case'moveTo':case'lineTo':to=v.to;break;case'quadTo':to=v.to;c1=v.ctrl;break;case'cubicTo':to=v.to;c1=v.ctrl1;c2=v.ctrl2;break;case'close':break;default:throw Error('grid2d path command differs');}await p.insert('wfc_grid2d_segment',encodeIeee754Cells([0n,pathId,BigInt(k),v.kind,to?.x??null,to?.y??null,c1?.x??null,c1?.y??null,c2?.x??null,c2?.y??null],SEGMENT).slice(1));}}break;}default:throw Error('grid2d media kind differs');}}
 for(let i=0;i<s.rules.length;i++){const r=s.rules[i]!;if(!['LEFT','RIGHT','TOP','BOTTOM'].includes(r.direction))throw Error('grid2d direction differs');await p.insert('wfc_grid2d_rule',[1n,BigInt(i),r.id,r.tileAId,r.tileBId,r.direction,flag(r.allowed)]);}for(let i=0;i<s.pinned.length;i++){const v=s.pinned[i]!;await p.insert('wfc_grid2d_pin',[1n,BigInt(i),unsigned(v.x),unsigned(v.y),v.tileId]);}for(let i=0;i<s.masked.length;i++){const v=s.masked[i]!;await p.insert('wfc_grid2d_mask',[1n,BigInt(i),unsigned(v.x),unsigned(v.y)]);}return p.finish();
}
/** 📥️ Reconstructs every ordered typed path and rejects orphaned or conflicting relationships. */
export async function grid2dSnapshotFromSqliteDatabase(d:SqliteDatabase,o:ArtifactSqliteOptions={}):Promise<Grid2dSnapshot>{
 const[documents,tileRows,bitmapRows,paletteRows,vectorRows,pathRows,colorRows,segmentRows,imageRows,ruleRows,pinRows,maskRows,pixelRows,literalRows]=await artifactSqliteTables(d,WFC_GRID2D_SQLITE_SCHEMA,o),doc=artifactSqliteDocument(documents!);identity(doc,13);const seedText=artifactSqliteText(doc,2);if(!/^(0|[1-9][0-9]*)$/.test(seedText)||seedText.length>20)throw Error('grid2d seed requires unsigned64 decimal');const seed=BigInt(seedText);if(seed>18446744073709551615n)throw Error('grid2d seed exceeds unsigned64');const roots=new Set([1n]),orderedTiles=await artifactSqliteOrderedRowsControlled((await groups(tileRows!,roots,9,o)).get(1n)??[],2,o),bitmapIds=new Set<bigint>(),vectorIds=new Set<bigint>(),imageIds=new Set<bigint>();
 for(let i=0;i<orderedTiles.length;i++){const r=orderedTiles[i]!;switch(artifactSqliteText(r,6)){case'bitmap':bitmapIds.add(r.rowid);break;case'vector':vectorIds.add(r.rowid);break;case'image':imageIds.add(r.rowid);break;default:throw Error('grid2d media kind differs');}readBinary64(r,5,WEIGHT);if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,orderedTiles.length);}
 const bitmaps=await media(bitmapRows!,bitmapIds,4,o),images=await media(imageRows!,imageIds,6,o);await media(vectorRows!,vectorIds,1,o);const palettes=await groups(paletteRows!,bitmapIds,7,o),paths=await groups(pathRows!,vectorIds,6,o),pathIds=new Set<bigint>();for(let i=0;i<pathRows!.length;i++){pathIds.add(pathRows![i]!.rowid);if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,pathRows!.length);}const segments=await groups(segmentRows!,pathIds,22,o),colors=new Map<bigint,Map<string,SqliteRow>>(),colorIds=new Set<bigint>();for(let i=0;i<colorRows!.length;i++){const r=colorRows![i]!;identity(r,7);const owner=artifactSqliteInteger(r,1),role=artifactSqliteText(r,2);if(!pathIds.has(owner)||!['fill','stroke'].includes(role)||colorIds.has(r.rowid))throw Error('grid2d path color role/ownership differs');colorIds.add(r.rowid);let roles=colors.get(owner);if(!roles)colors.set(owner,roles=new Map());if(roles.has(role))throw Error('duplicate grid2d path color role');roles.set(role,r);if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,colorRows!.length);}
 const bitmapPixels=await groups(pixelRows!,bitmapIds,4,o),bitmapLiterals=await groups(literalRows!,bitmapIds,4,o);
 const tiles:WfcTile2d[]=[];for(let i=0;i<orderedTiles.length;i++){const r=orderedTiles[i]!;let native:WfcTileMedia2d;switch(artifactSqliteText(r,6)){case'bitmap':{const v=bitmaps.get(r.rowid)!,palette:WfcColor[]=[];const rows=await artifactSqliteOrderedRowsControlled(palettes.get(r.rowid)??[],2,o);for(let j=0;j<rows.length;j++){palette.push(color(rows[j]!,3));if(j%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',j,rows.length);}native={kind:'bitmap',width:word(v,1),height:word(v,2),palette,pixels:await reconstructBitmapPixels(v,bitmapPixels.get(r.rowid)??[],bitmapLiterals.get(r.rowid)??[],o)};break;}case'image':{const v=images.get(r.rowid)!;native={kind:'image',child:{childId:artifactSqliteText(v,1),target:{artifactId:artifactSqliteText(v,2),dialect:{artifactKind:artifactSqliteText(v,3),standard:artifactSqliteText(v,4),subset:artifactSqliteText(v,5)}}}};break;}case'vector':{const nativePaths:WfcVectorPath[]=[],orderedPaths=await artifactSqliteOrderedRowsControlled(paths.get(r.rowid)??[],2,o);for(let j=0;j<orderedPaths.length;j++){const v=orderedPaths[j]!,nativeSegments:WfcPathSegment[]=[],orderedSegments=await artifactSqliteOrderedRowsControlled(segments.get(v.rowid)??[],2,o);for(let k=0;k<orderedSegments.length;k++){const s=orderedSegments[k]!,kind=artifactSqliteText(s,3);let count:number;switch(kind){case'close':count=0;break;case'moveTo':case'lineTo':count=2;break;case'quadTo':count=4;break;case'cubicTo':count=6;break;default:throw Error('grid2d path command differs');}for(let col=4;col<10;col++){if(ieee754IsNull(s,col,SEGMENT)!==(col>=4+count))throw Error('grid2d segment point presence differs');if(col<4+count)readBinary64(s,col,SEGMENT);}switch(kind){case'close':nativeSegments.push({kind:'close'});break;case'moveTo':nativeSegments.push({kind:'moveTo',to:point(s,4)});break;case'lineTo':nativeSegments.push({kind:'lineTo',to:point(s,4)});break;case'quadTo':nativeSegments.push({kind:'quadTo',ctrl:point(s,6),to:point(s,4)});break;case'cubicTo':nativeSegments.push({kind:'cubicTo',ctrl1:point(s,6),ctrl2:point(s,8),to:point(s,4)});break;}if(k%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',k,orderedSegments.length);}const fill=colors.get(v.rowid)?.get('fill'),stroke=colors.get(v.rowid)?.get('stroke');nativePaths.push({segments:nativeSegments,strokeWidth:readBinary64(v,3,PATH),...(fill?{fill:color(fill,3)}:{}),...(stroke?{stroke:color(stroke,3)}:{})});if(j%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',j,orderedPaths.length);}native={kind:'vector',paths:nativePaths};break;}default:throw Error('grid2d media kind differs');}const label=r.values[4]===null?undefined:artifactSqliteText(r,4);tiles.push({id:artifactSqliteText(r,3),...(label===undefined?{}:{label}),weight:readBinary64(r,5,WEIGHT),media:native});if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,orderedTiles.length);}
 const rules:WfcAdjacencyRule2d[]=[],pinned:WfcPinnedCell2d[]=[],masked:WfcCell2d[]=[];const ruleOrder=await artifactSqliteOrderedRowsControlled((await groups(ruleRows!,roots,8,o)).get(1n)??[],2,o);for(let i=0;i<ruleOrder.length;i++){const r=ruleOrder[i]!,id=artifactSqliteText(r,3),direction=artifactSqliteText(r,6);if(!['LEFT','RIGHT','TOP','BOTTOM'].includes(direction))throw Error('grid2d direction differs');rules.push({id,tileAId:artifactSqliteText(r,4),tileBId:artifactSqliteText(r,5),direction:direction as WfcDirection2d,allowed:artifactSqliteBoolean(r,7)});if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,ruleOrder.length);}const pinOrder=await artifactSqliteOrderedRowsControlled((await groups(pinRows!,roots,6,o)).get(1n)??[],2,o);for(let i=0;i<pinOrder.length;i++){const r=pinOrder[i]!;pinned.push({x:word(r,3),y:word(r,4),tileId:artifactSqliteText(r,5)});if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,pinOrder.length);}const maskOrder=await artifactSqliteOrderedRowsControlled((await groups(maskRows!,roots,5,o)).get(1n)??[],2,o);for(let i=0;i<maskOrder.length;i++){const r=maskOrder[i]!;masked.push({x:word(r,3),y:word(r,4)});if(i%256===0)await artifactSqliteCheckpoint(o,'reconstructSnapshot',i,maskOrder.length);}await artifactSqliteCheckpoint(o,'reconstructSnapshot',tiles.length,tiles.length);return{schema:artifactSqliteText(doc,1),seed,width:word(doc,3),height:word(doc,4),cellWidth:readBinary64(doc,5,DOCUMENT),cellHeight:readBinary64(doc,6,DOCUMENT),periodicX:artifactSqliteBoolean(doc,7),periodicY:artifactSqliteBoolean(doc,8),tiles,rules,pinned,masked};
}

import{projectBitmapPixels,reconstructBitmapPixels}from"../../../../../../../../../🪶️sqlite/🎨️bitmap/🟦️.ts";
const BITMAP_TABLES={bitmap:"wfc_grid2d_bitmap",pixel:"wfc_grid2d_bitmap_pixel",literal:"wfc_grid2d_bitmap_literal_scalar"};
