//! 🧪️ Original terminal authority and ledger close separately with unchanged bounded policy.
use super::*;
#[repr(transparent)]
struct TerminalJob<const N:usize>([u8;N]);

struct TerminalSourceInitializer<const N:usize>{written:usize}
unsafe impl<const N:usize> WorkerJobInitializer<TerminalJob<N>> for TerminalSourceInitializer<N>{
 fn initialization_demand(&self,maximum_copy_bytes:usize)->Result<RetirementDemand,ValueError>{let cursor=0;let bytes=(N-self.written).min(maximum_copy_bytes.saturating_sub(cursor));Ok(RetirementDemand{copy_bytes:bytes+cursor,depth:1,..Default::default()})}
 unsafe fn initialize_step(&mut self,target:*mut MaybeUninit<TerminalJob<N>>,grant:RetainedCloneGrant)->Result<WorkerJobInitializationStep,ValueError>{let cursor=0;let bytes=(N-self.written).min(grant.maximum_copy_bytes.saturating_sub(cursor));if bytes==0&&self.written<N{return Ok(WorkerJobInitializationStep{progress:Default::default(),complete:false})}unsafe{std::ptr::write_bytes(target.cast::<u8>().add(self.written),7,bytes);}self.written+=bytes;Ok(WorkerJobInitializationStep{progress:RetainedCloneProgress{copied_items:1,copied_bytes:bytes+cursor,..Default::default()},complete:self.written==N})}
 fn initialization_input_is_empty(&self)->bool{true}
 fn partial_retirement_demands(&self,_:usize)->Result<RetirementDemand,ValueError>{Ok(Default::default())}
 unsafe fn close_partial_step(&mut self,_:*mut MaybeUninit<TerminalJob<N>>,_:RetainedCloneGrant)->Result<RetainedCloneStep,ValueError>{Ok(RetainedCloneStep::Complete(Default::default()))}
 fn partial_terminal_is_empty(&self)->bool{true}

}
fn original_admission_turn<T>(params:&BatchJobParams,owner:impl FnOnce(&mut WorkerJobAdmissionContext<'_>)->T)->(T,RetainedCloneProgress){let entry=(params.now_us)().expect("original source clock must exist");let deadline=entry.checked_add(params.config.step_budget_us).expect("original deadline extent");let mut recipient=RetainedCloneProgress::default();let mut control=WorkerJobAdmissionContext::new(params.operation,params.generation,StepBudget::new(params.config.fuel_per_step,deadline,params.config.retained),params.now_us,&mut recipient).unwrap();let value=owner(&mut control);drop(control);assert!(recipient.fits(params.config.retained));(value,recipient)}
fn prepare_terminal_session<const N:usize>(params:BatchJobParams)->WorkerJobSession<TerminalJob<N>>{
 let identity=(params.operation,params.generation);let grant=params.config.retained;let clock=params.now_us;let fuel=params.config.fuel_per_step;let duration=params.config.step_budget_us;
 let mut storage=MaybeUninit::<WorkerJobSource<TerminalJob<N>>>::uninit();let mut recipient=RetainedCloneProgress::default();let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(fuel,clock().unwrap().checked_add(duration).unwrap(),grant),clock,&mut recipient).unwrap();let source=WorkerJobSource::start_preparation(&mut storage,&mut control).unwrap().unwrap().0;drop(control);assert!(recipient.fits(grant));let mut initializer=TerminalSourceInitializer::<N>{written:0};let mut turns=0;
 loop{let(step,_)=original_admission_turn(&params,|cx|source.prepare_step(&mut initializer,cx).unwrap());turns+=1;assert!(turns<64);if step.complete{break}}
 assert_eq!(source.source().unwrap().0,[7;N]);let pointer=source.source().unwrap()as*const _;let mut parameters=Some(params);let mut recipient=RetainedCloneProgress::default();let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(fuel,clock().unwrap().checked_add(duration).unwrap(),grant),clock,&mut recipient).unwrap();let(mut admission,progress)=WorkerJobAdmission::try_begin(source,&mut parameters,&mut control).unwrap().unwrap();drop(control);assert_eq!(recipient,progress);assert!(recipient.fits(grant));assert_eq!(admission.source()as*const _,pointer);
 let session=loop{let mut recipient=RetainedCloneProgress::default();let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(fuel,clock().unwrap().checked_add(duration).unwrap(),grant),clock,&mut recipient).unwrap();let(session,step)=admission.advance(&mut control).unwrap();drop(control);assert_eq!(recipient,step);assert!(step.fits(grant));turns+=1;assert!(turns<64);if let Some(session)=session{break session}assert_eq!(admission.source()as*const _,pointer);};drop(admission);assert!(parameters.is_none());assert!(source.source().is_none());session
}
impl<const N:usize> InteractiveJob for TerminalJob<N>{
 fn step<'a>(&'a mut self,cx:&mut StepContext<'_>)->Result<Option<JobOutcomeBorrow<'a>>,ValueError>{JobOutcomeBorrow::admit_yield(cx)}fn borrow_outcome<'a>(&'a self,descriptor:&'a JobOutcomeDescriptor)->Result<JobOutcomeView<'a>,ValueError>{match descriptor.kind(){JobOutcomeKind::Yield=>descriptor.yielded(),JobOutcomeKind::Cancelled=>descriptor.cancelled(),_=>Err(ValueError::literal(ValueRefusalKind::InvariantViolated,"fixture requires original yielded descriptor"))}}
 fn begin_close(&mut self){}
 fn close_step(&mut self,_:RetainedCloneGrant)->InteractiveJobCloseStep{InteractiveJobCloseStep::Complete{progress:Default::default()}}
 fn terminal_is_empty(&self)->bool{true}
}
fn observe<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
fn authority_law<const N:usize>(){
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let p=&fixture["policy"];
 let grant=RetainedCloneGrant{maximum_items:p["items"].as_u64().unwrap()as usize,maximum_copy_bytes:p["copy"].as_u64().unwrap()as usize,maximum_capacity_bytes:p["capacity"].as_u64().unwrap()as usize,maximum_release_bytes:p["release"].as_u64().unwrap()as usize,maximum_depth:p["depth"].as_u64().unwrap()as usize};
 let cancel=root_cancel_token();let params=BatchJobParams{operation:OperationId(98120),generation:Generation(12),cancel:cancel.clone(),config:BatchDriveConfig{retained:grant,site:"test.original-authority",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};
 let(mut authority,setup)=observe(||admit_original_fixture_owner!(WorkerJobAuthorityOwner,TerminalJob([7u8;N]),params).unwrap_or_else(|_|panic!("original authority admission")));let pointer=authority.0.as_ptr();let original_capacity=authority.0.capacity();let ledger_pointer=Arc::as_ptr(authority.payload_ledger.as_ref().unwrap());let mut physical=0;
 while !authority.preadmitted_fault.is_empty(){let(step,heap)=observe(||authority.preadmitted_fault.close_step(grant).unwrap());assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);physical+=heap.1;}
 let(_,heap)=observe(||{authority.job.remove_terminal(grant).unwrap();drop(authority.params.take());});assert_eq!(heap,(0,0));
 for phase in 0..2{
  let(demand,heap)=observe(||authority.terminal_authority_demands().unwrap());assert_eq!(heap,(0,0));assert!(demand.copy_bytes<=grant.maximum_copy_bytes);assert_eq!(authority.0.as_ptr(),pointer);assert_eq!(authority.0.capacity(),original_capacity);
  if phase==0{assert_eq!(Arc::as_ptr(authority.payload_ledger.as_ref().unwrap()),ledger_pointer);assert_eq!(demand.release_bytes,fixture["ledgerBytes"].as_u64().unwrap()as usize);}else{assert!(authority.payload_ledger.is_none());assert_eq!(demand.copy_bytes,fixture["bodyWords"].as_u64().unwrap()as usize*size_of::<usize>());assert_eq!(demand.release_bytes,original_capacity*size_of::<WorkerJobAuthority<TerminalJob<N>>>());}
  for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes.saturating_sub(1),..grant},RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..grant},RetainedCloneGrant{maximum_depth:demand.depth-1,..grant}].into_iter().filter(|denied|denied.maximum_items==0||denied.maximum_copy_bytes<demand.copy_bytes||denied.maximum_release_bytes<demand.release_bytes||denied.maximum_depth<demand.depth){let(step,heap)=observe(||authority.close_terminal_worker_authority(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);assert_eq!(authority.0.capacity(),original_capacity);}
  let(step,heap)=observe(||authority.close_terminal_worker_authority(grant));let progress=step.progress();assert!(progress.fits(grant));assert_eq!((progress.retained_capacity_bytes,progress.released_bytes),heap);assert_eq!(progress.released_bytes,demand.release_bytes);physical+=heap.1;
  if phase==0{assert!(matches!(step,WorkerJobCloseStep::Pending{..}));assert_eq!(authority.0.as_ptr(),pointer);}else{assert!(matches!(step,WorkerJobCloseStep::Complete{..}));assert!(authority.0.is_empty());assert_eq!(authority.0.capacity(),0);}
 }
 assert_eq!(physical,setup.0-setup.1);let(_,heap)=observe(||drop(authority));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker authority jobinline={N} samepointer preserved ledger128 separate backing physical={physical} copyheader={} body4096 terminalDrop0; semantic job/params transfer excluded",size_of::<Vec<WorkerJobAuthority<TerminalJob<N>>>>());
}
#[test]
fn worker_terminal_authority_retirement_preserves_original_ledger_then_in_place_backing(){authority_law::<0>();authority_law::<8192>();}

fn job_slot_law<const N:usize>(){
 let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};let mut slot=WorkerJobSource::from_job(TerminalJob([7u8;N]),OperationId(99110),Generation(12));let pointer=slot.original().unwrap()as*const TerminalJob<N>;
 let(demand,heap)=observe(||slot.terminal_removal_demands());assert_eq!(heap,(0,0));assert_eq!(demand.copy_bytes,0);
 for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(step,heap)=observe(||slot.remove_terminal(denied).unwrap());assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(slot.original().unwrap()as*const TerminalJob<N>,pointer);assert_eq!(slot.original().unwrap().0,[7u8;N]);}
 let(step,heap)=observe(||slot.remove_terminal(grant).unwrap());assert_eq!(heap,(0,0));assert!(matches!(step,RetainedCloneStep::Complete(_)));assert_eq!(step.progress().copied_bytes,0);assert!(slot.is_empty());let(_,heap)=observe(||drop(slot));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker jobinline={N} pointer stable zero/below/depth and in-place presence1 body4096 terminalDrop0 no semantic carrier transfer");
}
#[test]
fn worker_terminal_job_retirement_keeps_original_inline_job_for_in_place_removal(){job_slot_law::<0>();job_slot_law::<8192>();}

#[test]
fn worker_terminal_params_retirement_preserves_original_cancellation_and_separate_cursor(){
 let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};
 for ancestors in [1,3,64]{let(mut authority,birth)=observe(||{let mut cancel=CancelToken::root_now();for _ in 1..ancestors{cancel=cancel.child_now();}let params=BatchJobParams{operation:OperationId(99120),generation:Generation(12),cancel,config:BatchDriveConfig{retained:grant,site:"test.original-params",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};admit_original_fixture_owner!(WorkerJobAuthorityOwner,TerminalJob([]),params).unwrap_or_else(|_|panic!("original params authority"))});let pointer=authority.0.as_ptr();let mut released=0;
 while !authority.preadmitted_fault.is_empty(){let(step,heap)=observe(||authority.preadmitted_fault.close_step(grant).unwrap());assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;}authority.job.remove_terminal(grant).unwrap();
 let mut turns=0;while authority.params.is_some()||authority.cancel_retirement.is_some(){turns+=1;assert!(turns<512);let(demand,heap)=observe(||authority.original_params_demands().unwrap());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);for denied in [Some(RetainedCloneGrant{maximum_items:0,..grant}),(demand.copy_bytes>0).then_some(RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes.saturating_sub(1),..grant}),(demand.release_bytes>0).then_some(RetainedCloneGrant{maximum_release_bytes:demand.release_bytes.saturating_sub(1),..grant}),Some(RetainedCloneGrant{maximum_depth:0,..grant})].into_iter().flatten(){let(step,heap)=observe(||authority.close_original_worker_params(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);}
 let(step,heap)=observe(||authority.close_original_worker_params(grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert_eq!(authority.0.as_ptr(),pointer);}
 assert_eq!(turns,ancestors*2+2);for _ in 0..2{let(step,heap)=observe(||authority.close_terminal_worker_authority(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;}assert_eq!(released,birth.0-birth.1);let(_,heap)=observe(||drop(authority));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual Worker params ancestors={ancestors} original authority pointer stable on all denied/full turns params transfer then cancellation separate terminal cursor removal physical={released} originalbirth={} terminalDrop0 fixedbody4096",birth.0-birth.1);
 }
}

#[test]
fn worker_terminal_session_retirement_preserves_original_arc_aliases_and_funded_scaffolds(){
 let(_,shared_trace)=observe(||record_operation_started(OperationId(99219),Generation(12)));eprintln!("[DEBUG] explicit process-shared Trace ring startup born={} released={} precedes original Worker-owned construction and remains process-owned",shared_trace.0,shared_trace.1);
 let _admission=worker_session_slots_shared();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};
 for aliases in [0,1,3]{let(mut session,birth)=observe(||{let params=BatchJobParams{operation:OperationId(99220),generation:Generation(12),cancel:CancelToken::root_now(),config:BatchDriveConfig{retained:grant,site:"test.original-session",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};prepare_terminal_session::<8192>(params)});let pointer=Arc::as_ptr(&session.inner);let mut original_aliases:[Option<Arc<WorkerJobSessionInner<TerminalJob<8192>>>>;3]=std::array::from_fn(|index|(index<aliases).then(||Arc::clone(&session.inner)));session.begin_close();let mut released=0;let mut turns=0;
 while session.close_phase()!=WorkerJobClosePhase::SessionArc{turns+=1;assert!(turns<512);let(step,heap)=observe(||session.close_step(grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert_eq!(Arc::as_ptr(&session.inner),pointer);}
 let(demand,heap)=observe(||session.retirement_demands(grant.maximum_copy_bytes).unwrap());assert_eq!(heap,(0,0));assert_eq!(demand,session.original_session_arc_demands(grant.maximum_copy_bytes).unwrap());assert!(demand.copy_bytes<=4096);
 for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes.saturating_sub(1),..grant},RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..grant},RetainedCloneGrant{maximum_depth:0,..grant}].into_iter().filter(|denied|denied.maximum_items==0||denied.maximum_copy_bytes<demand.copy_bytes||denied.maximum_release_bytes<demand.release_bytes||denied.maximum_depth<demand.depth){let(step,heap)=observe(||session.close_step(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(Arc::as_ptr(&session.inner),pointer);assert!(!session.terminal_is_empty());}
 if aliases>0{let(step,heap)=observe(||session.close_step(grant));assert_eq!(step,WorkerJobCloseStep::Blocked);assert_eq!(heap,(0,0));assert_eq!(Arc::as_ptr(&session.inner),pointer);let(_,heap)=observe(||for original in &mut original_aliases{drop(original.take());});assert_eq!(heap,(0,0));}
 let(step,heap)=observe(||session.close_step(grant));assert!(matches!(step,WorkerJobCloseStep::Pending{..}));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);assert_eq!(heap,(0,demand.release_bytes));released+=heap.1;assert!(session.inner.0.is_none());assert_eq!(session.generation(),Generation(12));assert_eq!(session.close_phase(),WorkerJobClosePhase::RetirementSlot);assert!(!session.terminal_is_empty());
 let(demand,heap)=observe(||session.retirement_demands(grant.maximum_copy_bytes).unwrap());assert_eq!(heap,(0,0));assert_eq!(demand.release_bytes,size_of::<WorkerJobRetirementNode<TerminalJob<8192>>>());let(step,heap)=observe(||session.close_step(grant));assert!(matches!(step,WorkerJobCloseStep::Complete{..}));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert!(session.terminal_is_empty());assert_eq!(released,birth.0-birth.1);let(_,heap)=observe(||drop(session));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker session aliases={aliases} originalArc pointer retained all zero/below/full4096 original8192job authority then Arc{} and retirementnode{} separately paid totalphysical={released} terminalDrop0 semantic job/outcome handoffs excluded",semio_framework_value::retirement::shared::shared_retirement_allocation_bytes::<WorkerJobSessionInner<TerminalJob<8192>>>(),size_of::<WorkerJobRetirementNode<TerminalJob<8192>>>());
 }
}

struct RefusingSourceInitializer{written:bool}
unsafe impl WorkerJobInitializer<u8> for RefusingSourceInitializer{
 fn initialization_demand(&self,_:usize)->Result<RetirementDemand,ValueError>{Ok(RetirementDemand{copy_bytes:size_of::<u8>(),depth:1,..Default::default()})}
 unsafe fn initialize_step(&mut self,target:*mut MaybeUninit<u8>,_:RetainedCloneGrant)->Result<WorkerJobInitializationStep,ValueError>{unsafe{target.write(MaybeUninit::new(71));}self.written=true;Err(ValueError::literal(ValueRefusalKind::InvariantViolated,"original source writer refused after actual initialized byte and cursor").with_retained_progress(RetainedCloneProgress{copied_items:1,copied_bytes:size_of::<u8>(),..Default::default()}))}
 fn initialization_input_is_empty(&self)->bool{true}
 fn partial_retirement_demands(&self,_:usize)->Result<RetirementDemand,ValueError>{Ok(Default::default())}
 unsafe fn close_partial_step(&mut self,_:*mut MaybeUninit<u8>,_:RetainedCloneGrant)->Result<RetainedCloneStep,ValueError>{Ok(RetainedCloneStep::Complete(Default::default()))}
 fn partial_terminal_is_empty(&self)->bool{true}

}
#[test]
fn original_source_preparation_keeps_failed_effects_in_same_incoming_recipient(){
 fn now()->Option<u64>{Some(1)}
 let law:serde_json::Value=serde_json::from_str(include_str!("../../../👷️worker/🚪️admission/🚚️staged/🧫️fixtures/🔣️.json")).unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};let identity=(OperationId(99912),Generation(3));let mut storage=MaybeUninit::<WorkerJobSource<u8>>::uninit();let mut header=Default::default();let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut header).unwrap();let(source,birth)=WorkerJobSource::start_preparation(&mut storage,&mut control).unwrap().unwrap();drop(control);assert_eq!(birth,header);assert_eq!(birth.copied_bytes,law["sourceHeader"]["copiedBytes"].as_u64().unwrap()as usize);let mut writer=RefusingSourceInitializer{written:false};let mut recipient=Default::default();
 let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,RetainedCloneGrant{maximum_copy_bytes:0,..grant}),now,&mut recipient).unwrap();let(step,heap)=observe(||source.prepare_step(&mut writer,&mut control).unwrap());drop(control);assert_eq!(heap,(0,0));assert_eq!(step.progress,Default::default());assert_eq!(recipient,Default::default());assert!(!writer.written);assert!(source.source().is_none());
 let mut control=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut recipient).unwrap();let(error,heap)=observe(||source.prepare_step(&mut writer,&mut control).err().unwrap());drop(control);assert_eq!(heap,(0,0));assert!(writer.written);assert!(source.source().is_none());assert_eq!(unsafe{source.original.assume_init()},71);assert_eq!(error.retained_progress(),RetainedCloneProgress{copied_items:1,copied_bytes:1,..Default::default()});assert_eq!(recipient,error.retained_progress());assert!(recipient.fits(grant));eprintln!("[DEBUG] actual source header binding copies0, denied writer0, post-write refusal payload1 paid to same original recipient, presence retainedfalse heap0");
}

#[test]
fn original_destination_initialization_preserves_paid_page_custody_at_every_abandonment(){
 fn now()->Option<u64>{Some(1)}
 let _lease=worker_session_slots_exclusive();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};let mut initial_turns=0;while worker_job_retirements_are_parked(){let(step,heap)=observe(||pump_worker_job_retirements(1,grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);initial_turns+=1;assert!(initial_turns<8192);}
 let law:serde_json::Value=serde_json::from_str(include_str!("../../../👷️worker/🚪️admission/🚚️staged/📦️destination/🧫️fixtures/🔣️.json")).unwrap();let actual=law["layouts"].as_array().unwrap().iter().find(|row|row["pointerBytes"].as_u64().unwrap()as usize==size_of::<usize>()).unwrap();assert_eq!(size_of::<Option<JobPayloadPage>>(),actual["slotBytes"].as_u64().unwrap()as usize);
 for cut in 0..=3{
  let identity=(OperationId(99931),Generation(4));let mut storage=MaybeUninit::<WorkerJobSource<TerminalJob<0>>>::uninit();let mut recipient=Default::default();let mut cx=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut recipient).unwrap();let(source,_)=WorkerJobSource::start_preparation(&mut storage,&mut cx).unwrap().unwrap();drop(cx);let mut initializer=TerminalSourceInitializer::<0>{written:0};let mut receipt=Default::default();let mut cx=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut receipt).unwrap();assert!(source.prepare_step(&mut initializer,&mut cx).unwrap().complete);drop(cx);let pointer=source.source().unwrap()as*const _;let mut params=Some(BatchJobParams{operation:identity.0,generation:identity.1,cancel:CancelToken::root_now(),config:BatchDriveConfig{site:"test.original-destination",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1,retained:grant},now_us:now});let mut recipient=Default::default();let mut cx=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut recipient).unwrap();let((mut admission,birth),heap)=observe(||WorkerJobAdmission::try_begin(source,&mut params,&mut cx).unwrap().unwrap());drop(cx);assert_eq!(birth,recipient);assert_eq!((birth.retained_capacity_bytes,birth.released_bytes),heap);let page=admission.destination_page_identity().unwrap();let born=heap.0;let mut paid=Vec::new();
  for _ in 0..cut{if admission.destination_is_initialized(){break}let demand=admission.destination_initialization_demands().unwrap();assert!(demand.copy_bytes<=4096);for denied in[RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let mut recipient=Default::default();let mut cx=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,denied),now,&mut recipient).unwrap();let(step,heap)=observe(||admission.advance_destination_initialization(&mut cx).unwrap());drop(cx);assert_eq!(step,Default::default());assert_eq!(recipient,Default::default());assert_eq!(heap,(0,0));assert_eq!(admission.destination_page_identity(),Some(page));assert_eq!(admission.source()as*const _,pointer);}
   let mut recipient=Default::default();let mut cx=WorkerJobAdmissionContext::new(identity.0,identity.1,StepBudget::new(1,2,grant),now,&mut recipient).unwrap();let(step,heap)=observe(||admission.advance_destination_initialization(&mut cx).unwrap());drop(cx);assert_eq!(step,recipient);assert!(step.fits(grant));assert_eq!(heap,(0,0));assert_eq!(admission.destination_page_identity(),Some(page));assert_eq!(admission.source()as*const _,pointer);paid.push(step.copied_bytes);
  }
  let(_,heap)=observe(||drop(admission));assert_eq!(heap,(0,0));assert!(params.is_some());assert_eq!(source.source().unwrap()as*const _,pointer);let mut released=0;let mut turns=0;while worker_job_retirements_are_parked(){let(step,heap)=observe(||pump_worker_job_retirements(1,grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;turns+=1;assert!(turns<64);}assert_eq!(released,born);source.remove_terminal(grant).unwrap();assert!(source.source().is_none());eprintln!("[DEBUG] original destination cut={cut} same prepaid page={page:p} source pointer unchanged initializedCopies={paid:?} exact born/free={born}/{released} abandoned Drop0 original4096");
 }
}
