//! 🧪️ Original terminal authority and ledger close separately with unchanged bounded policy.
use super::*;
struct TerminalJob<const N:usize>([u8;N]);
impl<const N:usize> InteractiveJob for TerminalJob<N>{
 fn step(&mut self,_:&mut StepContext<'_>)->StepOutcome{StepOutcome::Yield}
 fn begin_close(&mut self){}
 fn close_step(&mut self,_:RetainedCloneGrant)->InteractiveJobCloseStep{InteractiveJobCloseStep::Complete{progress:Default::default()}}
 fn terminal_is_empty(&self)->bool{true}
}
fn observe<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
fn authority_law<const N:usize>(){
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let p=&fixture["policy"];
 let grant=RetainedCloneGrant{maximum_items:p["items"].as_u64().unwrap()as usize,maximum_copy_bytes:p["copy"].as_u64().unwrap()as usize,maximum_capacity_bytes:p["capacity"].as_u64().unwrap()as usize,maximum_release_bytes:p["release"].as_u64().unwrap()as usize,maximum_depth:p["depth"].as_u64().unwrap()as usize};
 let cancel=root_cancel_token();let params=BatchJobParams{operation:OperationId(98120),generation:Generation(12),cancel:cancel.clone(),config:BatchDriveConfig{retained:grant,site:"test.original-authority",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};
 let(mut authority,setup)=observe(||WorkerJobAuthorityOwner::try_new(TerminalJob([7u8;N]),params).unwrap_or_else(|_|panic!("original authority admission")));let pointer=authority.0.as_ptr();let original_capacity=authority.0.capacity();let ledger_pointer=Arc::as_ptr(authority.payload_ledger.as_ref().unwrap());let mut physical=0;
 while !authority.preadmitted_fault.is_empty(){let(step,heap)=observe(||authority.preadmitted_fault.close_step(grant).unwrap());assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);physical+=heap.1;}
 let(_,heap)=observe(||{authority.job.remove_terminal(grant).unwrap();drop(authority.params.take());});assert_eq!(heap,(0,0));
 for phase in 0..2{
  let(demand,heap)=observe(||authority.terminal_authority_demands().unwrap());assert_eq!(heap,(0,0));assert!(demand.copy_bytes<=grant.maximum_copy_bytes);assert_eq!(authority.0.as_ptr(),pointer);assert_eq!(authority.0.capacity(),original_capacity);
  if phase==0{assert_eq!(Arc::as_ptr(authority.payload_ledger.as_ref().unwrap()),ledger_pointer);assert_eq!(demand.release_bytes,fixture["ledgerBytes"].as_u64().unwrap()as usize);}else{assert!(authority.payload_ledger.is_none());assert_eq!(demand.copy_bytes,fixture["bodyWords"].as_u64().unwrap()as usize*size_of::<usize>());assert_eq!(demand.release_bytes,original_capacity*size_of::<WorkerJobAuthority<TerminalJob<N>>>());}
  for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant},RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..grant},RetainedCloneGrant{maximum_depth:demand.depth-1,..grant}]{let(step,heap)=observe(||authority.close_terminal_worker_authority(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);assert_eq!(authority.0.capacity(),original_capacity);}
  let(step,heap)=observe(||authority.close_terminal_worker_authority(grant));let progress=step.progress();assert!(progress.fits(grant));assert_eq!((progress.retained_capacity_bytes,progress.released_bytes),heap);assert_eq!(progress.released_bytes,demand.release_bytes);physical+=heap.1;
  if phase==0{assert!(matches!(step,WorkerJobCloseStep::Pending{..}));assert_eq!(authority.0.as_ptr(),pointer);}else{assert!(matches!(step,WorkerJobCloseStep::Complete{..}));assert!(authority.0.is_empty());assert_eq!(authority.0.capacity(),0);}
 }
 assert_eq!(physical,setup.0-setup.1);let(_,heap)=observe(||drop(authority));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker authority jobinline={N} samepointer preserved ledger128 separate backing physical={physical} copyheader={} body4096 terminalDrop0; semantic job/params transfer excluded",size_of::<Vec<WorkerJobAuthority<TerminalJob<N>>>>());
}
#[test]
fn worker_terminal_authority_retirement_preserves_original_ledger_then_in_place_backing(){authority_law::<0>();authority_law::<8192>();}

fn job_slot_law<const N:usize>(){
 let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};let mut slot=WorkerJobSlot::from_job(TerminalJob([7u8;N]));let pointer=slot.original().unwrap()as*const TerminalJob<N>;
 let(demand,heap)=observe(||slot.terminal_removal_demands());assert_eq!(heap,(0,0));assert_eq!(demand.copy_bytes,1);
 for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:0,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(step,heap)=observe(||slot.remove_terminal(denied).unwrap());assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(slot.original().unwrap()as*const TerminalJob<N>,pointer);assert_eq!(slot.original().unwrap().0,[7u8;N]);}
 let(step,heap)=observe(||slot.remove_terminal(grant).unwrap());assert_eq!(heap,(0,0));assert!(matches!(step,RetainedCloneStep::Complete(_)));assert_eq!(step.progress().copied_bytes,1);assert!(slot.is_empty());let(_,heap)=observe(||drop(slot));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker jobinline={N} pointer stable zero/below/depth and in-place presence1 body4096 terminalDrop0 no semantic carrier transfer");
}
#[test]
fn worker_terminal_job_retirement_keeps_original_inline_job_for_in_place_removal(){job_slot_law::<0>();job_slot_law::<8192>();}

#[test]
fn worker_terminal_params_retirement_preserves_original_cancellation_and_separate_cursor(){
 let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};
 for ancestors in [1,3,64]{let(mut authority,birth)=observe(||{let mut cancel=CancelToken::root_now();for _ in 1..ancestors{cancel=cancel.child_now();}let params=BatchJobParams{operation:OperationId(99120),generation:Generation(12),cancel,config:BatchDriveConfig{retained:grant,site:"test.original-params",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};WorkerJobAuthorityOwner::try_new(TerminalJob([]),params).unwrap_or_else(|_|panic!("original params authority"))});let pointer=authority.0.as_ptr();let mut released=0;
 while !authority.preadmitted_fault.is_empty(){let(step,heap)=observe(||authority.preadmitted_fault.close_step(grant).unwrap());assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;}authority.job.remove_terminal(grant).unwrap();
 let mut turns=0;while authority.params.is_some()||authority.cancel_retirement.is_some(){turns+=1;assert!(turns<512);let(demand,heap)=observe(||authority.original_params_demands().unwrap());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);for denied in [Some(RetainedCloneGrant{maximum_items:0,..grant}),Some(RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant}),(demand.release_bytes>0).then_some(RetainedCloneGrant{maximum_release_bytes:demand.release_bytes.saturating_sub(1),..grant}),Some(RetainedCloneGrant{maximum_depth:0,..grant})].into_iter().flatten(){let(step,heap)=observe(||authority.close_original_worker_params(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(authority.0.as_ptr(),pointer);}
 let(step,heap)=observe(||authority.close_original_worker_params(grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert_eq!(authority.0.as_ptr(),pointer);}
 assert_eq!(turns,ancestors*2+2);for _ in 0..2{let(step,heap)=observe(||authority.close_terminal_worker_authority(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;}assert_eq!(released,birth.0-birth.1);let(_,heap)=observe(||drop(authority));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual Worker params ancestors={ancestors} original authority pointer stable on all denied/full turns params transfer then cancellation separate terminal cursor removal physical={released} originalbirth={} terminalDrop0 fixedbody4096",birth.0-birth.1);
 }
}

#[test]
fn worker_terminal_session_retirement_preserves_original_arc_aliases_and_funded_scaffolds(){
 let(_,shared_trace)=observe(||record_operation_started(OperationId(99219),Generation(12)));eprintln!("[DEBUG] explicit process-shared Trace ring startup born={} released={} precedes original Worker-owned construction and remains process-owned",shared_trace.0,shared_trace.1);
 let _admission=worker_session_slots_shared();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_capacity_bytes:65536,maximum_release_bytes:262144,maximum_depth:64};
 for aliases in [0,1,3]{let(mut session,birth)=observe(||{let params=BatchJobParams{operation:OperationId(99220),generation:Generation(12),cancel:CancelToken::root_now(),config:BatchDriveConfig{retained:grant,site:"test.original-session",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000},now_us:default_now_us};WorkerJobSession::try_new(TerminalJob([7u8;8192]),params).unwrap_or_else(|_|panic!("original session admission"))});let pointer=Arc::as_ptr(&session.inner);let mut original_aliases:[Option<Arc<WorkerJobSessionInner<TerminalJob<8192>>>>;3]=std::array::from_fn(|index|(index<aliases).then(||Arc::clone(&session.inner)));session.begin_close();let mut released=0;let mut turns=0;
 while session.close_phase()!=WorkerJobClosePhase::SessionArc{turns+=1;assert!(turns<512);let(step,heap)=observe(||session.close_step(grant));assert!(step.progress().fits(grant));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert_eq!(Arc::as_ptr(&session.inner),pointer);}
 let(demand,heap)=observe(||session.retirement_demands(grant.maximum_copy_bytes).unwrap());assert_eq!(heap,(0,0));assert_eq!(demand,session.original_session_arc_demands(grant.maximum_copy_bytes).unwrap());assert!(demand.copy_bytes<=4096);
 for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant},RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(step,heap)=observe(||session.close_step(denied));assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));assert_eq!(Arc::as_ptr(&session.inner),pointer);assert!(!session.terminal_is_empty());}
 if aliases>0{let(step,heap)=observe(||session.close_step(grant));assert_eq!(step,WorkerJobCloseStep::Blocked);assert_eq!(heap,(0,0));assert_eq!(Arc::as_ptr(&session.inner),pointer);let(_,heap)=observe(||for original in &mut original_aliases{drop(original.take());});assert_eq!(heap,(0,0));}
 let(step,heap)=observe(||session.close_step(grant));assert!(matches!(step,WorkerJobCloseStep::Pending{..}));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);assert_eq!(heap,(0,demand.release_bytes));released+=heap.1;assert!(session.inner.0.is_none());assert_eq!(session.generation(),Generation(12));assert_eq!(session.close_phase(),WorkerJobClosePhase::RetirementSlot);assert!(!session.terminal_is_empty());
 let(demand,heap)=observe(||session.retirement_demands(grant.maximum_copy_bytes).unwrap());assert_eq!(heap,(0,0));assert_eq!(demand.release_bytes,size_of::<WorkerJobRetirementNode<TerminalJob<8192>>>());let(step,heap)=observe(||session.close_step(grant));assert!(matches!(step,WorkerJobCloseStep::Complete{..}));assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),heap);released+=heap.1;assert!(session.terminal_is_empty());assert_eq!(released,birth.0-birth.1);let(_,heap)=observe(||drop(session));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker session aliases={aliases} originalArc pointer retained all zero/below/full4096 original8192job authority then Arc{} and retirementnode{} separately paid totalphysical={released} terminalDrop0 semantic job/outcome handoffs excluded",semio_framework_value::retirement::shared::shared_retirement_allocation_bytes::<WorkerJobSessionInner<TerminalJob<8192>>>(),size_of::<WorkerJobRetirementNode<TerminalJob<8192>>>());
 }
}
