use super::*;
use crate::codec::{RetainedWireByteSource,OriginalWireSourceIdentity};
fn observe<T>(action:impl FnOnce()->T)->(T,usize,usize){crate::test_allocation::observe_backing(action)}
struct Pages{pages:Vec<Vec<u8>>,extent:usize}
struct Borrowed<'a>{owner:&'a Pages,authority:Option<(u64,u64)>}
impl RetainedWireByteSource for Borrowed<'_>{
 fn original_source_identity(&self)->OriginalWireSourceIdentity{OriginalWireSourceIdentity{address:self.owner as*const Pages as usize,extent:self.owner.extent,authority:self.authority}}
 fn byte_at(&self,index:usize)->Option<u8>{let mut remaining=index;for page in &self.owner.pages{if remaining<page.len(){return page.get(remaining).copied()}remaining-=page.len()}None}
}
#[test]
fn original_paged_dictionary_native_keeps_exact_authority_and_metadata0_receipts(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let p=&law["grant"];let n=|key:&str|p[key].as_u64().unwrap()as usize;let g=RetainedCloneGrant{maximum_items:n("items"),maximum_copy_bytes:n("copy"),maximum_capacity_bytes:n("capacity"),maximum_release_bytes:n("release"),maximum_depth:n("depth")};let pages:Vec<Vec<u8>>=law["pages"].as_array().unwrap().iter().map(|row|row.as_array().unwrap().iter().map(|b|b.as_u64().unwrap()as u8).collect()).collect();let extent=pages.iter().map(Vec::len).sum();let original=pages;let authority=Some((9,3));for inline in[false,true]{let pages=if inline{let bytes:Vec<u8>=original.iter().flatten().copied().collect();let mut body=vec![1,8];body.extend_from_slice(&bytes[4..]);body.extend_from_slice(&[0]);body.chunks(2).map(|p|p.to_vec()).collect()}else{original.clone()};let extent=pages.iter().map(Vec::len).sum();let owner=Pages{pages,extent};
 for cancel_at in[0,1,2,3,8,128]{let source=Borrowed{owner:&owner,authority};let(mut dictionary,b,r)=observe(||RetainedSourceDictionary::new(&source));assert_eq!((b,r),(0,0));let changed=Borrowed{owner:&owner,authority:Some((9,4))};let(result,b,r)=observe(||dictionary.begin_record(&changed,0,extent,g));assert!(result.is_err());assert_eq!((b,r),(0,0));assert!(dictionary.receipt().is_none());let(_,b,r)=observe(||if inline{dictionary.begin_inline_catalog(&source,0,g).unwrap()}else{dictionary.begin_record(&source,0,extent,g).unwrap()});assert_eq!((b,r),(0,0));assert_eq!(dictionary.take_receipt().unwrap().1.copied_bytes,0);let(mut born,mut released)=(0,0);
  for _ in 0..cancel_at{if dictionary.is_ready(){break}let source=Borrowed{owner:&owner,authority};let(demand,b,r)=observe(||dictionary.demands(&source).unwrap());assert_eq!((b,r),(0,0));for(axis,denied)in[RetainedCloneGrant{maximum_items:0,..g},RetainedCloneGrant{maximum_depth:demand.depth.saturating_sub(1),..g},RetainedCloneGrant{maximum_capacity_bytes:demand.capacity_bytes.saturating_sub(1),..g}].into_iter().enumerate(){if axis==2&&demand.capacity_bytes==0{continue}let(step,b,r)=observe(||dictionary.advance(&source,denied).unwrap());assert_eq!(step,RetainedSourceDictionaryStep::Blocked);assert_eq!((b,r),(0,0));assert!(dictionary.receipt().is_none())}let(_,b,r)=observe(||dictionary.advance(&source,g).unwrap());let(issued,p)=dictionary.take_receipt().unwrap();assert_eq!(issued,g);assert!(p.fits(g));assert_eq!(p.copied_bytes,0);assert_eq!((b,r),(p.retained_capacity_bytes,p.released_bytes));born+=b;released+=r;}
  if cancel_at==128{assert!(dictionary.is_ready());let((start,end),b,r)=observe(||dictionary.resolve_range(&source,0).unwrap());assert_eq!((b,r),(0,0));assert_eq!((start,end),if inline{(2,extent-1)}else{(4,extent)});assert_eq!(dictionary.position(),end);let text:Vec<u8>=(start..end).map(|i|source.byte_at(i).unwrap()).collect();assert_eq!(text,law["values"][0].as_str().unwrap().as_bytes());}
  dictionary.cancel();for _ in 0..128{if dictionary.terminal_is_empty(){break}let demand=dictionary.demands(&source).unwrap();if demand.release_bytes>0{let(step,b,r)=observe(||dictionary.close_step(&source,RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..g}).unwrap());assert_eq!(step,RetainedSourceDictionaryStep::Blocked);assert_eq!((b,r),(0,0))}let(_,b,r)=observe(||dictionary.close_step(&source,g).unwrap());let(issued,p)=dictionary.take_receipt().unwrap();assert_eq!(issued,g);assert!(p.fits(g));assert_eq!(p.copied_bytes,0);assert_eq!((b,r),(p.retained_capacity_bytes,p.released_bytes));born+=b;released+=r;}assert!(dictionary.terminal_is_empty());assert_eq!(born,released);let(_,b,r)=observe(||drop(dictionary));assert_eq!((b,r),(0,0));
 }}eprintln!("[DEBUG] Fresh per-turn paged dictionary views retain exact original header/opgen, borrowed UTF8/NUL ranges, independently denied axes and actual paged backing receipts through paid cancellation and terminalDrop0");
}
