[package]
name = "semio-s-artifact-stdio-binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Stdio binary artifact"

[package.metadata.semio]
role = "s-module"

[lints]
workspace = true

[lib]
path = "../../🦀️.rs"

[features]
default = []
component-app-assembly = []

[dependencies]
semio-framework = { workspace = true }
semio-framework-dispatch-macros = { workspace = true }
semio-framework-os-kernel = { workspace = true }
semio-framework-plugin = { workspace = true }
semio-framework-schema = { workspace = true }
semio-framework-value-derive = { workspace = true }
semio-s-artifact-stdio-contract = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
semio-framework-async-macros = { workspace = true }
semio-framework-ui-scene = { workspace = true }
