// 🧬️ EN 1997 diff schema.
syntax = "proto3";
package semio.s.norm.en1997.diff;

message En1997Diff {
  // @state artifact
  optional En1997Artifact artifact = 1;
  // @state artifact
  optional double v_ed_kn = 2;
  // @state artifact
  optional double h_ed_kn = 3;
  // @state artifact
  optional double footing_area_m2 = 4;
  // @state artifact
  optional double phi_deg = 5;
  // @state artifact
  optional double c_kpa = 6;
  // @state artifact
  optional double gamma_kn_m3 = 7;
  // @state artifact
  optional double b_m = 8;
  // @state artifact
  optional double d_f_m = 9;
  // @state artifact
  optional double e_s_mpa = 10;
  // @state artifact
  optional double nu = 11;
  // @state artifact
  optional double design_approach = 12;
  // @state artifact
  optional double annex = 13;
  // @state artifact
  optional double settlement_limit_mm = 14;
  // @state artifact
  optional double n_pile_ed_kn = 15;
  // @state artifact
  optional double alpha_s = 16;
  // @state artifact
  optional double pile_d_m = 17;
  // @state artifact
  optional double q_s_kpa = 18;
  // @state artifact
  optional double pile_l_m = 19;
  // @state artifact
  optional double q_b_kpa = 20;
  // @state artifact
  optional double pile_base_area_m2 = 21;
  // @state artifact
  optional uint32 pile_n_profiles = 22;
  // @state artifact
  optional double z_investigated_m = 23;
  // @state presence
  optional uint32 selected_check_index = 24;
}
