/** 📊️ Native table columns and fully typed SemioValue cells are independent domains. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import f from "../🧫️fixtures/🔣️.json";
import type {SemioTableSnapshot} from "../../../../🧬️schema/📸️snapshot/🟦️.ts";
import {SEMIO_TABLE_SQLITE_SCHEMA,semioTableSnapshotToSqliteDatabase,semioTableSnapshotFromSqliteDatabase} from "../🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const input:SemioTableSnapshot={schema:f.schema,columns:[{name:"null",kind:"null"},{name:"boolean",kind:"bool"},{name:"integer",kind:"int"},{name:"floating",kind:"float"},{name:"string",kind:"str"},{name:"binary",kind:"bytes"}],rows:[{cells:[{kind:"null"},{kind:"bool",value:false},{kind:"int",lexeme:f.integerLexeme},{kind:"float",lexeme:f.floatLexeme},{kind:"str",value:f.text},{kind:"bytes",value:[0,1,255]}]},{cells:[{kind:"list",items:[]},{kind:"map",entries:[{key:"same",value:{kind:"null"}},{key:"same",value:{kind:"bool",value:true}}]},{kind:"ref",id:{value:"external/native"}},{kind:"list",items:[{kind:"str",value:"nested"}]},{kind:"null"},{kind:"bool",value:true}]}]};
test("Semio table independently joined full typed cells and edited text",async()=>{expect(SEMIO_TABLE_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());const db=Database.deserialize(await exportSqliteDatabase(await semioTableSnapshotToSqliteDatabase(input)));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(f.query).all()).toHaveLength(12);expect(await semioTableSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_table_value SET string_value='edited' WHERE kind='str' AND string_value=?").run(f.text);const expected=structuredClone(input);expected.rows[0]!.cells[4]={kind:"str",value:"edited"};expect(await semioTableSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(expected);}finally{db.close();}});
test("Semio table cell ownership completeness, contiguous ordinals and bounded reconstruction",async()=>{const d=await semioTableSnapshotToSqliteDatabase(input);for(const mutate of [(x:any)=>x.tables[1].rows[1].values[2]=x.tables[1].rows[0].values[2],(x:any)=>x.tables[3].rows.pop(),(x:any)=>x.tables[3].rows[0].values[2]=999n,(x:any)=>x.tables[3].rows[1].values[3]=x.tables[3].rows[0].values[3]]){const x=structuredClone(d);mutate(x);await expect(semioTableSnapshotFromSqliteDatabase(x)).rejects.toThrow();}await expect(semioTableSnapshotToSqliteDatabase({...input,columns:[{name:"invalid",kind:"unknown"}] as any})).rejects.toThrow();await expect(semioTableSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();await expect(semioTableSnapshotFromSqliteDatabase(d,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();c.abort();await expect(semioTableSnapshotFromSqliteDatabase(d,{signal:c.signal})).rejects.toThrow();const empty={schema:"zero columns",columns:[],rows:[{cells:[]}]};expect(await semioTableSnapshotFromSqliteDatabase(await semioTableSnapshotToSqliteDatabase(empty))).toEqual(empty);});

test("quick::Semio table native construction frontier matches independent cells and exact octets",async()=>{const s:SemioTableSnapshot={schema:f.schema,columns:[{name:"exact",kind:"bytes"}],rows:Array.from({length:f.nativeAdmission.collectionItems},()=>({cells:[{kind:"bytes",value:[0,255]}]}))};const d=Database.deserialize(await exportSqliteDatabase(await semioTableSnapshotToSqliteDatabase(s)));try{expect(d.query("SELECT count(*) AS count FROM semio_table_row").get()).toEqual({count:f.nativeAdmission.collectionItems});expect(d.query("SELECT count(*) AS count FROM semio_table_cell").get()).toEqual({count:f.nativeAdmission.collectionItems});expect(d.query("SELECT hex(bytes_value) AS bytes FROM semio_table_value WHERE kind='bytes' LIMIT 1").get()).toEqual({bytes:"00FF"});}finally{d.close();}},30000);


test("Semio Table code-admitted intermediate owner survives independently queried physical SQLite",async()=>{
 const neutral=await Bun.file(new URL("../🧫️fixtures/🧩️intermediate/🔣️.json",import.meta.url)).json();
 const {default:Ajv}=await import("ajv");expect(neutral["role"]).toEqual("codeAdmittedIntermediateOwner");expect(neutral["snapshot"]).toEqual({"schema":"table\u0000世界","columns":[{"name":"same\u0000Ä","kind":"str"},{"name":"same\u0000Ä","kind":"str"}],"rows":[{"cells":[{"kind":"null"},{"kind":"bool","value":true},{"kind":"int","lexeme":"18446744073709551616"},{"kind":"float","lexeme":"1.234567890123456789"},{"kind":"str","value":"NUL\u0000世界"},{"kind":"bytes","value":[0,255]},{"kind":"list","items":[]},{"kind":"map","entries":[{"key":"same","value":{"kind":"null"}},{"key":"same","value":{"kind":"bool","value":false}}]},{"kind":"ref","id":{"value":"external\u0000Ä"}}]},{"cells":[]}]});expect(neutral["query"]).toEqual("SELECT count(*) AS n FROM semio_table_cell");expect(neutral["expectedRows"]).toEqual([{"n":9}]);
 const input=structuredClone(neutral.snapshot);
 const db=Database.deserialize(await exportSqliteDatabase(await semioTableSnapshotToSqliteDatabase(input)));
 try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(neutral.query).all()).toEqual(neutral.expectedRows);expect(await semioTableSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_table_value SET string_value=? WHERE kind='str'").run("independently edited");input.rows[0].cells[4]={kind:"str",value:"independently edited"};expect(await semioTableSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);console.log("[DEBUG] Semio table retains duplicate declaration names, arbitrary row widths and all nine independently queried native cell variants");}finally{db.close();}
});

import completeSemanticContract from "../🧫️fixtures/🎛️semantic.json";
import{independentSqliteExtent as completeIndependentExtent} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts";
test("Semio Table Native matched full and metadata empty independently preserve all complete cells",async()=>{
 for(const item of completeSemanticContract.cases){const source=structuredClone(item.sourceSnapshot)as SemioTableSnapshot;const database=await semioTableSnapshotToSqliteDatabase(source),bytes=await exportSqliteDatabase(database);expect(completeIndependentExtent(bytes)).toEqual({rows:item.rows,valueBytes:item.valueBytes,schemaBytes:completeSemanticContract.schemaBytes,tableWidths:completeSemanticContract.tableWidths});const limits={maxRows:item.rows,maxValueBytes:item.valueBytes,maxSchemaBytes:completeSemanticContract.schemaBytes,maxTables:7,maxColumns:8};expect(await semioTableSnapshotToSqliteDatabase(source,limits)).toEqual(database);expect(await semioTableSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes),limits)).toEqual(source);
 for(const short of[{...limits,maxRows:item.rows-1},{...limits,maxValueBytes:item.valueBytes-1},{...limits,maxSchemaBytes:limits.maxSchemaBytes-1},{...limits,maxTables:6},{...limits,maxColumns:7}]){await expect(semioTableSnapshotToSqliteDatabase(source,short)).rejects.toThrow();await expect(semioTableSnapshotFromSqliteDatabase(database,short)).rejects.toThrow();}
 }console.log("[DEBUG] Semio Table independently measured Native matched full and empty roles through all5 copied limits");
});
