use crate::standards::v1::subsets::audio::io::sqlite::snapshot::*;
use semio_framework_os_kernel::{ArtifactSqliteSnapshot,sqlite_snapshot::*};
pub(crate) fn fixture()->SemioAudioSnapshot { let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap(); SemioAudioSnapshot {schema:f["schema"].as_str().unwrap().into(),sample_rate:f["sampleRate"].as_u64().unwrap() as u32,format:SemioAudioFormat::Float64,channels:f["channels"].as_array().unwrap().iter().map(|samples|SemioAudioChannel{samples:samples.as_array().unwrap().iter().map(|bits|f32::from_bits(bits.as_u64().unwrap() as u32)).collect()}).collect(),tags:f["tags"].as_array().unwrap().iter().map(|tag|SemioAudioTag{key:tag[0].as_str().unwrap().into(),value:tag[1].as_str().unwrap().into()}).collect()} }
fn project(value:&SemioAudioSnapshot)->SqliteDatabase {value.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap()}
fn restore(db:&SqliteDatabase)->Result<SemioAudioSnapshot, semio_framework_value::ValueError>{SemioAudioSnapshot::from_sqlite_database(db,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default()))}
#[test]
fn sqlite_snapshot_semio_audio_preserves_all_ieee754_sample_bits_and_native_formats(){let original=fixture();let bytes=export_sqlite_database(&project(&original),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let value=restore(&import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!(<SemioAudioSnapshot as store::ArtifactPack>::encode_pack(&value),<SemioAudioSnapshot as store::ArtifactPack>::encode_pack(&original));for (a,b)in value.channels.iter().zip(&original.channels){assert_eq!(a.samples.iter().map(|n|n.to_bits()).collect::<Vec<_>>(),b.samples.iter().map(|n|n.to_bits()).collect::<Vec<_>>());}for format in [SemioAudioFormat::Pcm8,SemioAudioFormat::Pcm16,SemioAudioFormat::Pcm24,SemioAudioFormat::Pcm32,SemioAudioFormat::Float32,SemioAudioFormat::Float64]{let mut snapshot=SemioAudioSnapshot::default();snapshot.format=format;assert_eq!(restore(&project(&snapshot)).unwrap(),snapshot);}}
#[test]
fn sqlite_snapshot_semio_audio_validates_sample_shape_ownership_ordinals_and_limits(){let original=project(&fixture());for change in 0..4 {let mut db=original.clone();match change{0=>db.table_mut("semio_audio_sample").unwrap().rows[0].values[1]=SqliteValue::Integer(999),1=>db.table_mut("semio_audio_sample").unwrap().rows[0].values[2]=SqliteValue::Integer(99),2=>db.table_mut("semio_audio_sample").unwrap().rows[0].values[3]=SqliteValue::Real(1.0),_=>db.table_mut("semio_audio_sample").unwrap().rows[0].values[4]=SqliteValue::Integer(-1)}assert!(restore(&db).is_err());}let limits=SqliteDatabaseLimits{max_rows:1,max_value_bytes:1,..SqliteDatabaseLimits::default()};assert!(fixture().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());assert!(SemioAudioSnapshot::from_sqlite_database(&original,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());assert!(fixture().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());}
#[test]
fn sqlite_snapshot_semio_audio_independent_sample_query_and_edit(){use std::io::Write;use std::process::{Command,Stdio};let bytes=export_sqlite_database(&project(&fixture()),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';const db=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(db.query('PRAGMA integrity_check').get().integrity_check!=='ok'||db.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');if(db.query('SELECT value FROM semio_audio_sample WHERE channel_id=1 ORDER BY ordinal').all().map(r=>r.value).join(',')!=='0,0,1,-1')throw Error('samples');db.query('UPDATE semio_audio_sample SET value=0.5,ieee754_bits=1056964608 WHERE channel_id=1 AND ordinal=0').run();await Bun.write(Bun.stdout,db.serialize());db.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let out=child.wait_with_output().unwrap();assert!(out.status.success(),"{}",String::from_utf8_lossy(&out.stderr));let restored=restore(&import_sqlite_database(&out.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!(restored.channels[0].samples[0].to_bits(),0.5f32.to_bits());}

#[test]
fn sqlite_snapshot_semio_audio_bare_owner_capability_native_payload_bridge(){let snapshot=fixture();let payload=store::os_io::IoPayload::Binary(<SemioAudioSnapshot as store::ArtifactPack>::encode_pack(&snapshot));let codec=store::ArtifactCodec::bare::<SemioAudioSnapshot,crate::standards::v1::subsets::audio::schema::mutations::SemioAudioMutation>("s.stdio.semio.audio");let provider=codec.snapshot_sqlite.expect("owner must publish typed SQLite capability");assert_eq!(provider.snapshot_type,Some(std::any::TypeId::of::<SemioAudioSnapshot>()));let dialect=semio_framework_artifact_reference::ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"audio".into()};let db=(provider.export)("s.stdio.semio.audio",&dialect,&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;let bytes=export_sqlite_database(&db,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let db=import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let actual=(provider.import)("s.stdio.semio.audio",&dialect,db,SnapshotEncoding::Binary,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;assert_eq!(actual,payload);}

#[test]
fn sqlite_snapshot_semio_audio_typed_exact_subset_dialect_and_document_guard(){let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let snapshot=fixture();let database=project(&snapshot);let dialect=|v:&serde_json::Value|semio_framework_artifact_reference::ArtifactDialect{artifact_kind:v["artifactKind"].as_str().unwrap().into(),standard:v["standard"].as_str().unwrap().into(),subset:v["subset"].as_str().unwrap().into()};let mut callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(&f["sqliteDialect"]),&database,&mut control).unwrap().diagnostics.is_empty());for invalid in f["invalidSqliteDialects"].as_array().unwrap(){assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(invalid),&database,&mut control).is_err());}let mut malformed=database;malformed.table_mut("semio_audio_document").unwrap().rows[0].values[1]=SqliteValue::Text("other schema".into());assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(&f["sqliteDialect"]),&malformed,&mut control).is_err());}

#[test]
fn sqlite_snapshot_semio_audio_bounded_native_text_binary_admission() {
    let snapshot=fixture();let dialect=semio_framework_artifact_reference::ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"audio".into()};
    let provider=<SemioAudioSnapshot as store::ArtifactPack>::sqlite_snapshot_codec().unwrap();
    for encoding in [SnapshotEncoding::Binary,SnapshotEncoding::Text]{
        snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();
        let database=snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();
        let actual=(provider.import)("Semio native admission",&dialect,database,encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;
        let expected=match encoding{SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<SemioAudioSnapshot as store::ArtifactDsl>::print_dsl(&snapshot)),SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<SemioAudioSnapshot as store::ArtifactPack>::encode_pack(&snapshot))};assert!(actual==expected,"controlled native output differs from the authored ordinary wire");
        assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:16,..SqliteDatabaseLimits::default()})).is_err());
        assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());
    }
    let large= SemioAudioSnapshot{schema:"x".repeat(100000),..snapshot};
    assert!(large.preflight_sqlite_snapshot_encoding(SnapshotEncoding::Text,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:4096,..SqliteDatabaseLimits::default()})).is_err());
    assert!(large.preflight_sqlite_snapshot_encoding(SnapshotEncoding::Binary,&mut SqliteSnapshotControl::new(&mut |p|p.phase!=SqliteSnapshotPhase::EncodeNative||p.completed==0,SqliteDatabaseLimits::default())).is_err());
}

#[test]
fn sqlite_snapshot_semio_audio_explicit_controlled_native_owner(){
 use store::{ArtifactPack,ArtifactDsl};let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let expected=fixture();
 for payload in [store::os_io::IoPayload::Binary(expected.encode_pack()),store::os_io::IoPayload::Text(expected.print_dsl())]{
  let actual=SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert_eq!(actual.schema,expected.schema);assert_eq!(actual.sample_rate,expected.sample_rate);assert_eq!(actual.format,expected.format);assert_eq!(actual.tags,expected.tags);assert_eq!(actual.channels.len(),expected.channels.len());for(a,e)in actual.channels.iter().zip(&expected.channels){assert_eq!(a.samples.iter().map(|v|v.to_bits()).collect::<Vec<_>>(),e.samples.iter().map(|v|v.to_bits()).collect::<Vec<_>>());}
  assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:f["nativeAdmission"]["tinyBudgetBytes"].as_u64().unwrap() as usize,..SqliteDatabaseLimits::default()})).is_err());assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:2,..SqliteDatabaseLimits::default()})).is_err());
 }
 let count=f["nativeAdmission"]["collectionItems"].as_u64().unwrap() as usize;let canceled=f["nativeAdmission"]["cancelAfter"].as_u64().unwrap() as usize;let word=f["nativeAdmission"]["sampleWord"].as_u64().unwrap() as u32;let large=SemioAudioSnapshot{channels:vec![SemioAudioChannel{samples:vec![f32::from_bits(word);count]}],..expected};
 for payload in [store::os_io::IoPayload::Binary(large.encode_pack()),store::os_io::IoPayload::Text(large.print_dsl())]{let mut interior=false;let mut callback=|p:SqliteSnapshotProgress|{if p.phase==SqliteSnapshotPhase::DecodeNative&&p.total==count&&p.completed==canceled{interior=true;false}else{true}};assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default())).is_err());assert!(interior);}
}

#[test]
fn sqlite_snapshot_semio_audio_controlled_native_output(){let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let mut s=fixture();s.tags[0].value="x".repeat(f["nativeOutputBytes"].as_u64().unwrap() as usize);for encoding in [SnapshotEncoding::Binary,SnapshotEncoding::Text]{let actual=s.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();let expected=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<SemioAudioSnapshot as store::ArtifactPack>::encode_pack(&s)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<SemioAudioSnapshot as store::ArtifactDsl>::print_dsl(&s))};assert!(actual==expected,"controlled native output differs from the authored ordinary wire");for measured in [false,true]{let mut interior=false;let error=s.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |event|{let cancel=event.phase==SqliteSnapshotPhase::EncodeNative&&event.completed>=65536&&(if measured{event.total==0}else{event.total>65536&&event.completed<event.total});interior|=cancel;!cancel},SqliteDatabaseLimits::default())).unwrap_err();assert!(interior&&error.message.contains("cancel"),"{error}");}for limits in [SqliteDatabaseLimits{max_value_bytes:4096,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_file_bytes:4096,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_rows:0,..SqliteDatabaseLimits::default()}]{assert!(s.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());}assert!(s.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());}}

fn norm_complete_source(case:&serde_json::Value)->SemioAudioSnapshot{let mut source=fixture();source.format=match case["format"].as_str().unwrap(){"pcm8"=>SemioAudioFormat::Pcm8,"pcm16"=>SemioAudioFormat::Pcm16,"pcm24"=>SemioAudioFormat::Pcm24,"pcm32"=>SemioAudioFormat::Pcm32,"f32"=>SemioAudioFormat::Float32,"f64"=>SemioAudioFormat::Float64,_=>panic!("authored format")};if case["empty"].as_bool().unwrap(){source.channels.clear();}source}
fn norm_independent_complete_extent(source:&SemioAudioSnapshot)->serde_json::Value{
 use store::{ArtifactSqliteSnapshot as _,sqlite_snapshot::*};use std::{io::Write,process::{Command,Stdio}};let database=source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();let bytes=export_sqlite_database(&database,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script=concat!(include_str!("../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts"),"\nawait Bun.write(Bun.stdout,JSON.stringify(independentSqliteExtent(new Uint8Array(await Bun.stdin.arrayBuffer()))));");let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));serde_json::from_slice(&output.stdout).unwrap()
}
#[test]
fn sqlite_snapshot_semio_audio_complete_independent_native_semantic_limits(){
 use store::{ArtifactSqliteSnapshot as _,sqlite_snapshot::*};let contract:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🎛️semantic.json")).unwrap();
 for case in contract["cases"].as_array().unwrap(){let source=norm_complete_source(case);let extent=norm_independent_complete_extent(&source);assert_eq!(extent["rows"],case["rows"]);assert_eq!(extent["valueBytes"],case["valueBytes"]);assert_eq!(extent["schemaBytes"],contract["schemaBytes"]);assert_eq!(extent["tableWidths"],contract["tableWidths"]);let limits=SqliteDatabaseLimits{max_rows:case["rows"].as_u64().unwrap()as usize,max_value_bytes:case["valueBytes"].as_u64().unwrap()as usize,max_schema_bytes:contract["schemaBytes"].as_u64().unwrap()as usize,max_tables:4,max_columns:5,..SqliteDatabaseLimits::default()};let database=source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();assert_eq!(SemioAudioSnapshot::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),database);
  for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{source.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();let payload=source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();assert_eq!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),database);
   for short in[SqliteDatabaseLimits{max_rows:limits.max_rows-1,..limits},SqliteDatabaseLimits{max_value_bytes:limits.max_value_bytes-1,..limits},SqliteDatabaseLimits{max_schema_bytes:limits.max_schema_bytes-1,..limits},SqliteDatabaseLimits{max_tables:3,..limits},SqliteDatabaseLimits{max_columns:4,..limits}]{assert!(source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,short)).is_err(),"relational copied limits {short:?}");assert!(SemioAudioSnapshot::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |_|true,short)).is_err(),"reconstruct copied limits {short:?}");assert!(source.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,short)).is_err(),"preflight copied limits {encoding:?} {short:?}");assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,short)).is_err(),"encoder copied limits {encoding:?} {short:?}");assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,short)).is_err(),"decoder copied limits {encoding:?} {short:?}");}
  }
 }eprintln!("[DEBUG] Semio Audio independently measured complete copied native semantic limits");
}
#[test]
fn sqlite_snapshot_semio_audio_complete_independent_copied_columns_admission(){
 use store::{ArtifactSqliteSnapshot as _,sqlite_snapshot::*};let source=fixture();let database=source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();let limits=SqliteDatabaseLimits{max_columns:4,..SqliteDatabaseLimits::default()};assert!(source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());assert!(SemioAudioSnapshot::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let payload=source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert!(source.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err(),"preflight copied columns {encoding:?}");assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err(),"encoder copied columns {encoding:?}");assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err(),"decoder copied columns {encoding:?}");}
}

/// 🔮️ Interprets every actual public-file cell and declared table through independent SQLite.
fn norm_independent_public_file_extent(bytes:&[u8])->serde_json::Value{use std::{io::Write,process::{Command,Stdio}};let script=concat!(include_str!("../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts"),"\nawait Bun.write(Bun.stdout,JSON.stringify(independentSqliteExtent(new Uint8Array(await Bun.stdin.arrayBuffer()))));");let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));serde_json::from_slice(&output.stdout).unwrap()
}

#[semio_framework_async_macros::async_test]
async fn sqlite_snapshot_semio_audio_complete_actual_typed_public_io_limits(){
 use {semio_framework_artifact_reference::ArtifactDialect,semio_framework_os_kernel::io::io_mechanism::io_export_sqlite_snapshot,semio_framework_os_kernel::io::io_mechanism::io_import_sqlite_snapshot};use store::sqlite_snapshot::*;
 semio_framework_plugin::Plugin::<semio_framework_plugin::app::NoPluginApp>::builder("stdio").label("semioAudio complete public file scope").version("0.0.1").package_id("semio:stdio").artifact(crate::declaration(crate::definition().unwrap()).unwrap()).try_build().unwrap();
 let dialect=ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"audio".into()};let contract:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🎛️semantic.json")).unwrap();let public=&contract["publicIo"];
 for case in contract["cases"].as_array().unwrap(){let source=norm_complete_source(case);let domain=SqliteDatabaseLimits{max_rows:case["rows"].as_u64().unwrap()as usize,max_value_bytes:case["valueBytes"].as_u64().unwrap()as usize,max_schema_bytes:contract["schemaBytes"].as_u64().unwrap()as usize,max_tables:4,max_columns:5,..SqliteDatabaseLimits::default()};let expected=source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,domain)).unwrap();let public_case=public["cases"].as_array().unwrap().iter().find(|value|value["id"]==case["id"]).unwrap();
  for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let encoding_name=match encoding{SnapshotEncoding::Binary=>"binary",SnapshotEncoding::Text=>"text"};let limits=SqliteDatabaseLimits{max_rows:public_case["rows"].as_u64().unwrap()as usize,max_value_bytes:public_case["valueBytes"][encoding_name].as_u64().unwrap()as usize,max_schema_bytes:public["schemaBytes"].as_u64().unwrap()as usize,max_tables:5,max_columns:6,..domain};let file=io_export_sqlite_snapshot(&dialect,&source,encoding,limits,&mut |_|true).await.unwrap().value;assert_eq!(&file[..16],b"SQLite format 3\0");assert_eq!(norm_independent_public_file_extent(&file),serde_json::json!({"rows":public_case["rows"],"valueBytes":public_case["valueBytes"][encoding_name],"schemaBytes":public["schemaBytes"],"tableWidths":public["tableWidths"]}));let restored=io_import_sqlite_snapshot::<SemioAudioSnapshot>(&dialect,&file,limits,&mut |_|true).await.unwrap().value;assert_eq!(restored.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),expected);
   for short in[SqliteDatabaseLimits{max_rows:limits.max_rows-1,..limits},SqliteDatabaseLimits{max_value_bytes:limits.max_value_bytes-1,..limits},SqliteDatabaseLimits{max_schema_bytes:limits.max_schema_bytes-1,..limits},SqliteDatabaseLimits{max_tables:4,..limits},SqliteDatabaseLimits{max_columns:5,..limits}]{assert!(io_export_sqlite_snapshot(&dialect,&source,encoding,short,&mut |_|true).await.is_err());assert!(io_import_sqlite_snapshot::<SemioAudioSnapshot>(&dialect,&file,short,&mut |_|true).await.is_err());}
  }
 }eprintln!("[DEBUG] semioAudio actual registered typed IO preserved independently complete public files and all five public-file limits");
}

/// 🧵️ Uses literal UTF8 boundaries through every original controlled owner text position.
fn hex_utf8_document_payload(hex:&str,slot:usize)->store::os_io::IoPayload{let body=match slot {0=>format!("schema={hex}\nsampleRate=0\nchannels=[]\ntags=[]"),1=>format!("schema=73\nsampleRate=0\nchannels=[]\ntags=[[{hex},76]]"),_=>format!("schema=73\nsampleRate=0\nchannels=[]\ntags=[[6b,{hex}]]")};store::os_io::IoPayload::Text(format!("semio stdio.semio.audio.dsl v1\n{body}"))}
#[test]
fn sqlite_snapshot_semio_audio_literal_hex_utf8_boundaries_and_nested_refusals(){
 let authority:serde_json::Value=serde_json::from_str(include_str!("../../../../../✉️base/🚪️io/🪶️sqlite/📸️snapshot/🧪️tests/🧫️fixtures/🧵️hex-utf8/🔣️.json")).unwrap();
 for case in authority["positive"].as_array().unwrap(){for slot in 0..3{let actual=SemioAudioSnapshot::decode_sqlite_snapshot_native(&hex_utf8_document_payload(case["hex"].as_str().unwrap(),slot),&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert_eq!(match slot {0=>actual.schema.as_str(),1=>actual.tags[0].key.as_str(),_=>actual.tags[0].value.as_str()},case["text"].as_str().unwrap(),"{} slot={slot}",case["id"]);assert_eq!(crate::standards::v1::subsets::audio::io::text::snapshot::enc_format(actual.format),"pcm16");}}
 for case in authority["negative"].as_array().unwrap(){for slot in 0..3{assert!(SemioAudioSnapshot::decode_sqlite_snapshot_native(&hex_utf8_document_payload(case["hex"].as_str().unwrap(),slot),&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),"{} slot={slot}",case["id"]);}}eprintln!("[DEBUG] Semio Audio original native routes checked literal UTF8 authority at3 field positions");
}
