[package]
name = "remodel_mesh"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
remodel_dense = { path = "../../dense/rs" }
remodel_image = { path = "../../image/rs" }
remodel_camera = { path = "../../camera/rs" }
semio-framework-core = { path = "../../../framework/core/rs" }
mathematical_algebra = { path = "../../../framework/kernel/mathematical/algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
mathematical_spatial = { path = "../../../framework/kernel/mathematical/spatial/rs", package = "semio-framework-kernel-mathematical-spatial" }
mathematical_graph = { path = "../../../framework/kernel/mathematical/graph/rs", package = "semio-framework-kernel-mathematical-graph" }
mathematical_lie = { path = "../../../framework/kernel/mathematical/lie/rs", package = "semio-framework-kernel-mathematical-lie" }
base64 = "0.22"
