// 🧬️ EN 1999 snapshot schema.
syntax = "proto3";
package semio.s.norm.en1999.snapshot;

message En1999Snapshot {
  // @state persistent
  double n_ed_kn = 1;
  // @state persistent
  double m_ed_knm = 2;
  // @state persistent
  double a_mm2 = 3;
  // @state persistent
  double w_el_mm3 = 4;
  // @state persistent
  double alloy = 5;
  // @state persistent
  double chi = 6;
  // @state persistent
  double i_t_mm4 = 7;
  // @state persistent
  double l_cr_mm = 8;
  // @state persistent
  double theta_c = 9;
  // @state persistent
  double delta_sigma_ed = 10;
  // @state persistent
  double delta_sigma_c = 11;
  // @state persistent
  double fatigue_m = 12;
  // @state persistent
  double n_cycles = 13;
  // @state persistent
  double v_weld_ed_kn = 14;
  // @state persistent
  double weld_throat_mm = 15;
  // @state persistent
  double weld_length_mm = 16;
  // @state persistent
  double beta_w = 17;
  // @state persistent
  double sheet_b_mm = 18;
  // @state persistent
  double sheet_t_mm = 19;
  // @state persistent
  double sheet_k_sigma = 20;
  // @state persistent
  double sheet_w_el_mm3 = 21;
  // @state persistent
  double sheet_m_ed_knm = 22;
  // @state persistent
  double shell_t_mm = 23;
  // @state persistent
  double shell_r_mm = 24;
  // @state persistent
  double sigma_ed_shell_mpa = 25;
  // @state persistent
  double annex = 26;
}
