syntax = "proto3";
package semio.s.fem.fem3d.artifact;

// 🧬️ Fem3d artifact schema
message Fem3dArtifact {
  // @state artifact
  repeated FemNode nodes = 1;
  // @state artifact
  repeated FemElement elements = 2;
  // @state artifact
  repeated FemMaterial materials = 3;
  // @state artifact
  repeated FemSection sections = 4;
  // @state artifact
  repeated FemSolid solids = 5;
  // @state artifact
  repeated FemSupport supports = 6;
  // @state artifact
  repeated FemLoadCase load_cases = 7;
  // @state artifact
  repeated FemCombination combinations = 8;
  // @state artifact
  FemAnalysisSettings analysis = 9;
}


message FemAnalysisSettings {
  uint32 modal_count = 1;
  uint32 buckling_count = 2;
  double deformation_scale = 3;
}

message FemNode {
  string id = 1;
  double x = 2;
  double y = 3;
  double z = 4;
}

message FemMaterial {
  string id = 1;
  string name = 2;
  double e = 3;
  double g = 4;
  double nu = 5;
  double rho = 6;
}

message FemSection {
  string id = 1;
  string name = 2;
  double area = 3;
  double iy = 4;
  double iz = 5;
  double j = 6;
}

message FemSupport {
  string id = 1;
  string node_id = 2;
  repeated string fixed = 3;
}
