[package]
name = "geometry_brep_brepkit"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1.88"
geometry_brep_engine = { path = "../engine" }
brepkit-topology = { git = "https://github.com/andymai/brepkit" }
brepkit-operations = { git = "https://github.com/andymai/brepkit" }
brepkit-math = { git = "https://github.com/andymai/brepkit" }
