[package]
name = "remodel_geo"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "📦.rs"

[dependencies]
remodel_sfm = { path = "../../../sfm/⚡️/🦀", package = "remodel_sfm" }
remodel_dense = { path = "../../../dense/⚡️/🦀", package = "remodel_dense" }
remodel_mesh = { path = "../../../mesh/⚡️/🦀", package = "remodel_mesh" }
remodel_image = { path = "../../../image/⚡️/🦀", package = "remodel_image" }
remodel_camera = { path = "../../../camera/⚡️/🦀", package = "remodel_camera" }
mathematical_algebra = { path = "../../../../../../../🧰/🔨/math/⚡️/🦀/algebra", package = "semio-framework-os-kernel-math-algebra" }
mathematical_lie = { path = "../../../../../../../🧰/🔨/math/⚡️/🦀/lie", package = "semio-framework-os-kernel-math-lie" }
mathematical_spatial = { path = "../../../../../../../🧰/🔨/math/⚡️/🦀/spatial", package = "semio-framework-os-kernel-math-spatial" }
mathematical_optimize = { path = "../../../../../../../🧰/🔨/math/⚡️/🦀/optimize", package = "semio-framework-os-kernel-math-optimize" }
mathematical_random = { path = "../../../../../../../🧰/🔨/math/⚡️/🦀/random", package = "semio-framework-os-kernel-math-random" }
