import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve } from "node:path";
const ticket=dirname(import.meta.dir),root=resolve(ticket,"../../../../../../.."),[command,epoch="1"]=process.argv.slice(2),require=createRequire(join(root,"package.json")),ts=require("typescript"),Ajv=require("ajv"),plugin="✏️s/🔌️plugins/🧱️block",old=plugin+"/🗿️artifacts/◻️2d/🧬️schema/🧱️shared",shared=plugin+"/🧬️schema/🧱️shared",pkg=plugin+"/📦️packages/🦀️rust",sha=(s:string)=>createHash("sha256").update(s).digest("hex"),read=(p:string):string|null=>existsSync(join(root,p))?readFileSync(join(root,p),"utf8"):null,rel=(from:string,to:string)=>{const p=relative(dirname(from),to).replaceAll("\\","/");return p.startsWith(".")?p:"./"+p;},out=join(ticket,"🗑️generated/block-shared-schema-owner");mkdirSync(out,{recursive:true});
if(command==="red"||command==="model"){
 const sourcePath=join(out,"source-"+epoch+".json"),sourceRaw=readFileSync(sourcePath,"utf8"),source=JSON.parse(sourceRaw),dest=join(out,command+"-"+epoch);assert.equal(existsSync(dest),false);mkdirSync(dest,{recursive:true});const candidates=new Map(source.pairs.map((row:any)=>[row.path,row.after])),frames=new Map<string,string>(),visited=new Set<string>(),pending=[shared+"/🧪️tests/🟦️.ts"],value=(path:string):string|null=>candidates.has(path)?candidates.get(path) as string|null:read(path),locate=(from:string,specifier:string):string|null=>{
 if(specifier.startsWith(".")||specifier.startsWith("/")){const base=relative(root,resolve(root,dirname(from),specifier)).replaceAll("\\","/");for(const path of[base,base+".ts",base+".tsx",base+".mts",base+".js",base+".mjs",base+"/index.ts",base+"/index.js"])if(value(path)!==null)return path;throw Error("Missing prospective source import: "+from+" "+specifier);}
 if(specifier.startsWith("node:")||specifier.startsWith("bun:"))return null;let full:string;try{full=Bun.resolveSync(specifier,join(root,dirname(from)));}catch{throw Error("Unresolved external source import: "+from+" "+specifier);}const path=relative(root,full).replaceAll("\\","/");return path.startsWith("../")||path.startsWith("node_modules/")?null:path;
 };
 while(pending.length){const path=pending.pop()!;if(visited.has(path))continue;visited.add(path);assert.ok(!path.startsWith(plugin+"/🗿️artifacts/"),"Plugin closure reaches removable artifact: "+path);const text=value(path);assert.ok(text!==null,path);frames.set(path,text);if(!/\.[cm]?[jt]sx?$/.test(path))continue;const ast=ts.createSourceFile(path,text,ts.ScriptTarget.Latest,true);const visit=(node:any):void=>{let specifier:string|undefined;if((ts.isImportDeclaration(node)||ts.isExportDeclaration(node))&&node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier))specifier=node.moduleSpecifier.text;else if(ts.isCallExpression(node)&&node.arguments.length===1&&ts.isStringLiteral(node.arguments[0])&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||ts.isIdentifier(node.expression)&&["require","createRequire"].includes(node.expression.text)))specifier=node.arguments[0].text;if(specifier!==undefined){const target=locate(path,specifier);if(target)pending.push(target);}ts.forEachChild(node,visit);};visit(ast);}
 const floor=[...frames].map(([path,source])=>({path,source,sha256:sha(source),prospective:candidates.has(path)}));writeFileSync(join(dest,"plan.json"),JSON.stringify({sourceHash:sha(sourceRaw),frames:floor,artifactsAbsent:true,producer:{path:import.meta.path,source:readFileSync(import.meta.path,"utf8")}}));for(const row of floor){const path=join(dest,row.path);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,row.source);}if(command==="red"){const api=source.pairs.find((row:any)=>row.path===plugin+"/🟦️.ts");writeFileSync(join(dest,api.path),api.before);}
 const child=Bun.spawn([process.execPath,"test",join(dest,shared,"🧪️tests/🟦️.ts")],{cwd:root,stdout:"pipe",stderr:"pipe"}),timer=setInterval(()=>console.log("[DEBUG] Block plugin deletion model active"),10000),cancel=()=>child.kill();process.once("SIGINT",cancel);process.once("SIGTERM",cancel);try{const [stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);writeFileSync(join(dest,"actual.log"),stdout+stderr);const postGaps=source.pairs.filter((row:any)=>read(row.path)!==row.before).map((row:any)=>row.path),floorGaps=floor.filter(row=>!row.prospective&&read(row.path)!==row.source).map(row=>row.path);assert.equal(readFileSync(sourcePath,"utf8"),sourceRaw);writeFileSync(join(dest,"terminal.json"),JSON.stringify({sourceHash:sha(sourceRaw),exitCode,postGaps,floorGaps,heldFrames:floor.length,artifactsAbsent:true,sourceWrites:0,nativeExecuted:false,wholeRootAccepted:false}));console.log("[DEBUG] Block plugin deletion model completed "+JSON.stringify({command,exitCode,postGaps:postGaps.length,floorGaps:floorGaps.length,heldFrames:floor.length}));process.exitCode=exitCode;}finally{clearInterval(timer);process.off("SIGINT",cancel);process.off("SIGTERM",cancel);}process.exit(process.exitCode??0);
}
assert.equal(command,"stage");const destination=join(out,"source-"+epoch+".json");assert.equal(existsSync(destination),false);
const pairs:any[]=[],map=new Map<string,any>(),pair=(path:string,after:string|null):void=>{const before=read(path);assert.equal(map.has(path),false,path);const row={path,before,after,beforeHash:before===null?null:sha(before),afterHash:after===null?null:sha(after)};pairs.push(row);map.set(path,row);},replacement=(source:string,from:string,to:string):string=>{assert.equal(source.split(from).length-1,1,from);return source.replace(from,to);},imports=(source:string,from:string,to:string):string=>{const ast=ts.createSourceFile(from,source,ts.ScriptTarget.Latest,true),edits:any[]=[];const visit=(node:any):void=>{if((ts.isImportDeclaration(node)||ts.isExportDeclaration(node))&&node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier)){const specifier=node.moduleSpecifier.text;if(specifier.startsWith(".")){let target=relative(root,resolve(root,dirname(from),specifier)).replaceAll("\\","/");if(target===old||target.startsWith(old+"/"))target=shared+target.slice(old.length);const value=rel(to,target);if(value!==specifier)edits.push({start:node.moduleSpecifier.getStart(ast),end:node.moduleSpecifier.end,value:JSON.stringify(value)});}}ts.forEachChild(node,visit);};visit(ast);let after=source;for(const edit of edits.sort((a,b)=>b.start-a.start))after=after.slice(0,edit.start)+edit.value+after.slice(edit.end);return after;};
const suffixes=["🟦️.ts","📐️scalar/🟦️.ts","🪶️sqlite/🟦️.ts","🚪️io/🔣️json/🟦️.ts","🔣️.json","🦀️.rs"];for(const suffix of suffixes){const from=old+"/"+suffix,to=shared+"/"+suffix,source=read(from)!;assert.ok(source);pair(to,suffix.endsWith(".ts")?imports(source,from,to):source);pair(from,null);}
const names=["BlockKindIdentity","BlockAttribute","BlockAuthor","BlockCompatibilityRule","BlockRepresentation","BlockCamera2d","BlockCamera3d","BlockMeta"],parsers=names.map(name=>"parse"+name),types=[...names,"BlockVector3","BlockVector4"];pair(plugin+"/🟦️.ts",'/** 🧱️ Plugin-owned Block records remain independent of every artifact. */\nexport { '+parsers.join(", ")+' } from "./🧬️schema/🧱️shared/🟦️.ts";\nexport type { '+types.join(", ")+' } from "./🧬️schema/🧱️shared/🟦️.ts";\n');
const walk=(directory:string):void=>{for(const row of readdirSync(join(root,directory),{withFileTypes:true})){if(row.isSymbolicLink()||row.name.startsWith(".")||["node_modules","target","dist","temp","build","🗑️generated"].includes(row.name))continue;const path=directory+"/"+row.name;if(row.isDirectory())walk(path);else if(row.isFile()&&/\.[cm]?[jt]sx?$/.test(row.name)&&!map.has(path)){const before=read(path)!;const after=imports(before,path,path);if(after!==before)pair(path,after);}}};walk(plugin);
const native2d=plugin+"/🗿️artifacts/◻️2d/🦀️.rs",native3d=plugin+"/🗿️artifacts/🧊️3d/🦀️.rs",native5d=plugin+"/🗿️artifacts/🖐️5d/🦀️.rs",sharedUse="pub use semio_s_plugin_block::{"+names.join(", ")+"};";pair(native2d,replacement(read(native2d)!,'#[path = "🧬️schema/🧱️shared/🦀️.rs"]\nmod shared;\npub use shared::*;',sharedUse));for(const path of[native3d,native5d])pair(path,replacement(read(path)!,"pub use semio_s_artifact_block_2d::{"+names.slice().sort().join(", ")+"};",sharedUse));
const retirementPath=plugin+"/🗿️artifacts/◻️2d/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/♻️retirement/🦀️.rs",retirement=read(retirementPath)!,start=retirement.indexOf("//#region 🧱️SharedRows"),end=retirement.indexOf("//#endregion 🧱️SharedRows",start)+"//#endregion 🧱️SharedRows".length;assert.ok(start>=0&&end>start);const body=retirement.slice(start,end);pair(shared+"/♻️retirement/🦀️.rs","//! ♻️ Shared Block records retire at their plugin owner.\nuse crate::{"+names.join(", ")+"};\nuse semio_framework_value::retirement::{RetireOwned, RetirementCursor};\n"+body+"\n");let retired=retirement.slice(0,start)+retirement.slice(end);retired=retired.replace('//! The shared `Block*` rows are owned by this crate (`🧬️schema/🧱️shared`), so their retirement lives\n//! here too and every sibling block artifact that embeds them reuses it.','//! Shared Block records use the plugin-owned retirement implementations.');retired=replacement(retired,"use crate::{Block2dHandleKind, Block2dHandleTemplate, Block2dPresentation, Block2dSnapshot, BlockAttribute, BlockAuthor, BlockCamera2d, BlockCamera3d, BlockCompatibilityRule, BlockKindIdentity, BlockMeta, BlockRepresentation};","use crate::{Block2dHandleKind, Block2dHandleTemplate, Block2dPresentation, Block2dSnapshot};");pair(retirementPath,retired);
pair(plugin+"/🦀️.rs",'//! 🧱️ Block plugin schema authority has no artifact dependencies.\n#[path = "🧬️schema/🧱️shared/🦀️.rs"]\nmod schema;\npub use schema::{'+names.join(", ")+'};\n#[path = "🧬️schema/🧱️shared/♻️retirement/🦀️.rs"]\nmod retirement;\n');
const fixture={schemaVersion:1,runtimeExports:parsers.slice().sort(),cases:[
{type:"BlockKindIdentity",input:{id:"kind",name:"cube",label:"Cube",variant:"solid",description:"Shared kind",icon:"cube",unit:"m"}},
{type:"BlockAttribute",input:{key:"material",value:"wood",definition:"material"}},
{type:"BlockAuthor",input:{id:"author",name:"Author",email:"author@example.test"}},
{type:"BlockCompatibilityRule",input:{id:"rule",source:"left",target:"right",bidirectional:true}},
{type:"BlockRepresentation",input:{id:"representation",name:"Body",meshUrl:"asset.glb",tags:["near","detailed"],lod:"high",description:"Shared mesh",attributes:[{key:"material",value:"wood",definition:"material"}]}},
{type:"BlockCamera2d",input:{x:2.5,y:-4,zoom:1.25}},
{type:"BlockCamera3d",input:{position:[1,2,3],target:[0,0,0],zoom:1.5}},
{type:"BlockMeta",input:{description:"Shared document"}}
]},sharedSchema=JSON.parse(map.get(shared+"/🔣️.json").after),fixtureSchema={$schema:"http://json-schema.org/draft-07/schema#",type:"object",additionalProperties:false,required:["schemaVersion","runtimeExports","cases"],properties:{schemaVersion:{const:1},runtimeExports:{const:fixture.runtimeExports},cases:{type:"array",minItems:8,maxItems:8,uniqueItems:true,items:{oneOf:names.map(type=>({type:"object",additionalProperties:false,required:["type","input"],properties:{type:{const:type},input:{$ref:sharedSchema.$id+"#/$defs/"+type}}}))}}}};pair(shared+"/🧫️fixtures/🔣️.json",JSON.stringify(fixture,null,2)+"\n");pair(shared+"/🧫️fixtures/🛂️schema/🔣️.json",JSON.stringify(fixtureSchema,null,2)+"\n");
const frameworkWord="🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts",testPath=shared+"/🧪️tests/🟦️.ts";pair(testPath,`import {test,expect} from "bun:test";\nimport {Database} from "bun:sqlite";\nimport Ajv from "ajv";\nimport * as api from "${rel(testPath,plugin+"/🟦️.ts")}";\nimport * as transport from "../🚪️io/🔣️json/🟦️.ts";\nimport {binary64Value} from "${rel(testPath,frameworkWord)}";\nimport fixture from "../🧫️fixtures/🔣️.json";\nimport fixtureSchema from "../🧫️fixtures/🛂️schema/🔣️.json";\nimport schema from "../🔣️.json";\nconst plain=(value:unknown):unknown=>{if(value&&typeof value==="object"&&!Array.isArray(value)&&typeof (value as {bits?:unknown}).bits==="bigint")return binary64Value(value as {bits:bigint});if(Array.isArray(value))return value.map(plain);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,value])=>[key,plain(value)]));return value;};\ntest("plugin-owned Block records and explicit exports agree with schema and SQLite JSON",()=>{\nconst ajv=new Ajv({strict:true});ajv.addSchema(schema);const validate=ajv.compile(fixtureSchema);expect(validate(fixture),JSON.stringify(validate.errors)).toBe(true);expect(validate({...fixture,extra:true})).toBe(false);expect(Object.keys(api).sort()).toEqual(fixture.runtimeExports);const parsers:Record<string,(v:unknown)=>unknown>={BlockKindIdentity:transport.kind,BlockAttribute:transport.attribute,BlockAuthor:transport.author,BlockCompatibilityRule:transport.compatible,BlockRepresentation:transport.representation,BlockCamera2d:transport.camera2d,BlockCamera3d:transport.camera3d,BlockMeta:api.parseBlockMeta},database=new Database(":memory:");try{for(const row of fixture.cases){const input=JSON.stringify(row.input),owned=plain(parsers[row.type]!(row.input)),oracle=JSON.parse((database.query("SELECT json(?1) AS body").get(input) as {body:string}).body);expect(owned,row.type).toEqual(oracle);const count=(database.query("SELECT COUNT(*) AS count FROM json_each(?1)").get(input) as {count:number}).count;expect(Object.keys(owned as object).length,row.type).toBe(count);console.log("[DEBUG] Block plugin shared schema "+JSON.stringify({type:row.type,fields:count}));}}finally{database.close();}});\n`);
const nativeTest=shared+"/🧪️tests/🦀️.rs";pair(nativeTest,`//! 🧱️ Plugin-owned native records agree with the portable JSON corpus and independent Serde.\nuse semio_s_plugin_block::*;\nfn roundtrip<T: serde::de::DeserializeOwned + serde::Serialize>(input:serde_json::Value)->serde_json::Value{let value:T=serde_json::from_value(input).expect("native shared record");serde_json::to_value(value).expect("native shared record output")}\n#[test]\nfn shared_plugin_records_match_the_portable_schema_vectors(){let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).expect("shared corpus");assert_eq!(fixture["schemaVersion"],1);let rows=fixture["cases"].as_array().expect("eight records");assert_eq!(rows.len(),8);for row in rows{let input=row["input"].clone();let actual=match row["type"].as_str().expect("type"){${names.map(name=>'"'+name+'"=>roundtrip::<'+name+'>(input.clone()),').join("")}_=>panic!("unknown shared type")};assert_eq!(actual,input,"{}",row["type"]);eprintln!("[DEBUG] Native Block plugin shared schema {}",row["type"]);}}\n#[test]\nfn shared_retirement_is_owned_by_the_plugin(){fn owner<T:semio_framework_value::retirement::RetireOwned>(){} ${names.map(name=>"owner::<"+name+">();").join("")}}\n`);
pair(pkg+"/Cargo.toml",`[package]\nworkspace = "../../../.."\nname = "semio-s-plugin-block"\nversion.workspace = true\nedition.workspace = true\nrust-version.workspace = true\ndescription = "Block plugin shared schema and retirement authority"\n\n[package.metadata.semio]\nrole = "plugin"\n\n[lints]\nworkspace = true\n\n[lib]\npath = "../../🦀️.rs"\n\n[features]\ndefault = []\ntest-serde = ["dep:serde"]\n\n[[test]]\nname = "shared-schema"\npath = "../../🧬️schema/🧱️shared/🧪️tests/🦀️.rs"\nrequired-features = ["test-serde"]\n\n[dependencies]\nsemio-framework-value = { workspace = true }\nsemio-framework-dsl-record = { workspace = true }\nsemio-framework-dsl-record-derive = { workspace = true }\nserde = { workspace = true, optional = true }\n\n[dev-dependencies]\nserde = { workspace = true }\nserde_json = { workspace = true }\n`);
pair(pkg+"/📜️script.ts",'#!/usr/bin/env bun\n/** 🧱️ Runs the Block plugin native schema owner. */\nimport { runArtifactRustPackageMain } from "'+rel(pkg+"/📜️script.ts","🧰️framework/🛍️products/🦑️repo/🔨️modules/📚️library/⚡️caching/📦️artifacts/🦀️rust/🟦️.ts")+'";\nawait runArtifactRustPackageMain(import.meta.dir,"semio-s-plugin-block");\n');
const project={name:"@semio-tech/block-shared-rs",$schema:rel(pkg+"/📋️project.json","node_modules/nx/schemas/project-schema.json"),projectType:"library",tags:["language:rust","role:plugin","family:block"],targets:Object.fromEntries(["build","check","test"].map(command=>[command,{executor:"nx:run-commands",cache:false,options:{cwd:pkg,command:"bun ./📜️script.ts "+command+(command==="test"?" --features test-serde":""),forwardAllArgs:true}}]))};pair(pkg+"/📋️project.json",JSON.stringify(project,null,2)+"\n");
for(const path of[native2d,native3d,native5d]){const manifest=dirname(path)+"/📦️packages/🦀️rust/Cargo.toml";let after=read(manifest)!;after=replacement(after,"[dependencies]\n","[dependencies]\nsemio-s-plugin-block = { path = "+JSON.stringify(rel(manifest,pkg))+" }\n");after=replacement(after,"[dev-dependencies]\n",'[dev-dependencies]\nsemio-s-plugin-block = { path = '+JSON.stringify(rel(manifest,pkg))+', features = ["test-serde"] }\n');if(path===native2d)after=replacement(after,"test-serde = []",'test-serde = ["semio-s-plugin-block/test-serde"]');pair(manifest,after);}
const sourcePath=plugin+"/📦️packages/🟦️typescript/📜️script.ts";let script=read(sourcePath)!;const commandClass='class SharedSchemaScript extends BundleScript {\n  async run(segments:string[]):Promise<void>{if(segments.length)throw Error("shared-schema accepts no arguments");await runOwnedCommand(process.execPath,["test",resolve(this.root,"../../🧬️schema/🧱️shared/🧪️tests/🟦️.ts")],this.repoRoot,"block-shared-schema",undefined,{env:process.env});}\n}\n';script=replacement(script,"#!/usr/bin/env bun\n",'#!/usr/bin/env bun\nimport {runOwnedCommand} from "'+rel(sourcePath,"🧰️framework/🔨️modules/🏃️process/🎛️owned-execution/🟦️.ts")+'";\n');const marker='const router = new ScriptRouter(import.meta.dir).register("test", TestScript).register("publication-authority-audit", TestScript);';script=replacement(script,marker,commandClass+marker.replace(';','.register("shared-schema",SharedSchemaScript);'));pair(sourcePath,script);
const tsProjectPath=plugin+"/📦️packages/🟦️typescript/📋️project.json",tsProject=JSON.parse(read(tsProjectPath)!),tsPackagePath=plugin+"/📦️packages/🟦️typescript/package.json",tsPackage=JSON.parse(read(tsPackagePath)!);assert.equal(tsProject.targets["shared-schema"],undefined);tsProject.targets["shared-schema"]={executor:"nx:run-commands",cache:false,options:{cwd:plugin+"/📦️packages/🟦️typescript",command:"bun ./📜️script.ts shared-schema",forwardAllArgs:true}};pair(tsProjectPath,JSON.stringify(tsProject,null,2)+"\n");assert.equal(tsPackage.scripts["shared-schema"],undefined);tsPackage.scripts["shared-schema"]="bun nx run @semio-tech/block-js:shared-schema";pair(tsPackagePath,JSON.stringify(tsPackage,null,2)+"\n");const sManifest="✏️s/Cargo.toml",sBefore=read(sManifest)!,members=(Bun.TOML.parse(sBefore) as any).workspace.members,member=pkg.slice("✏️s/".length);assert.equal(members.includes(member),false);const sorted=[...members,member].sort(),begin=sBefore.indexOf("members = ["),finish=sBefore.indexOf("\n]",begin)+2;assert.ok(begin>=0&&finish>begin);const sAfter=sBefore.slice(0,begin)+"members = [\n"+sorted.map(value=>"    "+JSON.stringify(value)+",").join("\n")+"\n]"+sBefore.slice(finish),restore=Bun.TOML.parse(sAfter) as any,original=Bun.TOML.parse(sBefore) as any;restore.workspace.members=original.workspace.members;assert.deepEqual(restore,original);pair(sManifest,sAfter);
const ajv=new Ajv({strict:true});ajv.addSchema(sharedSchema);assert.equal(ajv.compile(fixtureSchema)(fixture),true);for(const row of pairs)assert.ok(read(row.path)===row.before,row.path);writeFileSync(destination,JSON.stringify({producer:{path:import.meta.path,source:readFileSync(import.meta.path,"utf8")},pairs,fixture,fixtureSchema,movedFiles:suffixes.length,sharedNativeTypes:names,retirementImplementations:8,sourceWrites:0,nativeExecuted:false,wholeRootAccepted:false,remainingArtifactCatalogAndBridgeDependencies:true}));console.log("[DEBUG] Block shared owner staged "+JSON.stringify({pairs:pairs.length,movedFiles:suffixes.length,nativeTypes:names.length,cases:fixture.cases.length,sourceWrites:0}));

