use crate::standards::v1::subsets::any::io::sqlite::snapshot::PlaybookSnapshot;
use semio_framework_os_kernel::{ArtifactSqliteSnapshot,sqlite_snapshot::*};
use semio_framework_value::ValueError;
fn fixture()->PlaybookSnapshot{let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let s=&f["snapshot"];let f=&s["flow"];let ft=&f["target"];let fd=&ft["dialect"];PlaybookSnapshot{schema:s["schema"].as_str().unwrap().into(),id:s["id"].as_str().unwrap().into(),version:s["version"].as_str().unwrap().into(),title:s["title"].as_str().map(String::from),flow:store::ArtifactChild::new(f["childId"].as_str().unwrap().into(),store::os_io::ArtifactRef{artifact_id:ft["artifactId"].as_str().unwrap().into(),dialect:store::os_io::ArtifactDialect{artifact_kind:fd["artifactKind"].as_str().unwrap().into(),standard:fd["standard"].as_str().unwrap().into(),subset:fd["subset"].as_str().unwrap().into()}})}}
fn project(s:&PlaybookSnapshot)->SqliteDatabase{s.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap()}
fn restore(d:&SqliteDatabase)->Result<PlaybookSnapshot,ValueError>{PlaybookSnapshot::from_sqlite_database(d,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default()))}
#[test]fn sqlite_snapshot_playbook_independent_sqlite_queries_and_owned_edit(){use std::io::Write;use std::process::{Command,Stdio};let s=fixture();let bytes=export_sqlite_database(&project(&s),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';const d=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(d.query('PRAGMA integrity_check').get().integrity_check!=='ok'||d.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');const f=d.query('SELECT child_id,artifact_id FROM playbook_flow_child').get();if(f.child_id===f.artifact_id)throw Error('distinct target');d.query(\"UPDATE playbook_document SET title='independent playbook title 日本'\").run();d.query(\"UPDATE playbook_flow_child SET artifact_id='independent target β'\").run();await Bun.write(Bun.stdout,d.serialize());d.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let back=restore(&import_sqlite_database(&output.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!(back.title.as_deref(),Some("independent playbook title 日本"));assert_eq!(back.flow.target.artifact_id,"independent target β");assert_eq!(back.flow.child_id,s.flow.child_id);assert_eq!(back.flow.target.dialect,s.flow.target.dialect);}
#[test]fn sqlite_snapshot_playbook_bad_owned_rows_and_bounded_cancellation(){let d=project(&fixture());for case in 0..5{let mut bad=d.clone();match case{0=>bad.table_mut("playbook_flow_child").unwrap().rows.clear(),1=>bad.table_mut("playbook_flow_child").unwrap().rows[0].values[0]=SqliteValue::Integer(2),2=>bad.table_mut("playbook_document").unwrap().rows[0].values[1]=SqliteValue::Blob(vec![0]),3=>bad.table_mut("playbook_document").unwrap().rows[0].values[4]=SqliteValue::Blob(vec![0]),_=>bad.table_mut("playbook_document").unwrap().sql=bad.table("playbook_document").unwrap().sql.replace("schema_id TEXT NOT NULL","schema_id TEXT")};assert!(restore(&bad).is_err());}assert!(fixture().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:16,..SqliteDatabaseLimits::default()})).is_err());assert!(PlaybookSnapshot::from_sqlite_database(&d,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());let mut large=fixture();large.title=Some("文".repeat(40000));assert!(large.encode_sqlite_snapshot_native(SnapshotEncoding::Text,&mut SqliteSnapshotControl::new(&mut|p|p.completed==0,SqliteDatabaseLimits::default())).is_err());}
#[test]fn sqlite_snapshot_playbook_owned_fields_and_title_presence(){for title in[None,Some(String::new())]{let mut s=fixture();s.title=title;let d=project(&s);assert_eq!(d.tables.len(),2);let back=restore(&import_sqlite_database(&export_sqlite_database(&d,SqliteDatabaseLimits::default(),&mut |_|true).unwrap(),SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!(back,s);assert_ne!(back.flow.child_id,back.flow.target.artifact_id);}}

#[test]fn sqlite_snapshot_playbook_exact_two_domain_rows_need_no_metadata_reservation(){let s=fixture();let d=s.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:2,..SqliteDatabaseLimits::default()})).unwrap();assert_eq!(d.tables.iter().map(|t|t.rows.len()).sum::<usize>(),2);assert_eq!(PlaybookSnapshot::from_sqlite_database(&d,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:2,..SqliteDatabaseLimits::default()})).unwrap(),s);}

#[test]
fn sqlite_snapshot_playbook_actual_declared_erased_encodings_and_coordinate_refusals(){
 let source=fixture();let codec=crate::standards::v1::subsets::any::io_declaration().native.codec;let provider=codec.snapshot_sqlite.unwrap();assert_eq!(provider.snapshot_type,Some(std::any::TypeId::of::<PlaybookSnapshot>()));let dialect=store::os_io::ArtifactDialect{artifact_kind:"s.playbook.playbook".into(),standard:"1".into(),subset:"*".into()};
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let payload=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<PlaybookSnapshot as store::ArtifactPack>::encode_pack(&source)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<PlaybookSnapshot as store::ArtifactDsl>::print_dsl(&source))};let database=(provider.export)(crate::PLAYBOOK_DOCUMENT_SCHEMA,&dialect,&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;assert_eq!(restore(&database).unwrap(),source);let bytes=export_sqlite_database(&database,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let imported=import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();assert_eq!((provider.import)(crate::PLAYBOOK_DOCUMENT_SCHEMA,&dialect,imported,encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value,payload);assert!((provider.import)(crate::PLAYBOOK_DOCUMENT_SCHEMA,&dialect,database,encoding,&mut SqliteSnapshotControl::new(&mut |p|p.phase!=SqliteSnapshotPhase::EncodeNative,SqliteDatabaseLimits::default())).is_err());}
 let database=project(&source);for(artifact_kind,standard,subset)in[("s.playbook.other","1","*"),("s.playbook.playbook","v1","*"),("s.playbook.playbook","1","other")]{let wrong=store::os_io::ArtifactDialect{artifact_kind:artifact_kind.into(),standard:standard.into(),subset:subset.into()};assert!(source.validate_sqlite_snapshot_subset(&wrong,&database,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err());}
}
#[semio_framework_async_macros::async_test]
async fn sqlite_snapshot_playbook_actual_declared_typed_io_and_final_metadata_rows(){
 use semio_framework_os_kernel::io::{register_native_snapshot_codec,io_mechanism::{io_export_sqlite_snapshot,io_import_sqlite_snapshot}};
 register_native_snapshot_codec(crate::PLAYBOOK_DIALECT,crate::standards::v1::subsets::any::io_declaration().native.codec).unwrap();let source=fixture();let dialect=store::os_io::ArtifactDialect{artifact_kind:"s.playbook.playbook".into(),standard:"1".into(),subset:"*".into()};
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let mut phases=Vec::new();let bytes=io_export_sqlite_snapshot(&dialect,&source,encoding,SqliteDatabaseLimits{max_rows:3,..SqliteDatabaseLimits::default()},&mut |p|{phases.push(p.phase);true}).await.unwrap().value;let database=import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();assert_eq!(database.tables.iter().map(|t|t.rows.len()).sum::<usize>(),3);let restored=io_import_sqlite_snapshot::<PlaybookSnapshot>(&dialect,&bytes,SqliteDatabaseLimits::default(),&mut |_|true).await.unwrap().value;assert_eq!(restored,source);assert!(!phases.iter().any(|p|matches!(p,SqliteSnapshotPhase::DecodeNative|SqliteSnapshotPhase::EncodeNative)));assert!(io_export_sqlite_snapshot(&dialect,&source,encoding,SqliteDatabaseLimits{max_rows:2,..SqliteDatabaseLimits::default()},&mut |_|true).await.is_err());}
}

#[test]
fn sqlite_snapshot_playbook_controlled_native_decode_honors_owned_fields_and_admission(){
 let source=fixture();for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let payload=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<PlaybookSnapshot as store::ArtifactPack>::encode_pack(&source)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<PlaybookSnapshot as store::ArtifactDsl>::print_dsl(&source))};let mut phases=Vec::new();let restored=PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |p|{phases.push(p.phase);true},SqliteDatabaseLimits::default())).unwrap();assert_eq!(restored,source);assert!(phases.contains(&SqliteSnapshotPhase::DecodeNative));restored.retire_sqlite_snapshot();assert!(PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:16,..SqliteDatabaseLimits::default()})).is_err());}
}

#[test]
fn sqlite_snapshot_playbook_canonical_json_controls_preserve_order_and_independent_values(){
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🎛️native-scenes.json")).unwrap();let text=serde_json::to_string(&fixture["steps"]).unwrap();let ordinary:Vec<crate::PlaybookStep>=semio_framework_pack_json::from_json_str(&text, semio_framework_pack_json::JsonMemberPolicy::Reject).unwrap();let mut accepted=|_|true;let mut decode=semio_framework_value::NativeDecodeControl::new(2_000_000,&mut accepted);let actual:Vec<crate::PlaybookStep>=semio_framework_pack_json::from_json_str_controlled(&text, semio_framework_pack_json::JsonMemberPolicy::Reject,&mut decode).unwrap();assert_eq!(actual,ordinary);
 let mut accepted=|_|true;let mut encode=semio_framework_value::NativeEncodeControl::new(2_000_000,&mut accepted);let written=semio_framework_pack_json::to_json_string_controlled(&actual,&mut encode).unwrap();assert_eq!(written,semio_framework_pack_json::to_json_string(&ordinary));assert_eq!(serde_json::from_str::<serde_json::Value>(&written).unwrap(),fixture["steps"]);
 let duplicate=fixture["duplicateKeyText"].as_str().unwrap();assert!(semio_framework_pack_json::from_json_str::<semio_framework_value::DslValue>(duplicate,semio_framework_pack_json::JsonMemberPolicy::Reject).is_err());let mut accepted=|_|true;let mut reject=semio_framework_value::NativeDecodeControl::new(2_000_000,&mut accepted);assert!(semio_framework_pack_json::from_json_str_controlled::<semio_framework_value::DslValue>(duplicate,semio_framework_pack_json::JsonMemberPolicy::Reject,&mut reject).is_err());let mut accepted=|_|true;let mut decode=semio_framework_value::NativeDecodeControl::new(2_000_000,&mut accepted);let actual:semio_framework_value::DslValue=semio_framework_pack_json::from_json_str_controlled(duplicate,semio_framework_pack_json::JsonMemberPolicy::Replace,&mut decode).unwrap();assert_eq!(actual,semio_framework_pack_json::from_json_str::<semio_framework_value::DslValue>(duplicate,semio_framework_pack_json::JsonMemberPolicy::Replace).unwrap());assert_eq!(serde_json::from_str::<serde_json::Value>(&semio_framework_pack_json::to_json_string(&actual)).unwrap(),serde_json::from_str::<serde_json::Value>(duplicate).unwrap());
 for text in fixture["invalidTexts"].as_array().unwrap(){let text=text.as_str().unwrap();assert!(serde_json::from_str::<serde_json::Value>(text).is_err());let mut accepted=|_|true;let mut decode=semio_framework_value::NativeDecodeControl::new(2_000_000,&mut accepted);assert!(semio_framework_pack_json::from_json_str_controlled::<semio_framework_value::DslValue>(text, semio_framework_pack_json::JsonMemberPolicy::Reject,&mut decode).is_err());}
 let mut accepted=|_|true;let mut decode=semio_framework_value::NativeDecodeControl::new(fixture["ownedByteLimit"].as_u64().unwrap() as usize,&mut accepted);assert!(semio_framework_pack_json::from_json_str_controlled::<Vec<crate::PlaybookStep>>(&text, semio_framework_pack_json::JsonMemberPolicy::Reject,&mut decode).is_err());let mut stopped=|_|false;let mut decode=semio_framework_value::NativeDecodeControl::new(2_000_000,&mut stopped);assert!(semio_framework_pack_json::from_json_str_controlled::<Vec<crate::PlaybookStep>>(&text, semio_framework_pack_json::JsonMemberPolicy::Reject,&mut decode).is_err());
}

#[test]
fn sqlite_snapshot_playbook_controlled_native_output_is_the_ordinary_pack_and_text(){
 let source=fixture();
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let expected=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<PlaybookSnapshot as store::ArtifactPack>::encode_pack(&source)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<PlaybookSnapshot as store::ArtifactDsl>::print_dsl(&source))};let length=match &expected{store::os_io::IoPayload::Binary(bytes)=>bytes.len(),store::os_io::IoPayload::Text(text)=>text.len()};let payload=source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:length,..SqliteDatabaseLimits::default()})).unwrap();assert_eq!(payload,expected);let decoded=PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert_eq!(decoded,source);decoded.retire_sqlite_snapshot();assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:length-1,..SqliteDatabaseLimits::default()})).is_err());assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:16,..SqliteDatabaseLimits::default()})).is_err());}
}

#[test]
fn sqlite_snapshot_playbook_canonical_block_options_follow_the_owned_value_schema(){
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🎛️native-scenes.json")).unwrap();let value:semio_framework_value::DslValue=semio_framework_pack_json::from_json_str(&serde_json::to_string(&fixture["steps"][0]["blocks"][0]["options"][0]).unwrap(), semio_framework_pack_json::JsonMemberPolicy::Reject).unwrap();let mut accepted=|_|true;let mut decode=semio_framework_value::NativeDecodeControl::new(200_000,&mut accepted);let decoded=<crate::playbook::PlaybookBlockOption as semio_framework_value::FromValue>::from_value_controlled(&value,&mut decode).unwrap();assert_eq!(decoded.value,"owned_β");assert_eq!(decoded.label,"Choice 日本");let mut accepted=|_|true;let mut encode=semio_framework_value::NativeEncodeControl::new(200_000,&mut accepted);let encoded=semio_framework_value::ToValue::to_value_controlled(&decoded,&mut encode).unwrap();assert_eq!(serde_json::from_str::<serde_json::Value>(&semio_framework_pack_json::to_json_string(&encoded)).unwrap(),fixture["steps"][0]["blocks"][0]["options"][0]);
}

#[test]
fn sqlite_snapshot_playbook_native_rows_and_schema_refuse_before_physical_ownership(){
 let source=fixture();let schema_bytes=PlaybookSnapshot::SQLITE_SCHEMA.len();
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let payload=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<PlaybookSnapshot as store::ArtifactPack>::encode_pack(&source)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<PlaybookSnapshot as store::ArtifactDsl>::print_dsl(&source))};let exact=SqliteDatabaseLimits{max_rows:2,max_schema_bytes:schema_bytes,..SqliteDatabaseLimits::default()};let decoded=PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap();assert_eq!(decoded,source);decoded.retire_sqlite_snapshot();assert_eq!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap(),payload);
  for limits in[SqliteDatabaseLimits{max_rows:1,..exact},SqliteDatabaseLimits{max_schema_bytes:schema_bytes-1,..exact}]{for phase in[SqliteSnapshotPhase::DecodeNative,SqliteSnapshotPhase::EncodeNative]{let mut constructed=false;let mut progress=|p:SqliteSnapshotProgress|{constructed|=p.phase==phase;true};let mut control=SqliteSnapshotControl::new(&mut progress,limits);let refused=match phase{SqliteSnapshotPhase::DecodeNative=>PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut control).is_err(),_=>source.encode_sqlite_snapshot_native(encoding,&mut control).is_err()};assert!(refused);assert!(!constructed);}}
 }
}

/// 📏️ Uses SQLite's actual UTF8 storage to demand every field at its exact native semantic ceiling.
#[test]
fn sqlite_snapshot_playbook_independent_exact_semantic_native_limits(){
 use std::{io::Write,process::{Command,Stdio}};
 let corpus:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let sources=[None,Some(String::new()),Some(corpus["editedTitle"].as_str().unwrap().into())].map(|title|{let mut source=fixture();source.title=title;source});
 for source in sources{
  let database=project(&source);
  let bytes=export_sqlite_database(&database,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();
  let mut child=Command::new("bun").arg("-e").arg("import{Database}from'bun:sqlite';const d=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()),{safeIntegers:true});try{if(d.query('PRAGMA integrity_check').get().integrity_check!=='ok'||d.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');const p=d.query('SELECT 8+length(CAST(schema_id AS BLOB))+length(CAST(authored_id AS BLOB))+length(CAST(version AS BLOB))+COALESCE(length(CAST(title AS BLOB)),0) AS bytes FROM playbook_document').get(),c=d.query('SELECT 8+length(CAST(child_id AS BLOB))+length(CAST(artifact_id AS BLOB))+length(CAST(artifact_kind AS BLOB))+length(CAST(standard AS BLOB))+length(CAST(subset AS BLOB)) AS bytes FROM playbook_flow_child').get();await Bun.write(Bun.stdout,String(Number(p.bytes+c.bytes)))}finally{d.close()}").stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let cells:String=String::from_utf8(output.stdout).unwrap();let cells:usize=cells.trim().parse().unwrap();
  let exact=SqliteDatabaseLimits{max_value_bytes:cells,..SqliteDatabaseLimits::default()};
  assert_eq!(source.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap(),database);
  assert_eq!(PlaybookSnapshot::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap(),source);
  for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{
   let payload=source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap();
   assert_eq!(PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap(),source);
   let refused=SqliteDatabaseLimits{max_value_bytes:cells-1,..exact};
   assert!(source.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,refused)).is_err());
   assert!(PlaybookSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,refused)).is_err());
  }
 }
}
