
use semio_framework_dsl_record::{ExprValue,FieldSpec,FieldValue,NativeSchemaControl,ParseOptions,RecordSpec,RecordSpecProducer,Shape,Wire,parse,parse_exact,parse_exact_controlled,parse_expr_text_controlled,print,print_expr};
use semio_framework_value::{DslValue};
use semio_framework_diagnostic::{Limits};
use semio_framework_dsl::{unit_by_symbol};
use semio_framework_diagnostic as diagnostic;
use semio_framework_os_kernel::native_decoding::*;
use semio_framework_dsl_record::*;
use semio_framework_os_kernel::os_dsl::*;
use semio_framework_os_kernel::PackEncodeOptions;
use semio_framework_os_kernel::PackDecodeOptions;
use semio_framework_os_kernel::pack_rt;
fn row_spec()->RecordSpec{RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(0,"label",Shape::Text),FieldSpec::new(1,"value",Shape::Float)])}
fn row_spec_controlled<C:NativeSchemaControl>(control:&mut C)->Result<RecordSpec,semio_framework_value::ValueError>{control.scoped_stage(|control|{control.begin_stage(2)?;let mut fields=control.allocate_vec(2)?;for(id,key,shape)in[(0,"label",Shape::Text),(1,"value",Shape::Float)]{fields.push(producer::field(id,key,shape,control)?);control.step()?;}producer::record(None,RecordLayout::Inline,fields,control)})}
fn row_producer()->RecordSpecProducer{RecordSpecProducer{ordinary:row_spec,decoding:|control|row_spec_controlled(control),encoding:|control|row_spec_controlled(control)}}
fn native_spec()->RecordSpec{RecordSpec::new(Some("controlled"),RecordLayout::Lines,vec![
    FieldSpec::new(0,"flag",Shape::Bool),FieldSpec::new(1,"signed",Shape::Int),FieldSpec::new(2,"unsigned",Shape::UInt),FieldSpec::new(3,"float",Shape::Float),FieldSpec::new(4,"text",Shape::Text),FieldSpec::new(5,"octets",Shape::Bytes64),FieldSpec::new(6,"tag",Shape::Enum(vec![("first".into(),0),("second".into(),1)])),FieldSpec::new(7,"count",Shape::Count),FieldSpec::new(8,"coord",Shape::Coord(3)),FieldSpec::new(9,"dir",Shape::Dir),FieldSpec::new(10,"dim",Shape::Dim(3)),FieldSpec::new(11,"range",Shape::Range),FieldSpec::new(12,"labels",Shape::List(Box::new(Shape::Text))),FieldSpec::new(13,"nested",Shape::Record(row_producer())),FieldSpec::new(14,"entries",Shape::Map(Box::new(Shape::Int))),FieldSpec::new(15,"dynamic",Shape::Value),FieldSpec::new(16,"formula",Shape::Expr),FieldSpec::new(17,"rows",Shape::Table(row_producer())),FieldSpec::new(18,"stress",Shape::Quantity(unit_by_symbol("GPa").unwrap())),FieldSpec::new(19,"embedded",Shape::Embed("text".into()))])}
fn evaluate(value:&ExprValue)->f64{match value{ExprValue::Num(value)=>*value,ExprValue::Neg(value)=>-evaluate(value),ExprValue::Binary(op,left,right)=>match op{ExprOp::Add=>evaluate(left)+evaluate(right),ExprOp::Sub=>evaluate(left)-evaluate(right),ExprOp::Mul=>evaluate(left)*evaluate(right),ExprOp::Div=>evaluate(left)/evaluate(right)},_=>panic!("numeric fixture")}}
#[test]
fn sqlite_snapshot_native_text_controls_schema_intrinsics(){
    use std::{io::Write,process::{Command,Stdio}};
    let fixture:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🛬️decoding/🔣️.json")).unwrap();let schema:serde_json::Value=serde_json::from_str(include_str!("../../🧬️schema/🛬️decoding/🔣️.json")).unwrap();let source=fixture["source"].as_str().unwrap();let mut accepted=|_:NativeDecodeProgress|true;let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let spec=native_spec();let record=parse_exact_controlled(source,&spec,&ParseOptions::default(),&mut control).unwrap();
    assert_eq!(record.get(0),Some(&FieldValue::Bool(true)));assert_eq!(record.get(1),Some(&FieldValue::Int(fixture["signed"].as_str().unwrap().parse().unwrap())));assert_eq!(record.get(2),Some(&FieldValue::UInt(fixture["unsigned"].as_str().unwrap().parse().unwrap())));let Some(FieldValue::Float(number))=record.get(3)else{panic!("Float")};assert_eq!(number.to_bits(),u64::from_str_radix(fixture["floatWord"].as_str().unwrap(),16).unwrap());assert_eq!(record.get(4),Some(&FieldValue::Text(fixture["text"].as_str().unwrap().into())));let octets:Vec<u8>=serde_json::from_value(fixture["octets"].clone()).unwrap();assert_eq!(record.get(5),Some(&FieldValue::Bytes64(octets.clone())));assert_eq!(record.get(6),Some(&FieldValue::Enum(1)));assert_eq!(record.get(7),record.get(2));let Some(FieldValue::Expr(formula))=record.get(16)else{panic!("Expr")};assert_eq!(evaluate(formula),fixture["formulaValue"].as_f64().unwrap());assert_eq!(record.get(18),Some(&FieldValue::Float(f64::INFINITY)));assert_eq!(record.get(19),Some(&FieldValue::Text("raw content".into())));
    for id in [8,9,10,11]{let Some(FieldValue::Tuple(values))=record.get(id)else{panic!("Tuple")};assert_eq!(values.len(),3);}let Some(FieldValue::List(rows))=record.get(17)else{panic!("Table")};assert_eq!(rows.len(),1);
    let native=print(&record,&spec,JoinMode::Document);let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let reconstructed=parse_exact_controlled(&native,&spec,&ParseOptions::default(),&mut control).unwrap();let options=PackEncodeOptions::default();assert_eq!(pack_rt::encode_record_body(&spec,&record,&options).unwrap(),pack_rt::encode_record_body(&spec,&reconstructed,&options).unwrap());
    let script="import{Database}from'bun:sqlite';import Ajv from'ajv/dist/2020.js';const x=JSON.parse(await Bun.stdin.text());if(!new Ajv({strict:true}).validate(x.schema,x.fixture))throw Error('fixture');const f=x.fixture,b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt('0x'+f.floatWord));const d=new Database(':memory:');d.run('CREATE TABLE literal(text TEXT,octets BLOB,word BLOB,integer TEXT,unsigned TEXT)');d.run('INSERT INTO literal VALUES(?,?,?,?,?)',f.text,new Uint8Array(f.octets),b,f.signed,f.unsigned);await Bun.write(Bun.stdout,JSON.stringify(d.query('SELECT text,hex(octets) AS octets,hex(word) AS word,integer,unsigned FROM literal').get()));d.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(serde_json::json!({"schema":schema,"fixture":fixture}).to_string().as_bytes()).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let row:serde_json::Value=serde_json::from_slice(&output.stdout).unwrap();assert_eq!(row["text"],fixture["text"]);assert_eq!(row["octets"],"00FF80");assert_eq!(row["word"],"010000000000F07F");assert_eq!(row["integer"],fixture["signed"]);assert_eq!(row["unsigned"],fixture["unsigned"]);
    for invalid in [r#"controlled float=nan64_zzzzzzzzzzzzzzzz"#,r#"controlled octets="AB==""#,r#"controlled text="bad\q""#,r#"controlled rows [] { row }"#]{let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert!(parse_exact_controlled(invalid,&spec,&ParseOptions::default(),&mut control).is_err());}
}

#[test]
fn sqlite_snapshot_native_text_controls_wire_ownership(){
    let fixture:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🛬️decoding/🔣️.json")).unwrap();let spec=RecordSpec::new(Some("edge"),RecordLayout::Inline,vec![FieldSpec::new(0,"link",Shape::Wire).positional(0)]);let mut accepted=|_:NativeDecodeProgress|true;
    for case in fixture["wires"].as_array().unwrap(){let source=case["source"].as_str().unwrap();let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let record=parse_exact_controlled(source,&spec,&ParseOptions::default(),&mut control).unwrap();let Some(FieldValue::Wire(wire))=record.get(0)else{panic!("Wire")};assert_eq!(wire.from.id,case["from"].as_str().unwrap());assert_eq!(wire.edge.as_ref().map(|(_,to)|to.id.as_str()),case["to"].as_str());assert_eq!(wire.edge.as_ref().map(|(directed,_)|*directed),case["directed"].as_bool());assert_eq!(wire.edge_label.id.as_deref(),case["labelId"].as_str());assert_eq!(wire.edge_label.kind.as_deref(),case["labelKind"].as_str());let native=print(&record,&spec,JoinMode::Document);let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert_eq!(parse_exact_controlled(&native,&spec,&ParseOptions::default(),&mut control).unwrap(),record);}
    let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let unordered=parse_exact_controlled(r#"edge a->b { title="🧬\u{0}field" raw=bytes64("AP+A") }"#,&spec,&ParseOptions::default(),&mut control).unwrap();let Some(FieldValue::Wire(wire))=unordered.get(0)else{panic!("Wire")};let DslValue::Object(properties)=&wire.properties else{panic!("properties")};assert_eq!(properties[0],("title".into(),DslValue::String(fixture["text"].as_str().unwrap().into())));assert_eq!(properties[1],("raw".into(),DslValue::Bytes(vec![0,255,128])));
    let source=format!("edge a -{}:Kind>b","label".repeat(32768));let mut interior=false;let mut cancelled=|event:NativeDecodeProgress|{if event.completed>=256&&event.completed<event.total{interior=true;false}else{true}};let mut control=NativeDecodeControl::new(1_000_000,&mut cancelled);assert!(parse_exact_controlled(&source,&spec,&ParseOptions::default(),&mut control).is_err());let admitted=control.owned_bytes();drop(control);assert!(interior);assert!(admitted<1024);
    let mut control=NativeDecodeControl::new(1,&mut accepted);assert!(parse_exact_controlled("edge large->target",&spec,&ParseOptions::default(),&mut control).is_err());for source in ["edge a -[]->b","edge a -:>b","edge a -[id] b"]{let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert!(parse_exact_controlled(source,&spec,&ParseOptions::default(),&mut control).is_err());}
}

#[test]
fn sqlite_snapshot_native_text_admits_quoted_semantic_keys(){
    use std::{io::Write,process::{Command,Stdio}};
    let keys:Vec<String>=serde_json::from_str(include_str!("../../🧫️fixtures/🛬️decoding/🔑️keys.json")).unwrap();let key_spec=RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(0,"value",Shape::Value),FieldSpec::new(1,"map",Shape::Map(Box::new(Shape::Int)))]);let mut accepted=|_:NativeDecodeProgress|true;
    for key in &keys{let mut expected=RecordValue::default();expected.fields.insert(0,FieldValue::Value(DslValue::Object(vec![(key.clone(),DslValue::Bool(true))])));expected.fields.insert(1,FieldValue::Map(vec![(key.clone(),FieldValue::Int(-1))]));let printed=print(&expected,&key_spec,JoinMode::Document);let mut control=NativeDecodeControl::new(65536,&mut accepted);assert_eq!(parse_exact_controlled(&printed,&key_spec,&ParseOptions::default(),&mut control).unwrap(),expected,"{key:?}");assert_eq!(parse_exact(&printed,&key_spec,&ParseOptions::default()).unwrap(),expected,"{key:?}");}
    let script="import{Database}from'bun:sqlite';const keys=JSON.parse(await Bun.stdin.text()),db=new Database(':memory:');db.run('CREATE TABLE identity(id INTEGER PRIMARY KEY,key TEXT)');keys.forEach((key,index)=>db.run('INSERT INTO identity VALUES(?,?)',index+1,key));await Bun.write(Bun.stdout,JSON.stringify(db.query('SELECT key FROM identity ORDER BY id').all().map(row=>row.key)));db.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(serde_json::to_string(&keys).unwrap().as_bytes()).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));assert_eq!(serde_json::from_slice::<Vec<String>>(&output.stdout).unwrap(),keys);

    let spec=RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(0,"value",Shape::Value),FieldSpec::new(1,"map",Shape::Map(Box::new(Shape::Int)))]);let mut accepted=|_:NativeDecodeProgress|true;let mut control=NativeDecodeControl::new(65536,&mut accepted);let record=parse_exact_controlled(r#"value={"🧬\u{0}key"=true second=bytes64("AP+A")} map={"🧬\u{0}key"=-1 plain=2}"#,&spec,&ParseOptions::default(),&mut control).unwrap();let Some(FieldValue::Value(DslValue::Object(entries)))=record.get(0)else{panic!("Object")};assert_eq!(entries[0],("🧬\0key".into(),DslValue::Bool(true)));assert_eq!(entries[1],("second".into(),DslValue::Bytes(vec![0,255,128])));let Some(FieldValue::Map(entries))=record.get(1)else{panic!("Map")};assert_eq!(entries[0],("🧬\0key".into(),FieldValue::Int(-1)));assert_eq!(entries[1],("plain".into(),FieldValue::Int(2)));
}

#[test]
fn sqlite_snapshot_native_pack_controls_expression_materialization(){
    let fixture:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🛬️decoding/🔣️.json")).unwrap();let spec=RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(0,"formula",Shape::Expr)]);let mut accepted=|_:NativeDecodeProgress|true;let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let full=parse_exact_controlled(fixture["source"].as_str().unwrap(),&native_spec(),&ParseOptions::default(),&mut control).unwrap();let mut expected=RecordValue::default();expected.fields.insert(0,full.get(16).unwrap().clone());let options=PackEncodeOptions::default();let encoded=pack_rt::encode_document(&spec,&expected,&options).unwrap();let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let(decoded,_)=pack_rt::decode_document_controlled(&encoded,&spec,&PackDecodeOptions::default(),&mut control).unwrap();let Some(FieldValue::Expr(value))=decoded.get(0)else{panic!("Expr")};assert_eq!(evaluate(value),fixture["formulaValue"].as_f64().unwrap());assert_eq!(pack_rt::encode_record_body(&spec,&decoded,&options).unwrap(),pack_rt::encode_record_body(&spec,&expected,&options).unwrap());
    let mut wide=RecordValue::default();wide.fields.insert(0,FieldValue::Expr(ExprValue::Call("sum".into(),vec![ExprValue::Num(1.0);3000])));let mut uncompressed=options.clone();uncompressed.codec=semio_framework_os_kernel::CodecId(0);let encoded=pack_rt::encode_document(&spec,&wide,&uncompressed).unwrap();let mut decode=PackDecodeOptions::default();decode.limits.max_total_alloc=100_000;let Some(FieldValue::Expr(expression))=wide.get(0)else{panic!("Expr")};let expression_bytes=print_expr(expression).len();let mut expression_interior=false;let mut bounded=|event:NativeDecodeProgress|{if event.total==expression_bytes&&event.completed>=256&&event.completed<event.total{expression_interior=true;}true};let mut control=NativeDecodeControl::new(1_000_000,&mut bounded);assert!(pack_rt::decode_document_controlled(&encoded,&spec,&decode,&mut control).is_err());assert!(control.owned_bytes()<=100_000);assert_eq!(control.maximum_bytes(),1_000_000);drop(control);assert!(expression_interior);
    let mut events=Vec::new();let mut canceled=|event:NativeDecodeProgress|{events.push(event);event.completed<256||event.total<=256};let mut control=NativeDecodeControl::new(1_000_000,&mut canceled);assert!(parse_expr_text_controlled(&format!("sum({})",vec!["1";3000].join(",")),&diagnostic::Limits::default(),&mut control).is_err());assert!(events.iter().any(|event|event.completed>=256&&event.completed<event.total));

}

fn optional_list_row_spec()->RecordSpec{RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(1,"min",Shape::Float).optional(),FieldSpec::new(2,"max",Shape::Float).optional(),FieldSpec::new(3,"label",Shape::Text).optional(),FieldSpec::new(4,"children",Shape::List(Box::new(Shape::Record(optional_list_row_producer())))).optional()])}
fn optional_list_row_spec_controlled<C:NativeSchemaControl>(control:&mut C)->Result<RecordSpec,semio_framework_value::ValueError>{control.scoped_stage(|control|{control.begin_stage(4)?;let mut fields=control.allocate_vec(4)?;let children=Shape::List(producer::boxed(Shape::Record(optional_list_row_producer()),control)?);for(id,key,shape)in[(1,"min",Shape::Float),(2,"max",Shape::Float),(3,"label",Shape::Text),(4,"children",children)]{fields.push(producer::field(id,key,shape,control)?.optional());control.step()?;}producer::record(None,RecordLayout::Inline,fields,control)})}
fn optional_list_row_producer()->RecordSpecProducer{RecordSpecProducer{ordinary:optional_list_row_spec,decoding:|control|optional_list_row_spec_controlled(control),encoding:|control|optional_list_row_spec_controlled(control)}}
fn optional_list_rows_json(rows:&[FieldValue])->serde_json::Value{serde_json::Value::Array(rows.iter().map(|value|{let FieldValue::Record(row)=value else{panic!("record")};let mut out=serde_json::Map::new();for(id,key)in[(1,"min"),(2,"max"),(3,"label"),(4,"children")]{match row.get(id){Some(FieldValue::Float(value))=>{out.insert(key.into(),serde_json::json!(value));},Some(FieldValue::Text(value))=>{out.insert(key.into(),value.clone().into());},Some(FieldValue::List(value))=>{out.insert(key.into(),optional_list_rows_json(value));},Some(FieldValue::Absent)|None=>{},other=>panic!("unexpected {other:?}")}}out.into()}).collect())}
#[test]
fn sqlite_snapshot_native_text_controls_record_list_boundaries(){
    let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧾️record-list/🧫️fixtures/🔣️.json")).unwrap();let spec=RecordSpec::new(None,RecordLayout::Inline,vec![FieldSpec::new(1,"items",Shape::List(Box::new(Shape::Record(optional_list_row_producer()))))]);let mut accepted=|_:NativeDecodeProgress|true;
    for case in fixture["cases"].as_array().unwrap(){let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);let record=parse_exact_controlled(case["source"].as_str().unwrap(),&spec,&ParseOptions::default(),&mut control).unwrap_or_else(|error|panic!("{}: {error}",case["id"]));let Some(FieldValue::List(rows))=record.get(1)else{panic!("list")};assert_eq!(optional_list_rows_json(rows),case["rows"],"{}",case["id"]);let printed=print(&record,&spec,JoinMode::Document);let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert_eq!(parse_exact_controlled(&printed,&spec,&ParseOptions::default(),&mut control).unwrap(),record);}
    for source in fixture["invalid"].as_array().unwrap(){let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert!(parse_exact_controlled(source.as_str().unwrap(),&spec,&ParseOptions::default(),&mut control).is_err(),"{source}");}
    let source=format!("items=[ {} ]",vec!["{ }";4096].join(" "));let mut interior=false;let mut canceled=|event:NativeDecodeProgress|{if event.completed>=256&&event.completed<event.total{interior=true;false}else{true}};let mut control=NativeDecodeControl::new(1_000_000,&mut canceled);assert!(parse_exact_controlled(&source,&spec,&ParseOptions::default(),&mut control).is_err());drop(control);assert!(interior);
    let mut control=NativeDecodeControl::new(1,&mut accepted);assert!(parse_exact_controlled("items=[ { } ]",&spec,&ParseOptions::default(),&mut control).is_err());
    let deep=format!("items=[ {}{{ }}{} ]","{ children=[ ".repeat(128)," ] }".repeat(128));let mut control=NativeDecodeControl::new(1_000_000,&mut accepted);assert!(parse_exact_controlled(&deep,&spec,&ParseOptions::default(),&mut control).is_err());
}
