//! 🗣️ BIM editor terminology: the one `app_labels!` block for the whole app (never split per window or panel), so every locale cell is compile-checked
//! in one place. No language is the default: the locale always comes from the addressed view model. `{name}` and `{count}` are named placeholders.

macro_rules! bim_labels {
    ($( $field:ident: $en:literal, $de:literal; )+) => {
        semio_framework_ui_locale::app_labels! {
            pub struct BimLabels {
                $( $field: native_en $en, native_de $de, reuse_en $en, reuse_de $de );+
            }
        }
    };
}

//#region 🔖️Labels
// 🗣️ A plain `//` comment: rustdoc does not document macro invocations.
bim_labels! {
    window_plan: "Plan", "Grundriss";
    window_world: "3D", "3D";
    window_section: "Section", "Schnitt";
    window_schedule: "Schedule", "Mengen";
    panel_outliner: "Outliner", "Struktur";
    panel_properties: "Properties", "Eigenschaften";
    panel_library: "Library", "Bibliothek";
    mode_edit: "Edit", "Bearbeiten";

    kind_site: "Site", "Grundstück";
    kind_building: "Building", "Gebäude";
    kind_storey: "Storey", "Geschoss";
    kind_grid: "Grid line", "Rasterlinie";
    kind_wall: "Wall", "Wand";
    kind_curtain_wall: "Curtain wall", "Vorhangfassade";
    kind_column: "Column", "Stütze";
    kind_beam: "Beam", "Träger";
    kind_slab: "Slab", "Decke";
    kind_roof: "Roof", "Dach";
    kind_opening: "Opening", "Öffnung";
    kind_stair: "Stair", "Treppe";
    kind_railing: "Railing", "Geländer";
    kind_ramp: "Ramp", "Rampe";
    kind_space: "Space", "Raum";
    kind_material: "Material", "Material";
    kind_wall_type: "Wall type", "Wandtyp";
    kind_slab_type: "Slab type", "Deckentyp";
    kind_ceiling: "Ceiling", "Unterdecke";
    kind_ceiling_type: "Ceiling type", "Unterdeckentyp";
    kind_roof_type: "Roof type", "Dachtyp";
    kind_column_type: "Column type", "Stützentyp";
    kind_beam_type: "Beam type", "Trägertyp";
    kind_window_type: "Window type", "Fenstertyp";
    kind_door_type: "Door type", "Türtyp";
    kind_zone: "Zone", "Zone";
    kind_area_scheme: "Area scheme", "Flächenschema";
    kind_view: "View", "Ansicht";
    kind_dimension: "Dimension", "Bemaßung";
    kind_tag: "Tag", "Kennzeichnung";
    kind_text_note: "Text note", "Textnotiz";
    kind_leader: "Leader", "Hinweislinie";
    kind_annotation_style: "Annotation style", "Beschriftungsstil";

    group_sites: "Sites", "Grundstücke";
    group_buildings: "Buildings", "Gebäude";
    group_storeys: "Storeys", "Geschosse";
    group_grids: "Grid lines", "Rasterlinien";
    group_walls: "Walls", "Wände";
    group_curtain_walls: "Curtain walls", "Vorhangfassaden";
    group_columns: "Columns", "Stützen";
    group_beams: "Beams", "Träger";
    group_slabs: "Slabs", "Decken";
    group_ceilings: "Ceilings", "Unterdecken";
    group_roofs: "Roofs", "Dächer";
    group_openings: "Openings", "Öffnungen";
    group_stairs: "Stairs", "Treppen";
    group_railings: "Railings", "Geländer";
    group_ramps: "Ramps", "Rampen";
    group_spaces: "Spaces", "Räume";
    group_zones: "Zones", "Zonen";
    group_area_schemes: "Area schemes", "Flächenschemata";
    group_materials: "Materials", "Materialien";
    group_wall_types: "Wall types", "Wandtypen";
    group_slab_types: "Slab types", "Deckentypen";
    group_ceiling_types: "Ceiling types", "Unterdeckentypen";
    group_roof_types: "Roof types", "Dachtypen";
    group_column_types: "Column types", "Stützentypen";
    group_beam_types: "Beam types", "Trägertypen";
    group_window_types: "Window types", "Fenstertypen";
    group_door_types: "Door types", "Türtypen";
    group_views: "Views", "Ansichten";
    group_dimensions: "Dimensions", "Bemaßungen";
    group_tags: "Tags", "Kennzeichnungen";
    group_text_notes: "Text notes", "Textnotizen";
    group_leaders: "Leaders", "Hinweislinien";
    group_annotation_styles: "Annotation styles", "Beschriftungsstile";
    group_view_plans: "Plans", "Grundrisse";
    group_view_ceiling_plans: "Ceiling plans", "Deckenspiegel";
    group_view_sections: "Sections", "Schnitte";
    group_view_elevations: "Elevations", "Fassaden";
    group_view_cameras: "3D views", "3D-Ansichten";

    field_name: "Name", "Name";
    field_site: "Site", "Grundstück";
    field_building: "Building", "Gebäude";
    field_storey: "Storey", "Geschoss";
    field_host: "Host", "Träger-Bauteil";
    field_wall_type: "Wall type", "Wandtyp";
    field_slab_type: "Slab type", "Deckentyp";
    field_ceiling_type: "Ceiling type", "Unterdeckentyp";
    field_drop: "Drop below storey top", "Abhängung unter Geschossoberkante";
    field_slope: "Slope (fall direction, angle)", "Neigung (Fallrichtung, Winkel)";
    field_roof_type: "Roof type", "Dachtyp";
    field_column_type: "Column type", "Stützentyp";
    field_beam_type: "Beam type", "Trägertyp";
    field_material: "Material", "Material";
    field_category: "Category", "Kategorie";
    field_level: "Level", "Ebene";
    field_height: "Height", "Höhe";
    field_width: "Width", "Breite";
    field_depth: "Depth", "Tiefe";
    field_thickness: "Thickness", "Dicke";
    field_length: "Length", "Länge";
    field_offset: "Offset", "Versatz";
    field_sill: "Sill", "Brüstung";
    field_cut_height: "Plan cut height", "Schnitthöhe im Grundriss";
    field_stringer: "Stringer", "Wangen";
    field_nosing: "Nosing", "Trittüberstand";
    field_tread_thickness: "Tread thickness", "Trittstärke";
    field_riser: "Risers", "Setzstufen";
    field_landing_depth: "Landing depth", "Podesttiefe";
    field_rail_profile: "Top rail section", "Handlaufprofil";
    field_post_profile: "Post section", "Pfostenprofil";
    field_baluster: "Balusters", "Stäbe";
    field_infill: "Infill", "Füllung";
    field_elevation: "Elevation", "Höhenlage";
    field_top_elevation: "Top elevation", "Oberkante";
    field_base_offset: "Base offset", "Fußversatz";
    field_top: "Top", "Kopfbindung";
    field_location: "Location line", "Bezugslinie";
    field_phase: "Phase", "Phase";
    phase_existing: "Existing", "Bestand";
    phase_new: "New", "Neubau";
    phase_demolished: "Demolished", "Abbruch";
    phase_temporary: "Temporary", "Temporär";
    phase_all: "All phases", "Alle Phasen";
    field_view_phase: "View phase", "Ansichtsphase";
    field_start_join: "Start join", "Anfangsverbindung";
    field_end_join: "End join", "Endverbindung";
    field_axis: "Axis", "Achse";
    field_start: "Start", "Anfang";
    field_end: "End", "Ende";
    field_position: "Position", "Position";
    field_origin: "Origin", "Ursprung";
    field_rotation: "Rotation", "Drehung";
    field_latitude: "Latitude", "Breitengrad";
    field_longitude: "Longitude", "Längengrad";
    field_true_north: "True north", "Nordrichtung";
    field_label: "Label", "Bezeichnung";
    field_number: "Number", "Nummer";
    field_usage: "Usage", "Nutzung";
    field_zone: "Zone", "Zone";
    field_floor_finish: "Floor finish", "Bodenbelag";
    field_wall_finish: "Wall finish", "Wandbelag";
    field_ceiling_finish: "Ceiling finish", "Deckenbelag";
    field_occupancy_density: "Occupancy (persons/m²)", "Belegung (Personen/m²)";
    field_measure: "Area measure", "Flächenart";
    field_usages: "Counted usages (comma separated, empty = all)", "Gezählte Nutzungen (kommagetrennt, leer = alle)";
    field_zones: "Counted zones (comma separated ids or names, empty = all)", "Gezählte Zonen (kommagetrennte Ids oder Namen, leer = alle)";
    field_available_usages: "Usages in the model", "Nutzungen im Modell";
    field_available_zones: "Zones in the model", "Zonen im Modell";
    choice_none: "None", "Keine";
    choice_gross: "Gross", "Brutto";
    choice_net: "Net", "Netto";
    choice_name: "Name", "Name";
    choice_type: "Type", "Typ";
    choice_number: "Number", "Nummer";
    choice_size: "Size", "Größe";
    choice_tick: "Tick", "Schrägstrich";
    choice_arrow: "Arrow", "Pfeil";
    choice_dot: "Dot", "Punkt";
    choice_metre: "Metres", "Meter";
    choice_centimetre: "Centimetres", "Zentimeter";
    choice_millimetre: "Millimetres", "Millimeter";
    field_kind: "Kind", "Art";
    field_plane: "Plane", "Schnittebene";
    field_camera: "Camera", "Kamera";
    field_crop: "Crop", "Zuschnitt";
    field_hidden: "Hidden categories", "Ausgeblendet";
    field_scale: "Scale 1:n", "Massstab 1:n";
    field_detail: "Detail level", "Detailgrad";
    field_view_depth: "View depth", "Sichttiefe";
    field_overhang: "Overhang", "Überstand";
    field_shape: "Shape", "Form";
    field_flight: "Flight", "Lauf";
    field_post_spacing: "Post spacing", "Pfostenabstand";
    field_path: "Path", "Verlauf";
    field_landing_start: "Foot landing (m)", "Antrittspodest (m)";
    field_landing_end: "Head landing (m)", "Austrittspodest (m)";
    field_landing_turn: "Turn landing (m)", "Wendepodest (m)";
    field_max_slope: "Slope limit (rise per run)", "Neigungsgrenze (Höhe je Länge)";
    field_rail_left: "Railing left", "Geländer links";
    field_rail_right: "Railing right", "Geländer rechts";
    field_host_side: "Host side", "Trägerseite";
    field_host_edge: "Host edge", "Trägerkante";
    field_host_inset: "Host inset (m)", "Trägerabstand (m)";
    field_rise: "Rise", "Höhenunterschied";
    field_run_length: "Sloped run", "Neigungsstrecke";
    field_ramp_slope: "Slope (%)", "Neigung (%)";
    field_landings: "Landings", "Podeste";
    field_compliant: "Complies with its limit", "Hält den Grenzwert ein";
    choice_left: "Left", "Links";
    choice_right: "Right", "Rechts";
    field_density: "Density", "Dichte";
    field_layers: "Layers", "Schichten";
    field_panes: "Panes", "Scheiben";
    field_flip_hand: "Flip hand", "Anschlag spiegeln";
    field_flip_facing: "Flip facing", "Seite spiegeln";
    field_panel_material: "Panel material", "Füllungsmaterial";
    field_mullion_material: "Mullion material", "Pfostenmaterial";
    field_max_riser: "Max riser", "Max. Steigung";
    field_min_tread: "Min tread", "Min. Auftritt";
    field_conductivity: "Conductivity", "Leitfähigkeit";
    field_specific_heat: "Specific heat", "Wärmekapazität";
    field_frame_width: "Frame width", "Rahmenbreite";
    field_frame_depth: "Frame depth", "Rahmentiefe";
    field_leaves: "Leaves", "Flügel";
    field_swing: "Swing", "Aufschlag";
    field_area: "Area", "Fläche";
    field_volume: "Volume", "Volumen";
    field_spaces: "Spaces", "Räume";
    field_resolved: "Resolved spaces", "Erfasste Räume";
    field_net_area: "Net floor area", "Nettogrundfläche";
    field_occupancy: "Occupancy (persons)", "Belegung (Personen)";
    field_floor_finish_area: "Floor finish area", "Bodenbelagsfläche";
    field_wall_finish_area: "Wall finish area", "Wandbelagsfläche";
    field_ceiling_finish_area: "Ceiling finish area", "Deckenbelagsfläche";
    field_mass: "Mass", "Masse";
    field_count: "Count", "Anzahl";
    field_type: "Type", "Typ";
    field_mixed: "Mixed", "Gemischt";
    section_authored: "Authored", "Eingegeben";
    section_inferred: "Inferred", "Abgeleitet";
    section_summary: "Summary", "Übersicht";

    action_add_named: "Add {name}", "{name} hinzufügen";
    action_delete: "Delete", "Löschen";
    action_delete_selection: "Delete selection", "Auswahl löschen";
    action_rename: "Rename", "Umbenennen";
    action_select_all: "Select all", "Alles auswählen";
    action_clear_selection: "Clear selection", "Auswahl aufheben";
    action_show_all_storeys: "All storeys", "Alle Geschosse";
    action_isolate_storey: "Isolate storey", "Geschoss isolieren";

    measure_storey: "Storey", "Geschoss";
    measure_cut_height: "Cut height", "Schnitthöhe";
    measure_projection: "Projection", "Projektion";
    measure_isolate: "Isolate storey", "Geschoss isolieren";
    measure_section_enabled: "Section plane", "Schnittebene";
    measure_section_axis: "Axis", "Achse";
    measure_section_offset: "Offset", "Versatz";
    measure_section_depth: "Depth", "Tiefe";
    measure_view: "View", "Ansicht";
    measure_all_storeys: "All storeys", "Alle Geschosse";
    measure_view_phase: "Phase filter", "Phasenfilter";

    projection_three_point: "Perspective", "Perspektive";
    projection_orthographic: "Orthographic", "Orthografisch";
    projection_axonometric: "Axonometric", "Axonometrie";
    projection_one_point: "One point", "Ein Fluchtpunkt";
    projection_two_point: "Two point", "Zwei Fluchtpunkte";

    column_name: "Name", "Name";
    column_type: "Type", "Typ";
    column_storey: "Storey", "Geschoss";
    column_count: "Count", "Anzahl";
    column_length: "Length", "Länge";
    column_area: "Area", "Fläche";
    column_volume: "Volume", "Volumen";
    column_height: "Height", "Höhe";
    column_mass: "Mass", "Masse";
    row_total: "Total", "Summe";

    status_elements: "{count} elements", "{count} Elemente";
    status_selected: "{count} selected", "{count} ausgewählt";
    status_storey: "Storey {name}", "Geschoss {name}";
    status_all_storeys: "All storeys", "Alle Geschosse";
    status_no_storey: "No storey", "Kein Geschoss";

    empty_outliner: "The model is empty", "Das Modell ist leer";
    empty_properties: "Nothing selected", "Nichts ausgewählt";
    empty_library: "The library is empty", "Die Bibliothek ist leer";
    empty_schedule: "No quantities yet", "Noch keine Mengen";
    empty_plan: "No plan view to show", "Kein Grundriss anzuzeigen";
    empty_section: "No section or elevation to show", "Kein Schnitt und keine Fassade anzuzeigen";
    status_view: "View {name}", "Ansicht {name}";

    progress_inference: "Inferring the model", "Modell wird abgeleitet";
    cancel_inference: "Cancel", "Abbrechen";
    unknown_body: "Unknown body", "Unbekannter Bereich";
    summary_project: "Project", "Projekt";
    summary_schema: "Schema", "Schema";

    cmd_create_entity: "Create Entity", "Bauteil anlegen";
    cmd_create_entity_describe: "Creates one entity of the given kind (site, building, storey, wall ...) in the given container, or in the selected or first container, and selects it.", "Legt ein Bauteil der angegebenen Art im angegebenen, im ausgewählten oder im ersten passenden Container an und wählt es aus.";
    cmd_create_view: "Create View", "Ansicht anlegen";
    cmd_create_view_describe: "Creates a view of the building: the plan or ceiling plan of a storey, a section, an elevation, the four elevations at once (kind elevations) or an orthographic or perspective camera, and binds the addressed window to it.", "Legt eine Ansicht des Gebäudes an: den Grundriss oder Deckenspiegel eines Geschosses, einen Schnitt, eine Fassade, die vier Fassaden auf einmal (Art elevations) oder eine orthografische oder perspektivische Kamera, und bindet das adressierte Fenster daran.";
    name_south: "South", "Süd";
    name_east: "East", "Ost";
    name_north: "North", "Nord";
    name_west: "West", "West";
    name_section: "Section", "Schnitt";
    name_ceiling_plan: "Ceiling plan", "Deckenspiegel";
    name_elevation: "Elevation", "Fassade";
    name_elevations: "All four elevations", "Alle vier Fassaden";
    name_camera: "3D view", "3D-Ansicht";
    view_plan_of: "Plan {name}", "Grundriss {name}";
    view_ceiling_of: "Ceiling plan {name}", "Deckenspiegel {name}";
    cmd_delete_selection: "Delete Selection", "Auswahl löschen";
    cmd_delete_selection_describe: "Deletes the given entities, or the current selection, children before parents, in one undoable step.", "Löscht die angegebenen Bauteile oder die aktuelle Auswahl, Kinder vor Eltern, in einem rückgängig machbaren Schritt.";
    cmd_rename_entity: "Rename Entity", "Bauteil umbenennen";
    cmd_rename_entity_describe: "Gives one entity a new name.", "Gibt einem Bauteil einen neuen Namen.";
    cmd_set_field: "Set Field", "Parameter festlegen";
    cmd_set_field_describe: "Sets one authored parameter (name, level, height ...) of the given entities, or of the selection, to the given value.", "Setzt einen Parameter (Name, Ebene, Höhe ...) der angegebenen Bauteile oder der Auswahl auf den angegebenen Wert.";
    cmd_set_view: "Set View", "Ansicht festlegen";
    cmd_set_view_describe: "Sets one view parameter of the addressed window (the authored view it shows, projection, isolated storey, section plane); the document does not change.", "Setzt einen Ansichtsparameter des adressierten Fensters (die gezeigte Ansicht, Projektion, isoliertes Geschoss, Schnittebene); das Dokument ändert sich nicht.";
    cmd_set_camera: "Set Camera", "Kamera festlegen";
    cmd_set_camera_describe: "Stores the navigation pose of the addressed window.", "Speichert die Navigationspose des adressierten Fensters.";
    cmd_canvas_pointer_down: "Canvas Pointer Down", "Leinwand-Zeiger gedrückt";
    cmd_canvas_pointer_down_describe: "A press in a plan or section window: it belongs to the armed utility (select picks, wall sets a point, window places ...).", "Ein Druck in einem Grundriss- oder Schnittfenster: er gehört zum aktiven Werkzeug (Auswahl wählt, Wand setzt einen Punkt, Fenster platziert ...).";
    cmd_canvas_pointer_move: "Canvas Pointer Move", "Leinwand-Zeiger bewegt";
    cmd_canvas_pointer_move_describe: "The pointer moved over a plan or section window: the armed utility's gesture advances and shows its preview.", "Der Zeiger bewegte sich über einem Grundriss- oder Schnittfenster: die Geste des aktiven Werkzeugs schreitet fort und zeigt ihre Vorschau.";
    cmd_canvas_pointer_up: "Canvas Pointer Up", "Leinwand-Zeiger losgelassen";
    cmd_canvas_pointer_up_describe: "A release in a plan or section window: a drag commits (marquee, handle, sliding opening, rectangle).", "Ein Loslassen in einem Grundriss- oder Schnittfenster: ein Ziehen wird abgeschlossen (Auswahlrahmen, Griff, gleitende Öffnung, Rechteck).";
    cmd_canvas_double_click: "Canvas Double Click", "Leinwand-Doppelklick";
    cmd_canvas_double_click_describe: "A double click finishes the gesture in progress (wall chain, railing, slab or roof polygon).", "Ein Doppelklick beendet die laufende Geste (Wandzug, Geländer, Decken- oder Dachpolygon).";
    cmd_canvas_commit_draft: "Finish Drawing", "Zeichnen beenden";
    cmd_canvas_commit_draft_describe: "Finishes the gesture in progress: a wall chain ends, a railing, slab or roof polygon is written.", "Beendet die laufende Geste: ein Wandzug endet, ein Geländer-, Decken- oder Dachpolygon wird geschrieben.";
    cmd_canvas_escape: "Cancel Drawing", "Zeichnen abbrechen";
    cmd_canvas_escape_describe: "Cancels the gesture in progress without a trace; what was already written stays.", "Bricht die laufende Geste spurlos ab; bereits Geschriebenes bleibt.";
    cmd_world_pointer_down: "World Pointer Down", "Welt-Zeiger gedrückt";
    cmd_world_pointer_down_describe: "A press in the 3D window while a drawing utility is armed: the ground point is the click of the click-click tools.", "Ein Druck im 3D-Fenster bei aktivem Zeichenwerkzeug: der Bodenpunkt ist der Klick der Klick-Klick-Werkzeuge.";
    cmd_world_pointer_move: "World Pointer Move", "Welt-Zeiger bewegt";
    cmd_world_pointer_move_describe: "The ground point under the pointer in the 3D window while a drawing utility is armed.", "Der Bodenpunkt unter dem Zeiger im 3D-Fenster bei aktivem Zeichenwerkzeug.";
    cmd_arm_select: "Select Tool", "Auswahlwerkzeug";
    cmd_arm_select_describe: "Arms the select utility in the addressed window (V).", "Aktiviert das Auswahlwerkzeug im adressierten Fenster (V).";
    cmd_arm_wall: "Wall Tool", "Wandwerkzeug";
    cmd_arm_wall_describe: "Arms the wall utility in the addressed window (W).", "Aktiviert das Wandwerkzeug im adressierten Fenster (W).";
    cmd_arm_wall_arc: "Arc Wall Tool", "Bogenwand-Werkzeug";
    cmd_arm_wall_arc_describe: "Arms the arc wall utility in the addressed window (A).", "Aktiviert das Bogenwand-Werkzeug im adressierten Fenster (A).";
    cmd_arm_curtain_wall: "Curtain Wall Tool", "Vorhangfassaden-Werkzeug";
    cmd_arm_curtain_wall_describe: "Arms the curtain wall utility in the addressed window (U).", "Aktiviert das Vorhangfassaden-Werkzeug im adressierten Fenster (U).";
    cmd_arm_column: "Column Tool", "Stützenwerkzeug";
    cmd_arm_column_describe: "Arms the column utility in the addressed window (C).", "Aktiviert das Stützenwerkzeug im adressierten Fenster (C).";
    cmd_arm_beam: "Beam Tool", "Trägerwerkzeug";
    cmd_arm_beam_describe: "Arms the beam utility in the addressed window (B).", "Aktiviert das Trägerwerkzeug im adressierten Fenster (B).";
    cmd_arm_slab: "Slab Tool", "Deckenwerkzeug";
    cmd_arm_slab_describe: "Arms the slab utility in the addressed window (S).", "Aktiviert das Deckenwerkzeug im adressierten Fenster (S).";
    cmd_arm_roof: "Roof Tool", "Dachwerkzeug";
    cmd_arm_roof_describe: "Arms the roof utility in the addressed window (R).", "Aktiviert das Dachwerkzeug im adressierten Fenster (R).";
    cmd_arm_window: "Window Tool", "Fensterwerkzeug";
    cmd_arm_window_describe: "Arms the window utility in the addressed window (N).", "Aktiviert das Fensterwerkzeug im adressierten Fenster (N).";
    cmd_arm_door: "Door Tool", "Türwerkzeug";
    cmd_arm_door_describe: "Arms the door utility in the addressed window (D).", "Aktiviert das Türwerkzeug im adressierten Fenster (D).";
    cmd_arm_opening: "Opening Tool", "Öffnungswerkzeug";
    cmd_arm_opening_describe: "Arms the opening utility in the addressed window (O).", "Aktiviert das Öffnungswerkzeug im adressierten Fenster (O).";
    cmd_arm_stair: "Stair Tool", "Treppenwerkzeug";
    cmd_arm_stair_describe: "Arms the stair utility in the addressed window (T).", "Aktiviert das Treppenwerkzeug im adressierten Fenster (T).";
    cmd_arm_railing: "Railing Tool", "Geländerwerkzeug";
    cmd_arm_railing_describe: "Arms the railing utility in the addressed window (L).", "Aktiviert das Geländerwerkzeug im adressierten Fenster (L).";
    cmd_arm_ramp: "Ramp Tool", "Rampenwerkzeug";
    cmd_arm_ramp_describe: "Arms the ramp utility in the addressed window (Shift+T).", "Aktiviert das Rampenwerkzeug im adressierten Fenster (Shift+T).";
    cmd_arm_space: "Space Tool", "Raumwerkzeug";
    cmd_arm_space_describe: "Arms the space utility in the addressed window (P).", "Aktiviert das Raumwerkzeug im adressierten Fenster (P).";
    cmd_arm_grid: "Grid Tool", "Rasterwerkzeug";
    cmd_arm_grid_describe: "Arms the grid line utility in the addressed window (G).", "Aktiviert das Rasterlinien-Werkzeug im adressierten Fenster (G).";
    cmd_arm_measure: "Measure Tool", "Messwerkzeug";
    cmd_arm_measure_describe: "Arms the measure utility in the addressed window (M).", "Aktiviert das Messwerkzeug im adressierten Fenster (M).";

    cmd_arm_move: "Move Tool", "Verschieben-Werkzeug";
    cmd_arm_move_describe: "Arms the move utility in the addressed window (E).", "Aktiviert das Verschieben-Werkzeug im adressierten Fenster (E).";
    cmd_arm_rotate: "Rotate Tool", "Drehen-Werkzeug";
    cmd_arm_rotate_describe: "Arms the rotate utility in the addressed window (Q).", "Aktiviert das Drehen-Werkzeug im adressierten Fenster (Q).";
    cmd_arm_slab_walls: "Slab From Walls Tool", "Decke-aus-Wänden-Werkzeug";
    cmd_arm_slab_walls_describe: "Arms the slab from walls utility in the addressed window (Shift+S).", "Aktiviert das Werkzeug Decke aus Wänden im adressierten Fenster (Umschalt+S).";
    cmd_arm_ceiling: "Ceiling Tool", "Unterdeckenwerkzeug";
    cmd_arm_ceiling_describe: "Arms the ceiling utility in the addressed window (I): a rectangle or a polygon becomes a ceiling hung below the storey top.", "Aktiviert das Unterdeckenwerkzeug im adressierten Fenster (I): ein Rechteck oder Polygon wird zu einer unter der Geschossoberkante abgehängten Unterdecke.";
    cmd_arm_ceiling_space: "Ceiling From Space Tool", "Unterdecke-aus-Raum-Werkzeug";
    cmd_arm_ceiling_space_describe: "Arms the ceiling from space utility in the addressed window (Shift+I): a click in a room hangs a ceiling over its outline.", "Aktiviert das Werkzeug Unterdecke aus Raum im adressierten Fenster (Umschalt+I): ein Klick in einen Raum hängt eine Unterdecke über seinen Umriss.";
    cmd_arm_split_wall: "Split Wall Tool", "Wand-teilen-Werkzeug";
    cmd_arm_split_wall_describe: "Arms the split wall utility in the addressed window (Shift+W): a click on a wall splits it there.", "Aktiviert das Werkzeug Wand teilen im adressierten Fenster (Umschalt+W): ein Klick auf eine Wand teilt sie dort.";
    cmd_arm_copy: "Copy Tool", "Kopierwerkzeug";
    cmd_arm_copy_describe: "Arms the copy utility in the addressed window (K): click a base point and a target, the selection is copied by that vector.", "Aktiviert das Kopierwerkzeug im adressierten Fenster (K): Basispunkt und Ziel anklicken, die Auswahl wird um diesen Vektor kopiert.";
    cmd_arm_mirror: "Mirror Tool", "Spiegelwerkzeug";
    cmd_arm_mirror_describe: "Arms the mirror utility in the addressed window (Shift+K): click the two points of the mirror line; with Ctrl or Command on the second click the mirror images are created as copies.", "Aktiviert das Spiegelwerkzeug im adressierten Fenster (Umschalt+K): die zwei Punkte der Spiegellinie anklicken; mit Strg oder Befehl beim zweiten Klick entstehen Spiegelkopien.";
    cmd_arm_array: "Array Tool", "Reihenwerkzeug";
    cmd_arm_array_describe: "Arms the linear array utility in the addressed window (Y): click a base point, the point of the first copy and the point of the last one.", "Aktiviert das Reihenwerkzeug im adressierten Fenster (Y): Basispunkt, Punkt der ersten Kopie und Punkt der letzten Kopie anklicken.";
    cmd_arm_array_radial: "Radial Array Tool", "Kreisreihen-Werkzeug";
    cmd_arm_array_radial_describe: "Arms the radial array utility in the addressed window (Shift+Y): click the centre, a reference point and the step; the circle is filled with copies.", "Aktiviert das Kreisreihen-Werkzeug im adressierten Fenster (Umschalt+Y): Mittelpunkt, Bezugspunkt und Schritt anklicken; der Kreis wird mit Kopien gefüllt.";
    cmd_arm_offset: "Offset Tool", "Versatzwerkzeug";
    cmd_arm_offset_describe: "Arms the offset utility in the addressed window (F): press a wall, then click the side and distance of its parallel copy.", "Aktiviert das Versatzwerkzeug im adressierten Fenster (F): eine Wand anklicken, dann Seite und Abstand ihrer parallelen Kopie anklicken.";
    cmd_arm_trim: "Trim Tool", "Kürzen-Werkzeug";
    cmd_arm_trim_describe: "Arms the trim utility in the addressed window (X): press the target wall, then the part of each wall to keep.", "Aktiviert das Kürzen-Werkzeug im adressierten Fenster (X): die Zielwand anklicken, dann den zu behaltenden Teil jeder Wand.";
    cmd_arm_extend: "Extend Tool", "Verlängern-Werkzeug";
    cmd_arm_extend_describe: "Arms the extend utility in the addressed window (Shift+X): press the target wall, then the end of each wall to extend to it.", "Aktiviert das Verlängern-Werkzeug im adressierten Fenster (Umschalt+X): die Zielwand anklicken, dann das zu verlängernde Ende jeder Wand.";
    cmd_arm_align: "Align Tool", "Ausrichten-Werkzeug";
    cmd_arm_align_describe: "Arms the align utility in the addressed window (Z): with elements selected, press the reference element near the edge or middle line to align them to.", "Aktiviert das Ausrichten-Werkzeug im adressierten Fenster (Z): bei gewählten Bauteilen das Bezugsbauteil nahe der Kante oder Mittellinie anklicken, auf die ausgerichtet wird.";
    cmd_arm_split: "Split Beam Or Slab Tool", "Träger-oder-Decke-teilen-Werkzeug";
    cmd_arm_split_describe: "Arms the split utility for beams and slabs in the addressed window (Shift+Z): a click on a beam splits it there, two clicks cut a slab along their line.", "Aktiviert das Teilen-Werkzeug für Träger und Decken im adressierten Fenster (Umschalt+Z): ein Klick auf einen Träger teilt ihn dort, zwei Klicks schneiden eine Decke entlang ihrer Linie.";
    cmd_arm_dimension: "Dimension Tool", "Bemaßungswerkzeug";
    cmd_arm_dimension_describe: "Arms the dimension utility in the addressed window (Shift+D): click the anchors (wall faces, ends, opening and column centres, grid lines or points; hold Shift to chain more), then click where the dimension line goes.", "Aktiviert das Bemaßungswerkzeug im adressierten Fenster (Umschalt+D): Klicken Sie die Anker (Wandflächen, -enden, Öffnungs- und Stützenmitten, Rasterlinien oder Punkte; mit Umschalt weitere anfügen), dann die Lage der Maßlinie.";
    cmd_arm_tag: "Tag Tool", "Kennzeichnungswerkzeug";
    cmd_arm_tag_describe: "Arms the tag utility in the addressed window (Shift+G): a click on an element places a tag that reads its name, type, number or size and follows the element.", "Aktiviert das Kennzeichnungswerkzeug im adressierten Fenster (Umschalt+G): Ein Klick auf ein Bauteil setzt eine Kennzeichnung, die Name, Typ, Nummer oder Größe liest und dem Bauteil folgt.";
    cmd_arm_text_note: "Text Tool", "Textwerkzeug";
    cmd_arm_text_note_describe: "Arms the text utility in the addressed window (Shift+N): a click places a free text note.", "Aktiviert das Textwerkzeug im adressierten Fenster (Umschalt+N): Ein Klick setzt eine freie Textnotiz.";
    cmd_arm_leader: "Leader Tool", "Hinweislinienwerkzeug";
    cmd_arm_leader_describe: "Arms the leader utility in the addressed window (Shift+L): click the element or point to point at, then click where the text goes.", "Aktiviert das Hinweislinienwerkzeug im adressierten Fenster (Umschalt+L): Klicken Sie auf das Bauteil oder den Punkt und dann auf die Lage des Textes.";
    cmd_flip_walls: "Flip Walls", "Wände wenden";
    cmd_flip_walls_describe: "Reverses the direction of the given walls, or of the selected walls, in one undoable step (Shift+F).", "Kehrt die Richtung der angegebenen oder der ausgewählten Wände in einem rückgängig machbaren Schritt um (Umschalt+F).";
    cmd_storey_up: "Move to Storey Above", "Ins Geschoss darüber verschieben";
    cmd_storey_up_describe: "Stands the given elements, or the selected ones, on the storey above their own in the same building; hosted openings follow their host (Alt+Up).", "Stellt die angegebenen oder die ausgewählten Bauteile auf das Geschoss über ihrem eigenen im selben Gebäude; Öffnungen folgen ihrem Wirt (Alt+Aufwärts).";
    cmd_storey_down: "Move to Storey Below", "Ins Geschoss darunter verschieben";
    cmd_storey_down_describe: "Stands the given elements, or the selected ones, on the storey below their own in the same building; hosted openings follow their host (Alt+Down).", "Stellt die angegebenen oder die ausgewählten Bauteile auf das Geschoss unter ihrem eigenen im selben Gebäude; Öffnungen folgen ihrem Wirt (Alt+Abwärts).";
    cmd_split_wall: "Split Wall", "Wand teilen";
    cmd_split_wall_describe: "Splits the given wall, or the selected one, at a fraction of its axis (0.5 is the middle) into two walls.", "Teilt die angegebene oder die ausgewählte Wand bei einem Bruchteil ihrer Achse (0,5 ist die Mitte) in zwei Wände.";
    cmd_set_property: "Set Property", "Eigenschaft setzen";
    cmd_set_property_describe: "Sets one typed property of a property set of the given elements, or of the selection; without a set and a name the value reads 'Set.Property = value'.", "Setzt eine typisierte Eigenschaft eines Eigenschaftssatzes der angegebenen Bauteile oder der Auswahl; ohne Satz und Namen lautet der Wert 'Satz.Eigenschaft = Wert'.";
    cmd_remove_property: "Remove Property", "Eigenschaft entfernen";
    cmd_remove_property_describe: "Removes one property of the given elements, or of the selection.", "Entfernt eine Eigenschaft der angegebenen Bauteile oder der Auswahl.";
    cmd_place_elements: "Place Elements", "Elemente platzieren";
    cmd_place_elements_describe: "Places the given elements, or the selection, so that the reference point of the first one lands on the typed coordinates 'x, y'; all keep their shape.", "Platziert die angegebenen Bauteile oder die Auswahl so, dass der Bezugspunkt des ersten auf den getippten Koordinaten 'x, y' liegt; alle behalten ihre Form.";
    cmd_engagement_input: "Typed Entry", "Eingabe";
    cmd_engagement_input_describe: "Keeps the line typed into the entry field of the window (a point, an offset, a length or an angle) while it is being typed.", "Merkt die in das Eingabefeld des Fensters getippte Zeile (Punkt, Versatz, Länge oder Winkel) während des Tippens.";
    cmd_engagement_submit: "Enter Typed Value", "Eingabe übernehmen";
    cmd_engagement_submit_describe: "Gives the typed line to the armed utility as a click: 'x, y', '@dx, dy', 'length<angle' or a bare length; an empty line finishes the gesture.", "Gibt die getippte Zeile dem aktiven Werkzeug wie einen Klick: 'x, y', '@dx, dy', 'Länge<Winkel' oder eine Länge; eine leere Zeile beendet die Geste.";

    arg_kind: "Kind", "Art";
    arg_container: "Container", "Container";
    arg_name: "Name", "Name";
    arg_entity: "Entity", "Bauteil";
    arg_entities: "Entities", "Bauteile";
    arg_parameter: "Parameter", "Parameter";
    arg_value: "Value", "Wert";
    arg_setting: "Setting", "Einstellung";
    arg_part: "Part of the definition", "Teil der Definition";
    arg_operation: "Operation", "Vorgang";
    arg_key: "Key", "Schlüssel";
    cmd_edit_schedule: "Edit Schedule", "Bauteilliste bearbeiten";
    cmd_export_schedule_csv: "Export Schedule as CSV", "Bauteilliste als CSV exportieren";
    cmd_analyse_model: "Analyse Model", "Modell analysieren";
    cmd_analyse_model_describe: "Brings the analysis every window, gesture and export reads (layouts, solids, rooms, quantities, findings) up to the model in steps with progress, so the next read answers at once. It can be cancelled; the analysis done so far is kept.", "Bringt die Analyse, aus der jedes Fenster, jede Geste und jeder Export liest (Verläufe, Körper, Räume, Mengen, Befunde), in Schritten mit Fortschritt auf den Stand des Modells, damit die nächste Abfrage sofort antwortet. Sie lässt sich abbrechen; die bisherige Analyse bleibt erhalten.";
    measure_analyse: "Analyse model", "Modell analysieren";
    cmd_export_model: "Export Model", "Modell exportieren";
    cmd_export_model_describe: "Writes the whole model as an IFC 2x3 file, a binary glTF scene, an SVG sheet of its views or a CSV report and offers it as a download. The analysis the file shows runs in steps with progress and can be cancelled; the analysis done so far is kept.", "Schreibt das ganze Modell als IFC-2x3-Datei, als binäre glTF-Szene, als SVG-Blatt seiner Ansichten oder als CSV-Bericht und bietet es zum Download an. Die Analyse, die die Datei zeigt, läuft in Schritten mit Fortschritt und lässt sich abbrechen; die bisherige Analyse bleibt erhalten.";
    measure_export: "Export", "Export";
    export_ifc: "IFC 2x3 (STEP)", "IFC 2x3 (STEP)";
    export_glb: "glTF binary (3D)", "glTF binär (3D)";
    export_svg: "SVG sheet (views)", "SVG-Blatt (Ansichten)";
    export_csv: "CSV report (schedules)", "CSV-Bericht (Listen)";
    cmd_export_schedule_csv_describe: "Writes the table of a schedule (the one named, else the one the window shows) as an RFC 4180 CSV file and offers it as a download. The inference runs in steps with progress and can be cancelled; the file lists the rows and totals exactly as the window shows them, with stable tokens instead of localized words.", "Schreibt die Tabelle einer Bauteilliste (der genannten, sonst der im Fenster gezeigten) als CSV-Datei nach RFC 4180 und bietet sie zum Herunterladen an. Die Inferenz läuft schrittweise mit Fortschritt und lässt sich abbrechen; die Datei enthält Zeilen und Summen genau wie das Fenster, mit stabilen Kennungen statt lokalisierter Wörter.";
    cmd_edit_schedule_describe: "Edits one part of a schedule definition (name, category, a column, a sort key, a filter, a grouping level, itemization, a storey or a phase of the scope) as one undoable step; the rows and totals follow by inference.", "Bearbeitet einen Teil einer Bauteillisten-Definition (Name, Kategorie, eine Spalte, ein Sortierschlüssel, ein Filter, eine Gruppierungsebene, Einzelauflistung, ein Geschoss oder eine Phase des Umfangs) in einem rückgängig machbaren Schritt; Zeilen und Summen folgen durch Inferenz.";
    arg_fraction: "Fraction", "Bruchteil";
    arg_position: "Position", "Position";
    arg_property_set: "Property set", "Eigenschaftssatz";
    arg_property: "Property", "Eigenschaft";
    arg_typed_line: "Typed line", "Getippte Zeile";

    fault_create_kind_unknown: "This kind of entity does not exist.", "Diese Bauteilart gibt es nicht.";
    fault_create_unsupported: "This kind of entity cannot be created yet.", "Diese Bauteilart kann noch nicht angelegt werden.";
    fault_create_site_missing: "Create a site first.", "Legen Sie zuerst ein Grundstück an.";
    fault_create_building_missing: "Create a building first.", "Legen Sie zuerst ein Gebäude an.";
    fault_create_storey_missing: "Create or select a storey first.", "Legen Sie zuerst ein Geschoss an oder wählen Sie eines aus.";
    fault_create_wall_type_missing: "Create a wall type first.", "Legen Sie zuerst einen Wandtyp an.";
    fault_delete_unsupported: "These entities cannot be deleted yet.", "Diese Bauteile können noch nicht gelöscht werden.";
    fault_rename_target_missing: "The entity to rename does not exist.", "Das umzubenennende Bauteil gibt es nicht.";
    fault_rename_unsupported: "This kind of entity cannot be renamed yet.", "Diese Bauteilart kann noch nicht umbenannt werden.";
    fault_rename_rejected: "The name is not valid.", "Der Name ist ungültig.";
    fault_set_target_missing: "The entity to change does not exist.", "Das zu ändernde Bauteil gibt es nicht.";
    fault_set_field_unknown: "This entity has no such parameter.", "Dieses Bauteil hat keinen solchen Parameter.";
    fault_set_read_only: "This parameter cannot be edited yet.", "Dieser Parameter kann noch nicht bearbeitet werden.";
    fault_set_value_invalid: "The value is not valid for this parameter.", "Der Wert ist für diesen Parameter ungültig.";
    fault_view_window_required: "This setting belongs to one open window.", "Diese Einstellung gehört zu einem geöffneten Fenster.";
    fault_view_window_unsupported: "This window has no view settings.", "Dieses Fenster hat keine Ansichtseinstellungen.";
    fault_view_field_unknown: "This window has no such view setting.", "Dieses Fenster hat keine solche Ansichtseinstellung.";
    fault_view_value_invalid: "The value is not valid for this view setting.", "Der Wert ist für diese Ansichtseinstellung ungültig.";
    fault_view_storey_missing: "The storey does not exist.", "Das Geschoss gibt es nicht.";
    fault_view_view_missing: "The view does not exist or is of another kind.", "Die Ansicht gibt es nicht oder sie ist von anderer Art.";
    fault_view_kind_unknown: "This kind of view does not exist.", "Diese Ansichtsart gibt es nicht.";
    fault_view_building_missing: "Create a building first.", "Legen Sie zuerst ein Gebäude an.";
    fault_camera_window_required: "A camera belongs to one open window.", "Eine Kamera gehört zu einem geöffneten Fenster.";
    fault_camera_pose_mismatch: "This window takes a different kind of camera pose.", "Dieses Fenster nimmt eine andere Art von Kamerapose.";
    fault_camera_invalid: "The camera pose is not valid.", "Die Kamerapose ist ungültig.";
    fault_tool_storey_missing: "Create or select a storey to draw on first.", "Legen Sie zuerst ein Geschoss an oder wählen Sie eines aus, auf dem gezeichnet wird.";
    fault_tool_type_missing: "The library has no type for this tool yet. Add one first.", "Die Bibliothek enthält noch keinen Typ für dieses Werkzeug. Legen Sie zuerst einen an.";
    fault_tool_rejected: "The model does not accept this here: it overlaps another element or leaves its host.", "Das Modell nimmt das hier nicht an: es überschneidet ein anderes Bauteil oder verlässt sein Trägerbauteil.";
    fault_tool_input_invalid: "The typed entry is not a point, an offset, a length or an angle.", "Die Eingabe ist weder ein Punkt noch ein Versatz, eine Länge oder ein Winkel.";
    fault_gesture_retained_route: "Drawing gestures run only inside an open editor window.", "Zeichengesten laufen nur in einem geöffneten Editorfenster.";
    fault_split_target_missing: "Select the wall to split.", "Wählen Sie die zu teilende Wand aus.";
    fault_split_fraction_invalid: "Split strictly between the two ends of the wall, for example at 0.5.", "Teilen Sie echt zwischen den beiden Enden der Wand, zum Beispiel bei 0,5.";
    fault_storey_target_missing: "Select at least one element that stands on a storey.", "Wählen Sie mindestens ein Bauteil aus, das auf einem Geschoss steht.";
    fault_storey_no_neighbour: "There is no storey in that direction for every selected element.", "In dieser Richtung gibt es nicht für jedes gewählte Bauteil ein Geschoss.";
    fault_flip_wall_missing: "Select at least one wall to flip.", "Wählen Sie mindestens eine Wand zum Wenden aus.";
    fault_analyse_inference: "The model could not be analysed.", "Das Modell konnte nicht analysiert werden.";
    fault_analyse_cancelled: "The analysis was cancelled; what was analysed so far is kept.", "Die Analyse wurde abgebrochen; das bisher Analysierte bleibt erhalten.";
    fault_export_format_unknown: "That is not a file format the model can be exported to.", "In dieses Dateiformat kann das Modell nicht exportiert werden.";
    fault_export_inference: "The model could not be analysed, so no file was written.", "Das Modell konnte nicht analysiert werden, deshalb wurde keine Datei geschrieben.";
    fault_export_failed: "The file could not be written.", "Die Datei konnte nicht geschrieben werden.";
    fault_export_cancelled: "The export was cancelled; the analysis done so far is kept.", "Der Export wurde abgebrochen; die bisherige Analyse bleibt erhalten.";
    fault_property_target_missing: "The element to describe does not exist.", "Das zu beschreibende Bauteil gibt es nicht.";
    fault_property_name_invalid: "A property needs a property set and a name, written 'Set.Property = value'.", "Eine Eigenschaft braucht einen Satz und einen Namen, geschrieben 'Satz.Eigenschaft = Wert'.";
    fault_property_value_invalid: "The value does not fit the type of this property.", "Der Wert passt nicht zum Typ dieser Eigenschaft.";
    fault_property_missing: "This element has no such property.", "Dieses Bauteil hat keine solche Eigenschaft.";
    fault_place_target_missing: "Select the elements to place.", "Wählen Sie die zu platzierenden Bauteile aus.";
    fault_place_point_invalid: "Type the position as 'x, y' in metres.", "Tippen Sie die Position als 'x, y' in Metern.";
    fault_place_unsupported: "These elements have no placement to move.", "Diese Bauteile haben keine Platzierung, die sich verschieben ließe.";

    utility_select: "Select", "Auswählen";
    utility_move: "Move", "Verschieben";
    utility_rotate: "Rotate", "Drehen";
    utility_wall: "Wall", "Wand";
    utility_wall_arc: "Arc wall", "Bogenwand";
    utility_curtain_wall: "Curtain wall", "Vorhangfassade";
    utility_column: "Column", "Stütze";
    utility_beam: "Beam", "Träger";
    utility_slab: "Slab", "Decke";
    utility_slab_walls: "Slab from walls", "Decke aus Wänden";
    utility_ceiling: "Ceiling", "Unterdecke";
    utility_ceiling_space: "Ceiling from space", "Unterdecke aus Raum";
    utility_roof: "Roof", "Dach";
    utility_window: "Window", "Fenster";
    utility_door: "Door", "Tür";
    utility_opening: "Opening", "Öffnung";
    utility_stair: "Stair", "Treppe";
    utility_railing: "Railing", "Geländer";
    utility_ramp: "Ramp", "Rampe";
    utility_space: "Space", "Raum";
    utility_grid: "Grid line", "Rasterlinie";
    utility_measure: "Measure", "Messen";
    utility_split_wall: "Split wall", "Wand teilen";
    utility_copy: "Copy", "Kopieren";
    utility_mirror: "Mirror", "Spiegeln";
    utility_array: "Array", "Reihe";
    utility_array_radial: "Radial array", "Kreisreihe";
    utility_offset: "Offset wall", "Wand versetzen";
    utility_trim: "Trim wall", "Wand kürzen";
    utility_extend: "Extend wall", "Wand verlängern";
    utility_align: "Align", "Ausrichten";
    utility_split: "Split beam or slab", "Träger oder Decke teilen";
    utility_dimension: "Dimension", "Bemaßen";
    utility_tag: "Tag", "Kennzeichnen";
    utility_text_note: "Text", "Text";
    utility_leader: "Leader", "Hinweislinie";

    domain_elements: "Elements", "Bauteile";
    domain_library: "Library", "Bibliothek";

    field_description: "Description", "Beschreibung";
    field_author: "Author", "Autor";
    field_organization: "Organization", "Organisation";
    field_phase_names: "Phase names", "Phasennamen";
    field_boundary: "Outline", "Umriss";
    field_holes: "Holes", "Aussparungen";
    field_footprint: "Footprint", "Grundriss";
    field_anchors: "Anchors", "Anker";
    field_anchor: "Anchor", "Anker";
    field_direction_angle: "Direction (rad)", "Richtung (rad)";
    field_lock: "Lock (m)", "Sperre (m)";
    field_style: "Annotation style", "Beschriftungsstil";
    field_element: "Element", "Bauteil";
    field_reads: "Reads", "Liest";
    field_text: "Text", "Text";
    field_text_height: "Text height (m)", "Texthöhe (m)";
    field_terminator: "Line end", "Linienende";
    field_unit: "Unit", "Einheit";
    field_precision: "Decimals", "Nachkommastellen";
    field_mark_size: "Mark size (m)", "Markengröße (m)";
    field_extension_gap: "Extension gap (m)", "Hilfslinienabstand (m)";
    field_extension_overshoot: "Extension overshoot (m)", "Hilfslinienüberstand (m)";
    field_measured: "Measured (m)", "Gemessen (m)";
    field_printed: "Printed", "Gedruckt";
    field_lock_difference: "Lock difference (m)", "Abweichung von der Sperre (m)";
    field_classification: "Classification", "Klassifizierung";
    section_project: "Project", "Projekt";
    section_property_sets: "Property sets", "Eigenschaftssätze";
    section_actions: "Actions", "Aktionen";
    action_flip_wall: "Flip wall", "Wand wenden";
    action_split_wall_at: "Split wall at", "Wand teilen bei";
    action_place_at: "Place at x, y", "Platzieren bei x, y";
    action_add_property: "Add property: Set.Property = value", "Eigenschaft hinzufügen: Satz.Eigenschaft = Wert";
    action_remove_property: "Remove property {name}", "Eigenschaft {name} entfernen";

    entry_label: "Typed entry", "Eingabe";
    entry_placeholder: "x, y · @dx, dy · length<angle · length", "x, y · @dx, dy · Länge<Winkel · Länge";
    entry_describe: "Type a point, an offset or a length and press Enter instead of clicking; Escape cancels.", "Tippen Sie einen Punkt, einen Versatz oder eine Länge und drücken Sie Enter statt zu klicken; Escape bricht ab.";
    status_typing: "Typed: {name}", "Eingabe: {name}";
    surface_plan_describe: "Plan drawing surface of one storey. Arm a tool with its key, then click or type a point such as 3, 4 or @2<90 into the entry field and press Enter. Or move a cursor with Ctrl or Cmd and the arrow keys (add Shift for one metre steps) and press Ctrl or Cmd and Enter to click there.", "Grundrissfläche eines Geschosses. Aktivieren Sie ein Werkzeug mit seiner Taste, dann klicken Sie oder tippen Sie einen Punkt wie 3, 4 oder @2<90 in das Eingabefeld und drücken Sie Enter. Oder bewegen Sie einen Cursor mit Strg oder Cmd und den Pfeiltasten (mit Umschalt in Schritten von einem Meter) und klicken Sie dort mit Strg oder Cmd und Enter.";
    surface_world_describe: "3D view of the model. Select with the pointer or from the outliner; the entry field places geometry with typed coordinates.", "3D-Ansicht des Modells. Wählen Sie mit dem Zeiger oder in der Struktur; das Eingabefeld platziert Geometrie mit getippten Koordinaten.";
    surface_section_describe: "Section drawing along a line through the model. Type positions as distance along the line and height, or move a cursor with Ctrl or Cmd and the arrow keys and press Ctrl or Cmd and Enter to click there.", "Schnittzeichnung entlang einer Linie durch das Modell. Tippen Sie Positionen als Abstand entlang der Linie und Höhe oder bewegen Sie einen Cursor mit Strg oder Cmd und den Pfeiltasten und klicken Sie dort mit Strg oder Cmd und Enter.";
    surface_schedule_describe: "Table of quantities per element and per kind; a row selects its element.", "Tabelle der Mengen je Bauteil und je Art; eine Zeile wählt ihr Bauteil aus.";

    measure_hide_storey: "Hide {name}", "{name} ausblenden";
    measure_visible_storeys: "Storeys", "Geschosse";
    axis_x: "X", "X";
    axis_y: "Y", "Y";
    axis_z: "Z", "Z";

    kind_schedule: "Schedule", "Bauteilliste";
    group_schedules: "Schedules", "Bauteillisten";
    field_columns: "Columns", "Spalten";
    field_sort: "Sort", "Sortierung";
    field_filter: "Filter", "Filter";
    field_group: "Grouping", "Gruppierung";
    field_itemize: "Itemize every instance", "Jedes Bauteil einzeln auflisten";
    field_scope_storeys: "Storeys", "Geschosse";
    field_scope_phases: "Phases", "Phasen";

    sf_id: "Id", "Id";
    sf_name: "Name", "Name";
    sf_kind: "Kind", "Art";
    sf_storey: "Storey", "Geschoss";
    sf_level: "Level", "Ebene";
    sf_type: "Type", "Typ";
    sf_phase: "Phase", "Phase";
    sf_material: "Material", "Material";
    sf_host: "Host", "Trägerbauteil";
    sf_number: "Number", "Nummer";
    sf_usage: "Usage", "Nutzung";
    sf_swing: "Swing", "Anschlag";
    sf_leaves: "Leaves", "Flügel";
    sf_panes: "Panes", "Scheiben";
    sf_count: "Count", "Anzahl";
    sf_length: "Length", "Länge";
    sf_width: "Width", "Breite";
    sf_height: "Height", "Höhe";
    sf_perimeter: "Perimeter", "Umfang";
    sf_gross_side_area: "Gross side area", "Bruttoseitenfläche";
    sf_opening_area: "Opening area", "Öffnungsfläche";
    sf_net_side_area: "Net side area", "Nettoseitenfläche";
    sf_gross_area: "Gross area", "Bruttofläche";
    sf_net_area: "Net area", "Nettofläche";
    sf_surface_area: "Surface area", "Oberfläche";
    sf_gross_volume: "Gross volume", "Bruttovolumen";
    sf_net_volume: "Net volume", "Nettovolumen";
    sf_mass: "Mass", "Masse";
    sf_risers: "Risers", "Steigungen";
    sf_thickness: "Thickness", "Dicke";
    sf_layer_area: "Layer area", "Schichtfläche";
    sf_layer_volume: "Layer volume", "Schichtvolumen";
    sf_layer_mass: "Layer mass", "Schichtmasse";

    sc_wall: "Walls", "Wände";
    sc_curtain_wall: "Curtain walls", "Vorhangfassaden";
    sc_slab: "Slabs", "Decken";
    sc_roof: "Roofs", "Dächer";
    sc_column: "Columns", "Stützen";
    sc_beam: "Beams", "Träger";
    sc_window: "Windows", "Fenster";
    sc_door: "Doors", "Türen";
    sc_void: "Voids", "Aussparungen";
    sc_stair: "Stairs", "Treppen";
    sc_railing: "Railings", "Geländer";
    sc_space: "Rooms", "Räume";
    sc_material: "Material take-off", "Materialauszug";

    so_equals: "equals", "ist gleich";
    so_not_equals: "differs from", "ist ungleich";
    so_contains: "contains", "enthält";
    so_greater: "greater than", "größer als";
    so_greater_or_equal: "at least", "mindestens";
    so_less: "less than", "kleiner als";
    so_less_or_equal: "at most", "höchstens";
    so_empty: "is empty", "ist leer";
    so_not_empty: "is not empty", "ist nicht leer";

    sv_existing: "Existing", "Bestand";
    sv_new: "New", "Neu";
    sv_demolished: "Demolished", "Abbruch";
    sv_temporary: "Temporary", "Temporär";
    sv_left: "Left", "Links";
    sv_right: "Right", "Rechts";
    sv_single: "Single leaf", "Einflügelig";
    sv_double: "Double leaf", "Zweiflügelig";

    sp_door: "Door schedule", "Türliste";
    sp_window: "Window schedule", "Fensterliste";
    sp_room: "Room schedule", "Raumbuch";
    sp_finish: "Room finish schedule", "Raumbelagsliste";
    sp_wall: "Wall schedule", "Wandliste";
    sp_material: "Material take-off", "Materialauszug";

    sch_show: "Show", "Anzeigen";
    sch_export_csv: "Export CSV", "CSV exportieren";
    sch_edit: "Edit definition", "Definition bearbeiten";
    sch_table: "Show table", "Tabelle anzeigen";
    sch_back: "All schedules", "Alle Listen";
    sch_none: "No schedules yet", "Noch keine Bauteillisten";
    sch_rows: "Rows", "Zeilen";
    sch_empty_table: "No element matches the schedule", "Kein Bauteil entspricht der Liste";
    sch_part: "Part", "Teil";
    sch_item: "Setting", "Einstellung";
    sch_value: "Value", "Wert";
    sch_actions: "Actions", "Aktionen";
    sch_available: "Available", "Verfügbar";
    sch_shown: "Shown", "Angezeigt";
    act_add: "Add", "Hinzufügen";
    act_remove: "Remove", "Entfernen";
    act_up: "Move up", "Nach oben";
    act_down: "Move down", "Nach unten";
    act_total: "Sum this column", "Spalte summieren";
    act_descending: "Reverse the order", "Reihenfolge umkehren";
    act_next_comparison: "Next comparison", "Nächster Vergleich";
    act_toggle: "Toggle", "Umschalten";
    act_new_named: "New {name}", "Neu: {name}";
    act_delete_named: "Delete {name}", "{name} löschen";
    panel_diagnostics: "Diagnostics", "Diagnose";
    diag_surface_describe: "Findings of the model grouped by severity, storey and kind. Open or close a severity group to filter; activating a finding selects its elements in the plan, the 3D view and the outliner.", "Befunde des Modells, gruppiert nach Schwere, Geschoss und Art. Öffnen oder schließen Sie eine Gruppe, um zu filtern; ein Befund wählt seine Bauteile im Grundriss, in der 3D-Ansicht und in der Struktur aus.";
    diag_errors: "Errors", "Fehler";
    diag_warnings: "Warnings", "Warnungen";
    diag_notes: "Notes", "Hinweise";
    diag_error: "Error", "Fehler";
    diag_warning: "Warning", "Warnung";
    diag_note: "Note", "Hinweis";
    diag_model_wide: "Whole model", "Gesamtes Modell";
    diag_empty: "No problems found", "Keine Probleme gefunden";
    diag_cat_annotation: "Annotations", "Beschriftungen";
    diag_cat_ceiling: "Ceilings", "Unterdecken";
    diag_cat_clash: "Clashes", "Kollisionen";
    diag_cat_degenerate: "Degenerate geometry", "Entartete Geometrie";
    diag_cat_opening: "Openings", "Öffnungen";
    diag_cat_railing: "Railings", "Geländer";
    diag_cat_ramp: "Ramps", "Rampen";
    diag_cat_reference: "References", "Verweise";
    diag_cat_roof: "Roofs", "Dächer";
    diag_cat_space: "Spaces", "Räume";
    diag_cat_stair: "Stairs", "Treppen";
    diag_cat_storey: "Storeys", "Geschosse";
    status_errors: "Errors: {count}", "Fehler: {count}";
    status_warnings: "Warnings: {count}", "Warnungen: {count}";
    status_notes: "Notes: {count}", "Hinweise: {count}";
    status_no_problems: "No problems", "Keine Probleme";
    cmd_select_findings: "Select Findings", "Befunde auswählen";
    cmd_select_findings_describe: "Selects the elements a finding of the diagnostics names, in the plan, the 3D view and the outliner.", "Wählt die Bauteile, die ein Befund der Diagnose nennt, im Grundriss, in der 3D-Ansicht und in der Struktur aus.";
    fault_diagnostic_target_missing: "None of the elements the finding names exists any more.", "Keines der Bauteile, die der Befund nennt, gibt es noch.";
    cmd_set_classification: "Set Classification", "Klassifizierung setzen";
    cmd_set_classification_describe: "Classifies the given elements or types, or the selection, with a code of a classification system.", "Klassifiziert die angegebenen Bauteile oder Typen oder die Auswahl mit einem Code eines Klassifikationssystems.";
    cmd_remove_classification: "Remove Classification", "Klassifizierung entfernen";
    cmd_remove_classification_describe: "Removes the classification in one system from the given elements or types, or from the selection.", "Entfernt die Klassifizierung in einem System von den angegebenen Bauteilen oder Typen oder von der Auswahl.";
    arg_classification_system: "Classification system", "Klassifizierungssystem";
    arg_classification_code: "Classification code", "Klassifizierungscode";
    arg_classification_title: "Classification title", "Klassifizierungstitel";
    fault_classification_target_missing: "Select the elements to classify.", "Wählen Sie die zu klassifizierenden Bauteile aus.";
    fault_classification_invalid: "A classification needs a system and a code.", "Eine Klassifizierung braucht ein System und einen Code.";
    fault_classification_missing: "None of these elements is classified.", "Keines dieser Bauteile ist klassifiziert.";
    cmd_cursor_left: "Cursor Left", "Cursor nach links";
    cmd_cursor_left_describe: "Moves the keyboard cursor of the armed tool 0.1 m to the left.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 0,1 m nach links.";
    cmd_cursor_right: "Cursor Right", "Cursor nach rechts";
    cmd_cursor_right_describe: "Moves the keyboard cursor of the armed tool 0.1 m to the right.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 0,1 m nach rechts.";
    cmd_cursor_up: "Cursor Up", "Cursor nach oben";
    cmd_cursor_up_describe: "Moves the keyboard cursor of the armed tool 0.1 m up.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 0,1 m nach oben.";
    cmd_cursor_down: "Cursor Down", "Cursor nach unten";
    cmd_cursor_down_describe: "Moves the keyboard cursor of the armed tool 0.1 m down.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 0,1 m nach unten.";
    cmd_cursor_left_far: "Cursor Far Left", "Cursor weit nach links";
    cmd_cursor_left_far_describe: "Moves the keyboard cursor of the armed tool 1 m to the left.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 1 m nach links.";
    cmd_cursor_right_far: "Cursor Far Right", "Cursor weit nach rechts";
    cmd_cursor_right_far_describe: "Moves the keyboard cursor of the armed tool 1 m to the right.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 1 m nach rechts.";
    cmd_cursor_up_far: "Cursor Far Up", "Cursor weit nach oben";
    cmd_cursor_up_far_describe: "Moves the keyboard cursor of the armed tool 1 m up.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 1 m nach oben.";
    cmd_cursor_down_far: "Cursor Far Down", "Cursor weit nach unten";
    cmd_cursor_down_far_describe: "Moves the keyboard cursor of the armed tool 1 m down.", "Bewegt den Tastaturcursor des aktiven Werkzeugs um 1 m nach unten.";
    cmd_cursor_place: "Place at Cursor", "Am Cursor platzieren";
    cmd_cursor_place_describe: "Clicks the armed tool at the keyboard cursor, as a click at that exact point would.", "Klickt mit dem aktiven Werkzeug am Tastaturcursor, wie ein Klick auf genau diesen Punkt.";
    window_sheet: "Sheet", "Blatt";
    surface_sheet_describe: "Sheet at actual size in millimetres with its viewports, title block and revision table. Drag a viewport to move it, drag the handle at its corner to change its scale, or set position and scale in the properties. The place view tool puts the selected view on the sheet with a click; type positions as millimetres from the top left corner, or move a cursor with Ctrl or Cmd and the arrow keys and press Ctrl or Cmd with Enter.", "Blatt in Originalgrösse in Millimetern mit seinen Ansichtsfenstern, dem Schriftkopf und der Änderungstabelle. Ziehen Sie ein Ansichtsfenster, um es zu verschieben, ziehen Sie den Griff an seiner Ecke, um den Massstab zu ändern, oder setzen Sie Position und Massstab in den Eigenschaften. Das Werkzeug Ansicht platzieren setzt die gewählte Ansicht mit einem Klick auf das Blatt; geben Sie Positionen als Millimeter von der linken oberen Ecke ein oder bewegen Sie einen Cursor mit Strg oder Cmd und den Pfeiltasten und drücken Sie Strg oder Cmd mit Enter.";
    empty_sheet: "No sheet to show", "Kein Blatt anzuzeigen";
    status_sheet: "Sheet {name}", "Blatt {name}";
    status_viewports: "Viewports: {count}", "Ansichtsfenster: {count}";
    status_sheet_findings: "Layout findings: {count}", "Befunde am Blattaufbau: {count}";
    kind_sheet: "Sheet", "Blatt";
    group_sheets: "Sheets", "Blätter";
    kind_viewport: "Viewport", "Ansichtsfenster";
    group_viewports: "Viewports", "Ansichtsfenster";
    kind_sheet_revision: "Revision", "Änderung";
    group_sheet_revisions: "Revisions", "Änderungen";
    choice_landscape: "Landscape", "Querformat";
    choice_portrait: "Portrait", "Hochformat";
    field_paper: "Paper (A0 to A4, or width × height in mm)", "Papier (A0 bis A4 oder Breite × Höhe in mm)";
    field_orientation: "Orientation", "Ausrichtung";
    field_project_line: "Project line", "Projektzeile";
    field_drawn_by: "Drawn by", "Gezeichnet";
    field_checked_by: "Checked by", "Geprüft";
    field_date: "Date (year-month-day)", "Datum (Jahr-Monat-Tag)";
    field_revision_mark: "Current revision mark", "Aktueller Änderungsindex";
    field_scale_label: "Scale line", "Massstabszeile";
    field_sheet: "Sheet", "Blatt";
    field_view: "View", "Ansicht";
    field_mark: "Mark", "Index";
    field_sheet_size: "Paper size (mm)", "Papiergrösse (mm)";
    field_scales: "Scales", "Massstäbe";
    field_viewports: "Viewports", "Ansichtsfenster";
    field_findings: "Layout findings", "Befunde am Blattaufbau";
    field_window: "Window (mm)", "Ausschnitt (mm)";
    sheet_project: "Project", "Projekt";
    sheet_number: "Sheet no.", "Blatt-Nr.";
    sheet_title: "Title", "Bezeichnung";
    sheet_scale: "Scale", "Massstab";
    sheet_drawn_by: "Drawn by", "Gezeichnet";
    sheet_checked_by: "Checked by", "Geprüft";
    sheet_date: "Date", "Datum";
    sheet_revision: "Revision", "Änderung";
    sheet_rev_mark: "Mark", "Index";
    sheet_rev_date: "Date", "Datum";
    sheet_rev_description: "Description", "Beschreibung";
    sheet_rev_author: "By", "Von";
    utility_viewport: "Place View", "Ansicht platzieren";
    cmd_arm_viewport: "Arm Place View", "Ansicht platzieren aktivieren";
    cmd_arm_viewport_describe: "Arms the place view tool: a click on the sheet puts the selected view there as a viewport.", "Aktiviert das Werkzeug Ansicht platzieren: ein Klick auf das Blatt setzt die gewählte Ansicht dort als Ansichtsfenster.";
    cmd_export_sheets: "Export Sheets", "Blätter exportieren";
    cmd_export_sheets_describe: "Writes one sheet as an SVG file, or the sheet set as one PDF file with a page per sheet, as a cancellable job and hands the shell one download.", "Schreibt ein Blatt als SVG-Datei oder den Blattsatz als eine PDF-Datei mit einer Seite je Blatt, als abbrechbare Aufgabe, und übergibt der Oberfläche einen Download.";
    measure_export_sheets: "Export sheets", "Blätter exportieren";
    export_sheet_svg: "Sheet as SVG", "Blatt als SVG";
    export_sheets_pdf: "Sheets as PDF", "Blätter als PDF";
    fault_create_sheet_missing: "Create a sheet first.", "Legen Sie zuerst ein Blatt an.";
    fault_create_view_missing: "There is no plan, section or elevation to put on the sheet.", "Es gibt keinen Grundriss, Schnitt und keine Fassade, die auf das Blatt kämen.";
    fault_export_sheet_missing: "That sheet does not exist.", "Dieses Blatt gibt es nicht.";
    fault_export_sheets_none: "The model has no sheet to export.", "Das Modell hat kein Blatt zum Exportieren.";
    sch_surface_describe: "Table of one schedule; a row selects its element. The definition editor lists columns, sort keys, filters, grouping and scope as rows with buttons.", "Tabelle einer Bauteilliste; eine Zeile wählt ihr Bauteil aus. Der Definitionseditor listet Spalten, Sortierung, Filter, Gruppierung und Umfang als Zeilen mit Schaltflächen.";
    kind_property_template: "Property template", "Eigenschaftsvorlage";
    group_property_templates: "Property templates", "Eigenschaftsvorlagen";
    kind_classification_system: "Classification system", "Klassifikationssystem";
    group_classification_systems: "Classification systems", "Klassifikationssysteme";
    kind_classification_entry: "Classification entry", "Klassifikationseintrag";
    field_applies_to: "Applies to (kinds, comma separated)", "Gilt für (Arten, kommagetrennt)";
    field_edition: "Edition", "Ausgabe";
    field_source: "Source", "Quelle";
    field_definitions: "Property definitions", "Eigenschaftsdefinitionen";
    field_reached: "Holders with its properties", "Träger mit seinen Eigenschaften";
    field_entries: "Entries", "Einträge";
    field_classified: "Classified holders", "Klassifizierte Träger";
    section_effective: "Effective properties", "Wirksame Eigenschaften";
    section_templates: "Apply a template", "Vorlage anwenden";
    section_classification: "Classification", "Klassifizierung";
    section_definitions: "Add a property definition", "Eigenschaftsdefinition hinzufügen";
    section_entries: "Entry table", "Eintragstabelle";
    source_own: "own", "eigen";
    source_type: "from the type", "vom Typ";
    source_default: "default", "Vorgabe";
    issue_missing: "required, no value", "erforderlich, kein Wert";
    issue_kind: "value of the wrong type", "Wert vom falschen Typ";
    issue_below: "below the minimum", "unter dem Minimum";
    issue_above: "above the maximum", "über dem Maximum";
    issue_not_allowed: "not an allowed value", "kein zulässiger Wert";
    action_apply_template: "Apply template {name}", "Vorlage {name} anwenden";
    action_remove_classification: "Remove classification {name}", "Klassifizierung {name} entfernen";
    action_move_up: "Move {name} up", "{name} nach oben";
    action_move_down: "Move {name} down", "{name} nach unten";
    action_remove_definition: "Remove definition {name}", "Definition {name} entfernen";
    action_add_definition: "Add definition: Name or Name:type", "Definition hinzufügen: Name oder Name:Typ";
    def_name: "Name", "Name";
    def_kind: "Type (text, real, integer, boolean, length, area, volume, angle)", "Typ (text, real, integer, boolean, length, area, volume, angle)";
    def_unit: "Unit label", "Einheitenbezeichnung";
    def_description: "Description", "Beschreibung";
    def_required: "Required (true or false)", "Erforderlich (true oder false)";
    def_default: "Default value", "Vorgabewert";
    def_minimum: "Minimum", "Minimum";
    def_maximum: "Maximum", "Maximum";
    def_allowed: "Allowed values (separated by ;)", "Zulässige Werte (getrennt durch ;)";
    entry_add: "Add entry: code | title | parent", "Eintrag hinzufügen: Code | Titel | Übergeordnet";
    entry_retitle: "Retitle entry: code | title", "Eintrag umbenennen: Code | Titel";
    entry_reparent: "Move entry: code | parent (empty = root)", "Eintrag verschieben: Code | Übergeordnet (leer = Wurzel)";
    entry_remove: "Remove entry: code", "Eintrag entfernen: Code";
    panel_classification: "Classification", "Klassifizierung";
    classification_assign: "Assign {name}", "{name} zuweisen";
    classification_search: "Search code or title", "Code oder Titel suchen";
    classification_hits: "Matches", "Treffer";
    classification_none: "No classification system in the library.", "Kein Klassifikationssystem in der Bibliothek.";
    classification_surface_describe: "Tree of the entry tables of the classification systems; a search narrows the tree to the matches, a row assigns its code to the selected elements.", "Baum der Eintragstabellen der Klassifikationssysteme; eine Suche beschränkt den Baum auf die Treffer, eine Zeile weist ihren Code den gewählten Bauteilen zu.";
    cmd_apply_template: "Apply Template", "Vorlage anwenden";
    cmd_apply_template_describe: "Gives the given elements or types, or the selection, the defaults of a property set template.", "Gibt den angegebenen Bauteilen oder Typen oder der Auswahl die Vorgaben einer Eigenschaftsvorlage.";
    cmd_edit_template: "Edit Template", "Vorlage bearbeiten";
    cmd_edit_template_describe: "Adds, removes, moves or edits one property definition of a property set template.", "Fügt eine Eigenschaftsdefinition einer Eigenschaftsvorlage hinzu, entfernt, verschiebt oder ändert sie.";
    cmd_edit_classification: "Edit Classification System", "Klassifikationssystem bearbeiten";
    cmd_edit_classification_describe: "Adds, retitles, moves or removes one entry of the entry table of a classification system.", "Fügt einen Eintrag der Eintragstabelle eines Klassifikationssystems hinzu, benennt ihn um, verschiebt oder entfernt ihn.";
    cmd_search_classification: "Search Classification", "Klassifikation durchsuchen";
    cmd_search_classification_describe: "Selects the entries of a classification system whose code or title contains the text; an empty text clears the search.", "Wählt die Einträge eines Klassifikationssystems, deren Code oder Titel den Text enthält; ein leerer Text hebt die Suche auf.";
    arg_template: "Property template", "Eigenschaftsvorlage";
    arg_index: "Position", "Position";
    arg_parent: "Parent code", "Übergeordneter Code";
    arg_query: "Search text", "Suchtext";
    fault_classification_system_missing: "The classification system does not exist.", "Das Klassifikationssystem existiert nicht.";
    fault_classification_edit_invalid: "That entry edit makes no sense for the table.", "Diese Änderung ist für die Tabelle nicht sinnvoll.";
    fault_classification_entry_has_children: "Move or remove the children of the entry first.", "Verschieben oder entfernen Sie zuerst die Unterpunkte des Eintrags.";
    fault_classification_no_match: "No entry matches the search text.", "Kein Eintrag passt zum Suchtext.";
    fault_template_target_missing: "The property template does not exist.", "Die Eigenschaftsvorlage existiert nicht.";
    fault_template_not_applicable: "The template does not apply to that kind of element.", "Die Vorlage gilt nicht für diese Art von Bauteil.";
    fault_template_edit_invalid: "That edit makes no sense for the template.", "Diese Änderung ist für die Vorlage nicht sinnvoll.";
    fault_template_value_invalid: "That value does not fit the field.", "Dieser Wert passt nicht zum Feld.";
}
//#endregion 🔖️Labels

/// 🗣️ Resolves the label set of the addressed view's locale and terminology.
pub fn bim_labels(view_state: &semio_framework_plugin::ViewModel) -> &'static BimLabels {
    semio_framework_plugin::resolve_labels::<BimLabels>(view_state)
}

impl BimLabels {
    /// 🧩️ Fills the `{name}` placeholder of a label.
    pub fn named(text: semio_framework_ui_locale::LabelText, name: &str) -> String {
        text.as_str().replace("{name}", name)
    }

    /// 🧮️ Fills the `{count}` placeholder of a label.
    pub fn counted(text: semio_framework_ui_locale::LabelText, count: usize) -> String {
        text.as_str().replace("{count}", &count.to_string())
    }
}

#[cfg(test)]
#[path = "🧪️tests/🔬️unit/🦀️.rs"]
mod tests;
