/** 🧵️ Actual TrueType contour and component owners yield unhinted quadratic glyph geometry. */
import {FontReader,type FontFace,type FontOutlineLimits,type FontProgress} from "../🟦️.ts";
import type {PathSegment} from "../../../🟦️.ts";
import {UnitRetirement,type WorkRetirement} from "../../../🧹️retire/🟦️.ts";
export type FontPoint={x:number;y:number;onCurve:boolean};
export type GlyphOutline={glyph:number;segments:PathSegment[]};
type Component={glyph:number;flags:number;args:readonly[number,number];matrix:readonly[number,number,number,number];shift:readonly[number,number]};
type Frame={glyph:number;reader:FontReader;at:number;phase:string;contours:number;instructions:boolean;ends:number[];flags:number[];points:FontPoint[];index:number;repeat:number;flag:number;position:number;component:Component|null;child:number;copyAt:number;shift:readonly[number,number]};
const transform=(m:readonly[number,number,number,number],p:FontPoint):readonly[number,number]=>[m[0]*p.x+m[2]*p.y,m[1]*p.x+m[3]*p.y];
export class GlyphOutlineJob{
 private frames:Frame[]=[];private completed:Frame[]=[];private output:GlyphOutline;private root=-1;private phase="header";private contour=0;private point=0;private end=0;private first=0;private remaining=0;private last=-1;private totalPoints=0;private totalContours=0;private components=0;private work=0;private aborted=false;private transferred=false;private failure:unknown=null;
 constructor(private face:FontFace,glyph:number,private readonly limits:FontOutlineLimits){this.output={glyph,segments:[]};try{if(!Number.isInteger(glyph)||glyph<0||glyph>=face.glyphs||!Number.isInteger(limits.maxDepth)||limits.maxDepth<1||limits.maxDepth>32||!Number.isInteger(limits.maxPoints)||limits.maxPoints<1||limits.maxPoints>1048576||!Number.isInteger(limits.maxContours)||limits.maxContours<1||limits.maxContours>65536||!Number.isInteger(limits.maxComponents)||limits.maxComponents<1||limits.maxComponents>262144||!Number.isInteger(limits.maxSegments)||limits.maxSegments<1||limits.maxSegments>1048576||!Number.isInteger(limits.maxWork)||limits.maxWork<1||limits.maxWork>1e9)throw Error("Invalid font outline limits");this.frames.push(this.frame(glyph));}catch(error){this.failure=error;}}
 private frame(glyph:number):Frame{const f=this.face,r=new FontReader(f.bytes,f.loca.offset,f.loca.offset+f.loca.length),from=f.longLoca?r.u32(f.loca.offset+glyph*4):r.u16(f.loca.offset+glyph*2)*2,to=f.longLoca?r.u32(f.loca.offset+(glyph+1)*4):r.u16(f.loca.offset+(glyph+1)*2)*2;if(from>to||to>f.glyf.length)throw Error("Glyph source span invalid");return{glyph,reader:new FontReader(f.bytes,f.glyf.offset+from,f.glyf.offset+to),at:f.glyf.offset+from,phase:from===to?"done":"header",contours:0,instructions:false,ends:[],flags:[],points:[],index:0,repeat:0,flag:0,position:0,component:null,child:-1,copyAt:0,shift:[0,0]};}
 private pushPoint(frame:Frame,point:FontPoint):void{if(++this.totalPoints>this.limits.maxPoints)throw Error("Font retained point limit exceeded");frame.points.push(point);}
 private pushContour(frame:Frame,end:number):void{if(++this.totalContours>this.limits.maxContours)throw Error("Font retained contour limit exceeded");frame.ends.push(end);}
 private segment(value:PathSegment):void{if(this.output.segments.length===this.limits.maxSegments)throw Error("Font output segment limit exceeded");this.output.segments.push(value);}
 private step():void{
  if(this.phase==="contourStart"){const root=this.completed[this.root]!;if(this.contour===root.ends.length){this.phase="complete";return;}this.end=root.ends[this.contour]!;this.first=this.contour?root.ends[this.contour-1]!+1:0;const first=root.points[this.first]!,last=root.points[this.end]!;let start:readonly[number,number];if(first.onCurve){start=[first.x,first.y];this.point=this.first+1;this.remaining=this.end-this.first;}else if(last.onCurve){start=[last.x,last.y];this.point=this.first;this.remaining=this.end-this.first;}else{start=[(first.x+last.x)/2,(first.y+last.y)/2];this.point=this.first;this.remaining=this.end-this.first+1;}this.segment({kind:"move",to:start});this.phase="contour";return;}
  if(this.phase==="contour"){if(this.remaining===0){this.segment({kind:"close"});this.contour++;this.phase="contourStart";return;}const root=this.completed[this.root]!,index=this.point>this.end?this.first:this.point,p=root.points[index]!;if(p.onCurve){this.segment({kind:"line",to:[p.x,p.y]});this.point=index+1;this.remaining--;return;}const nextIndex=index===this.end?this.first:index+1,q=root.points[nextIndex]!;this.segment({kind:"quad",ctrl:[p.x,p.y],to:q.onCurve?[q.x,q.y]:[(p.x+q.x)/2,(p.y+q.y)/2]});const used=q.onCurve?Math.min(2,this.remaining):1;this.point=index+used;this.remaining-=used;return;}
  const frame=this.frames.at(-1)!;this.phase=frame.phase;const r=frame.reader;switch(frame.phase){
   case "header":{r.range(frame.at,10);frame.contours=r.i16(frame.at);frame.at+=10;if(frame.contours<-1||frame.contours>this.limits.maxContours)throw Error("Invalid font contour count");frame.phase=frame.contours<0?"component":frame.contours===0?"done":"endPoints";break;}
   case "endPoints":if(frame.ends.length<frame.contours){const end=r.u16(frame.at);frame.at+=2;if(frame.ends.length&&end<=frame.ends.at(-1)!)throw Error("Font contour endpoints are not ordered");if(end+1>this.limits.maxPoints)throw Error("Font glyph point limit exceeded");this.pushContour(frame,end);break;}r.range(frame.at,2);{const instructions=r.u16(frame.at);frame.at+=2;r.range(frame.at,instructions);frame.at+=instructions;}frame.phase="flags";break;
   case "flags":{const count=frame.ends.at(-1)!+1;if(frame.flags.length===count){frame.index=0;frame.position=0;frame.phase="x";break;}if(frame.repeat){frame.repeat--;}else{frame.flag=r.u8(frame.at++);if(frame.flag&8){frame.repeat=r.u8(frame.at++);if(frame.flags.length+frame.repeat+1>count)throw Error("Font repeated flag exceeds point authority");}}frame.flags.push(frame.flag);break;}
   case "x":{if(frame.index===frame.flags.length){frame.index=0;frame.position=0;frame.phase="y";break;}const flag=frame.flags[frame.index++]!;let delta=0;if(flag&2){delta=r.u8(frame.at++);if(!(flag&16))delta=-delta;}else if(!(flag&16)){delta=r.i16(frame.at);frame.at+=2;}frame.position+=delta;this.pushPoint(frame,{x:frame.position,y:0,onCurve:!!(flag&1)});break;}
   case "y":{if(frame.index===frame.flags.length){frame.phase="done";break;}const flag=frame.flags[frame.index]!;let delta=0;if(flag&4){delta=r.u8(frame.at++);if(!(flag&32))delta=-delta;}else if(!(flag&32)){delta=r.i16(frame.at);frame.at+=2;}frame.position+=delta;frame.points[frame.index++]!.y=frame.position;break;}
   case "component":{if(++this.components>this.limits.maxComponents)throw Error("Font component limit exceeded");const flags=r.u16(frame.at),glyph=r.u16(frame.at+2);frame.instructions ||= !!(flags&256);frame.at+=4;if(glyph>=this.face.glyphs||this.frames.some(value=>value.glyph===glyph))throw Error("Cyclic or invalid font component");if(this.frames.length===this.limits.maxDepth)throw Error("Font component depth limit exceeded");let args:readonly[number,number];if(flags&1){args=flags&2?[r.i16(frame.at),r.i16(frame.at+2)]:[r.u16(frame.at),r.u16(frame.at+2)];frame.at+=4;}else{args=flags&2?[r.i8(frame.at),r.i8(frame.at+1)]:[r.u8(frame.at),r.u8(frame.at+1)];frame.at+=2;}let matrix:[number,number,number,number]=[1,0,0,1];const scale=()=>{const value=r.i16(frame.at)/16384;frame.at+=2;return value;};const transforms=Number(!!(flags&8))+Number(!!(flags&64))+Number(!!(flags&128));if(transforms>1||(flags&2048)&&(flags&4096))throw Error("Invalid font component transform flags");if(flags&8){matrix[0]=matrix[3]=scale();}else if(flags&64){matrix[0]=scale();matrix[3]=scale();}else if(flags&128){matrix=[scale(),scale(),scale(),scale()];}let shift:readonly[number,number]=flags&2?args:[0,0];if(flags&2&&flags&2048)shift=transform(matrix,{x:args[0],y:args[1],onCurve:true});frame.component={glyph,flags,args,matrix,shift};frame.phase="waiting";this.frames.push(this.frame(glyph));break;}
   case "copyPoints":{const child=this.completed[frame.child]!,component=frame.component!;if(frame.copyAt<child.points.length){const point=child.points[frame.copyAt++]!,mapped=transform(component.matrix,point);this.pushPoint(frame,{x:mapped[0]+frame.shift[0],y:mapped[1]+frame.shift[1],onCurve:point.onCurve});break;}frame.copyAt=0;frame.phase="copyContours";break;}
   case "copyContours":{const child=this.completed[frame.child]!;if(frame.copyAt<child.ends.length){this.pushContour(frame,frame.index+child.ends[frame.copyAt++]!);break;}const flags=frame.component!.flags;frame.component=null;frame.child=-1;if(flags&32){frame.phase="component";}else{if(frame.instructions){const count=r.u16(frame.at);frame.at+=2;r.range(frame.at,count);frame.at+=count;}frame.phase="done";}break;}
   case "done":{this.frames.pop();const index=this.completed.length;this.completed.push(frame);if(!this.frames.length){this.root=index;this.phase="contourStart";break;}const parent=this.frames.at(-1)!,component=parent.component!;parent.child=index;parent.copyAt=0;parent.index=parent.points.length;parent.shift=component.shift;if(!(component.flags&2)){const anchor=parent.points[component.args[0]],target=frame.points[component.args[1]];if(!anchor||!target)throw Error("Font component point attachment exceeds authority");const mapped=transform(component.matrix,target);parent.shift=[anchor.x-mapped[0],anchor.y-mapped[1]];}parent.phase="copyPoints";break;}
   default:throw Error("Font outline stage invalid");
  }
 }
 advance(grant:number):FontProgress{if(!Number.isSafeInteger(grant)||grant<1)throw Error("Invalid glyph work grant");if(this.aborted||this.transferred)throw Error("Font outline cancelled");if(this.failure)throw this.failure;try{for(let turn=0;turn<grant&&this.phase!=="complete";turn++){if(this.work>=this.limits.maxWork)throw Error("Font outline work limit exceeded");this.step();this.work++;}}catch(error){this.failure=error;throw error;}return{phase:this.phase,work:this.work,done:this.phase==="complete"};}
 result():GlyphOutline{if(this.aborted||this.transferred||this.failure||this.phase!=="complete")throw Error("Font outline incomplete");return this.output;}
 cancel():void{this.aborted=true;}
 intoRetirement():{job:WorkRetirement;output:GlyphOutline|null}{if(this.transferred)throw Error("Font outline ownership already transferred");const output=!this.aborted&&!this.failure&&this.phase==="complete"?this.result():null;this.transferred=true;this.aborted=true;let stage=0;return{output,job:new UnitRetirement(()=>{const list=this.frames.length?this.frames:this.completed;if(list.length){const frame=list.at(-1)!;if(frame.points.length){frame.points.pop();return false;}if(frame.flags.length){frame.flags.pop();return false;}if(frame.ends.length){frame.ends.pop();return false;}list.pop();return false;}if(!output&&this.output.segments.length){this.output.segments.pop();return false;}if(stage===0){this.output={glyph:0,segments:[]};stage++;return false;}this.face=null as unknown as FontFace;return true;})};}
}
