import type { Binary64 } from "../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
export interface DwgLogicalLayer { name: string; color: number; }
export type DwgLogicalGeometryKind = 'point' | 'line' | 'circle' | 'arc' | 'ellipse' | 'lwPolyline' | 'spline' | 'text' | 'face3d' | 'polyline3d' | 'polyfaceMesh';
export interface DwgLogicalGeometry { kind: DwgLogicalGeometryKind; values: Binary64[]; indices: number[]; text: string; closed: boolean; }
export type DwgEntityMode = 'explicitOwner' | 'paperSpace' | 'modelSpace' | 'reserved';
export type DwgEntityReferenceMode = 'byLayer' | 'byBlock' | 'continuous' | 'explicit';
export interface DwgEntityColor { kind: 'byLayer' | 'byBlock' | 'index' | 'trueColor'; index: number; rgb: number; transparency?: number; name?: string; bookName?: string; colorHandle?: bigint; }
export interface DwgEntityCommon { mode: DwgEntityMode; color: DwgEntityColor; linetypeScale: Binary64; linetype: DwgEntityReferenceMode; plotStyle: DwgEntityReferenceMode; material: DwgEntityReferenceMode; shadow: number; invisible: number; lineweight: number; layerHandle: bigint; linetypeHandle?: bigint; materialHandle?: bigint; shadowHandle?: bigint; plotStyleHandle?: bigint; fullVisualStyleHandle?: bigint; faceVisualStyleHandle?: bigint; edgeVisualStyleHandle?: bigint; }
export interface DwgLineEntity { common: DwgEntityCommon; start: Binary64[]; end: Binary64[]; thickness: Binary64; extrusion: Binary64[]; }
export interface DwgArcEntity { common: DwgEntityCommon; center: Binary64[]; radius: Binary64; thickness: Binary64; extrusion: Binary64[]; startAngle: Binary64; endAngle: Binary64; }
export interface DwgLwPolylineVertex { point: Binary64[]; bulge: Binary64; vertexId?: number; startWidth?: Binary64; endWidth?: Binary64; }
export interface DwgLwPolylineEntity { common: DwgEntityCommon; closed: boolean; constantWidth?: Binary64; elevation: Binary64; thickness: Binary64; extrusion: Binary64[]; vertices: DwgLwPolylineVertex[]; }
export interface DwgBlockBeginEntity { common: DwgEntityCommon; }
export interface DwgBlockEndEntity { common: DwgEntityCommon; }
export interface DwgInsertEntity { common: DwgEntityCommon; insertion: Binary64[]; scale: Binary64[]; rotation: Binary64; extrusion: Binary64[]; blockHeaderHandle: bigint; attributeHandles: bigint[]; sequenceEndHandle?: bigint; }
export type DwgDimensionTextAttachment = 'topCenter' | 'topLeft' | 'topRight' | 'middleCenter' | 'middleLeft' | 'middleRight' | 'bottomCenter' | 'bottomLeft' | 'bottomRight';
export type DwgDimensionLineSpacingStyle = 'atLeast' | 'exact';
export interface DwgDimensionStatus { blockReferenceIsExclusive: boolean; userPositionedText: boolean; }
export interface DwgDimensionEntityCommon { common: DwgEntityCommon; extrusion: Binary64[]; textMidpoint: Binary64[]; elevation: Binary64; status: DwgDimensionStatus; userText: string; textRotation: Binary64; horizontalDirection: Binary64; insertionScale: Binary64[]; insertionRotation: Binary64; attachment: DwgDimensionTextAttachment; lineSpacingStyle: DwgDimensionLineSpacingStyle; lineSpacingFactor: Binary64; actualMeasurement: Binary64; flipArrow1: boolean; flipArrow2: boolean; cloneInsertionPoint: Binary64[]; dimensionStyleHandle: bigint; dimensionBlockHandle?: bigint; }
export interface DwgLinearDimensionEntity { dimension: DwgDimensionEntityCommon; extensionLine1: Binary64[]; extensionLine2: Binary64[]; definitionPoint: Binary64[]; obliqueAngle: Binary64; dimensionRotation: Binary64; }
export type DwgViewportStatusFlag = 'perspective' | 'frontClipping' | 'backClipping' | 'ucsFollow' | 'frontClipNotAtEye' | 'ucsIconVisible' | 'ucsIconAtOrigin' | 'fastZoom' | 'snap' | 'grid' | 'isometricSnap' | 'hidePlot' | 'isoPairTop' | 'isoPairRight' | 'zoomLock' | 'alwaysEnabled' | 'nonRectangularClipping' | 'viewportOff' | 'gridBeyondDrawingLimits' | 'adaptiveGrid' | 'adaptiveSubdivision' | 'gridFollowsWorkplane';
export type DwgViewportRenderMode = 'optimized2d' | 'wireframe' | 'hiddenLine' | 'flatShaded' | 'gouraudShaded' | 'flatShadedWithWireframe' | 'gouraudShadedWithWireframe';
export type DwgOrthographicView = 'none' | 'top' | 'bottom' | 'front' | 'back' | 'left' | 'right';
export type DwgShadePlotMode = 'asDisplayed' | 'wireframe' | 'hidden' | 'rendered';
export type DwgDefaultLightingType = 'oneDistantLight' | 'twoDistantLights';
export interface DwgViewportEntity { common: DwgEntityCommon; center: Binary64[]; width: Binary64; height: Binary64; viewTarget: Binary64[]; viewDirection: Binary64[]; twistAngle: Binary64; viewHeight: Binary64; lensLength: Binary64; frontClip: Binary64; backClip: Binary64; snapAngle: Binary64; viewCenter: Binary64[]; snapBase: Binary64[]; snapUnit: Binary64[]; gridUnit: Binary64[]; circleZoomPercent: number; gridMajor: number; frozenLayerHandles: bigint[]; status: DwgViewportStatusFlag[]; styleSheet: string; renderMode: DwgViewportRenderMode; ucsAtOrigin: boolean; ucsPerViewport: boolean; ucsOrigin: Binary64[]; ucsXAxis: Binary64[]; ucsYAxis: Binary64[]; ucsElevation: Binary64; orthographicView: DwgOrthographicView; shadePlotMode: DwgShadePlotMode; useDefaultLights: boolean; defaultLightingType: DwgDefaultLightingType; brightness: Binary64; contrast: Binary64; ambientColor: DwgComplexColor; clipBoundaryHandle?: bigint; namedUcsHandle?: bigint; baseUcsHandle?: bigint; backgroundHandle?: bigint; visualStyleHandle?: bigint; shadePlotHandle?: bigint; sunHandle?: bigint; }
export interface DwgPointEntity { common: DwgEntityCommon; point: Binary64[]; thickness: Binary64; extrusion: Binary64[]; xAxisAngle: Binary64; }
export interface DwgCircleEntity { common: DwgEntityCommon; center: Binary64[]; radius: Binary64; thickness: Binary64; extrusion: Binary64[]; }
export interface DwgEllipseEntity { common: DwgEntityCommon; center: Binary64[]; majorAxis: Binary64[]; extrusion: Binary64[]; axisRatio: Binary64; startParameter: Binary64; endParameter: Binary64; }
export interface DwgTextEntity { common: DwgEntityCommon; elevation: Binary64; insertion: Binary64[]; alignment?: Binary64[]; extrusion: Binary64[]; thickness: Binary64; obliqueAngle: Binary64; rotation: Binary64; height: Binary64; widthFactor: Binary64; value: string; generation: number; horizontalAlignment: number; verticalAlignment: number; styleHandle: bigint; }
export interface DwgSplineEntity { common: DwgEntityCommon; degree: number; rational: boolean; closed: boolean; periodic: boolean; knotTolerance: Binary64; controlTolerance: Binary64; knots: Binary64[]; controlPoints: Binary64[]; weights: Binary64[]; }
export interface DwgFace3dEntity { common: DwgEntityCommon; corners: Binary64[]; invisibleEdges: number; }
export interface DwgPolyline3dEntity { common: DwgEntityCommon; curveType: number; flags: number; vertexHandles: bigint[]; sequenceEndHandle: bigint; }
export interface DwgPolyfaceMeshEntity { common: DwgEntityCommon; vertexCount: number; faceCount: number; vertexHandles: bigint[]; sequenceEndHandle: bigint; }
export interface DwgVertexEntity { common: DwgEntityCommon; flags: number; point: Binary64[]; }
export interface DwgPolyfaceFaceEntity { common: DwgEntityCommon; indices: number[]; }
export interface DwgSequenceEndEntity { common: DwgEntityCommon; }
export type DwgEntityBody = { kind: 'line'; value: DwgLineEntity } | { kind: 'arc'; value: DwgArcEntity } | { kind: 'lwPolyline'; value: DwgLwPolylineEntity } | { kind: 'blockBegin'; value: DwgBlockBeginEntity } | { kind: 'blockEnd'; value: DwgBlockEndEntity } | { kind: 'insert'; value: DwgInsertEntity } | { kind: 'dimensionLinear'; value: DwgLinearDimensionEntity } | { kind: 'viewport'; value: DwgViewportEntity } | { kind: 'point'; value: DwgPointEntity } | { kind: 'circle'; value: DwgCircleEntity } | { kind: 'ellipse'; value: DwgEllipseEntity } | { kind: 'text'; value: DwgTextEntity } | { kind: 'spline'; value: DwgSplineEntity } | { kind: 'face3d'; value: DwgFace3dEntity } | { kind: 'polyline3d'; value: DwgPolyline3dEntity } | { kind: 'polyfaceMesh'; value: DwgPolyfaceMeshEntity } | { kind: 'vertex'; value: DwgVertexEntity } | { kind: 'polyfaceFace'; value: DwgPolyfaceFaceEntity } | { kind: 'sequenceEnd'; value: DwgSequenceEndEntity };
export type DwgObjectCategory = 'entity' | 'tableControl' | 'tableRecord' | 'dictionary' | 'object' | 'custom';
export interface DwgNamedReference { name: string; handle: bigint; }
export type DwgXRecordValue = { kind: 'string'; groupCode: number; value: string } | { kind: 'real'; groupCode: number; value: Binary64 } | { kind: 'boolean'; groupCode: number; value: boolean } | { kind: 'integer8' | 'integer16' | 'integer32'; groupCode: number; value: number } | { kind: 'integer64'; groupCode: number; value: bigint } | { kind: 'point3d'; groupCode: number; value: [Binary64,Binary64,Binary64] } | { kind: 'binary'; groupCode: number; octets: number[] } | { kind: 'handle'; groupCode: number; value: bigint } | { kind: 'objectId'; groupCode: number; absoluteValue: bigint };
export interface DwgDictionaryBody { entries: DwgNamedReference[]; cloningFlag: number; hardOwner: boolean; defaultEntryHandle?: bigint; }
export interface DwgTableControlEntry { handle?: bigint; }
export interface DwgTableControlEntries { entryHandles: DwgTableControlEntry[]; }
export interface DwgBlockTableControl { entryHandles: DwgTableControlEntry[]; modelSpaceHandle?: bigint; paperSpaceHandle?: bigint; }
export interface DwgLinetypeTableControl { entryHandles: DwgTableControlEntry[]; byBlockHandle: bigint; byLayerHandle: bigint; }
export interface DwgDimensionStyleTableControl { entryHandles: DwgTableControlEntry[]; additionalHandles: bigint[]; }
export type DwgTableControlBody = { kind:'block';value:DwgBlockTableControl }|{kind:'layer'|'textStyle'|'view'|'ucs'|'viewport'|'registeredApplication';value:DwgTableControlEntries}|{kind:'linetype';value:DwgLinetypeTableControl}|{kind:'dimensionStyle';value:DwgDimensionStyleTableControl};
export interface DwgTableRecordCommon { name:string;xrefResolution:number;xrefHandle?:bigint; }
export interface DwgRegisteredApplicationTableRecord { common:DwgTableRecordCommon;group71:number; }
export interface DwgTextStyleTableRecord { common:DwgTableRecordCommon;isShape:boolean;isVertical:boolean;textSize:Binary64;widthFactor:Binary64;obliqueAngle:Binary64;generation:number;lastHeight:Binary64;fontFile:string;bigFontFile:string; }
export interface DwgLayerTableRecord { common:DwgTableRecordCommon;frozen:boolean;off:boolean;frozenInNewViewports:boolean;locked:boolean;plottable:boolean;lineweight:number;color:DwgComplexColor;plotStyleHandle?:bigint;materialHandle?:bigint;linetypeHandle?:bigint; }
export interface DwgLinetypeDash { length:Binary64;complexShapeCode:number;styleHandle?:bigint;xOffset:Binary64;yOffset:Binary64;scale:Binary64;rotation:Binary64;shapeFlags:number;text?:string; }
export interface DwgLinetypeTableRecord { common:DwgTableRecordCommon;description:string;patternLength:Binary64;alignment:number;dashes:DwgLinetypeDash[]; }
export interface DwgBlockHeaderTableRecord { common:DwgTableRecordCommon;anonymous:boolean;hasAttributes:boolean;isXref:boolean;xrefOverlaid:boolean;xrefLoaded:boolean;ownedEntityHandles:bigint[];basePoint:[Binary64,Binary64,Binary64];xrefPath:string;insertBackreferenceHandles:bigint[];description:string;insertUnits:number;explodable:boolean;blockScaling:number;blockEntityHandle:bigint;endBlockEntityHandle:bigint;layoutHandle?:bigint; }
export interface DwgViewportTableRecord { common:DwgTableRecordCommon;viewHeight:Binary64;viewWidth:Binary64;center:[Binary64,Binary64];target:[Binary64,Binary64,Binary64];direction:[Binary64,Binary64,Binary64];twist:Binary64;lensLength:Binary64;frontClipping:Binary64;backClipping:Binary64;viewMode:[boolean,boolean,boolean,boolean];renderMode:number;useDefaultLights:boolean;defaultLightingType:number;brightness:Binary64;contrast:Binary64;ambientColor:DwgComplexColor;lowerLeft:[Binary64,Binary64];upperRight:[Binary64,Binary64];ucsFollow:boolean;circleZoom:number;fastZoom:boolean;ucsIcon:number;gridMode:boolean;gridUnit:[Binary64,Binary64];snapMode:boolean;snapStyle:boolean;snapIsopair:number;snapAngle:Binary64;snapBase:[Binary64,Binary64];snapUnit:[Binary64,Binary64];ucsAtOrigin:boolean;ucsViewport:boolean;ucsOrigin:[Binary64,Binary64,Binary64];ucsXAxis:[Binary64,Binary64,Binary64];ucsYAxis:[Binary64,Binary64,Binary64];ucsElevation:Binary64;ucsOrthographicView:number;gridFlags:number;gridMajor:number;backgroundHandle?:bigint;visualStyleHandle?:bigint;sunHandle?:bigint;namedUcsHandle?:bigint;baseUcsHandle?:bigint; }
export interface DwgDimensionGeometry { scale:Binary64;arrowSize:Binary64;extensionOriginOffset:Binary64;dimensionLineIncrement:Binary64;extensionLineExtension:Binary64;rounding:Binary64;dimensionLineExtension:Binary64;plusTolerance:Binary64;minusTolerance:Binary64;fixedExtensionLength:Binary64;jogAngle:Binary64; }
export interface DwgDimensionBehavior { tolerance:boolean;limits:boolean;textInsideHorizontal:boolean;textOutsideHorizontal:boolean;suppressExtension1:boolean;suppressExtension2:boolean;textVerticalAlignment:number;zeroSuppression:number;angularZeroSuppression:number;arcSymbol:number; }
export interface DwgDimensionText { height:Binary64;centerMarkSize:Binary64;tickSize:Binary64;alternateScale:Binary64;linearScale:Binary64;verticalPosition:Binary64;toleranceScale:Binary64;gap:Binary64;alternateRounding:Binary64;alternateEnabled:boolean;alternateDecimals:number;textOutsideExtensions:boolean;separateArrowheads:boolean;forceTextInside:boolean;suppressOutsideExtensions:boolean;dimensionLineColor:DwgComplexColor;extensionLineColor:DwgComplexColor;textColor:DwgComplexColor; }
export interface DwgDimensionUnits { alternateDecimalPlaces:number;decimalPlaces:number;toleranceDecimalPlaces:number;alternateUnits:number;alternateToleranceDecimalPlaces:number;angularUnits:number;fractionFormat:number;linearUnits:number;decimalSeparator:number;textMovement:number;textHorizontalAlignment:number;suppressDimensionLine1:boolean;suppressDimensionLine2:boolean;toleranceVerticalAlignment:number;toleranceZeroSuppression:number;alternateZeroSuppression:number;alternateToleranceZeroSuppression:number;userPositionedText:boolean;arrowTextFit:number; }
export interface DwgDimensionR2010 { fixedExtensionEnabled:boolean;textDirection:boolean;alternateMeasurementFactor:Binary64;alternateMeasurementSuffix:string;measurementFactor:Binary64;measurementSuffix:string;dimensionLineweight:number;extensionLineweight:number;flag:boolean; }
export interface DwgDimensionStyleTableRecord { common:DwgTableRecordCommon;dimensionPostfix:string;alternatePostfix:string;geometry:DwgDimensionGeometry;fillMode:number;fillColor:DwgComplexColor;behavior:DwgDimensionBehavior;text:DwgDimensionText;units:DwgDimensionUnits;r2010:DwgDimensionR2010;textStyleHandle?:bigint;leaderArrowHandle?:bigint;arrowHandle?:bigint;arrow1Handle?:bigint;arrow2Handle?:bigint;dimensionLinetypeHandle?:bigint;extension1LinetypeHandle?:bigint;extension2LinetypeHandle?:bigint; }
export type DwgTableRecordBody={kind:'registeredApplication';value:DwgRegisteredApplicationTableRecord}|{kind:'textStyle';value:DwgTextStyleTableRecord}|{kind:'layer';value:DwgLayerTableRecord}|{kind:'linetype';value:DwgLinetypeTableRecord}|{kind:'blockHeader';value:DwgBlockHeaderTableRecord}|{kind:'viewport';value:DwgViewportTableRecord}|{kind:'dimensionStyle';value:DwgDimensionStyleTableRecord};
export interface DwgXRecordBody { values: DwgXRecordValue[]; objectIdHandles: bigint[]; cloningFlag: number; }
export type DwgAssociativeDependencyStatus = 'upToDate';
export interface DwgAssociativeDependency { status: DwgAssociativeDependencyStatus; isReadDependency: boolean; isWriteDependency: boolean; isAttachedToObject: boolean; isDelegatingToOwningAction: boolean; order: number; dependentOnObjectHandle: bigint; name?: string; readDependencyHandle?: bigint; dependencyNodeHandle?: bigint; dependencyBodyHandle?: bigint; dependencyBodyId: number; }
export type DwgEvaluationVariant = { kind: 'integer32'; value: number };
export interface DwgAssociativeValueDependency { dependency: DwgAssociativeDependency; cachedValue: DwgEvaluationVariant; valueName: string; }
export interface DwgAssociativeGeometryDependency { dependency: DwgAssociativeDependency; enabled: boolean; persistentSubentityClassName: string; dependentOnCompoundObject: boolean; }
export type DwgEvaluationExpressionValue = { kind: 'empty' } | { kind: 'double'; value: Binary64 } | { kind: 'pointGroup10' | 'pointGroup11'; value: Binary64[] } | { kind: 'string'; value: string } | { kind: 'integer32' | 'integer16'; value: number } | { kind: 'objectReference'; value: bigint };
export interface DwgEvaluationExpression { parentId: number; majorVersion: number; minorVersion: number; value: DwgEvaluationExpressionValue; nodeId: number; }
export interface DwgBlockGripLocationComponent { evaluationExpression: DwgEvaluationExpression; gripType: number; gripExpression: string; }
export interface DwgDynamicBlockProxyNode { evaluationExpression: DwgEvaluationExpression; }
export interface DwgAssociativeActionDependency { owned: boolean; dependencyHandle: bigint; }
export interface DwgAssociativeAction { status: 'upToDate'; owningNetworkHandle?: bigint; actionBodyHandle?: bigint; actionIndex: number; maximumDependencyIndex: number; dependencies: DwgAssociativeActionDependency[]; }
export interface DwgAssociativeVariable { action: DwgAssociativeAction; name: string; expression: string; evaluatorId: string; description: string; evaluatedValue: DwgEvaluationVariant; mergeable: boolean; mergeableVariableName?: string; mustMerge: boolean; referencedValueDependencyHandles: bigint[]; }
export interface DwgAssociativeDimensionDependencyBody { name: string; }
export type DwgComplexColorValue = { kind: 'none' | 'byLayer' | 'byBlock' | 'foreground' | 'layerOff' | 'layerFrozen' } | { kind: 'byColor'; red: number; green: number; blue: number } | { kind: 'byAci'; index: number } | { kind: 'byPen'; index: number };
export interface DwgComplexColor { index: number; value: DwgComplexColorValue; name?: string; bookName?: string; }
export type DwgVisualStylePropertyOperation = 'inherit' | 'set' | 'disable' | 'enable';
export interface DwgVisualStyleProperty<T> { value: T; operation: DwgVisualStylePropertyOperation; }
export interface DwgVisualStyleProperties { faceLightingModel: DwgVisualStyleProperty<number>; faceLightingQuality: DwgVisualStyleProperty<number>; faceColorMode: DwgVisualStyleProperty<number>; faceModifiers: DwgVisualStyleProperty<number>; faceOpacity: DwgVisualStyleProperty<Binary64>; faceSpecularAmount: DwgVisualStyleProperty<Binary64>; faceMonochromeColor: DwgVisualStyleProperty<DwgComplexColor>; edgeModel: DwgVisualStyleProperty<number>; edgeStyles: DwgVisualStyleProperty<number>; edgeIntersectionColor: DwgVisualStyleProperty<DwgComplexColor>; edgeObscuredColor: DwgVisualStyleProperty<DwgComplexColor>; edgeObscuredLinePattern: DwgVisualStyleProperty<number>; edgeIntersectionLinePattern: DwgVisualStyleProperty<number>; edgeCreaseAngle: DwgVisualStyleProperty<Binary64>; edgeModifiers: DwgVisualStyleProperty<number>; edgeColor: DwgVisualStyleProperty<DwgComplexColor>; edgeOpacity: DwgVisualStyleProperty<Binary64>; edgeWidth: DwgVisualStyleProperty<number>; edgeOverhang: DwgVisualStyleProperty<number>; edgeJitter: DwgVisualStyleProperty<number>; edgeSilhouetteColor: DwgVisualStyleProperty<DwgComplexColor>; edgeSilhouetteWidth: DwgVisualStyleProperty<number>; edgeHaloGap: DwgVisualStyleProperty<number>; edgeIsolines: DwgVisualStyleProperty<number>; hiddenEdgePrecision: DwgVisualStyleProperty<boolean>; displaySettings: DwgVisualStyleProperty<number>; displayBrightness: DwgVisualStyleProperty<Binary64>; displayShadowType: DwgVisualStyleProperty<number>; }
export interface DwgVisualStyle { description: string; styleType: number; extensionLightingModel: number; internalOnly: boolean; properties: DwgVisualStyleProperties; }
export interface DwgBlockParameterDependencyBody { name: string; }
export interface DwgBlockRepresentationData { representedBlockHeaderHandle: bigint; }
export interface DwgDynamicBlockPurgePreventer { protectedBlockHeaderHandle: bigint; }
export interface DwgEvaluationGraphNode { id: number; expressionHandle: bigint; }
export interface DwgEvaluationGraphEdge { fromNodeId: number; toNodeId: number; referenceCount: number; invertible: boolean; suppressed: boolean; }
export interface DwgEvaluationGraph { nodes: DwgEvaluationGraphNode[]; edges: DwgEvaluationGraphEdge[]; }
export interface DwgBlockParameterConnection { code: number; name: string; }
export interface DwgBlockParameterProperty { connections: DwgBlockParameterConnection[]; }
export type DwgBlockParameterBaseLocation = 'startPoint' | 'midpoint';
export interface DwgBlockFlipValueSet { baseLabel: string; flippedLabel: string; }
export interface DwgNamedEvaluationNodeReference { nodeId: number; expressionName: string; }
export interface DwgBlockFlipParameter { evaluationExpression: DwgEvaluationExpression; name: string; showProperties: boolean; chainActions: boolean; definitionBase: Binary64[]; definitionEnd: Binary64[]; properties: DwgBlockParameterProperty[]; baseLocation: DwgBlockParameterBaseLocation; label: string; description: string; valueSet: DwgBlockFlipValueSet; labelPoint: Binary64[]; updatedFlip: DwgNamedEvaluationNodeReference; }
export type DwgVisibilityEvaluationHistory = 'stateless' | 'required';
export interface DwgVisibilityState { name: string; visibleEntityHandles: bigint[]; controlledExpressionHandles: bigint[]; }
export interface DwgBlockVisibilityParameter { evaluationExpression: DwgEvaluationExpression; elementName: string; showProperties: boolean; chainActions: boolean; definitionPoint: Binary64[]; properties: DwgBlockParameterProperty[]; updatedVisibilityNodeId: number; initialized: boolean; name: string; description: string; evaluationHistory: DwgVisibilityEvaluationHistory; eligibleEntityHandles: bigint[]; states: DwgVisibilityState[]; }
export type DwgPlaceholder = Record<string, never>;
export interface DwgDictionaryVariable { value: string; }
export interface DwgAnnotationScale { name: string; paperUnits: Binary64; drawingUnits: Binary64; isUnitScale: boolean; }
export interface DwgDrawOrderEntry { entityHandle: bigint; sortHandle: bigint; }
export interface DwgSortEntitiesTable { blockHeaderHandle: bigint; entries: DwgDrawOrderEntry[]; }
export interface DwgCellContentFormat { propertyOverrideFlags: number; propertyFlags: number; valueDataType: number; valueUnitType: number; valueFormatString: string; rotation: Binary64; blockScale: Binary64; alignment: number; contentColor: DwgComplexColor; textStyleHandle?: bigint; textHeight: Binary64; }
export interface DwgCellMargins { vertical: Binary64; horizontal: Binary64; bottom: Binary64; right: Binary64; horizontalSpacing: Binary64; verticalSpacing: Binary64; }
export interface DwgCellBorder { overrideFlags: number; borderType: number; color: DwgComplexColor; lineweight: number; linetypeHandle?: bigint; visible: number; doubleLineSpacing: Binary64; }
export interface DwgCellBorders { top?: DwgCellBorder; horizontalInside?: DwgCellBorder; bottom?: DwgCellBorder; left?: DwgCellBorder; verticalInside?: DwgCellBorder; right?: DwgCellBorder; }
export interface DwgCellStyle { propertyOverrideFlags: number; mergeFlags: number; backgroundColor: DwgComplexColor; contentLayout: number; contentFormat: DwgCellContentFormat; margins: DwgCellMargins; borders: DwgCellBorders; }
export interface DwgTableStyle { description: string; bitFlags: number; templateStyleHandle?: bigint; table: DwgCellStyle; title: DwgCellStyle; header: DwgCellStyle; data: DwgCellStyle; }
export type DwgMlineLinetype = 'byLayer' | 'byBlock' | 'continuous';
export interface DwgMlineCaps { square: boolean; innerArcs: boolean; roundOuterArcs: boolean; }
export interface DwgMlineStyleElement { offset: Binary64; color: DwgComplexColor; linetype: DwgMlineLinetype; }
export interface DwgMlineStyle { name: string; description: string; fillEnabled: boolean; displayMiters: boolean; startCaps: DwgMlineCaps; endCaps: DwgMlineCaps; fillColor: DwgComplexColor; startAngle: Binary64; endAngle: Binary64; elements: DwgMlineStyleElement[]; }
export type DwgMLeaderContentType='none'|'block'|'mText';
export type DwgMLeaderDrawOrder='leaderFirst'|'contentFirst';
export type DwgMLeaderLeaderOrder='headFirst'|'tailFirst';
export type DwgMLeaderKind='invisible'|'straight'|'spline';
export type DwgMLeaderTextAttachment='topOfTop'|'middleOfTop'|'middle'|'middleOfBottom'|'bottomOfBottom'|'bottomLine'|'bottomOfTop'|'bottomOfTopUnderline'|'bottomOfTopNoUnderline'|'center';
export type DwgMLeaderTextAngle='horizontal'|'aligned'|'alwaysRightReading';
export type DwgMLeaderTextAlignment='left'|'center'|'right';
export type DwgMLeaderAttachmentDirection='horizontal'|'vertical';
export type DwgMLeaderBlockConnection='extents'|'basePoint';
export interface DwgMLeaderLeaderStyle { kind:DwgMLeaderKind;color:DwgComplexColor;linetypeStyleHandle:bigint;lineweight:number; }
export interface DwgMLeaderLanding { enabled:boolean;gap:Binary64; }
export interface DwgMLeaderDogleg { enabled:boolean;length:Binary64; }
export interface DwgMLeaderArrow { symbolHandle?:bigint;size:Binary64; }
export interface DwgMLeaderTextStyle { defaultContent:string;styleHandle:bigint;leftAttachment:DwgMLeaderTextAttachment;rightAttachment:DwgMLeaderTextAttachment;angle:DwgMLeaderTextAngle;alignment:DwgMLeaderTextAlignment;color:DwgComplexColor;height:Binary64;frame:boolean;alwaysLeft:boolean;alignmentSpace:Binary64;attachmentDirection:DwgMLeaderAttachmentDirection;topAttachment:DwgMLeaderTextAttachment;bottomAttachment:DwgMLeaderTextAttachment; }
export interface DwgMLeaderBlockStyle { contentHandle?:bigint;color:DwgComplexColor;scale:Binary64[];useScale:boolean;rotation:Binary64;useRotation:boolean;connection:DwgMLeaderBlockConnection; }
export interface DwgMLeaderStyle { contentType: DwgMLeaderContentType; drawOrder: DwgMLeaderDrawOrder; leaderOrder: DwgMLeaderLeaderOrder; maximumSegmentPoints: number; firstSegmentAngle: Binary64; secondSegmentAngle: Binary64;leader:DwgMLeaderLeaderStyle;landing:DwgMLeaderLanding;dogleg:DwgMLeaderDogleg;description: string;arrow:DwgMLeaderArrow;text:DwgMLeaderTextStyle;block:DwgMLeaderBlockStyle;overallScale: Binary64; propertyOverridesChanged: boolean; annotative: boolean; breakSize: Binary64; }
export type DwgMaterialProjection = 'inherit' | 'planar' | 'box' | 'cylinder' | 'sphere';
export type DwgMaterialTiling = 'inherit' | 'tile' | 'crop' | 'clamp' | 'mirror';
export type DwgMaterialMapSource = 'none' | 'currentScene';
export interface DwgMaterialColor { factor: Binary64; overrideRgb?: number; }
export interface DwgMaterialMap { blendFactor: Binary64; projection: DwgMaterialProjection; tiling: DwgMaterialTiling; scaleToEntity: boolean; useCurrentBlockTransform: boolean; transform: Binary64[]; source: DwgMaterialMapSource; }
export interface DwgMaterialChannels { diffuse: boolean; specular: boolean; reflection: boolean; opacity: boolean; bump: boolean; refraction: boolean; }
export interface DwgMaterial { name: string; description: string; ambient: DwgMaterialColor; diffuse: DwgMaterialColor; diffuseMap: DwgMaterialMap; specular: DwgMaterialColor; specularMap: DwgMaterialMap; specularGloss: Binary64; reflectionMap: DwgMaterialMap; opacity: Binary64; opacityMap: DwgMaterialMap; bumpMap: DwgMaterialMap; refractionIndex: Binary64; refractionMap: DwgMaterialMap; translucence: Binary64; selfIllumination: Binary64; reflectivity: Binary64; enabledChannels: DwgMaterialChannels; }
export interface DwgBlockActionConnection { nodeId: number; name: string; }
export interface DwgBlockActionDependency { objectHandle: bigint; }
export interface DwgBlockAction { evaluationExpression: DwgEvaluationExpression; name: string; displayLocation: Binary64[]; dependencies: DwgBlockActionDependency[]; actionNodeIds: number[]; }
export interface DwgBlockMoveAction { action: DwgBlockAction; xConnection: DwgBlockActionConnection; yConnection: DwgBlockActionConnection; distanceMultiplier: Binary64; angleOffset: Binary64; coordinateMode: 'cartesianXy'; }
export interface DwgAssocNetworkMember { handle: bigint; kind: 'network' | 'action'; }
export interface DwgAssocNetwork { action: DwgAssociativeAction; networkActionIndex: number; actions: DwgAssocNetworkMember[]; }
export interface DwgConstraintNodeCore { id: number; connectedNodeIds: number[]; }
export interface DwgGeometricConstraint { node: DwgConstraintNodeCore; ownerNodeId: number; implied: boolean; active: boolean; }
export interface DwgConstraintGeometry { node: DwgConstraintNodeCore; geometryDependencyHandle?: bigint; geometryNodeId: number; }
export interface DwgExplicitConstraint { geometric: DwgGeometricConstraint; valueDependencyHandle: bigint; dimensionDependencyHandle: bigint; }
export interface DwgConstrainedImplicitPoint { geometry: DwgConstraintGeometry; point?: Binary64[]; pointKind: number; pointIndex: number; curveNodeId: number; }
export interface DwgConstrainedBoundedLine { geometry: DwgConstraintGeometry; origin: Binary64[]; direction: Binary64[]; ray: boolean; bounded: boolean; startPoint: Binary64[]; endPoint: Binary64[]; }
export interface DwgDistanceConstraint { explicit: DwgExplicitConstraint; directionKind: number; direction?: Binary64[]; }
export interface DwgAxisConstraint { geometric: DwgGeometricConstraint; datumLineIndex: number; }
export interface DwgConstrainedDatumLine { geometry: DwgConstraintGeometry; origin: Binary64[]; direction: Binary64[]; }
export type DwgConstraintNode = { kind: 'constrainedImplicitPoint'; value: DwgConstrainedImplicitPoint } | { kind: 'pointCurveConstraint' | 'pointCoincidenceConstraint' | 'perpendicularConstraint' | 'parallelConstraint' | 'midPointConstraint' | 'equalLengthConstraint' | 'colinearConstraint' | 'fixedConstraint'; value: DwgGeometricConstraint } | { kind:'horizontalConstraint'|'verticalConstraint';value:DwgAxisConstraint }|{ kind: 'constrainedBoundedLine'; value: DwgConstrainedBoundedLine } | { kind: 'distanceConstraint'; value: DwgDistanceConstraint } | { kind: 'constrainedDatumLine'; value: DwgConstrainedDatumLine };
export interface DwgAssoc2dConstraintGroup { action: DwgAssociativeAction; doNotCheckNewlyAddedConstraints: boolean; workPlane: Binary64[][]; memberActionHandles: bigint[]; nodes: DwgConstraintNode[]; }
export interface DwgBlockElement { evaluationExpression: DwgEvaluationExpression; name: string; }
export interface DwgBlockGrip { element: DwgBlockElement; location: Binary64[]; insertionCycling: boolean; insertionCyclingWeight: number; updatedX: DwgNamedEvaluationNodeReference; updatedY: DwgNamedEvaluationNodeReference; }
export interface DwgPropertyExpressionReference { propertyIndex: number; nodeId: number; }
export interface DwgBlockTwoPointParameter { element: DwgBlockElement; showProperties: boolean; chainActions: boolean; definitionBase: Binary64[]; definitionEnd: Binary64[]; properties: DwgBlockParameterProperty[]; propertyExpressionReferences: DwgPropertyExpressionReference[]; baseLocation: DwgBlockParameterBaseLocation; }
export interface DwgBlockLinearParameter { parameter: DwgBlockTwoPointParameter; distanceName: string; distanceDescription: string; labelOffset: Binary64; allowedValues: Binary64[]; }
export interface DwgBlockLinearGrip { grip: DwgBlockGrip; orientation: Binary64[]; }
export interface DwgBlockFlipGrip { grip: DwgBlockGrip; updatedFlip: DwgNamedEvaluationNodeReference; orientation: Binary64[]; }
export interface DwgBlockVisibilityGrip { grip: DwgBlockGrip; }
export interface DwgBlockAlignmentParameter { parameter: DwgBlockTwoPointParameter; updatedGripNodeId: number; alignPerpendicular: boolean; }
export interface DwgBlockAlignmentGrip { grip: DwgBlockGrip; firstLocationNodeId: number; secondLocationNodeId: number; orientation: Binary64[]; }
export interface DwgStretchSelection { objectHandle: bigint; vertexIndices: number[]; }
export interface DwgStretchSelector { nodeId: number; pointIndices: number[]; }
export interface DwgBlockStretchAction { action: DwgBlockAction; xConnection: DwgBlockActionConnection; yConnection: DwgBlockActionConnection; points: Binary64[][]; selections: DwgStretchSelection[]; selectors: DwgStretchSelector[]; distanceMultiplier: Binary64; angleOffset: Binary64; coordinateMode: 'cartesianXy'; }
export interface DwgBlockActionWithBasePoint { action: DwgBlockAction; offset: Binary64[]; xBaseConnection: DwgBlockActionConnection; yBaseConnection: DwgBlockActionConnection; dependent: boolean; basePoint: Binary64[]; }
export interface DwgBlockScaleAction { base: DwgBlockActionWithBasePoint; uniformScaleConnection: DwgBlockActionConnection; xScaleConnection: DwgBlockActionConnection; yScaleConnection: DwgBlockActionConnection; mode: 'xy'; }
export interface DwgBlockFlipAction { action: DwgBlockAction; flipConnection: DwgBlockActionConnection; updatedFlipConnection: DwgBlockActionConnection; updatedBaseConnection: DwgBlockActionConnection; updatedEndConnection: DwgBlockActionConnection; }
export interface DwgBlockOnePointParameter { element: DwgBlockElement; showProperties: boolean; chainActions: boolean; definitionPoint: Binary64[]; properties: DwgBlockParameterProperty[]; }
export interface DwgBlockBasePointParameter { parameter: DwgBlockOnePointParameter; point: Binary64[]; basePoint: Binary64[]; }
export interface DwgBlockParameterAllowedValues { values: Binary64[]; }
export interface DwgBlockLinearConstraintParameter { parameter: DwgBlockTwoPointParameter; displacementGripNodeId: number; dependencyHandle: bigint; expressionName: string; expressionDescription: string; value: Binary64; allowedValues: DwgBlockParameterAllowedValues; }
export interface DwgPlotOptions { useStandardScale: boolean; plotViewportBorders: boolean; plotWithLineweights: boolean; drawViewportsFirst: boolean; modelType: boolean; updatePaper: boolean; initializing: boolean; }
export interface DwgLayoutOptions { paperSpaceLinetypeScaling: boolean; }
export interface DwgLayout { pageSetupName: string; printerConfiguration: string; canonicalMediaName: string; stylesheet: string; name: string; plotOptions: DwgPlotOptions; margins: Binary64[]; paperSize: Binary64[]; plotOrigin: Binary64[]; paperUnit: 'inches'; rotation: 'quarterTurn'; plotArea: 'display' | 'layout'; plotWindowLowerLeft: Binary64[]; plotWindowUpperRight: Binary64[]; paperUnits: Binary64; drawingUnits: Binary64; standardScale: 'custom' | 'oneToOne'; standardScaleFactor: Binary64; paperImageOrigin: Binary64[]; shadePlot: 'asDisplayed'; shadePlotResolution: 'normal'; shadePlotDpi: number; tabOrder: number; options: DwgLayoutOptions; insertionBase: Binary64[]; limitsMinimum: Binary64[]; limitsMaximum: Binary64[]; ucsOrigin: Binary64[]; ucsXAxis: Binary64[]; ucsYAxis: Binary64[]; ucsElevation: Binary64; orthographicView: DwgOrthographicView; extentsMinimum: Binary64[]; extentsMaximum: Binary64[]; plotViewHandle?: bigint; visualStyleHandle?: bigint; blockHeaderHandle: bigint; activeViewportHandle?: bigint; baseUcsHandle?: bigint; namedUcsHandle?: bigint; viewportHandles: bigint[]; }
export type DwgLogicalObjectBody = { kind: 'dictionary'; value: DwgDictionaryBody } | { kind: 'tableControl'; value: DwgTableControlBody } | { kind: 'tableRecord'; value: DwgTableRecordBody } | { kind: 'xrecord'; value: DwgXRecordBody } | { kind: 'entity'; value: DwgEntityBody } | { kind: 'associativeDependency'; value: DwgAssociativeDependency } | { kind: 'associativeValueDependency'; value: DwgAssociativeValueDependency } | { kind: 'associativeGeometryDependency'; value: DwgAssociativeGeometryDependency } | { kind: 'blockGripLocationComponent'; value: DwgBlockGripLocationComponent } | { kind: 'dynamicBlockProxyNode'; value: DwgDynamicBlockProxyNode } | { kind: 'associativeVariable'; value: DwgAssociativeVariable } | { kind: 'associativeDimensionDependencyBody'; value: DwgAssociativeDimensionDependencyBody } | { kind: 'visualStyle'; value: DwgVisualStyle } | { kind: 'blockParameterDependencyBody'; value: DwgBlockParameterDependencyBody } | { kind: 'blockRepresentationData'; value: DwgBlockRepresentationData } | { kind: 'dynamicBlockPurgePreventer'; value: DwgDynamicBlockPurgePreventer } | { kind: 'evaluationGraph'; value: DwgEvaluationGraph } | { kind: 'blockFlipParameter'; value: DwgBlockFlipParameter } | { kind: 'blockVisibilityParameter'; value: DwgBlockVisibilityParameter } | { kind: 'placeholder'; value: DwgPlaceholder } | { kind: 'dictionaryVariable'; value: DwgDictionaryVariable } | { kind: 'annotationScale'; value: DwgAnnotationScale } | { kind: 'sortEntitiesTable'; value: DwgSortEntitiesTable } | { kind: 'tableStyle'; value: DwgTableStyle } | { kind: 'mlineStyle'; value: DwgMlineStyle } | { kind: 'mLeaderStyle'; value: DwgMLeaderStyle } | { kind: 'material'; value: DwgMaterial } | { kind: 'blockMoveAction'; value: DwgBlockMoveAction } | { kind: 'assocNetwork'; value: DwgAssocNetwork } | { kind: 'assoc2dConstraintGroup'; value: DwgAssoc2dConstraintGroup } | { kind: 'blockLinearParameter'; value: DwgBlockLinearParameter } | { kind: 'blockLinearGrip'; value: DwgBlockLinearGrip } | { kind: 'blockFlipGrip'; value: DwgBlockFlipGrip } | { kind: 'blockVisibilityGrip'; value: DwgBlockVisibilityGrip } | { kind: 'blockAlignmentParameter'; value: DwgBlockAlignmentParameter } | { kind: 'blockAlignmentGrip'; value: DwgBlockAlignmentGrip } | { kind: 'blockStretchAction'; value: DwgBlockStretchAction } | { kind: 'blockScaleAction'; value: DwgBlockScaleAction } | { kind: 'blockFlipAction'; value: DwgBlockFlipAction } | { kind: 'blockBasePointParameter'; value: DwgBlockBasePointParameter } | { kind: 'blockVerticalConstraintParameter'; value: DwgBlockLinearConstraintParameter } | { kind: 'blockHorizontalConstraintParameter'; value: DwgBlockLinearConstraintParameter } | { kind: 'layout'; value: DwgLayout };
export interface DwgExtendedEntityData { applicationHandle: bigint; values: DwgXRecordValue[]; }
export interface DwgLogicalObject { handle: bigint; typeCode: number; className: string; category: DwgObjectCategory; ownerHandle?: bigint; reactorHandles: bigint[]; extensionDictionaryHandle?: bigint; referencedHandles: bigint[]; extendedData: DwgExtendedEntityData[]; body?: DwgLogicalObjectBody; }
export interface DwgLogicalDrawing { layers: DwgLogicalLayer[]; objects: DwgLogicalObject[]; extmin: Binary64[]; extmax: Binary64[]; }
export interface DwgHeaderUnits { unit1Conversion: Binary64; unit2Conversion: Binary64; unit3Conversion: Binary64; unit4Conversion: Binary64; unit1Name: string; unit2Name: string; unit3Name: string; unit4Name: string; }
export interface DwgHeaderModes { dimensionAssociative: boolean; dimensionShow: boolean; polylineGeneration: boolean; orthographicMode: boolean; regenerationMode: boolean; fillMode: boolean; quickTextMode: boolean; paperSpaceLinetypeScale: boolean; limitsCheck: boolean; userTimer: boolean; sketchPolyline: boolean; angleDirection: boolean; splineFrame: boolean; mirrorText: boolean; worldView: boolean; tileMode: boolean; paperLimitsCheck: boolean; visualRetain: boolean; displaySilhouette: boolean; polylineEllipse: boolean; }
export interface DwgHeaderIntegerSettings { proxyGraphics: number; treeDepth: number; linearUnits: number; linearPrecision: number; angularUnits: number; angularPrecision: number; attributeMode: number; pointDisplayMode: number; userInteger1: number; userInteger2: number; userInteger3: number; userInteger4: number; userInteger5: number; splineSegments: number; surfaceU: number; surfaceV: number; surfaceType: number; surfaceTab1: number; surfaceTab2: number; splineType: number; shadeEdge: number; shadeDifference: number; unitMode: number; maximumActiveViewports: number; isolines: number; multilineJustification: number; textQuality: number; }
export interface DwgHeaderScalars { linetypeScale: Binary64; textSize: Binary64; traceWidth: Binary64; sketchIncrement: Binary64; filletRadius: Binary64; thickness: Binary64; angleBase: Binary64; pointDisplaySize: Binary64; polylineWidth: Binary64; userReal1: Binary64; userReal2: Binary64; userReal3: Binary64; userReal4: Binary64; userReal5: Binary64; chamferA: Binary64; chamferB: Binary64; chamferC: Binary64; chamferD: Binary64; facetResolution: Binary64; multilineScale: Binary64; currentEntityLinetypeScale: Binary64; currentEntityColorIndex: number; paperSpaceViewportScale: Binary64; }
export interface DwgHeaderTimeState { createdAt: DwgJulianDate; updatedAt: DwgJulianDate; editingDuration: DwgJulianDate; userTimerDuration: DwgJulianDate; }
export interface DwgHeaderSpaceGeometry { insertionBase: Binary64[]; extentsMinimum: Binary64[]; extentsMaximum: Binary64[]; limitsMinimum: Binary64[]; limitsMaximum: Binary64[]; elevation: Binary64; ucsOrigin: Binary64[]; ucsXAxis: Binary64[]; ucsYAxis: Binary64[]; ucsOrthographicView: number; ucsOriginTop: Binary64[]; ucsOriginBottom: Binary64[]; ucsOriginLeft: Binary64[]; ucsOriginRight: Binary64[]; ucsOriginFront: Binary64[]; ucsOriginBack: Binary64[]; }
export interface DwgDimensionSettings { scale: Binary64; arrowSize: Binary64; extensionOffset: Binary64; lineIncrement: Binary64; extension: Binary64; rounding: Binary64; lineExtension: Binary64; tolerancePlus: Binary64; toleranceMinus: Binary64; fixedExtensionLength: Binary64; jogAngle: Binary64; textFill: number; textFillColorIndex: number; tolerance: boolean; limits: boolean; textInsideHorizontal: boolean; textOutsideHorizontal: boolean; suppressExtension1: boolean; suppressExtension2: boolean; textAbove: number; zeroSuppression: number; angularZeroSuppression: number; arcSymbol: number; textHeight: Binary64; centerMark: Binary64; tickSize: Binary64; alternateScale: Binary64; linearFactor: Binary64; textVerticalPosition: Binary64; textFactor: Binary64; gap: Binary64; alternateRounding: Binary64; alternateUnits: boolean; alternateDecimalPlaces: number; textOutsideForceLine: boolean; separateArrows: boolean; textInside: boolean; suppressOutside: boolean; lineColorIndex: number; extensionColorIndex: number; textColorIndex: number; angularDecimalPlaces: number; decimalPlaces: number; toleranceDecimalPlaces: number; alternateUnitsFormat: number; alternateToleranceDecimalPlaces: number; angularUnitFormat: number; fractionalFormat: number; linearUnitFormat: number; decimalSeparator: number; textMovement: number; justification: number; suppressDimension1: boolean; suppressDimension2: boolean; toleranceJustification: number; toleranceZeroSuppression: number; alternateZeroSuppression: number; alternateToleranceZeroSuppression: number; userPositionedText: boolean; fit: number; fixedExtensionEnabled: boolean; textDirection: boolean; alternateMeasurementScale: Binary64; measurementScale: Binary64; dimensionLineWeight: number; extensionLineWeight: number; }
export interface DwgDrawingPolicy { textStackAlignment: number; textStackSize: number; currentEntityLineweight: number; endCaps: number; joinStyle: number; lineweightDisplay: boolean; externalReferenceEditing: boolean; extendedNames: boolean; plotStyleMode: boolean; oleStartup: boolean; insertionUnits: number; currentPlotStyleType: number; sortEntities: number; indexControl: number; hideText: number; xclipFrame: number; dimensionAssociation: number; haloGap: number; obscuredColor: number; intersectionColor: number; obscuredLinetype: number; intersectionDisplay: number; cameraDisplay: boolean; stepsPerSecond: Binary64; stepSize: Binary64; dwf3dPrecision: Binary64; lensLength: Binary64; cameraHeight: Binary64; solidHistory: number; showHistory: number; polysolidWidth: Binary64; polysolidHeight: Binary64; loftAngle1: Binary64; loftAngle2: Binary64; loftMagnitude1: Binary64; loftMagnitude2: Binary64; loftParameter: number; loftNormals: number; latitude: Binary64; longitude: Binary64; northDirection: Binary64; timezone: number; lightGlyphDisplay: number; tileModeLightSync: number; dwfFrame: number; dgnFrame: number; realWorldScale: boolean; interfereColorIndex: number; shadowMode: number; shadowPlaneLocation: Binary64; }
export interface DwgHeaderStrings { menu: string; dimensionPostfix: string; dimensionAlternatePostfix: string; dimensionAlternateMeasurementZeroSuffix: string; dimensionMeasurementZeroSuffix: string; hyperlinkBase: string; stylesheet: string; fingerprintGuid: string; versionGuid: string; projectName: string; }
export interface DwgHeaderRelations { handleSeed: bigint; currentLayer: bigint; textStyle: bigint; currentLinetype: bigint; currentMaterial: bigint; dimensionStyle: bigint; multilineStyle: bigint; paperUcsName?: bigint; paperUcsOrthographicReference?: bigint; paperUcsBase?: bigint; modelUcsName?: bigint; modelUcsOrthographicReference?: bigint; modelUcsBase?: bigint; dimensionTextStyle: bigint; dimensionLeaderBlock?: bigint; dimensionBlock?: bigint; dimensionBlock1?: bigint; dimensionBlock2?: bigint; dimensionLinetype?: bigint; dimensionExtensionLinetype1?: bigint; dimensionExtensionLinetype2?: bigint; blockControl: bigint; layerControl: bigint; styleControl: bigint; linetypeControl: bigint; viewControl: bigint; ucsControl: bigint; viewportControl: bigint; appidControl: bigint; dimensionStyleControl: bigint; groupDictionary: bigint; multilineStyleDictionary: bigint; namedObjectsDictionary: bigint; layoutDictionary: bigint; plotSettingsDictionary: bigint; plotStyleNameDictionary: bigint; materialDictionary: bigint; colorDictionary: bigint; visualStyleDictionary: bigint; paperSpaceBlockRecord: bigint; modelSpaceBlockRecord: bigint; byLayerLinetype: bigint; byBlockLinetype: bigint; continuousLinetype: bigint; interfereObjectVisualStyle?: bigint; interfereViewportVisualStyle?: bigint; dragVisualStyle?: bigint; }
export interface DwgHeaderVariables { units: DwgHeaderUnits; modes: DwgHeaderModes; integers: DwgHeaderIntegerSettings; scalars: DwgHeaderScalars; time: DwgHeaderTimeState; paperSpace: DwgHeaderSpaceGeometry; modelSpace: DwgHeaderSpaceGeometry; dimensions: DwgDimensionSettings; policy: DwgDrawingPolicy; strings: DwgHeaderStrings; relations: DwgHeaderRelations; }
export interface DwgClass { number: number; proxyFlags: number; applicationName: string; cppClassName: string; dxfName: string; wasZombie: boolean; itemClassId: number; objectCount: number; dwgVersion: number; maintenanceVersion: number; reservedValues: number[]; }
export interface DwgDependency { feature: string; fullPath: string; relativePath: string; fingerprint: string; version: string; timestamp: number; fileSize: number; affectsGraphics: boolean; referenceCount: number; }
export interface DwgJulianDate { days: number; milliseconds: number; }
export interface DwgVersionStamp { version: number; maintenance: number; }
export interface DwgAuxiliaryHeader { totalSaves: number; savePartitionOne: number; savePartitionTwo: number; saveGeneration: number; legacyStampOne: DwgVersionStamp; legacyStampTwo: DwgVersionStamp; compatibilityProfile: 'autocad2009'; createdAt: DwgJulianDate; updatedAt: DwgJulianDate; handleSeed: bigint; terminalSaveGeneration: number; }
export interface DwgRevisionHistory { formatMajor: number; formatMinor: number; revisions: number[]; }
export interface DwgRgba { red: number; green: number; blue: number; alpha: number; }
export interface DwgIndexedPreview { width: number; height: number; origin: 'bottomUp'; palette: DwgRgba[]; pixelIndices: number[]; backgroundPaletteIndex: number; }
export interface DwgApplicationProperty { id: number; kind: 'string' | 'dateTime'; value: string; }
export interface DwgProductInformation { name: string; buildVersion: string; registryVersion: string; installId: string; localeId: string; }
export interface DwgApplicationHistory { historyIdentifierOne: string; historyIdentifierTwo: string; classVersion: number; applicationVersionDigest: string; applicationVersion: string; trustCommentDigest: string; trustComment: string; propertySetDigest: string; propertyFormatIdentifier: string; properties: DwgApplicationProperty[]; productDigest: string; product: DwgProductInformation; }
export interface DwgCustomProperty { key: string; value: string; }
export interface DwgSummaryInfo { title: string; subject: string; author: string; keywords: string; comments: string; lastSavedBy: string; revisionNumber: string; hyperlinkBase: string; totalEditingTime: bigint; createdAt: DwgJulianDate; modifiedAt: DwgJulianDate; customProperties: DwgCustomProperty[]; }
export interface DwgApplicationInfo { name: string; versionChecksum: string; version: string; commentChecksum: string; comment: string; productChecksum: string; product: string; applicationVersion: string; }
export interface DwgTemplate { description: string; measurement: 'english' | 'metric'; }
export interface DwgArtifact { schema: string; version: string; maintenanceVersion: number; codepage: number; drawing: DwgLogicalDrawing; header: DwgHeaderVariables; classes: DwgClass[]; dependencies: DwgDependency[]; summary: DwgSummaryInfo; application: DwgApplicationInfo; template: DwgTemplate; auxiliaryHeader: DwgAuxiliaryHeader; revisionHistory: DwgRevisionHistory; preview: DwgIndexedPreview; applicationHistory: DwgApplicationHistory; }
