/** 🖼️ TIFF's authored directory and twelve exact scalar value domains. */
import type {TiffSnapshot,TiffValues,TiffFieldType,TiffTag} from "../🟦️.ts";
import {parseTiffFieldType} from "../🟦️.ts";
import {ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteInteger,artifactSqliteText,artifactSqliteDocument,artifactSqliteCheckpoint,artifactSqliteValueBudget,artifactSqliteTextBytes,type ArtifactSqliteOptions} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {encodeIeee754Cells,readBinary32,readBinary64,type Ieee754Column} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import {sqliteValueByteLength,type SqliteDatabase,type SqliteRow} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";

export const TIFF_SQLITE_SCHEMA=`CREATE TABLE tiff_document (id INTEGER PRIMARY KEY, schema TEXT NOT NULL, byte_order TEXT NOT NULL CHECK(byte_order IN ('littleEndian','bigEndian')));
CREATE TABLE tiff_ifd (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES tiff_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0));
CREATE TABLE tiff_tag (id INTEGER PRIMARY KEY, ifd_id INTEGER NOT NULL REFERENCES tiff_ifd(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), tag_number INTEGER NOT NULL CHECK(tag_number BETWEEN 0 AND 65535), field_type INTEGER NOT NULL CHECK(field_type BETWEEN 1 AND 12), value_type INTEGER NOT NULL CHECK(value_type BETWEEN 1 AND 12));
CREATE TABLE tiff_byte_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 255));
CREATE TABLE tiff_ascii_value (tag_id INTEGER PRIMARY KEY REFERENCES tiff_tag(id), value TEXT NOT NULL);
CREATE TABLE tiff_short_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 65535));
CREATE TABLE tiff_long_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 4294967295));
CREATE TABLE tiff_rational_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), numerator INTEGER NOT NULL CHECK(numerator BETWEEN 0 AND 4294967295), denominator INTEGER NOT NULL CHECK(denominator BETWEEN 0 AND 4294967295));
CREATE TABLE tiff_signed_byte_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN -128 AND 127));
CREATE TABLE tiff_undefined_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 255));
CREATE TABLE tiff_signed_short_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN -32768 AND 32767));
CREATE TABLE tiff_signed_long_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value INTEGER NOT NULL CHECK(value BETWEEN -2147483648 AND 2147483647));
CREATE TABLE tiff_signed_rational_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), numerator INTEGER NOT NULL CHECK(numerator BETWEEN -2147483648 AND 2147483647), denominator INTEGER NOT NULL CHECK(denominator BETWEEN -2147483648 AND 2147483647));
CREATE TABLE tiff_float_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value REAL, value_bits INTEGER, value_class TEXT);
CREATE TABLE tiff_double_value (id INTEGER PRIMARY KEY, tag_id INTEGER NOT NULL REFERENCES tiff_tag(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value REAL, value_bits INTEGER, value_class TEXT);
CREATE TABLE tiff_document_pixels (document_id INTEGER PRIMARY KEY REFERENCES tiff_document(id), rgba_pixels BLOB NOT NULL);
CREATE TABLE tiff_ifd_pixels (ifd_id INTEGER PRIMARY KEY REFERENCES tiff_ifd(id), strip_pixels BLOB NOT NULL);
`;
const KINDS:readonly TiffFieldType[]=["byte","ascii","short","long","rational","sByte","undefined","sShort","sLong","sRational","float","double"];
const TABLES:readonly [string,TiffFieldType,number][]=[["tiff_byte_value","byte",4],["tiff_ascii_value","ascii",2],["tiff_short_value","short",4],["tiff_long_value","long",4],["tiff_rational_value","rational",5],["tiff_signed_byte_value","sByte",4],["tiff_undefined_value","undefined",4],["tiff_signed_short_value","sShort",4],["tiff_signed_long_value","sLong",4],["tiff_signed_rational_value","sRational",5],["tiff_float_value","float",6],["tiff_double_value","double",6]];
const TABLE_ORDER=["tiff_document","tiff_ifd","tiff_tag","tiff_byte_value","tiff_ascii_value","tiff_short_value","tiff_long_value","tiff_rational_value","tiff_signed_byte_value","tiff_undefined_value","tiff_signed_short_value","tiff_signed_long_value","tiff_signed_rational_value","tiff_float_value","tiff_double_value","tiff_document_pixels","tiff_ifd_pixels"];
const FLOAT:readonly Ieee754Column[]=[{index:3,width:32}],DOUBLE:readonly Ieee754Column[]=[{index:3,width:64}];
function code(kind:TiffFieldType):bigint{parseTiffFieldType(kind);const i=KINDS.indexOf(kind);if(i<0)throw Error("unknown TIFF field type");return BigInt(i+1);}
function kind(row:SqliteRow,index:number):TiffFieldType{const n=artifactSqliteInteger(row,index);if(n<1n||n>12n)throw Error("unknown TIFF field type");return KINDS[Number(n)-1]!;}
function bounded(value:unknown,min:number,max:number):bigint{if(typeof value!=="number"||!Number.isInteger(value)||value<min||value>max)throw Error("TIFF scalar is outside its native width");return BigInt(value);}
function scalar(row:SqliteRow,index:number,min:number,max:number):number{const v=artifactSqliteInteger(row,index);if(v<BigInt(min)||v>BigInt(max))throw Error("TIFF scalar is outside its native width");return Number(v);}
function identity(row:SqliteRow,columns:number):void{if(row.rowid<=0n||row.values.length!==columns||artifactSqliteInteger(row,0)!==row.rowid)throw Error("TIFF entity identity or column shape is invalid");}
function addGroup(groups:Map<bigint,Map<number,SqliteRow>>,owner:bigint,row:SqliteRow,column:number):void{const n=artifactSqliteInteger(row,column);if(n<0n||n>BigInt(Number.MAX_SAFE_INTEGER))throw Error("TIFF ordinal width");let group=groups.get(owner);if(!group){group=new Map();groups.set(owner,group);}if(group.has(Number(n)))throw Error("duplicate TIFF ordinal");group.set(Number(n),row);}
async function order(group:Map<number,SqliteRow>,options:ArtifactSqliteOptions):Promise<SqliteRow[]>{const rows=new Array<SqliteRow>(group.size);for(const [ordinal,row]of group){if(ordinal>=rows.length)throw Error("TIFF ordinals must be contiguous");rows[ordinal]=row;if(ordinal%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",ordinal,rows.length);}return rows;}
async function octets(values:readonly number[],options:ArtifactSqliteOptions):Promise<Uint8Array>{artifactSqliteValueBudget(values.length,options);await artifactSqliteCheckpoint(options,"projectSnapshot",0,values.length);const result=new Uint8Array(values.length);for(let i=0;i<values.length;i++){result[i]=Number(bounded(values[i],0,255));if(i%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",i,values.length);}return result;}
async function pixels(row:SqliteRow,options:ArtifactSqliteOptions):Promise<number[]>{const v=row.values[1];if(!(v instanceof Uint8Array))throw Error("TIFF pixels require a BLOB");await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,v.length);const out:number[]=[];for(let i=0;i<v.length;i++){out.push(v[i]!);if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,v.length);}return out;}

/** 📤️ Project only the explicit native TIFF fields, retaining duplicate tag order. */
export async function tiffSnapshotToSqliteDatabase(snapshot:TiffSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
  await artifactSqliteCheckpoint(options,"projectSnapshot",0,0);if(snapshot.byteOrder!=="littleEndian"&&snapshot.byteOrder!=="bigEndian")throw Error("unknown TIFF byte order");
  let count=2,bytes=16+artifactSqliteTextBytes(snapshot.schema)+artifactSqliteTextBytes(snapshot.byteOrder)+snapshot.pixels.length,units=0;
  for(const ifd of snapshot.ifds){count+=2;bytes+=32+ifd.pixels.length;for(const tag of ifd.entries){code(tag.kind);code(tag.values.kind);bounded(tag.tag,0,65535);count+=1+(tag.values.kind==="ascii"?1:tag.values.value.length);bytes+=48;
      switch(tag.values.kind){case"ascii":bytes+=8+artifactSqliteTextBytes(tag.values.value);break;case"rational":case"sRational":bytes+=tag.values.value.length*40;break;case"float":case"double":for(const value of tag.values.value){const cells=encodeIeee754Cells([0n,0n,0n,value],tag.values.kind==="float"?FLOAT:DOUBLE,options.maxColumns);bytes+=cells.reduce<number>((n,v)=>n+sqliteValueByteLength(v),0);if(++units%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",units,0);}break;default:bytes+=tag.values.value.length*32;}
      if(count+1>(options.maxRows??1000000))throw Error("TIFF row limit");artifactSqliteValueBudget(bytes,options);if(++units%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",units,0);
    }if(count+1>(options.maxRows??1000000))throw Error("TIFF row limit");artifactSqliteValueBudget(bytes,options);if(++units%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",units,0);}
  if(count+1>(options.maxRows??1000000))throw Error("TIFF row limit");artifactSqliteValueBudget(bytes,options);const p=await ArtifactSqliteProjection.create(TIFF_SQLITE_SCHEMA,options);
  await p.insert("tiff_document",[snapshot.schema,snapshot.byteOrder],1n);await p.insert("tiff_document_pixels",[await octets(snapshot.pixels,options)],1n);
  for(const [ordinal,ifd]of snapshot.ifds.entries()){const id=await p.insert("tiff_ifd",[1n,BigInt(ordinal)]);await p.insert("tiff_ifd_pixels",[await octets(ifd.pixels,options)],id);
    for(const [ordinal,tag]of ifd.entries.entries()){const tagId=await p.insert("tiff_tag",[id,BigInt(ordinal),bounded(tag.tag,0,65535),code(tag.kind),code(tag.values.kind)]);
      const ints=async(table:string,values:readonly number[],min:number,max:number):Promise<void>=>{for(const [i,v]of values.entries())await p.insert(table,[tagId,BigInt(i),bounded(v,min,max)]);};
      const pairs=async(table:string,values:readonly [number,number][],min:number,max:number):Promise<void>=>{for(const [i,pair]of values.entries()){if(pair.length!==2)throw Error("TIFF rational requires two scalar fields");await p.insert(table,[tagId,BigInt(i),bounded(pair[0],min,max),bounded(pair[1],min,max)]);}};
      switch(tag.values.kind){case"byte":await ints("tiff_byte_value",tag.values.value,0,255);break;case"ascii":await p.insert("tiff_ascii_value",[tag.values.value],tagId);break;case"short":await ints("tiff_short_value",tag.values.value,0,65535);break;case"long":await ints("tiff_long_value",tag.values.value,0,4294967295);break;case"rational":await pairs("tiff_rational_value",tag.values.value,0,4294967295);break;case"sByte":await ints("tiff_signed_byte_value",tag.values.value,-128,127);break;case"undefined":await ints("tiff_undefined_value",tag.values.value,0,255);break;case"sShort":await ints("tiff_signed_short_value",tag.values.value,-32768,32767);break;case"sLong":await ints("tiff_signed_long_value",tag.values.value,-2147483648,2147483647);break;case"sRational":await pairs("tiff_signed_rational_value",tag.values.value,-2147483648,2147483647);break;case"float":for(const [i,value]of tag.values.value.entries())await p.insert("tiff_float_value",encodeIeee754Cells([0n,tagId,BigInt(i),value],FLOAT,options.maxColumns).slice(1));break;case"double":for(const [i,value]of tag.values.value.entries())await p.insert("tiff_double_value",encodeIeee754Cells([0n,tagId,BigInt(i),value],DOUBLE,options.maxColumns).slice(1));break;}
    }
  }return p.finish();
}

/** 📥️ Restore each native field after strict declared-schema and relationship validation. */
export async function tiffSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<TiffSnapshot>{
  await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,0);const source=await artifactSqliteTables(database,TIFF_SQLITE_SCHEMA,options);const tables=new Map(TABLE_ORDER.map((name,index)=>[name,source[index]!]));const rows=(name:string):readonly SqliteRow[]=>tables.get(name)!;
  const doc=artifactSqliteDocument(rows("tiff_document"));identity(doc,3);const byteOrder=artifactSqliteText(doc,2);if(byteOrder!=="littleEndian"&&byteOrder!=="bigEndian")throw Error("unknown TIFF byte order");
  const directories=new Map<number,SqliteRow>();const ids=new Set<bigint>();let units=0;const tick=async():Promise<void>=>{if(++units%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",units,0);};
  for(const row of rows("tiff_ifd")){identity(row,3);if(artifactSqliteInteger(row,1)!==1n||ids.has(row.rowid))throw Error("invalid TIFF directory ownership");ids.add(row.rowid);const n=scalar(row,2,0,rows("tiff_ifd").length-1);if(directories.has(n))throw Error("duplicate TIFF directory ordinal");directories.set(n,row);await tick();}
  const tags=new Map<bigint,SqliteRow>();const directoryTags=new Map<bigint,Map<number,SqliteRow>>();for(const row of rows("tiff_tag")){identity(row,6);if(!ids.has(artifactSqliteInteger(row,1))||tags.has(row.rowid))throw Error("dangling or duplicate TIFF tag");scalar(row,3,0,65535);kind(row,4);kind(row,5);tags.set(row.rowid,row);addGroup(directoryTags,artifactSqliteInteger(row,1),row,2);await tick();}
  const values=new Map<bigint,Map<number,SqliteRow>>(),ascii=new Map<bigint,SqliteRow>();for(const [table,type,columns]of TABLES){const seen=new Set<bigint>();for(const row of rows(table)){identity(row,columns);if(seen.has(row.rowid))throw Error("duplicate TIFF typed identity");seen.add(row.rowid);const owner=type==="ascii"?row.rowid:artifactSqliteInteger(row,1);const tag=tags.get(owner);if(!tag||kind(tag,5)!==type)throw Error("TIFF component differs from its declared variant");if(type==="ascii"){artifactSqliteText(row,1);if(ascii.has(owner))throw Error("duplicate TIFF ASCII component");ascii.set(owner,row);}else{addGroup(values,owner,row,2);if(type==="float")readBinary32(row,3,FLOAT);else if(type==="double")readBinary64(row,3,DOUBLE);else{artifactSqliteInteger(row,3);if(type==="rational"||type==="sRational")artifactSqliteInteger(row,4);}}await tick();}}
  const root=artifactSqliteDocument(rows("tiff_document_pixels"));identity(root,2);const documentPixels=await pixels(root,options);const ifdPixels=new Map<bigint,SqliteRow>();for(const row of rows("tiff_ifd_pixels")){identity(row,2);if(!ids.has(row.rowid)||ifdPixels.has(row.rowid))throw Error("dangling or duplicate TIFF directory pixels");ifdPixels.set(row.rowid,row);await tick();}if(ifdPixels.size!==ids.size)throw Error("missing TIFF directory pixels");
  const ifds:TiffSnapshot["ifds"]=[];for(const directory of await order(directories,options)){const component=ifdPixels.get(directory.rowid)!;const entries:TiffTag[]=[];for(const tag of await order(directoryTags.get(directory.rowid)??new Map(),options)){const typedRows=await order(values.get(tag.rowid)??new Map(),options);values.delete(tag.rowid);const type=kind(tag,5);
      const integers=async(min:number,max:number):Promise<number[]>=>{const out:number[]=[];for(const row of typedRows){out.push(scalar(row,3,min,max));await tick();}return out;};
      const pairs=async(min:number,max:number):Promise<[number,number][]>=>{const out:[number,number][]=[];for(const row of typedRows){out.push([scalar(row,3,min,max),scalar(row,4,min,max)]);await tick();}return out;};
      let value:TiffValues;switch(type){case"byte":value={kind:type,value:await integers(0,255)};break;case"ascii":{const row=ascii.get(tag.rowid);if(!row)throw Error("missing TIFF ASCII component");value={kind:type,value:artifactSqliteText(row,1)};ascii.delete(tag.rowid);break;}case"short":value={kind:type,value:await integers(0,65535)};break;case"long":value={kind:type,value:await integers(0,4294967295)};break;case"rational":value={kind:type,value:await pairs(0,4294967295)};break;case"sByte":value={kind:type,value:await integers(-128,127)};break;case"undefined":value={kind:type,value:await integers(0,255)};break;case"sShort":value={kind:type,value:await integers(-32768,32767)};break;case"sLong":value={kind:type,value:await integers(-2147483648,2147483647)};break;case"sRational":value={kind:type,value:await pairs(-2147483648,2147483647)};break;case"float":{const out=[];for(const row of typedRows){out.push(readBinary32(row,3,FLOAT));await tick();}value={kind:type,value:out};break;}case"double":{const out=[];for(const row of typedRows){out.push(readBinary64(row,3,DOUBLE));await tick();}value={kind:type,value:out};break;}}
      entries.push({tag:scalar(tag,3,0,65535),kind:kind(tag,4),values:value});await tick();
    }directoryTags.delete(directory.rowid);ifds.push({entries,pixels:await pixels(component,options)});await tick();}
  if(values.size||ascii.size||directoryTags.size)throw Error("unowned TIFF components");await artifactSqliteCheckpoint(options,"reconstructSnapshot",units,units);return {schema:artifactSqliteText(doc,1),byteOrder,ifds,pixels:documentPixels};
}
