//! 🧪️ Closed original Binary receiving laws with physical allocator observations.
use super::{bind,Carrier};
use semio_framework_os_kernel::NativeSnapshotBodyWallet;
use semio_framework_value::{NativeDecodeControl,RetainedCloneGrant};
use std::{alloc::{GlobalAlloc,Layout,System},cell::Cell};
thread_local!{static TRACE:Cell<Option<(usize,usize)>>=const{Cell::new(None)};}
struct Allocator;
unsafe impl GlobalAlloc for Allocator{
 unsafe fn alloc(&self,layout:Layout)->*mut u8{let pointer=unsafe{System.alloc(layout)};if !pointer.is_null(){TRACE.with(|trace|if let Some((born,released))=trace.get(){trace.set(Some((born+layout.size(),released)))});}pointer}
 unsafe fn dealloc(&self,pointer:*mut u8,layout:Layout){TRACE.with(|trace|if let Some((born,released))=trace.get(){trace.set(Some((born,released+layout.size())))});unsafe{System.dealloc(pointer,layout)}}
 unsafe fn realloc(&self,pointer:*mut u8,layout:Layout,size:usize)->*mut u8{let next=unsafe{System.realloc(pointer,layout,size)};if !next.is_null(){TRACE.with(|trace|if let Some((born,released))=trace.get(){trace.set(Some((born+size,released+layout.size())))});}next}
}
#[global_allocator]static ALLOCATOR:Allocator=Allocator;
fn observe<T>(operation:impl FnOnce()->T)->(T,usize,usize){TRACE.with(|trace|{assert!(trace.get().is_none());trace.set(Some((0,0)));});let result=operation();let (born,released)=TRACE.with(|trace|trace.take().unwrap());(result,born,released)}
fn fixture()->serde_json::Value{serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap()}
fn grant(value:&serde_json::Value)->RetainedCloneGrant{RetainedCloneGrant{maximum_items:value["maximumItems"].as_u64().unwrap()as usize,maximum_copy_bytes:value["maximumCopyBytes"].as_u64().unwrap()as usize,maximum_capacity_bytes:value["maximumCapacityBytes"].as_u64().unwrap()as usize,maximum_release_bytes:value["maximumReleaseBytes"].as_u64().unwrap()as usize,maximum_depth:value["maximumDepth"].as_u64().unwrap()as usize}}
#[test]
fn binary_original_receiving_shapes_and_independent_authored_body_bounds(){
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let maximum=original["nativeMaximumBytes"].as_u64().unwrap()as usize;let schema=original["canonicalSchema"].as_str().unwrap();
 for row in fixture["shapeCases"].as_array().unwrap(){let raw=row["raw"].as_array().unwrap().iter().map(|v|v.as_u64().unwrap()as u8).collect::<Vec<_>>();let carrier=if row["carrier"]=="binary"{Carrier::Raw(&raw)}else{Carrier::Hex(row["text"].as_str().unwrap())};let accepted=row["accepted"].as_bool().unwrap();let mut observer=|_|true;let mut native=NativeDecodeControl::new(if accepted{maximum}else{original["refusalNativeMaximumBytes"].as_u64().unwrap()as usize},&mut observer);let mut body=NativeSnapshotBodyWallet::new(if accepted{full}else{grant(&original["refusalGrant"])});let mut slot=None;let (result,born,released)=observe(||bind(carrier,schema,&mut slot,&mut native,&mut body));let accepted=row["accepted"].as_bool().unwrap();assert_eq!(result.is_ok(),accepted);assert_eq!(released,0);if accepted{let output=slot.as_ref().unwrap();assert_eq!(output.schema,schema);assert_eq!(serde_json::to_value(&output.bytes).unwrap(),row["expected"]);assert_eq!(born,body.progress().retained_capacity_bytes);}else{assert!(slot.is_none());assert_eq!((born,released),(0,0));assert_eq!(result.unwrap_err().message,row["cause"].as_str().unwrap());assert_eq!(body.progress(),Default::default());}}
 for row in fixture["bodyCases"].as_array().unwrap(){let maximum=row["limits"].as_array().unwrap().iter().find(|v|v["pointerBytes"].as_u64().unwrap()as usize==std::mem::size_of::<usize>()).unwrap()["maximum"].as_u64().unwrap()as usize;let mut original_grant=full;match row["axis"].as_str().unwrap(){"items"=>original_grant.maximum_items=maximum,"copy"=>original_grant.maximum_copy_bytes=maximum,"capacity"=>original_grant.maximum_capacity_bytes=maximum,"depth"=>original_grant.maximum_depth=maximum,_=>unreachable!()};let mut observer=|_|true;let mut native=NativeDecodeControl::new(original["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut observer);let mut body=NativeSnapshotBodyWallet::new(original_grant);let mut slot=None;let(result,born,released)=observe(||bind(Carrier::Raw(&[0,255,1,128]),schema,&mut slot,&mut native,&mut body));assert_eq!(result.is_ok(),row["accepted"].as_bool().unwrap());assert_eq!(released,0);if result.is_err(){assert!(slot.is_none());assert_eq!(born,0);assert_eq!(body.progress(),Default::default());}else{assert_eq!(born,body.progress().retained_capacity_bytes);assert_eq!(body.progress().copied_items,3);}}
 eprintln!("[DEBUG] Original Binary fourteen raw/hex/envelope shape laws and twelve independently authored body bounds retain typed schema/octet slots; refused birth/release 0/0");
}

#[test]
fn binary_original_receiving_cancellation_retains_fields_and_funded_close(){
 use semio_framework_os_kernel::NativeSnapshotDecodeOwner;
 use semio_framework_value::{native_decoding::{NativeDecodeProgress,NativeDecodeRetirementRecipient},ValueError,ValueRefusalKind};
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let zero=grant(&original["closeZeroGrant"]);let close=grant(&original["closeFundedGrant"]);let policy=&fixture["cancellation"];let schema=policy["schemaSeed"].as_str().unwrap().repeat(policy["schemaRepeat"].as_u64().unwrap()as usize);let pattern=policy["bytePattern"].as_array().unwrap();let bytes=(0..policy["byteCount"].as_u64().unwrap()as usize).map(|index|pattern[index%pattern.len()].as_u64().unwrap()as u8).collect::<Vec<_>>();
 for field in["schema","octets"]{for checkpoint in policy["checkpoints"].as_array().unwrap(){let total=if field=="schema"{schema.len()}else{bytes.len()};let checkpoint=checkpoint.as_str().unwrap();let after=match checkpoint{"first"=>0,"interior"=>total/2,"final"=>total,_=>unreachable!()};let armed=Cell::new(false);let reached=Cell::new(false);let parent_restored=Cell::new(false);let partial_schema=Cell::new(0);let partial_octets=Cell::new(0);let mut callback=|event:NativeDecodeProgress|{if !armed.get(){parent_restored.set(event.completed==17&&event.total==17);return true}let stop=event.total==total&&event.completed>=after;reached.set(reached.get()||stop);!stop};let mut recipient=NativeDecodeRetirementRecipient::new();let mut native=NativeDecodeControl::new(original["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();native.begin_stage(17).unwrap();native.advance(17).unwrap();armed.set(true);
 let mut owner=NativeSnapshotDecodeOwner::new(&mut native,full);let (result,born,released)=observe(||owner.receive::<super::BinarySnapshot,super::BinarySnapshot>(|slot,native,body|{let result=bind(Carrier::Raw(&bytes),&schema,slot,native,body);if let Some(output)=slot.as_ref(){assert!(schema.starts_with(&output.schema));assert_eq!(&bytes[..output.bytes.len()],output.bytes);partial_schema.set(output.schema.len());partial_octets.set(output.bytes.len());}result?;slot.take().ok_or_else(||ValueError::literal(ValueRefusalKind::InvariantViolated,"lost Binary law slot"))}));let progress=owner.progress();drop(owner);assert_eq!(result.unwrap_err().kind,ValueRefusalKind::Canceled);assert!(reached.get());assert_eq!(released,0);assert_eq!(born,progress.retained_capacity_bytes);assert!(native.has_retirement_owner());armed.set(false);native.checkpoint().unwrap();assert!(parent_restored.get());
 let (_,zero_born,zero_release)=observe(||native.close_retirement_recipient(zero).unwrap());assert_eq!((zero_born,zero_release),(0,0));assert!(native.has_retirement_owner());let mut total_release=0;let mut total_birth=born;while native.has_retirement_owner(){let(step,close_born,close_release)=observe(||native.close_retirement_recipient(close).unwrap());assert_eq!(close_born,step.progress().retained_capacity_bytes);assert_eq!(close_release,step.progress().released_bytes);total_release+=close_release;total_birth+=close_born;}assert_eq!(total_release,total_birth);eprintln!("[DEBUG] Original Binary {field}/{checkpoint} cancellation retained schema{} octets{} born{born}/released0, zero close0/0 and funded release{total_release}",partial_schema.get(),partial_octets.get());}}
}

#[test]
fn binary_original_receiving_literal_schema_and_relational_constraints(){
 use semio_framework_os_kernel::{ArtifactSqliteSnapshot,NativeSnapshotDecodeOwner,NativeSnapshotEncodeOwner,sqlite_snapshot::{SqliteSnapshotControl,SqliteValue}};
 use semio_framework_value::native_decoding::NativeDecodeRetirementRecipient;
 use semio_framework_value::native_encoding::NativeEncodeRetirementRecipient;
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let maximum=original["nativeMaximumBytes"].as_u64().unwrap()as usize;let snapshot=super::BinarySnapshot{schema:original["literalSchema"].as_str().unwrap().into(),bytes:fixture["shapeCases"][0]["expected"].as_array().unwrap().iter().map(|v|v.as_u64().unwrap()as u8).collect()};let mut callback=|_|true;let mut recipient=NativeDecodeRetirementRecipient::new();let mut native=NativeDecodeControl::new(maximum,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();let mut owner=NativeSnapshotDecodeOwner::new(&mut native,full);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let database=snapshot.to_sqlite_database_receiving(&mut control,&mut owner).unwrap();drop(owner);while native.has_retirement_owner(){native.close_retirement_recipient(full).unwrap();}
 for row in fixture["semanticCases"].as_array().unwrap(){let mut candidate=database.clone();match row["id"].as_str().unwrap(){"literal-schema"=>{},"row-permutation"=>candidate.table_mut("binary_byte").unwrap().rows.reverse(),"invalid-octet"=>candidate.table_mut("binary_byte").unwrap().rows[0].values[3]=SqliteValue::Integer(256),"ordinal-gap"=>candidate.table_mut("binary_byte").unwrap().rows[0].values[2]=SqliteValue::Integer(99),"duplicate-identity"=>{let rows=&mut candidate.table_mut("binary_byte").unwrap().rows;rows[1].rowid=rows[0].rowid;rows[1].values[0]=rows[0].values[0].clone();},"unknown-document"=>candidate.table_mut("binary_byte").unwrap().rows[0].values[1]=SqliteValue::Integer(2),"missing-document"=>candidate.table_mut("binary_document").unwrap().rows.clear(),_=>unreachable!()};let mut callback=|_|true;let mut recipient=NativeEncodeRetirementRecipient::new();let mut native=semio_framework_value::NativeEncodeControl::new(maximum,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();let mut owner=NativeSnapshotEncodeOwner::new(&mut native,full);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let(result,born,released)=observe(||super::BinarySnapshot::from_sqlite_database_receiving(&candidate,&mut control,&mut owner));let progress=owner.progress();drop(owner);assert_eq!(result.is_ok(),row["accepted"].as_bool().unwrap(),"{}",row["id"]);if let Ok(output)=result{assert_eq!(output,snapshot);}else{assert_eq!(released,0);}while native.has_retirement_owner(){native.close_retirement_recipient(full).unwrap();}eprintln!("[DEBUG] Original Binary relational {} accepted{} actual born{born}/released{released} retained{}",row["id"],row["accepted"],progress.retained_capacity_bytes);}
}
#[test]
fn binary_original_receiving_native_output_matches_closed_raw_and_hex(){
 use semio_framework_os_kernel::{ArtifactSqliteSnapshot,NativeSnapshotEncodeOwner,sqlite_snapshot::{SnapshotEncoding,SqliteSnapshotControl}};
 use semio_framework_value::native_encoding::NativeEncodeRetirementRecipient;
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let maximum=original["nativeMaximumBytes"].as_u64().unwrap()as usize;
 for row in fixture["shapeCases"].as_array().unwrap().iter().filter(|row|row["accepted"]==true){let bytes=row["expected"].as_array().unwrap().iter().map(|v|v.as_u64().unwrap()as u8).collect::<Vec<_>>();let snapshot=super::BinarySnapshot{schema:original["canonicalSchema"].as_str().unwrap().into(),bytes};for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let mut callback=|_|true;let mut recipient=NativeEncodeRetirementRecipient::new();let mut native=semio_framework_value::NativeEncodeControl::new(maximum,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();let mut owner=NativeSnapshotEncodeOwner::new(&mut native,full);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let(result,born,released)=observe(||snapshot.encode_sqlite_snapshot_native(encoding,&mut control,&mut owner));let output=result.unwrap();let progress=owner.progress();drop(owner);match output{store::io_schema::IoPayload::Binary(bytes)=>assert_eq!(bytes,snapshot.bytes),store::io_schema::IoPayload::Text(text)=>{let suffix=snapshot.bytes.iter().map(|byte|format!("{byte:02x}")).collect::<String>();assert_eq!(text,original["canonicalPrefix"].as_str().unwrap().to_owned()+&suffix);}}while native.has_retirement_owner(){native.close_retirement_recipient(full).unwrap();}eprintln!("[DEBUG] Original Binary native output {} {encoding:?} actual born{born}/released{released} retained{}",row["id"],progress.retained_capacity_bytes);}}
}

#[test]
fn binary_original_receiving_output_cancellation_keeps_actual_payload_until_funded_close(){
 use semio_framework_os_kernel::{ArtifactSqliteSnapshot,NativeSnapshotEncodeOwner,sqlite_snapshot::{SnapshotEncoding,SqliteSnapshotControl}};
 use semio_framework_value::{native_encoding::{NativeEncodeProgress,NativeEncodeRetirementRecipient},ValueRefusalKind};
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let zero=grant(&original["closeZeroGrant"]);let close=grant(&original["closeFundedGrant"]);let policy=&fixture["cancellation"];let pattern=policy["bytePattern"].as_array().unwrap();let bytes=(0..policy["byteCount"].as_u64().unwrap()as usize).map(|index|pattern[index%pattern.len()].as_u64().unwrap()as u8).collect::<Vec<_>>();let snapshot=super::BinarySnapshot{schema:original["canonicalSchema"].as_str().unwrap().into(),bytes};
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{for checkpoint in policy["checkpoints"].as_array().unwrap(){let checkpoint=checkpoint.as_str().unwrap();let total=snapshot.bytes.len();let after=match checkpoint{"first"=>0,"interior"=>total/2,"final"=>total,_=>unreachable!()};let armed=Cell::new(false);let reached=Cell::new(false);let restored=Cell::new(false);let mut callback=|event:NativeEncodeProgress|{if !armed.get(){restored.set(event.completed==17&&event.total==17);return true}let stop=event.total==total&&event.completed>=after;reached.set(reached.get()||stop);!stop};let mut recipient=NativeEncodeRetirementRecipient::new();let mut native=semio_framework_value::NativeEncodeControl::new(original["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();native.begin_stage(17).unwrap();native.advance(17).unwrap();armed.set(true);let mut owner=NativeSnapshotEncodeOwner::new(&mut native,full);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let(result,born,released)=observe(||snapshot.encode_sqlite_snapshot_native(encoding,&mut control,&mut owner));let progress=owner.progress();drop(owner);assert_eq!(result.unwrap_err().kind,ValueRefusalKind::Canceled);assert!(reached.get());assert_eq!(released,0);assert_eq!(born,progress.retained_capacity_bytes);assert!(native.has_retirement_owner());armed.set(false);native.checkpoint().unwrap();assert!(restored.get());let(_,zero_born,zero_release)=observe(||native.close_retirement_recipient(zero).unwrap());assert_eq!((zero_born,zero_release),(0,0));assert!(native.has_retirement_owner());let mut total_release=0;let mut total_birth=born;while native.has_retirement_owner(){let(step,close_born,close_release)=observe(||native.close_retirement_recipient(close).unwrap());assert_eq!(close_born,step.progress().retained_capacity_bytes);assert_eq!(close_release,step.progress().released_bytes);total_release+=close_release;total_birth+=close_born;}assert_eq!(total_release,total_birth);eprintln!("[DEBUG] Original Binary {encoding:?}/{checkpoint} output cancellation actual born{born}/released0, zero close0/0 and funded release{total_release}");}}
}

#[test]
fn binary_original_receiving_explicit_subset_policy_preserves_zero_authority(){
 use semio_framework_os_kernel::{ArtifactSqliteSnapshot,NativeSnapshotDecodeOwner,NativeSnapshotEncodeOwner,sqlite_snapshot::{SqliteDatabase,SqliteSnapshotControl}};
 let fixture=fixture();let original=&fixture["original"];let zero=grant(&original["refusalGrant"]);let snapshot=super::BinarySnapshot{schema:original["canonicalSchema"].as_str().unwrap().into(),bytes:Vec::new()};let database=SqliteDatabase{tables:Vec::new()};
 for row in fixture["subsetCases"].as_array().unwrap(){let dialect=semio_framework_artifact_reference::ArtifactDialect{artifact_kind:"s.stdio.binary".into(),standard:"raw".into(),subset:row["subset"].as_str().unwrap().into()};let mut callback=|_|true;let mut native=NativeDecodeControl::new(0,&mut callback);let mut owner=NativeSnapshotDecodeOwner::new(&mut native,zero);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let(result,born,released)=observe(||snapshot.validate_sqlite_snapshot_subset_decoding(&dialect,&database,&mut control,&mut owner));assert_eq!((born,released),(0,0));assert_eq!(result.is_ok(),row["accepted"].as_bool().unwrap());assert_eq!(owner.progress(),Default::default());if let Err(error)=result{assert_eq!(error.cause.message,row["cause"].as_str().unwrap());}drop(owner);assert_eq!(native.owned_bytes(),0);let mut callback=|_|true;let mut native=semio_framework_value::NativeEncodeControl::new(0,&mut callback);let mut owner=NativeSnapshotEncodeOwner::new(&mut native,zero);let mut sql_callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut sql_callback,Default::default());let(result,born,released)=observe(||snapshot.validate_sqlite_snapshot_subset_encoding(&dialect,&database,&mut control,&mut owner));assert_eq!((born,released),(0,0));assert_eq!(result.is_ok(),row["accepted"].as_bool().unwrap());assert_eq!(owner.progress(),Default::default());if let Err(error)=result{assert_eq!(error.cause.message,row["cause"].as_str().unwrap());}drop(owner);assert_eq!(native.owned_bytes(),0);}
 eprintln!("[DEBUG] Original Binary explicit wildcard/unsupported subset policy preserves zero five-axis authority, both native directions and allocator birth/release0/0");
}


#[test]
fn binary_original_receiving_required_pack_retains_every_cancelled_backing_and_raw_carrier(){
 use semio_framework_os_kernel::{ArtifactPackReceiving,NativeSnapshotDecodeOwner};
 use semio_framework_value::{native_decoding::NativeDecodeRetirementRecipient,ControlledRetirement,RetainedCloneStep,ValueRefusalKind};
 let fixture=fixture();let original=&fixture["original"];let full=grant(&original["grant"]);let close=grant(&original["closeFundedGrant"]);let zero=grant(&original["closeZeroGrant"]);let policy=&fixture["cancellation"];let pattern=policy["bytePattern"].as_array().unwrap();let bytes=(0..policy["byteCount"].as_u64().unwrap()as usize).map(|index|pattern[index%pattern.len()].as_u64().unwrap()as u8).collect::<Vec<_>>();let wire=bytes.as_ptr();let mut canceled=0;
 for cut in 0..24{
  let enabled=Cell::new(true);let turns=Cell::new(0usize);let mut callback=|_|{let turn=turns.get();turns.set(turn+1);!enabled.get()||turn<cut};let mut recipient=NativeDecodeRetirementRecipient::new();let mut native=NativeDecodeControl::new(original["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut callback);native.install_retirement_recipient(&mut recipient).unwrap();let mut owner=NativeSnapshotDecodeOwner::new(&mut native,full);
  let(result,born,released)=observe(||super::BinarySnapshot::receive_pack(&bytes,&mut owner));let progress=owner.progress();assert_eq!(born,progress.retained_capacity_bytes);assert_eq!(released,progress.released_bytes);drop(owner);enabled.set(false);assert_eq!(wire,bytes.as_ptr());let mut output=match result{Ok(output)=>{assert_eq!(output.bytes,bytes);assert_eq!(output.schema,crate::STDIO_BINARY_DOCUMENT_SCHEMA);Some(output)},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);assert_eq!(error.retained_progress(),progress);canceled+=1;None}};
  let mut extra_born=0;let mut extra_released=0;
  if native.has_retirement_owner(){let(step,b,r)=observe(||native.close_retirement_recipient(zero).unwrap());assert_eq!((b,r),(0,0));assert_eq!(step.progress(),Default::default());assert!(native.has_retirement_owner());}
  for _ in 0..4096{if !native.has_retirement_owner(){break}let(step,b,r)=observe(||native.close_retirement_recipient(close).unwrap());assert_eq!(b,step.progress().retained_capacity_bytes);assert_eq!(r,step.progress().released_bytes);extra_born+=b;extra_released+=r;}assert!(!native.has_retirement_owner());
  let mut retirement=ControlledRetirement::new(output.take()).unwrap();for _ in 0..4096{if retirement.terminal_is_empty(){break}let(step,b,r)=observe(||retirement.step(close).unwrap());assert_eq!(b,step.progress().retained_capacity_bytes);assert_eq!(r,step.progress().released_bytes);extra_born+=b;extra_released+=r;if matches!(step,RetainedCloneStep::Complete(_)){break}}assert!(retirement.terminal_is_empty());assert_eq!(born+extra_born,released+extra_released);
  eprintln!("[DEBUG] Original required Binary raw receiver cut{cut} actual born{born}/released{released}, retained original wire, fixed-policy cleanup{extra_born}/{extra_released}");
 }
 assert!(canceled>0);
}
