/** 🖨️ Explicit Raster layer, mask, literal child and complete intrinsic entities. */
import sql from "./🗄️.sql" with {type:"text"};
import type {RasterSnapshot} from "../../../🧬️schema/📸️snapshot/🟦️.ts";
import type {RasterLayerNode,RasterLayerMask,RasterTransform} from "../../../🧬️schema/🟦️.ts";
import type {IntrinsicValue} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🧬️schema/🟦️.ts";
import type {SqliteDatabase,SqliteValue,SqliteRow} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import {ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteInteger,artifactSqliteText,artifactSqliteBoolean,artifactSqliteOrderedRowsControlled,artifactSqliteCheckpoint,type ArtifactSqliteOptions} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {encodeIeee754Cells,readBinary64,readBinary32} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import {parseBinary64,parseBinary32,type Binary64,type Binary32} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts";
import {artifactSqliteOrderKeyEntries,artifactSqliteCompareKeys} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🔤️keys/🟦️.ts";
export const RASTER_SQLITE_SCHEMA:string=sql;
const bool=(value:boolean)=>{if(typeof value!=="boolean")throw Error("Raster boolean required");return value?1n:0n;};
const text=(value:string)=>{if(typeof value!=="string")throw Error("Raster text required");return value;};
const u32=(value:number|undefined)=>{if(value===undefined)return null;if(!Number.isInteger(value)||value<0||value>0xffffffff)throw Error("Raster unsigned32 range");return BigInt(value);};
/** 📤️ Project the actual owned Raster forest and each intrinsic parameter variant. */
export async function rasterSnapshotToSqliteDatabase(s:RasterSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const p=await ArtifactSqliteProjection.create(RASTER_SQLITE_SCHEMA,options),put=(name:string,cells:readonly SqliteValue[],id?:bigint)=>p.insert('raster_'+name,cells,id);
 const scalar64=(value:Binary64)=>put('scalar64',encodeIeee754Cells([1n,parseBinary64(value)],[{index:1,width:64}],options.maxColumns).slice(1));
 const scalar32=(value:Binary32)=>put('scalar32',encodeIeee754Cells([1n,parseBinary32(value)],[{index:1,width:32}],options.maxColumns).slice(1));
 const transform=async(name:string,id:bigint,v:RasterTransform)=>{await put(name,[await scalar64(v.x),await scalar64(v.y),await scalar64(v.a),await scalar64(v.b),await scalar64(v.c),await scalar64(v.d)],id);};
 const intrinsic=async(root:IntrinsicValue):Promise<bigint>=>{type Edge={table:'item'|'member';parent:bigint;ordinal:number;name?:string};type Task={value:IntrinsicValue;edge?:Edge}|{close:IntrinsicValue};const pending:Task[]=[{value:root}],active=new Set<IntrinsicValue>();let rootId=0n;
  while(pending.length){await p.checkpoint();const task=pending.pop()!;if('close'in task){active.delete(task.close);continue;}const v=task.value;if(v===null||typeof v!=='object'||active.has(v))throw Error("Raster cyclic or invalid intrinsic ownership");active.add(v);pending.push({close:v});const id=await put('value',[text(v.kind)]);if(task.edge){const e=task.edge;await put(e.table,e.table==='item'?[e.parent,BigInt(e.ordinal),id]:[e.parent,BigInt(e.ordinal),text(e.name!),id]);}else rootId=id;
   switch(v.kind){case'null':break;case'boolean':await put('boolean',[bool(v.value)],id);break;case'signed':if(typeof v.value!=='bigint'||v.value< -9223372036854775808n||v.value>9223372036854775807n)throw Error("Raster signed64 range");await put('signed',[v.value],id);break;case'unsigned':if(typeof v.value!=='bigint'||v.value<0n||v.value>18446744073709551615n)throw Error("Raster unsigned64 range");await put('unsigned',[v.value>>32n,v.value&0xffffffffn],id);break;case'float':await put('float',[await scalar64(v.value)],id);break;case'text':await put('text',[text(v.value)],id);break;case'bytes':if(!(v.value instanceof Uint8Array))throw Error("Raster intrinsic octets required");await put('bytes',[v.value],id);break;
    case'array':if(!Array.isArray(v.items))throw Error("Raster intrinsic ordered items required");p.checkRowsAdditional(pending.length+v.items.length*2);await put('array',[],id);for(let i=v.items.length-1;i>=0;i--)pending.push({value:v.items[i]!,edge:{table:'item',parent:id,ordinal:i}});break;
    case'object':if(!Array.isArray(v.members))throw Error("Raster intrinsic ordered members required");p.checkRowsAdditional(pending.length+v.members.length*2);await put('object',[],id);for(let i=v.members.length-1;i>=0;i--){const m=v.members[i]!;pending.push({value:m.value,edge:{table:'member',parent:id,ordinal:i,name:text(m.name)}});}break;
    default:throw Error("Raster intrinsic variant");
   }
  }return rootId;
 };
 await put('document',[text(s.schema),text(s.id),s.title===undefined?null:text(s.title)],1n);
 const assets=Object.entries(s.assets);if(assets.length>64)throw Error("Raster map capacity");p.checkRowsAdditional(assets.length);await artifactSqliteOrderKeyEntries(assets,options);for(let i=0;i<assets.length;i++){const[key,h]=assets[i]!,t=h.target,d=t.dialect;await put('asset',[1n,BigInt(i),key,text(h.childId),text(d.artifactKind),text(d.standard),text(d.subset),text(t.artifactId)]);}
 type Pending={node:RasterLayerNode;parent:bigint|null;ordinal:number};p.checkRowsAdditional(s.layers.length);const pending:Pending[]=[];for(let i=s.layers.length-1;i>=0;i--)pending.push({node:s.layers[i]!,parent:null,ordinal:i});
 while(pending.length){await p.checkpoint();const{node:v,parent,ordinal}=pending.pop()!;const id=await put('layer',[parent===null?1n:null,parent,BigInt(ordinal),text(v.kind),text(v.id),text(v.name),bool(v.visible),bool(v.locked),await scalar32(v.opacity),text(v.blendMode)]);await transform('transform',id,v.transform);
  const mask=(v.kind==='pixel'||v.kind==='group')?v.mask:undefined;if(mask!==undefined){await put('mask',[bool(mask.enabled),bool(mask.linked),bool(mask.invert),u32(mask.width),u32(mask.height),mask.imageKey===undefined?null:text(mask.imageKey)],id);await transform('mask_transform',id,mask.transform);}
  switch(v.kind){case'pixel':await put('pixel',[u32(v.width),u32(v.height),v.imageKey===undefined?null:text(v.imageKey)],id);break;case'group':await put('group',[],id);p.checkRowsAdditional(pending.length+v.children.length);for(let i=v.children.length-1;i>=0;i--)pending.push({node:v.children[i]!,parent:id,ordinal:i});break;case'adjustment':{await put('adjustment',[text(v.adjustmentKind)],id);const params=Object.entries(v.params);if(params.length>64)throw Error("Raster map capacity");p.checkRowsAdditional(params.length);await artifactSqliteOrderKeyEntries(params,options);for(let i=0;i<params.length;i++){const[key,value]=params[i]!;await put('parameter',[id,BigInt(i),key,await intrinsic(value)]);}break;}default:throw Error("Raster layer variant");}
 }return p.finish();
}
/** 📥️ Consume each declared entity once and reconstruct explicit ordered typed owners. */
export async function rasterSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<RasterSnapshot>{
 const names=['document','scalar64','scalar32','asset','layer','transform','mask','mask_transform','pixel','group','adjustment','parameter','value','boolean','signed','unsigned','float','text','bytes','array','item','object','member'],widths=[4,4,4,9,11,7,7,7,4,1,2,5,2,2,2,3,2,2,2,1,4,1,5],source=await artifactSqliteTables(database,RASTER_SQLITE_SCHEMA,options),tables=new Map<string,Map<bigint,SqliteRow>>();
 for(let i=0;i<names.length;i++){const rows=new Map<bigint,SqliteRow>();for(let j=0;j<source[i]!.length;j++){const row=source[i]![j]!;if(row.rowid<=0n||row.values.length!==widths[i]||artifactSqliteInteger(row,0)!==row.rowid||rows.has(row.rowid))throw Error("Raster row identity or columns");rows.set(row.rowid,row);if(j%256===0)await artifactSqliteCheckpoint(options,'reconstructSnapshot',j,source[i]!.length);}tables.set(names[i]!,rows);}
 const table=(name:string)=>{const rows=tables.get(name);if(!rows)throw Error("Raster unknown table");return rows;},take=(name:string,id:bigint)=>{const rows=table(name),v=rows.get(id);if(v===undefined)throw Error("Raster dangling or multiply owned entity");rows.delete(id);return v;},has=(name:string,id:bigint)=>table(name).has(id),integer=artifactSqliteInteger,string=artifactSqliteText,boolean=artifactSqliteBoolean;
 const scalar64=(row:SqliteRow,index:number)=>readBinary64(take('scalar64',integer(row,index)),1,[{index:1,width:64}]);
 const real=(row:SqliteRow,index:number)=>scalar64(row,index);
 const optionalText=(row:SqliteRow,index:number)=>row.values[index]===null?undefined:string(row,index);
 const unsigned=(row:SqliteRow,index:number)=>{const v=integer(row,index);if(v<0n||v>0xffffffffn)throw Error("Raster unsigned32 range");return Number(v);};
 const optionalUnsigned=(row:SqliteRow,index:number)=>row.values[index]===null?undefined:unsigned(row,index);
 const transform=(name:string,id:bigint):RasterTransform=>{const row=take(name,id);return{x:real(row,1),y:real(row,2),a:real(row,3),b:real(row,4),c:real(row,5),d:real(row,6)};};
 const groups=new Map<string,Map<bigint,SqliteRow[]>>();
 const list=async(name:string,parent:bigint,index=1,ordinal=2)=>{const key=name+':'+index;let indexed=groups.get(key);if(indexed===undefined){indexed=new Map();let count=0;for(const row of table(name).values()){if(row.values[index]!==null){const parent=integer(row,index),items=indexed.get(parent)??[];items.push(row);indexed.set(parent,items);}if(++count%256===0)await artifactSqliteCheckpoint(options,'reconstructSnapshot',count,table(name).size);}groups.set(key,indexed);}const values=await artifactSqliteOrderedRowsControlled(indexed.get(parent)??[],ordinal,options);indexed.delete(parent);for(const row of values)take(name,row.rowid);return values;};
 const intrinsic=async(root:bigint):Promise<IntrinsicValue>=>{type Task={id:bigint;put:(v:IntrinsicValue)=>void};let result:IntrinsicValue|undefined;const pending:Task[]=[{id:root,put:v=>{result=v}}];while(pending.length){const task=pending.pop()!,row=take('value',task.id),kind=string(row,1);let value:IntrinsicValue;
  switch(kind){case'null':value={kind};break;case'boolean':value={kind,value:boolean(take('boolean',task.id),1)};break;case'signed':value={kind,value:integer(take('signed',task.id),1)};break;case'unsigned':{const v=take('unsigned',task.id);value={kind,value:(BigInt(unsigned(v,1))<<32n)|BigInt(unsigned(v,2))};break;}case'float':value={kind,value:scalar64(take('float',task.id),1)};break;case'text':value={kind,value:string(take('text',task.id),1)};break;case'bytes':{const v=take('bytes',task.id).values[1];if(!(v instanceof Uint8Array))throw Error("Raster intrinsic blob required");const bytes=new Uint8Array(v.length);if(v.length>65536)await artifactSqliteCheckpoint(options,'reconstructSnapshot',0,v.length);for(let i=0;i<v.length;i+=65536){bytes.set(v.subarray(i,Math.min(v.length,i+65536)),i);if(v.length>65536)await artifactSqliteCheckpoint(options,'reconstructSnapshot',Math.min(v.length,i+65536),v.length);}value={kind,value:bytes};break;}
   case'array':{take('array',task.id);const rows=await list('item',task.id),items:IntrinsicValue[]=new Array(rows.length);value={kind,items};for(let i=rows.length-1;i>=0;i--)pending.push({id:integer(rows[i]!,3),put:v=>{items[i]=v}});break;}
   case'object':{take('object',task.id);const rows=await list('member',task.id),members:{name:string;value:IntrinsicValue}[]=new Array(rows.length);value={kind,members};for(let i=rows.length-1;i>=0;i--){const row=rows[i]!,name=string(row,3);pending.push({id:integer(row,4),put:v=>{members[i]={name,value:v}}});}break;}
   default:throw Error("Raster intrinsic variant");
  }task.put(value);await artifactSqliteCheckpoint(options,'reconstructSnapshot',0,0,false);
 }return result!;};
 const document=take('document',1n),s:RasterSnapshot={schema:string(document,1),id:string(document,2),layers:[],assets:{}};if(document.values[3]!==null)s.title=string(document,3);
 let previous:string|undefined;const assets=await list('asset',1n);if(assets.length>64)throw Error("Raster map capacity");for(const row of assets){const key=string(row,3);if(previous!==undefined&&await artifactSqliteCompareKeys(previous,key,options,'reconstructSnapshot')>=0)throw Error("Raster asset key order");previous=key;Object.defineProperty(s.assets,key,{enumerable:true,writable:true,configurable:true,value:{childId:string(row,4),target:{dialect:{artifactKind:string(row,5),standard:string(row,6),subset:string(row,7)},artifactId:string(row,8)}}});}
 type Task={row:SqliteRow;output:RasterLayerNode[]};const pending:Task[]=[];for(const row of(await list('layer',1n,1,3)).reverse())pending.push({row,output:s.layers});
 while(pending.length){const{row,output}=pending.pop()!;if((row.values[1]===null)===(row.values[2]===null))throw Error("Raster ambiguous forest owner");const id=row.rowid,kind=string(row,4),opacity=readBinary32(take('scalar32',integer(row,9)),1,[{index:1,width:32}]),common={id:string(row,5),name:string(row,6),visible:boolean(row,7),locked:boolean(row,8),opacity,blendMode:string(row,10),transform:transform('transform',id)};let mask:RasterLayerMask|undefined;if(has('mask',id)){const row=take('mask',id);mask={enabled:boolean(row,1),linked:boolean(row,2),invert:boolean(row,3),transform:transform('mask_transform',id)};const width=optionalUnsigned(row,4),height=optionalUnsigned(row,5),key=optionalText(row,6);if(width!==undefined)mask.width=width;if(height!==undefined)mask.height=height;if(key!==undefined)mask.imageKey=key;}
  let node:RasterLayerNode;switch(kind){case'pixel':{const row=take('pixel',id);node={kind,...common};if(mask!==undefined)node.mask=mask;const width=optionalUnsigned(row,1),height=optionalUnsigned(row,2),key=optionalText(row,3);if(width!==undefined)node.width=width;if(height!==undefined)node.height=height;if(key!==undefined)node.imageKey=key;break;}
   case'group':{take('group',id);const children:RasterLayerNode[]=[];node={kind,...common,children};if(mask!==undefined)node.mask=mask;for(const row of(await list('layer',id,2,3)).reverse())pending.push({row,output:children});break;}
   case'adjustment':{if(mask!==undefined)throw Error("Raster adjustment cannot own mask");const row=take('adjustment',id),params:Record<string,IntrinsicValue>={};const rows=await list('parameter',id);if(rows.length>64)throw Error("Raster map capacity");let previous:string|undefined;for(const row of rows){const key=string(row,3);if(previous!==undefined&&await artifactSqliteCompareKeys(previous,key,options,'reconstructSnapshot')>=0)throw Error("Raster parameter key order");previous=key;Object.defineProperty(params,key,{value:await intrinsic(integer(row,4)),enumerable:true,writable:true,configurable:true});}node={kind,...common,adjustmentKind:string(row,1),params};break;}
   default:throw Error("Raster layer variant");
  }output.push(node);await artifactSqliteCheckpoint(options,'reconstructSnapshot',0,0,false);
 }for(const rows of tables.values())if(rows.size)throw Error("orphan Raster entities");return s;
}
