import {test,expect} from "bun:test";
import Ajv from "ajv/dist/2020";
import TOML from "@iarna/toml";
import glob from "fast-glob";
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import {captureOwnedProcess} from "../../../../../../../../🔨️modules/🏃️process/📥️capture/🟦️.ts";
import schema from "../🧬️schema/🔣️.json";
import vectors from "../🧫️fixtures/🔣️.json";
import {parseCargoCommandScope,selectedCargoArguments} from "../🟦️.ts";
import {CargoCliOperationOwner,parseCargoCliPolicy,runCargoCliCommand} from "../../🎛️control/🚪️cli/🟦️.ts";
import policy from "../../🎛️control/🚪️cli/🧩️entrypoint/🎛️policy/🔣️.json";
import cliSchema from "../../🎛️control/🚪️cli/🧬️schema/🔣️.json";
import cliVectors from "../../🎛️control/🚪️cli/🧫️fixtures/🔣️.json";
const original=JSON.parse(readFileSync(new URL("../../🧫️fixtures/🔣️.json",import.meta.url),"utf8")),artifact=process.env.SEMIO_TEST_ARTIFACT_DIR;
if(!artifact)throw Error("Explicit controlled Cargo test artifact root required");
const put=(root:string,path:string,source:string)=>{mkdirSync(join(root,path,".."),{recursive:true});writeFileSync(join(root,path),source);};
const workspace=(members:string[])=>`[workspace]\nresolver="2"\nmembers=${JSON.stringify(members)}\n[workspace.metadata.semio.repository]\nschema-version=1\nexclude-patterns=[]\nowner-manifests=["*/Cargo.toml"]\nmember-manifests=${JSON.stringify(members.map(member=>member+"/Cargo.toml"))}\n[workspace.package]\nedition="2021"\n`;
const pkg=(name:string)=>`[package]\nname="${name}"\nversion="0.1.0"\nedition.workspace=true\n[lib]\npath="🦀️.rs"\n`;
const owner=()=>{const deadline=performance.now()+60000;return new CargoCliOperationOwner(parseCargoCliPolicy(policy),{remainingMilliseconds:()=>deadline-performance.now(),publish:event=>{expect(Number.isSafeInteger(event.completed)).toBe(true);console.log("[DEBUG] controlled Cargo "+event.stage+" "+event.completed);},yieldContinuation:()=>new Promise<void>(done=>setImmediate(done))});};
test("explicit portable command scopes agree with independent closed schema",()=>{const admit=new Ajv({strict:true}).compile(schema);for(const value of vectors.accepted){expect(admit(value)).toBe(true);expect(parseCargoCommandScope(value)).toEqual(value);}for(const value of vectors.rejected){expect(admit(value)).toBe(false);expect(()=>parseCargoCommandScope(value)).toThrow();}});
test("all original CLI policy vectors retain separate finite discovery and retirement authority",()=>{const admit=new (require("ajv").default)({strict:true}).compile(cliSchema);for(const value of cliVectors.accepted){expect(admit(value)).toBe(true);expect(parseCargoCliPolicy(value)).toEqual(value);}for(const value of cliVectors.rejected){expect(admit(value)).toBe(false);expect(()=>parseCargoCliPolicy(value)).toThrow();}});
test("all original package command cases use asynchronous finite physical selection",async()=>{const root=mkdtempSync(join(artifact,"cs-"));put(root,"Cargo.toml",workspace(["framework/*"]));put(root,"framework/kernel/Cargo.toml",pkg("neutral-kernel"));put(root,"specific/Cargo.toml",workspace(["*"]));put(root,"specific/model/Cargo.toml",pkg("specific-model"));expect(TOML.parse(readFileSync(join(root,"Cargo.toml"),"utf8"))).toEqual(Bun.TOML.parse(readFileSync(join(root,"Cargo.toml"),"utf8")));expect(await glob("framework/*/Cargo.toml",{cwd:root,followSymbolicLinks:false})).toEqual(["framework/kernel/Cargo.toml"]);for(const row of original.commandSelection){const operation=owner();try{const result=runCargoCliCommand(operation,()=>selectedCargoArguments(root,row.args,{schemaVersion:1,manifest:"Cargo.toml"},operation.operation));expect(result).toBeInstanceOf(Promise);if(row.error)await expect(result).rejects.toThrow();else expect(await result).toEqual([row.args[0],"--manifest-path",join(root,row.manifest),...row.args.slice(1)]);}finally{await operation.closeSystemOwners();}}},60000);
test("cancellation and exhausted work refuse before selecting even an explicit manifest",async()=>{for(const cancelled of[false,true]){const operation=owner();if(cancelled)operation.cancelDiscovery();else operation.operation.workspace.completed=operation.operation.maximumUnits;await expect(runCargoCliCommand(operation,()=>selectedCargoArguments(process.cwd(),["check","--manifest-path","Cargo.toml"],{schemaVersion:1,manifest:"Cargo.toml"},operation.operation))).rejects.toThrow();await operation.closeSystemOwners();}},60000);

test("explicit child workspace admission survives parent package exclusions",async()=>{
 const row=vectors.excludedIndependentOwner,root=mkdtempSync(join(artifact,"cx-")),rootSource=workspace(row.rootMembers).replace('resolver="2"','resolver="2"\nexclude='+JSON.stringify(row.rootExclusions)).replace('exclude-patterns=[]','exclude-patterns='+JSON.stringify(row.rootExclusions)).replace('owner-manifests=["*/Cargo.toml"]','owner-manifests='+JSON.stringify(row.ownerManifests));put(root,"Cargo.toml",rootSource);put(root,"root-package/Cargo.toml",pkg(row.rootName));put(root,"root-package/🦀️.rs","pub fn value()->u8{1}\n");put(root,"nested/Cargo.toml",workspace(row.childMembers));put(root,row.childManifest,pkg(row.childName));put(root,"nested/package/🦀️.rs","pub fn value()->u8{2}\n");
 expect(TOML.parse(rootSource).workspace.exclude).toEqual(row.rootExclusions);expect(await glob(row.ownerManifests,{cwd:root,followSymbolicLinks:false})).toEqual(["nested/Cargo.toml"]);const operation=owner();try{const native=await captureOwnedProcess("cargo",["metadata","--manifest-path",join(root,row.childManifest),"--offline","--no-deps","--format-version","1"],{invocation:{policy:{version:1,owner:"cargo-metadata-oracle",maximumElapsedMilliseconds:0},capabilities:{},control:{signal:operation.operation.signal,remainingMilliseconds:()=>null,publish(){},async yieldContinuation(){}}},cwd:root,env:{...process.env},budgetMs:Math.floor(operation.operation.remainingMilliseconds()),maxOutputBytes:4*1024*1024,stdoutPath:join(root,"metadata.json"),stderrPath:join(root,"metadata.stderr") });expect(native.status).toBe(0);const oracle=JSON.parse(native.stdout),manifest=oracle.packages.find((value:any)=>value.name===row.childName).manifest_path;expect(oracle.workspace_root).toBe(join(root,"nested"));expect(manifest).toBe(join(root,row.childManifest));expect(await runCargoCliCommand(operation,()=>selectedCargoArguments(root,row.args,{schemaVersion:1,manifest:"Cargo.toml"},operation.operation))).toEqual([row.args[0],"--manifest-path",manifest,...row.args.slice(1)]);}finally{await operation.closeSystemOwners();}
},60000);

test("actual asynchronous native argv discovery never reads testing collections while preserving named modules",async()=>{
 const law=JSON.parse(readFileSync(new URL("../../🧫️fixtures/🧭️native-discovery/🔣️.json",import.meta.url),"utf8")).testingCollections,root=mkdtempSync(join(artifact,"ct-"));
 put(root,"Cargo.toml",workspace(["framework/**"]).replace('owner-manifests=["*/Cargo.toml"]','owner-manifests=["ordinary/**/Cargo.toml"]'));
 const selections:{name:string;manifest:string}[]=[];
 for(const [index,row]of law.members.entries()){const name="physical-member-"+index;put(root,row.manifest,row.admitted?pkg(name):"[forbidden invalid TOML []");if(row.admitted){selections.push({name,manifest:row.manifest});expect(TOML.parse(readFileSync(join(root,row.manifest),"utf8")).package.name).toBe(name);}}
 for(const [index,row]of law.owners.entries()){put(root,row.manifest,row.admitted?workspace(["pkg"]):"[forbidden invalid TOML []");if(row.admitted){const manifest=join(row.manifest,"../pkg/Cargo.toml").replaceAll("\\","/"),name="physical-owner-"+index;put(root,manifest,pkg(name));selections.push({name,manifest});}}
 const physical=await glob("**/Cargo.toml",{cwd:root,followSymbolicLinks:false});for(const row of [...law.members,...law.owners])expect(physical).toContain(row.manifest);
 for(const row of selections){const operation=owner();try{const argv=["check","-p",row.name];expect(await runCargoCliCommand(operation,()=>selectedCargoArguments(root,argv,{schemaVersion:1,manifest:"Cargo.toml"},operation.operation))).toEqual(["check","--manifest-path",join(root,row.manifest),...argv.slice(1)]);}finally{await operation.closeSystemOwners();}}
 console.error("[DEBUG] Actual finite native argv discovery selected all genuine collection-named modules; malformed test-only documents were never admitted or parsed, independent fast-glob/TOML retained");
},60000);
