import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { dirname, isAbsolute, join, relative } from "node:path";
const root = process.env.SEMIO_FIXTURE_REPO_ROOT!, ticket = dirname(dirname(import.meta.dir));
const generated = join(ticket,"🗑️generated");
const inputPath = join(import.meta.dir,"📥️input.md");
const manifestReport = join(ticket,"📓️authored-manifest-2026-09-09.md");
const overview = join(ticket,"📓️fixture-separation-completion-2026-09-09.md");
const metadataPath = join(ticket,"🎫️ticket.json");
const command = process.argv[2];
if (command === "prepare") {
 assert(existsSync(overview), "Final verification overview is required");
 assert.deepEqual(JSON.parse(readFileSync(join(generated,"coordinator/fixture-layout-current.json"),"utf8")),[]);
 assert.deepEqual(JSON.parse(readFileSync(join(generated,"coordinator/fixture-manifest-dependencies.json"),"utf8")),[]);
 assert.equal(JSON.parse(readFileSync(join(generated,"coordinator/mutation-registry-current.json"),"utf8")).findings,0);
 assert.deepEqual(JSON.parse(readFileSync(join(generated,"coordinator/computed-fixture-read-audit.json"),"utf8")).missing,[]);
 const candidate = JSON.parse(readFileSync(join(generated,"coordinator/authored-manifest-candidate.json"),"utf8"));
 const files = [...new Set<string>([...candidate.files, inputPath, manifestReport, overview, import.meta.path, join(ticket,"📓️ticket-lifecycle-completion-2026-09-09.md")].map(path=>isAbsolute(path)?relative(root,path).replaceAll("\\","/"):path))].sort();
 assert(files.length>30000);
 assert(files.every(path=>!path.startsWith("/") && !path.split("/").includes("AGENTS.md") && !path.includes("/🗑️generated/")));
 assert(files.every(path=>!path.split("/").some(segment=>segment===".." || segment===".") && !path.includes("\0")));
 const directories = files.filter(path=>existsSync(join(root,path)) && !statSync(join(root,path)).isFile());
 assert.deepEqual(directories,[]);
 const payload = { path:"26/05/30/ASSETS-FIXTURES-SEPARATION", no_management:true, summary:readFileSync(overview,"utf8"), files };
 const input = "# Ticket Closure Input\n\n```json\n"+JSON.stringify(payload,null,2)+"\n```\n";
 assert(Buffer.byteLength(JSON.stringify(payload))<32*1024*1024);
 writeFileSync(inputPath,input);
 if (!existsSync(manifestReport)) writeFileSync(manifestReport,"# Exact Authored File Manifest\n");
 const lifecyclePath = relative(root,join(ticket,"📓️ticket-lifecycle-completion-2026-09-09.md")).replaceAll("\\","/");
 const states = files.reduce((counts,path)=>{ counts[existsSync(join(root,path))?"present":path===lifecyclePath?"planned":"removed"]++; return counts; },{present:0,removed:0,planned:0});
 writeFileSync(manifestReport,"# Exact Authored File Manifest\n\nThe full closure input is retained at [📥️input.md](./🧑‍💻coordination/📋️ticket-close/📥️input.md). Its files array is the deduplicated exact path ledger, including source and destination names of relocations, modified consumers, and retained ticket evidence. Generated outputs and AGENTS.md are excluded.\n\n"+JSON.stringify({paths:files.length,...states,requestBytes:Buffer.byteLength(input),sha256:createHash("sha256").update(input).digest("hex")})+"\n\n## Report Inputs\n\n"+candidate.inputs.map((row:any)=>"- "+row.report+": "+row.paths+" newly contributed paths").join("\n")+"\n");
 console.log("[DEBUG] "+JSON.stringify({paths:files.length,...states,requestBytes:Buffer.byteLength(input)}));
} else if (command === "verify") {
 const meta = JSON.parse(readFileSync(metadataPath,"utf8"));
 assert.equal(meta.status,"closed");
 assert.equal(meta.title,"Assets Fixtures Separation");
 const inputBytes = readFileSync(inputPath), input = JSON.parse(inputBytes.toString("utf8").match(/```json\n([\s\S]*?)\n```/)![1]);
 const manifest = JSON.parse(readFileSync(manifestReport,"utf8").match(/^\{.+\}$/m)![0]);
 assert.equal(meta.summary.trim(),input.summary.trim());
 assert.equal(meta.summary.trim(),readFileSync(overview,"utf8").trim());
 assert.equal(createHash("sha256").update(inputBytes).digest("hex"),manifest.sha256);
 assert.equal(input.files.length,manifest.paths);
 assert(input.files.length>30000);
 assert.equal(new Set(input.files).size,input.files.length);
 assert(input.files.every((path:string)=>!path.includes("/🗑️generated/") && !path.endsWith("/AGENTS.md")));
 const links = [...readFileSync(overview,"utf8").matchAll(/\]\(\.\/([^\n)]+)\)/g)];
 for (const [,path] of links) if (path!=="📓️ticket-lifecycle-completion-2026-09-09.md") assert(existsSync(join(ticket,path)),path);
 assert(!existsSync(join(ticket,"📌️important/📝️.md")));
 writeFileSync(join(ticket,"📓️ticket-lifecycle-completion-2026-09-09.md"),"# Ticket Lifecycle Completion\n\nThe actual repository MCP ticket_close call succeeded with no_management=true. The original Assets Fixtures Separation title and ASSETS-FIXTURES-SEPARATION folder are restored. The ticket metadata is closed and its summary exactly matches the retained final overview and closure input. The important-marker preimage was consumed by the repository lifecycle. The complete submitted files array contains "+input.files.length+" unique paths; its retained input SHA-256 matches the authored manifest report. All "+links.length+" overview report links were checked. No Git mutation or external message was requested.\n\nThe first close's evidence cleanup and its exact recovery are recorded in [closure retention recovery](./📓️closure-retention-recovery-2026-09-09.md). The final close used a ticket-private build overlay to preserve requested inputs and Markdown reports, with unchanged repository lifecycle source files.\n");
 console.log("[DEBUG] ticket status, original title, exact summary, "+input.files.length+" unique authored paths, input hash and "+links.length+" report links verified");
} else if (command === "cleanup") {
 assert.equal(JSON.parse(readFileSync(metadataPath,"utf8")).status,"closed");
 const lifecycle = join(ticket,"📓️ticket-lifecycle-completion-2026-09-09.md");
 assert(existsSync(lifecycle));
 const retained = (directory:string):string[] => readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{ const path = join(directory,entry.name); return path===generated?[]:entry.isDirectory()?retained(path):[path]; });
 const hashes = retained(ticket).map(path=>({path,sha256:createHash("sha256").update(readFileSync(path)).digest("hex")}));
 await rm(generated,{recursive:true,force:true});
 assert(!existsSync(generated));
 for (const item of hashes) assert.equal(createHash("sha256").update(readFileSync(item.path)).digest("hex"),item.sha256,item.path);
 const completion = readFileSync(lifecycle,"utf8")+"\nGenerated output was explicitly removed after closure. All "+hashes.length+" retained files were checked byte-for-byte by SHA-256 across generated-output removal; none were deleted or changed by that removal. This completion statement was then appended and its final bytes verified by SHA-256.\n";
 writeFileSync(lifecycle,completion);
 assert.equal(createHash("sha256").update(readFileSync(lifecycle)).digest("hex"),createHash("sha256").update(completion).digest("hex"));
 console.log("[DEBUG] ticket generated outputs removed; retained inputs and Markdown reports preserved");
} else throw new Error("Expected prepare, verify or cleanup");
