import * as sqliteOwner from "../🟦️.ts";
import{expect,test}from"bun:test";
import Ajv from"ajv";
import fixture from"../🧫️fixtures/🔣️.json";
import schema from"../../../../🧬️schema/📸️snapshot/🔣️.json";
import{Database}from"bun:sqlite";
import{Buffer}from"node:buffer";
import controls from"../🧫️fixtures/🎛️control.json";
import words from"../🧫️fixtures/🔢️binary64.json";
import choices from"../🧫️fixtures/🛂️choices.json";
import { EN1995_SQLITE_SCHEMA, en1995SnapshotToSqliteDatabase, en1995SnapshotFromSqliteDatabase, type En1995SqliteSnapshot, type En1995SqliteMember } from "../🟦️.ts";
import {binary64,type Binary64} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts";
import{exportSqliteDatabase,importSqliteDatabase}from"../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
test("EN1995 complete neutral state agrees with independent JSON schema",()=>{expect(new Ajv({strict:false}).validate(schema,fixture)).toBe(true)});
test("EN1995 owning facade exposes complete relational snapshot directions",()=>{expect(Object.hasOwn(sqliteOwner,"en1995SnapshotToSqliteDatabase")).toBe(true);expect(Object.hasOwn(sqliteOwner,"en1995SnapshotFromSqliteDatabase")).toBe(true)});
test("EN1995 root arrays enforce complete closed owned member and connection shapes",()=>{const ajv=new Ajv({strict:false});expect(ajv.validate(schema,{...fixture,members:[{}]})).toBe(false);expect(ajv.validate(schema,{...fixture,connections:[{}]})).toBe(false);expect(ajv.validate(schema,{...fixture,members:[{...fixture.members[0],unknown:true}]})).toBe(false);expect(ajv.validate(schema,{...fixture,connections:[{...fixture.connections[0],unknown:true}]})).toBe(false)});

function ownedFixture():En1995SqliteSnapshot{
 const f=fixture;return{annex:f.annex as En1995SqliteSnapshot["annex"],members:f.members.map(m=>({...m,role:m.role as En1995SqliteMember["role"],support:m.support as En1995SqliteMember["support"],bM:binary64(m.bM),hM:binary64(m.hM),spanM:binary64(m.spanM),supportLengthM:binary64(m.supportLengthM),bearingLengthM:binary64(m.bearingLengthM),bucklingLengthYM:binary64(m.bucklingLengthYM),bucklingLengthZM:binary64(m.bucklingLengthZM),lateralRestraintSpacingM:binary64(m.lateralRestraintSpacingM),notchDepthM:binary64(m.notchDepthM),notchDistanceM:binary64(m.notchDistanceM),mCritNm:binary64(m.mCritNm),massKgPerM:binary64(m.massKgPerM),massKgPerM2:binary64(m.massKgPerM2),dampingXi:binary64(m.dampingXi),fireDurationS:binary64(m.fireDurationS),bridgeNObs:binary64(m.bridgeNObs),bridgeTLYears:binary64(m.bridgeTLYears),bridgeBeta:binary64(m.bridgeBeta),bridgeA:binary64(m.bridgeA),bridgeB:binary64(m.bridgeB),bridgeCrowdPerM2:binary64(m.bridgeCrowdPerM2),actions:m.actions.map(a=>({...a,qLineNPerM:binary64(a.qLineNPerM),fPointN:binary64(a.fPointN),mKNm:binary64(a.mKNm),vKN:binary64(a.vKN),nKN:binary64(a.nKN),nTKN:binary64(a.nTKN),fC90KN:binary64(a.fC90KN)}))})),connections:f.connections.map(c=>({...c,diameterM:binary64(c.diameterM),spacingM:binary64(c.spacingM),edgeDistanceM:binary64(c.edgeDistanceM),endDistanceM:binary64(c.endDistanceM),t1M:binary64(c.t1M),t2M:binary64(c.t2M),steelPlateThicknessM:binary64(c.steelPlateThicknessM),fUK:binary64(c.fUK),actions:c.actions.map(a=>({...a,fKN:binary64(a.fKN)}))}))};
}
function nativeWord(value:number):bigint{const b=Buffer.alloc(8);b.writeDoubleBE(value);return b.readBigUInt64BE()}
function setEveryWord(s:En1995SqliteSnapshot,v:Binary64):void{
 for(const m of s.members){m.bM=v;m.hM=v;m.spanM=v;m.supportLengthM=v;m.bearingLengthM=v;m.bucklingLengthYM=v;m.bucklingLengthZM=v;m.lateralRestraintSpacingM=v;m.notchDepthM=v;m.notchDistanceM=v;m.mCritNm=v;m.massKgPerM=v;m.massKgPerM2=v;m.dampingXi=v;m.fireDurationS=v;m.bridgeNObs=v;m.bridgeTLYears=v;m.bridgeBeta=v;m.bridgeA=v;m.bridgeB=v;m.bridgeCrowdPerM2=v;for(const a of m.actions){a.qLineNPerM=v;a.fPointN=v;a.mKNm=v;a.vKN=v;a.nKN=v;a.nTKN=v;a.fC90KN=v}}
 for(const c of s.connections){c.diameterM=v;c.spacingM=v;c.edgeDistanceM=v;c.endDistanceM=v;c.t1M=v;c.t2M=v;c.steelPlateThicknessM=v;c.fUK=v;for(const a of c.actions)a.fKN=v}
}
test("EN1995 independent schema matches closed choices and every native unsigned width",()=>{
 const ajv=new Ajv({strict:false});for(const value of choices.invalidUnsigned8){expect(ajv.validate(schema,{...fixture,members:[{...fixture.members[0]!,serviceClass:value}]})).toBe(false);expect(ajv.validate(schema,{...fixture,connections:[{...fixture.connections[0]!,serviceClass:value}]})).toBe(false)}for(const value of choices.validUnsigned8){expect(ajv.validate(schema,{...fixture,members:[{...fixture.members[0]!,serviceClass:value}]})).toBe(true);expect(ajv.validate(schema,{...fixture,connections:[{...fixture.connections[0]!,serviceClass:value}]})).toBe(true)}
 for(const field of["number","rows","shearPlanes"])for(const value of choices.invalidUnsigned32)expect(ajv.validate(schema,{...fixture,connections:[{...fixture.connections[0]!,[field]:value}]})).toBe(false);for(const field of["number","rows","shearPlanes"])for(const value of choices.validUnsigned32)expect(ajv.validate(schema,{...fixture,connections:[{...fixture.connections[0]!,[field]:value}]})).toBe(true);
 expect(ajv.validate(schema,{...fixture,annex:"unknown"})).toBe(false);for(const field of["role","support"])expect(ajv.validate(schema,{...fixture,members:[{...fixture.members[0]!,[field]:"unknown"}]})).toBe(false);
});
test("EN1995 independent SQLite queries complete ordered timber relationships and applies semantic edits",async()=>{
 expect(EN1995_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());const expected=ownedFixture(),database=await en1995SnapshotToSqliteDatabase(expected);expect(await en1995SnapshotFromSqliteDatabase(database)).toEqual(expected);
 const db=Database.deserialize(await exportSqliteDatabase(database));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query("SELECT m.label_de,a.kind,a.ordinal,a.q_line_n_per_m FROM en1995_member m JOIN en1995_member_action a ON a.member_id=m.id WHERE m.id=1 ORDER BY a.ordinal").all()).toEqual([{label_de:fixture.members[0]!.labelDe,kind:fixture.members[0]!.actions[0]!.kind,ordinal:0,q_line_n_per_m:2500.5},{label_de:fixture.members[0]!.labelDe,kind:"",ordinal:1,q_line_n_per_m:-2500.5}]);expect(db.query("SELECT c.fastener_type,a.f_k_n FROM en1995_connection c JOIN en1995_connection_action a ON a.connection_id=c.id WHERE c.id=1 ORDER BY a.ordinal").all()).toEqual([{fastener_type:fixture.connections[0]!.fastenerType,f_k_n:42000.25},{fastener_type:fixture.connections[0]!.fastenerType,f_k_n:-42000.25}]);
  db.run("UPDATE en1995_member_action SET q_line_n_per_m=42.5,q_line_n_per_m_ieee754_bits=?,q_line_n_per_m_ieee754_class='finite' WHERE id=1",[BigInt.asIntN(64,nativeWord(42.5))]);db.run("UPDATE en1995_connection SET label_de='Geändert 世界',rows=4294967293,service_class=254 WHERE id=1");db.run("UPDATE en1995_document SET annex='En'");expected.members[0]!.actions[0]!.qLineNPerM={bits:nativeWord(42.5)};expected.connections[0]!.labelDe="Geändert 世界";expected.connections[0]!.rows=4294967293;expected.connections[0]!.serviceClass=254;expected.annex="En";expect(await en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).toEqual(expected)}finally{db.close()}
});
for(const text of words.ieee754Binary64Bits)test(`EN1995 all thirty-seven numeric domains retain word ${text}`,async()=>{
 const expected=ownedFixture(),v={bits:BigInt(text)};setEveryWord(expected,v);const db=Database.deserialize(await exportSqliteDatabase(await en1995SnapshotToSqliteDatabase(expected)),{safeIntegers:true});try{const b=Buffer.alloc(8);b.writeBigUInt64BE(v.bits);const scalar=b.readDoubleBE(),r=db.query("SELECT b_m,b_m_ieee754_bits FROM en1995_member WHERE id=1").get()as{b_m:number|null;b_m_ieee754_bits:bigint};expect(BigInt.asUintN(64,r.b_m_ieee754_bits)).toBe(v.bits);expect(r.b_m).toBe(Number.isNaN(scalar)?null:scalar);expect(await en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).toEqual(expected)}finally{db.close()}
});
for(const value of choices.annex)test(`EN1995 retains owned annex ${value}`,async()=>{const expected={...ownedFixture(),annex:value}as En1995SqliteSnapshot;expect(await en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(await exportSqliteDatabase(await en1995SnapshotToSqliteDatabase(expected))))).toEqual(expected)});
for(const field of["role","support"]as const)for(const value of choices[field])test(`EN1995 retains owned ${field} ${value}`,async()=>{const expected=ownedFixture();expected.members[0]={...expected.members[0]!,[field]:value}as En1995SqliteMember;expect(await en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(await exportSqliteDatabase(await en1995SnapshotToSqliteDatabase(expected))))).toEqual(expected)});
test("EN1995 empty member and connection collections retain every independently queryable table",async()=>{const expected={...ownedFixture(),members:[],connections:[]},database=await en1995SnapshotToSqliteDatabase(expected);expect(database.tables.length).toBe(5);expect(await en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(await exportSqliteDatabase(database)))).toEqual(expected)});
test("EN1995 rejects malformed choices booleans unsigned widths ordinals parent identities and words",async()=>{
 const database=await en1995SnapshotToSqliteDatabase(ownedFixture());for(const sql of["UPDATE en1995_document SET annex='unknown'","UPDATE en1995_member SET service_class=256 WHERE id=1","UPDATE en1995_member SET role='unknown' WHERE id=1","UPDATE en1995_member SET support='unknown' WHERE id=1","UPDATE en1995_member SET document_id=99 WHERE id=1","UPDATE en1995_member SET ordinal=0 WHERE id=2","UPDATE en1995_member_action SET member_id=99 WHERE id=1","UPDATE en1995_member_action SET ordinal=99 WHERE id=1","UPDATE en1995_connection SET service_class=-1 WHERE id=1","UPDATE en1995_connection SET number=4294967296 WHERE id=1","UPDATE en1995_connection SET rows=-1 WHERE id=1","UPDATE en1995_connection SET shear_planes=4294967296 WHERE id=1","UPDATE en1995_connection SET steel_plate=2 WHERE id=1","UPDATE en1995_connection SET document_id=99 WHERE id=1","UPDATE en1995_connection SET ordinal=0 WHERE id=2","UPDATE en1995_connection_action SET connection_id=99 WHERE id=1","UPDATE en1995_connection_action SET ordinal=99 WHERE id=1","UPDATE en1995_member SET b_m_ieee754_class='nan' WHERE id=1","DELETE FROM en1995_document"]){const db=Database.deserialize(await exportSqliteDatabase(database));try{db.run("PRAGMA ignore_check_constraints=ON");db.run(sql);await expect(en1995SnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow()}finally{db.close()}}
 await expect(en1995SnapshotToSqliteDatabase(ownedFixture(),{maxRows:1})).rejects.toThrow();await expect(en1995SnapshotFromSqliteDatabase(database,{maxValueBytes:0})).rejects.toThrow();
});
test("EN1995 initial and nested operations support cancellation and exact owned value admission",async()=>{
 const expected=ownedFixture(),initial=new AbortController();initial.abort();await expect(en1995SnapshotToSqliteDatabase(expected,{signal:initial.signal})).rejects.toHaveProperty("kind","canceled");const database=await en1995SnapshotToSqliteDatabase(expected);await expect(en1995SnapshotFromSqliteDatabase(database,{signal:initial.signal})).rejects.toHaveProperty("kind","canceled");expected.members[0]!.actions=Array.from({length:controls.entityCount},()=>({...expected.members[0]!.actions[0]!}));const large=await en1995SnapshotToSqliteDatabase(expected);
 for(const phase of["projectSnapshot","reconstructSnapshot"]as const){const c=new AbortController();let reached=false;const options={signal:c.signal,onProgress:(event:{phase:string;completed:number})=>{if(event.phase===phase&&event.completed>=controls.cancelAt){reached=true;c.abort()}}};await expect(phase==="projectSnapshot"?en1995SnapshotToSqliteDatabase(expected,options):en1995SnapshotFromSqliteDatabase(large,options)).rejects.toHaveProperty("kind","canceled");expect(reached).toBe(true)}
 expected.members[0]!.labelDe="x".repeat(controls.largeTextBytes);await expect(en1995SnapshotToSqliteDatabase(expected,{maxValueBytes:controls.largeTextBytes-1})).rejects.toThrow();const c=new AbortController();let reached=false;await expect(en1995SnapshotToSqliteDatabase(expected,{signal:c.signal,onProgress:event=>{if(event.phase==="projectSnapshot"&&event.completed>0&&event.total===0){reached=true;c.abort()}}})).rejects.toHaveProperty("kind","canceled");expect(reached).toBe(true);
});

import NormSemanticAjv from "ajv/dist/2020.js";
import normSemanticContract from "../🧫️fixtures/🎛️semantic.json";

import {en1995SnapshotToSqliteDatabase as normSemanticProject,en1995SnapshotFromSqliteDatabase as normSemanticRestore} from "../🟦️.ts";
import {exportSqliteDatabase as normSemanticExport,importSqliteDatabase as normSemanticImport} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import {independentSqliteExtent as normIndependentExtent} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts";
test("EN1995 complete independent cells preserve copied limits and required empty metadata",async()=>{
 expect(normSemanticContract["schemaBytes"]).toEqual(5814);expect(normSemanticContract["tableWidths"]).toEqual({"en1995_connection":37,"en1995_connection_action":9,"en1995_document":2,"en1995_member":73,"en1995_member_action":28});expect(normSemanticContract["cases"]).toEqual([{"id":"full","rows":9,"valueBytes":2293},{"id":"emptyCollections","rows":1,"valueBytes":10}]);
 for(const item of normSemanticContract.cases){const source=ownedFixture();if(item.id==="emptyCollections"){source.members=[];source.connections=[];}const database=await normSemanticProject(source),bytes=await normSemanticExport(database);expect(normIndependentExtent(bytes)).toEqual({rows:item.rows,valueBytes:item.valueBytes,schemaBytes:normSemanticContract.schemaBytes,tableWidths:normSemanticContract.tableWidths});const limits={maxRows:item.rows,maxValueBytes:item.valueBytes,maxSchemaBytes:normSemanticContract.schemaBytes,maxTables:5,maxColumns:73};expect(await normSemanticProject(source,limits)).toEqual(database);expect(await normSemanticRestore(await normSemanticImport(bytes),limits)).toEqual(source);
  for(const short of[{...limits,maxRows:item.rows-1},{...limits,maxValueBytes:item.valueBytes-1},{...limits,maxSchemaBytes:limits.maxSchemaBytes-1},{...limits,maxTables:4},{...limits,maxColumns:72}]){await expect(normSemanticProject(source,short)).rejects.toThrow();await expect(normSemanticRestore(database,short)).rejects.toThrow();}
 }console.log("[DEBUG] EN1995 complete independent SQLite cells and metadata preserve full and empty semantic limits");
});
