schema:
  interface:
    entity: &entity
      fields:
        id: string
        hash: string
        owner: *entity
        owns: [*entity]
    weakEntity: &weakEntity
      contraints:
        - &hashAsId
          description: "id is hash of entity"
    strongEntity: &strongEntity
      contraints:
        - &uuidv7AsId
          description: "id is uuidv7 at creation time"

    name: string
class: &class
  point: &point
    is:
    fields:
      x: number
      y: number
      z: number
  vector: &vector
    fields:
      x: number
      y: number
      z: number
