/** 🧪️ Persisted Procedure identity and two independent child handles inspected with SQLite. */
import{test,expect}from"bun:test";
import{Database}from"bun:sqlite";
import{procedureSnapshotToSqliteDatabase,procedureSnapshotFromSqliteDatabase,PROCEDURE_SQLITE_SCHEMA}from"../🟦️.ts";
import{exportSqliteDatabase,importSqliteDatabase}from"../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import corpus from"../🧫️fixtures/🔣️.json";
test("Procedure independent three-table producer preserves every exact child target field",async()=>{const d=await procedureSnapshotToSqliteDatabase(corpus.snapshot),oracle=new Database(":memory:");try{oracle.exec("PRAGMA application_id=1397576526;PRAGMA user_version=1");oracle.exec(PROCEDURE_SQLITE_SCHEMA);for(const table of d.tables)for(const row of table.rows)oracle.query(`INSERT INTO ${table.name} VALUES(${row.values.map(()=>"?").join(",")})`).run(...row.values);expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(oracle.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(await procedureSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(corpus.snapshot);oracle.query("UPDATE procedure_document SET schema_id=?").run(corpus.editedSchema);oracle.query("UPDATE procedure_text_child SET artifact_id=?").run(corpus.editedTarget);const back=await procedureSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()));expect(back.schema).toBe(corpus.editedSchema);expect(back.text.target.artifactId).toBe(corpus.editedTarget);expect(back.text.childId).toBe(corpus.snapshot.text.childId);expect(back.flow).toEqual(corpus.snapshot.flow);}finally{oracle.close();}});
test("Procedure physical export refuses missing or malformed rows and host-local fields",async()=>{const d=await procedureSnapshotToSqliteDatabase(corpus.snapshot);for(const sql of["DELETE FROM procedure_text_child","UPDATE procedure_flow_child SET id=2","UPDATE procedure_document SET schema_id=x'00'","UPDATE procedure_text_child SET subset=x'00'","INSERT INTO procedure_document VALUES(2,'extra')"]){const native=Database.deserialize(await exportSqliteDatabase(d));try{native.exec(sql);await expect(procedureSnapshotFromSqliteDatabase(await importSqliteDatabase(native.serialize()))).rejects.toThrow();}finally{native.close();}}const bad={tables:d.tables.map((table,i)=>i===0?{...table,sql:table.sql.replace("schema_id TEXT NOT NULL","schema_id TEXT")}:table)};await expect(procedureSnapshotFromSqliteDatabase(bad)).rejects.toThrow();await expect(procedureSnapshotToSqliteDatabase({...corpus.snapshot,path:[]} as typeof corpus.snapshot)).rejects.toThrow();});
test("Procedure bounds and cancellation precede large owned child strings",async()=>{const huge={...corpus.snapshot,schema:"文".repeat(40000)};await expect(procedureSnapshotToSqliteDatabase(huge,{maxValueBytes:16})).rejects.toThrow("value limit");await expect(procedureSnapshotToSqliteDatabase(corpus.snapshot,{maxRows:2})).rejects.toThrow("row limit");const signal=new AbortController();await expect(procedureSnapshotToSqliteDatabase(huge,{signal:signal.signal,onProgress:p=>{if(p.completed>0)signal.abort();}})).rejects.toHaveProperty("kind","canceled");const d=await procedureSnapshotToSqliteDatabase(corpus.snapshot),stop=new AbortController();await expect(procedureSnapshotFromSqliteDatabase(d,{signal:stop.signal,onProgress:p=>{if(p.phase==="reconstructSnapshot")stop.abort();}})).rejects.toHaveProperty("kind","canceled");});

test("direct Procedure projection admits exactly its three domain rows",async()=>{const d=await procedureSnapshotToSqliteDatabase(corpus.snapshot,{maxRows:3});expect(d.tables.reduce((n,t)=>n+t.rows.length,0)).toBe(3);expect(await procedureSnapshotFromSqliteDatabase(d,{maxRows:3})).toEqual(corpus.snapshot);const independent=Database.deserialize(await exportSqliteDatabase(d,{maxRows:3}));try{expect(independent.query("SELECT count(*) AS n FROM procedure_document").get()).toEqual({n:1});}finally{independent.close();}});

/** 📏️ Demands every literal child field against SQLite's actual UTF8 storage. */
test("Procedure complete three-table cells have independent exact and one-short limits",async()=>{
 const edited=structuredClone(corpus.snapshot);edited.schema=corpus.editedSchema;edited.text.target.artifactId=corpus.editedTarget;
 for(const source of[corpus.snapshot,edited]){
  const database=await procedureSnapshotToSqliteDatabase(source),db=Database.deserialize(await exportSqliteDatabase(database),{safeIntegers:true});let bytes:number;
  try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);const tables=(db.query("SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name").all()as{name:string}[]).map(({name})=>{const columns=db.query('PRAGMA table_info('+name+')').all()as{name:string}[],expression=columns.map(({name})=>{const c='"'+name.replaceAll('"','""')+'"';return "CASE typeof("+c+") WHEN 'integer' THEN 8 WHEN 'real' THEN 8 WHEN 'text' THEN length(CAST("+c+" AS BLOB)) WHEN 'blob' THEN length("+c+") WHEN 'null' THEN 0 ELSE NULL END"}).join('+'),r=db.query('SELECT COUNT(*) AS rows,COALESCE(SUM('+expression+'),0) AS bytes FROM '+name).get()as{rows:bigint;bytes:bigint}|null;if(!r)throw Error("Independent SQLite aggregate row is absent");return{table:name,columns:columns.length,rows:Number(r.rows),semanticBytes:Number(r.bytes)}});
   expect(tables.map(t=>[t.table,t.columns])).toEqual(corpus.semanticCells.tableWidths);expect(tables.reduce((n,t)=>n+t.rows,0)).toBe(corpus.semanticCells.rows);bytes=tables.reduce((n,t)=>n+t.semanticBytes,0);
   const texts=[source.schema,...[source.flow,source.text].flatMap(c=>[c.childId,c.target.artifactId,c.target.dialect.artifactKind,c.target.dialect.standard,c.target.dialect.subset])];expect(bytes).toBe(24+texts.reduce((n,text)=>n+new TextEncoder().encode(text).length,0));
  }finally{db.close()}
  const exact={maxRows:3,maxValueBytes:bytes};expect(await procedureSnapshotToSqliteDatabase(source,exact)).toEqual(database);expect(await procedureSnapshotFromSqliteDatabase(database,exact)).toEqual(source);
  for(const short of[{maxRows:2,maxValueBytes:bytes},{maxRows:3,maxValueBytes:bytes-1}]){await expect(procedureSnapshotToSqliteDatabase(source,short)).rejects.toThrow();await expect(procedureSnapshotFromSqliteDatabase(database,short)).rejects.toThrow();}
 }
});
