use super::*;
use crate::value::observe_retirement_allocations as observe;

fn denied(grant:RetainedCloneGrant,copy_demand:usize)->Vec<RetainedCloneGrant>{
    [Some(RetainedCloneGrant {maximum_items:0,..grant}),copy_demand.checked_sub(1).map(|maximum_copy_bytes|RetainedCloneGrant {maximum_copy_bytes,..grant}),grant.maximum_capacity_bytes.checked_sub(1).map(|maximum_capacity_bytes|RetainedCloneGrant {maximum_capacity_bytes,..grant}),grant.maximum_release_bytes.checked_sub(1).map(|maximum_release_bytes|RetainedCloneGrant {maximum_release_bytes,..grant}),grant.maximum_depth.checked_sub(1).map(|maximum_depth|RetainedCloneGrant {maximum_depth,..grant}),(grant.maximum_release_bytes>8).then_some(RetainedCloneGrant {maximum_release_bytes:8,..grant})].into_iter().flatten().collect()
}

fn check_denied(result:Result<RetainedCloneStep,crate::ValueError>,heap:(usize,usize),grant:RetainedCloneGrant,admitted:RetainedCloneGrant){
    assert_eq!(heap,(0,0));match result{Ok(step)=>assert_eq!(step.progress(),Default::default()),Err(error)=>{assert!(grant.maximum_depth<admitted.maximum_depth);assert_eq!(error.kind,crate::ValueRefusalKind::DepthLimit);assert_eq!(error.retained_progress(),Default::default());}}
}

#[test]
fn original_scalar_clone_requires_original_authority(){
    let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();
    for encoded in law["values"].as_array().unwrap(){let value:u64=encoded.as_str().unwrap().parse().unwrap();for copy in law["copyGrants"].as_array().unwrap(){let copy=copy.as_u64().unwrap()as usize;for cancelled in [None,Some(0),Some(1)]{
        let demand=RetainedCloneSource::<u64>::owned_constructor_demand::<()>();let grant=RetainedCloneGrant {maximum_items:1,maximum_capacity_bytes:demand.capacity_bytes,maximum_depth:demand.depth,..Default::default()};let(result,heap)=observe(||RetainedCloneSource::admit_owned(value,(),grant));let(mut source,receipt)=result.map_err(|(error,_,_)|error).unwrap();assert_eq!(heap,(receipt.retained_capacity_bytes,receipt.released_bytes));let(mut born,mut freed)=heap;let original=source.borrow().get()as *const u64;
        let(mut cursor,heap)=observe(u64::retained_clone_cursor);assert_eq!(heap,(0,0));let normal=RetainedCloneGrant {maximum_items:1,maximum_copy_bytes:law["payloadBytes"].as_u64().unwrap()as usize,maximum_depth:law["depth"].as_u64().unwrap()as usize,..Default::default()};
        if cancelled!=Some(0){for denied in [RetainedCloneGrant {maximum_items:0,..normal},RetainedCloneGrant {maximum_copy_bytes:0,..normal},RetainedCloneGrant {maximum_copy_bytes:normal.maximum_copy_bytes-1,..normal},RetainedCloneGrant {maximum_depth:0,..normal}]{let leases=Arc::strong_count(source.borrow().lease);let(result,heap)=observe(||cursor.advance(source.borrow(),denied));assert_eq!(heap,(0,0));match result{Ok(step)=>assert_eq!(step.progress(),Default::default()),Err(error)=>{assert_eq!(denied.maximum_depth,0);assert_eq!(error.kind,crate::ValueRefusalKind::DepthLimit);assert_eq!(error.retained_progress(),Default::default());}}assert_eq!(Arc::strong_count(source.borrow().lease),leases,"[DEBUG] Original scalar denial cannot bind an unadmitted source lease");assert_eq!(source.borrow().get()as *const u64,original);assert!(cursor.value.is_none());}
            let(result,heap)=observe(||cursor.advance(source.borrow(),normal));let step=result.unwrap();assert!(matches!(step,RetainedCloneStep::Complete(_)));assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress {copied_items:1,copied_bytes:8,..Default::default()});if cancelled.is_none(){let(output,heap)=observe(||cursor.take());assert_eq!(heap,(0,0));assert_eq!(output,Some(value));}
        }
        assert_eq!(observe(||cursor.begin_close()).1,(0,0));let mut turns=0;while !cursor.terminal_is_empty(){let grant=RetainedCloneGrant {maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:cursor.next_close_capacity_byte_demand(copy).unwrap(),maximum_release_bytes:cursor.next_close_release_byte_demand().unwrap(),maximum_depth:cursor.next_close_depth_demand().unwrap()};for denied in denied(grant,cursor.next_close_copy_byte_demand().unwrap()){let(result,heap)=observe(||cursor.close_step(denied));check_denied(result,heap,denied,grant);}let(result,heap)=observe(||cursor.close_step(grant));let step=result.unwrap();assert!(step.progress().fits(grant));assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));born+=heap.0;freed+=heap.1;turns+=1;assert!(turns<10000);}
        assert_eq!(observe(||drop(cursor)).1,(0,0));while !source.terminal_is_empty(){let grant=RetainedCloneGrant {maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:source.next_close_capacity_byte_demand(copy).unwrap(),maximum_release_bytes:source.next_close_release_byte_demand().unwrap(),maximum_depth:source.next_close_depth_demand().unwrap()};for denied in denied(grant,source.next_close_copy_byte_demand().unwrap()){let(result,heap)=observe(||source.close_step(denied));check_denied(result,heap,denied,grant);}let(result,heap)=observe(||source.close_step(grant));let step=result.unwrap();assert!(step.progress().fits(grant));assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));born+=heap.0;freed+=heap.1;turns+=1;assert!(turns<10000);}assert_eq!(observe(||drop(source)).1,(0,0));assert_eq!(born,freed);println!("[DEBUG] Original scalar value={value} closeCopy={copy} cancel={cancelled:?} exactRoot=true deniedLeases=0 physical={born} terminalDrop=0");
    }}}
}
