type XlsxRemoval { id: String!, index: Int! }
type XlsxRelocation { id: String!, from: Int!, to: Int! }
type XlsxContentTypeEntryPatch { contentType: String }
type XlsxContentTypeRow { name: String!, contentType: String! }
type XlsxContentTypeEntryInsertion { index: Int!, row: XlsxContentTypeRow! }
type XlsxContentTypeEntryModification { id: String!, patch: XlsxContentTypeEntryPatch! }
type XlsxContentTypeEntriesDiff {
  removed: [XlsxRemoval!]
  inserted: [XlsxContentTypeEntryInsertion!]
  moved: [XlsxRelocation!]
  modified: [XlsxContentTypeEntryModification!]
}
type XlsxOpcContentTypesDiff { defaults: XlsxContentTypeEntriesDiff, overrides: XlsxContentTypeEntriesDiff }
type XlsxOpcPartDiff { contentType: String, bytes: [Int!] }
type XlsxOpcPartInsertion { index: Int!, row: XlsxOpcPart! }
type XlsxOpcPartModification { id: String!, patch: XlsxOpcPartDiff! }
type XlsxOpcPartsDiff {
  removed: [XlsxRemoval!]
  inserted: [XlsxOpcPartInsertion!]
  moved: [XlsxRelocation!]
  modified: [XlsxOpcPartModification!]
}
type XlsxOpcRelationshipDiff { relType: String, target: String, targetMode: XlsxOpcTargetMode }
type XlsxOpcRelationshipInsertion { index: Int!, row: XlsxOpcRelationship! }
type XlsxOpcRelationshipModification { id: String!, patch: XlsxOpcRelationshipDiff! }
type XlsxOpcRelationshipListDiff {
  removed: [XlsxRemoval!]
  inserted: [XlsxOpcRelationshipInsertion!]
  moved: [XlsxRelocation!]
  modified: [XlsxOpcRelationshipModification!]
}
type XlsxOpcRelationshipOwnerPatch { relationships: XlsxOpcRelationshipListDiff! }
type XlsxOpcRelationshipOwnerInsertion { index: Int!, row: XlsxOpcRelationshipOwner! }
type XlsxOpcRelationshipOwnerModification { id: String!, patch: XlsxOpcRelationshipOwnerPatch! }
type XlsxOpcRelationshipsDiff {
  removed: [XlsxRemoval!]
  inserted: [XlsxOpcRelationshipOwnerInsertion!]
  moved: [XlsxRelocation!]
  modified: [XlsxOpcRelationshipOwnerModification!]
}
type XlsxOpcDiff {
  comment: String
  contentTypes: XlsxOpcContentTypesDiff
  parts: XlsxOpcPartsDiff
  relationships: XlsxOpcRelationshipsDiff
}
scalar XlsxXmlDocumentDiff
type XlsxXmlPartDiff { contentType: String, document: XlsxXmlDocumentDiff }
type XlsxXmlPartInsertion { index: Int!, row: XlsxXmlPart! }
type XlsxXmlPartModification { id: String!, patch: XlsxXmlPartDiff! }
type XlsxXmlPartsDiff {
  removed: [XlsxRemoval!]
  inserted: [XlsxXmlPartInsertion!]
  moved: [XlsxRelocation!]
  modified: [XlsxXmlPartModification!]
}
type XlsxDiff {
  opc: XlsxOpcDiff @state(class: ARTIFACT)
  xmlParts: XlsxXmlPartsDiff @state(class: ARTIFACT)
}
