// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionArgControl } from "./ActionArgControl";

/**
 * @emoji 📝 Declares one argument of an action: its `id` (the JSON key sent in `ActionDescriptor.args`),
 * human `label`, input `control`, whether it is `required`, an optional `default` value, and an optional
 * `description`. An empty `ActionDefinition.args` (the common case) means a no-argument action.
 */
export type ActionArgDef = { id: string, label: string, control: ActionArgControl, required: boolean, default?: unknown, description?: string, };
