// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsMediaFormat } from "./OsMediaFormat";

/**
 * 🔌 How a `MediaType` is actually encoded once it crosses a process boundary — binary payloads reuse `OsMediaFormat`, structured payloads carry a schema id instead (see `MediaKindDescriptor::schema`).
 */
export type MediaWireFormat = { "kind": "binary", format: OsMediaFormat, } | { "kind": "document", schema: string, };
