import { createHash } from "node:crypto";
import { createRequire, builtinModules } from "node:module";
import { createReadStream, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { StringDecoder } from "node:string_decoder";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import assert from "node:assert/strict";

const ticket = dirname(import.meta.dir), root = resolve(ticket, "../../../../../../.."), output = join(ticket, "🗑️generated/framework-import-enforcement"), inputPath = join(output, "synthetic-neutral-enforcement-source-ready-3.json"), inputSource = readFileSync(inputPath, "utf8"), input = JSON.parse(inputSource), digest = (source: string) => createHash("sha256").update(source).digest("hex"), require = createRequire(join(root, "package.json"));
mkdirSync(output, { recursive: true });
if (process.argv[2] === "guard-final") {
 const path = join(output, "synthetic-neutral-enforcement-source-ready-6.json"), source = readFileSync(path, "utf8"), ready = JSON.parse(source), rows = [...ready.rows, ...ready.ownerRows], contexts = [...ready.context, ...ready.ownerContexts], guards = [...rows.map(row => ({ path: row.path, expected: row.before })), ...contexts.map(row => ({ path: row.path, expected: row.source }))].map(row => { const current = existsSync(join(root, row.path)) ? readFileSync(join(root, row.path), "utf8") : null; return { path: row.path, expectedHash: row.expected === null ? null : digest(row.expected), currentHash: current === null ? null : digest(current), exact: current === row.expected }; }); assert.equal(rows.length, 18); assert.equal(contexts.length, 22); assert.equal(guards.length, 40); const receipt = { at: new Date().toISOString(), sourceReady: { path, sha256: digest(source) }, guards, seedAdmission: ready.seedAdmission, native: "No Cargo/compiler invocation", sourceWrites: 0 }; writeFileSync(join(output, "synthetic-neutral-enforcement-current-guards-6.json"), JSON.stringify(receipt, null, 2)); assert.equal(guards.every(row => row.exact), true, "Fresh current source guard drift"); console.log("[DEBUG] final Ready6 fresh40 current guards exact; source/native writes0");
} else if (process.argv[2] === "inspect-laws") {
 const source = input.rows.find(row => row.path.includes("/🧪️tests/🧱️dependency-direction/")).authored, names = ["declared semantic roles satisfy", "authored owner exports agree", "authored schema type declarations accept", "policy construction rejects"]; for (const name of names) { const begin = source.indexOf(`test("${name}`), next = source.indexOf("\ntest(", begin + 1); console.log(source.slice(begin, next < 0 ? undefined : next)); }
} else if (process.argv[2] === "inspect") {
 const rowKeys = Object.fromEntries(["rows", "ownerRows", "context", "ownerContexts"].map(key => [key, input[key].map(row => ({ path: row.path, keys: Object.keys(row), phase: row.phase, beforeBytes: Buffer.byteLength(row.before ?? row.source ?? ""), authoredBytes: Buffer.byteLength(row.authored ?? ""), currentHash: existsSync(join(root, row.path)) ? digest(readFileSync(join(root, row.path), "utf8")) : null }))]));
 const fixtureRow = input.rows.find(row => row.path.includes("/🧫️fixtures/🧱️dependency-direction/")), fixture = JSON.parse(fixtureRow.authored), validationKeys = Object.fromEntries(Object.entries(input.validation).map(([key, value]) => [key, Array.isArray(value) ? { count: value.length, firstKeys: value.length && value[0] && typeof value[0] === "object" ? Object.keys(value[0]) : [] } : typeof value])), fixtureKeys = Object.fromEntries(Object.entries(fixture).map(([key, value]) => [key, Array.isArray(value) ? { count: value.length, first: value[0] } : value]));
 writeFileSync(join(output, "synthetic-rebase-inspection-4.json"), JSON.stringify({ rowKeys, fixtureKeys, validationKeys, inputKeys: Object.keys(input) }, null, 2));
 console.log(JSON.stringify({ rowKeys, fixtureKeys, validationKeys, inputKeys: Object.keys(input) }, null, 2));
} else if (process.argv[2] === "rebase" || process.argv[2] === "compact") {
 const { createPatch, applyPatch } = await import("diff"), { parse, modify, applyEdits, parseTree, findNodeAtLocation } = require("jsonc-parser"), allPrevious = [...input.rows, ...input.ownerRows], seedPath = ".vscode/🧩️launch.seed.jsonc", pairs: any[] = [], captured = (path: string) => existsSync(join(root, path)) ? readFileSync(join(root, path), "utf8") : null;
 assert.equal(allPrevious.length, 18); assert.equal(new Set(allPrevious.map(row => row.path)).size, 18);
 const mutations = allPrevious.map(row => {
  const before = captured(row.path); let authored = row.authored, gui: any = null;
  if (row.path === seedPath) {
   const old = parse(row.before), proposed = parse(row.authored), current = parse(before), oldCommand = "bun nx run @semio-tech/repo-lib:lint-framework-module-product-direction", newCommand = "bun nx run @semio-tech/repo-lib:lint-framework-neutral-product-direction", oldIndex = old.configurations.findIndex(row => row.command === oldCommand), newGate = proposed.configurations.find(row => row.command === newCommand), currentIndex = current.configurations.findIndex(row => row.command === oldCommand), additions = proposed.configurations.filter(row => !old.configurations.some(old => old.name === row.name) && row.command !== newCommand);
   assert.ok(oldIndex >= 0 && currentIndex >= 0); assert.equal(additions.length, 2); assert.deepEqual(current.configurations[currentIndex], old.configurations[oldIndex]); assert.ok(current.configurations.length >= old.configurations.length + 3);
   authored = before; for (const field of ["name", "command"]) authored = applyEdits(authored, modify(authored, ["configurations", currentIndex, field], newGate[field], { formattingOptions: { insertSpaces: true, tabSize: 2 } }));
   for (const addition of additions) { assert.equal(current.configurations.some(row => row.name === addition.name), false); authored = applyEdits(authored, modify(authored, ["configurations", current.configurations.length], addition, { isArrayInsertion: true, formattingOptions: { insertSpaces: true, tabSize: 2 } })); current.configurations.push(addition); }
   const baseline = parse(before), next = parse(authored), oldNodes = findNodeAtLocation(parseTree(before), ["configurations"]).children, nextNodes = findNodeAtLocation(parseTree(authored), ["configurations"]).children, unchangedRaw = oldNodes.every((node, index) => index === currentIndex || before.slice(node.offset, node.offset + node.length) === authored.slice(nextNodes[index].offset, nextNodes[index].offset + nextNodes[index].length)), expectedRenamed = structuredClone(baseline.configurations[currentIndex]); expectedRenamed.name = newGate.name; expectedRenamed.command = newGate.command;
   assert.deepEqual(next.configurations[currentIndex], expectedRenamed); assert.equal(unchangedRaw, true); assert.equal(next.configurations.length, baseline.configurations.length + 2); assert.deepEqual(next.configurations.slice(baseline.configurations.length), additions);
   const foreign = baseline.configurations.filter(row => !old.configurations.some(old => old.name === row.name)); assert.ok(foreign.length >= 3); for (const entry of foreign) assert.deepEqual(next.configurations.find(row => row.name === entry.name), entry);
   gui = { previousCount: old.configurations.length, beforeCount: baseline.configurations.length, authoredCount: next.configurations.length, renamedIndex: currentIndex, unchangedRaw, foreign, additions, exactRenamed: expectedRenamed };
  } else if (before !== row.before) {
   assert.ok(before !== null && row.before !== null, `Changed owner presence requires separate admission ${row.path}`); const patch = createPatch(row.path, row.before, row.authored); authored = applyPatch(before, patch); assert.notEqual(authored, false, `Foreign rebase conflict ${row.path}`); assert.equal(applyPatch(authored, createPatch(row.path, row.authored, row.before)), before, `Foreign inverse conflict ${row.path}`);
  }
  assert.equal(typeof authored, "string"); const result = { ...row, before, beforeHash: before === null ? null : digest(before), authored, authoredHash: digest(authored), inverse: before, forward: createPatch(row.path, before ?? "", authored), inverseEdit: createPatch(row.path, authored, before ?? ""), previousBefore: row.before, previousAuthored: row.authored, previousInverse: row.inverse, observedForeign: before !== row.before, attribution: before === row.before ? "unchanged prior authority" : "observed current successor; authorship unassigned", gui }; pairs.push(result); return result;
 });
 const contexts = [...input.context, ...input.ownerContexts].map(row => { const current = captured(row.path); assert.equal(typeof current, "string"); return { ...row, source: current, sha256: digest(current), hash: digest(current), before: current, current, authored: current, inverse: current, previousSource: row.source, previousHash: digest(row.source), observedForeign: current !== row.source, attribution: current === row.source ? "unchanged prior context" : "observed current successor; authorship unassigned" }; }); assert.equal(contexts.length, 22);
 const compact = process.argv[2] === "compact", preserved = compact ? { phaseOrder: input.phaseOrder, validationFromReady3: input.validation, jackCasesExact: input.jackCasesExact, remaining: input.remaining } : { ...input, precedingSourceReadySource: inputSource, fullObservedPairs: pairs }, successor: any = { ...preserved, at: new Date().toISOString(), rows: mutations.slice(0, input.rows.length), ownerRows: mutations.slice(input.rows.length), context: contexts.slice(0, input.context.length), ownerContexts: contexts.slice(input.context.length), seedAdmission: mutations.find(row => row.path === seedPath).gui, mounted: false, registeredRuntime: "pending Root test-first publication after native fence", native: "No Cargo/compiler invocation from this lane", guards: mutations.map(row => ({ path: row.path, beforeHash: row.beforeHash, matches: captured(row.path) === row.before })), contextGuards: contexts.map(row => ({ path: row.path, capturedHash: row.sha256, matches: captured(row.path) === row.source })), rebase: { input: inputPath, mutationCount: 18, contextCount: 22, foreignMutations: mutations.filter(row => row.observedForeign).map(row => row.path), foreignContexts: contexts.filter(row => row.observedForeign).map(row => row.path), sourceWrites: 0 } };
 assert.equal(successor.guards.every(row => row.matches), true); assert.equal(successor.contextGuards.every(row => row.matches), true);
 if (compact) {
  for (const row of mutations) { row.priorAuthorityReference = { path: inputPath, sha256: digest(inputSource), ownerPath: row.path }; if (!row.observedForeign) { delete row.previousBefore; delete row.previousAuthored; delete row.previousInverse; } } for (const row of contexts) { row.priorAuthorityReference = { path: inputPath, sha256: digest(inputSource), ownerPath: row.path }; delete row.before; delete row.current; delete row.authored; if (!row.observedForeign) delete row.previousSource; }
  const test = successor.rows.find(row => row.path.includes("/🧪️tests/🧱️dependency-direction/")), fixtureRow = successor.rows.find(row => row.path.includes("/🧫️fixtures/🧱️dependency-direction/")), fixture = JSON.parse(fixtureRow.authored), pseudo = fixture.publicExportCases.find(row => row.id === "synthetic-pseudo-package"), replacements = [["config.forbidden.some(rule=>rule.from.path.some", "rules.some(rule=>rule.from.path.some"], ['join(root,String(index)+".d.ts")', 'join(root,"declaration-"+String(index)+".d.ts")']]; assert.equal(pseudo.accept, false); pseudo.specifier = "@semio-tech/synthetic-pseudo"; for (const [before, after] of replacements) { assert.equal(test.authored.split(before).length, 2); test.authored = test.authored.replace(before, after); } fixtureRow.authored = JSON.stringify(fixture, null, 2) + "\n"; for (const row of [test, fixtureRow]) { row.authoredHash = digest(row.authored); row.forward = createPatch(row.path, row.before ?? "", row.authored); row.inverseEdit = createPatch(row.path, row.authored, row.before ?? ""); }
  const names = ["synthetic-neutral-enforcement-source-ready-3.json", "synthetic-neutral-enforcement-source-ready-4.json", "synthetic-neutral-enforcement-source-ready-5.json", "synthetic-neutral-enforcement-successor-proof-4.json", "synthetic-neutral-enforcement-successor-proof-5.json"], history: any[] = []; for (const name of names) { const path = join(output, name), state = createHash("sha256"); let bytes = 0; for await (const chunk of createReadStream(path)) { state.update(chunk); bytes += chunk.length; } history.push({ path, bytes, sha256: state.digest("hex"), retained: true }); } successor.sourceRootHistory = history; successor.lawCorrection = { replacements, pseudo: { specifier: pseudo.specifier, accept: false }, producerBodiesUnchanged: true };
  const decoder = new StringDecoder("utf8"), wanted = new Set(["construction", "hosted", "callbackRoster", "strictDiagnostics", "virtualRequires", "gui", "registered", "native", "sourceWrites"]), sections: string[] = []; let line = "", truncated = false, active: string[] | null = null; const consume = (value: string) => { const header = value.match(/^  "([^"]+)":/); if (header || value === "}") { if (active) { sections.push(active.join("\n").replace(/,\s*$/, "")); active = null; } if (header && wanted.has(header[1])) active = [value]; } else if (active) active.push(value); }; for await (const chunk of createReadStream(join(output, "synthetic-neutral-enforcement-successor-proof-5.json"))) { const text = decoder.write(chunk); let begin = 0, end = text.indexOf("\n"); while (end >= 0) { const part = text.slice(begin, end); if (!truncated) line += part; consume(line); line = ""; truncated = false; begin = end + 1; end = text.indexOf("\n", begin); } if (!truncated) { line += text.slice(begin); if (!active && line.length > 4096) { line = line.slice(0, 256); truncated = true; } } } if (active) sections.push(active.join("\n").replace(/,\s*$/, "")); const observations = JSON.parse("{" + sections.join(",") + "}"); assert.equal(observations.hosted.length, 13); assert.equal(observations.hosted.every(row => row.passed), true); assert.equal(observations.construction.length, 7); assert.equal(observations.strictDiagnostics.length, 0);
  const { parseTree, findNodeAtLocation } = require("jsonc-parser"), seed = mutations.find(row => row.path === seedPath), oldNodes = findNodeAtLocation(parseTree(seed.before), ["configurations"]).children, nextNodes = findNodeAtLocation(parseTree(seed.authored), ["configurations"]).children, headerExact = seed.before.slice(0, oldNodes[0].offset) === seed.authored.slice(0, nextNodes[0].offset), footerExact = seed.before.slice(oldNodes.at(-1).offset + oldNodes.at(-1).length) === seed.authored.slice(nextNodes.at(-1).offset + nextNodes.at(-1).length); assert.equal(headerExact, true); assert.equal(footerExact, true); assert.equal(fixture.cases.length, 80); assert.deepEqual(fixture.cases, JSON.parse(input.rows.find(row => row.path === fixtureRow.path).authored).cases);
  const unchangedProducers = mutations.filter(row => row.phase === "production").map(row => { assert.equal(row.authored, allPrevious.find(previous => previous.path === row.path).authored); return { path: row.path, authoredHash: row.authoredHash }; }); assert.equal(unchangedProducers.length, 4); for (const row of successor.ownerRows) assert.equal(row.authored, input.ownerRows.find(previous => previous.path === row.path).authored); const readyPath = join(output, "synthetic-neutral-enforcement-source-ready-6.json"), readySource = JSON.stringify(successor, null, 2); writeFileSync(readyPath, readySource); writeFileSync(join(output, "synthetic-neutral-enforcement-final-admission-6.json"), JSON.stringify({ sourceReady: { path: readyPath, sha256: digest(readySource) }, observations, sourceRootHistory: history, guards: [...successor.guards, ...successor.contextGuards], headerExact, footerExact, unchangedProducers, ownerSixUnchanged: true, original80Exact: true, mounted: false, sourceWrites: 0 }, null, 2)); console.log("[DEBUG] compact successor6 full18/22, all40 current exact; hosted13/constructor7/strict0 carried with streamed immutable proof hash; raw GUI header/footer exact; production4/owner6/original80 unchanged");
 } else { writeFileSync(join(output, "synthetic-neutral-enforcement-source-ready-4.json"), JSON.stringify(successor, null, 2)); console.log(`[DEBUG] synthetic successor4 guarded18/22; foreign mutations${successor.rebase.foreignMutations.length}/contexts${successor.rebase.foreignContexts.length}; GUI${successor.seedAdmission.beforeCount}→${successor.seedAdmission.authoredCount}; no source publication`); }
} else if (process.argv[2] === "admit") {
 const successorSource = readFileSync(join(output, "synthetic-neutral-enforcement-source-ready-5.json"), "utf8"), successor = JSON.parse(successorSource), rows = [...successor.rows, ...successor.ownerRows], proofSource = readFileSync(join(output, "synthetic-neutral-enforcement-successor-proof-5.json"), "utf8"), proof = JSON.parse(proofSource), { parse, parseTree, findNodeAtLocation } = require("jsonc-parser"), seed = rows.find(row => row.path === ".vscode/🧩️launch.seed.jsonc"), before = parse(seed.before), after = parse(seed.authored), oldNodes = findNodeAtLocation(parseTree(seed.before), ["configurations"]).children, newNodes = findNodeAtLocation(parseTree(seed.authored), ["configurations"]).children, headerExact = seed.before.slice(0, oldNodes[0].offset) === seed.authored.slice(0, newNodes[0].offset), footerExact = seed.before.slice(oldNodes.at(-1).offset + oldNodes.at(-1).length) === seed.authored.slice(newNodes.at(-1).offset + newNodes.at(-1).length);
 assert.equal(headerExact, true); assert.equal(footerExact, true); assert.equal(before.configurations.length, 1179); assert.equal(after.configurations.length, 1181); const constructorAndTaxonomy = rows.filter(row => row.phase === "production").map(row => { const previous = [...input.rows, ...input.ownerRows].find(old => old.path === row.path); assert.equal(row.authored, previous.authored); return { path: row.path, authoredHash: row.authoredHash, unchanged: true }; }); assert.equal(constructorAndTaxonomy.length, 4);
 for (const row of successor.ownerRows) assert.equal(row.authored, input.ownerRows.find(old => old.path === row.path).authored); const fixture = JSON.parse(rows.find(row => row.path.includes("/🧫️fixtures/🧱️dependency-direction/")).authored), previousFixture = JSON.parse(input.rows.find(row => row.path.includes("/🧫️fixtures/🧱️dependency-direction/")).authored); assert.equal(fixture.cases.length, 80); assert.deepEqual(fixture.cases, previousFixture.cases); assert.equal(proof.hosted.length, 13); assert.equal(proof.hosted.every(row => row.passed), true); assert.equal(proof.construction.length, 7); assert.equal(proof.strictDiagnostics.length, 0);
 const guards = [...rows.map(row => ({ path: row.path, expected: row.before })), ...[...successor.context, ...successor.ownerContexts].map(row => ({ path: row.path, expected: row.source }))].map(row => { const current = existsSync(join(root, row.path)) ? readFileSync(join(root, row.path), "utf8") : null; return { path: row.path, before: row.expected, current, inverse: current, exact: current === row.expected }; }); assert.equal(guards.length, 40); assert.equal(guards.every(row => row.exact), true); writeFileSync(join(output, "synthetic-neutral-enforcement-final-admission-5.json"), JSON.stringify({ successorSource, proofSource, headerExact, footerExact, constructorAndTaxonomy, ownerRowsUnchanged: true, original80Exact: true, guards, native: "No compiler/Cargo invocation", sourceWrites: 0 }, null, 2)); console.log("[DEBUG] synthetic final40 guards exact, raw GUI header/footer exact, original80 exact, production4 +owner6 unchanged; prior hosted13 and constructor7 GREEN");
} else if (process.argv[2] === "correct") {
 const { createPatch } = await import("diff"), previousSource = readFileSync(join(output, "synthetic-neutral-enforcement-source-ready-4.json"), "utf8"), successor = JSON.parse(previousSource), test = successor.rows.find(row => row.path.includes("/🧪️tests/🧱️dependency-direction/")), fixtureRow = successor.rows.find(row => row.path.includes("/🧫️fixtures/🧱️dependency-direction/")), fixture = JSON.parse(fixtureRow.authored), pseudo = fixture.publicExportCases.find(row => row.id === "synthetic-pseudo-package"); assert.ok(pseudo); assert.equal(pseudo.accept, false); assert.equal(pseudo.specifier.startsWith("@semio-test/"), true); const previousSpecifier = pseudo.specifier; pseudo.specifier = "@semio-tech/synthetic-pseudo";
 const replacements = [["config.forbidden.some(rule=>rule.from.path.some", "rules.some(rule=>rule.from.path.some"], ['join(root,String(index)+".d.ts")', 'join(root,"declaration-"+String(index)+".d.ts")']]; const beforeTest = test.authored; for (const [before, after] of replacements) { assert.equal(test.authored.split(before).length, 2); test.authored = test.authored.replace(before, after); }
 for (const row of [test, fixtureRow]) { if (row === fixtureRow) row.authored = JSON.stringify(fixture, null, 2) + "\n"; row.authoredHash = digest(row.authored); row.forward = createPatch(row.path, row.before ?? "", row.authored); row.inverseEdit = createPatch(row.path, row.authored, row.before ?? ""); }
 successor.at = new Date().toISOString(); successor.precedingRebaseSource = previousSource; successor.hostedRedSource = readFileSync(join(output, "synthetic-neutral-enforcement-successor-proof-4.json"), "utf8"); successor.lawCorrection = { testBefore: beforeTest, testAuthored: test.authored, inverse: beforeTest, replacements, pseudo: { previousSpecifier, authoredSpecifier: pseudo.specifier, accept: false }, sourceWrites: 0 }; successor.fullObservedPairs = [...successor.rows, ...successor.ownerRows]; writeFileSync(join(output, "synthetic-neutral-enforcement-source-ready-5.json"), JSON.stringify(successor, null, 2)); console.log("[DEBUG] synthetic successor5 retains18/22, corrects two authored law defects and explicit first-party pseudo namespace; production bodies unchanged");
} else if (process.argv[2] === "validate") {
 const epoch = process.argv[3] ?? "4", successorPath = join(output, `synthetic-neutral-enforcement-source-ready-${epoch}.json`), successorSource = readFileSync(successorPath, "utf8"), successor = JSON.parse(successorSource), rows = [...successor.rows, ...successor.ownerRows], { default: ts } = await import("typescript"), { default: Ajv } = await import("ajv/dist/2020.js"), overlay = new Map(rows.map(row => [resolve(root, row.path), row.authored])), library = "🧰️framework/🛍️products/🦑️repo/🔨️modules/📚️library", testPath = `${library}/🧪️tests/🧱️dependency-direction/🟦️.ts`, fixturePath = `${library}/🧫️fixtures/🧱️dependency-direction/🔣️.json`, schemaPath = `${library}/🧬️schema/🧱️dependency-direction/🔣️.json`, read = (path: string) => overlay.get(resolve(root, path)) as string ?? readFileSync(resolve(root, path), "utf8"), fixture = JSON.parse(read(fixturePath)), previousFixture = JSON.parse(input.rows.find(row => row.path === fixturePath).authored), schema = JSON.parse(read(schemaPath)), validate = new Ajv({ strict: true }).compile(schema);
 assert.equal(validate(fixture), true, JSON.stringify(validate.errors)); if (epoch === "5") { const expected = structuredClone(previousFixture); expected.publicExportCases.find(row => row.id === "synthetic-pseudo-package").specifier = "@semio-tech/synthetic-pseudo"; assert.deepEqual(fixture, expected); } else assert.deepEqual(fixture, previousFixture); assert.equal(input.validation.originalCases80Exact, true); const hostile = structuredClone(fixture); hostile.infrastructureCases[0].unexpected = true; assert.equal(validate(hostile), false);
 const options = { strict: true, noUncheckedIndexedAccess: true, noEmit: true, skipLibCheck: true, allowImportingTsExtensions: true, esModuleInterop: true, resolveJsonModule: true, target: ts.ScriptTarget.ESNext, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, types: ["bun"] }, host = ts.createCompilerHost(options), oldRead = host.readFile.bind(host), oldExists = host.fileExists.bind(host); host.readFile = path => overlay.get(resolve(path)) as string ?? oldRead(path); host.fileExists = path => overlay.has(resolve(path)) || oldExists(path);
 const program = ts.createProgram([resolve(root, testPath)], options, host), diagnostics = ts.getPreEmitDiagnostics(program).map(row => ({ code: row.code, path: row.file?.fileName, message: ts.flattenDiagnosticMessageText(row.messageText, "\n") })); writeFileSync(join(output, `synthetic-strict-successor-${epoch}.json`), JSON.stringify({ diagnostics, importedSources: program.getSourceFiles().filter(row => !row.isDeclarationFile).map(row => ({ path: row.fileName, hash: digest(row.text) })) }, null, 2)); assert.equal(diagnostics.length, 0, JSON.stringify(diagnostics));
 const constructorPath = `${library}/🕸️dependencies/🧭️direction/🏗️construction/🟨️.cjs`, module: any = { exports: {} }; new Function("module", "exports", "require", read(constructorPath))(module, module.exports, require); const construction = fixture.constructionCases.map(row => { let accepted = false, error: string | null = null; try { module.exports.buildDependencyDirectionPolicy({ taxonomy: JSON.parse(read(`${library}/🔣️taxonomy.json`)), plugins: [], workspacePackages: row.packages, nodeBuiltins: builtinModules }); accepted = true; } catch (failure) { error = String(failure); } assert.equal(accepted, row.accept, row.id); return { id: row.id, accepted, expected: row.accept, error }; }); assert.equal(construction.length, 7);
 const callbacks: any[] = [], cache = new Map<string, any>(), dependencyCruiser = await import("dependency-cruiser"), reads = new Map<string, any>(), nativeFs = require("node:fs"), nativeModule = require("node:module"), virtualRequires: any[] = [], runtime = join(output, `synthetic-hosted-successor-${epoch}-runtime`); process.env.SEMIO_TEST_ARTIFACT_DIR = runtime; mkdirSync(runtime, { recursive: true });
 const contained = (base: string, path: string) => { const child = relative(base, resolve(path)); return child !== "" && child !== ".." && !child.startsWith("../") && !child.startsWith("..\\") && !isAbsolute(child); }, ownedRead = (path: any, encoding: any) => { const resolved = resolve(path instanceof URL ? fileURLToPath(path) : path), value = overlay.get(resolved) ?? nativeFs.readFileSync(path, encoding); if (contained(root, resolved) && !contained(ticket, resolved) && !relative(root, resolved).split("\\").join("/").includes("node_modules/") && typeof value === "string") reads.set(resolved, { path: resolved, source: nativeFs.readFileSync(resolved, "utf8"), hash: digest(nativeFs.readFileSync(resolved, "utf8")) }); return value; }, protect = (path: any) => assert.equal(contained(ticket, path), true, `Hosted write outside ticket refused ${path}`), fs = { ...nativeFs, readFileSync: ownedRead, writeFileSync: (path: any, ...args: any[]) => { protect(path); return nativeFs.writeFileSync(path, ...args); }, mkdirSync: (path: any, ...args: any[]) => { protect(path); return nativeFs.mkdirSync(path, ...args); }, mkdtempSync: (path: any, ...args: any[]) => { protect(path); return nativeFs.mkdtempSync(path, ...args); }, rmSync: (path: any, ...args: any[]) => { protect(path); return nativeFs.rmSync(path, ...args); }, symlinkSync: (target: any, path: any, ...args: any[]) => { protect(path); return nativeFs.symlinkSync(target, path, ...args); } };
 const load = (path: string): any => { const resolved = resolve(path); if (cache.has(resolved)) return cache.get(resolved); if (resolved.endsWith(".json")) return JSON.parse(ownedRead(resolved, "utf8")); const exports: any = {}, module: any = { exports }, local = createRequire(resolved), text = overlay.get(resolved) as string ?? ownedRead(resolved, "utf8"), transformed = ts.transpileModule(text.replaceAll("import.meta.dir", JSON.stringify(dirname(resolved))).replaceAll("import.meta.url", JSON.stringify(pathToFileURL(resolved).href)), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText; cache.set(resolved, exports); const scopedModule = { ...nativeModule, createRequire: (path: any) => { const delegate = nativeModule.createRequire(path), wrapped = (name: string) => { const target = delegate.resolve(name); if (overlay.has(target)) { virtualRequires.push({ requester: String(path), target, authoredHash: digest(overlay.get(target) as string) }); return load(target); } return delegate(name); }; return Object.assign(wrapped, delegate); } }, importer = (name: string) => name === "bun:test" ? { expect: require(name).expect, test: (name: string, run: () => unknown) => callbacks.push({ name, run }) } : name === "node:fs" ? fs : name === "node:module" ? scopedModule : name === "dependency-cruiser" ? dependencyCruiser : name.startsWith(".") && /\.(ts|cjs|json)$/.test(name) ? load(resolve(dirname(resolved), name)) : local(name); new Function("require", "module", "exports", transformed)(importer, module, exports); cache.set(resolved, module.exports); return module.exports; };
 load(resolve(root, testPath)); const hosted: any[] = []; assert.equal(new Set(callbacks.map(row => row.name)).size, callbacks.length); for (const callback of callbacks) { try { await callback.run(); hosted.push({ name: callback.name, passed: true }); } catch (error) { hosted.push({ name: callback.name, passed: false, error: String(error) }); } console.log(`[DEBUG] staged synthetic callback ${callback.name}: ${hosted.at(-1).passed ? "PASS" : "FAIL"}`); }
 const guards = [...rows.map(row => ({ path: row.path, expected: row.before })), ...[...successor.context, ...successor.ownerContexts].map(row => ({ path: row.path, expected: row.source }))].map(row => { const current = existsSync(join(root, row.path)) ? readFileSync(join(root, row.path), "utf8") : null; return { path: row.path, before: row.expected, current, inverse: current, exact: current === row.expected }; }), proof = { successorSource, construction, hosted, callbackRoster: callbacks.map(row => row.name), strictDiagnostics: diagnostics, fullSourceGuards: guards, hostedSourceReads: [...reads.values()], virtualRequires, corpusExactExceptDeclaredPseudoIdentity: true, original80Retained: true, gui: successor.seedAdmission, mounted: false, registered: "not executed; complete exact hosted callbacks, roster explicit", native: "no compiler or Cargo invocation", sourceWrites: 0 }; writeFileSync(join(output, `synthetic-neutral-enforcement-successor-proof-${epoch}.json`), JSON.stringify(proof, null, 2)); assert.equal(hosted.every(row => row.passed), true, JSON.stringify(hosted)); assert.equal(guards.every(row => row.exact), true, "Current source guard drift"); console.log(`[DEBUG] synthetic strict0/constructor7/hosted${hosted.length} GREEN/original80 retained/current40 exact; source publication0/native0`);
} else throw Error("Expected inspect, rebase or validate");
