[package]
name = "note-program"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:note"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "note"
ports = { react = 6080, wgpu = 6180 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
semio-framework-os = { path = "../../../framework/product/os/core/rs" }
semio-framework-program = { path = "../../../framework/program/rs" }
vcs = { path = "../../../vcs/rs" }
store = { path = "../../../store/rs" }
protocol = { path = "../../../protocol/rs" }
dsl = { path = "../../../dsl/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

