//! 🎛️ Original timelines and variant fields retain their complete ordered reconstruction workspace.
use super::{SemioAnimationSnapshot,AnimTimeline,AnimChannel,AnimTarget,AnimTargetProperty,AnimInterpolation,AnimKeyframe,AnimValue,SemioPoint3,SemioQuaternion,identity,single_float_row,float_columns};
use store::{ArtifactSqliteSnapshot,sqlite_snapshot::{SqliteDatabase,SqliteSnapshotControl,SqliteSnapshotPhase,artifact::{RowIndex,RowIndexStorage,reconstruct_text_into},transfer::{SchemaValidationStorage,validate_database_into,validate_component_into,reserve}}};
use semio_framework_value::{ValueError,ValueRefusalKind};
#[derive(semio_framework_value::RetireOwned)]
struct Prefix{snapshot:Option<SemioAnimationSnapshot>,validation:SchemaValidationStorage,indexes:[RowIndexStorage;7],orders:[Vec<usize>;4]}
fn empty()->Prefix{Prefix{snapshot:Some(super::native_decoding::empty()),validation:SchemaValidationStorage::empty(),indexes:std::array::from_fn(|_|RowIndexStorage::empty()),orders:std::array::from_fn(|_|Vec::new())}}
fn invalid(message:&'static str)->ValueError{ValueError::literal(ValueRefusalKind::InvalidValue,message)}
pub(super)fn reconstruct(database:&SqliteDatabase,control:&mut SqliteSnapshotControl<'_>,declared:&str)->Result<SemioAnimationSnapshot,ValueError>{crate::standards::v1::subsets::base::io::sqlite::snapshot::native_decoding::workspace::reconstruct_projected(control,empty,|prefix,control|{
 let phase=SqliteSnapshotPhase::ReconstructSnapshot;control.check_database(database,phase)?;validate_database_into(&mut prefix.validation,database,declared,phase,control)?;validate_component_into(&mut prefix.validation,database,SemioAnimationSnapshot::SQLITE_SCHEMA,phase,control)?;let document=single_float_row(database,"semio_animation_document")?;identity(document,2)?;if document.rowid!=1{return Err(invalid("invalid Semio animation document identifier"))}
 let [timeline_index,channel_index,keyframe_index,weight_index,scalar_index,vector_index,quaternion_index]=&mut prefix.indexes;let [order,channel_order,keyframe_order,weight_order]=&mut prefix.orders;
 let timelines=RowIndex::new(timeline_index,database,"semio_animation_timeline",4,float_columns("semio_animation_timeline"),control,"invalid Semio animation timeline owner or identity")?;let channels=RowIndex::new(channel_index,database,"semio_animation_channel",7,float_columns("semio_animation_channel"),control,"invalid Semio animation relationship owner or identity")?;let keyframes=RowIndex::new(keyframe_index,database,"semio_animation_keyframe",5,float_columns("semio_animation_keyframe"),control,"invalid Semio animation relationship owner or identity")?;let mut weights=RowIndex::new(weight_index,database,"semio_animation_weight",4,float_columns("semio_animation_weight"),control,"invalid Semio animation relationship owner or identity")?;let mut scalars=RowIndex::new(scalar_index,database,"semio_animation_scalar",2,float_columns("semio_animation_scalar"),control,"duplicate Semio animation variant detail")?;let mut vectors=RowIndex::new(vector_index,database,"semio_animation_vector3",4,float_columns("semio_animation_vector3"),control,"duplicate Semio animation variant detail")?;let mut quaternions=RowIndex::new(quaternion_index,database,"semio_animation_quaternion",5,float_columns("semio_animation_quaternion"),control,"duplicate Semio animation variant detail")?;
 timelines.ordered_into(order,2,control,"Semio animation timeline ordinals must be contiguous")?;for(count,&index)in timelines.indices().iter().enumerate(){if timelines.row(index)?.integer(1)?!=1{return Err(invalid("invalid Semio animation timeline owner or identity"))}control.checkpoint(phase,count+1,timelines.len())?;}for(count,&index)in channels.indices().iter().enumerate(){if timelines.get(channels.row(index)?.integer(1)?,control)?.is_none(){return Err(invalid("invalid Semio animation relationship owner or identity"))}control.checkpoint(phase,count+1,channels.len())?;}for(count,&index)in keyframes.indices().iter().enumerate(){if channels.get(keyframes.row(index)?.integer(1)?,control)?.is_none(){return Err(invalid("invalid Semio animation relationship owner or identity"))}control.checkpoint(phase,count+1,keyframes.len())?;}for(count,&index)in weights.indices().iter().enumerate(){if keyframes.get(weights.row(index)?.integer(1)?,control)?.is_none(){return Err(invalid("invalid Semio animation relationship owner or identity"))}control.checkpoint(phase,count+1,weights.len())?;}
 channels.grouped_by_into(channel_order,2,control,"Semio animation relationship ordinals must be contiguous",|row|Ok((0,Some(row.integer(1)?))))?;keyframes.grouped_by_into(keyframe_order,2,control,"Semio animation relationship ordinals must be contiguous",|row|Ok((0,Some(row.integer(1)?))))?;weights.grouped_by_into(weight_order,2,control,"Semio animation relationship ordinals must be contiguous",|row|Ok((0,Some(row.integer(1)?))))?;let snapshot=prefix.snapshot.as_mut().unwrap();snapshot.timelines=reserve(order.len(),control)?;let mut completed=0;
 for &index in order.iter(){let row=timelines.row(index)?;let range=channels.range_by(channel_order,(0,Some(row.rowid)),control,|row|Ok((0,Some(row.integer(1)?))))?;snapshot.timelines.push(AnimTimeline{name:None,channels:Vec::new()});let timeline=snapshot.timelines.last_mut().unwrap();timeline.channels=reserve(range.len(),control)?;if let Some(word)=row.optional_text(3)?{timeline.name=Some(String::new());reconstruct_text_into(timeline.name.as_mut().unwrap(),control,word)?;}
  for position in range{let row=channels.row(channel_order[position])?;let custom=row.optional_text(5)?;let property=match row.text(4)?{"translation"=>AnimTargetProperty::Translation,"rotation"=>AnimTargetProperty::Rotation,"scale"=>AnimTargetProperty::Scale,"weights"=>AnimTargetProperty::Weights,"custom"=>{if custom.is_none(){return Err(invalid("missing custom animation property name"))}AnimTargetProperty::Custom{name:String::new()}},_=>return Err(invalid("unknown Semio animation target property"))};if row.text(4)?!="custom"&&custom.is_some(){return Err(invalid("unexpected custom animation property name"))}let interpolation=match row.text(6)?{"linear"=>AnimInterpolation::Linear,"step"=>AnimInterpolation::Step,"cubic_spline"=>AnimInterpolation::CubicSpline,_=>return Err(invalid("unknown Semio animation interpolation"))};let range=keyframes.range_by(keyframe_order,(0,Some(row.rowid)),control,|row|Ok((0,Some(row.integer(1)?))))?;timeline.channels.push(AnimChannel{target:AnimTarget{node:String::new(),property},interpolation,keyframes:Vec::new()});let channel=timeline.channels.last_mut().unwrap();channel.keyframes=reserve(range.len(),control)?;reconstruct_text_into(&mut channel.target.node,control,row.text(3)?)?;if let AnimTargetProperty::Custom{name}=&mut channel.target.property{reconstruct_text_into(name,control,custom.unwrap())?;}
   for position in range{let row=keyframes.row(keyframe_order[position])?;channel.keyframes.push(AnimKeyframe{t:row.real(3)?,value:AnimValue::Scalar{value:0.0}});let keyframe=channel.keyframes.last_mut().unwrap();match row.text(4)?{
    "scalar"=>{let detail=scalars.take(row.rowid,control)?.ok_or_else(||invalid("missing scalar animation value"))?;keyframe.value=AnimValue::Scalar{value:detail.real(1)?};},
    "vector3"=>{let detail=vectors.take(row.rowid,control)?.ok_or_else(||invalid("missing vector animation value"))?;keyframe.value=AnimValue::Vec3{value:SemioPoint3{x:detail.real(1)?,y:detail.real(2)?,z:detail.real(3)?}};},
    "quaternion"=>{let detail=quaternions.take(row.rowid,control)?.ok_or_else(||invalid("missing quaternion animation value"))?;keyframe.value=AnimValue::Quat{value:SemioQuaternion{x:detail.real(1)?,y:detail.real(2)?,z:detail.real(3)?,w:detail.real(4)?}};},
    "weights"=>{keyframe.value=AnimValue::Weights{values:Vec::new()};let range=weights.range_by(weight_order,(0,Some(row.rowid)),control,|row|Ok((0,Some(row.integer(1)?))))?;if let AnimValue::Weights{values}=&mut keyframe.value{*values=reserve(range.len(),control)?;for position in range{let detail=weights.take_index(weight_order[position],control)?.ok_or_else(||invalid("multiply owned Semio animation weight"))?;values.push(detail.real(3)?);completed+=1;control.checkpoint(phase,completed,0)?;}}},
    _=>return Err(invalid("unknown Semio animation keyframe value kind")),
   }completed+=1;control.checkpoint(phase,completed,0)?;}control.checkpoint(phase,completed,0)?;
  }control.checkpoint(phase,completed,0)?;
 }if scalars.remaining()!=0||vectors.remaining()!=0||quaternions.remaining()!=0||weights.remaining()!=0{return Err(invalid("orphan or contradictory Semio animation variant detail"))}reconstruct_text_into(&mut snapshot.schema,control,document.text(1)?)?;control.checkpoint(phase,completed,completed)
},|prefix|prefix.snapshot.take().unwrap())}
