[package]
name = "norm_en_1996"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
norm_core = { path = "../../../core/rs" }
serde = { version = "1.0.219", features = ["derive"] }
mathematical_algebra = { path = "../../../../s/kernel/mathematical/algebra/rs", package = "semio-s-kernel-mathematical-algebra" }
fem_core = { path = "../../../../fem/core/rs" }
norm_en_1990 = { path = "../../1990/rs" }
norm_en_1991 = { path = "../../1991/rs" }
vcs = { path = "../../../../s/kernel/vcs/rs", package = "semio-s-kernel-vcs" }
store = { path = "../../../../s/kernel/store/rs", package = "semio-s-kernel-store" }
dsl = { path = "../../../../s/kernel/dsl/rs", package = "semio-s-kernel-dsl" }
