import {Database as Sqlite} from 'bun:sqlite';
import assert from 'node:assert/strict';
const ticket=new URL('../../../',import.meta.url);const inputs=new URL('📥️inputs/',ticket);const captures:Record<string,any[]>={};
const owners=['brep','cad','document','drawing','kit','model','presentation'];
for(const owner of owners){const path=new URL('semio-'+owner+'-complete-semantic/📜️script.ts',inputs);let source=await Bun.file(path).text();const rows:any[]=[];
class Database extends Sqlite{close(){const tables:Record<string,any[][]>={};for(const item of this.query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as any[]){if(item.name==='semio_snapshot')continue;const cells=this.query('SELECT * FROM '+item.name).safeIntegers(true).values();if(cells.length)tables[item.name]=cells.map(row=>row.map(cell=>typeof cell==='number'&&!Number.isFinite(cell)?{realSpecial:String(cell)}:typeof cell==='bigint'?{integerDecimal:cell.toString()}:cell instanceof Uint8Array?{blobBytes:Array.from(cell)}:cell));}rows.push(tables);return super.close();}}
source=source.replace(/import\s+([^;]+?)\s+from\s+(['"])([^'"]+)\2\s*;/g,(_,bindings:string,_quote:string,module:string)=>{if(module==='bun:sqlite')return '';const resolved=module.startsWith('.')?new URL(module,path).href:module;return 'const '+bindings.replace(/ as /g,':')+'='+(bindings.trim().startsWith('{')?'await import('+JSON.stringify(resolved)+')':'(await import('+JSON.stringify(resolved)+')).default')+';';}).replaceAll('import.meta.url',JSON.stringify(path.href));
const localBun=new Proxy(Bun,{get(target,key){if(key==='write')return async()=>0;return Reflect.get(target,key);}});await new (Object.getPrototypeOf(async function(){}).constructor)('Database','Bun',new Bun.Transpiler({loader:'ts'}).transformSync(source))(Database,localBun);captures[owner]=rows;
}
await Bun.write(new URL('retained-manual-child-cells.json',import.meta.url),JSON.stringify(captures,null,2)+'\n');console.log('[DEBUG] '+JSON.stringify(Object.fromEntries(Object.entries(captures).map(([key,value])=>[key,value.length]))));

const contracts=await Bun.file(new URL('current-matched-child-contracts.json',import.meta.url)).json();
const subsetRoot=new URL('✏️s/🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/',new URL('../../../../../../../../../../',import.meta.url));
const dirs={flow:'🌊️flow',image:'🖼️image',animation:'🎞️animation',mesh:'🔺️mesh',value:'🔢️value',table:'📊️table',graph:'🕸️graph',audio:'🔊️audio',video:'🎬️video',text:'🔤️text',object:'📦️object'};

const word=(n:number)=>{const v=new DataView(new ArrayBuffer(8));v.setFloat64(0,n);return {bits:v.getBigUint64(0).toString(16).padStart(16,'0')};};
for(const owner of ['audio','video','text','object']){const f=await Bun.file(new URL((dirs as any)[owner]+'/🚪️io/🪶️sqlite/📸️snapshot/🧫️fixtures/🔣️.json',subsetRoot)).json();let full:any,empty:any;
if(owner==='audio'){full={schema:f.schema,sampleRate:f.sampleRate,format:'f64',channels:f.channels.map((samples:number[])=>({samples:samples.map(bits=>({bits}))})),tags:f.tags.map(([key,value]:string[])=>({key,value}))};empty={...full,channels:[]};}
if(owner==='video'){full={schema:f.schema,streams:['video','audio','subtitle'].map(kind=>({kind,codec:f.codec,width:4294967295,height:4294967295,rate:{num:f.rateNumerator,den:f.rateDenominator},samples:[{pts:f.timestamp,key:true,data:[0,1,255]},{pts:'0',key:false,data:[]}]}))};empty={...full,streams:[]};}
if(owner==='text'){full={schema:f.schema,runs:f.runs.map((r:any)=>({...r,marks:r.marks.map((m:any)=>({...m,kind:['bold','italic','code'].includes(m.kind)?m.kind:'link'}))}))};empty={...full,runs:[]};}
if(owner==='object'){const child=(i:number,childId:string)=>({childId,target:{artifactId:f.children[i][0],dialect:{artifactKind:f.children[i][1],standard:f.children[i][2],subset:f.children[i][3]}}});full={schema:'stdio.semio.object',transform:{translation:Object.fromEntries(['x','y','z'].map((k,i)=>[k,word(f.translation[i])])),rotation:{x:word(0),y:word(0),z:word(0),w:word(1)},scale:{x:word(-1),y:word(2),z:word(.5)}},brep:child(0,'brep-owned'),mesh:child(1,'mesh-owned'),properties:child(2,'value-owned')};empty={...full,brep:null,mesh:null,properties:null};}
contracts[owner]={cases:[{id:'full',sourceSnapshot:full},{id:'metadataRetainingEmpty',sourceSnapshot:empty}]};}

for(const tag of ['audio','object','flow','video']){const mounted=await Bun.file(new URL((dirs as any)[tag]+'/🚪️io/🪶️sqlite/📸️snapshot/🧫️fixtures/🎛️semantic.json',subsetRoot)).json();const full=contracts[tag].cases[0].sourceSnapshot;const empty=contracts[tag].cases[1].sourceSnapshot;for(const c of mounted.cases){if(['full','metadataRetainingEmpty'].includes(c.id))continue;const source=structuredClone((c.empty??false)?empty:full);if(tag==='audio')source.format=c.format;if(tag==='object'&&c.word!==null)source.transform.translation.x={bits:c.word};if(tag==='flow'){source.nodes[0].position={x:{bits:c.word},y:{bits:c.word}};if(c.id.startsWith('singleNodeEmptyRelations-')){source.nodes=source.nodes.slice(0,1);source.nodes[0].params=[];source.edges=[];}}if(tag==='video')Object.assign(source,c.snapshot);contracts[tag].cases.push({...c,sourceSnapshot:source});}}
const authored:Record<string,any[]>={};
function float(value:any){const h=value.bits;const wide=h.length===16;const bits=BigInt('0x'+h);const buf=new ArrayBuffer(wide?8:4);const view=new DataView(buf);if(wide)view.setBigUint64(0,bits);else view.setUint32(0,Number(bits));const n=wide?view.getFloat64(0):view.getFloat32(0);return [Number.isNaN(n)?null:n,wide?BigInt.asIntN(64,bits):bits,Number.isNaN(n)?'nan':n===Infinity?'positiveInfinity':n===-Infinity?'negativeInfinity':'finite'];}
for(const [owner,dir] of Object.entries(dirs)){authored[owner]=[];for(const demand of contracts[owner].cases){const s=demand.sourceSnapshot;const db=new Sqlite(':memory:');db.exec(await Bun.file(new URL(dir+'/🚪️io/🪶️sqlite/📸️snapshot/🗄️.sql',subsetRoot)).text());const ids:Record<string,number>={};const add=(name:string,cells:any[])=>{const table='semio_'+owner+'_'+name;const id=ids[name]=(ids[name]??0)+1;db.query('INSERT INTO '+table+' VALUES ('+Array(cells.length+1).fill('?').join(',')+')').run(id,...cells);return id;};const vector=(fields:any[])=>{const words=fields.map(float);return [...words.map(x=>x[0]),...words.flatMap(x=>x.slice(1))];};
if(owner==='flow'){add('document',[s.schema]);const nodes=new Map<string,number>();s.nodes.forEach((n:any,i:number)=>{const id=add('node',[1,i,n.id,n.kind,n.label,...vector([n.position.x,n.position.y])]);nodes.set(n.id,id);n.params.forEach((p:any,j:number)=>add('parameter',[id,j,p.key,p.value]));});s.edges.forEach((e:any,i:number)=>add('edge',[1,i,e.id,nodes.get(e.from.node),e.from.port,nodes.get(e.to.node),e.to.port,e.kind]));}
if(owner==='image'){add('document',[s.schema,s.width,s.height,s.colorspace,s.bitDepth,s.icc===null?null:new Uint8Array(s.icc)]);s.frames.forEach((f:any,i:number)=>{const id=add('frame',[1,i,f.delayMs]);f.rgba8.forEach((v:number,j:number)=>add('sample',[id,Math.floor(j/4),j%4,v]));});s.metadata.forEach((m:any,i:number)=>add('metadata',[1,i,m.key,m.value]));}
if(owner==='animation'){add('document',[s.schema]);s.timelines.forEach((t:any,i:number)=>{const tid=add('timeline',[1,i,t.name]);t.channels.forEach((c:any,j:number)=>{const cid=add('channel',[tid,j,c.target.node,c.target.property.kind,c.target.property.name??null,c.interpolation==='cubicSpline'?'cubic_spline':c.interpolation]);c.keyframes.forEach((k:any,l:number)=>{const t=float(k.t);const kind=({vec3:'vector3',quat:'quaternion'} as any)[k.value.kind]??k.value.kind;const kid=add('keyframe',[cid,l,t[0],kind,t[1],t[2]]);if(kind==='weights')k.value.values.forEach((v:any,m:number)=>add('weight',[kid,m,...float(v)]));else{const fields=kind==='scalar'?[k.value.value]:['x','y','z',...(kind==='quaternion'?['w']:[])].map(x=>k.value.value[x]);db.query('INSERT INTO semio_animation_'+kind+' VALUES ('+Array(1+fields.length*3).fill('?').join(',')+')').run(kid,...vector(fields));}});});});}
if(owner==='mesh'){add('document',[s.schema]);s.meshes.forEach((m:any,i:number)=>{const mid=add('mesh',[1,i,m.id]);m.primitives.forEach((p:any,j:number)=>{const topology=p.topology.replace(/[A-Z]/g,(x:string)=>'_'+x.toLowerCase());const pid=add('primitive',[mid,j,p.id,topology,p.materialId??null]);for(const [source,name,axes] of [['positions','position',['x','y','z']],['normals','normal',['x','y','z']],['uvs','uv',['u','v']],['colors','color',['r','g','b','a']]] as any[])p[source].forEach((v:any,k:number)=>add(name,[pid,k,...vector(axes.map((a:string)=>v[a]))]));p.indices.forEach((v:number,k:number)=>add('index',[pid,k,v]));});});s.materials.forEach((m:any,i:number)=>{const words=[m.baseColor.r,m.baseColor.g,m.baseColor.b,m.baseColor.a,m.metallic,m.roughness].map(float);add('material',[1,i,m.id,...words.map(x=>x[0]),...['baseColorTexture','metallicRoughnessTexture','normalTexture','occlusionTexture','emissiveTexture'].map(k=>m[k]??null),...words.flatMap(x=>x.slice(1))]);});s.textures.forEach((t:any,i:number)=>add('texture',[1,i,t.id,t.mime,new Uint8Array(t.bytes)]));}

if(['value','table','graph'].includes(owner)){const nativeNodes=new Map<string,number>((s.nodes??[]).map((n:any,i:number)=>[n.id.value,i+1]));const tree=(v:any):number=>{const id=add('value',[v.kind,v.kind==='bool'?Number(v.value):null,v.kind==='int'?v.lexeme:null,v.kind==='float'?v.lexeme:null,v.kind==='str'?v.value:null,v.kind==='bytes'?new Uint8Array(v.value):null,v.kind==='ref'?(owner==='value'?nativeNodes.get(v.id.value):v.id.value):null]);if(v.kind==='list')v.items.forEach((x:any,i:number)=>add('list_element',[id,i,tree(x)]));if(v.kind==='map')v.entries.forEach((x:any,i:number)=>add('map_entry',[id,i,x.key,tree(x.value)]));return id;};
if(owner==='value'){const root=tree(s.root);add('document',[s.schema,root]);s.nodes.forEach((n:any,i:number)=>add('node',[1,i,n.id.value,tree(n.value)]));}
if(owner==='table'){add('document',[s.schema]);s.columns.forEach((c:any,i:number)=>add('column',[1,i,c.name,c.kind]));s.rows.forEach((r:any,i:number)=>{const id=add('row',[1,i]);r.cells.forEach((v:any,j:number)=>add('cell',[id,j,tree(v)]));});}
if(owner==='graph'){add('document',[s.schema]);s.nodes.forEach((n:any,i:number)=>{const id=add('node',[1,i,n.id.value,n.kind,n.label,...vector([n.position.x,n.position.y,n.width,n.height])]);n.ports.forEach((p:any,j:number)=>{const pid=add('port',[id,j,p.name,p.kind==='inOut'?'in_out':p.kind,p.category]);p.properties.forEach((x:any,k:number)=>add('port_property',[pid,k,x.key,tree(x.value)]));});n.properties.forEach((x:any,j:number)=>add('property',[id,j,x.key,tree(x.value)]));});s.edges.forEach((e:any,i:number)=>{const id=add('edge',[1,i,e.id.value,nativeNodes.get(e.source.value),nativeNodes.get(e.target.value),e.kind,e.label,e.sourcePort??null,e.targetPort??null]);e.properties.forEach((x:any,j:number)=>add('edge_property',[id,j,x.key,tree(x.value)]));});}}

if(owner==='audio'){add('document',[s.schema,s.sampleRate,s.format]);s.channels.forEach((c:any,i:number)=>{const id=add('channel',[1,i]);c.samples.forEach((v:any,j:number)=>{const buf=new DataView(new ArrayBuffer(4));buf.setUint32(0,v.bits);const n=buf.getFloat32(0);add('sample',[id,j,Number.isNaN(n)?null:n,BigInt(v.bits)]);});});s.tags.forEach((t:any,i:number)=>add('tag',[1,i,t.key,t.value]));}
if(owner==='video'){add('document',[s.schema]);s.streams.forEach((t:any,i:number)=>{const id=add('stream',[1,i,t.kind,t.codec,t.width,t.height,BigInt(t.rate.num),BigInt(t.rate.den)]);t.samples.forEach((v:any,j:number)=>add('sample',[id,j,v.pts,Number(v.key),new Uint8Array(v.data)]));});}
if(owner==='text'){add('document',[s.schema]);s.runs.forEach((r:any,i:number)=>{const id=add('run',[1,i,r.language,r.content]);r.marks.forEach((m:any,j:number)=>add('mark',[id,j,m.kind,m.href]));});}
if(owner==='object'){add('document',[s.schema,...vector(['translation','rotation','scale'].flatMap(k=>['x','y','z',...(k==='rotation'?['w']:[])].map(a=>s.transform[k][a])))]);for(const [name,table] of [['brep','brep_child'],['mesh','mesh_child'],['properties','value_child']]){const c=s[name];if(c!==null){const d=c.target.dialect;const id=add('reference',[c.target.artifactId,d.artifactKind,d.standard,d.subset]);add(table,[1,c.childId,id]);}}}
const tables:Record<string,any[][]>={};let rows=0,bytes=0;for(const {name} of db.query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as any[]){const cells=db.query('SELECT * FROM '+name).safeIntegers(true).values();if(cells.length)tables[name]=cells.map(row=>row.map(cell=>{bytes+=cell===null?0:typeof cell==='string'?new TextEncoder().encode(cell).length:cell instanceof Uint8Array?cell.length:8;return typeof cell==='number'&&!Number.isFinite(cell)?{realSpecial:String(cell)}:typeof cell==='bigint'?{integerDecimal:cell.toString()}:cell instanceof Uint8Array?{blobBytes:Array.from(cell)}:cell;}));rows+=cells.length;}if(demand.rows!==undefined){assert.equal(rows,demand.rows);assert.equal(bytes,demand.valueBytes);}authored[owner].push({id:demand.id,sourceSnapshot:s,tables,rows,valueBytes:bytes});db.close();console.log('[DEBUG] '+owner+'/'+demand.id+' '+rows+'/'+bytes);}}
await Bun.write(new URL('additional-authored-child-cells.json',import.meta.url),JSON.stringify(authored,null,2)+'\n');

const tags=['brep','mesh','model','value','document','cad','drawing','image','video','audio','animation','presentation','flow','text','table','graph','object','kit'];const allDirs=['🧊️brep','🔺️mesh','🏛️model','🔢️value','📑️document','📐️cad','🖊️drawing','🖼️image','🎬️video','🔊️audio','🎞️animation','📽️presentation','🌊️flow','🔤️text','📊️table','🕸️graph','📦️object','🧰️kit'];let allSql=await Bun.file(new URL('✉️base/🚪️io/🪶️sqlite/📸️snapshot/🗄️.sql',subsetRoot)).text();for(const dir of allDirs)allSql+=await Bun.file(new URL(dir+'/🚪️io/🪶️sqlite/📸️snapshot/🗄️.sql',subsetRoot)).text();const metadata=await Bun.file(new URL('🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧬️schema/🗄️.sql',new URL('../../../../../../../../../../',import.meta.url))).text();
const cases:any[]=[];const publicCases:any[]=[];const semanticCells:any[]=[];let tableWidths:any;const decode=(c:any)=>c&&typeof c==='object'?('integerDecimal'in c?BigInt(c.integerDecimal):'blobBytes'in c?new Uint8Array(c.blobBytes):'realSpecial'in c?Number(c.realSpecial):c):c;
for(let index=0;index<tags.length;index++){const tag=tags[index];for(let variant=0;variant<2;variant++){const child=authored[tag]?.[variant];const tables=child?.tables??captures[tag][variant];const snapshot=child?.sourceSnapshot??contracts[tag].cases[variant].sourceSnapshot;const id=tag+'/'+(variant?'metadataRetainingEmpty':'full');const body={schema:'stdio.semio',subset:{subset:tag,...snapshot}};for(const encoding of [null,'binary','text']){const db=new Sqlite(':memory:');db.exec(allSql);if(encoding)db.exec(metadata);const insert=(name:string,row:any[])=>db.query('INSERT INTO '+name+' VALUES ('+row.map(()=>'?').join(',')+')').run(...row.map(decode));const root:any[]=[1,'stdio.semio',tag,...Array(18).fill(null)];root[3+index]=1;insert('semio_base_document',root);for(const [name,rows] of Object.entries(tables) as [string,any[][]][])for(const row of rows)insert(name,row);if(encoding)insert('semio_snapshot',[1,'s.stdio.semio','v1','*',1,encoding]);assert.deepEqual(db.query('PRAGMA integrity_check').get(),{integrity_check:'ok'});assert.deepEqual(db.query('PRAGMA foreign_key_check').all(),[]);let rows=0,valueBytes=0,schemaBytes=0;const widths:Record<string,number>={};const cells:Record<string,any[][]>={};for(const t of db.query("SELECT name,sql FROM sqlite_master WHERE type='table' ORDER BY name").all() as any[]){schemaBytes+=Buffer.byteLength(t.name)+Buffer.byteLength(t.sql);widths[t.name]=db.query('PRAGMA table_info('+t.name+')').all().length;const vals=db.query('SELECT * FROM '+t.name).safeIntegers(true).values();if(vals.length)cells[t.name]=vals.map(row=>row.map(c=>typeof c==='number'&&!Number.isFinite(c)?{realSpecial:String(c)}:typeof c==='bigint'?{integerDecimal:c.toString()}:c instanceof Uint8Array?{blobBytes:Array.from(c)}:c));rows+=vals.length;for(const row of vals)for(const c of row)valueBytes+=c===null?0:typeof c==='string'?Buffer.byteLength(c):c instanceof Uint8Array?c.length:8;}assert.equal(Object.keys(widths).length,encoding?184:183);assert.equal(schemaBytes,encoding?57019:56726);assert.equal(Math.max(...Object.values(widths)),54);if(!encoding){tableWidths=widths;cases.push({id,sourceSnapshot:body,rows,valueBytes});semanticCells.push({id,tables:cells});}else{let pub=publicCases.find(x=>x.id===id);if(!pub){pub={id,rows,valueBytes:{}};publicCases.push(pub);}pub.valueBytes[encoding]=valueBytes;assert.equal(valueBytes-cases.at(-1).valueBytes,encoding==='binary'?38:36);}db.close();}}}
const publicWidths={...tableWidths,semio_snapshot:6};const contract={schemaBytes:56726,tableWidths,cases,publicIo:{schemaBytes:57019,tableWidths:publicWidths,cases:publicCases}};const contractSchema={$schema:'https://json-schema.org/draft/2020-12/schema',type:'object',properties:Object.fromEntries(Object.entries(contract).map(([k,v])=>[k,{const:v}])),required:Object.keys(contract),additionalProperties:false};const Ajv=(await import('ajv/dist/2020')).default;assert.equal(new Ajv({strict:true}).compile(contractSchema)(contract),true);assert.equal(cases.length,36);await Bun.write(new URL('handcrafted-native-complete-contract.json',import.meta.url),JSON.stringify(contract,null,2)+'\n');await Bun.write(new URL('handcrafted-native-complete-contract-schema.json',import.meta.url),JSON.stringify(contractSchema,null,2)+'\n');await Bun.write(new URL('handcrafted-native-complete-semantic-cells.json',import.meta.url),JSON.stringify(semanticCells,null,2)+'\n');console.log('[DEBUG] Base36 '+JSON.stringify(cases.map(({id,rows,valueBytes})=>({id,rows,valueBytes}))));

const hydrates:Record<string,string>={};for(const folder of ['semio-kit-complete-semantic','semio-mesh-complete-semantic','semio-flow-image-complete-semantic','semio-document-complete-semantic','semio-presentation-complete-semantic','semio-cad-complete-semantic','semio-model-complete-semantic','semio-drawing-complete-semantic','semio-graph-animation-complete-semantic','semio-brep-complete-semantic']){for(const file of new Bun.Glob('*specifications.json').scanSync({cwd:decodeURIComponent(new URL(folder+'/',inputs).pathname)})){const specs=await Bun.file(new URL(folder+'/'+file,inputs)).json();for(const spec of specs)hydrates[spec.name]=spec.hydrate;}}
hydrates.flow='const h=(v:any):any=>Array.isArray(v)?v.map(h):v!==null&&typeof v==="object"?("bits"in v?{bits:BigInt("0x"+v.bits)}:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,h(x)]))):v;Object.assign(source,h(source))';hydrates.audio='';hydrates.text='';hydrates.video='for(const stream of source.streams){stream.rate.num=BigInt(stream.rate.num);stream.rate.den=BigInt(stream.rate.den);for(const sample of stream.samples)sample.pts=BigInt(sample.pts)}';hydrates.object='const hydrate=(v:any):any=>Array.isArray(v)?v.map(hydrate):v!==null&&typeof v==="object"?("bits"in v?{bits:BigInt("0x"+v.bits)}:Object.fromEntries(Object.entries(v).filter(([,x])=>x!==null).map(([k,x])=>[k,hydrate(x)]))):v;Object.assign(source,hydrate(source));for(const key of ["brep","mesh","properties"])if(source[key]===null)delete source[key]';hydrates.value='';hydrates.table='';
const ieee=await import(new URL('🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts',new URL('../../../../../../../../../../',import.meta.url)).href);let words32=0,words64=0,parsers=0;for(const item of cases){const source=structuredClone(item.sourceSnapshot.subset);const tag=source.subset;delete source.subset;new Function('source',new Bun.Transpiler({loader:'ts'}).transformSync(hydrates[tag]??''))(source);const admit=(v:any):void=>{if(Array.isArray(v))v.forEach(admit);else if(v&&typeof v==='object'){if('bits'in v){if(typeof v.bits==='number'){ieee.parseBinary32(v);words32++;}else{ieee.parseBinary64(v);words64++;}}else Object.values(v).forEach(admit);}};admit(source);const module=await import(new URL(allDirs[tags.indexOf(tag)]+'/🧬️schema/📸️snapshot/🟦️.ts',subsetRoot).href);const parse=module['parseSemio'+tag[0].toUpperCase()+tag.slice(1)+'Snapshot'];if(parse){parse(source);parsers++;}}
const baseHydrate='const handlers='+JSON.stringify(hydrates)+';const child=source.subset;const tag=child.subset;new Function("source",handlers[tag])(child)';const runnableHydrates=Object.fromEntries(Object.entries(hydrates).map(([k,v])=>[k,new Bun.Transpiler({loader:'ts'}).transformSync(v)]));const hydrate='const handlers='+JSON.stringify(runnableHydrates)+';new Function("source",handlers[source.subset.subset])(source.subset)';new Bun.Transpiler({loader:'ts'}).transformSync(hydrate);await Bun.write(new URL('handcrafted-native-complete-demand-specifications.json',import.meta.url),JSON.stringify([{name:'base',cap:'Base',tables:183,maxColumns:54,contract,hydrate,rustBody:'let subset=case["id"].as_str().unwrap().split("/").next().unwrap();let empty=case["id"].as_str().unwrap().ends_with("/metadataRetainingEmpty");SemioSnapshot{schema:"stdio.semio".into(),subset:complete_child_fixture(subset,empty)}'}],null,2)+'\n');console.log('[DEBUG] '+JSON.stringify({actualBinary32Words:words32,actualBinary64Words:words64,actualDomainParsers:parsers}));

for(let index=0;index<tags.length;index++){const tag=tags[index];const mounted=await Bun.file(new URL(allDirs[index]+'/🚪️io/🪶️sqlite/📸️snapshot/🧫️fixtures/🎛️semantic.json',subsetRoot)).json();for(let v=0;v<2;v++){const base=cases[index*2+v];const selected=mounted.cases.find((c:any)=>c.id===(tag==='object'?(v?'empty_original':'full_original'):tag==='audio'?(v?'empty_f64':'full_f64'):v?'metadataRetainingEmpty':'full'));assert(selected);assert.equal(selected.rows,base.rows-1);assert.equal(selected.valueBytes,base.valueBytes-(27+Buffer.byteLength(tag)));}console.log('[DEBUG] child mounted matched '+tag);}
