//! 🧪️ Original canonical Fault bytes agree with Serde under independently denied native grants.
use crate::*;
use semio_framework_value::FromValue;
use semio_framework_value::retained_clone::{RetainedCloneGrant,RetainedCloneProgress};
fn observed<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
#[test]
fn original_fault_wire_cursor_preserves_canonical_bytes_original_custody_and_literal_zero_metadata(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let p=law["originalGrant"].as_array().unwrap();let grant=RetainedCloneGrant{maximum_items:p[0].as_u64().unwrap()as usize,maximum_copy_bytes:p[1].as_u64().unwrap()as usize,maximum_capacity_bytes:p[2].as_u64().unwrap()as usize,maximum_release_bytes:p[3].as_u64().unwrap()as usize,maximum_depth:p[4].as_u64().unwrap()as usize};
 let canonical:serde_json::Value=serde_json::from_str(include_str!("../../../🧫️fixtures/🧯️fault/🔣️.json")).unwrap();let mut rows=canonical["cases"].as_array().unwrap().clone();let mut escaped=rows[1].clone();escaped["id"]=serde_json::json!("literal-json-escapes");escaped["input"]["message"]=serde_json::json!((0u8..32).map(char::from).collect::<String>()+"\"\\ / Über 🧩");escaped["expected"]["message"]=escaped["input"]["message"].clone();escaped["input"]["retainedProgress"]=serde_json::json!({"copiedItems":19,"copiedBytes":17,"retainedCapacityBytes":8192,"releasedBytes":64});escaped["expected"]["retainedProgress"]=escaped["input"]["retainedProgress"].clone();rows.push(escaped);
 for row in &rows{let fault=Fault::from_value(serde_json::from_value(row["input"].clone()).unwrap()).unwrap();let foreign=Fault::from_value(serde_json::from_value(row["input"].clone()).unwrap()).unwrap();let original=std::ptr::addr_of!(fault);let text=fault.message.as_ptr();
  for cut in law["cuts"].as_array().unwrap(){let cut=cut.as_u64().map_or(usize::MAX,|value|value as usize);let(mut cursor,heap)=observed(FaultWireCursor::new);assert_eq!(heap,(0,0));let mut output=[std::mem::MaybeUninit::<u8>::uninit();2048];let mut foreign_output=output;let target=output.as_mut_ptr();let mut turns=0;let mut copied=0;
   while !cursor.is_complete()&&turns<cut{let(demand,heap)=observed(||cursor.advance_demands(&fault,&output).unwrap());assert_eq!(heap,(0,0));for denied in [Some(RetainedCloneGrant{maximum_items:0,..grant}),Some(RetainedCloneGrant{maximum_depth:0,..grant}),(demand.copy_bytes>0).then_some(RetainedCloneGrant{maximum_copy_bytes:0,..grant})].into_iter().flatten(){let before=cursor.written();let(step,heap)=observed(||cursor.advance_one(&fault,&mut output,denied).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress::default());assert_eq!(cursor.written(),before);}
    if turns>0{let(refused,heap)=observed(||cursor.advance_one(&foreign,&mut output,grant));assert!(refused.is_err());assert_eq!(heap,(0,0));let(refused,heap)=observed(||cursor.advance_one(&fault,&mut foreign_output,grant));assert!(refused.is_err());assert_eq!(heap,(0,0));}
    let(step,heap)=observed(||cursor.advance_one(&fault,&mut output,grant).unwrap());assert_eq!(heap,(0,0));let receipt=step.progress();assert!(receipt.fits(grant));assert_eq!(receipt.copied_items,1);assert!(receipt.copied_bytes<=1);assert_eq!(receipt.retained_capacity_bytes,0);assert_eq!(receipt.released_bytes,0);copied+=receipt.copied_bytes;turns+=1;assert!(turns<10000);assert_eq!(std::ptr::addr_of!(fault),original);assert_eq!(fault.message.as_ptr(),text);assert_eq!(output.as_mut_ptr(),target);
   }
   assert_eq!(copied,cursor.written());if cut==usize::MAX{assert!(cursor.is_complete());let actual:serde_json::Value=serde_json::from_slice(unsafe{std::slice::from_raw_parts(output.as_ptr().cast::<u8>(),cursor.written())}).unwrap();assert_eq!(actual,row["expected"]);let independently_encoded=serde_json::to_vec(&row["expected"]).unwrap();assert_eq!(serde_json::from_slice::<serde_json::Value>(&independently_encoded).unwrap(),actual);}
   if !cursor.terminal_is_empty(){let(step,heap)=observed(||cursor.close_step(RetainedCloneGrant{maximum_items:0,..grant}).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress::default());assert!(!cursor.terminal_is_empty());let(step,heap)=observed(||cursor.close_step(RetainedCloneGrant{maximum_copy_bytes:0,..grant}).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress{copied_items:1,..Default::default()});assert!(cursor.terminal_is_empty());}let(_,heap)=observed(||drop(cursor));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual Fault wire original={} cut={cut} turns={turns} bytes={copied} copy17 metadata0 heap0 originalSource={original:p} originalTarget={target:p} terminalDrop0",row["id"]);
  }
 }
}

#[test]
fn original_fault_wire_cursor_streams_long_wire_through_one_native_window_and_paid_drains(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🌊️stream/🧫️fixtures/🔣️.json")).unwrap();let p=law["originalGrant"].as_array().unwrap();let grant=RetainedCloneGrant{maximum_items:p[0].as_u64().unwrap()as usize,maximum_copy_bytes:p[1].as_u64().unwrap()as usize,maximum_capacity_bytes:p[2].as_u64().unwrap()as usize,maximum_release_bytes:p[3].as_u64().unwrap()as usize,maximum_depth:p[4].as_u64().unwrap()as usize};
 let canonical:serde_json::Value=serde_json::from_str(include_str!("../../../🧫️fixtures/🧯️fault/🔣️.json")).unwrap();let mut row=canonical["cases"][1].clone();row["input"]["message"]=serde_json::json!("🧩\\\"\n".repeat(2049));row["expected"]["message"]=row["input"]["message"].clone();let fault=Fault::from_value(serde_json::from_value(row["input"].clone()).unwrap()).unwrap();let foreign=Fault::from_value(serde_json::from_value(row["input"].clone()).unwrap()).unwrap();let native_fault=std::ptr::addr_of!(fault);let native_message=fault.message.as_ptr();
 for cut in [0,1,13,512,usize::MAX]{let mut target=[std::mem::MaybeUninit::<u8>::uninit();17];let mut foreign_target=target;let native_target=target.as_mut_ptr();let(mut cursor,heap)=observed(FaultWireCursor::new);assert_eq!(heap,(0,0));let mut output=Vec::new();let mut turns=0;let mut copied=0;let mut drains=0;
  while (!cursor.is_complete()||!cursor.buffered_bytes(&target).unwrap().is_empty())&&turns<cut{
   if cursor.buffered_bytes(&target).unwrap().len()==17||cursor.is_complete(){
    let(bytes,heap)=observed(||cursor.buffered_bytes(&target).unwrap());assert_eq!(heap,(0,0));output.extend_from_slice(bytes);
    let before=cursor.written();let(step,heap)=observed(||cursor.drain_buffer(&target,RetainedCloneGrant{maximum_items:0,..grant}).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),Default::default());assert_eq!(cursor.written(),before);assert!(!cursor.buffered_bytes(&target).unwrap().is_empty());
    let(refusal,heap)=observed(||cursor.drain_buffer(&foreign_target,grant));assert!(refusal.is_err());assert_eq!(heap,(0,0));let(step,heap)=observed(||cursor.drain_buffer(&target,RetainedCloneGrant{maximum_copy_bytes:0,..grant}).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress{copied_items:1,..Default::default()});assert!(cursor.buffered_bytes(&target).unwrap().is_empty());assert_eq!(cursor.written(),before);drains+=1;
   }else{
    let(demand,heap)=observed(||cursor.advance_demands(&fault,&target).unwrap());assert_eq!(heap,(0,0));for denied in [Some(RetainedCloneGrant{maximum_items:0,..grant}),Some(RetainedCloneGrant{maximum_depth:0,..grant}),(demand.copy_bytes>0).then_some(RetainedCloneGrant{maximum_copy_bytes:0,..grant})].into_iter().flatten(){let before=cursor.written();let(step,heap)=observed(||cursor.advance_one(&fault,&mut target,denied).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),Default::default());assert_eq!(cursor.written(),before);}
    if !cursor.terminal_is_empty(){let(refused,heap)=observed(||cursor.advance_one(&foreign,&mut target,grant));assert!(refused.is_err());assert_eq!(heap,(0,0));let(refused,heap)=observed(||cursor.advance_one(&fault,&mut foreign_target,grant));assert!(refused.is_err());assert_eq!(heap,(0,0));}
    let(step,heap)=observed(||cursor.advance_one(&fault,&mut target,grant).unwrap());assert_eq!(heap,(0,0));assert!(step.progress().fits(grant));assert_eq!(step.progress().copied_items,1);assert!(step.progress().copied_bytes<=1);copied+=step.progress().copied_bytes;
   }turns+=1;assert!(turns<100000);assert_eq!(target.as_mut_ptr(),native_target);assert_eq!(std::ptr::addr_of!(fault),native_fault);assert_eq!(fault.message.as_ptr(),native_message);
  }assert_eq!(cursor.written(),copied);if cut==usize::MAX{assert_eq!(output.len(),copied);assert_eq!(serde_json::from_slice::<serde_json::Value>(&output).unwrap(),row["expected"]);assert!(copied>8193);assert!(drains>480);}
  if !cursor.terminal_is_empty(){let(step,heap)=observed(||cursor.close_step(RetainedCloneGrant{maximum_copy_bytes:0,..grant}).unwrap());assert_eq!(heap,(0,0));assert_eq!(step.progress(),RetainedCloneProgress{copied_items:1,..Default::default()});}let(_,heap)=observed(||drop(cursor));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual long canonical Fault streamed17 cut={cut} turns={turns} bytes={copied} drains={drains} originalFault={native_fault:p} target={native_target:p} heap0 metadata0 terminalDrop0");
 }
}
