[package]
name = "semio-framework-kernel-mathematical-graph-normal-directed"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_normal_directed"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph = { path = "../../../rs", package = "semio-framework-kernel-mathematical-graph" }
mathematical_random = { path = "../../../../random/rs", package = "semio-framework-kernel-mathematical-random" }
mathematical_algebra = { path = "../../../../algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
mathematical_graph_traversal = { path = "../../../traversal/rs", package = "semio-framework-kernel-mathematical-graph-traversal" }
mathematical_graph_components = { path = "../../../components/rs", package = "semio-framework-kernel-mathematical-graph-components" }
mathematical_graph_dag = { path = "../../../dag/rs", package = "semio-framework-kernel-mathematical-graph-dag" }
mathematical_graph_cycles = { path = "../../../cycles/rs", package = "semio-framework-kernel-mathematical-graph-cycles" }
mathematical_graph_paths = { path = "../../../paths/rs", package = "semio-framework-kernel-mathematical-graph-paths" }
mathematical_graph_operators = { path = "../../../operators/rs", package = "semio-framework-kernel-mathematical-graph-operators" }
mathematical_graph_coloring = { path = "../../../coloring/rs", package = "semio-framework-kernel-mathematical-graph-coloring" }
mathematical_graph_generate = { path = "../../../generate/rs", package = "semio-framework-kernel-mathematical-graph-generate" }
mathematical_graph_generate_random = { path = "../../../generate/random/rs", package = "semio-framework-kernel-mathematical-graph-generate-random" }
mathematical_graph_io = { path = "../../../io/rs", package = "semio-framework-kernel-mathematical-graph-io" }
mathematical_graph_structure = { path = "../../../structure/rs", package = "semio-framework-kernel-mathematical-graph-structure" }
mathematical_graph_cliques = { path = "../../../cliques/rs", package = "semio-framework-kernel-mathematical-graph-cliques" }
mathematical_graph_clustering = { path = "../../../clustering/rs", package = "semio-framework-kernel-mathematical-graph-clustering" }
mathematical_graph_matching = { path = "../../../matching/rs", package = "semio-framework-kernel-mathematical-graph-matching" }
mathematical_graph_bipartite = { path = "../../../bipartite/rs", package = "semio-framework-kernel-mathematical-graph-bipartite" }
mathematical_graph_trees = { path = "../../../trees/rs", package = "semio-framework-kernel-mathematical-graph-trees" }
mathematical_graph_planarity = { path = "../../../planarity/rs", package = "semio-framework-kernel-mathematical-graph-planarity" }
mathematical_graph_flow = { path = "../../../flow/rs", package = "semio-framework-kernel-mathematical-graph-flow" }
mathematical_graph_centrality = { path = "../../../centrality/rs", package = "semio-framework-kernel-mathematical-graph-centrality" }
mathematical_graph_distance = { path = "../../../distance/rs", package = "semio-framework-kernel-mathematical-graph-distance" }
mathematical_graph_similarity = { path = "../../../similarity/rs", package = "semio-framework-kernel-mathematical-graph-similarity" }
mathematical_graph_isomorphism = { path = "../../../isomorphism/rs", package = "semio-framework-kernel-mathematical-graph-isomorphism" }
mathematical_graph_connectivity = { path = "../../../connectivity/rs", package = "semio-framework-kernel-mathematical-graph-connectivity" }
mathematical_graph_community = { path = "../../../community/rs", package = "semio-framework-kernel-mathematical-graph-community" }
mathematical_graph_approximation = { path = "../../../approximation/rs", package = "semio-framework-kernel-mathematical-graph-approximation" }
mathematical_graph_spectral = { path = "../../../spectral/rs", package = "semio-framework-kernel-mathematical-graph-spectral" }
