[package]
name = "semio-framework-plugin-host"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
semio-framework-core = { path = "../../../core/rs" }
ui_wgpu = { path = "../../../ui/wgpu/rs", package = "ui_wgpu" }
vcs = { path = "../../../os/kernel/vcs/rs", package = "semio-framework-os-kernel-vcs" }
store = { path = "../../../os/kernel/store/rs", package = "semio-framework-os-kernel-store" }
wasmtime = { version = "22.0.1", features = ["cranelift", "component-model"] }
wasmtime-wasi = "22.0.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
