/** 📇️ Independent SQLite proves every date width and owned document info relationship. */
import { expect,test } from "bun:test";
import { Database } from "bun:sqlite";
import { PdfProjection,PdfReader } from "../../../🪶️sqlite/🧩️entity/🟦️.ts";
import { PDF17_SQLITE_SCHEMA } from "../../../🪶️sqlite/🧬️schema/🟦️.ts";
import { pdfAnnotationNumberColumns } from "../../../🪶️sqlite/📌️annotation/🔢️number/🟦️.ts";
import { writePdfDate,readPdfDate,writePdfInfo,readPdfInfo } from "../../../🪶️sqlite/📇️metadata/📆️date/🟦️.ts";
import { exportSqliteDatabase,importSqliteDatabase } from "../../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import { writePdfEmbeddedFile,readPdfEmbeddedFile,writePdfOutputIntent,readPdfOutputIntent,writePdfEncryption,readPdfEncryption,writePdfPreferences,readPdfPreferences,writePdfMarkInfo,readPdfMarkInfo } from "../../../🪶️sqlite/📇️metadata/🟦️.ts";

test("PDF metadata preserves files, all encryption kinds, profiles and complete viewer preferences",async()=>{
  const fixture=JSON.parse(await Bun.file(new URL("../../../🪶️sqlite/📇️metadata/🧫️fixtures/🔣️.json",import.meta.url)).text());const out=await PdfProjection.create(PDF17_SQLITE_SCHEMA,{},pdfAnnotationNumberColumns);const files:bigint[]=[];for(const value of fixture.files)files.push(await writePdfEmbeddedFile(out,value));const intents:bigint[]=[];for(const value of fixture.intents)intents.push(await writePdfOutputIntent(out,value));const encryption:bigint[]=[];for(const value of fixture.encryption)encryption.push(await writePdfEncryption(out,value));const preferences=await writePdfPreferences(out,fixture.preferences);const mark=await writePdfMarkInfo(out,fixture.mark);const bytes=await exportSqliteDatabase(await out.finish());const sql=Database.deserialize(bytes);expect(sql.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(sql.query("SELECT algorithm,permissions FROM pdf_encryption ORDER BY id").all()).toEqual([{algorithm:"rc4_40",permissions:-2147483648},{algorithm:"rc4_128",permissions:2147483647},{algorithm:"aes128",permissions:-1},{algorithm:"aes256",permissions:0}]);expect(sql.query("SELECT length(profile) AS size FROM pdf_output_intent ORDER BY id").all()).toEqual([{size:2},{size:0},{size:null}]);const reader=await PdfReader.create(await importSqliteDatabase(bytes),PDF17_SQLITE_SCHEMA,{},pdfAnnotationNumberColumns);for(const[i,key]of files.entries())expect(await readPdfEmbeddedFile(reader,key)).toEqual(fixture.files[i]);for(const[i,key]of intents.entries())expect(await readPdfOutputIntent(reader,key)).toEqual(fixture.intents[i]);for(const[i,key]of encryption.entries())expect(await readPdfEncryption(reader,key)).toEqual(fixture.encryption[i]);expect(await readPdfPreferences(reader,preferences)).toEqual(fixture.preferences);expect(await readPdfMarkInfo(reader,mark)).toEqual(fixture.mark);await reader.finish();sql.close();
},{timeout:30_000});

test("PDF dates and document info preserve all native fields without wire normalization",async()=>{
  const fixture=JSON.parse(await Bun.file(new URL("../../../🪶️sqlite/📇️metadata/📆️date/🧫️fixtures/🔣️.json",import.meta.url)).text());const out=await PdfProjection.create(PDF17_SQLITE_SCHEMA,{},pdfAnnotationNumberColumns);const dates:bigint[]=[];for(const value of fixture.dates)dates.push(await writePdfDate(out,value));const info=await writePdfInfo(out,fixture.info);
  const bytes=await exportSqliteDatabase(await out.finish());const sql=Database.deserialize(bytes);expect(sql.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(sql.query("SELECT year,CAST(month AS TEXT) AS month,offset_minutes FROM pdf_date ORDER BY id LIMIT 1").get()).toEqual({year:-2147483648,month:"4294967295",offset_minutes:-2147483648});
  const reader=await PdfReader.create(await importSqliteDatabase(bytes),PDF17_SQLITE_SCHEMA,{},pdfAnnotationNumberColumns);for(const[index,key]of dates.entries())expect(await readPdfDate(reader,key)).toEqual(fixture.dates[index]);expect(await readPdfInfo(reader,info)).toEqual(fixture.info);await reader.finish();sql.close();
},{timeout:30_000});
