[workspace]
members = [
    "ui/styling/rs",
    "infinite/cavas/vello",
    "mathematical/core",
    "mathematical/graph",
    "mathematical/graph/port",
    "mathematical/graph/port/directed",
    "mathematical/graph/normal/directed",
    "mathematical/graph/normal/undirected",
    "mathematical/graph/port/directed/normal",
    "mathematical/graph/port/directed/dag",
    "mathematical/graph/port/undirected",
    "neural/engine",
    "flow/modules/wasm",
    "flow/modules/math",
    "flow/modules/text",
    "flow/modules/logic",
    "flow/modules/dictionary",
    "flow/modules/list",
    "flow/core",
    "reasoning/mindmap/wires",
    "reasoning/mindmap/rs",
    "gis/map/rs",
    "reasoning/mindmap",
    "puzzle/2d/rs",
    "puzzle/3d/rs",
    "semio/client/lib/rs",
    "semio/client/lib/query",
    "semio/client/bin/store",
    "semio/server/hub",
]

resolver = "2"
