# 🔺️ Sparse owned TIFF directory and sample deltas.
type TiffTagModified { tag: UInt16! values: TiffValues! }
input TiffTagModifiedInput { tag: UInt16! values: TiffValuesInput! }
type TiffTagAdded { tag: UInt16! values: TiffValues! }
input TiffTagAddedInput { tag: UInt16! values: TiffValuesInput! }
type TiffTagsDiff { removed: [UInt16!] modified: [TiffTagModified!] added: [TiffTagAdded!] }
input TiffTagsDiffInput { removed: [UInt16!] modified: [TiffTagModifiedInput!] added: [TiffTagAddedInput!] }
type TiffIfdDiff { entries: TiffTagsDiff blocks: [TiffSampleBlock!] }
input TiffIfdDiffInput { entries: TiffTagsDiffInput blocks: [TiffSampleBlockInput!] }
type TiffIfdModified { index: Int64! diff: TiffIfdDiff! }
input TiffIfdModifiedInput { index: Int64! diff: TiffIfdDiffInput! }
type TiffIfdAdded { index: Int64! ifd: TiffIfd! }
input TiffIfdAddedInput { index: Int64! ifd: TiffIfdInput! }
type TiffIfdsDiff { removed: [Int64!] modified: [TiffIfdModified!] added: [TiffIfdAdded!] }
input TiffIfdsDiffInput { removed: [Int64!] modified: [TiffIfdModifiedInput!] added: [TiffIfdAddedInput!] }
type TiffDiff { ifds: TiffIfdsDiff @state(class: ARTIFACT) }
input TiffDiffInput { ifds: TiffIfdsDiffInput }
