[package]
name = "remodel_camera"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_algebra = { path = "../../../s/kernel/mathematical/algebra/rs", package = "semio-s-kernel-mathematical-algebra" }
mathematical_lie = { path = "../../../s/kernel/mathematical/lie/rs", package = "semio-s-kernel-mathematical-lie" }
mathematical_optimize = { path = "../../../s/kernel/mathematical/optimize/rs", package = "semio-s-kernel-mathematical-optimize" }
