import{readFileSync,writeFileSync,existsSync,mkdirSync}from"node:fs";import{dirname,join}from"node:path";
const root="/Users/ueli/Documents/semio",input=dirname(import.meta.path),writer="✏️s/🔌️plugins/✒️writer/🗿️artifacts/✒️writer/🏅️standards/🔖️1/🪆️subsets/✳️any/✏️editor",plugin="🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/🦀️.rs",diagnostic="🧰️framework/🔨️modules/⚠️diagnostic",value="🧰️framework/🔨️modules/🌱️value/♻️retirement/📦️allocation-return/🦀️.rs",label="🧰️framework/🔨️modules/🖱️ui/🌐️locale/🏷️label/🦀️.rs";
type Pair={path:string,before:string,after:string};const read=(path:string)=>existsSync(join(root,path))?readFileSync(join(root,path),"utf8"):"";const source=(name:string)=>readFileSync(join(input,name),"utf8");
function replace(text:string,before:string,after:string){if(text.split(before).length!==2)throw Error("one exact anchor required: "+before);return text.replace(before,after)}
function save(name:string,pairs:Pair[],mount:boolean){writeFileSync(join(input,name),JSON.stringify(pairs,null,2)+"\n");if(mount){for(const pair of pairs)if(read(pair.path)!==pair.before)throw Error("fresh whole-file guard: "+pair.path);for(const pair of pairs){mkdirSync(dirname(join(root,pair.path)),{recursive:true});writeFileSync(join(root,pair.path),pair.after)}}console.log("[DEBUG] "+JSON.stringify({paths:pairs.length,mounted:mount}));}
const command=process.argv[2];
if(command==="demand"){
 const path=writer+"/🧪️tests/🔬️unit/🦀️.rs",before=read(path);if(before.includes("writer_parent_return_keeps_actual_allocations"))throw Error("demand already mounted");save("demand-guarded-pairs.json",[{path,before,after:before+"\n"+source("writer-law.rs")},{path:writer+"/🧪️tests/🧫️fixtures/📦️parent-return.json",before:read(writer+"/🧪️tests/🧫️fixtures/📦️parent-return.json"),after:source("fixture.json")}],true);
}else if(command==="stage"){
 const pairs:Pair[]=[];const append=(path:string,after:string)=>pairs.push({path,before:read(path),after});
 let text=read(value);text=replace(text,"    fn admit(&self,layout:Layout)",source("return-bytes.rs")+"\n    fn admit(&self,layout:Layout)");append(value,text);const byteLaw="🧰️framework/🔨️modules/🌱️value/♻️retirement/📦️allocation-return/🧪️tests/🦀️.rs";append(byteLaw,read(byteLaw)+"\n"+source("byte-law.rs"));
 text=read(label);text=replace(text,"    /// 📏️ Exact first owned cell capacity required for its physical return.",source("label-return.rs")+"\n    /// 📏️ Exact first owned cell capacity required for its physical return.");append(label,text);
 text=read(plugin);text=replace(text,"        /// 📏️ A caller reserves the first complete allocation before requesting its return.",source("child-return.rs")+"\n        /// 📏️ A caller reserves the first complete allocation before requesting its return.");text=replace(text,"        /// ✏️ A document-operation emission carrying `artifact_mutations` and nothing else.",source("emit-return.rs")+"\n        /// ✏️ A document-operation emission carrying `artifact_mutations` and nothing else.");append(plugin,text);
 append(diagnostic+"/📦️close/🦀️.rs",source("fault-owner.rs"));append(diagnostic+"/📦️close/🧪️tests/🦀️.rs",source("fault-law.rs"));append(diagnostic+"/📦️close/🧫️fixtures/📦️parent-return.json",source("fixture.json"));append(diagnostic+"/🦀️.rs",read(diagnostic+"/🦀️.rs")+'\n#[path="📦️close/🦀️.rs"]\nmod owned_close;\npub use owned_close::{FaultCloseOwner,FaultCloseStep};\n');
 text=read(writer+"/🦀️.rs");text=replace(text,"    pending_completion_rejection: Option<ArtifactToolCompletionRejection<EditorApp<WriterPlayApp>>>,","    pending_completion_rejection: Option<ArtifactToolCompletionRejection<EditorApp<WriterPlayApp>>>,\n    returned_allocations: semio_framework_value::retirement::allocation_return::ParentAllocationReturn<16>,\n    returned_fault: semio_framework_plugin::__diagnostic::FaultCloseOwner,\n    return_refusal: Option<semio_framework_value::ValueError>,");
 text=replace(text,"            pending_completion_rejection: None,","            pending_completion_rejection: None,\n            returned_allocations: semio_framework_value::retirement::allocation_return::ParentAllocationReturn::try_new(MAX_WRITER_COMMAND_RAW_BYTES,MAX_WRITER_COMMAND_RAW_BYTES*16).expect(\"fixed Writer parent allocation authority\"),\n            returned_fault: semio_framework_plugin::__diagnostic::FaultCloseOwner::empty(),\n            return_refusal: None,");
 const start=text.indexOf("        if let Some(rejected) = self.pending_completion_rejection.as_mut() {",text.indexOf("    fn close_step(&mut self,")),end=text.indexOf("        if self.command.is_some() {",start);if(start<0||end<0)throw Error("Writer original close boundary absent");text=text.slice(0,start)+source("writer-close.rs")+text.slice(end);
 text=replace(text,"            && self.pending_completion_rejection.is_none()","            && self.pending_completion_rejection.is_none()\n            && self.returned_allocations.terminal_is_empty()\n            && self.returned_fault.terminal_is_empty()\n            && self.return_refusal.is_none()");append(writer+"/🦀️.rs",text);
 text=read(writer+"/🧪️tests/🔬️unit/🦀️.rs");text=replace(text,"        pending_completion_rejection: None,","        pending_completion_rejection: None,\n        returned_allocations: semio_framework_value::retirement::allocation_return::ParentAllocationReturn::try_new(MAX_WRITER_COMMAND_RAW_BYTES,MAX_WRITER_COMMAND_RAW_BYTES*16).unwrap(),\n        returned_fault: semio_framework_plugin::__diagnostic::FaultCloseOwner::empty(),\n        return_refusal: None,");append(writer+"/🧪️tests/🔬️unit/🦀️.rs",text);
 append(writer+"/🧪️tests/🧬️schema/📦️parent-return.json",source("schema.json"));save("provider-held-pairs.json",pairs,false);
}else if(command==="exhaustive-fault-join"){
 const path=diagnostic+"/📦️close/🦀️.rs";save("exhaustive-known-fault-guarded-pairs.json",[{path,before:read(path),after:source("fault-owner.rs")}],true);
}else if(command==="backpressure-demand"){
 const path=writer+"/🧪️tests/🔬️unit/🦀️.rs",before=read(path);if(before.includes("writer_parent_return_drains_full_parent"))throw Error("full parent demand already mounted");const fixturePath=writer+"/🧪️tests/🧫️fixtures/📦️parent-return.json",schemaPath=writer+"/🧪️tests/🧬️schema/📦️parent-return.json",fixture=JSON.parse(read(fixturePath)),schema=JSON.parse(read(schemaPath));fixture.parentSlots=16;schema.required.push("parentSlots");schema.properties.parentSlots={const:16};save("full-parent-backpressure-demand-guarded-pairs.json",[{path,before,after:before+"\n"+source("backpressure-law.rs")},{path:fixturePath,before:read(fixturePath),after:JSON.stringify(fixture,null,2)+"\n"},{path:schemaPath,before:read(schemaPath),after:JSON.stringify(schema,null,2)+"\n"}],true);
}else if(command==="backpressure-join"){
 const path=writer+"/🦀️.rs",before=read(path),start=before.indexOf("        if !self.returned_allocations.terminal_is_empty(){return match"),end=before.indexOf("\n",start);if(start<0||end<0)throw Error("actual parent close boundary");const close=before.slice(start,end);let after=before.slice(0,start)+before.slice(end+1);after=replace(after,"        if self.return_refusal.is_some(){return InteractiveJobCloseStep::Blocked;}",close.replace("if !self.returned_allocations.terminal_is_empty()", "if !self.returned_allocations.terminal_is_empty()&&self.returned_allocations.next_close_byte_demand()<=maximum_bytes")+"\n        if self.return_refusal.is_some(){return InteractiveJobCloseStep::Blocked;}");save("full-parent-backpressure-guarded-pairs.json",[{path,before,after}],true);
}else if(command==="zst-join"){
 const path=writer+"/🦀️.rs",before=read(path);let after=replace(before,"if $owner.capacity()!=0{return match self.returned_allocations.return_empty_vec", "if writer_empty_vec_backing_bytes(&$owner)!=0{return match self.returned_allocations.return_empty_vec");after=replace(after,"struct WriterCommandToolPayload {","/// 📏️ Zero-sized lanes own no physical backing even when Vec reports its sentinel capacity.\nfn writer_empty_vec_backing_bytes<T>(owner:&Vec<T>)->usize{owner.capacity().checked_mul(std::mem::size_of::<T>()).expect(\"actual Writer empty vector layout\")}\n\nstruct WriterCommandToolPayload {");save("zero-layout-caller-guarded-pairs.json",[{path,before,after}],true);
}else if(command==="byte-neutral"){
 const base="🧰️framework/🔨️modules/🌱️value/♻️retirement/📦️allocation-return",fixturePath=base+"/🧫️fixtures/📦️return.json",schemaPath=base+"/🧬️schema/🔣️.json",lawPath=base+"/🧪️tests/🦀️.rs";
 const fixture=JSON.parse(read(fixturePath));if(fixture.byteWords)throw Error("neutral bytes already mounted");fixture.byteWords=[0,255,1,128];const schema=JSON.parse(read(schemaPath));schema.$defs.Fixture.required.push("byteWords");schema.$defs.Fixture.properties.byteWords={type:"array",minItems:4,maxItems:4,items:{type:"integer",minimum:0,maximum:255}};
 const law=replace(read(lawPath),"let words=serde_json::json!([0,255,1,128]);","let words=fixture[\"byteWords\"].clone();");save("byte-neutral-guarded-pairs.json",[{path:fixturePath,before:read(fixturePath),after:JSON.stringify(fixture,null,2)+"\n"},{path:schemaPath,before:read(schemaPath),after:JSON.stringify(schema,null,2)+"\n"},{path:lawPath,before:read(lawPath),after:law}],true);
}else if(command==="current-capsule"){
 const first=JSON.parse(source("provider-guarded-pairs.json"))as Pair[],neutral=JSON.parse(source("byte-neutral-guarded-pairs.json"))as Pair[],demand=JSON.parse(source("demand-guarded-pairs.json"))as Pair[];const pairs=new Map<string,Pair>();for(const pair of [...first,...neutral,...demand])if(!pairs.has(pair.path))pairs.set(pair.path,{...pair,after:read(pair.path)});save("current-production-readback-pairs.json",[...pairs.values()],false);
}else if(command==="provider")save("provider-guarded-pairs.json",JSON.parse(source("provider-held-pairs.json")),true);else throw Error("exact demand/stage/provider/byte-neutral/current-capsule required");
