//! 📇️ PDF document dates, information, files, intents, encryption and viewer parameters.
use semio_framework_value::{ValueError,ValueRefusalKind};
use crate::standards::v1_7::subsets::base::io::sqlite::snapshot::*;

pub(super) fn write_date(out: &mut Projection<'_, '_>, date: &PdfDate) -> Result<i64,ValueError> { out.insert("pdf_date",&[C::Integer(i64::from(date.year)),C::Integer(i64::from(date.month)),C::Integer(i64::from(date.day)),C::Integer(i64::from(date.hour)),C::Integer(i64::from(date.minute)),C::Integer(i64::from(date.second)),date.offset_minutes.map_or(C::Null,|value|C::Integer(i64::from(value)))]) }
pub(super) fn read_date(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfDate,ValueError> { let row = reader.take("pdf_date",key,8)?; Ok(PdfDate { year:integer(row,1)?,month:integer(row,2)?,day:integer(row,3)?,hour:integer(row,4)?,minute:integer(row,5)?,second:integer(row,6)?,offset_minutes:optional_typed_integer(row,7)? }) }
pub(super) fn write_info(out: &mut Projection<'_, '_>, info: &PdfInfo) -> Result<i64,ValueError> { let creation = info.creation_date.as_ref().map(|value|write_date(out,value)).transpose()?; let modification = info.modification_date.as_ref().map(|value|write_date(out,value)).transpose()?; let extra = cos::write_dictionary(out,&info.extra)?; out.insert("pdf_document_info",&[text_cell(&info.title),text_cell(&info.author),text_cell(&info.subject),text_cell(&info.keywords),text_cell(&info.creator),text_cell(&info.producer),creation.map_or(C::Null,C::Integer),modification.map_or(C::Null,C::Integer),text_cell(&info.trapped),C::Integer(extra)]) }
pub(super) fn read_info(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfInfo,ValueError> { let row = reader.take("pdf_document_info",key,11)?; Ok(PdfInfo { title:reader.optional_text(row,1)?,author:reader.optional_text(row,2)?,subject:reader.optional_text(row,3)?,keywords:reader.optional_text(row,4)?,creator:reader.optional_text(row,5)?,producer:reader.optional_text(row,6)?,creation_date:optional_integer(row,7)?.map(|value|read_date(reader,value)).transpose()?,modification_date:optional_integer(row,8)?.map(|value|read_date(reader,value)).transpose()?,trapped:reader.optional_text(row,9)?,extra:cos::read_dictionary(reader,row.integer(10)?)? }) }

pub(super) fn write_file(out: &mut Projection<'_, '_>, file: &PdfEmbeddedFile) -> Result<i64,ValueError> { let creation = file.creation_date.as_ref().map(|value|write_date(out,value)).transpose()?; let modification = file.modification_date.as_ref().map(|value|write_date(out,value)).transpose()?; out.insert("pdf_embedded_file",&[C::Text(&file.id),C::Text(&file.file_name),text_cell(&file.description),text_cell(&file.mime_type),C::Blob(&file.data),creation.map_or(C::Null,C::Integer),modification.map_or(C::Null,C::Integer),text_cell(&file.relationship),C::Integer(i64::from(file.listed))]) }
pub(super) fn read_file(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfEmbeddedFile,ValueError> { let row = reader.take("pdf_embedded_file",key,10)?; Ok(PdfEmbeddedFile { id:reader.text(row,1)?,file_name:reader.text(row,2)?,description:reader.optional_text(row,3)?,mime_type:reader.optional_text(row,4)?,data:reader.blob(row,5)?,creation_date:optional_integer(row,6)?.map(|value|read_date(reader,value)).transpose()?,modification_date:optional_integer(row,7)?.map(|value|read_date(reader,value)).transpose()?,relationship:reader.optional_text(row,8)?,listed:boolean(row,9)? }) }
pub(super) fn write_intent(out: &mut Projection<'_, '_>, intent: &PdfOutputIntent) -> Result<i64,ValueError> { let profile=intent.profile.as_ref().map(|reference|artifact_reference::write(out,reference).map(C::Integer)).transpose()?.unwrap_or(C::Null); out.insert("pdf_output_intent",&[C::Text(&intent.subtype),C::Text(&intent.condition_identifier),text_cell(&intent.condition),text_cell(&intent.registry_name),text_cell(&intent.info),profile]) }
pub(super) fn read_intent(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfOutputIntent,ValueError> { let row = reader.take("pdf_output_intent",key,7)?; Ok(PdfOutputIntent { subtype:reader.text(row,1)?,condition_identifier:reader.text(row,2)?,condition:reader.optional_text(row,3)?,registry_name:reader.optional_text(row,4)?,info:reader.optional_text(row,5)?,profile:if row.values[6] == V::Null { None } else { Some(artifact_reference::read(reader,row.integer(6)?)?) } }) }
pub(super) fn write_encryption(out: &mut Projection<'_, '_>, encryption: &PdfEncryption) -> Result<i64,ValueError> { let algorithm = match encryption.algorithm { PdfEncryptionAlgorithm::Rc4_40 => "rc4_40",PdfEncryptionAlgorithm::Rc4_128 => "rc4_128",PdfEncryptionAlgorithm::Aes128 => "aes128",PdfEncryptionAlgorithm::Aes256 => "aes256" }; out.insert("pdf_encryption",&[C::Text(algorithm),C::Integer(i64::from(encryption.permissions)),C::Text(&encryption.user_password),text_cell(&encryption.owner_password),C::Integer(i64::from(encryption.encrypt_metadata))]) }
pub(super) fn read_encryption(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfEncryption,ValueError> { let row = reader.take("pdf_encryption",key,6)?; let algorithm = match row.text(1)? { "rc4_40" => PdfEncryptionAlgorithm::Rc4_40,"rc4_128" => PdfEncryptionAlgorithm::Rc4_128,"aes128" => PdfEncryptionAlgorithm::Aes128,"aes256" => PdfEncryptionAlgorithm::Aes256,_ => return Err(ValueError::new(ValueRefusalKind::InvalidValue,"unknown PDF encryption algorithm")) }; Ok(PdfEncryption { algorithm,permissions:integer(row,2)?,user_password:reader.text(row,3)?,owner_password:reader.optional_text(row,4)?,encrypt_metadata:boolean(row,5)? }) }

pub(super) fn page_mode(mode: PdfPageMode) -> &'static str { match mode { PdfPageMode::UseNone => "useNone",PdfPageMode::UseOutlines => "useOutlines",PdfPageMode::UseThumbs => "useThumbs",PdfPageMode::FullScreen => "fullScreen",PdfPageMode::UseOc => "useOc",PdfPageMode::UseAttachments => "useAttachments" } }
pub(super) fn read_page_mode(mode: &str) -> Result<PdfPageMode,ValueError> { Ok(match mode { "useNone" => PdfPageMode::UseNone,"useOutlines" => PdfPageMode::UseOutlines,"useThumbs" => PdfPageMode::UseThumbs,"fullScreen" => PdfPageMode::FullScreen,"useOc" => PdfPageMode::UseOc,"useAttachments" => PdfPageMode::UseAttachments,_ => return Err(ValueError::new(ValueRefusalKind::InvalidValue,"unknown PDF page mode")) }) }
pub(super) fn page_layout(layout: PdfPageLayout) -> &'static str { match layout { PdfPageLayout::SinglePage => "singlePage",PdfPageLayout::OneColumn => "oneColumn",PdfPageLayout::TwoColumnLeft => "twoColumnLeft",PdfPageLayout::TwoColumnRight => "twoColumnRight",PdfPageLayout::TwoPageLeft => "twoPageLeft",PdfPageLayout::TwoPageRight => "twoPageRight" } }
pub(super) fn read_page_layout(layout: &str) -> Result<PdfPageLayout,ValueError> { Ok(match layout { "singlePage" => PdfPageLayout::SinglePage,"oneColumn" => PdfPageLayout::OneColumn,"twoColumnLeft" => PdfPageLayout::TwoColumnLeft,"twoColumnRight" => PdfPageLayout::TwoColumnRight,"twoPageLeft" => PdfPageLayout::TwoPageLeft,"twoPageRight" => PdfPageLayout::TwoPageRight,_ => return Err(ValueError::new(ValueRefusalKind::InvalidValue,"unknown PDF page layout")) }) }
pub(super) fn write_preferences(out: &mut Projection<'_, '_>, preferences: &PdfViewerPreferences) -> Result<i64,ValueError> {
    let extra = cos::write_dictionary(out,&preferences.extra)?;
    let key = out.insert("pdf_viewer_preferences",&[C::Integer(i64::from(preferences.hide_toolbar)),C::Integer(i64::from(preferences.hide_menubar)),C::Integer(i64::from(preferences.hide_window_ui)),C::Integer(i64::from(preferences.fit_window)),C::Integer(i64::from(preferences.center_window)),C::Integer(i64::from(preferences.display_doc_title)),preferences.non_full_screen_page_mode.map_or(C::Null,|value|C::Text(page_mode(value))),text_cell(&preferences.direction),text_cell(&preferences.view_area),text_cell(&preferences.view_clip),text_cell(&preferences.print_area),text_cell(&preferences.print_clip),text_cell(&preferences.print_scaling),text_cell(&preferences.duplex),C::Integer(i64::from(preferences.pick_tray_by_pdf_size)),integer_cell(preferences.num_copies),C::Integer(extra)])?;
    for (ordinal,page) in preferences.print_page_range.iter().enumerate() { out.insert("pdf_print_page_range",&[C::Integer(key),C::Integer(ordinal as i64),C::Integer(i64::from(*page))])?; }
    Ok(key)
}
pub(super) fn read_preferences(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfViewerPreferences,ValueError> {
    let row = reader.take("pdf_viewer_preferences",key,18)?; let mut print_page_range = Vec::new(); for page in reader.children("pdf_print_page_range",1,2,key)? { let page = reader.take("pdf_print_page_range",page.rowid,4)?; print_page_range.push(integer(page,3)?); }
    Ok(PdfViewerPreferences { hide_toolbar:boolean(row,1)?,hide_menubar:boolean(row,2)?,hide_window_ui:boolean(row,3)?,fit_window:boolean(row,4)?,center_window:boolean(row,5)?,display_doc_title:boolean(row,6)?,non_full_screen_page_mode:row.optional_text(7)?.map(read_page_mode).transpose()?,direction:reader.optional_text(row,8)?,view_area:reader.optional_text(row,9)?,view_clip:reader.optional_text(row,10)?,print_area:reader.optional_text(row,11)?,print_clip:reader.optional_text(row,12)?,print_scaling:reader.optional_text(row,13)?,duplex:reader.optional_text(row,14)?,pick_tray_by_pdf_size:boolean(row,15)?,print_page_range,num_copies:optional_typed_integer(row,16)?,extra:cos::read_dictionary(reader,row.integer(17)?)? })
}
pub(super) fn write_mark(out: &mut Projection<'_, '_>, mark: &PdfMarkInfo) -> Result<i64,ValueError> { out.insert("pdf_mark_info",&[C::Integer(i64::from(mark.marked)),C::Integer(i64::from(mark.user_properties)),C::Integer(i64::from(mark.suspects))]) }
pub(super) fn read_mark(reader: &mut Reader<'_, '_, '_>, key: i64) -> Result<PdfMarkInfo,ValueError> { let row = reader.take("pdf_mark_info",key,4)?; Ok(PdfMarkInfo { marked:boolean(row,1)?,user_properties:boolean(row,2)?,suspects:boolean(row,3)? }) }
