[package]
name = "semio-framework-os-kernel-db-storage-neo4j"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "Db storage backend over neo4j"

[lints]
workspace = true
[lib]
name = "db_storage_neo4j"
path = "lib.rs"

[dependencies]
db_core = { path = "../../../core/rs", package = "semio-framework-os-kernel-db-core" }
db_storage = { path = "../../rs", package = "semio-framework-os-kernel-db-storage" }
pack = { path = "../../../../pack/rs", package = "semio-framework-os-kernel-pack" }
neo4rs = "0.8"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
base64 = "0.22.1"
blake3 = "1"

[dev-dependencies]
serde = "1"
