//! 🛫️ Paid flat Equation records preserve the exact authored expression and child addresses.
use semio_framework_value::{ValueError,ValueRefusalKind};
use super::*;
use semio_framework_value::NativeEncodeControl;
fn child_paid(id:&str,target:&store::os_io::ArtifactRef,c:&mut NativeEncodeControl<'_>)->Result<Child,ValueError>{Ok(Child{child_id:c.copy_text(id)?,artifact_id:c.copy_text(&target.artifact_id)?,artifact_kind:c.copy_text(&target.dialect.artifact_kind)?,standard:c.copy_text(&target.dialect.standard)?,subset:c.copy_text(&target.dialect.subset)?})}
fn children(node:&EquationNode)->impl Iterator<Item=&EquationNode>{let(slice,first,second):(&[EquationNode],Option<&EquationNode>,Option<&EquationNode>)=match&node.kind{EquationNodeKind::Add{terms}=>(terms,None,None),EquationNodeKind::Mul{factors}=>(factors,None,None),EquationNodeKind::Pow{base,exponent}=>(&[],Some(base),Some(exponent)),_=>(&[],None,None)};slice.iter().chain(first).chain(second)}
fn frontier<'a>(snapshot:&'a EquationSnapshot,maximum:usize,c:&mut NativeEncodeControl<'_>)->Result<Vec<&'a EquationNode>,ValueError>{
 c.scoped_stage(|c|{c.begin_stage(0)?;let mut rows=[snapshot.graph.nodes.len(),snapshot.graph.edges.len(),snapshot.geometry.points.len()].into_iter().try_fold(6usize,usize::checked_add).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation semantic row count overflow"))?;if rows>maximum{return Err(ValueError::new(ValueRefusalKind::WorkLimit,"Equation semantic row limit exceeded"))}let mut nodes=c.allocate_vec(1)?;nodes.push(&snapshot.equation.expr);let mut index=0;while index<nodes.len(){let node=nodes[index];let child_count=match&node.kind{EquationNodeKind::Add{terms}=>terms.len(),EquationNodeKind::Mul{factors}=>factors.len(),EquationNodeKind::Pow{..}=>2,_=>0};let edges=if matches!(node.kind,EquationNodeKind::Add{..}|EquationNodeKind::Mul{..}){child_count}else{0};rows=rows.checked_add(2).and_then(|rows|rows.checked_add(edges)).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation semantic row count overflow"))?;let minimum=nodes.len().checked_sub(index+1).and_then(|count|count.checked_add(child_count)).and_then(|count|count.checked_mul(2)).and_then(|count|count.checked_add(rows)).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation semantic row count overflow"))?;if minimum>maximum{return Err(ValueError::new(ValueRefusalKind::WorkLimit,"Equation semantic row limit exceeded"))}let required=nodes.len().checked_add(child_count).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"Equation frontier overflow"))?;if required>nodes.capacity(){let extra=required-nodes.capacity();c.charge(extra.checked_mul(std::mem::size_of::<&EquationNode>()).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"Equation frontier allocation overflow"))?)?;nodes.try_reserve_exact(required-nodes.len()).map_err(|_|ValueError::new(ValueRefusalKind::AllocationFailed,"Equation frontier allocation failed"))?;}c.scoped_stage(|c|{c.begin_stage(child_count)?;for child in children(node){nodes.push(child);c.step()?;}Ok::<_,ValueError>(())})?;index+=1;c.step()?;}Ok(nodes)})
}
pub(super) fn project(snapshot:&EquationSnapshot,maximum:usize,c:&mut NativeEncodeControl<'_>)->Result<semio_framework_dsl_record::RecordValue,ValueError>{
 let result=(||->Result<semio_framework_dsl_record::RecordValue,ValueError>{let source=frontier(snapshot,maximum,c)?;c.begin_stage(source.len())?;let mut nodes=c.allocate_vec(source.len())?;let mut next=1u64;
  for value in source{let mut node=Node{label:value.label.0,kind:Kind::Integer,lexeme:None,numer:None,denom:None,name:None,terms:Vec::new(),factors:Vec::new(),base:None,exponent:None};match&value.kind{
   EquationNodeKind::Integer{lexeme}=>node.lexeme=Some(c.copy_text(lexeme)?),
   EquationNodeKind::Rational{numer,denom}=>{node.kind=Kind::Rational;node.numer=Some(c.copy_text(numer)?);node.denom=Some(c.copy_text(denom)?);},
   EquationNodeKind::Symbol{name}=>{node.kind=Kind::Symbol;node.name=Some(c.copy_text(name)?);},
   EquationNodeKind::Add{terms}|EquationNodeKind::Mul{factors:terms}=>{let mut indices=c.allocate_vec(terms.len())?;c.scoped_stage(|c|{c.begin_stage(terms.len())?;for _ in terms{indices.push(next);next=next.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation child identity overflow"))?;c.step()?;}Ok::<_,ValueError>(())})?;if matches!(value.kind,EquationNodeKind::Add{..}){node.kind=Kind::Add;node.terms=indices;}else{node.kind=Kind::Mul;node.factors=indices;}},
   EquationNodeKind::Pow{..}=>{node.kind=Kind::Pow;node.base=Some(next);node.exponent=Some(next.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation child identity overflow"))?);next=next.checked_add(2).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Equation child identity overflow"))?;}
  }nodes.push(node);c.step()?;}
  let value=EquationPackRecord{notation:child_paid(&snapshot.notation.child_id,&snapshot.notation.target,c)?,results:child_paid(&snapshot.results.child_id,&snapshot.results.target,c)?,computed:child_paid(&snapshot.computed.child_id,&snapshot.computed.target,c)?,equation:Expression{next_label:snapshot.equation.next_label,nodes},graph:snapshot.graph.clone(),geometry:snapshot.geometry.clone()};value.__dsl_to_record_controlled(c)
 })();result
}
