// @generated by protobuf-ts 2.8.2 with parameter server_grpc1,generate_dependencies
// @generated from protobuf file "gateway/v1/gateway.proto" (package "semio.gateway.v1", syntax proto3)
// tslint:disable
import { Design } from "../../model/v1/model";
import { LayoutDesignRequest } from "../../assembler/v1/assembler";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service semio.gateway.v1.GatewayService
 */
export const GatewayService = new ServiceType("semio.gateway.v1.GatewayService", [
    { name: "LayoutDesign", options: {}, I: LayoutDesignRequest, O: Design }
]);
