[build]
locked = true
target = "🌐️.html"
dist = "../../../../../../../../../../.🧬semio/🦑️repo/⚡️cache/📺️renderer-modules/🧊️wgpu"
public_url = "/"
filehash = false

[watch]
watch = ["../../🧊️renderer", "../../🌐️browser-worker", "../../🧵️frame-job", "../../🎠️runtime", "../../🏠️os-host", "../../📐️surface-lane", "../../📮️runtime-mailbox-core", "../../📸️render-snapshot", "../../🪢️kernel-seam", "../../🎬️renderer-boot", "../../🚀️browser-boot", "../../🚚️browser-frame-transport", "../../🔌️browser-interactive-job-port", "../../⏱️turn-budget", "../../🫀️boot-liveness", "../../🗄️wasm-module-cache", "../../🎞️frame-worker", "../../📇️interactive-job-registry", "../../../../../../../../../🔨️modules/🖱️ui/🧱️elements/🕸️Diagram", "../../../../../../../../../🔨️modules/🖱️ui/🧱️elements/🔌️Ports", "🟦️typescript", "🌐️.html", "../../../../../../🧑‍💻dev/🔌️plugin-modules"]

[serve]
addresses = ["127.0.0.1"]
open = false

[[proxy]]
backend = "http://127.0.0.1:6141/osm/"

[[proxy]]
backend = "http://127.0.0.1:6141/vt/"

[[proxy]]
backend = "http://127.0.0.1:6141/mesh/"

[[proxy]]
backend = "http://127.0.0.1:6141/infinite-assets/"

[[proxy]]
backend = "http://127.0.0.1:6141/cad-assets/"

[[hooks]]
stage = "pre_build"
command = "bun"
command_arguments = ["../../../../../../../../🦑️repo/🔨️modules/📚️library/⚡️caching/🦀️cargo/📜️script.ts", "native", "cargo", "metadata", "--manifest", "🧰️framework/🛍️products/💻️os/🔨️modules/📺️renderer/🧑‍🎨engine/🎯️targets/🧊️wgpu/📦️packages/🦀️rust/Cargo.toml"]
