[build]
target = "🌐️.html"
dist = "../../../../../../../../../../.🦑️repo/⚡️cache/📺️renderer-modules/🧊️wgpu"
public_url = "/"
filehash = false

[watch]
watch = ["../../🧊️renderer", "../../🎬️renderer-boot", "../../🚀️browser-boot", "../../🚚️browser-frame-transport", "../../🔌️browser-interactive-job-port", "../../🎞️frame-worker", "../../📇️interactive-job-registry", "../../../../../../../../../🔨️modules/🖱️ui/🧱️elements/🕸️Diagram", "../../../../../../../../../🔨️modules/🖱️ui/🧱️elements/🔌️Ports", "🟦️typescript", "🌐️.html", "../../../../../../🧑‍💻dev/🔌️plugin-modules"]

[serve]
addresses = ["127.0.0.1"]
open = false

[[proxy]]
backend = "http://127.0.0.1:6141/osm/"

[[proxy]]
backend = "http://127.0.0.1:6141/vt/"

[[proxy]]
backend = "http://127.0.0.1:6141/mesh/"

[[proxy]]
backend = "http://127.0.0.1:6141/infinite-fixture/"

[[proxy]]
backend = "http://127.0.0.1:6141/cad-fixture/"
