[package]
name = "semio-rust-coordinate-oracle"
version = "0.0.0"
edition = "2021"

[workspace]

[[bin]]
name = "oracle"
path = "🦀️.rs"

[dependencies]
serde_json = "1"
syn = { version = "2", features = ["full", "visit", "parsing"] }
