//! 📐️ Controlled authored CAD layers, blocks and every entity variant.
use super::{SemioCadSnapshot,CadLayer,CadBlock,CadEntityRecord,CadEntity,SemioPoint2,STDIO_SEMIOCAD_DOCUMENT_SCHEMA};
use crate::standards::v1::subsets::base::schema::snapshot::native_decoding as native;
use semio_framework_value::native_decoding::NativeDecodeControl;
use store::sqlite_snapshot::{SqliteSnapshotControl,SqliteDatabaseLimits};
pub(super) fn decode(payload:&store::os_io::IoPayload,control:&mut SqliteSnapshotControl<'_>)->Result<SemioCadSnapshot,String>{native::decode(payload,STDIO_SEMIOCAD_DOCUMENT_SCHEMA,control,binary,document)}
fn f64(reader:&mut store::ByteReader<'_>)->Result<f64,String>{reader.read_f64_le().map_err(|error|error.to_string())}
fn point(reader:&mut store::ByteReader<'_>)->Result<SemioPoint2,String>{Ok(SemioPoint2{x:f64(reader)?,y:f64(reader)?})}
fn boolean(value:u8)->Result<bool,String>{match value{0=>Ok(false),1=>Ok(true),_=>Err("invalid Semio native CAD boolean".into())}}
fn entity_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<CadEntity,String>{
 native::entities(entities,1,limits)?;Ok(match reader.read_u8().map_err(|error|error.to_string())?{
 0=>CadEntity::Line{a:point(reader)?,b:point(reader)?},1=>CadEntity::Arc{center:point(reader)?,radius:f64(reader)?,start_angle:f64(reader)?,end_angle:f64(reader)?},2=>CadEntity::Circle{center:point(reader)?,radius:f64(reader)?},3=>CadEntity::Ellipse{center:point(reader)?,major_axis_end:point(reader)?,ratio:f64(reader)?,start_param:f64(reader)?,end_param:f64(reader)?},
 4=>{let vertices=native::binary_list(reader,control,limits,entities,|reader,_,_|point(reader))?;let closed=boolean(reader.read_u8().map_err(|error|error.to_string())?)?;CadEntity::Polyline{vertices,closed}},
 5=>CadEntity::Text{position:point(reader)?,height:f64(reader)?,rotation:f64(reader)?,content:native::text(reader,control)?},6=>CadEntity::Insert{block_name:native::text(reader,control)?,insertion_point:point(reader)?,scale:point(reader)?,rotation:f64(reader)?},7=>CadEntity::Solid{p1:point(reader)?,p2:point(reader)?,p3:point(reader)?,p4:point(reader)?},8=>CadEntity::Dimension{def_point:point(reader)?,text_position:point(reader)?,measurement:f64(reader)?,text:native::text(reader,control)?},_=>return Err("invalid Semio native CAD entity".into())})
}
fn record_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<CadEntityRecord,String>{let handle=native::text(reader,control)?;let layer=native::text(reader,control)?;let entity=entity_binary(reader,control,limits,entities)?;Ok(CadEntityRecord{handle,layer,entity})}
pub(crate) fn binary(body:&[u8],control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioCadSnapshot,String>{
 let mut entities=0;native::entities(&mut entities,1,limits)?;let mut reader=store::ByteReader::new(body);if reader.read_u8().map_err(|error|error.to_string())?!=1{return Err("unsupported Semio CAD native format".into())}let schema=native::text(&mut reader,control)?;
 let layers=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,_|{let name=native::text(reader,control)?;let bits=reader.read_varint_u64().map_err(|error|error.to_string())?;let color_index=bits as i32;if color_index as u64!=bits{return Err("invalid Semio native signed32 layer color".into())}let line_type=native::text(reader,control)?;let visible=boolean(reader.read_u8().map_err(|error|error.to_string())?)?;Ok(CadLayer{name,color_index,line_type,visible})})?;
 let blocks=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let name=native::text(reader,control)?;let base_point=point(reader)?;let entities=native::binary_list(reader,control,limits,entities,|reader,control,entities|record_binary(reader,control,limits,entities))?;Ok(CadBlock{name,base_point,entities})})?;
 let entities=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|record_binary(reader,control,limits,entities))?;if reader.remaining()!=0{return Err("Semio CAD native trailing bytes".into())}Ok(SemioCadSnapshot{schema,layers,blocks,entities})
}
fn point_text(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioPoint2,String>{let[x,y]=native::record(value,control)?;Ok(SemioPoint2{x:native::float(x,control)?,y:native::float(y,control)?})}
fn bool_text(value:&str)->Result<bool,String>{match value{"0"=>Ok(false),"1"=>Ok(true),_=>Err("invalid Semio native CAD boolean".into())}}
fn entity_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<CadEntity,String>{
 native::entities(entities,1,limits)?;let(tag,value)=value.split_at_checked(1).ok_or("Semio native CAD entity tag missing")?;Ok(match tag{
 "L"=>{let[a,b]=native::record(value,control)?;CadEntity::Line{a:point_text(a,control)?,b:point_text(b,control)?}},
 "A"=>{let[center,radius,start_angle,end_angle]=native::record(value,control)?;CadEntity::Arc{center:point_text(center,control)?,radius:native::float(radius,control)?,start_angle:native::float(start_angle,control)?,end_angle:native::float(end_angle,control)?}},
 "C"=>{let[center,radius]=native::record(value,control)?;CadEntity::Circle{center:point_text(center,control)?,radius:native::float(radius,control)?}},
 "E"=>{let[center,major_axis_end,ratio,start_param,end_param]=native::record(value,control)?;CadEntity::Ellipse{center:point_text(center,control)?,major_axis_end:point_text(major_axis_end,control)?,ratio:native::float(ratio,control)?,start_param:native::float(start_param,control)?,end_param:native::float(end_param,control)?}},
 "P"=>{let[vertices,closed]=native::record(value,control)?;CadEntity::Polyline{vertices:native::text_list(vertices,control,limits,entities,|value,control,_|point_text(value,control))?,closed:bool_text(closed)?}},
 "T"=>{let[position,height,rotation,content]=native::record(value,control)?;CadEntity::Text{position:point_text(position,control)?,height:native::float(height,control)?,rotation:native::float(rotation,control)?,content:native::hex_text(content,control)?}},
 "I"=>{let[block_name,insertion_point,scale,rotation]=native::record(value,control)?;CadEntity::Insert{block_name:native::hex_text(block_name,control)?,insertion_point:point_text(insertion_point,control)?,scale:point_text(scale,control)?,rotation:native::float(rotation,control)?}},
 "S"=>{let[p1,p2,p3,p4]=native::record(value,control)?;CadEntity::Solid{p1:point_text(p1,control)?,p2:point_text(p2,control)?,p3:point_text(p3,control)?,p4:point_text(p4,control)?}},
 "D"=>{let[def_point,text_position,measurement,text]=native::record(value,control)?;CadEntity::Dimension{def_point:point_text(def_point,control)?,text_position:point_text(text_position,control)?,measurement:native::float(measurement,control)?,text:native::hex_text(text,control)?}},_=>return Err("invalid Semio native CAD entity".into())})
}
fn record_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<CadEntityRecord,String>{let[handle,layer,value]=native::record(value,control)?;let handle=native::hex_text(handle,control)?;let layer=native::hex_text(layer,control)?;let entity=entity_text(value,control,limits,entities)?;Ok(CadEntityRecord{handle,layer,entity})}
pub(crate) fn document(body:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioCadSnapshot,String>{
 let mut entities=0;native::entities(&mut entities,1,limits)?;let fields=native::fields(body,["schema","layers","blocks","entities"],control)?;let schema=native::hex_text(fields[0].ok_or("Semio CAD native schema missing")?,control)?;
 let layers=native::text_list(fields[1].unwrap_or("[]"),control,limits,&mut entities,|value,control,_|{let[name,color_index,line_type,visible]=native::record(value,control)?;let name=native::hex_text(name,control)?;let color_index=control.scoped_stage(|control|{control.begin_stage(color_index.len())?;for _ in color_index.bytes(){control.step()?;}color_index.parse::<i32>().map_err(|_|"invalid Semio native signed32 layer color".to_string())})?;let line_type=native::hex_text(line_type,control)?;let visible=bool_text(visible)?;Ok(CadLayer{name,color_index,line_type,visible})})?;
 let blocks=native::text_list(fields[2].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[name,base_point,records]=native::record(value,control)?;let name=native::hex_text(name,control)?;let base_point=point_text(base_point,control)?;let entities=native::text_list(records,control,limits,entities,|value,control,entities|record_text(value,control,limits,entities))?;Ok(CadBlock{name,base_point,entities})})?;
 let entities=native::text_list(fields[3].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|record_text(value,control,limits,entities))?;Ok(SemioCadSnapshot{schema,layers,blocks,entities})
}
