[package]
name = "dag-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[package.metadata.component]
package = "semio:dag"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph_port_directed_dag = { path = "../../rs" }
semio-framework-plugin = { path = "../../../../../../../framework/plugin/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

