/** 🎟️ Original staged custody changes preserve semantic metadata zero and native source currency. */
import{test,expect}from"bun:test";import Ajv from"ajv";import{Database}from"bun:sqlite";import{readFileSync}from"node:fs";
test("original staged source metadata charges only actual source bytes",async()=>{
 const law=await Bun.file(new URL("../🧫️fixtures/🔣️.json",import.meta.url)).json(),schema=await Bun.file(new URL("../🧬️schema/🔣️.json",import.meta.url)).json();expect(new Ajv({strict:true}).compile(schema)(law)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE metadata(stage TEXT PRIMARY KEY,copy INTEGER)");for(const row of law.metadata)db.query("INSERT INTO metadata VALUES(?,?)").run(row.stage,row.copy);expect(db.query("SELECT sum(copy) AS copied FROM metadata").get()).toEqual({copied:0});const ranges=db.query("WITH RECURSIVE ranges(start,length) AS (SELECT 0,min(?1,?2) UNION ALL SELECT start+length,min(?1-start-length,?2) FROM ranges WHERE start+length<?1) SELECT length FROM ranges").all(law.sourceBytes,law.grant[1])as{length:number}[];expect(ranges.map(row=>row.length)).toEqual(law.ranges);expect(ranges.reduce((total,row)=>total+row.length,0)).toBe(law.sourceBytes);}finally{db.close()}
 console.log("[DEBUG] Ajv/SQLite original staged metadata8 phases copy0, actual8192 source4096/4096, staticfault26 only, unchanged original five-axis policy");
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8"),payload=readFileSync(new URL("../../../../../♻️retirement/📄️payload/🦀️.rs",import.meta.url),"utf8");
 expect(source).toContain("let copied_bytes=0;");expect(source).toContain("let child=grant;");expect(source).toContain("WorkerJobSession::<J>::admission_demand()");expect(source).toContain("remaining.min(grant.maximum_copy_bytes)");expect(source).toContain("copied_bytes:bytes,");expect(source).not.toContain("bytes+cursor");expect(payload.slice(payload.indexOf("impl<J> WorkerJobSource"),payload.indexOf("impl<J> Drop for WorkerJobSource"))).not.toContain("copied_bytes:size_of::<bool>()");
});
test("original staged owner retirement changes metadata without payload copies",async()=>{
 const law=await Bun.file(new URL("../🧫️fixtures/🔣️.json",import.meta.url)).json(),schema=await Bun.file(new URL("../🧬️schema/🔣️.json",import.meta.url)).json();expect(new Ajv({strict:true}).compile(schema)(law)).toBe(true);const db=new Database(":memory:");try{expect(db.query("SELECT ?1 AS copied").get(law.retirementMetadataCopy)).toEqual({copied:0});}finally{db.close()}console.log("[DEBUG] Ajv/SQLite original staged owner params/cancel/ledger/vector/session/node retirement metadata copy0, native release remains independent");
 const source=readFileSync(new URL("../../../../../🦀️.rs",import.meta.url),"utf8"),payload=readFileSync(new URL("../../../../../♻️retirement/📄️payload/🦀️.rs",import.meta.url),"utf8");for(const[start,end]of[["fn original_admission_page_demands(","fn close_original_admission_page("],["fn original_params_demands(","fn close_original_worker_params("],["fn terminal_authority_demands(","fn close_terminal_worker_authority("],["fn original_session_arc_demands(","fn close_original_session_arc("],["fn release_retirement_slot(","impl<J: InteractiveJob + 'static> Drop"]])expect(source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)))).not.toMatch(/copy(?:ied)?_bytes\s*[:=]\s*size_of/);expect(payload).not.toContain("copied_bytes:size_of::<bool>()");
});
