[package]
name = "fem_core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "../../../../../../../✏️s/🔌️plugin/🏗️fem/🔨️module/🫀️core/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
mathematical_algebra = { path = "../../../../../../../🧰️framework/🔨️module/🧮️math/➕️algebra/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-algebra" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
spade = "2.15.1"
thiserror = "2.0.12"
