[package]
name = "semio-s-imperative"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.semio]
role = "s-module"

[features]
default = []

[lib]
crate-type = ["rlib"]
path = "🦀️.rs"

[dependencies]
neural_engine = { path = "../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🧠️neural/⚙️engine/📦️packages/🦀️rust", package = "semio-framework-os-kernel-neural-engine" }
serde.workspace = true
serde_json.workspace = true
semio-framework-os-kernel = { path = "../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
semio-framework = { path = "../../../../../🧰️framework/📦️packages/🦀️rust", package = "semio-framework" }
semio-framework-value-derive = { path = "../../../../../🧰️framework/🔨️modules/🌱️value/✨️derive/📦️packages/🦀️rust", package = "semio-framework-value-derive" }
imperative_extension_sdk = { path = "../../🧩️extension_sdk/📦️packages/🦀️rust", package = "semio-s-imperative-extension-sdk" }

[dev-dependencies]
semio-framework-async-macros = { path = "../../../../../🧰️framework/🔨️modules/⏳️async/✨️macros/📦️packages/🦀️rust" }
