[package]
name = "semio-s-imperative"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.semio]
role = "s-module"

[features]
default = ["linked-modules"]
linked-modules = [
    "imperative_module_core",
    "imperative_module_text",
    "imperative_module_math",
    "imperative_module_logic",
    "imperative_module_control",
]

[lib]
crate-type = ["rlib"]
path = "📦️glue.rs"

[dependencies]
neural_engine = { path = "../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🧠️neural/⚙️engine/📦️packages/🦀️rust", package = "semio-framework-os-kernel-neural-engine" }
serde.workspace = true
serde_json.workspace = true
semio-framework-os-kernel = { path = "../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
semio-framework-core = { path = "../../../../../🧰️framework/📦️packages/🦀️rust", package = "semio-framework-core" }
imperative_extension_sdk = { path = "../../🧩️extension_sdk/📦️packages/🦀️rust", package = "semio-s-imperative-extension-sdk" }
imperative_module_core = { path = "../../../../../✏️s/🔌️plugins/📜️imperative/🧩️extensions/🫀️core/📦️packages/🦀️rust", package = "semio-s-plugin-imperative-core", optional = true }
imperative_module_text = { path = "../../../../../✏️s/🔌️plugins/📜️imperative/🧩️extensions/📝️text/📦️packages/🦀️rust", package = "semio-s-plugin-imperative-text", optional = true }
imperative_module_math = { path = "../../../../../✏️s/🔌️plugins/📜️imperative/🧩️extensions/🧮️math/📦️packages/🦀️rust", package = "semio-s-plugin-imperative-math", optional = true }
imperative_module_logic = { path = "../../../../../✏️s/🔌️plugins/📜️imperative/🧩️extensions/🧠️logic/📦️packages/🦀️rust", package = "semio-s-plugin-imperative-logic", optional = true }
imperative_module_control = { path = "../../../../../✏️s/🔌️plugins/📜️imperative/🧩️extensions/🎮️control/📦️packages/🦀️rust", package = "semio-s-plugin-imperative-control", optional = true }
