/** 📽️ Actual slide shapes and shared DocBlock content independently inspected by SQLite. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import f from "../🧫️fixtures/🔣️.json";
import type {SemioPresentationSnapshot,PlaceholderKind,SlideShape} from "../../../../🧬️schema/📸️snapshot/🟦️.ts";
import {SEMIO_PRESENTATION_SQLITE_SCHEMA,semioPresentationSnapshotToSqliteDatabase,semioPresentationSnapshotFromSqliteDatabase} from "../🟦️.ts";
import {binary64,exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const frame=()=>({origin:{x:binary64(1),y:binary64(-2)},width:binary64(3),height:binary64(4)}),placeholderKinds:PlaceholderKind[]=[{kind:"title"},{kind:"subtitle"},{kind:"body"},{kind:"footer"},{kind:"slideNumber"},{kind:"dateTime"},{kind:"other",value:""}];
const shapes:SlideShape[]=[{shapeKind:"textBox",frame:frame(),blocks:[{kind:"image",image_id:"external-image",alt:"",width:binary64(-0),height:null},{kind:"heading",level:255,style_id:"external-style",runs:[{text:f.text,style:{bold:true,italic:false,underline:true,size:binary64(2),font:"",color:null,link:""}}]}]},{shapeKind:"picture",frame:frame(),image:{assetId:f.picture.assetId,mime:f.picture.mime,bytes:f.picture.bytes.slice()}},{shapeKind:"table",frame:frame(),rows:[{cells:[]},{cells:[{blocks:[]},{blocks:[{kind:"code",language:null,text:f.text}]}]}]},...placeholderKinds.map(kind=>({shapeKind:"placeholder" as const,frame:frame(),kind}))];
const input:SemioPresentationSnapshot={schema:f.schema,masters:[{id:f.masterId,shapes}],layouts:[{id:f.layoutId,masterId:f.masterId,shapes:[]}],slides:[{id:f.slideId,layoutId:f.layoutId,shapes:[],notes:[{kind:"quote",blocks:[{kind:"pageBreak"}]}]},{id:"empty",layoutId:null,shapes:[],notes:[]}]};
test("Semio Presentation independent master joins and edited picture bytes",async()=>{expect(SEMIO_PRESENTATION_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());const db=Database.deserialize(await exportSqliteDatabase(await semioPresentationSnapshotToSqliteDatabase(input)));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(f.query).all()).toHaveLength(1);expect(await semioPresentationSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_presentation_picture SET bytes=X'ff00'").run();const edited=structuredClone(input),picture=edited.masters[0]!.shapes[1]!;if(picture.shapeKind!=="picture")throw Error("fixture picture");picture.image.bytes=[255,0];expect(await semioPresentationSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(edited);}finally{db.close();}});
test("quick::Semio Presentation exact frame/run/image words and content ownership",async()=>{for(const hex of f.float64Bits){const s=structuredClone(input),word={bits:BigInt("0x"+hex)},shape=s.masters[0]!.shapes[0]!;shape.frame={origin:{x:word,y:word},width:word,height:word};if(shape.shapeKind!=="textBox")throw Error("fixture text box");const image=shape.blocks[0]!,heading=shape.blocks[1]!;if(image.kind!=="image"||heading.kind!=="heading")throw Error("fixture blocks");image.width=word;image.height=word;heading.runs[0]!.style.size=word;const db=Database.deserialize(await exportSqliteDatabase(await semioPresentationSnapshotToSqliteDatabase(s)));try{expect(await semioPresentationSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}}const d=await semioPresentationSnapshotToSqliteDatabase(input);for(const mutate of[(x:any)=>x.tables[2].rows[0].values[4]=999n,(x:any)=>x.tables[4].rows[0].values[2]=1n,(x:any)=>x.tables[5].rows[0].values[1]=999n,(x:any)=>x.tables[10].rows[0].values[2]="unexpected",(x:any)=>x.tables[3].rows[1].values[5]=x.tables[3].rows[0].values[5]]){const x=structuredClone(d);mutate(x);await expect(semioPresentationSnapshotFromSqliteDatabase(x)).rejects.toThrow();}await expect(semioPresentationSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();await expect(semioPresentationSnapshotFromSqliteDatabase(d,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();c.abort();await expect(semioPresentationSnapshotFromSqliteDatabase(d,{signal:c.signal})).rejects.toThrow();},30000);

test("Semio Presentation native construction frontier independently preserves other placeholder names and shape order",async()=>{const count=f.nativeAdmission.collectionItems,s:SemioPresentationSnapshot={schema:f.schema,masters:[{id:"master",shapes:Array.from({length:count},()=>({shapeKind:"placeholder",frame:frame(),kind:{kind:"other",value:""}}))}],layouts:[],slides:[]};const db=Database.deserialize(await exportSqliteDatabase(await semioPresentationSnapshotToSqliteDatabase(s)));try{expect(db.query("SELECT count(*) AS n FROM semio_presentation_shape").get()).toEqual({n:count});expect(db.query("SELECT count(*) AS n FROM semio_presentation_placeholder").get()).toEqual({n:count});expect(db.query("SELECT semio_presentation_placeholder.kind,other FROM semio_presentation_placeholder JOIN semio_presentation_shape ON semio_presentation_shape.id=semio_presentation_placeholder.id WHERE ordinal=?").get(f.nativeAdmission.cancelAfter)).toEqual({kind:"other",other:""});expect(await semioPresentationSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}});

import completeSemanticContract from "../🧫️fixtures/🎛️semantic.json";
import{independentSqliteExtent as completeIndependentExtent}from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts";
test("Semio Presentation Native matched full and metadata empty independently preserve all complete cells",async()=>{
 for(const item of completeSemanticContract.cases){const source=structuredClone(item.sourceSnapshot)as unknown as SemioPresentationSnapshot;const hydrate=(value:unknown):unknown=>Array.isArray(value)?value.map(hydrate):value!==null&&typeof value==="object"?("bits"in value?{bits:String((value as {bits:string}).bits).length===8?Number.parseInt(String((value as {bits:string}).bits),16):BigInt("0x"+String((value as {bits:string}).bits))}:Object.fromEntries(Object.entries(value).map(([key,item])=>[key,hydrate(item)]))):value;Object.assign(source,hydrate(source));const database=await semioPresentationSnapshotToSqliteDatabase(source),bytes=await exportSqliteDatabase(database);expect(completeIndependentExtent(bytes)).toEqual({rows:item.rows,valueBytes:item.valueBytes,schemaBytes:completeSemanticContract.schemaBytes,tableWidths:completeSemanticContract.tableWidths});const limits={maxRows:item.rows,maxValueBytes:item.valueBytes,maxSchemaBytes:completeSemanticContract.schemaBytes,maxTables:26,maxColumns:18};expect(await semioPresentationSnapshotToSqliteDatabase(source,limits)).toEqual(database);expect(await semioPresentationSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes),limits)).toEqual(source);
 for(const short of[{...limits,maxRows:item.rows-1},{...limits,maxValueBytes:item.valueBytes-1},{...limits,maxSchemaBytes:limits.maxSchemaBytes-1},{...limits,maxTables:25},{...limits,maxColumns:17}]){await expect(semioPresentationSnapshotToSqliteDatabase(source,short)).rejects.toThrow();await expect(semioPresentationSnapshotFromSqliteDatabase(database,short)).rejects.toThrow();}
 }console.log("[DEBUG] Semio Presentation independently measured Native matched full and empty roles through all5 copied limits");
});
