syntax = "proto3";
package stdio.gltf.mutation.scene;
import "🏠️default-scene/🔗️bind/🛰️.proto";
import "📷️node-camera/🔗️bind/🛰️.proto";
import "🌿️node-child/🔗️bind/🛰️.proto";
import "🏗️node-mesh/🔗️bind/🛰️.proto";
import "🩻️node-skin/🔗️bind/🛰️.proto";
import "🌲️scene-root/🔗️bind/🛰️.proto";
import "🌳️node/🧩️change-extensions/🛰️.proto";
import "🌳️node/📝️change-extras/🛰️.proto";
import "🌳️node/⚖️change-weights/🛰️.proto";
import "🌳️node/🏷️rename/🛰️.proto";
import "🎬️scene/🧩️change-extensions/🛰️.proto";
import "🎬️scene/📝️change-extras/🛰️.proto";
import "🎬️scene/🏷️rename/🛰️.proto";
import "🌳️node/🌱️create/🛰️.proto";
import "🎬️scene/🌱️create/🛰️.proto";
import "🌳️node/🗑️delete/🛰️.proto";
import "🎬️scene/🗑️delete/🛰️.proto";
import "🌳️node/🚚️move/🛰️.proto";
import "🌿️node-child/🚚️move/🛰️.proto";
import "🎬️scene/🚚️move/🛰️.proto";
import "🌲️scene-root/🚚️move/🛰️.proto";
import "🌿️node-child/🔀️reorder/🛰️.proto";
import "🌳️node/🔀️reorder/🛰️.proto";
import "🌲️scene-root/🔀️reorder/🛰️.proto";
import "🎬️scene/🔀️reorder/🛰️.proto";
import "🌳️node/🌿️reparent/🛰️.proto";
import "🌳️node/📐️transform/🛰️.proto";
import "🏠️default-scene/✂️unbind/🛰️.proto";
import "📷️node-camera/✂️unbind/🛰️.proto";
import "🌿️node-child/✂️unbind/🛰️.proto";
import "🏗️node-mesh/✂️unbind/🛰️.proto";
import "🩻️node-skin/✂️unbind/🛰️.proto";
import "🌲️scene-root/✂️unbind/🛰️.proto";

message GltfSceneMutation {
  oneof mutation {
    GltfBindDefaultSceneMutationV1 bind_default_scene = 1;
    GltfBindNodeCameraPayloadV1 bind_node_camera = 2;
    GltfBindNodeChildPayloadV1 bind_node_child = 3;
    GltfBindNodeMeshPayloadV1 bind_node_mesh = 4;
    GltfBindNodeSkinPayloadV1 bind_node_skin = 5;
    GltfBindSceneRootNodePayloadV1 bind_scene_root_node = 6;
    GltfChangeNodeExtensionDataPayloadV1 change_node_extension_data = 7;
    GltfChangeNodeExtraDataPresenceV1 change_node_extra_data = 8;
    GltfChangeNodeMorphWeightsPayloadV1 change_node_morph_weights = 9;
    GltfChangeNodeNameMutationV1 change_node_name = 10;
    GltfChangeSceneExtensionDataPayloadV1 change_scene_extension_data = 11;
    GltfChangeSceneExtraDataPayloadV1 change_scene_extra_data = 12;
    GltfChangeSceneNamePayloadV1 change_scene_name = 13;
    GltfCreateNodePayloadV1 create_node = 14;
    GltfCreateScenePayloadV1 create_scene = 15;
    GltfDeleteNodePayloadV1 delete_node = 16;
    GltfDeleteScenePayloadV1 delete_scene = 17;
    GltfMoveNodePayloadV1 move_node = 18;
    GltfMoveNodeChildPayloadV1 move_node_child = 19;
    GltfMoveScenePayloadV1 move_scene = 20;
    GltfMoveSceneRootNodePayloadV1 move_scene_root_node = 21;
    GltfReorderNodeChildrenPayloadV1 reorder_node_children = 22;
    GltfReorderNodesPayloadV1 reorder_nodes = 23;
    GltfReorderSceneRootNodesPayloadV1 reorder_scene_root_nodes = 24;
    GltfReorderScenesPayloadV1 reorder_scenes = 25;
    GltfReparentNodePayloadV1 move_node_parent = 26;
    GltfTransformNodePayloadV1 change_node_transform = 27;
    GltfUnbindDefaultSceneMutationV1 unbind_default_scene = 28;
    GltfUnbindNodeCameraPayloadV1 unbind_node_camera = 29;
    GltfUnbindNodeChildPayloadV1 unbind_node_child = 30;
    GltfUnbindNodeMeshPayloadV1 unbind_node_mesh = 31;
    GltfUnbindNodeSkinPayloadV1 unbind_node_skin = 32;
    GltfUnbindSceneRootNodePayloadV1 unbind_scene_root_node = 33;
  }
}
