/** ✒️ Shared Writer ownership and independent SQL edits. */
import { Database } from "bun:sqlite";
import { expect,test } from "bun:test";
import fixture from "../🧫️fixtures/🔣️.json";
import { writerSnapshotToSqliteDatabase,writerSnapshotFromSqliteDatabase,validateWriterSnapshotSqliteDialect } from "../🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
test("Writer child reference components are independent owned text rather than a joined URI",async()=>{for(const document of fixture.referenceCases){const snapshot={...fixture.snapshot,document};const database=await writerSnapshotToSqliteDatabase(snapshot),oracle=Database.deserialize(await exportSqliteDatabase(database));try{expect(oracle.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(await writerSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(snapshot);expect(await validateWriterSnapshotSqliteDialect(snapshot,fixture.dialect,database)).toEqual([]);}finally{oracle.close();}}});
test("Writer fixed child identity and authored text remain separately queryable",async()=>{const database=await writerSnapshotToSqliteDatabase(fixture.snapshot);expect(await writerSnapshotFromSqliteDatabase(database)).toEqual(fixture.snapshot);expect(await validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database)).toEqual([]);const db=Database.deserialize(await exportSqliteDatabase(database));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(fixture.query).get()).toEqual(fixture.result);db.query("UPDATE writer_document SET text=?").run(fixture.editedText);expect(await writerSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).toEqual({...fixture.snapshot,text:fixture.editedText});}finally{db.close();}});
test("Writer actual SQL ownership edits refuse missing child and mismatched fixed parent",async()=>{for(const sql of["DELETE FROM writer_document_child","UPDATE writer_document_child SET document_id=2","INSERT INTO writer_document_child SELECT 2,document_id,child_id,target_artifact_id,target_artifact_kind,target_standard,target_subset FROM writer_document_child"]){const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{db.run("PRAGMA ignore_check_constraints=ON");db.run(sql);await expect(writerSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow();}finally{db.close();}}});

test("Writer neutral exact coordinates, fixed identity, request bounds and callback abort are controlled",async()=>{const database=await writerSnapshotToSqliteDatabase(fixture.snapshot);for(const dialect of fixture.invalidDialects)await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,dialect,database)).rejects.toThrow("subset");const db=Database.deserialize(await exportSqliteDatabase(database));try{db.query("UPDATE writer_document SET schema=?").run("foreign schema");await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow("identity");}finally{db.close();}for(const options of[{maxRows:fixture.limitedRows},{maxValueBytes:fixture.limitedValueBytes}]){await expect(writerSnapshotToSqliteDatabase(fixture.snapshot,options)).rejects.toThrow("limit");await expect(writerSnapshotFromSqliteDatabase(database,options)).rejects.toThrow("limit");}for(const operation of["project","reconstruct","guard"]){const controller=new AbortController();const options={signal:controller.signal,onProgress:()=>controller.abort()};const promise=operation==="project"?writerSnapshotToSqliteDatabase(fixture.snapshot,options):operation==="reconstruct"?writerSnapshotFromSqliteDatabase(database,options):validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database,options);await expect(promise).rejects.toMatchObject({kind:"canceled"});}});

test("Writer independent signed surrogate renumbering preserves the complete owned state",async()=>{const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{for(const sql of fixture.renumberSql)db.run(sql);expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);const database=await importSqliteDatabase(new Uint8Array(db.serialize()));expect(await writerSnapshotFromSqliteDatabase(database)).toEqual(fixture.snapshot);expect(await validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database)).toEqual([]);}finally{db.close();}});
test("Writer independent semantic field edits refuse a mismatched original snapshot",async()=>{for(const sql of fixture.mismatchSql){const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{db.run(sql);expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow("identity");}finally{db.close();}}});
import {parseWriterSnapshot} from "../../../../🧬️schema/📸️snapshot/🟦️.ts";
import {Buffer} from "node:buffer";
test("writer canonical native UTF8 fields refuse independently proven lossy UTF16 states",()=>{for(const units of fixture.invalidUtf16CodeUnits){const invalid=String.fromCharCode(...units);expect(Buffer.from(invalid,"utf8").toString("utf8")).not.toBe(invalid);const source={...fixture.snapshot,text:invalid};expect(()=>parseWriterSnapshot(source)).toThrow();}});

test("Writer declared owner corpus pins complete authored SQL tables independently",async()=>{
 const {default:law}=await import("../🧫️fixtures/🧩️declaration/🔣️.json");
 
 const {default:Ajv}=await import("ajv");
 
 const db=new Database(":memory:");
 try{db.exec(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());expect(db.query("SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name").all()).toEqual(law.tables.map(name=>({name})));expect(db.query("PRAGMA integrity_check").all()).toEqual([{integrity_check:"ok"}]);expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);}finally{db.close();}
 console.log("[DEBUG] Writer closed declaration owner "+law.dialect.artifactKind+" schema="+law.schema+" complete_authored_SQL_tables="+law.tables.length);
});

test("Writer original authored examples keep every reference component and full owner",async()=>{
 const {default:law}=await import("../🧫️fixtures/🔗️authored-examples/🔣️.json");const {default:Ajv}=await import("ajv");
 for(const entry of law.examples){const snapshot=parseWriterSnapshot(entry.snapshot);const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(snapshot)));try{expect(db.query("PRAGMA integrity_check").all()).toEqual([{integrity_check:"ok"}]);expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query("SELECT child_id,target_artifact_id,target_artifact_kind,target_standard,target_subset FROM writer_document_child").get()).toEqual({child_id:snapshot.document.childId,target_artifact_id:snapshot.document.target.artifactId,target_artifact_kind:snapshot.document.target.dialect.artifactKind,target_standard:snapshot.document.target.dialect.standard,target_subset:snapshot.document.target.dialect.subset});expect(await writerSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).toEqual(entry.snapshot);}finally{db.close();}}
 console.log("[DEBUG] Writer authored examples complete owners=2 current literal reference fields=4 independently queryable");
});

test("Writer hub tail commits retain the complete current transition and content address",async()=>{
 const {default:law}=await import("../../../../🧫️fixtures/🔁️hub-tail-after-check-in/🧭️current-checkpoints/🔣️.json");
 
 const {default:captured}=await import("../../../../🧫️fixtures/🔁️hub-tail-after-check-in/🔣️.json");
 const {default:Ajv}=await import("ajv");
 const {historyTransitionId}=await import("../../../../../../../../../../../../../🧰️framework/🔨️modules/📡️replication/🟦️.ts");
 const {blake3}=await import("@noble/hashes/blake3.js");
 const protocolSchema={definitions:{Transition:{type:"object",additionalProperties:false,required:["checkpointId","parentId","changeId","mutationIds","description","savedAt","authors","message","timestamp","lineId"],properties:{checkpointId:{type:"string"},parentId:{type:["string","null"]},changeId:{type:"string"},mutationIds:{type:"array",items:{type:"string"}},description:{type:["string","null"]},savedAt:{type:"string"},authors:{type:"array",items:{type:"object",additionalProperties:false,required:["id","name","avatar"],properties:{id:{type:"string"},name:{type:"string"},avatar:{type:["string","null"]}}},message:{type:["string","null"]},timestamp:{type:"string"},lineId:{type:["string","null"]}}}}};
 const validate=new Ajv({strict:true}).compile({$ref:"#/definitions/Transition",definitions:protocolSchema.definitions});
 for(const row of law.checkpoints){expect(validate(row.transition)).toBe(true);const t=row.transition,bytes:number[]=[];const u=(out:number[],n:number)=>{let value=BigInt(n);do{const part=Number(value&127n);value>>=7n;out.push(part|(value?128:0));}while(value);};const s=(value:string)=>{const text=Buffer.from(value,"utf8");u(bytes,text.length);bytes.push(...text);};const o=(value:string|null)=>{bytes.push(value===null?0:1);if(value!==null)s(value);};
 u(bytes,2);s(t.checkpointId);o(t.parentId);s(t.changeId);u(bytes,t.mutationIds.length);for(const id of t.mutationIds)s(id);o(t.description);s(t.savedAt);u(bytes,t.authors.length);for(const author of t.authors){s(author.id);s(author.name);o(author.avatar);}o(t.message);s(t.timestamp);o(t.lineId);
 const material:number[]=[];u(material,row.clock.actor);u(material,row.clock.physical_ms);u(material,row.clock.logical);u(material,bytes.length);material.push(...bytes);const expectedId="transition-"+Buffer.from(blake3(Uint8Array.from(material))).toString("hex").slice(0,16);expect(historyTransitionId(row.clock,bytes)).toBe(expectedId);
 console.log("[DEBUG] Writer current checkpoint producer index="+row.index+" bytes="+bytes.length+" id="+expectedId+" payload="+JSON.stringify(bytes));
 expect(captured.envelopes[row.index]!.diff.payload).toEqual(bytes);expect(captured.envelopes[row.index]!.mutation_id).toBe(expectedId);
 }
});
