/** procedural facet WASM facades */
export * as procedural2d_schema from "../../🗿️artifacts/🌀️procedural2d/🧬️schema/🟦️component.ts";
export * as procedural2d_snapshot_schema from "../../🗿️artifacts/🌀️procedural2d/📸️snapshot/🧬️schema/🟦️component.ts";
export * as procedural2d_diff from "../../🗿️artifacts/🌀️procedural2d/🔺️diff/🟦️component.ts";
export * as procedural2d_diff_schema from "../../🗿️artifacts/🌀️procedural2d/🔺️diff/🧬️schema/🟦️component.ts";
export * as procedural2d_dsl from "../../🗿️artifacts/🌀️procedural2d/🗣️dsl/🟦️component.ts";
export * as procedural2d_pack from "../../🗿️artifacts/🌀️procedural2d/📸️snapshot/🎒️pack/🟦️component.ts";
export * as procedural2d_op from "../../🗿️artifacts/🌀️procedural2d/🔧️op/🟦️component.ts";
export * as procedural2d_spr from "../../🗿️artifacts/🌀️procedural2d/📡️spr/🟦️component.ts";
export * as procedural3d_schema from "../../🗿️artifacts/🧊️procedural3d/🧬️schema/🟦️component.ts";
export * as procedural3d_snapshot_schema from "../../🗿️artifacts/🧊️procedural3d/📸️snapshot/🧬️schema/🟦️component.ts";
export * as procedural3d_diff from "../../🗿️artifacts/🧊️procedural3d/🔺️diff/🟦️component.ts";
export * as procedural3d_diff_schema from "../../🗿️artifacts/🧊️procedural3d/🔺️diff/🧬️schema/🟦️component.ts";
export * as procedural3d_dsl from "../../🗿️artifacts/🧊️procedural3d/🗣️dsl/🟦️component.ts";
export * as procedural3d_pack from "../../🗿️artifacts/🧊️procedural3d/📸️snapshot/🎒️pack/🟦️component.ts";
export * as procedural3d_op from "../../🗿️artifacts/🧊️procedural3d/🔧️op/🟦️component.ts";
export * as procedural3d_spr from "../../🗿️artifacts/🧊️procedural3d/📡️spr/🟦️component.ts";
