//! 🧪️ The actual Worker callback receives the original narrow turn and returns its unique physical receipt before semantic access.
use super::*;
struct OriginalTurnProbe{source:[u8;17],output:[u8;17],copied:bool,closing:bool}
impl InteractiveJob for OriginalTurnProbe{
 fn step<'a>(&'a mut self,cx:&mut StepContext<'_>)->Result<Option<JobOutcomeBorrow<'a>>,ValueError>{if self.copied{return JobOutcomeBorrow::admit_complete(cx,None,None)}let grant=cx.retained_grant();if grant.maximum_items==0||grant.maximum_copy_bytes<17||grant.maximum_depth==0{return Ok(None)}self.output.copy_from_slice(&self.source);self.copied=true;cx.consume_retained(RetainedCloneProgress{copied_items:1,copied_bytes:17,..Default::default()})?;Ok(None)}
 fn borrow_outcome<'a>(&'a self,descriptor:&'a JobOutcomeDescriptor)->Result<JobOutcomeView<'a>,ValueError>{descriptor.complete(None,None)}
 fn begin_close(&mut self){self.closing=true;}
 fn close_step(&mut self,_:RetainedCloneGrant)->InteractiveJobCloseStep{InteractiveJobCloseStep::Complete{progress:Default::default()}}
 fn terminal_is_empty(&self)->bool{self.closing}
 fn next_close_copy_byte_demand(&self)->Result<usize,ValueError>{Ok(0)}
 fn next_close_capacity_byte_demand(&self,_:usize)->Result<usize,ValueError>{Ok(0)}
 fn next_close_release_byte_demand(&self)->Result<usize,ValueError>{Ok(0)}
 fn next_close_depth_demand(&self)->Result<usize,ValueError>{Ok(1)}
}
fn observe<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
fn policy(row:&serde_json::Value)->RetainedCloneGrant{RetainedCloneGrant{maximum_items:row[0].as_u64().unwrap()as usize,maximum_copy_bytes:row[1].as_u64().unwrap()as usize,maximum_capacity_bytes:row[2].as_u64().unwrap()as usize,maximum_release_bytes:row[3].as_u64().unwrap()as usize,maximum_depth:row[4].as_u64().unwrap()as usize}}
#[test]
fn original_worker_turn_receipt_preserves_narrow_callback_and_exactly_once_recipient(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let original=policy(&law["issued"]);let creation=policy(&law["policy"]);assert_eq!(original_worker_turn_grant(creation,original),policy(&law["effective"]));let cancel=root_cancel_token();let params=BatchJobParams{operation:OperationId(81291),generation:Generation(3),cancel:cancel.clone(),config:BatchDriveConfig{retained:creation,site:"original-worker-turn",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000000},now_us:default_now_us};let mut session=admit_original_fixture_owner!(MountedWorkerJobSession,OriginalTurnProbe{source:[7;17],output:[0;17],copied:false,closing:false},params).unwrap_or_else(|_|panic!("original external session admission"));
 for denied in[RetainedCloneGrant{maximum_items:0,..original},RetainedCloneGrant{maximum_depth:0,..original}]{let(poll,heap)=observe(||session.pump_one_for_interactive_turn(denied).unwrap_or_else(|_|panic!("original denied opportunity preserves idle owner")));assert_eq!(poll,WorkerJobPoll::Idle);assert_eq!(heap,(0,0));assert!(session.take_checked_out_retained_step_receipt().is_none());assert!(session.checked_out_job().is_none());assert_eq!(session.poll(),WorkerJobPoll::Idle);}
 let(poll,heap)=observe(||session.pump_one_for_interactive_turn(original).unwrap_or_else(|_|panic!("original caller callback")));assert_eq!(poll,WorkerJobPoll::Outcome);assert_eq!(heap,(0,0));let address=session.checked_out_job().unwrap()as*const _;assert!(session.checked_out_outcome().is_err());assert_eq!(session.acknowledge_checked_out_outcome(original).progress(),Default::default());let(grant_view,progress_view)=session.checked_out_retained_step_receipt().unwrap();assert_eq!(*grant_view,original);assert_eq!(*progress_view,RetainedCloneProgress{copied_items:1,copied_bytes:17,..Default::default()});let view_pointer=progress_view as*const RetainedCloneProgress;assert_eq!(session.checked_out_retained_step_receipt().unwrap().1 as*const RetainedCloneProgress,view_pointer);let((effective,progress),heap)=observe(||session.take_checked_out_retained_step_receipt().unwrap());assert_eq!(heap,(0,0));assert_eq!(effective,original);assert_eq!(progress,RetainedCloneProgress{copied_items:1,copied_bytes:17,..Default::default()});assert!(progress.fits(original));assert!(session.take_checked_out_retained_step_receipt().is_none());assert!(session.checked_out_outcome().unwrap().is_none());assert_eq!(session.checked_out_job().unwrap()as*const _,address);assert_eq!(session.checked_out_job().unwrap().output,[7;17]);session.resume().unwrap();
 let(poll,heap)=observe(||session.pump_one_for_interactive_turn(original).unwrap_or_else(|_|panic!("original semantic callback")));assert_eq!(poll,WorkerJobPoll::Terminal);assert_eq!(heap,(0,0));assert!(session.checked_out_outcome().is_err());let(grant,receipt)=session.take_checked_out_retained_step_receipt().unwrap();assert_eq!(grant,original);assert_eq!(receipt,RetainedCloneProgress{copied_items:1,..Default::default()});assert!(matches!(session.checked_out_outcome().unwrap(),Some(JobOutcomeView::Complete{state:None,output:None,..})));assert_eq!(session.checked_out_job().unwrap()as*const _,address);for _ in 0..2{session.acknowledge_checked_out_outcome(original);}session.begin_close();let mut turns=0;while !session.terminal_is_empty(){if session.has_original_cancel_alias_witness(&cancel).unwrap_or(false){session.return_original_cancel_alias_step(&cancel,creation).unwrap();}else{session.close_step(creation);}turns+=1;assert!(turns<100000);}let(_,heap)=observe(||drop(session));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Worker callback sameOwner={address:p} incoming17copy all5intersect nativeCopy17 heap0 uniqueReceipt then separateSemantic metadataCopy0 terminalDrop0 closeTurns={turns}");
}

#[test]
fn original_batch_receipt_and_mutable_job_fence_preserve_none_semantics_and_original_authority(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let original=policy(&law["issued"]);let creation=policy(&law["policy"]);let cancel=root_cancel_token();let params=BatchJobParams{operation:OperationId(81292),generation:Generation(4),cancel:cancel.clone(),config:BatchDriveConfig{retained:creation,site:"original-batch-turn",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000000},now_us:default_now_us};let mut session=admit_original_fixture_owner!(BatchJobSession,OriginalTurnProbe{source:[7;17],output:[0;17],copied:false,closing:false},params).unwrap_or_else(|_|panic!("original external batch session admission"));let(poll,heap)=observe(||session.step(original).unwrap());assert_eq!(poll,WorkerJobPoll::Outcome);assert_eq!(heap,(0,0));assert!(session.checkout_outcome());assert!(session.checked_out_job_mut().is_none());assert!(session.checked_out_outcome().is_err());let(grant,receipt)=session.take_checked_out_retained_step_receipt().unwrap();assert_eq!(grant,original);assert_eq!(receipt,RetainedCloneProgress{copied_items:1,copied_bytes:17,..Default::default()});assert!(session.take_checked_out_retained_step_receipt().is_none());assert!(session.checked_out_outcome().unwrap().is_none());assert_eq!(session.checked_out_job_mut().unwrap().output,[7;17]);session.resume().unwrap();assert_eq!(session.step(original).unwrap(),WorkerJobPoll::Terminal);assert!(session.checkout_outcome());assert!(session.checked_out_job_mut().is_none());let(_,receipt)=session.take_checked_out_retained_step_receipt().unwrap();assert_eq!(receipt,RetainedCloneProgress{copied_items:1,..Default::default()});assert!(session.checked_out_job_mut().is_none());let denied=session.acknowledge_outcome(RetainedCloneGrant{maximum_items:0,..original});assert_eq!(denied.progress(),Default::default());assert!(session.checked_out_job_mut().is_none());for _ in 0..2{let step=session.acknowledge_outcome(RetainedCloneGrant{maximum_copy_bytes:0,..original});assert_eq!(step.progress(),RetainedCloneProgress{copied_items:1,..Default::default()});}assert!(session.checked_out_job_mut().is_some());session.begin_close();let mut turns=0;while !session.terminal_is_empty(){if session.has_original_cancel_alias_witness(&cancel).unwrap_or(false){session.return_original_cancel_alias_step(&cancel,creation).unwrap();}else{session.close_step(creation);}turns+=1;assert!(turns<100000);}let(_,heap)=observe(||drop(session));assert_eq!(heap,(0,0));eprintln!("[DEBUG] actual original Batch callback17 physicalreceipt once evenNone then separate descriptorACKmetadata0 beforemutablejob originalgrant stableauthority terminalDrop0");
}

#[test]
fn original_worker_admission_preserves_sources_metadata_zero_and_exact_native_birth(){
 let _slots=worker_session_slots_shared();let law:serde_json::Value=serde_json::from_str(include_str!("../../🚪️admission/🧫️fixtures/🔣️.json")).unwrap();let grant=policy(&law["cases"][0]["grant"]);let cancel=root_cancel_token();let mut job=Some(OriginalTurnProbe{source:[7;17],output:[0;17],copied:false,closing:false});let mut params=Some(BatchJobParams{operation:OperationId(81293),generation:Generation(5),cancel:cancel.clone(),config:BatchDriveConfig{retained:grant,site:"original-admission",stage:InteractiveStage::InteractiveStep,fuel_per_step:1,step_budget_us:1000000},now_us:default_now_us});let demand=WorkerJobSession::<OriginalTurnProbe>::admission_demand();assert_eq!(demand.copy_bytes,b"job-session.terminal-fault".len());let pointer=job.as_ref().unwrap()as*const _;let mut recipient=RetainedCloneProgress::default();
 for denied in[RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant},RetainedCloneGrant{maximum_capacity_bytes:0,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(mut control,heap)=observe(||WorkerJobAdmissionContext::new(OperationId(81293),Generation(5),StepBudget::new(1,u64::MAX,denied),default_now_us,&mut recipient).unwrap());assert_eq!(heap,(0,0));let(result,heap)=observe(||WorkerJobSession::try_admit_owned(&mut job,&mut params,&mut control).unwrap());assert!(result.is_none());assert_eq!(heap,(0,0));drop(control);assert_eq!(recipient,Default::default());assert_eq!(job.as_ref().unwrap()as*const _,pointer);assert_eq!(params.as_ref().unwrap().operation,OperationId(81293));}
 let mut control=WorkerJobAdmissionContext::new(OperationId(81293),Generation(5),StepBudget::new(1,u64::MAX,grant),default_now_us,&mut recipient).unwrap();let((mut session,progress),heap)=observe(||WorkerJobSession::try_admit_owned(&mut job,&mut params,&mut control).unwrap().unwrap());drop(control);assert_eq!(recipient,progress);assert_eq!(progress.copied_items,1);assert_eq!(progress.copied_bytes,b"job-session.terminal-fault".len()+size_of::<OriginalTurnProbe>());assert_eq!(heap,(progress.retained_capacity_bytes,0));assert!(progress.fits(grant));assert!(job.is_none()&&params.is_none());let born=heap.0;let mut released=0;session.begin_close();let mut turns=0;while !session.terminal_is_empty(){let(step,heap)=observe(||if session.has_original_cancel_alias_witness(&cancel).unwrap_or(false){WorkerJobCloseStep::Pending{progress:session.return_original_cancel_alias_step(&cancel,grant).unwrap().unwrap().progress()}}else{session.close_step(grant)});assert!(step.progress().fits(grant));assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));released+=heap.1;turns+=1;assert!(turns<100000);}assert_eq!(released,born);assert_eq!(observe(||drop(session)).1,(0,0));eprintln!("[DEBUG] actual original Worker admission metadataCopy0 faultSourceCopy25 nativeBorn={born} deniedSameSources=true terminalRelease={released} turns={turns}");
}

#[test]
fn original_context_cancel_alias_preserves_same_root_paid_metadata_zero_and_return_witness(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../../../🎟️context/🛑️cancel/🤝️alias/🧫️fixtures/🔣️.json")).unwrap();let turn:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let creation=policy(&turn["policy"]);let(cancel,birth)=CancelToken::admit_root(creation).unwrap().unwrap();assert_eq!(birth.copied_bytes,0);let(mut authority,birth)=JobPayloadAuthority::admit(OperationId(81294),Generation(6),creation).unwrap().unwrap();assert_eq!(birth.copied_bytes,0);let pointer=&cancel as*const CancelToken;let mut sequence=0;
 for row in law["cases"].as_array().unwrap(){let grant=policy(&row["grant"]);let mut recipient=RetainedCloneProgress::default();let mut cx=StepContext::with_payload_authority(OperationId(81294),Generation(6),StepBudget::new(1,u64::MAX,grant),&cancel,default_now_us,&mut sequence,&mut recipient,&authority).unwrap();assert_eq!(cx.original_cancel_token()as*const _,pointer);let(alias,heap)=observe(||cx.admit_original_cancel_alias().unwrap());assert_eq!(heap,(0,0));assert_eq!(alias.is_some(),row["admitted"].as_bool().unwrap());let expected=RetainedCloneProgress{copied_items:row["receipt"][0].as_u64().unwrap()as usize,..Default::default()};assert_eq!(cx.retained_progress(),expected);assert!(expected.fits(grant));assert_eq!(cx.original_cancel_token()as*const _,pointer);drop(cx);if let Some(alias)=alias{let mut owner=semio_framework_async::CancelTokenRetirement::from_token(alias);assert!(owner.is_original_alias_witness(&cancel));let(step,heap)=observe(||owner.return_alias_step(&cancel,grant).unwrap());assert_eq!(step.progress(),RetainedCloneProgress{copied_items:1,..Default::default()});assert_eq!(heap,(0,0));assert!(owner.terminal_is_empty());assert_eq!(observe(||drop(owner)).1,(0,0));}}
 authority.close_step(creation).unwrap();assert!(authority.terminal_is_empty());let mut cancel=semio_framework_async::CancelTokenRetirement::from_token(cancel);let mut turns=0;while !cancel.terminal_is_empty(){cancel.close_step(creation).unwrap();turns+=1;assert!(turns<10);}eprintln!("[DEBUG] actual original context alias sameRoot=true deniedNoAlias=true metadataCopy0 admittedItem1 heap0 matchingRootReturnItem1 heap0");
}
