syntax = "proto3";
package semio.s.cad.cad.mutation;

// 🧬️ CadMutation schema.

message CadMutation {
  // @state artifact
  string schema = 1;
  // @state artifact
  string id = 2;
  // @state artifact
  repeated CadObject objects = 3;
  // @state artifact
  repeated CadObject building_objects = 4;
  // @state artifact
  repeated CadObject energy_objects = 5;
  // @state artifact
  repeated CadObject structure_classic_objects = 6;
  // @state artifact
  map<string, CadReferenceList> references_by_model_definition_id = 7;
  // @state artifact
  repeated CadNode nodes = 8;
  // @state artifact
  optional CadGeometry shape_geometry = 9;
  // @state artifact
  optional CadGeometry building_geometry = 10;
  // @state artifact
  optional CadGeometry energy_geometry = 11;
  // @state artifact
  optional CadGeometry structure_classic_geometry = 12;
  // @state artifact
  string active_model_definition_id = 13;
}

message CadObject { string id = 1; }
message CadNode { string id = 1; }
message CadReferenceList { repeated string values = 1; }
message CadGeometry { string anchors_json = 1; }
message CadCamera { double zoom = 1; }
message CadComponentSelection { string mode = 1; }
message CadDislocateOptions { bool move_enabled = 1; bool rotate_enabled = 2; }
