// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaType } from "./MediaType";
import type { OsMediaCapability } from "./OsMediaCapability";
import type { OsMediaFormat } from "./OsMediaFormat";

/**
 * 🗂️ An app-declared OS resource kind (e.g. a 3D mesh format, a raster format) — the manifest-level
 * counterpart to `AppBuilder::artifact_kind(...)` (`framework/plugin/rs`), letting `framework/product/os/core`
 * build its artifact catalog from `AppDefinition.artifact_kinds` at plugin registration time instead of
 * hardcoding a per-app match on kind-id strings. Absorbs the manifest-level media-kind fields
 * (`media_type`/`schema`/`export_formats`/`import_formats`, matching `MediaKindDescriptor` below field-for-field)
 * so one spec carries both the OS-catalog presentation shape and the `MediaType` a wire actually negotiates
 * — see `crate::media_types_compatible`. `OsArtifactDescriptor` (`framework/product/os/core`) threads
 * `media_type` through so registry lookups return it alongside the rest of the descriptor.
 */
export type ArtifactKindSpec = { id: string, name: string, sourceFormat: string, componentKind: string, dimension: string, mediaCapability: OsMediaCapability, mediaType: MediaType, schema: string, exportFormats: Array<OsMediaFormat>, importFormats: Array<OsMediaFormat>, };
