// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 🌳️ Closes the informal `FRAMEWORK_CATEGORY_*`/`*_TAB_ID` string-constant convention that used to
 * live in the renderer: every panel tab is either a framework-predefined kind (compile-time
 * exhaustive) or an app-declared custom tab (open id, still required to be unique/non-empty,
 * validated at construction by `AppBuilder`).
 */
export type PanelTabKind = { "kind": "workbenchCategory" } | { "kind": "displayCategory" } | { "kind": "detailsCategory" } | { "kind": "settingsCategory" } | { "kind": "displayWindows" } | { "kind": "displayLayout" } | { "kind": "settingsGeneral" } | { "kind": "settingsTheme" } | { "kind": "app", "id": string };
