syntax = "proto3";
package semio.s_stdio_wav.diff;
message WavDiffFmt { uint32 audio_format = 1; uint32 channels = 2; uint32 sample_rate = 3; uint32 byte_rate = 4; uint32 block_align = 5; uint32 bits_per_sample = 6; bytes ext = 7; }
message WavDiffData { string kind = 1; repeated double value = 2; }
message WavDiffRiffChunk { string fourcc = 1; bytes data = 2; uint32 pad_byte = 3; }
message WavDiffChunkRef { string kind = 1; uint64 value = 2; }
message WavDiffRiffChunks { repeated WavDiffRiffChunk values = 1; }
message WavDiffChunkOrder { repeated WavDiffChunkRef values = 1; }
message WavDiffSplice { uint64 index = 1; uint64 remove = 2; WavDiffData insert = 3; }
message WavDiff {
  optional WavDiffFmt fmt = 1;
  optional WavDiffData data = 2;
  optional uint32 fmt_pad_byte = 3;
  optional uint32 data_pad_byte = 4;
  optional WavDiffRiffChunks other_chunks = 5;
  optional WavDiffChunkOrder chunk_order = 6;
  repeated WavDiffSplice data_splices = 7;
}
