[package]
name = "process-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:process"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "process3d"
app = "process3d-play"
aliases = ["process 3d"]
ports = { react = 6022, wgpu = 6122 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "../../../../../../../✏️s/🔌️plugin/🏭️process/🛂️manifest/🗿️artifact/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
process_3d = { path = "../../../../../../../✏️s/🔌️plugin/🏭️process/🎛️app/🧊️3d/⚡️implementation/🦀️rust", package = "semio-s-app-process-3d" }
process_3d_engine = { path = "../../../../../../../✏️s/🔌️plugin/🏭️process/🎛️app/🧊️3d/🔨️module/⚙️engine/⚡️implementation/🦀️rust", package = "semio-s-app-process-3d-engine" }
process_3d_ui = { path = "../../../../../../../✏️s/🔌️plugin/🏭️process/🎛️app/🧊️3d/🔨️module/🖱️ui/⚡️implementation/🦀️rust", package = "semio-s-app-process-3d-ui" }
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️product/💻️os/🔨️module/🔌️plugin/⚡️implementation/🦀️rust", features = ["component-guest"], package = "semio-framework-plugin" }
semio-framework-os = { path = "../../../../../../../🧰️framework/🛍️product/💻️os/⚡️implementation/🦀️rust", package = "semio-framework-os" }
serde_json = "1.0.140"
