# 🧬️ PDF 1.7/VT direct mutation aggregate.
input PdfVtMutationInput {
  insertEncryptionDictionary: InsertEncryptionDictionaryMutationInput
  removeEncryptionDictionary: RemoveEncryptionDictionaryMutationInput
  setOutputIntent: SetOutputIntentMutationInput
  removeOutputIntent: RemoveOutputIntentMutationInput
  setTrimBox: SetTrimBoxMutationInput
  removeTrimBox: RemoveTrimBoxMutationInput
  embedFontFile: EmbedFontFileMutationInput
  removeFontFile: RemoveFontFileMutationInput
  insertJavascriptAction: InsertJavascriptActionMutationInput
  removeJavascriptAction: RemoveJavascriptActionMutationInput
  insertLaunchAction: InsertLaunchActionMutationInput
  removeLaunchAction: RemoveLaunchActionMutationInput
  insertMediaAnnotation: InsertMediaAnnotationMutationInput
  removeMediaAnnotation: RemoveMediaAnnotationMutationInput
  setDpartRoot: SetDpartRootMutationInput
  removeDpartRoot: RemoveDpartRootMutationInput
  setDpartMetadata: SetDpartMetadataMutationInput
  removeDpartMetadata: RemoveDpartMetadataMutationInput
}
