//! 🪵️ Handwritten timber members, characteristic actions, connections and connection actions.
use super::En1995Snapshot;
use crate::{TimberMember,TimberConnection,CharacteristicAction,ConnectionAction,MemberRole,SupportType,document::AnnexChoice};
use std::collections::BTreeMap;
use store::{ArtifactSqliteSnapshot,sqlite_snapshot::{SnapshotEncoding,SqliteDatabase,SqliteSnapshotControl,SqliteSnapshotPhase,validate_sqlite_database_schema,artifact::{Cell,FloatColumn,FloatRow,NativeEncodingBound,Projection,insert_ieee754,reconstruct_text}}};

const MEMBER_FLOATS:&[FloatColumn]=&[FloatColumn::Binary64(10),FloatColumn::Binary64(11),FloatColumn::Binary64(12),FloatColumn::Binary64(13),FloatColumn::Binary64(14),FloatColumn::Binary64(15),FloatColumn::Binary64(16),FloatColumn::Binary64(17),FloatColumn::Binary64(18),FloatColumn::Binary64(19),FloatColumn::Binary64(20),FloatColumn::Binary64(21),FloatColumn::Binary64(22),FloatColumn::Binary64(23),FloatColumn::Binary64(24),FloatColumn::Binary64(25),FloatColumn::Binary64(26),FloatColumn::Binary64(27),FloatColumn::Binary64(28),FloatColumn::Binary64(29),FloatColumn::Binary64(30)];
const MEMBER_ACTION_FLOATS:&[FloatColumn]=&[FloatColumn::Binary64(7),FloatColumn::Binary64(8),FloatColumn::Binary64(9),FloatColumn::Binary64(10),FloatColumn::Binary64(11),FloatColumn::Binary64(12),FloatColumn::Binary64(13)];
const CONNECTION_FLOATS:&[FloatColumn]=&[FloatColumn::Binary64(9),FloatColumn::Binary64(12),FloatColumn::Binary64(13),FloatColumn::Binary64(14),FloatColumn::Binary64(15),FloatColumn::Binary64(16),FloatColumn::Binary64(18),FloatColumn::Binary64(20)];
const CONNECTION_ACTION_FLOATS:&[FloatColumn]=&[FloatColumn::Binary64(6)];
type Entities<'a>=BTreeMap<i64,FloatRow<'a>>;

fn annex(value:AnnexChoice)-> &'static str{match value{AnnexChoice::En=>"En",AnnexChoice::De=>"De"}}
fn read_annex(value:&str)->Result<AnnexChoice,String>{match value{"En"=>Ok(AnnexChoice::En),"De"=>Ok(AnnexChoice::De),_=>Err("EN1995 unsupported annex".into())}}
fn role(value:MemberRole)-> &'static str{match value{MemberRole::Beam=>"beam",MemberRole::Column=>"column",MemberRole::Floor=>"floor",MemberRole::Bridge=>"bridge"}}
fn read_role(value:&str)->Result<MemberRole,String>{match value{"beam"=>Ok(MemberRole::Beam),"column"=>Ok(MemberRole::Column),"floor"=>Ok(MemberRole::Floor),"bridge"=>Ok(MemberRole::Bridge),_=>Err("EN1995 unsupported member role".into())}}
fn support(value:SupportType)-> &'static str{match value{SupportType::SimplySupported=>"simplySupported",SupportType::Cantilever=>"cantilever",SupportType::ContinuousTwoSpan=>"continuousTwoSpan"}}
fn read_support(value:&str)->Result<SupportType,String>{match value{"simplySupported"=>Ok(SupportType::SimplySupported),"cantilever"=>Ok(SupportType::Cantilever),"continuousTwoSpan"=>Ok(SupportType::ContinuousTwoSpan),_=>Err("EN1995 unsupported support".into())}}
fn checkpoint(control:&mut SqliteSnapshotControl<'_>,position:usize,total:usize)->Result<(),String>{if position%256==0{control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,position,total)?;}Ok(())}
fn entities<'a>(database:&'a SqliteDatabase,table:&str,columns:usize,floats:&'static[FloatColumn],control:&mut SqliteSnapshotControl<'_>)->Result<Entities<'a>,String>{let rows=&database.table(table)?.rows;let mut result=Entities::new();for(position,row)in rows.iter().enumerate(){checkpoint(control,position,rows.len())?;let row=FloatRow::new(row,floats)?;if row.values.len()!=columns||row.rowid<=0||row.integer(0)?!=row.rowid||result.insert(row.rowid,row).is_some(){return Err(format!("{table} requires exact fields and unique positive aliased identities"));}}Ok(result)}
fn ordered<'a>(rows:impl Iterator<Item=FloatRow<'a>>,parent:i64,control:&mut SqliteSnapshotControl<'_>)->Result<Vec<FloatRow<'a>>,String>{let mut result=BTreeMap::new();for(position,row)in rows.enumerate(){checkpoint(control,position,0)?;let ordinal=usize::try_from(row.integer(2)?).map_err(|error|error.to_string())?;if row.integer(1)?!=parent||result.insert(ordinal,row).is_some(){return Err("EN1995 entity has a foreign parent or duplicate ordinal".into());}}for(position,ordinal)in result.keys().copied().enumerate(){checkpoint(control,position,result.len())?;if position!=ordinal{return Err("EN1995 ordinals must be dense".into());}}Ok(result.into_values().collect())}
fn groups<'a>(rows:Entities<'a>,parents:&Entities<'_>,control:&mut SqliteSnapshotControl<'_>)->Result<BTreeMap<i64,Vec<FloatRow<'a>>>,String>{let mut result=BTreeMap::<i64,Vec<FloatRow<'a>>>::new();for(position,row)in rows.into_values().enumerate(){checkpoint(control,position,0)?;let parent=row.integer(1)?;if !parents.contains_key(&parent){return Err("EN1995 action has an unknown owning member or connection".into());}result.entry(parent).or_default().push(row);}Ok(result)}
fn ordinal(value:usize)->Result<Cell<'static>,String>{Ok(Cell::Integer(i64::try_from(value).map_err(|error|error.to_string())?))}
fn read_u32(row:FloatRow<'_>,column:usize)->Result<u32,String>{u32::try_from(row.integer(column)?).map_err(|error|error.to_string())}
fn read_u8(row:FloatRow<'_>,column:usize)->Result<u8,String>{u8::try_from(row.integer(column)?).map_err(|error|error.to_string())}
fn read_flag(row:FloatRow<'_>,column:usize)->Result<bool,String>{match row.integer(column)?{0=>Ok(false),1=>Ok(true),_=>Err("EN1995 boolean requires exactly zero or one".into())}}

impl ArtifactSqliteSnapshot for En1995Snapshot{
 fn decode_sqlite_snapshot_native(payload:&store::io::IoPayload,control:&mut SqliteSnapshotControl<'_>)->Result<Self,String>{store::decode_sqlite_snapshot_record_native(payload,<Self as store::ArtifactDsl>::envelope_id(),Self::__dsl_spec_producer(),Self::__dsl_from_record_controlled,control)}
    const SQLITE_SCHEMA:&'static str=include_str!("🗄️.sql");
    fn encode_sqlite_snapshot_native(&self,encoding:SnapshotEncoding,control:&mut SqliteSnapshotControl<'_>)->Result<store::io_schema::IoPayload,String>{
  control.checkpoint(SqliteSnapshotPhase::EncodeNative,0,0)?;let add=|count:usize,size:usize|count.checked_add(size).ok_or("Native semantic row count overflow");let mut rows=1usize;for size in[self.members.len(),self.connections.len()]{rows=add(rows,size)?}control.check_rows(rows)?;for(index,member)in self.members.iter().enumerate(){rows=add(rows,member.actions.len())?;control.check_rows(rows)?;if(index+1)%256==0{control.checkpoint(SqliteSnapshotPhase::EncodeNative,index+1,self.members.len())?}}for(index,connection)in self.connections.iter().enumerate(){rows=add(rows,connection.actions.len())?;control.check_rows(rows)?;if(index+1)%256==0{control.checkpoint(SqliteSnapshotPhase::EncodeNative,index+1,self.connections.len())?}}
  store::encode_sqlite_snapshot_record_native(encoding,<Self as store::ArtifactDsl>::envelope_id(),Self::__dsl_spec_producer(),|native|self.__dsl_to_record_controlled(native),control)
 }

 fn preflight_sqlite_snapshot_encoding(&self,_:SnapshotEncoding,control:&mut SqliteSnapshotControl<'_>)->Result<(),String>{
        let mut bound=NativeEncodingBound::new(control)?;bound.add(16384)?;
        for member in &self.members{bound.add(32768)?;for text in [&member.id,&member.label_en,&member.label_de,&member.strength_class]{bound.repeated(text.len(),24)?;}for action in &member.actions{bound.add(12288)?;for text in [&action.id,&action.kind,&action.category,&action.load_duration]{bound.repeated(text.len(),24)?;}}}
        for connection in &self.connections{bound.add(16384)?;for text in [&connection.id,&connection.label_en,&connection.label_de,&connection.fastener_type,&connection.strength_class]{bound.repeated(text.len(),24)?;}for action in &connection.actions{bound.add(2048)?;for text in [&action.id,&action.kind,&action.load_duration]{bound.repeated(text.len(),24)?;}}}
        bound.finish()
    }
    fn to_sqlite_database(&self,control:&mut SqliteSnapshotControl<'_>)->Result<SqliteDatabase,String>{
        let mut out=Projection::new(Self::SQLITE_SCHEMA,control)?;out.insert_key("en1995_document",1,&[Cell::Text(annex(self.annex))])?;
        for(position,member)in self.members.iter().enumerate(){
            let id=insert_ieee754(&mut out,"en1995_member",&[Cell::Integer(1),ordinal(position)?,Cell::Text(&member.id),Cell::Text(&member.label_en),Cell::Text(&member.label_de),Cell::Text(role(member.role)),Cell::Text(&member.strength_class),Cell::Integer(i64::from(member.service_class)),Cell::Text(support(member.support)),Cell::Real(member.b_m),Cell::Real(member.h_m),Cell::Real(member.span_m),Cell::Real(member.support_length_m),Cell::Real(member.bearing_length_m),Cell::Real(member.buckling_length_y_m),Cell::Real(member.buckling_length_z_m),Cell::Real(member.lateral_restraint_spacing_m),Cell::Real(member.notch_depth_m),Cell::Real(member.notch_distance_m),Cell::Real(member.m_crit_nm),Cell::Real(member.mass_kg_per_m),Cell::Real(member.mass_kg_per_m2),Cell::Real(member.damping_xi),Cell::Real(member.fire_duration_s),Cell::Real(member.bridge_n_obs),Cell::Real(member.bridge_t_l_years),Cell::Real(member.bridge_beta),Cell::Real(member.bridge_a),Cell::Real(member.bridge_b),Cell::Real(member.bridge_crowd_per_m2)],MEMBER_FLOATS)?;
            for(position,action)in member.actions.iter().enumerate(){insert_ieee754(&mut out,"en1995_member_action",&[Cell::Integer(id),ordinal(position)?,Cell::Text(&action.id),Cell::Text(&action.kind),Cell::Text(&action.category),Cell::Text(&action.load_duration),Cell::Real(action.q_line_n_per_m),Cell::Real(action.f_point_n),Cell::Real(action.m_k_nm),Cell::Real(action.v_k_n),Cell::Real(action.n_k_n),Cell::Real(action.n_t_k_n),Cell::Real(action.f_c90_k_n)],MEMBER_ACTION_FLOATS)?;}
        }
        for(position,connection)in self.connections.iter().enumerate(){
            let id=insert_ieee754(&mut out,"en1995_connection",&[Cell::Integer(1),ordinal(position)?,Cell::Text(&connection.id),Cell::Text(&connection.label_en),Cell::Text(&connection.label_de),Cell::Text(&connection.fastener_type),Cell::Text(&connection.strength_class),Cell::Integer(i64::from(connection.service_class)),Cell::Real(connection.diameter_m),Cell::Integer(i64::from(connection.number)),Cell::Integer(i64::from(connection.rows)),Cell::Real(connection.spacing_m),Cell::Real(connection.edge_distance_m),Cell::Real(connection.end_distance_m),Cell::Real(connection.t1_m),Cell::Real(connection.t2_m),Cell::Integer(i64::from(connection.steel_plate)),Cell::Real(connection.steel_plate_thickness_m),Cell::Integer(i64::from(connection.shear_planes)),Cell::Real(connection.f_u_k)],CONNECTION_FLOATS)?;
            for(position,action)in connection.actions.iter().enumerate(){insert_ieee754(&mut out,"en1995_connection_action",&[Cell::Integer(id),ordinal(position)?,Cell::Text(&action.id),Cell::Text(&action.kind),Cell::Text(&action.load_duration),Cell::Real(action.f_k_n)],CONNECTION_ACTION_FLOATS)?;}
        }
        out.finish()
    }
    fn from_sqlite_database(database:&SqliteDatabase,control:&mut SqliteSnapshotControl<'_>)->Result<Self,String>{
        validate_sqlite_database_schema(database,Self::SQLITE_SCHEMA,control.limits()).map_err(|error|error.to_string())?;control.check_database(database,SqliteSnapshotPhase::ReconstructSnapshot)?;
        let documents=entities(database,"en1995_document",2,&[],control)?;if documents.len()!=1||!documents.contains_key(&1){return Err("EN1995 requires exactly document identity one".into());}let document=documents[&1];
        let member_rows=entities(database,"en1995_member",31,MEMBER_FLOATS,control)?;let connection_rows=entities(database,"en1995_connection",21,CONNECTION_FLOATS,control)?;
        let mut member_actions=groups(entities(database,"en1995_member_action",14,MEMBER_ACTION_FLOATS,control)?,&member_rows,control)?;let mut connection_actions=groups(entities(database,"en1995_connection_action",7,CONNECTION_ACTION_FLOATS,control)?,&connection_rows,control)?;
        let mut members=Vec::new();for row in ordered(member_rows.into_values(),1,control)?{
            checkpoint(control,members.len(),0)?;let mut actions=Vec::new();for action in ordered(member_actions.remove(&row.rowid).unwrap_or_default().into_iter(),row.rowid,control)?{checkpoint(control,actions.len(),0)?;actions.push(CharacteristicAction{id:reconstruct_text(control,action.text(3)?)?,kind:reconstruct_text(control,action.text(4)?)?,category:reconstruct_text(control,action.text(5)?)?,load_duration:reconstruct_text(control,action.text(6)?)?,q_line_n_per_m:action.real(7)?,f_point_n:action.real(8)?,m_k_nm:action.real(9)?,v_k_n:action.real(10)?,n_k_n:action.real(11)?,n_t_k_n:action.real(12)?,f_c90_k_n:action.real(13)?});}
            members.push(TimberMember{id:reconstruct_text(control,row.text(3)?)?,label_en:reconstruct_text(control,row.text(4)?)?,label_de:reconstruct_text(control,row.text(5)?)?,role:read_role(row.text(6)?)?,strength_class:reconstruct_text(control,row.text(7)?)?,service_class:read_u8(row,8)?,support:read_support(row.text(9)?)?,b_m:row.real(10)?,h_m:row.real(11)?,span_m:row.real(12)?,support_length_m:row.real(13)?,bearing_length_m:row.real(14)?,buckling_length_y_m:row.real(15)?,buckling_length_z_m:row.real(16)?,lateral_restraint_spacing_m:row.real(17)?,notch_depth_m:row.real(18)?,notch_distance_m:row.real(19)?,m_crit_nm:row.real(20)?,mass_kg_per_m:row.real(21)?,mass_kg_per_m2:row.real(22)?,damping_xi:row.real(23)?,fire_duration_s:row.real(24)?,bridge_n_obs:row.real(25)?,bridge_t_l_years:row.real(26)?,bridge_beta:row.real(27)?,bridge_a:row.real(28)?,bridge_b:row.real(29)?,bridge_crowd_per_m2:row.real(30)?,actions});
        }
        let mut connections=Vec::new();for row in ordered(connection_rows.into_values(),1,control)?{
            checkpoint(control,connections.len(),0)?;let mut actions=Vec::new();for action in ordered(connection_actions.remove(&row.rowid).unwrap_or_default().into_iter(),row.rowid,control)?{checkpoint(control,actions.len(),0)?;actions.push(ConnectionAction{id:reconstruct_text(control,action.text(3)?)?,kind:reconstruct_text(control,action.text(4)?)?,load_duration:reconstruct_text(control,action.text(5)?)?,f_k_n:action.real(6)?});}
            connections.push(TimberConnection{id:reconstruct_text(control,row.text(3)?)?,label_en:reconstruct_text(control,row.text(4)?)?,label_de:reconstruct_text(control,row.text(5)?)?,fastener_type:reconstruct_text(control,row.text(6)?)?,strength_class:reconstruct_text(control,row.text(7)?)?,service_class:read_u8(row,8)?,diameter_m:row.real(9)?,number:read_u32(row,10)?,rows:read_u32(row,11)?,spacing_m:row.real(12)?,edge_distance_m:row.real(13)?,end_distance_m:row.real(14)?,t1_m:row.real(15)?,t2_m:row.real(16)?,steel_plate:read_flag(row,17)?,steel_plate_thickness_m:row.real(18)?,shear_planes:read_u32(row,19)?,f_u_k:row.real(20)?,actions});
        }
        let snapshot=Self{annex:read_annex(document.text(1)?)?,members,connections};control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,1,1)?;Ok(snapshot)
    }
}

pub fn sqlite_codec()->store::ArtifactSqliteSnapshotCodec{<En1995Snapshot as store::ArtifactSqliteSnapshot>::sqlite_codec()}
