/** 🖨️ Neutral Raster intrinsic domains, literal handles and independent relational oracle. */
import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import Ajv from "ajv";
import fixture from "../../🧫️fixtures/🪶️sqlite/🔣️.json";
import schema from "../../🧫️fixtures/🪶️sqlite/🧬️schema/🔣️.json";
import {type RasterSnapshot} from "../../🟦️.ts";
import {parseRasterTransform} from "../../../🟦️.ts";
import {RASTER_SQLITE_SCHEMA,rasterSnapshotToSqliteDatabase,rasterSnapshotFromSqliteDatabase} from "../../🪶️sqlite/🟦️.ts";
import type {IntrinsicValue} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🧬️schema/🌳️intrinsic/🟦️.ts";
import {parseBinary64,parseBinary32,parseBinary32Transport,binary64,binary32} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
function intrinsic(v:any):IntrinsicValue{switch(v.kind){case"null":return{kind:"null"};case"boolean":case"text":return{kind:v.kind,value:v.value};case"signed":case"unsigned":return{kind:v.kind,value:BigInt(v.value)};case"float":return{kind:"float",value:parseBinary64({bits:BigInt('0x'+v.value)})};case"bytes":return{kind:"bytes",value:Uint8Array.from(v.value)};case"array":return{kind:"array",items:v.items.map(intrinsic)};case"object":return{kind:"object",members:v.members.map((m:any)=>({name:m.name,value:intrinsic(m.value)}))};default:throw Error("neutral intrinsic kind");}}
function snapshot():RasterSnapshot{const common={id:"",name:"literal name\0",visible:false,locked:true,opacity:binary32(0.5),blendMode:"arbitrary!",transform:{x:binary64(fixture.transform.x),y:binary64(fixture.transform.y),a:binary64(fixture.transform.a),b:binary64(fixture.transform.b),c:binary64(fixture.transform.c),d:binary64(fixture.transform.d)}};return{schema:fixture.schema,id:fixture.id,title:fixture.title,layers:[{kind:"pixel",...common,width:4294967295,height:0,imageKey:"",mask:{...fixture.mask,transform:{x:binary64(fixture.mask.transform.x),y:binary64(fixture.mask.transform.y),a:binary64(fixture.mask.transform.a),b:binary64(fixture.mask.transform.b),c:binary64(fixture.mask.transform.c),d:binary64(fixture.mask.transform.d)}}},{kind:"group",...common,children:[{kind:"group",...common,children:[]}]},{kind:"adjustment",...common,adjustmentKind:"private effect",params:{"":intrinsic(fixture.parameter)}}],assets:{"":structuredClone(fixture.child)}};}
test("Raster independent neutral schema and authored tables",()=>{expect(new Ajv({strict:true}).compile(schema)(fixture)).toBe(true);const db=new Database(":memory:");db.exec(RASTER_SQLITE_SCHEMA);expect(db.query("SELECT count(*) AS n FROM sqlite_master WHERE type='table'").get()).toEqual({n:23});expect(db.query("PRAGMA foreign_key_list(raster_mask_transform)").all().length).toBe(7);db.close();});
test("Raster all three layers, mask, full integer intrinsic variants and literal child identity",async()=>{const s=snapshot(),bytes=await exportSqliteDatabase(await rasterSnapshotToSqliteDatabase(s)),db=new Database(bytes);expect(db.query("SELECT kind FROM raster_layer ORDER BY id").all()).toEqual(["pixel","group","group","adjustment"].map(kind=>({kind})));expect(db.query("SELECT high,low FROM raster_unsigned").get()).toEqual({high:4294967295,low:4294967295});expect(db.query("SELECT key FROM raster_member ORDER BY ordinal").all()).toEqual([{key:"duplicate"},{key:"duplicate"},{key:""}]);expect(db.query("SELECT hex(value) AS bytes FROM raster_bytes").get()).toEqual({bytes:"007FFF"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);db.close();expect(await rasterSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes))).toEqual(s);});
test("Raster independent SQL edits retain complete child strings",async()=>{const db=new Database(await exportSqliteDatabase(await rasterSnapshotToSqliteDatabase(snapshot())));db.exec("UPDATE raster_asset SET standard='SQL literal'; UPDATE raster_text SET value='SQL intrinsic text'");const s=await rasterSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())));expect(s.assets['']!.target.dialect.standard).toBe("SQL literal");db.close();});
test("Raster row/value limits and interior typed intrinsic copy cancellation",async()=>{const s=snapshot();await expect(rasterSnapshotToSqliteDatabase(s,{maxRows:1})).rejects.toThrow();await expect(rasterSnapshotToSqliteDatabase(s,{maxValueBytes:1})).rejects.toThrow();const adjustment=s.layers[2]! as any;adjustment.params['']={kind:"bytes",value:new Uint8Array(fixture.intrinsicBytes)};let observed=false;const controller=new AbortController();await expect(rasterSnapshotToSqliteDatabase(s,{signal:controller.signal,onProgress:p=>{if(p.phase==='projectSnapshot'&&p.completed>=fixture.cancelAfter&&p.completed<p.total){observed=true;controller.abort();}}})).rejects.toThrow();expect(observed).toBe(true);});

test("Raster intrinsic raw words and deep ownership are independently queryable",async()=>{const s=snapshot(),a=s.layers[2];if(a?.kind!=="adjustment")throw Error("neutral adjustment");for(let i=0;i<fixture.float64Words.length;i++)a.params[String(i)]={kind:"float",value:parseBinary64({bits:BigInt("0x"+fixture.float64Words[i])})};let deep:IntrinsicValue={kind:"text",value:"literal leaf\0"};for(let i=0;i<fixture.depth;i++)deep={kind:"array",items:[deep]};a.params.deep=deep;const bytes=await exportSqliteDatabase(await rasterSnapshotToSqliteDatabase(s)),db=new Database(bytes);expect(db.query("SELECT printf('%016llx',bits) AS bits FROM raster_scalar64 WHERE class='nan' ORDER BY id").all()).toEqual(fixture.float64Words.filter(word=>((BigInt('0x'+word)>>52n)&2047n)===2047n&&(BigInt('0x'+word)&4503599627370495n)!==0n).map(bits=>({bits})));expect(db.query("SELECT count(*) AS n FROM raster_array").get()).toEqual({n:fixture.depth+1});db.close();const restored=await rasterSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes));const r=restored.layers[2];if(r?.kind!=="adjustment")throw Error("restored adjustment");for(let i=0;i<fixture.float64Words.length;i++)expect(r.params[String(i)]).toEqual(a.params[String(i)]);let value=r.params.deep!;for(let i=0;i<fixture.depth;i++){if(value.kind!=="array"||value.items.length!==1)throw Error("deep array ownership");value=value.items[0]!;}expect(value).toEqual({kind:"text",value:"literal leaf\0"});});
test("Raster refuses orphan bodies and noncontiguous relationship ordinals",async()=>{for(const edit of ["INSERT INTO raster_text(id,value) VALUES(99999,'orphan')","UPDATE raster_member SET ordinal=ordinal+1"]){const db=new Database(await exportSqliteDatabase(await rasterSnapshotToSqliteDatabase(snapshot())));db.exec(edit);const data=await importSqliteDatabase(new Uint8Array(db.serialize()));db.close();await expect(rasterSnapshotFromSqliteDatabase(data)).rejects.toThrow();}});

test("Raster literal-key sorting cancels inside a long shared prefix before field copying",async()=>{const s=snapshot(),prefix="a".repeat(fixture.intrinsicBytes);s.assets={};s.assets[prefix+"z"]=structuredClone(fixture.child);s.assets[prefix+"a"]=structuredClone(fixture.child);const controller=new AbortController();let observed=false;await expect(rasterSnapshotToSqliteDatabase(s,{signal:controller.signal,onProgress:p=>{if(p.phase==='projectSnapshot'&&p.total===2*(prefix.length+1)&&p.completed>=fixture.cancelAfter&&p.completed<p.total){observed=true;controller.abort();}}})).rejects.toThrow();expect(observed).toBe(true);});

test("Raster reconstructed key-order validation has genuine interior cancellation",async()=>{const s=snapshot(),prefix="a".repeat(fixture.intrinsicBytes);s.assets={[prefix+"z"]:structuredClone(fixture.child),[prefix+"a"]:structuredClone(fixture.child)};const data=await rasterSnapshotToSqliteDatabase(s),controller=new AbortController();let observed=false;await expect(rasterSnapshotFromSqliteDatabase(data,{signal:controller.signal,onProgress:p=>{if(p.phase==='reconstructSnapshot'&&p.total===2*(prefix.length+1)&&p.completed>=fixture.cancelAfter&&p.completed<p.total){observed=true;controller.abort();}}})).rejects.toThrow();expect(observed).toBe(true);});

test("Raster every layer scalar word remains exact without a numeric carrier",async()=>{for(let i=0;i<fixture.float64Words.length;i++){const s=snapshot(),node=s.layers[0]!;Object.assign(node,{opacity:parseBinary32({bits:Number.parseInt(fixture.float32Words[i]!,16)})});Object.assign(node.transform,{x:parseBinary64({bits:BigInt('0x'+fixture.float64Words[i]!)})});const bytes=await exportSqliteDatabase(await rasterSnapshotToSqliteDatabase(s)),db=new Database(bytes);expect(db.query("SELECT printf('%08llx',bits) AS bits FROM raster_scalar32 ORDER BY id LIMIT 1").get()).toEqual({bits:fixture.float32Words[i]});expect(db.query("SELECT printf('%016llx',bits) AS bits FROM raster_scalar64 ORDER BY id LIMIT 1").get()).toEqual({bits:fixture.float64Words[i]});db.close();const restored=await rasterSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes));expect(restored.layers[0]!.opacity).toEqual(node.opacity);expect(restored.layers[0]!.transform.x).toEqual(node.transform.x);expect(parseBinary32Transport(restored.layers[0]!.opacity)).toEqual(node.opacity);expect(parseRasterTransform(restored.layers[0]!.transform).x).toEqual(node.transform.x);}});
