[package]
name="vcs-id"
version="0.1.0"
edition="2021"
[workspace]
[lib]
path="🦀️.rs"
[dependencies]
semio-framework-hash={path="../../../../../../../../🧰️framework/🔨️modules/🔏️hash/📦️packages/🦀️rust"}
semio-framework-value={path="../../../../../../../../🧰️framework/🔨️modules/🌱️value/📦️packages/🦀️rust"}
[dev-dependencies]
serde={version="1.0",features=["derive"]}
serde_json="1.0.140"
blake3="1.8.2"
leb128="0.2.7"
