//! 📤️ Registered captured serializers publish through the existing sealed download completion.
use super::*;
use semio_framework_plugin::retained_command::{ArtifactCommandWork,ArtifactCommandInputs,ArtifactCommandWorkStep};
use semio_framework_plugin::app::{ArtifactDownloadOutput,ArtifactOutputChunks};
use semio_framework_os_kernel::io::io_mechanism::{OwnedSerializerRequest,OwnedSerializerJob,OwnedSerializerOutput,io_begin_owned_serialization};
use semio_framework_artifact_reference::ArtifactDialect;
use semio_framework_value::{DslValue,retirement::controlled::ControlledRetirement,retained_clone::{RetainedCloneGrant,RetainedCloneProgress},ValueError};
type App=semio_framework_plugin::EditorApp<DrawingPlayApp>;
const OUTPUT_LIMIT:usize=ArtifactOutputChunks::MAXIMUM_TOTAL_BYTES;
const PAGE_INPUT:usize=ArtifactOutputChunks::CHUNK_BYTES/4*3;
#[derive(semio_framework_value::RetireOwned)]
struct DownloadOwners{chunks:Option<ArtifactOutputChunks>,raw:Option<OwnedSerializerOutput>,filename:String,mime:String,metadata:Option<((ArtifactDialect,ArtifactDialect),DslValue)>,refusal:Option<ValueError>}
struct Work{read:Option<store::SnapshotRead<DrawingSnapshot>>,read_close:Option<Box<dyn semio_framework_value::ErasedSnapshotRetirement>>,request:Option<OwnedSerializerRequest>,job:Option<Box<dyn OwnedSerializerJob>>,birth_grant:RetainedCloneGrant,birth_progress:RetainedCloneProgress,handoff_grant:RetainedCloneGrant,handoff_progress:RetainedCloneProgress,download:ControlledRetirement<DownloadOwners>,phase:&'static str,page:usize,cursor:usize,complete:bool,closing:bool}
impl Work{
 fn new(read:store::SnapshotRead<DrawingSnapshot>,birth_grant:RetainedCloneGrant,handoff_grant:RetainedCloneGrant)->Self{let download=ControlledRetirement::new(DownloadOwners{chunks:None,raw:None,filename:String::new(),mime:String::new(),metadata:None,refusal:None}).unwrap_or_else(|_|unreachable!());Self{read:Some(read),read_close:None,request:None,job:None,birth_grant,birth_progress:Default::default(),handoff_grant,handoff_progress:Default::default(),download,phase:"header",page:0,cursor:0,complete:false,closing:false}}
 fn source_authority_matches(&self,generation:u64,revision:[u8;32])->bool{self.read.as_ref().is_some_and(|read|read.commit_authority_matches(generation,revision))||self.request.as_ref().is_some_and(|request|request.source.commit_authority_matches(generation,revision))||self.job.as_ref().is_some_and(|job|job.source_authority_matches(generation,revision))}
 fn close_demands(&self,body:usize)->Result<semio_framework_value::RetirementDemand,ValueError>{if self.request.is_some(){return Ok(semio_framework_value::RetirementDemand{depth:1,..Default::default()});}if !self.download.terminal_is_empty(){return Ok(semio_framework_value::RetirementDemand{copy_bytes:self.download.next_copy_byte_demand()?,capacity_bytes:self.download.next_capacity_byte_demand(body)?,release_bytes:self.download.next_release_byte_demand()?,depth:self.download.next_depth_demand()?});}if let Some(job)=&self.job{if let Some(release_bytes)=job.terminal_frame_release_bytes(){return Ok(semio_framework_value::RetirementDemand{release_bytes,depth:1,..Default::default()});}return Ok(semio_framework_value::RetirementDemand{copy_bytes:job.next_close_copy_byte_demand()?,capacity_bytes:job.next_close_capacity_byte_demand(body)?,release_bytes:job.next_close_release_byte_demand()?,depth:job.next_close_depth_demand()?});}if let Some(read)=&self.read_close{return store::artifact_retirement_box_demands(read,body);}store::artifact_retirement_owned_birth_demands(&self.read)}
}
impl ArtifactCommandWork<App> for Work{
 fn tool_id(&self)->&'static str{"exportDocument"}
 fn extent(&self,command:&DrawingCommand,_snapshot:&DrawingSnapshot,_interaction:&protocol::InteractionState,_context:Option<&semio_framework_plugin::app::ArtifactOwnedToolJobContext<App>>)->Option<usize>{(!self.complete&&matches!(command,DrawingCommand::ExportDocument(_))).then_some(1)}
 fn step(&mut self,input:&ArtifactCommandInputs<'_,App>,cx:&mut semio_framework_job::StepContext<'_>)->Result<ArtifactCommandWorkStep<App>,Fault>{if self.complete||self.closing||cx.is_cancelled(){return Err(Fault::from("Drawing export cancelled or terminal"));}let generation=input.operation.generation;let revision=input.operation.canonical_base_revision;if self.phase!="handoff-fault"&&!self.source_authority_matches(generation,revision){return Err(Fault::from("Drawing export source authority changed"));}if cx.should_yield(){return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});}let DrawingCommand::ExportDocument(payload)=input.command else{return Err(Fault::from("Drawing export command required"));};
  if self.phase=="header"{let target=match payload.format.as_str(){"png"=>("s.stdio.png","1.2","image/png"),"svg"=>("s.stdio.svg","1.1","image/svg+xml"),"pdf"=>("s.stdio.pdf","1.4","application/pdf"),_=>return Err(Fault::from("Drawing exports to png, pdf or svg"))};let owners=self.download.original_mut().unwrap();owners.filename=format!("{}.{}",export_document::export_stem(self.read.as_ref().unwrap().get()),payload.format);owners.mime=target.2.into();owners.chunks=Some(ArtifactOutputChunks::new(OUTPUT_LIMIT));let mut options=Vec::with_capacity(3);if let Some(width)=payload.width{options.push(("width".into(),DslValue::uint(u64::from(width))));}if let Some(height)=payload.height{options.push(("height".into(),DslValue::uint(u64::from(height))));}options.push(("transparent".into(),DslValue::Bool(payload.transparent.unwrap_or(true))));self.request=Some(OwnedSerializerRequest{source:self.read.take().unwrap().into_erased(),route:(crate::DRAWING_DIALECT.into(),ArtifactDialect{artifact_kind:target.0.into(),standard:target.1.into(),subset:"*".into()}),generation,revision,options:DslValue::Object(options),children:None});self.phase="admit";cx.consume_fuel(1);return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});}
  if self.phase=="admit"{match io_begin_owned_serialization(self.request.take().unwrap(),self.birth_grant){Ok(admission)=>{self.birth_progress=admission.progress;self.birth_grant=Default::default();self.job=Some(admission.job);self.phase="produce";},Err(refusal)=>{self.request=Some(refusal.request);self.birth_progress=refusal.progress;self.download.original_mut().unwrap().refusal=Some(refusal.error);self.phase="refused";return Err(Fault::from(self.download.original().unwrap().refusal.as_ref().unwrap().message.as_ref()));}}cx.consume_fuel(1);return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});}
  if self.phase=="refused"{return Err(Fault::from(self.download.original().unwrap().refusal.as_ref().unwrap().message.as_ref()));}
  if self.phase=="produce"{match self.job.as_mut().unwrap().step(cx){semio_framework_job::StepOutcome::Yield=>return Ok(ArtifactCommandWorkStep::Progress{stage:cx.stage(),preview:b""}),semio_framework_job::StepOutcome::Complete(_)=>self.phase="handoff-output",semio_framework_job::StepOutcome::Fault(_)=>self.phase="handoff-fault",semio_framework_job::StepOutcome::Cancelled=>return Err(Fault::from("Drawing export cancelled")),_=>return Err(Fault::from("Drawing serializer produced unsupported scheduling output"))}return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});}
  if self.phase=="handoff-output"{match self.job.as_mut().unwrap().take_output(self.handoff_grant){Ok(Some(handoff))=>{self.handoff_progress=handoff.progress;self.handoff_grant=Default::default();self.download.original_mut().unwrap().raw=Some(handoff.output);self.phase="output";cx.consume_fuel(1);return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});},Ok(None)=>return Err(Fault::from("Drawing serializer completed without original output")),Err(error)=>{self.download.original_mut().unwrap().refusal=Some(error);return Err(Fault::from("Drawing original output handoff refused"));}}}
  if self.phase=="handoff-fault"{match self.job.as_mut().unwrap().take_fault(self.handoff_grant){Ok(Some(handoff))=>{self.handoff_progress=handoff.progress;self.handoff_grant=Default::default();cx.consume_fuel(1);return Err(handoff.fault);},Ok(None)=>return Err(Fault::from("Drawing serializer failed without original diagnostic")),Err(error)=>{self.download.original_mut().unwrap().refusal=Some(error);return Err(Fault::from("Drawing original diagnostic handoff refused"));}}}
  let owners=self.download.original_mut().unwrap();while !cx.should_yield(){if cx.is_cancelled(){return Err(Fault::from("Drawing export cancelled before publication"));}cx.set_stage(self.phase);match self.phase{
   "output"=>{let raw=owners.raw.as_ref().ok_or_else(||Fault::from("Drawing export output ownership missing"))?;if self.page<raw.pages.len(){let page=base64_codec::base64_standard_encode(raw.pages.get(self.page).unwrap()).into_bytes();owners.chunks.as_ref().unwrap().push(page)?;self.page+=1;cx.consume_fuel(1);continue;}if self.cursor<raw.contiguous.len(){let end=(self.cursor+PAGE_INPUT).min(raw.contiguous.len());let page=base64_codec::base64_standard_encode(&raw.contiguous[self.cursor..end]).into_bytes();owners.chunks.as_ref().unwrap().push(page)?;self.cursor=end;cx.consume_fuel(1);continue;}owners.chunks.as_ref().unwrap().seal()?;self.phase="publish";cx.consume_fuel(1);return Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""});},
   "publish"=>{if !self.job.as_ref().unwrap().source_authority_matches(generation,revision){return Err(Fault::from("Drawing export source authority changed before publication"));}let download=ArtifactDownloadOutput::new(std::mem::take(&mut owners.filename),std::mem::take(&mut owners.mime),Some("base64".into()),owners.chunks.take().unwrap())?;self.complete=true;cx.consume_fuel(1);return Ok(ArtifactCommandWorkStep::CompleteDownload{download,ephemeral:Default::default()});},
   _=>return Err(Fault::from("Drawing export transport stage invalid")),
  }}Ok(ArtifactCommandWorkStep::Progress{stage:self.phase,preview:b""})}
 fn begin_close(&mut self){self.closing=true;if let Some(job)=&mut self.job{job.begin_close();}}
 fn close_step(&mut self,grant:RetainedCloneGrant)->semio_framework_job::InteractiveJobCloseStep{use semio_framework_job::InteractiveJobCloseStep;if !self.closing{return InteractiveJobCloseStep::Blocked;}if self.request.is_some(){if grant.maximum_items==0||grant.maximum_depth==0{return InteractiveJobCloseStep::Blocked;}let request=self.request.take().unwrap();if request.children.is_some(){self.request=Some(request);return InteractiveJobCloseStep::Refused(semio_framework_value::ValueRefusalKind::UnsupportedOwner);}let OwnedSerializerRequest{source,route,generation,revision,options,children}=request;match source.try_into_typed::<DrawingSnapshot>(){Ok(read)=>{self.read=Some(read);self.download.original_mut().unwrap().metadata=Some((route,options));return InteractiveJobCloseStep::Pending{progress:RetainedCloneProgress{copied_items:1,..Default::default()}};},Err(source)=>{self.request=Some(OwnedSerializerRequest{source,route,generation,revision,options,children});return InteractiveJobCloseStep::Refused(semio_framework_value::ValueRefusalKind::UnsupportedOwner);}}}if !self.download.terminal_is_empty(){return match self.download.step(grant){Ok(step)=>InteractiveJobCloseStep::Pending{progress:step.progress()},Err(error)=>InteractiveJobCloseStep::Refused(error.kind)};}if let Some(job)=&mut self.job{if let Some(release_bytes)=job.terminal_frame_release_bytes(){if grant.maximum_items==0||grant.maximum_depth==0||grant.maximum_release_bytes<release_bytes{return InteractiveJobCloseStep::Blocked;}drop(self.job.take());return InteractiveJobCloseStep::Pending{progress:RetainedCloneProgress{copied_items:1,released_bytes:release_bytes,..Default::default()}};}return job.close_step(grant);}if self.read_close.is_some()||self.read.is_some(){let step=if self.read_close.is_some(){store::artifact_retirement_box_close_step(&mut self.read_close,grant)}else{store::artifact_retirement_admit_owned(&mut self.read,&mut self.read_close,grant)};return match step{Ok(step)=>InteractiveJobCloseStep::Pending{progress:step.progress()},Err(error)=>InteractiveJobCloseStep::Refused(error.kind)};}InteractiveJobCloseStep::Complete{progress:Default::default()}}
 fn next_close_copy_byte_demand(&self)->Result<usize,ValueError>{Ok(self.close_demands(0)?.copy_bytes)}
 fn next_close_capacity_byte_demand(&self,body:usize)->Result<usize,ValueError>{Ok(self.close_demands(body)?.capacity_bytes)}
 fn next_close_release_byte_demand(&self)->Result<usize,ValueError>{Ok(self.close_demands(0)?.release_bytes)}
 fn next_close_depth_demand(&self)->Result<usize,ValueError>{Ok(self.close_demands(0)?.depth)}
 fn terminal_frame_release_bytes(&self)->Option<usize>{self.terminal_is_empty().then_some(std::mem::size_of::<Self>())}
 fn terminal_is_empty(&self)->bool{self.closing&&self.download.terminal_is_empty()&&self.read.is_none()&&self.read_close.is_none()&&self.request.is_none()&&self.job.is_none()}
}

pub(super) struct DrawingExportCommandJobFactory{keys:Vec<semio_framework::ToolFactoryKey>}
impl DrawingExportCommandJobFactory{pub(super) fn new(controller:&str)->Self{Self{keys:vec![semio_framework::ToolFactoryKey::new(controller,"exportDocument")]}}}
impl semio_framework::ToolJobFactory for DrawingExportCommandJobFactory {
 type Payload=semio_framework_plugin::retained_command::ArtifactRetainedCommandPayload<App>;
 type Job=semio_framework_plugin::retained_command::ArtifactRetainedCommandJob<App>;
 fn keys(&self)->&[semio_framework::ToolFactoryKey]{&self.keys}
 fn payload_schema_id(&self)->&str{DRAWING_BOUNDED_PAYLOAD_SCHEMA}
 fn classification(&self)->semio_framework::InteractiveJobClassification{semio_framework::InteractiveJobClassification::Migrated}
 fn execution_contract(&self)->semio_framework::ToolExecutionContract{semio_framework::ToolExecutionContract::resumable(4096,4096,1,OUTPUT_LIMIT,7500,1,1)}
 fn create_job(&mut self,_operation:semio_framework_job::Operation,payload:Self::Payload)->Result<Self::Job,semio_framework::ToolJobFactoryError>{Ok(Self::Job::new(payload))}
 fn create_job_from_wire_pages_with_payload(&mut self,_operation:semio_framework_job::Operation,payload:Self::Payload,input:semio_framework::action_bus::RetainedToolWireInput,checkpoint:Option<semio_framework::action_bus::RetainedToolWireInput>)->Result<Self::Job,(semio_framework::ToolJobFactoryError,semio_framework::action_bus::RetainedToolWireInput,Option<semio_framework::action_bus::RetainedToolWireInput>)>{if checkpoint.is_some()||input.declared_bytes()>4096{return Err((semio_framework::ToolJobFactoryError::new("Drawing export rejects oversized command or checkpoint"),input,checkpoint));}Ok(Self::Job::from_wire(payload,input))}
}
impl semio_framework_plugin::ArtifactOwnedToolJobFactory for DrawingExportCommandJobFactory{type Owner=App;const TOOL_IDS:&'static[&'static str]=DRAWING_EXPORT_TOOL_IDS;const DOCUMENT_SCHEMA:&'static str=DRAWING_DOCUMENT_SCHEMA;const PUBLICATION_CONTRACTS:&'static[semio_framework_plugin::ArtifactToolPublicationContract]=DRAWING_EXPORT_PUBLICATION_CONTRACTS;}
pub(super) fn build(request:semio_framework_plugin::ArtifactOwnedToolJobRequest<App>)->Result<semio_framework::ToolOperationSpec,Fault>{
 let work=Work::new(request.snapshot_read,request.retained_birth_grant,request.retained_handoff_grant);
 let operation=semio_framework_plugin::AppOperationContext{app_instance_id:request.app_instance_id,parent_document_id:request.parent_document_id.clone(),operation_id:request.operation.operation.0,generation:request.operation.generation.0,canonical_base_revision:request.canonical_base_revision,authoring_seed:request.authoring_seed.clone()};
 let payload=semio_framework_plugin::retained_command::ArtifactRetainedCommandPayload::new(semio_framework_plugin::retained_command::ArtifactRetainedCommandInputs{command:*request.command,snapshot:request.snapshot,config:request.config,history:request.history,interaction_state:request.interaction_state,interaction_hover:request.interaction_hover,context:Some(request.context),operation,completion:request.completion},DrawingCommand::command_id,4096,4096,Box::new(work));
 Ok(semio_framework::ToolOperationSpec::new(request.controller_id,request.tool_id,request.payload_schema_id,payload,request.operation))
}

#[cfg(test)]
#[path="🧪️tests/🔬️unit/🦀️.rs"]
mod tests;
