import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import * as ts from "typescript";
const root=process.env.SEMIO_TAXONOMY_REPO_ROOT!,ticket=dirname(dirname(import.meta.dir)),owner="🧰️framework/🛍️products/💻️os/🧫️fixtures/⚖️scale",projectPath=owner+"/📦️packages/🦀️rust/📋️project.json",host="🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/🖥️host/📦️packages/🦀️rust/📜️script.ts",launches=[".vscode/launch.json",".vscode/🧩️launch.seed.jsonc"],files=[projectPath,host,...launches],before=files.map(path=>({path,sha256:createHash("sha256").update(readFileSync(join(root,path))).digest("hex")}));
const read=(path:string)=>readFileSync(join(root,path),"utf8"),replace=(path:string,from:string,to:string)=>{const source=read(path);assert.equal(source.split(from).length-1,1,path);writeFileSync(join(root,path),source.replace(from,to));};
writeFileSync(join(import.meta.dir,"📥️input.md"),"# Runner Coordinate Repair Input\n\n```json\n"+JSON.stringify({updated:before.map(row=>row.path),before},null,2)+"\n```\n");
replace(projectPath,'"sourceRoot": "🧰️framework/🛍️products/💻️os/🧪️tests/⚖️scale"',`"sourceRoot": "${owner}"`);
for(const path of launches)replace(path,'@semio-tech/framework-os-scale-fixture:build"','@semio-tech/framework-os-scale-fixture:build-wasm"');
replace(host,'"🧪️tests", "⚖️scale", "🦀️rust", "🦀️.rs"','"🧫️fixtures", "⚖️scale", "🦀️.rs"');
const project=JSON.parse(read(projectPath));assert(existsSync(join(root,project.sourceRoot)));assert(existsSync(join(root,project.root,"📜️script.ts")));
let commands=0;for(const path of launches){const value=ts.parseConfigFileTextToJson(path,read(path));assert(!value.error);for(const item of value.config.configurations){const command=item.command??"";const match=command.match(/@semio-tech\/framework-os-scale-fixture:([^\s]+)/u);if(match){assert(project.targets[match[1]],command);commands++;}}}
const source=ts.createSourceFile("📜️script.ts",read(host),ts.ScriptTarget.Latest,true);assert.equal((source as ts.SourceFile&{parseDiagnostics:readonly unknown[]}).parseDiagnostics.length,0);
assert(existsSync(join(root,owner,"🦀️.rs")));assert(!read(host).includes('"🧪️tests", "⚖️scale"'));
writeFileSync(join(ticket,"📓️testing-taxonomy-runner-repairs-2026-09-12.md"),"# Final Runner Coordinate Repairs\n\nCorrected the scale project sourceRoot to its fixture source owner, retargeted the two existing VS Code build commands to the declared build-wasm target, and repaired the host test command's segmented source-reader path. No compatibility target was added.\n\nThe actual JSON/TypeScript parsers accepted all four files; every scale launch target resolves to a declared target, both source roots and dispatch script exist, and the host source reader resolves to the fixture. This is configuration/path verification; the separately recorded current WIT ABI failure still limits the WASM build.\n\nThe two artifact constants are consumed only by explicit host testing and dev benchmarking commands. They are test-execution orchestration, not production runtime imports of fixture source.\n\n```json\n"+JSON.stringify({updated:files,verifiedLaunchCommands:commands},null,2)+"\n```\n");console.log("[DEBUG] runner references "+JSON.stringify({files:files.length,verifiedLaunchCommands:commands}));
