use super::*;
#[test]
fn prepared_regions_created_round_ellipses_preserve_translated_paint_and_stroke_holes(){
 let rows:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🥚️ellipse/🔣️.json")).unwrap();
 for row in rows.as_array().unwrap(){let rx=row["radii"][0].as_f64().unwrap();let ry=row["radii"][1].as_f64().unwrap();let mut segments=vec![crate::PathSegment::Move{to:[0.0,-ry]}];for to in [[rx,0.0],[0.0,ry],[-rx,0.0],[0.0,-ry]]{segments.push(crate::PathSegment::Arc{rx,ry,rotation:0.0,large_arc:false,sweep:true,to});}segments.push(crate::PathSegment::Close);let source=serde_json::json!({"segments":segments,"query":row["input"]});let mut previous=None;
  for grant in [1,7,4096]{let regions=finish(&source,grant,input(&source));assert_eq!(regions.fill.len(),row["expected"]["fillContours"].as_u64().unwrap()as usize);assert_eq!(regions.stroke.len(),row["expected"]["strokeContours"].as_u64().unwrap()as usize);for at in 0..4{assert!((regions.bounds.unwrap()[at]-row["expected"]["bounds"][at].as_f64().unwrap()).abs()<=regions.flatness);}if let Some(before)=&previous{assert_eq!(&regions,before);}previous=Some(regions.clone());for q in row["expected"]["queries"].as_array().unwrap(){for query_grant in [1,7,4096]{let mut query=PreparedRegionQueryJob::new(stamp(regions.flatness),serde_json::from_value(q["point"].clone()).unwrap(),q["tolerance"].as_f64().unwrap(),regions.flatness).unwrap();while !query.advance(&regions,stamp(regions.flatness),query_grant).unwrap().done{}assert_eq!(query.result(stamp(regions.flatness)).unwrap(),q["hit"].as_bool().unwrap());}}let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());eprintln!("[DEBUG] Native created ellipse {} grant={grant} terminal_empty=true",row["name"]);}
 }
}
#[test]
fn prepared_regions_canonicalize_cancelled_coincident_retraced_degenerate_and_overlapping_paint_topology(){
 let rows:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🧵️topology/🔣️.json")).unwrap();
 for row in rows.as_array().unwrap(){let source=serde_json::json!({"segments":row["segments"],"query":row["input"]});let expected=&row["expected"];let mut previous=None;for grant in [1,7,4096]{
  let regions=finish(&source,grant,input(&source));let bounds:Option<[f64;4]>=serde_json::from_value(expected["bounds"].clone()).unwrap();assert_eq!(regions.bounds,bounds,"{}",row["name"]);assert_eq!(regions.fill.len(),expected["fillContours"].as_u64().unwrap()as usize,"{}",row["name"]);assert_eq!(regions.stroke.len(),expected["strokeContours"].as_u64().unwrap()as usize,"{}",row["name"]);if let Some(previous)=&previous{assert_eq!(&regions,previous,"{}",row["name"]);}previous=Some(regions.clone());let before=regions.clone();let fill=regions.fill.as_ptr();let stroke=regions.stroke.as_ptr();for q in expected["queries"].as_array().unwrap(){for query_grant in [1,7,4096]{let mut query=PreparedRegionQueryJob::new(stamp(regions.flatness),serde_json::from_value(q["point"].clone()).unwrap(),q["tolerance"].as_f64().unwrap(),regions.flatness).unwrap();while !query.advance(&regions,stamp(regions.flatness),query_grant).unwrap().done{}assert_eq!(query.result(stamp(regions.flatness)).unwrap(),q["hit"].as_bool().unwrap(),"{} {}",row["name"],q["point"]);}}assert_eq!(regions,before);assert_eq!(regions.fill.as_ptr(),fill);assert_eq!(regions.stroke.as_ptr(),stroke);let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());eprintln!("[DEBUG] Native canonical paint topology {} grant={grant} actual_bounds={:?} queries={} terminal_empty=true",row["name"],before.bounds,expected["queries"].as_array().unwrap().len()*3);
 }}
}
fn stamp(flatness:f64)->PreparedRegionStamp{PreparedRegionStamp{source:crate::schema::scene_identity::SceneIdentity{instance:710033,base:9007199254740993,generation:u64::MAX,revision:[3;32]},build:9007199254740993,entry:2,flatness}}
fn sources()->serde_json::Value{serde_json::from_str(include_str!("../../../../🧮️geometry/🎯️picking/🎨️paint/🧫️fixtures/🔣️.json")).unwrap()}
fn input(source:&serde_json::Value)->PaintedPathPreparation{let q=&source["query"];PaintedPathPreparation{transform:serde_json::from_value(q["transform"].clone()).unwrap(),flatness:q["flatness"].as_f64().unwrap(),fill:q["fill"].as_bool().unwrap(),fill_rule:serde_json::from_value(q["fillRule"].clone()).unwrap(),stroke:(!q["stroke"].is_null()).then(||PaintedPathStroke{width:q["stroke"]["width"].as_f64().unwrap(),cap:serde_json::from_value(q["stroke"]["cap"].clone()).unwrap(),join:serde_json::from_value(q["stroke"]["join"].clone()).unwrap(),dash:serde_json::from_value(q["stroke"]["dash"].clone()).unwrap()}),limits:PaintedRegionLimits{max_segments:65536,max_points:262144,max_contours:65536,max_work:1000000000}}}
fn finish(source:&serde_json::Value,grant:usize,options:PaintedPathPreparation)->PaintedPathRegions{let segments:Vec<crate::PathSegment>=serde_json::from_value(source["segments"].clone()).unwrap();let before=serde_json::to_value(&segments).unwrap();let mut job=PaintedPathPrepareJob::new(options).unwrap();let(mut work,mut reads,mut done)=(0,0,false);assert!(job.result().is_err());for _ in 0..2000000{let p=job.advance(grant,|at|{reads+=1;segments.get(at).cloned()}).unwrap();assert!(p.work>work&&p.work-work<=grant as u64);work=p.work;if p.done{done=true;break;}assert!(job.result().is_err());}assert!(done);assert_eq!(reads,segments.len()+1);assert_eq!(serde_json::to_value(&segments).unwrap(),before);let(mut close,output)=job.into_retirement();while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());output.unwrap()}
#[test]
fn prepared_painted_regions_reuse_geometry_for_every_neutral_point(){let sources=sources();let rows:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🔣️.json")).unwrap();for row in rows.as_array().unwrap(){let source=sources.as_array().unwrap().iter().find(|s|s["name"]==row["source"]).unwrap();let mut previous=None;for grant in [1,7,4096]{let regions=finish(source,grant,input(source));if let Some(previous)=previous.as_ref(){assert_eq!(&regions,previous);}previous=Some(regions.clone());if !row["bounds"].is_null(){assert_eq!(regions.bounds,Some(serde_json::from_value(row["bounds"].clone()).unwrap()));}let before=regions.clone();for q in row["queries"].as_array().unwrap(){for query_grant in [1,7,4096]{let mut job=PreparedRegionQueryJob::new(stamp(regions.flatness),serde_json::from_value(q["point"].clone()).unwrap(),q["tolerance"].as_f64().unwrap(),regions.flatness).unwrap();let(mut work,mut done)=(0,false);assert!(job.result(stamp(regions.flatness)).is_err());for _ in 0..2000000{let p=job.advance(&regions,stamp(regions.flatness),query_grant).unwrap();assert!(p.work>work&&p.work-work<=query_grant as u64);work=p.work;if p.done{done=true;break;}}assert!(done);assert_eq!(job.result(stamp(regions.flatness)).unwrap(),q["expected"].as_bool().unwrap(),"{}",row["source"]);}}for precision in row["precision"].as_array().unwrap(){let point=serde_json::from_value(source["query"]["point"].clone()).unwrap();assert_eq!(PreparedRegionQueryJob::new(stamp(regions.flatness),point,0.0,precision["requiredFlatness"].as_f64().unwrap()).is_ok(),precision["accepted"].as_bool().unwrap());}assert_eq!(regions,before);let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());eprintln!("[DEBUG] Native prepared regions {} grant={grant} reusable_queries=3 terminal_empty=true",row["source"]);}}}
#[test]
fn prepared_regions_refuse_insufficient_precision_and_cancel_only_borrowed_cursor(){let sources=sources();let source=&sources[6];let regions=finish(source,7,input(source));let before=regions.clone();let point=serde_json::from_value(source["query"]["point"].clone()).unwrap();assert!(PreparedRegionQueryJob::new(stamp(regions.flatness),point,0.0,regions.flatness/2.0).is_err());let mut job=PreparedRegionQueryJob::new(stamp(regions.flatness),point,0.0,regions.flatness).unwrap();for grant in [0,9007199254740992]{assert!(job.advance(&regions,stamp(regions.flatness),grant).is_err());}job.advance(&regions,stamp(regions.flatness),1).unwrap();job.cancel();assert!(job.result(stamp(regions.flatness)).is_err());assert!(job.advance(&regions,stamp(regions.flatness),1).is_err());assert_eq!(regions,before);let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(1).unwrap().done{}assert!(close.terminal_is_empty());}
#[test]
fn prepared_regions_cancel_actual_children_and_private_contours_at_every_phase(){let sources=sources();let source=&sources[6];let segments:Vec<crate::PathSegment>=serde_json::from_value(source["segments"].clone()).unwrap();let phases:Vec<String>=serde_json::from_str(include_str!("../../🧫️fixtures/🧹️retirement/🔣️.json")).unwrap();for phase in phases{for grant in [1,7,4096]{let mut job=PaintedPathPrepareJob::new(input(source)).unwrap();let mut reached=false;for _ in 0..2000000{if job.phase==phase{reached=true;break;}job.advance(1,|at|segments.get(at).cloned()).unwrap();}assert!(reached,"{phase}");let flat=job.flat.len();let child=job.flatten.is_some()||job.outline.is_some();job.cancel();assert_eq!(job.flat.len(),flat);assert_eq!(job.flatten.is_some()||job.outline.is_some(),child);assert!(job.result().is_err());let(mut close,output)=job.into_retirement();assert!(output.is_none());assert!(close.advance(0).is_err());let mut work=0;while !close.terminal_is_empty(){let p=close.advance(grant).unwrap();assert!(p.work>work&&p.work-work<=grant as u64);work=p.work;}eprintln!("[DEBUG] Native prepared regions cancel phase={phase} grant={grant} actual_retirement_work={work} terminal_empty=true");}}}
#[test]
fn prepared_regions_admit_exact_output_counts_and_retire_refused_private_owners(){let sources=sources();let source=&sources[6];let regions=finish(source,7,input(source));let segments:Vec<crate::PathSegment>=serde_json::from_value(source["segments"].clone()).unwrap();let mut options=input(source);options.limits.max_segments=segments.len();options.limits.max_points=regions.points;options.limits.max_contours=regions.contours;let again=finish(source,1,options.clone());assert_eq!(regions,again);for key in 0..4{let mut options=options.clone();match key{0=>options.limits.max_segments-=1,1=>options.limits.max_points-=1,2=>options.limits.max_contours-=1,3=>options.limits.max_work=1,_=>unreachable!()};let mut job=PaintedPathPrepareJob::new(options).unwrap();assert!(job.advance(1000000,|at|segments.get(at).cloned()).is_err());assert!(job.result().is_err());let(mut close,output)=job.into_retirement();assert!(output.is_none());while !close.advance(1).unwrap().done{}assert!(close.terminal_is_empty());}for regions in [regions,again]{let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(7).unwrap().done{}}eprintln!("[DEBUG] Native prepared regions enforce exact output/segment counts and total work limits with genuine retirement");}
#[test]
fn prepared_regions_cache_actual_resolved_boolean_and_png_trace_geometry(){
 use crate::schema::{scene_preparation::{DocumentVectorJob,DocumentSceneContent,DocumentSceneLimits,DocumentAlgorithmLimits},scene_booleans::DocumentBooleanLimits,scene_trace::DocumentTraceLimits,scene_retirement::ScenePlanCloseJob};
 let rows:serde_json::Value=serde_json::from_str(include_str!("../../../📋️prepare/🧫️fixtures/🎬️vector/🔣️.json")).unwrap();let checks:serde_json::Value=serde_json::from_str(include_str!("../../../../🧮️geometry/🎯️picking/🎨️paint/🧫️fixtures/🎬️resolved/🔣️.json")).unwrap();
 for check in checks.as_array().unwrap(){for grant in [1,7,4096]{
  let row=rows.as_array().unwrap().iter().find(|r|r["name"]==check["source"]).unwrap();let document:crate::DrawingSnapshot=serde_json::from_value(row["document"].clone()).unwrap();let l=&row["limits"];let limits=DocumentSceneLimits{max_nodes:l["maxNodes"].as_u64().unwrap()as usize,max_depth:l["maxDepth"].as_u64().unwrap()as usize,max_segments:l["maxSegments"].as_u64().unwrap()as usize,max_references:l["maxReferences"].as_u64().unwrap()as usize,max_source_bytes:l["maxSourceBytes"].as_u64().unwrap()as usize};let algorithms=DocumentAlgorithmLimits{max_work:10000000,trace:DocumentTraceLimits{max_pixels:100000,max_decoded_pixels:100000,max_source_bytes:100000,max_bytes:100000,max_chunks:100,max_edges:65536,max_segments:65536,max_retained_segments:65536,max_work:10000000},booleans:DocumentBooleanLimits{tolerance:0.005,epsilon:1e-8,max_depth:32,max_references:256,max_edges:65536,max_parameters:262144,max_atomic_edges:65536,max_segments:65536,max_retained_segments:262144,max_work:10000000}};let mut producer=DocumentVectorJob::new(&document,limits,algorithms).unwrap();while !producer.advance(grant).unwrap().done{}let(mut retired,plan)=producer.into_retirement();while !retired.advance(grant).unwrap().done{}assert!(retired.terminal_is_empty());let plan=plan.unwrap();let node=plan.nodes.iter().find(|node|node.id=="result").unwrap();let DocumentSceneContent::Path{segments,..}=&node.content else{panic!("actual resolved path required")};let pointer=segments.as_ptr();let before=serde_json::to_value(segments).unwrap();let mut job=PaintedPathPrepareJob::from_prepared(node,0.001,PaintedRegionLimits{max_segments:65536,max_points:262144,max_contours:65536,max_work:1000000000}).unwrap();while !job.advance(grant,|index|segments.get(index).cloned()).unwrap().done{}let(mut retired,regions)=job.into_retirement();while !retired.advance(grant).unwrap().done{}assert!(retired.terminal_is_empty());let regions=regions.unwrap();let fill=regions.fill.as_ptr();let stroke=regions.stroke.as_ptr();let complete=regions.clone();for query_grant in [1,7,4096]{let mut query=PreparedRegionQueryJob::new(stamp(regions.flatness),serde_json::from_value(check["point"].clone()).unwrap(),0.0,0.001).unwrap();while !query.advance(&regions,stamp(regions.flatness),query_grant).unwrap().done{}assert_eq!(query.result(stamp(regions.flatness)).unwrap(),check["expected"].as_bool().unwrap());assert_eq!(regions.fill.as_ptr(),fill);assert_eq!(regions.stroke.as_ptr(),stroke);assert_eq!(regions,complete);}assert_eq!(segments.as_ptr(),pointer);assert_eq!(serde_json::to_value(segments).unwrap(),before);let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());let mut close=ScenePlanCloseJob::new(plan);while !close.advance(grant).unwrap().done{}assert!(close.terminal_is_empty());eprintln!("[DEBUG] Native prepared region actual source={} grant={grant} immutable_cache_queries=3 resolved_source_and_regions_terminal_empty=true",check["source"]);
 }}
}
#[test]
fn prepared_regions_preserve_failed_flatten_child_and_refuse_unsafe_source_admission(){let source=&sources()[6];let mut job=PaintedPathPrepareJob::new(input(source)).unwrap();let mut reads=0;for grant in [0,9007199254740992]{assert!(job.advance(grant,|_|{reads+=1;None}).is_err());}assert_eq!(reads,0);let segments=[crate::PathSegment::Move{to:[1e10,0.0]},crate::PathSegment::Line{to:[1.0,1.0]}];assert!(job.advance(4096,|index|segments.get(index).cloned()).is_err());assert!(job.flatten.is_some());job.cancel();assert!(job.flatten.is_some());let(mut close,output)=job.into_retirement();assert!(output.is_none());let mut work=0;while !close.terminal_is_empty(){let p=close.advance(1).unwrap();assert_eq!(p.work-work,1);work=p.work;}assert!(work>8);eprintln!("[DEBUG] Native prepared region failed genuine flatten child and actual private owner retirement work={work} terminal_empty=true");}

fn neutral_stamp(row:&serde_json::Value)->PreparedRegionStamp{let source=&row["source"];PreparedRegionStamp{source:crate::schema::scene_identity::SceneIdentity{instance:source["instance"].as_u64().unwrap()as u32,base:source["base"].as_str().unwrap().parse().unwrap(),generation:source["generation"].as_str().unwrap().parse().unwrap(),revision:serde_json::from_value(source["revision"].clone()).unwrap()},build:row["build"].as_str().unwrap().parse().unwrap(),entry:row["entry"].as_u64().unwrap()as usize,flatness:row["flatness"].as_f64().unwrap()}}
#[test]
fn metadata_only_cached_queries_refuse_all_neutral_source_build_entry_precision_lanes(){
 let rows:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪪️identity/🔣️.json")).unwrap();let source=&sources()[6];let regions=finish(source,7,input(source));let before=regions.clone();let point=serde_json::from_value(source["query"]["point"].clone()).unwrap();
 assert!(std::mem::size_of::<PreparedRegionQueryJob>()<=256);
 for row in rows.as_array().unwrap(){for grant in [1,7,4096]{
  let captured=neutral_stamp(&row["captured"]);let live=neutral_stamp(&row["live"]);let mut query=PreparedRegionQueryJob::new(captured,point,0.0,captured.flatness).unwrap();query.advance(&regions,captured,1).unwrap();let work=query.work;
  if row["accepted"].as_bool().unwrap(){while !query.advance(&regions,live,grant).unwrap().done{}assert_eq!(query.result(live).unwrap(),source["expected"].as_bool().unwrap());}
  else{assert!(query.advance(&regions,live,grant).unwrap_err().contains("authority"));assert_eq!(query.work,work);assert!(query.result(captured).unwrap_err().contains("authority"));assert!(query.advance(&regions,captured,grant).is_err());}
  assert_eq!(regions,before);
 }}
 let captured=stamp(regions.flatness);let mut ready=PreparedRegionQueryJob::new(captured,point,0.0,regions.flatness).unwrap();while !ready.advance(&regions,captured,4096).unwrap().done{}assert!(ready.result(PreparedRegionStamp{build:captured.build-1,..captured}).unwrap_err().contains("authority"));
 let mut query=PreparedRegionQueryJob::new(captured,point,0.0,regions.flatness).unwrap();let mut changed=regions.clone();changed.flatness*=2.0;assert!(query.advance(&changed,captured,1).unwrap_err().contains("precision"));assert_eq!(query.work,0);assert!(query.result(captured).unwrap_err().contains("precision"));
 for invalid in [PreparedRegionStamp{build:0,..captured},PreparedRegionStamp{entry:1024,..captured},PreparedRegionStamp{flatness:f64::NAN,..captured}]{assert!(PreparedRegionQueryJob::new(invalid,point,0.0,regions.flatness).is_err());}
 let mut close=PaintedRegionsCloseJob::new(regions);while !close.advance(7).unwrap().done{}let mut close=PaintedRegionsCloseJob::new(changed);while !close.advance(7).unwrap().done{}
 eprintln!("[DEBUG] Native metadata-only queries checked 24 neutral full-width source/build/entry/precision authorities and stale publication; cursor_bytes={}",std::mem::size_of::<PreparedRegionQueryJob>());
}

#[test]
fn prepared_regions_stroke_cancel_actual_union_sources_frontiers_and_partial_output_in_every_phase(){
 let source=&sources()[6];let segments:Vec<crate::PathSegment>=serde_json::from_value(source["segments"].clone()).unwrap();let phases:Vec<String>=serde_json::from_str(include_str!("../../🧫️fixtures/🧹️retirement/🖊️stroke/🔣️.json")).unwrap();
 for phase in phases{for grant in [1,7,4096]{let mut job=PaintedPathPrepareJob::new(input(source)).unwrap();let mut reached=false;for _ in 0..2000000{if job.stroke_canonical.as_ref().is_some_and(|child|child.phase==phase){reached=true;break;}job.advance(1,|at|segments.get(at).cloned()).unwrap();}assert!(reached,"{phase}");let child=job.stroke_canonical.as_ref().unwrap();let owners=(child.source.len(),child.current.len(),child.next.len(),child.active.len(),child.combined.len(),child.region.contours.len(),child.segments.len(),child.child.is_some(),child.child_retirement.is_some());job.cancel();let child=job.stroke_canonical.as_ref().unwrap();assert_eq!(owners,(child.source.len(),child.current.len(),child.next.len(),child.active.len(),child.combined.len(),child.region.contours.len(),child.segments.len(),child.child.is_some(),child.child_retirement.is_some()));let(mut close,output)=job.into_retirement();assert!(output.is_none());let mut work=0;while !close.terminal_is_empty(){let p=close.advance(grant).unwrap();assert!(p.work>work&&p.work-work<=grant as u64);work=p.work;}assert!(close.job.is_none());eprintln!("[DEBUG] Native painted stroke cancelled phase={phase} grant={grant} actual_retirement_work={work} terminal_empty=true");}}
}
