import {existsSync as testingSchemaExists} from "node:fs";
/** 🤝️ Original semantic result loans preserve native payload custody through a bounded borrow. */
import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import {applyPatch} from "fast-json-patch";
import {existsSync,readFileSync} from "node:fs";
test("original semantic outcome loans retain all payload pages until the borrow ends and exact closure follows",async()=>{
 expect(existsSync(new URL("../🧬️schema/🔣️.json",import.meta.url))).toBe(false);
 const law=await Bun.file(new URL("../🧫️fixtures/🔣️.json",import.meta.url)).json();const db=new Database(":memory:");try{db.run("CREATE TABLE loans(variant TEXT,pages INTEGER,stage INTEGER,original INTEGER,borrowed INTEGER)");for(const variant of law.variants)for(const pages of law.pages){let row={original:1,borrowed:0};for(let stage=0;stage<4;stage++){if(stage===1)row=applyPatch(row,[{op:"replace",path:"/borrowed",value:1}],true).newDocument;if(stage===2)row=applyPatch(row,[{op:"replace",path:"/borrowed",value:0}],true).newDocument;if(stage===3)row=applyPatch(row,[{op:"replace",path:"/original",value:0}],true).newDocument;db.query("INSERT INTO loans VALUES(?,?,?,?,?)").run(variant,pages,stage,row.original,row.borrowed);}}expect(db.query("SELECT count(*) AS n FROM loans WHERE stage=1 AND original=1 AND borrowed=1").get()).toEqual({n:18});expect(db.query("SELECT count(*) AS n FROM loans WHERE stage=2 AND original=1 AND borrowed=0").get()).toEqual({n:18});expect(db.query("SELECT count(*) AS n FROM loans WHERE original=0 AND borrowed=1").get()).toEqual({n:0});}finally{db.close();}const file=new URL("../🦀️.rs",import.meta.url);expect(existsSync(file)).toBe(true);const source=readFileSync(file,"utf8");expect(readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8").includes("fn borrow_outcome")).toBe(true);expect(source.includes("pub trait RetainedInteractiveJob")).toBe(false);expect(source.includes("pub enum JobOutcomeBorrow<'a>")).toBe(true);expect(source.includes("cx.consume_retained")).toBe(true);expect(source.includes("job.step(cx)")).toBe(true);console.log("[DEBUG] SQLite/RFC6902 original semantic six-variant loan wholeCorpusSchema=false retains same payload custody until borrow ends; independent original full4096 policy");
});

test("original checked-out receipt is borrowed before parent admission and returned exactly once",async()=>{expect(testingSchemaExists(new URL("../../../👷️worker/🎟️turn/🤝️receipt/🧬️schema/🔣️.json",import.meta.url))).toBe(false);const law=await Bun.file(new URL("../../../👷️worker/🎟️turn/🤝️receipt/🧫️fixtures/🔣️.json",import.meta.url)).json();const db=new Database(":memory:");try{for(const row of law.cases){const p=row.parentRemaining,a=law.actual;const verdict=db.query("SELECT (?1>=?6 AND ?2>=?7 AND ?3>=?8 AND ?4>=?9 AND ?5>0)AS accepted").get(...p,...a)as{accepted:number};expect(!!verdict.accepted).toBe(row.accepted);expect(row.pendingAfter).toBe(!row.accepted);expect(row.recipientAfter).toEqual(row.accepted?a:[0,0,0,0]);expect(row.repeatTake).toBe(false);}}finally{db.close();}const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");expect(source.includes("pub fn checked_out_retained_step_receipt(&self)")).toBe(true);expect(source.includes("authority.retained_receipt_pending.then_some((&authority.issued_retained,&authority.retained_step_progress))")).toBe(true);console.log("[DEBUG] Independent SQLite six original receipt views immutable issued grant/actual progress, parent remaining allaxes, refused originalheld, funded once-only");});
