import {test,expect} from "bun:test";
import {Database} from "bun:sqlite";
import {readFileSync,existsSync} from "node:fs";
import Ajv from "ajv";
import {join} from "node:path";
import {parseSqliteDatabaseSchema,exportSqliteDatabase,importSqliteDatabase,type SqliteDatabase,type SqliteValue} from "../../../../../../../🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
type Fixture={rows:Record<string,(string|number|null)[][]>;rowsTotal:number;identityOffset:number;edit:{table:string;column:string;value:string};blobSizes?:string[];clocks?:{actor:string;physicalMs:string;logical:string}[];interiorControl?:{textUnit:string;repeat:number;utf8Bytes:number}};
type SafeIntegerQuery={safeIntegers(value:true):{all():unknown[]}};
const quote=(value:string)=>'"'+value.replaceAll('"','""')+'"';
export function authoredSnapshotSqliteContract(directory:string):void{
 test("neutral control categories retain independent relational ownership and Unicode bytes",()=>{const fixture=JSON.parse(readFileSync(new URL("../../../🪶️sqlite/🧫️fixtures/⚠️refusal/🔣️.json",import.meta.url),"utf8"))as{parent:number;label:string;labelUtf8Bytes:number;cases:{id:string;owner:number;maximumBytes:number;cancel:boolean;expectedKind:string|null}[]};const sql=readFileSync(new URL("../../../🪶️sqlite/🧫️fixtures/⚠️refusal/🗄️.sql",import.meta.url),"utf8");expect(Buffer.byteLength(fixture.label,"utf8")).toBe(fixture.labelUtf8Bytes);for(const sample of fixture.cases){const database=new Database(":memory:");try{database.exec(sql);database.query("INSERT INTO space_field_parent VALUES (?)").run(fixture.parent);database.query("INSERT INTO space_field_child VALUES (1,?,0,?)").run(sample.owner,fixture.label);expect(database.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(database.query("PRAGMA foreign_key_check").all().length).toBe(sample.expectedKind==="invalidValue"?1:0);expect(database.query("SELECT length(CAST(label AS BLOB)) AS bytes FROM space_field_child").get()).toEqual({bytes:fixture.labelUtf8Bytes});}finally{database.close();}}});
 const sql=readFileSync(join(directory,"🪶️sqlite/🗄️.sql"),"utf8"),f=JSON.parse(readFileSync(join(directory,"🧫️fixtures/🪶️sqlite/🔣️.json"),"utf8"))as Fixture;
 const schema=parseSqliteDatabaseSchema(sql);
 const expected:SqliteDatabase={tables:schema.tables.map(table=>({...table,rows:f.rows[table.name]!.map(row=>({rowid:BigInt(row[0] as number),values:row.map(value=>typeof value==="number"?BigInt(value):value)}))}))};
 function independent():Database{const d=new Database(":memory:");d.exec("PRAGMA foreign_keys=ON");d.exec(sql);d.exec("PRAGMA application_id=1397576526; PRAGMA user_version=1");for(const table of expected.tables){const statement=d.query("INSERT INTO "+quote(table.name)+" VALUES ("+table.rows[0]!.values.map(()=>"?").join(",")+")");for(const row of table.rows)statement.run(...row.values as (null|string|bigint)[]);}return d;}
 function healthy(d:Database):void{expect(d.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(d.query("PRAGMA foreign_key_check").all()).toEqual([]);}
 if(f.interiorControl)test("independent Unicode octet measurement preserves the interior cancellation specimen",async()=>{const specimen=f.interiorControl!,text=specimen.textUnit.repeat(specimen.repeat),d=independent();try{expect(Buffer.byteLength(text,"utf8")).toBe(specimen.utf8Bytes);d.query("UPDATE "+quote(f.edit.table)+" SET "+quote(f.edit.column)+"=?").run(text);healthy(d);const measured=d.query("SELECT length(CAST("+quote(f.edit.column)+" AS BLOB)) AS bytes FROM "+quote(f.edit.table)).all()as{bytes:number}[];expect(measured.every(row=>row.bytes===specimen.utf8Bytes)).toBe(true);const imported=await importSqliteDatabase(d.serialize()),column=(d.query("PRAGMA table_info("+quote(f.edit.table)+")").all()as{name:string}[]).findIndex(row=>row.name===f.edit.column);expect(imported.tables.find(table=>table.name===f.edit.table)!.rows.every(row=>row.values[column]===text)).toBe(true);}finally{d.close();}});
 test("independently authored semantic SQLite preserves every literal owned field",async()=>{const d=Database.deserialize(await exportSqliteDatabase(expected));try{healthy(d);let count=0;for(const table of expected.tables){const rows=(d.query("SELECT * FROM "+quote(table.name)+" ORDER BY id")as unknown as SafeIntegerQuery).safeIntegers(true).all()as Record<string,SqliteValue>[];count+=rows.length;expect<readonly (readonly SqliteValue[])[]>(rows.map(row=>Object.values(row))).toEqual(table.rows.map(row=>row.values));}expect(count).toBe(f.rowsTotal);}finally{d.close();}});
 test("independent writer and consistent surrogate renumbering preserve typed cells",async()=>{const d=independent();try{healthy(d);expect(await importSqliteDatabase(d.serialize())).toEqual(expected);d.exec("PRAGMA foreign_keys=OFF");for(const table of expected.tables){const columns=new Set((d.query("PRAGMA foreign_key_list("+quote(table.name)+")").all()as{from:string}[]).map(row=>row.from).filter(name=>name!=="id"));d.exec("UPDATE "+quote(table.name)+" SET "+["id=id+"+f.identityOffset,...[...columns].map(name=>quote(name)+"="+quote(name)+"+"+f.identityOffset)].join(","));}healthy(d);const decoded=await importSqliteDatabase(d.serialize());for(let i=0;i<decoded.tables.length;i++){const table=decoded.tables[i]!,before=expected.tables[i]!;expect(table.rows.map(row=>row.rowid)).toEqual(before.rows.map(row=>row.rowid+BigInt(f.identityOffset)));const changes=new Set(["id",...(d.query("PRAGMA foreign_key_list("+quote(table.name)+")").all()as{from:string}[]).map(row=>row.from)]);const names=(d.query("PRAGMA table_info("+quote(table.name)+")").all()as{name:string}[]).map(row=>row.name);expect<readonly (readonly SqliteValue[])[]>(table.rows.map(row=>row.values.map((value,j)=>changes.has(names[j]!)&&value!==null?(value as bigint)-BigInt(f.identityOffset):value))).toEqual(before.rows.map(row=>row.values));}}finally{d.close();}});
 test("independent SQL edits remain directly editable semantic fields",async()=>{const d=independent();try{d.query("UPDATE "+quote(f.edit.table)+" SET "+quote(f.edit.column)+"=?").run(f.edit.value);healthy(d);const database=await importSqliteDatabase(d.serialize());const column=(d.query("PRAGMA table_info("+quote(f.edit.table)+")").all()as{name:string}[]).findIndex(c=>c.name===f.edit.column);expect(column).toBeGreaterThan(0);expect(database.tables.find(t=>t.name===f.edit.table)!.rows.every(row=>row.values[column]===f.edit.value)).toBe(true);}finally{d.close();}});
 test("declared full unsigned words agree with independent BigInt oracle",()=>{const d=independent();try{if(f.blobSizes){const rows=(d.query("SELECT size_high,size_low FROM collection_blob_body ORDER BY id")as unknown as SafeIntegerQuery).safeIntegers(true).all()as{size_high:bigint;size_low:bigint}[];expect(rows.map(row=>((row.size_high<<32n)|row.size_low).toString())).toEqual(f.blobSizes);}if(f.clocks){const rows=(d.query("SELECT * FROM space_history_timestamp ORDER BY id")as unknown as SafeIntegerQuery).safeIntegers(true).all()as Record<string,bigint>[];expect(rows.map(row=>({actor:((row.actor_high!<<32n)|row.actor_low!).toString(),physicalMs:((row.physical_ms_high!<<32n)|row.physical_ms_low!).toString(),logical:((row.logical_high!<<32n)|row.logical_low!).toString()}))).toEqual(f.clocks);}healthy(d);}finally{d.close();}});
}

/** 📏️ Validates each real owner's borrowed preflight contract against independent SQLite and UTF-8 measurements. */
export function authoredSnapshotPreflightContract(directory:string):void{
 test("public native preflight admits only borrowed scratch and guards the real typed owner",()=>{
  const path=join(directory,"🧫️fixtures/🪶️sqlite/📏️preflight/🔣️.json");
  expect(existsSync(path)).toBe(true);
  const facet=JSON.parse(readFileSync(path,"utf8")) as {owner:string;table:string;column:string;textUnit:string;repeat:number;utf8Bytes:number;cancelAt:number;rows:number;schemaBytes:number;scratch:string;result:string;bounds:string[];encodings:string[];sourceUnchanged:boolean};
  const schema=JSON.parse(readFileSync(join(directory,"🪶️sqlite/📏️preflight/🧬️schema/🔣️.json"),"utf8"));
  const validate=new Ajv({strict:true}).compile(schema);
  expect(validate(facet)).toBe(true);
  for(const wrong of [{...facet,scratch:"copiedPayload"},{...facet,result:"encodedOutput"},{...facet,sourceUnchanged:false},{...facet,encodings:["binary"]},{...facet,extra:true}])expect(validate(wrong)).toBe(false);
  const sql=readFileSync(join(directory,"🪶️sqlite/🗄️.sql"),"utf8"),fixture=JSON.parse(readFileSync(join(directory,"🧫️fixtures/🪶️sqlite/🔣️.json"),"utf8")) as Fixture;
  const text=facet.textUnit.repeat(facet.repeat),database=new Database(":memory:");
  try{
   database.exec("PRAGMA foreign_keys=ON");database.exec(sql);
   for(const [name,rows] of Object.entries(fixture.rows))for(const row of rows)database.query("INSERT INTO "+quote(name)+" VALUES ("+row.map(()=>"?").join(",")+")").run(...row);
   let rows=0;for(const name of Object.keys(fixture.rows))rows+=(database.query("SELECT count(*) AS count FROM "+quote(name)).get() as {count:number}).count;
   expect(rows).toBe(facet.rows);expect(rows).toBe(fixture.rowsTotal);
   expect(Buffer.byteLength(sql,"utf8")).toBe(facet.schemaBytes);
   expect(Buffer.byteLength(text,"utf8")).toBe(facet.utf8Bytes);expect(new TextEncoder().encode(text).byteLength).toBe(facet.utf8Bytes);
   expect(facet.cancelAt).toBeLessThan(facet.utf8Bytes);expect(Buffer.byteLength(facet.textUnit,"utf8")).toBeLessThan(facet.cancelAt);
   database.query("UPDATE "+quote(facet.table)+" SET "+quote(facet.column)+"=?").run(text);
   expect(database.query("SELECT length(CAST("+quote(facet.column)+" AS BLOB)) AS bytes FROM "+quote(facet.table)).all().every(row=>(row as {bytes:number}).bytes===facet.utf8Bytes)).toBe(true);
   expect(database.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(database.query("PRAGMA foreign_key_check").all()).toEqual([]);
   const reopened=Database.deserialize(database.serialize());try{expect(reopened.query("SELECT "+quote(facet.column)+" AS literal FROM "+quote(facet.table)).all().every(row=>(row as {literal:string}).literal===text)).toBe(true);}finally{reopened.close();}
  }finally{database.close();}
 });
}
