#[test]
fn owned_operation_source_retirement_preserves_independent_currencies(){
 use semio_framework_value::{ErasedSnapshotRetirement,NativeEncodeControl,retained_clone::{RetainedCloneGrant,RetainedCloneStep}};
 use protocol::io::binary::operation_bytes::{OwnedOperationBytes,OperationByteOutput};
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/♻️source-currencies/🔣️.json")).unwrap();assert_eq!(fixture["sourceBytes"],8194);assert_eq!(fixture["maximumCopyBytes"],1);assert_eq!(fixture["maximumReleaseBytes"],4096);assert_eq!(fixture["maximumAllocationBytes"],65536);
 let mut owner=OwnedOperationBytes::try_new(8194,65536).unwrap();let mut allow=|_|true;let mut control=NativeEncodeControl::new(65536,&mut allow);let(result,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{for _ in 0..8194{owner.write_bytes(b"x",&mut control)?;}Ok::<_,PackRefusal>(())});result.unwrap();assert_eq!(event.released_bytes,0);let backing=owner.allocated_bytes();assert_eq!(event.requested_bytes,backing);assert_eq!(control.owned_bytes(),backing);
 let demand=ErasedSnapshotRetirement::next_copy_byte_demand(&owner).unwrap();assert_eq!(demand,1);assert_eq!(ErasedSnapshotRetirement::next_release_byte_demand(&owner).unwrap(),0);assert_eq!(ErasedSnapshotRetirement::next_capacity_byte_demand(&owner,1).unwrap(),0);assert_eq!(ErasedSnapshotRetirement::next_depth_demand(&owner).unwrap(),1);
 for grant in[RetainedCloneGrant::default(),RetainedCloneGrant{maximum_items:1,maximum_release_bytes:4096,maximum_depth:1,..Default::default()},RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:1,..Default::default()}]{let length=owner.len();let(result,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||ErasedSnapshotRetirement::close_step(&mut owner,grant));if grant.maximum_depth==0&&grant.maximum_items!=0{assert!(result.is_err());}else{let progress=match result.unwrap(){RetainedCloneStep::Progress(progress)|RetainedCloneStep::Complete(progress)=>progress};assert_eq!(progress.copied_items,0)}assert_eq!(owner.len(),length);assert_eq!((event.requested_bytes,event.released_bytes),(0,0));}
 let mut copied=0;while owner.len()!=0{let(step,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||ErasedSnapshotRetirement::close_step(&mut owner,RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:1,maximum_depth:1,..Default::default()}).unwrap());let progress=match step{RetainedCloneStep::Progress(progress)|RetainedCloneStep::Complete(progress)=>progress};assert_eq!((progress.copied_items,progress.copied_bytes,progress.released_bytes),(1,1,0));assert_eq!((event.requested_bytes,event.released_bytes),(0,0));copied+=progress.copied_bytes;}assert_eq!(copied,8194);assert_eq!(owner.allocated_bytes(),backing);
 let mut released=0;for _ in 0..128{let demand=ErasedSnapshotRetirement::next_release_byte_demand(&owner).unwrap();assert!(demand<=4096);if demand!=0{for grant in[RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:4096,maximum_depth:1,..Default::default()},RetainedCloneGrant{maximum_items:1,maximum_release_bytes:demand-1,maximum_depth:1,..Default::default()}]{let(before,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||ErasedSnapshotRetirement::close_step(&mut owner,grant).unwrap());let progress=match before{RetainedCloneStep::Progress(progress)|RetainedCloneStep::Complete(progress)=>progress};assert_eq!(progress.released_bytes,0);assert_eq!((event.requested_bytes,event.released_bytes),(0,0));assert_eq!(ErasedSnapshotRetirement::next_release_byte_demand(&owner).unwrap(),demand);}}
 let(step,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||ErasedSnapshotRetirement::close_step(&mut owner,RetainedCloneGrant{maximum_items:1,maximum_release_bytes:demand,maximum_depth:1,..Default::default()}).unwrap());let progress=match step{RetainedCloneStep::Progress(progress)|RetainedCloneStep::Complete(progress)=>progress};assert!(!event.overflowed);assert_eq!(event.requested_bytes,0);assert_eq!(event.released_bytes,progress.released_bytes);assert_eq!(progress.copied_bytes,0);assert!(event.released_bytes<=4096&&event.largest_release_bytes<=4096);released+=event.released_bytes;if owner.terminal_is_empty(){break}}
 assert!(owner.terminal_is_empty());assert_eq!(released,backing);assert_eq!(ErasedSnapshotRetirement::next_copy_byte_demand(&owner).unwrap(),0);assert_eq!(ErasedSnapshotRetirement::next_release_byte_demand(&owner).unwrap(),0);assert_eq!(ErasedSnapshotRetirement::next_depth_demand(&owner).unwrap(),0);let(_,event)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(owner));assert_eq!((event.requested_bytes,event.released_bytes),(0,0));eprintln!("[DEBUG] original operation8194 backing={backing} copy8194 releases0; exact physical<=4096 independently funded and observed; zero terminal demands; separate currencies cannot substitute");
}
