    #[test]
    fn child_complete_group_source_candidate_accepted_ledger_retains_original_registry_sources(){
        mod registry{include!(concat!(env!("CARGO_MANIFEST_DIR"),"/@REGISTRY_PROVIDER@"));}
        use semio_framework_value::{ErasedSnapshotRetirement,SnapshotRetirementStep};
        use semio_framework_tool_machine::{ScrubLedger,ScrubInput,ToolStep,ToolAbortReason};
        use semio_framework_os_kernel::{ActorId,HybridLogicalTimestamp};
        use semio_framework_os_kernel::os_pack::codec::PackEncodeOptions;
        let fixture:serde_json::Value=serde_json::from_str(include_str!(concat!(env!("CARGO_MANIFEST_DIR"),"/@REGISTRY_FIXTURE@"))).unwrap();
        assert_eq!(fixture["sourceBytes"],8194);assert_eq!(fixture["maximumItems"],1);assert_eq!(fixture["maximumBytes"],4096);
        let reuse:serde_json::Value=serde_json::from_str(include_str!(concat!(env!("CARGO_MANIFEST_DIR"),"/@REGISTRY_REUSE_FIXTURE@"))).unwrap();assert_eq!(reuse["sourceBytes"],8194);assert_eq!(reuse["maximumAllocationBytes"],65536);assert_eq!(reuse["maximumItems"],1);assert_eq!(reuse["maximumBytes"],4096);assert_eq!(reuse["reusedIdentity"],3);
        fn child(control:&mut NativeEncodeControl<'_>)->paged_owner::PagedChildOwner{
            let options=PackEncodeOptions::default();let mut owner=paged_owner::PagedChildOwner::empty();
            for(field,text)in[(reader::ChildGroupText::Owner,"owner"),(reader::ChildGroupText::Slot,"slot"),(reader::ChildGroupText::ChildId,"child"),(reader::ChildGroupText::Schema,"child.empty")]{owner.read_metadata_from_encoding_source(field,&text,&options,control).unwrap();}
            let mut receipt=owner.produce_owned_operation(8194,&options,control,|_,output,control|{output.write_bytes(b"17",control)?;for _ in 0..8192{output.write_bytes(b" ",control)?;}Ok(())}).unwrap();
            receipt.read_first_schema_from_source(&"label.set-label",control).unwrap();
            for terminology in semio_framework_ui_locale::Terminology::ALL{for locale in semio_framework_ui_locale::Locale::ALL{receipt.read_label_from_source(terminology,locale,&"label",control).unwrap();}}
            eprintln!("[DEBUG] registry source before outer commit cumulative admitted bytes={}",control.owned_bytes());receipt.commit(control).unwrap();eprintln!("[DEBUG] registry full8194 source after commit cumulative={} retained={}",control.owned_bytes(),owner.allocated_bytes());owner
        }
        fn reconcile(owner:&mut registry::RetainedSourceRegistry<paged_owner::PagedChildOwner>,ledger:&ScrubLedger<registry::RetainedSourceIdentity>,control:&mut NativeEncodeControl<'_>)->Result<(),semio_framework_value::ValueError>{
            owner.reconcile(|identity,control|{for accepted in ledger.provisional(){control.checkpoint()?;control.step()?;if *accepted==identity{return Ok(true)}}Ok(false)},control)
        }
        for host_abort in[false,true]{
            let actor=ActorId("actor".into());let clock=|physical_ms|HybridLogicalTimestamp{actor:0,physical_ms,logical:0};let mut ledger=ScrubLedger::default();
            let mut allow=|_|true;let mut control=NativeEncodeControl::new(65536,&mut allow);let mut owner=registry::RetainedSourceRegistry::empty();
            let first=child(&mut control);let first_allocated=first.allocated_bytes();let first_pointer=first.operations[0].byte_ref(0).map(|byte|byte as *const u8).unwrap();let mut incoming=Some(first);let mut allow_zero=|_|true;let mut zero=NativeEncodeControl::new(0,&mut allow_zero);assert!(owner.insert(&mut incoming,&mut zero).is_err());assert_eq!(owner.retained_count(),0);assert!(owner.terminal_is_empty());assert_eq!(incoming.as_ref().unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(first_pointer));let one=owner.insert(&mut incoming,&mut control).unwrap();assert!(incoming.is_none());let scalar_clone=one.clone();let another_scalar_clone=scalar_clone.clone();assert_eq!(another_scalar_clone,one);
            ledger.send("window","tool",&actor,"base",ScrubInput::Tick{gesture:"press".into(),leaves:vec![one]},clock(1)).unwrap();reconcile(&mut owner,&ledger,&mut control).unwrap();
            assert_eq!(owner.borrow(one).unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(first_pointer));assert_eq!(owner.retained_count(),1);
            let second=child(&mut control);let second_pointer=second.operations[0].byte_ref(0).map(|byte|byte as *const u8).unwrap();let second_allocated=second.allocated_bytes();let mut incoming=Some(second);let continuation=control.pause().unwrap();let mut reject=|_|false;let mut rejected=NativeEncodeControl::resume(continuation,&mut reject).unwrap();
            assert!(owner.insert(&mut incoming,&mut rejected).is_err());assert_eq!(incoming.as_ref().unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(second_pointer));assert!(reconcile(&mut owner,&ledger,&mut rejected).is_err());assert_eq!(owner.borrow(one).unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(first_pointer));
            let continuation=rejected.pause().unwrap();let mut allow=|_|true;let mut control=NativeEncodeControl::resume(continuation,&mut allow).unwrap();let two=owner.insert(&mut incoming,&mut control).unwrap();assert!(incoming.is_none());assert_eq!(owner.retained_count(),2);
            ledger.send("window","tool",&actor,"base",ScrubInput::Tick{gesture:"press".into(),leaves:vec![two]},clock(2)).unwrap();
            assert!(owner.borrow(one).is_some());assert_eq!(ledger.provisional().copied().collect::<Vec<_>>(),vec![two]);reconcile(&mut owner,&ledger,&mut control).unwrap();assert!(owner.borrow(one).is_none());assert_eq!(owner.borrow(two).unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(second_pointer));assert!(owner.take(one,&mut control).is_err());
            assert_eq!(owner.close_step(0,4096).unwrap(),SnapshotRetirementStep::Pending{released_items:0,released_bytes:0});let mut displaced=0;
            for _ in 0..16384{if owner.retained_count()==1{break}match owner.close_step(1,4096).unwrap(){SnapshotRetirementStep::Pending{released_items,released_bytes}=>{assert!(released_items<=1&&released_bytes<=4096);displaced+=released_bytes;},SnapshotRetirementStep::Complete=>panic!("live accepted source disappeared"),SnapshotRetirementStep::Blocked=>panic!("admitted displaced original cannot block under1/4096")}}
            assert_eq!(owner.retained_count(),1);assert_eq!(displaced,first_allocated);assert_eq!(owner.borrow(two).unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(second_pointer));
            if host_abort{
                assert!(matches!(ledger.abort("window",Some("press"),ToolAbortReason::CaptureLost),ToolStep::Aborted(..)));assert!(ledger.is_empty());let mut incoming=Some(owner.take(two,&mut control).unwrap());assert_eq!(incoming.as_ref().unwrap().operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(second_pointer));reconcile(&mut owner,&ledger,&mut control).unwrap();assert!(owner.borrow(two).is_none());let metadata=owner.allocated_bytes();let mut second_released=0;
                for _ in 0..16384{match owner.close_step(1,4096).unwrap(){SnapshotRetirementStep::Pending{released_items,released_bytes}=>{assert!(released_items<=1&&released_bytes<=4096);second_released+=released_bytes;if released_items==0&&released_bytes==0{break}},SnapshotRetirementStep::Complete=>break,SnapshotRetirementStep::Blocked=>panic!("admitted aborted original cannot block under1/4096")}}
                assert_eq!(owner.retained_count(),0);let third_pointer=second_pointer;let third_allocated=second_allocated;let before_readmission=control.owned_bytes();let three=owner.insert(&mut incoming,&mut control).unwrap();assert!(incoming.is_none());assert!(control.owned_bytes()>=before_readmission&&control.owned_bytes()<=65536);
                ledger.send("window","tool",&actor,"base",ScrubInput::Tick{gesture:"new-press".into(),leaves:vec![three]},clock(3)).unwrap();let retained=owner.borrow(three).expect("open registry lost monotone identity after abort and bounded source drain");assert_eq!(retained.operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(third_pointer));assert_eq!(second_released,0);assert!(owner.allocated_bytes()>=metadata);reconcile(&mut owner,&ledger,&mut control).unwrap();
                let ToolStep::Committed(_,leaves)=ledger.send("window","tool",&actor,"base",ScrubInput::Commit{gesture:"new-press".into(),leaves:vec![three]},clock(4)).unwrap()else{panic!("reused open registry did not commit actual new press")};assert_eq!(leaves,vec![three]);let mut published=owner.take(three,&mut control).unwrap();assert_eq!(published.operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(third_pointer));assert_eq!(published.operations[0].len(),8194);reconcile(&mut owner,&ledger,&mut control).unwrap();assert!(owner.take(three,&mut control).is_err());assert_eq!(drain_retained(&mut published),third_allocated);let metadata=owner.allocated_bytes();owner.begin_close();assert_eq!(drain_retained(&mut owner),metadata);
                assert!(matches!(ledger.send("window","tool",&actor,"base",ScrubInput::Commit{gesture:"new-press".into(),leaves:vec![three]},clock(5)).unwrap(),ToolStep::Idle));
            }else{
                let ToolStep::Committed(_,leaves)=ledger.send("window","tool",&actor,"base",ScrubInput::Commit{gesture:"press".into(),leaves:vec![two]},clock(3)).unwrap()else{panic!("accepted release did not commit")};assert_eq!(leaves,vec![two]);assert!(ledger.is_empty());
                let mut published=owner.take(leaves[0],&mut control).unwrap();assert_eq!(published.operations[0].byte_ref(0).map(|byte|byte as *const u8),Some(second_pointer));assert_eq!(published.operations[0].len(),8194);assert_eq!(published.operations[0].byte_at(0),Some(b'1'));assert_eq!(published.operations[0].byte_at(1),Some(b'7'));for at in 2..8194{assert_eq!(published.operations[0].byte_at(at),Some(b' '));}
                reconcile(&mut owner,&ledger,&mut control).unwrap();assert!(owner.take(two,&mut control).is_err());assert!(matches!(ledger.send("window","tool",&actor,"base",ScrubInput::Commit{gesture:"press".into(),leaves:vec![two]},clock(4)).unwrap(),ToolStep::Idle));
                assert_eq!(drain_retained(&mut published),second_allocated);let metadata=owner.allocated_bytes();owner.begin_close();assert_eq!(drain_retained(&mut owner),metadata);
            }
            assert!(owner.terminal_is_empty());assert_eq!(owner.retained_count(),0);
        }
        eprintln!("[DEBUG] actual ScrubLedger scalar clones preserve original8194 sources; accepted tick displacement retires only absent original; extraction precedes accepted-ledger reconcile; commit transfers pointer once, late commit stays idle, host abort revokes authority first; all original/registry/publication allocations independently drain1/4096");
    }
