
#[test]
fn paged_semantic_text_parent_retains_original8194_actual_allocations_until4096_disposal(){
    use crate::{NativeDecodeControl,ErasedSnapshotRetirement,paged_text::PagedText,retirement::allocation_return::{ParentAllocationReturn,AllocationReturnStep}};
    let fixture:serde_json::Value=serde_json::from_str(include_str!(concat!(env!("CARGO_MANIFEST_DIR"),"/@TEXT_FIXTURE@"))).unwrap();let text=fixture["text"].as_str().unwrap().repeat(fixture["textBytes"].as_u64().unwrap()as usize);assert_eq!(text.len(),8194);assert_eq!(fixture["maximumItems"],1);assert_eq!(fixture["maximumBytes"],4096);
    let mut owner=PagedText::<{isize::MAX as usize}>::empty();let mut allow=|_|true;let mut decoding=NativeDecodeControl::new(65536,&mut allow);owner.read_from_source(&text.as_str(),&mut decoding).unwrap();assert!(owner.borrow().unwrap().bytes().eq(text.bytes()));let actual=owner.allocated_bytes();assert_eq!(decoding.owned_bytes(),actual);let mut parent=ParentAllocationReturn::<64>::try_new(4096,actual).unwrap();assert!(!owner.return_one(&mut parent,0).unwrap().progressed);assert_eq!(owner.byte_len(),8194);assert!(owner.borrow().is_ok());assert_eq!(parent.retained_bytes(),0);let mut returned=0;
    for _ in 0..8194+128{if owner.terminal_is_empty(){break;}let before=owner.allocated_bytes();let progress=owner.return_one(&mut parent,1).unwrap();assert!(progress.progressed);assert_eq!(before-owner.allocated_bytes(),progress.returned_allocation_bytes);returned+=progress.returned_allocation_bytes;assert!(owner.borrow().is_err());}assert!(owner.terminal_is_empty());assert_eq!(returned,actual);assert_eq!(parent.retained_bytes(),actual);assert!(!parent.terminal_is_empty());let mut physical=0;for _ in 0..128{match parent.close_step(1,4096){AllocationReturnStep::Complete=>break,AllocationReturnStep::Pending{released_items,released_bytes}=>{assert!(released_items<=1);assert!(released_bytes<=4096);physical+=released_bytes;}}}assert!(parent.terminal_is_empty());assert_eq!(physical,actual);
    println!("[DEBUG] original8194 paged semantic text returns actual source backing to preadmitted real parent with zero child physical credit, denies zero-item handoff without changing text borrow, and parent alone physically releases1/4096");
}
