
#[test]
fn paged_semantic_text_stream_formats_full8194_and_retains_every_refusal(){
    use crate::{paged_text::{PagedText,write_encoding_format},NativeEncodeControl,ValueError,ValueRefusalKind,ErasedSnapshotRetirement,SnapshotRetirementStep};
    let fixture:serde_json::Value=serde_json::from_str(include_str!(concat!(env!("CARGO_MANIFEST_DIR"),"/@TEXT_STREAM_FIXTURE@"))).unwrap();assert_eq!(fixture["sourceBytes"],8194);assert_eq!(fixture["maximumAllocationBytes"],65536);assert_eq!(fixture["initialAllocationBytes"],4096);assert_eq!(fixture["maximumItems"],1);assert_eq!(fixture["maximumBytes"],4096);let payload=std::iter::repeat_n('x',8181).collect::<String>();
    fn drain<const N:usize>(owner:&mut PagedText<N>)->usize{let mut released=0;for _ in 0..8194+128{match owner.close_step(1,4096).unwrap(){SnapshotRetirementStep::Complete=>break,SnapshotRetirementStep::Pending{released_items,released_bytes}=>{assert!(released_items<=1&&released_bytes<=4096);released+=released_bytes;},SnapshotRetirementStep::Blocked=>panic!("stream owner blocked")}}assert!(owner.terminal_is_empty());released}
    let mut owner=PagedText::<{isize::MAX as usize}>::empty();let mut allow=|_|true;let mut control=NativeEncodeControl::new(65536,&mut allow);owner.encode_with(8194,&mut control,|output|write_encoding_format(output,format_args!("Set label to {}",payload))).unwrap();let view=owner.borrow().unwrap();assert_eq!(view.byte_len(),8194);assert!(view.bytes().eq(b"Set label to ".iter().copied().chain(std::iter::repeat_n(b'x',8181))));assert_eq!(owner.allocated_bytes(),control.owned_bytes());let allocated=owner.allocated_bytes();assert_eq!(drain(&mut owner),allocated);
    for mode in["initial","interior","ignored","producer","segment"]{let mut owner=PagedText::<{isize::MAX as usize}>::empty();let mut callback=|progress:crate::native_encoding::NativeEncodeProgress|mode!="interior"||progress.completed<256;let mut control=NativeEncodeControl::new(if mode=="initial"{4096}else{65536},&mut callback);let result=owner.encode_with(if mode=="segment"{128}else{8194},&mut control,|output|{
        if mode=="ignored"{assert!(output.write_text(&payload).is_ok());assert!(output.write_text("too many octets after real prefix").is_err());return Ok(())}
        write_encoding_format(output,format_args!("Set label to {}",payload))?;if mode=="producer"{return Err(ValueError::new(ValueRefusalKind::Canceled,"whole semantic producer refused after full output"))}Ok(())
    });assert!(result.is_err(),"{mode}");assert!(owner.borrow().is_err(),"{mode}");assert_eq!(owner.allocated_bytes(),control.owned_bytes());if mode=="initial"{assert_eq!(owner.byte_len(),0);assert!(owner.allocated_bytes()>0&&owner.allocated_bytes()<=4096);}if mode=="interior"{assert!(owner.byte_len()>0&&owner.byte_len()<8194);}if mode=="producer"{assert_eq!(owner.byte_len(),8194);}if mode=="segment"{assert!(owner.byte_len()<=128);}let allocated=owner.allocated_bytes();assert_eq!(drain(&mut owner),allocated);}
    eprintln!("[DEBUG] semantic authored formatting owns full8194 directly at64k; actual initial4096, interior cancellation, ignored write refusal, producer refusal and segment refusal retain actual pages until1/4096 physical close");
}
