//! 🗣️ Drawing play app — the complete UI label set (constitutional: was `ui`'s Locale/Terminology region).

semio_framework_plugin::app_labels! {
    /// 🗣️ Complete UI label set for the drawing app; one field per label makes every locale combination compile-checked.
    pub struct DrawingPlayLabels {
        nodes: native_en "Path Nodes", native_de "Pfadknoten", reuse_en "Path Nodes", reuse_de "Pfadknoten";
        anchor: native_en "Anchor", native_de "Anker", reuse_en "Anchor", reuse_de "Anker";
        control_one: native_en "First Handle", native_de "Erster Griff", reuse_en "First Handle", reuse_de "Erster Griff";
        control_two: native_en "Second Handle", native_de "Zweiter Griff", reuse_en "Second Handle", reuse_de "Zweiter Griff";
        split_segment: native_en "Split Segment", native_de "Segment teilen", reuse_en "Split Segment", reuse_de "Segment teilen";
        curve_segment: native_en "Convert to Curve", native_de "In Kurve umwandeln", reuse_en "Convert to Curve", reuse_de "In Kurve umwandeln";
        straighten_segment: native_en "Straighten Segment", native_de "Segment begradigen", reuse_en "Straighten Segment", reuse_de "Segment begradigen";
        delete_node: native_en "Delete Node", native_de "Knoten löschen", reuse_en "Delete Node", reuse_de "Knoten löschen";
        reverse_path: native_en "Reverse Path", native_de "Pfadrichtung umkehren", reuse_en "Reverse Path", reuse_de "Pfadrichtung umkehren";
        close_contour: native_en "Close Contour", native_de "Kontur schließen", reuse_en "Close Contour", reuse_de "Kontur schließen";
        open_contour: native_en "Open Contour", native_de "Kontur öffnen", reuse_en "Open Contour", reuse_de "Kontur öffnen";
        join_contour: native_en "Join Next Contour", native_de "Mit nächster Kontur verbinden", reuse_en "Join Next Contour", reuse_de "Mit nächster Kontur verbinden";
        convert_to_path: native_en "Convert to Path", native_de "In Pfad umwandeln", reuse_en "Convert to Path", reuse_de "In Pfad umwandeln";
        blend_normal: native_en "Normal", native_de "Normal", reuse_en "Normal", reuse_de "Normal";
        blend_multiply: native_en "Multiply", native_de "Multiplizieren", reuse_en "Multiply", reuse_de "Multiplizieren";
        blend_screen: native_en "Screen", native_de "Negativ multiplizieren", reuse_en "Screen", reuse_de "Negativ multiplizieren";
        blend_overlay: native_en "Overlay", native_de "Überlagern", reuse_en "Overlay", reuse_de "Überlagern";
        blend_darken: native_en "Darken", native_de "Abdunkeln", reuse_en "Darken", reuse_de "Abdunkeln";
        blend_lighten: native_en "Lighten", native_de "Aufhellen", reuse_en "Lighten", reuse_de "Aufhellen";
        boolean_union: native_en "Union", native_de "Vereinigung", reuse_en "Union", reuse_de "Vereinigung";
        boolean_intersect: native_en "Intersection", native_de "Schnittmenge", reuse_en "Intersection", reuse_de "Schnittmenge";
        boolean_subtract: native_en "Subtract", native_de "Abziehen", reuse_en "Subtract", reuse_de "Abziehen";
        boolean_exclude: native_en "Exclude", native_de "Ausschließen", reuse_en "Exclude", reuse_de "Ausschließen";
        group: native_en "Group", native_de "Gruppieren", reuse_en "Group", reuse_de "Gruppieren";
        duplicate: native_en "Duplicate", native_de "Duplizieren", reuse_en "Duplicate", reuse_de "Duplizieren";
        delete: native_en "Delete", native_de "Löschen", reuse_en "Delete", reuse_de "Löschen";
        bring_front: native_en "Bring to Front", native_de "In den Vordergrund", reuse_en "Bring to Front", reuse_de "In den Vordergrund";
        send_back: native_en "Send to Back", native_de "In den Hintergrund", reuse_en "Send to Back", reuse_de "In den Hintergrund";
        align_left: native_en "Align Left", native_de "Links ausrichten", reuse_en "Align Left", reuse_de "Links ausrichten";
        align_center: native_en "Align Center", native_de "Horizontal zentrieren", reuse_en "Align Center", reuse_de "Horizontal zentrieren";
        align_right: native_en "Align Right", native_de "Rechts ausrichten", reuse_en "Align Right", reuse_de "Rechts ausrichten";
        align_top: native_en "Align Top", native_de "Oben ausrichten", reuse_en "Align Top", reuse_de "Oben ausrichten";
        align_middle: native_en "Align Middle", native_de "Vertikal zentrieren", reuse_en "Align Middle", reuse_de "Vertikal zentrieren";
        align_bottom: native_en "Align Bottom", native_de "Unten ausrichten", reuse_en "Align Bottom", reuse_de "Unten ausrichten";
        distribute_horizontal: native_en "Distribute Horizontally", native_de "Horizontal verteilen", reuse_en "Distribute Horizontally", reuse_de "Horizontal verteilen";
        distribute_vertical: native_en "Distribute Vertically", native_de "Vertikal verteilen", reuse_en "Distribute Vertically", reuse_de "Vertikal verteilen";
        arrange: native_en "Arrange", native_de "Anordnen", reuse_en "Arrange", reuse_de "Anordnen";
        mixed: native_en "Mixed", native_de "Gemischt", reuse_en "Mixed", reuse_de "Gemischt";
        select_hint: native_en "Select a layer on the canvas or in Layers to edit it.", native_de "Wähle eine Ebene auf der Leinwand oder in der Ebenenliste aus.", reuse_en "Select a layer on the canvas or in Layers to edit it.", reuse_de "Wähle eine Ebene auf der Leinwand oder in der Ebenenliste aus.";
        window_canvas: native_en "Canvas", native_de "Leinwand", reuse_en "Canvas", reuse_de "Leinwand";
        mode_edit: native_en "Edit", native_de "Bearbeiten", reuse_en "Edit", reuse_de "Bearbeiten";
        add_path: native_en "Add Path", native_de "Pfad hinzufügen", reuse_en "Add Path", reuse_de "Pfad hinzufügen";
        add_rectangle: native_en "Add Rectangle", native_de "Rechteck hinzufügen", reuse_en "Add Rectangle", reuse_de "Rechteck hinzufügen";
        add_text: native_en "Add Text", native_de "Text hinzufügen", reuse_en "Add Text", reuse_de "Text hinzufügen";
        add_group: native_en "Add Group", native_de "Gruppe hinzufügen", reuse_en "Add Group", reuse_de "Gruppe hinzufügen";
        add_boolean: native_en "Add Boolean", native_de "Boolean hinzufügen", reuse_en "Add Boolean", reuse_de "Boolean hinzufügen";
        empty_state: native_en "Drop layers here", native_de "Ebenen hier ablegen", reuse_en "Drop layers here", reuse_de "Ebenen hier ablegen";
        kind_path: native_en "Path", native_de "Pfad", reuse_en "Path", reuse_de "Pfad";
        kind_rectangle: native_en "Rectangle", native_de "Rechteck", reuse_en "Rectangle", reuse_de "Rechteck";
        kind_ellipse: native_en "Ellipse", native_de "Ellipse", reuse_en "Ellipse", reuse_de "Ellipse";
        kind_line: native_en "Line", native_de "Linie", reuse_en "Line", reuse_de "Linie";
        kind_polygon: native_en "Polygon", native_de "Polygon", reuse_en "Polygon", reuse_de "Polygon";
        kind_text: native_en "Text", native_de "Text", reuse_en "Text", reuse_de "Text";
        kind_image: native_en "Image", native_de "Bild", reuse_en "Image", reuse_de "Bild";
        kind_group: native_en "Group", native_de "Gruppe", reuse_en "Group", reuse_de "Gruppe";
        kind_boolean: native_en "Boolean", native_de "Boolean", reuse_en "Boolean", reuse_de "Boolean";
        kind_trace: native_en "Trace", native_de "Nachzeichnung", reuse_en "Trace", reuse_de "Nachzeichnung";
        boolean_operation: native_en "Boolean Mutation", native_de "Boolean-Mutation", reuse_en "Boolean Mutation", reuse_de "Boolean-Mutation";
        children: native_en "Children", native_de "Kinder", reuse_en "Children", reuse_de "Kinder";
        trace_threshold: native_en "Trace Threshold", native_de "Trace-Schwellenwert", reuse_en "Trace Threshold", reuse_de "Trace-Schwellenwert";
        simplify: native_en "Simplify", native_de "Vereinfachen", reuse_en "Simplify", reuse_de "Vereinfachen";
        source_key: native_en "Source Key", native_de "Quellschlüssel", reuse_en "Source Key", reuse_de "Quellschlüssel";
        width: native_en "Width", native_de "Breite", reuse_en "Width", reuse_de "Breite";
        height: native_en "Height", native_de "Höhe", reuse_en "Height", reuse_de "Höhe";
        content: native_en "Content", native_de "Inhalt", reuse_en "Content", reuse_de "Inhalt";
        size: native_en "Size", native_de "Größe", reuse_en "Size", reuse_de "Größe";
        segment_count: native_en "Segment Count", native_de "Segmentanzahl", reuse_en "Segment Count", reuse_de "Segmentanzahl";
        children_count: native_en "Children Count", native_de "Kinderanzahl", reuse_en "Children Count", reuse_de "Kinderanzahl";
        appearance: native_en "Appearance", native_de "Erscheinungsbild", reuse_en "Appearance", reuse_de "Erscheinungsbild";
        fill: native_en "Fill", native_de "Füllung", reuse_en "Fill", reuse_de "Füllung";
        fill_type: native_en "Fill Type", native_de "Füllungstyp", reuse_en "Fill Type", reuse_de "Füllungstyp";
        fill_none: native_en "None", native_de "Keine", reuse_en "None", reuse_de "Keine";
        fill_solid: native_en "Solid", native_de "Einfarbig", reuse_en "Solid", reuse_de "Einfarbig";
        fill_linear: native_en "Linear Gradient", native_de "Linearer Verlauf", reuse_en "Linear Gradient", reuse_de "Linearer Verlauf";
        fill_radial: native_en "Radial Gradient", native_de "Radialer Verlauf", reuse_en "Radial Gradient", reuse_de "Radialer Verlauf";
        gradient_stops: native_en "Gradient Stops", native_de "Verlaufspunkte", reuse_en "Gradient Stops", reuse_de "Verlaufspunkte";
        gradient_stop: native_en "Color Stop", native_de "Farbpunkt", reuse_en "Color Stop", reuse_de "Farbpunkt";
        stop_position: native_en "Position", native_de "Position", reuse_en "Position", reuse_de "Position";
        add_stop: native_en "Add Color Stop", native_de "Farbpunkt hinzufügen", reuse_en "Add Color Stop", reuse_de "Farbpunkt hinzufügen";
        remove_stop: native_en "Remove Color Stop", native_de "Farbpunkt entfernen", reuse_en "Remove Color Stop", reuse_de "Farbpunkt entfernen";
        gradient_start_x: native_en "Start X", native_de "Anfang X", reuse_en "Start X", reuse_de "Anfang X";
        gradient_start_y: native_en "Start Y", native_de "Anfang Y", reuse_en "Start Y", reuse_de "Anfang Y";
        gradient_end_x: native_en "End X", native_de "Ende X", reuse_en "End X", reuse_de "Ende X";
        gradient_end_y: native_en "End Y", native_de "Ende Y", reuse_en "End Y", reuse_de "Ende Y";
        gradient_center_x: native_en "Center X", native_de "Mittelpunkt X", reuse_en "Center X", reuse_de "Mittelpunkt X";
        gradient_center_y: native_en "Center Y", native_de "Mittelpunkt Y", reuse_en "Center Y", reuse_de "Mittelpunkt Y";
        gradient_radius: native_en "Radius", native_de "Radius", reuse_en "Radius", reuse_de "Radius";
        fill_alpha: native_en "Fill Alpha", native_de "Füllung Alpha", reuse_en "Fill Alpha", reuse_de "Füllung Alpha";
        fill_enabled: native_en "Fill Enabled", native_de "Füllung aktiv", reuse_en "Fill Enabled", reuse_de "Füllung aktiv";
        stroke_enabled: native_en "Stroke Enabled", native_de "Kontur aktiv", reuse_en "Stroke Enabled", reuse_de "Kontur aktiv";
        stroke_color: native_en "Stroke Color", native_de "Konturfarbe", reuse_en "Stroke Color", reuse_de "Konturfarbe";
        stroke_cap: native_en "Line Caps", native_de "Linienenden", reuse_en "Line Caps", reuse_de "Linienenden";
        stroke_join: native_en "Line Joins", native_de "Linienverbindungen", reuse_en "Line Joins", reuse_de "Linienverbindungen";
        stroke_dash: native_en "Dash Pattern (e.g. 8 4)", native_de "Strichmuster (z. B. 8 4)", reuse_en "Dash Pattern (e.g. 8 4)", reuse_de "Strichmuster (z. B. 8 4)";
        cap_butt: native_en "Flat", native_de "Flach", reuse_en "Flat", reuse_de "Flach";
        cap_square: native_en "Square", native_de "Quadratisch", reuse_en "Square", reuse_de "Quadratisch";
        stroke_round: native_en "Round", native_de "Rund", reuse_en "Round", reuse_de "Rund";
        join_miter: native_en "Miter", native_de "Gehrung", reuse_en "Miter", reuse_de "Gehrung";
        join_bevel: native_en "Bevel", native_de "Abgeschrägt", reuse_en "Bevel", reuse_de "Abgeschrägt";
        stroke_width: native_en "Stroke Width", native_de "Strichstärke", reuse_en "Stroke Width", reuse_de "Strichstärke";
        layer: native_en "Layer", native_de "Ebene", reuse_en "Layer", reuse_de "Ebene";
        name: native_en "Name", native_de "Name", reuse_en "Name", reuse_de "Name";
        opacity: native_en "Opacity", native_de "Deckkraft", reuse_en "Opacity", reuse_de "Deckkraft";
        blend_mode: native_en "Blend Mode", native_de "Mischmodus", reuse_en "Blend Mode", reuse_de "Mischmodus";
        visible: native_en "Visible", native_de "Sichtbar", reuse_en "Visible", reuse_de "Sichtbar";
        locked: native_en "Locked", native_de "Gesperrt", reuse_en "Locked", reuse_de "Gesperrt";
        orientation: native_en "Orientation", native_de "Ausrichtung", reuse_en "Orientation", reuse_de "Ausrichtung";
        position_x: native_en "Position X", native_de "Position X", reuse_en "Position X", reuse_de "Position X";
        position_y: native_en "Position Y", native_de "Position Y", reuse_en "Position Y", reuse_de "Position Y";
        scale_x: native_en "Scale X", native_de "Skalierung X", reuse_en "Scale X", reuse_de "Skalierung X";
        scale_y: native_en "Scale Y", native_de "Skalierung Y", reuse_en "Scale Y", reuse_de "Skalierung Y";
        rotation: native_en "Rotation", native_de "Rotation", reuse_en "Rotation", reuse_de "Rotation";
    }
}
