//! 🧰️ Original Kit reconstruction retains catalog, relationships, child handles and pin fields.
use super::{SemioKitSnapshot,SemioKitType,SemioKitDesign,SemioKitPiece,SemioKitConnection,SemioObjectSnapshot,SemioModelSnapshot,SemioValueSnapshot,SemioTransform,SemioPoint3,SemioQuaternion,identity,float_columns,kit_blob_size,validate_semio_child_identity};
use store::{ArtifactSqliteSnapshot,sqlite_snapshot::{SqliteDatabase,SqliteSnapshotControl,SqliteSnapshotPhase,artifact::{FloatRow,RowIndex,RowIndexStorage,reconstruct_text_into},transfer::{SchemaValidationStorage,validate_database_into,validate_component_into,reserve}}};
use semio_framework_value::{ValueError,ValueRefusalKind};
use semio_framework_artifact_reference::{ArtifactRef,ArtifactDialect};
#[derive(semio_framework_value::RetireOwned)]
struct Prefix{snapshot:Option<SemioKitSnapshot>,validation:SchemaValidationStorage,indices:[RowIndexStorage;9],orders:[Vec<usize>;7],unique:[Vec<usize>;4],design_unique:Vec<[Vec<usize>;2]>}
fn empty()->Prefix{Prefix{snapshot:Some(super::native_decoding::empty()),validation:SchemaValidationStorage::empty(),indices:std::array::from_fn(|_|RowIndexStorage::empty()),orders:std::array::from_fn(|_|Vec::new()),unique:std::array::from_fn(|_|Vec::new()),design_unique:Vec::new()}}
fn invalid(message:&'static str)->ValueError{ValueError::literal(ValueRefusalKind::InvalidValue,message)}
fn reference()->ArtifactRef{ArtifactRef{artifact_id:String::new(),dialect:ArtifactDialect{artifact_kind:String::new(),standard:String::new(),subset:String::new()}}}
fn reference_into(target:&mut ArtifactRef,references:&mut RowIndex<'_>,id:i64,control:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{let row=references.take(id,control)?.ok_or_else(||invalid("dangling or multiply owned Semio kit reference"))?;for(field,column)in [(&mut target.artifact_id,1),(&mut target.dialect.artifact_kind,2),(&mut target.dialect.standard,3),(&mut target.dialect.subset,4)]{reconstruct_text_into(field,control,row.text(column)?)?;}Ok(())}
fn children_into<S:Send+'static>(destination:&mut Vec<store::ArtifactChild<S>>,rows:&RowIndex<'_>,order:&[usize],subset:&str,references:&mut RowIndex<'_>,control:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{
*destination=reserve(order.len(),control)?;for &index in order{let row=rows.row(index)?;if row.integer(1)?!=1{return Err(invalid("invalid Semio kit child ownership or identity"))}destination.push(store::ArtifactChild::new(String::new(),reference()));let child=destination.last_mut().unwrap();reference_into(&mut child.target,references,row.integer(4)?,control)?;reconstruct_text_into(&mut child.child_id,control,row.text(3)?)?;validate_semio_child_identity(&child.child_id,&child.target,subset).map_err(|error|ValueError::new(ValueRefusalKind::InvalidValue,error))?;}Ok(())
}
/// 🧵️ Installs one complete original Kit prefix before any allocating or cancellable field operation.
pub(super)fn reconstruct(database:&SqliteDatabase,control:&mut SqliteSnapshotControl<'_>,declared:&str)->Result<SemioKitSnapshot,ValueError>{crate::standards::v1::subsets::base::io::sqlite::snapshot::native_decoding::workspace::reconstruct_projected(control,empty,|prefix,control|{
let phase=SqliteSnapshotPhase::ReconstructSnapshot;control.check_database(database,phase)?;validate_database_into(&mut prefix.validation,database,declared,phase,control)?;validate_component_into(&mut prefix.validation,database,SemioKitSnapshot::SQLITE_SCHEMA,phase,control)?;let document=super::single_float_row(database,"semio_kit_document")?;identity(document,2)?;if document.rowid!=1{return Err(invalid("invalid Semio kit document identifier"))}
let [type_s,design_s,piece_s,connection_s,reference_s,object_s,model_s,blob_s,representation_s]=&mut prefix.indices;
let types=RowIndex::new(type_s,database,"semio_kit_type",6,&[],control,"invalid Semio kit type identity")?;let designs=RowIndex::new(design_s,database,"semio_kit_design",5,&[],control,"invalid Semio kit design identity")?;let mut pieces=RowIndex::new(piece_s,database,"semio_kit_piece",15,float_columns("semio_kit_piece"),control,"invalid Semio kit piece identity")?;let mut connections=RowIndex::new(connection_s,database,"semio_kit_connection",8,&[],control,"invalid Semio kit connection identity")?;
let mut references=RowIndex::new(reference_s,database,"semio_kit_reference",5,&[],control,"invalid Semio kit reference identity")?;let objects=RowIndex::new(object_s,database,"semio_kit_object_child",5,&[],control,"invalid Semio kit object identity")?;let models=RowIndex::new(model_s,database,"semio_kit_model_child",5,&[],control,"invalid Semio kit model identity")?;let mut blobs=RowIndex::new(blob_s,database,"semio_kit_blob",4,&[],control,"invalid Semio kit blob identity")?;let representations=RowIndex::new(representation_s,database,"semio_kit_representation",8,&[],control,"invalid Semio kit representation identity")?;
let [type_order,design_order,piece_order,connection_order,object_order,model_order,representation_order]=&mut prefix.orders;types.ordered_into(type_order,2,control,"Semio kit type ordinals")?;designs.ordered_into(design_order,2,control,"Semio kit design ordinals")?;pieces.grouped_by_into(piece_order,2,control,"Semio kit piece ordinals",|row|Ok((0,Some(row.integer(1)?))))?;connections.grouped_by_into(connection_order,2,control,"Semio kit connection ordinals",|row|Ok((0,Some(row.integer(1)?))))?;objects.ordered_into(object_order,2,control,"Semio kit object ordinals")?;models.ordered_into(model_order,2,control,"Semio kit model ordinals")?;representations.ordered_into(representation_order,2,control,"Semio kit representation ordinals")?;
let [type_unique,design_unique,object_unique,model_unique]=&mut prefix.unique;for(rows,scratch)in [(&types,type_unique),(&designs,design_unique),(&objects,object_unique),(&models,model_unique)]{rows.unique_text(scratch,rows.indices(),3,control,"duplicate Semio kit native identifier")?;for &index in rows.indices(){if rows.row(index)?.integer(1)?!=1{return Err(invalid("invalid Semio kit native ownership"))}control.checkpoint(phase,index,rows.len())?;}}
for rows in [&pieces,&connections]{for &index in rows.indices(){if designs.get(rows.row(index)?.integer(1)?,control)?.is_none(){return Err(invalid("invalid Semio kit relationship owner"))}control.checkpoint(phase,index,rows.len())?;}}
for &index in references.indices(){let row=references.row(index)?;for column in 1..5{row.text(column)?;}control.checkpoint(phase,index,references.len())?;}for &index in blobs.indices(){let row=blobs.row(index)?;row.text(1)?;kit_blob_size(row.text(2)?)?;row.text(3)?;control.checkpoint(phase,index,blobs.len())?;}
let snapshot=prefix.snapshot.as_mut().unwrap();snapshot.types=reserve(type_order.len(),control)?;snapshot.designs=reserve(design_order.len(),control)?;prefix.design_unique=reserve(design_order.len(),control)?;
for &index in type_order.iter(){let row=types.row(index)?;snapshot.types.push(SemioKitType{id:String::new(),name:String::new(),category:String::new()});let kind=snapshot.types.last_mut().unwrap();for(field,column)in [(&mut kind.id,3),(&mut kind.name,4),(&mut kind.category,5)]{reconstruct_text_into(field,control,row.text(column)?)?;}}
for &index in design_order.iter(){let row=designs.row(index)?;snapshot.designs.push(SemioKitDesign{id:String::new(),name:String::new(),pieces:Vec::new(),connections:Vec::new()});prefix.design_unique.push([Vec::new(),Vec::new()]);let design=snapshot.designs.last_mut().unwrap();let [piece_unique,connection_unique]=prefix.design_unique.last_mut().unwrap();reconstruct_text_into(&mut design.id,control,row.text(3)?)?;reconstruct_text_into(&mut design.name,control,row.text(4)?)?;
let range=pieces.range_by(piece_order,(0,Some(row.rowid)),control,|row|Ok((0,Some(row.integer(1)?))))?;pieces.unique_text(piece_unique,&piece_order[range.clone()],3,control,"duplicate Semio kit piece identifier")?;design.pieces=reserve(range.len(),control)?;
for ordinal in range{let piece=pieces.take_index(piece_order[ordinal],control)?.ok_or_else(||invalid("duplicate Semio kit piece ownership"))?;let kind=types.get(piece.integer(4)?,control)?.ok_or_else(||invalid("dangling Semio kit piece type"))?;design.pieces.push(SemioKitPiece{id:String::new(),type_id:String::new(),transform:SemioTransform{translation:SemioPoint3{x:piece.real(5)?,y:piece.real(6)?,z:piece.real(7)?},rotation:SemioQuaternion{x:piece.real(8)?,y:piece.real(9)?,z:piece.real(10)?,w:piece.real(11)?},scale:SemioPoint3{x:piece.real(12)?,y:piece.real(13)?,z:piece.real(14)?}}});let native=design.pieces.last_mut().unwrap();reconstruct_text_into(&mut native.id,control,piece.text(3)?)?;reconstruct_text_into(&mut native.type_id,control,kind.text(3)?)?;}
let range=connections.range_by(connection_order,(0,Some(row.rowid)),control,|row|Ok((0,Some(row.integer(1)?))))?;connections.unique_text(connection_unique,&connection_order[range.clone()],3,control,"duplicate Semio kit connection identifier")?;design.connections=reserve(range.len(),control)?;
for ordinal in range{let row_c=connections.take_index(connection_order[ordinal],control)?.ok_or_else(||invalid("duplicate Semio kit connection ownership"))?;let connecting=pieces.get(row_c.integer(4)?,control)?.ok_or_else(||invalid("dangling Semio kit connecting piece"))?;let connected=pieces.get(row_c.integer(6)?,control)?.ok_or_else(||invalid("dangling Semio kit connected piece"))?;if connecting.integer(1)?!=row.rowid||connected.integer(1)?!=row.rowid{return Err(invalid("Semio kit connection crosses owning design"))}design.connections.push(SemioKitConnection{id:String::new(),connecting_piece_id:String::new(),connecting_port:String::new(),connected_piece_id:String::new(),connected_port:String::new()});let native=design.connections.last_mut().unwrap();for(field,text)in [(&mut native.id,row_c.text(3)?),(&mut native.connecting_piece_id,connecting.text(3)?),(&mut native.connecting_port,row_c.text(5)?),(&mut native.connected_piece_id,connected.text(3)?),(&mut native.connected_port,row_c.text(7)?)]{reconstruct_text_into(field,control,text)?;}
}
}
children_into::<SemioObjectSnapshot>(&mut snapshot.objects,&objects,object_order,"object",&mut references,control)?;children_into::<SemioModelSnapshot>(&mut snapshot.models,&models,model_order,"model",&mut references,control)?;let value=database.table("semio_kit_value_child")?;if !value.rows.is_empty(){let row=FloatRow::new(value.single_row()?,&[])?;identity(row,4)?;if row.integer(1)?!=1{return Err(invalid("invalid Semio kit value child owner"))}snapshot.properties=Some(store::ArtifactChild::<SemioValueSnapshot>::new(String::new(),reference()));let child=snapshot.properties.as_mut().unwrap();reference_into(&mut child.target,&mut references,row.integer(3)?,control)?;reconstruct_text_into(&mut child.child_id,control,row.text(2)?)?;validate_semio_child_identity(&child.child_id,&child.target,"value").map_err(|error|ValueError::new(ValueRefusalKind::InvalidValue,error))?;}
snapshot.representations=reserve(representation_order.len(),control)?;for &index in representation_order.iter(){let row=representations.row(index)?;if row.integer(1)?!=1{return Err(invalid("invalid Semio kit representation ownership"))}let checkpoint=row.optional_text(6)?;let blob=if row.is_null(7)?{None}else{Some(row.integer(7)?)};snapshot.representations.push(store::ArtifactLink{target:reference(),role:String::new(),pin:store::LinkPin::Head});let link=snapshot.representations.last_mut().unwrap();
match row.text(5)?{"head" if checkpoint.is_none()&&blob.is_none()=>{},"checkpoint" if blob.is_none()=>{let text=checkpoint.ok_or_else(||invalid("missing Semio kit checkpoint pin"))?;link.pin=store::LinkPin::Checkpoint{id:String::new()};let store::LinkPin::Checkpoint{id}=&mut link.pin else{unreachable!()};reconstruct_text_into(id,control,text)?;},"snapshot" if checkpoint.is_none()=>{let row=blobs.take(blob.ok_or_else(||invalid("missing Semio kit snapshot pin"))?,control)?.ok_or_else(||invalid("dangling or multiply owned Semio kit blob pin"))?;link.pin=store::LinkPin::Snapshot{blob:store::BlobRef{hash:String::new(),size:kit_blob_size(row.text(2)?)?,media_type:String::new()}};let store::LinkPin::Snapshot{blob}=&mut link.pin else{unreachable!()};reconstruct_text_into(&mut blob.hash,control,row.text(1)?)?;reconstruct_text_into(&mut blob.media_type,control,row.text(3)?)?;},_=>return Err(invalid("invalid Semio kit link pin shape"))}
reference_into(&mut link.target,&mut references,row.integer(4)?,control)?;let kind=types.get(row.integer(3)?,control)?.ok_or_else(||invalid("dangling Semio kit representation type role"))?;reconstruct_text_into(&mut link.role,control,kind.text(3)?)?;
}
if references.remaining()!=0||blobs.remaining()!=0||pieces.remaining()!=0||connections.remaining()!=0{return Err(invalid("orphan Semio kit reference or blob pin descriptor"))}reconstruct_text_into(&mut snapshot.schema,control,document.text(1)?)?;control.checkpoint(phase,1,1)
},|prefix|prefix.snapshot.take().unwrap())}
                           