import { toolJobFemNumericalMicrocursorExact } from "../../../../../📜️script.ts";

/** 🧪️ Faithful P6h false-positive mutations. */
export function toolJobFemNumericalMicrocursorSelfTests(sparse: string, mesh: string, analyses: string, model: string, elements: string, session: string, runtime: string): number {
  const exact = (s = sparse, m = mesh, a = analyses, mo = model, e = elements, se = session, r = runtime) => toolJobFemNumericalMicrocursorExact(s, m, a, mo, e, se, r);
  if (!exact()) throw new Error("[verify interactivity tool-jobs p6h] live structural fixture was falsely rejected.");
  const mutations: readonly [string, () => boolean][] = [
    ["LDLT whole column", () => exact(sparse.replace("self.advance_column_microcursor().is_err()", "ldlt_column(&self.state.a, self.state.column).is_err()"))],
    ["LDLT missing source cursor", () => exact(sparse.replaceAll("SourceEntry", "SourceBatch"))],
    ["LDLT missing max+1", () => exact(sparse.replace("const LDLT_MAXIMUM_ORDER: usize = 40;", ""))],
    ["LDLT silent default", () => exact(sparse.replace("if self.advance_column_microcursor().is_err()", "unwrap_or_default(); if self.advance_column_microcursor().is_err()"))],
    ["checkpoint revision loss", () => exact(sparse.replace("revision: operation.base_revision.0", "revision: 0"))],
    ["checkpoint seed loss", () => exact(sparse.replace("seed: operation.seed", "seed: 0"))],
    ["LDLT constructor preallocation restored", () => exact(sparse.replace("reserve_lane: u8", "workspace: Vec::with_capacity(n)"))],
    ["subspace whole iteration", () => exact(sparse.replace("let result = match self.state.work.stage", "self.iterate(); let result = match self.state.work.stage"))],
    ["subspace missing Jacobi cell", () => exact(sparse.replaceAll("JacobiRotateCell", "JacobiRotateSweep"))],
    ["subspace missing max+1", () => exact(sparse.replace("const SUBSPACE_MAXIMUM_ORDER: usize = 40;", ""))],
    ["subspace missing worker replay law", () => exact(sparse.replace("p6h_subspace_cancellation_is_observed_at_every_nested_stage_and_worker_replay_is_exact", "subspace_smoke"))],
    ["subspace constructor preallocation restored", () => exact(sparse.replace("initialization_cursor: usize", "preallocated: MatD"))],
    ["subspace whole preview serializer restored", () => exact(sparse.replace("fn advance_preview_entry(state: &mut SubspaceCheckpoint", "fn advance_preview_publication(state: &mut SubspaceCheckpoint"))],
    ["subspace displaced work dropped recursively", () => exact(sparse.replace("retiring_work: Option<SubspaceWork>", "self.state.work = SubspaceWork::empty()"))],
    ["checkpoint truncation law omitted", () => exact(sparse.replaceAll("NumericalCheckpointFault::Truncated", "NumericalCheckpointFault::Field"))],
    ["LDLT checkpoint tag omitted", () => exact(sparse.replaceAll('b"FEMLCP1\\0"', 'b"FEMLCP0\\0"'))],
    ["subspace checkpoint tag omitted", () => exact(sparse.replaceAll('b"FEMSCP1\\0"', 'b"FEMSCP0\\0"'))],
    ["checkpoint page cursor omitted", () => exact(sparse.replace("struct NumericalPageCursor", "struct NumericalBuffer"))],
    ["LDLT restore cursor omitted", () => exact(sparse.replace("pub struct LdltRestoreCursor", "struct LdltReplay"))],
    ["subspace restore cursor omitted", () => exact(sparse.replace("pub struct SubspaceRestoreCursor", "struct SubspaceReplay"))],
    ["retained checkpoint stream omitted", () => exact(sparse.replaceAll("JobPayloadStream::CheckpointState", "JobPayloadStream::Preview"))],
    ["direct page backing omitted", () => exact(sparse.replace("fn restore_u32_entry(", "fn restore_u32_entry_with_whole_page_copy("))],
    ["terminal result writer omitted", () => exact(sparse.replace("terminal_writer: Option<RetainedJobPayloadWriter>", "terminal_bytes: Vec<u8>"))],
    ["restore interrupted close omitted", () => exact(sparse.replaceAll("interrupted_restore.close_step(1, usize::MAX)", "drop(interrupted_restore)"))],
    ["whole publication buffer restored", () => exact(`${sparse}\npublication_bytes preview_bytes`)],
    ["mesh whole recovery", () => exact(sparse, mesh.replace("advance_constraint_recovery()", "recover_constraint()"))],
    ["mesh rebuilt edge collection", () => exact(sparse, mesh.replace("match self.advance_constraint_recovery()", "triangulation.edges(); match self.advance_constraint_recovery()"))],
    ["mesh missing edge retirement", () => exact(sparse, mesh.replaceAll("RetireFormerEdge", "ForgetFormerEdge"))],
    ["mesh owner credit lost", () => exact(sparse, mesh, analyses, model, elements, session.replaceAll("roots: 3", "roots: 2"))],
    ["element whole matrix", () => exact(sparse, mesh, analyses.replace("element.mounted_stiffness_cell(&context, row, column)", "Some(element.stiffness_global(&context).get(row, column))"))],
    ["element missing multiply cell", () => exact(sparse, mesh, analyses.replaceAll("LocalStiffnessMultiplyCell", "LocalStiffnessMatrix"))],
    ["element family omitted", () => exact(sparse, mesh, analyses, model, elements.replace("fn mounted_stiffness_cell(", "fn removed_mounted_stiffness_cell("))],
    ["element parity law omitted", () => exact(sparse, mesh, analyses, model, elements.replace("p6h_mounted_element_fixed_schema_cells_match_batch_and_reject_maximum_plus_one", "element_smoke"))],
    ["element interruption law omitted", () => exact(sparse, mesh, analyses.replace("p6h_element_stiffness_microcursor_deadline_stale_cancel_close_and_stage_laws", "element_smoke"))],
    ["checkpoint owner page loop", () => exact(sparse.replace("if let Some(value) = values.get(cursor.item)", "while let Some(value) = values.get(cursor.item)"))],
    ["checkpoint pair page loop", () => exact(sparse.replace("if let Some((index, value)) = values.get(cursor.item)", "while let Some((index, value)) = values.get(cursor.item)"))],
    ["restore scalar page loop", () => exact(sparse.replace("if item < length {\n        owner.push(read_checkpoint_u32", "while item < length {\n        owner.push(read_checkpoint_u32"))],
    ["restore contiguous page copy", () => exact(sparse.replace("self.decode_page_entry(source)", "{ let mut bytes = [0u8; 16384]; bytes[..source.len()].copy_from_slice(source); self.decode_page_entry(&bytes[..source.len()]) }"))],
    ["weak checkpoint identity", () => exact(sparse.replace("self == Self::from_operation(operation)", "self.operation == operation.operation.0"))],
    ["checkpoint page admission fallthrough", () => exact(sparse.replace("return match writer.begin_staged_page(context)", "match writer.begin_staged_page(context)"))],
    ["mesh post-work fuel", () => exact(sparse, mesh.replace("context.consume_fuel(1);\n        match self.stage", "match self.stage"))],
    ["mesh prepare batch loop", () => exact(sparse, mesh.replace("let complete = match self.preparation", "for _ in 0..8 {} let complete = match self.preparation"))],
    ["mesh insertion batch loop", () => exact(sparse, mesh.replace("triangulation.insert_next();", "while triangulation.insert_next() {}"))],
    ["mesh whole point lookup", () => exact(sparse, mesh.replace("self.point_index.get(cursor.lookup)", "self.point_index.iter().find(|_| true)"))],
    ["mesh decorative direct recovery law", () => exact(sparse, mesh.replaceAll("job.step(&mut context)", "job.advance_constraint_recovery()"))],
    ["element borrowed construction law", () => exact(sparse, mesh, analyses.replace("AssemblyJobConstruction::new_owned(Arc::new(model), operation, 1)", "AssemblyJob::new(&model, operation, 1)"))],
    ["element Bar2 law removed", () => exact(sparse, mesh, analyses.replace("let bar = Bar2", "let bar = AxialSpring"))],
    ["element numerical identity removed", () => exact(sparse, mesh, analyses.replace("mounted stiffness mismatch", "mounted stiffness smoke"))],
    ["element max+1 production admission bypassed", () => exact(sparse, mesh, analyses.replace("reserve_exact_owner_page(&mut rejected", "reserve_exact_owner_smoke(&mut rejected"))],
    ["element rejected backing identity omitted", () => exact(sparse, mesh, analyses.replaceAll("rejected.as_ptr()", "std::ptr::null()"))],
    ["LDLT contributor library search restored", () => exact(sparse.replace("let comparison = self.state.l_cols[active][mid].0.cmp", "let _ = self.state.l_cols[active].binary_search_by_key(&(column as u32), |entry| entry.0); let comparison = self.state.l_cols[active][mid].0.cmp"))],
    ["LDLT contributor bounds omitted", () => exact(sparse.replaceAll("lookup_lower", "lookup_start"))],
    ["subspace constructor factor scan restored", () => exact(sparse.replace("let factor_pages_valid = k_factor.l_cols.capacity()", "let _all = k_factor.l_cols.iter().all(|column| column.is_empty()); let factor_pages_valid = k_factor.l_cols.capacity()"))],
    ["subspace retained factor validation bypassed", () => exact(sparse.replace("!self.state.factor_validation_complete", "false"))],
    ["mesh preparation point scan restored", () => exact(sparse, mesh.replace("self.point_indices.get(self.point_lookup_cursor)", "self.point_indices.iter().find(|_| true)"))],
    ["mesh preparation polygon kernel restored", () => exact(sparse, mesh.replace("self.advance_grid_classification(domain)", "point_in_polygon([0.0; 2], &domain.outer); self.advance_grid_classification(domain)"))],
    ["mesh mounted bounds scan restored", () => exact(sparse, mesh.replace("fn begin_mounted(points: Vec<[f64; 2]>, maximum_triangles: usize) -> Result<Self, MeshError> {", "fn begin_mounted(points: Vec<[f64; 2]>, maximum_triangles: usize) -> Result<Self, MeshError> { for point in &points { let _ = point; }"))],
    ["mesh mounted insertion sort restored", () => exact(sparse, mesh.replace("match self.mounted_initialization.stage", "self.insertion_order.sort_by_key(|index| *index); match self.mounted_initialization.stage"))],
    ["mesh finish retain restored", () => exact(sparse, mesh.replace("match self.finish.stage", "self.triangles.retain(|_| true); match self.finish.stage"))],
    ["mesh finish whole sort restored", () => exact(sparse, mesh.replace("match self.finish.stage", "self.triangles.sort_unstable(); match self.finish.stage"))],
    ["mesh contiguous publication restored", () => exact(sparse, mesh.replace("let mut scalar = [0; 8];", "let _bytes = Vec::with_capacity(self.mesh.points.len()); let mut scalar = [0; 8];"))],
    ["mesh publication point loop restored", () => exact(sparse, mesh.replace("let mut scalar = [0; 8];", "for point in &self.mesh.points { let _ = point; } let mut scalar = [0; 8];"))],
    ["mesh adjacency retirement loop restored", () => exact(sparse, mesh.replace("let owner = &mut slot.adjacent[self.constraint_retire_adjacency_cursor];", "for owner in &mut slot.adjacent { let _ = owner; } let owner = &mut slot.adjacent[self.constraint_retire_adjacency_cursor];"))],
    ["assembly DOF whole lookup restored", () => exact(sparse, mesh, analyses.replace("self.plan.dof_map.order.get(build.lookup_cursor)", "self.plan.dof_map.get(node_id, element.dofs_per_node()[dof_index]).map(|index| &self.plan.dof_map.order[index])"))],
    ["assembly node whole lookup restored", () => exact(sparse, mesh, analyses.replace("self.model.node(build.lookup_cursor)", "self.model.dynamic().and_then(|model| model.nodes.iter().find(|node| node.id == node_id))"))],
    ["assembly partition minimum scan restored", () => exact(sparse, mesh, analyses.replace("let partition = &self.state.partitions[partition_index];", "let _ = self.state.partitions.iter().filter_map(|_| None::<AssemblyTriplet>).min_by_key(|entry| entry.sequence); let partition = &self.state.partitions[partition_index];"))],
    ["mesh cursor execution law omitted", () => exact(sparse, mesh.replace("p6h_mounted_mesh_preparation_initialization_finish_publication_interrupt_replay_timing_and_close", "mesh_cursor_smoke"))],
    ["assembly cursor execution law omitted", () => exact(sparse, mesh, analyses.replace("p6h_owned_assembly_lookup_partition_scan_transfer_interrupt_replay_and_timing", "assembly_cursor_smoke"))],
    ["staged page close omitted", () => exact(sparse, mesh, analyses, model, elements, session, runtime.replace("if let Some((ledger, _, length)) = self.staged.as_ref()", "if false"))],
    ["staged page transfer omitted", () => exact(sparse, mesh, analyses, model, elements, session, runtime.replaceAll("self.staged.take()", "None"))],
  ];
  for (const [name, mutation] of mutations) if (mutation()) throw new Error(`[verify interactivity tool-jobs p6h] mutation ${name} was falsely accepted.`);
  return mutations.length;
}
