/** 🔊️ Full owned binary32 sample words retain all native floating states. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import f from "../../🧫️fixtures/🪶️sqlite/🔣️.json";
import type {SemioAudioSnapshot} from "../../🟦️.ts";
import {SEMIO_AUDIO_SQLITE_SCHEMA,semioAudioSnapshotToSqliteDatabase,semioAudioSnapshotFromSqliteDatabase} from "../../🪶️sqlite/🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const input:SemioAudioSnapshot={schema:f.schema,sampleRate:f.sampleRate,format:"f64",channels:f.channels.map(channel=>({samples:channel.map(bits=>({bits}))})),tags:f.tags.map(([key,value])=>({key:key!,value:value!}))};
test("Semio audio independent sample bits queries and edited exact scalar",async()=>{expect(SEMIO_AUDIO_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../../🪶️sqlite/🗄️.sql",import.meta.url)).text());const db=Database.deserialize(await exportSqliteDatabase(await semioAudioSnapshotToSqliteDatabase(input)));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(f.query).all()).toHaveLength(9);expect(await semioAudioSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_audio_sample SET value=NULL,ieee754_bits=? WHERE id=1").run(0x7fa12345);const expected=structuredClone(input);expected.channels[0]!.samples[0]={bits:0x7fa12345};expect(await semioAudioSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(expected);}finally{db.close();}});
test("Semio audio IEEE mismatch, relation widths, limits, cancellation and all formats",async()=>{const d=await semioAudioSnapshotToSqliteDatabase(input);for(const mutate of [(x:any)=>x.tables[2].rows[0].values[3]=1,(x:any)=>x.tables[2].rows[0].values[4]=-1n,(x:any)=>x.tables[2].rows[0].values[1]=99n,(x:any)=>x.tables[1].rows[0].values[2]=99n,(x:any)=>x.tables[0].rows[0].values[2]=4294967296n]){const x=structuredClone(d);mutate(x);await expect(semioAudioSnapshotFromSqliteDatabase(x)).rejects.toThrow();}await expect(semioAudioSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();await expect(semioAudioSnapshotFromSqliteDatabase(d,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();c.abort();await expect(semioAudioSnapshotToSqliteDatabase(input,{signal:c.signal})).rejects.toThrow();for(const format of ["pcm8","pcm16","pcm24","pcm32","f32","f64"]as const){const empty={...input,format,channels:[{samples:[]}],tags:[]};expect(await semioAudioSnapshotFromSqliteDatabase(await semioAudioSnapshotToSqliteDatabase(empty))).toEqual(empty);}});

test("Semio audio native cancellation frontier has independent exact signaling sample words",()=>{const {collectionItems,cancelAfter,sampleWord}=f.nativeAdmission;const bytes=new Uint8Array(collectionItems*4);const view=new DataView(bytes.buffer);const db=new Database(":memory:");try{db.run("CREATE TABLE samples(ordinal INTEGER PRIMARY KEY,bits INTEGER)");for(let ordinal=0;ordinal<collectionItems;ordinal++){view.setUint32(ordinal*4,sampleWord,true);db.query("INSERT INTO samples VALUES(?,?)").run(ordinal,view.getUint32(ordinal*4,true));}expect(db.query("SELECT count(*) count FROM samples").get()).toEqual({count:collectionItems});expect(db.query("SELECT bits FROM samples WHERE ordinal=?").get(cancelAfter)).toEqual({bits:sampleWord});expect(Buffer.from(bytes).readUInt32LE(cancelAfter*4)).toBe(sampleWord);}finally{db.close();}});
