//! 🎟️ Checks the exact original retained identity and receipt at the host component boundary.
use super::{wit_reactor,PluginHostError,TurnFault};
use semio_framework::kernel::{RetainedTurnInput,RetainedTurnReceipt};
use semio_framework_value::{RetainedCloneGrant,RetainedCloneProgress};
pub(super) fn input_to_wit(input:RetainedTurnInput)->wit_reactor::RetainedTurnInput{wit_reactor::RetainedTurnInput{operation:input.operation,generation:input.generation,epoch:input.epoch,grant:grant_to_wit(input.grant)}}
fn grant_to_wit(grant:RetainedCloneGrant)->wit_reactor::RetainedGrant{wit_reactor::RetainedGrant{maximum_items:grant.maximum_items as u64,maximum_copy_bytes:grant.maximum_copy_bytes as u64,maximum_capacity_bytes:grant.maximum_capacity_bytes as u64,maximum_release_bytes:grant.maximum_release_bytes as u64,maximum_depth:grant.maximum_depth as u64}}
fn extent(value:u64)->Result<usize,TurnFault>{usize::try_from(value).map_err(|_|fault("retained component extent exceeds original native address space"))}
fn grant_from_wit(grant:wit_reactor::RetainedGrant)->Result<RetainedCloneGrant,TurnFault>{Ok(RetainedCloneGrant{maximum_items:extent(grant.maximum_items)?,maximum_copy_bytes:extent(grant.maximum_copy_bytes)?,maximum_capacity_bytes:extent(grant.maximum_capacity_bytes)?,maximum_release_bytes:extent(grant.maximum_release_bytes)?,maximum_depth:extent(grant.maximum_depth)?})}
pub(super) fn receipt_from_wit(receipt:wit_reactor::RetainedTurnReceipt,original:RetainedTurnInput)->Result<RetainedTurnReceipt,TurnFault>{let input=RetainedTurnInput{operation:receipt.input.operation,generation:receipt.input.generation,epoch:receipt.input.epoch,grant:grant_from_wit(receipt.input.grant)?};let spent=RetainedCloneProgress{copied_items:extent(receipt.spent.copied_items)?,copied_bytes:extent(receipt.spent.copied_bytes)?,retained_capacity_bytes:extent(receipt.spent.retained_capacity_bytes)?,released_bytes:extent(receipt.spent.released_bytes)?};let receipt=RetainedTurnReceipt{input,spent,remaining:grant_from_wit(receipt.remaining)?};receipt.validate_for(original).map_err(|_|fault("returned retained component receipt does not conserve its original supplied identity and currencies"))?;Ok(receipt)}
fn fault(message:&'static str)->TurnFault{TurnFault::Host(PluginHostError::Plugin(message.to_string()))}
fn input_from_wit(input:wit_reactor::RetainedTurnInput)->Result<RetainedTurnInput,TurnFault>{Ok(RetainedTurnInput{operation:input.operation,generation:input.generation,epoch:input.epoch,grant:grant_from_wit(input.grant)?})}
fn progress_from_wit(spent:wit_reactor::RetainedProgress)->Result<RetainedCloneProgress,TurnFault>{Ok(RetainedCloneProgress{copied_items:extent(spent.copied_items)?,copied_bytes:extent(spent.copied_bytes)?,retained_capacity_bytes:extent(spent.retained_capacity_bytes)?,released_bytes:extent(spent.released_bytes)?})}
fn cause_from_wit(cause:wit_reactor::ActorAuthorityRefusal)->semio_framework_value::ValueRefusalKind{use semio_framework_value::ValueRefusalKind as Native;use wit_reactor::ActorAuthorityRefusal as Wire;match cause{Wire::InvalidValue=>Native::InvalidValue,Wire::Canceled=>Native::Canceled,Wire::OwnershipLimit=>Native::OwnershipLimit,Wire::AllocationFailed=>Native::AllocationFailed,Wire::WorkLimit=>Native::WorkLimit,Wire::DepthLimit=>Native::DepthLimit,Wire::UnsupportedOwner=>Native::UnsupportedOwner,Wire::InvariantViolated=>Native::InvariantViolated}}
/// 🌱️ Returns the raw admission tuple before any Host readiness or receipt validation.
pub(super) fn admission_from_wit(call:wit_reactor::ActorAdmissionCall)->Result<crate::reactor::original_actor_context::OriginalActorAdmissionReply,TurnFault>{Ok(crate::reactor::original_actor_context::OriginalActorAdmissionReply{input:input_from_wit(call.input)?,spent:progress_from_wit(call.spent)?,ready:call.ready,refusal:call.refusal.map(cause_from_wit)})}
/// ♻️ A blocked or refused close keeps its exact actual child delta in the required receiving ABI.
pub(super) fn close_from_wit(call:wit_reactor::ActorContextCloseCall)->Result<crate::reactor::original_actor_context::OriginalActorCloseReply,TurnFault>{Ok(crate::reactor::original_actor_context::OriginalActorCloseReply{input:input_from_wit(call.input)?,spent:progress_from_wit(call.spent)?,complete:call.complete,blocked:call.blocked,refusal:call.refusal.map(cause_from_wit)})}
/// 🧾️ Semantic failure is a scalar marker while the same typed Fault remains in guest custody.
pub(super) fn failure_from_wit(call:wit_reactor::ActorCallRefusal)->TurnFault{let original=(||Ok::<_,TurnFault>(crate::reactor::original_actor_context::OriginalActorFixedCall{input:input_from_wit(call.input)?,spent:progress_from_wit(call.spent)?,kind:crate::reactor::original_actor_context::OriginalActorFixedKind::Failure{authority:match call.failure{wit_reactor::ActorCallFailure::Authority(cause)=>Some(cause_from_wit(cause)),wit_reactor::ActorCallFailure::Semantic=>None}}}))();match original{Ok(call)=>TurnFault::ActorCall(call),Err(error)=>error}}
