// source: model/v1/model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.semio.model.v1.Decision');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.semio.model.v1.LayoutModification');
goog.require('proto.semio.model.v1.LayoutModificationStrategy');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.semio.model.v1.Decision = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.semio.model.v1.Decision, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.semio.model.v1.Decision.displayName = 'proto.semio.model.v1.Decision';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.semio.model.v1.Decision.prototype.toObject = function(opt_includeInstance) {
  return proto.semio.model.v1.Decision.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.semio.model.v1.Decision} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.model.v1.Decision.toObject = function(includeInstance, msg) {
  var f, obj = {
    modification: (f = msg.getModification()) && proto.semio.model.v1.LayoutModification.toObject(includeInstance, f),
    strategy: (f = msg.getStrategy()) && proto.semio.model.v1.LayoutModificationStrategy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.semio.model.v1.Decision}
 */
proto.semio.model.v1.Decision.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.semio.model.v1.Decision;
  return proto.semio.model.v1.Decision.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.semio.model.v1.Decision} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.semio.model.v1.Decision}
 */
proto.semio.model.v1.Decision.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.semio.model.v1.LayoutModification;
      reader.readMessage(value,proto.semio.model.v1.LayoutModification.deserializeBinaryFromReader);
      msg.setModification(value);
      break;
    case 2:
      var value = new proto.semio.model.v1.LayoutModificationStrategy;
      reader.readMessage(value,proto.semio.model.v1.LayoutModificationStrategy.deserializeBinaryFromReader);
      msg.setStrategy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.semio.model.v1.Decision.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.semio.model.v1.Decision.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.semio.model.v1.Decision} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.model.v1.Decision.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModification();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.semio.model.v1.LayoutModification.serializeBinaryToWriter
    );
  }
  f = message.getStrategy();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.semio.model.v1.LayoutModificationStrategy.serializeBinaryToWriter
    );
  }
};


/**
 * optional LayoutModification modification = 1;
 * @return {?proto.semio.model.v1.LayoutModification}
 */
proto.semio.model.v1.Decision.prototype.getModification = function() {
  return /** @type{?proto.semio.model.v1.LayoutModification} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.LayoutModification, 1));
};


/**
 * @param {?proto.semio.model.v1.LayoutModification|undefined} value
 * @return {!proto.semio.model.v1.Decision} returns this
*/
proto.semio.model.v1.Decision.prototype.setModification = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.model.v1.Decision} returns this
 */
proto.semio.model.v1.Decision.prototype.clearModification = function() {
  return this.setModification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.model.v1.Decision.prototype.hasModification = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LayoutModificationStrategy strategy = 2;
 * @return {?proto.semio.model.v1.LayoutModificationStrategy}
 */
proto.semio.model.v1.Decision.prototype.getStrategy = function() {
  return /** @type{?proto.semio.model.v1.LayoutModificationStrategy} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.LayoutModificationStrategy, 2));
};


/**
 * @param {?proto.semio.model.v1.LayoutModificationStrategy|undefined} value
 * @return {!proto.semio.model.v1.Decision} returns this
*/
proto.semio.model.v1.Decision.prototype.setStrategy = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.model.v1.Decision} returns this
 */
proto.semio.model.v1.Decision.prototype.clearStrategy = function() {
  return this.setStrategy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.model.v1.Decision.prototype.hasStrategy = function() {
  return jspb.Message.getField(this, 2) != null;
};


