// source: model/v1/model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.semio.model.v1.Pose');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.semio.model.v1.Point');
goog.require('proto.semio.model.v1.Quaternion');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.semio.model.v1.Pose = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.semio.model.v1.Pose, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.semio.model.v1.Pose.displayName = 'proto.semio.model.v1.Pose';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.semio.model.v1.Pose.prototype.toObject = function(opt_includeInstance) {
  return proto.semio.model.v1.Pose.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.semio.model.v1.Pose} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.model.v1.Pose.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointOfView: (f = msg.getPointOfView()) && proto.semio.model.v1.Point.toObject(includeInstance, f),
    view: (f = msg.getView()) && proto.semio.model.v1.Quaternion.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.semio.model.v1.Pose}
 */
proto.semio.model.v1.Pose.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.semio.model.v1.Pose;
  return proto.semio.model.v1.Pose.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.semio.model.v1.Pose} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.semio.model.v1.Pose}
 */
proto.semio.model.v1.Pose.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.semio.model.v1.Point;
      reader.readMessage(value,proto.semio.model.v1.Point.deserializeBinaryFromReader);
      msg.setPointOfView(value);
      break;
    case 2:
      var value = new proto.semio.model.v1.Quaternion;
      reader.readMessage(value,proto.semio.model.v1.Quaternion.deserializeBinaryFromReader);
      msg.setView(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.semio.model.v1.Pose.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.semio.model.v1.Pose.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.semio.model.v1.Pose} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.model.v1.Pose.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointOfView();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.semio.model.v1.Point.serializeBinaryToWriter
    );
  }
  f = message.getView();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.semio.model.v1.Quaternion.serializeBinaryToWriter
    );
  }
};


/**
 * optional Point point_of_view = 1;
 * @return {?proto.semio.model.v1.Point}
 */
proto.semio.model.v1.Pose.prototype.getPointOfView = function() {
  return /** @type{?proto.semio.model.v1.Point} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.Point, 1));
};


/**
 * @param {?proto.semio.model.v1.Point|undefined} value
 * @return {!proto.semio.model.v1.Pose} returns this
*/
proto.semio.model.v1.Pose.prototype.setPointOfView = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.model.v1.Pose} returns this
 */
proto.semio.model.v1.Pose.prototype.clearPointOfView = function() {
  return this.setPointOfView(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.model.v1.Pose.prototype.hasPointOfView = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Quaternion view = 2;
 * @return {?proto.semio.model.v1.Quaternion}
 */
proto.semio.model.v1.Pose.prototype.getView = function() {
  return /** @type{?proto.semio.model.v1.Quaternion} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.Quaternion, 2));
};


/**
 * @param {?proto.semio.model.v1.Quaternion|undefined} value
 * @return {!proto.semio.model.v1.Pose} returns this
*/
proto.semio.model.v1.Pose.prototype.setView = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.model.v1.Pose} returns this
 */
proto.semio.model.v1.Pose.prototype.clearView = function() {
  return this.setView(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.model.v1.Pose.prototype.hasView = function() {
  return jspb.Message.getField(this, 2) != null;
};


