// source: extension/translator/v1/translator.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.semio.server.v1.TranslateRepresentationRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.semio.model.v1.Pose');
goog.require('proto.semio.model.v1.Representation');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.semio.server.v1.TranslateRepresentationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.semio.server.v1.TranslateRepresentationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.semio.server.v1.TranslateRepresentationRequest.displayName = 'proto.semio.server.v1.TranslateRepresentationRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.semio.server.v1.TranslateRepresentationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.semio.server.v1.TranslateRepresentationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.server.v1.TranslateRepresentationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    representation: (f = msg.getRepresentation()) && proto.semio.model.v1.Representation.toObject(includeInstance, f),
    targetPose: (f = msg.getTargetPose()) && proto.semio.model.v1.Pose.toObject(includeInstance, f),
    sourcePose: (f = msg.getSourcePose()) && proto.semio.model.v1.Pose.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest}
 */
proto.semio.server.v1.TranslateRepresentationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.semio.server.v1.TranslateRepresentationRequest;
  return proto.semio.server.v1.TranslateRepresentationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.semio.server.v1.TranslateRepresentationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest}
 */
proto.semio.server.v1.TranslateRepresentationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.semio.model.v1.Representation;
      reader.readMessage(value,proto.semio.model.v1.Representation.deserializeBinaryFromReader);
      msg.setRepresentation(value);
      break;
    case 2:
      var value = new proto.semio.model.v1.Pose;
      reader.readMessage(value,proto.semio.model.v1.Pose.deserializeBinaryFromReader);
      msg.setTargetPose(value);
      break;
    case 3:
      var value = new proto.semio.model.v1.Pose;
      reader.readMessage(value,proto.semio.model.v1.Pose.deserializeBinaryFromReader);
      msg.setSourcePose(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.semio.server.v1.TranslateRepresentationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.semio.server.v1.TranslateRepresentationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.semio.server.v1.TranslateRepresentationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRepresentation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.semio.model.v1.Representation.serializeBinaryToWriter
    );
  }
  f = message.getTargetPose();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.semio.model.v1.Pose.serializeBinaryToWriter
    );
  }
  f = message.getSourcePose();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.semio.model.v1.Pose.serializeBinaryToWriter
    );
  }
};


/**
 * optional semio.model.v1.Representation representation = 1;
 * @return {?proto.semio.model.v1.Representation}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.getRepresentation = function() {
  return /** @type{?proto.semio.model.v1.Representation} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.Representation, 1));
};


/**
 * @param {?proto.semio.model.v1.Representation|undefined} value
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
*/
proto.semio.server.v1.TranslateRepresentationRequest.prototype.setRepresentation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.clearRepresentation = function() {
  return this.setRepresentation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.hasRepresentation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional semio.model.v1.Pose target_pose = 2;
 * @return {?proto.semio.model.v1.Pose}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.getTargetPose = function() {
  return /** @type{?proto.semio.model.v1.Pose} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.Pose, 2));
};


/**
 * @param {?proto.semio.model.v1.Pose|undefined} value
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
*/
proto.semio.server.v1.TranslateRepresentationRequest.prototype.setTargetPose = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.clearTargetPose = function() {
  return this.setTargetPose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.hasTargetPose = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional semio.model.v1.Pose source_pose = 3;
 * @return {?proto.semio.model.v1.Pose}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.getSourcePose = function() {
  return /** @type{?proto.semio.model.v1.Pose} */ (
    jspb.Message.getWrapperField(this, proto.semio.model.v1.Pose, 3));
};


/**
 * @param {?proto.semio.model.v1.Pose|undefined} value
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
*/
proto.semio.server.v1.TranslateRepresentationRequest.prototype.setSourcePose = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.semio.server.v1.TranslateRepresentationRequest} returns this
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.clearSourcePose = function() {
  return this.setSourcePose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.semio.server.v1.TranslateRepresentationRequest.prototype.hasSourcePose = function() {
  return jspb.Message.getField(this, 3) != null;
};


