import{readFileSync,writeFileSync,mkdirSync,openSync,writeSync,closeSync}from"node:fs";import{createHash}from"node:crypto";
const ticket=import.meta.dir+"/../..",path="C:/git/semio/🧰️framework/🛍️products/📓️print/🧬️schema/🔣️.json",fixturePath="C:/git/semio/🧰️framework/🛍️products/📓️print/🎮️commands/🧪️print-pipeline-verification/🧫️fixtures/🔓️api-freshness.json",before=readFileSync(path,"utf8"),fb=readFileSync(fixturePath,"utf8"),fixture=JSON.parse(fb),snapshot=JSON.parse(readFileSync(ticket+"/🗑️generated/printed-api-current-snapshot.json","utf8")),hash=(s:string)=>createHash("sha256").update(s).digest("hex");if(hash(before)!=="ccc2232de96a34f3e4cecf703e5bc65b3f08ec15d1819f1508ee3a64ab9cb0c2")throw Error("Schema source release changed");
let i=0;const objects=new Map<string,any>();
function ws(){while(/\s/.test(before[i]??"")&&i<before.length)i++;}
function str(){const start=i++;while(i<before.length){const c=before[i++];if(c==='\\'){i++;continue;}if(c==='"')return JSON.parse(before.slice(start,i));}throw Error("String");}
function value(keys:string[]){ws();if(before[i]==='{'){const start=i++,members:any[]=[];ws();while(before[i]!=='}'){const keyStart=i,key=str();ws();if(before[i++]!==':')throw Error("Colon");const valueStart=i;value([...keys,key]);members.push({key,keyStart,valueStart,end:i});ws();if(before[i]===','){i++;ws();}else if(before[i]!=='}')throw Error("Delimiter");}i++;objects.set(keys.join("\0"),{start,end:i,members});}else if(before[i]==='['){i++;ws();while(before[i]!==']'){value(keys);ws();if(before[i]===','){i++;ws();}else if(before[i]!==']')throw Error("Array");}i++;}else if(before[i]==='"')str();else{while(i<before.length&&!/[\s,}\]]/.test(before[i]))i++;}}
value([]);ws();if(i!==before.length)throw Error("Trailing");

const original=JSON.parse(before),expected=structuredClone(original),changes:any[]=[],edits:any[]=[],descriptor={syntax:"expression",type:"integer",minimum:1,default:5,description:{en:"Number of geographic palette levels, independently of vector integration steps; one level uses the palette midpoint.",de:"Anzahl der geografischen Palettenstufen unabhängig von den Vektorintegrationsschritten; eine Stufe nutzt die Palettenmitte."}};
for(const[family,scopes]of Object.entries(snapshot.scopes)as any){if(!scopes["semio / viz / geo / base"])continue;const options=expected["x-semio-family-options"][family].options,ownSteps=Object.entries(scopes).some(([scope,keys]:any)=>scope!=="semio / viz / geo / base"&&keys.includes("steps"));if(!options.steps||options.paletteSteps)throw Error(family);const node=objects.get(["x-semio-family-options",family,"options"].join("\0")),parts=new Map(node.members.map((m:any)=>[m.key,before.slice(m.keyStart,m.end)]));if(!ownSteps){changes.push({family,key:"steps",before:structuredClone(options.steps)});delete options.steps;parts.delete("steps");delete fixture.printed.nativeContracts[family].steps;}options.paletteSteps=structuredClone(descriptor);fixture.printed.nativeContracts[family].paletteSteps={type:"integer",syntax:"expression",default:"5"};changes.push({family,key:"paletteSteps",after:descriptor,retainedOwnSteps:ownSteps});parts.set("paletteSteps",JSON.stringify("paletteSteps")+": "+JSON.stringify(descriptor,null,2).replace(/\n/g,"\n        "));const body=[...parts].sort((a:any,b:any)=>a[0].localeCompare(b[0])).map((p:any)=>p[1]).join(",\n        ");edits.push({start:node.start,end:node.end,text:"{\n        "+body+"\n      }"});}
let after=before;for(const edit of edits.sort((a,b)=>b.start-a.start))after=after.slice(0,edit.start)+edit.text+after.slice(edit.end);const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;if(JSON.stringify(canonical(JSON.parse(after)))!==JSON.stringify(canonical(expected)))throw Error("Unexpected semantic mutation");if(JSON.stringify(expected["x-semio-family-options"]["spatial-vector-field"].options.steps)!==JSON.stringify(original["x-semio-family-options"]["spatial-vector-field"].options.steps))throw Error("Vector RK4 descriptor changed");
const retained=ticket+"/📥️authored-inputs/native-palette-descriptor-before";mkdirSync(retained,{recursive:true});writeFileSync(retained+"/🔣️.json",before);writeFileSync(retained+"/🔓️api-freshness.json",fb);writeFileSync(retained+"/descriptor-delta.json",JSON.stringify(changes,null,2));
function save(p:string,b:string,a:string){if(readFileSync(p,"utf8")!==b)throw Error("Concurrent mutation");const bytes=Buffer.from(a);if(bytes.length<Buffer.byteLength(b))throw Error("Unexpected shrink");const fd=openSync(p,"r+");try{let offset=0;while(offset<bytes.length)offset+=writeSync(fd,bytes,offset,bytes.length-offset,offset);}finally{closeSync(fd);}if(readFileSync(p,"utf8")!==a)throw Error("Exact byte roundtrip");}
save(path,before,after);const fa=JSON.stringify(fixture,null,2)+"\n";save(fixturePath,fb,fa);console.log(JSON.stringify({before:hash(before),after:hash(after),fixture:hash(fa),families:edits.length,removedBaseSteps:changes.filter(c=>c.key==='steps').length,retainedVectorOwnSteps:true}));