CREATE TABLE bmp_image (
 id INTEGER PRIMARY KEY CHECK (id = 1), schema TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL,
 row_order TEXT NOT NULL CHECK (row_order IN ('bottomUp','topDown')), profile TEXT NOT NULL,
 red_mask INTEGER NOT NULL, green_mask INTEGER NOT NULL, blue_mask INTEGER NOT NULL, alpha_mask INTEGER NOT NULL,
 x_pixels_per_meter INTEGER NOT NULL, y_pixels_per_meter INTEGER NOT NULL, colors_used INTEGER NOT NULL, colors_important INTEGER NOT NULL,
 reserved_1 INTEGER NOT NULL, reserved_2 INTEGER NOT NULL
);
CREATE TABLE bmp_palette_entry (id INTEGER PRIMARY KEY, image INTEGER NOT NULL REFERENCES bmp_image(id), ordinal INTEGER NOT NULL, b INTEGER NOT NULL, g INTEGER NOT NULL, r INTEGER NOT NULL, reserved INTEGER NOT NULL);
CREATE TABLE bmp_pixel_index (id INTEGER PRIMARY KEY, image INTEGER NOT NULL REFERENCES bmp_image(id), ordinal INTEGER NOT NULL, palette_index INTEGER NOT NULL);
CREATE TABLE bmp_pixel_sample (id INTEGER PRIMARY KEY, image INTEGER NOT NULL REFERENCES bmp_image(id), ordinal INTEGER NOT NULL, red INTEGER NOT NULL, green INTEGER NOT NULL, blue INTEGER NOT NULL, alpha INTEGER NOT NULL, reserved INTEGER NOT NULL);
CREATE TABLE bmp_gap_octet (id INTEGER PRIMARY KEY, image INTEGER NOT NULL REFERENCES bmp_image(id), ordinal INTEGER NOT NULL, value INTEGER NOT NULL);
CREATE TABLE bmp_trailer_octet (id INTEGER PRIMARY KEY, image INTEGER NOT NULL REFERENCES bmp_image(id), ordinal INTEGER NOT NULL, value INTEGER NOT NULL);
