[tool.poetry]
name = "semio"
version = "0.0.1"
description = "Use this package to develop Semio APIs in Python."
authors = ["Ueli Saluz <semio@posteo.org>"]
repository = "https://github.com/usalu/semio"
keywords = ["semio", "api", "development"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "*"
protobuf = "*"
grpcio-reflection = "^1.51.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
