[tool.poetry]
name = "semio"
version = "0.1.0"
description = "Semio enables designers to explicitly formalize design intent leading to a new way of designing."
authors = ["Ueli Saluz <semio@posteo.org>"]
license = "AGPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
grpcio = "^1.51.1"
protobuf = "^4.21.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
