[package]
name = "dag-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:dag"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "dag"
ports = { react = 6017, wgpu = 6117 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
dag = { path = "../../../app/dag/rs", package = "semio-s-app-dag" }
dag_ui = { path = "../../../app/dag/ui/rs", package = "semio-s-app-dag-ui" }
semio-framework-plugin = { path = "../../../../../../framework/product/os/module/plugin/rs", features = ["component-guest"], package = "semio-framework-plugin" }

