//! 🧊️ Admitted native BRep topology, analytic geometry, p-curves and all spline arrays.
use crate::standards::v1::subsets::base::schema::geometry::{SemioPoint2,SemioPoint3};
use crate::standards::v1::subsets::brep::schema::snapshot::{SemioBrepSnapshot,BrepVertex,BrepEdge,BrepLoop,BrepLoopEdge,BrepFace,BrepShell,BrepShellFace,BrepSolid,BrepSolidShell,BrepCoedge,BrepCurve,BrepCurve2,BrepSurface,STDIO_SEMIOBREP_DOCUMENT_SCHEMA};
use crate::standards::v1::subsets::base::io::sqlite::snapshot::native_decoding as native;
use semio_framework_value::native_decoding::NativeDecodeControl;
use semio_framework_value::{ValueError,ValueRefusalKind};
use store::sqlite_snapshot::{SqliteSnapshotControl,SqliteDatabaseLimits};
pub(crate) fn decode(payload:&store::io::IoPayload,control:&mut SqliteSnapshotControl<'_>,native_control:&mut semio_framework_value::NativeDecodeControl<'_>)->Result<SemioBrepSnapshot,ValueError>{
 let limits=control.limits();crate::standards::v1::subsets::brep::io::sqlite::snapshot::admit_layout(limits)?;
 let size=match payload{store::io::IoPayload::Binary(value)=>value.len(),store::io::IoPayload::Text(value)=>value.len()};if size>limits.max_file_bytes{return Err(ValueError::new(ValueRefusalKind::OwnershipLimit,"Semio Brep native input exceeds file limit"))}
 control.allocation_stage_native(store::sqlite_snapshot::SqliteSnapshotPhase::DecodeNative,|remaining,checkpoint|{
  let native_before=native_control.owned_bytes();let result=native_control.scoped_maximum(native_before.checked_add(remaining).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"native snapshot allowance overflow"))?,|native_control|{
  let result=(||->Result<SemioBrepSnapshot,ValueError>{let result=match payload{
   store::io::IoPayload::Binary(value)=>{let body=store::semio_format::unwrap_binary_controlled(value,STDIO_SEMIOBREP_DOCUMENT_SCHEMA,store::semio_format::Component::Pack,1,native_control).map_err(store::semio_format::SemioError::into_value_error)?;binary(body,native_control,limits)?},
   store::io::IoPayload::Text(value)=>{let body=store::semio_format::split_text_preamble_controlled(value,STDIO_SEMIOBREP_DOCUMENT_SCHEMA,store::semio_format::Component::Dsl,1,native_control).map_err(store::semio_format::SemioError::into_value_error)?;document(body,native_control,limits)?}
  };let result=native::Owned::new(result);native_control.checkpoint()?;Ok(result.take())})();result});(result,native_control.owned_bytes().saturating_sub(native_before))
 })?
}
fn f64(reader:&mut store::ByteReader<'_>)->Result<f64,ValueError>{reader.read_f64_le().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))}
fn point2(reader:&mut store::ByteReader<'_>)->Result<SemioPoint2,ValueError>{Ok(SemioPoint2{x:f64(reader)?,y:f64(reader)?})}
fn point3(reader:&mut store::ByteReader<'_>)->Result<SemioPoint3,ValueError>{Ok(SemioPoint3{x:f64(reader)?,y:f64(reader)?,z:f64(reader)?})}
fn boolean(reader:&mut store::ByteReader<'_>)->Result<bool,ValueError>{match reader.read_u8().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?{0=>Ok(false),1=>Ok(true),_=>Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native boolean"))}}
fn u32(reader:&mut store::ByteReader<'_>)->Result<u32,ValueError>{u32::try_from(reader.read_varint_u64().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?).map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"BRep native integer exceeds unsigned32"))}
fn numbers_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<Vec<f64>,ValueError>{native::binary_list(reader,control,limits,entities,|reader,_,_|f64(reader))}
fn curve_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepCurve,ValueError>{native::entities(entities,1,limits)?;Ok(match reader.read_u8().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?{
0=>BrepCurve::Line{origin:point3(reader)?,direction:point3(reader)?},1=>BrepCurve::Circle{center:point3(reader)?,axis:point3(reader)?,radius:f64(reader)?},2=>BrepCurve::Ellipse{center:point3(reader)?,axis:point3(reader)?,radius_major:f64(reader)?,radius_minor:f64(reader)?},
3=>{let control_points=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,_,_|point3(reader))?);let weights=native::Owned::new(numbers_binary(reader,control,limits,entities)?);let degree=u32(reader)?;let knots=native::Owned::new(numbers_binary(reader,control,limits,entities)?);BrepCurve::Nurbs{control_points:control_points.take(),weights:weights.take(),degree,knots:knots.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native curve kind"))})}
fn curve2_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepCurve2,ValueError>{native::entities(entities,1,limits)?;Ok(match reader.read_u8().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?{
0=>BrepCurve2::Line{origin:point2(reader)?,direction:point2(reader)?},1=>BrepCurve2::Circle{center:point2(reader)?,radius:f64(reader)?},2=>BrepCurve2::Ellipse{center:point2(reader)?,x_axis:point2(reader)?,radius_major:f64(reader)?,radius_minor:f64(reader)?},
3=>{let control_points=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,_,_|point2(reader))?);let weights=native::Owned::new(numbers_binary(reader,control,limits,entities)?);let degree=u32(reader)?;let knots=native::Owned::new(numbers_binary(reader,control,limits,entities)?);BrepCurve2::Nurbs{control_points:control_points.take(),weights:weights.take(),degree,knots:knots.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native p-curve kind"))})}
fn surface_binary(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepSurface,ValueError>{native::entities(entities,1,limits)?;Ok(match reader.read_u8().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?{
0=>BrepSurface::Plane{origin:point3(reader)?,normal:point3(reader)?},1=>BrepSurface::Cylinder{origin:point3(reader)?,axis:point3(reader)?,radius:f64(reader)?},2=>BrepSurface::Cone{origin:point3(reader)?,axis:point3(reader)?,radius:f64(reader)?,half_angle:f64(reader)?},3=>BrepSurface::Sphere{center:point3(reader)?,radius:f64(reader)?},4=>BrepSurface::Torus{center:point3(reader)?,axis:point3(reader)?,major_radius:f64(reader)?,minor_radius:f64(reader)?},
5=>{let control_points=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,_,_|point3(reader))?);let weights=native::Owned::new(numbers_binary(reader,control,limits,entities)?);let u_count=u32(reader)?;let v_count=u32(reader)?;let degree_u=u32(reader)?;let degree_v=u32(reader)?;let knots_u=native::Owned::new(numbers_binary(reader,control,limits,entities)?);let knots_v=native::Owned::new(numbers_binary(reader,control,limits,entities)?);BrepSurface::Nurbs{control_points:control_points.take(),weights:weights.take(),u_count,v_count,degree_u,degree_v,knots_u:knots_u.take(),knots_v:knots_v.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native surface kind"))})}
pub(crate) fn binary(body:&[u8],control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioBrepSnapshot,ValueError>{crate::standards::v1::subsets::brep::io::sqlite::snapshot::admit_binary(body,control,limits)?;let mut reader=store::ByteReader::new(body);if reader.read_u8().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?!=1{return Err(ValueError::new(ValueRefusalKind::InvalidValue,"unsupported BRep native format"))}let mut entities=0;native::entities(&mut entities,1,limits)?;let schema=native::text(&mut reader,control)?;let mut owner=native::Owned::new(SemioBrepSnapshot{schema,vertices:Vec::new(),edges:Vec::new(),loops:Vec::new(),faces:Vec::new(),shells:Vec::new(),solids:Vec::new(),coedges:Vec::new(),next_label:0});
owner.get_mut().vertices=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,_|{let id=native::Owned::new(native::text(reader,control)?);let point=point3(reader)?;let tol=f64(reader)?;Ok(BrepVertex{id:id.take(),point,tol})})?;
owner.get_mut().edges=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let start_vertex=native::Owned::new(native::text(reader,control)?);let end_vertex=native::Owned::new(native::text(reader,control)?);let curve=native::Owned::new(curve_binary(reader,control,limits,entities)?);let tol=f64(reader)?;Ok(BrepEdge{id:id.take(),start_vertex:start_vertex.take(),end_vertex:end_vertex.take(),curve:curve.take(),tol})})?;
owner.get_mut().loops=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let edges=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,control,_|{let edge=native::Owned::new(native::text(reader,control)?);let orientation=boolean(reader)?;Ok(BrepLoopEdge{edge:edge.take(),orientation})})?);{Ok(BrepLoop{id:id.take(),edges:edges.take()})}})?;
owner.get_mut().faces=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let outer_loop=native::Owned::new(native::text(reader,control)?);let inner_loops=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,control,_|native::text(reader,control))?);let surface=native::Owned::new(surface_binary(reader,control,limits,entities)?);let orientation=boolean(reader)?;let tol=f64(reader)?;{Ok(BrepFace{id:id.take(),outer_loop:outer_loop.take(),inner_loops:inner_loops.take(),surface:surface.take(),orientation,tol})}})?;
owner.get_mut().shells=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let faces=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,control,_|{let face=native::Owned::new(native::text(reader,control)?);let orientation=boolean(reader)?;Ok(BrepShellFace{face:face.take(),orientation})})?);{Ok(BrepShell{id:id.take(),faces:faces.take()})}})?;
owner.get_mut().solids=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let shells=native::Owned::new(native::binary_list(reader,control,limits,entities,|reader,control,_|{let shell=native::Owned::new(native::text(reader,control)?);let is_void=boolean(reader)?;Ok(BrepSolidShell{shell:shell.take(),is_void})})?);{Ok(BrepSolid{id:id.take(),shells:shells.take()})}})?;
owner.get_mut().coedges=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|{let id=native::Owned::new(native::text(reader,control)?);let edge=native::Owned::new(native::text(reader,control)?);let forward=boolean(reader)?;let pcurve=native::Owned::new(if boolean(reader)?{Some(curve2_binary(reader,control,limits,entities)?)}else{None});let prange=(f64(reader)?,f64(reader)?);let loop_id=native::Owned::new(native::text(reader,control)?);let next=native::Owned::new(native::text(reader,control)?);let prev=native::Owned::new(native::text(reader,control)?);{Ok(BrepCoedge{id:id.take(),edge:edge.take(),forward,pcurve:pcurve.take(),prange,loop_id:loop_id.take(),next:next.take(),prev:prev.take()})}})?;
owner.get_mut().next_label=reader.read_varint_u64().map_err(|e|ValueError::new(ValueRefusalKind::InvalidValue,e.to_string()))?;if reader.remaining()!=0{return Err(ValueError::new(ValueRefusalKind::InvalidValue,"BRep native trailing bytes"))}Ok(owner.take())}
fn bool_text(value:&str)->Result<bool,ValueError>{match value{"0"=>Ok(false),"1"=>Ok(true),_=>Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native boolean"))}}
fn u32_text(value:&str,control:&mut NativeDecodeControl<'_>)->Result<u32,ValueError>{control.scoped_stage(|control|{control.begin_stage(value.len())?;for _ in value.bytes(){control.step()?;}value.parse().map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native unsigned32"))})}
fn point2_text(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioPoint2,ValueError>{let[x,y]=native::record(value,control)?;Ok(SemioPoint2{x:native::float(x,control)?,y:native::float(y,control)?})}
fn point3_text(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioPoint3,ValueError>{let[x,y,z]=native::record(value,control)?;Ok(SemioPoint3{x:native::float(x,control)?,y:native::float(y,control)?,z:native::float(z,control)?})}
fn numbers_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<Vec<f64>,ValueError>{native::text_list(value,control,limits,entities,|value,control,_|native::float(value,control))}
fn curve_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepCurve,ValueError>{native::entities(entities,1,limits)?;let(tag,value)=value.split_at_checked(1).ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"BRep native curve tag missing"))?;Ok(match tag{
"L"=>{let[origin,direction]=native::record(value,control)?;BrepCurve::Line{origin:point3_text(origin,control)?,direction:point3_text(direction,control)?}},
"C"=>{let[center,axis,radius]=native::record(value,control)?;BrepCurve::Circle{center:point3_text(center,control)?,axis:point3_text(axis,control)?,radius:native::float(radius,control)?}},
"E"=>{let[center,axis,radius_major,radius_minor]=native::record(value,control)?;BrepCurve::Ellipse{center:point3_text(center,control)?,axis:point3_text(axis,control)?,radius_major:native::float(radius_major,control)?,radius_minor:native::float(radius_minor,control)?}},
"N"=>{let[control_points,weights,degree,knots]=native::record(value,control)?;let control_points=native::Owned::new(native::text_list(control_points,control,limits,entities,|value,control,_|point3_text(value,control))?);let weights=native::Owned::new(numbers_text(weights,control,limits,entities)?);let degree=u32_text(degree,control)?;let knots=native::Owned::new(numbers_text(knots,control,limits,entities)?);BrepCurve::Nurbs{control_points:control_points.take(),weights:weights.take(),degree,knots:knots.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native curve kind"))})}
fn curve2_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepCurve2,ValueError>{native::entities(entities,1,limits)?;let(tag,value)=value.split_at_checked(1).ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"BRep native p-curve tag missing"))?;Ok(match tag{
"L"=>{let[origin,direction]=native::record(value,control)?;BrepCurve2::Line{origin:point2_text(origin,control)?,direction:point2_text(direction,control)?}},
"C"=>{let[center,radius]=native::record(value,control)?;BrepCurve2::Circle{center:point2_text(center,control)?,radius:native::float(radius,control)?}},
"E"=>{let[center,x_axis,radius_major,radius_minor]=native::record(value,control)?;BrepCurve2::Ellipse{center:point2_text(center,control)?,x_axis:point2_text(x_axis,control)?,radius_major:native::float(radius_major,control)?,radius_minor:native::float(radius_minor,control)?}},
"N"=>{let[control_points,weights,degree,knots]=native::record(value,control)?;let control_points=native::Owned::new(native::text_list(control_points,control,limits,entities,|value,control,_|point2_text(value,control))?);let weights=native::Owned::new(numbers_text(weights,control,limits,entities)?);let degree=u32_text(degree,control)?;let knots=native::Owned::new(numbers_text(knots,control,limits,entities)?);BrepCurve2::Nurbs{control_points:control_points.take(),weights:weights.take(),degree,knots:knots.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native p-curve kind"))})}
fn surface_text(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<BrepSurface,ValueError>{native::entities(entities,1,limits)?;let(tag,value)=value.split_at_checked(1).ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"BRep native surface tag missing"))?;Ok(match tag{
"P"=>{let[origin,normal]=native::record(value,control)?;BrepSurface::Plane{origin:point3_text(origin,control)?,normal:point3_text(normal,control)?}},
"C"=>{let[origin,axis,radius]=native::record(value,control)?;BrepSurface::Cylinder{origin:point3_text(origin,control)?,axis:point3_text(axis,control)?,radius:native::float(radius,control)?}},
"O"=>{let[origin,axis,radius,half_angle]=native::record(value,control)?;BrepSurface::Cone{origin:point3_text(origin,control)?,axis:point3_text(axis,control)?,radius:native::float(radius,control)?,half_angle:native::float(half_angle,control)?}},
"S"=>{let[center,radius]=native::record(value,control)?;BrepSurface::Sphere{center:point3_text(center,control)?,radius:native::float(radius,control)?}},
"T"=>{let[center,axis,major_radius,minor_radius]=native::record(value,control)?;BrepSurface::Torus{center:point3_text(center,control)?,axis:point3_text(axis,control)?,major_radius:native::float(major_radius,control)?,minor_radius:native::float(minor_radius,control)?}},
"N"=>{let[control_points,weights,u_count,v_count,degree_u,degree_v,knots_u,knots_v]=native::record(value,control)?;let control_points=native::Owned::new(native::text_list(control_points,control,limits,entities,|value,control,_|point3_text(value,control))?);let weights=native::Owned::new(numbers_text(weights,control,limits,entities)?);let u_count=u32_text(u_count,control)?;let v_count=u32_text(v_count,control)?;let degree_u=u32_text(degree_u,control)?;let degree_v=u32_text(degree_v,control)?;let knots_u=native::Owned::new(numbers_text(knots_u,control,limits,entities)?);let knots_v=native::Owned::new(numbers_text(knots_v,control,limits,entities)?);BrepSurface::Nurbs{control_points:control_points.take(),weights:weights.take(),u_count,v_count,degree_u,degree_v,knots_u:knots_u.take(),knots_v:knots_v.take()}},_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native surface kind"))})}
pub(crate) fn document(body:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioBrepSnapshot,ValueError>{crate::standards::v1::subsets::brep::io::sqlite::snapshot::admit_document(body,control,limits)?;let fields=native::fields(body,["schema","vertices","edges","loops","faces","shells","solids","coedges","nextLabel"],control)?;let mut entities=0;native::entities(&mut entities,1,limits)?;let schema=native::hex_text(fields[0].ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"BRep native schema missing"))?,control)?;let mut owner=native::Owned::new(SemioBrepSnapshot{schema,vertices:Vec::new(),edges:Vec::new(),loops:Vec::new(),faces:Vec::new(),shells:Vec::new(),solids:Vec::new(),coedges:Vec::new(),next_label:0});
owner.get_mut().vertices=native::text_list(fields[1].unwrap_or("[]"),control,limits,&mut entities,|value,control,_|{let[id,point,tol]=native::record(value,control)?;{let id=native::Owned::new(native::hex_text(id,control)?);let point=point3_text(point,control)?;let tol=native::float(tol,control)?;Ok(BrepVertex{id:id.take(),point,tol})}})?;
owner.get_mut().edges=native::text_list(fields[2].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,start_vertex,end_vertex,curve,tol]=native::record(value,control)?;{let id=native::Owned::new(native::hex_text(id,control)?);let start_vertex=native::Owned::new(native::hex_text(start_vertex,control)?);let end_vertex=native::Owned::new(native::hex_text(end_vertex,control)?);let curve=native::Owned::new(curve_text(curve,control,limits,entities)?);let tol=native::float(tol,control)?;Ok(BrepEdge{id:id.take(),start_vertex:start_vertex.take(),end_vertex:end_vertex.take(),curve:curve.take(),tol})}})?;
owner.get_mut().loops=native::text_list(fields[3].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,edges]=native::record(value,control)?;let id=native::Owned::new(native::hex_text(id,control)?);let edges=native::Owned::new(native::text_list(edges,control,limits,entities,|value,control,_|{let[edge,orientation]=native::record(value,control)?;{let edge=native::Owned::new(native::hex_text(edge,control)?);let orientation=bool_text(orientation)?;Ok(BrepLoopEdge{edge:edge.take(),orientation})}})?);{Ok(BrepLoop{id:id.take(),edges:edges.take()})}})?;
owner.get_mut().faces=native::text_list(fields[4].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,outer_loop,inner_loops,surface,orientation,tol]=native::record(value,control)?;let id=native::Owned::new(native::hex_text(id,control)?);let outer_loop=native::Owned::new(native::hex_text(outer_loop,control)?);let inner_loops=native::Owned::new(native::text_list(inner_loops,control,limits,entities,|value,control,_|{let[id]=native::record(value,control)?;native::hex_text(id,control)})?);let surface=native::Owned::new(surface_text(surface,control,limits,entities)?);{let orientation=bool_text(orientation)?;let tol=native::float(tol,control)?;Ok(BrepFace{id:id.take(),outer_loop:outer_loop.take(),inner_loops:inner_loops.take(),surface:surface.take(),orientation,tol})}})?;
owner.get_mut().shells=native::text_list(fields[5].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,faces]=native::record(value,control)?;let id=native::Owned::new(native::hex_text(id,control)?);let faces=native::Owned::new(native::text_list(faces,control,limits,entities,|value,control,_|{let[face,orientation]=native::record(value,control)?;{let face=native::Owned::new(native::hex_text(face,control)?);let orientation=bool_text(orientation)?;Ok(BrepShellFace{face:face.take(),orientation})}})?);{Ok(BrepShell{id:id.take(),faces:faces.take()})}})?;
owner.get_mut().solids=native::text_list(fields[6].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,shells]=native::record(value,control)?;let id=native::Owned::new(native::hex_text(id,control)?);let shells=native::Owned::new(native::text_list(shells,control,limits,entities,|value,control,_|{let[shell,is_void]=native::record(value,control)?;{let shell=native::Owned::new(native::hex_text(shell,control)?);let is_void=bool_text(is_void)?;Ok(BrepSolidShell{shell:shell.take(),is_void})}})?);{Ok(BrepSolid{id:id.take(),shells:shells.take()})}})?;
owner.get_mut().coedges=native::text_list(fields[7].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|{let[id,edge,forward,pcurve,prange,loop_id,next,prev]=native::record(value,control)?;let id=native::Owned::new(native::hex_text(id,control)?);let edge=native::Owned::new(native::hex_text(edge,control)?);let forward=bool_text(forward)?;let pcurve=native::Owned::new(if pcurve=="-"{None}else{Some(curve2_text(pcurve.strip_prefix('~').ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native optional p-curve"))?,control,limits,entities)?)});let[a,b]=native::record(prange,control)?;let prange=(native::float(a,control)?,native::float(b,control)?);{let loop_id=native::Owned::new(native::hex_text(loop_id,control)?);let next=native::Owned::new(native::hex_text(next,control)?);let prev=native::Owned::new(native::hex_text(prev,control)?);Ok(BrepCoedge{id:id.take(),edge:edge.take(),forward,pcurve:pcurve.take(),prange,loop_id:loop_id.take(),next:next.take(),prev:prev.take()})}})?;
let next_label=fields[8].ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"BRep native nextLabel missing"))?;owner.get_mut().next_label=control.scoped_stage(|control|{control.begin_stage(next_label.len())?;for _ in next_label.bytes(){control.step()?;}next_label.parse::<u64>().map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"invalid BRep native unsigned64 label"))})?;Ok(owner.take())}
