type SpaceConfig {
  camera: [SpaceWindowCameraEntry!]! @state(class: CONFIG)
  collapsedNodeIds: [String!]! @state(class: CONFIG)
  previewOffNodeIds: [String!]! @state(class: CONFIG)
  activeNodeId: String @state(class: CONFIG)
  focusedNodeId: String @state(class: CONFIG)
  clipboardNodeIds: [String!]! @state(class: CONFIG)
  workflowEngagementInput: String! @state(class: CONFIG)
  compiledDagEngagementInput: String! @state(class: CONFIG)
  pendingImportNodeId: String @state(class: CONFIG)
  pendingImportFormat: String @state(class: CONFIG)
  activePanelTab: String! @state(class: CONFIG)
  spaceId: String @state(class: CONFIG)
  clientId: String @state(class: CONFIG)
  clientName: String @state(class: CONFIG)
  locale: String! @state(class: CONFIG)
}

type SpaceWindowCameraEntry {
  key: String!
  value: SpaceWindowCamera!
}

type SpaceWindowCamera {
  x: Float!
  y: Float!
  zoom: Float!
}
