[package]
name = "semio-s-plugin-playbook"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:playbook"

[package.metadata.semio]
consumes = ["playbook.blockKind"]

[[package.metadata.semio.playground]]
variant = "playbook"
ports = { react = 6085, wgpu = 6185 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "../../../../../../../✏️s/🔌️plugin/📖️playbook/🛂️manifest/🗿️artifact/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️product/💻️os/🔨️module/🔌️plugin/⚡️implementation/🦀️rust", features = ["component-guest"], package = "semio-framework-plugin" }
playbook = { path = "../../../../../../../✏️s/🔌️plugin/📖️playbook/🎛️app/📖️playbook/⚡️implementation/🦀️rust", package = "semio-s-app-playbook" }
playbook_ui = { path = "../../../../../../../✏️s/🔌️plugin/📖️playbook/🎛️app/📖️playbook/🔨️module/🖱️ui/⚡️implementation/🦀️rust", package = "semio-s-app-playbook-ui" }
