//! 🗂️ Adjacent concrete GLTF relational indexes await the owning capability baseline.
use super::*;
use semio_framework_os_kernel::sqlite_snapshot::transfer::{reserve,validate_table_controlled};

struct Entity<'a>{row:&'a SqliteRow,used:bool}
struct Relation<'a>{owner:i64,ordinal:usize,row:&'a SqliteRow}
struct Relations<'a>{owner_column:usize,ordinal_column:usize,rows:Vec<Relation<'a>>}
struct TableIndex<'a>{name:&'a str,rows:Vec<Entity<'a>>,relations:Option<Relations<'a>>}
pub(super) struct Read<'a,'c,'p>{database:&'a SqliteDatabase,control:&'c mut SqliteSnapshotControl<'p>,tables:Vec<TableIndex<'a>>,visits:usize}

fn sort<T>(values:&mut[T],key:impl Fn(&T)->(i64,usize),control:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{
 fn sift<T>(values:&mut[T],mut root:usize,end:usize,key:&impl Fn(&T)->(i64,usize),work:&mut usize,control:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{
  while let Some(mut child)=root.checked_mul(2).and_then(|n|n.checked_add(1)).filter(|n|*n<end){if child+1<end&&key(&values[child])<key(&values[child+1]){child+=1;}*work=work.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"GLTF index sort workload overflow"))?;if *work%256==0{control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,*work,0)?;}if key(&values[root])>=key(&values[child]){break}values.swap(root,child);root=child;}Ok(())
 }
 control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,0,0)?;let mut work=0;let count=values.len();for start in(0..count/2).rev(){sift(values,start,count,&key,&mut work,control)?;}for end in(1..count).rev(){values.swap(0,end);sift(values,0,end,&key,&mut work,control)?;}control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,work,work)
}
impl<'a,'c,'p> Read<'a,'c,'p>{
 pub(super) fn new(database:&'a SqliteDatabase,control:&'c mut SqliteSnapshotControl<'p>)->Result<Self,ValueError>{
  let expected=Projection::new(SQLITE_SCHEMA,control)?.finish()?;if database.tables.len()!=expected.tables.len(){return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF authored table count differs"))}let mut tables=reserve(database.tables.len(),control)?;let mut rows=0usize;let mut bytes=0usize;let mut visited=0usize;
  for table in &database.tables{
   let expected=expected.tables.iter().find(|candidate|candidate.name.eq_ignore_ascii_case(&table.name)).ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"GLTF undeclared table"))?;if tables.iter().any(|index:&TableIndex<'_>|index.name.eq_ignore_ascii_case(&table.name)){return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF duplicate table"))}validate_table_controlled(table,&expected.sql,SqliteSnapshotPhase::ReconstructSnapshot,control)?;let width=WIDTHS.iter().find(|(name,_)|name.eq_ignore_ascii_case(&table.name)).ok_or_else(||ValueError::new(ValueRefusalKind::InvariantViolated,"GLTF authored width missing"))?.1;rows=rows.checked_add(table.rows.len()).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"GLTF row count overflow"))?;control.check_rows(rows)?;let mut entities=reserve(table.rows.len(),control)?;
   for row in &table.rows{if row.rowid<1||row.integer(0)?!=row.rowid||row.values.len()!=width{return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF entity identity or authored width differs"))}for value in &row.values{bytes=bytes.checked_add(match value{SqliteValue::Null=>0,SqliteValue::Integer(_)|SqliteValue::Real(_)=>8,SqliteValue::Text(value)=>value.len(),SqliteValue::Blob(value)=>value.len()}).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"GLTF value byte count overflow"))?;control.check_value_bytes(bytes)?;}entities.push(Entity{row,used:false});visited=visited.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"GLTF traversal overflow"))?;if visited%256==0{control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,visited,0)?;}}
   sort(&mut entities,|entity| (entity.row.rowid,0),control)?;if entities.windows(2).any(|pair|pair[0].row.rowid==pair[1].row.rowid){return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF duplicate entity identity"))}tables.push(TableIndex{name:&table.name,rows:entities,relations:None});
  }Ok(Self{database,control,tables,visits:visited})
 }
 pub(super) fn reserve<T>(&mut self,count:usize)->Result<Vec<T>,ValueError>{self.checkpoint()?;reserve(count,self.control)}
 pub(super) fn reserve_fields<T>(&mut self,values:&mut Vec<T>,additional:usize)->Result<(),ValueError>{let required=values.len().checked_add(additional).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"GLTF owned field count overflow"))?;if required>values.capacity(){let mut next=self.reserve(required)?;next.extend(values.drain(..));*values=next;self.checkpoint()?;}Ok(())}
 pub(super) fn checkpoint(&mut self)->Result<(),ValueError>{self.visits=self.visits.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"GLTF traversal overflow"))?;if self.visits%256==0{self.control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,self.visits,0)?;}Ok(())}
 fn table_index(&self,table:&str)->Result<usize,ValueError>{self.tables.iter().position(|value|value.name.eq_ignore_ascii_case(table)).ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"GLTF required table missing"))}
 pub(super) fn consume(&mut self,table:&'static str,row:&'a SqliteRow)->Result<&'a SqliteRow,ValueError>{let table=self.table_index(table)?;let position=self.tables[table].rows.binary_search_by_key(&row.rowid,|entity|entity.row.rowid).map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"GLTF entity is missing"))?;let entity=&mut self.tables[table].rows[position];if entity.used||!std::ptr::eq(entity.row,row){return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF entity has multiple owners"))}entity.used=true;self.checkpoint()?;Ok(row)}
 pub(super) fn key(&mut self,table:&'static str,key:i64)->Result<&'a SqliteRow,ValueError>{let index=self.table_index(table)?;let position=self.tables[index].rows.binary_search_by_key(&key,|entity|entity.row.rowid).map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"GLTF required entity is missing"))?;self.consume(table,self.tables[index].rows[position].row)}
 pub(super) fn optional_key(&mut self,table:&'static str,key:i64)->Result<Option<&'a SqliteRow>,ValueError>{let index=self.table_index(table)?;if self.tables[index].rows.binary_search_by_key(&key,|entity|entity.row.rowid).is_ok(){self.key(table,key).map(Some)}else{Ok(None)}}
 pub(super) fn rows(&mut self,table:&'static str,owner_column:usize,owner:i64,ordinal_column:usize)->Result<Vec<&'a SqliteRow>,ValueError>{
  let index=self.table_index(table)?;if self.tables[index].relations.is_none(){let borrowed=&self.database.table(table)?.rows;let mut rows=reserve(borrowed.len(),self.control)?;for row in borrowed{let owner=row.integer(owner_column)?;let ordinal=usize::try_from(row.integer(ordinal_column)?).map_err(|error|ValueError::new(ValueRefusalKind::InvalidValue,error.to_string()))?;if owner<1{return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF relationship owner differs"))}rows.push(Relation{owner,ordinal,row});self.checkpoint()?;}sort(&mut rows,|row|(row.owner,row.ordinal),self.control)?;let mut owner=0;let mut next=0;for row in &rows{if row.owner!=owner{owner=row.owner;next=0;}if row.ordinal!=next{return Err(ValueError::new(ValueRefusalKind::InvalidValue,"GLTF relationship ordinals must be contiguous and unique"))}next+=1;self.checkpoint()?;}self.tables[index].relations=Some(Relations{owner_column,ordinal_column,rows});}
  let relations=self.tables[index].relations.as_ref().unwrap();if relations.owner_column!=owner_column||relations.ordinal_column!=ordinal_column{return Err(ValueError::new(ValueRefusalKind::InvariantViolated,"GLTF authored relationship columns differ"))}let start=relations.rows.partition_point(|row|row.owner<owner);let end=relations.rows.partition_point(|row|row.owner<=owner);let mut result=reserve(end-start,self.control)?;for position in start..end{let row=self.tables[index].relations.as_ref().unwrap().rows[position].row;result.push(self.consume(table,row)?);}Ok(result)
 }
 pub(super) fn finish(mut self)->Result<(),ValueError>{for table in &self.tables{for entity in &table.rows{if !entity.used{return Err(ValueError::new(ValueRefusalKind::InvalidValue,format!("GLTF unowned entity remains in {}",table.name)))}self.visits=self.visits.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"GLTF final ownership traversal overflow"))?;if self.visits%256==0{self.control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,self.visits,0)?;}}}self.control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,self.visits,self.visits)}
 pub(super) fn text(&mut self,row:&SqliteRow,column:usize)->Result<String, ValueError>{Reconstruction::new(self.control)?.text(row.text(column)?)}
 pub(super) fn optional_text(&mut self,row:&SqliteRow,column:usize)->Result<Option<String>, ValueError>{row.optional_text(column)?.map(|text|Reconstruction::new(self.control)?.text(text)).transpose()}
 pub(super) fn scalar(&mut self)->Result<(), ValueError>{Reconstruction::new(self.control)?.scalar()}
 pub(super) fn word(&mut self,row:&SqliteRow,column:usize)->Result<u64, ValueError>{self.scalar()?;let high=u32::try_from(row.integer(column)?).map_err(|error| ValueError::new(ValueRefusalKind::InvalidValue, error.to_string()))?;let low=u32::try_from(row.integer(column+1)?).map_err(|error| ValueError::new(ValueRefusalKind::InvalidValue, error.to_string()))?;Ok((u64::from(high)<<32)|u64::from(low))}
 pub(super) fn optional_word(&mut self,row:&SqliteRow,column:usize)->Result<Option<u64>, ValueError>{match(row.values.get(column),row.values.get(column+1)){(Some(SqliteValue::Null),Some(SqliteValue::Null))=>Ok(None),(Some(SqliteValue::Integer(_)),Some(SqliteValue::Integer(_)))=>self.word(row,column).map(Some),_=>Err(ValueError::new(ValueRefusalKind::InvalidValue, "GLTF optional unsigned words differ"))}}
 pub(super) fn index(&mut self,row:&SqliteRow,column:usize)->Result<usize, ValueError>{usize::try_from(self.word(row,column)?).map_err(|error| ValueError::new(ValueRefusalKind::InvalidValue, error.to_string()))}
 pub(super) fn optional_index(&mut self,row:&SqliteRow,column:usize)->Result<Option<usize>, ValueError>{self.optional_word(row,column)?.map(|value|usize::try_from(value).map_err(|error| ValueError::new(ValueRefusalKind::InvalidValue, error.to_string()))).transpose()}
 pub(super) fn boolean(&mut self,row:&SqliteRow,column:usize)->Result<bool, ValueError>{self.scalar()?;match row.integer(column)?{0=>Ok(false),1=>Ok(true),_=>Err(ValueError::new(ValueRefusalKind::InvalidValue, "GLTF boolean must be zero or one"))}}
 pub(super) fn json_owned(&mut self,row:&SqliteRow,column:usize)->Result<semio_framework_dsl_record::__rt::DecodedFieldOwner<Option<GltfJson>>, ValueError>{self.json(row,column).map(owned_option)}
 pub(super) fn json(&mut self,row:&SqliteRow,column:usize)->Result<Option<GltfJson>, ValueError>{match row.values.get(column){Some(SqliteValue::Null)=>Ok(None),Some(SqliteValue::Integer(id)) if *id>0=>extras::reconstruct(self,*id).map(Some),_=>Err(ValueError::new(ValueRefusalKind::InvalidValue, "GLTF extras root must be a positive entity or absent"))}}
}
