//! 🤖️ Generated by `bun ./📜️script.ts surface-schema` (surface-schema-projection) — do not edit.
//! @see 🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/🦀️.rs

/// 🧬️ config schema of `s.architect.program`, projected from `NoConfig`.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct NoConfig {}
