syntax = "proto3";
package stdio.gltf.mutation;
import "🔗️🎬️bind-default-scene/🛰️.proto";
import "🔗️🧬️bind-morph-target-attribute/🛰️.proto";
import "🔗️🔘️bind-node-camera/🛰️.proto";
import "🔗️🔘️bind-node-child/🛰️.proto";
import "🔗️🔘️bind-node-mesh/🛰️.proto";
import "🔗️🔘️bind-node-skin/🛰️.proto";
import "🔗️🔺️bind-primitive-attribute/🛰️.proto";
import "🔗️🔺️bind-primitive-indices/🛰️.proto";
import "🔗️🔺️bind-primitive-material/🛰️.proto";
import "🔗️🎬️bind-scene-root-node/🛰️.proto";
import "✏️📦️change-asset-descriptive-metadata/🛰️.proto";
import "✏️📦️change-asset-extension-data/🛰️.proto";
import "✏️📦️change-asset-extra-data/🛰️.proto";
import "✏️📦️change-asset-version/🛰️.proto";
import "✏️📄️change-document-extension-data/🛰️.proto";
import "✏️📄️change-document-extra-data/🛰️.proto";
import "✏️💎️change-material-alpha-mode/🛰️.proto";
import "✏️💎️change-material-double-sided/🛰️.proto";
import "✏️🕸️change-mesh-extension-data/🛰️.proto";
import "✏️🕸️change-mesh-extra-data/🛰️.proto";
import "✏️🕸️change-mesh-morph-weights/🛰️.proto";
import "✏️🕸️change-mesh-name/🛰️.proto";
import "✏️🔘️change-node-extension-data/🛰️.proto";
import "✏️🔘️change-node-extra-data/🛰️.proto";
import "✏️🔘️change-node-morph-weights/🛰️.proto";
import "✏️🔘️change-node-name/🛰️.proto";
import "✏️🔺️change-primitive-extension-data/🛰️.proto";
import "✏️🔺️change-primitive-extra-data/🛰️.proto";
import "✏️🔺️change-primitive-topology-mode/🛰️.proto";
import "✏️🎬️change-scene-extension-data/🛰️.proto";
import "✏️🎬️change-scene-extra-data/🛰️.proto";
import "✏️🎬️change-scene-name/🛰️.proto";
import "🌱️📐️create-accessor/🛰️.proto";
import "🌱️🎞️create-animation/🛰️.proto";
import "🌱️💾️create-buffer/🛰️.proto";
import "🌱️👁️create-buffer-view/🛰️.proto";
import "🌱️🎥️create-camera/🛰️.proto";
import "🌱️🖼️create-image/🛰️.proto";
import "🌱️💎️create-material/🛰️.proto";
import "🌱️🕸️create-mesh/🛰️.proto";
import "🌱️🧬️create-morph-target/🛰️.proto";
import "🌱️🔘️create-node/🛰️.proto";
import "🌱️🔺️create-primitive/🛰️.proto";
import "🌱️🎛️create-sampler/🛰️.proto";
import "🌱️🎬️create-scene/🛰️.proto";
import "🌱️🧥️create-skin/🛰️.proto";
import "🌱️🎨️create-texture/🛰️.proto";
import "📣️🧩️add-used-extension/🛰️.proto";
import "🗑️📐️delete-accessor/🛰️.proto";
import "🗑️🎞️delete-animation/🛰️.proto";
import "🗑️💾️delete-buffer/🛰️.proto";
import "🗑️👁️delete-buffer-view/🛰️.proto";
import "🗑️🎥️delete-camera/🛰️.proto";
import "🗑️🖼️delete-image/🛰️.proto";
import "🗑️💎️delete-material/🛰️.proto";
import "🗑️🕸️delete-mesh/🛰️.proto";
import "🗑️🧬️delete-morph-target/🛰️.proto";
import "🗑️🔘️delete-node/🛰️.proto";
import "🗑️🔺️delete-primitive/🛰️.proto";
import "🗑️🎛️delete-sampler/🛰️.proto";
import "🗑️🎬️delete-scene/🛰️.proto";
import "🗑️🧥️delete-skin/🛰️.proto";
import "🗑️🎨️delete-texture/🛰️.proto";
import "🚚️📐️move-accessor/🛰️.proto";
import "🚚️🎞️move-animation/🛰️.proto";
import "🚚️💾️move-buffer/🛰️.proto";
import "🚚️👁️move-buffer-view/🛰️.proto";
import "🚚️🎥️move-camera/🛰️.proto";
import "🚚️🖼️move-image/🛰️.proto";
import "🚚️💎️move-material/🛰️.proto";
import "🚚️🕸️move-mesh/🛰️.proto";
import "🚚️🧬️move-morph-target/🛰️.proto";
import "🚚️🧬️move-morph-target-attribute/🛰️.proto";
import "🚚️🔘️move-node/🛰️.proto";
import "🚚️🔘️move-node-child/🛰️.proto";
import "🚚️🔺️move-primitive/🛰️.proto";
import "🚚️🔺️move-primitive-attribute/🛰️.proto";
import "🚚️🧩️move-required-extension/🛰️.proto";
import "🚚️🎛️move-sampler/🛰️.proto";
import "🚚️🎬️move-scene/🛰️.proto";
import "🚚️🎬️move-scene-root-node/🛰️.proto";
import "🚚️🧥️move-skin/🛰️.proto";
import "🚚️🎨️move-texture/🛰️.proto";
import "🚚️🧩️move-used-extension/🛰️.proto";
import "🔀️📐️reorder-accessors/🛰️.proto";
import "🔀️🎞️reorder-animations/🛰️.proto";
import "🔀️👁️reorder-buffer-views/🛰️.proto";
import "🔀️💾️reorder-buffers/🛰️.proto";
import "🔀️🎥️reorder-cameras/🛰️.proto";
import "🔀️🖼️reorder-images/🛰️.proto";
import "🔀️💎️reorder-materials/🛰️.proto";
import "🔀️🕸️reorder-meshs/🛰️.proto";
import "🔀️🧬️reorder-morph-target-attributes/🛰️.proto";
import "🔀️🧬️reorder-morph-targets/🛰️.proto";
import "🔀️🔘️reorder-node-children/🛰️.proto";
import "🔀️🔘️reorder-nodes/🛰️.proto";
import "🔀️🔺️reorder-primitive-attributes/🛰️.proto";
import "🔀️🔺️reorder-primitives/🛰️.proto";
import "🔀️🧩️reorder-required-extensions/🛰️.proto";
import "🔀️🎛️reorder-samplers/🛰️.proto";
import "🔀️🎬️reorder-scene-root-nodes/🛰️.proto";
import "🔀️🎬️reorder-scenes/🛰️.proto";
import "🔀️🧥️reorder-skins/🛰️.proto";
import "🔀️🎨️reorder-textures/🛰️.proto";
import "🔀️🧩️reorder-used-extensions/🛰️.proto";
import "👪️🔘️move-node-parent/🛰️.proto";
import "✅️🧩️add-required-extension/🛰️.proto";
import "🔄️🔘️change-node-transform/🛰️.proto";
import "✂️🎬️unbind-default-scene/🛰️.proto";
import "✂️🧬️unbind-morph-target-attribute/🛰️.proto";
import "✂️🔘️unbind-node-camera/🛰️.proto";
import "✂️🔘️unbind-node-child/🛰️.proto";
import "✂️🔘️unbind-node-mesh/🛰️.proto";
import "✂️🔘️unbind-node-skin/🛰️.proto";
import "✂️🔺️unbind-primitive-attribute/🛰️.proto";
import "✂️🔺️unbind-primitive-indices/🛰️.proto";
import "✂️🔺️unbind-primitive-material/🛰️.proto";
import "✂️🎬️unbind-scene-root-node/🛰️.proto";
import "🚫️🧩️remove-required-extension/🛰️.proto";
import "🔙️🧩️remove-used-extension/🛰️.proto";
message GltfMutation {
  oneof mutation {
    GltfBindDefaultSceneMutationV1 bind_default_scene = 1;
    GltfBindMorphTargetAttributePayloadV1 bind_morph_target_attribute = 2;
    GltfBindNodeCameraPayloadV1 bind_node_camera = 3;
    GltfBindNodeChildPayloadV1 bind_node_child = 4;
    GltfBindNodeMeshPayloadV1 bind_node_mesh = 5;
    GltfBindNodeSkinPayloadV1 bind_node_skin = 6;
    GltfBindPrimitiveAttributePayloadV1 bind_primitive_attribute = 7;
    GltfBindPrimitiveIndicesPayloadV1 bind_primitive_indices = 8;
    GltfBindPrimitiveMaterialPayloadV1 bind_primitive_material = 9;
    GltfBindSceneRootNodePayloadV1 bind_scene_root_node = 10;
    GltfChangeAssetDescriptiveMetadataMutationV1 change_asset_descriptive_metadata = 11;
    GltfChangeAssetExtensionDataMutationV1 change_asset_extension_data = 12;
    GltfChangeAssetExtraDataMutationV1 change_asset_extra_data = 13;
    GltfChangeAssetVersionMutationV1 change_asset_version = 14;
    GltfChangeDocumentExtensionDataMutationV1 change_document_extension_data = 15;
    GltfChangeDocumentExtraDataMutationV1 change_document_extra_data = 16;
    GltfChangeMaterialAlphaModeMutationV1 change_material_alpha_mode = 17;
    GltfChangeMaterialDoubleSidedMutationV1 change_material_double_sided = 18;
    GltfChangeMeshExtensionDataPayloadV1 change_mesh_extension_data = 19;
    GltfChangeMeshExtraDataPayloadV1 change_mesh_extra_data = 20;
    GltfChangeMeshMorphWeightsPayloadV1 change_mesh_morph_weights = 21;
    GltfChangeMeshNamePayloadV1 change_mesh_name = 22;
    GltfChangeNodeExtensionDataPayloadV1 change_node_extension_data = 23;
    GltfChangeNodeExtraDataPresenceV1 change_node_extra_data = 24;
    GltfChangeNodeMorphWeightsPayloadV1 change_node_morph_weights = 25;
    GltfChangeNodeNameMutationV1 change_node_name = 26;
    GltfChangePrimitiveExtensionDataPayloadV1 change_primitive_extension_data = 27;
    GltfChangePrimitiveExtraDataPayloadV1 change_primitive_extra_data = 28;
    GltfChangePrimitiveTopologyModePayloadV1 change_primitive_topology_mode = 29;
    GltfChangeSceneExtensionDataPayloadV1 change_scene_extension_data = 30;
    GltfChangeSceneExtraDataPayloadV1 change_scene_extra_data = 31;
    GltfChangeSceneNamePayloadV1 change_scene_name = 32;
    GltfCreateAccessorPayloadV1 create_accessor = 33;
    GltfCreateAnimationPayloadV1 create_animation = 34;
    GltfCreateBufferPayloadV1 create_buffer = 35;
    GltfCreateBufferViewPayloadV1 create_buffer_view = 36;
    GltfCreateCameraPayloadV1 create_camera = 37;
    GltfCreateImagePayloadV1 create_image = 38;
    GltfCreateMaterialPayloadV1 create_material = 39;
    GltfCreateMeshPayloadV1 create_mesh = 40;
    GltfCreateMorphTargetPayloadV1 create_morph_target = 41;
    GltfCreateNodePayloadV1 create_node = 42;
    GltfCreatePrimitivePayloadV1 create_primitive = 43;
    GltfCreateSamplerPayloadV1 create_sampler = 44;
    GltfCreateScenePayloadV1 create_scene = 45;
    GltfCreateSkinPayloadV1 create_skin = 46;
    GltfCreateTexturePayloadV1 create_texture = 47;
    GltfDeclareUsedExtensionMutationV1 add_used_extension = 48;
    GltfDeleteAccessorPayloadV1 delete_accessor = 49;
    GltfDeleteAnimationPayloadV1 delete_animation = 50;
    GltfDeleteBufferPayloadV1 delete_buffer = 51;
    GltfDeleteBufferViewPayloadV1 delete_buffer_view = 52;
    GltfDeleteCameraPayloadV1 delete_camera = 53;
    GltfDeleteImagePayloadV1 delete_image = 54;
    GltfDeleteMaterialPayloadV1 delete_material = 55;
    GltfDeleteMeshPayloadV1 delete_mesh = 56;
    GltfDeleteMorphTargetPayloadV1 delete_morph_target = 57;
    GltfDeleteNodePayloadV1 delete_node = 58;
    GltfDeletePrimitivePayloadV1 delete_primitive = 59;
    GltfDeleteSamplerPayloadV1 delete_sampler = 60;
    GltfDeleteScenePayloadV1 delete_scene = 61;
    GltfDeleteSkinPayloadV1 delete_skin = 62;
    GltfDeleteTexturePayloadV1 delete_texture = 63;
    GltfMoveAccessorPayloadV1 move_accessor = 64;
    GltfMoveAnimationPayloadV1 move_animation = 65;
    GltfMoveBufferPayloadV1 move_buffer = 66;
    GltfMoveBufferViewPayloadV1 move_buffer_view = 67;
    GltfMoveCameraPayloadV1 move_camera = 68;
    GltfMoveImagePayloadV1 move_image = 69;
    GltfMoveMaterialPayloadV1 move_material = 70;
    GltfMoveMeshPayloadV1 move_mesh = 71;
    GltfMoveMorphTargetPayloadV1 move_morph_target = 72;
    GltfMoveMorphTargetAttributePayloadV1 move_morph_target_attribute = 73;
    GltfMoveNodePayloadV1 move_node = 74;
    GltfMoveNodeChildPayloadV1 move_node_child = 75;
    GltfMovePrimitivePayloadV1 move_primitive = 76;
    GltfMovePrimitiveAttributePayloadV1 move_primitive_attribute = 77;
    GltfMoveRequiredExtensionMutationV1 move_required_extension = 78;
    GltfMoveSamplerPayloadV1 move_sampler = 79;
    GltfMoveScenePayloadV1 move_scene = 80;
    GltfMoveSceneRootNodePayloadV1 move_scene_root_node = 81;
    GltfMoveSkinPayloadV1 move_skin = 82;
    GltfMoveTexturePayloadV1 move_texture = 83;
    GltfMoveUsedExtensionMutationV1 move_used_extension = 84;
    GltfReorderAccessorsPayloadV1 reorder_accessors = 85;
    GltfReorderAnimationsPayloadV1 reorder_animations = 86;
    GltfReorderBufferViewsPayloadV1 reorder_buffer_views = 87;
    GltfReorderBuffersPayloadV1 reorder_buffers = 88;
    GltfReorderCamerasPayloadV1 reorder_cameras = 89;
    GltfReorderImagesPayloadV1 reorder_images = 90;
    GltfReorderMaterialsPayloadV1 reorder_materials = 91;
    GltfReorderMeshsPayloadV1 reorder_meshs = 92;
    GltfReorderMorphTargetAttributesPayloadV1 reorder_morph_target_attributes = 93;
    GltfReorderMorphTargetsPayloadV1 reorder_morph_targets = 94;
    GltfReorderNodeChildrenPayloadV1 reorder_node_children = 95;
    GltfReorderNodesPayloadV1 reorder_nodes = 96;
    GltfReorderPrimitiveAttributesPayloadV1 reorder_primitive_attributes = 97;
    GltfReorderPrimitivesPayloadV1 reorder_primitives = 98;
    GltfReorderRequiredExtensionsMutationV1 reorder_required_extensions = 99;
    GltfReorderSamplersPayloadV1 reorder_samplers = 100;
    GltfReorderSceneRootNodesPayloadV1 reorder_scene_root_nodes = 101;
    GltfReorderScenesPayloadV1 reorder_scenes = 102;
    GltfReorderSkinsPayloadV1 reorder_skins = 103;
    GltfReorderTexturesPayloadV1 reorder_textures = 104;
    GltfReorderUsedExtensionsMutationV1 reorder_used_extensions = 105;
    GltfReparentNodePayloadV1 move_node_parent = 106;
    GltfRequireExtensionMutationV1 add_required_extension = 107;
    GltfTransformNodePayloadV1 change_node_transform = 108;
    GltfUnbindDefaultSceneMutationV1 unbind_default_scene = 109;
    GltfUnbindMorphTargetAttributePayloadV1 unbind_morph_target_attribute = 110;
    GltfUnbindNodeCameraPayloadV1 unbind_node_camera = 111;
    GltfUnbindNodeChildPayloadV1 unbind_node_child = 112;
    GltfUnbindNodeMeshPayloadV1 unbind_node_mesh = 113;
    GltfUnbindNodeSkinPayloadV1 unbind_node_skin = 114;
    GltfUnbindPrimitiveAttributePayloadV1 unbind_primitive_attribute = 115;
    GltfUnbindPrimitiveIndicesPayloadV1 unbind_primitive_indices = 116;
    GltfUnbindPrimitiveMaterialPayloadV1 unbind_primitive_material = 117;
    GltfUnbindSceneRootNodePayloadV1 unbind_scene_root_node = 118;
    GltfUnrequireExtensionMutationV1 remove_required_extension = 119;
    GltfWithdrawUsedExtensionMutationV1 remove_used_extension = 120;
  }
}
