// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gateway/v1/gateway.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Semio.Gateway.V1 {

  /// <summary>Holder for reflection information generated from gateway/v1/gateway.proto</summary>
  public static partial class GatewayReflection {

    #region Descriptor
    /// <summary>File descriptor for gateway/v1/gateway.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GatewayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhnYXRld2F5L3YxL2dhdGV3YXkucHJvdG8SEHNlbWlvLmdhdGV3YXkudjEa",
            "FG1vZGVsL3YxL21vZGVsLnByb3RvGhxhc3NlbWJsZXIvdjEvYXNzZW1ibGVy",
            "LnByb3RvMmMKDkdhdGV3YXlTZXJ2aWNlElEKDExheW91dERlc2lnbhInLnNl",
            "bWlvLmFzc2VtYmxlci52MS5MYXlvdXREZXNpZ25SZXF1ZXN0GhYuc2VtaW8u",
            "bW9kZWwudjEuRGVzaWduIgBCugEKFGNvbS5zZW1pby5nYXRld2F5LnYxQgxH",
            "YXRld2F5UHJvdG9QAVoyZ2l0aHViLmNvbS91c2FsdS9zZW1pby9zcmMvc2No",
            "ZW1hL3NlbWlvL2dhdGV3YXkvdjGiAgNTR1iqAhBTZW1pby5HYXRld2F5LlYx",
            "ygIQU2VtaW9cR2F0ZXdheVxWMeICHFNlbWlvXEdhdGV3YXlcVjFcR1BCTWV0",
            "YWRhdGHqAhJTZW1pbzo6R2F0ZXdheTo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Semio.Model.V1.ModelReflection.Descriptor, global::Semio.Assembler.V1.AssemblerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
