// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: manager/v1/manager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Semio.Manager.V1 {

  /// <summary>Holder for reflection information generated from manager/v1/manager.proto</summary>
  public static partial class ManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for manager/v1/manager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhtYW5hZ2VyL3YxL21hbmFnZXIucHJvdG8SEHNlbWlvLm1hbmFnZXIudjEa",
            "FG1vZGVsL3YxL21vZGVsLnByb3RvGhxleHRlbnNpb24vdjEvZXh0ZW5zaW9u",
            "LnByb3RvImsKDkVsZW1lbnRSZXF1ZXN0EjEKB3NvYmplY3QYASABKAsyFy5z",
            "ZW1pby5tb2RlbC52MS5Tb2JqZWN0Ugdzb2JqZWN0EiYKD3RhcmdldF90eXBl",
            "X3VybBgCIAEoCVINdGFyZ2V0VHlwZVVybCJ3ChFBdHRyYWN0aW9uUmVxdWVz",
            "dBI6CgphdHRyYWN0aW9uGAEgASgLMhouc2VtaW8ubW9kZWwudjEuQXR0cmFj",
            "dGlvblIKYXR0cmFjdGlvbhImCg90YXJnZXRfdHlwZV91cmwYAiABKAlSDXRh",
            "cmdldFR5cGVVcmwikwEKEkF0dHJhY3Rpb25SZXNwb25zZRI7Cg5hdHRyYWN0",
            "ZWRfcG9zZRgBIAEoCzIULnNlbWlvLm1vZGVsLnYxLlBvc2VSDWF0dHJhY3Rl",
            "ZFBvc2USQAoQYXR0cmFjdGlvbl9wb2ludBgCIAEoCzIVLnNlbWlvLm1vZGVs",
            "LnYxLlBvaW50Ug9hdHRyYWN0aW9uUG9pbnQioAEKHEV4dGVuc2lvblJlZ2lz",
            "dHJhdGlvblJlcXVlc3QSGAoHYWRkcmVzcxgBIAEoCVIHYWRkcmVzcxI7Cgll",
            "eHRlbmRpbmcYAiABKAsyHS5zZW1pby5leHRlbnNpb24udjEuRXh0ZW5kaW5n",
            "UglleHRlbmRpbmcSKQoQcmVwbGFjZV9leGlzdGluZxgDIAEoCFIPcmVwbGFj",
            "ZUV4aXN0aW5nIloKHUV4dGVuc2lvblJlZ2lzdHJhdGlvblJlc3BvbnNlEhgK",
            "B3N1Y2Nlc3MYASABKAhSB3N1Y2Nlc3MSHwoLb2xkX2FkZHJlc3MYAiABKAlS",
            "Cm9sZEFkZHJlc3MiIAoeR2V0UmVnaXN0ZXJlZEV4dGVuc2lvbnNSZXF1ZXN0",
            "ItwBChxSZWdpc3RlcmVkRXh0ZW5zaW9uc1Jlc3BvbnNlEl4KCmV4dGVuc2lv",
            "bnMYASADKAsyPi5zZW1pby5tYW5hZ2VyLnYxLlJlZ2lzdGVyZWRFeHRlbnNp",
            "b25zUmVzcG9uc2UuRXh0ZW5zaW9uc0VudHJ5UgpleHRlbnNpb25zGlwKD0V4",
            "dGVuc2lvbnNFbnRyeRIQCgNrZXkYASABKAlSA2tleRIzCgV2YWx1ZRgCIAEo",
            "CzIdLnNlbWlvLmV4dGVuc2lvbi52MS5FeHRlbmRpbmdSBXZhbHVlOgI4ATK3",
            "AwoOTWFuYWdlclNlcnZpY2USUgoOUmVxdWVzdEVsZW1lbnQSIC5zZW1pby5t",
            "YW5hZ2VyLnYxLkVsZW1lbnRSZXF1ZXN0Gh4uc2VtaW8ubW9kZWwudjEuUmVw",
            "cmVzZW50YXRpb24SXgoRUmVxdWVzdEF0dHJhY3Rpb24SIy5zZW1pby5tYW5h",
            "Z2VyLnYxLkF0dHJhY3Rpb25SZXF1ZXN0GiQuc2VtaW8ubWFuYWdlci52MS5B",
            "dHRyYWN0aW9uUmVzcG9uc2USdAoRUmVnaXN0ZXJFeHRlbnNpb24SLi5zZW1p",
            "by5tYW5hZ2VyLnYxLkV4dGVuc2lvblJlZ2lzdHJhdGlvblJlcXVlc3QaLy5z",
            "ZW1pby5tYW5hZ2VyLnYxLkV4dGVuc2lvblJlZ2lzdHJhdGlvblJlc3BvbnNl",
            "EnsKF0dldFJlZ2lzdGVyZWRFeHRlbnNpb25zEjAuc2VtaW8ubWFuYWdlci52",
            "MS5HZXRSZWdpc3RlcmVkRXh0ZW5zaW9uc1JlcXVlc3QaLi5zZW1pby5tYW5h",
            "Z2VyLnYxLlJlZ2lzdGVyZWRFeHRlbnNpb25zUmVzcG9uc2VCugEKFGNvbS5z",
            "ZW1pby5tYW5hZ2VyLnYxQgxNYW5hZ2VyUHJvdG9QAVoyZ2l0aHViLmNvbS91",
            "c2FsdS9zZW1pby9zcmMvc2NoZW1hL3NlbWlvL21hbmFnZXIvdjGiAgNTTViq",
            "AhBTZW1pby5NYW5hZ2VyLlYxygIQU2VtaW9cTWFuYWdlclxWMeICHFNlbWlv",
            "XE1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhJTZW1pbzo6TWFuYWdlcjo6VjFi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Semio.Model.V1.ModelReflection.Descriptor, global::Semio.Extension.V1.ExtensionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.ElementRequest), global::Semio.Manager.V1.ElementRequest.Parser, new[]{ "Sobject", "TargetTypeUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.AttractionRequest), global::Semio.Manager.V1.AttractionRequest.Parser, new[]{ "Attraction", "TargetTypeUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.AttractionResponse), global::Semio.Manager.V1.AttractionResponse.Parser, new[]{ "AttractedPose", "AttractionPoint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.ExtensionRegistrationRequest), global::Semio.Manager.V1.ExtensionRegistrationRequest.Parser, new[]{ "Address", "Extending", "ReplaceExisting" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.ExtensionRegistrationResponse), global::Semio.Manager.V1.ExtensionRegistrationResponse.Parser, new[]{ "Success", "OldAddress" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.GetRegisteredExtensionsRequest), global::Semio.Manager.V1.GetRegisteredExtensionsRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Manager.V1.RegisteredExtensionsResponse), global::Semio.Manager.V1.RegisteredExtensionsResponse.Parser, new[]{ "Extensions" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ElementRequest : pb::IMessage<ElementRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ElementRequest> _parser = new pb::MessageParser<ElementRequest>(() => new ElementRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ElementRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ElementRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ElementRequest(ElementRequest other) : this() {
      sobject_ = other.sobject_ != null ? other.sobject_.Clone() : null;
      targetTypeUrl_ = other.targetTypeUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ElementRequest Clone() {
      return new ElementRequest(this);
    }

    /// <summary>Field number for the "sobject" field.</summary>
    public const int SobjectFieldNumber = 1;
    private global::Semio.Model.V1.Sobject sobject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Sobject Sobject {
      get { return sobject_; }
      set {
        sobject_ = value;
      }
    }

    /// <summary>Field number for the "target_type_url" field.</summary>
    public const int TargetTypeUrlFieldNumber = 2;
    private string targetTypeUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetTypeUrl {
      get { return targetTypeUrl_; }
      set {
        targetTypeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ElementRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ElementRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Sobject, other.Sobject)) return false;
      if (TargetTypeUrl != other.TargetTypeUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (sobject_ != null) hash ^= Sobject.GetHashCode();
      if (TargetTypeUrl.Length != 0) hash ^= TargetTypeUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (sobject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Sobject);
      }
      if (TargetTypeUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (sobject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Sobject);
      }
      if (TargetTypeUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (sobject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sobject);
      }
      if (TargetTypeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ElementRequest other) {
      if (other == null) {
        return;
      }
      if (other.sobject_ != null) {
        if (sobject_ == null) {
          Sobject = new global::Semio.Model.V1.Sobject();
        }
        Sobject.MergeFrom(other.Sobject);
      }
      if (other.TargetTypeUrl.Length != 0) {
        TargetTypeUrl = other.TargetTypeUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (sobject_ == null) {
              Sobject = new global::Semio.Model.V1.Sobject();
            }
            input.ReadMessage(Sobject);
            break;
          }
          case 18: {
            TargetTypeUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (sobject_ == null) {
              Sobject = new global::Semio.Model.V1.Sobject();
            }
            input.ReadMessage(Sobject);
            break;
          }
          case 18: {
            TargetTypeUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AttractionRequest : pb::IMessage<AttractionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttractionRequest> _parser = new pb::MessageParser<AttractionRequest>(() => new AttractionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AttractionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionRequest(AttractionRequest other) : this() {
      attraction_ = other.attraction_ != null ? other.attraction_.Clone() : null;
      targetTypeUrl_ = other.targetTypeUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionRequest Clone() {
      return new AttractionRequest(this);
    }

    /// <summary>Field number for the "attraction" field.</summary>
    public const int AttractionFieldNumber = 1;
    private global::Semio.Model.V1.Attraction attraction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Attraction Attraction {
      get { return attraction_; }
      set {
        attraction_ = value;
      }
    }

    /// <summary>Field number for the "target_type_url" field.</summary>
    public const int TargetTypeUrlFieldNumber = 2;
    private string targetTypeUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetTypeUrl {
      get { return targetTypeUrl_; }
      set {
        targetTypeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AttractionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AttractionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Attraction, other.Attraction)) return false;
      if (TargetTypeUrl != other.TargetTypeUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (attraction_ != null) hash ^= Attraction.GetHashCode();
      if (TargetTypeUrl.Length != 0) hash ^= TargetTypeUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (attraction_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Attraction);
      }
      if (TargetTypeUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (attraction_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Attraction);
      }
      if (TargetTypeUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (attraction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Attraction);
      }
      if (TargetTypeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetTypeUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AttractionRequest other) {
      if (other == null) {
        return;
      }
      if (other.attraction_ != null) {
        if (attraction_ == null) {
          Attraction = new global::Semio.Model.V1.Attraction();
        }
        Attraction.MergeFrom(other.Attraction);
      }
      if (other.TargetTypeUrl.Length != 0) {
        TargetTypeUrl = other.TargetTypeUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (attraction_ == null) {
              Attraction = new global::Semio.Model.V1.Attraction();
            }
            input.ReadMessage(Attraction);
            break;
          }
          case 18: {
            TargetTypeUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (attraction_ == null) {
              Attraction = new global::Semio.Model.V1.Attraction();
            }
            input.ReadMessage(Attraction);
            break;
          }
          case 18: {
            TargetTypeUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AttractionResponse : pb::IMessage<AttractionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttractionResponse> _parser = new pb::MessageParser<AttractionResponse>(() => new AttractionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AttractionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionResponse(AttractionResponse other) : this() {
      attractedPose_ = other.attractedPose_ != null ? other.attractedPose_.Clone() : null;
      attractionPoint_ = other.attractionPoint_ != null ? other.attractionPoint_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttractionResponse Clone() {
      return new AttractionResponse(this);
    }

    /// <summary>Field number for the "attracted_pose" field.</summary>
    public const int AttractedPoseFieldNumber = 1;
    private global::Semio.Model.V1.Pose attractedPose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Pose AttractedPose {
      get { return attractedPose_; }
      set {
        attractedPose_ = value;
      }
    }

    /// <summary>Field number for the "attraction_point" field.</summary>
    public const int AttractionPointFieldNumber = 2;
    private global::Semio.Model.V1.Point attractionPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Point AttractionPoint {
      get { return attractionPoint_; }
      set {
        attractionPoint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AttractionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AttractionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AttractedPose, other.AttractedPose)) return false;
      if (!object.Equals(AttractionPoint, other.AttractionPoint)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (attractedPose_ != null) hash ^= AttractedPose.GetHashCode();
      if (attractionPoint_ != null) hash ^= AttractionPoint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (attractedPose_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AttractedPose);
      }
      if (attractionPoint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AttractionPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (attractedPose_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AttractedPose);
      }
      if (attractionPoint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AttractionPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (attractedPose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttractedPose);
      }
      if (attractionPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttractionPoint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AttractionResponse other) {
      if (other == null) {
        return;
      }
      if (other.attractedPose_ != null) {
        if (attractedPose_ == null) {
          AttractedPose = new global::Semio.Model.V1.Pose();
        }
        AttractedPose.MergeFrom(other.AttractedPose);
      }
      if (other.attractionPoint_ != null) {
        if (attractionPoint_ == null) {
          AttractionPoint = new global::Semio.Model.V1.Point();
        }
        AttractionPoint.MergeFrom(other.AttractionPoint);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (attractedPose_ == null) {
              AttractedPose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(AttractedPose);
            break;
          }
          case 18: {
            if (attractionPoint_ == null) {
              AttractionPoint = new global::Semio.Model.V1.Point();
            }
            input.ReadMessage(AttractionPoint);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (attractedPose_ == null) {
              AttractedPose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(AttractedPose);
            break;
          }
          case 18: {
            if (attractionPoint_ == null) {
              AttractionPoint = new global::Semio.Model.V1.Point();
            }
            input.ReadMessage(AttractionPoint);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExtensionRegistrationRequest : pb::IMessage<ExtensionRegistrationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtensionRegistrationRequest> _parser = new pb::MessageParser<ExtensionRegistrationRequest>(() => new ExtensionRegistrationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtensionRegistrationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationRequest(ExtensionRegistrationRequest other) : this() {
      address_ = other.address_;
      extending_ = other.extending_ != null ? other.extending_.Clone() : null;
      replaceExisting_ = other.replaceExisting_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationRequest Clone() {
      return new ExtensionRegistrationRequest(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private string address_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "extending" field.</summary>
    public const int ExtendingFieldNumber = 2;
    private global::Semio.Extension.V1.Extending extending_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Extension.V1.Extending Extending {
      get { return extending_; }
      set {
        extending_ = value;
      }
    }

    /// <summary>Field number for the "replace_existing" field.</summary>
    public const int ReplaceExistingFieldNumber = 3;
    private bool replaceExisting_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ReplaceExisting {
      get { return replaceExisting_; }
      set {
        replaceExisting_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtensionRegistrationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtensionRegistrationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Address != other.Address) return false;
      if (!object.Equals(Extending, other.Extending)) return false;
      if (ReplaceExisting != other.ReplaceExisting) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (extending_ != null) hash ^= Extending.GetHashCode();
      if (ReplaceExisting != false) hash ^= ReplaceExisting.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (extending_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Extending);
      }
      if (ReplaceExisting != false) {
        output.WriteRawTag(24);
        output.WriteBool(ReplaceExisting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (extending_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Extending);
      }
      if (ReplaceExisting != false) {
        output.WriteRawTag(24);
        output.WriteBool(ReplaceExisting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (extending_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extending);
      }
      if (ReplaceExisting != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtensionRegistrationRequest other) {
      if (other == null) {
        return;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.extending_ != null) {
        if (extending_ == null) {
          Extending = new global::Semio.Extension.V1.Extending();
        }
        Extending.MergeFrom(other.Extending);
      }
      if (other.ReplaceExisting != false) {
        ReplaceExisting = other.ReplaceExisting;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 18: {
            if (extending_ == null) {
              Extending = new global::Semio.Extension.V1.Extending();
            }
            input.ReadMessage(Extending);
            break;
          }
          case 24: {
            ReplaceExisting = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 18: {
            if (extending_ == null) {
              Extending = new global::Semio.Extension.V1.Extending();
            }
            input.ReadMessage(Extending);
            break;
          }
          case 24: {
            ReplaceExisting = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExtensionRegistrationResponse : pb::IMessage<ExtensionRegistrationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtensionRegistrationResponse> _parser = new pb::MessageParser<ExtensionRegistrationResponse>(() => new ExtensionRegistrationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtensionRegistrationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationResponse(ExtensionRegistrationResponse other) : this() {
      success_ = other.success_;
      oldAddress_ = other.oldAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionRegistrationResponse Clone() {
      return new ExtensionRegistrationResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "old_address" field.</summary>
    public const int OldAddressFieldNumber = 2;
    private string oldAddress_ = "";
    /// <summary>
    /// The old address of the same service type if there was one.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OldAddress {
      get { return oldAddress_; }
      set {
        oldAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtensionRegistrationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtensionRegistrationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (OldAddress != other.OldAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (OldAddress.Length != 0) hash ^= OldAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (OldAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OldAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (OldAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OldAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (OldAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OldAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtensionRegistrationResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.OldAddress.Length != 0) {
        OldAddress = other.OldAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            OldAddress = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            OldAddress = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetRegisteredExtensionsRequest : pb::IMessage<GetRegisteredExtensionsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRegisteredExtensionsRequest> _parser = new pb::MessageParser<GetRegisteredExtensionsRequest>(() => new GetRegisteredExtensionsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRegisteredExtensionsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRegisteredExtensionsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRegisteredExtensionsRequest(GetRegisteredExtensionsRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRegisteredExtensionsRequest Clone() {
      return new GetRegisteredExtensionsRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRegisteredExtensionsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRegisteredExtensionsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRegisteredExtensionsRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RegisteredExtensionsResponse : pb::IMessage<RegisteredExtensionsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisteredExtensionsResponse> _parser = new pb::MessageParser<RegisteredExtensionsResponse>(() => new RegisteredExtensionsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisteredExtensionsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Manager.V1.ManagerReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisteredExtensionsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisteredExtensionsResponse(RegisteredExtensionsResponse other) : this() {
      extensions_ = other.extensions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisteredExtensionsResponse Clone() {
      return new RegisteredExtensionsResponse(this);
    }

    /// <summary>Field number for the "extensions" field.</summary>
    public const int ExtensionsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Semio.Extension.V1.Extending>.Codec _map_extensions_codec
        = new pbc::MapField<string, global::Semio.Extension.V1.Extending>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Semio.Extension.V1.Extending.Parser), 10);
    private readonly pbc::MapField<string, global::Semio.Extension.V1.Extending> extensions_ = new pbc::MapField<string, global::Semio.Extension.V1.Extending>();
    /// <summary>
    /// A map with extensions where the address is the key and the extension description is the value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Semio.Extension.V1.Extending> Extensions {
      get { return extensions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisteredExtensionsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisteredExtensionsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Extensions.Equals(other.Extensions)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Extensions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      extensions_.WriteTo(output, _map_extensions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      extensions_.WriteTo(ref output, _map_extensions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += extensions_.CalculateSize(_map_extensions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisteredExtensionsResponse other) {
      if (other == null) {
        return;
      }
      extensions_.Add(other.extensions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            extensions_.AddEntriesFrom(input, _map_extensions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            extensions_.AddEntriesFrom(ref input, _map_extensions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
