// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server/v1/server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Semio.Server.V1 {

  /// <summary>Holder for reflection information generated from server/v1/server.proto</summary>
  public static partial class ServerReflection {

    #region Descriptor
    /// <summary>File descriptor for server/v1/server.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZzZXJ2ZXIvdjEvc2VydmVyLnByb3RvEg9zZW1pby5zZXJ2ZXIudjEaFG1v",
            "ZGVsL3YxL21vZGVsLnByb3RvGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnBy",
            "b3RvGhdnb29nbGUvYXBpL2NsaWVudC5wcm90bxoZZ29vZ2xlL2FwaS9yZXNv",
            "dXJjZS5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvImYKE0xh",
            "eW91dERlc2lnblJlcXVlc3QSLgoGbGF5b3V0GAEgASgLMhYuc2VtaW8ubW9k",
            "ZWwudjEuTGF5b3V0UgZsYXlvdXQSHwoLdGFyZ2V0X3R5cGUYAiABKAlSCnRh",
            "cmdldFR5cGUygAEKDVNlcnZlclNlcnZpY2USWwoMTGF5b3V0RGVzaWduEhYu",
            "c2VtaW8ubW9kZWwudjEuTGF5b3V0GhYuc2VtaW8ubW9kZWwudjEuRGVzaWdu",
            "IhuC0+STAhU6ASoiEHYxL2xheW91dC1kZXNpZ24aEspBD2xvY2FsaG9zdDo1",
            "MDAwMEKAAQoTY29tLnNlbWlvLnNlcnZlci52MUILU2VydmVyUHJvdG9QAaIC",
            "A1NTWKoCD1NlbWlvLlNlcnZlci5WMcoCD1NlbWlvXFNlcnZlclxWMeICG1Nl",
            "bWlvXFNlcnZlclxWMVxHUEJNZXRhZGF0YeoCEVNlbWlvOjpTZXJ2ZXI6OlYx",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Semio.Model.V1.ModelReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ClientReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Server.V1.LayoutDesignRequest), global::Semio.Server.V1.LayoutDesignRequest.Parser, new[]{ "Layout", "TargetType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LayoutDesignRequest : pb::IMessage<LayoutDesignRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LayoutDesignRequest> _parser = new pb::MessageParser<LayoutDesignRequest>(() => new LayoutDesignRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LayoutDesignRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Server.V1.ServerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayoutDesignRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayoutDesignRequest(LayoutDesignRequest other) : this() {
      layout_ = other.layout_ != null ? other.layout_.Clone() : null;
      targetType_ = other.targetType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LayoutDesignRequest Clone() {
      return new LayoutDesignRequest(this);
    }

    /// <summary>Field number for the "layout" field.</summary>
    public const int LayoutFieldNumber = 1;
    private global::Semio.Model.V1.Layout layout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Layout Layout {
      get { return layout_; }
      set {
        layout_ = value;
      }
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 2;
    private string targetType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetType {
      get { return targetType_; }
      set {
        targetType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LayoutDesignRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LayoutDesignRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Layout, other.Layout)) return false;
      if (TargetType != other.TargetType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (layout_ != null) hash ^= Layout.GetHashCode();
      if (TargetType.Length != 0) hash ^= TargetType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (layout_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Layout);
      }
      if (TargetType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (layout_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Layout);
      }
      if (TargetType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (layout_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Layout);
      }
      if (TargetType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LayoutDesignRequest other) {
      if (other == null) {
        return;
      }
      if (other.layout_ != null) {
        if (layout_ == null) {
          Layout = new global::Semio.Model.V1.Layout();
        }
        Layout.MergeFrom(other.Layout);
      }
      if (other.TargetType.Length != 0) {
        TargetType = other.TargetType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (layout_ == null) {
              Layout = new global::Semio.Model.V1.Layout();
            }
            input.ReadMessage(Layout);
            break;
          }
          case 18: {
            TargetType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (layout_ == null) {
              Layout = new global::Semio.Model.V1.Layout();
            }
            input.ReadMessage(Layout);
            break;
          }
          case 18: {
            TargetType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
