// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extension/translator/v1/translator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Semio.Extension.Translator.V1 {

  /// <summary>Holder for reflection information generated from extension/translator/v1/translator.proto</summary>
  public static partial class TranslatorReflection {

    #region Descriptor
    /// <summary>File descriptor for extension/translator/v1/translator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TranslatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihleHRlbnNpb24vdHJhbnNsYXRvci92MS90cmFuc2xhdG9yLnByb3RvEh1z",
            "ZW1pby5leHRlbnNpb24udHJhbnNsYXRvci52MRoUbW9kZWwvdjEvbW9kZWwu",
            "cHJvdG8iKAoLVHJhbnNsYXRpbmcSGQoIdHlwZV91cmwYASABKAlSB3R5cGVV",
            "cmwi1gEKHlRyYW5zbGF0ZVJlcHJlc2VudGF0aW9uUmVxdWVzdBJGCg5yZXBy",
            "ZXNlbnRhdGlvbhgBIAEoCzIeLnNlbWlvLm1vZGVsLnYxLlJlcHJlc2VudGF0",
            "aW9uUg5yZXByZXNlbnRhdGlvbhI1Cgt0YXJnZXRfcG9zZRgCIAEoCzIULnNl",
            "bWlvLm1vZGVsLnYxLlBvc2VSCnRhcmdldFBvc2USNQoLc291cmNlX3Bvc2UY",
            "AyABKAsyFC5zZW1pby5tb2RlbC52MS5Qb3NlUgpzb3VyY2VQb3NlMo0BChFU",
            "cmFuc2xhdG9yU2VydmljZRJ4ChdUcmFuc2xhdGVSZXByZXNlbnRhdGlvbhI9",
            "LnNlbWlvLmV4dGVuc2lvbi50cmFuc2xhdG9yLnYxLlRyYW5zbGF0ZVJlcHJl",
            "c2VudGF0aW9uUmVxdWVzdBoeLnNlbWlvLm1vZGVsLnYxLlJlcHJlc2VudGF0",
            "aW9uQowCCiFjb20uc2VtaW8uZXh0ZW5zaW9uLnRyYW5zbGF0b3IudjFCD1Ry",
            "YW5zbGF0b3JQcm90b1ABWj9naXRodWIuY29tL3VzYWx1L3NlbWlvL3NyYy9z",
            "Y2hlbWEvc2VtaW8vZXh0ZW5zaW9uL3RyYW5zbGF0b3IvdjGiAgNTRVSqAh1T",
            "ZW1pby5FeHRlbnNpb24uVHJhbnNsYXRvci5WMcoCHVNlbWlvXEV4dGVuc2lv",
            "blxUcmFuc2xhdG9yXFYx4gIpU2VtaW9cRXh0ZW5zaW9uXFRyYW5zbGF0b3Jc",
            "VjFcR1BCTWV0YWRhdGHqAiBTZW1pbzo6RXh0ZW5zaW9uOjpUcmFuc2xhdG9y",
            "OjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Semio.Model.V1.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Extension.Translator.V1.Translating), global::Semio.Extension.Translator.V1.Translating.Parser, new[]{ "TypeUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Extension.Translator.V1.TranslateRepresentationRequest), global::Semio.Extension.Translator.V1.TranslateRepresentationRequest.Parser, new[]{ "Representation", "TargetPose", "SourcePose" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Translating : pb::IMessage<Translating>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Translating> _parser = new pb::MessageParser<Translating>(() => new Translating());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Translating> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Extension.Translator.V1.TranslatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Translating() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Translating(Translating other) : this() {
      typeUrl_ = other.typeUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Translating Clone() {
      return new Translating(this);
    }

    /// <summary>Field number for the "type_url" field.</summary>
    public const int TypeUrlFieldNumber = 1;
    private string typeUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TypeUrl {
      get { return typeUrl_; }
      set {
        typeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Translating);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Translating other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TypeUrl != other.TypeUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TypeUrl.Length != 0) hash ^= TypeUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TypeUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TypeUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TypeUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TypeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TypeUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Translating other) {
      if (other == null) {
        return;
      }
      if (other.TypeUrl.Length != 0) {
        TypeUrl = other.TypeUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TypeUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TypeUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TranslateRepresentationRequest : pb::IMessage<TranslateRepresentationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TranslateRepresentationRequest> _parser = new pb::MessageParser<TranslateRepresentationRequest>(() => new TranslateRepresentationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TranslateRepresentationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Extension.Translator.V1.TranslatorReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TranslateRepresentationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TranslateRepresentationRequest(TranslateRepresentationRequest other) : this() {
      representation_ = other.representation_ != null ? other.representation_.Clone() : null;
      targetPose_ = other.targetPose_ != null ? other.targetPose_.Clone() : null;
      sourcePose_ = other.sourcePose_ != null ? other.sourcePose_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TranslateRepresentationRequest Clone() {
      return new TranslateRepresentationRequest(this);
    }

    /// <summary>Field number for the "representation" field.</summary>
    public const int RepresentationFieldNumber = 1;
    private global::Semio.Model.V1.Representation representation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Representation Representation {
      get { return representation_; }
      set {
        representation_ = value;
      }
    }

    /// <summary>Field number for the "target_pose" field.</summary>
    public const int TargetPoseFieldNumber = 2;
    private global::Semio.Model.V1.Pose targetPose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Pose TargetPose {
      get { return targetPose_; }
      set {
        targetPose_ = value;
      }
    }

    /// <summary>Field number for the "source_pose" field.</summary>
    public const int SourcePoseFieldNumber = 3;
    private global::Semio.Model.V1.Pose sourcePose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Pose SourcePose {
      get { return sourcePose_; }
      set {
        sourcePose_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TranslateRepresentationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TranslateRepresentationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Representation, other.Representation)) return false;
      if (!object.Equals(TargetPose, other.TargetPose)) return false;
      if (!object.Equals(SourcePose, other.SourcePose)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (representation_ != null) hash ^= Representation.GetHashCode();
      if (targetPose_ != null) hash ^= TargetPose.GetHashCode();
      if (sourcePose_ != null) hash ^= SourcePose.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (representation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Representation);
      }
      if (targetPose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPose);
      }
      if (sourcePose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SourcePose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (representation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Representation);
      }
      if (targetPose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPose);
      }
      if (sourcePose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SourcePose);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (representation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Representation);
      }
      if (targetPose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPose);
      }
      if (sourcePose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SourcePose);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TranslateRepresentationRequest other) {
      if (other == null) {
        return;
      }
      if (other.representation_ != null) {
        if (representation_ == null) {
          Representation = new global::Semio.Model.V1.Representation();
        }
        Representation.MergeFrom(other.Representation);
      }
      if (other.targetPose_ != null) {
        if (targetPose_ == null) {
          TargetPose = new global::Semio.Model.V1.Pose();
        }
        TargetPose.MergeFrom(other.TargetPose);
      }
      if (other.sourcePose_ != null) {
        if (sourcePose_ == null) {
          SourcePose = new global::Semio.Model.V1.Pose();
        }
        SourcePose.MergeFrom(other.SourcePose);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (representation_ == null) {
              Representation = new global::Semio.Model.V1.Representation();
            }
            input.ReadMessage(Representation);
            break;
          }
          case 18: {
            if (targetPose_ == null) {
              TargetPose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(TargetPose);
            break;
          }
          case 26: {
            if (sourcePose_ == null) {
              SourcePose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(SourcePose);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (representation_ == null) {
              Representation = new global::Semio.Model.V1.Representation();
            }
            input.ReadMessage(Representation);
            break;
          }
          case 18: {
            if (targetPose_ == null) {
              TargetPose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(TargetPose);
            break;
          }
          case 26: {
            if (sourcePose_ == null) {
              SourcePose = new global::Semio.Model.V1.Pose();
            }
            input.ReadMessage(SourcePose);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
