// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extension/transformer/v1/transformer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Semio.Extension.Transformer.V1 {

  /// <summary>Holder for reflection information generated from extension/transformer/v1/transformer.proto</summary>
  public static partial class TransformerReflection {

    #region Descriptor
    /// <summary>File descriptor for extension/transformer/v1/transformer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransformerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipleHRlbnNpb24vdHJhbnNmb3JtZXIvdjEvdHJhbnNmb3JtZXIucHJvdG8S",
            "HnNlbWlvLmV4dGVuc2lvbi50cmFuc2Zvcm1lci52MRoUbW9kZWwvdjEvbW9k",
            "ZWwucHJvdG8iDgoMVHJhbnNmb3JtaW5nIo0BChRSZXdyaXRlTGF5b3V0UmVx",
            "dWVzdBI2CglkZWNpc2lvbnMYASADKAsyGC5zZW1pby5tb2RlbC52MS5EZWNp",
            "c2lvblIJZGVjaXNpb25zEj0KDmluaXRpYWxfbGF5b3V0GAIgASgLMhYuc2Vt",
            "aW8ubW9kZWwudjEuTGF5b3V0Ug1pbml0aWFsTGF5b3V0MnMKElRyYW5zZm9y",
            "bWVyU2VydmljZRJdCg1SZXdyaXRlTGF5b3V0EjQuc2VtaW8uZXh0ZW5zaW9u",
            "LnRyYW5zZm9ybWVyLnYxLlJld3JpdGVMYXlvdXRSZXF1ZXN0GhYuc2VtaW8u",
            "bW9kZWwudjEuTGF5b3V0QpMCCiJjb20uc2VtaW8uZXh0ZW5zaW9uLnRyYW5z",
            "Zm9ybWVyLnYxQhBUcmFuc2Zvcm1lclByb3RvUAFaQGdpdGh1Yi5jb20vdXNh",
            "bHUvc2VtaW8vc3JjL3NjaGVtYS9zZW1pby9leHRlbnNpb24vdHJhbnNmb3Jt",
            "ZXIvdjGiAgNTRVSqAh5TZW1pby5FeHRlbnNpb24uVHJhbnNmb3JtZXIuVjHK",
            "Ah5TZW1pb1xFeHRlbnNpb25cVHJhbnNmb3JtZXJcVjHiAipTZW1pb1xFeHRl",
            "bnNpb25cVHJhbnNmb3JtZXJcVjFcR1BCTWV0YWRhdGHqAiFTZW1pbzo6RXh0",
            "ZW5zaW9uOjpUcmFuc2Zvcm1lcjo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Semio.Model.V1.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Extension.Transformer.V1.Transforming), global::Semio.Extension.Transformer.V1.Transforming.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Semio.Extension.Transformer.V1.RewriteLayoutRequest), global::Semio.Extension.Transformer.V1.RewriteLayoutRequest.Parser, new[]{ "Decisions", "InitialLayout" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Transforming : pb::IMessage<Transforming>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Transforming> _parser = new pb::MessageParser<Transforming>(() => new Transforming());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Transforming> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Extension.Transformer.V1.TransformerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Transforming() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Transforming(Transforming other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Transforming Clone() {
      return new Transforming(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Transforming);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Transforming other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Transforming other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A rewrite layout request is a description for layout (graph) rewrites.
  /// </summary>
  public sealed partial class RewriteLayoutRequest : pb::IMessage<RewriteLayoutRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RewriteLayoutRequest> _parser = new pb::MessageParser<RewriteLayoutRequest>(() => new RewriteLayoutRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RewriteLayoutRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Semio.Extension.Transformer.V1.TransformerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewriteLayoutRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewriteLayoutRequest(RewriteLayoutRequest other) : this() {
      decisions_ = other.decisions_.Clone();
      initialLayout_ = other.initialLayout_ != null ? other.initialLayout_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RewriteLayoutRequest Clone() {
      return new RewriteLayoutRequest(this);
    }

    /// <summary>Field number for the "decisions" field.</summary>
    public const int DecisionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Semio.Model.V1.Decision> _repeated_decisions_codec
        = pb::FieldCodec.ForMessage(10, global::Semio.Model.V1.Decision.Parser);
    private readonly pbc::RepeatedField<global::Semio.Model.V1.Decision> decisions_ = new pbc::RepeatedField<global::Semio.Model.V1.Decision>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Semio.Model.V1.Decision> Decisions {
      get { return decisions_; }
    }

    /// <summary>Field number for the "initial_layout" field.</summary>
    public const int InitialLayoutFieldNumber = 2;
    private global::Semio.Model.V1.Layout initialLayout_;
    /// <summary>
    /// An optional initial layout that is used a starting layout to apply the decisions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Semio.Model.V1.Layout InitialLayout {
      get { return initialLayout_; }
      set {
        initialLayout_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RewriteLayoutRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RewriteLayoutRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!decisions_.Equals(other.decisions_)) return false;
      if (!object.Equals(InitialLayout, other.InitialLayout)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= decisions_.GetHashCode();
      if (initialLayout_ != null) hash ^= InitialLayout.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      decisions_.WriteTo(output, _repeated_decisions_codec);
      if (initialLayout_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InitialLayout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      decisions_.WriteTo(ref output, _repeated_decisions_codec);
      if (initialLayout_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InitialLayout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += decisions_.CalculateSize(_repeated_decisions_codec);
      if (initialLayout_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitialLayout);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RewriteLayoutRequest other) {
      if (other == null) {
        return;
      }
      decisions_.Add(other.decisions_);
      if (other.initialLayout_ != null) {
        if (initialLayout_ == null) {
          InitialLayout = new global::Semio.Model.V1.Layout();
        }
        InitialLayout.MergeFrom(other.InitialLayout);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            decisions_.AddEntriesFrom(input, _repeated_decisions_codec);
            break;
          }
          case 18: {
            if (initialLayout_ == null) {
              InitialLayout = new global::Semio.Model.V1.Layout();
            }
            input.ReadMessage(InitialLayout);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            decisions_.AddEntriesFrom(ref input, _repeated_decisions_codec);
            break;
          }
          case 18: {
            if (initialLayout_ == null) {
              InitialLayout = new global::Semio.Model.V1.Layout();
            }
            input.ReadMessage(InitialLayout);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
