/** 🔖️ Explicit bookmark trees, page labels, named destinations and open actions. */
import type { PdfOutlineItem,PdfNamedDestination,PdfPageLabelRange,PdfPageLabelStyle,PdfOpenAction } from "../../../../../🧬️schema/📸️snapshot/🟦️.ts";
import { PdfProjection,PdfReader,pdfInteger,pdfNumber,pdfBoolean,type Binary64 } from "../../🧩️entity/🟦️.ts";
import { writePdfDictionary,readPdfDictionary } from "../../🧩️cos/🟦️.ts";
import { writePdfDestination,readPdfDestination,writePdfAction,readPdfAction } from "../🟦️.ts";
import { artifactSqliteInteger,artifactSqliteText } from "../../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";

function style(value:string|null|undefined):PdfPageLabelStyle|null{switch(value){case undefined:case null:return null;case "decimal":return "decimal";case "romanUpper":return "romanUpper";case "romanLower":return "romanLower";case "lettersUpper":return "lettersUpper";case "lettersLower":return "lettersLower";default:throw new Error("Unknown PDF page label style");}}
async function writeShallow(out:PdfProjection,value:PdfOutlineItem):Promise<bigint>{const destination=value.destination==null?null:await writePdfDestination(out,value.destination);const action=value.action==null?null:await writePdfAction(out,value.action);const extra=await writePdfDictionary(out,value.extra??[]);if(value.color!=null&&value.color.length!==3)throw new Error("PDF outline color requires three components");return out.insert("pdf_outline",[value.title,destination,action,...(value.color??[null,null,null]),value.italic?1n:0n,value.bold?1n:0n,value.open?1n:0n,extra]);}
async function readShallow(reader:PdfReader,key:bigint):Promise<PdfOutlineItem>{const row=await reader.take("pdf_outline",key,11);let color:[Binary64,Binary64,Binary64]|null=null;const present=!reader.isNull("pdf_outline",row,4);for(const column of [5,6])if(reader.isNull("pdf_outline",row,column)===present)throw new Error("PDF outline color requires all three coordinates");if(present)color=[reader.real("pdf_outline",row,4),reader.real("pdf_outline",row,5),reader.real("pdf_outline",row,6)];return {title:await reader.text(row,1),destination:row.values[2]===null?null:await readPdfDestination(reader,artifactSqliteInteger(row,2)),action:row.values[3]===null?null:await readPdfAction(reader,artifactSqliteInteger(row,3)),color,italic:pdfBoolean(row,7),bold:pdfBoolean(row,8),open:pdfBoolean(row,9),children:[],extra:await readPdfDictionary(reader,artifactSqliteInteger(row,10))};}

/** 🌳️ Project bookmark containment iteratively, rejecting cycles before child materialization. */
export async function writePdfOutline(out:PdfProjection,value:PdfOutlineItem):Promise<bigint>{const root=await writeShallow(out,value);const active=new WeakSet<object>([value]);const pending=[{key:root,value,ordinal:0}];while(pending.length){const frame=pending[pending.length-1]!;const children=frame.value.children??[];out.checkRowsAdditional(2*(children.length-frame.ordinal));if(frame.ordinal<children.length){const ordinal=frame.ordinal++;const value=children[ordinal]!;if(active.has(value))throw new Error("Cyclic PDF outline containment");active.add(value);const key=await writeShallow(out,value);await out.insert("pdf_outline_child",[frame.key,BigInt(ordinal),key]);pending.push({key,value,ordinal:0});}else{active.delete(frame.value);pending.pop();}}return root;}
/** 📥️ Restore ordered bookmark trees with unique entity ownership. */
export async function readPdfOutline(reader:PdfReader,key:bigint):Promise<PdfOutlineItem>{const root=await readShallow(reader,key);const pending=[{value:root,children:await reader.children("pdf_outline_child",1,2,key),ordinal:0}];while(pending.length){const frame=pending[pending.length-1]!;if(frame.ordinal<frame.children.length){const child=frame.children[frame.ordinal++]!;const relation=await reader.take("pdf_outline_child",child.rowid,4);const key=artifactSqliteInteger(relation,3);const value=await readShallow(reader,key);frame.value.children!.push(value);pending.push({value,children:await reader.children("pdf_outline_child",1,2,key),ordinal:0});}else pending.pop();}return root;}
/** 🏷️ Project complete named destination fields. */
export async function writePdfNamedDestination(out:PdfProjection,value:PdfNamedDestination):Promise<bigint>{return out.insert("pdf_named_destination",[value.name,await writePdfDestination(out,value.destination)]);}
/** 📥️ Restore an authored named destination. */
export async function readPdfNamedDestination(reader:PdfReader,key:bigint):Promise<PdfNamedDestination>{const row=await reader.take("pdf_named_destination",key,3);return {name:await reader.text(row,1),destination:await readPdfDestination(reader,artifactSqliteInteger(row,2))};}
/** 🔢️ Project the exact label numbering policy and unsigned native coordinates. */
export async function writePdfLabel(out:PdfProjection,value:PdfPageLabelRange):Promise<bigint>{return out.insert("pdf_page_label",[pdfInteger(value.startIndex),style(value.style),value.prefix??null,pdfInteger(value.start??1)]);}
/** 📥️ Restore all page label fields without inferred defaults. */
export async function readPdfLabel(reader:PdfReader,key:bigint):Promise<PdfPageLabelRange>{const row=await reader.take("pdf_page_label",key,5);return {startIndex:pdfNumber(row,1),style:style(await reader.optionalText(row,2)),prefix:await reader.optionalText(row,3),start:pdfNumber(row,4)};}
/** 🚪️ Project the declared destination or action entry point. */
export async function writePdfOpenAction(out:PdfProjection,value:PdfOpenAction):Promise<bigint>{switch(value.kind){case "destination":return out.insert("pdf_open_action",[value.kind,await writePdfDestination(out,value.destination),null]);case "action":return out.insert("pdf_open_action",[value.kind,null,await writePdfAction(out,value.action)]);default:throw new Error("Unknown PDF open action");}}
/** 📥️ Reject a mixed entry point and restore its exact owner. */
export async function readPdfOpenAction(reader:PdfReader,key:bigint):Promise<PdfOpenAction>{const row=await reader.take("pdf_open_action",key,4);switch(artifactSqliteText(row,1)){case "destination":reader.nullExcept("pdf_open_action",row,2,4,[2]);return {kind:"destination",destination:await readPdfDestination(reader,artifactSqliteInteger(row,2))};case "action":reader.nullExcept("pdf_open_action",row,2,4,[3]);return {kind:"action",action:await readPdfAction(reader,artifactSqliteInteger(row,3))};default:throw new Error("Unknown PDF open action");}}
