[package]
name = "semio-framework-os-kernel-math-graph-connectivity"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_connectivity"
crate-type = ["rlib"]
path = "../../../../🕸️graph/🔗️connectivity/⚡️implementations/🦀️rust/📦️lib.rs"

[dependencies]
mathematical_graph = { path = "../../../../🕸️graph/⚡️implementations/🦀️rust", package = "semio-framework-os-kernel-math-graph" }
mathematical_graph_flow = { path = "../../../../🕸️graph/🌊️flow/⚡️implementations/🦀️rust", package = "semio-framework-os-kernel-math-graph-flow" }
mathematical_graph_components = { path = "../../../../🕸️graph/🧩️components/⚡️implementations/🦀️rust", package = "semio-framework-os-kernel-math-graph-components" }
