[package]
name = "semio-framework-os-kernel-math-sampling"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[dependencies]
mathematical_random = { path = "../../../🎲️random/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-random" }

[lints]
workspace = true
[lib]
name = "mathematical_sampling"
crate-type = ["rlib"]
path = "../../../🎯️sampling/⚡️implementation/🦀️rust/📦️lib.rs"
