[profile.fundamental]
slow-timeout = { period = "15s", terminate-after = 1 }

[profile.quick]
slow-timeout = { period = "300s", terminate-after = 1 }

[profile.long]
slow-timeout = { period = "900s", terminate-after = 1 }

[profile.exhaustive]
slow-timeout = { period = "1800s", terminate-after = 1 }
