//! 🫴️ Genuine guest database admission preserves original backing before and after cancellation.
use super::*;
use semio_framework_value::{NativeEncodeControl,RetainedCloneGrant,RetainedCloneProgress,ValueRefusalKind,native_encoding::NativeEncodeRetirementRecipient};
use semio_framework::sqlite_snapshot::{SqliteDatabase,SqliteRow,SqliteValue,SnapshotEncoding,SqliteSnapshotControl};
use semio_framework_artifact_reference::io::text::artifact_reference::DialectCoordinateText;
use std::cell::Cell;
fn fixture()->serde_json::Value{serde_json::from_str(include_str!("../🧫️fixtures/guest-input-slot.json")).unwrap()}
fn original(f:&serde_json::Value)->Option<SqliteDatabase>{let mut database=SqliteDatabase::from_schema(f["schema"].as_str().unwrap()).unwrap();database.tables[0].rows.push(SqliteRow{rowid:1,values:vec![SqliteValue::Integer(1),SqliteValue::Text(f["value"].as_str().unwrap().into())]});Some(database)}
#[test]
fn probe_sqlite_original_guest_input_slot_refuses_before_adoption(){
 let f=fixture();let dialect=semio_framework_artifact_reference::ArtifactDialect::parse_coordinate(f["dialect"].as_str().unwrap()).unwrap();let mut database=original(&f);let pointer=database.as_ref().unwrap().tables[0].rows[0].text(1).unwrap().as_ptr();let mut observe=|_|true;let mut native=NativeEncodeControl::new(f["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut observe);let mut sql_observe=|_|true;let mut sql=SqliteSnapshotControl::new(&mut sql_observe,Default::default());let mut owner=store::NativeSnapshotEncodeOwner::new(&mut native,serde_json::from_value(f["deniedCloseGrant"].clone()).unwrap());let result=guest_sqlite_import("unregistered.original",&dialect,&mut database,SnapshotEncoding::Text,&mut sql,&mut owner);assert_eq!(result.err().unwrap().cause.kind,ValueRefusalKind::WorkLimit);assert_eq!(owner.progress(),RetainedCloneProgress::default());assert!(database.is_some());assert_eq!(database.as_ref().unwrap().tables[0].rows[0].text(1).unwrap().as_ptr(),pointer);assert_eq!(serde_json::to_value(database.as_ref().unwrap().tables[0].rows[0].text(1).unwrap()).unwrap(),f["value"]);eprintln!("[DEBUG] Genuine guest SQLite caller slot: preadmission refusal keeps exact database backing; independent serde agrees");
}
#[test]
fn probe_sqlite_original_guest_input_slot_canceled_body_retains_receiving_owner(){
 let f=fixture();let caller:RetainedCloneGrant=serde_json::from_value(f["grant"].clone()).unwrap();let dialect=semio_framework_artifact_reference::ArtifactDialect::parse_coordinate(f["dialect"].as_str().unwrap()).unwrap();let mut database=original(&f);let live=Cell::new(true);let mut observe=|_|live.get();let mut recipient=NativeEncodeRetirementRecipient::new();let mut native=NativeEncodeControl::new(f["nativeMaximumBytes"].as_u64().unwrap()as usize,&mut observe);native.install_retirement_recipient(&mut recipient).unwrap();let mut sql_observe=|_|{live.set(false);false};let mut sql=SqliteSnapshotControl::new(&mut sql_observe,Default::default());let mut owner=store::NativeSnapshotEncodeOwner::new(&mut native,caller);let result=guest_sqlite_import("unregistered.original",&dialect,&mut database,SnapshotEncoding::Text,&mut sql,&mut owner);assert_eq!(result.err().unwrap().cause.kind,ValueRefusalKind::Canceled);assert!(owner.progress().retained_capacity_bytes>0);drop(owner);assert!(database.is_none());assert!(native.has_retirement_owner());live.set(true);let step=native.close_retirement_recipient(serde_json::from_value(f["deniedCloseGrant"].clone()).unwrap()).unwrap();assert_eq!(step.progress(),RetainedCloneProgress::default());assert!(native.has_retirement_owner());let close:RetainedCloneGrant=serde_json::from_value(f["closeGrant"].clone()).unwrap();assert_eq!(f["closeAuthority"],"independentCallerWallet");let mut receipt=RetainedCloneProgress::default();for _ in 0..f["maximumTurns"].as_u64().unwrap(){if !native.has_retirement_owner(){break}assert!(receipt.fits(close));let remaining=RetainedCloneGrant{maximum_items:close.maximum_items-receipt.copied_items,maximum_copy_bytes:close.maximum_copy_bytes-receipt.copied_bytes,maximum_capacity_bytes:close.maximum_capacity_bytes-receipt.retained_capacity_bytes,maximum_release_bytes:close.maximum_release_bytes-receipt.released_bytes,..close};let step=native.close_retirement_recipient(remaining).unwrap();receipt=receipt.checked_add(step.progress()).unwrap();}assert!(!native.has_retirement_owner());eprintln!("[DEBUG] Genuine guest SQLite original input adopted only after frame birth; canceled body retains actual recipient, zero close unchanged, funded close terminal");
}

#[test]
fn probe_sqlite_original_coordinate_prebirth_keeps_exact_slot_and_physical_receipt(){
 let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/coordinate.json")).unwrap();let original:RetainedCloneGrant=serde_json::from_value(f["bodyGrant"].clone()).unwrap();let close:RetainedCloneGrant=serde_json::from_value(f["closeGrant"].clone()).unwrap();let bytes=f["originalBytes"].as_u64().unwrap()as usize;let dialect=semio_framework_artifact_reference::ArtifactDialect::parse_coordinate(f["coordinate"].as_str().unwrap()).unwrap();
 for axis in ["work","copy","capacity","depth"]{let mut denied=original;match axis{"work"=>denied.maximum_items=0,"copy"=>denied.maximum_copy_bytes=f["oneShortBytes"].as_u64().unwrap()as usize,"capacity"=>denied.maximum_capacity_bytes=f["oneShortBytes"].as_u64().unwrap()as usize,"depth"=>denied.maximum_depth=0,_=>unreachable!()};let mut coordinate=String::new();let pointer=coordinate.as_ptr();let mut accept=|_|true;let mut native=NativeEncodeControl::new(bytes,&mut accept);let mut owner=store::NativeSnapshotEncodeOwner::new(&mut native,denied);let(result,born,released)=crate::test_allocation::observe_backing(||guest_sqlite_import_coordinate(&dialect,&mut coordinate,&mut owner));assert_eq!(result.unwrap_err().kind,match axis{"work"=>ValueRefusalKind::WorkLimit,"depth"=>ValueRefusalKind::DepthLimit,_=>ValueRefusalKind::OwnershipLimit});assert_eq!((born,released,owner.progress()),(0,0,RetainedCloneProgress::default()));assert_eq!((coordinate.as_ptr(),coordinate.len(),coordinate.capacity()),(pointer,0,0));}
 let mut coordinate=String::new();let mut accept=|_|true;let mut native=NativeEncodeControl::new(bytes,&mut accept);let mut owner=store::NativeSnapshotEncodeOwner::new(&mut native,original);let(result,born,released)=crate::test_allocation::observe_backing(||guest_sqlite_import_coordinate(&dialect,&mut coordinate,&mut owner));result.unwrap();assert_eq!((born,released),(bytes,0));assert_eq!(owner.progress(),RetainedCloneProgress{copied_items:1,copied_bytes:bytes,retained_capacity_bytes:bytes,released_bytes:0});assert_eq!(coordinate.capacity(),bytes);assert_eq!(coordinate,f["coordinate"].as_str().unwrap());drop(owner);
 let mut destination=semio_framework_value::retirement::ControlledRetirement::new(coordinate).ok().unwrap();let pointer=destination.original().unwrap().as_ptr();let(zero,born,released)=crate::test_allocation::observe_backing(||destination.step(serde_json::from_value(f["deniedCloseGrant"].clone()).unwrap()).unwrap());assert_eq!((zero.progress(),born,released),(RetainedCloneProgress::default(),0,0));assert_eq!(destination.original().unwrap().as_ptr(),pointer);let mut receipt=RetainedCloneProgress::default();for _ in 0..4096{if destination.terminal_is_empty(){break}assert!(receipt.fits(close));let remaining=RetainedCloneGrant{maximum_items:close.maximum_items-receipt.copied_items,maximum_copy_bytes:close.maximum_copy_bytes-receipt.copied_bytes,maximum_capacity_bytes:close.maximum_capacity_bytes-receipt.retained_capacity_bytes,maximum_release_bytes:close.maximum_release_bytes-receipt.released_bytes,..close};let(step,born,released)=crate::test_allocation::observe_backing(||destination.step(remaining).unwrap());assert_eq!((born,released),(step.progress().retained_capacity_bytes,step.progress().released_bytes));receipt=receipt.checked_add(step.progress()).unwrap();}assert!(destination.terminal_is_empty());assert_eq!(receipt.released_bytes,bytes+receipt.retained_capacity_bytes);eprintln!("[DEBUG] Actual guest coordinate helper four prebirth denials heap0 and exact pointer unchanged; original30-byte allocator birth posted to same wallet, independently funded cumulative destination close conserved");
}

#[test]
fn probe_sqlite_original_coordinate_cancellation_retains_paid_original_prefix(){
 let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/coordinate.json")).unwrap();let original:RetainedCloneGrant=serde_json::from_value(f["bodyGrant"].clone()).unwrap();let close:RetainedCloneGrant=serde_json::from_value(f["closeGrant"].clone()).unwrap();let bytes=f["originalBytes"].as_u64().unwrap()as usize;let copied=f["canceledCopyBytes"].as_u64().unwrap()as usize;let dialect=semio_framework_artifact_reference::ArtifactDialect::parse_coordinate(f["coordinate"].as_str().unwrap()).unwrap();let mut coordinate=String::new();let mut observe=|progress:semio_framework_value::native_encoding::NativeEncodeProgress|progress.completed<copied;let mut native=NativeEncodeControl::new(bytes,&mut observe);let mut owner=store::NativeSnapshotEncodeOwner::new(&mut native,original);let(result,born,released)=crate::test_allocation::observe_backing(||guest_sqlite_import_coordinate(&dialect,&mut coordinate,&mut owner));let error=result.unwrap_err();assert_eq!(error.kind,ValueRefusalKind::Canceled);let progress=RetainedCloneProgress{copied_items:1,copied_bytes:copied,retained_capacity_bytes:bytes,released_bytes:0};assert_eq!(owner.progress(),progress);assert_eq!(error.retained_progress(),progress);assert_eq!((born,released),(bytes,0));assert_eq!((coordinate.as_str(),coordinate.capacity()),(f["canceledPrefix"].as_str().unwrap(),bytes));drop(owner);
 let mut destination=semio_framework_value::retirement::ControlledRetirement::new(coordinate).ok().unwrap();let mut receipt=RetainedCloneProgress::default();for _ in 0..4096{if destination.terminal_is_empty(){break}assert!(receipt.fits(close));let grant=RetainedCloneGrant{maximum_items:close.maximum_items-receipt.copied_items,maximum_copy_bytes:close.maximum_copy_bytes-receipt.copied_bytes,maximum_capacity_bytes:close.maximum_capacity_bytes-receipt.retained_capacity_bytes,maximum_release_bytes:close.maximum_release_bytes-receipt.released_bytes,..close};let(step,born,released)=crate::test_allocation::observe_backing(||destination.step(grant).unwrap());assert_eq!((born,released),(step.progress().retained_capacity_bytes,step.progress().released_bytes));receipt=receipt.checked_add(step.progress()).unwrap();}assert!(destination.terminal_is_empty());assert_eq!(receipt.released_bytes,bytes+receipt.retained_capacity_bytes);eprintln!("[DEBUG] Actual guest coordinate cancellation preserves original21-byte prefix inside original30-byte backing; same paid receipt retained on original error and independent cumulative close conserved");
}
