syntax = "proto3";
package stdio.tiff.mutation;
import "🧭️change-byte-order/🛰️.proto";
import "📥️insert-ifd/🛰️.proto";
import "📤️remove-ifd/🛰️.proto";
import "🏷️replace-tag/🛰️.proto";
import "🗑️remove-tag/🛰️.proto";
import "🟪️replace-pixels/🛰️.proto";
message TiffMutation { oneof mutation { ChangeByteOrderMutation change_byte_order = 2; InsertIfdMutation insert_ifd = 3; RemoveIfdMutation remove_ifd = 4; ReplaceTagMutation replace_tag = 5; RemoveTagMutation remove_tag = 6; ReplacePixelsMutation replace_pixels = 7; } }
