[package]
name = "imperative_engine"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "../../../../../✏️s/🔨module/📜imperative/⚡️implementation/🦀rust/📦lib.rs"

[dependencies]
neural_engine = { path = "../../../../../🧰framework/🛍️product/💻os/🔨module/🧠neural/⚙️engine/⚡️implementation/🦀rust", package = "semio-framework-os-kernel-neural-engine" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
vcs = { path = "../../../../../🧰framework/🛍️product/💻os/🔨module/🌿vcs/⚡️implementation/🦀rust", package = "semio-framework-os-kernel-vcs" }
store = { path = "../../../../../🧰framework/🛍️product/💻os/🔨module/🏪store/⚡️implementation/🦀rust", package = "semio-framework-os-kernel-store" }
protocol = { path = "../../../../../🧰framework/🛍️product/💻os/🔨module/📡protocol/⚡️implementation/🦀rust", package = "semio-framework-os-kernel-protocol" }
imperative_module_core = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🫀core/⚡️implementation/🦀rust", package = "imperative_module_core" }
imperative_module_text = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/📝text/⚡️implementation/🦀rust", package = "imperative_module_text" }
imperative_module_math = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🧮math/⚡️implementation/🦀rust", package = "imperative_module_math" }
imperative_module_logic = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🧠logic/⚡️implementation/🦀rust", package = "imperative_module_logic" }
imperative_module_control = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🎮control/⚡️implementation/🦀rust", package = "imperative_module_control" }

[dev-dependencies]
imperative_module_core = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🫀core/⚡️implementation/🦀rust", package = "imperative_module_core" }
imperative_module_text = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/📝text/⚡️implementation/🦀rust", package = "imperative_module_text" }
imperative_module_math = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🧮math/⚡️implementation/🦀rust", package = "imperative_module_math" }
imperative_module_logic = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🧠logic/⚡️implementation/🦀rust", package = "imperative_module_logic" }
imperative_module_control = { path = "../../../../../✏️s/🔌plugin/📜imperative/🧩extension/🎮control/⚡️implementation/🦀rust", package = "imperative_module_control" }
