/** 🔔️ Original Host embedding supplies full authority and collects each original wake receipt before a successor effect. */
import{test,expect}from"bun:test";import Ajv from"ajv";import{Database}from"bun:sqlite";import{applyPatch}from"fast-json-patch";import{readFileSync}from"node:fs";
test("original Host wake registration requires explicit embedding and original receipt custody",async()=>{const law=await Bun.file(new URL("../🧫️fixtures/🔣️.json",import.meta.url)).json(),schema=await Bun.file(new URL("../🧬️schema/🔣️.json",import.meta.url)).json();expect(new Ajv({strict:true}).compile(schema)(law)).toBe(true);const db=new Database(":memory:");try{db.run("CREATE TABLE receipt(phase INTEGER,items INTEGER,copy INTEGER,capacity INTEGER,release INTEGER,collected INTEGER)");for(const[phase,receipt]of law.receipts.entries())db.run("INSERT INTO receipt VALUES(?,?,?,?,?,?)",phase,receipt.copiedItems,receipt.copiedBytes,receipt.retainedCapacityBytes,receipt.releasedBytes,0);expect(db.query("SELECT sum(items)AS items,sum(copy)AS copy,sum(capacity)AS capacity,sum(release)AS release FROM receipt").get()).toEqual({items:2,copy:136,capacity:112,release:0});const original={collected:false};const after=applyPatch(original,[{op:"replace",path:"/collected",value:true}],true).newDocument;db.run("UPDATE receipt SET collected=?",Number(after.collected));expect(db.query("SELECT count(*)AS n FROM receipt WHERE collected=1").get()).toEqual({n:2});}finally{db.close();}const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(source.includes("pub struct GuestRelayWakeAuthority")).toBe(true);expect(await Bun.file(new URL("../🦀️.rs",import.meta.url)).exists()).toBe(true);expect(readFileSync(new URL("../🦀️.rs",import.meta.url),"utf8").includes("last_epoch")).toBe(true);console.log("[DEBUG] Ajv/SQLite/RFC6902 authored original Host2fullcurrency examples conserved sequentialissuer/collection/registration foreignUnsupported missingauthorityOriginalRetained ENDE fixed4096");});

test("original Host close returns one complete original receipt before another owner",async()=>{
 const law=await Bun.file(new URL("../🧫️fixtures/🔣️.json",import.meta.url)).json(),schema=await Bun.file(new URL("../🧬️schema/🔣️.json",import.meta.url)).json();expect(new Ajv({strict:true}).compile(schema)(law)).toBe(true);
 const db=new Database(":memory:");try{db.run("CREATE TABLE checkout(epoch INTEGER PRIMARY KEY,original INTEGER,spent INTEGER,returned INTEGER)");db.run("INSERT INTO checkout VALUES(70,1,0,0)");db.run("UPDATE checkout SET spent=1 WHERE epoch=70 AND returned=0");expect(db.query("SELECT original-spent AS remaining FROM checkout WHERE epoch=70").get()).toEqual({remaining:0});db.run("UPDATE checkout SET spent=spent+1 WHERE epoch=70 AND original-spent>0");expect(db.query("SELECT spent FROM checkout WHERE epoch=70").get()).toEqual({spent:1});db.run("UPDATE checkout SET returned=1 WHERE epoch=70");expect(db.query("SELECT count(*)AS n FROM checkout WHERE returned=0").get()).toEqual({n:0});}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8"),close=source.slice(source.indexOf("    fn pump_close("),source.indexOf("    fn outcome_payload("));expect(close.includes("fn pump_close(&self")).toBe(true);expect(close.includes("checkout_original_wake(&mut session.wake,index,session.generation)")).toBe(true);expect(close.includes("session.wake.receipt=Some(GuestRelayWakeReceipt")).toBe(true);expect(close.includes("self.collect_original_wake_receipt")).toBe(true);expect(close.includes("close_step(1,")).toBe(false);
 console.log("[DEBUG] Ajv/SQLite original close checkout cannot admit second currency or drop actual borrowed receipt; current original full-grant caller guarded");
});
