grammar ReasoningWiresSnapshot;
document: 'semio' 'reasoning.wires.dsl' 'v1' field+ EOF;
field: 'fixture-root' '=' INT | 'meta-root' '=' INT | 'content' '=' child | 'nodes' '=' '[' node* ']';
child: 'child_id' '=' text 'target' '=' target;
target: 'artifact-id' '=' text 'artifact-kind' '=' text 'standard' '=' text 'subset' '=' text;
node: '{' 'kind' '=' kind nodeField* '}';
kind: 'null' | 'boolean' | 'unsigned' | 'signed' | 'float' | 'text' | 'bytes' | 'array' | 'object';
nodeField: 'boolean' '=' boolean | 'unsigned' '=' INT | 'signed' '=' INT | 'float' '=' number | 'text' '=' text | 'bytes' '=' TEXT | 'items' '=' '[' INT* ']' | 'members' '=' '[' member* ']';
member: '{' 'name' '=' text 'value' '=' INT '}';
boolean: 'true' | 'false';
number: INT | FLOAT | IDENT | '-' IDENT;
text: TEXT | IDENT;
FLOAT: '-'? [0-9]+ '.' [0-9]+ ([eE] [+-]? [0-9]+)? | '-'? [0-9]+ [eE] [+-]? [0-9]+;
INT: '-'? [0-9]+;
IDENT: [a-zA-Z_] [a-zA-Z_0-9.-]*;
TEXT: '"' ('\\' . | ~["\\])* '"';
WS: [ \t\r\n]+ -> skip;
