//! 🧪️ Original shared actor admission and live preview conserve each physical extent and original pointer.
use semio_framework_value::{SharedUtf8,retained_clone::{RetainedCloneGrant,RetainedCloneProgress},retirement::controlled::ControlledRetirement};
use semio_framework_trace::observe_heap_allocations_on_this_thread as observe;
#[test]
fn original_sync_actor_identity_grants_preserve_pointer_preview_and_physical_custody(){
 let policy:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let grant:RetainedCloneGrant=serde_json::from_value(policy["grant"].clone()).unwrap();let maximum=policy["maximumTurns"].as_u64().unwrap()as usize;
 for row in policy["actors"].as_array().unwrap(){let text=row["text"].as_str().unwrap();let capacity=row["capacity"].as_u64().unwrap()as usize;let(mut original,heap)=observe(||{let mut original=String::new();original.try_reserve_exact(capacity).unwrap();original.push_str(text);original});let held=heap.requested_bytes-heap.released_bytes;let pointer=original.as_ptr();let original_capacity=original.capacity();let demand=SharedUtf8::admission_demand();
  for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant},RetainedCloneGrant{maximum_capacity_bytes:demand.capacity_bytes-1,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(result,heap)=observe(||SharedUtf8::admit(original,denied));let(_,returned)=result.unwrap_err();assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));assert_eq!((returned.as_ptr(),returned.capacity()),(pointer,original_capacity));original=returned;}
  let((owner,receipt),heap)=observe(||SharedUtf8::admit(original,grant).unwrap());assert!(receipt.fits(grant));assert_eq!((heap.requested_bytes,heap.released_bytes),(receipt.retained_capacity_bytes,receipt.released_bytes));let(mut born,mut released)=(heap.requested_bytes,heap.released_bytes);assert_eq!(owner.as_ptr(),pointer);assert_eq!(owner.as_str(),text);assert_eq!(serde_json::to_value(&owner).unwrap(),row["text"]);
  let demand=SharedUtf8::lease_demand();for denied in [RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant},RetainedCloneGrant{maximum_depth:0,..grant}]{let(result,heap)=observe(||owner.admit_clone(denied));assert!(result.is_err());assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));assert_eq!(owner.as_ptr(),pointer);}
  let((lease,receipt),heap)=observe(||owner.admit_clone(grant).unwrap());assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));assert_eq!(receipt,RetainedCloneProgress{copied_items:1,copied_bytes:demand.copy_bytes,..Default::default()});assert_eq!(lease.as_ptr(),pointer);
  let(event,heap)=observe(||semio_framework_os_kernel::os_store::sync::ArtifactEvent::Preview{actor:lease,key:String::new(),seq:1,payload:Vec::new()});assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));let semio_framework_os_kernel::os_store::sync::ArtifactEvent::Preview{actor:lease,..}=event else{unreachable!()};assert_eq!(lease.as_ptr(),pointer);
  for original in [lease,owner]{let mut close=ControlledRetirement::new(original).unwrap();for _ in 0..maximum{if close.terminal_is_empty(){break;}let(step,heap)=observe(||close.step(grant).unwrap());assert!(step.progress().fits(grant));assert_eq!((heap.requested_bytes,heap.released_bytes),(step.progress().retained_capacity_bytes,step.progress().released_bytes));born+=heap.requested_bytes;released+=heap.released_bytes;}assert!(close.terminal_is_empty());assert_eq!(observe(||drop(close)).1.released_bytes,policy["terminalDropBytes"].as_u64().unwrap()as usize);}
  assert_eq!(released,held+born);eprintln!("[DEBUG] original Sync actor bytes={} capacity={original_capacity} held={held} born={born} released={released}; original UTF8 pointer, four birth refusals, lease denial, live preview move, independently charged closure and terminalDrop0",text.len());
 }
}
