import { fileURLToPath as testFileUrlToPath, pathToFileURL } from "node:url";
const testSourceDirectory = testFileUrlToPath(new URL("../../🧫️fixtures/🌐️wasi-activation/", import.meta.url));
/** 🧭️ Qualifies isolated browser WASI resources against neutral traces and Preview2. */
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv from "ajv";
import ts from "typescript";
import { runExactCargoLawProcess } from "../../../../../../🦑️repo/🔨️modules/📚️library/📦️packages/🟦️typescript/🟦️.ts";

export async function testBrowserWasiActivation(repoRoot: string): Promise<void> {
  const fixture = JSON.parse(readFileSync(join(testSourceDirectory, "🔣️.json"), "utf8"));
  const schemaDocument = JSON.parse(readFileSync(resolve(testSourceDirectory, "../../🧬️schema/🔣️.json"), "utf8"));
  const ajv = new Ajv({ strict: true, allErrors: true });
  ajv.addSchema(schemaDocument);
  const validate = ajv.getSchema(`${schemaDocument.$id}#/$defs/WasiActivationV1`)!;
  assert(validate(fixture), JSON.stringify(validate.errors));
  const { createBrowserWasiActivation, createGuestLogLineSink, classifyGuestLogLine } = await import("../../🌐️wasi/🟦️.ts");
  const program = ts.createProgram([join(testSourceDirectory, "../../🌐️wasi/🟦️.ts")], { noEmit: true, strict: true, target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, lib: ["lib.es2023.d.ts", "lib.esnext.disposable.d.ts", "lib.dom.d.ts"], types: [], skipLibCheck: true });
  const diagnostics = ts.getPreEmitDiagnostics(program);
  assert.equal(diagnostics.length, 0, ts.formatDiagnosticsWithColorAndContext(diagnostics, { getCanonicalFileName: path => path, getCurrentDirectory: () => testSourceDirectory, getNewLine: () => "\n" }));
  const writes: number[][] = [];
  const port = { nowNs: () => BigInt(Math.floor(performance.now() * 1e6)), write(_stream: "stdout" | "stderr", bytes: Uint8Array) { writes.push([...bytes]); } };
  const a = createBrowserWasiActivation(port), b = createBrowserWasiActivation(port);
  const aImports = a.imports, bImports = b.imports;
  const key = (path: string) => `wasi:${path}@0.2.0`;
  const environment = aImports[key("cli/environment")];
  assert.deepEqual({ environment: environment.getEnvironment(), arguments: environment.getArguments(), cwd: environment.initialCwd() ?? null, terminal: aImports[key("cli/terminal-stdin")].getTerminalStdin() ?? null }, fixture.emptyAmbient);
  assert.notEqual(aImports[key("io/streams")].OutputStream, bImports[key("io/streams")].OutputStream);
  const stdin = aImports[key("cli/stdin")].getStdin();
  assert.throws(() => stdin.read(1n), error => (error as { tag: string }).tag === "closed");
  const output = aImports[key("cli/stdout")].getStdout();
  assert.throws(() => output.write(new Uint8Array(fixture.output)), /permit/);
  assert.equal(output.checkWrite(), BigInt(fixture.limits.writeBytes));
  output.write(new Uint8Array(fixture.output));
  assert.deepEqual(writes, [fixture.output]);
  const clock = aImports[key("clocks/monotonic-clock")], polling = aImports[key("io/poll")];
  for (const value of [-1n, 0x10000000000000000n, 1, NaN]) assert.throws(() => clock.subscribeDuration(value), /u64/);
  const ready = clock.subscribeDuration(0n);
  assert.deepEqual([...(await polling.poll([ready]))], fixture.readyIndices);
  await assert.rejects(bImports[key("io/poll")].poll([ready]), /foreign/);
  await assert.rejects(polling.poll([]), /poll list/);
  const pending = clock.subscribeDuration(0xffffffffffffffffn);
  const waiters = Array.from({ length: fixture.limits.waiters }, () => polling.poll([pending]));
  const settling = Promise.allSettled(waiters);
  await assert.rejects(polling.poll([pending]), /waiter capacity/);
  const closing = a.close();
  assert.equal(a.close(), closing);
  await closing;
  assert.equal((await settling).filter(result => result.status === "rejected").length, fixture.limits.waiters);
  assert.deepEqual(a.progress(), fixture.terminal);
  assert.throws(() => output.checkWrite(), /closed/);
  await b.close();
  const capacity = createBrowserWasiActivation(port);
  for (let count = 0; count < fixture.limits.resources; count++) capacity.imports[key("clocks/monotonic-clock")].subscribeDuration(0n);
  assert.throws(() => capacity.imports[key("cli/stdout")].getStdout(), /resource capacity/);
  await capacity.close();
  const fault = createBrowserWasiActivation({ ...port, write() { throw new Error("sink-fault"); } });
  const faultOutput = fault.imports[key("cli/stdout")].getStdout();
  while (fault.progress().resources < fixture.limits.resources) fault.imports[key("clocks/monotonic-clock")].subscribeDuration(0n);
  faultOutput.checkWrite();
  assert.throws(() => faultOutput.write(new Uint8Array([1])), error => {
    const failure = error as { tag: string; val: { toDebugString(): string } };
    assert.equal(failure.tag, "last-operation-failed");
    assert.match(failure.val.toDebugString(), /sink-fault/);
    return true;
  });
  await fault.close();
  assert.deepEqual(fault.progress(), fixture.terminal);
  let closingSink: ReturnType<typeof createBrowserWasiActivation>;
  closingSink = createBrowserWasiActivation({ ...port, write() { void closingSink.close(); throw new Error("closed-sink"); } });
  const closingOutput = closingSink.imports[key("cli/stdout")].getStdout();
  closingOutput.checkWrite();
  assert.throws(() => closingOutput.write(new Uint8Array([1])), error => (error as { tag: string }).tag === "closed");
  assert.deepEqual(closingSink.progress(), fixture.terminal);
  let closingClock: ReturnType<typeof createBrowserWasiActivation>, clockReads = 0;
  closingClock = createBrowserWasiActivation({ ...port, nowNs() { if (++clockReads === 2) void closingClock.close(); return 0n; } });
  assert.throws(() => closingClock.imports[key("clocks/monotonic-clock")].subscribeDuration(1n), /closed/);
  assert.deepEqual(closingClock.progress(), fixture.terminal);
  const quota = createBrowserWasiActivation({ ...port, write() {} });
  const limited = quota.imports[key("cli/stdout")].getStdout();
  for (let offset = 0; offset < fixture.limits.outputBytes; offset += fixture.limits.writeBytes) {
    assert.equal(limited.checkWrite(), BigInt(fixture.limits.writeBytes));
    limited.write(new Uint8Array(fixture.limits.writeBytes));
  }
  assert.throws(() => limited.checkWrite(), error => (error as { tag: string }).tag === "closed");
  await quota.close();
  const artifactBase = process.env.SEMIO_TEST_ARTIFACT_DIR;
  assert(artifactBase?.includes("🗑️generated"));
  mkdirSync(artifactBase, { recursive: true });
  const evidence = mkdtempSync(join(artifactBase, "browser-wasi-activation-"));
  const oracle = await runExactCargoLawProcess("node", ["--input-type=module", "-e", `
    import assert from "node:assert/strict";
    import { readFileSync } from "node:fs";
    import { pathToFileURL } from "node:url";
    const fixture = JSON.parse(readFileSync(process.argv[1], "utf8"));
    const io = await import(pathToFileURL(process.argv[2] + "/node_modules/@bytecodealliance/preview2-shim/dist/browser/io.js"));
    const writes = [];
    const output = io.outputStreamCreate({ write(bytes) { writes.push([...bytes]); } });
    output.write(new Uint8Array(fixture.output));
    const ready = await io.poll.poll([io.pollableCreate()]);
    assert.deepEqual(writes, [fixture.output]);
    assert.deepEqual([...ready], fixture.readyIndices);
    console.log(JSON.stringify({ writes, ready: [...ready], preview2: 1 }));
  `, join(testSourceDirectory, "🔣️.json"), repoRoot], { cwd: repoRoot, env: process.env, budgetMs: 60_000, maxOutputBytes: 64 * 1024, stdoutPath: join(evidence, "oracle.stdout.json"), stderrPath: join(evidence, "oracle.stderr"), cancelled: () => false });
  assert.equal(oracle.status, 0, oracle.stderr);
  const hostCalls = [];
  const sink = createGuestLogLineSink((line) => hostCalls.push(line));
  for (const chunk of fixture.lineBuffer.chunks) sink.write("stderr", new TextEncoder().encode(chunk));
  assert.deepEqual(hostCalls, fixture.lineBuffer.hostCalls);
  assert.equal(hostCalls.length, 2);
  assert.equal(sink.pendingBytes("stderr"), 0);
  assert.equal(classifyGuestLogLine("stderr", hostCalls[0].text), "debug");
  assert.equal(classifyGuestLogLine("stderr", hostCalls[1].text), "error");
  const preview2Writes = [];
  const io = await import(pathToFileURL(join(repoRoot, "node_modules/@bytecodealliance/preview2-shim/dist/browser/io.js")).href);
  const preview2 = io.outputStreamCreate({ write(bytes) { preview2Writes.push(new TextDecoder().decode(bytes)); } });
  for (const chunk of fixture.lineBuffer.chunks) preview2.write(new TextEncoder().encode(chunk));
  assert.equal(preview2Writes.length, fixture.lineBuffer.preview2HostCalls);

  console.log(`browser-wasi-activation: AJV=1 TypeScript=1 Preview2=1 actors=2 laws=${fixture.laws.length} resources=${fixture.limits.resources} waiters=${fixture.limits.waiters} evidence=${evidence}`);
}
