syntax = "proto3";
package semio.app.layout.layout;
message LayoutPresence {
  // @state presence
  string active_page_id = 1;
  // @state presence
  repeated string selected_ids = 2;
  // @state presence
  optional string hovered_id = 3;
  // @state presence
  LayoutDropPreviewState drop_preview = 4;
  // @state presence
  LayoutCamera camera = 5;
  // @state presence
  LayoutCamera preview_camera = 6;
}
message LayoutDropPreviewState {
  string kind = 1;
  double x = 2;
  double y = 3;
}
message LayoutCamera {
  double x = 1;
  double y = 2;
  double zoom = 3;
}
