[package]
name = "compose_query"
version = "0.1.0"
edition = "2021"


[lints]
workspace = true
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
mathematical_graph_dsl = { path = "../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph/🗣️dsl", package = "semio-framework-os-kernel-math-graph-dsl" }
mathematical_graph_manifest = { path = "../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph/🛂manifest", package = "semio-framework-os-kernel-math-graph-manifest" }
futures-util = { version = "0.3.31", default-features = false, features = ["std"] }
pin-project-lite = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.83"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
compose = { path = "../../rs" }
async-graphql = { version = "7.2.1", default-features = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
