/** 🧫️ Actual single and multiple substitution records agree with independent OpenType tables. */
import {test,expect} from "bun:test";
import Ajv from "ajv";
import opentype from "opentype.js";
import {FontFaceAdmissionJob} from "../../../🟦️.ts";
import {builtinFontLocations} from "../../../📇️catalog/🟦️.ts";
import {FontReader} from "../../../🟦️.ts";
import {FontSubstitutionJob} from "../🟦️.ts";
import schema from "../🧬️schema/🔣️.json";
import rows from "../🧫️fixtures/🔣️.json";
const limits={maxFontBytes:67108864,maxTables:128,maxGlyphs:262144,maxPoints:1048576,maxContours:65536,maxComponents:262144,maxDepth:32,maxSegments:1048576,maxWork:1e9};
test("shared GSUB single and multiple matches preserve original authority",async()=>{expect(new Ajv({strict:true}).compile(schema)(rows)).toBe(true);let count=0;for(const source of [...builtinFontLocations("Anta"),...builtinFontLocations("Noto Emoji")]){const bytes=new Uint8Array(await Bun.file(source.url).arrayBuffer()),foreign=opentype.parse(bytes.buffer),admission=new FontFaceAdmissionJob(bytes,limits);while(!admission.advance(4096).done){}const face=admission.result(),table=(foreign.tables as any).gsub;if(table){const r=new FontReader(bytes,face.gsub!.offset,face.gsub!.offset+face.gsub!.length),list=face.gsub!.offset+r.u16(face.gsub!.offset+8);for(let index=0;index<table.lookups.length;index++){const lookup=table.lookups[index],row=rows.find(row=>row.kind===lookup.lookupType);if(!row||lookup.lookupFlag!==0)continue;const offset=list+r.u16(list+2+index*2),actual={index,kind:lookup.lookupType,flags:lookup.lookupFlag,offset,subtables:lookup.subtables.length},coverage=(foreign as any).substitution.expandCoverage(lookup.subtables[0].coverage) as number[];for(const probe of row.probes){const glyph=probe==="missing"?65535:coverage[probe==="first"?0:probe==="middle"?Math.floor(coverage.length/2):coverage.length-1]!;let expected:number[]|null=null;for(const sub of lookup.subtables){const covered=(foreign as any).substitution.expandCoverage(sub.coverage).indexOf(glyph);if(covered<0)continue;expected=lookup.lookupType===1?[sub.substFormat===1?(glyph+sub.deltaGlyphId)&65535:sub.substitute[covered]]:sub.sequences[covered];break;}for(const grant of [1,7,4096]){const job=new FontSubstitutionJob(face,actual,glyph,limits.maxWork);let work=0;while(true){const p=job.advance(grant);expect(p.work-work).toBeLessThanOrEqual(grant);work=p.work;if(p.done)break;expect(()=>job.result()).toThrow();}expect(job.result()).toEqual(expected);const moved=job.intoRetirement();while(!moved.job.advance(1).done){}expect(moved.output).toEqual(expected);expect(face.bytes).toBe(bytes);count++;}for(const stop of [0,1,2,7,20,40,100]){const job=new FontSubstitutionJob(face,actual,glyph,limits.maxWork);job.advance(Math.max(1,stop));job.cancel();expect(()=>job.result()).toThrow();const moved=job.intoRetirement();expect(moved.output).toBeNull();while(!moved.job.advance(1).done){}expect(face.bytes).toBe(bytes);}}}}const moved=admission.intoRetirement();while(!moved.job.advance(1).done){}}expect(count).toBeGreaterThan(0);console.log(`[DEBUG] Original GSUB single/multiple matches=${count}: OpenType tables, grants1/7/4096 and seven interruptions`);},120000);
