#!/usr/bin/env bun
//#region 🧪️ResidentOracle
import { strict as assert } from "node:assert";
import { runInThisContext } from "node:vm";
import Ajv from "ajv";
import { produce } from "immer";
import ts from "typescript";
import { BundleScript, ScriptRouter, runBundleScriptMain } from "@semio-tech/repo-lib";
import { OwnedResidentLedger } from "./🟦️.ts";
import * as resident from "./🟦️.ts";
import fixture from "./🧫️fixture/🔣️.json";
import fixtureSchema from "./📐️schema/🔣️.json";
import capacitySchema from "./🧬️schema.json";
import admissionContract from "./📨️admission/🤝️contract.json";
import admissionContractSchema from "./📨️admission/🧬️schema.json";
import admissionFixture from "./📨️admission/🧫️fixture/🔣️.json";
import admissionFixtureSchema from "./📨️admission/📐️schema/🔣️.json";

class TestScript extends BundleScript {
  async run(): Promise<void> {
    const ajv = new Ajv({ strict: true, allErrors: true }); ajv.addSchema(capacitySchema);
    assert(ajv.compile(fixtureSchema)(fixture), JSON.stringify(ajv.errors));
    assert(ajv.compile(admissionContractSchema)(admissionContract), JSON.stringify(ajv.errors)); assert(ajv.compile(admissionFixtureSchema)(admissionFixture), JSON.stringify(ajv.errors));
    let nativeModel = { consumer: "cell", shell: "source", consumerDrops: 0, shellDrops: 0, aliases: 2, pages: 2, terminal: false };
    const nativeTrace = admissionFixture.nativeOwnership.releaseTrace.map(({ phase }) => {
      nativeModel = produce(nativeModel, draft => {
        if (phase === "shell-handed-to-parent") draft.shell = "parent";
        if (phase === "consumer-handed-to-parent") draft.consumer = "parent";
        if (phase === "parent-typed-retirement") { assert.equal(draft.consumer, "parent"); assert.equal(draft.shell, "parent"); draft.consumer = "empty"; draft.shell = "empty"; draft.consumerDrops++; draft.shellDrops++; }
        if (phase === "aliases-pages-root-released") { assert.equal(draft.consumer, "empty"); assert.equal(draft.shell, "empty"); draft.aliases = 0; draft.pages = 0; draft.terminal = true; }
      });
      return { phase, consumerDrops: nativeModel.consumerDrops, shellDrops: nativeModel.shellDrops, terminal: nativeModel.terminal };
    });
    assert.deepEqual(nativeTrace, admissionFixture.nativeOwnership.releaseTrace);
    const sealedConsumer = produce({ slot: null as { value: number } | null }, draft => { draft.slot = null; });
    assert.equal(sealedConsumer.slot === null, admissionFixture.nativeOwnership.foreignRepopulation.afterEmptyObservation);
    assert.equal(Reflect.set(sealedConsumer, "slot", { value: 73 }), admissionFixture.nativeOwnership.foreignRepopulation.accepted);
    const phaseAccess = admissionFixture.nativeOwnership.phaseAccess.map(({ phase }) => {
      const state = produce({ forward: { value: 73 } as { value: number } | null, recovery: null as { value: number } | null }, draft => {
        if (phase === "consumer-closing" || phase === "root-closing") { draft.recovery = draft.forward; draft.forward = null; }
      });
      assert.equal(Reflect.set(state, "forward", { value: 91 }), false);
      return { phase, forward: state.forward !== null, recovery: state.recovery !== null };
    });
    assert.deepEqual(phaseAccess, admissionFixture.nativeOwnership.phaseAccess);
    const cancellationModels = admissionFixture.nativeOwnership.exactAllocation.cancelFrontiers.map(frontier => {
      let state = { reserved: true, allocated: false, initialized: false, published: false, allocations: 0, deallocations: 0 };
      for (const phase of ["reserved", "allocated", "initialized", "published"]) {
        state = produce(state, draft => { if (phase === "allocated") { draft.allocated = true; draft.allocations++; } if (phase === "initialized") draft.initialized = true; if (phase === "published") draft.published = true; });
        if (phase === frontier) break;
      }
      state = produce(state, draft => { if (draft.allocated) { draft.allocated = false; draft.deallocations++; } draft.initialized = false; draft.published = false; draft.reserved = false; });
      assert.equal(state.reserved || state.allocated || state.initialized || state.published, false);
      return state;
    });
    assert.deepEqual(cancellationModels.map(state => state.allocations), admissionFixture.nativeOwnership.exactAllocation.cancelAllocations);
    assert.deepEqual(cancellationModels.map(state => state.deallocations), admissionFixture.nativeOwnership.exactAllocation.cancelDeallocations);
    let preparationState = { reserved: false, allocations: 0 }; let preparationRefusals = 0;
    for (const frontier of admissionFixture.nativeOwnership.preparationGrantFrontiers) {
      assert.deepEqual(preparationState, frontier.before);
      for (const refusal of admissionFixture.nativeOwnership.preparationGrantCases.slice(0, -1)) {
        const unchanged = produce(preparationState, () => {});
        assert.equal(unchanged, preparationState, refusal); assert.deepEqual(unchanged, frontier.afterRefusal); preparationRefusals++;
      }
      preparationState = produce(preparationState, draft => {
        if (frontier.phase === "reserve") { assert.equal(draft.reserved, false); draft.reserved = true; }
        else { assert.equal(frontier.phase, "allocate"); assert(draft.reserved); assert.equal(draft.allocations, 0); draft.allocations++; }
      });
      assert.deepEqual(preparationState, frontier.afterExact);
    }
    assert.throws(() => produce({ reserved: false, allocations: 0 }, draft => { assert(draft.reserved); draft.allocations++; }));
    console.log(`[DEBUG] Native preparation reference phases=${admissionFixture.nativeOwnership.preparationGrantFrontiers.length} refusalStates=${preparationRefusals} allocationBeforeReservationRejected=true nativeGrantArithmeticExecuted=false oracle=Immer`);
    assert.equal(admissionFixture.nativeOwnership.unknownFaultFinalDisposal, false);
    console.log(`[DEBUG] Native ownership neutralTrace=${nativeTrace.length} phaseAccess=${phaseAccess.length} cancellationFrontiers=${cancellationModels.length} sealedReplacementRefused=true oracle=Ajv+Immer actualNativeExecution=false unknownFaultFinalDisposal=false`);
    const bootstrap = new OwnedResidentLedger(fixture.capacity); const bootstrapConsumer = Object.freeze({ name: "original" }); const foreignConsumer = Object.freeze({ name: "foreign" }); const bootstrapGrant = admissionFixture.grants[2]!;
    assert.equal(typeof Reflect.get(bootstrap, "prepareAdmission"), "function", "Original admission cells must survive a wrapper throwing after preparation");
    for (const short of admissionFixture.grants.slice(0, 2)) { assert.equal(bootstrap.prepareAdmission(bootstrapConsumer, "data", short).kind, "blocked"); assert.deepEqual(bootstrap.usage.data, { bytes: 0, slots: 0, owners: 0 }); }
    const prepare = resident.OwnedResidentLedger.prototype.prepareAdmission; const originalFault = Object.freeze({ retained: Buffer.alloc(1024, admissionFixture.unrelatedByte) }); let caught: unknown;
    resident.OwnedResidentLedger.prototype.prepareAdmission = function (consumer, partition, grant) { const result = prepare.call(this, consumer, partition, grant); assert.equal(result.kind, "pending"); throw originalFault; };
    try { bootstrap.prepareAdmission(bootstrapConsumer, "data", bootstrapGrant); assert.fail("wrapper must throw"); } catch (error) { caught = error; } finally { resident.OwnedResidentLedger.prototype.prepareAdmission = prepare; }
    assert.equal(caught, originalFault); const heldAdmission = bootstrap.preparedAdmission(bootstrapConsumer); assert(heldAdmission); assert.equal(bootstrap.preparedAdmission(bootstrapConsumer), heldAdmission); assert.equal(bootstrap.preparedAdmission(foreignConsumer), null); assert.equal(bootstrap.prepareAdmission(foreignConsumer, "data", bootstrapGrant).kind, "blocked");
    const cellUsage = produce({ bytes: 0, slots: 0, owners: 0 }, draft => { for (const axis of ["bytes", "slots", "owners"] as const) draft[axis] += admissionContract.charge[axis]; }); assert.deepEqual(bootstrap.usage.data, cellUsage);
    assert.equal(heldAdmission.retainFailure(caught, { maxItems: 0, maxBytes: 4096 }).kind, "blocked"); assert.equal(heldAdmission.hasFailure, false); assert.equal(heldAdmission.retainFailure(caught, bootstrapGrant).kind, "pending"); assert.equal(heldAdmission.failure, originalFault); assert.equal(heldAdmission.retainFailure(originalFault, bootstrapGrant).kind, "ready"); assert.equal(heldAdmission.retainFailure(foreignConsumer, bootstrapGrant).kind, "rejected");
    assert.equal(bootstrap.claimAdmission(bootstrapConsumer, heldAdmission, bootstrapGrant).kind, "rejected"); heldAdmission.beginClose(); assert.equal(heldAdmission.closeStep(bootstrapGrant).kind, "pending"); assert.equal(bootstrap.preparedAdmission(bootstrapConsumer), null); assert.equal(heldAdmission.closeStep(bootstrapGrant).kind, "rejected"); assert.deepEqual(bootstrap.usage.data, cellUsage); assert.equal(heldAdmission.retirement, null); assert.equal(heldAdmission.failure, originalFault);
    const nextConsumer = Object.freeze({ name: "next" }); assert.equal(bootstrap.prepareAdmission(nextConsumer, "data", bootstrapGrant).kind, "pending"); const nextCell = bootstrap.preparedAdmission(nextConsumer); assert(nextCell); const claim = resident.OwnedResidentLedger.prototype.claimAdmission;
    resident.OwnedResidentLedger.prototype.claimAdmission = function (consumer, cell, grant) { const result = claim.call(this, consumer, cell, grant); assert.equal(result.kind, "ready"); throw originalFault; };
    try { bootstrap.claimAdmission(nextConsumer, nextCell, bootstrapGrant); assert.fail("claim wrapper must throw"); } catch (error) { assert.equal(error, originalFault); } finally { resident.OwnedResidentLedger.prototype.claimAdmission = claim; }
    assert(nextCell.claimed); assert.equal(bootstrap.preparedAdmission(nextConsumer), null); assert.equal(bootstrap.claimAdmission(nextConsumer, nextCell, bootstrapGrant).kind, "rejected"); assert.equal(nextCell.retainFailure(originalFault, bootstrapGrant).kind, "pending"); nextCell.beginClose(); assert.equal(nextCell.closeStep(bootstrapGrant).kind, "rejected");
    for (const kind of admissionFixture.faultKinds) {
      const pool = new OwnedResidentLedger(fixture.capacity); const consumer = Object.freeze({}); const fault = kind === "null" ? null : kind === "undefined" ? undefined : kind === "proxy" ? new Proxy({}, { get() { throw new Error("fault root must remain opaque"); } }) : Object.freeze({ bytes: Buffer.alloc(256, 73) });
      const freeze = Object.freeze; let original: unknown; Object.freeze = value => { if (value instanceof resident.OwnedResidentAdmission) { original = value; throw fault; } return freeze(value); };
      try { assert.equal(pool.prepareAdmission(consumer, "data", bootstrapGrant).kind, "rejected"); } finally { Object.freeze = freeze; }
      const cell = pool.preparedAdmission(consumer); assert(cell); assert.equal(cell, original); assert(cell.hasFailure); assert.equal(cell.failure, fault); assert.equal(pool.claimAdmission(consumer, cell, bootstrapGrant).kind, "rejected"); cell.beginClose(); cell.closeStep(bootstrapGrant); assert.equal(cell.closeStep(bootstrapGrant).kind, "rejected"); assert.deepEqual(pool.usage.data, cellUsage); assert.equal(cell.retirement, null);
    }
    const unusedCellPool = new OwnedResidentLedger(fixture.capacity); const unusedConsumer = Object.freeze({}); unusedCellPool.prepareAdmission(unusedConsumer, "data", bootstrapGrant); const unusedCell = unusedCellPool.preparedAdmission(unusedConsumer); assert(unusedCell); unusedCellPool.claimAdmission(unusedConsumer, unusedCell, bootstrapGrant); unusedCell.beginClose(); assert.equal(unusedCell.closeStep({ maxItems: 1, maxBytes: 295 }).kind, "blocked"); assert.equal(unusedCell.closeStep(bootstrapGrant).kind, "complete"); assert(resident.OwnedResidentRetirement.matches(unusedCell.retirement, unusedCell)); assert.deepEqual(unusedCellPool.usage.data, { bytes: 0, slots: 0, owners: 0 });
    const resourceCellPool = new OwnedResidentLedger(fixture.capacity); const resourceConsumer = Object.freeze({}); resourceCellPool.prepareAdmission(resourceConsumer, "data", bootstrapGrant); const resourceCell = resourceCellPool.preparedAdmission(resourceConsumer); assert(resourceCell); resourceCellPool.claimAdmission(resourceConsumer, resourceCell, bootstrapGrant);
    const reservedRecord = resourceCellPool.reserveRecord("data", fixture.domainRecord.envelope, resourceCell, bootstrapGrant); assert.equal(reservedRecord.step.kind, "ready"); assert.equal(resourceCell.result?.root, reservedRecord.record, "Canonical admission must publish the original record into the held cell before returning");
    const grant = { maxItems: 1, maxBytes: 4096 }; const cellCharge = admissionContract.charge;
    const charges = { owner: { bytes: 200, slots: 2, owners: 2 }, page: { bytes: 520, slots: 3, owners: 2 }, reader: { bytes: 136, slots: 2, owners: 2 }, record: { bytes: fixture.domainRecord.envelope.bytes + 264, slots: fixture.domainRecord.envelope.slots + 3, owners: fixture.domainRecord.envelope.owners + 3 } };
    const sum = (...values: resident.ResidentResources[]): resident.ResidentResources => values.reduce((total, value) => produce(total, draft => { for (const axis of ["bytes", "slots", "owners"] as const) draft[axis] += value[axis]; }), { bytes: 0, slots: 0, owners: 0 });
    const claimCell = (ledger: OwnedResidentLedger, partition: resident.ResidentPartition = "data"): resident.OwnedResidentAdmission => { const consumer = Object.freeze({}); assert.equal(ledger.prepareAdmission(consumer, partition, grant).kind, "pending"); const cell = ledger.preparedAdmission(consumer); assert(cell); assert.equal(ledger.claimAdmission(consumer, cell, grant).kind, "ready"); return cell; };
    const createOwner = (ledger: OwnedResidentLedger, partition: resident.ResidentPartition = "data") => { const cell = claimCell(ledger, partition); const result = ledger.beginOwner(partition, cell, grant); assert.equal(result.step.kind, "ready"); assert(result.owner); return { cell, root: result.owner }; };
    const createPage = (ledger: OwnedResidentLedger, owner: resident.OwnedResidentOwner, length: number, partition: resident.ResidentPartition = "data") => { const cell = claimCell(ledger, partition); const result = owner.reservePage(length, cell, grant); assert.equal(result.step.kind, "ready"); assert(result.page); return { cell, root: result.page }; };
    const closeCell = (cell: resident.OwnedResidentAdmission, maximumBytes = 0): void => { cell.beginClose(); const bound = 16 + Math.ceil(maximumBytes / grant.maxBytes); for (let turn = 0; turn < bound && !cell.terminalIsEmpty(); turn++) { const current = cell.closeStep(grant); assert(current.items <= 1 && current.bytes <= grant.maxBytes); if (current.kind === "rejected") { assert(cell.hasFailure); assert.equal(cell.result?.root ?? null, null); break; } } assert(cell.hasFailure ? cell.retirement === null : cell.terminalIsEmpty()); };
    const closeLedger = (ledger: OwnedResidentLedger): void => { const used = ledger.usage; const bound = 16 * (used.data.owners + used.control.owners + 1) + Math.ceil((used.data.bytes + used.control.bytes) / grant.maxBytes); ledger.beginClose(); for (let turn = 0; turn < bound && !ledger.terminalIsEmpty(); turn++) { const current = ledger.closeStep(grant); assert.notEqual(current.kind, "rejected"); assert(current.items <= 1 && current.bytes <= grant.maxBytes); } assert(ledger.terminalIsEmpty()); assert.deepEqual(ledger.usage, { data: { bytes: 0, slots: 0, owners: 0 }, control: { bytes: 0, slots: 0, owners: 0 } }); };
    for (const kind of admissionFixture.resourceKinds) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, 0); source.root.allocate(grant); source.root.seal(grant); const cell = claimCell(pool); const fault = Object.freeze({ unfinishedFacade: kind }); const freeze = Object.freeze;
      Object.freeze = value => { const match = kind === "owner" ? value instanceof resident.OwnedResidentOwner : kind === "record" ? value instanceof resident.OwnedResidentRecord : kind === "page" ? value instanceof resident.OwnedResidentPage : kind === "reader" ? value instanceof resident.OwnedResidentReader : value instanceof resident.OwnedResidentExternalBacking; if (match) throw fault; return freeze(value); };
      try { const result = kind === "owner" ? pool.beginOwner("data", cell, grant) : kind === "record" ? pool.reserveRecord("data", fixture.domainRecord.envelope, cell, grant) : kind === "page" ? owner.root.reservePage(0, cell, grant) : kind === "reader" ? owner.root.beginRead(source.root, cell, grant) : owner.root.reserveExternalBacking(0, cell, grant); assert.equal(result.step.kind, "rejected"); } finally { Object.freeze = freeze; }
      const original = cell.result!.root; assert(original); assert(!Object.isFrozen(original)); let shadowCalls = 0; Object.defineProperties(original, { beginClose: { value() { shadowCalls++; } }, closeStep: { value() { shadowCalls++; return { kind: "complete", phase: "forged-public-close", items: 1, bytes: 4096 }; } } });
      cell.beginClose(); cell.closeStep(grant); assert.equal(shadowCalls, 0, "Parent retirement must use its exact private state, not a failed facade's shadowed methods"); closeCell(cell); closeCell(source.cell); closeCell(owner.cell); assert.equal(cell.failure, fault); assert.deepEqual(pool.usage.data, cellCharge);
    }
    const quarantinePool = new OwnedResidentLedger(fixture.capacity); const quarantineOwner = createOwner(quarantinePool); const quarantineFault = Object.freeze({ fault: "own-cell-not-parent" });
    const blockedPage = createPage(quarantinePool, quarantineOwner.root, 1); blockedPage.cell.retainFailure(quarantineFault, grant); assert.equal(blockedPage.root.allocate(grant).kind, "rejected", "Own page admission quarantine must reject allocation"); closeCell(blockedPage.cell);
    const writingPage = createPage(quarantinePool, quarantineOwner.root, 2); writingPage.root.allocate(grant); writingPage.root.writeByte(73, grant); writingPage.cell.retainFailure(quarantineFault, grant); assert.equal(writingPage.root.writeByte(19, grant).kind, "rejected"); assert.equal(writingPage.root.seal(grant).kind, "rejected"); closeCell(writingPage.cell);
    const readablePage = createPage(quarantinePool, quarantineOwner.root, 1); readablePage.root.allocate(grant); readablePage.root.writeByte(73, grant); readablePage.root.seal(grant); const readerFaultCell = claimCell(quarantinePool); const faultedReader = quarantineOwner.root.beginRead(readablePage.root, readerFaultCell, grant).reader; assert(faultedReader); readerFaultCell.retainFailure(quarantineFault, grant); assert.throws(() => faultedReader.byteAt(0)); assert.throws(() => faultedReader.length); closeCell(readerFaultCell);
    readablePage.cell.retainFailure(quarantineFault, grant); const deniedReadCell = claimCell(quarantinePool); assert.equal(quarantineOwner.root.beginRead(readablePage.root, deniedReadCell, grant).reader, null); closeCell(deniedReadCell); closeCell(readablePage.cell);
    const fenceCell = claimCell(quarantinePool); const fenceSlot = quarantineOwner.root.reserveExternalBacking(4, fenceCell, grant).slot; assert(fenceSlot); fenceCell.retainFailure(quarantineFault, grant); assert.equal(fenceSlot.beginReceive(grant).kind, "rejected"); closeCell(fenceCell);
    const lateCell = claimCell(quarantinePool); const lateSlot = quarantineOwner.root.reserveExternalBacking(4, lateCell, grant).slot; assert(lateSlot); lateSlot.beginReceive(grant); lateCell.retainFailure(quarantineFault, grant); const lateBacking = new ArrayBuffer(4); new Uint8Array(lateBacking).set(Buffer.from([73, 19, 2, 3])); const lateResult = lateSlot.adoptTransferred(lateBacking, grant); assert.equal(lateResult.step.kind, "pending"); assert.equal(lateResult.receipt, null); assert.equal(lateBacking.byteLength, 0); assert.throws(() => lateSlot.byteAt(0)); assert.throws(() => lateSlot.length); closeCell(lateCell, 4);
    const custodyFaultCell = claimCell(quarantinePool); const custodyFaultSlot = quarantineOwner.root.reserveExternalBacking(1, custodyFaultCell, grant).slot; assert(custodyFaultSlot); custodyFaultSlot.beginReceive(grant); const originalCustody = custodyFaultSlot.adoptTransferred(new ArrayBuffer(1), grant).receipt; assert(resident.OwnedResidentBackingCustody.matches(originalCustody, custodyFaultSlot)); custodyFaultCell.retainFailure(quarantineFault, grant); assert(!resident.OwnedResidentBackingCustody.matches(originalCustody, custodyFaultSlot)); closeCell(custodyFaultCell, 1); closeCell(quarantineOwner.cell);
    for (const vector of fixture.invalidCapacities) assert.throws(() => new OwnedResidentLedger(vector.value), vector.name);
    const ledger = new OwnedResidentLedger(fixture.capacity); assert.deepEqual(ledger.capacity, fixture.capacity); const writer = createOwner(ledger); const consumer = createOwner(ledger); const page = createPage(ledger, writer.root, 256);
    assert.equal(page.root.allocate({ maxItems: 0, maxBytes: 4096 }).kind, "blocked"); page.root.allocate(grant); const bytes = Buffer.alloc(256); for (let i = 0; i < bytes.length; i++) { bytes[i] = (fixture.pattern.multiplier * i + fixture.pattern.addend) & 255; assert.equal(page.root.writeByte(bytes[i]!, grant).bytes, 1); } assert.equal(page.root.seal(grant).kind, "ready");
    const readerCell = claimCell(ledger); const reader = consumer.root.beginRead(page.root, readerCell, grant).reader; assert(reader); assert.deepEqual(ledger.usage.data, sum(charges.owner, charges.owner, charges.page, charges.reader, cellCharge, cellCharge, cellCharge, cellCharge));
    writer.root.beginClose(); assert.equal(writer.root.closeStep(grant).kind, "blocked"); for (let i = 0; i < bytes.length; i++) assert.equal(reader.byteAt(i), bytes[i]); closeCell(readerCell); assert.throws(() => reader.byteAt(0)); closeLedger(ledger); assert(resident.OwnedResidentRetirement.matches(writer.root.retirement, writer.root)); assert(!resident.OwnedResidentRetirement.matches(writer.root.retirement, consumer.root)); assert(!resident.OwnedResidentRetirement.matches({ root: writer.root }, writer.root));
    const recordPool = new OwnedResidentLedger(fixture.capacity); const recordCell = claimCell(recordPool); const record = recordPool.reserveRecord("data", fixture.domainRecord.envelope, recordCell, grant).record; assert(record); const shell = Object.create(null); const foreign = Object.create(null); let propertiesRead = 0; Object.defineProperty(shell, "terminal", { get() { propertiesRead++; throw new Error("No structural terminal authority"); } }); assert.deepEqual(recordPool.usage.data, sum(charges.record, cellCharge));
    assert.throws(() => { assert.equal(record.install(shell, grant).kind, "ready"); throw new Error("after-install"); }, /after-install/); assert(record.matchesShell(shell)); assert.equal(record.install(foreign, grant).kind, "rejected"); record.beginClose(); assert.equal(record.closeStep(grant).kind, "blocked"); assert.equal(record.detach(foreign, grant).kind, "rejected");
    assert.throws(() => { assert.equal(record.detach(shell, grant).kind, "pending"); throw new Error("after-detach"); }, /after-detach/); assert(resident.OwnedResidentRecordDetachment.matches(record.detachment, record, shell)); assert(!resident.OwnedResidentRecordDetachment.matches(record.detachment, record, foreign)); assert.equal(record.detach(shell, grant).kind, "rejected"); assert.equal(record.closeStep({ maxItems: 0, maxBytes: 4096 }).kind, "blocked"); assert.equal(record.closeStep({ maxItems: 1, maxBytes: 263 }).kind, "blocked");
    assert.equal(record.closeStep(grant).kind, "complete"); assert.deepEqual(recordPool.usage.data, sum(cellCharge, { bytes: 8, slots: 0, owners: 0 })); assert.equal(recordCell.result!.record, record); assert.equal(recordCell.result!.owner, null); assert(!record.terminalIsEmpty(), "Resource still retains its original admission alias until the separate detach turn"); recordCell.beginClose(); assert.equal(recordCell.closeStep({ maxItems: 1, maxBytes: 63 }).kind, "blocked"); assert.equal(recordCell.result!.record, record); assert.equal(recordCell.closeStep(grant).phase, "resident-admission-result-detach"); assert.equal(recordCell.result!.record, null); assert(record.terminalIsEmpty()); assert.deepEqual(recordPool.usage.data, cellCharge); assert.equal(recordCell.closeStep(grant).kind, "complete"); assert.equal(propertiesRead, 0); closeLedger(recordPool);
    for (const row of fixture.liveRecord) {
      const pool = new OwnedResidentLedger(fixture.capacity); const cell = claimCell(pool); const record = pool.reserveRecord("data", fixture.domainRecord.envelope, cell, grant).record; assert(record); const shell = Object.create(null); const foreign = Object.create(null); assert.equal(record.install(shell, grant).kind, "ready"); const before = pool.usage; const model = produce({ installed: true, closing: false, detached: false, foreign: false }, draft => { if (row.transition === "foreign") draft.foreign = true; if (["record-close", "cell-close", "ledger-close", "own-fault", "detach"].includes(row.transition)) draft.closing = true; if (row.transition === "detach") draft.detached = true; });
      if (row.transition === "record-close" || row.transition === "detach") record.beginClose(); if (row.transition === "cell-close") cell.beginClose(); if (row.transition === "ledger-close") pool.beginClose(); if (row.transition === "own-fault") assert.equal(cell.retainFailure(shell, grant).kind, "pending"); if (row.transition === "detach") assert.equal(record.detach(shell, grant).kind, "pending");
      assert.equal(record.matchesLiveShell(row.transition === "foreign" ? foreign : shell), row.live, row.transition); assert.equal(record.matchesShell(row.transition === "foreign" ? foreign : shell), row.identity, row.transition); assert.equal(!model.foreign && model.installed && !model.closing && !model.detached, row.live); assert.deepEqual(pool.usage, before);
    }
    console.log(`[DEBUG] Resident liveRecord=${fixture.liveRecord.length} identityOnlyDistinct=true oracle=Ajv+Immer`);
    const overflowPool = new OwnedResidentLedger({ bytes: Number.MAX_SAFE_INTEGER, slots: 128, owners: 128, control: { bytes: 0, slots: 0, owners: 0 } }); for (const axis of ["bytes", "slots", "owners"] as const) { const cell = claimCell(overflowPool); const before = overflowPool.usage; assert.equal(overflowPool.reserveRecord("data", { bytes: 0, slots: 0, owners: 0, [axis]: Number.MAX_SAFE_INTEGER }, cell, grant).record, null); assert.deepEqual(overflowPool.usage, before); closeCell(cell); }
    const hugeOwner = createOwner(overflowPool); const hugeCell = claimCell(overflowPool); const beforeHuge = overflowPool.usage; assert.equal(hugeOwner.root.reserveExternalBacking(Number.MAX_SAFE_INTEGER, hugeCell, grant).slot, null); assert.equal(hugeOwner.root.reserveExternalBacking(Number.MAX_SAFE_INTEGER - 328, hugeCell, grant).slot, null); assert.deepEqual(overflowPool.usage, beforeHuge); closeLedger(overflowPool);
    for (const length of fixture.pageLengths) { const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, length); source.root.allocate(grant); const expected = Buffer.alloc(length, 23); for (const byte of expected) source.root.writeByte(byte, grant); assert.equal(source.root.seal(grant).kind, "ready"); const cell = claimCell(pool); const view = owner.root.beginRead(source.root, cell, grant).reader; assert(view); assert.equal(view.length, length); for (let i = 0; i < length; i++) assert.equal(view.byteAt(i), expected[i]); assert.throws(() => view.byteAt(length)); closeLedger(pool); }
    for (const kind of fixture.admissionFailures) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const live = createPage(pool, owner.root, 1); live.root.allocate(grant); live.root.writeByte(73, grant); live.root.seal(grant); const baseline = pool.usage.data; const cell = claimCell(pool); const fault = Object.freeze({ exact: Buffer.alloc(512, 73) }); let original: unknown; const freeze = Object.freeze;
      Object.freeze = value => { const match = kind === "owner" ? value instanceof resident.OwnedResidentOwner : kind === "record" ? value instanceof resident.OwnedResidentRecord : kind === "page" ? value instanceof resident.OwnedResidentPage : kind === "reader" ? value instanceof resident.OwnedResidentReader : value instanceof resident.OwnedResidentExternalBacking; if (match) { original = value; throw fault; } return freeze(value); };
      try { const result = kind === "owner" ? pool.beginOwner("data", cell, grant) : kind === "record" ? pool.reserveRecord("data", fixture.domainRecord.envelope, cell, grant) : kind === "page" ? owner.root.reservePage(1, cell, grant) : kind === "reader" ? owner.root.beginRead(live.root, cell, grant) : owner.root.reserveExternalBacking(32, cell, grant); assert.equal(result.step.kind, "rejected"); } finally { Object.freeze = freeze; }
      assert.equal(cell.result!.root, original); assert.equal(cell.failure, fault); const retained = pool.usage; assert.equal(cell.closeStep({ maxItems: 0, maxBytes: 4096 }).kind, "blocked"); assert.deepEqual(pool.usage, retained); closeCell(cell); assert.deepEqual(pool.usage.data, sum(baseline, cellCharge)); assert.equal(cell.failure, fault); const readCell = claimCell(pool); const read = owner.root.beginRead(live.root, readCell, grant).reader; assert(read); assert.equal(read.byteAt(0), 73); closeCell(readCell); closeCell(live.cell); closeCell(owner.cell); assert.deepEqual(pool.usage.data, cellCharge); assert.equal(cell.retirement, null);
    }
    for (const kind of admissionFixture.resourceKinds) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, 1); source.root.allocate(grant); source.root.writeByte(73, grant); source.root.seal(grant); const cell = claimCell(pool); const fault = Object.freeze({ boundary: "after-canonical-return" }); let original: object | null = null;
      try { const result = kind === "owner" ? pool.beginOwner("data", cell, grant) : kind === "record" ? pool.reserveRecord("data", fixture.domainRecord.envelope, cell, grant) : kind === "page" ? owner.root.reservePage(1, cell, grant) : kind === "reader" ? owner.root.beginRead(source.root, cell, grant) : owner.root.reserveExternalBacking(32, cell, grant); assert.equal(result.step.kind, "ready"); original = "owner" in result ? result.owner : "record" in result ? result.record : "page" in result ? result.page : "reader" in result ? result.reader : result.slot; throw fault; } catch (error) { assert.equal(error, fault); assert.equal(cell.retainFailure(error, grant).kind, "pending"); }
      assert(original); assert.equal(cell.result!.root, original); assert.equal(cell.result!.kind, kind); const occupied = pool.usage; assert.equal(pool.beginOwner("data", cell, grant).step.kind, "rejected"); assert.deepEqual(pool.usage, occupied); closeCell(cell); closeCell(source.cell); closeCell(owner.cell); assert.deepEqual(pool.usage.data, cellCharge); assert.equal(cell.failure, fault);
    }
    for (const kind of ["record", "witness", "observation", "owner", "page", "reader", "custody", "external"] as const) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, 0); source.root.allocate(grant); source.root.seal(grant); const cell = claimCell(pool); const fault = Object.freeze({ finalizer: kind }); const freeze = Object.freeze; let captured: unknown;
      Object.freeze = value => { const match = kind === "witness" ? value instanceof resident.OwnedResidentRetirement : kind === "observation" ? value instanceof resident.OwnedResidentRecordDetachment : kind === "custody" ? value instanceof resident.OwnedResidentBackingCustody : kind === "record" ? value instanceof resident.OwnedResidentRecord : kind === "owner" ? value instanceof resident.OwnedResidentOwner : kind === "page" ? value instanceof resident.OwnedResidentPage : kind === "reader" ? value instanceof resident.OwnedResidentReader : value instanceof resident.OwnedResidentExternalBacking; if (match) { captured = value; throw fault; } return freeze(value); };
      try { const result = kind === "record" || kind === "witness" || kind === "observation" ? pool.reserveRecord("data", fixture.domainRecord.envelope, cell, grant) : kind === "owner" ? pool.beginOwner("data", cell, grant) : kind === "page" ? owner.root.reservePage(0, cell, grant) : kind === "reader" ? owner.root.beginRead(source.root, cell, grant) : owner.root.reserveExternalBacking(32, cell, grant); assert.equal(result.step.kind, "rejected"); } finally { Object.freeze = freeze; }
      assert(captured); assert.equal(cell.failure, fault); closeCell(cell); closeCell(source.cell); closeCell(owner.cell); assert.deepEqual(pool.usage.data, cellCharge);
    }
    const shared = new OwnedResidentLedger(fixture.capacity); const rawOwner = createOwner(shared); const uiOwner = createOwner(shared); const rawCell = claimCell(shared); const raw = rawOwner.root.reserveExternalBacking(4161, rawCell, grant).slot; assert(raw); const destination = createPage(shared, uiOwner.root, 256); const scratch = createPage(shared, uiOwner.root, 256); assert.deepEqual(shared.usage.data, sum(charges.owner, charges.owner, { bytes: 4161 + 328, slots: 4, owners: 3 }, charges.page, charges.page, cellCharge, cellCharge, cellCharge, cellCharge, cellCharge));
    raw.beginReceive(grant); rawOwner.root.beginClose(); const postedUsage = shared.usage; assert.equal(rawOwner.root.closeStep(grant).kind, "blocked"); assert.deepEqual(shared.usage, postedUsage); const backing = new ArrayBuffer(4161); const alias = new Uint8Array(backing); for (let i = 0; i < alias.length; i++) alias[i] = i & 255; const late = raw.adoptTransferred(backing, grant); assert.equal(late.step.kind, "pending"); assert.equal(late.receipt, null); assert.equal(backing.byteLength, 0); assert.equal(alias.byteLength, 0); closeLedger(shared);
    const transferPool = new OwnedResidentLedger(fixture.capacity); const transferOwner = createOwner(transferPool); const transferCell = claimCell(transferPool); const transfer = transferOwner.root.reserveExternalBacking(32, transferCell, grant).slot; assert(transfer); transfer.beginReceive(grant); const moved = new ArrayBuffer(32); const fault = Object.freeze({ after: "actual-transfer" }); const NativeBytes = globalThis.Uint8Array;
    globalThis.Uint8Array = new Proxy(NativeBytes, { construct(target, args, newTarget) { if (args[0] instanceof ArrayBuffer) throw fault; return Reflect.construct(target, args, newTarget); } }); try { assert.equal(transfer.adoptTransferred(moved, grant).step.kind, "rejected"); } finally { globalThis.Uint8Array = NativeBytes; } assert.equal(moved.byteLength, 0); assert.equal(transferCell.failure, fault); closeCell(transferCell, 32); closeCell(transferOwner.cell); assert.deepEqual(transferPool.usage.data, cellCharge);
    for (const vector of fixture.controlCases) {
      const pool = new OwnedResidentLedger({ ...fixture.capacity, control: vector.control }); const owner = createOwner(pool); const dataCell = claimCell(pool); const current = pool.usage.data; const maximum = fixture.capacity.bytes - vector.control.bytes - current.bytes - 328; assert(owner.root.reserveExternalBacking(maximum, dataCell, grant).slot); const before = pool.usage; const denied = Object.freeze({}); assert.equal(pool.prepareAdmission(denied, "data", grant).kind, "blocked"); assert.deepEqual(pool.usage, before);
      const control = createOwner(pool, "control"); createPage(pool, control.root, 1, "control"); assert.equal(pool.prepareAdmission(Object.freeze({}), "control", grant).kind, "blocked"); closeLedger(pool);
    }
    const probeSource = await Bun.file(`${import.meta.dir}/🟦️.ts`).text(); const probeAst = ts.createSourceFile("resident.ts", probeSource, ts.ScriptTarget.ES2022, true); const probeFunction = probeAst.statements.find(item => ts.isFunctionDeclaration(item) && item.name?.text === "forward"); assert(probeFunction);
    const probeCompiled = ts.transpileModule(probeFunction.getText(probeAst), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }); const probeForward: unknown = runInThisContext(`(() => { ${probeCompiled.outputText}; return forward; })()`); assert.equal(typeof probeForward, "function");
    for (const failure of fixture.closeChildren) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, 0); owner.root.beginClose(); const actual = resident.OwnedResidentPage.prototype.closeStep; const fault = Object.freeze({ close: failure }); let calls = 0;
      const child: resident.ResidentStep = { kind: failure === "full-grant-complete" ? "complete" : failure === "blocked" ? "blocked" : "rejected", phase: failure, items: 1, bytes: failure === "over-grant" ? 4097 : failure === "full-grant-complete" ? 4096 : 7 };
      resident.OwnedResidentPage.prototype.closeStep = function (): resident.ResidentStep { calls++; if (failure === "throw") throw fault; return child; };
      let current: resident.ResidentStep; try { current = owner.root.closeStep({ maxItems: 1, maxBytes: 264 }); } finally { resident.OwnedResidentPage.prototype.closeStep = actual; }
      assert.equal(calls, 0); assert.deepEqual(current, { kind: "pending", phase: "resident-page-close", items: 1, bytes: 264 }); assert.equal(owner.root.retirement, null); assert(source.root.retirement);
      if (failure !== "throw") { assert(typeof probeForward === "function"); assert.deepEqual(Reflect.apply(probeForward, undefined, [child, grant]), { ...child, kind: failure === "full-grant-complete" ? "pending" : child.kind }); }
      closeCell(source.cell); closeCell(owner.cell); closeLedger(pool);
    }
    for (const frontier of fixture.childFaultFrontiers) {
      const pool = new OwnedResidentLedger(fixture.capacity); const owner = createOwner(pool); const source = createPage(pool, owner.root, 1); source.root.allocate(grant); source.root.writeByte(73, grant); const fault = Object.freeze({ frontier }); const fill = Uint8Array.prototype.fill; owner.root.beginClose();
      Uint8Array.prototype.fill = function (value, start, end) { if (frontier === "after-fill") fill.call(this, value, start, end); throw fault; };
      let current: resident.ResidentStep; try { current = owner.root.closeStep(grant); } finally { Uint8Array.prototype.fill = fill; }
      assert.equal(current.kind, "rejected"); assert.equal(current.bytes, 0); assert.equal(owner.cell.failure, fault); assert.equal(source.root.retirement, null); closeCell(source.cell); closeCell(owner.cell); assert.deepEqual(pool.usage.data, cellCharge); assert.equal(owner.cell.retirement, null);
    }
    const custodyPool = new OwnedResidentLedger(fixture.capacity); const custodyOwner = createOwner(custodyPool); const custodyReader = createOwner(custodyPool); const custodyCell = claimCell(custodyPool); const custody = custodyOwner.root.reserveExternalBacking(4, custodyCell, grant).slot; assert(custody); custody.beginReceive(grant); const contents = new ArrayBuffer(4); new Uint8Array(contents).set([1, 2, 3, 4]); const receipt = custody.adoptTransferred(contents, grant).receipt; assert(resident.OwnedResidentBackingCustody.matches(receipt, custody)); const viewCell = claimCell(custodyPool); const view = custodyReader.root.beginRead(custody, viewCell, grant).reader; assert(view);
    custodyOwner.root.beginClose(); assert(!resident.OwnedResidentBackingCustody.matches(receipt, custody)); assert.equal(view.byteAt(3), 4); assert.equal(custodyOwner.root.closeStep(grant).kind, "blocked"); closeLedger(custodyPool); assert(!resident.OwnedResidentBackingCustody.matches(receipt, custody));
    const lostPool = new OwnedResidentLedger(fixture.capacity); const lostConsumer = Object.freeze({}); lostPool.prepareAdmission(lostConsumer, "data", grant); closeLedger(lostPool);
    const program = ts.createProgram([`${import.meta.dir}/🟦️.ts`], { strict: true, noEmit: true, target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, types: [], lib: ["lib.es2022.d.ts", "lib.dom.d.ts"] });
    const diagnostics = ts.getPreEmitDiagnostics(program); assert.equal(diagnostics.length, 0, ts.formatDiagnosticsWithColorAndContext(diagnostics, { getCanonicalFileName: name => name, getCurrentDirectory: () => import.meta.dir, getNewLine: () => "\n" }));
    console.log(`[DEBUG] Resident capacity=${fixture.invalidCapacities.length} actualOverflow=2 ownerReader=1 partialExtent=${fixture.pageLengths.length} simultaneousRawUiScratch=1 postedCancel=1 unsubmittedCancel=1 transferredViewFault=1 controlAxes=${fixture.controlCases.length} childClose=${fixture.closeChildren.length} childFault=${fixture.childFaultFrontiers.length} privateDispatch=${admissionFixture.resourceKinds.length} quarantine=${admissionFixture.quarantine.length} domainRecord=1 recordOverflow=3 finalizerFrontiers=8 admissionFailures=${fixture.admissionFailures.length} admissionBootstrap=${admissionFixture.bootstrap.length} firstFault=${admissionFixture.faultKinds.length} resourceWrapper=${admissionFixture.resourceKinds.length} terminalAliasDetach=1 strictTS=0 oracle=Ajv+Immer+Buffer+BigInt`);
  }
}
//#endregion 🧪️ResidentOracle
const router = new ScriptRouter(import.meta.dir).register("test", TestScript);
await runBundleScriptMain(router, import.meta.url, { defaultCommand: "test" });
