[package]
name = "semio-s-kernel-mathematical-graph-manifest"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
build = "build.rs"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
dsl = { path = "../../../../dsl/rs", package = "semio-s-kernel-dsl" }
neural_engine = { path = "../../../../neural/engine/rs", package = "semio-s-kernel-neural-engine" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[build-dependencies]
serde_json = "1.0.140"
