[package]
name = "reasoning-mindmap-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[package.metadata.component]
package = "semio:reasoning-mindmap"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "reasoning-wires"
aliases = ["wires"]
ports = { react = 6015, wgpu = 6115 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
semio-framework-plugin = { path = "../../../../framework/plugin/rs" }
reasoning_mindmap = { path = "../../rs" }
reasoning_mindmap_wires = { path = "../../wires/rs" }
puzzle_2d = { path = "../../../../puzzle/2d/rs" }
vcs = { path = "../../../../vcs/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

