type LowpolyConfig {
  activeObjectId: String! @state(class: CONFIG)
  selectionMode: String! @state(class: CONFIG)
  selectionIds: [Int!]! @state(class: CONFIG)
  selectionTargetsMesh: Boolean! @state(class: CONFIG)
  selectionTargetsVertex: Boolean! @state(class: CONFIG)
  selectionTargetsEdge: Boolean! @state(class: CONFIG)
  selectionTargetsFace: Boolean! @state(class: CONFIG)
  selectionKeys: [String!]! @state(class: CONFIG)
  paintUtility: String! @state(class: CONFIG)
  activePaintLayer: Int! @state(class: CONFIG)
  selectionMethod: String! @state(class: CONFIG)
  selectionModeDefault: String! @state(class: CONFIG)
  selectedObjectIds: [String!]! @state(class: CONFIG)
  hoveredObjectId: String @state(class: CONFIG)
  hoveredTargetObjectId: String @state(class: CONFIG)
  hoveredTargetMode: String @state(class: CONFIG)
  hoveredTargetId: Int @state(class: CONFIG)
  utilityParamsJson: String! @state(class: CONFIG)
  paintColorR: Int! @state(class: CONFIG)
  paintColorG: Int! @state(class: CONFIG)
  paintColorB: Int! @state(class: CONFIG)
  paintColorA: Int! @state(class: CONFIG)
  worldCameraPosition: [Float!]! @state(class: CONFIG)
  worldCameraTarget: [Float!]! @state(class: CONFIG)
  worldCameraFov: Float! @state(class: CONFIG)
  engagementInput: String! @state(class: CONFIG)
  showEdges: Boolean! @state(class: CONFIG)
  sunEnabled: Boolean! @state(class: CONFIG)
  sunAzimuth: Float! @state(class: CONFIG)
  sunElevation: Float! @state(class: CONFIG)
  sunIntensity: Float! @state(class: CONFIG)
  sunColor: String! @state(class: CONFIG)
  activeUtilityId: String! @state(class: CONFIG)
  locale: String! @state(class: CONFIG)
}
