syntax = "proto3";
package semio.app.lowpoly.lowpoly;
message LowpolyConfig {
  // @state config
  string active_object_id = 1;
  // @state config
  string selection_mode = 2;
  // @state config
  repeated uint32 selection_ids = 3;
  // @state config
  bool selection_targets_mesh = 4;
  // @state config
  bool selection_targets_vertex = 5;
  // @state config
  bool selection_targets_edge = 6;
  // @state config
  bool selection_targets_face = 7;
  // @state config
  repeated string selection_keys = 8;
  // @state config
  string paint_utility = 9;
  // @state config
  uint32 active_paint_layer = 10;
  // @state config
  string selection_method = 11;
  // @state config
  string selection_mode_default = 12;
  // @state config
  repeated string selected_object_ids = 13;
  // @state config
  optional string hovered_object_id = 14;
  // @state config
  optional string hovered_target_object_id = 15;
  // @state config
  optional string hovered_target_mode = 16;
  // @state config
  optional uint32 hovered_target_id = 17;
  // @state config
  string utility_params_json = 18;
  // @state config
  uint32 paint_color_r = 19;
  // @state config
  uint32 paint_color_g = 20;
  // @state config
  uint32 paint_color_b = 21;
  // @state config
  uint32 paint_color_a = 22;
  // @state config
  repeated double world_camera_position = 23;
  // @state config
  repeated double world_camera_target = 24;
  // @state config
  double world_camera_fov = 25;
  // @state config
  string engagement_input = 26;
  // @state config
  bool show_edges = 27;
  // @state config
  bool sun_enabled = 28;
  // @state config
  double sun_azimuth = 29;
  // @state config
  double sun_elevation = 30;
  // @state config
  double sun_intensity = 31;
  // @state config
  string sun_color = 32;
  // @state config
  string active_utility_id = 33;
  // @state config
  string locale = 34;
}
