[package]
name = "remodel_feature"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
remodel_image = { path = "../../image/rs", package = "remodel_image" }
mathematical_spatial = { path = "../../../../../framework/kernel/mathematical/spatial/rs", package = "semio-framework-kernel-mathematical-spatial" }
mathematical_random = { path = "../../../../../framework/kernel/mathematical/random/rs", package = "semio-framework-kernel-mathematical-random" }
