import {dirname,isAbsolute,join,relative,resolve} from "node:path";
import {lstat} from "node:fs/promises";
import {CargoController} from "../🎛️control/🟦️.ts";
import {cargoManifestDocument,cargoPhysicalDirectory,cargoPhysicalPath,assertCargoDiscoveryCurrent,type CargoDiscoveryOperation} from "../📁️physical/🟦️.ts";
import {cargoPatternMatches} from "../🔎️pattern/🟦️.ts";
import type {CargoTomlTable,CargoTomlValue} from "../📖️toml/🟦️.ts";

type CargoWorkspaceContribution=Readonly<{schemaVersion:1;members:readonly string[];exclude:readonly string[]}>;
type CargoWorkspaceScope=Readonly<{directory:string;manifest:string;lock:string;contribution:CargoWorkspaceContribution;memberManifests:readonly string[]}>;
type CargoWorkspacePackage=Readonly<{directory:string;manifest:string;name:string;workspace:string}>;
const slash=(value:string):string=>value.replaceAll("\\","/");
const isTable=(value:unknown):value is CargoTomlTable=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const table=(value:unknown):CargoTomlTable=>{if(!isTable(value))throw Error("Cargo requires an owned table");return value;};
const opaque=new Set(["node_modules","target","dist","build","🤖️generated","🗑️generated","coverage","temp","compose"]);
class ModelOwners {readonly scopes:CargoWorkspaceScope[]=[];readonly packages:CargoWorkspacePackage[]=[];scopesComplete=false;packagesComplete=false;scopeState:"empty"|"running"|"refused"|"complete"="empty";packageState:"empty"|"running"|"refused"|"complete"="empty";scopeManifest:string|null=null;constructor(readonly root:string){} }
const models=new WeakMap<object,ModelOwners>();

/** 📦️ Allocates an explicit partial owner only after the caller admits it. */
async function retain<T>(operation:CargoDiscoveryOperation,path:string,bytes:number,make:()=>T):Promise<T>{await new CargoController(operation,operation.workspace).step("model-owner",path,1,bytes);const owner=make();operation.workspace.partialRecords.push(owner);return owner;}
async function model(root:string,operation:CargoDiscoveryOperation):Promise<ModelOwners>{const previous=models.get(operation.workspace);if(previous){if(previous.root!==resolve(root))throw Error("Cargo workspace cannot mix repository roots");return previous;}const owner=await retain(operation,root,256,()=>new ModelOwners(resolve(root)));models.set(operation.workspace,owner);return owner;}
async function checkpoint(operation:CargoDiscoveryOperation,path:string,units=1,bytes=0):Promise<void>{if(operation.workspace.state!=="active")throw Error("Cargo discovery view is no longer current");await new CargoController(operation,operation.workspace).step("model",path,units,bytes);}
async function strings(value:unknown,path:string,operation:CargoDiscoveryOperation):Promise<string[]>{if(!Array.isArray(value))throw Error("Cargo requires authored pattern arrays");const rows=await retain<string[]>(operation,path,64,()=>[]),seen=await retain(operation,path,64,()=>new Set<string>());for(const pattern of value){await checkpoint(operation,path);if(typeof pattern!=="string"||!pattern.length||pattern.length>4096||isAbsolute(pattern)||/^[A-Za-z]:\//u.test(pattern)||pattern.includes("\\")||pattern.split("/").includes("..")||seen.has(pattern))throw Error("Cargo pattern is invalid or repeated");await checkpoint(operation,path,pattern.length,32+pattern.length*2);seen.add(pattern);rows.push(pattern);}return rows;}
async function closed(value:CargoTomlTable,names:readonly string[],operation:CargoDiscoveryOperation,path:string):Promise<void>{for(const key in value){await checkpoint(operation,path);if(Object.hasOwn(value,key)&&!names.includes(key))throw Error("Cargo declaration has an unknown field");}}
async function pathPresent(root:string,path:string,operation:CargoDiscoveryOperation):Promise<boolean>{await checkpoint(operation,path);const full=resolve(root,path),rel=slash(relative(resolve(root),full));if(rel.startsWith("../")||isAbsolute(rel))throw Error("Cargo path escapes repository");let current=resolve(root);for(const part of rel.split("/").filter(Boolean)){await checkpoint(operation,path);current=join(current,part);try{const row=await lstat(current);if(row.isSymbolicLink())throw Error("Cargo path contains a symlink");}catch(error){if(error&&typeof error==="object"&&"code" in error&&error.code==="ENOENT")return false;throw error;}}return true;}
async function matches(patterns:readonly string[],path:string,operation:CargoDiscoveryOperation):Promise<boolean>{for(const pattern of patterns)if(await cargoPatternMatches(pattern,path,operation))return true;return false;}
async function prefixes(patterns:readonly string[],operation:CargoDiscoveryOperation):Promise<string[]>{const result=await retain<string[]>(operation,"pattern-prefixes",64,()=>[]);for(const pattern of patterns){let index=0;for(;index<pattern.length;index++){await checkpoint(operation,pattern);if("*?[{".includes(pattern[index]!))break;}await checkpoint(operation,pattern,1,32+index*2);result.push(pattern.slice(0,index).replace(/\/$/u,""));}return result;}
async function inPrefix(directory:string,values:readonly string[],operation:CargoDiscoveryOperation):Promise<boolean>{for(const prefix of values){await checkpoint(operation,directory,prefix.length+directory.length+1);if(!prefix||directory===prefix||directory.startsWith(prefix+"/")||prefix.startsWith(directory+"/"))return true;}return false;}
async function sorted(values:ReadonlySet<string>,operation:CargoDiscoveryOperation):Promise<string[]>{const result=await retain<string[]>(operation,"sort",64+values.size*16,()=>[]);for(const value of values){await checkpoint(operation,value);result.push(value);}const scratch=await retain<string[]>(operation,"sort",64+values.size*16,()=>[]);for(let width=1;width<result.length;width*=2){for(let start=0;start<result.length;start+=width*2){let left=start,right=Math.min(start+width,result.length),out=start;const middle=right,end=Math.min(start+width*2,result.length);while(left<middle||right<end){await checkpoint(operation,"sort");if(right>=end||left<middle&&result[left]!.localeCompare(result[right]!)<=0)scratch[out++]=result[left++]!;else scratch[out++]=result[right++]!;}for(let index=start;index<end;index++){await checkpoint(operation,"sort");result[index]=scratch[index]!;}}}return result;}

/** 🧬️ Admits the closed physical membership declaration with explicit ownership. */
async function parseCargoWorkspaceContribution(value:unknown,operation:CargoDiscoveryOperation):Promise<CargoWorkspaceContribution>{const row=table(value);await closed(row,["schemaVersion","members","exclude"],operation,"contribution");if(row.schemaVersion!==1)throw Error("Cargo contribution version is invalid");const members=await strings(row.members,"members",operation),exclude=await strings(row.exclude,"exclude",operation);if(!members.length)throw Error("Cargo contribution has no members");return retain(operation,"contribution",64,()=>({schemaVersion:1,members,exclude}));}
async function scope(directory:string,workspace:CargoTomlTable,operation:CargoDiscoveryOperation):Promise<CargoWorkspaceScope>{const metadata=workspace.metadata===undefined?undefined:table(workspace.metadata),semio=metadata?.semio===undefined?undefined:table(metadata.semio),admission=semio?.repository===undefined?undefined:table(semio.repository);if(!admission)throw Error("Cargo repository workspace lacks authored admission");await closed(admission,["schema-version","owner-manifests","member-manifests","exclude-patterns"],operation,directory);if(admission["schema-version"]!==1)throw Error("Cargo repository workspace version is invalid");const memberManifests=await strings(admission["member-manifests"],directory,operation);if(!memberManifests.length||memberManifests.some(value=>!value.endsWith("Cargo.toml")))throw Error("Cargo repository member authority is invalid");const contribution=await parseCargoWorkspaceContribution({schemaVersion:1,members:workspace.members,exclude:admission["exclude-patterns"]},operation),prefix=directory==="."?"":directory+"/";return retain(operation,directory,128+directory.length*6,()=>({directory,manifest:prefix+"Cargo.toml",lock:prefix+"Cargo.lock",memberManifests,contribution}));}
async function repositoryAdmission(document:CargoTomlTable):Promise<CargoTomlTable|undefined>{const workspace=document.workspace===undefined?undefined:table(document.workspace),metadata=workspace?.metadata===undefined?undefined:table(workspace.metadata),semio=metadata?.semio===undefined?undefined:table(metadata.semio);return semio?.repository===undefined?undefined:table(semio.repository);}

/** 🗂️ Discovers authored repository owners through incremental physical cursors. */
async function discoverCargoWorkspaces(root:string,manifest:string,operation:CargoDiscoveryOperation):Promise<readonly CargoWorkspaceScope[]>{const owner=await model(root,operation);await checkpoint(operation,"workspaces");if(owner.scopeManifest!==null&&owner.scopeManifest!==manifest)throw Error("Cargo discovery cannot mix manifest scopes");owner.scopeManifest=manifest;const base=slash(dirname(manifest));if(owner.scopesComplete)return owner.scopes;if(owner.scopeState!=="empty")throw Error("Cargo workspace discovery is incomplete");owner.scopeState="running";
 try{const rootDocument=await cargoManifestDocument(root,manifest,operation),admission=await repositoryAdmission(rootDocument);if(!admission)throw Error("Root Cargo workspace lacks authored repository admission");const patterns=await strings(admission["owner-manifests"],"owners",operation);await strings(admission["exclude-patterns"],"owner-exclusions",operation);if(patterns.some(value=>!value.endsWith("Cargo.toml")))throw Error("Cargo owner manifest pattern is invalid");const prefix=await prefixes(patterns,operation),files=await retain(operation,"owner-paths",64,()=>new Set<string>([manifest])),pending=await retain<string[]>(operation,"directories",64,()=>[""]);
 for(let index=0;index<pending.length;index++){const directory=pending[index]!;if(directory&&!await inPrefix(directory,prefix,operation))continue;const depth=directory?directory.split("/").length:0;if(depth>=operation.maximumDepth)throw Error("Cargo physical owner depth refused");let relevant=false;for(const pattern of patterns){await checkpoint(operation,pattern,pattern.length+1);if(pattern.split("/").includes("**")||depth<pattern.split("/").length){relevant=true;break;}}if(!relevant)continue;const cursor=await cargoPhysicalDirectory(root,slash(join(base,directory||".")),operation),control=new CargoController(operation,operation.workspace);while(true){const entry=await cursor.next(control);if(!entry)break;if(entry.name.startsWith(".")||opaque.has(entry.name)||entry.kind==="symlink")continue;const path=directory?directory+"/"+entry.name:entry.name;if(entry.kind==="directory"){await checkpoint(operation,path,1,32+path.length*2);pending.push(path);}else if(entry.kind==="file"&&entry.name==="Cargo.toml"&&await matches(patterns,path,operation)){await checkpoint(operation,path,1,32+path.length*2);files.add(slash(join(base,path)));}}}
 for(const path of await sorted(files,operation)){const document=await cargoManifestDocument(root,path,operation);if(path===manifest||await repositoryAdmission(document)!==undefined){const selected=await scope(slash(dirname(path)),table(document.workspace),operation);await checkpoint(operation,path,1,16);owner.scopes.push(selected);}}if(!owner.scopes.some(row=>row.directory===base))throw Error("Root Cargo owner is absent");owner.scopesComplete=true;owner.scopeState="complete";return owner.scopes;}catch(error){owner.scopeState="refused";throw error;}}

/** 🧭️ Selects the actual nearest physical owner, including explicit isolated native workspaces. */
export async function cargoWorkspaceForManifest(root:string,manifest:string,operation:CargoDiscoveryOperation):Promise<CargoWorkspaceScope>{const document=await cargoManifestDocument(root,manifest,operation),packageRow=document.package===undefined?undefined:table(document.package);let directory=packageRow?.workspace!==undefined?typeof packageRow.workspace==="string"?resolve(root,dirname(manifest),packageRow.workspace):(()=>{throw Error("Cargo workspace pointer must be text");})():resolve(root,dirname(manifest));
 while(true){await checkpoint(operation,manifest);const path=slash(relative(resolve(root),join(directory,"Cargo.toml")));if(path.startsWith("../")||isAbsolute(path))throw Error("Cargo workspace escapes repository");if(await pathPresent(root,path,operation)){const row=await cargoManifestDocument(root,path,operation);if(row.workspace!==undefined){const local=slash(relative(resolve(root),directory))||".",workspace=table(row.workspace);if(await repositoryAdmission(row)!==undefined)return scope(local,workspace,operation);const contribution=await parseCargoWorkspaceContribution({schemaVersion:1,members:workspace.members??["."],exclude:workspace.exclude??[]},operation),memberManifests=await retain<string[]>(operation,path,64,()=>[]);for(const member of contribution.members){await checkpoint(operation,path,1,32+member.length*2);memberManifests.push(member==="."?"Cargo.toml":member+"/Cargo.toml");}const prefix=local==="."?"":local+"/";return retain(operation,path,128,()=>({directory:local,manifest:prefix+"Cargo.toml",lock:prefix+"Cargo.lock",memberManifests,contribution}));}}if(directory===resolve(root))throw Error("Cargo package has no workspace");directory=dirname(directory);}}

/** 🦀️ Expands current package members while pruning child workspace ownership. */
async function cargoWorkspaceMembers(root:string,owner:CargoWorkspaceScope,operation:CargoDiscoveryOperation):Promise<readonly CargoWorkspacePackage[]>{const pending=await retain<string[]>(operation,owner.manifest,64,()=>[""]),paths=await retain(operation,owner.manifest,64,()=>new Set<string>()),prefix=await prefixes(owner.memberManifests,operation),leaves=await retain<string[]>(operation,owner.manifest,64,()=>[]);for(const pattern of owner.memberManifests){await checkpoint(operation,pattern,1,32+pattern.length*2);leaves.push(pattern.endsWith("/Cargo.toml")?pattern.slice(0,-11):"");}const relativeManifest=(directory:string)=>slash(join(owner.directory,directory,"Cargo.toml")),fullDirectory=(directory:string)=>slash(join(owner.directory,directory));
 if(await matches(owner.memberManifests,"Cargo.toml",operation)&&!await matches(owner.contribution.exclude,".",operation)&&!await matches(owner.contribution.exclude,"./",operation)&&!await matches(owner.contribution.exclude,"Cargo.toml",operation)){const path=relativeManifest("");if((await cargoManifestDocument(root,path,operation)).package!==undefined){await checkpoint(operation,path,1,32+path.length*2);paths.add(path);}}
 for(let index=0;index<pending.length;index++){const directory=pending[index]!;if(directory&&!await inPrefix(directory,prefix,operation))continue;if(directory.split("/").length>=operation.maximumDepth)throw Error("Cargo physical member depth refused");const path=relativeManifest(directory);if(directory&&await pathPresent(root,path,operation)){const document=await cargoManifestDocument(root,path,operation);if(document.package!==undefined&&await matches(leaves,directory,operation)){await checkpoint(operation,path,1,32+path.length*2);paths.add(path);}}const cursor=await cargoPhysicalDirectory(root,fullDirectory(directory),operation),control=new CargoController(operation,operation.workspace);while(true){const entry=await cursor.next(control);if(!entry)break;const local=directory?directory+"/"+entry.name:entry.name;if(entry.name.startsWith(".")||opaque.has(entry.name)||entry.kind==="symlink")continue;let excluded=await matches(owner.contribution.exclude,local,operation)||await matches(owner.contribution.exclude,local+"/",operation);if(!excluded)for(const pattern of owner.contribution.exclude)if(pattern.endsWith("/**")&&await cargoPatternMatches(pattern.slice(0,-3),local,operation)){excluded=true;break;}if(excluded)continue;if(entry.kind==="directory"){await checkpoint(operation,local,1,32+local.length*2);pending.push(local);}else if(entry.kind==="file"&&entry.name==="Cargo.toml"&&local!=="Cargo.toml"&&await matches(owner.memberManifests,local,operation)&&!await matches(owner.contribution.exclude,slash(dirname(local)),operation)){const manifest=relativeManifest(directory);await checkpoint(operation,manifest,1,32+manifest.length*2);paths.add(manifest);}}}
 if(!paths.size)throw Error("Cargo workspace has no current source-bound members");const names=await retain(operation,owner.manifest,64,()=>new Set<string>()),packages=await retain<CargoWorkspacePackage[]>(operation,owner.manifest,64,()=>[]);for(const manifest of await sorted(paths,operation)){const document=await cargoManifestDocument(root,manifest,operation);if(document.package===undefined)continue;const selected=await cargoWorkspaceForManifest(root,manifest,operation);if(selected.directory!==owner.directory)continue;const packageRow=table(document.package),name=packageRow.name;if(typeof name!=="string"||!name||names.has(name))throw Error("Cargo member name is missing or repeated");await checkpoint(operation,manifest,name.length+1,32+name.length*2);names.add(name);const row=await retain(operation,manifest,128,()=>({directory:slash(dirname(manifest)),manifest,name,workspace:owner.directory}));await checkpoint(operation,manifest,1,16);packages.push(row);}if(!packages.length)throw Error("Cargo workspace has no current source-bound members");return packages;}

/** 📦️ Returns current owned metadata from the same admitted manifest read. */
async function cargoRepositoryPackages(root:string,manifest:string,operation:CargoDiscoveryOperation):Promise<readonly CargoWorkspacePackage[]>{const owner=await model(root,operation);await checkpoint(operation,"packages");if(owner.scopeManifest!==null&&owner.scopeManifest!==manifest)throw Error("Cargo package scope changed");if(owner.packagesComplete)return owner.packages;if(owner.packageState!=="empty")throw Error("Cargo package discovery is incomplete");owner.packageState="running";try{const names=await retain(operation,"package-names",64,()=>new Set<string>());for(const scope of await discoverCargoWorkspaces(root,manifest,operation))for(const row of await cargoWorkspaceMembers(root,scope,operation)){await checkpoint(operation,row.manifest,row.name.length+1,32+row.name.length*2);if(names.has(row.name))throw Error("Repository Cargo package name is repeated");names.add(row.name);owner.packages.push(row);}owner.packageState="complete";owner.packagesComplete=true;return owner.packages;}catch(error){owner.packageState="refused";throw error;}}


/** 🧬️ Admits the exact portable manifest authority without a default workspace. */
export type CargoCommandScope=Readonly<{schemaVersion:1;manifest:string}>;
export function parseCargoCommandScope(value:unknown):CargoCommandScope{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).sort().join(",")!=="manifest,schemaVersion")throw Error("Explicit Cargo command scope required");const row=value as Record<string,unknown>,manifest=row.manifest;if(row.schemaVersion!==1||typeof manifest!=="string"||manifest.length>256||!manifest.length||isAbsolute(manifest)||/^[A-Za-z]:/u.test(manifest)||manifest.includes("\\")||manifest.includes("\0")||manifest.split("/").some(part=>!part||part==="."||part==="..")||manifest.split("/").at(-1)!=="Cargo.toml")throw Error("Cargo command scope is not a portable manifest");return{schemaVersion:1,manifest};}
/** 🎯️ Selects exact current package argv using one required finite asynchronous discovery operation. */
export async function selectedCargoArguments(root:string,args:readonly string[],value:CargoCommandScope,operation:CargoDiscoveryOperation):Promise<string[]>{
 const control=new CargoController(operation,operation.workspace);await control.step("command-scope","",1,128);const selectedScope=parseCargoCommandScope(value),copied:string[]=[],names:string[]=[];operation.workspace.partialRecords.push(copied,names);if(!args.length)throw Error("Cargo command is absent");
 for(const argument of args){if(typeof argument!=="string"||argument.length>4096||argument.includes("\0"))throw Error("Cargo argument is not finite literal text");await control.step("argument",argument,argument.length+1,32+argument.length*2);copied.push(argument);}
 for(let index=1;index<copied.length;index++){const argument=copied[index]!;await control.step("selector",argument);if(argument==="--")break;if(argument==="--manifest-path"||argument.startsWith("--manifest-path=")){const manifest=argument==="--manifest-path"?copied[index+1]:argument.slice(16);if(!manifest||resolve(root,manifest).length>256)throw Error("Explicit Cargo manifest is absent or oversized");await control.finish("arguments-complete",selectedScope.manifest);return copied;}if(argument==="-p"||argument==="--package"){const name=copied[++index];if(!name)throw Error("Cargo package selector lacks a name");await control.step("selected-name",name,1,16);names.push(name);}else if(argument.startsWith("--package=")){const name=argument.slice(10);if(!name)throw Error("Cargo package selector lacks a name");await control.step("selected-name",name,1,32+name.length*2);names.push(name);}}
 if(!names.length){await control.finish("arguments-complete",selectedScope.manifest);return copied;}
 const packages=await cargoRepositoryPackages(root,selectedScope.manifest,operation),rows:CargoWorkspacePackage[]=[];operation.workspace.partialRecords.push(rows);
 for(const name of names){let selected:CargoWorkspacePackage|undefined;for(const row of packages){await control.step("package-name",row.manifest,name.length+1);if(row.name===name){if(selected)throw Error("Cargo package name is ambiguous");selected=row;}}if(!selected)throw Error("Unknown current Cargo package in the explicit manifest scope");await control.step("package-selection",selected.manifest,1,16);rows.push(selected);}
 const workspace=rows[0]!.workspace;for(const row of rows){await control.step("workspace-selection",row.manifest);if(row.workspace!==workspace)throw Error("Cargo command selects different physical workspaces");}
 await assertCargoDiscoveryCurrent(operation.workspace,operation);const manifest=join(root,rows[0]!.manifest);if(manifest.length>256)throw Error("Selected Cargo manifest path exceeds256 UTF16 units");await control.step("selected-arguments",manifest,1,64+manifest.length*2+copied.length*16);const result=[copied[0]!,"--manifest-path",manifest,...copied.slice(1)];operation.workspace.partialRecords.push(result);await control.finish("arguments-complete",manifest);return result;
}
