//! 🧪️ Original image publication preserves mutation/selection identity through all funding refusals.
use super::*;
fn observe<T>(action:impl FnOnce()->T)->(T,(usize,usize)){let(value,allocation)=semio_framework_trace::observe_heap_allocations_on_this_thread(action);assert!(!allocation.overflowed);(value,(allocation.requested_bytes,allocation.released_bytes))}
fn drain<T:semio_framework_value::retirement::RetireOwned>(value:T)->(usize,usize){let mut owner=semio_framework_value::retirement::controlled::ControlledRetirement::new(value).unwrap_or_else(|_|panic!("image publication original owner unsupported"));let(mut born,mut released)=(0,0);for _ in 0..2000000{if owner.terminal_is_empty(){return(born,released);}let copy=owner.next_copy_byte_demand().unwrap();let release=owner.next_release_byte_demand().unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:owner.next_capacity_byte_demand(if copy>0{copy}else{release}).unwrap(),maximum_release_bytes:release,maximum_depth:owner.next_depth_demand().unwrap()};let(step,physical)=observe(||owner.step(grant).unwrap());assert!(step.progress().fits(grant));assert_eq!(physical,(step.progress().retained_capacity_bytes,step.progress().released_bytes));born+=physical.0;released+=physical.1;}panic!("image publication original close stalled")}
#[test]
fn drawing_image_publication_original_funding_and_atomic_selection(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let image:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🔣️.json")).unwrap();let operation=AppOperationContext{app_instance_id:1,parent_document_id:"images".into(),operation_id:1,generation:1,canonical_base_revision:[0;32],authoring_seed:"images".into()};let snapshot=DrawingSnapshot::default();let input=super::super::ImportImage{payload:image["cases"][0]["input"]["payload"].as_str().unwrap().into(),name:Some(law["name"].as_str().unwrap().into()),parent_id:None,index:None};let mut journeys=0;
 for stop in law["cancelAfter"].as_array().unwrap().iter().map(|value|value.as_u64().unwrap()as usize).chain([usize::MAX]){let asset:DrawingImageAsset=serde_json::from_value(image["cases"][0]["expected"].clone()).unwrap();let original_bytes=asset.samples.allocated_bytes();let original_pointer=asset.samples.get(0).unwrap()as*const[u8;4];let(mut job,physical)=observe(||DrawingImagePublicationJob::new(asset,&operation));assert_eq!(physical,(0,0));let mut born=original_bytes;let mut output=None;
  for turn in 0..20000{if turn==stop{break;}let quote=job.work_demands(&input,&operation,262144).unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:quote.copy_bytes,maximum_capacity_bytes:quote.capacity_bytes,maximum_release_bytes:quote.release_bytes,maximum_depth:quote.depth};if job.ready(){let(value,physical)=observe(||job.take_result(&input,&operation,grant).unwrap().unwrap());assert_eq!(physical,(0,0));assert!(value.1.fits(grant));output=Some(value.0);break;}for axis in law["deniedAxes"].as_array().unwrap(){if axis.as_str()==Some("capacityBytes")&&quote.capacity_bytes==0{continue;}let mut denied=grant;match axis.as_str().unwrap(){"items"=>denied.maximum_items=0,"copyBytes"=>denied.maximum_copy_bytes-=1,"capacityBytes"=>denied.maximum_capacity_bytes-=1,_=>denied.maximum_depth=0};let before=(job.phase,job.text,job.seed_offset,job.root,job.depth,job.visited);let(receipt,physical)=observe(||job.advance(&snapshot,&input,&operation,denied).unwrap());assert_eq!(receipt,Default::default());assert_eq!(physical,(0,0));assert_eq!((job.phase,job.text,job.seed_offset,job.root,job.depth,job.visited),before);}
   let(receipt,physical)=observe(||job.advance(&snapshot,&input,&operation,grant).unwrap());assert!(receipt.fits(grant));assert_eq!(physical,(quote.capacity_bytes,0));assert_eq!(physical.0,receipt.retained_capacity_bytes);born+=physical.0;
  }
  let(mut close_born,mut released)=drain(job);if let Some(output)=output{assert_eq!(output.mutations.len(),2);assert_eq!(output.selection.len(),1);let DrawingMutation::ImportImageAsset(asset)=&output.mutations[0]else{unreachable!()};assert_eq!(asset.asset.samples.get(0).unwrap()as*const[u8;4],original_pointer);assert_eq!(asset.asset_id.to_string_owner(),format!("image-asset-{}",law["identity"]["expectedDigest"].as_str().unwrap()));let DrawingMutation::CreateLayer(layer)=&output.mutations[1]else{unreachable!()};assert_eq!(crate::schema::layer_id(&layer.layer).to_string_owner(),format!("layer-{}",law["identity"]["expectedDigest"].as_str().unwrap()));assert_eq!(output.selection[0].domain,law["selection"]["domain"].as_str().unwrap());assert_eq!(output.selection[0].targets[0].id,crate::schema::layer_id(&layer.layer).to_string_owner());let(additional,bytes)=drain(output);close_born+=additional;released+=bytes;}else{assert_ne!(stop,usize::MAX);}assert_eq!(born+close_born,released);journeys+=1;
 }
 println!("[DEBUG] Image publication original samples, authoring-seeded SHA identity, two semantic mutations and selection; exact funding/cancellation journeys={journeys}");
}