type SpacePresence {
  selectedNodeIds: [String!]! @state(class: PRESENCE)
  hoveredNodeId: String @state(class: PRESENCE)
  camera: [SpaceWindowCameraEntry!]! @state(class: PRESENCE)
  activeNodeId: String @state(class: PRESENCE)
  focusedNodeId: String @state(class: PRESENCE)
  collapsedNodeIds: [String!]! @state(class: PRESENCE)
  previewOffNodeIds: [String!]! @state(class: PRESENCE)
}

type SpaceWindowCameraEntry {
  key: String!
  value: SpaceWindowCamera!
}

type SpaceWindowCamera {
  x: Float!
  y: Float!
  zoom: Float!
}
