[package]
name = "norm_en_1993"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
norm_core = { path = "../../../core/rs", package = "norm_core" }
serde = { version = "1.0.219", features = ["derive"] }
mathematical_algebra = { path = "../../../../../../framework/kernel/mathematical/algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
fem_core = { path = "../../../../fem/core/rs", package = "fem_core" }
norm_en_1990 = { path = "../../1990/rs", package = "norm_en_1990" }
norm_en_1991 = { path = "../../1991/rs", package = "norm_en_1991" }
vcs = { path = "../../../../../../framework/kernel/vcs/rs", package = "semio-framework-kernel-vcs" }
store = { path = "../../../../../kernel/store/rs", package = "semio-s-kernel-store" }
dsl = { path = "../../../../../../framework/kernel/dsl/rs", package = "semio-framework-kernel-dsl" }
