//! ⏯️ Package glue — wiring only. Domain lives at owner `🦀️.rs`; pure and target-neutral, so the
//! owner file compiles unmodified on native, `wasm32-unknown-unknown` and `wasm32-wasip2`.

#[cfg(test)]
extern crate self as semio_framework_tool_run;

#[path = "../../🦀️.rs"]
mod component;
pub use component::entities;
pub use component::progress_clone;
pub use component::step_ring_insert;
pub use component::presentation;
pub use component::{
    ToolRunTickWireCursor,
    TOOL_RUN_STEP_RING_CAPACITY,
    TOOL_RUN_STEP_ARGS_MAX,
    TOOL_RUN_COUNTERS_MAX,
    TOOL_RUN_PROVISIONAL_OPS_MAX,
    TOOL_RUN_MEMBER_OPS_MAX,
    TOOL_RUN_TRACE_RESIDENT_RECORDS,
    TOOL_RUN_TRACE_PAGE_OPS_MAX,
    TOOL_RUN_TRACE_PAGE_BYTES_MAX,
    TOOL_RUN_TICK_BYTES_MAX,
    TOOL_RUN_TRACE_LOG_COMPACT_FLOOR,
    TOOL_RUN_STATUS_ANNOUNCE_INTERVAL_MS,
    TOOL_RUN_RESERVED_REASON_FLOOR,
    TOOL_RUN_REASON_REBASING,
    TOOL_RUN_REASON_CONFLICT,
    TOOL_RUN_REASON_TRACE_TRUNCATED,
    TOOL_RUN_REASON_PROVISIONAL_CAP,
    TOOL_RUN_GROUP_ID_PREFIX,
    ToolRunId,
    ToolRunIdentity,
    ToolRunFreshness,
    ToolRunState,
    ToolRunSlot,
    ToolRunEvent,
    ToolRunEventKey,
    ToolRunEffect,
    ToolRunRejection,
    ToolRunTransition,
    ToolRunLane,
    ToolRunMachine,
    ToolRunVerdict,
    ToolRunStepKind,
    ToolRunStepArg,
    ToolRunStep,
    ToolRunStepRing,
    ToolRunCounter,
    ToolRunProgress,
    ToolRunTraceSubject,
    ToolRunTraceOp,
    TOOL_RUN_TRACE_PAGE_OVERHEAD_BYTES,
    ToolRunTracePage,
    ToolRunTraceDelta,
    ToolRunTraceCursor,
    ToolRunTraceRecord,
    ToolRunTraceApply,
    ToolRunTraceStore,
    ToolRunTick,
    ToolRunLimitError,
    ToolRunTickWriter,
    ToolRunCodecError,
    JobKindId,
    ToolRunRebasePolicy,
    ToolRunReconfigurePolicy,
    ToolRunTraceKind,
    ToolRunStageDefinition,
    ToolRunCounterDefinition,
    ToolRunReasonDefinition,
    ToolRunSettingsReads,
    tool_run_pointer_tokens,
    tool_run_pointer_value,
    ToolRunDefinition,
    ToolRunDefinitionError,
    TOOL_RUN_PANEL_ID,
    tool_run_panel_group_id,
    tool_run_panel_group_run,
    tool_run_panel_new_runs,
    TOOL_RUN_START_ACTION_ID,
    TOOL_RUN_PAUSE_ACTION_ID,
    TOOL_RUN_RESUME_ACTION_ID,
    TOOL_RUN_STEP_ACTION_ID,
    TOOL_RUN_ABORT_ACTION_ID,
    TOOL_RUN_FINALIZE_ACTION_ID,
    TOOL_RUN_DISMISS_ACTION_ID,
    TOOL_RUN_ACTION_IDS,
    TOOL_RUN_START_CHORD,
    TOOL_RUN_PAUSE_RESUME_CHORD,
    TOOL_RUN_STEP_CHORD,
    TOOL_RUN_ABORT_CHORD,
    TOOL_RUN_FINALIZE_CHORD,
    TOOL_RUN_DISMISS_CHORD,
    TOOL_RUN_ARG_TOOL_ID,
    TOOL_RUN_ARG_WINDOW_ID,
    TOOL_RUN_ARG_RUN_ID,
    TOOL_RUN_ARG_GENERATION,
    ToolRunActionArg,
    ToolRunAction,
    ToolRunLabel,
    tool_run_format,
};
