/** 🎬️ Owned vector plans and node-indexed painted caches publish as one completed scene. */
import {PaintedPathPrepareJob,PaintedRegionsCloseJob,type PaintedPathRegions} from "../🟦️.ts";
import {ScenePlanCloseJob} from "../../🧹️retire/🟦️.ts";
import type {DocumentScenePlan} from "../../📋️prepare/🟦️.ts";
import {segmentBounds} from "../../../🧮️geometry/🟦️.ts";
import {UnitRetirement,type WorkRetirement,type WorkRetirementProgress} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/◻️2d/🧹️retire/🟦️.ts";
type Point=readonly[number,number];type Bounds=[number,number,number,number];
export type PaintedSceneLimits={maxNodes:number;maxSegments:number;maxPoints:number;maxContours:number;maxWork:number};
export type PreparedSceneCounts={nodes:number;segments:number;points:number;contours:number};
export type PreparedPaint={kind:"empty"}|{kind:"path";regions:PaintedPathRegions}|{kind:"image";corners:Point[]};
export type PreparedGeometry={geometryBounds:Bounds|null;bounds:Bounds|null;paint:PreparedPaint};
export type PreparedScene={plan:DocumentScenePlan;geometry:PreparedGeometry[];flatness:number;counts:PreparedSceneCounts};
export type ScenePaintProgress=PreparedSceneCounts&{phase:"nodes"|"bounds"|"path"|"pathCleanup"|"complete";work:number;done:boolean};
const valid=(v:number)=>Number.isFinite(v)&&Math.abs(v)<=1e9;
const invalid=(message:string):never=>{throw new RangeError(message);};
const union=(a:Bounds|null,b:Bounds):Bounds=>a?[Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.max(a[2],b[2]),Math.max(a[3],b[3])]:b;
function rectangle(x:number,y:number,w:number,h:number,m:readonly number[]):PreparedGeometry{const corners=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]].map(([a,b])=>[m[0]!*a!+m[2]!*b!+m[4]!,m[1]!*a!+m[3]!*b!+m[5]!]as Point);let bounds:Bounds|null=null;for(const p of corners){if(!p.every(valid))invalid("Painted scene coordinate limit exceeded");bounds=union(bounds,[p[0],p[1],p[0],p[1]]);}return{geometryBounds:bounds,bounds,paint:{kind:"image",corners}};}
/** 🧹️ Adopts actual cache entries and their real vector-plan close frontier. */
export class PreparedSceneCloseJob implements WorkRetirement{
 private geometry:PreparedGeometry[];private extra:PreparedGeometry|null;private plan:ScenePlanCloseJob|null;private regions:WorkRetirement|null=null;private fixed:Point[]|null=null;private phase=0;private counter:UnitRetirement;
 constructor(scene:PreparedScene,extra:PreparedGeometry|null=null){this.geometry=scene.geometry;this.extra=extra;this.plan=new ScenePlanCloseJob(scene.plan);this.counter=new UnitRetirement(()=>this.step());}
 private step():boolean{if(this.regions){if(!this.regions.terminalIsEmpty()){this.regions.advance(1);return false;}this.regions=null;return false;}if(this.fixed){if(this.fixed.length)this.fixed.pop();else this.fixed=null;return false;}if(this.phase===0){const g=this.extra??this.geometry.pop();this.extra=null;if(g){if(g.paint.kind==="path")this.regions=new PaintedRegionsCloseJob(g.paint.regions);else if(g.paint.kind!=="empty")this.fixed=g.paint.corners;return false;}this.geometry=[];this.phase=1;return false;}if(this.plan){if(!this.plan.terminalIsEmpty()){this.plan.advance(1);return false;}this.plan=null;return false;}return true;}
 terminalIsEmpty():boolean{return this.counter.terminalIsEmpty();}
 advance(grant:number):WorkRetirementProgress{return this.counter.advance(grant);}
}
/** 🧱️ Constructor adoption keeps refused owned input available for real retirement. */
export class ScenePaintJob{
 private plan:DocumentScenePlan|null;private limits:PaintedSceneLimits;private geometry:PreparedGeometry[]=[];private counts:PreparedSceneCounts={nodes:0,segments:0,points:0,contours:0};private phase:ScenePaintProgress["phase"]="nodes";private work=0;private validated=false;private index=0;private segment=0;private pen:Point=[0,0];private origin:Point=[0,0];private bounds:Bounds|null=null;private matrix:[number,number,number,number,number,number]=[1,0,0,1,0,0];
 private path:PaintedPathPrepareJob|null=null;private pathRetirement:WorkRetirement|null=null;private retiredPaths:WorkRetirement[]=[];private pending:PreparedGeometry|null=null;private output:PreparedScene|null=null;private cancelled=false;private failure:unknown=null;private transferred=false;
 constructor(plan:DocumentScenePlan,private flatness:number,limits:PaintedSceneLimits){this.plan=plan;this.limits={...limits};}
 private validate():void{const l=this.limits;if(!Number.isFinite(this.flatness)||this.flatness<1e-6||this.flatness>16||!([['maxNodes',1024],['maxSegments',65536],['maxPoints',262144],['maxContours',65536],['maxWork',1e9]]as const).every(([key,max])=>Number.isSafeInteger(l[key])&&l[key]>0&&l[key]<=max))invalid("Invalid painted scene contract");if(this.plan!.nodes.length>l.maxNodes)invalid("Painted scene node limit exceeded");this.validated=true;}
 private admit(g:PreparedGeometry):void{const p=g.paint,points=p.kind==="path"?p.regions.points:p.kind==="empty"?0:4,contours=p.kind==="path"?p.regions.contours:p.kind==="empty"?0:1;if(this.counts.points+points>this.limits.maxPoints||this.counts.contours+contours>this.limits.maxContours)invalid("Painted scene cache count limit exceeded");this.geometry.push(g);this.pending=null;this.counts.points+=points;this.counts.contours+=contours;this.counts.nodes++;this.index++;this.phase="nodes";}
 private step():void{
  if(!this.validated){this.validate();return;}
  const node=this.plan!.nodes[this.index];
  switch(this.phase){
   case"nodes":{if(!node){this.output={plan:this.plan!,geometry:this.geometry,flatness:this.flatness,counts:{...this.counts}};this.plan=null;this.geometry=[];this.phase="complete";break;}if(node.transform.length!==6||!node.transform.every(valid))invalid("Painted scene transform limit exceeded");this.matrix=[...node.transform];const c=node.content;if(c.kind==="boolean"||c.kind==="trace")invalid("Unresolved algorithm in painted scene");if((c.kind==="path"||c.kind==="glyphs")){if(this.counts.segments+c.segments.length>this.limits.maxSegments)invalid("Painted scene segment limit exceeded");this.counts.segments+=c.segments.length;}this.bounds=null;this.segment=0;this.pen=[0,0];this.origin=[0,0];if(!node.visible||c.kind==="group"){this.admit({geometryBounds:null,bounds:null,paint:{kind:"empty"}});}else if((c.kind==="path"||c.kind==="glyphs")){if(c.stroke&&(c.stroke.dash?.length??0)>1024)invalid("Painted scene stroke limit exceeded");this.phase="bounds";}else if(c.kind==="image"){this.pending=rectangle(0,0,c.width,c.height,node.transform);this.admit(this.pending);}else invalid("Unresolved semantic text in painted scene");break;}
   case"bounds":{const c=node!.content;if(c.kind!=="path"&&c.kind!=="glyphs")throw new RangeError("Painted scene path owner changed");const s=c.segments[this.segment];if(s){if(!(s.kind==="close"&&this.bounds===null)){const b=segmentBounds(s,this.pen,this.origin,this.matrix),world:Bounds=[b[0],b[1],b[0]+b[2],b[1]+b[3]];if(!world.every(valid))invalid("Painted scene bounds limit exceeded");this.bounds=union(this.bounds,world);}if(s.kind==="move")this.origin=this.pen=s.to;else if(s.kind==="close")this.pen=this.origin;else this.pen=s.to;this.segment++;}else{this.path=PaintedPathPrepareJob.fromPrepared(node!,this.flatness,{maxSegments:65536,maxPoints:262144,maxContours:65536,maxWork:this.limits.maxWork});this.phase="path";}break;}
   case"path":{const c=node!.content;if(c.kind!=="path"&&c.kind!=="glyphs")throw new RangeError("Painted scene path owner changed");if(this.path!.advanceWork(1,index=>c.segments[index])){const moved=this.path!.intoRetirement();this.path=null;if(this.pathRetirement)this.retiredPaths.push(this.pathRetirement);this.pathRetirement=moved.job;this.pending={geometryBounds:this.bounds,bounds:moved.output!.bounds,paint:{kind:"path",regions:moved.output!}};this.phase="pathCleanup";}break;}
   case"pathCleanup":this.admit(this.pending!);break;
   case"complete":break;
  }
 }
 advance(grant:number):ScenePaintProgress{if(!Number.isSafeInteger(grant)||grant<1)invalid("Invalid painted scene work grant");if(this.cancelled)throw new DOMException("Painted scene cancelled","AbortError");if(this.failure)throw this.failure;try{for(let at=0;at<grant&&this.phase!=="complete";at++){if(this.validated&&this.work>=this.limits.maxWork)invalid("Painted scene work limit exceeded");this.step();this.work++;}}catch(error){this.failure=error;throw error;}return{phase:this.phase,work:this.work,...this.counts,done:this.phase==="complete"};}
 result():PreparedScene{if(this.cancelled)throw new DOMException("Painted scene cancelled","AbortError");if(this.failure)throw this.failure;if(this.phase!=="complete")throw Error("Painted scene incomplete");return this.output!;}
 cancel():void{this.cancelled=true;}
 intoRetirement():{job:WorkRetirement;output:PreparedScene|null}{if(this.transferred)invalid("Painted scene ownership already transferred");this.transferred=true;const success=this.phase==="complete"&&!this.cancelled&&!this.failure,output=success?this.output:null;let discarded:PreparedSceneCloseJob|null=null;if(this.output&&!success)discarded=new PreparedSceneCloseJob(this.output);else if(this.plan)discarded=new PreparedSceneCloseJob({plan:this.plan,geometry:this.geometry,flatness:this.flatness,counts:this.counts},this.pending);this.output=null;this.plan=null;this.geometry=[];this.pending=null;this.cancelled=true;if(this.path){this.path.cancel();if(this.pathRetirement)this.retiredPaths.push(this.pathRetirement);this.pathRetirement=this.path.intoRetirement().job;this.path=null;}return{output,job:new UnitRetirement(()=>{const retired=this.retiredPaths.at(-1);if(retired){if(!retired.terminalIsEmpty())retired.advance(1);else this.retiredPaths.pop();return false;}if(this.pathRetirement){if(!this.pathRetirement.terminalIsEmpty()){this.pathRetirement.advance(1);return false;}this.pathRetirement=null;return false;}if(discarded){if(!discarded.terminalIsEmpty()){discarded.advance(1);return false;}discarded=null;return false;}this.failure=null;return true;})};}
}
