import { readFileSync,existsSync,mkdirSync,writeFileSync,linkSync,unlinkSync } from "node:fs";
import { resolve,dirname } from "node:path";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import Parser from "web-tree-sitter";
import Ajv from "ajv/dist/2020.js";
const ticket=resolve(import.meta.dir,".."),out=resolve(ticket,"🗑️generated/current-native-origin/epoch-6/product/current-entrypoint-consumer-source1.json"),sha=(body:string|Buffer)=>createHash("sha256").update(body).digest("hex");let root=ticket;while(!existsSync(resolve(root,"nx.json")))root=dirname(root);if(process.argv.slice(2).join(" ")!=="source")throw Error("Exact source command required");const recipe=JSON.parse(readFileSync(resolve(import.meta.dir,"recipe.json"),"utf8")),bindings=[import.meta.path,...["recipe.json","schema.json","fixtures.json"].map(path=>resolve(import.meta.dir,path)),resolve(root,recipe.binary),resolve(root,recipe.unit),...['node_modules/web-tree-sitter/tree-sitter.js','node_modules/web-tree-sitter/tree-sitter.wasm','node_modules/tree-sitter-wasms/out/tree-sitter-rust.wasm'].map(path=>resolve(root,path))].map(path=>({path,sha256:sha(readFileSync(path))}));await Parser.init({locateFile:(name:string)=>resolve(root,"node_modules/web-tree-sitter",name)});const parser=new Parser();parser.setLanguage(await Parser.Language.load(resolve(root,"node_modules/tree-sitter-wasms/out/tree-sitter-rust.wasm")));const validate=new Ajv({strict:true}).compile(JSON.parse(readFileSync(resolve(import.meta.dir,"schema.json"),"utf8"))),checks=[];
for(const row of JSON.parse(readFileSync(resolve(import.meta.dir,"fixtures.json"),"utf8"))){const tree=parser.parse(row.source);if(tree.rootNode.hasError())throw Error("Independent actual current Rust syntax refusal");const own={blockingCalls:row.source.split("block_on(").length-1,driverCalls:row.source.split(recipe.driver+"(").length-1,driverDefinitions:row.source.split("fn "+recipe.driver+"<").length-1,canonicalBlockingCalls:row.source.split("semio_framework_async::block_on(").length-1},functions=tree.rootNode.descendantsOfType("function_item"),calls=tree.rootNode.descendantsOfType("call_expression").map((node:any)=>node.childForFieldName("function")?.text),external={blockingCalls:calls.filter((name:string)=>name?.split("::").at(-1)==="block_on").length,driverCalls:calls.filter((name:string)=>name===recipe.driver).length,driverDefinitions:functions.filter((node:any)=>node.childForFieldName("name").text===recipe.driver).length,canonicalBlockingCalls:calls.filter((name:string)=>name==="semio_framework_async::block_on").length};if(!isDeepStrictEqual(own,external)||!!validate(own)!==row.accepted||!!validate(external)!==row.accepted)throw Error("Independent canonical driver owner/call oracle differs "+row.id);checks.push({...row,own,external});}
const path=resolve(root,recipe.unit),before=readFileSync(path,"utf8");if(before.split(recipe.from).length!==2)throw Error("Exact current stale driver consumer differs");const after=before.replace(recipe.from,recipe.to),bt=parser.parse(before),at=parser.parse(after);if(bt.rootNode.hasError()||at.rootNode.hasError())throw Error("Current consumer syntax differs");const functions=(tree:any)=>tree.rootNode.descendantsOfType("function_item").map((node:any)=>node.childForFieldName("name").text);if(!isDeepStrictEqual(functions(bt),functions(at))||after.replace(recipe.to,recipe.from)!==before)throw Error("Current entire original consumer conservation differs");for(const binding of bindings)if(sha(readFileSync(binding.path))!==binding.sha256)throw Error("Current consumer binding advanced");const pair={path:recipe.unit,before,after,beforeHash:sha(before),afterHash:sha(after),forward:{start:0,delete:before,insert:after},inverse:{start:0,delete:after,insert:before}};mkdirSync(dirname(out),{recursive:true});const temp=out+".writing";writeFileSync(temp,JSON.stringify({ready:true,bindings,pairs:[pair],checks,functions:functions(bt).length,originalAssertionsConserved:true,sourceWritesOutsideTicket:false,nativeExecuted:false,scope:"Exact current canonical private driver token consumer; original block_on1 and drivercall3 assertions retained; no alias/restoration"}),{flag:"wx"});linkSync(temp,out);unlinkSync(temp);console.log("[DEBUG] "+JSON.stringify({ready:true,checks:checks.length,pairs:1,functions:functions(bt).length}));
