syntax = "proto3";
package semio.app.shooting.shooting;
message ShootingPresence {
  // @state shared-ui
  repeated string selected_shot_ids = 1;
  // @state shared-ui
  repeated string selected_asset_ids = 2;
  // @state shared-ui
  optional string hovered_asset_id = 3;
  // @state shared-ui
  ShootingCamera camera = 4;
  // @state shared-ui
  string active_utility_id = 5;
}

message ShootingCamera {
  repeated double position = 1;
  repeated double target = 2;
  double zoom = 3;
  double fov = 4;
  repeated double up = 5;
  optional string projection = 6;
}
