[package]
name = "semio-framework-kernel-mathematical-statistics"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_statistics"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_algebra = { path = "../../algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
mathematical_probability = { path = "../../probability/rs", package = "semio-framework-kernel-mathematical-probability" }
mathematical_tabular = { path = "../../tabular/rs", package = "semio-framework-kernel-mathematical-tabular" }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
