import {expect,test} from "bun:test";
import {createRequire} from "node:module";
import {join,resolve} from "node:path";
import {readFileSync,mkdirSync} from "node:fs";
import {Database} from "bun:sqlite";
import {runRuntimeInventoryBridge} from "../🟦️.ts";
import {CargoDiscoveryWorkspace,type CargoDiscoveryOperation} from "../../../../📚️library/🗂️workspaces/🦀️cargo/📁️physical/🟦️.ts";
import {MutationInventoryProcessWorkspace} from "../../../../../../../🔨️modules/🧪️test/🎮️mutation/🏭️inventory/🏃️execution/🟦️.ts";
import {JsonSyntaxWorkspace} from "../../../../../../../🔨️modules/🎒️pack/🔤️json/📥️decode/🟦️.ts";
import corpus from "../🔣️.json";

const root=process.env.SEMIO_RECEIVER_LAW_ROOT!,artifact=process.env.SEMIO_RECEIVER_LAW_ARTIFACT!,snapshot=process.env.SEMIO_RECEIVER_LAW_SNAPSHOT!,require=createRequire(join(root,"package.json")),machine=resolve(import.meta.dir,"../📜️script.ts");
const manifest={artifact:"sample.item",standard:"1",subset:"any"};
function control(id:string,maximumUnits=1000000,maximumOwnedBytes=16777216,cancelStage:string|null=null){const workspace=new CargoDiscoveryWorkspace(),controller=new AbortController(),events:unknown[]=[];const operation:CargoDiscoveryOperation={workspace,signal:controller.signal,maximumUnits,maximumOwnedBytes,maximumDepth:64,onProgress:progress=>{events.push(progress);if(cancelStage&&progress.stage===cancelStage)controller.abort();},yieldContinuation:()=>new Promise(resolve=>setTimeout(resolve,0))};const directory=join(artifact,id);mkdirSync(directory,{recursive:true});return{workspace,operation,events,policy:{version:1 as const,maximumUnits:1000000,maximumOwnedBytes:16777216,maximumCaptureBytes:65536,budgetMs:10000,compilerStorage:{buildDirectory:join(directory,"build"),leaseDirectory:join(directory,"lease"),targetDirectory:join(directory,"target"),captureDirectory:join(directory,"capture")}}};}
function owners(workspace:CargoDiscoveryWorkspace){return workspace.partialRecords.map(record=>{if(!record||typeof record!=="object"||!("processWorkspace"in record)||!(record.processWorkspace instanceof MutationInventoryProcessWorkspace)||!("syntax"in record)||!(record.syntax instanceof JsonSyntaxWorkspace)||!("source"in record)||!("inventory"in record))throw Error("Receiver owner was not retained");return{processWorkspace:record.processWorkspace,syntax:record.syntax,source:record.source,inventory:record.inventory};});}

test("real owned process capture and receiver agree with Execa, Ajv and SQLite",async()=>{const ajv=new(require("ajv").default)({strict:true}),schema=JSON.parse(readFileSync(join(snapshot,"🧰️framework/🔨️modules/🧪️test/🧬️schema/🔣️.json"),"utf8")),validate=ajv.compile({$schema:schema.$schema,$defs:schema.$defs,$ref:"#/$defs/RuntimeMutationInventory"}),db=new Database(":memory:");try{for(const row of corpus.cases.filter(row=>row.accepted)){const c=control(row.id),argv=[machine,"machine",row.id],oracle=await require("execa")(process.execPath,argv,{cwd:snapshot,env:process.env}),result=await runRuntimeInventoryBridge(snapshot,{command:process.execPath,args:argv},manifest,c.policy,c.operation);expect(result).toEqual(JSON.parse(oracle.stdout));expect(validate(result)).toBe(true);expect(db.query("select json_extract(?,'$.artifact') as artifact").get(row.source)).toEqual({artifact:result.artifact});const owner=owners(c.workspace)[0]!;expect(owner.source).toBe(oracle.stdout);expect(owner.inventory).toBe(result);expect(owner.processWorkspace.result?.code).toBe(0);expect(owner.processWorkspace.admittedEnvironment.CARGO_TARGET_DIR).toBe(c.policy.compilerStorage.targetDirectory);expect(owner.processWorkspace.admittedEnvironment.CARGO_BUILD_BUILD_DIR).toBe(c.policy.compilerStorage.buildDirectory);expect(owner.processWorkspace.reads.length).toBe(1);expect(owner.syntax.owners.length).toBeGreaterThan(0);expect(owner.syntax.units).toBe(owner.processWorkspace.completed);expect(owner.syntax.ownedBytes).toBe(owner.processWorkspace.ownedBytes);expect(c.events.length).toBeGreaterThan(0);}}finally{db.close();}});
test("process refusal preserves its receipt and never parses stdout",async()=>{const c=control("exit-refusal");await expect(runRuntimeInventoryBridge(snapshot,{command:process.execPath,args:[machine,"machine","process-refusal"]},manifest,c.policy,c.operation)).rejects.toThrow("exit/7");const owner=owners(c.workspace)[0]!;expect(owner.processWorkspace.result?.code).toBe(7);expect(owner.source).toBeUndefined();expect(owner.inventory).toBeUndefined();expect(owner.syntax.owners.length).toBe(0);});
test("protocol refusal retains the real source and partial syntax",async()=>{const c=control("protocol-refusal");await expect(runRuntimeInventoryBridge(snapshot,{command:process.execPath,args:[machine,"machine","undeclared-field"]},manifest,c.policy,c.operation)).rejects.toThrow();const owner=owners(c.workspace)[0]!;expect(owner.processWorkspace.result?.code).toBe(0);expect(owner.source).toBe(corpus.cases.find(row=>row.id==="undeclared-field")!.source);expect(owner.inventory).toBeUndefined();expect(owner.syntax.owners.length).toBeGreaterThan(0);});
test("zero caller credit refuses before creating any receiver owner",async()=>{const c=control("zero",0,0);await expect(runRuntimeInventoryBridge(snapshot,{command:process.execPath,args:[machine,"machine","empty"]},manifest,c.policy,c.operation)).rejects.toThrow("budget");expect(c.workspace.partialRecords).toEqual([]);expect(c.workspace.completed).toBe(0);expect(c.workspace.ownedBytes).toBe(0);});
test("actual protocol cancellation retains process and decoder partial owners",async()=>{const c=control("cancel-protocol",1000000,16777216,"inventory-protocol");await expect(runRuntimeInventoryBridge(snapshot,{command:process.execPath,args:[machine,"machine","dispatch"]},manifest,c.policy,c.operation)).rejects.toThrow();const owner=owners(c.workspace)[0]!;expect(owner.processWorkspace.result?.code).toBe(0);expect(owner.source).toBeDefined();expect(owner.inventory).toBeUndefined();expect(owner.syntax.owners.length).toBeGreaterThan(0);expect(c.operation.signal.aborted).toBe(true);});
