import{Database}from"bun:sqlite";import{join}from"node:path";import assert from"node:assert/strict";
const repo="/Users/ueli/Documents/semio",root=join(repo,"🧰️framework/🛍️products/💻️os/🔨️modules/🔁️workflow/🗿️artifacts/🏃️run/🧬️schema/📸️snapshot");
const io=await import(join(repo,"🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts")),ieee=await import(join(repo,"🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts")),owner=await import(join(root,"🟦️.ts")),fixture=await Bun.file(join(root,"🧫️fixtures/🪶️sqlite/🔣️.json")).json();
function snapshot(){const value=structuredClone(fixture.snapshot);value.status="canceled";value.trigger.kind="automation";for(const[index,node]of value.nodeRecords.entries()){node.status=fixture.nodeStatuses[index];node.durationMs=ieee.binary64(node.durationMs);}return value;}
const cases=[{name:"base",snapshot:snapshot()},...fixture.binary64Words.map((word:string)=>{const value=snapshot();for(const node of value.nodeRecords)node.durationMs={bits:BigInt("0x"+word)};return{name:word,snapshot:value};})];
for(const[kind,finished]of[["manual","absent"],["manual","empty"],["manual","unicode"],["automation","absent"],["automation","unicode"]]as const){const value=snapshot();value.trigger=structuredClone(fixture.triggers.find((trigger:{kind:string})=>trigger.kind===kind));if(finished==="absent")delete value.finishedAt;else value.finishedAt=finished==="empty"?"":"\0😀";cases.push({name:kind+"-"+finished,snapshot:value});}
const report=[];for(const value of cases){const database=await owner.runSnapshotToSqliteDatabase(value.snapshot),db=Database.deserialize(await io.exportSqliteDatabase(database),{safeIntegers:true});try{assert.equal(db.query("PRAGMA integrity_check").get().integrity_check,"ok");assert.equal(db.query("PRAGMA foreign_key_check").all().length,0);const names=db.query("SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name").all()as{name:string}[];assert.equal(names.length,7);const tables=names.map(({name})=>{const rows=db.query('SELECT * FROM "'+name+'" ORDER BY id').all();let bytes=0;for(const row of rows)for(const cell of Object.values(row))bytes+=cell===null?0:typeof cell==="string"?Buffer.byteLength(cell):8;return{table:name,rows:rows.length,bytes};});report.push({name:value.name,tables,bytes:tables.reduce((sum,table)=>sum+table.bytes,0)});console.log("[DEBUG] independent Run complete SQL cells case="+value.name+" bytes="+report.at(-1)!.bytes+" rows="+tables.reduce((sum,table)=>sum+table.rows,0)+" tables=7");}finally{db.close();}}
await Bun.write(join(repo,".🧬semio/🦑️repo/🎫️tickets/🎆️26/🌙️09/☀️30/UNIVERSAL-ARTIFACT-SNAPSHOT-SQ-LITE-I-O/🗑️generated/run-independent-semantic-cell-extents.json"),JSON.stringify(report,null,2)+"\n");

