//! 🛫️ Borrowed explicit Semio native fields are measured and emitted under one ownership control.
use semio_framework_value::{ValueError,ValueRefusalKind};
use semio_framework_value::native_encoding::NativeEncodeControl;
use store::sqlite_snapshot::{SnapshotEncoding,SqliteSnapshotControl,SqliteSnapshotPhase,SqliteDatabaseLimits};
use crate::standards::v1::subsets::base::schema::geometry::{SemioTransform,native::{NativeF64,NativeF32}};
pub(crate) struct Writer<'a,'b,'c>{control:&'a mut NativeEncodeControl<'b>,output:Option<&'c mut Vec<u8>>,count:usize,entities:usize,limits:SqliteDatabaseLimits,primitive_value_limit:Option<usize>}
impl Writer<'_,'_,'_>{
 pub(crate) fn bytes(&mut self,bytes:&[u8])->Result<(),ValueError>{self.count=self.count.checked_add(bytes.len()).filter(|count|*count<=self.limits.max_file_bytes&&self.primitive_value_limit.is_none_or(|maximum|*count<=maximum)).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"Semio native output exceeds file or ownership limit"))?;for chunk in bytes.chunks(256){if let Some(output)=self.output.as_mut(){if output.len().checked_add(chunk.len()).filter(|length|*length<=output.capacity()).is_none(){return Err(ValueError::new(ValueRefusalKind::InvariantViolated,"Semio native writer exceeded admitted output"))}output.extend_from_slice(chunk)}self.control.advance(chunk.len())?;}Ok(())}
 pub(crate) fn entities(&mut self,count:usize)->Result<(),ValueError>{let next=self.entities.checked_add(count).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"Semio native output entity count overflow"))?;if next>self.limits.max_rows{return Err(ValueError::new(ValueRefusalKind::OwnershipLimit,"Semio native output entities exceed caller row limit"))}self.entities=next;Ok(())}
 pub(crate) fn byte(&mut self,value:u8)->Result<(),ValueError>{self.bytes(&[value])}
 pub(crate) fn varint(&mut self,mut value:u64)->Result<(),ValueError>{let mut bytes=[0;10];let mut length=0;loop{bytes[length]=(value&127) as u8;value>>=7;if value!=0{bytes[length]|=128}length+=1;if value==0{break}}self.bytes(&bytes[..length])}
 pub(crate) fn string(&mut self,value:&str,encoding:SnapshotEncoding)->Result<(),ValueError>{match encoding{SnapshotEncoding::Binary=>{self.varint(u64::try_from(value.len()).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native text exceeds binary width"))?)?;self.bytes(value.as_bytes())},SnapshotEncoding::Text=>{const DIGITS:&[u8;16]=b"0123456789abcdef";for byte in value.bytes(){self.bytes(&[DIGITS[usize::from(byte>>4)],DIGITS[usize::from(byte&15)]])?;}Ok(())}}}
 pub(crate) fn number(&mut self,value:f64,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{return self.bytes(&value.to_le_bytes())}let mut word=Word{bytes:[0;384],length:0};std::fmt::write(&mut word,format_args!("{}",NativeF64(value))).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native scalar exceeds stack word"))?;self.bytes(&word.bytes[..word.length])}
 pub(crate) fn number32(&mut self,value:f32,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{return self.bytes(&value.to_le_bytes())}let mut word=Word{bytes:[0;384],length:0};std::fmt::write(&mut word,format_args!("{}",NativeF32(value))).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native binary32 scalar exceeds stack word"))?;self.bytes(&word.bytes[..word.length])}
 pub(crate) fn hex_number(&mut self,value:f64,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{return self.bytes(&value.to_le_bytes())}let mut word=Word{bytes:[0;384],length:0};std::fmt::write(&mut word,format_args!("{}",NativeF64(value))).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native scalar exceeds stack word"))?;let text=std::str::from_utf8(&word.bytes[..word.length]).map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"Semio numeric word is not UTF-8"))?;self.string(text,encoding)}
 pub(crate) fn integer(&mut self,value:u64,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{return self.varint(value)}let mut word=Word{bytes:[0;384],length:0};std::fmt::write(&mut word,format_args!("{value}")).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native integer exceeds stack word"))?;self.bytes(&word.bytes[..word.length])}
 pub(crate) fn fixed_u32(&mut self,value:u32,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{self.bytes(&value.to_le_bytes())}else{self.integer(u64::from(value),encoding)}}
 pub(crate) fn fixed_u64(&mut self,value:u64,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{self.bytes(&value.to_le_bytes())}else{self.integer(value,encoding)}}
 pub(crate) fn signed64(&mut self,value:i64,encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{return self.bytes(&value.to_le_bytes())}let mut word=Word{bytes:[0;384],length:0};std::fmt::write(&mut word,format_args!("{value}")).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native signed integer exceeds stack word"))?;self.bytes(&word.bytes[..word.length])}
 pub(crate) fn octets(&mut self,value:&[u8],encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Binary{self.varint(u64::try_from(value.len()).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native octet length exceeds width"))?)?;self.bytes(value)}else{const DIGITS:&[u8;16]=b"0123456789abcdef";for byte in value{self.bytes(&[DIGITS[usize::from(byte>>4)],DIGITS[usize::from(byte&15)]])?;}Ok(())}}
 pub(crate) fn binary_envelope(&mut self,token:&str)->Result<(),ValueError>{self.bytes(b"\x89SEM\r\n\x1a\n")?;self.bytes(&u32::try_from(token.len()).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native envelope width"))?.to_le_bytes())?;self.bytes(token.as_bytes())}
 pub(crate) fn text_record(&mut self,emit:impl Fn(&mut Writer<'_,'_,'_>)->Result<(),ValueError>)->Result<(),ValueError>{let limits=self.limits;let primitive_value_limit=self.primitive_value_limit;let size=self.control.scoped_stage(|control|{control.begin_stage(0)?;let mut measure=Writer{control,output:None,count:0,entities:0,limits,primitive_value_limit};emit(&mut measure)?;Ok::<usize,ValueError>(measure.count)})?;self.varint(u64::try_from(size).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio text record exceeds binary width"))?)?;let start=self.count;emit(self)?;if self.count.checked_sub(start)!=Some(size){return Err(ValueError::new(ValueRefusalKind::InvariantViolated,"Semio text record measured size differs"))}Ok(())}
 pub(crate) fn delimiter(&mut self,bytes:&[u8],encoding:SnapshotEncoding)->Result<(),ValueError>{if encoding==SnapshotEncoding::Text{self.bytes(bytes)?;}Ok(())}
 pub(crate) fn list<T>(&mut self,items:&[T],encoding:SnapshotEncoding,mut emit:impl FnMut(&mut Self,&T)->Result<(),ValueError>)->Result<(),ValueError>{self.entities(items.len())?;if encoding==SnapshotEncoding::Binary{self.varint(u64::try_from(items.len()).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native list exceeds binary width"))?)?;}else{self.bytes(b"[")?;}for(index,item)in items.iter().enumerate(){if index!=0{self.delimiter(b",",encoding)?;}emit(self,item)?;}self.delimiter(b"]",encoding)}
 pub(crate) fn reference(&mut self,target:&semio_framework_artifact_reference::ArtifactRef,encoding:SnapshotEncoding)->Result<(),ValueError>{self.entities(1)?;self.delimiter(b"[",encoding)?;for(index,field)in [&target.artifact_id,&target.dialect.artifact_kind,&target.dialect.standard,&target.dialect.subset].into_iter().enumerate(){if index!=0{self.delimiter(b",",encoding)?;}self.string(field,encoding)?;}self.delimiter(b"]",encoding)}
 pub(crate) fn child<T>(&mut self,child:&store::ArtifactChild<T>,encoding:SnapshotEncoding)->Result<(),ValueError>{self.delimiter(b"[",encoding)?;self.string(&child.child_id,encoding)?;self.delimiter(b",",encoding)?;self.reference(&child.target,encoding)?;self.delimiter(b"]",encoding)}
 pub(crate) fn optional_child<T>(&mut self,child:&Option<store::ArtifactChild<T>>,encoding:SnapshotEncoding)->Result<(),ValueError>{if let Some(child)=child{self.entities(1)?;if encoding==SnapshotEncoding::Binary{self.byte(1)?;}self.child(child,encoding)}else if encoding==SnapshotEncoding::Binary{self.byte(0)}else{self.bytes(b"[]")}}
 pub(crate) fn transform(&mut self,transform:&SemioTransform,encoding:SnapshotEncoding)->Result<(),ValueError>{self.delimiter(b"[",encoding)?;for(index,value)in [transform.translation.x,transform.translation.y,transform.translation.z,transform.rotation.x,transform.rotation.y,transform.rotation.z,transform.rotation.w,transform.scale.x,transform.scale.y,transform.scale.z].into_iter().enumerate(){if index!=0{self.delimiter(b",",encoding)?;}self.number(value,encoding)?;}self.delimiter(b"]",encoding)}
 pub(crate) fn pin(&mut self,pin:&store::LinkPin,encoding:SnapshotEncoding)->Result<(),ValueError>{match pin{store::LinkPin::Head=>if encoding==SnapshotEncoding::Binary{self.byte(0)}else{self.bytes(b"[h]")},store::LinkPin::Checkpoint{id}=>{if encoding==SnapshotEncoding::Binary{self.byte(1)?;}else{self.bytes(b"[c,")?;}self.string(id,encoding)?;self.delimiter(b"]",encoding)},store::LinkPin::Snapshot{blob}=>{self.entities(1)?;if encoding==SnapshotEncoding::Binary{self.byte(2)?;}else{self.bytes(b"[s,")?;}self.string(&blob.hash,encoding)?;self.delimiter(b",",encoding)?;self.integer(blob.size,encoding)?;self.delimiter(b",",encoding)?;self.string(&blob.media_type,encoding)?;self.delimiter(b"]",encoding)}}}
 pub(crate) fn link(&mut self,link:&store::ArtifactLink,encoding:SnapshotEncoding)->Result<(),ValueError>{self.delimiter(b"[",encoding)?;self.reference(&link.target,encoding)?;self.delimiter(b",",encoding)?;self.pin(&link.pin,encoding)?;self.delimiter(b",",encoding)?;self.string(&link.role,encoding)?;self.delimiter(b"]",encoding)}
}
struct Word{bytes:[u8;384],length:usize}
impl std::fmt::Write for Word{fn write_str(&mut self,value:&str)->std::fmt::Result{let end=self.length.checked_add(value.len()).filter(|end|*end<=self.bytes.len()).ok_or(std::fmt::Error)?;self.bytes[self.length..end].copy_from_slice(value.as_bytes());self.length=end;Ok(())}}
pub(crate) fn encode(encoding:SnapshotEncoding,text_preamble:&str,binary_token:&str,control:&mut SqliteSnapshotControl<'_>,fields:impl Fn(&mut Writer<'_,'_,'_>,SnapshotEncoding)->Result<(),ValueError>,native_owner:&mut semio_framework_os_kernel::NativeSnapshotEncodeOwner<'_, '_>)->Result<store::io::IoPayload,ValueError>{encode_fields(encoding,text_preamble,binary_token,control,false,fields,native_owner)}
/// 🎟️ Uses the caller's physical ledger after the owner completes explicit SQL admission.
pub(crate)fn encode_admitted(encoding:SnapshotEncoding,text_preamble:&str,binary_token:&str,control:&mut SqliteSnapshotControl<'_>,admit:impl FnOnce(&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>,fields:impl Fn(&mut Writer<'_,'_,'_>,SnapshotEncoding)->Result<(),ValueError>,native_owner:&mut semio_framework_os_kernel::NativeSnapshotEncodeOwner<'_, '_>)->Result<store::io::IoPayload,ValueError>{admit(control)?;encode_fields(encoding,text_preamble,binary_token,control,true,fields,native_owner)}
fn encode_fields(encoding:SnapshotEncoding,text_preamble:&str,binary_token:&str,control:&mut SqliteSnapshotControl<'_>,semantic_admitted:bool,fields:impl Fn(&mut Writer<'_,'_,'_>,SnapshotEncoding)->Result<(),ValueError>,native_owner:&mut semio_framework_os_kernel::NativeSnapshotEncodeOwner<'_, '_>)->Result<store::io::IoPayload,ValueError>{let native_control=native_owner.native();
 let limits=control.limits();let primitive_value_limit=(!semantic_admitted).then_some(limits.max_value_bytes);
 control.allocation_stage_native(SqliteSnapshotPhase::EncodeNative,|remaining,checkpoint|{
 let native_before=native_control.owned_bytes();
    let Some(allowance)=native_before.checked_add(remaining) else{return (Err(ValueError::new(ValueRefusalKind::OwnershipLimit,"native snapshot allowance overflow")),0)};let result=native_control.scoped_maximum(allowance,|native| {native.scoped_observer(&mut |event:semio_framework_value::native_encoding::NativeEncodeProgress|checkpoint(event.completed,event.total),|native|{

 let result=(||->Result<store::io::IoPayload,ValueError>{
 let envelope=|writer:&mut Writer<'_,'_,'_>|{if encoding==SnapshotEncoding::Text{writer.bytes(text_preamble.as_bytes())?;}else{writer.bytes(b"\x89SEM\r\n\x1a\n")?;writer.bytes(&u32::try_from(binary_token.len()).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"Semio native envelope width"))?.to_le_bytes())?;writer.bytes(binary_token.as_bytes())?;}fields(writer,encoding)};
 native.begin_stage(0)?;let mut measure=Writer{control:native,output:None,count:0,entities:0,limits,primitive_value_limit};envelope(&mut measure)?;let count=measure.count;
 native.begin_stage(count)?;let mut bytes=native.allocate_vec::<u8>(count)?;let mut writer=Writer{control:native,output:Some(&mut bytes),count:0,entities:0,limits,primitive_value_limit};envelope(&mut writer)?;if writer.count!=count||bytes.len()!=count{return Err(ValueError::new(ValueRefusalKind::InvariantViolated,"Semio native measured and emitted sizes differ"))}native.checkpoint()?;match encoding{SnapshotEncoding::Binary=>Ok(store::io::IoPayload::Binary(bytes)),SnapshotEncoding::Text=>Ok(store::io::IoPayload::Text(String::from_utf8(bytes).map_err(|_|ValueError::new(ValueRefusalKind::InvalidValue,"Semio native output is not UTF-8"))?))}
 })();
 result
    })});
    (result,native_control.owned_bytes().saturating_sub(native_before))
 })?
}

pub(crate) fn encode_snapshot(value:&crate::standards::v1::subsets::base::schema::snapshot::SemioSnapshot,encoding:SnapshotEncoding,control:&mut SqliteSnapshotControl<'_>,native_owner:&mut semio_framework_os_kernel::NativeSnapshotEncodeOwner<'_, '_>)->Result<store::io::IoPayload,ValueError>{encode_admitted(encoding,"semio stdio.semio.dsl v1\n","stdio.semio.pack v1",control,|control|value.admit_sqlite_values(control,SqliteSnapshotPhase::EncodeNative),|w,e|{w.entities(1)?;if e==SnapshotEncoding::Binary{w.byte(1)?;w.byte(crate::standards::v1::subsets::base::schema::snapshot::subset_ordinal(&value.subset))?;w.string(&value.schema,e)?}else{w.bytes(b"subset=")?;w.bytes(crate::standards::v1::subsets::base::schema::snapshot::subset_tag(&value.subset).as_bytes())?;w.bytes(b"\nschema=")?;w.string(&value.schema,e)?;w.byte(b'\n')?}subset(&value.subset,w,e)},native_owner)}
fn subset(value:&crate::standards::v1::subsets::base::schema::snapshot::SemioSubsetSnapshot,w:&mut Writer<'_,'_,'_>,e:SnapshotEncoding)->Result<(),ValueError>{
 use crate::standards::v1::subsets::base::schema::snapshot::SemioSubsetSnapshot as S;use crate::standards::v1::subsets as owners;
 let token=match value{S::Brep(_)=>"stdio.semio.brep.pack v1",S::Mesh(_)=>"stdio.semio.mesh.pack v1",S::Model(_)=>"stdio.semio.model.pack v1",S::Value(_)=>"stdio.semio.value.pack v1",S::Document(_)=>"s.stdio.semio.document.pack v1",S::Cad(_)=>"stdio.semio.cad.pack v1",S::Drawing(_)=>"stdio.semio.drawing.pack v1",S::Image(_)=>"s.stdio.semio.image.pack v1",S::Video(_)=>"stdio.semio.video.pack v1",S::Audio(_)=>"stdio.semio.audio.pack v1",S::Animation(_)=>"s.stdio.semio.animation.pack v1",S::Presentation(_)=>"s.stdio.semio.presentation.pack v1",S::Flow(_)=>"stdio.semio.flow.pack v1",S::Text(_)=>"s.stdio.semio.text.pack v1",S::Table(_)=>"s.stdio.semio.table.pack v1",S::Graph(_)=>"s.stdio.semio.graph.pack v1",S::Object(_)=>"stdio.semio.object.pack v1",S::Kit(_)=>"stdio.semio.kit.pack v1"};
 if e==SnapshotEncoding::Binary{w.binary_envelope(token)?}match value{
 S::Brep(v)=>owners::brep::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Mesh(v)=>owners::mesh::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Model(v)=>owners::model::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Value(v)=>owners::value::io::sqlite::snapshot::native_encoding::fields(v,w),
 S::Document(v)=>owners::document::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Cad(v)=>owners::cad::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Drawing(v)=>owners::drawing::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Image(v)=>owners::image::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Video(v)=>owners::video::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Audio(v)=>owners::audio::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Animation(v)=>owners::animation::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Presentation(v)=>owners::presentation::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Flow(v)=>owners::flow::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Text(v)=>owners::text::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Table(v)=>owners::table::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Graph(v)=>owners::graph::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Object(v)=>owners::object::io::sqlite::snapshot::native_encoding::fields(v,w,e),
 S::Kit(v)=>owners::kit::io::sqlite::snapshot::native_encoding::fields(v,w,e)
 }
}
