use crate::mesh::io::sqlite::snapshot::*;
use semio_framework_os_kernel::{ArtifactSqliteSnapshot,sqlite_snapshot::*};
#[test]
fn sqlite_snapshot_semio_mesh_controlled_native_output(){
 let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let mut snapshot=fixture();snapshot.textures[0].bytes=vec![255;f["nativeOutputBytes"].as_u64().unwrap() as usize];
 for encoding in [SnapshotEncoding::Binary,SnapshotEncoding::Text]{let actual=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();let expected=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&snapshot)),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<SemioMeshSnapshot as store::ArtifactDsl>::print_dsl(&snapshot))};assert!(actual==expected,"controlled mesh output differs from authored wire");
 for measured in [false,true]{let mut interior=false;let error=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |event|{let cancel=event.phase==SqliteSnapshotPhase::EncodeNative&&event.completed>=65536&&(if measured{event.total==0}else{event.total>65536&&event.completed<event.total});interior|=cancel;!cancel},SqliteDatabaseLimits::default())).unwrap_err();assert!(interior&&error.message.contains("cancel"),"{error}");}
 for limits in [SqliteDatabaseLimits{max_value_bytes:4096,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_file_bytes:4096,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_rows:0,..SqliteDatabaseLimits::default()}]{assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());}assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());}
}
fn fixture()->SemioMeshSnapshot{let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let positions=f["positions"].as_array().unwrap().iter().map(|p|SemioPoint3{x:p[0].as_f64().unwrap(),y:p[1].as_f64().unwrap(),z:p[2].as_f64().unwrap()}).collect::<Vec<_>>();SemioMeshSnapshot{schema:f["schema"].as_str().unwrap().into(),meshes:vec![SemioMesh{id:f["meshId"].as_str().unwrap().into(),primitives:[SemioTopology::Points,SemioTopology::Lines,SemioTopology::LineStrip,SemioTopology::Triangles,SemioTopology::TriangleStrip,SemioTopology::TriangleFan].into_iter().enumerate().map(|(ordinal,topology)|SemioPrimitive{id:format!("primitive-{ordinal}"),topology,positions:positions.clone(),normals:vec![SemioPoint3{x:0.0,y:0.0,z:1.0};3],uvs:vec![SemioUv{u:0.0,v:0.0},SemioUv{u:1.0,v:0.0},SemioUv{u:0.0,v:1.0}],colors:vec![SemioRgba{r:1.0,g:0.0,b:0.0,a:1.0},SemioRgba{r:0.0,g:1.0,b:0.0,a:0.5},SemioRgba{r:0.0,g:0.0,b:1.0,a:0.0}],indices:vec![0,1,2],material_id:if ordinal%2==0{Some("material".into())}else{None}}).collect()}],materials:vec![SemioMaterial{id:"material".into(),base_color:SemioRgba{r:0.25,g:0.5,b:0.75,a:1.0},metallic:0.25,roughness:0.75,base_color_texture:Some("texture".into()),metallic_roughness_texture:Some("texture".into()),normal_texture:Some("texture".into()),occlusion_texture:Some("texture".into()),emissive_texture:Some("texture".into()) }],textures:vec![SemioTexture{id:"texture".into(),mime:f["mime"].as_str().unwrap().into(),bytes:vec![0,1,255]}]}}
fn project(value:&SemioMeshSnapshot)->SqliteDatabase{value.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap()}
fn restore(db:&SqliteDatabase)->Result<SemioMeshSnapshot, semio_framework_value::ValueError>{SemioMeshSnapshot::from_sqlite_database(db,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default()))}
#[test]
fn sqlite_snapshot_semio_mesh_all_topologies_vertex_fields_pbr_textures_and_native_state(){let snapshot=fixture();let bytes=export_sqlite_database(&project(&snapshot),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let restored=restore(&import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!(restored,snapshot);assert_eq!(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&restored),<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&snapshot));assert_eq!(<SemioMeshSnapshot as store::ArtifactDsl>::print_dsl(&restored),<SemioMeshSnapshot as store::ArtifactDsl>::print_dsl(&snapshot));assert_eq!(restore(&project(&SemioMeshSnapshot::default())).unwrap(),SemioMeshSnapshot::default());}
#[test]
fn sqlite_snapshot_semio_mesh_rejects_reference_vertex_index_ordinal_and_budget_corruption(){let original=project(&fixture());for change in 0..5{let mut db=original.clone();match change{0=>db.table_mut("semio_mesh_primitive").unwrap().rows[0].values[5]=SqliteValue::Integer(999),1=>db.table_mut("semio_mesh_index").unwrap().rows[0].values[3]=SqliteValue::Integer(i64::from(u32::MAX)+1),2=>db.table_mut("semio_mesh_position").unwrap().rows[0].values[2]=SqliteValue::Integer(99),3=>db.table_mut("semio_mesh_index").unwrap().rows[0].values[1]=SqliteValue::Integer(999),_=>db.table_mut("semio_mesh_position").unwrap().rows[0].values[1]=SqliteValue::Integer(999)}assert!(restore(&db).is_err());}let limits=SqliteDatabaseLimits{max_rows:1,max_value_bytes:1,..SqliteDatabaseLimits::default()};assert!(fixture().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());assert!(SemioMeshSnapshot::from_sqlite_database(&original,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err());assert!(fixture().to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());}
#[test]
fn sqlite_snapshot_semio_mesh_independent_vertex_join_and_material_edit(){use std::io::Write;use std::process::{Command,Stdio};let bytes=export_sqlite_database(&project(&fixture()),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';const db=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(db.query('PRAGMA integrity_check').get().integrity_check!=='ok'||db.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');const rows=db.query('SELECT vertex_index,x,y,z FROM semio_mesh_index JOIN semio_mesh_position ON semio_mesh_index.primitive_id=semio_mesh_position.primitive_id AND semio_mesh_index.vertex_index=semio_mesh_position.ordinal WHERE semio_mesh_index.primitive_id=1 ORDER BY semio_mesh_index.ordinal').all();if(rows.length!==3||rows[1].x!==1||rows[2].y!==1)throw Error('vertices');db.query('UPDATE semio_mesh_material SET metallic=0.5,metallic_ieee754_bits=1056964608').run();await Bun.write(Bun.stdout,db.serialize());db.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let out=child.wait_with_output().unwrap();assert!(out.status.success(),"{}",String::from_utf8_lossy(&out.stderr));let restored=restore(&import_sqlite_database(&out.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();let mut expected=fixture();expected.materials[0].metallic=0.5;assert_eq!(restored,expected);}

#[test]
fn sqlite_snapshot_semio_mesh_bare_owner_capability_native_payload_bridge(){let snapshot=fixture();let payload=store::os_io::IoPayload::Binary(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&snapshot));let codec=store::ArtifactCodec::bare::<SemioMeshSnapshot,crate::standards::v1::subsets::mesh::schema::mutations::SemioMeshMutation>("s.stdio.semio.mesh");let provider=codec.snapshot_sqlite.expect("owner must publish typed SQLite capability");assert_eq!(provider.snapshot_type,Some(std::any::TypeId::of::<SemioMeshSnapshot>()));let dialect=store::os_io::ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"mesh".into()};let db=(provider.export)("s.stdio.semio.mesh",&dialect,&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;let bytes=export_sqlite_database(&db,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let db=import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let actual=(provider.import)("s.stdio.semio.mesh",&dialect,db,SnapshotEncoding::Binary,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;assert_eq!(actual,payload);}

#[test]
fn sqlite_snapshot_semio_mesh_owned_numeric_bits_independent_sqlite(){use std::io::Write;use std::process::{Command,Stdio};let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();for(index,bits)in f["float64Bits"].as_array().unwrap().iter().enumerate(){let bits=u64::from_str_radix(bits.as_str().unwrap(),16).unwrap();let bits32=u32::from_str_radix(f["float32Bits"][index].as_str().unwrap(),16).unwrap();let v=f64::from_bits(bits);let v32=f32::from_bits(bits32);let mut s=fixture();s.meshes[0].primitives[0].positions[0].x=v;s.materials[0].metallic=v32;let bytes=export_sqlite_database(&project(&s),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';const d=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(d.query('PRAGMA integrity_check').get().integrity_check!=='ok'||d.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');await Bun.write(Bun.stdout,d.serialize());d.close();";let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let out=child.wait_with_output().unwrap();assert!(out.status.success(),"{}",String::from_utf8_lossy(&out.stderr));let r=restore(&import_sqlite_database(&out.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap()).unwrap();assert_eq!((r.meshes[0].primitives[0].positions[0].x).to_bits(),bits);assert_eq!(r.materials[0].metallic.to_bits(),bits32);assert_eq!(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&r),<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&s));}}

#[test]
fn sqlite_snapshot_semio_mesh_typed_exact_subset_dialect_and_document_guard(){let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let snapshot=fixture();let database=project(&snapshot);let dialect=|v:&serde_json::Value|store::os_io::ArtifactDialect{artifact_kind:v["artifactKind"].as_str().unwrap().into(),standard:v["standard"].as_str().unwrap().into(),subset:v["subset"].as_str().unwrap().into()};let mut callback=|_|true;let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(&f["sqliteDialect"]),&database,&mut control).unwrap().diagnostics.is_empty());for invalid in f["invalidSqliteDialects"].as_array().unwrap(){assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(invalid),&database,&mut control).is_err());}let mut malformed=database;malformed.table_mut("semio_mesh_document").unwrap().rows[0].values[1]=SqliteValue::Text("other schema".into());assert!(snapshot.validate_sqlite_snapshot_subset(&dialect(&f["sqliteDialect"]),&malformed,&mut control).is_err());}

#[test]
fn sqlite_snapshot_semio_mesh_bounded_native_text_binary_admission() {
    let snapshot=fixture();let dialect=store::os_io::ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"mesh".into()};
    let provider=<SemioMeshSnapshot as store::ArtifactPack>::sqlite_snapshot_codec().unwrap();
    for encoding in [SnapshotEncoding::Binary,SnapshotEncoding::Text]{
        snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();
        let database=snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();
        let actual=(provider.import)("Semio native admission",&dialect,database,encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;
        let expected=match encoding{SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<SemioMeshSnapshot as store::ArtifactDsl>::print_dsl(&snapshot)),SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&snapshot))};assert_eq!(actual,expected);
        assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:16,..SqliteDatabaseLimits::default()})).is_err());
        assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());
    }
    let large= SemioMeshSnapshot{schema:"x".repeat(100000),..snapshot};
    assert!(large.preflight_sqlite_snapshot_encoding(SnapshotEncoding::Text,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:4096,..SqliteDatabaseLimits::default()})).is_err());
    assert!(large.preflight_sqlite_snapshot_encoding(SnapshotEncoding::Binary,&mut SqliteSnapshotControl::new(&mut |p|p.phase!=SqliteSnapshotPhase::EncodeNative||p.completed==0,SqliteDatabaseLimits::default())).is_err());
}

#[test]
fn sqlite_snapshot_semio_mesh_native_text_preserves_ieee_words(){use store::ArtifactDsl;let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();for word in f["float32Bits"].as_array().unwrap(){let bits=u32::from_str_radix(word.as_str().unwrap(),16).unwrap();let mut value=fixture();value.materials[0].metallic=f32::from_bits(bits);let actual=SemioMeshSnapshot::parse_dsl(&value.print_dsl()).unwrap();assert_eq!(actual.materials[0].metallic.to_bits(),bits);}for word in f["float64Bits"].as_array().unwrap(){let bits=u64::from_str_radix(word.as_str().unwrap(),16).unwrap();let mut value=fixture();value.meshes[0].primitives[0].positions[0].x=f64::from_bits(bits);let actual=SemioMeshSnapshot::parse_dsl(&value.print_dsl()).unwrap();assert_eq!(actual.meshes[0].primitives[0].positions[0].x.to_bits(),bits);}}
#[test]
fn sqlite_snapshot_semio_mesh_explicit_controlled_native_owner(){use store::{ArtifactPack,ArtifactDsl};let f:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let expected=fixture();for payload in [store::os_io::IoPayload::Binary(expected.encode_pack()),store::os_io::IoPayload::Text(expected.print_dsl())]{let actual=SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert_eq!(actual,expected);assert!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:f["nativeAdmission"]["tinyBudgetBytes"].as_u64().unwrap() as usize,..SqliteDatabaseLimits::default()})).is_err());assert!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:2,..SqliteDatabaseLimits::default()})).is_err());}let count=f["nativeAdmission"]["collectionItems"].as_u64().unwrap() as usize;let canceled=f["nativeAdmission"]["cancelAfter"].as_u64().unwrap() as usize;let value=SemioMeshSnapshot{schema:expected.schema,meshes:vec![SemioMesh{id:"mesh".into(),primitives:vec![SemioPrimitive{id:"points".into(),topology:SemioTopology::Points,positions:vec![SemioPoint3{x:-0.0,y:0.0,z:1.0};count],..SemioPrimitive::default()}]}],materials:Vec::new(),textures:Vec::new()};for payload in [store::os_io::IoPayload::Binary(value.encode_pack()),store::os_io::IoPayload::Text(value.print_dsl())]{let mut interior=false;let mut callback=|p:SqliteSnapshotProgress|{if p.phase==SqliteSnapshotPhase::DecodeNative&&p.total==count&&p.completed==canceled{interior=true;false}else{true}};assert!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default())).is_err());assert!(interior);}}

#[test]
fn sqlite_snapshot_semio_mesh_erased_preserves_code_admitted_intermediate_owner(){
 use std::io::Write;use std::process::{Command,Stdio};
 let neutral:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🧩️intermediate/🔣️.json")).unwrap();let input=&neutral["snapshot"];
 let mesh=&input["meshes"][0];let primitive=&mesh["primitives"][0];let material=&input["materials"][0];let snapshot=SemioMeshSnapshot{schema:input["schema"].as_str().unwrap().into(),meshes:vec![SemioMesh{id:mesh["id"].as_str().unwrap().into(),primitives:vec![SemioPrimitive{id:primitive["id"].as_str().unwrap().into(),topology:SemioTopology::Points,positions:Vec::new(),normals:Vec::new(),uvs:Vec::new(),colors:Vec::new(),indices:primitive["indices"].as_array().unwrap().iter().map(|value|u32::try_from(value.as_u64().unwrap()).unwrap()).collect(),material_id:Some(primitive["materialId"].as_str().unwrap().into())}]}],materials:vec![SemioMaterial{id:material["id"].as_str().unwrap().into(),base_color:SemioRgba{r:0.0,g:0.0,b:0.0,a:0.0},metallic:0.0,roughness:0.0,base_color_texture:Some(material["baseColorTexture"].as_str().unwrap().into()),metallic_roughness_texture:Some(material["metallicRoughnessTexture"].as_str().unwrap().into()),normal_texture:Some(material["normalTexture"].as_str().unwrap().into()),occlusion_texture:Some(material["occlusionTexture"].as_str().unwrap().into()),emissive_texture:Some(material["emissiveTexture"].as_str().unwrap().into())}],textures:Vec::new()};
 let provider=<SemioMeshSnapshot as store::ArtifactPack>::sqlite_snapshot_codec().unwrap();let dialect=store::os_io::ArtifactDialect{artifact_kind:"s.stdio.semio".into(),standard:"v1".into(),subset:"mesh".into()};
 for encoding in [SnapshotEncoding::Text,SnapshotEncoding::Binary]{
  let payload=match encoding{SnapshotEncoding::Text=>store::os_io::IoPayload::Text(<SemioMeshSnapshot as store::ArtifactDsl>::print_dsl(&snapshot)),SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(<SemioMeshSnapshot as store::ArtifactPack>::encode_pack(&snapshot))};
  assert_eq!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),snapshot);
  let db=(provider.export)("s.stdio.semio.mesh",&dialect,&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;assert_eq!(restore(&db).unwrap(),snapshot);
  let bytes=export_sqlite_database(&db,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';const f=JSON.parse(process.argv[1]);const db=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));try{if(db.query('PRAGMA integrity_check').get().integrity_check!=='ok'||db.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');if(JSON.stringify(db.query(f.query).all())!==JSON.stringify(f.expectedRows))throw Error('full query');await Bun.write(Bun.stdout,db.serialize());}finally{db.close();}";
  let text=serde_json::to_string(&neutral).unwrap();let mut child=Command::new("bun").args(["-e",script,&text]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));
  let db=import_sqlite_database(&output.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let result=(provider.import)("s.stdio.semio.mesh",&dialect,db,encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;
  assert_eq!(SemioMeshSnapshot::decode_sqlite_snapshot_native(&result,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),snapshot);
 }
}
