/** ⏪️ The original actor custody consumes independent grant currencies without a cold disposal branch. */
import {test,expect} from "bun:test";
import Ajv from "ajv";
import {Database} from "bun:sqlite";
import {readFileSync} from "node:fs";
import fixture from "../🧫️fixtures/🔣️.json";
import custodySchema from "../🧬️schema/🔣️.json";
test("original catalog constructor borrows independent authority and retains each actual receipt",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE constructor(phase TEXT,original TEXT,receipt INTEGER,installed INTEGER)");for(const row of fixture.constructorCustody)db.query("INSERT INTO constructor VALUES(?,?,?,?)").run(row.phase,row.original,Number(row.receipt),Number(row.installed));expect(db.query("SELECT original,installed FROM constructor WHERE phase IN ('sourceDenied','ticketsDenied') ORDER BY rowid").all()).toEqual([{original:"factory",installed:0},{original:"catalog",installed:0}]);expect(db.query("SELECT phase FROM constructor WHERE installed=1 AND original!='store'").all()).toEqual([]);expect(db.query("SELECT receipt FROM constructor WHERE phase='recipientPaid'").get()).toEqual({receipt:0});}finally{db.close()}
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");expect(source.includes("fn build_document_store_owners(grant: RetainedCloneGrant)")).toBe(true);expect(source.includes("fn take_constructor_receipt(")).toBe(true);expect(source.includes("constructor_receipts: std::mem::MaybeUninit<[Option<")).toBe(true);const ctor=source.slice(source.indexOf("pub async fn with_registry_on_bus("),source.indexOf("let genesis_mutations",source.indexOf("pub async fn with_registry_on_bus(")));expect(ctor.includes("install_unscheduled_catalog")).toBe(false);expect(source.includes("drive_store_constructor_unit_in_phase(grant,ArtifactStoreConstructorPhase::Preparation)")).toBe(true);expect(source.includes("drive_store_constructor_unit_in_phase(grant,ArtifactStoreConstructorPhase::Close)")).toBe(true);const child=readFileSync(new URL("../../../🌱️initialization/🏪️catalog/🦀️.rs",import.meta.url),"utf8");expect(child.includes("owners.admit_constructor(child)")).toBe(true);expect(child.includes("*self.original=Some(Err(original))")).toBe(true);const store=readFileSync(new URL("../../../../🏪️store/🦀️.rs",import.meta.url),"utf8");expect(store.includes("slot.prepare_step(source.as_ref()")).toBe(true);expect(store.includes("factory_retirement_tickets.slots[index].preparation_is_complete()")).toBe(true);expect(store.includes("returned_constructor_alias")).toBe(false);console.log("[DEBUG] SQLite preserves denied original factory/catalog custody and genuine outstanding constructor receipts under independent authority");
});
test("original Actor header transfers use independent policy and account native copy",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE header(phase TEXT,field TEXT)");for(const row of fixture.actorHeaderCustody)for(const field of row.headers)db.query("INSERT INTO header VALUES(?,?)").run(row.phase,field);expect(db.query("SELECT field FROM header WHERE phase='sessionRemoval' ORDER BY rowid").all()).toEqual([{field:"sessionCursor"},{field:"retiredFlag"}]);expect(db.query("SELECT field FROM header WHERE phase='commandAdmission' ORDER BY rowid").all()).toEqual([{field:"event"},{field:"commandSlot"}]);}finally{db.close()}
 const source=readFileSync(new URL("../🦀️.rs",import.meta.url),"utf8");const native=readFileSync(new URL("./🦀️.rs",import.meta.url),"utf8");expect(source.includes("fn session_transfer_copy_bytes")).toBe(true);expect(source.includes("fn session_removal_copy_bytes")).toBe(true);expect(source.includes("copied_bytes:demand.copy_bytes")).toBe(true);expect(native.includes("body.max(demand.copy_bytes)")).toBe(false);expect(native.includes("native_original_actor_grant()")).toBe(true);const toy=readFileSync(new URL("../../../🧪️tests/🧪️time-travel/🦀️.rs",import.meta.url),"utf8");expect(toy.includes("original_fixture_retirement_grant")).toBe(false);expect(toy.includes("advance_typed_operation_publication()")).toBe(false);expect(toy.includes("original_time_travel_fixture_caller()")).toBe(true);console.log("[DEBUG] SQLite declares exact native Session/cursor/flag and command headers; original positive authority comes from independent neutral policy");
});
test("original returned snapshot pump reserves parent headers and never drives a scalar reclamation loop",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE returned(phase TEXT,original TEXT,terminal INTEGER)");for(const row of fixture.snapshotReturnCustody)db.query("INSERT INTO returned VALUES(?,?,?)").run(row.phase,row.original,Number(row.terminal));expect(db.query("SELECT phase FROM returned WHERE terminal=1 AND original!='none'").all()).toEqual([]);expect(db.query("SELECT terminal FROM returned WHERE original='shell'").get()).toEqual({terminal:0});}finally{db.close()}
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");const pump=source.slice(source.indexOf("impl SnapshotReadReturnPump {"),source.indexOf("impl Drop for SnapshotReadReturnPump"));expect(pump.includes("maximum_copy_bytes:grant.maximum_copy_bytes-parent_copy")).toBe(true);expect(pump.includes("copied_bytes.checked_add(parent_copy)")).toBe(true);expect(source.includes("fn advance_snapshot_read_returns_one(&mut self,grant:RetainedCloneGrant)")).toBe(true);const reclaim=source.slice(source.indexOf("pub(crate) fn reclaim_document_snapshot_read_returns("),source.indexOf("fn snapshot_read_returns_terminal_is_empty("));expect(reclaim.includes(".drive(")).toBe(false);expect(reclaim.includes("for _")).toBe(false);console.log("[DEBUG] SQLite keeps original snapshot cursor shell pending until paid removal; actual pump forwards complete grants and receipts without scalar reclamation");
});
test("original child member close transports its full receipt and retains typed metadata",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE member(phase TEXT,entry TEXT,metadata TEXT,terminal INTEGER)");for(const row of fixture.childMemberCustody)db.query("INSERT INTO member VALUES(?,?,?,?)").run(row.phase,row.entry,row.metadata,Number(row.terminal));expect(db.query("SELECT phase FROM member WHERE terminal=1 AND (entry!='none' OR metadata!='none')").all()).toEqual([]);expect(db.query("SELECT terminal FROM member WHERE metadata='emptyCursor'").get()).toEqual({terminal:0});}finally{db.close()}
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");const member=source.slice(source.indexOf("impl<M: SpaceMember> ChildMemberRetirement<M>"),source.indexOf("impl<M> Drop for ChildMemberRetirement"));expect(source.includes("struct ChildMemberMetadata")).toBe(true);expect(member.includes("fn close_step(&mut self,grant:RetainedCloneGrant)")).toBe(true);expect(member.includes("member.close_owned_step(child)")).toBe(true);expect(member.includes("ControlledRetirement::new(original)")).toBe(true);expect(member.includes("SnapshotRetirementStep")).toBe(false);expect(member.includes("self.metadata.is_none()")).toBe(true);console.log("[DEBUG] SQLite declares original child entry metadata cursor custody beyond member terminal; production retains all original grant and receipt currencies");
});
test("original child snapshot handoff reserves its headers and closes original metadata fields",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE child(phase TEXT,snapshot TEXT,metadata TEXT,terminal INTEGER)");for(const row of fixture.childSnapshotCustody)db.query("INSERT INTO child VALUES(?,?,?,?)").run(row.phase,row.snapshot,row.metadata,Number(row.terminal));expect(db.query("SELECT phase FROM child WHERE terminal=1 AND (snapshot!='none' OR metadata!='none')").all()).toEqual([]);expect(db.query("SELECT metadata FROM child WHERE phase='leasePaid'").get()).toEqual({metadata:"member"});expect(db.query("SELECT metadata FROM child WHERE phase='metadataPaid'").get()).toEqual({metadata:"cursor"});}finally{db.close()}
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");const close=source.slice(source.indexOf("impl ChildContentRetirement {"),source.indexOf("impl Drop for ChildContentRetirement"));expect(source.includes("struct ChildContentMemberMetadata")).toBe(true);expect(close.includes("snapshot_handoff_copy_bytes")).toBe(true);expect(close.includes("maximum_copy_bytes:grant.maximum_copy_bytes-parent_copy")).toBe(true);expect(close.includes("ControlledRetirement::new(original)")).toBe(true);expect(close.includes("self.metadata_close.is_none()")).toBe(true);expect(close.includes("retained_identity_bytes")).toBe(false);console.log("[DEBUG] SQLite retains original child metadata after snapshot closure and requires paid original header handoff before separately funded native field retirement");
});
test("original child retirement quotes and receipts its native moved headers",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE header(phase TEXT,field TEXT)");for(const row of fixture.childHeaderCustody)for(const field of row.headers)db.query("INSERT INTO header VALUES(?,?)").run(row.phase,field);expect(db.query("SELECT phase FROM header WHERE field='rootArc' ORDER BY phase").all()).toEqual([{phase:"emptyRoot"},{phase:"rootAlias"}]);expect(db.query("SELECT field FROM header WHERE phase='entry' ORDER BY rowid").all()).toEqual([{field:"entryArc"},{field:"entryBody"},{field:"rootCount"},{field:"pendingEntry"}]);}finally{db.close()}
 const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");expect(source.includes("fn next_take_copy_bytes(")).toBe(true);const close=source.slice(source.indexOf("impl ChildContentRetirement {"),source.indexOf("impl Drop for ChildContentRetirement"));expect(close.includes("copy_bytes: self.view.next_take_copy_bytes()")).toBe(true);expect(close.includes("copied_bytes: demand.copy_bytes")).toBe(true);console.log("[DEBUG] SQLite declares exact original root/page/entry header custody independently of native pointer width; production quotes and pays each actual moved header");
});
test("original inactive member fields retire before subject removal and reopen",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE member(phase TEXT,view TEXT,typed TEXT,metadata TEXT,terminal INTEGER)");for(const row of fixture.memberCloseCustody)db.query("INSERT INTO member VALUES(?,?,?,?,?)").run(row.phase,row.view,row.typed,row.metadata,Number(row.terminal));expect(db.query("SELECT phase FROM member WHERE terminal=1 AND (typed!='none' OR metadata!='none')").all()).toEqual([]);expect(db.query("SELECT phase FROM member WHERE metadata='cursor'").all()).toEqual([{phase:"metadataPaid"}]);}finally{db.close()}
 const actor=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(actor.includes("metadata_close: Option<")).toBe(true);expect(actor.includes("member_subject_retirement_demands")).toBe(true);expect(actor.includes("member_subject_retirement_step(grant)")).toBe(true);const settle=actor.slice(actor.indexOf("fn settle_time_travel_owners("),actor.indexOf("async fn refresh_time_travel_children("));expect(settle.includes("self.time_travel.member.take()")).toBe(false);console.log("[DEBUG] SQLite retains original inactive member view/typed/metadata ownership until separately funded close phases permit subject removal and reopen");
});
test("original reviewed child view survives Begin and atomically returns on Discard",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE review(phase TEXT,visible TEXT,retained TEXT,displaced TEXT,base INTEGER)");for(const row of fixture.reviewViewCustody)db.query("INSERT INTO review VALUES(?,?,?,?,?)").run(row.phase,row.visible,row.retained,row.displaced,row.base);expect(db.query("SELECT retained FROM review WHERE phase='editing'").get()).toEqual({retained:"review"});expect(db.query("SELECT visible,retained,displaced FROM review WHERE phase='discarded'").get()).toEqual({visible:"review",retained:null,displaced:"draft"});expect(db.query("SELECT count(DISTINCT base) AS bases FROM review").get()).toEqual({bases:1});}finally{db.close();}
 const actor=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(actor.includes("review_children: Option<TimeTravelReviewChildren>")).toBe(true);expect(actor.includes("drive_original_review_children(grant)")).toBe(true);const publication=readFileSync(new URL("../../🎮️decision/🗑️discard/🦀️.rs",import.meta.url),"utf8");expect(publication.includes("review.base!=self.session.base")).toBe(true);expect(publication.includes("self.children.replace(review.view)")).toBe(true);expect(publication.includes("maximum_copy_bytes-self.view_copy_bytes")).toBe(true);expect(publication.includes("requires its admitted view producer")).toBe(false);console.log("[DEBUG] SQLite conserves the same original review view through captured/Editing/Discarded custody and keeps the displaced draft in its prepaid close slot");
});
test("original command receipt remains work until its genuine recipient takes custody",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);
 const db=new Database(":memory:");try{db.exec("CREATE TABLE receipt(phase TEXT,receipt INTEGER,work INTEGER,terminal INTEGER)");for(const row of fixture.receiptCustody)db.query("INSERT INTO receipt VALUES(?,?,?,?)").run(row.phase,Number(row.receipt),Number(row.work),Number(row.terminal));expect(db.query("SELECT phase FROM receipt WHERE receipt=1 AND (work=0 OR terminal=1)").all()).toEqual([]);expect(db.query("SELECT phase FROM receipt WHERE terminal=1").all()).toEqual([{phase:"recipientPaid"}]);}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");const work=source.slice(source.indexOf("pub fn has_pending_work("),source.indexOf("fn stage_time_travel_command("));expect(work).toContain("self.command_receipt.is_some()");const terminal=source.slice(source.indexOf("pub fn terminal_is_empty("),source.indexOf("fn next_problem("));expect(terminal).toContain("self.command_receipt.is_none()");console.log("[DEBUG] SQLite original receipt remains an actual owner frontier after physical emptiness until its recipient takes custody");
});
test("original Actor Discard publishes only after genuine typed Store and editor custody",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE publication(phase TEXT,session TEXT,editor TEXT,store TEXT,frames INTEGER)");for(const row of fixture.discardPublicationCustody)db.query("INSERT INTO publication VALUES(?,?,?,?,?)").run(row.phase,row.session,row.editor,row.store,row.frames);expect(db.query("SELECT phase FROM publication WHERE session!=editor OR editor!=store OR (session='retained' AND frames<5)").all()).toEqual([]);expect(db.query("SELECT phase FROM publication WHERE frames=5 AND session='live'").all()).toEqual([{phase:"effectsPreparing"}]);}finally{db.close();}
 const source=readFileSync(new URL("../../🎮️decision/🗑️discard/🦀️.rs",import.meta.url),"utf8");const publication=source.slice(source.indexOf("pub(super) fn publish_discard("),source.indexOf("pub(super) fn discard_effects_retirement_demands("));expect(publication.indexOf("prepare_discard_effects")).toBeLessThan(publication.indexOf("cursor.commit"));expect(publication.indexOf("cursor.commit")).toBeLessThan(publication.indexOf("commit_discard_effects"));expect(publication).toContain("maximum_copy_bytes<copied_bytes");expect(publication).toContain("content_revision_now()");expect(publication).not.toContain("session.apply");expect(publication).not.toContain(".settle(");console.log("[DEBUG] SQLite original three-owner custody remains atomic across five admitted frame boundaries");
});
test("actor time travel retains the incoming command before semantic reduction",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE custody(phase TEXT,original TEXT,applied INTEGER,mayReduce INTEGER)");for(const row of fixture.pendingCommandCustody){db.query("INSERT INTO custody VALUES(?,?,?,?)").run(row.phase,row.original,Number(row.applied),Number(row.mayReduce));}expect(db.query("SELECT phase FROM custody WHERE applied=1 AND original!='none'").all()).toEqual([]);expect(db.query("SELECT phase FROM custody WHERE mayReduce=1").all()).toEqual([{phase:"storeEffectsAdmitted"}]);expect(db.query("SELECT original FROM custody WHERE phase='received'").get()).toEqual({original:"event"});}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(source).toContain("pending_command: Option<");expect(source).toContain("TimeTravelActionOutcome::Pending");const entrance=source.slice(source.indexOf("async fn apply_time_travel_event("),source.indexOf("async fn perform_time_travel_effects("));expect(entrance).not.toContain("self.time_travel.session.apply(event)");expect(entrance).toContain("stage_time_travel_command");console.log("[DEBUG] Independent SQLite conserves received original Event until separately paid native semantic frame and Store effects precede terminal acknowledgement");
});
test("time travel original retirement separately admits copy birth release and depth",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE owners(position INTEGER PRIMARY KEY,owner TEXT)");fixture.owners.forEach((owner,index)=>db.query("INSERT INTO owners VALUES(?,?)").run(index,owner));for(const grant of fixture.grants){const result=db.query("SELECT CASE WHEN ?>0 AND ?>=? AND ?>=? AND ?>=? AND ?>=? THEN 1 ELSE 0 END AS admitted").get(grant.items,grant.copy,fixture.copyBytes,grant.capacity,fixture.capacityBytes,grant.release,fixture.releaseBytes,grant.depth,fixture.depth) as {admitted:number};expect(Boolean(result.admitted)).toBe(grant.accepted);expect((db.query("SELECT COUNT(*) AS count FROM owners").get() as {count:number}).count).toBe(4);}}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(source).toContain("fn time_travel_retirement_demands");expect(source).toContain("grant: RetainedCloneGrant");expect(source).not.toContain("op.retire_cold()");expect(source).not.toContain("retirements: VecDeque");console.log("[DEBUG] SQLite preserves original actor owners under every missing grant currency including exact empty backing release");
});
test("time travel close retains its original session in an admitted inline owner",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE session(owner TEXT PRIMARY KEY,custody TEXT)");db.query("INSERT INTO session VALUES(?,?)").run("drafts.pending.report.fault","live");for(const grant of fixture.sessionCustody){db.query("UPDATE session SET custody=CASE WHEN ?>0 AND ?>0 THEN 'retirement' ELSE 'live' END").run(grant.items,grant.depth);expect(db.query("SELECT custody FROM session").get()).toEqual({custody:grant.accepted?"retirement":"live"});expect((db.query("SELECT count(*) AS count FROM session").get() as {count:number}).count).toBe(1);}}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(source).toContain("session_retirement: Option<");expect(source).toContain("ControlledRetirement<TimeTravelSession>");expect(source).toContain("session_retired: bool");const retirement=readFileSync(new URL("../🦀️.rs",import.meta.url),"utf8");expect(retirement).toContain("fn session_retirement_demands");expect(retirement).toContain("fn session_retirement_step");expect(retirement).toContain("ControlledRetirement::new(original)");expect(retirement).toContain("self.session=original");console.log("[DEBUG] SQLite conserves original session custody across zero item and zero depth before inline admission");
});
test("time travel driver receives its caller funded full grant",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE grants(items INTEGER,copy INTEGER,capacity INTEGER,release INTEGER,depth INTEGER)");for(const grant of fixture.grants){db.query("INSERT INTO grants VALUES(?,?,?,?,?)").run(grant.items,grant.copy,grant.capacity,grant.release,grant.depth);}expect(db.query("SELECT items,copy,capacity,release,depth FROM grants ORDER BY rowid").all()).toEqual(fixture.grants.map(({items,copy,capacity,release,depth})=>({items,copy,capacity,release,depth})));}finally{db.close();}
 const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");expect(source).toContain("drive_time_travel_turn(&mut self, grant: RetainedCloneGrant, identity:");const start=source.indexOf("async fn drive_time_travel_turn(");const stop=source.indexOf("async fn prepare_time_travel_patch(",start);const driver=source.slice(start,stop);expect(driver).toContain("self.time_travel_retire_step(grant)");expect(driver).not.toContain("history_planning_retirement_grant(");console.log("[DEBUG] SQLite retains all five caller grant currencies without allocation quote credits in TimeTravel driver");
});
test("native config fixture retains null empty and owning selection fields",()=>{
 const db=new Database(":memory:");try{db.exec("CREATE TABLE selections(position INTEGER PRIMARY KEY,value TEXT)");fixture.configSelections.forEach((selection,index)=>db.query("INSERT INTO selections VALUES(?,?)").run(index,selection));expect(db.query("SELECT value FROM selections ORDER BY position").all().map((row)=> (row as {value:string|null}).value)).toEqual(fixture.configSelections);}finally{db.close();}
 const snapshot=readFileSync(new URL("../../../🧪️tests/🖥️test-app-mutations-config/🦀️.rs",import.meta.url),"utf8");expect(snapshot).toContain("artifact_retire_struct!(TestConfig { selected })");const leaf=readFileSync(new URL("../../../🧪️testing/🖥️test-app-mutations/🎚️config/🧬️mutations/📝️change-test-config/🦀️.rs",import.meta.url),"utf8");expect(leaf).toContain("artifact_retire_struct!(ChangeTestConfigSelection { selected })");const mutation=readFileSync(new URL("../../../🧪️testing/🖥️test-app-mutations/🎚️config/🧬️mutations/🦀️.rs",import.meta.url),"utf8");expect(mutation).toContain("RetireOwned for TestConfigMutation");expect(mutation).toContain("value.retirement_birth_bytes()");console.log("[DEBUG] Independent SQLite preserves native config null empty and Unicode NUL selection owners");
});

test("original member constructor retains refused error and records all actual currencies",()=>{expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE failure(phase TEXT,original TEXT,error TEXT,terminal INTEGER)");for(const row of fixture.constructorFailureCustody)db.query("INSERT INTO failure VALUES(?,?,?,?)").run(row.phase,row.original,row.error,Number(row.terminal));expect(db.query("SELECT phase FROM failure WHERE terminal=1 AND (original!='none' OR error!='none')").all()).toEqual([]);expect(db.query("SELECT error FROM failure WHERE phase='ticketRefused'").get()).toEqual({error:"retained"});}finally{db.close()}const source=readFileSync(new URL("../../../../🏪️store/🧩️composition/🚪️open/🏭️operation/🦀️.rs",import.meta.url),"utf8");expect(source.includes("constructor_error: ManuallyDrop<Option<ValueError>>")).toBe(true);expect(source.includes("owners.constructor_demands(grant.maximum_copy_bytes)")).toBe(true);expect(source.includes("maximum_release_bytes < demand.release_bytes")).toBe(true);expect(source.includes("artifact_retirement_admit_owned(&mut self.constructor_error")).toBe(true);const child=readFileSync(new URL("../../../🌱️initialization/🏪️catalog/🦀️.rs",import.meta.url),"utf8");expect(child.includes("refusal_close:ManuallyDrop<Option<Box<dyn store::ErasedSnapshotRetirement>>>")).toBe(true);expect(child.includes("artifact_retirement_admit_owned(&mut self.refusal")).toBe(true);expect(child.includes("owned catalog refusal has no controlled close")).toBe(false);console.log("[DEBUG] SQLite retains original refused constructor error through real controlled closure; actual caller carries all five currencies");});

test("original constructor semantic metadata moves preserve physical birth and release",()=>{expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE metadata(transfer TEXT,kind TEXT,copy INTEGER)");for(const row of fixture.constructorCopySemantics)db.query("INSERT INTO metadata VALUES(?,?,?)").run(row.transfer,row.kind,row.copyBytes);expect(db.query("SELECT SUM(copy) AS copied FROM metadata").get()).toEqual({copied:0});expect(db.query("SELECT COUNT(*) AS retained FROM metadata").get()).toEqual({retained:4});}finally{db.close()}const source=readFileSync(new URL("../../../../🏪️store/🦀️.rs",import.meta.url),"utf8");expect(source.includes("fn constructor_header_copy_bytes()->usize{0}")).toBe(true);expect(source.includes("pub fn installation_copy_bytes(&self)->usize{0}")).toBe(true);expect(source.includes("let copied_bytes=0;")).toBe(true);expect(source.includes("capacity_bytes:Self::source_birth_bytes")).toBe(false);console.log("[DEBUG] SQLite assigns zero semantic copy to original metadata moves while physical source/ticket allocation and release stay independently funded");});

test("original peer publication keeps supplied five-axis authority before physical birth",()=>{const base=new URL("../../../../🏪️store/👥️presence/",import.meta.url);const schema=JSON.parse(readFileSync(new URL("🧬️schema/🔣️.json",base),"utf8"));const law=JSON.parse(readFileSync(new URL("🧫️fixtures/🫴️publication.json",base),"utf8"));expect(new Ajv().compile({...schema,$ref:"#/$defs/OriginalPublicationLaw"})(law)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE authority(axis TEXT,amount INTEGER)");for(const [axis,amount]of Object.entries(law.grant))db.query("INSERT INTO authority VALUES(?,?)").run(axis,Number(amount));expect(db.query("SELECT amount FROM authority WHERE axis='maximumCopyBytes'").get()).toEqual({amount:0});expect(db.query("SELECT COUNT(*) AS axes FROM authority").get()).toEqual({axes:5});}finally{db.close()}const source=readFileSync(new URL("../../../../🏪️store/🦀️.rs",import.meta.url),"utf8");expect(source.includes("begin_peer_publication(&self, grant: RetainedCloneGrant)")).toBe(true);const producer=readFileSync(new URL("../../../../🏪️store/👥️presence/🚪️io/📬️publication/🦀️.rs",import.meta.url),"utf8");expect(producer.includes("original: &mut NativeSnapshotDecodeOwner")).toBe(true);expect(producer.includes("admit(original.remaining_grant(), progress, 2)?")).toBe(true);expect(producer.includes("copied_bytes: 0")).toBe(true);console.log("[DEBUG] SQLite retains independently declared five-axis publication authority with semantic metadata copy0 and separately funded original physical births");});

test("original displaced snapshot waits in fixed custody before granted retirement",()=>{expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE custody(phase TEXT,source TEXT,frame INTEGER)");for(const row of fixture.snapshotCustody)db.query("INSERT INTO custody VALUES(?,?,?)").run(row.phase,row.source,Number(row.frame));expect(db.query("SELECT source,frame FROM custody WHERE phase='denied'").get()).toEqual({source:"original",frame:0});expect(db.query("SELECT source,frame FROM custody WHERE phase='admitted'").get()).toEqual({source:"none",frame:1});}finally{db.close()}const source=readFileSync(new URL("../../🦀️.rs",import.meta.url),"utf8");const close=readFileSync(new URL("../🦀️.rs",import.meta.url),"utf8");expect(source.includes("snapshot_aliases: std::mem::ManuallyDrop<[Option<store::ArtifactDerivedSnapshot<P>>; 8]>")).toBe(true);expect(close.includes("admit_original_snapshot_alias")).toBe(true);console.log("[DEBUG] SQLite preserves original displaced snapshot custody through denial and one genuine granted frame admission");});

test("original codec refuses before decoding without independently supplied retained operation",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE codec(phase TEXT,pack TEXT,spr TEXT,ops TEXT,reduced INTEGER)");for(const row of fixture.codecCustody)db.query("INSERT INTO codec VALUES(?,?,?,?,?)").run(row.phase,row.pack,row.spr,row.ops,Number(row.reduced));expect(db.query("SELECT phase FROM codec WHERE reduced=1").all()).toEqual([]);expect(db.query("SELECT pack,spr,ops FROM codec WHERE phase='unfunded'").get()).toEqual({pack:"original",spr:"original",ops:"original"});}finally{db.close()}const source=readFileSync(new URL("../../../🦀️.rs",import.meta.url),"utf8");for(const [start,stop]of [["pub async fn artifact_app_apply_ops<","pub fn replay_envelopes_fault("],["pub async fn artifact_app_replay_envelopes<","pub type ArtifactCodecFuture"]]){const body=source.slice(source.indexOf(start),source.indexOf(stop,source.indexOf(start)));expect(body.includes("codec requires an original retained reduction operation")).toBe(true);expect(body.includes("parse_document_pack")).toBe(false);expect(body.includes("funded_bounded_artifact_store_owners")).toBe(false);expect(body.includes("close_owned_unscheduled")).toBe(false);}console.log("[DEBUG] SQLite preserves all borrowed codec sources on unfunded refusal before parsing or catalog birth; codec success remains pending a real retained caller");
});

test("original constructor cursor refuses shallow Drop before typed sources and errors are terminal",()=>{
 expect(new Ajv().compile(custodySchema)(fixture)).toBe(true);const db=new Database(":memory:");try{db.exec("CREATE TABLE cursor(original INTEGER,error INTEGER,ticket INTEGER,done INTEGER,mayDrop INTEGER)");for(const row of fixture.constructorCursorDrop)db.query("INSERT INTO cursor VALUES(?,?,?,?,?)").run(Number(row.original),Number(row.error),Number(row.ticket),Number(row.done),Number(row.mayDrop));expect(db.query("SELECT count(*) AS invalid FROM cursor WHERE mayDrop != (done=1 AND original=0 AND error=0 AND ticket=0)").get()).toEqual({invalid:0});}finally{db.close()}const source=readFileSync(new URL("../../../🌱️initialization/🏪️catalog/🦀️.rs",import.meta.url),"utf8");expect(source.includes("original:ManuallyDrop<Option<Result<")).toBe(true);expect(source.includes("refusal:ManuallyDrop<Option<ValueError>>")).toBe(true);expect(source.includes("refusal_close:ManuallyDrop<Option<Box<dyn store::ErasedSnapshotRetirement>>>")).toBe(true);expect(source.includes("Drop for OriginalCatalogConstructor")).toBe(true);console.log("[DEBUG] SQLite permits shallow constructor Drop only after original sources, owned errors and close tickets are genuinely terminal");
});
