/** 📖️ Handwritten persisted Playbook identity and exact composed child relations. */
import{ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteDocument,artifactSqliteText,artifactSqliteCheckpoint,type ArtifactSqliteOptions}from"../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import type{SqliteDatabase}from"../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import{parsePlaybookArtifact,type PlaybookArtifact}from"../../🟦️.ts";
import type{PlaybookSnapshot}from"../🟦️.ts";
/** 🏛️ Individual semantic contract: parent identity, narrative handle and flow handle. */
export const PLAYBOOK_SQLITE_SCHEMA=`CREATE TABLE playbook_document (id INTEGER PRIMARY KEY, schema_id TEXT NOT NULL, authored_id TEXT NOT NULL, version TEXT NOT NULL, title TEXT);
CREATE TABLE playbook_narrative_child (id INTEGER PRIMARY KEY REFERENCES playbook_document(id), child_id TEXT NOT NULL, artifact_id TEXT NOT NULL, artifact_kind TEXT NOT NULL, standard TEXT NOT NULL, subset TEXT NOT NULL);
CREATE TABLE playbook_flow_child (id INTEGER PRIMARY KEY REFERENCES playbook_document(id), child_id TEXT NOT NULL, artifact_id TEXT NOT NULL, artifact_kind TEXT NOT NULL, standard TEXT NOT NULL, subset TEXT NOT NULL);`;
/** 📤️ Projects persisted fields without invoking local child materialization. */
export async function playbookSnapshotToSqliteDatabase(snapshot:PlaybookSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{const p=await ArtifactSqliteProjection.create(PLAYBOOK_SQLITE_SCHEMA,options),s=parsePlaybookArtifact(snapshot);p.checkRowsAdditional(3);await p.insert("playbook_document",[s.schema,s.id,s.version,s.title]);const narrative=s.document,n=narrative.target,nd=n.dialect;await p.insert("playbook_narrative_child",[narrative.childId,n.artifactId,nd.artifactKind,nd.standard,nd.subset]);const flow=s.flow,f=flow.target,fd=f.dialect;await p.insert("playbook_flow_child",[flow.childId,f.artifactId,fd.artifactKind,fd.standard,fd.subset]);return p.finish();}
/** 📥️ Restores the two independently addressed children after complete schema/row validation. */
export async function playbookSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<PlaybookSnapshot>{const tables=await artifactSqliteTables(database,PLAYBOOK_SQLITE_SCHEMA,options),parent=artifactSqliteDocument(tables[0]!),narrative=artifactSqliteDocument(tables[1]!),flow=artifactSqliteDocument(tables[2]!);if(parent.values.length!==5||narrative.values.length!==6||flow.values.length!==6)throw Error("Playbook persisted column count differs");const snapshot={schema:artifactSqliteText(parent,1),id:artifactSqliteText(parent,2),version:artifactSqliteText(parent,3),title:parent.values[4]===null?null:artifactSqliteText(parent,4),document:{childId:artifactSqliteText(narrative,1),target:{artifactId:artifactSqliteText(narrative,2),dialect:{artifactKind:artifactSqliteText(narrative,3),standard:artifactSqliteText(narrative,4),subset:artifactSqliteText(narrative,5)}}},flow:{childId:artifactSqliteText(flow,1),target:{artifactId:artifactSqliteText(flow,2),dialect:{artifactKind:artifactSqliteText(flow,3),standard:artifactSqliteText(flow,4),subset:artifactSqliteText(flow,5)}}}};await artifactSqliteCheckpoint(options,"reconstructSnapshot",3,3);return snapshot;}
