type CadPresence {
  selectedObjectIds: [String!]! @state(class: PRESENCE)
  selectedNodeIds: [String!]! @state(class: PRESENCE)
  hoveredObjectId: String @state(class: PRESENCE)
  hoveredTargetObjectId: String @state(class: PRESENCE)
  hoveredTargetMode: String @state(class: PRESENCE)
  hoveredTargetId: Int @state(class: PRESENCE)
  activeObjectId: String @state(class: PRESENCE)
  componentSelectionMode: String! @state(class: PRESENCE)
  componentSelectionIds: [Int!]! @state(class: PRESENCE)
  componentSelectionTargetsMesh: Boolean! @state(class: PRESENCE)
  componentSelectionTargetsVertex: Boolean! @state(class: PRESENCE)
  componentSelectionTargetsEdge: Boolean! @state(class: PRESENCE)
  componentSelectionTargetsFace: Boolean! @state(class: PRESENCE)
  cameraPosition: [Float!]! @state(class: PRESENCE)
  cameraTarget: [Float!]! @state(class: PRESENCE)
  cameraZoom: Float! @state(class: PRESENCE)
  cameraFov: Float! @state(class: PRESENCE)
  activeUtilityId: String! @state(class: PRESENCE)
  engagementStep: String! @state(class: PRESENCE)
  engagementPane: String @state(class: PRESENCE)
}
