import {isAbsolute,relative,resolve} from "node:path";
import {CargoController} from "../🎛️control/🟦️.ts";
import {cargoManifestDocument,cargoPhysicalPath,type CargoDiscoveryOperation} from "../📁️physical/🟦️.ts";
import {discoverCargoWorkspaces,cargoWorkspaceMembers,type CargoWorkspaceScope} from "../🟦️.ts";
import type {CargoTomlTable} from "../📖️toml/🟦️.ts";

export type CargoPreparation=Readonly<{script:string;command:readonly string[]}>;
export type CargoOwnerPreparation=Readonly<{manifest:string;directory:string;script:string;command:readonly string[]}>;
export interface CargoPreparationExecution {execute(recipe:CargoOwnerPreparation,operation:CargoDiscoveryOperation):Promise<void>;}
class PreparationOwners {readonly reachable=new Set<string>();readonly pending:string[]=[];readonly recipes:CargoOwnerPreparation[]=[];}
const slash=(value:string):string=>value.replaceAll("\\","/");
const isTable=(value:unknown):value is CargoTomlTable=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const table=(value:unknown):CargoTomlTable=>{if(!isTable(value))throw Error("Cargo preparation requires an owned table");return value;};

/** 🧬️ Admits an exact owner recipe with literal arguments under caller control. */
export async function parseCargoPreparation(value:unknown,operation:CargoDiscoveryOperation):Promise<CargoPreparation>{
 const control=new CargoController(operation,operation.workspace),row=table(value);await control.step("preparation-admission","",0);for(const key in row){await control.step("preparation-field",key);if(Object.hasOwn(row,key)&&key!=="script"&&key!=="command")throw Error("Cargo preparation has an unknown field");}const script=row.script;if(typeof script!=="string"||!script||script.length>4096||isAbsolute(script)||/^[A-Za-z]:\//u.test(script)||script.includes("\\")||script.includes("\0")||script.split("/").at(-1)!=="📜️script.ts")throw Error("Cargo preparation script is invalid");if(!Array.isArray(row.command)||!row.command.length)throw Error("Cargo preparation requires literal arguments");await control.step("preparation-command-owner",script,1,64);const command:string[]=[];operation.workspace.partialRecords.push(command);for(const argument of row.command){if(typeof argument!=="string"||!argument||argument.length>4096)throw Error("Cargo preparation argument is invalid");for(const character of argument){await control.step("preparation-argument",script);if(character==="\0")throw Error("Cargo preparation argument contains NUL");}await control.step("preparation-argument-owner",script,1,16);command.push(argument);}await control.step("preparation-owner",script,1,64);const recipe={script,command};operation.workspace.partialRecords.push(recipe);await control.finish("preparation-admitted",script);return recipe;
}

/** 🔗️ Retains all dependency traversal and recipe owners before executing any preparation. */
export async function cargoOwnerPreparations(root:string,selected:CargoWorkspaceScope,operation:CargoDiscoveryOperation):Promise<readonly CargoOwnerPreparation[]>{
 const control=new CargoController(operation,operation.workspace);await control.step("preparation-workspace",selected.manifest,1,256);const owner=new PreparationOwners();operation.workspace.partialRecords.push(owner);owner.reachable.add(selected.directory);owner.pending.push(selected.directory);const scopes=await discoverCargoWorkspaces(root,operation);
 for(let index=0;index<owner.pending.length;index++){const directory=owner.pending[index]!;let scope:CargoWorkspaceScope|undefined;for(const candidate of scopes){await control.step("preparation-scope",directory);if(candidate.directory===directory){scope=candidate;break;}}if(!scope)throw Error("Cargo selected preparation scope is unknown");const scopeDocument=await cargoManifestDocument(root,scope.manifest,operation),authority=table(scopeDocument.workspace);
  for(const pkg of await cargoWorkspaceMembers(root,scope,operation)){const document=await cargoManifestDocument(root,pkg.manifest,operation);await control.step("preparation-groups-owner",pkg.manifest,1,64);const groups:CargoTomlTable[]=[document];operation.workspace.partialRecords.push(groups);if(document.target!==undefined){const targets=table(document.target);for(const target in targets){await control.step("preparation-target",pkg.manifest);if(Object.hasOwn(targets,target)){await control.step("preparation-target-owner",pkg.manifest,1,16);groups.push(table(targets[target]));}}}
   for(const group of groups)for(const kind of ["dependencies","dev-dependencies","build-dependencies"]){await control.step("preparation-dependency-group",pkg.manifest);if(group[kind]===undefined)continue;const dependencies=table(group[kind]);for(const alias in dependencies){await control.step("preparation-dependency",pkg.manifest);if(!Object.hasOwn(dependencies,alias))continue;const entry=dependencies[alias];if(!isTable(entry))continue;const inherited=entry.workspace!==undefined;if(inherited&&entry.workspace!==true)throw Error("Cargo dependency workspace selector is invalid");const dependency=inherited?table(authority.dependencies)[alias]:entry;if(!dependency)throw Error("Cargo inherited dependency is absent");if(!isTable(dependency)||dependency.path===undefined)continue;if(typeof dependency.path!=="string")throw Error("Cargo dependency path must be text");await control.step("preparation-dependency-path",pkg.manifest,dependency.path.length+1,32+dependency.path.length*2);const local=slash(relative(resolve(root),resolve(root,inherited?scope.directory:pkg.directory,dependency.path)));if(local.startsWith("../")||isAbsolute(local))throw Error("Cargo dependency escapes repository");let child:CargoWorkspaceScope|undefined;for(const candidate of scopes){await control.step("preparation-nearest-scope",pkg.manifest);if((candidate.directory==="."||local===candidate.directory||local.startsWith(candidate.directory+"/"))&&(!child||candidate.directory.length>child.directory.length))child=candidate;}if(child&&!owner.reachable.has(child.directory)){await control.step("preparation-reachable-owner",pkg.manifest,1,48);owner.reachable.add(child.directory);owner.pending.push(child.directory);}}}
   const packageRow=table(document.package),metadata=packageRow.metadata===undefined?undefined:table(packageRow.metadata),semio=metadata?.semio===undefined?undefined:table(metadata.semio);if(semio?.preparation===undefined)continue;const recipe=await parseCargoPreparation(semio.preparation,operation),identity=await cargoPhysicalPath(root,slash(relative(resolve(root),resolve(root,pkg.directory,recipe.script))),operation,"file"),within=slash(relative(resolve(root,scope.directory),identity.full));if(within.startsWith("../")||isAbsolute(within))throw Error("Cargo preparation leaves its defining scope");let duplicate=false;for(const previous of owner.recipes){await control.step("preparation-recipe-compare",pkg.manifest);if(previous.script!==identity.full||previous.command.length!==recipe.command.length)continue;let equal=true;for(let argument=0;argument<recipe.command.length;argument++){const current=recipe.command[argument]!,prior=previous.command[argument]!;if(current.length!==prior.length){equal=false;break;}for(let character=0;character<current.length;character++){await control.step("preparation-argument-compare",pkg.manifest);if(current[character]!==prior[character]){equal=false;break;}}if(!equal)break;}if(equal){duplicate=true;break;}}if(duplicate)continue;await control.step("preparation-recipe-owner",pkg.manifest,1,128+identity.full.length*2);owner.recipes.push({manifest:pkg.manifest,directory:pkg.directory,script:identity.full,command:recipe.command});
  }
 }await control.finish("preparation-plan-admitted",selected.manifest);return owner.recipes;
}

/** 🛠️ Executes only a complete admitted plan through the caller's owned subprocess port. */
export async function prepareCargoOwners(root:string,selected:CargoWorkspaceScope,operation:CargoDiscoveryOperation,execution:CargoPreparationExecution):Promise<void>{const control=new CargoController(operation,operation.workspace);for(const recipe of await cargoOwnerPreparations(root,selected,operation)){await control.step("preparation-execute",recipe.manifest);operation.workspace.state="prepared";await execution.execute(recipe,operation);control.check();}await control.finish("preparation-complete",selected.manifest);}
