//! 🧪️ Exact native receipt collection preserves original output backing and the same borrowed recipient.
use super::*;
use semio_framework_value::{RetainedCloneGrant,RetainedCloneProgress};
fn observe<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
#[test]
fn original_reactor_publication_receipts_preserve_all_five_tuples_and_same_recipient_once(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let original=&law["grant"];let grant=RetainedCloneGrant{maximum_items:original[0].as_u64().unwrap()as usize,maximum_copy_bytes:original[1].as_u64().unwrap()as usize,maximum_capacity_bytes:original[2].as_u64().unwrap()as usize,maximum_release_bytes:original[3].as_u64().unwrap()as usize,maximum_depth:64};let operation=semio_framework_job::OperationId(99210);let generation=semio_framework_job::Generation(1);let cancel=semio_framework_job::root_cancel_token();let(mut authority,birth)=semio_framework_job::JobPayloadAuthority::admit(operation,generation,grant).unwrap().unwrap();let mut sequence=0;let mut recipient=RetainedCloneProgress{copied_bytes:23,..Default::default()};let pointer=&mut recipient as*mut RetainedCloneProgress;let mut cx=semio_framework_job::StepContext::with_payload_authority(operation,generation,semio_framework_job::StepBudget::new(9,u64::MAX,grant),&cancel,semio_framework_job::logical_now_us,&mut sequence,&mut recipient,&authority).unwrap();let mut output=crate::plugin_runtime::PluginExchangeOutput::default();output.frames=vec![vec![83u8;41]];let page_pointer=output.frames[0].as_ptr();let rows=law["receipts"].as_array().unwrap();let receipt=|index:usize|{let p=&rows[index]["spent"];let progress=RetainedCloneProgress{copied_items:p[0].as_u64().unwrap()as usize,copied_bytes:p[1].as_u64().unwrap()as usize,retained_capacity_bytes:p[2].as_u64().unwrap()as usize,released_bytes:p[3].as_u64().unwrap()as usize};(RetainedCloneGrant{maximum_items:progress.copied_items,maximum_copy_bytes:progress.copied_bytes,maximum_capacity_bytes:progress.retained_capacity_bytes,maximum_release_bytes:progress.released_bytes,maximum_depth:64},progress)};
 let(g,p)=receipt(0);output.constructor_receipt=Some((crate::app::ArtifactStoreConstructorKind::Recipient,crate::app::ArtifactStoreConstructorPhase::Preparation,g,p));let(g,p)=receipt(1);output.preparation_receipt=Some((operation,g,p));output.history_command_receipt=Some(receipt(2));output.tool_run_receipt=Some(receipt(3));let(g,p)=receipt(4);output.retirement_receipt=Some((operation,g,p));
 let(result,heap)=observe(||collect_original_publication_receipts(&mut output,&mut cx));assert!(result.is_ok());assert_eq!(heap,(0,0));assert_eq!(output.frames[0].as_ptr(),page_pointer);let expected=&law["expected"];let spent=RetainedCloneProgress{copied_items:expected[0].as_u64().unwrap()as usize,copied_bytes:23+expected[1].as_u64().unwrap()as usize,retained_capacity_bytes:expected[2].as_u64().unwrap()as usize,released_bytes:expected[3].as_u64().unwrap()as usize};assert_eq!(cx.retained_progress(),spent);let(result,heap)=observe(||collect_original_publication_receipts(&mut output,&mut cx));assert!(result.is_ok());assert_eq!(heap,(0,0));assert_eq!(cx.retained_progress(),spent);assert_eq!(output.frames[0].as_ptr(),page_pointer);
 let remaining=cx.retained_grant();let bad=RetainedCloneGrant{maximum_depth:remaining.maximum_depth+1,..remaining};let actual=RetainedCloneProgress{copied_items:1,copied_bytes:41,..Default::default()};output.preparation_receipt=Some((operation,bad,actual));let(result,heap)=observe(||collect_original_publication_receipts(&mut output,&mut cx));let refused=match result{Err(refused)=>refused,Ok(())=>panic!("forged original depth must refuse")};assert_eq!(heap,(0,0));assert_eq!(refused.receipts.preparation,Some((operation,bad,actual)));assert_eq!(refused.error.kind,semio_framework_value::ValueRefusalKind::InvariantViolated);assert_eq!(cx.retained_progress().copied_bytes,spent.copied_bytes+41);assert_eq!(output.frames[0].as_ptr(),page_pointer);drop(cx);assert_eq!(&mut recipient as*mut _,pointer);let closed=authority.close_step(grant).unwrap().progress();assert_eq!(closed.released_bytes,birth.retained_capacity_bytes);drop(authority);eprintln!("[DEBUG] actual Reactor all5 original tuples total5/277/216/128 plus prior23 sameRecipient={pointer:p} samePage={page_pointer:p} collectedOnce heap0 forgedDepth retains exact tuple and actual41 receipt");
}
