cargo-features = ["trim-paths"]

[workspace]
resolver = "2"
members = [
    "🔨️modules/⌨️cli/📦️packages/🦀️rust",
    "🔨️modules/🌳️tree/📦️packages/🦀️rust",
    "🔨️modules/🎛️dashboard/📦️packages/🦀️rust",
    "🔨️modules/🎫️tickets/📦️packages/🦀️rust",
    "🔨️modules/🎯️goals/📦️packages/🦀️rust",
    "🔨️modules/🏃️test-runner/📦️packages/🦀️rust",
    "🔨️modules/🏠️workspace/📦️packages/🦀️rust",
    "🔨️modules/📊️metrics/📦️packages/🦀️rust",
    "🔨️modules/📐️model/📦️packages/🦀️rust",
    "🔨️modules/📜️statutes/📦️packages/🦀️rust",
    "🔨️modules/📝️todos/📦️packages/🦀️rust",
    "🔨️modules/📡️events/📦️packages/🦀️rust",
    "🔨️modules/🔌️mcp/📦️packages/🦀️rust",
    "🔨️modules/🔎️search/📦️packages/🦀️rust",
    "🔨️modules/🔗️graphql/📦️packages/🦀️rust",
    "🔨️modules/🖥️server/🎛️coordinator/📦️packages/🦀️rust",
    "🔨️modules/🗂️codebase/📦️packages/🦀️rust",
    "🔨️modules/🗣️languages/📦️packages/🦀️rust",
    "🔨️modules/🚚️move/📦️packages/🦀️rust",
    "🔨️modules/🧑️contributors/📦️packages/🦀️rust",
    "🔨️modules/🧩️providers/📦️packages/🦀️rust",
    "🔨️modules/🧪️test/📦️packages/🦀️rust",
    "🔨️modules/🧾️yaml/📦️packages/🦀️rust",
    "🔨️modules/🪝️hooks/📦️packages/🦀️rust",
    "🔨️modules/🪪️identity/📦️packages/🦀️rust",
]
exclude = ["**/🏅️standards/**", "**/🔮️oracles/**", "**/👽️guest/**"]

[workspace.metadata.semio.repository]
schema-version = 1
member-manifests = ["🔨️modules/**/📦️packages/🦀️rust/Cargo.toml"]
owner-manifests = []

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.95"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }

[profile.dev]
debug = false
incremental = false

[profile.dev.build-override]
opt-level = 3

[profile.dev.package.semio-framework-hash]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
codegen-units = 1
incremental = false

[profile.wasm-dev.package.semio-framework-replication]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "debuginfo"
incremental = false
trim-paths = "object"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "symbols"
incremental = false
trim-paths = "object"

[workspace.lints.rust]
future_incompatible = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cloned_instead_of_copied = "warn"
inefficient_to_string = "warn"
map_unwrap_or = "warn"
needless_pass_by_value = "warn"
semicolon_if_nothing_returned = "warn"
unnecessary_wraps = "warn"
redundant_clone = "warn"
