import {test,expect} from "bun:test";import {readFileSync} from "node:fs";import {resolve} from "node:path";
const root=resolve(import.meta.dir,"../../../../../../../..");
const board="🧰️framework/🛍️products/💻️os/🔨️modules/♾️infinite/🎲️board";
test("Board layout admits declared snapshot records before geometry",()=>{const schema=readFileSync(resolve(root,board,"🔌️ports/➡️directed/🧬️schema/📸️snapshot/🦀️.rs"),"utf8");expect(schema).not.toContain("Vec<std::collections::BTreeMap");expect(schema).toContain("Vec<BoardNodeSnapshot>");});

import Ajv from "ajv";import {hierarchy,tree} from "d3-hierarchy";import {forceSimulation,forceLink} from "d3-force";
const fixture=JSON.parse(readFileSync(resolve(root,board,"🧬️schema/💡️inferences/📐️layout/🧫️fixtures/🔣️.json"),"utf8"));
test("neutral snapshot schema agrees with independent Ajv",()=>{const schema=JSON.parse(readFileSync(resolve(root,board,"🔌️ports/➡️directed/🧬️schema/📸️snapshot/🔣️.json"),"utf8"));const validate=new Ajv({strict:false}).compile(schema);expect(validate(fixture.snapshot)).toBe(true);for(const value of fixture.refusals)expect(validate(value)).toBe(false);console.log("[DEBUG] Board snapshot independent Ajv positive1 refusal3");});
test("neutral tree and layered coordinates match independent d3 hierarchy",()=>{const rootNode=hierarchy({id:"r",children:[{id:"a"},{id:"b"}]});for(const [breadth,expected,dag]of [[48,fixture.treeExpected,false],[40,fixture.layeredExpected,true]] as const){tree().nodeSize([breadth,120])(rootNode);const actual=Object.fromEntries(rootNode.descendants().map(node=>[node.data.id,dag?[node.y-60,node.x]:[node.x,node.y-60]]));expect(actual).toEqual(expected);}console.log("[DEBUG] Board tree/layered exact shared neutral coordinates independently observed d3");});
test("neutral pinned force positions match independent d3 force",()=>{const nodes=structuredClone(fixture.pinned);const simulation=forceSimulation(nodes).force("link",forceLink([{source:"a",target:"b"}]).id((node:any)=>node.id)).stop();simulation.tick(10);expect(nodes.map((node:any)=>[node.x,node.y])).toEqual([[-10,0],[10,0]]);console.log("[DEBUG] Board pinned force exact independent d3 positions");});
test("pure layout owners expose typed facts without physical codecs",()=>{for(const file of ["⚛️force","🌳️hierarchical","🔁️redraw","🕸️layered"]){const body=readFileSync(resolve(root,board,"🧬️schema/💡️inferences/📐️layout",file,"🦀️.rs"),"utf8");expect(body).not.toMatch(/serde_json|from_json|to_json|as_object|as_array|\bValue\b/);}});

import "../board-boundary/🟦️.ts";

test("all typed options are independently admitted by their schema",()=>{const schema=JSON.parse(readFileSync(resolve(root,board,"🧬️schema/📐️layout/🔣️.json"),"utf8"));const ajv=new Ajv({strict:false});ajv.addSchema(schema);for(const [name,input]of [["ForceGraphLayoutOptions",{}],["HierarchicalTreeLayoutOptions",{direction:"upwards"}],["DagLayoutOptions",{orientation:"topBottom"}],["RedrawLayoutOptions",fixture.treeOptions]]as const){const validate=ajv.getSchema("board.layout.options#/$defs/"+name)!;expect(validate(input)).toBe(true);expect(validate({...input,unexpected:true})).toBe(false);}console.log("[DEBUG] Board options independent Ajv 4families positive/refusal");});

test("explicit optional absence and nonoptional null refusal share declared facets",()=>{const f=JSON.parse(readFileSync(resolve(root,board,"🧬️schema/💡️inferences/📐️layout/🧫️fixtures/🔣️nullable.json"),"utf8"));const ajv=new Ajv({strict:false});const snapshot=ajv.compile(JSON.parse(readFileSync(resolve(root,board,"🔌️ports/➡️directed/🧬️schema/📸️snapshot/🔣️.json"),"utf8")));ajv.addSchema(JSON.parse(readFileSync(resolve(root,board,"🧬️schema/📐️layout/🔣️.json"),"utf8")));const redraw=ajv.getSchema("board.layout.options#/$defs/RedrawLayoutOptions")!,dag=ajv.getSchema("board.layout.options#/$defs/DagLayoutOptions")!;expect(snapshot(f.optionalSnapshot)).toBe(true);expect(redraw(f.optionalRedraw)).toBe(true);for(const input of f.redrawRefusals)expect(redraw(input)).toBe(false);for(const input of f.dagRefusals)expect(dag(input)).toBe(false);console.log("[DEBUG] Board null policy independent Ajv2 optional/8 required refusals");});
