use super::*;
fn observe<T>(work:impl FnOnce()->T)->(T,usize,usize){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(work);(value,heap.requested_bytes,heap.released_bytes)}
fn origin(row:&serde_json::Value)->FlowInvocationOrigin{FlowInvocationOrigin{window_id:row["windowId"].as_str().unwrap().into(),window_kind_id:row["windowKindId"].as_str().unwrap().into(),neuron_id:row["neuronId"].as_str().unwrap().into(),extension_id:row["extensionId"].as_str().unwrap().into(),operator_id:row["operatorId"].as_str().unwrap().into(),node_hash:row["nodeHash"].as_u64().unwrap(),input_json:row["inputJson"].as_str().unwrap().into(),dependency_json:row["dependencyJson"].as_str().unwrap().into(),operator_version:row["operatorVersion"].as_str().unwrap().into(),outer_node_hash:None}}
#[test]
fn original_invocation_identity_preserves_actual_operation_and_paid_text(){
 let corpus:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();for row in corpus["identities"].as_array().unwrap(){let operation=row["operationId"].as_str().unwrap().parse::<u64>().unwrap();for copy in [1,3,64]{for cancel in [None,Some(0),Some(3),Some(9),Some(37)]{
  let(mut source,born,free)=observe(||FlowInvocationIdentity::new(operation));assert_eq!((born,free),(0,0));let(mut births,mut releases)=(0,0);for turn in 0..100{if cancel==Some(turn)||source.complete(){break}let d=source.demands();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:d.capacity_bytes,maximum_release_bytes:d.release_bytes,maximum_depth:d.depth};let(p,born,free)=observe(||source.step(RetainedCloneGrant{maximum_items:0,..grant}).unwrap());assert_eq!(p,Default::default());assert_eq!((born,free),(0,0));let(p,born,free)=observe(||source.step(grant).unwrap());assert!(p.fits(grant));assert_eq!((born,free),(p.retained_capacity_bytes,p.released_bytes));births+=born;releases+=free;assert_eq!(source.source(),operation);}if cancel.is_none(){assert!(source.complete());assert_eq!(source.text(),row["cancellationId"].as_str());}
  let(mut owner,born,free)=observe(||ControlledRetirement::new(source).unwrap_or_else(|_|unreachable!()));assert_eq!((born,free),(0,0));let mut idle=0;for _ in 0..100000{if owner.terminal_is_empty(){break}let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:owner.next_capacity_byte_demand(copy).unwrap(),maximum_release_bytes:owner.next_release_byte_demand().unwrap(),maximum_depth:owner.next_depth_demand().unwrap()};let(step,born,free)=observe(||owner.step(grant).unwrap());let p=step.progress();assert!(p.fits(grant));assert_eq!((born,free),(p.retained_capacity_bytes,p.released_bytes));births+=born;releases+=free;if p==Default::default(){idle+=1}else{idle=0}assert!(idle<64);}assert!(owner.terminal_is_empty());assert_eq!(births,releases);assert_eq!(observe(||drop(owner)),((),0,0));eprintln!("[DEBUG] Original invocation identity operation={operation} copy={copy} cancel={cancel:?} terminalDrop=0");
 }}}
}
#[test]
fn original_invocation_ledger_preserves_sources_and_allocation_receipts(){
 let corpus:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();
 for copy in [1,3,64]{for cancel in [None,Some(0),Some(1),Some(3)]{
  let((mut session,mut accepted),born,free)=observe(||(FlowEvalSession::new(),corpus["cases"].as_array().unwrap().iter().map(|row|FlowInvocationOriginLease::from_cold(origin(&row["source"]))).collect::<Vec<_>>()));let original=born-free;let pointers:Vec<_>=accepted.iter().map(|source|source.input_json.as_ptr()).collect();let(mut births,mut releases)=(0,0);let mut turn=0;
  while !accepted.is_empty(){if cancel==Some(turn){break}let mut idle=0;while session.invocation_origin_reserve_pending(){let d=session.next_invocation_origin_reserve_demands(copy).unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:d.capacity_bytes,maximum_release_bytes:d.release_bytes,maximum_depth:d.depth};let(p,born,free)=observe(||session.reserve_invocation_origin_step(RetainedCloneGrant{maximum_items:0,..grant}).unwrap());assert_eq!(p,Default::default());assert_eq!((born,free),(0,0));let(p,born,free)=observe(||session.reserve_invocation_origin_step(grant).unwrap());assert!(p.fits(grant));assert_eq!((born,free),(p.retained_capacity_bytes,p.released_bytes));births+=born;releases+=free;if p==Default::default(){idle+=1}else{idle=0}assert!(idle<64);}
   let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:0,maximum_release_bytes:0,maximum_depth:1};let original_source=accepted.pop().unwrap();let input=original_source.input_json.as_ptr();let(original_source,born,free)=observe(||{let(error,source)=session.retain_invocation_origin_step(original_source,RetainedCloneGrant{maximum_items:0,..grant}).err().unwrap();assert_eq!(error.retained_progress(),Default::default());source});assert_eq!((born,free),(0,0));assert_eq!(original_source.input_json.as_ptr(),input);let(p,born,free)=observe(||session.retain_invocation_origin_step(original_source,grant).unwrap_or_else(|_|unreachable!()));assert_eq!(p.copied_bytes,0);assert_eq!((born,free),(0,0));turn+=1;
  }
  for index in 0..session.state.invocation_origins.len(){assert!(pointers.contains(&session.invocation_origin_at(index).unwrap().input_json.as_ptr()));}
  session.begin_close();let mut idle=0;for _ in 0..100000{if session.terminal_is_empty(){break}let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:session.next_close_capacity_byte_demand(copy).unwrap(),maximum_release_bytes:session.next_close_release_byte_demand().unwrap(),maximum_depth:session.next_close_depth_demand().unwrap()};let(step,born,free)=observe(||session.close_step(grant));let p=step.progress();assert!(!matches!(step,semio_framework_job::InteractiveJobCloseStep::Refused{..}));assert!(p.fits(grant));assert_eq!((born,free),(p.retained_capacity_bytes,p.released_bytes));births+=born;releases+=free;if p==Default::default(){idle+=1}else{idle=0}assert!(idle<64);}assert!(session.terminal_is_empty());assert_eq!(observe(||drop(session)),((),0,0));let(mut owner,born,free)=observe(||ControlledRetirement::new(accepted).unwrap_or_else(|_|unreachable!()));assert_eq!((born,free),(0,0));while !owner.terminal_is_empty(){let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:owner.next_capacity_byte_demand(copy).unwrap(),maximum_release_bytes:owner.next_release_byte_demand().unwrap(),maximum_depth:owner.next_depth_demand().unwrap()};let(step,born,free)=observe(||owner.step(grant).unwrap());let p=step.progress();assert_eq!((born,free),(p.retained_capacity_bytes,p.released_bytes));births+=born;releases+=free;}assert_eq!(observe(||drop(owner)),((),0,0));assert_eq!(original+births,releases);eprintln!("[DEBUG] Original invocation copy={copy} cancel={cancel:?} sameSource=true terminalDrop=0");
 }}
}
