/** 📇️ Explicit native metadata admission into canonical PDF ownership. */
import type { PdfInfo,PdfEmbeddedFile,PdfOutputIntent,PdfEncryption,PdfViewerPreferences,PdfMarkInfo,PdfPageMode,PdfPageLayout } from "../../../../../🧬️schema/📸️snapshot/🟦️.ts";
import { record,array,text,integer,integers,boolean,pdfDictionaryFromNativeJson } from "../🟦️.ts";
import { pdfDateFromNativeJson } from "../📌️annotation/🟦️.ts";
const optionalText=(value:unknown)=>value==null?null:text(value);
const optionalInteger=(value:unknown)=>value==null?null:integer(value);
/** 🪟️ Admit one of the six explicitly declared page modes. */
export function pdfPageModeFromNativeJson(value:unknown):PdfPageMode{switch(text(value)){case "useNone":return "useNone";case "useOutlines":return "useOutlines";case "useThumbs":return "useThumbs";case "fullScreen":return "fullScreen";case "useOc":return "useOc";case "useAttachments":return "useAttachments";default:throw new Error("Unknown PDF page mode");}}
/** 📐️ Admit one of the six explicitly declared page layouts. */
export function pdfPageLayoutFromNativeJson(value:unknown):PdfPageLayout{switch(text(value)){case "singlePage":return "singlePage";case "oneColumn":return "oneColumn";case "twoColumnLeft":return "twoColumnLeft";case "twoColumnRight":return "twoColumnRight";case "twoPageLeft":return "twoPageLeft";case "twoPageRight":return "twoPageRight";default:throw new Error("Unknown PDF page layout");}}
/** 📇️ Admit all document info scalars, date references and COS extras. */
export function pdfInfoFromNativeJson(input:unknown):PdfInfo{const row=record(input);return {title:optionalText(row.title),author:optionalText(row.author),subject:optionalText(row.subject),keywords:optionalText(row.keywords),creator:optionalText(row.creator),producer:optionalText(row.producer),creationDate:row.creationDate==null?null:pdfDateFromNativeJson(row.creationDate),modificationDate:row.modificationDate==null?null:pdfDateFromNativeJson(row.modificationDate),trapped:optionalText(row.trapped),extra:pdfDictionaryFromNativeJson(row.extra??[])};}
/** 📎️ Admit complete attachment bytes and intrinsic dates. */
export function pdfEmbeddedFromNativeJson(input:unknown):PdfEmbeddedFile{const row=record(input);return {id:text(row.id),fileName:text(row.fileName),description:optionalText(row.description),mimeType:optionalText(row.mimeType),data:integers(row.data),creationDate:row.creationDate==null?null:pdfDateFromNativeJson(row.creationDate),modificationDate:row.modificationDate==null?null:pdfDateFromNativeJson(row.modificationDate),relationship:optionalText(row.relationship),listed:boolean(row.listed??false)};}
/** 🎯️ Admit explicit output-intent profile ownership and absence. */
export function pdfIntentFromNativeJson(input:unknown):PdfOutputIntent{const row=record(input);return {subtype:text(row.subtype),conditionIdentifier:text(row.conditionIdentifier),condition:optionalText(row.condition),registryName:optionalText(row.registryName),info:optionalText(row.info),profile:row.profile==null?null:integers(row.profile)};}
/** 🔒️ Admit all four named encryption domains and authored defaults. */
export function pdfEncryptionFromNativeJson(input:unknown):PdfEncryption{const row=record(input);const value=text(row.algorithm);let algorithm:PdfEncryption["algorithm"];switch(value){case "rc4_40":algorithm="rc4_40";break;case "rc4_128":algorithm="rc4_128";break;case "aes128":algorithm="aes128";break;case "aes256":algorithm="aes256";break;default:throw new Error("Unknown PDF encryption algorithm");}return {algorithm,permissions:integer(row.permissions??-1),userPassword:text(row.userPassword??""),ownerPassword:optionalText(row.ownerPassword),encryptMetadata:boolean(row.encryptMetadata??true)};}
/** 🪟️ Admit every viewer preference, print range and COS extra. */
export function pdfPreferencesFromNativeJson(input:unknown):PdfViewerPreferences{const row=record(input);return {hideToolbar:boolean(row.hideToolbar??false),hideMenubar:boolean(row.hideMenubar??false),hideWindowUi:boolean(row.hideWindowUi??false),fitWindow:boolean(row.fitWindow??false),centerWindow:boolean(row.centerWindow??false),displayDocTitle:boolean(row.displayDocTitle??false),nonFullScreenPageMode:row.nonFullScreenPageMode==null?null:pdfPageModeFromNativeJson(row.nonFullScreenPageMode),direction:optionalText(row.direction),viewArea:optionalText(row.viewArea),viewClip:optionalText(row.viewClip),printArea:optionalText(row.printArea),printClip:optionalText(row.printClip),printScaling:optionalText(row.printScaling),duplex:optionalText(row.duplex),pickTrayByPdfSize:boolean(row.pickTrayByPdfSize??false),printPageRange:array(row.printPageRange??[]).map(integer),numCopies:optionalInteger(row.numCopies),extra:pdfDictionaryFromNativeJson(row.extra??[])};}
/** 🏷️ Admit all three mark-info booleans. */
export function pdfMarkFromNativeJson(input:unknown):PdfMarkInfo{const row=record(input);return {marked:boolean(row.marked??false),userProperties:boolean(row.userProperties??false),suspects:boolean(row.suspects??false)};}
