/** 🔬 Rewrites the `family` and `options` of every catalogue kind the SCIENTIFIC agent owns, so each
 *  taxonomy leaf points at a real registered family with an option set no sibling leaf repeats.
 *  Run: `bun ./🏗️catalog-scientific.ts` from this ticket folder. Entries of other owners are untouched.
 */

//#region 🔖️Mapping
type Assignment = readonly [family: string, options: Readonly<Record<string, string | number | boolean>>];

const MAPPING: Readonly<Record<string, Assignment>> = {
  // §21 circular and genomic
  "21/circos-plot": ["sci-circos", { showTracks: true, showLinks: true }],
  "21/circular-genome-plot": ["sci-circos", { showTracks: true, showLinks: false }],
  "21/circular-synteny-plot": ["sci-circos", { showTracks: false, showLinks: true }],
  "21/ideogram": ["sci-ideogram", { showBands: true, showMarks: false, columnGap: 9 }],
  "21/karyotype-diagram": ["sci-ideogram", { showBands: true, showMarks: true, columnGap: 9 }],
  "21/chromosome-map": ["sci-ideogram", { showBands: false, showMarks: true, columnGap: 9 }],
  "21/chromosome-banding-diagram": ["sci-ideogram", { showBands: true, showMarks: false, columnGap: 6 }],
  "21/genome-track": ["sci-genome-track", { mode: "multi" }],
  "21/coverage-track": ["sci-genome-track", { mode: "coverage" }],
  "21/read-pileup": ["sci-genome-track", { mode: "pileup" }],
  "21/variant-track": ["sci-genome-track", { mode: "variant" }],
  "21/gene-structure-diagram": ["sci-genome-track", { mode: "gene-structure", laneHeight: 6 }],
  "21/exon-intron-diagram": ["sci-genome-track", { mode: "gene-structure", laneHeight: 9 }],
  "21/transcript-diagram": ["sci-genome-track", { mode: "transcript", laneHeight: 6 }],
  "21/gene-map": ["sci-genome-track", { mode: "transcript", laneHeight: 4 }],
  "21/protein-domain-diagram": ["sci-genome-track", { mode: "domain" }],
  "21/synteny-plot": ["sci-genome-track", { mode: "synteny" }],
  "21/manhattan-plot": ["sci-manhattan", { mode: "manhattan" }],
  "21/regional-association-plot": ["sci-manhattan", { mode: "regional" }],
  "21/sequence-logo": ["sci-seqlogo", { alphabetSize: 4 }],
  "21/motif-logo": ["sci-seqlogo", { alphabetSize: 20 }],
  "21/hi-c-contact-map": ["sci-contact-map", { logScale: true, bins: 24 }],
  "21/protein-interaction-network": ["sci-pathway", { mode: "interaction", nodeShape: "circle" }],
  "21/phylogenetic-network": ["sci-pathway", { mode: "interaction", nodeShape: "box" }],

  // §22 medical and biomedical
  "22/survival-curve": ["sci-survival", { mode: "kaplan-meier", confidence: false }],
  "22/kaplan-meier-plot": ["sci-survival", { mode: "kaplan-meier", confidence: true }],
  "22/cumulative-hazard-plot": ["sci-survival", { mode: "cumulative-hazard", confidence: true }],
  "22/dose-response-curve": ["sci-dose-response", { markEC: true }],
  "22/growth-chart": ["sci-growth-chart", {}],
  "22/nomogram": ["sci-nomogram", {}],
  "22/ma-plot": ["sci-scatter-diagnostic", { mode: "ma" }],
  "22/volcano-plot": ["sci-scatter-diagnostic", { mode: "volcano" }],
  "22/gene-expression-heatmap": ["sci-contact-map", { logScale: false, bins: 16 }],
  "22/pathway-diagram": ["sci-pathway", { mode: "pathway", nodeShape: "box" }],
  "22/metabolic-network-diagram": ["sci-pathway", { mode: "metabolic", nodeShape: "circle" }],
  "22/anatomical-schematic": ["sci-schematic", { leaders: "" }],
  "22/patient-timeline": ["sci-clinical-timeline", { laneHeight: 7 }],
  "22/clinical-event-timeline": ["sci-clinical-timeline", { laneHeight: 9 }],

  // §25 mathematical functions
  "25/cartesian-function-plot": ["sci-function", { mode: "cartesian" }],
  "25/parametric-curve": ["sci-function", { mode: "parametric", domain: "0,6.2832" }],
  "25/implicit-curve": ["sci-function", { mode: "implicit", expr: "\\SemioX*\\SemioX+\\SemioY*\\SemioY-2", domain: "-2,2", range: "-2,2" }],
  "25/piecewise-function": ["sci-function", { mode: "piecewise", pieces: "-3/0/-\\SemioX,0/3/\\SemioX*\\SemioX/3", domain: "-3,3", range: "-1,4" }],
  "25/polar-function": ["sci-function", { mode: "polar", expr: "1+0.6*cos(3*\\SemioT)", domain: "0,6.2832" }],
  "25/vector-valued-function-plot": ["sci-function", { mode: "vector-valued", glyphs: 5, domain: "0,6.2832" }],
  "25/complex-plane-plot": ["sci-complex", { mode: "complex-plane" }],
  "25/argand-diagram": ["sci-complex", { mode: "argand" }],
  "25/domain-coloring-plot": ["sci-complex", { mode: "domain-coloring", columns: 24, rows: 24 }],
  "25/riemann-surface-visualization": ["sci-complex", { mode: "riemann-surface", sheets: 3 }],
  "25/sequence-plot": ["sci-iteration", { mode: "sequence" }],
  "25/recurrence-plot": ["sci-iteration", { mode: "recurrence" }],
  "25/cobweb-plot": ["sci-iteration", { mode: "cobweb" }],
  "25/bifurcation-diagram": ["sci-iteration", { mode: "bifurcation" }],
  "25/phase-portrait": ["sci-dynamics", { mode: "phase-portrait" }],
  "25/phase-space-plot": ["sci-dynamics", { mode: "phase-space" }],
  "25/stability-diagram": ["sci-dynamics", { mode: "stability" }],
  "25/nullcline-plot": ["sci-dynamics", { mode: "nullcline" }],
  "25/slope-field": ["sci-dynamics", { mode: "direction-field", normalize: true }],
  "25/integral-area-visualization": ["sci-integral", { bars: false }],
  "25/riemann-sum-diagram": ["sci-integral", { bars: true, rule: "left" }],
  "25/taylor-approximation-plot": ["sci-approximation", { mode: "taylor", order: 5 }],
  "25/fourier-series-approximation": ["sci-approximation", { mode: "fourier", order: 6, expr: "\\SemioX<0?-1:1", domain: "-3.14,3.14", range: "-1.5,1.5" }],

  // §26 geometry
  "26/euclidean-construction": ["sci-construction", { mode: "coordinate", marks: true }],
  "26/triangle-diagram": ["sci-construction", { mode: "polygon", marks: true }],
  "26/polygon-diagram": ["sci-construction", { mode: "polygon", marks: false, points: "A/0/0,B/40/0,C/48/22,D/22/34,E/2/20" }],
  "26/circle-geometry": ["sci-construction", { mode: "circle" }],
  "26/angle-diagram": ["sci-construction", { mode: "polygon", marks: true, labels: false }],
  "26/similarity-diagram": ["sci-construction", { mode: "similarity" }],
  "26/congruence-diagram": ["sci-construction", { mode: "congruence" }],
  "26/coordinate-geometry": ["sci-construction", { mode: "coordinate", marks: false }],
  "26/tangent-construction": ["sci-construction", { mode: "tangent" }],
  "26/secant-construction": ["sci-construction", { mode: "secant" }],
  "26/conic-section": ["sci-conic", { kind: "ellipse", foci: true, directrix: true }],
  "26/ellipse": ["sci-conic", { kind: "ellipse", foci: true, directrix: false }],
  "26/parabola": ["sci-conic", { kind: "parabola", a: 0.5, directrix: true }],
  "26/hyperbola": ["sci-conic", { kind: "hyperbola", asymptotes: true }],
  "26/translation": ["sci-transform", { kind: "translation" }],
  "26/rotation": ["sci-transform", { kind: "rotation" }],
  "26/reflection": ["sci-transform", { kind: "reflection" }],
  "26/scaling": ["sci-transform", { kind: "scaling" }],
  "26/shear": ["sci-transform", { kind: "shear" }],
  "26/triangulation": ["sci-mesh", { mode: "triangulation" }],
  "26/mesh": ["sci-mesh", { mode: "mesh" }],
  "26/tessellation": ["sci-tiling", { kind: "hexagonal" }],
  "26/regular-tiling": ["sci-tiling", { kind: "square" }],
  "26/penrose-tiling": ["sci-tiling", { kind: "penrose", depth: 3, size: 4 }],
  "26/hyperbolic-tiling": ["sci-tiling", { kind: "hyperbolic", p: 5, q: 4, depth: 3 }],
  "26/fractal-geometry": ["sci-fractal", { kind: "koch", depth: 3, size: 60 }],
  "26/l-system-drawing": ["sci-fractal", { kind: "l-system", depth: 4, size: 90 }],

  // §29 three-dimensional
  "29/3d-scatter-plot": ["sci-3d", { mode: "scatter" }],
  "29/3d-line-plot": ["sci-3d", { mode: "line" }],
  "29/3d-trajectory": ["sci-3d", { mode: "trajectory" }],
  "29/3d-bar-chart": ["sci-3d", { mode: "bar" }],
  "29/3d-surface": ["sci-3d", { mode: "surface", columns: 12, rows: 12 }],
  "29/3d-wireframe": ["sci-3d", { mode: "wireframe", columns: 12, rows: 12 }],
  "29/3d-mesh": ["sci-3d", { mode: "mesh", columns: 8, rows: 8 }],
  "29/3d-contour": ["sci-3d", { mode: "contour", levels: 6 }],
  "29/3d-vector-field": ["sci-3d", { mode: "vector-field" }],
  "29/3d-quiver-plot": ["sci-3d", { mode: "quiver", zoom: 5 }],
  "29/point-cloud": ["sci-3d", { mode: "point-cloud" }],
  "29/voxel-visualization": ["sci-3d", { mode: "voxel", levels: 4 }],
  "29/volume-visualization": ["sci-3d", { mode: "volume", levels: 5 }],
  "29/isosurface-visualization": ["sci-3d", { mode: "isosurface", levels: 3 }],
  "29/3d-network": ["sci-3d", { mode: "network" }],
  "29/3d-tree": ["sci-3d", { mode: "tree" }],
  "29/3d-geometric-solid": ["sci-3d", { mode: "solid", solid: "octahedron" }],
  "29/polyhedron": ["sci-3d", { mode: "polyhedron", solid: "icosahedron" }],
  "29/exploded-3d-assembly": ["sci-3d", { mode: "exploded", solid: "cube", explode: 0.8 }],
  "29/axonometric-drawing": ["sci-3d", { mode: "solid", solid: "cube", projection: "axonometric", azimuth: 30, elevation: 20 }],
  "29/isometric-drawing": ["sci-3d", { mode: "solid", solid: "cube", projection: "isometric" }],
  "29/perspective-projection": ["sci-3d", { mode: "solid", solid: "cube", projection: "perspective", distance: 14 }],
  "29/orthographic-projection": ["sci-3d", { mode: "solid", solid: "cube", projection: "orthographic" }],
  "29/oblique-projection": ["sci-3d", { mode: "solid", solid: "cube", projection: "oblique" }],

  // §30 physics
  "30/free-body-diagram": ["sci-force", { mode: "free-body" }],
  "30/force-diagram": ["sci-force", { mode: "force", body: "point" }],
  "30/vector-decomposition-diagram": ["sci-force", { mode: "decomposition" }],
  "30/motion-diagram": ["sci-force", { mode: "motion" }],
  "30/position-time-graph": ["sci-kinematics", { mode: "position" }],
  "30/velocity-time-graph": ["sci-kinematics", { mode: "velocity" }],
  "30/acceleration-time-graph": ["sci-kinematics", { mode: "acceleration" }],
  "30/phase-space-diagram": ["sci-kinematics", { mode: "phase-space" }],
  "30/projectile-trajectory": ["sci-kinematics", { mode: "projectile" }],
  "30/orbital-trajectory": ["sci-kinematics", { mode: "orbital" }],
  "30/spacetime-diagram": ["sci-spacetime", { mode: "spacetime" }],
  "30/minkowski-diagram": ["sci-spacetime", { mode: "minkowski" }],
  "30/light-cone-diagram": ["sci-spacetime", { mode: "light-cone" }],
  "30/feynman-diagram": ["sci-feynman", { coils: 7 }],
  "30/energy-level-diagram": ["sci-levels", { mode: "energy-level" }],
  "30/potential-energy-diagram": ["sci-levels", { mode: "potential" }],
  "30/band-diagram": ["sci-levels", { mode: "band" }],
  "30/field-line-diagram": ["sci-fieldlines", { mode: "field-lines" }],
  "30/equipotential-map": ["sci-fieldlines", { mode: "equipotential" }],
  "30/wave-diagram": ["sci-wave", { mode: "travelling" }],
  "30/standing-wave-diagram": ["sci-wave", { mode: "standing" }],
  "30/interference-diagram": ["sci-wave", { mode: "interference" }],
  "30/diffraction-pattern": ["sci-wave", { mode: "diffraction" }],
  "30/polarization-diagram": ["sci-wave", { mode: "polarisation" }],
  "30/ray-diagram": ["sci-optics", { mode: "ray", objectDistance: 52 }],
  "30/lens-diagram": ["sci-optics", { mode: "lens", objectDistance: 40 }],
  "30/mirror-diagram": ["sci-optics", { mode: "mirror", objectDistance: 40 }],
  "30/poincare-sphere": ["sci-poincare", {}],

  // §31 electrical and electronics
  "31/circuit-schematic": ["sci-circuit", { mode: "schematic" }],
  "31/logic-circuit": ["sci-circuit", { mode: "logic", elements: "and/0/0/12/0/A,or/20/0/32/0/B,not/40/0/50/0/C,wire/12/0/20/0/" }],
  "31/logic-gate-diagram": ["sci-circuit", { mode: "logic", symbolSize: 5, elements: "nand/0/0/12/0/,xor/20/0/32/0/,not/40/0/50/0/" }],
  "31/ladder-diagram": ["sci-circuit", { mode: "ladder", elements: "wire/0/0/0/30/,wire/40/0/40/30/,resistor/0/24/40/24/K1,resistor/0/12/40/12/K2" }],
  "31/wiring-diagram": ["sci-circuit", { mode: "wiring", elements: "node/0/0/0/0/,wire/0/0/24/0/L1,node/24/0/24/0/,wire/24/0/24/18/L2,node/24/18/24/18/" }],
  "31/block-diagram": ["sci-circuit", { mode: "block", elements: "block/0/0/16/0/in,wire/16/0/24/0/,block/24/0/44/0/G,wire/44/0/52/0/,block/52/0/68/0/out" }],
  "31/signal-flow-graph": ["sci-circuit", { mode: "signal-flow", elements: "node/0/0/0/0/x,wire/0/0/20/0/a,node/20/0/20/0/y,wire/20/0/40/0/b,node/40/0/40/0/z" }],
  "31/transfer-function-block-diagram": ["sci-circuit", { mode: "block", symbolSize: 6, elements: "block/0/0/20/0/G(s),wire/20/0/32/0/,block/32/0/52/0/H(s)" }],
  "31/bode-plot": ["sci-control", { mode: "bode" }],
  "31/magnitude-plot": ["sci-control", { mode: "bode", decades: "-1,3" }],
  "31/phase-plot": ["sci-control", { mode: "bode-phase" }],
  "31/nyquist-plot": ["sci-control", { mode: "nyquist" }],
  "31/nichols-chart": ["sci-control", { mode: "nichols" }],
  "31/root-locus-plot": ["sci-control", { mode: "root-locus" }],
  "31/pole-zero-plot": ["sci-control", { mode: "pole-zero" }],
  "31/frequency-response-plot": ["sci-control", { mode: "bode", samples: 200 }],
  "31/impulse-response-plot": ["sci-control", { mode: "impulse" }],
  "31/step-response-plot": ["sci-control", { mode: "step" }],
  "31/smith-chart": ["sci-smith", {}],
  "31/constellation-diagram": ["sci-constellation", { mode: "constellation" }],
  "31/eye-diagram": ["sci-constellation", { mode: "eye" }],
  "31/oscilloscope-trace": ["sci-signal", { mode: "waveform", stems: false, samples: 96 }],
  "31/waveform-plot": ["sci-signal", { mode: "waveform", stems: true, samples: 48 }],

  // §32 signal processing
  "32/waveform": ["sci-signal", { mode: "waveform", stems: false }],
  "32/time-domain-signal": ["sci-signal", { mode: "waveform", stems: true }],
  "32/frequency-spectrum": ["sci-signal", { mode: "spectrum" }],
  "32/magnitude-spectrum": ["sci-signal", { mode: "magnitude", decibel: true }],
  "32/phase-spectrum": ["sci-signal", { mode: "phase" }],
  "32/power-spectral-density": ["sci-signal", { mode: "psd" }],
  "32/periodogram": ["sci-signal", { mode: "periodogram", decibel: true }],
  "32/cepstrum": ["sci-signal", { mode: "cepstrum" }],
  "32/autocorrelation-plot": ["sci-signal", { mode: "autocorrelation" }],
  "32/cross-correlation-plot": ["sci-signal", { mode: "cross-correlation" }],
  "32/coherence-plot": ["sci-signal", { mode: "coherence" }],
  "32/lag-plot": ["sci-signal", { mode: "lag" }],
  "32/filter-response-plot": ["sci-signal", { mode: "filter-response" }],
  "32/pole-zero-map": ["sci-control", { mode: "pole-zero", denominator: "1,0.8,4" }],
  "32/spectrogram": ["sci-timefreq", { mode: "spectrogram" }],
  "32/scalogram": ["sci-timefreq", { mode: "scalogram", scales: 12 }],
  "32/wavelet-plot": ["sci-timefreq", { mode: "scalogram", scales: 16 }],
  "32/waterfall-spectrum": ["sci-timefreq", { mode: "waterfall" }],
  "32/time-frequency-map": ["sci-timefreq", { mode: "time-frequency", window: 24, hop: 6 }],

  // §33 chemistry
  "33/chemical-structure": ["sci-molecule", { mode: "skeletal", bondGap: 0.7 }],
  "33/skeletal-formula": ["sci-molecule", { mode: "skeletal", bondGap: 0.95 }],
  "33/lewis-structure": ["sci-molecule", { mode: "lewis" }],
  "33/reaction-scheme": ["sci-molecule", { mode: "reaction", bondGap: 0.7 }],
  "33/reaction-mechanism": ["sci-molecule", { mode: "reaction", bondGap: 0.55 }],
  "33/reaction-coordinate-diagram": ["sci-energy-profile", { barriers: true, smooth: true }],
  "33/energy-profile": ["sci-energy-profile", { barriers: false, smooth: false }],
  "33/molecular-orbital-diagram": ["sci-orbital", { mode: "molecular-orbital" }],
  "33/electron-configuration-diagram": ["sci-orbital", { mode: "configuration" }],
  "33/orbital-visualization": ["sci-orbital", { mode: "orbital", lobes: 4 }],
  "33/crystal-structure": ["sci-crystal", { lattice: "face-centred" }],
  "33/unit-cell-diagram": ["sci-crystal", { lattice: "body-centred" }],
  "33/phase-diagram": ["sci-phase-diagram", { mode: "unary" }],
  "33/ternary-phase-diagram": ["sci-phase-diagram", { mode: "ternary", points: "0.2/0.5/x,0.6/0.2/y,0.3/0.3/z" }],
  "33/pourbaix-diagram": ["sci-electrochem", { mode: "pourbaix" }],
  "33/frost-diagram": ["sci-electrochem", { mode: "frost" }],
  "33/latimer-diagram": ["sci-electrochem", { mode: "latimer" }],
  "33/nmr-spectrum": ["sci-spectrum-peaks", { kind: "nmr", reversed: true }],
  "33/ir-spectrum": ["sci-spectrum-peaks", { kind: "ir", reversed: true, domain: "400,4000", peaks: "1710/0.9/40/C=O,2950/0.6/60/C-H,1450/0.4/30/,1100/0.7/25/C-O" }],
  "33/mass-spectrum": ["sci-spectrum-peaks", { kind: "ms", reversed: false, domain: "0,200", peaks: "43/100/1/,91/62/1/,105/38/1/,150/22/1/M" }],
  "33/uv-vis-spectrum": ["sci-spectrum-peaks", { kind: "uv-vis", reversed: false, domain: "200,700", peaks: "270/0.9/24/,340/0.5/30/,430/0.2/40/" }],
  "33/chromatogram": ["sci-spectrum-peaks", { kind: "chromatogram", reversed: false, domain: "0,20", peaks: "3.2/0.6/0.12/,5.8/1/0.14/,8.4/0.35/0.18/,12.6/0.7/0.2/" }],

  // §34 biology and ecology
  "34/cell-diagram": ["sci-schematic", { shapes: "ellipse/22/18/12/9/nucleus,ellipse/12/10/6/4/mito,ellipse/34/22/7/4/golgi,rounded/32/9/8/4/ER" }],
  "34/anatomical-diagram": ["sci-schematic", { outline: "" }],
  "34/biological-pathway": ["sci-pathway", { mode: "pathway", unit: 1 }],
  "34/food-web": ["sci-pathway", { mode: "food-web", nodeShape: "circle" }],
  "34/food-chain": ["sci-pathway", { mode: "food-web", nodeShape: "box" }],
  "34/ecological-network": ["sci-pathway", { mode: "food-web", nodeShape: "circle", unit: 1.1 }],
  "34/pedigree": ["sci-pedigree", {}],
  "34/punnett-square": ["sci-punnett", {}],
  "34/life-cycle-diagram": ["sci-lifecycle", {}],
  "34/population-growth-curve": ["sci-population", { mode: "growth" }],
  "34/predator-prey-phase-plot": ["sci-population", { mode: "phase" }],
  "34/species-abundance-plot": ["sci-population", { mode: "abundance" }],
  "34/rarefaction-curve": ["sci-population", { mode: "rarefaction" }],
  "34/ecological-niche-plot": ["sci-population", { mode: "niche" }],

  // §35 earth science diagram kinds
  "35/skew-t-log-p-diagram": ["sci-skewt", { mode: "skew-t", skew: 45 }],
  "35/tephigram": ["sci-skewt", { mode: "tephigram", skew: 30 }],
  "35/meteogram": ["sci-climate-series", { mode: "meteogram" }],
  "35/climate-stripe": ["sci-climate-series", { mode: "stripes" }],
  "35/climate-anomaly-chart": ["sci-climate-series", { mode: "anomaly" }],
  "35/climograph": ["sci-climograph", { mode: "climograph", tempScale: 1.6 }],
  "35/walter-lieth-climate-diagram": ["sci-climograph", { mode: "climograph", tempScale: 2 }],
  "35/hydrograph": ["sci-climograph", { mode: "hydrograph" }],
  "35/hyetograph": ["sci-climograph", { mode: "hyetograph" }],
  "35/river-profile": ["sci-geo-section", { mode: "river-profile" }],
  "35/geological-cross-section": ["sci-geo-section", { mode: "cross-section" }],
  "35/stratigraphic-column": ["sci-geo-section", { mode: "stratigraphic-column" }],
  "35/seismic-section": ["sci-geo-section", { mode: "seismic", traces: 14 }],
  "35/seismogram": ["sci-geo-section", { mode: "seismogram" }],

  // §36 structural analysis kinds
  "36/beam-diagram": ["sci-beam", { mode: "beam" }],
  "36/shear-force-diagram": ["sci-beam", { mode: "shear" }],
  "36/bending-moment-diagram": ["sci-beam", { mode: "moment" }],
  "36/stress-strain-curve": ["sci-material", { modulus: true }],
  "36/mohrs-circle": ["sci-mohr", { principal: true }],
  "36/truss-diagram": ["sci-truss", { mode: "truss" }],
  "36/frame-diagram": ["sci-truss", { mode: "frame" }],
  "36/finite-element-mesh": ["sci-truss", { mode: "mesh", columns: 8, rows: 5 }],
  "36/cfd-mesh": ["sci-truss", { mode: "mesh", columns: 12, rows: 8 }],
  "36/engineering-drawing": ["sci-dimensioned", { hatch: false }],
  "36/dimensioned-drawing": ["sci-dimensioned", { hatch: true }],

  // §38 mathematical and abstract diagrams
  "38/commutative-diagram": ["sci-abstract-diagram", { mode: "commutative", nodeShape: "none", unit: 18 }],
  "38/category-theory-diagram": ["sci-abstract-diagram", { mode: "commutative", nodeShape: "none", unit: 22 }],
  "38/string-diagram": ["sci-abstract-diagram", { mode: "string", nodeShape: "box", edges: "a/c/wire/,b/d/wire/,a/b/wire/" }],
  "38/penrose-graphical-notation": ["sci-abstract-diagram", { mode: "tensor", nodeShape: "circle", edges: "a/b/leg/,a/c/leg/,b/d/leg/" }],
  "38/tensor-network-diagram": ["sci-abstract-diagram", { mode: "tensor", nodeShape: "box", edges: "a/b/leg/,c/d/leg/,a/c/leg/,b/d/leg/" }],
  "38/hasse-diagram": ["sci-abstract-diagram", { mode: "hasse", nodeShape: "circle", edges: "c/a/order/,c/b/order/,a/d/order/,b/d/order/" }],
  "38/lattice-diagram": ["sci-abstract-diagram", { mode: "hasse", nodeShape: "none", edges: "c/a/order/,c/b/order/,a/d/order/,b/d/order/" }],
  "38/group-lattice": ["sci-abstract-diagram", { mode: "hasse", nodeShape: "box", edges: "c/a/order/,c/b/order/,a/d/order/,b/d/order/" }],
  "38/cayley-graph": ["sci-abstract-diagram", { mode: "cayley", nodeShape: "circle", edges: "a/b/arrow/r,b/d/arrow/r,d/c/arrow/r,c/a/arrow/r" }],
  "38/coxeter-diagram": ["sci-abstract-diagram", { mode: "dynkin", nodeShape: "circle", unit: 14, nodes: "a/0/0/,b/1/0/,c/2/0/,d/3/0/", edges: "a/b/order/4,b/c/order/3,c/d/order/3" }],
  "38/dynkin-diagram": ["sci-abstract-diagram", { mode: "dynkin", nodeShape: "circle", unit: 18, nodes: "a/0/0/,b/1/0/,c/2/0/,d/3/0/", edges: "a/b/double/,b/c/order/,c/d/order/" }],
  "38/proof-tree": ["sci-abstract-diagram", { mode: "proof", nodeShape: "none", edges: "c/a/order/,d/a/order/,a/b/order/" }],
  "38/inference-tree": ["sci-abstract-diagram", { mode: "proof", nodeShape: "box", edges: "c/a/order/,d/a/order/,a/b/order/" }],
  "38/rewrite-diagram": ["sci-abstract-diagram", { mode: "rewrite", nodeShape: "box", edges: "a/b/double/,b/d/double/,a/c/dashed/" }],
  "38/logic-diagram": ["sci-abstract-diagram", { mode: "commutative", nodeShape: "box", unit: 18 }],
  "38/young-diagram": ["sci-grid-diagram", { mode: "young", partition: "4,3,1" }],
  "38/karnaugh-map": ["sci-grid-diagram", { mode: "karnaugh", rowLabels: "00,01,11,10", columnLabels: "00,01,11,10", cells: "1/1/0,1/2/1,1/3/1,1/4/0,2/1/1,2/2/1,2/3/0,2/4/0,3/1/0,3/2/1,3/3/1,3/4/1,4/1/1,4/2/0,4/3/0,4/4/1" }],
  "38/truth-table": ["sci-grid-diagram", { mode: "truth-table", rowLabels: "0,1", columnLabels: "0,1", cells: "1/1/0,1/2/1,2/1/1,2/2/0" }],
  "38/cayley-table-visualization": ["sci-grid-diagram", { mode: "cayley-table", rowLabels: "e,a,b", columnLabels: "e,a,b", cells: "1/1/e,1/2/a,1/3/b,2/1/a,2/2/b,2/3/e,3/1/b,3/2/e,3/3/a" }],
  "38/knot-diagram": ["sci-braid", { mode: "knot" }],
  "38/braid-diagram": ["sci-braid", { mode: "braid" }],
  "38/set-diagram": ["sci-set", { mode: "venn", labels: false }],

  // §39 set and overlap
  "39/venn-diagram": ["sci-set", { mode: "venn", labels: true }],
  "39/euler-diagram": ["sci-set", { mode: "euler" }],
  "39/area-proportional-venn-diagram": ["sci-set", { mode: "area-proportional" }],
  "39/multi-set-venn-diagram": ["sci-set", { mode: "venn", sets: "A/38,B/26,C/17,D/12" }],
  "39/upset-plot": ["sci-upset", { mode: "upset", cell: 5 }],
  "39/combination-matrix": ["sci-upset", { mode: "combination-matrix", cell: 5 }],
  "39/intersection-matrix": ["sci-upset", { mode: "combination-matrix", cell: 7 }],
  "39/set-overlap-network": ["sci-set", { mode: "euler", radius: 9 }],

  // §40 optimisation and operations research
  "40/feasible-region-plot": ["sci-optimization", { mode: "feasible-region" }],
  "40/constraint-plot": ["sci-optimization", { mode: "objective-contours", levels: 2 }],
  "40/objective-function-contours": ["sci-optimization", { mode: "objective-contours", levels: 6 }],
  "40/pareto-frontier": ["sci-optimization", { mode: "pareto", points: "1/5,2/4.5,3/3,4/1.5,1.5/2,2.5/3.5,3.5/2.5", domain: "0,5", range: "0,6" }],
  "40/tradeoff-curve": ["sci-optimization", { mode: "pareto", points: "0.5/4.8,1.2/4.2,2/3.4,3/2.4,4/1.6,5/1.1", domain: "0,6", range: "0,6" }],
  "40/decision-lattice": ["sci-optimization", { mode: "decision-lattice" }],
  "40/queueing-network-diagram": ["sci-optimization", { mode: "queueing" }],

  // §41 probability
  "41/probability-tree": ["sci-probability-tree", { showProbabilities: true }],
  "41/probability-mass-function": ["sci-distribution", { law: "binomial", curve: "pdf", discrete: true, p1: 12, p2: 0.4, domain: "0,12" }],
  "41/probability-density-function": ["sci-distribution", { law: "normal", curve: "pdf" }],
  "41/cdf": ["sci-distribution", { law: "normal", curve: "cdf" }],
  "41/survival-function": ["sci-distribution", { law: "normal", curve: "survival" }],
  "41/hazard-function": ["sci-distribution", { law: "exponential", curve: "hazard", p1: 0.8, domain: "0,6" }],
  "41/quantile-function": ["sci-distribution", { law: "normal", curve: "quantile", domain: "0.01,0.99", range: "-3,3" }],
  "41/joint-density-plot": ["sci-density", { mode: "joint" }],
  "41/marginal-density-plot": ["sci-density", { mode: "marginal" }],
  "41/conditional-density-plot": ["sci-density", { mode: "conditional", at: 0.5 }],
  "41/copula-plot": ["sci-density", { mode: "copula" }],
  "41/probability-simplex": ["sci-simplex", { gridLines: 4 }],
  "41/random-walk-plot": ["sci-stochastic", { mode: "random-walk" }],
  "41/brownian-motion-path": ["sci-stochastic", { mode: "brownian" }],
  "41/monte-carlo-simulation-plot": ["sci-stochastic", { mode: "monte-carlo", samples: 300 }],

  // §43 sports
  "43/shot-chart": ["sci-pitch", { mode: "shot-chart", surface: "football" }],
  "43/pitch-map": ["sci-pitch", { mode: "pitch-map", surface: "football" }],
  "43/sports-heatmap": ["sci-pitch", { mode: "heatmap", surface: "football" }],
  "43/pass-network": ["sci-pitch", { mode: "pass-network", surface: "football" }],
  "43/player-position-map": ["sci-pitch", { mode: "positions", surface: "football" }],
  "43/formation-diagram": ["sci-pitch", { mode: "positions", surface: "generic" }],
  "43/movement-trajectory": ["sci-pitch", { mode: "trajectory", surface: "basketball" }],
  "43/race-chart": ["sci-sports-series", { mode: "race" }],
  "43/lap-chart": ["sci-sports-series", { mode: "lap" }],
  "43/split-time-chart": ["sci-sports-series", { mode: "split" }],
  "43/play-by-play-timeline": ["sci-sports-series", { mode: "play-by-play" }],
  "43/win-probability-chart": ["sci-sports-series", { mode: "win-probability", series: "A/1:0.5+2:0.62+3:0.44+4:0.71+5:0.83" }],
  "43/standings-chart": ["sci-sports-series", { mode: "standings" }],
  "43/spider-player-profile": ["sci-sports-series", { mode: "radar", series: "A/1:4+2:3+3:5+4:2+5:4+6:3,B/1:2+2:5+3:3+4:4+5:2+6:5" }],
  "43/tournament-bracket": ["sci-bracket", { rounds: 3 }],
  "43/knockout-bracket": ["sci-bracket", { rounds: 4, slotHeight: 5 }],
  "43/head-to-head-matrix": ["sci-transition", { mode: "matrix", cell: 7 }],

  // §44 music
  "44/staff-notation": ["sci-staff", { clef: "treble" }],
  "44/piano-roll": ["sci-pianoroll", { mode: "piano-roll" }],
  "44/midi-event-plot": ["sci-pianoroll", { mode: "midi" }],
  "44/rhythm-timeline": ["sci-pianoroll", { mode: "rhythm" }],
  "44/tempo-map": ["sci-pianoroll", { mode: "tempo" }],
  "44/dynamic-profile": ["sci-pianoroll", { mode: "dynamics" }],
  "44/pitch-contour": ["sci-pianoroll", { mode: "pitch-contour", curve: "0/60,1/64,2/67,3/65,4/62,5/60,6/59,7/62" }],
  "44/tonnetz": ["sci-tonnetz", { mode: "tonnetz" }],
  "44/circle-of-fifths": ["sci-tonnetz", { mode: "circle-of-fifths" }],
  "44/harmonic-network-diagram": ["sci-tonnetz", { mode: "harmonic-network" }],
};
//#endregion 🔖️Mapping

//#region 🔖️Apply
const CATALOG = "C:/git/semio/🧰️framework/🛍️products/📓️print/🖼️assets/🔣️viz-catalog.json";

type Kind = { id: string; family: string; options: Record<string, unknown>; data: string; namespace: string };

const raw = await Bun.file(CATALOG).text();
const catalog = JSON.parse(raw) as { schemaVersion: number; kinds: Kind[] };

let touched = 0;
const seen = new Map<string, string>();
for (const kind of catalog.kinds) {
  const assignment = MAPPING[kind.id];
  if (assignment === undefined) continue;
  const [family, options] = assignment;
  kind.family = family;
  kind.options = { ...options };
  kind.data = "demo-science";
  const signature = `${family}::${JSON.stringify(options)}`;
  const previous = seen.get(signature);
  if (previous !== undefined) throw new Error(`duplicate family/option signature: ${kind.id} repeats ${previous}`);
  seen.set(signature, kind.id);
  touched += 1;
}

const missing = Object.keys(MAPPING).filter((id) => !catalog.kinds.some((kind) => kind.id === id));
if (missing.length > 0) throw new Error(`mapping refers to unknown catalogue ids: ${missing.join(", ")}`);

await Bun.write(CATALOG, `${JSON.stringify(catalog, undefined, 2)}\n`);
console.log(`scientific catalogue entries rewritten: ${touched}`);
//#endregion 🔖️Apply
