/** 🧯️ Ticket-local bootstrap: emits 🛂️manifest/🤖️generated/🎚️ui-axes.ts without importing the framework barrel (which needs the file). Same byte plan as 🖱️ui/📦️packages/🦀️rust/📜️script.ts. */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
const repoRoot = process.argv[2]!;
const axes = JSON.parse(readFileSync(join(repoRoot, "🧰️framework/🔨️modules/🖱️ui/🔣️ui-axes.json"), "utf8")) as { locales: { id: string }[]; terminologies: { id: string }[] };
const localeIds = axes.locales.map((e) => JSON.stringify(e.id)).join(", ");
const terminologyIds = axes.terminologies.map((e) => JSON.stringify(e.id)).join(", ");
const content = `/** @generated by ui/script.ts from 🔣️ui-axes.json — do not edit. */

export const SHELL_LOCALES = [${localeIds}] as const;
export type ShellLocale = (typeof SHELL_LOCALES)[number];

export const SHELL_TERMINOLOGIES = [${terminologyIds}] as const;
export type ShellTerminology = (typeof SHELL_TERMINOLOGIES)[number];

/** 🧭️ Membership guard — the runtime twin of the Rust \`Locale::parse\`/exhaustive-match guarantee. */
export const isShellLocale = (value: string): value is ShellLocale => (SHELL_LOCALES as readonly string[]).includes(value);
/** 🧭️ Membership guard — the runtime twin of the Rust \`Terminology::parse\`/exhaustive-match guarantee. */
export const isShellTerminology = (value: string): value is ShellTerminology => (SHELL_TERMINOLOGIES as readonly string[]).includes(value);

/** 🗺️ Full locale×terminology matrix for a manifest label, mirroring Rust \`LocalizedLabel\`. */
export type LocalizedLabel = Readonly<Record<ShellTerminology, Readonly<Record<ShellLocale, string>>>>;
`;
const target = join(repoRoot, "🧰️framework/🔨️modules/🛂️manifest/🤖️generated/🎚️ui-axes.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, content);
console.log(`[DEBUG] bootstrap wrote ${target}`);
