/** 📷️ Direct owned PNG sample and metadata projection. */
import {parsePngSnapshot,type PngSnapshot,type PngTransparency,type PngBackground} from "../../../🧬️schema/📸️snapshot/🟦️.ts";
import {ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteDocument,artifactSqliteText,artifactSqliteInteger,artifactSqliteDocumentReference,artifactSqliteOrderedRowsControlled,type ArtifactSqliteOptions} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {ValueError,sqliteOperation,type SqliteDatabase,type SqliteRow,type SqliteOperation} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import {NativeDecodeControl} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🛬️decode/🟦️.ts";
const invalid=(message:string):never=>{throw new ValueError("invalidValue",message);};
const n=(row:SqliteRow,column:number,min=0,max=4294967295):number=>{const v=artifactSqliteInteger(row,column);return v>=BigInt(min)&&v<=BigInt(max)?Number(v):invalid("Owned INTEGER exceeds declared precision");};
const bool=(row:SqliteRow,column:number):boolean=>n(row,column,0,1)===1;
const ints=(values:readonly number[]):bigint[]=>values.map(BigInt);
function optional(rows:readonly SqliteRow[]):SqliteRow|null{if(rows.length>1)invalid("Owned optional field has multiple rows");return rows.length?artifactSqliteDocument(rows):null;}
async function ordered(rows:readonly SqliteRow[],operation:SqliteOperation):Promise<readonly SqliteRow[]>{const result=await artifactSqliteOrderedRowsControlled(rows,2,operation);for(const row of result)artifactSqliteDocumentReference(row,1);return result;}
async function mapped<T>(rows:readonly SqliteRow[],operation:SqliteOperation,width:number,project:(row:SqliteRow)=>T):Promise<T[]>{
 return operation.allocationStage(maximum=>new NativeDecodeControl(maximum,event=>{operation.onProgress?.({phase:"reconstructSnapshot",completed:event.completed,total:event.total});return true;},operation.signal),async control=>{await control.beginStage(rows.length);await control.admitSlots(rows.length,width);const result:T[]=[];for(const row of rows){result.push(project(row));await control.step();}return result;});
}
async function owned<T>(value:unknown,parse:(value:unknown)=>T,operation:SqliteOperation):Promise<T>{
 return operation.allocationStage(maximum=>new NativeDecodeControl(maximum,event=>{operation.onProgress?.({phase:"reconstructSnapshot",completed:event.completed,total:event.total});return true;},operation.signal),async control=>{
  await control.charge(8);const pending:unknown[]=[value];while(pending.length){const item=pending.pop();if(typeof item==="string"){let bytes=0;for(const c of item){const code=c.codePointAt(0)!;bytes+=code<128?1:code<2048?2:code<65536?3:4;await control.step();}await control.charge(bytes);}else if(item!==null&&typeof item==="object"){if(Array.isArray(item)){await control.admitSlots(item.length,16);for(const child of item)pending.push(child);}else{let count=0;for(const key in item)if(Object.hasOwn(item,key))count++;await control.admitSlots(count,16);for(const key in item)if(Object.hasOwn(item,key))pending.push((item as Record<string,unknown>)[key]);}}else await control.charge(8);await control.step();}return parse(value);
 });
}
export const PNG_SQLITE_SCHEMA="CREATE TABLE png_image (id INTEGER PRIMARY KEY CHECK(id=1), schema TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, bit_depth INTEGER NOT NULL, color_type INTEGER NOT NULL, interlace INTEGER NOT NULL CHECK(interlace IN (0,1)), has_palette INTEGER NOT NULL CHECK(has_palette IN (0,1)));\nCREATE TABLE png_sample (id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES png_image(id), ordinal INTEGER NOT NULL, value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 65535));\nCREATE TABLE png_palette_entry (id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES png_image(id), ordinal INTEGER NOT NULL, red INTEGER NOT NULL, green INTEGER NOT NULL, blue INTEGER NOT NULL);\nCREATE TABLE png_transparency (id INTEGER PRIMARY KEY CHECK(id=1), color_type INTEGER NOT NULL, first INTEGER NOT NULL, second INTEGER NOT NULL, third INTEGER NOT NULL);\nCREATE TABLE png_alpha (id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES png_image(id), ordinal INTEGER NOT NULL, value INTEGER NOT NULL CHECK(value BETWEEN 0 AND 255));\nCREATE TABLE png_background (id INTEGER PRIMARY KEY CHECK(id=1), color_type INTEGER NOT NULL, first INTEGER NOT NULL, second INTEGER NOT NULL, third INTEGER NOT NULL);\nCREATE TABLE png_gamma (id INTEGER PRIMARY KEY CHECK(id=1), value INTEGER NOT NULL);\nCREATE TABLE png_chromaticities (id INTEGER PRIMARY KEY CHECK(id=1), white_x INTEGER NOT NULL, white_y INTEGER NOT NULL, red_x INTEGER NOT NULL, red_y INTEGER NOT NULL, green_x INTEGER NOT NULL, green_y INTEGER NOT NULL, blue_x INTEGER NOT NULL, blue_y INTEGER NOT NULL);\nCREATE TABLE png_srgb (id INTEGER PRIMARY KEY CHECK(id=1), intent INTEGER NOT NULL);\nCREATE TABLE png_physical_dims (id INTEGER PRIMARY KEY CHECK(id=1), ppu_x INTEGER NOT NULL, ppu_y INTEGER NOT NULL, unit_is_meter INTEGER NOT NULL CHECK(unit_is_meter IN (0,1)));\nCREATE TABLE png_timestamp (id INTEGER PRIMARY KEY CHECK(id=1), year INTEGER NOT NULL, month INTEGER NOT NULL, day INTEGER NOT NULL, hour INTEGER NOT NULL, minute INTEGER NOT NULL, second INTEGER NOT NULL);\nCREATE TABLE png_text (id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES png_image(id), ordinal INTEGER NOT NULL, keyword TEXT NOT NULL, value TEXT NOT NULL, kind INTEGER NOT NULL, compressed INTEGER NOT NULL CHECK(compressed IN (0,1)), language_tag TEXT NOT NULL, translated_keyword TEXT NOT NULL);\nCREATE TABLE png_ancillary_chunk (id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES png_image(id), ordinal INTEGER NOT NULL, kind BLOB NOT NULL, after_raster INTEGER NOT NULL CHECK(after_raster IN (0,1)), data BLOB NOT NULL);\n";
const colors=["grayscale","invalid","rgb","palette","grayscaleAlpha","invalid","rgba"] as const,intents=["perceptual","relativeColorimetric","saturation","absoluteColorimetric"] as const;
const blob=(row:SqliteRow,column:number):Uint8Array=>row.values[column] instanceof Uint8Array?row.values[column] as Uint8Array:invalid("Owned ancillary field requires BLOB");
export async function pngSnapshotToSqliteDatabase(value:PngSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const operation=sqliteOperation(options),s=await owned(value,parsePngSnapshot,operation),i=s.image,p=await ArtifactSqliteProjection.create(PNG_SQLITE_SCHEMA,operation);
 await p.insert("png_image",[s.schema,...ints([i.width,i.height,i.bitDepth,colors.indexOf(i.colorType),Number(i.interlace),Number(i.palette!==null)])],1n);
 for(const [ordinal,v]of i.samples.entries())await p.insert("png_sample",ints([1,ordinal,v]));
 if(i.palette)for(const[ordinal,c]of i.palette.entries())await p.insert("png_palette_entry",ints([1,ordinal,c.r,c.g,c.b]));
 if(i.transparency){const t=i.transparency;await p.insert("png_transparency",ints(t.colorType==="indexed"?[3,0,0,0]:t.colorType==="grayscale"?[0,t.gray,0,0]:[2,t.r,t.g,t.b]),1n);if(t.colorType==="indexed")for(const[ordinal,v]of t.alpha.entries())await p.insert("png_alpha",ints([1,ordinal,v]));}
 if(i.background){const c=i.background;await p.insert("png_background",ints(c.colorType==="indexed"?[3,c.index,0,0]:c.colorType==="grayscale"?[0,c.gray,0,0]:[2,c.r,c.g,c.b]),1n);}
 if(i.gamma!==null)await p.insert("png_gamma",ints([i.gamma]),1n);
 if(i.chromaticities)await p.insert("png_chromaticities",ints([i.chromaticities.whiteX,i.chromaticities.whiteY,i.chromaticities.redX,i.chromaticities.redY,i.chromaticities.greenX,i.chromaticities.greenY,i.chromaticities.blueX,i.chromaticities.blueY]),1n);
 if(i.srgb!==null)await p.insert("png_srgb",ints([intents.indexOf(i.srgb)]),1n);
 if(i.physicalDims)await p.insert("png_physical_dims",ints([i.physicalDims.ppuX,i.physicalDims.ppuY,Number(i.physicalDims.unitIsMeter)]),1n);
 if(i.timestamp)await p.insert("png_timestamp",ints([i.timestamp.year,i.timestamp.month,i.timestamp.day,i.timestamp.hour,i.timestamp.minute,i.timestamp.second]),1n);
 for(const[ordinal,t]of i.textChunks.entries())await p.insert("png_text",[1n,BigInt(ordinal),t.keyword,t.value,BigInt(["text","zText","iText"].indexOf(t.kind)),BigInt(Number(t.compressed)),t.languageTag,t.translatedKeyword]);
 for(const[ordinal,c]of i.ancillaryChunks.entries()){const kind=operation.allocateBytes(4),data=operation.allocateBytes(c.data.length);kind.set(c.kind);for(let at=0;at<data.length;at++){data[at]=c.data[at]!;if(at%65536===0)await p.checkpoint();}await p.insert("png_ancillary_chunk",[1n,BigInt(ordinal),kind,BigInt(Number(c.afterRaster)),data]);}
 const database=await p.finish();
 return database;
}
export async function pngSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<PngSnapshot>{
 const operation=sqliteOperation(options),tables=await artifactSqliteTables(database,PNG_SQLITE_SCHEMA,operation),[images,sampleRows,paletteRows,transRows,alphaRows,backgroundRows,gammaRows,chromaRows,srgbRows,physicalRows,timeRows,textRows,ancillaryRows]=tables,row=artifactSqliteDocument(images!);
 const samples=await mapped(await ordered(sampleRows!,operation),operation,8,r=>n(r,3,0,65535)),paletteEntries=await mapped(await ordered(paletteRows!,operation),operation,40,r=>({r:n(r,3,0,255),g:n(r,4,0,255),b:n(r,5,0,255)})),hasPalette=bool(row,7);if(!hasPalette&&paletteEntries.length)invalid("PNG absent palette contains entries");
 const alpha=await mapped(await ordered(alphaRows!,operation),operation,8,r=>n(r,3,0,255)),t=optional(transRows!),b=optional(backgroundRows!);
 const color=(r:SqliteRow,isBackground:boolean):PngTransparency|PngBackground=>{const kind=n(r,1,0,3),first=n(r,2,0,65535),second=n(r,3,0,65535),third=n(r,4,0,65535);if(kind===2){if(!isBackground&&alpha.length)invalid("RGB transparency owns indexed alpha");return{colorType:"rgb",r:first,g:second,b:third};}if(second||third)invalid("PNG sparse color metadata owns undeclared channels");if(kind===0){if(!isBackground&&alpha.length)invalid("Grayscale transparency owns indexed alpha");return{colorType:"grayscale",gray:first};}if(kind===3){if(isBackground)return{colorType:"indexed",index:first};if(first)invalid("Indexed transparency owns a gray sample");return{colorType:"indexed",alpha};}return invalid("PNG color metadata discriminator differs");};
 if(!t&&alpha.length)invalid("PNG alpha lacks indexed transparency");
 const chroma=optional(chromaRows!),physical=optional(physicalRows!),time=optional(timeRows!),gamma=optional(gammaRows!),srgb=optional(srgbRows!);
 const textChunks=await mapped(await ordered(textRows!,operation),operation,80,r=>({keyword:artifactSqliteText(r,3),value:artifactSqliteText(r,4),kind:["text","zText","iText"][n(r,5,0,2)],compressed:bool(r,6),languageTag:artifactSqliteText(r,7),translatedKeyword:artifactSqliteText(r,8)}));
 const ancillaryChunks=[];for(const r of await ordered(ancillaryRows!,operation)){const kind=blob(r,3),data=blob(r,5);const chunk=await operation.allocationStage(maximum=>new NativeDecodeControl(maximum,()=>true,operation.signal),async control=>{await control.charge(24);await control.admitSlots(kind.length+data.length,8);const ownKind=[],ownData=[];for(const v of kind){ownKind.push(v);await control.step();}for(const v of data){ownData.push(v);await control.step();}return{kind:ownKind,data:ownData,afterRaster:bool(r,4)};});ancillaryChunks.push(chunk);}
 return owned({schema:artifactSqliteText(row,1),image:{width:n(row,2),height:n(row,3),bitDepth:n(row,4),colorType:colors[n(row,5,0,6)],interlace:bool(row,6),samples,palette:hasPalette?paletteEntries:null,transparency:t?color(t,false):null,background:b?color(b,true):null,gamma:gamma?n(gamma,1):null,chromaticities:chroma?{whiteX:n(chroma,1),whiteY:n(chroma,2),redX:n(chroma,3),redY:n(chroma,4),greenX:n(chroma,5),greenY:n(chroma,6),blueX:n(chroma,7),blueY:n(chroma,8)}:null,srgb:srgb?intents[n(srgb,1,0,3)]:null,physicalDims:physical?{ppuX:n(physical,1),ppuY:n(physical,2),unitIsMeter:bool(physical,3)}:null,timestamp:time?{year:n(time,1,0,65535),month:n(time,2,0,255),day:n(time,3,0,255),hour:n(time,4,0,255),minute:n(time,5,0,255),second:n(time,6,0,255)}:null,textChunks,ancillaryChunks}},parsePngSnapshot,operation);
}
