/** 📑️ Actual document block syntax, typed style/image references and independent SQLite edits. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import f from "../🧫️fixtures/🔣️.json";
import type {SemioDocumentSnapshot,DocBlock,DocRun} from "../../../../🧬️schema/📸️snapshot/🟦️.ts";
import {SEMIO_DOCUMENT_SQLITE_SCHEMA,semioDocumentSnapshotToSqliteDatabase,semioDocumentSnapshotFromSqliteDatabase} from "../🟦️.ts";
import {binary64,exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const run=():DocRun=>({text:f.text,style:{bold:true,italic:false,underline:true,size:binary64(12.5),font:"",color:null,link:"https://example.invalid/世界"}});
const input:SemioDocumentSnapshot={schema:f.schema,styles:[{id:f.styleIds[0]!,name:"",basedOn:null},{id:f.styleIds[1]!,name:f.text,basedOn:f.styleIds[0]!}],images:[{id:f.imageId,mime:f.mime,bytes:f.bytes.slice()}],blocks:[{kind:"paragraph",style_id:f.styleIds[0]!,runs:[run()]},{kind:"heading",level:255,style_id:null,runs:[run()]},{kind:"list",ordered:true,items:[{blocks:[]},{blocks:[{kind:"pageBreak"}]}]},{kind:"table",rows:[{cells:[]},{cells:[{blocks:[]},{blocks:[{kind:"code",language:"",text:f.text}]}]}]},{kind:"code",language:null,text:f.text},{kind:"quote",blocks:[{kind:"paragraph",style_id:f.styleIds[1]!,runs:[]}]},{kind:"image",image_id:f.imageId,alt:f.text,width:null,height:binary64(-0)},{kind:"pageBreak"}]};
test("Semio Document independent formatting/image joins and edited code",async()=>{expect(SEMIO_DOCUMENT_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());const db=Database.deserialize(await exportSqliteDatabase(await semioDocumentSnapshotToSqliteDatabase(input)));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(f.query).all()).toHaveLength(2);expect(await semioDocumentSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_document_code SET text='independent'").run();const edited=structuredClone(input),code=edited.blocks[4]!,table=edited.blocks[3]!;if(code.kind!=="code"||table.kind!=="table")throw Error("fixture code");code.text="independent";const nested=table.rows[1]!.cells[1]!.blocks[0]!;if(nested.kind!=="code")throw Error("fixture nested code");nested.text="independent";expect(await semioDocumentSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(edited);}finally{db.close();}});
test("quick::Semio Document nullable IEEE words, single ownership, deep trees and controls",async()=>{for(const hex of f.float64Bits){const s=structuredClone(input),word={bits:BigInt("0x"+hex)},paragraph=s.blocks[0]!,image=s.blocks[6]!;if(paragraph.kind!=="paragraph"||image.kind!=="image")throw Error("fixture");paragraph.runs[0]!.style.size=word;image.width=word;image.height=word;const db=Database.deserialize(await exportSqliteDatabase(await semioDocumentSnapshotToSqliteDatabase(s)));try{expect(await semioDocumentSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}}const d=await semioDocumentSnapshotToSqliteDatabase(input);for(const mutate of[(x:any)=>x.tables[1].rows[0].values[5]=2n,(x:any)=>x.tables[4].rows[0].values[3]=999n,(x:any)=>x.tables[15].rows[0].values[1]=1n,(x:any)=>x.tables[8].rows[0].values[4]=2n,(x:any)=>x.tables[16].rows[0].values[1]=999n]){const x=structuredClone(d);mutate(x);await expect(semioDocumentSnapshotFromSqliteDatabase(x)).rejects.toThrow();}let deep:DocBlock={kind:"pageBreak"};for(let i=0;i<2000;i++)deep={kind:"quote",blocks:[deep]};const source:SemioDocumentSnapshot={schema:"deep",styles:[],images:[],blocks:[deep]},restored=await semioDocumentSnapshotFromSqliteDatabase(await semioDocumentSnapshotToSqliteDatabase(source));let depth=0,block=restored.blocks[0]!;while(block.kind==="quote"){depth++;block=block.blocks[0]!;}expect(depth).toBe(2000);await expect(semioDocumentSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();await expect(semioDocumentSnapshotFromSqliteDatabase(d,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();await expect(semioDocumentSnapshotToSqliteDatabase(source,{signal:c.signal,onProgress:p=>{if(p.completed>=256)c.abort();}})).rejects.toThrow();},30000);

test("Semio Document native construction frontier independently preserves empty optional language and member order",async()=>{const count=f.nativeAdmission.collectionItems,s:SemioDocumentSnapshot={schema:f.schema,styles:[],images:[],blocks:Array.from({length:count},()=>({kind:"code",language:"",text:""}))};const db=Database.deserialize(await exportSqliteDatabase(await semioDocumentSnapshotToSqliteDatabase(s)));try{expect(db.query("SELECT count(*) AS n FROM semio_document_member").get()).toEqual({n:count});expect(db.query("SELECT count(*) AS n FROM semio_document_code").get()).toEqual({n:count});expect(db.query("SELECT language,text FROM semio_document_code JOIN semio_document_member ON block_id=semio_document_code.id WHERE ordinal=?").get(f.nativeAdmission.cancelAfter)).toEqual({language:"",text:""});expect(await semioDocumentSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}});

import completeSemanticContract from "../🧫️fixtures/🎛️semantic.json";
import{independentSqliteExtent as completeIndependentExtent}from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧪️tests/🔮️semantic-extent/🟦️.ts";
test("Semio Document Native matched full and metadata empty independently preserve all complete cells",async()=>{
 for(const item of completeSemanticContract.cases){const source=structuredClone(item.sourceSnapshot)as unknown as SemioDocumentSnapshot;const hydrate=(value:unknown):unknown=>Array.isArray(value)?value.map(hydrate):value!==null&&typeof value==="object"?("bits"in value?{bits:String((value as {bits:string}).bits).length===8?Number.parseInt(String((value as {bits:string}).bits),16):BigInt("0x"+String((value as {bits:string}).bits))}:Object.fromEntries(Object.entries(value).map(([key,item])=>[key,hydrate(item)]))):value;Object.assign(source,hydrate(source));const database=await semioDocumentSnapshotToSqliteDatabase(source),bytes=await exportSqliteDatabase(database);expect(completeIndependentExtent(bytes)).toEqual({rows:item.rows,valueBytes:item.valueBytes,schemaBytes:completeSemanticContract.schemaBytes,tableWidths:completeSemanticContract.tableWidths});const limits={maxRows:item.rows,maxValueBytes:item.valueBytes,maxSchemaBytes:completeSemanticContract.schemaBytes,maxTables:18,maxColumns:13};expect(await semioDocumentSnapshotToSqliteDatabase(source,limits)).toEqual(database);expect(await semioDocumentSnapshotFromSqliteDatabase(await importSqliteDatabase(bytes),limits)).toEqual(source);
 for(const short of[{...limits,maxRows:item.rows-1},{...limits,maxValueBytes:item.valueBytes-1},{...limits,maxSchemaBytes:limits.maxSchemaBytes-1},{...limits,maxTables:17},{...limits,maxColumns:12}]){await expect(semioDocumentSnapshotToSqliteDatabase(source,short)).rejects.toThrow();await expect(semioDocumentSnapshotFromSqliteDatabase(database,short)).rejects.toThrow();}
 }console.log("[DEBUG] Semio Document independently measured Native matched full and empty roles through all5 copied limits");
});
