[package]
name = "semio-framework-os-kernel-math-graph-approximation"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_approximation"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph = { path = "../../rs", package = "semio-framework-os-kernel-math-graph" }
mathematical_graph_paths = { path = "../../paths/rs", package = "semio-framework-os-kernel-math-graph-paths" }
mathematical_graph_matching = { path = "../../matching/rs", package = "semio-framework-os-kernel-math-graph-matching" }
mathematical_graph_trees = { path = "../../trees/rs", package = "semio-framework-os-kernel-math-graph-trees" }
mathematical_graph_cliques = { path = "../../cliques/rs", package = "semio-framework-os-kernel-math-graph-cliques" }
mathematical_random = { path = "../../../random/rs", package = "semio-framework-os-kernel-math-random" }
