import {test,expect} from "bun:test";
import Ajv from "ajv";
import {mkdirSync,writeFileSync,readFileSync,readdirSync} from "node:fs";
import {join} from "node:path";
import schema from "../🧬️schema/🔣️.json";
import fixture from "../🧫️fixtures/🔣️.json";
import policy from "../../🎛️control/🚪️cli/🧩️entrypoint/🧫️fixtures/🔣️.json";
import {CargoCommandEntryOwnerV1} from "../../🎛️control/🚪️cli/🧩️entrypoint/🟦️.ts";
import {parseCargoCommandRequestV1,runCargoCommandV1} from "../🟦️.ts";
import {decodeCargoProvenanceV1} from "../../../../../../../../🔨️modules/🏃️process/📦️artifacts/🏗️native-build/🧾️receipt/🟦️.ts";

test("actual Cargo command request requires explicit root argv environment and storage",()=>{
 const validate=new Ajv({strict:true}).compile(schema);expect(validate(fixture.request)).toBe(true);expect(parseCargoCommandRequestV1(fixture.request)).toEqual(fixture.request);for(const key of fixture.missing){const value={...fixture.request};delete value[key];expect(validate(value)).toBe(false);expect(()=>parseCargoCommandRequestV1(value)).toThrow();}for(const [key,bad] of fixture.bad){const value={...fixture.request,[key]:bad};expect(validate(value)).toBe(false);expect(()=>parseCargoCommandRequestV1(value)).toThrow();}
});
test("actual Cargo command uses its required owner through real native execution and retirement",async()=>{
 const output=process.env.SEMIO_TEST_ARTIFACT_DIR;if(!output)throw Error("Original caller-owned artifacts required");const cwd=join(output,"owner");mkdirSync(cwd,{recursive:true});const environment=Object.fromEntries(Object.entries(process.env).filter((row):row is [string,string]=>typeof row[1]==="string"));delete environment.SEMIO_TEST_ARTIFACT_DIR;const request={version:1 as const,root:cwd,cwd,args:["--version"],environment,storage:{version:1 as const,directory:output},provenance:{version:1 as const,buildDirectory:join(cwd,"compiler"),mirrorDirectory:null}},events:string[]=[],owner=new CargoCommandEntryOwnerV1({...policy.policy,maximumElapsedMilliseconds:10000},line=>events.push(line));await runCargoCommandV1(request,owner);expect(owner.cli.workspace.state).toBe("retired");expect(events.length).toBeGreaterThan(0);const reference=Bun.spawn(["cargo","--version"],{cwd,env:environment,stdout:"pipe",stderr:"pipe"});expect(await reference.exited).toBe(0);expect(await new Response(reference.stdout).text()).toMatch(/^cargo /u);console.log("[DEBUG] mandatory actual command owner completed native Cargo with independent native output and funded retirement");
});
test("actual Cargo command refuses cancelled owning authority before native publication",async()=>{
 const output=process.env.SEMIO_TEST_ARTIFACT_DIR;if(!output)throw Error("Original caller-owned artifacts required");const events:string[]=[],owner=new CargoCommandEntryOwnerV1(policy.policy,line=>events.push(line));owner.cli.cancelDiscovery();await expect(runCargoCommandV1({version:1,root:process.cwd(),cwd:process.cwd(),args:["--version"],environment:{},storage:{version:1,directory:output},provenance:{version:1,buildDirectory:join(output,"compiler"),mirrorDirectory:null}},owner)).rejects.toThrow();expect(owner.cli.workspace.state).toBe("retired");
});

test("actual Cargo command retains complete native compiler input and feature custody",async()=>{
 const output=process.env.SEMIO_TEST_ARTIFACT_DIR;if(!output)throw Error("Original caller-owned artifacts required");const root=join(output,"native"),buildDirectory=join(output,"compiler");mkdirSync(root,{recursive:true});writeFileSync(join(root,"Cargo.toml"),fixture.native.manifest);writeFileSync(join(root,"Cargo.lock"),fixture.native.lock);writeFileSync(join(root,"lib.rs"),fixture.native.source);
 const environment=Object.fromEntries(Object.entries(process.env).filter((row):row is [string,string]=>typeof row[1]==="string"));delete environment.SEMIO_TEST_ARTIFACT_DIR;environment.CARGO_TARGET_DIR=join(output,"target");const args=["check","--manifest-path",join(root,"Cargo.toml"),"--locked","--offline","--features","owned","--message-format=json"],events:string[]=[],owner=new CargoCommandEntryOwnerV1({...policy.policy,maximumElapsedMilliseconds:30000},line=>events.push(line));await runCargoCommandV1({version:1,root,cwd:root,args,environment,storage:{version:1,directory:output},provenance:{version:1,buildDirectory,mirrorDirectory:null}},owner);
 const ledger=join(buildDirectory,"semio-cargo-provenance"),names=readdirSync(ledger);expect(names).toHaveLength(1);const observation=decodeCargoProvenanceV1(readFileSync(join(ledger,names[0]!),"utf8"));expect(observation.args).toEqual(args);expect(observation.cwd).toBe(root);expect(observation.manifest).toBe(join(root,"Cargo.toml"));expect(observation.status).toBe(0);expect(observation.cancelled).toBe(false);expect(owner.cli.workspace.state).toBe("retired");expect(events.length).toBeGreaterThan(0);const unit=observation.units.find(row=>row.message.target.name===fixture.native.name);expect(unit.message.features).toEqual(["owned"]);expect(unit.depInfo.length).toBeGreaterThan(0);expect(unit.inputs.some(row=>row.path===join(root,"lib.rs")&&row.kind==="file"&&typeof row.sha256==="string")).toBe(true);expect(unit.artifacts.every(row=>typeof row.sha256==="string")).toBe(true);
 const reference=Bun.spawn(["cargo","metadata","--manifest-path",join(root,"Cargo.toml"),"--locked","--offline","--no-deps","--format-version=1"],{cwd:root,env:environment,stdout:"pipe",stderr:"pipe"});const text=await new Response(reference.stdout).text();expect(await reference.exited).toBe(0);const independent=JSON.parse(text);expect(independent.packages[0].targets[0].src_path).toBe(unit.message.target.src_path);expect(independent.packages[0].manifest_path).toBe(unit.message.manifest_path);console.log("[DEBUG] complete actual Cargo compiler provenance agrees with independent native metadata");
});
