syntax = "proto3";
package semio.s.trinity.rewriting.mutation.edit_rhs;
import "✏️s/🔌️plugins/🔱️trinity/🗿️artifacts/♻️rewriting/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/🛰️.proto";
import "✏️s/🔌️plugins/🔱️trinity/🗿️artifacts/🔌️jack/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/📸️snapshot/🛰️.proto";
import "🧰️framework/🔨️modules/🌱️value/🧬️schema/🛰️.proto";
import "🧰️framework/🔨️modules/🕸️graph/🛂️manifest/🌱️value/🧬️schema/🛰️.proto";
message EditRhs { semio.s.trinity.rewriting.artifact.Rhs new_rhs = 1; }
