export async function compileNativeScientificRelationStyles(workDir:string):Promise<void>{
  const neutral=fixture.scientificRelationStyles,control=neutral.vectors,original=JSON.stringify(control),validate=new Ajv2020({strict:false}).compile(neutral.schema),failures:string[]=[];
  if(!validate(control))throw Error("Scientific relation style vectors rejected");
  for(const appearance of (["light","dark"]as const).filter(value=>!process.env.PRINT_NATIVE_CONTROL_THEME||value===process.env.PRINT_NATIVE_CONTROL_THEME)){
    const language=appearance==="light"?"en":"de",directory=join(workDir,appearance),body:{raw:string}[]=[];
    for(const entry of control.cases){
      const options={mode:"commutative",unit:control.unit,nodeShape:"none",nodes:"a/"+control.origin[0]+"/"+control.origin[1]+"/,b/"+(control.origin[0]!+1)+"/"+control.origin[1]+"/",edges:"a/b/"+(entry.style==="arrow"?"wire":"arrow")+"/",width:80,height:48,axes:false,grid:false,title:"",xlabel:"",ylabel:""},base={chart:{width:control.canvas[0],height:control.canvas[1],language,theme:{appearance},layers:[],presets:[{kind:"commutative-diagram",options}]}}as unknown as VizChartSnapshot,before=JSON.stringify(base),outcome=changeVizChartValue(base,{path:["presets","0","options","edges"],value:"a/b/"+entry.style+"/"}),replay=applyVizChartDiff(base,outcome.diff),inverse=applyVizChartDiff(replay.snapshot,inverseVizChartDiff(base,outcome.diff));
      if(outcome.messages.length||outcome.diff.edits.length!==1||replay.messages.length||inverse.messages.length||JSON.stringify(base)!==before)throw Error("Relation style mutation refused");deepStrictEqual(inverse.snapshot,base);const result=await inferVizChart(replay.snapshot);if(!result.complete)throw Error("Relation style inference refused");
      body.push({raw:"\\clearpage\\ExplSyntaxOn\\tl_set:Nn\\l_semio_viz_test_canvas_case_tl{Rs"+entry.style+"}\\ExplSyntaxOff\\SemioVizProbeBegin{scientific-relation-styles}{"+entry.style+"}\n"+result.tikz.replace(/(\\begin\{VizFigure\}[^\n]*\n)/,"$1\\draw[line width=.01mm] (0,0) rectangle ("+control.canvas.join(",")+");\n")});
    }
    if(!process.env.PRINT_NATIVE_STYLE_REPLAY)await compileVizProbeDocument({case:"scientific-relation-styles",scenario:appearance,geometry:true,documentClass:"semio",documentClassOptions:"type=paper,language="+language+",theme="+appearance,packages:["semio-viz"],preamble:scientificCanvasProbePreamble(),body},{workDir:directory,scenario:undefined,keepWorkDir:true});
    const source=process.env.PRINT_NATIVE_STYLE_REPLAY?join(process.env.PRINT_NATIVE_STYLE_REPLAY,appearance):directory,pdf=await getDocument({data:new Uint8Array(readFileSync(join(source,"🧪️probe-out",appearance+".pdf"))),useSystemFonts:true}).promise,paints=new Map<string,ReturnType<typeof nativeControlPdfPaint>>();
    try{for(let page=1;page<=pdf.numPages;page++){const operators=await(await pdf.getPage(page)).getOperatorList();for(const entry of control.cases){const marker="SemioVizBodyRs"+entry.style;if(operators.argsArray.some((args,index)=>[OPS.beginMarkedContent,OPS.beginMarkedContentProps].includes(operators.fnArray[index]!)&&String(args?.[0]?.name??args?.[0])===marker))paints.set(entry.style,nativeControlPdfPaint(operators,control.canvas,marker));}}}finally{await pdf.destroy();}
    await Bun.write(join(directory,"actual-owned-styles.json"),JSON.stringify(Object.fromEntries(paints),null,2));
    for(const entry of control.cases)try{
      const actual=paints.get(entry.style);if(!actual)throw Error("Missing actual style body");if(actual.paths.some(path=>path.bounds.some((value,axis)=>value<0||value>control.canvas[axis%2]!)))throw Error("Relation path is outside the visible authored frame");const origin=control.origin.map(value=>value*control.unit),paint={...actual,paths:actual.paths.map(path=>({...path,points:path.points.map(point=>point.map((value,axis)=>value-origin[axis]!)),bounds:path.bounds.map((value,axis)=>value-origin[axis%2]!)}))};const line=d3Path();line.moveTo(0,0);line.lineTo(control.unit,0);if(line.toString()!=="M0,0L"+control.unit+",0")throw Error("Independent D3 line changed");
      const shafts=paint.paths.filter(path=>!path.closed&&path.points.length===2&&Math.abs(path.bounds[1]!)<.02&&Math.abs(path.bounds[3]!)<.02),heads=paint.paths.filter(path=>!path.closed&&path.points.length===3&&path.bounds[3]!-path.bounds[1]!>.5),hooks=paint.paths.filter(path=>!path.closed&&path.points.length>20&&path.bounds[0]!<1.2&&path.bounds[2]!<1.3);
      if(!shafts.length)throw Error("D3 relation shaft missing");if(entry.double?shafts.length!==2:shafts.length!==1)throw Error("Declared relation shaft multiplicity differs "+shafts.length);
      for(const shaft of shafts){if(!entry.hook)equal([shaft.points[0]![0]!],[0],"D3 source",.03);if(entry.hook&&!(shaft.points[0]![0]!>0&&shaft.points[0]![0]!<1.3))throw Error("Injection hook source does not connect to shaft");equal([shaft.points[1]![0]!],[control.unit],"D3 target",entry.directed?1.8:.03);equal(shaft.dash,entry.dashPt.map(value=>value*72/72.27),"Actual dash pattern",.01);equal([shaft.dashPhase],[0],"Actual dash phase",.001);}
      if(heads.length!==(entry.directed?1:0))throw Error("Declared target arrowhead count differs");for(const head of heads){equal([head.bounds[2]!-head.bounds[0]!],[1.1],"Straight Barb length",.04);if(Math.abs(head.bounds[2]!-control.unit)>head.width+.05)throw Error("Declared target lies outside head stroke envelope");}
      if(entry.hook?hooks.length!==1:hooks.length!==0)throw Error("Injection source hook geometry differs "+hooks.length);if(entry.double&&Math.max(...shafts.map(path=>path.width))-Math.min(...shafts.map(path=>path.width))<.12)throw Error("Double relation has no separated visible strokes");
    }catch(error){failures.push(appearance+"/"+entry.style+": "+String(error));}
  }
  if(JSON.stringify(control)!==original)throw Error("Style vector changed");if(failures.length)throw Error("Scientific relation styles:\n"+failures.join("\n"));console.log("[DEBUG] Scientific16 actual bilingual/theme relation styles matched D3 shafts, multiplicity, target heads, injection hooks and PDF dash state");
}

