cargo-features = [ "trim-paths" ]

[workspace]
resolver = "2"
members = [
    "🔨️modules/🌐️spatial-kernel/⚙️engine/🧠️semio/🌊️session/📦️packages/🦀️rust",
    "🔨️modules/📜️imperative/📦️packages/🦀️rust",
    "🔨️modules/📜️imperative/🧩️extension_sdk/📦️packages/🦀️rust",
]
exclude = [
    "**/🏅️standards/**",
    "**/🏭️bridge/**",
    "**/👽️guest/**",
    "**/🔮️oracles/**",
    "🔌️plugins/**",
    "🔌️plugins/✒️writer/🗿️artifacts/✒️writer",
    "🔌️plugins/➗️mathematical/🗿️artifacts/➗️equation",
    "🔌️plugins/➗️mathematical/🗿️artifacts/➗️equation/🏅️standards/🔖️1/🪆️subsets/✳️any/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/➗️mathematical/🗿️artifacts/➗️equation/🏅️standards/🔖️1/🪆️subsets/✳️any/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🀄️wfc",
    "🔌️plugins/🀄️wfc/🗿️artifacts/◻️2d",
    "🔌️plugins/🀄️wfc/🗿️artifacts/🔲️grid2d",
    "🔌️plugins/🀄️wfc/🗿️artifacts/🖼️bitmap",
    "🔌️plugins/🀄️wfc/🗿️artifacts/🧊️3d",
    "🔌️plugins/🀄️wfc/🗿️artifacts/🧱️grid3d",
    "🔌️plugins/🌀️procedural/🗿️artifacts/🌀️generation2d",
    "🔌️plugins/🌀️procedural/🗿️artifacts/🧊️generation3d",
    "🔌️plugins/🌊️flow/🗿️artifacts/🌊️flow",
    "🔌️plugins/🌊️flow/🧩️extensions/🏗️bim",
    "🔌️plugins/🌊️flow/🧩️extensions/📃️list",
    "🔌️plugins/🌊️flow/🧩️extensions/📐️brep",
    "🔌️plugins/🌊️flow/🧩️extensions/📖️dictionary",
    "🔌️plugins/🌊️flow/🧩️extensions/📝️text",
    "🔌️plugins/🌊️flow/🧩️extensions/🔤️primitive",
    "🔌️plugins/🌊️flow/🧩️extensions/🖍️draw",
    "🔌️plugins/🌊️flow/🧩️extensions/🧠️logic",
    "🔌️plugins/🌊️flow/🧩️extensions/🧮️math",
    "🔌️plugins/🌍️gis/🗿️artifacts/🏔️gisterrain",
    "🔌️plugins/🌍️gis/🗿️artifacts/🗺️gismap",
    "🔌️plugins/🌿️vcs/🗿️artifacts/🌿️vcs",
    "🔌️plugins/🎞️animate/🗿️artifacts/🎬️presentation",
    "🔌️plugins/🎥️shooting/🗿️artifacts/🎥️shooting",
    "🔌️plugins/🎪️demonstrator/🗿️artifacts/🎪️playground",
    "🔌️plugins/🎬️sequence/🗿️artifacts/🎬️sequence",
    "🔌️plugins/🏗️fem/🗿️artifacts/◻️2d",
    "🔌️plugins/🏗️fem/🗿️artifacts/◻️2d/🏅️standards/🔖️1/🪆️subsets/🌐️any/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🏗️fem/🗿️artifacts/🧊️3d",
    "🔌️plugins/🏗️fem/🗿️artifacts/🧊️3d/🏅️standards/🔖️1/🪆️subsets/🌐️any/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🏙️bim/🗿️artifacts/🏢️model",
    "🔌️plugins/🏛️architect/🗿️artifacts/🏛️program",
    "🔌️plugins/🏭️process/🗿️artifacts/🧊️process3d",
    "🔌️plugins/🏭️process/🧩️extensions/🔩️metal",
    "🔌️plugins/🏭️process/🧩️extensions/🤖️robotic",
    "🔌️plugins/🏭️process/🧩️extensions/🧱️concrete",
    "🔌️plugins/🏭️process/🧩️extensions/🪵️wood",
    "🔌️plugins/💠️lowpoly/🗿️artifacts/💠️lowpoly",
    "🔌️plugins/💡️reasoning/🗿️artifacts/🔌️wires",
    "🔌️plugins/📋️forms/🗿️artifacts/📋️forms",
    "🔌️plugins/📏️layout/🗿️artifacts/📏️layout",
    "🔌️plugins/📐️cad/🗿️artifacts/📐️cad",
    "🔌️plugins/📐️cad/🧩️extensions/🏛️aec-building-structure",
    "🔌️plugins/📐️cad/🧩️extensions/🏢️aec-building",
    "🔌️plugins/📐️cad/🧩️extensions/📐️spatial-shape",
    "🔌️plugins/📐️cad/🧩️extensions/🔥️aec-building-energy",
    "🔌️plugins/📕️norm",
    "🔌️plugins/📕️norm/🗿️artifacts/⚖️en1990",
    "🔌️plugins/📕️norm/🗿️artifacts/⚡️din18599",
    "🔌️plugins/📕️norm/🗿️artifacts/🌍️en1997",
    "🔌️plugins/📕️norm/🗿️artifacts/🌬️din16798",
    "🔌️plugins/📕️norm/🗿️artifacts/🏋️en1991",
    "🔌️plugins/📕️norm/🗿️artifacts/🏛️en1992",
    "🔌️plugins/📕️norm/🗿️artifacts/🏭️vdi3805",
    "🔌️plugins/📕️norm/🗿️artifacts/📇️iso16757",
    "🔌️plugins/📕️norm/🗿️artifacts/🔩️en1993",
    "🔌️plugins/📕️norm/🗿️artifacts/🧩️en1994",
    "🔌️plugins/📕️norm/🗿️artifacts/🧱️din4108",
    "🔌️plugins/📕️norm/🗿️artifacts/🪨️en1996",
    "🔌️plugins/📕️norm/🗿️artifacts/🪵️en1995",
    "🔌️plugins/📕️norm/🗿️artifacts/🪶️en1999",
    "🔌️plugins/📕️norm/🗿️artifacts/🫨️en1998",
    "🔌️plugins/📖️playbook/🗿️artifacts/📖️playbook",
    "🔌️plugins/📖️playbook/🧩️extensions/🌀️procedural",
    "🔌️plugins/📜️imperative/🗿️artifacts/📜️procedure",
    "🔌️plugins/📜️imperative/🧩️extensions/🎮️control",
    "🔌️plugins/📜️imperative/🧩️extensions/📝️text",
    "🔌️plugins/📜️imperative/🧩️extensions/📣️effect",
    "🔌️plugins/📜️imperative/🧩️extensions/🧠️logic",
    "🔌️plugins/📜️imperative/🧩️extensions/🧮️math",
    "🔌️plugins/📸️remodel/🗿️artifacts/📸️remodeling",
    "🔌️plugins/🔋️energy/🗿️artifacts/🔋️model",
    "🔌️plugins/🔱️trinity",
    "🔌️plugins/🔱️trinity/🗿️artifacts/♻️rewriting",
    "🔌️plugins/🔱️trinity/🗿️artifacts/🔌️jack",
    "🔌️plugins/🕸️dag/🗿️artifacts/🕸️dag",
    "🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing",
    "🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🖨️raster/🗿️artifacts/🖨️raster",
    "🔌️plugins/🗄️stdio",
    "🔌️plugins/🗄️stdio/🔮️oracles/🎒️archive/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/📃️document/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/📊️tabular/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/📰markup/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/🔊️audio/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/🔤️part21/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/🖊️drawing/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/🖼️raster/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🔮️oracles/🧊️mesh/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/☁️las",
    "🔌️plugins/🗄️stdio/🗿️artifacts/☁️las/🏅️standards/🔖️1.0/🪆️subsets/🎩️header/🏭️generator/🧪️tests/🧰️support/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/☁️las/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🌐️html",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🌐️html/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🌦️epw",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🌦️epw/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎒️zip",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎒️zip/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎞️gif",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎞️gif/🏅️standards/7️⃣87a/🪆️subsets/✳️any/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎞️gif/🏅️standards/9️⃣89a/🪆️subsets/🧱️base/🏭️generator/🧪️tests/🧰️support/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎞️gif/🏅️standards/9️⃣89a/🪆️subsets/🧱️base/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎞️gif/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎥️mp4",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎥️mp4/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎨️svg",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎨️svg/🏅️standards/🔖️1.1/🪆️subsets/🧱️base/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎨️svg/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎵️mp3",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🎵️mp3/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🏗️ifc",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🏗️ifc/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/💬️bcf",
    "🔌️plugins/🗄️stdio/🗿️artifacts/💬️bcf/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/💾️binary",
    "🔌️plugins/🗄️stdio/🗿️artifacts/💾️binary/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📊️csv",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📊️csv/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📐️step",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📐️step/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📑️tsv",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📑️tsv/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📕️xlsx",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📕️xlsx/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/4️⃣1.4/🪆️subsets/🖨️x/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/4️⃣1.4/🪆️subsets/🗄️a/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/4️⃣1.4/🪆️subsets/🧱️base/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/♿️ua/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/⚕️h/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/📐️e/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/🖨️x/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/🗄️a/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/🧱️base/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/🧱️base/🏭️generator/🧪️tests/🧰️support/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🏅️standards/7️⃣1.7/🪆️subsets/🧾️vt/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📖️pdf/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📜️docx",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📜️docx/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📝️md",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📝️md/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📰️xml",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📰️xml/🏅️standards/🔖️1.0/🪆️subsets/🧱️base/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📰️xml/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📷️png",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📷️png/🏅️standards/🔖️1.2/🪆️subsets/✳️any/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📷️png/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📸️jpg",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📸️jpg/🏅️standards/🔖️jfif-1.01/🪆️subsets/🧾️document/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📸️jpg/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📼️avi",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📼️avi/🏅️standards/🔖️1.0/🪆️subsets/🎛️hdrl/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📼️avi/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📽️pptx",
    "🔌️plugins/🗄️stdio/🗿️artifacts/📽️pptx/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔊️wav",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔊️wav/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔤️txt",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔤️txt/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔺️stl",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🔺️stl/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖊️dwg",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖊️dwg/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖋️dxf",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖋️dxf/🏅️standards/🔖️r12/🪆️subsets/📰️header/🏭️generator/🧪️tests/🧰️support/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖋️dxf/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖼️tiff",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖼️tiff/🏅️standards/🔖️6.0/🪆️subsets/🧾️document/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖼️tiff/🏅️standards/🔖️6.0/🪆️subsets/🧾️document/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🖼️tiff/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗜️deflate",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗜️deflate/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗽️obj",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗽️obj/🏅️standards/🔖️3.0/🪆️subsets/📐️geometry/🏭️generator/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗽️obj/🏅️standards/🔖️3.0/🪆️subsets/📐️geometry/🏭️generator/🧪️tests/🧰️support/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🗽️obj/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧊️gltf",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧊️gltf/🏅️standards/🔖️2.0/🪆️subsets/♾️any/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧊️gltf/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧱️ply",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧱️ply/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧾️json",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧾️json/🏅️standards/🔖️rfc8259/🪆️subsets/🧱️base/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧾️json/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/📐️cad/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/📐️cad/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/📑️document/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/🔺️mesh/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/🖊️drawing/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/🖊️drawing/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/🖊️drawing/🔬️probes/📖️reader/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/🧊️brep/🏭️generator/🧩️json/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🪟️bmp",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🪟️bmp/🏅️standards/🔖️v3/🪆️subsets/✳️any/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗄️stdio/🗿️artifacts/🪟️bmp/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🗒️note/🗿️artifacts/🗒️note",
    "🔌️plugins/🗒️note/🗿️artifacts/🗒️note/🏅️standards/🔖️1/🪆️subsets/✳️any/🏭️generator/🔁️codec/📦️packages/🦀️rust",
    "🔌️plugins/🗒️note/🗿️artifacts/🗒️note/🔮️oracles/📦️packages/🦀️rust",
    "🔌️plugins/🧩️puzzle/🗿️artifacts/◻️2d",
    "🔌️plugins/🧩️puzzle/🗿️artifacts/🖐️5d",
    "🔌️plugins/🧩️puzzle/🗿️artifacts/🧊️3d",
    "🔌️plugins/🧱️block",
    "🔌️plugins/🧱️block/🗿️artifacts/◻️2d",
    "🔌️plugins/🧱️block/🗿️artifacts/🖐️5d",
    "🔌️plugins/🧱️block/🗿️artifacts/🧊️3d",
    "🔌️plugins/🪐️space/🗿️artifacts/🏠️home",
    "🔌️plugins/🪐️space/🗿️artifacts/🪐️space",
    "🔌️plugins/🪐️space/🫀️core",
    "🔌️plugins/🪵️sourcing/🗿️artifacts/🗂️curation",
    "🔌️plugins/🪵️sourcing/🧩️extensions/🧱️slabs",
    "🔌️plugins/🪵️sourcing/🧩️extensions/🪟️windows",
    "🔌️plugins/🪵️sourcing/🧩️extensions/🪵️beams",
    "🧑‍💻dev/**",
    "🧑‍💻dev/🌊️flow",
    "🧑‍💻dev/🎭️variants/🌍️gis/💡️services",
    "🧑‍💻dev/💡️services",
    "🧑‍💻dev/📐️cad",
    "🧑‍💻dev/🧩️composition",
    "🧑‍💻dev/🧹️fixture-sweep",
]

[workspace.metadata.semio.repository]
schema-version = 1
exclude-patterns = [
  "**/🏅️standards/**",
  "**/👽️guest/**",
  "**/🔮️oracles/**",
  "**/🏭️bridge/**",
  "🔌️plugins/**",
  "🧑‍💻dev/**"
]
member-manifests = [ "🔨️modules/**/📦️packages/🦀️rust/Cargo.toml" ]

  [workspace.package]
  version = "0.1.0"
  edition = "2021"
  rust-version = "1.95"

[workspace.dependencies.semio-framework-job]
path = "../🧰️framework/🔨️modules/🧵️job/📦️packages/🦀️rust"

[workspace.dependencies.serde]
version = "1.0.228"
features = [ "derive" ]

[workspace.dependencies.serde_json]
version = "1.0.149"
features = [ "raw_value" ]

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

  [workspace.lints.rust.future_incompatible]
  level = "warn"
  priority = -1

  [workspace.lints.rust.rust_2018_idioms]
  level = "warn"
  priority = -1

[workspace.lints.clippy]
cloned_instead_of_copied = "warn"
inefficient_to_string = "warn"
map_unwrap_or = "warn"
needless_pass_by_value = "warn"
semicolon_if_nothing_returned = "warn"
unnecessary_wraps = "warn"
redundant_clone = "warn"

  [workspace.lints.clippy.all]
  level = "warn"
  priority = -1

[profile.dev]
debug = false
incremental = false

  [profile.dev.build-override]
  opt-level = 3

[profile.dev.package.wasmtime]
opt-level = 3

[profile.dev.package.wasmtime-environ]
opt-level = 3

[profile.dev.package.wasmtime-internal-core]
opt-level = 3

[profile.dev.package.wasmtime-internal-cranelift]
opt-level = 3

[profile.dev.package.wasmtime-internal-fiber]
opt-level = 3

[profile.dev.package.wasmtime-internal-unwinder]
opt-level = 3

[profile.dev.package.wasmtime-internal-cache]
opt-level = 3

[profile.dev.package.wasmtime-internal-component-util]
opt-level = 3

[profile.dev.package.wasmtime-internal-jit-debug]
opt-level = 3

[profile.dev.package.wasmtime-internal-jit-icache-coherence]
opt-level = 3

[profile.dev.package.wasmtime-wasi]
opt-level = 3

[profile.dev.package.wasmtime-wasi-io]
opt-level = 3

[profile.dev.package.cranelift-codegen]
opt-level = 3

[profile.dev.package.cranelift-frontend]
opt-level = 3

[profile.dev.package.cranelift-entity]
opt-level = 3

[profile.dev.package.cranelift-bforest]
opt-level = 3

[profile.dev.package.cranelift-bitset]
opt-level = 3

[profile.dev.package.cranelift-control]
opt-level = 3

[profile.dev.package.cranelift-native]
opt-level = 3

[profile.dev.package.cranelift-codegen-shared]
opt-level = 3

[profile.dev.package.cranelift-assembler-x64]
opt-level = 3

[profile.dev.package.regalloc2]
opt-level = 3

[profile.dev.package.wasmparser]
opt-level = 3

[profile.dev.package.pulley-interpreter]
opt-level = 3

[profile.dev.package.gimli]
opt-level = 3

[profile.dev.package.object]
opt-level = 3

[profile.dev.package.wit-parser]
opt-level = 3

[profile.dev.package.semio-framework-plugin-host]
opt-level = 3

[profile.dev.package.semio-framework-hash]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
codegen-units = 1
incremental = false

[profile.wasm-dev.package.semio-framework-os-flow]
opt-level = 2

[profile.wasm-dev.package.semio-framework-os-kernel-neural-engine]
opt-level = 2

[profile.wasm-dev.package.semio-framework-replication]
opt-level = 2

[profile.wasm-dev.package.semio-framework-pack]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "debuginfo"
incremental = false
trim-paths = "object"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "symbols"
incremental = false
trim-paths = "object"

[profile.wasm-release.package.semio-framework-os-kernel]
codegen-units = 1
