import {readFileSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import assert from "node:assert/strict";
import {blake3} from "/Users/ueli/Documents/semio/node_modules/@noble/hashes/blake3.js";
import {historyTransitionId} from "/Users/ueli/Documents/semio/🧰️framework/🔨️modules/📡️replication/🟦️.ts";
const ticket=join(import.meta.dir,"../.."),repo="/Users/ueli/Documents/semio",path=join(repo,"✏️s/🔌️plugins/✒️writer/🗿️artifacts/✒️writer/🏅️standards/🔖️1/🪆️subsets/✳️any/🧫️fixtures/🔁️hub-tail-after-check-in/🔣️.json"),before=readFileSync(path,"utf8"),fixture=JSON.parse(before);
const law=JSON.parse(readFileSync(join(path,"../🧭️current-checkpoints/🔣️.json"),"utf8")),witnesses=[];
for(const row of law.checkpoints){const t=row.transition,bytes:number[]=[];const u=(out:number[],n:number)=>{let value=BigInt(n);do{const part=Number(value&127n);value>>=7n;out.push(part|(value?128:0));}while(value);};const s=(value:string)=>{const text=Buffer.from(value,"utf8");u(bytes,text.length);bytes.push(...text);};const o=(value:string|null)=>{bytes.push(value===null?0:1);if(value!==null)s(value);};
u(bytes,2);s(t.checkpointId);o(t.parentId);s(t.changeId);u(bytes,t.mutationIds.length);for(const id of t.mutationIds)s(id);o(t.description);s(t.savedAt);u(bytes,t.authors.length);for(const author of t.authors){s(author.id);s(author.name);o(author.avatar);}o(t.message);s(t.timestamp);o(t.lineId);
const material:number[]=[];u(material,row.clock.actor);u(material,row.clock.physical_ms);u(material,row.clock.logical);u(material,bytes.length);material.push(...bytes);const id="transition-"+Buffer.from(blake3(Uint8Array.from(material))).toString("hex").slice(0,16);assert.equal(historyTransitionId(row.clock,bytes),id);assert.deepEqual(bytes.slice(0,-1),fixture.envelopes[row.index].diff.payload);assert.equal(bytes.at(-1),0);witnesses.push({index:row.index,payload:bytes,id,previousId:fixture.envelopes[row.index].mutation_id});console.log("[DEBUG] Writer independent current checkpoint wire bytes="+bytes.length+" first_party_id="+id+" third_party_blake3_same=true original_all_fields_unchanged=true");}
writeFileSync(join(ticket,"🗑️generated/writer-current-checkpoint-producer-witnesses.json"),JSON.stringify(witnesses,null,2)+"\n");
for(const witness of witnesses){const envelope=fixture.envelopes[witness.index];envelope.diff.payload=witness.payload;envelope.mutation_id=witness.id;for(const other of fixture.envelopes){other.dependencies=other.dependencies.map((id:string)=>id===witness.previousId?witness.id:id);if(other.observed===witness.previousId)other.observed=witness.id;}}
fixture.description="A current-schema handcrafted Writer catch-up tail: four edits, a checkpoint, eleven edits by two authors, a second checkpoint. All original operation payloads, actors, HLC timestamps, checkpoint facts and causal relationships are preserved. Both complete checkpoint payloads explicitly carry absent line identity; transition IDs cover the current full wire bytes. The independent current checkpoint semantics fixture pins every checkpoint field. Folding all17 envelopes beside two local edits, printing the real document pack and initializing its exact owner must succeed.";
writeFileSync(join(import.meta.dir,"held-provider-pairs.json"),JSON.stringify([{path,before,after:JSON.stringify(fixture,null,2)+"\n"}],null,2)+"\n");
