[workspace]

[package]
name = "semio-s-artifact-stdio-obj-test-oracle"
version = "0.1.0"
edition = "2021"
publish = false
description = "🔮️ Owned independent test oracle provider"

[package.metadata.semio]
role = "test"

[lib]
name = "semio_s_artifact_stdio_obj_test_oracle"
path = "../../🦀️.rs"

[features]
oracles = []

[dependencies]
"semio-repo-test-host" = { path = "../../../../../../../../🧰️framework/🛍️products/🦑️repo/🔨️modules/🧪️test/📦️packages/🦀️rust", default-features = false }
