[package]
workspace = "../../../../../.."
name = "semio-s-artifact-stdio-md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Stdio md artifact"

[package.metadata.semio]
role = "artifact"

[lints]
workspace = true

[lib]
path = "../../🦀️.rs"

[features]
default = []
component-app-assembly = []

[dependencies]
semio-framework-ui-locale = { path = "../../../../../../../🧰️framework/🔨️modules/🖱️ui/🌐️locale/📦️packages/🦀️rust" }
semio-framework-schema-composition = { path = "../../../../../../../🧰️framework/🔨️modules/🧬️schema/🧩️composition/📦️packages/🦀️rust" }
semio-framework-schema-state = { path = "../../../../../../../🧰️framework/🔨️modules/🧬️schema/📶️state/📦️packages/🦀️rust" }
semio-framework-schema-registry = { path = "../../../../../../../🧰️framework/🔨️modules/🧬️schema/📇️registry/📦️packages/🦀️rust" }
semio-framework-2d = { path = "../../../../../../../🧰️framework/🔨️modules/◻️2d/📦️packages/🦀️rust", default-features = false }
semio-framework-value = { path = "../../../../../../../🧰️framework/🔨️modules/🌱️value/📦️packages/🦀️rust" }
pack = { workspace = true }
semio-framework = { workspace = true }
semio-framework-hash = { workspace = true }
semio-framework-job = { workspace = true }
semio-framework-os-kernel = { workspace = true }
semio-framework-plugin = { workspace = true }
semio-framework-schema = { workspace = true }
semio-framework-value-derive = { workspace = true }
semio-s-artifact-stdio-contract = { workspace = true }
semio-s-artifact-stdio-txt = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
semio-framework-async-macros = { workspace = true }
semio-framework-plugin = { workspace = true, features = ["artifact-app-testing"] }

[package.metadata.semio.composition]
manifest = "../../🧩️composition/🔣️.json"
