//! 🫙️ Actual original Flow SQLite native prefixes preserve source identity and physical retirement receipts.
use semio_framework_os_kernel as store;
use semio_framework_value::{ErasedSnapshotRetirement,ValueError,ValueRefusalKind,RetirementDemand,native_decoding::NativeDecodeRetirementRecipient,retained_clone::{RetainedCloneGrant,RetainedCloneProgress,RetainedCloneStep},retirement::RetireOwned};
use semio_s_artifact_stdio_semio::standards::v1::subsets::flow::schema::snapshot::{SemioFlowSnapshot,FlowNode,FlowParam,FlowEdge,PortRef};
use store::{ArtifactSqliteSnapshot,ArtifactPack,ArtifactDsl,sqlite_snapshot::{SqliteSnapshotControl,SqliteDatabaseLimits}};
#[global_allocator]
static PREFIX_HEAP:semio_framework_trace::HeapWitness=semio_framework_trace::HeapWitness;
fn corpus()->serde_json::Value{serde_json::from_str(include_str!("../../🧫️fixtures/🫙️prefix/🔣️.json")).unwrap()}
fn policy(f:&serde_json::Value)->RetainedCloneGrant{let p=&f["policy"];RetainedCloneGrant{maximum_items:p["maximumItems"].as_u64().unwrap()as usize,maximum_copy_bytes:p["maximumCopyBytes"].as_u64().unwrap()as usize,maximum_capacity_bytes:p["maximumCapacityBytes"].as_u64().unwrap()as usize,maximum_release_bytes:p["maximumReleaseBytes"].as_u64().unwrap()as usize,maximum_depth:p["maximumDepth"].as_u64().unwrap()as usize}}
fn fixture(f:&serde_json::Value)->SemioFlowSnapshot{let v=&f["flow"];let node=v["nodeId"].as_str().unwrap();SemioFlowSnapshot{schema:v["schema"].as_str().unwrap().into(),nodes:vec![FlowNode{id:node.into(),kind:"original-kind".into(),label:v["label"].as_str().unwrap().repeat(f["labelRepetitions"].as_u64().unwrap()as usize),params:vec![FlowParam{key:v["parameterKey"].as_str().unwrap().into(),value:v["parameterValue"].as_str().unwrap().into()}],position:Default::default()}],edges:vec![FlowEdge{id:"original-edge".into(),from:PortRef{node:node.into(),port:v["sourcePort"].as_str().unwrap().into()},to:PortRef{node:node.into(),port:v["targetPort"].as_str().unwrap().into()},kind:"original-edge-kind".into()}]}}
fn demand(owner:&dyn ErasedSnapshotRetirement)->RetirementDemand{let copy=owner.next_copy_byte_demand().unwrap();let release=owner.next_release_byte_demand().unwrap();owner.next_demand(if copy==0{release}else{copy}).unwrap()}
fn close(owner:&mut dyn ErasedSnapshotRetirement,grant:RetainedCloneGrant)->(usize,usize){
let mut born=0;let mut freed=0;for _ in 0..1000000{
if owner.terminal_is_empty(){return(born,freed)}let d=demand(owner);assert!(d.copy_bytes<=grant.maximum_copy_bytes&&d.capacity_bytes<=grant.maximum_capacity_bytes&&d.release_bytes<=grant.maximum_release_bytes&&d.depth<=grant.maximum_depth);
for axis in 0..5{let mut denied=grant;let active=match axis{0=>{denied.maximum_items=0;1},1=>{denied.maximum_copy_bytes=d.copy_bytes.saturating_sub(1);d.copy_bytes},2=>{denied.maximum_capacity_bytes=d.capacity_bytes.saturating_sub(1);d.capacity_bytes},3=>{denied.maximum_release_bytes=d.release_bytes.saturating_sub(1);d.release_bytes},_=>{denied.maximum_depth=d.depth.saturating_sub(1);d.depth}};if active==0{continue}
let(result,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||owner.close_step(denied));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0),"denied currency changed original prefix backing");if axis==4{assert_eq!(result.unwrap_err().kind,ValueRefusalKind::DepthLimit)}else{assert_eq!(result.unwrap().progress(),RetainedCloneProgress::default())}assert_eq!(demand(owner),d);assert!(!owner.terminal_is_empty());
}
let(step,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||owner.close_step(grant).unwrap());let progress=step.progress();assert!(progress.fits(grant));assert_eq!(heap.requested_bytes,progress.retained_capacity_bytes);assert_eq!(heap.released_bytes,progress.released_bytes);born+=heap.requested_bytes;freed+=heap.released_bytes;
if matches!(step,RetainedCloneStep::Complete(_)){assert!(owner.terminal_is_empty());return(born,freed)}
}panic!("original prefix close did not converge")
}
fn close_value<T:RetireOwned>(original:T,grant:RetainedCloneGrant)->(usize,usize){let mut original=Some(original);let mut owner=None;let(step,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||store::artifact_retirement_admit_owned(&mut original,&mut owner,grant).unwrap());assert!(original.is_none());assert_eq!(heap.requested_bytes,step.progress().retained_capacity_bytes);assert_eq!(heap.released_bytes,step.progress().released_bytes);let(mut born,mut freed)=close(owner.as_mut().unwrap().as_mut(),grant);born+=heap.requested_bytes;freed+=heap.released_bytes;let(step,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||store::artifact_retirement_box_close_step(&mut owner,grant).unwrap());assert!(owner.is_none());assert_eq!(heap.requested_bytes,step.progress().retained_capacity_bytes);assert_eq!(heap.released_bytes,step.progress().released_bytes);(born+heap.requested_bytes,freed+heap.released_bytes)}
/// 🗃️ Creates a test input through its original recipient and authored caller close policy.
fn fixture_database<T:ArtifactSqliteSnapshot>(snapshot:&T)->store::sqlite_snapshot::SqliteDatabase{
let grant=policy(&corpus());let mut recipient=NativeDecodeRetirementRecipient::new();let database={let mut control=SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();snapshot.to_sqlite_database(&mut control).unwrap()};close(&mut recipient,grant);database
}
fn source(payload:&store::io::IoPayload)->(*const u8,usize){match payload{store::io::IoPayload::Binary(v)=>(v.as_ptr(),v.len()),store::io::IoPayload::Text(v)=>(v.as_ptr(),v.len())}}
#[test]
fn native_prefix_original_flow_success_and_cancelled_interior(){
let f=corpus();let grant=policy(&f);let expected=fixture(&f);let mut prefixes=0;
for encoding in f["encodings"].as_array().unwrap(){let payload=if encoding=="binary"{store::io::IoPayload::Binary(expected.encode_pack())}else{store::io::IoPayload::Text(expected.print_dsl())};let original=source(&payload);
for(stop,mode)in f["stops"].as_array().unwrap().iter().map(|v|(v.as_u64().unwrap()as usize,"count")).chain(f["interiorPhases"].as_array().unwrap().iter().map(|v|(usize::MAX,v.as_str().unwrap()))).chain(std::iter::once((usize::MAX,"success"))){
let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut label_stage=0;let mut interior=false;
let label_bytes=expected.nodes[0].label.len();let key_bytes=expected.nodes[0].params[0].key.len();
let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;if event.total==label_bytes&&event.completed==0{label_stage+=1}let cancel=(mode=="label"&&label_stage>=3&&event.total==label_bytes&&event.completed>=65536)||(mode=="parameter"&&label_stage>=3&&event.total==key_bytes&&event.completed==key_bytes);interior|=cancel;current!=stop&&!cancel};
let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioFlowSnapshot::decode_sqlite_snapshot_native(&payload,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});
assert_eq!(source(&payload),original);assert_eq!(heap.released_bytes,0,"normal decode released an original prefix");let mut born=heap.requested_bytes;let mut freed=0;
match result{Ok(actual)=>{assert_eq!(actual,expected);assert_eq!(mode,"success");assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;freed+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if mode!="count"{assert!(interior);assert!(heap.requested_bytes>=label_bytes,"interior cancellation lacks the real long label backing")}if recipient.has_owner(){prefixes+=1;assert!(admitted>0)}let(b,r)=close_value(error,grant);born+=b;freed+=r}}
let(b,r)=close(&mut recipient,grant);born+=b;freed+=r;assert_eq!(born,freed,"whole original prefix and refusal metadata physical balance");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}
}assert!(prefixes>=2);println!("[DEBUG] Actual original Flow binary/text native prefixes retained source pointers, all5 denied currencies and exact caller-funded physical close; cancelledPrefixes={prefixes}");
}
#[test]
fn native_prefix_missing_recipient_refuses_before_owned_materialization(){let f=corpus();let expected=fixture(&f);let payload=store::io::IoPayload::Binary(expected.encode_pack());let pointer=source(&payload);let(result,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||SemioFlowSnapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())));assert_eq!(result.unwrap_err().kind,ValueRefusalKind::OwnershipLimit);assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));assert_eq!(source(&payload),pointer);println!("[DEBUG] Missing caller recipient rejected original Flow source before any materialized prefix");}

#[test]
fn native_prefix_original_link_pin_variants_and_funded_fields(){
let pins:serde_json::Value=serde_json::from_str(include_str!("../../../../../../../../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🏪️store/🔗️link/🧫️fixtures/♻️retirement/🔣️.json")).unwrap();let grant=policy(&corpus());
for row in pins["pins"].as_array().unwrap(){let pin=match row["kind"].as_str().unwrap(){"head"=>store::LinkPin::Head,"checkpoint"=>store::LinkPin::Checkpoint{id:row["id"].as_str().unwrap().into()},"snapshot"=>store::LinkPin::Snapshot{blob:store::BlobRef{hash:row["blob"]["hash"].as_str().unwrap().into(),size:row["blob"]["size"].as_u64().unwrap(),media_type:row["blob"]["mediaType"].as_str().unwrap().into()}},_=>panic!("invalid neutral pin")};let original=match &pin{store::LinkPin::Head=>0,store::LinkPin::Checkpoint{id}=>{assert_eq!(id,row["id"].as_str().unwrap());id.capacity()},store::LinkPin::Snapshot{blob}=>{assert_eq!(blob.hash,row["blob"]["hash"].as_str().unwrap());assert_eq!(blob.size,row["blob"]["size"].as_u64().unwrap());assert_eq!(blob.media_type,row["blob"]["mediaType"].as_str().unwrap());blob.hash.capacity()+blob.media_type.capacity()}};
assert!(store::LinkPin::controlled_retirement_supported());let(born,released)=close_value(pin,grant);assert_eq!(original+born,released);
}println!("[DEBUG] Neutral head/checkpoint/snapshot pins preserve all authored fields and conserve exact original backing through independently denied and funded five-currency close");
}

#[test]
fn native_prefix_original_envelope_selected_child_same_ledger_and_cancelled_fields(){
use semio_s_artifact_stdio_semio::standards::v1::subsets::base::schema::snapshot::{SemioSnapshot,SemioSubsetSnapshot};
let f=corpus();let envelope:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🫙️prefix/✉️envelope.json")).unwrap();let expected=SemioSnapshot{schema:envelope["schema"].as_str().unwrap().into(),subset:SemioSubsetSnapshot::Flow(fixture(&f))};let grant=policy(&f);let database=fixture_database(&expected);let pointer=database.tables.as_ptr();let SemioSubsetSnapshot::Flow(flow)=&expected.subset else{unreachable!()};let label_bytes=flow.nodes[0].label.len();let mut cancelled_children=0;
for stop in [0,1,7,31,89,usize::MAX-1,usize::MAX]{let mut recipient=NativeDecodeRetirementRecipient::new();let mut events=0;let mut interior=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=events;events+=1;let canceled=stop==usize::MAX-1&&event.total==label_bytes&&event.completed>=65536&&event.completed<label_bytes;interior|=canceled;current!=stop&&!canceled};let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioSnapshot::from_sqlite_database(&database,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});assert_eq!(database.tables.as_ptr(),pointer);assert_eq!(heap.released_bytes,0,"envelope released original child or validation fields during production");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(actual)=>{assert_eq!(stop,usize::MAX);assert_eq!(actual,expected);assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;released+=r;},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if stop==usize::MAX-1{assert!(interior);assert!(heap.requested_bytes>=label_bytes);cancelled_children+=1;}let(b,r)=close_value(error,grant);born+=b;released+=r;}}
let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"whole envelope and original selected child physical conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}assert_eq!(cancelled_children,1);println!("[DEBUG] Original envelope selected Flow child shares exact physical allocation ledger, retains partial fields and original child cursor, and closes through denied/funded five-currency grants");
}

#[test]
fn native_prefix_original_flow_relational_workspace_and_cancelled_fields(){
let f=corpus();let grant=policy(&f);let expected=fixture(&f);let database=fixture_database(&expected);let original=database.tables.as_ptr();let label_bytes=expected.nodes[0].label.len();let mut actual_prefixes=0;
for stop in [0,1,7,31,89,usize::MAX-1,usize::MAX]{let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;let interior=stop==usize::MAX-1&&event.total==label_bytes&&event.completed>=65536&&event.completed<label_bytes;reached|=interior;current!=stop&&!interior};let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioFlowSnapshot::from_sqlite_database(&database,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});assert_eq!(database.tables.as_ptr(),original);assert_eq!(heap.released_bytes,0,"relational work released original owner before caller close");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(actual)=>{assert_eq!(stop,usize::MAX);assert_eq!(actual,expected);assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;released+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if stop==usize::MAX-1{assert!(reached);assert!(born>=label_bytes);}let(b,r)=close_value(error,grant);born+=b;released+=r}}
if recipient.has_owner(){actual_prefixes+=1;}let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"original relational field/index/schema scratch backing conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}assert!(actual_prefixes>=5);println!("[DEBUG] Actual original Flow relational workspace preserves schema/index/field owners through six cancellation boundaries, semantic completion and all5 caller-funded physical currencies");
}

#[test]
fn native_prefix_original_document_relational_blocks_and_cancelled_fields(){
use semio_s_artifact_stdio_semio::standards::v1::subsets::document::schema::snapshot::{SemioDocumentSnapshot,DocBlock,DocStyle,DocImage,DocRun,RunStyle,DocListItem,DocTableRow,DocTableCell};
let f=corpus();let grant=policy(&f);let neutral:serde_json::Value=serde_json::from_str(include_str!("../../../../../../📑️document/🚪️io/🪶️sqlite/📸️snapshot/🧫️fixtures/🔣️.json")).unwrap();
let text=neutral["text"].as_str().unwrap().repeat(f["labelRepetitions"].as_u64().unwrap()as usize);let text_bytes=text.len();let image_id=neutral["imageId"].as_str().unwrap();
let expected=SemioDocumentSnapshot{schema:neutral["schema"].as_str().unwrap().into(),styles:vec![DocStyle{id:"".into(),name:"root".into(),based_on:None},DocStyle{id:"child".into(),name:"child".into(),based_on:Some("".into())}],images:vec![DocImage{id:image_id.into(),mime:neutral["mime"].as_str().unwrap().into(),bytes:vec![0,255,127]}],blocks:vec![
DocBlock::Paragraph{style_id:Some("".into()),runs:vec![DocRun{text:text.clone(),style:RunStyle{bold:true,italic:true,underline:true,size:Some(-1.5),font:Some("".into()),color:Some("#ff0000".into()),link:Some("https://example.test".into())}},DocRun::plain("")]},
DocBlock::Heading{level:255,style_id:Some("child".into()),runs:vec![]},
DocBlock::List{ordered:true,items:vec![DocListItem{blocks:vec![DocBlock::PageBreak]},DocListItem{blocks:vec![]}]},
DocBlock::Table{rows:vec![DocTableRow{cells:vec![DocTableCell{blocks:vec![DocBlock::paragraph("cell")]},DocTableCell{blocks:vec![]}]}]},
DocBlock::Code{language:Some("".into()),text},DocBlock::Quote{blocks:vec![DocBlock::Quote{blocks:vec![]}]},
DocBlock::Image{image_id:image_id.into(),alt:"".into(),width:Some(0.0),height:None},DocBlock::PageBreak]};
let database=fixture_database(&expected);let original=database.tables.as_ptr();let mut retained=0;
for stop in [0,1,7,31,89,233,usize::MAX-1,usize::MAX]{
let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;let interior=stop==usize::MAX-1&&event.total==text_bytes&&event.completed>=65536&&event.completed<text_bytes;reached|=interior;current!=stop&&!interior};
let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioDocumentSnapshot::from_sqlite_database(&database,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});
assert_eq!(database.tables.as_ptr(),original);assert_eq!(heap.released_bytes,0,"document fields and scratch released before caller retirement");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(actual)=>{assert_eq!(stop,usize::MAX);assert_eq!(actual,expected);assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;released+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if stop==usize::MAX-1{assert!(reached);assert!(born>=text_bytes);}let(b,r)=close_value(error,grant);born+=b;released+=r}}
if recipient.has_owner(){retained+=1;}let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"complete original document block forest physical conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}
assert!(retained>=6);println!("[DEBUG] Original document complete eight block variants, nested collections, formatting, styles and octets preserve all5 denied currencies and physical conservation through seven cancellations");
}

#[test]
fn native_prefix_original_presentation_relational_shapes_and_cancelled_fields(){
use semio_s_artifact_stdio_semio::standards::v1::subsets::{presentation::schema::snapshot::{SemioPresentationSnapshot,SlideMaster,SlideLayout,Slide,SlideShape,SlideFrame,SlidePictureImage,SlideTableRow,SlideTableCell,PlaceholderKind},document::schema::snapshot::{DocBlock,DocRun},base::schema::geometry::SemioPoint2};
let f=corpus();let grant=policy(&f);let neutral:serde_json::Value=serde_json::from_str(include_str!("../../../../../../📽️presentation/🚪️io/🪶️sqlite/📸️snapshot/🧫️fixtures/🔣️.json")).unwrap();
let text=neutral["text"].as_str().unwrap().repeat(f["labelRepetitions"].as_u64().unwrap()as usize);let text_bytes=text.len();let frame=SlideFrame{origin:SemioPoint2{x:-1.0,y:2.0},width:3.5,height:4.25};
let expected=SemioPresentationSnapshot{schema:neutral["schema"].as_str().unwrap().into(),masters:vec![SlideMaster{id:neutral["masterId"].as_str().unwrap().into(),shapes:vec![SlideShape::Placeholder{frame,kind:PlaceholderKind::Title}]}],layouts:vec![SlideLayout{id:neutral["layoutId"].as_str().unwrap().into(),master_id:neutral["masterId"].as_str().unwrap().into(),shapes:vec![]}],slides:vec![Slide{id:neutral["slideId"].as_str().unwrap().into(),layout_id:Some(neutral["layoutId"].as_str().unwrap().into()),shapes:vec![
SlideShape::Placeholder{frame,kind:PlaceholderKind::Other{value:"".into()}},
SlideShape::TextBox{frame,blocks:vec![DocBlock::Paragraph{style_id:Some("external-style".into()),runs:vec![DocRun::plain(text)]},DocBlock::Image{image_id:"external-image".into(),alt:"".into(),width:None,height:Some(0.0)}]},
SlideShape::Picture{frame,image:SlidePictureImage{asset_id:neutral["picture"]["assetId"].as_str().unwrap().into(),mime:neutral["picture"]["mime"].as_str().unwrap().into(),bytes:neutral["picture"]["bytes"].as_array().unwrap().iter().map(|v|v.as_u64().unwrap()as u8).collect()}},
SlideShape::Table{frame,rows:vec![SlideTableRow{cells:vec![SlideTableCell{blocks:vec![DocBlock::Quote{blocks:vec![DocBlock::PageBreak]}]},SlideTableCell{blocks:vec![]}]}]}],
notes:vec![DocBlock::Code{language:Some("".into()),text:"notes".into()}]},Slide{id:"".into(),layout_id:None,shapes:vec![],notes:vec![]}]};
let database=fixture_database(&expected);let original=database.tables.as_ptr();let mut retained=0;
for stop in [0,1,7,31,89,233,usize::MAX-1,usize::MAX]{
let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;let interior=stop==usize::MAX-1&&event.total==text_bytes&&event.completed>=65536&&event.completed<text_bytes;reached|=interior;current!=stop&&!interior};
let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioPresentationSnapshot::from_sqlite_database(&database,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});
assert_eq!(database.tables.as_ptr(),original);assert_eq!(heap.released_bytes,0,"presentation fields and scratch released before caller retirement");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(actual)=>{assert_eq!(stop,usize::MAX);assert_eq!(actual,expected);assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;released+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if stop==usize::MAX-1{assert!(reached);assert!(born>=text_bytes);}let(b,r)=close_value(error,grant);born+=b;released+=r}}
if recipient.has_owner(){retained+=1;}let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"complete original presentation shape and block forest physical conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}
assert!(retained>=6);println!("[DEBUG] Original presentation four shape variants, nested block collections, notes, master/layout references and picture octets preserve all5 denied currencies through seven cancellations");
}

#[test]
fn native_prefix_original_value_relational_forest_and_cancelled_variants(){
use semio_s_artifact_stdio_semio::standards::v1::subsets::value::schema::snapshot::{SemioValueSnapshot,SemioValue,SemioValueEntry,SemioValueNode,ValueId};
let f=corpus();let grant=policy(&f);let neutral:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🫙️prefix/🌳️forest.json")).unwrap();
let repetitions=f["labelRepetitions"].as_u64().unwrap()as usize;let text=neutral["text"].as_str().unwrap().repeat(repetitions);let text_bytes=text.len();let octets=neutral["octets"].as_array().unwrap().iter().map(|value|value.as_u64().unwrap()as u8).collect::<Vec<_>>().repeat(repetitions*2);let octet_bytes=octets.len();let node=neutral["nodeId"].as_str().unwrap();let key=neutral["key"].as_str().unwrap();
let expected=SemioValueSnapshot{schema:neutral["schema"].as_str().unwrap().into(),root:SemioValue::Map{entries:vec![
SemioValueEntry{key:key.into(),value:SemioValue::Null},SemioValueEntry{key:key.into(),value:SemioValue::Bool{value:true}},
SemioValueEntry{key:key.into(),value:SemioValue::Int{lexeme:neutral["integerLexeme"].as_str().unwrap().into()}},SemioValueEntry{key:key.into(),value:SemioValue::Float{lexeme:neutral["floatLexeme"].as_str().unwrap().into()}},
SemioValueEntry{key:key.into(),value:SemioValue::Str{value:text}},SemioValueEntry{key:key.into(),value:SemioValue::Bytes{value:octets}},
SemioValueEntry{key:key.into(),value:SemioValue::List{items:vec![SemioValue::Null]}},SemioValueEntry{key:key.into(),value:SemioValue::Ref{id:ValueId{value:node.into()}}}]},nodes:vec![SemioValueNode{id:ValueId{value:node.into()},value:SemioValue::Bool{value:false}}]};
let database=fixture_database(&expected);let original=database.tables.as_ptr();let mut retained=0;
for(stop,mode)in neutral["stops"].as_array().unwrap().iter().map(|value|(value.as_u64().unwrap()as usize,"count")).chain(neutral["interiorPhases"].as_array().unwrap().iter().map(|value|(usize::MAX,value.as_str().unwrap()))).chain(std::iter::once((usize::MAX,"success"))){
let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut reached=false;let target=if mode=="text"{text_bytes}else{octet_bytes};let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;let interior=mode!="count"&&mode!="success"&&event.total==target&&event.completed>=65536&&event.completed<target;reached|=interior;current!=stop&&!interior};
let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=SemioValueSnapshot::from_sqlite_database(&database,&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});
assert_eq!(database.tables.as_ptr(),original);assert_eq!(heap.released_bytes,0,"original recursive value fields or scalar forest released before caller close");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(actual)=>{assert_eq!(mode,"success");assert_eq!(actual,expected);assert_eq!(admitted,heap.requested_bytes);let(b,r)=close_value(actual,grant);born+=b;released+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if mode=="text"||mode=="octets"{assert!(reached);assert!(born>=target);}let(b,r)=close_value(error,grant);born+=b;released+=r}}
if recipient.has_owner(){retained+=1;}let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"all original recursive value variants and links physical conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}
assert!(retained>=7);println!("[DEBUG] Original value forest preserves nine variants, exact numeric lexemes, duplicate ordered map keys, graph references and all5 denied close currencies through six count and two interior cancellations");
}
#[test]
fn native_prefix_original_projection_text_rows_and_cancelled_fields(){
use semio_s_artifact_stdio_semio::standards::v1::subsets::text::schema::snapshot::{SemioTextSnapshot,SemioTextRun,SemioTextMark,SemioTextMarkKind};
let f=corpus();let grant=policy(&f);let neutral:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🫙️prefix/🧮️projection.json")).unwrap();let content=neutral["content"].as_str().unwrap().repeat(f["labelRepetitions"].as_u64().unwrap()as usize);let length=content.len();
let expected=SemioTextSnapshot{schema:neutral["schema"].as_str().unwrap().into(),runs:vec![SemioTextRun{language:neutral["language"].as_str().unwrap().into(),content,marks:vec![SemioTextMark{kind:SemioTextMarkKind::Link,href:neutral["href"].as_str().unwrap().into()}]}]};let original=expected.runs[0].content.as_ptr();
for stop in [0,1,7,31,89,233,usize::MAX-1,usize::MAX]{
let mut recipient=NativeDecodeRetirementRecipient::new();let mut count=0;let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{let current=count;count+=1;let interior=stop==usize::MAX-1&&event.total==length&&event.completed>=65536&&event.completed<length;reached|=interior;current!=stop&&!interior};
let((result,admitted),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||{let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());control.install_native_retirement_recipient(&mut recipient).unwrap();let result=expected.to_sqlite_database(&mut control);(result,SqliteDatabaseLimits::default().max_allocation_bytes-control.allocation_remaining_bytes())});
assert_eq!(expected.runs[0].content.as_ptr(),original);assert_eq!(heap.released_bytes,0,"original projection schema, census, row or field released before caller close");let(mut born,mut released)=(heap.requested_bytes,0);
match result{Ok(database)=>{assert_eq!(stop,usize::MAX);assert_eq!(admitted,heap.requested_bytes);for(table,rows)in neutral["expectedRows"].as_object().unwrap(){assert_eq!(database.table(table).unwrap().rows.len(),rows.as_u64().unwrap()as usize);}let run=database.table("semio_text_run").unwrap().single_row().unwrap();assert_eq!(run.rowid,1);assert_eq!(run.integer(1).unwrap(),1);assert_eq!(run.text(3).unwrap(),expected.runs[0].language);assert_eq!(run.text(4).unwrap(),expected.runs[0].content);let mark=database.table("semio_text_mark").unwrap().single_row().unwrap();assert_eq!(mark.rowid,1);assert_eq!(mark.integer(1).unwrap(),1);assert_eq!(mark.text(3).unwrap(),neutral["kind"].as_str().unwrap());assert_eq!(mark.text(4).unwrap(),neutral["href"].as_str().unwrap());let(b,r)=close_value(database,grant);born+=b;released+=r},Err(error)=>{assert_eq!(error.kind,ValueRefusalKind::Canceled);if stop==usize::MAX-1{assert!(reached);assert!(born>=length);}let(b,r)=close_value(error,grant);born+=b;released+=r}}
let(b,r)=close(&mut recipient,grant);born+=b;released+=r;assert_eq!(born,released,"complete original projection physical conservation");let(_,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(recipient));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));
}
println!("[DEBUG] Original text projection exact per-table identities, schema/census and interior field custody preserve five denied currencies and physical conservation through seven cancellations");
}                                                                                                                                                