//! 🛫️ The authored native owner must emit exact ordinary bytes with cumulative admission and real interior cancellation.
use store::{ArtifactDsl,ArtifactPack,ArtifactSqliteSnapshot,sqlite_snapshot::{SnapshotEncoding,SqliteDatabaseLimits,SqliteSnapshotControl,SqliteSnapshotPhase}};
pub(crate) fn assert_output<T:ArtifactDsl+ArtifactPack+ArtifactSqliteSnapshot>(snapshot:&T){
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let actual=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();let expected=match encoding{SnapshotEncoding::Binary=>store::os_io::IoPayload::Binary(snapshot.encode_pack()),SnapshotEncoding::Text=>store::os_io::IoPayload::Text(snapshot.print_dsl())};assert!(actual==expected,"controlled native wire differs");let count=match &actual{store::os_io::IoPayload::Binary(bytes)=>bytes.len(),store::os_io::IoPayload::Text(text)=>text.len()};assert!(count>65536);
 let exact=SqliteDatabaseLimits{max_value_bytes:count,max_file_bytes:count,..SqliteDatabaseLimits::default()};let admitted=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,exact)).unwrap();assert!(actual==admitted,"exact owned output budget changed wire");
 for measure in[true,false]{let mut reached=false;let error=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |event|{let cancel=event.phase==SqliteSnapshotPhase::EncodeNative&&event.completed>=65536&&(if measure{event.total==0}else{event.total>65536&&event.completed<event.total});reached|=cancel;!cancel},SqliteDatabaseLimits::default())).unwrap_err();assert!(reached&&error.contains("cancel"),"{error}")}
 for limits in[SqliteDatabaseLimits{max_value_bytes:count-1,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_file_bytes:count-1,..SqliteDatabaseLimits::default()},SqliteDatabaseLimits{max_rows:0,..SqliteDatabaseLimits::default()}]{assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).is_err())}
 assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());
 }
}

/// 🌳️ The independent engine precedes late schema-copy cancellation on the authored small retirement stack.
pub(crate) fn assert_reconstruction<T:ArtifactSqliteSnapshot+Send+'static>(snapshot:T,schema_bytes:usize,stack_bytes:usize){
 use std::{io::Write,process::{Command,Stdio}};
 let database=snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();snapshot.retire_sqlite_snapshot();
 let bytes=store::sqlite_snapshot::export_sqlite_database(&database,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();
 let script="import{Database}from'bun:sqlite';const d=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(d.query('PRAGMA integrity_check').get().integrity_check!=='ok'||d.query('PRAGMA foreign_key_check').all().length||d.query('SELECT COUNT(*) n FROM sqlite_schema WHERE type=\"table\"').get().n<3)throw Error('relational oracle');await Bun.write(Bun.stdout,d.serialize());d.close();";
 let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let database=store::sqlite_snapshot::import_sqlite_database(&output.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap();
 std::thread::Builder::new().stack_size(stack_bytes).spawn(move||{let mut reached=false;let result=T::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |event|{let cancel=event.phase==SqliteSnapshotPhase::ReconstructSnapshot&&event.total==schema_bytes&&event.completed>=65536&&event.completed<event.total;reached|=cancel;!cancel},SqliteDatabaseLimits::default()));match result{Ok(snapshot)=>{snapshot.retire_sqlite_snapshot();panic!("late reconstruction cancellation was ignored")},Err(error)=>assert!(reached&&error.contains("cancel"),"{error}")}}).unwrap().join().unwrap();
}
