# SPDX-License-Identifier: AGPL-3.0-only
# #region 🔖️Compose
# Dev stack: a single workspace app container. Neo4j 5 Community runs inside `compose` and publishes localhost Bolt/HTTP ports.
name: compose
services:
  compose:
    image: compose
    container_name: compose
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    shm_size: 1gb
    environment:
      DEVCONTAINER: "true"
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DATABASE: compose
      NEO4J_TELEMETRY: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/workspaces/semio:cached
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    command: ["sleep", "infinity"]
# #endregion 🔖️Compose
