import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname, sep } from "node:path";
import { createHash } from "node:crypto";
const ticket=resolve(import.meta.dir,"..");let root=ticket;while(!existsSync(resolve(root,"nx.json")))root=dirname(root);
const [command,epoch,proofArg]=process.argv.slice(2);if(!((command==="release"&&epoch==="3")||(command==="release-pack"&&epoch==="4"))||!proofArg)throw Error("Exact live workspace release required");
const directory=resolve(ticket,"🗑️generated/pack-live-native/workspace-"+epoch),sha=(source:string|Buffer)=>createHash("sha256").update(source).digest("hex"),read=(path:string)=>JSON.parse(readFileSync(path,"utf8")),proofPath=resolve(proofArg),proof=read(proofPath),planPath=resolve(directory,"current-plan-1.json"),plan=read(planPath),metadataPath=resolve(directory,"metadata-terminal-1.json"),metadata=read(metadataPath),out=resolve(directory,"released-final-source-current-1.json");
if(existsSync(out)||!proofPath.startsWith(directory+sep)||proof.ready!==true||metadata.exitCode!==0||metadata.externalAdvances.length)throw Error("Independent current checkpoint or immutable release refused");
const outcomes=(command==="release-pack"?[0]:[0,1]).map(index=>{const receipts=Object.fromEntries(["terminal","runtime","post","origin-diagnostic-review"].map(kind=>[kind,resolve(directory,"native-"+kind+"-"+index+".json")])),terminal=read(receipts.terminal),runtime=read(receipts.runtime),post=read(receipts.post),origin=read(receipts["origin-diagnostic-review"]);if(terminal.exitCode!==0||!runtime.wholeSelectedGreen||runtime.selected!==(index===0?112:264)||runtime.completed!==runtime.passed||runtime.skipped||post.ownedGaps.length||origin.currentGaps.length)throw Error("Actual whole outcome or consumed-current gap");return{index,receipts:Object.entries(receipts).map(([kind,path])=>({kind,path,sha256:sha(readFileSync(path))})),runtime:{selected:runtime.selected,completed:runtime.completed,passed:runtime.passed,skipped:runtime.skipped},compiler:{units:read(resolve(directory,"native-compiler-post-"+index+".json")).selectedUnits.length,checks:origin.inputs.length,retainedPreGaps:origin.retainedSnapshotPreGaps.length,unavailableExternalPre:origin.unavailableExternalPre.length,unavailableGeneratedPre:origin.unavailableGeneratedPre.length,otherPreFrontiers:origin.otherPreFrontiers.length,currentGaps:origin.currentGaps.length}};});
const ownedChecks=plan.owned.map((row:any)=>({path:row.path,expected:row.afterHash,current:existsSync(resolve(root,row.path))?sha(readFileSync(resolve(root,row.path))):null}));if(ownedChecks.some((row:any)=>row.expected!==row.current))throw Error("Actual owned publication successor changed before release");
const currentFrames=plan.snapshotAssets.map((row:any)=>{const path=resolve(root,row.path),before=Buffer.from(row.source,"base64"),current=existsSync(path)?readFileSync(path):null,a=before.toString("base64"),b=current?.toString("base64")??null;return{path,before:a,current:b,encoding:"base64",beforeHash:sha(before),currentHash:current?sha(current):null,exact:current!==null&&before.equals(current),forward:{start:0,delete:a,insert:b},inverse:{start:0,delete:b,insert:a},authorship:"unknown",semanticEquivalence:false};});
const foreignCurrent=currentFrames.filter((row:any)=>!row.exact);mkdirSync(dirname(out),{recursive:true});writeFileSync(out,JSON.stringify({at:new Date().toISOString(),proof:{path:proofPath,sha256:sha(readFileSync(proofPath))},plan:{path:planPath,sha256:sha(readFileSync(planPath))},metadata:{path:metadataPath,sha256:sha(readFileSync(metadataPath))},outcomes,ownedChecks,currentFrames,foreignCurrent,sourceCheckpointReleased:true,compilerActive:false,productionPublished:true,sourceWritesOutsideTicket:false,scope:"Actual unchanged selected whole owner GREEN and time-scoped compiled source checks; later unowned current frames qualified separately without runtime equivalence or Specific deletion claim"},null,2));console.log(JSON.stringify({out,outcomes:outcomes.map(row=>row.runtime),ownedGaps:0,foreignCurrent:foreignCurrent.map((row:any)=>row.path),sourceCheckpointReleased:true}));

