[package]
name = "procedural-wire-format-proof"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "proof"
path = "main.rs"

[dependencies]
protocol = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
dsl = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
flow_core = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel", default-features = false }
old_2d_protocol = { path = "/Users/ueli/Documents/semio/✏️s/🔌️plugins/🌀️procedural/🎛️apps/◻2d/🔨️modules/📡️protocol/⚡️implementations/🦀️rust", package = "semio-s-app-procedural-2d-protocol" }
old_3d_protocol = { path = "/Users/ueli/Documents/semio/✏️s/🔌️plugins/🌀️procedural/🎛️apps/🧊️3d/🔨️modules/📡️protocol/⚡️implementations/🦀️rust", package = "semio-s-app-procedural-3d-protocol" }
old_3d_engine = { path = "/Users/ueli/Documents/semio/✏️s/🔌️plugins/🌀️procedural/🎛️apps/🧊️3d/🔨️modules/⚙️engine/⚡️implementations/🦀️rust", package = "semio-s-app-procedural-3d-engine" }
new_procedural = { path = "/Users/ueli/Documents/semio/✏️s/🔌️plugins/🌀️procedural/📦️packages/🦀️rust", package = "semio-s-plugin-procedural" }

[workspace]
members = ["."]
