"""🧭️ S20 reachability census over the current plugin descriptors (`<plugin>/🔣️.json`, regenerated by the
chain's describe step): every declared verb (app action, window-kind action, app command, mode command, plugin
command) with its interactive-job classification, palette/keybinding control and window kinds. A verb is
DISPATCH-DEAD when its classification is not `migrated` (UI dispatch refuses it: `interactive-job.not-ui-safe`),
and CONTROL-LESS when it is migrated but no chrome control (palette, window action pane, context menu, keybinding)
names it — the latter may still be dispatched by a guest-rendered control, which `--source` checks by id."""
import json, os, sys, collections, subprocess
ROOT = "/Users/ueli/Documents/semio"
REG = json.load(open(f"{ROOT}/🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/📇️registry/🤖️generated/🔌️plugins.json"))
FRAMEWORK = {"setActiveUtility", "setActiveTool", "startIntroduction", "setHistoryCommandFilter", "noteShellCommand", "copy", "cut", "paste",
             "recordTutorial", "clearSelection", "interactionHover", "interactionSelect", "selectAll", "setInteractionGranularity", "setSelectionMode"}

def owner_root(entry):
    return os.path.join(ROOT, os.path.dirname(os.path.dirname(entry["cratePath"])))

def label(row, lang):
    return ((row.get("label") or {}).get("native") or {}).get(lang, "")

def rows():
    for entry in REG:
        root = owner_root(entry)
        descriptor = json.load(open(os.path.join(root, "🔣️.json")))
        manifest = descriptor["manifest"]
        plugin = manifest["pluginId"]
        mtime = os.path.getmtime(os.path.join(root, "🔣️.json"))
        for app in manifest.get("apps", []):
            keyed = {binding.get("actionId") or binding.get("commandId") for binding in app.get("keybindings", []) if isinstance(binding, dict)}
            seen = collections.OrderedDict()
            for wk in app.get("windowKinds", []):
                for action in wk.get("actions", []):
                    seen.setdefault(action["id"], (action, []))[1].append(wk["id"])
            for action in app.get("actions", []):
                seen.setdefault(action["id"], (action, []))[1].append("*")
            for aid, (action, wks) in seen.items():
                if action["kind"] in ("history", "clipboard") or aid in FRAMEWORK:
                    continue
                yield dict(plugin=plugin, root=root, app=app["id"], shape="action", row=action, windows=wks, keyed=aid in keyed or bool(action.get("keys")), mtime=mtime)
            for command in app.get("commands", []):
                yield dict(plugin=plugin, root=root, app=app["id"], shape="app-command", row=command, windows=[], keyed=bool(command.get("keybindings")), mtime=mtime)
            for mode in app.get("modes", []):
                for command in mode.get("commands", []):
                    yield dict(plugin=plugin, root=root, app=app["id"], shape=f"mode-command:{mode['id']}", row=command, windows=[], keyed=bool(command.get("keybindings")), mtime=mtime)
        for command in manifest.get("commands", []):
            yield dict(plugin=plugin, root=root, app=None, shape="plugin-command", row=command, windows=[], keyed=bool(command.get("keybindings")), mtime=mtime)

def main():
    out_path = sys.argv[1]
    source = "--source" in sys.argv
    out = []
    for r in rows():
        row = r["row"]
        job = row.get("semantics", {}).get("execution", {}).get("interactiveJob", "unclassified")
        kind = row.get("kind", "command")
        rec = {"plugin": r["plugin"], "app": r["app"], "shape": r["shape"], "id": row["id"], "kind": kind, "job": job,
               "inPalette": bool(row.get("inPalette", False)), "keyed": r["keyed"], "windows": r["windows"],
               "label_en": label(row, "en"), "label_de": label(row, "de"), "owner": r["root"][len(ROOT) + 1:]}
        rec["dispatchDead"] = job != "migrated"
        rec["chromeControl"] = rec["inPalette"] or rec["keyed"]
        out.append(rec)
    if source:
        for rec in out:
            if rec["dispatchDead"] or rec["chromeControl"] or rec["kind"] == "interaction":
                continue
            needle = f'"{rec["id"]}"'
            hit = subprocess.run(["/usr/bin/grep", "-rlF", "--include=*.rs", "--include=*.ts", "--include=*.tsx", needle, os.path.join(ROOT, rec["owner"])], capture_output=True, text=True).stdout.split()
            rec["sourceRefs"] = len([h for h in hit if "/🧪️tests/" not in h and "/target/" not in h])
    json.dump(out, open(out_path, "w"), ensure_ascii=False, indent=1)
    dead = [r for r in out if r["dispatchDead"]]
    print(f"verbs={len(out)} dispatch-dead={len(dead)}")
    by = collections.Counter((r["plugin"], r["job"]) for r in dead)
    for (plugin, job), n in sorted(by.items()):
        print(f"  {plugin:36s} {job:26s} {n}")
    for r in dead:
        print(f"    DEAD {r['plugin']:14s} {r['app'] or '-':44s} {r['shape']:16s} {r['id']:34s} {r['kind']:12s} {r['job']:24s} palette={r['inPalette']} keyed={r['keyed']} windows={','.join(r['windows'])}")
    agent_controlless = [r for r in out if not r["dispatchDead"] and not r["chromeControl"] and r["kind"] not in ("interaction",)]
    print(f"migrated-without-chrome-control={len(agent_controlless)} (inPalette=false, no keybinding; guest-rendered controls not visible here)")
    if source:
        zero = [r for r in agent_controlless if r.get("sourceRefs", 1) <= 1]
        print(f"  of which referenced by id in <=1 non-test source file of the owner: {len(zero)}")
        for r in zero:
            print(f"    NOCTRL {r['plugin']:14s} {r['app'] or '-':44s} {r['shape']:16s} {r['id']:34s} {r['kind']:10s} refs={r.get('sourceRefs')}")

if __name__ == "__main__":
    main()
