// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 🧭️ A logical 9-point placement, `Start`/`End` rather than `Left`/`Right` so it stays correct under
 * RTL locales without a renderer-side flip (CLAUDE.md's multi-language accessibility mandate).
 */
export type Anchor = "topStart" | "top" | "topEnd" | "start" | "center" | "end" | "bottomStart" | "bottom" | "bottomEnd";
