// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";

/**
 * 🗝️ One row of a [`Component::KeyValueList`].
 */
export type KeyValueEntry = { label: Label, value: string, };
