// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 🏷️ Display-ready UI text carried on the wire.
 *
 * ⚠️ Decision (flagged per packet brief): the old `UiNode`'s `Label` (`crate::wgpu::Label` in
 * `🧰️framework/🔨️modules/🖱️ui/📦️packages/🦀️rust/🎯️targets/🧊️wgpu/🦀️label.rs`) is NOT reused here. It
 * is defined inside the old wgpu-target UI package, imports that package's own `Locale`/
 * `Terminology` axes, and its whole point (`From<LabelText>` wired to the `app_labels!` macro,
 * no `From<&str>`) is a compile-time-checked-label enforcement mechanism that lives at the
 * authoring boundary, not the wire boundary — and this crate must not depend on that package at
 * all (no engine, no wgpu; see `📦️glue.rs`). This is therefore a minimal, independent transparent
 * string. The localization/terminology resolution that used to happen via `LabelText::fill` still
 * happens upstream of the runtime (manifest/host), before a `Label` ever reaches this contract.
 */
export type Label = string;
