// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsoluteLayout } from "./AbsoluteLayout";
import type { GridLayout } from "./GridLayout";
import type { LeafLayout } from "./LeafLayout";
import type { OverlayLayout } from "./OverlayLayout";
import type { ScrollLayout } from "./ScrollLayout";
import type { StackLayout } from "./StackLayout";

/**
 * 🧬️ The renderer-neutral layout vocabulary a [`crate::UiNodeRecord`] carries — expressible by CSS
 * flex/grid, by a taffy tree, and by native stacks alike. No CSS strings, no taffy types, no pixel
 * geometry: every metric is a closed enum over [`SpaceToken`].
 */
export type LayoutSpec = { "kind": "leaf" } & LeafLayout | { "kind": "stack" } & StackLayout | { "kind": "grid" } & GridLayout | { "kind": "overlay" } & OverlayLayout | { "kind": "scroll" } & ScrollLayout | { "kind": "absolute" } & AbsoluteLayout;
