// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { EdgeSpace } from "./EdgeSpace";

/**
 * 🪟️ A positioning context whose children stack on top of one another anchored to the box —
 * modals, popovers, tooltips.
 */
export type OverlayLayout = { anchor: Anchor, inset: EdgeSpace, dismissible: boolean, };
