// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuotaKind } from "./QuotaKind";
import type { UiContractViolation } from "./UiContractViolation";
import type { UiNodeId } from "./UiNodeId";
import type { UiRevision } from "./UiRevision";

/**
 * 🚫️ Why [`apply_patch`] rejected a [`crate::UiPatch`] — carries enough detail (both revisions, the
 * exceeded quota with its actual/max, or the full violation list) for the existing `patch-rejected`
 * wire event to explain itself and for the sender to resynchronise.
 */
export type PatchRejection = { "type": "revisionMismatch", expected: UiRevision, actual: UiRevision, } | { "type": "unknownNode", id: UiNodeId, } | { "type": "quotaExceeded", quota: QuotaKind, actual: number, max: number, } | { "type": "invariantViolated", violations: Array<UiContractViolation>, };
