// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 💍️ Props for `Component::Ring`. `on_change` moved to the record's `bindings`.
 */
export type RingProps = { orbId: string, t: number, };
