// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 📍️ Where a [`RowAction`] paints: on the tree row itself, or folded into the row's context menu.
 */
export type RowActionPlacement = "row" | "menu";
