// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ➖️ Props for `Component::Separator`. Every field the old `UiSeparatorNode` carried
 * (`presence`, `menu`) now lives on the record, so this is intentionally empty — kept as its own
 * struct (rather than a unit variant) purely for structural symmetry with every other component.
 */
export type SeparatorProps = Record<string, never>;
