// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 🎚️ Props for `Component::Slider`. `on_change` moved to the record's `bindings`.
 */
export type SliderProps = { value: number, min: number, max: number, step: number, unit: string | null, };
