// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 📐️ Closed spacing scale a renderer resolves against the active theme's spacing ramp — never a raw
 * `f32`/px. tokens.json's `spacing` table today only names `compact`/`touch` (see [`crate::Density`]);
 * no full ramp exists there yet, so this scale is the shape this packet's own brief specifies
 * verbatim (`None,Xs,Sm,Md,Lg,Xl,…`) pending a registrar-added token set — flagged in the packet report.
 */
export type SpaceToken = "none" | "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
