// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 🖼️ The 15 embeddable product surface kinds. Ported VERBATIM from the wgpu target's `SurfaceKind`,
 * same serde renames — including the one real inconsistency already in the wire format
 * (`virtualFileSystem` is camelCase where every sibling is kebab-case). Preserved rather than
 * "cleaned up" because the packet brief demands a byte-identical port; a rename is a breaking wire
 * change for a later packet to make deliberately, not a silent side effect of this one.
 */
export type SurfaceKind = "canvas-2d" | "world-3d" | "node-graph" | "text-editor" | "table" | "paint-2d" | "virtualFileSystem" | "tiled-map" | "board-2d" | "icon-render" | "ink-canvas" | "graph-timeline" | "block-list" | "diff-view" | "event-feed";
