import { interactivityArtifactSubmitFailures } from "../../../../../../../../📜️script.ts";

/** 🧪️ Executes interactivity artifact submit policy assertions. */
export function interactivityArtifactSubmitSelfTests(): void {
  const fixtures = `artifact_submit_late_readiness_parks_then_one_shot_wake_reschedules artifact_submit_pool_saturation_without_later_ingress_retains_exact_job artifact_submit_cancel_before_during_after_preserves_exact_owner artifact_submit_stale_generation_and_slot_aba_cannot_consume_current_work artifact_submit_missing_handle_terminalizes_without_mailbox_mutation artifact_submit_terminal_job_work_result_take_resume_and_close_one_owner artifact_submit_item_cap_plus_one_and_nested_bytes_plus_one_return_owner artifact_runner_one_grant_polls_one_turn_and_never_blocks_on`;
  const goodEngine = `//#region 🔖️ArtifactHandle const ARTIFACT_SUBMIT_PAGE_BYTES: u64 = 16 * 1024 const ARTIFACT_SUBMIT_OPERATION_PAGES: u64 = 64 const ARTIFACT_SUBMIT_TOTAL_PAGES: u64 = 1024 const ARTIFACT_SUBMIT_OPERATION_ITEMS: usize = 64 ArtifactSubmitAdmission::try_claim(items, bytes) batch.envelopes.capacity() envelope.dependencies.capacity() envelope.diff.payload.capacity() envelope.inverse.payload.capacity() dependency.0.capacity() impl std::task::Wake for ArtifactSubmitWake self.generation == state.generation self.scheduled.compare_exchange(false, true SubmitProgress::Waiting self.pool.try_submit(Lane::Io, job) error.into_job() self.pool.callback_at retry_generation ARTIFACT_SUBMIT_RETRY_LIMIT pub fn take_terminal_job pub fn take_terminal_work pub fn take_terminal_result pub fn take_actor_terminal_job pub fn close_step pub fn terminal_is_empty pub fn resume(mut self) fn drive_one(self: Arc<Self>, generation: u64) { if generation != self.generation { return; } if self.authority.generation() != self.authority_generation {} self.scheduled.store matches!(work.as_ref(), Some(ArtifactSubmitWorkOwner::Request { .. })) self.authority.submit_retained std::pin::Pin::new(future).poll(&mut context) } fn close_one ArtifactEngine::create_retained ArtifactEngine::open_retained ${fixtures} //#endregion 🔖️ArtifactHandle`;
  const goodArtifact = `type ArtifactBuildFuture type ArtifactTurnFuture impl Wake ArtifactRunner fn submit_exact { self.pool.try_submit(semio_framework_async::Lane::UserVisible, job) self.pool.callback_at } fn run_turn { future.as_mut().poll(&mut context) Self::start_turn(engine, envelope.payload) } pub fn close_step { let closed = close(); if closed { terminal.take(); } } pub fn terminal_is_empty impl ArtifactRunnerTerminalJob { pub fn close(mut self) { let closed = close(); if !closed { terminal_job = Some(owner); } } } impl Drop for ArtifactRunnerTerminalJob pub fn submit_retained { self.address.ask(Priority::Command } pub async fn query pub async fn frontier //#region 🧪️Tests`;
  const mutations = [
    ["outer-block-on", goodEngine.replace("//#endregion 🔖️ArtifactHandle", "block_on(future) //#endregion 🔖️ArtifactHandle"), goodArtifact],
    ["inner-runner-block-on", goodEngine, goodArtifact.replace("future.as_mut().poll(&mut context)", "block_on(engine.submit())")],
    ["missing-byte-ledger", goodEngine.replace("envelope.inverse.payload.capacity()", "0"), goodArtifact],
    ["stale-after-mutation", goodEngine.replace("if generation != self.generation { return; } if self.authority.generation() != self.authority_generation {} self.scheduled.store", "self.scheduled.store; if generation != self.generation { return; }"), goodArtifact],
    ["poll-loop", goodEngine.replace("std::pin::Pin::new(future).poll(&mut context)", "loop { std::pin::Pin::new(future).poll(&mut context) }"), goodArtifact],
    ["wake-storm", goodEngine.replace("self.scheduled.compare_exchange(false, true", "self.scheduled.store(true"), goodArtifact],
    ["quiet-saturation-strand", goodEngine.replace("self.pool.callback_at", "drop"), goodArtifact],
    ["missing-terminal-work", goodEngine.replace("pub fn take_terminal_work", "fn inspect_terminal_work"), goodArtifact],
    ["blocking-mailbox", goodEngine, goodArtifact.replace("self.address.ask(Priority::Command", "self.address.ask_blocking(Priority::Command")],
    ["sync-live-constructor", goodEngine.replace("ArtifactEngine::create_retained", "move || db_artifact::ArtifactEngine::create("), goodArtifact],
    ["drop-runner-before-close", goodEngine, goodArtifact.replaceAll("if !closed { terminal_job = Some(owner); }", "drop(owner);")],
  ] as const;
  for (const [name, engine, artifact] of mutations) if (interactivityArtifactSubmitFailures(engine, artifact).length === 0) throw new Error(`[verify interactivity] ArtifactHandle submit self-test ${name} was falsely accepted.`);
  if (interactivityArtifactSubmitFailures(goodEngine, goodArtifact).length !== 0) throw new Error("[verify interactivity] ArtifactHandle submit self-test retained authority was falsely rejected.");
}
