/** forms facet WASM facades */
export * as forms_schema from "../../🗿️artifacts/📋️forms/🧬️schema/🟦️component.ts";
export * as forms_snapshot from "../../🗿️artifacts/📋️forms/🧬️schema/📸️snapshot/🟦️component.ts";
export * as forms_snapshot_text from "../../🗿️artifacts/📋️forms/🧬️schema/📸️snapshot/📝️text/🟦️component.ts";
export * as forms_snapshot_binary from "../../🗿️artifacts/📋️forms/🧬️schema/📸️snapshot/💾️binary/🟦️component.ts";
export * as forms_diff from "../../🗿️artifacts/📋️forms/🧬️schema/🔺️diff/🟦️component.ts";
export * as forms_diff_text from "../../🗿️artifacts/📋️forms/🧬️schema/🔺️diff/📝️text/🟦️component.ts";
export * as forms_diff_binary from "../../🗿️artifacts/📋️forms/🧬️schema/🔺️diff/💾️binary/🟦️component.ts";
export * as forms_mutations from "../../🗿️artifacts/📋️forms/🧬️schema/🧬️mutations/🟦️component.ts";
export * as forms_mutations_text from "../../🗿️artifacts/📋️forms/🧬️schema/🧬️mutations/📝️text/🟦️component.ts";
export * as forms_mutations_binary from "../../🗿️artifacts/📋️forms/🧬️schema/🧬️mutations/💾️binary/🟦️component.ts";
export * as forms_io from "../../🗿️artifacts/📋️forms/🚪️io/🟦️component.ts";
export * as forms_builder from "../../🗿️artifacts/📋️forms/🏗️builder/🟦️component.ts";
export * as forms_decomposer from "../../🗿️artifacts/📋️forms/🪓️decomposer/🟦️component.ts";
