/** forms facet WASM facades */
export * as forms_schema from "../../🗿️artifacts/📋️forms/🧬️schema/🟦️component.ts";
export * as forms_snapshot_schema from "../../🗿️artifacts/📋️forms/📸️snapshot/🧬️schema/🟦️component.ts";
export * as forms_diff_schema from "../../🗿️artifacts/📋️forms/🔺️diff/🧬️schema/🟦️component.ts";
export * as forms_diff from "../../🗿️artifacts/📋️forms/🔺️diff/🟦️component.ts";
export * as forms_dsl from "../../🗿️artifacts/📋️forms/🗣️dsl/🟦️component.ts";
export * as forms_pack from "../../🗿️artifacts/📋️forms/📸️snapshot/🎒️pack/🟦️component.ts";
export * as forms_op from "../../🗿️artifacts/📋️forms/🔧️op/🟦️component.ts";
export * as forms_spr from "../../🗿️artifacts/📋️forms/📡️spr/🟦️component.ts";
