[package]
name = "semio-s-app-norm-en1999-ui"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
description = "EN 1999 app - DocumentApp facade (constitutional: ui)"

[lints]
workspace = true
[lib]
path = "../../../../../../../../../✏️s/🔌plugin/📕norm/🎛️app/📘en1999/🔨module/🖱️ui/⚡️implementation/🦀rust/📦lib.rs"

[dependencies]
en1999 = { path = "../../../../../../../../../✏️s/🔌plugin/📕norm/🎛️app/📘en1999/⚡️implementation/🦀rust", package = "semio-s-app-norm-en1999" }
en1999_engine = { path = "../../../../../../../../../✏️s/🔌plugin/📕norm/🎛️app/📘en1999/🔨module/⚙️engine/⚡️implementation/🦀rust", package = "semio-s-app-norm-en1999-engine" }
en1999_op = { path = "../../../../../../../../../✏️s/🔌plugin/📕norm/🎛️app/📘en1999/🔨module/🔧op/⚡️implementation/🦀rust", package = "semio-s-app-norm-en1999-op" }
