//! 🌱️ Original initializer authority and cancellation Arc require separately funded physical release.
use super::*;
use crate::test_app_mutation_fixture::{TestSnapshot,TestMutation};
use semio_framework_job::InteractiveJob;
use semio_framework_value::{retirement::controlled::ControlledRetirement,retained_clone::{RetainedCloneGrant,RetainedCloneProgress,RetainedCloneStep,admit_retained_clone_close}};
use std::mem::size_of;
fn funds(grant:RetainedCloneGrant,demand:RetirementDemand)->bool{grant.maximum_items>0&&grant.maximum_copy_bytes>=demand.copy_bytes&&grant.maximum_capacity_bytes>=demand.capacity_bytes&&grant.maximum_release_bytes>=demand.release_bytes&&grant.maximum_depth>=demand.depth}
fn nested(mut demand:RetirementDemand)->Result<RetirementDemand,ValueError>{demand.depth=demand.depth.checked_add(1).ok_or_else(||ValueError::literal(semio_framework_value::ValueRefusalKind::DepthLimit,"fixture child depth overflow"))?;Ok(demand)}
struct OriginalAuthority{payload:Option<ControlledRetirement<String>>,pointer:usize,closing:bool}
impl ArtifactStoreInitializationAuthority<TestSnapshot,TestMutation> for OriginalAuthority{
 fn step<'a>(&'a mut self,cx:&mut semio_framework_job::StepContext<'_>)->Result<Option<semio_framework_job::JobOutcomeBorrow<'a>>,ValueError>{semio_framework_job::JobOutcomeBorrow::admit_yield(cx)}
 fn borrow_outcome<'a>(&'a self,descriptor:&'a semio_framework_job::JobOutcomeDescriptor)->Result<semio_framework_job::JobOutcomeView<'a>,ValueError>{descriptor.yielded()}
 fn request_cancel(&mut self){self.closing=true;}
 fn begin_close(&mut self){self.closing=true;}
 fn take_candidate(&mut self)->Option<ArtifactStore<TestSnapshot,TestMutation>>{None}
 fn retirement_demands(&self,body:usize)->Result<RetirementDemand,ValueError>{self.payload.as_ref().map_or(Ok(Default::default()),|owner|if owner.terminal_is_empty(){Ok(RetirementDemand{copy_bytes:size_of::<Option<ControlledRetirement<String>>>(),depth:1,..Default::default()})}else{nested(RetirementDemand{copy_bytes:owner.next_copy_byte_demand()?,capacity_bytes:owner.next_capacity_byte_demand(body)?,release_bytes:owner.next_release_byte_demand()?,depth:owner.next_depth_demand()?})})}
 fn close_step(&mut self,grant:RetainedCloneGrant)->Result<RetainedCloneStep,ValueError>{let demand=self.retirement_demands(grant.maximum_copy_bytes)?;if !self.closing||!funds(grant,demand){return Ok(RetainedCloneStep::Progress(Default::default()));}let Some(owner)=self.payload.as_mut()else{return Ok(RetainedCloneStep::Complete(Default::default()))};if owner.terminal_is_empty(){drop(self.payload.take());return Ok(RetainedCloneStep::Progress(RetainedCloneProgress{copied_items:1,copied_bytes:demand.copy_bytes,..Default::default()}));}if let Some(original)=owner.original(){assert_eq!(original.as_ptr()as usize,self.pointer);}let child=RetainedCloneGrant{maximum_depth:grant.maximum_depth-1,..grant};let step=owner.step(child)?;admit_retained_clone_close(child,step,owner.terminal_is_empty(),"native original initializer fixture").map(|step|RetainedCloneStep::Progress(step.progress()))}
 fn terminal_is_empty(&self)->bool{self.closing&&self.payload.is_none()}
}
#[test]
fn original_initializer_job_keeps_source_authority_cancel_arc_and_full_receipts(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let grant:RetainedCloneGrant=serde_json::from_value(law["grant"].clone()).unwrap();
 for size in[0,1,8192]{let mut original=String::with_capacity(size);original.extend(std::iter::repeat_n('x',size));assert_eq!(serde_json::to_value(&original).unwrap(),serde_json::Value::String("x".repeat(size)));let pointer=original.as_ptr()as usize;let mut born=original.capacity()+size_of::<OriginalAuthority>()+semio_framework_value::retirement::shared::shared_retirement_allocation_bytes::<std::sync::atomic::AtomicBool>();let mut job=ArtifactStoreInitializationJob::new(Box::new(OriginalAuthority{payload:Some(ControlledRetirement::new(original).ok().unwrap()),pointer,closing:false}));let mut released=0;let mut turns=0;
  while !job.terminal_is_empty(){let(demand,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||job.retirement_demands(grant.maximum_copy_bytes).unwrap());assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));let mut denials=vec![RetainedCloneGrant{maximum_items:0,..grant},RetainedCloneGrant{maximum_depth:0,..grant}];if demand.copy_bytes>0{denials.push(RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..grant});}if demand.capacity_bytes>0{denials.push(RetainedCloneGrant{maximum_capacity_bytes:demand.capacity_bytes-1,..grant});}if demand.release_bytes>0{denials.push(RetainedCloneGrant{maximum_release_bytes:demand.release_bytes-1,..grant});}for denied in denials{let(step,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||InteractiveJob::close_step(&mut job,denied));assert_eq!(step.progress(),Default::default());assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));assert!(!job.terminal_is_empty());}
   let(step,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||InteractiveJob::close_step(&mut job,grant));assert!(step.progress().fits(grant));assert_eq!((heap.requested_bytes,heap.released_bytes),(step.progress().retained_capacity_bytes,step.progress().released_bytes));born+=heap.requested_bytes;released+=heap.released_bytes;turns+=1;assert!(turns<100000);
  }assert_eq!(born,released);let((),heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(||drop(job));assert_eq!((heap.requested_bytes,heap.released_bytes),(0,0));println!("[DEBUG] original initializer size={size} turns={turns} physical={released} unchanged5currencies originalBytes samePointer authorityFrame and cancelArc separate terminalDrop0");
 }
}
