import { readFileSync, existsSync, mkdirSync, writeFileSync, linkSync, unlinkSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import JSON5 from "json5";
const ticket=resolve(import.meta.dir,".."),out=resolve(ticket,"🗑️generated/current-native-origin/epoch-3"),[command,owner]=process.argv.slice(2),controller=new AbortController(),sha=(body:Buffer|string)=>createHash("sha256").update(body).digest("hex");process.once("SIGINT",()=>controller.abort());process.once("SIGTERM",()=>controller.abort());if(command!=="observe"||!["board","product"].includes(owner))throw Error("Exact current owning post observation required");const directory=resolve(out,owner),bindings=[import.meta.path,...["plan.json","metadata.json","terminal.json",owner==="product"?"dispatcher2-terminal.json":"dispatcher-terminal.json",owner==="product"?"runtime-import-custody7.json":"runtime-import-custody5.json"].map(name=>resolve(directory,name))].map(path=>({path,sha256:sha(readFileSync(path))})),plan=JSON.parse(readFileSync(bindings[1].path,"utf8")),metadata=JSON.parse(readFileSync(bindings[2].path,"utf8")),terminal=JSON.parse(readFileSync(bindings[3].path,"utf8"));if(terminal.owningExitCode!==1||!terminal.sourcePostUnavailable||!terminal.postRefusal.includes("Cargo.toml"))throw Error("Actual current owning source refusal required");
function guard(){controller.signal.throwIfAborted();for(const row of bindings)if(sha(readFileSync(row.path))!==row.sha256)throw Error("Current post observation authority advanced");}
const beforeManifests=new Map([...plan.declarations,...plan.providers].map((row:any)=>[row.path,row.source])),checks:any[]=[],pairs:any[]=[];
for(let n=0;n<plan.checks.length;n++){controller.signal.throwIfAborted();const row=plan.checks[n],expected=row.path==="Cargo.lock"?metadata.lock.afterHash:row.expected,bytes=existsSync(row.destination)?readFileSync(row.destination):null,current=bytes?sha(bytes):null;checks.push({path:row.path,destination:row.destination,expected,current,exact:expected===current});if(current!==expected){const before=row.path==="Cargo.toml"?plan.workspace.source:row.path==="Cargo.lock"?metadata.lock.after:beforeManifests.get(row.path)??null,after=bytes?bytes.toString("utf8"):null;if(before!==null&&sha(before)!==expected)throw Error("Full available current source-before body differs");pairs.push({path:row.path,before,after,beforeHash:expected,afterHash:current,beforeAvailable:before!==null,forward:before===null?null:{start:0,delete:before,insert:after},inverse:before===null?null:{start:0,delete:after,insert:before}});}if(n%128===0){console.log("[DEBUG] "+JSON.stringify({phase:"complete-current-owning-post-source-observation",owner,completed:n+1,total:plan.checks.length}));await new Promise<void>(done=>setImmediate(done));}}
const phases:any[]=[];for(const locked of[false,true]){guard();const args=["metadata",...(locked?["--locked"]:[]),"--format-version=1","--manifest-path",resolve(plan.snapshot,plan.route.manifest)],lockBefore=readFileSync(resolve(plan.snapshot,"Cargo.lock")),child=Bun.spawn(["cargo",...args],{cwd:plan.snapshot,env:{...process.env,...plan.environment},stdout:"pipe",stderr:"pipe",signal:controller.signal}),[stdout,stderr,exitCode]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(exitCode!==0)throw Error("Actual current post metadata failed "+stderr);const parsed=JSON.parse(stdout),external=JSON5.parse(stdout);if(!isDeepStrictEqual(parsed,external))throw Error("Independent current post metadata JSON oracle differs");const prior=JSON.parse(metadata.phases[locked?1:0].stdout),lockAfter=readFileSync(resolve(plan.snapshot,"Cargo.lock"));phases.push({locked,args,exitCode,stdout,stderr,stdoutHash:sha(stdout),stdoutByteCount:Buffer.byteLength(stdout),completePriorMetadataObjectExact:isDeepStrictEqual(prior,parsed),lockBeforeHash:sha(lockBefore),lockAfterHash:sha(lockAfter),lockUnchanged:lockBefore.equals(lockAfter),independentJsonOracleExact:true});}
guard();for(const row of checks){const current=existsSync(row.destination)?sha(readFileSync(row.destination)):null;if(current!==row.current)throw Error("Current post source advanced during observation "+row.path);}const rootPair=pairs.find(row=>row.path==="Cargo.toml"),TOML=await import("@iarna/toml"),before=rootPair?Bun.TOML.parse(rootPair.before):null,after=rootPair?Bun.TOML.parse(rootPair.after):null;if(rootPair&&(!isDeepStrictEqual(before,TOML.parse(rootPair.before))||!isDeepStrictEqual(after,TOML.parse(rootPair.after))))throw Error("Independent current post manifest TOML oracle differs");let outsideExcludeExact=false;if(rootPair){const prior=structuredClone(before),later=structuredClone(after);delete prior.workspace.exclude;delete later.workspace.exclude;outsideExcludeExact=isDeepStrictEqual(prior,later);}const output=resolve(directory,"complete-post-observation.json"),result={at:new Date().toISOString(),owner,bindings,checks,pairs,phases,workspace:{changedPaths:pairs.map(row=>row.path),outsideExcludeExact,beforeExclude:before?.workspace.exclude??null,afterExclude:after?.workspace.exclude??null},ready:false,owningAcceptanceClaimed:false,originalPostRefusalRetained:true,nativeExecuted:false,sourceWritesOutsideTicket:false,scope:"Read-only complete current post-source and fresh actual metadata observation; no retroactive source-exact/native acceptance"};mkdirSync(dirname(output),{recursive:true});writeFileSync(output+".writing",JSON.stringify(result),{flag:"wx"});linkSync(output+".writing",output);unlinkSync(output+".writing");console.log("[DEBUG] "+JSON.stringify({owner,checks:checks.length,pairs:pairs.map(row=>row.path),metadataObjectsExact:phases.every(row=>row.completePriorMetadataObjectExact),outsideExcludeExact,owningAcceptanceClaimed:false}));
