//! 🏛️ Explicit concrete entities, ordered reinforcement and exact binary64 state.
use crate::standards::v1::subsets::any::schema::snapshot::En1992Snapshot;
#[path="📏️cells/🦀️.rs"]mod semantic_cells;
use crate::{ConcreteGrade,ReinforcementGrade,PrestressSteel,RcMember,BarLayer,Stirrups,PunchingSpec,PrestressSpec,FireSpec,LoadCaseActions,Anchor,MemberKind,SupportCondition,ExposureClass,DuctilityClass,FireRating,TightnessClass,document::AnnexChoice};
use std::collections::BTreeMap;
use store::{ArtifactSqliteSnapshot,sqlite_snapshot::{SqliteDatabase,SnapshotEncoding,SqliteSnapshotControl,SqliteSnapshotPhase,validate_sqlite_database_schema,artifact::{Cell,FloatColumn,FloatRow,RowWriter,reconstruct_text}}};
use semio_framework_value::{ValueError, ValueRefusalKind};
fn invalid(message: impl Into<String>) -> ValueError { ValueError::new(ValueRefusalKind::InvalidValue, message) }

const DOCUMENT:&[FloatColumn]=&[FloatColumn::Binary64(3),FloatColumn::Binary64(4)];
const CONCRETE:&[FloatColumn]=&[FloatColumn::Binary64(5)];
const REINFORCEMENT:&[FloatColumn]=&[FloatColumn::Binary64(5),FloatColumn::Binary64(6),FloatColumn::Binary64(8),FloatColumn::Binary64(9)];
const STEEL:&[FloatColumn]=&[FloatColumn::Binary64(5),FloatColumn::Binary64(6)];
const MEMBER:&[FloatColumn]=&[FloatColumn::Binary64(11),FloatColumn::Binary64(12),FloatColumn::Binary64(13),FloatColumn::Binary64(14),FloatColumn::Binary64(15),FloatColumn::Binary64(17),FloatColumn::Binary64(19),FloatColumn::Binary64(22),FloatColumn::Binary64(23),FloatColumn::Binary64(24),FloatColumn::Binary64(25),FloatColumn::Binary64(26),FloatColumn::Binary64(27),FloatColumn::Binary64(28)];
const BAR:&[FloatColumn]=&[FloatColumn::Binary64(4),FloatColumn::Binary64(7),FloatColumn::Binary64(8),FloatColumn::Binary64(10)];
const STIRRUPS:&[FloatColumn]=&[FloatColumn::Binary64(1),FloatColumn::Binary64(2)];
const PUNCHING:&[FloatColumn]=&[FloatColumn::Binary64(1),FloatColumn::Binary64(2),FloatColumn::Binary64(4)];
const PRESTRESS:&[FloatColumn]=&[FloatColumn::Binary64(1),FloatColumn::Binary64(2),FloatColumn::Binary64(3),FloatColumn::Binary64(4)];
const FIRE:&[FloatColumn]=&[FloatColumn::Binary64(2)];
const ACTION:&[FloatColumn]=&[FloatColumn::Binary64(7),FloatColumn::Binary64(8),FloatColumn::Binary64(9),FloatColumn::Binary64(10),FloatColumn::Binary64(11),FloatColumn::Binary64(12),FloatColumn::Binary64(13),FloatColumn::Binary64(14)];
const ANCHOR:&[FloatColumn]=&[FloatColumn::Binary64(4),FloatColumn::Binary64(6),FloatColumn::Binary64(7),FloatColumn::Binary64(8),FloatColumn::Binary64(9),FloatColumn::Binary64(10),FloatColumn::Binary64(11)];
fn ordinal(n:usize)->Result<Cell<'static>, ValueError>{Ok(Cell::Integer(i64::try_from(n).map_err(|e| invalid(e.to_string()))?))}
fn checkpoint(c:&mut SqliteSnapshotControl<'_>,n:usize,total:usize)->Result<(), ValueError>{if n%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,n,total)?;}Ok(())}
type Entities<'a>=BTreeMap<i64,FloatRow<'a>>;
fn entities<'a>(d:&'a SqliteDatabase,table:&str,count:usize,floats:&'static[FloatColumn],c:&mut SqliteSnapshotControl<'_>)->Result<Entities<'a>, ValueError>{let rows=&d.table(table)?.rows;let mut out=Entities::new();for(n,row)in rows.iter().enumerate(){checkpoint(c,n,rows.len())?;let r=FloatRow::new(row,floats)?;if r.rowid<=0||r.integer(0)?!=r.rowid||r.values.len()!=count||out.insert(r.rowid,r).is_some(){return Err(invalid("EN1992 identity or owned column shape differs"));}}Ok(out)}
fn ordered<'a>(rows:impl IntoIterator<Item=FloatRow<'a>>,parent:i64,c:&mut SqliteSnapshotControl<'_>)->Result<Vec<FloatRow<'a>>, ValueError>{let mut out=BTreeMap::new();for(n,r)in rows.into_iter().enumerate(){checkpoint(c,n,0)?;let i=usize::try_from(r.integer(2)?).map_err(|e| invalid(e.to_string()))?;if r.integer(1)?!=parent||out.insert(i,r).is_some(){return Err(invalid("EN1992 parent or ordinal differs"));}}for(n,i)in out.keys().copied().enumerate(){checkpoint(c,n,out.len())?;if n!=i{return Err(invalid("EN1992 ordinals must be dense"));}}Ok(out.into_values().collect())}
fn groups<'a>(rows:Entities<'a>,parents:&Entities<'_>,c:&mut SqliteSnapshotControl<'_>)->Result<BTreeMap<i64,Vec<FloatRow<'a>>>, ValueError>{let mut out=BTreeMap::<i64,Vec<FloatRow<'a>>>::new();for(n,r)in rows.into_values().enumerate(){checkpoint(c,n,0)?;let p=r.integer(1)?;if !parents.contains_key(&p){return Err(invalid("EN1992 owning foreign key is dangling"));}out.entry(p).or_default().push(r);}Ok(out)}
fn optional_entities<'a>(rows:Entities<'a>,parents:&Entities<'_>,c:&mut SqliteSnapshotControl<'_>)->Result<Entities<'a>, ValueError>{for(n,id)in rows.keys().enumerate(){checkpoint(c,n,rows.len())?;if !parents.contains_key(id){return Err(invalid("EN1992 optional member entity is dangling"));}}Ok(rows)}
fn text(r:FloatRow<'_>,i:usize,c:&mut SqliteSnapshotControl<'_>)->Result<String, ValueError>{reconstruct_text(c,r.text(i)?)}
fn boolean(r:FloatRow<'_>,i:usize)->Result<bool, ValueError>{match r.integer(i)?{0=>Ok(false),1=>Ok(true),_=>Err(invalid("EN1992 boolean differs"))}}
fn u32_value(r:FloatRow<'_>,i:usize)->Result<u32, ValueError>{u32::try_from(r.integer(i)?).map_err(|e| invalid(e.to_string()))}
fn annex(a:AnnexChoice)->&'static str{match a{AnnexChoice::En=>"En",AnnexChoice::De=>"De"}}
fn read_annex(a:&str)->Result<AnnexChoice, ValueError>{match a{"En"=>Ok(AnnexChoice::En),"De"=>Ok(AnnexChoice::De),_=>Err(invalid("EN1992 annex differs"))}}
fn member_kind(a:MemberKind)->&'static str{match a{MemberKind::Beam=>"Beam",MemberKind::Slab=>"Slab",MemberKind::Column=>"Column",MemberKind::Wall=>"Wall",MemberKind::FlatSlab=>"FlatSlab",MemberKind::RibbedSlab=>"RibbedSlab",MemberKind::TensionMember=>"TensionMember",MemberKind::Bridge=>"Bridge",MemberKind::LiquidRetaining=>"LiquidRetaining"}}
fn read_member_kind(a:&str)->Result<MemberKind, ValueError>{match a{"Beam"=>Ok(MemberKind::Beam),"Slab"=>Ok(MemberKind::Slab),"Column"=>Ok(MemberKind::Column),"Wall"=>Ok(MemberKind::Wall),"FlatSlab"=>Ok(MemberKind::FlatSlab),"RibbedSlab"=>Ok(MemberKind::RibbedSlab),"TensionMember"=>Ok(MemberKind::TensionMember),"Bridge"=>Ok(MemberKind::Bridge),"LiquidRetaining"=>Ok(MemberKind::LiquidRetaining),_=>Err(invalid("EN1992 member kind differs"))}}
fn support(a:SupportCondition)->&'static str{match a{SupportCondition::SimplySupported=>"SimplySupported",SupportCondition::Continuous=>"Continuous",SupportCondition::Cantilever=>"Cantilever",SupportCondition::Fixed=>"Fixed"}}
fn read_support(a:&str)->Result<SupportCondition, ValueError>{match a{"SimplySupported"=>Ok(SupportCondition::SimplySupported),"Continuous"=>Ok(SupportCondition::Continuous),"Cantilever"=>Ok(SupportCondition::Cantilever),"Fixed"=>Ok(SupportCondition::Fixed),_=>Err(invalid("EN1992 support differs"))}}
fn exposure(a:ExposureClass)->&'static str{match a{ExposureClass::X0=>"X0",ExposureClass::Xc1=>"Xc1",ExposureClass::Xc2=>"Xc2",ExposureClass::Xc3=>"Xc3",ExposureClass::Xc4=>"Xc4",ExposureClass::Xd1=>"Xd1",ExposureClass::Xd2=>"Xd2",ExposureClass::Xd3=>"Xd3",ExposureClass::Xs1=>"Xs1",ExposureClass::Xs2=>"Xs2",ExposureClass::Xs3=>"Xs3",ExposureClass::Xf1=>"Xf1",ExposureClass::Xf2=>"Xf2",ExposureClass::Xf3=>"Xf3",ExposureClass::Xf4=>"Xf4",ExposureClass::Xa1=>"Xa1",ExposureClass::Xa2=>"Xa2",ExposureClass::Xa3=>"Xa3"}}
fn read_exposure(a:&str)->Result<ExposureClass, ValueError>{match a{"X0"=>Ok(ExposureClass::X0),"Xc1"=>Ok(ExposureClass::Xc1),"Xc2"=>Ok(ExposureClass::Xc2),"Xc3"=>Ok(ExposureClass::Xc3),"Xc4"=>Ok(ExposureClass::Xc4),"Xd1"=>Ok(ExposureClass::Xd1),"Xd2"=>Ok(ExposureClass::Xd2),"Xd3"=>Ok(ExposureClass::Xd3),"Xs1"=>Ok(ExposureClass::Xs1),"Xs2"=>Ok(ExposureClass::Xs2),"Xs3"=>Ok(ExposureClass::Xs3),"Xf1"=>Ok(ExposureClass::Xf1),"Xf2"=>Ok(ExposureClass::Xf2),"Xf3"=>Ok(ExposureClass::Xf3),"Xf4"=>Ok(ExposureClass::Xf4),"Xa1"=>Ok(ExposureClass::Xa1),"Xa2"=>Ok(ExposureClass::Xa2),"Xa3"=>Ok(ExposureClass::Xa3),_=>Err(invalid("EN1992 exposure differs"))}}
fn ductility(a:DuctilityClass)->&'static str{match a{DuctilityClass::A=>"a",DuctilityClass::B=>"b",DuctilityClass::C=>"c"}}
fn read_ductility(a:&str)->Result<DuctilityClass, ValueError>{match a{"a"=>Ok(DuctilityClass::A),"b"=>Ok(DuctilityClass::B),"c"=>Ok(DuctilityClass::C),_=>Err(invalid("EN1992 ductility differs"))}}
fn fire_rating(a:FireRating)->&'static str{match a{FireRating::R30=>"R30",FireRating::R60=>"R60",FireRating::R90=>"R90",FireRating::R120=>"R120"}}
fn read_fire(a:&str)->Result<FireRating, ValueError>{match a{"R30"=>Ok(FireRating::R30),"R60"=>Ok(FireRating::R60),"R90"=>Ok(FireRating::R90),"R120"=>Ok(FireRating::R120),_=>Err(invalid("EN1992 fire rating differs"))}}
fn tightness(a:TightnessClass)->&'static str{match a{TightnessClass::Tc0=>"Tc0",TightnessClass::Tc1=>"Tc1",TightnessClass::Tc2=>"Tc2"}}
fn read_tightness(a:Option<&str>)->Result<Option<TightnessClass>, ValueError>{match a{None=>Ok(None),Some("Tc0")=>Ok(Some(TightnessClass::Tc0)),Some("Tc1")=>Ok(Some(TightnessClass::Tc1)),Some("Tc2")=>Ok(Some(TightnessClass::Tc2)),_=>Err(invalid("EN1992 tightness differs"))}}
fn insert_action(p:&mut RowWriter<'_,'_>,table:&str,parent:i64,n:usize,a:&LoadCaseActions)->Result<(), ValueError>{p.insert_float(table,&[Cell::Integer(parent),ordinal(n)?,Cell::Text(&a.id),Cell::Text(&a.kind),Cell::Text(&a.category),Cell::Text(&a.source),Cell::Real(a.g_k_line),Cell::Real(a.q_k_line),Cell::Real(a.point_force),Cell::Real(a.m_k),Cell::Real(a.n_k),Cell::Real(a.v_k),Cell::Real(a.t_k),Cell::Real(a.v_k_punch)],ACTION)?;Ok(())}
fn read_action(a:FloatRow<'_>,c:&mut SqliteSnapshotControl<'_>)->Result<LoadCaseActions, ValueError>{Ok(LoadCaseActions{id:text(a,3,c)?,kind:text(a,4,c)?,category:text(a,5,c)?,source:text(a,6,c)?,g_k_line:a.real(7)?,q_k_line:a.real(8)?,point_force:a.real(9)?,m_k:a.real(10)?,n_k:a.real(11)?,v_k:a.real(12)?,t_k:a.real(13)?,v_k_punch:a.real(14)?})}
/// 🪪️ Optional relational capability of the concrete artifact owner.
pub fn codec()->store::ArtifactSqliteSnapshotCodec{<En1992Snapshot as ArtifactSqliteSnapshot>::sqlite_codec()}
fn visit_rows(s:&En1992Snapshot,p:&mut RowWriter<'_,'_>)->Result<(),ValueError>{
  p.insert_key_float("en1992_document",1,&[Cell::Text(annex(s.annex)),Cell::Text(&s.title),Cell::Real(s.design_working_life_years),Cell::Real(s.delta_c_dev),Cell::Text(&s.cement_type)],DOCUMENT)?;
  for(n,v)in s.concrete_grades.iter().enumerate(){p.insert_float("en1992_concrete_grade",&[Cell::Integer(1),ordinal(n)?,Cell::Text(&v.id),Cell::Text(&v.name),Cell::Real(v.f_ck)],CONCRETE)?;}
  for(n,v)in s.reinforcement_grades.iter().enumerate(){p.insert_float("en1992_reinforcement_grade",&[Cell::Integer(1),ordinal(n)?,Cell::Text(&v.id),Cell::Text(&v.name),Cell::Real(v.f_yk),Cell::Real(v.e_s),Cell::Text(ductility(v.ductility)),Cell::Real(v.k),Cell::Real(v.eps_uk)],REINFORCEMENT)?;}
  for(n,v)in s.prestress_steels.iter().enumerate(){p.insert_float("en1992_prestress_steel",&[Cell::Integer(1),ordinal(n)?,Cell::Text(&v.id),Cell::Text(&v.name),Cell::Real(v.f_pk),Cell::Real(v.f_p0_1k)],STEEL)?;}
  for(n,v)in s.members.iter().enumerate(){let id=p.insert_float("en1992_member",&[Cell::Integer(1),ordinal(n)?,Cell::Text(&v.id),Cell::Text(&v.label_en),Cell::Text(&v.label_de),Cell::Text(member_kind(v.kind)),Cell::Text(&v.concrete_grade_id),Cell::Text(&v.reinforcement_grade_id),Cell::Text(&v.prestress_steel_id),Cell::Text(exposure(v.exposure)),Cell::Real(v.width),Cell::Real(v.height),Cell::Real(v.effective_depth),Cell::Real(v.cover),Cell::Real(v.span),Cell::Text(support(v.support)),Cell::Real(v.buckling_length),Cell::Integer(i64::from(v.use_fem)),Cell::Real(v.udl),Cell::Integer(i64::from(v.deflection_sensitive)),v.tightness.map_or(Cell::Null,|t|Cell::Text(tightness(t))),Cell::Real(v.hd_over_h),Cell::Real(v.liquid_sigma_s),Cell::Real(v.liquid_rho_p_eff),Cell::Real(v.liquid_f_ct_eff),Cell::Real(v.liquid_s_r_max),Cell::Real(v.bridge_sigma_c),Cell::Real(v.bridge_delta_sigma_s)],MEMBER)?;
   for(k,a)in v.longitudinal.iter().enumerate(){p.insert_float("en1992_bar_layer",&[Cell::Integer(id),ordinal(k)?,Cell::Text(&a.id),Cell::Real(a.diameter),Cell::Integer(i64::from(a.count)),Cell::Text(&a.position),Cell::Real(a.anchorage_length),Cell::Real(a.lap_length),Cell::Text(&a.bond_condition),Cell::Real(a.aggregate_size)],BAR)?;}
   if let Some(a)=&v.stirrups{p.insert_key_float("en1992_stirrups",id,&[Cell::Real(a.diameter),Cell::Real(a.spacing),Cell::Integer(i64::from(a.legs))],STIRRUPS)?;}
   if let Some(a)=&v.punching{p.insert_key_float("en1992_punching",id,&[Cell::Real(a.column_width),Cell::Real(a.column_depth),Cell::Text(&a.column_position),Cell::Real(a.asw)],PUNCHING)?;}
   if let Some(a)=&v.prestress{p.insert_key_float("en1992_prestress",id,&[Cell::Real(a.force),Cell::Real(a.area),Cell::Real(a.eccentricity),Cell::Real(a.loss_ratio)],PRESTRESS)?;}
   if let Some(a)=&v.fire{p.insert_key_float("en1992_fire",id,&[Cell::Text(fire_rating(a.rating)),Cell::Real(a.axis_distance),Cell::Text(&a.column_method),Cell::Text(&a.slab_system)],FIRE)?;}
   for(k,a)in v.actions.iter().enumerate(){insert_action(p,"en1992_member_action",id,k,a)?;}
  }
  for(n,v)in s.anchors.iter().enumerate(){let id=p.insert_float("en1992_anchor",&[Cell::Integer(1),ordinal(n)?,Cell::Text(&v.id),Cell::Real(v.h_ef),Cell::Integer(i64::from(v.cracked)),Cell::Real(v.f_uk),Cell::Real(v.f_yk),Cell::Real(v.a_s),Cell::Real(v.d),Cell::Real(v.c1),Cell::Real(v.f_ck)],ANCHOR)?;for(k,a)in v.actions.iter().enumerate(){insert_action(p,"en1992_anchor_action",id,k,a)?;}}
 Ok(())
}
fn admit(s:&En1992Snapshot,c:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{semantic_cells::extent(c.limits())?;let mut p=RowWriter::borrowed(c,SqliteSnapshotPhase::ProjectSnapshot)?;visit_rows(s,&mut p)?;p.finish_borrowed()}
impl ArtifactSqliteSnapshot for En1992Snapshot{
 const SQLITE_SCHEMA:&'static str=include_str!("🗄️.sql");
 fn decode_sqlite_snapshot_native(payload:&store::io_schema::IoPayload,c:&mut SqliteSnapshotControl<'_>,native_control: &mut semio_framework_os_kernel::NativeSnapshotDecodeOwner<'_, '_>)->Result<Self,ValueError>{let limits=c.limits();semantic_cells::extent(limits)?;store::decode_sqlite_snapshot_record_native(payload,<Self as store::ArtifactDsl>::envelope_id(),Self::__dsl_spec_producer(),|record, snapshot_output, n,_body| { let constructed: Result<_, semio_framework_value::ValueError> = (|| {semantic_cells::admit_record(record,limits,n)?;Self::__dsl_from_record_controlled(record,n)})(); *snapshot_output = Some(constructed?); Ok(()) },c,native_control)}
 fn encode_sqlite_snapshot_native(&self,encoding:SnapshotEncoding,c:&mut SqliteSnapshotControl<'_>,native_owner:&mut semio_framework_os_kernel::NativeSnapshotEncodeOwner<'_, '_>)->Result<store::io_schema::IoPayload,ValueError>{admit(self,c)?;store::encode_sqlite_snapshot_record_native(encoding,<Self as store::ArtifactDsl>::envelope_id(),Self::__dsl_spec_producer(),|n|self.__dsl_to_record_controlled(n),c,native_owner)}
 fn to_sqlite_database(&self,c:&mut SqliteSnapshotControl<'_>)->Result<SqliteDatabase,ValueError>{semantic_cells::extent(c.limits())?;let mut p=RowWriter::new(Self::SQLITE_SCHEMA,c)?;visit_rows(self,&mut p)?;p.finish()}
 fn from_sqlite_database(d:&SqliteDatabase,c:&mut SqliteSnapshotControl<'_>)->Result<Self, ValueError>{
  c.check_database(d,SqliteSnapshotPhase::ReconstructSnapshot)?;validate_sqlite_database_schema(d,Self::SQLITE_SCHEMA,c.limits())?;
  let documents=entities(d,"en1992_document",6,DOCUMENT,c)?;if documents.len()!=1||!documents.contains_key(&1){return Err(invalid("EN1992 requires one identity-1 document"));}let r=documents[&1];
  let member_rows=entities(d,"en1992_member",29,MEMBER,c)?;let anchor_rows=entities(d,"en1992_anchor",12,ANCHOR,c)?;
  let mut bars=groups(entities(d,"en1992_bar_layer",11,BAR,c)?,&member_rows,c)?;let mut actions=groups(entities(d,"en1992_member_action",15,ACTION,c)?,&member_rows,c)?;let mut anchor_actions=groups(entities(d,"en1992_anchor_action",15,ACTION,c)?,&anchor_rows,c)?;
  let mut stirrups=optional_entities(entities(d,"en1992_stirrups",4,STIRRUPS,c)?,&member_rows,c)?;let mut punching=optional_entities(entities(d,"en1992_punching",5,PUNCHING,c)?,&member_rows,c)?;let mut prestress=optional_entities(entities(d,"en1992_prestress",5,PRESTRESS,c)?,&member_rows,c)?;let mut fire=optional_entities(entities(d,"en1992_fire",5,FIRE,c)?,&member_rows,c)?;
  let mut concrete_grades=Vec::new();for v in ordered(entities(d,"en1992_concrete_grade",6,CONCRETE,c)?.into_values(),1,c)?{concrete_grades.push(ConcreteGrade{id:text(v,3,c)?,name:text(v,4,c)?,f_ck:v.real(5)?});}
  let mut reinforcement_grades=Vec::new();for v in ordered(entities(d,"en1992_reinforcement_grade",10,REINFORCEMENT,c)?.into_values(),1,c)?{reinforcement_grades.push(ReinforcementGrade{id:text(v,3,c)?,name:text(v,4,c)?,f_yk:v.real(5)?,e_s:v.real(6)?,ductility:read_ductility(v.text(7)?)?,k:v.real(8)?,eps_uk:v.real(9)?});}
  let mut prestress_steels=Vec::new();for v in ordered(entities(d,"en1992_prestress_steel",7,STEEL,c)?.into_values(),1,c)?{prestress_steels.push(PrestressSteel{id:text(v,3,c)?,name:text(v,4,c)?,f_pk:v.real(5)?,f_p0_1k:v.real(6)?});}
  let mut members=Vec::new();for v in ordered(member_rows.into_values(),1,c)?{
   let mut longitudinal=Vec::new();for a in ordered(bars.remove(&v.rowid).unwrap_or_default(),v.rowid,c)?{longitudinal.push(BarLayer{id:text(a,3,c)?,diameter:a.real(4)?,count:u32_value(a,5)?,position:text(a,6,c)?,anchorage_length:a.real(7)?,lap_length:a.real(8)?,bond_condition:text(a,9,c)?,aggregate_size:a.real(10)?});}
   let stirrups=stirrups.remove(&v.rowid).map(|a|Ok::<_, ValueError>(Stirrups{diameter:a.real(1)?,spacing:a.real(2)?,legs:u32_value(a,3)?})).transpose()?;
   let punching=punching.remove(&v.rowid).map(|a|Ok::<_, ValueError>(PunchingSpec{column_width:a.real(1)?,column_depth:a.real(2)?,column_position:text(a,3,c)?,asw:a.real(4)?})).transpose()?;
   let prestress=prestress.remove(&v.rowid).map(|a|Ok::<_, ValueError>(PrestressSpec{force:a.real(1)?,area:a.real(2)?,eccentricity:a.real(3)?,loss_ratio:a.real(4)?})).transpose()?;
   let fire=fire.remove(&v.rowid).map(|a|Ok::<_, ValueError>(FireSpec{rating:read_fire(a.text(1)?)?,axis_distance:a.real(2)?,column_method:text(a,3,c)?,slab_system:text(a,4,c)?})).transpose()?;
   let mut member_actions=Vec::new();for a in ordered(actions.remove(&v.rowid).unwrap_or_default(),v.rowid,c)?{member_actions.push(read_action(a,c)?);}
   members.push(RcMember{id:text(v,3,c)?,label_en:text(v,4,c)?,label_de:text(v,5,c)?,kind:read_member_kind(v.text(6)?)?,concrete_grade_id:text(v,7,c)?,reinforcement_grade_id:text(v,8,c)?,prestress_steel_id:text(v,9,c)?,exposure:read_exposure(v.text(10)?)?,width:v.real(11)?,height:v.real(12)?,effective_depth:v.real(13)?,cover:v.real(14)?,span:v.real(15)?,support:read_support(v.text(16)?)?,buckling_length:v.real(17)?,longitudinal,stirrups,punching,prestress,fire,actions:member_actions,use_fem:boolean(v,18)?,udl:v.real(19)?,deflection_sensitive:boolean(v,20)?,tightness:read_tightness(v.optional_text(21)?)?,hd_over_h:v.real(22)?,liquid_sigma_s:v.real(23)?,liquid_rho_p_eff:v.real(24)?,liquid_f_ct_eff:v.real(25)?,liquid_s_r_max:v.real(26)?,bridge_sigma_c:v.real(27)?,bridge_delta_sigma_s:v.real(28)?});
  }
  let mut anchors=Vec::new();for v in ordered(anchor_rows.into_values(),1,c)?{let mut actions=Vec::new();for a in ordered(anchor_actions.remove(&v.rowid).unwrap_or_default(),v.rowid,c)?{actions.push(read_action(a,c)?);}anchors.push(Anchor{id:text(v,3,c)?,h_ef:v.real(4)?,cracked:boolean(v,5)?,f_uk:v.real(6)?,f_yk:v.real(7)?,a_s:v.real(8)?,d:v.real(9)?,c1:v.real(10)?,f_ck:v.real(11)?,actions});}
  let result=Self{annex:read_annex(r.text(1)?)?,title:text(r,2,c)?,design_working_life_years:r.real(3)?,delta_c_dev:r.real(4)?,cement_type:text(r,5,c)?,concrete_grades,reinforcement_grades,prestress_steels,members,anchors};c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,1,1)?;Ok(result)
 }
 fn validate_sqlite_snapshot_subset(&self,dialect:&semio_framework_artifact_reference::ArtifactDialect,_d:&SqliteDatabase,c:&mut SqliteSnapshotControl<'_>)->store::io_schema::IoResult<()>{c.checkpoint(SqliteSnapshotPhase::ProjectSnapshot,0,1).map_err(store::io_schema::IoError::from_value_error)?;if dialect.artifact_kind!="s.norm.en1992"||dialect.standard!="1"||dialect.subset!="*"{return Err(store::io_schema::IoError::from_value_error(invalid("EN1992 owned dialect differs")));}c.checkpoint(SqliteSnapshotPhase::ProjectSnapshot,1,1).map_err(store::io_schema::IoError::from_value_error)?;Ok(store::io_schema::IoOutcome::clean(()))}
 fn preflight_sqlite_snapshot_encoding(&self,_encoding:SnapshotEncoding,c:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{admit(self,c)}
}

#[cfg(test)]
#[path = "🧪️tests/🦀️.rs"]
mod tests;
