[package]
name = "process-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[package.metadata.component]
package = "semio:process"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "process3d"
app = "process3d-play"
aliases = ["process 3d"]
ports = { react = 6022, wgpu = 6122 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
process_3d = { path = "../../3d/rs" }
semio-framework-plugin = { path = "../../../framework/plugin/rs" }
semio-framework-core = { path = "../../../framework/core/rs" }
semio-framework-os = { path = "../../../framework/product/os/core/rs" }
kernel_3d_brepkit = { path = "../../../kernel/3d/brep/rs" }
kernel_3d_engine = { path = "../../../kernel/3d/brep/engine/rs", features = ["parallel"] }
vcs = { path = "../../../vcs/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
