//! 🧶️ Original paged scalars and admitted Unicode16 resolve bounded extended grapheme boundaries.
use super::{UnicodeLayout,UnicodeProperty,UnicodePropertyCursor,normalize::NormalizedScalar};
use super::super::super::{FontProgress,reserve_slot};
use semio_framework_value::{list::PagedList,retirement::{RetireOwned,RetirementCursor}};
#[derive(Clone,Copy,Debug,PartialEq,Eq)]
pub struct UnicodeCluster{pub start:usize,pub end:usize}
semio_framework_value::artifact_retire_leaf!(UnicodeCluster);
#[derive(semio_framework_value::RetireOwned)]
struct Owners{output:Option<PagedList<UnicodeCluster,{usize::MAX}>>,failure:Option<String>}
pub struct UnicodeGraphemeCursor{owners:Owners,layout:UnicodeLayout,source_pointer:usize,source_count:usize,data_pointer:usize,max_work:u64,phase:u8,at:usize,start:usize,work:u64,cancelled:bool,probe:Option<UnicodePropertyCursor>,current:Option<UnicodeProperty>,previous:Option<u8>,regional_count:usize,pictographic:bool,joined_pictographic:bool,indic:bool,linker:bool,final_cluster:bool}
impl RetireOwned for UnicodeGraphemeCursor{fn retirement(self)->Box<dyn RetirementCursor>{self.owners.retirement()}fn retirement_birth_bytes(&self)->Option<usize>{self.owners.retirement_birth_bytes()}fn controlled_retirement_supported()->bool{true}}
impl UnicodeGraphemeCursor{
 pub fn new(layout:UnicodeLayout,bytes:&[u8],source:&PagedList<NormalizedScalar,{usize::MAX}>,max_work:u64)->Self{let invalid=bytes.len()!=layout.byte_length||source.len()>1048576||!(1..=1000000000).contains(&max_work);Self{owners:Owners{output:Some(PagedList::new()),failure:invalid.then(||"Invalid Unicode grapheme limits".into())},layout,source_pointer:source.get(0).map_or(0,|value|value as*const NormalizedScalar as usize),source_count:source.len(),data_pointer:bytes.as_ptr()as usize,max_work,phase:0,at:0,start:0,work:0,cancelled:false,probe:None,current:None,previous:None,regional_count:0,pictographic:false,joined_pictographic:false,indic:false,linker:false,final_cluster:false}}
 fn joins(&self,p:UnicodeProperty)->bool{let a=self.previous;let b=p.grapheme;if a==Some(1)&&b==2{return true;}if a.is_some_and(|value|matches!(value,1|2|3))||matches!(b,1|2|3){return false;}if a==Some(9)&&matches!(b,9|10|12|13){return true;}if a.is_some_and(|value|matches!(value,12|10))&&matches!(b,10|11){return true;}if a.is_some_and(|value|matches!(value,13|11))&&b==11{return true;}if matches!(b,4|5|8)||a==Some(7){return true;}if p.flags&16!=0&&self.indic&&self.linker{return true;}if a==Some(5)&&self.joined_pictographic&&p.flags&2!=0{return true;}a==Some(6)&&b==6&&self.regional_count%2==1}
 fn consume(&mut self){let p=self.current.take().unwrap();let g=p.grapheme;self.regional_count=if g==6{self.regional_count+1}else{0};self.joined_pictographic=g==5&&self.pictographic;if p.flags&2!=0{self.pictographic=true;}else if g!=4{self.pictographic=false;}if p.flags&16!=0{self.indic=true;self.linker=false;}else if self.indic&&p.flags&(32|64)!=0{self.linker|=p.flags&64!=0;}else{self.indic=false;self.linker=false;}self.previous=Some(g);self.at+=1;self.phase=0;}
 fn step(&mut self,bytes:&[u8],source:&PagedList<NormalizedScalar,{usize::MAX}>)->Result<(),String>{if bytes.len()!=self.layout.byte_length||bytes.as_ptr()as usize!=self.data_pointer||source.len()!=self.source_count||source.get(0).map_or(0,|value|value as*const NormalizedScalar as usize)!=self.source_pointer{return Err("Captured Unicode grapheme source changed".into());}match self.phase{0=>{if self.at==source.len(){if self.start==self.at{self.phase=4;}else{self.final_cluster=true;self.phase=3;}return Ok(());}self.probe=Some(UnicodePropertyCursor::new(self.layout,source.get(self.at).unwrap().scalar)?);self.phase=1;},1=>{if self.probe.as_mut().unwrap().step(bytes)?{self.current=Some(self.probe.as_ref().unwrap().result()?);self.probe=None;self.phase=2;}},2=>{if self.at>self.start&&!self.joins(self.current.unwrap()){self.phase=3;}else{self.consume();}},3=>{let output=self.owners.output.as_mut().unwrap();if !reserve_slot(output)?{return Ok(());}output.push_reserved(UnicodeCluster{start:self.start,end:self.at}).map_err(|_|"Unicode cluster reservation lost")?;self.start=self.at;self.phase=if self.final_cluster{4}else{2};},_=>return Err("Unicode grapheme stage invalid".into())}Ok(())}
 pub fn advance(&mut self,bytes:&[u8],source:&PagedList<NormalizedScalar,{usize::MAX}>,grant:usize)->Result<FontProgress,String>{if grant==0{return Err("Invalid Unicode grapheme work grant".into());}if self.cancelled{return Err("Unicode grapheme cancelled".into());}if let Some(error)=&self.owners.failure{return Err(error.clone());}for _ in 0..grant{if self.phase==4{break;}if self.work==self.max_work{self.owners.failure=Some("Unicode grapheme work limit exceeded".into());return Err(self.owners.failure.as_ref().unwrap().clone());}if let Err(error)=self.step(bytes,source){self.owners.failure=Some(error.clone());return Err(error);}self.work+=1;}Ok(FontProgress{phase:match self.phase{0=>"read",1=>"property",2=>"boundary",3=>"emit",_=>"complete"},work:self.work,done:self.phase==4})}
 pub fn result(&self)->Result<&PagedList<UnicodeCluster,{usize::MAX}>,String>{if self.phase!=4||self.cancelled||self.owners.failure.is_some(){return Err("Unicode grapheme incomplete".into());}self.owners.output.as_ref().ok_or_else(||"Unicode cluster output transferred".into())}
 pub fn take_result(&mut self)->Result<PagedList<UnicodeCluster,{usize::MAX}>,String>{self.result()?;Ok(self.owners.output.take().unwrap())}
 pub fn cancel(&mut self){self.cancelled=true;}
}
