//! 📝️ Form field trees, widget references and optional content configuration.
use semio_framework_value::{ValueError,ValueRefusalKind};
use crate::standards::v1_7::subsets::base::io::sqlite::snapshot::*;
fn write_names(out:&mut Projection<'_,'_>,key:i64,role:&str,names:&[String])->Result<(),ValueError>{for(ordinal,name)in names.iter().enumerate(){out.insert("pdf_field_name",&[C::Integer(key),C::Integer(ordinal as i64),C::Text(role),C::Text(name)])?;}Ok(())}
fn read_names(reader:&mut Reader<'_,'_,'_>,key:i64,role:&'static str)->Result<Vec<String>,ValueError>{let mut names=Vec::new();for row in reader.children_with_role("pdf_field_name",1,2,key,Some((3,role)))?{let row=reader.take("pdf_field_name",row.rowid,5)?;names.push(reader.text(row,4)?);}Ok(names)}
fn write_field_shallow(out:&mut Projection<'_,'_>,value:&PdfFormField)->Result<i64,ValueError>{
    let mut fields=[C::Null;6];
    let kind=match &value.kind{PdfFormFieldKind::Button{value,default_value,..}=>{fields[0]=text_cell(value);fields[1]=text_cell(default_value);"button"},PdfFormFieldKind::Text{value,default_value,max_length,rich_value}=>{fields[0]=text_cell(value);fields[1]=text_cell(default_value);fields[2]=integer_cell(*max_length);fields[3]=text_cell(rich_value);"text"},PdfFormFieldKind::Choice{top_index,..}=>{fields[4]=integer_cell(*top_index);"choice"},PdfFormFieldKind::Signature{value}=>{fields[5]=value.as_ref().map(|value|cos::write_dictionary(out,value)).transpose()?.map_or(C::Null,C::Integer);"signature"},PdfFormFieldKind::Container=>"container"};
    let actions=cos::write_dictionary(out,&value.additional_actions)?;let extra=cos::write_dictionary(out,&value.extra)?;let mut cells=vec![C::Text(&value.name),C::Text(kind),C::Integer(i64::from(value.flags)),text_cell(&value.alternate_name),text_cell(&value.mapping_name),text_cell(&value.default_appearance),integer_cell(value.quadding)];cells.extend(fields);cells.extend([C::Integer(actions),C::Integer(extra)]);let key=out.insert("pdf_form_field",&cells)?;
    match &value.kind{PdfFormFieldKind::Button{options,..}=>write_names(out,key,"option",options)?,PdfFormFieldKind::Choice{values,default_values,options,..}=>{write_names(out,key,"value",values)?;write_names(out,key,"default",default_values)?;for(ordinal,(export,display))in options.iter().enumerate(){out.insert("pdf_choice_option",&[C::Integer(key),C::Integer(ordinal as i64),C::Text(export),C::Text(display)])?;}},_=>{}}
    for(ordinal,widget)in value.widgets.iter().enumerate(){out.insert("pdf_field_widget",&[C::Integer(key),C::Integer(ordinal as i64),C::Integer(i64::from(widget[0])),C::Integer(i64::from(widget[1]))])?;}
    Ok(key)
}
fn read_field_shallow(reader:&mut Reader<'_,'_,'_>,key:i64)->Result<PdfFormField,ValueError>{
    let row=reader.take("pdf_form_field",key,16)?;
    let(kind,present):(PdfFormFieldKind,&[usize])=match row.text(2)?{"button"=>(PdfFormFieldKind::Button{value:reader.optional_text(row,8)?,default_value:reader.optional_text(row,9)?,options:read_names(reader,key,"option")?},&[8,9]),"text"=>(PdfFormFieldKind::Text{value:reader.optional_text(row,8)?,default_value:reader.optional_text(row,9)?,max_length:optional_typed_integer(row,10)?,rich_value:reader.optional_text(row,11)?},&[8,9,10,11]),"choice"=>{let mut options=Vec::new();for child in reader.children("pdf_choice_option",1,2,key)?{let child=reader.take("pdf_choice_option",child.rowid,5)?;options.push((reader.text(child,3)?,reader.text(child,4)?));}(PdfFormFieldKind::Choice{values:read_names(reader,key,"value")?,default_values:read_names(reader,key,"default")?,options,top_index:optional_typed_integer(row,12)?},&[12])},"signature"=>(PdfFormFieldKind::Signature{value:optional_integer(row,13)?.map(|key|cos::read_dictionary(reader,key)).transpose()?},&[13]),"container"=>(PdfFormFieldKind::Container,&[]),_=>return Err(ValueError::new(ValueRefusalKind::InvalidValue,"unknown PDF form field kind"))};null_except(row,8..14,present)?;
    let mut widgets=Vec::new();for child in reader.children("pdf_field_widget",1,2,key)?{let child=reader.take("pdf_field_widget",child.rowid,5)?;widgets.push([integer(child,3)?,integer(child,4)?]);}let children=Vec::new();
    Ok(PdfFormField{name:reader.text(row,1)?,kind,flags:integer(row,3)?,alternate_name:reader.optional_text(row,4)?,mapping_name:reader.optional_text(row,5)?,default_appearance:reader.optional_text(row,6)?,quadding:optional_typed_integer(row,7)?,widgets,children,additional_actions:cos::read_dictionary(reader,row.integer(14)?)?,extra:cos::read_dictionary(reader,row.integer(15)?)?})
}
pub(super) fn write_acro(out:&mut Projection<'_,'_>,value:&PdfAcroForm)->Result<i64,ValueError>{let extra=cos::write_dictionary(out,&value.extra)?;let key=out.insert("pdf_acro_form",&[C::Integer(i64::from(value.need_appearances)),C::Integer(i64::from(value.signature_flags)),text_cell(&value.default_appearance),integer_cell(value.quadding),C::Integer(extra)])?;for(ordinal,field)in value.fields.iter().enumerate(){let field=write_field(out,field)?;out.insert("pdf_acro_field",&[C::Integer(key),C::Integer(ordinal as i64),C::Integer(field)])?;}for(ordinal,name)in value.default_fonts.iter().enumerate(){out.insert("pdf_acro_font",&[C::Integer(key),C::Integer(ordinal as i64),C::Text(name)])?;}Ok(key)}
pub(super) fn read_acro(reader:&mut Reader<'_,'_,'_>,key:i64)->Result<PdfAcroForm,ValueError>{let row=reader.take("pdf_acro_form",key,6)?;let mut fields=Vec::new();for child in reader.children("pdf_acro_field",1,2,key)?{let child=reader.take("pdf_acro_field",child.rowid,4)?;fields.push(read_field(reader,child.integer(3)?)?);}let mut default_fonts=Vec::new();for child in reader.children("pdf_acro_font",1,2,key)?{let child=reader.take("pdf_acro_font",child.rowid,4)?;default_fonts.push(reader.text(child,3)?);}Ok(PdfAcroForm{fields,need_appearances:boolean(row,1)?,signature_flags:integer(row,2)?,default_appearance:reader.optional_text(row,3)?,quadding:optional_typed_integer(row,4)?,default_fonts,extra:cos::read_dictionary(reader,row.integer(5)?)?})}
pub(super) fn write_optional(out:&mut Projection<'_,'_>,value:&PdfOptionalContent)->Result<i64,ValueError>{let extra=cos::write_dictionary(out,&value.extra)?;let key=out.insert("pdf_optional_content",&[text_cell(&value.name),C::Integer(i64::from(value.base_state_off)),C::Integer(extra)])?;for(ordinal,group)in value.groups.iter().enumerate(){let usage=cos::write_dictionary(out,&group.usage)?;let group_key=out.insert("pdf_optional_group",&[C::Integer(key),C::Integer(ordinal as i64),C::Text(&group.id),C::Text(&group.name),C::Integer(usage)])?;for(ordinal,intent)in group.intent.iter().enumerate(){out.insert("pdf_optional_group_intent",&[C::Integer(group_key),C::Integer(ordinal as i64),C::Text(intent)])?;}}
    for(role,names)in[("on",&value.on),("off",&value.off)]{for(ordinal,name)in names.iter().enumerate(){out.insert("pdf_optional_name",&[C::Integer(key),C::Integer(ordinal as i64),C::Text(role),C::Text(name)])?;}}
    for(ordinal,value)in value.order.iter().enumerate(){let value=cos::write_object(out,value)?;out.insert("pdf_optional_order",&[C::Integer(key),C::Integer(ordinal as i64),C::Integer(value)])?;}Ok(key)
}
pub(super) fn read_optional(reader:&mut Reader<'_,'_,'_>,key:i64)->Result<PdfOptionalContent,ValueError>{let row=reader.take("pdf_optional_content",key,4)?;let mut groups=Vec::new();for group in reader.children("pdf_optional_group",1,2,key)?{let group=reader.take("pdf_optional_group",group.rowid,6)?;let mut intent=Vec::new();for child in reader.children("pdf_optional_group_intent",1,2,group.rowid)?{let child=reader.take("pdf_optional_group_intent",child.rowid,4)?;intent.push(reader.text(child,3)?);}groups.push(PdfOptionalContentGroup{id:reader.text(group,3)?,name:reader.text(group,4)?,intent,usage:cos::read_dictionary(reader,group.integer(5)?)?});}
    let mut on=Vec::new();let mut off=Vec::new();for(role,names)in[("on",&mut on),("off",&mut off)]{for child in reader.children_with_role("pdf_optional_name",1,2,key,Some((3,role)))?{let child=reader.take("pdf_optional_name",child.rowid,5)?;names.push(reader.text(child,4)?);}}let mut order=Vec::new();for child in reader.children("pdf_optional_order",1,2,key)?{let child=reader.take("pdf_optional_order",child.rowid,4)?;order.push(cos::read_object(reader,child.integer(3)?)?);}Ok(PdfOptionalContent{groups,name:reader.optional_text(row,1)?,base_state_off:boolean(row,2)?,on,off,order,extra:cos::read_dictionary(reader,row.integer(3)?)?})}

fn write_field(out:&mut Projection<'_,'_>,field:&PdfFormField)->Result<i64,ValueError>{
    let key=write_field_shallow(out,field)?;let mut pending=vec![(key,field.children.iter().enumerate())];
    while let Some((parent,children))=pending.last_mut(){if let Some((ordinal,child))=children.next(){let parent=*parent;let key=write_field_shallow(out,child)?;out.insert("pdf_field_child",&[C::Integer(parent),C::Integer(ordinal as i64),C::Integer(key)])?;pending.push((key,child.children.iter().enumerate()));}else{pending.pop();}}Ok(key)
}
fn read_field(reader:&mut Reader<'_,'_,'_>,key:i64)->Result<PdfFormField,ValueError>{
    let field=read_field_shallow(reader,key)?;let children=reader.children("pdf_field_child",1,2,key)?.into_iter();let mut pending=vec![(field,children)];
    loop{let child=pending.last_mut().and_then(|(_,children)|children.next());if let Some(child)=child{let child=reader.take("pdf_field_child",child.rowid,4)?;let key=child.integer(3)?;let field=read_field_shallow(reader,key)?;let children=reader.children("pdf_field_child",1,2,key)?.into_iter();pending.push((field,children));}else{let(field,_)=pending.pop().ok_or_else(||ValueError::new(ValueRefusalKind::InvalidValue,"PDF form field stack is empty"))?;if let Some((parent,_))=pending.last_mut(){parent.children.push(field);}else{return Ok(field);}}}
}
