[package]
name = "semio-s-plugin-imperative-logic"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "../../../../../../../✏️s/🔌️plugin/📜️imperative/🧩️extension/🧠️logic/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
neural_engine = { path = "../../../../../../../🧰️framework/🛍️product/💻️os/🔨️module/🧠️neural/⚙️engine/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-neural-engine" }
serde_json = "1.0.140"
