[package]
name = "semio-s-artifact-process-process3d"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "process process3d artifact"

[package.metadata.semio]
role = "s-module"

[lints]
workspace = true

[lib]
path = "../../🦀️.rs"

[dependencies]
semio-s-artifact-stdio-dwg = { workspace = true }
semio-s-artifact-stdio-gltf = { workspace = true }
semio-s-artifact-stdio-ifc = { workspace = true }
semio-s-artifact-stdio-json = { workspace = true }
semio-s-artifact-stdio-obj = { workspace = true }
semio-s-artifact-stdio-png = { workspace = true }
semio-s-artifact-stdio-semio = { workspace = true }
semio-s-artifact-stdio-step = { workspace = true }
semio-s-artifact-stdio-stl = { workspace = true }
semio-s-artifact-stdio-txt = { workspace = true }
semio-framework-os-kernel = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
semio-framework-schema = { path = "../../../../../../../🧰️framework/🔨️modules/🧬️schema/📦️packages/🦀️rust", package = "semio-framework-schema" }
semio-framework-3d = { path = "../../../../../../../🧰️framework/🔨️modules/🧊️3d/📦️packages/🦀️rust" }
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/📦️packages/🦀️rust", features = ["component-guest"], package = "semio-framework-plugin" }
semio-framework = { path = "../../../../../../../🧰️framework/📦️packages/🦀️rust", package = "semio-framework" }
semio-framework-job = { path = "../../../../../../../🧰️framework/🔨️modules/🧵️job/📦️packages/🦀️rust", package = "semio-framework-job" }
semio-framework-dispatch-macros = { path = "../../../../../../../🧰️framework/🔨️modules/🔀️dispatch/📦️packages/🦀️rust", package = "semio-framework-dispatch-macros" }
semio-framework-value-derive = { path = "../../../../../../../🧰️framework/🔨️modules/🌱️value/✨️derive/📦️packages/🦀️rust", package = "semio-framework-value-derive" }
serde_json.workspace = true
base64_codec = { path = "../../../../../../../🧰️framework/🔨️modules/🚪️io/🔤️base64/📦️packages/🦀️rust", package = "semio-framework-io-base64" }
framework_hash = { package = "semio-framework-hash", path = "../../../../../../../🧰️framework/🔨️modules/🔏️hash/📦️packages/🦀️rust" }

[dev-dependencies]
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/📦️packages/🦀️rust", features = ["component-guest", "artifact-app-testing"], package = "semio-framework-plugin" }
semio-framework-os-kernel = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel", features = ["protocol-laws"] }
semio-framework-async-macros = { path = "../../../../../../../🧰️framework/🔨️modules/⏳️async/✨️macros/📦️packages/🦀️rust" }
