import { readJsonFileV1, hashFileV1 } from "../native-json-inputs/📜️script.ts";
import { existsSync, readFileSync, realpathSync, statSync, readdirSync, mkdirSync, writeFileSync, linkSync, unlinkSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
const ticket=resolve(import.meta.dir,".."),out=resolve(ticket,"🗑️generated/current-native-origin/epoch-4"),[command,owner]=process.argv.slice(2),controller=new AbortController(),io={signal:controller.signal},sha=(body:Buffer|string)=>createHash("sha256").update(body).digest("hex"),helper=resolve(ticket,"current-native-origin-inputs-4/📜️script.ts"),runtimeHelper=resolve(ticket,"current-native-runtime-custody-inputs-8/📜️script.ts"),own=[import.meta.path,resolve(import.meta.dir,"fixtures.json"),resolve(ticket,"native-json-inputs/📜️script.ts")],bindings=own.map(path=>({path,sha256:sha(readFileSync(path))}));process.once("SIGINT",()=>controller.abort());process.once("SIGTERM",()=>controller.abort());
function admit(proof:any,expected:any){if(!proof||!Object.entries(expected).every(([key,value])=>isDeepStrictEqual(proof[key],value)))throw Error("Exact independently released current whole dispatcher proof required");}
function ownGuard(){controller.signal.throwIfAborted();for(const row of bindings)if(sha(readFileSync(row.path))!==row.sha256)throw Error("Current dispatcher authority advanced");}
function write(path:string,value:any){mkdirSync(dirname(path),{recursive:true});const temporary=path+".writing";writeFileSync(temporary,JSON.stringify(value),{flag:"wx"});linkSync(temporary,path);unlinkSync(temporary);}
if(command==="laws"){
 const fixtures=JSON.parse(readFileSync(own[1],"utf8")),Ajv=(await import("ajv/dist/2020.js")).default,validate=new Ajv({strict:true}).compile({type:"object",required:Object.keys(fixtures.expected),properties:Object.fromEntries(Object.entries(fixtures.expected).map(([key,value])=>[key,{const:value}]))}),checks=[];
 for(const row of fixtures.fixtures){let accepted=true;try{admit(row.proof,fixtures.expected);}catch{accepted=false;}const external=!!validate(row.proof);if(accepted!==row.accepted||external!==row.accepted)throw Error("Independent dispatcher oracle differs");checks.push({...row,accepted,external});}
 const controlRoot=resolve(out,"dispatcher4-source-controls"),sourceChecks:any[]=[];mkdirSync(controlRoot,{recursive:true});
 const mutations:any={valid:()=>{},"initial-bytes":(p:any)=>writeFileSync(p.initialChecks[0].destination,"advanced"),"prepared-bytes":(p:any)=>writeFileSync(p.checks[0].destination,"advanced"),"initial-member-extra":(p:any)=>writeFileSync(resolve(p.initialSnapshot,"🧰️framework/extra.rs"),"extra"),"prepared-member-extra":(p:any)=>writeFileSync(resolve(p.snapshot,"🧰️framework/extra.rs"),"extra"),"initial-member-missing":(p:any)=>unlinkSync(p.initialChecks[1].destination),"prepared-member-missing":(p:any)=>unlinkSync(p.checks[1].destination),"idempotence":(p:any)=>p.preparation.idempotent=false,"preparation-exit":(p:any)=>p.preparation.exitCode=1,"initial-authority-missing":(p:any)=>p.initialChecks=[],"pair-encoding":(p:any)=>p.preparation.pairs[0].encoding="utf8","pair-before-hash":(p:any)=>p.preparation.pairs[0].beforeHash="bad","pair-after-hash":(p:any)=>p.preparation.pairs[0].afterHash="bad","pair-forward":(p:any)=>p.preparation.pairs[0].forward.insert="bad","pair-inverse":(p:any)=>p.preparation.pairs[0].inverse.insert="bad","pair-initial-join":(p:any)=>p.preparation.pairs[0].path="absent","initial-expected":(p:any)=>p.initialChecks[0].expected="bad","prepared-expected":(p:any)=>p.checks[0].expected="bad","prepared-lock":(p:any,m:any)=>m.lock.afterHash="bad"};
 function fixture(id:string){const initialSnapshot=resolve(controlRoot,id,"initial"),snapshot=resolve(controlRoot,id,"prepared"),initialChecks:any[]=[],checks:any[]=[];for(const[base,rows,text]of[[initialSnapshot,initialChecks,"initial"],[snapshot,checks,"prepared"]]as any){mkdirSync(resolve(base,"🧰️framework"),{recursive:true});for(const[path,body]of[["Cargo.toml",text],["🧰️framework/owner.rs","fn owner() {}"],["Cargo.lock","lock"]]){const destination=resolve(base,path);writeFileSync(destination,body,{flag:"wx"});rows.push({path,destination,expected:sha(body)});}}const before=Buffer.from("initial").toString("base64"),after=Buffer.from("prepared").toString("base64"),pair={path:"Cargo.toml",encoding:"base64",before,after,beforeHash:sha("initial"),afterHash:sha("prepared"),forward:{start:0,delete:before,insert:after},inverse:{start:0,delete:after,insert:before}};return{plan:{initialSnapshot,snapshot,initialChecks,checks,preparation:{idempotent:true,exitCode:0,pairs:[pair]}},metadata:{lock:{afterHash:sha("lock")}}};}
 function observed(p:any,m:any){function members(base:string){return readdirSync(resolve(base,"🧰️framework")).sort();}return{preparation:p.preparation,initial:p.initialChecks.map((r:any)=>({path:r.path,expected:r.expected,actual:existsSync(r.destination)?sha(readFileSync(r.destination)):null})),prepared:p.checks.map((r:any)=>({path:r.path,expected:r.expected,actual:existsSync(r.destination)?sha(readFileSync(r.destination)):null})),members:[members(p.initialSnapshot),members(p.snapshot)],lock:m.lock.afterHash};}
 const baseline=fixture("oracle"),sourceOracle=new Ajv({strict:true}).compile({const:observed(baseline.plan,baseline.metadata)});for(const[id,mutate]of Object.entries(mutations)as any){const{plan,metadata}=fixture(id);mutate(plan,metadata);let accepted=true,refusal:string|null=null;try{sourceGuard(plan,metadata);}catch(error){accepted=false;refusal=String(error);}const external=!!sourceOracle(observed(plan,metadata)),expected=id==="valid";if(accepted!==expected||external!==expected)throw Error("Actual source guard mutation oracle differs "+id);sourceChecks.push({id,accepted,external,refusal});}
 ownGuard();write(resolve(out,"dispatcher4-laws.json"),{ready:true,bindings,checks,sourceChecks,nativeExecuted:false});process.exit(0);
}
if(command!=="run"||!["board","product"].includes(owner))throw Error("Exact current whole dispatch required");
const directory=resolve(out,owner),paths={plan:resolve(directory,"plan.json"),metadata:resolve(directory,"metadata.json"),runtime:resolve(directory,"runtime-import-custody8.json"),laws:resolve(out,"dispatcher4-laws.json"),proof:resolve(directory,"independent-release.json")},documents:any={};for(const[key,path]of Object.entries(paths)){documents[key]=await readJsonFileV1(path,io);bindings.push({path,sha256:await hashFileV1(path,io)});}const plan=documents.plan,metadata=documents.metadata,runtime=documents.runtime,laws=documents.laws,proof=documents.proof,expected={ready:true,owner,helperHash:sha(readFileSync(helper)),dispatcherHash:bindings[0].sha256,planHash:sha(readFileSync(paths.plan)),metadataHash:sha(readFileSync(paths.metadata)),runtimeHash:sha(readFileSync(paths.runtime)),lawsHash:sha(readFileSync(paths.laws))};admit(proof,expected);
if(!laws.ready||!isDeepStrictEqual(laws.bindings,bindings.slice(0,3))||!runtime.ready||runtime.owner!==owner||runtime.planHash!==expected.planHash||metadata.planHash!==expected.planHash||metadata.exitCode!==0||metadata.phases.length!==2||runtime.importFailure||runtime.gaps.length||!runtime.bindings.some((row:any)=>row.path===runtimeHelper&&row.sha256===sha(readFileSync(runtimeHelper))))throw Error("Exact current complete runtime/metadata/control custody required");
function sourceGuard(plan:any,metadata:any){controller.signal.throwIfAborted();if(!plan.preparation?.idempotent||plan.preparation.exitCode!==0||!plan.initialChecks?.length)throw Error("Exact actual current preparation lifecycle required");for(const row of [...plan.initialChecks,...plan.checks]){const expected=row.destination===resolve(plan.snapshot,"Cargo.lock")?metadata.lock.afterHash:row.expected,current=existsSync(row.destination)?sha(readFileSync(row.destination)):null;if(current!==expected)throw Error("Current complete initial/prepared source advanced "+row.path);}for(const row of plan.preparation.pairs){if(row.encoding!=="base64")throw Error("Exact full preparation encoding required");const before=row.before===null?null:Buffer.from(row.before,"base64"),after=row.after===null?null:Buffer.from(row.after,"base64");if((before?sha(before):null)!==row.beforeHash||(after?sha(after):null)!==row.afterHash||row.forward.start!==0||row.forward.delete!==row.before||row.forward.insert!==row.after||row.inverse.start!==0||row.inverse.delete!==row.after||row.inverse.insert!==row.before)throw Error("Current complete preparation pair differs");const initial=plan.initialChecks.find((check:any)=>check.path===row.path),prepared=plan.checks.find((check:any)=>check.path===row.path);if((initial?.expected??null)!==row.beforeHash||(prepared?.expected??null)!==row.afterHash)throw Error("Current preparation pair not joined to initial/prepared authority");}const ignored=new Set(["node_modules",".git",".nx","target","dist","build","🗑️generated","coverage",".venv","__pycache__"]);for(const[base,rows]of[[plan.initialSnapshot,plan.initialChecks],[plan.snapshot,plan.checks]]){const paths=new Set<string>();function walk(path:string,key:string){if(statSync(path).isDirectory()){for(const name of readdirSync(path))if(!ignored.has(name))walk(resolve(path,name),key+"/"+name);}else if(statSync(path).isFile())paths.add(key);}walk(resolve(base,"🧰️framework"),"🧰️framework");const expectedPaths=new Set(rows.filter((row:any)=>row.path.startsWith("🧰️framework/")&&row.expected!==null).map((row:any)=>row.path));if(paths.size!==expectedPaths.size||[...paths].some(path=>!expectedPaths.has(path)))throw Error("Current initial/prepared framework membership advanced");}}
function runtimeGuard(){ownGuard();sourceGuard(plan,metadata);for(const row of runtime.links)if(!existsSync(row.path)||realpathSync(row.path)!==row.target)throw Error("Current runtime symlink mapping advanced");for(const row of runtime.bindings){controller.signal.throwIfAborted();if(!existsSync(row.path)||sha(readFileSync(row.path))!==row.sha256)throw Error("Current complete physical runtime body advanced "+row.path);}const bodies=new Set<string>();for(const packageRow of runtime.packages){const seen=new Set<string>();function walk(path:string){const actual=realpathSync(path);if(seen.has(actual))return;seen.add(actual);if(statSync(actual).isDirectory()){for(const name of readdirSync(actual))if(!["node_modules",".git",".cache"].includes(name))walk(resolve(actual,name));}else if(statSync(actual).isFile())bodies.add(actual);}walk(packageRow.base);}const expectedBodies=new Set(runtime.packageBodies.map((row:any)=>row.path));if(bodies.size!==expectedBodies.size||[...bodies].some(path=>!expectedBodies.has(path)))throw Error("Current complete physical runtime package membership advanced");}
const pre=resolve(directory,"dispatcher4-immediate-pre.json"),terminal=resolve(directory,"dispatcher4-terminal.json");runtimeGuard();write(pre,{at:new Date().toISOString(),bindings,expected,route:plan.route,nativeExecuted:false,historicalAcceptanceClaimed:false});console.log("[DEBUG] "+JSON.stringify({phase:"current-owning-whole-dispatch",owner,helper,proof:paths.proof}));let exitCode:number|null=null,refusal:string|null=null;try{const child=Bun.spawn([process.execPath,helper,"run",owner,paths.proof],{cwd:import.meta.dir,env:process.env,stdout:"inherit",stderr:"inherit",signal:controller.signal});exitCode=await child.exited;}catch(error){refusal=String(error);console.error(error);}let postRefusal:string|null=null;try{runtimeGuard();}catch(error){postRefusal=String(error);}write(terminal,{at:new Date().toISOString(),bindings,expected,route:plan.route,exitCode,refusal,postRefusal,cancelled:controller.signal.aborted,historicalAcceptanceClaimed:false,scope:"Current source original owning whole via exact current runtime/module/Low release; no historical floor or fallback"});process.exit(exitCode===0&&!refusal&&!postRefusal?0:1);
