[package]
name = "mathematical_graph_community"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph = { path = "../../rs" }
mathematical_graph_centrality = { path = "../../centrality/rs" }
mathematical_graph_cliques = { path = "../../cliques/rs" }
mathematical_random = { path = "../../../random/rs" }
