//! 🧪️ Native receipt conservation and malformed identity refusal use the real original paid ledger.
use super::*;
#[test]
fn original_actor_wire_refusals_preserve_exact_original_backing_without_heap(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../../🧪️tests/📄️checkpoint/🔣️.json")).unwrap();let mut input=receiving_input();input.operation=law["invalidOriginalOperation"].as_u64().unwrap();let budget=crate::lane_defaults::budget_for(crate::Lane::Interactive);let turn=crate::TurnGrant{retained:input,actor:crate::ActorId(7),shard:crate::ShardId(0),budget,envelopes:Vec::new()};let decision=crate::Decision{run:vec![turn.clone()],wake_at:None};let sentinel:Vec<u8>=serde_json::from_value(law["wireOutputSentinel"].clone()).unwrap();let mut output=Vec::with_capacity(256);output.extend_from_slice(&sentinel);let pointer=output.as_ptr();let original=(output.len(),output.capacity());
 macro_rules! producer{($producer:expr)=>{let(result,physical)=heap(||semio_framework_async::poll::resolve_ready($producer.pack_encode(&mut output)));assert_eq!(physical,(0,0));assert_eq!(result.unwrap_err().to_string(),law["wireRefusal"].as_str().unwrap());assert_eq!(output,sentinel);assert_eq!(output.as_ptr(),pointer);assert_eq!((output.len(),output.capacity()),original);assert_eq!(*turn.original_input(),input);};}
 producer!(turn);producer!(decision);eprintln!("[DEBUG] Actual original TurnGrant/Decision operation0 wire refusal before mutation preserves original sentinel/pointer/length/capacity/header/grant with exact allocator0/release0 and static cause");
}
#[semio_framework_async_macros::async_test]
async fn original_actor_zero_spend_replay_cannot_return_authority_for_a_new_issued_epoch(){
 let law=receiving_law();let input=receiving_input();let mut kernel=crate::Kernel::new(crate::ShardKind::Native,2,0,1).await;let actor=receiving_actor(&mut kernel,input).await;
 assert!(kernel.tick(0).await.run.is_empty());let entry=&kernel.scheduler.actors[&actor];assert_eq!(kernel.retained_turn(actor).unwrap(),input);assert!(entry.issued.is_none());assert!(!entry.returned);
 receiving_submit(&mut kernel,actor,1).await;let first=kernel.tick(1).await.run.pop().unwrap();assert_eq!(first.original_input().epoch,law["zeroSpend"]["firstEpoch"].as_u64().unwrap());let spent=serde_json::from_value(law["zeroSpend"]["spent"].clone()).unwrap();let result=receiving_result(*first.original_input(),spent);kernel.complete(actor,&result,2).await.unwrap();
 assert!(kernel.tick(3).await.run.is_empty());let entry=&kernel.scheduler.actors[&actor];assert_eq!(kernel.retained_turn(actor).unwrap(),input);assert!(entry.issued.is_none());assert!(entry.returned);
 receiving_submit(&mut kernel,actor,2).await;let second=kernel.tick(4).await.run.pop().unwrap();assert_eq!(second.original_input().epoch,law["zeroSpend"]["secondEpoch"].as_u64().unwrap());assert_eq!(second.original_input().grant,input.grant);let before=serde_json::to_value(&kernel.actors[&actor].metrics).unwrap();let pointer=result.effects.as_ptr();let(refusal,physical)=heap(||semio_framework_async::poll::resolve_ready(kernel.complete(actor,&result,5)));assert_eq!(physical,(0,0));assert_eq!(refusal.unwrap_err().to_string(),law["receiptRefusal"].as_str().unwrap());assert_eq!(result.effects.as_ptr(),pointer);assert_eq!(serde_json::to_value(&kernel.actors[&actor].metrics).unwrap(),before);assert_eq!(kernel.scheduler.actors[&actor].issued,Some(*second.original_input()));let next=receiving_result(*second.original_input(),spent);kernel.complete(actor,&next,6).await.unwrap();
 eprintln!("[DEBUG] Actual original Actor zero-spend receipt remains stale across genuine19-to20 admission, empty ticks preserve epoch, same remaining grant and refusal heap0/pointers/metrics unchanged");
}

#[semio_framework_async_macros::async_test]
async fn original_actor_epoch_overflow_refuses_before_removing_the_original_envelope(){
 let law=receiving_law();let input=RetainedTurnInput{epoch:law["overflow"]["epoch"].as_str().unwrap().parse().unwrap(),..receiving_input()};let mut kernel=crate::Kernel::new(crate::ShardKind::Native,2,0,1).await;let actor=receiving_actor(&mut kernel,input).await;
 receiving_submit(&mut kernel,actor,1).await;let first=kernel.tick(1).await.run.pop().unwrap();assert_eq!(*first.original_input(),input);let result=receiving_result(*first.original_input(),Default::default());kernel.complete(actor,&result,2).await.unwrap();receiving_submit(&mut kernel,actor,2).await;let entry=&kernel.scheduler.actors[&actor];let prior=(kernel.retained_turn(actor).unwrap(),entry.issued,entry.returned,entry.mailbox.len());assert_eq!(prior.3,1);
 for time in [3,4]{assert!(kernel.tick(time).await.run.is_empty());let entry=&kernel.scheduler.actors[&actor];assert_eq!((kernel.retained_turn(actor).unwrap(),entry.issued,entry.returned,entry.mailbox.len()),prior);}
 eprintln!("[DEBUG] Actual original Actor maximumu64 caller epoch first issued, checked next-epoch overflow retains same input/remaining/mailbox and emits no renewed turn");
}
fn heap<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}

fn receiving_law()->serde_json::Value{serde_json::from_str(include_str!("../🫴️receiving/🧫️fixtures/🔣️.json")).unwrap()}
fn receiving_input()->RetainedTurnInput{let law:serde_json::Value=serde_json::from_str(include_str!("../📃️policy/🧫️fixtures/🔣️.json")).unwrap();serde_json::from_value(law["input"].clone()).unwrap()}
fn receiving_result(input:RetainedTurnInput,spent:RetainedCloneProgress)->crate::TurnResult{crate::TurnResult{retained_receipt:input.return_original(spent).unwrap(),ui_patches:Vec::new(),effects:vec![81],command_ingress:Vec::new(),cold_pair_ingress:Default::default(),lifecycle_receipt:None,ui_patch_receipt:None,next_wake:None,status:crate::TurnStatus::Idle,usage:crate::Usage{fuel:100,wall_us:50,memory_bytes:1024}}}
async fn receiving_actor(kernel:&mut crate::Kernel,input:RetainedTurnInput)->crate::ActorId{let package=crate::PackageId("original-receiving".into());kernel.activate(package.clone(),7,crate::ActorKind::PluginApp{plugin:package,app_id:"original".into(),instance_id:0},crate::Lane::Interactive,None,crate::ActivationEvent::Manual,input).await}
async fn receiving_submit(kernel:&mut crate::Kernel,actor:crate::ActorId,seq:u64){let envelope=crate::Envelope{to:actor,from:crate::Origin::Kernel,lane:crate::Lane::Interactive,seq,deadline_ms:None,coalesce:None,cancel_of:None,payload:crate::Payload::Event{bytes:vec![1]}};assert_ne!(kernel.submit(&envelope).await,crate::Backpressure::Rejected)}

#[semio_framework_async_macros::async_test]
async fn original_actor_unissued_completion_refuses_before_metrics_and_preserves_result(){
 let law=receiving_law();let input=receiving_input();let mut kernel=crate::Kernel::new(crate::ShardKind::Native,2,0,1).await;let actor=receiving_actor(&mut kernel,input).await;let result=receiving_result(input,Default::default());let pointer=result.effects.as_ptr();let before=serde_json::to_value(&kernel.actors[&actor].metrics).unwrap();let status=kernel.actors[&actor].status.clone();let(refused,physical)=heap(||semio_framework_async::poll::resolve_ready(kernel.complete(actor,&result,1)));assert_eq!(serde_json::to_value([physical.0,physical.1]).unwrap(),law["refusalHeap"]);assert_eq!(refused.unwrap_err().to_string(),law["unissuedRefusal"].as_str().unwrap());assert_eq!(serde_json::to_value(&kernel.actors[&actor].metrics).unwrap(),before);assert_eq!(kernel.actors[&actor].status,status);assert_eq!(result.effects.as_ptr(),pointer);assert_eq!(result.retained_receipt.input,input);eprintln!("[DEBUG] Actual original Actor unissued completion refused heap0 same result pointer no metrics/status side effects");
}

#[semio_framework_async_macros::async_test]
async fn original_actor_issued_turn_refuses_forgery_and_duplicate_then_conserves_every_axis(){
 let law=receiving_law();let input=receiving_input();let mut kernel=crate::Kernel::new(crate::ShardKind::Native,2,0,1).await;let actor=receiving_actor(&mut kernel,input).await;receiving_submit(&mut kernel,actor,1).await;let first=kernel.tick(1).await.run.pop().unwrap();assert_eq!(*first.original_input(),input);receiving_submit(&mut kernel,actor,2).await;assert_eq!(serde_json::to_value(kernel.tick(2).await.run.is_empty()).unwrap(),law["blockedWhileIssued"]);
 let spent:RetainedCloneProgress=serde_json::from_value(law["spent"][0].clone()).unwrap();let result=receiving_result(*first.original_input(),spent);let pointer=result.effects.as_ptr();let before=serde_json::to_value(&kernel.actors[&actor].metrics).unwrap();let status=kernel.actors[&actor].status.clone();
 for axis in 0..13{let mut forged=result.clone();match axis{0=>forged.retained_receipt.input.operation+=1,1=>forged.retained_receipt.input.generation+=1,2=>forged.retained_receipt.input.epoch+=1,3=>forged.retained_receipt.input.grant.maximum_items+=1,4=>forged.retained_receipt.input.grant.maximum_copy_bytes+=1,5=>forged.retained_receipt.input.grant.maximum_capacity_bytes+=1,6=>forged.retained_receipt.input.grant.maximum_release_bytes+=1,7=>forged.retained_receipt.input.grant.maximum_depth+=1,8=>forged.retained_receipt.remaining.maximum_items+=1,9=>forged.retained_receipt.remaining.maximum_copy_bytes+=1,10=>forged.retained_receipt.remaining.maximum_capacity_bytes+=1,11=>forged.retained_receipt.remaining.maximum_release_bytes+=1,_=>forged.retained_receipt.remaining.maximum_depth+=1};let original=forged.effects.as_ptr();let(refused,physical)=heap(||semio_framework_async::poll::resolve_ready(kernel.complete(actor,&forged,3)));assert_eq!(serde_json::to_value([physical.0,physical.1]).unwrap(),law["refusalHeap"]);assert_eq!(refused.unwrap_err().to_string(),law["receiptRefusal"].as_str().unwrap());assert_eq!(forged.effects.as_ptr(),original);assert_eq!(serde_json::to_value(&kernel.actors[&actor].metrics).unwrap(),before);assert_eq!(kernel.actors[&actor].status,status);}
 kernel.complete(actor,&result,4).await.unwrap();assert_eq!(result.effects.as_ptr(),pointer);let accepted=serde_json::to_value(&kernel.actors[&actor].metrics).unwrap();let duplicate=kernel.complete(actor,&result,5).await;assert_eq!(serde_json::to_value(duplicate.is_err()).unwrap(),law["duplicateRefused"]);assert_eq!(serde_json::to_value(&kernel.actors[&actor].metrics).unwrap(),accepted);let second=kernel.tick(6).await.run.pop().unwrap();assert_eq!(second.original_input().operation,input.operation);assert_eq!(second.original_input().generation,input.generation);assert_eq!(serde_json::to_value(second.original_input().epoch).unwrap(),law["epochs"][1]);assert_eq!(serde_json::to_value(second.original_input().grant).unwrap(),law["remaining"][0]);assert!(kernel.complete(actor,&result,7).await.is_err());assert_eq!(serde_json::to_value(&kernel.actors[&actor].metrics).unwrap(),accepted);let spent:RetainedCloneProgress=serde_json::from_value(law["spent"][1].clone()).unwrap();let result=receiving_result(*second.original_input(),spent);assert_eq!(serde_json::to_value(result.retained_receipt.remaining).unwrap(),law["remaining"][1]);kernel.complete(actor,&result,8).await.unwrap();receiving_submit(&mut kernel,actor,3).await;assert_eq!(serde_json::to_value(kernel.tick(9).await.run.is_empty()).unwrap(),law["exhaustedNotReissued"]);eprintln!("[DEBUG] Actual original Actor issued identity71/3 epochs19/20 all13 forged axes heap0 same owner duplicate refused no renewal conserved all5 remaining currencies");
}
#[test]
fn original_retained_turn_receipt_roundtrips_all_identity_axes_and_rejects_every_forged_currency(){
 let fixture=include_str!("../🧫️fixtures/🔣️.json");let oracle:RetainedTurnReceipt=serde_json::from_str(fixture).unwrap();let original:RetainedTurnReceipt=semio_framework_pack_json::from_json_str(fixture,semio_framework_pack_json::JsonMemberPolicy::Reject).unwrap();assert_eq!(original,oracle);let input=original.input;let input_pointer=&input as*const _;
 let(admitted,measured)=heap(||semio_framework_job::JobPayloadAuthority::admit(semio_framework_job::OperationId(input.operation),semio_framework_job::Generation(input.generation),input.grant).unwrap());let(mut authority,birth)=admitted.unwrap();assert_eq!((birth.retained_capacity_bytes,birth.released_bytes),measured);assert_eq!(birth,original.spent);let(receipt,measured)=heap(||input.return_original(birth).unwrap());assert_eq!(measured,(0,0));assert_eq!(receipt,original);assert_eq!(&input as*const _,input_pointer);
 for altered in [RetainedTurnInput{operation:input.operation+1,..input},RetainedTurnInput{generation:input.generation+1,..input},RetainedTurnInput{epoch:input.epoch+1,..input},RetainedTurnInput{grant:RetainedCloneGrant{maximum_depth:input.grant.maximum_depth+1,..input.grant},..input}]{let(result,measured)=heap(||receipt.validate_for(altered));assert!(result.is_err());assert_eq!(measured,(0,0));assert_eq!(&input as*const _,input_pointer);}
 for spent in [RetainedCloneProgress{copied_items:input.grant.maximum_items+1,..birth},RetainedCloneProgress{copied_bytes:input.grant.maximum_copy_bytes+1,..birth},RetainedCloneProgress{retained_capacity_bytes:input.grant.maximum_capacity_bytes+1,..birth},RetainedCloneProgress{released_bytes:input.grant.maximum_release_bytes+1,..birth}]{let(result,measured)=heap(||input.return_original(spent));assert!(result.is_err());assert_eq!(measured,(0,0));}
 let corrupt=RetainedTurnReceipt{remaining:RetainedCloneGrant{maximum_release_bytes:receipt.remaining.maximum_release_bytes-1,..receipt.remaining},..receipt};let(result,measured)=heap(||corrupt.validate_for(input));assert!(result.is_err());assert_eq!(measured,(0,0));
 let mut bytes=Vec::with_capacity(160);let cursor=bytes.as_ptr();let(result,measured)=heap(||semio_framework_async::poll::resolve_ready(receipt.pack_encode(&mut bytes)));result.unwrap();assert_eq!(measured,(0,0));assert_eq!(bytes.as_ptr(),cursor);let mut position=0;let(decoded,measured)=heap(||semio_framework_async::poll::resolve_ready(RetainedTurnReceipt::pack_decode(&bytes,&mut position)));assert_eq!(decoded.unwrap(),receipt);assert_eq!(measured,(0,0));assert_eq!(position,bytes.len());assert_eq!(semio_framework_pack_json::to_json_string(&receipt),semio_framework_pack_json::to_json_string(&oracle));
 let(step,measured)=heap(||authority.close_step(input.grant).unwrap());assert_eq!((step.progress().retained_capacity_bytes,step.progress().released_bytes),measured);assert_eq!(birth.retained_capacity_bytes,step.progress().released_bytes);let(_,measured)=heap(||drop(authority));assert_eq!(measured,(0,0));eprintln!("[DEBUG] original native retained ABI3identity+5grant+4spent/remaining conserved, actualAuthority128, allforged0heap, Pack original backing pointer stable, terminalAuthorityDrop0");
}

#[semio_framework_async_macros::async_test]
async fn original_actor_lane_policy_preserves_supplied_retained_input_without_heap_or_renewal(){
 let law:serde_json::Value=serde_json::from_str(include_str!("../📃️policy/🧫️fixtures/🔣️.json")).unwrap();let input:RetainedTurnInput=serde_json::from_value(law["input"].clone()).unwrap();let pointer=&input as*const _;
 for lane in [crate::Lane::Interactive,crate::Lane::UserVisible,crate::Lane::Background,crate::Lane::Maintenance]{
  let(budget,measured)=heap(||crate::lane_defaults::budget_for(lane));assert_eq!(measured,(0,0));let(scaled,measured)=heap(||semio_framework_async::poll::resolve_ready(budget.scaled(0.125)));assert_eq!(measured,(0,0));assert!(scaled.fuel<budget.fuel);
  let mut kernel=crate::Kernel::new(crate::ShardKind::Native,2,0,1).await;let package=crate::PackageId("original-lane-policy".into());let actor=kernel.activate(package.clone(),7,crate::ActorKind::PluginApp{plugin:package,app_id:"original".into(),instance_id:0},lane,None,crate::ActivationEvent::Manual,input).await;kernel.scheduler.set_throttle(actor,0.125).await;receiving_submit(&mut kernel,actor,1).await;let turn=kernel.tick(1).await.run.pop().unwrap();assert_eq!(*turn.original_input(),input);assert_eq!(turn.budget,scaled);let wire=crate::TurnGrant{envelopes:Vec::new(),..turn.clone()};let mut packed=Vec::with_capacity(256);let backing=packed.as_ptr();let(result,measured)=heap(||semio_framework_async::poll::resolve_ready(wire.pack_encode(&mut packed)));result.unwrap();assert_eq!(measured,(0,0));assert_eq!(packed.as_ptr(),backing);let mut cursor=0;let(decoded,measured)=heap(||semio_framework_async::poll::resolve_ready(crate::TurnGrant::pack_decode(&packed,&mut cursor)));assert_eq!(measured,(0,0));assert_eq!(decoded.unwrap(),wire);assert_eq!(cursor,packed.len());assert_eq!(&input as*const _,pointer);
  let original=turn.original_input().return_original(RetainedCloneProgress{copied_items:1,..Default::default()}).unwrap();assert_eq!(original.remaining.maximum_items,input.grant.maximum_items-1);assert_eq!(original.remaining.maximum_copy_bytes,input.grant.maximum_copy_bytes);assert_eq!(original.remaining.maximum_capacity_bytes,input.grant.maximum_capacity_bytes);assert_eq!(original.remaining.maximum_release_bytes,input.grant.maximum_release_bytes);assert_eq!(original.remaining.maximum_depth,input.grant.maximum_depth);
 }
 eprintln!("[DEBUG] actual original Actor all4lane independent issued input71/3/19 all5currencies unchanged same supplied pointer scheduling scale and Pack original backing noHeap noScalarBridge receipt conservation");
}
