//! 🌱️ Exact owned PNG mutation oracle admitted by the independent PNG reader.
use semio_repo_test_host::Json;
use std::io::{Cursor,Write};

fn object(items:impl IntoIterator<Item=(&'static str,Json)>)->Json {Json::Object(items.into_iter().map(|(key,value)|(key.into(),value)).collect())}
fn number(value:impl Into<f64>)->Json {Json::Number(value.into())}
fn text(value:impl Into<String>)->Json {Json::String(value.into())}
fn integers(values:impl IntoIterator<Item=u16>)->Json {Json::Array(values.into_iter().map(number).collect())}
fn n(row:&Json,key:&str)->u64 {match row.get(key){Some(Json::Number(value))=>*value as u64,_=>0}}
fn yes(row:&Json,key:&str)->bool {matches!(row.get(key),Some(Json::Bool(true)))}
fn present<'a>(row:&'a Json,key:&str)->Option<&'a Json> {row.get(key).filter(|value|!matches!(value,Json::Null))}
fn set(row:&mut Json,key:&str,value:Json)->Result<(),String> {let Json::Object(fields)=row else{return Err("owned PNG field owner must be an object".into())};if let Some(field)=fields.iter_mut().find(|(name,_)|name==key){field.1=value}else{fields.push((key.into(),value))}Ok(())}
fn color(name:&str)->Result<png::ColorType,String>{match name{"grayscale"=>Ok(png::ColorType::Grayscale),"rgb"=>Ok(png::ColorType::Rgb),"palette"=>Ok(png::ColorType::Indexed),"grayscaleAlpha"=>Ok(png::ColorType::GrayscaleAlpha),"rgba"=>Ok(png::ColorType::Rgba),_=>Err("unknown owned PNG color profile".into())}}
fn color_name(value:png::ColorType)->&'static str {match value{png::ColorType::Grayscale=>"grayscale",png::ColorType::Rgb=>"rgb",png::ColorType::Indexed=>"palette",png::ColorType::GrayscaleAlpha=>"grayscaleAlpha",png::ColorType::Rgba=>"rgba"}}
fn sample_count(value:png::ColorType)->usize {match value{png::ColorType::Grayscale|png::ColorType::Indexed=>1,png::ColorType::Rgb=>3,png::ColorType::GrayscaleAlpha=>2,png::ColorType::Rgba=>4}}
fn unpack(buffer:&[u8],width:usize,height:usize,channels:usize,depth:u8)->Result<Vec<u16>,String> {
 let row_samples=width.checked_mul(channels).ok_or("PNG oracle row overflow")?;let stride=(row_samples*usize::from(depth)).div_ceil(8);
 if buffer.len()!=stride*height{return Err("PNG oracle sample cardinality differs from native frame".into())}
 let mut samples=Vec::with_capacity(row_samples*height);
 for row in buffer.chunks_exact(stride){for index in 0..row_samples{samples.push(match depth{16=>u16::from_be_bytes([row[index*2],row[index*2+1]]),8=>u16::from(row[index]),1|2|4=>u16::from((row[index*usize::from(depth)/8]>>(8-usize::from(depth)-index*usize::from(depth)%8))&((1u8<<depth)-1)),_=>return Err("invalid native PNG precision".into())});}}
 Ok(samples)
}
fn chunk_scan(bytes:&[u8])->Result<Vec<([u8;4],Vec<u8>,bool)>,String>{let mut chunks=Vec::new();let mut at=8;let mut after=false;while at+12<=bytes.len(){let size=u32::from_be_bytes(bytes[at..at+4].try_into().map_err(|_|"PNG length")?)as usize;let kind=bytes[at+4..at+8].try_into().map_err(|_|"PNG type")?;let end=at+8+size;let data=bytes.get(at+8..end).ok_or("PNG chunk truncated")?.to_vec();chunks.push((kind,data,after));if &kind==b"IDAT"{after=true}if &kind==b"IEND"{break}at=end+4;}Ok(chunks)}

/// 🔬️ Reads every exact native sample before any display transform.
pub fn reading(bytes:&[u8])->Result<Json,String>{
 let mut reader=png::Decoder::new(Cursor::new(bytes)).read_info().map_err(|error|error.to_string())?;
 let mut buffer=vec![0;reader.output_buffer_size().ok_or("PNG oracle output extent")?];let frame=reader.next_frame(&mut buffer).map_err(|error|error.to_string())?;let info=reader.info();
 let depth=info.bit_depth as u8;let profile=info.color_type;let samples=unpack(&buffer[..frame.buffer_size()],frame.width as usize,frame.height as usize,sample_count(profile),depth)?;
 let palette=info.palette.as_ref().map_or(Json::Null,|values|Json::Array(values.chunks_exact(3).map(|value|object([("r",number(value[0])),("g",number(value[1])),("b",number(value[2]))])).collect()));
 let raw_transparency=chunk_scan(bytes)?.into_iter().find(|(kind,_,_)|kind==b"tRNS").map(|(_,data,_)|data);let transparency=match raw_transparency.as_deref(){Some(values)=>match profile{png::ColorType::Indexed=>object([("colorType",text("indexed")),("alpha",integers(values.iter().map(|value|u16::from(*value))))]),png::ColorType::Grayscale if values.len()==2=>object([("colorType",text("grayscale")),("gray",number(u16::from_be_bytes([values[0],values[1]])))]),png::ColorType::Rgb if values.len()==6=>object([("colorType",text("rgb")),("r",number(u16::from_be_bytes([values[0],values[1]]))),("g",number(u16::from_be_bytes([values[2],values[3]]))),("b",number(u16::from_be_bytes([values[4],values[5]])))]),_=>return Err("PNG oracle invalid native transparency".into())},None=>Json::Null};
 let chrm=info.chrm_chunk.map_or(Json::Null,|value|object([("whiteX",number(value.white.0.into_scaled())),("whiteY",number(value.white.1.into_scaled())),("redX",number(value.red.0.into_scaled())),("redY",number(value.red.1.into_scaled())),("greenX",number(value.green.0.into_scaled())),("greenY",number(value.green.1.into_scaled())),("blueX",number(value.blue.0.into_scaled())),("blueY",number(value.blue.1.into_scaled()))]));
 let mut texts=Vec::new();let mut text_at=[0usize;3];for(kind,_,_)in chunk_scan(bytes)?{match &kind{b"tEXt"=>{let value=info.uncompressed_latin1_text.get(text_at[0]).ok_or("PNG text admission order")?;text_at[0]+=1;texts.push(text_reading(&value.keyword,&value.text,"text",false,"",""));},b"zTXt"=>{let value=info.compressed_latin1_text.get(text_at[1]).ok_or("PNG compressed text admission order")?;text_at[1]+=1;texts.push(text_reading(&value.keyword,&value.get_text().map_err(|error|error.to_string())?,"zText",true,"",""));},b"iTXt"=>{let value=info.utf8_text.get(text_at[2]).ok_or("PNG UTF8 text admission order")?;text_at[2]+=1;texts.push(text_reading(&value.keyword,&value.get_text().map_err(|error|error.to_string())?,"iText",value.compressed,&value.language_tag,&value.translated_keyword));},_=>{}}}
 let mut timestamp=Json::Null;let mut background=Json::Null;let mut ancillary=Vec::new();
 for(kind,data,after)in chunk_scan(bytes)?{match &kind{b"tIME" if data.len()==7=>{timestamp=object([("year",number(u16::from_be_bytes([data[0],data[1]]))),("month",number(data[2])),("day",number(data[3])),("hour",number(data[4])),("minute",number(data[5])),("second",number(data[6]))]);},b"bKGD"=>{background=match profile{png::ColorType::Indexed if data.len()==1=>object([("colorType",text("indexed")),("index",number(data[0]))]),png::ColorType::Grayscale|png::ColorType::GrayscaleAlpha if data.len()==2=>object([("colorType",text("grayscale")),("gray",number(u16::from_be_bytes([data[0],data[1]])))]),_ if data.len()==6=>object([("colorType",text("rgb")),("r",number(u16::from_be_bytes([data[0],data[1]]))),("g",number(u16::from_be_bytes([data[2],data[3]]))),("b",number(u16::from_be_bytes([data[4],data[5]])))]),_=>return Err("PNG oracle invalid background".into())};},b"IHDR"|b"IDAT"|b"IEND"|b"PLTE"|b"tRNS"|b"gAMA"|b"cHRM"|b"sRGB"|b"pHYs"|b"tEXt"|b"zTXt"|b"iTXt"=>{},_=>ancillary.push(object([("kind",integers(kind.into_iter().map(u16::from))),("data",integers(data.into_iter().map(u16::from))),("afterRaster",Json::Bool(after))]))}}
 let image=object([("width",number(info.width)),("height",number(info.height)),("bitDepth",number(depth)),("colorType",text(color_name(profile))),("interlace",Json::Bool(info.interlaced)),("samples",integers(samples)),("palette",palette),("transparency",transparency),("gamma",info.gama_chunk.map_or(Json::Null,|value|number(value.into_scaled()))),("chromaticities",chrm),("srgb",info.srgb.map_or(Json::Null,|value|text(match value{png::SrgbRenderingIntent::Perceptual=>"perceptual",png::SrgbRenderingIntent::RelativeColorimetric=>"relativeColorimetric",png::SrgbRenderingIntent::Saturation=>"saturation",png::SrgbRenderingIntent::AbsoluteColorimetric=>"absoluteColorimetric"}))),("physicalDims",info.pixel_dims.map_or(Json::Null,|value|object([("ppuX",number(value.xppu)),("ppuY",number(value.yppu)),("unitIsMeter",Json::Bool(matches!(value.unit,png::Unit::Meter)))]))),("timestamp",timestamp),("background",background),("textChunks",Json::Array(texts)),("ancillaryChunks",Json::Array(ancillary))]);
 Ok(object([("schema",text("stdio.png")),("image",image)]))
}
fn text_reading(keyword:&str,value:&str,kind:&str,compressed:bool,language:&str,translated:&str)->Json {object([("keyword",text(keyword)),("value",text(value)),("compressed",Json::Bool(compressed)),("kind",text(kind)),("languageTag",text(language)),("translatedKeyword",text(translated))])}
/// 🧿️ Compact exact-sample observation with every native owned metadata field.
pub fn project(bytes:&[u8])->Result<Json,String>{let mut snapshot=reading(bytes)?;let Json::Object(fields)=&mut snapshot else{unreachable!()};let Json::Object(image)=&mut fields.iter_mut().find(|(key,_)|key=="image").ok_or("PNG image missing")?.1 else{unreachable!()};let at=image.iter().position(|(key,_)|key=="samples").ok_or("PNG samples missing")?;let(_,samples)=image.remove(at);let Json::Array(samples)=samples else{unreachable!()};let count=samples.len();let mut hash=0xcbf29ce484222325u64;for sample in samples{let Json::Number(value)=sample else{unreachable!()};for byte in(value as u16).to_be_bytes(){hash=(hash^u64::from(byte)).wrapping_mul(0x100000001b3)}}image.push(("nativeSamplesDigest".into(),text(format!("{hash:016x}"))));image.push(("nativeSampleCount".into(),number(count as f64)));Ok(snapshot)}
fn values(row:&Json,key:&str)->Result<Vec<u16>,String>{row.array(key).iter().map(|value|match value{Json::Number(value)if value.fract()==0.0&&(0.0..=65535.0).contains(value)=>Ok(*value as u16),_=>Err(format!("invalid owned PNG {key} sample"))}).collect()}
fn pack(samples:&[u16],width:usize,height:usize,channels:usize,depth:u8)->Result<Vec<u8>,String>{let count=width.checked_mul(height).and_then(|value|value.checked_mul(channels)).ok_or("PNG sample extent")?;if samples.len()!=count{return Err("owned PNG sample count differs".into())}let maximum=if depth==16{65535}else{(1u16<<depth)-1};if samples.iter().any(|value|*value>maximum){return Err("owned PNG sample exceeds precision".into())}let row_samples=width*channels;let stride=(row_samples*usize::from(depth)).div_ceil(8);let mut bytes=vec![0;stride*height];for(row,source)in samples.chunks_exact(row_samples).enumerate(){for(index,value)in source.iter().copied().enumerate(){let target=&mut bytes[row*stride..(row+1)*stride];match depth{16=>target[index*2..index*2+2].copy_from_slice(&value.to_be_bytes()),8=>target[index]=value as u8,1|2|4=>target[index*usize::from(depth)/8]|=(value as u8)<<(8-usize::from(depth)-index*usize::from(depth)%8),_=>return Err("owned PNG precision".into())}}}Ok(bytes)}

/// 📤️ Materializes owned values using the independent PNG encoder.
pub fn encode(snapshot:&Json)->Result<Vec<u8>,String>{
 if snapshot.str("schema")!="stdio.png"{return Err("owned PNG schema identity differs".into())}let image=snapshot.get("image").ok_or("owned PNG image missing")?;let width=n(image,"width")as u32;let height=n(image,"height")as u32;let profile=color(&image.str("colorType"))?;let depth=n(image,"bitDepth")as u8;let samples=values(image,"samples")?;
 let mut bytes=Vec::new();{
 let mut encoder=png::Encoder::new(&mut bytes,width,height);encoder.set_color(profile);encoder.set_depth(png::BitDepth::from_u8(depth).ok_or("owned PNG depth")?);
 if let Some(palette)=present(image,"palette"){let Json::Array(entries)=palette else{return Err("owned PNG palette".into())};encoder.set_palette(entries.iter().flat_map(|value|[n(value,"r")as u8,n(value,"g")as u8,n(value,"b")as u8]).collect::<Vec<_>>());}
 if let Some(value)=present(image,"transparency"){let raw=match value.str("colorType").as_str(){"indexed"=>values(value,"alpha")?.into_iter().map(|value|value as u8).collect(),"grayscale"=>(n(value,"gray")as u16).to_be_bytes().to_vec(),"rgb"=>["r","g","b"].into_iter().flat_map(|key|(n(value,key)as u16).to_be_bytes()).collect(),_=>return Err("owned PNG transparency".into())};encoder.set_trns(raw);}
 if let Some(value)=present(image,"gamma"){let Json::Number(value)=value else{return Err("owned PNG gamma".into())};encoder.set_source_gamma(png::ScaledFloat::from_scaled(*value as u32));}
 if let Some(value)=present(image,"chromaticities"){let scaled=|key|png::ScaledFloat::from_scaled(n(value,key)as u32);encoder.set_source_chromaticities(png::SourceChromaticities{white:(scaled("whiteX"),scaled("whiteY")),red:(scaled("redX"),scaled("redY")),green:(scaled("greenX"),scaled("greenY")),blue:(scaled("blueX"),scaled("blueY"))});}
 if let Some(Json::String(value))=present(image,"srgb"){encoder.set_source_srgb(match value.as_str(){"relativeColorimetric"=>png::SrgbRenderingIntent::RelativeColorimetric,"saturation"=>png::SrgbRenderingIntent::Saturation,"absoluteColorimetric"=>png::SrgbRenderingIntent::AbsoluteColorimetric,_=>png::SrgbRenderingIntent::Perceptual});}
 if let Some(value)=present(image,"physicalDims"){encoder.set_pixel_dims(Some(png::PixelDimensions{xppu:n(value,"ppuX")as u32,yppu:n(value,"ppuY")as u32,unit:if yes(value,"unitIsMeter"){png::Unit::Meter}else{png::Unit::Unspecified}}));}
 let mut writer=encoder.write_header().map_err(|error|error.to_string())?;
 if let Some(value)=present(image,"timestamp"){let mut data=(n(value,"year")as u16).to_be_bytes().to_vec();data.extend(["month","day","hour","minute","second"].map(|key|n(value,key)as u8));writer.write_chunk(png::chunk::ChunkType(*b"tIME"),&data).map_err(|error|error.to_string())?;}
 if let Some(value)=present(image,"background"){let data=match value.str("colorType").as_str(){"indexed"=>vec![n(value,"index")as u8],"grayscale"=>(n(value,"gray")as u16).to_be_bytes().to_vec(),"rgb"=>["r","g","b"].into_iter().flat_map(|key|(n(value,key)as u16).to_be_bytes()).collect(),_=>return Err("owned PNG background".into())};writer.write_chunk(png::chunk::ChunkType(*b"bKGD"),&data).map_err(|error|error.to_string())?;}
 for value in image.array("textChunks"){match value.str("kind").as_str(){"zText"=>writer.write_text_chunk(&png::text_metadata::ZTXtChunk::new(value.str("keyword"),value.str("value"))),"iText"=>{let mut chunk=png::text_metadata::ITXtChunk::new(value.str("keyword"),value.str("value"));chunk.compressed=yes(&value,"compressed");chunk.language_tag=value.str("languageTag");chunk.translated_keyword=value.str("translatedKeyword");writer.write_text_chunk(&chunk)},_=>writer.write_text_chunk(&png::text_metadata::TEXtChunk::new(value.str("keyword"),value.str("value")))}.map_err(|error|error.to_string())?;}
 let ancillary=image.array("ancillaryChunks");for value in ancillary.iter().filter(|value|!yes(value,"afterRaster")){write_ancillary(&mut writer,value)?;}
 writer.write_image_data(&pack(&samples,width as usize,height as usize,sample_count(profile),depth)?).map_err(|error|error.to_string())?;for value in ancillary.iter().filter(|value|yes(value,"afterRaster")){write_ancillary(&mut writer,value)?;}writer.finish().map_err(|error|error.to_string())?;
 }
 if yes(image,"interlace"){bytes=interlace(bytes,&samples,width as usize,height as usize,sample_count(profile),depth)?;}
 Ok(bytes)
}
fn write_ancillary<W:Write>(writer:&mut png::Writer<W>,value:&Json)->Result<(),String>{let kind:Vec<u8>=values(value,"kind")?.into_iter().map(|value|value as u8).collect();let kind:[u8;4]=kind.try_into().map_err(|_|"owned PNG ancillary type")?;let data:Vec<u8>=values(value,"data")?.into_iter().map(|value|value as u8).collect();writer.write_chunk(png::chunk::ChunkType(kind),&data).map_err(|error|error.to_string())}
fn crc(bytes:&[u8])->u32{let mut value=u32::MAX;for byte in bytes{value^=u32::from(*byte);for _ in 0..8{value=(value>>1)^if value&1!=0{0xedb88320}else{0};}}!value}
fn append_chunk(output:&mut Vec<u8>,kind:[u8;4],data:&[u8]){output.extend_from_slice(&(data.len()as u32).to_be_bytes());let at=output.len();output.extend_from_slice(&kind);output.extend_from_slice(data);let checksum=crc(&output[at..]);output.extend_from_slice(&checksum.to_be_bytes());}
fn interlace(bytes:Vec<u8>,samples:&[u16],width:usize,height:usize,channels:usize,depth:u8)->Result<Vec<u8>,String>{let mut filtered=Vec::new();for(x0,y0,dx,dy)in [(0,0,8,8),(4,0,8,8),(0,4,4,8),(2,0,4,4),(0,2,2,4),(1,0,2,2),(0,1,1,2)]{if x0>=width||y0>=height{continue}let pass_width=(width-x0).div_ceil(dx);for y in (y0..height).step_by(dy){let mut row=Vec::new();for x in (x0..width).step_by(dx){row.extend_from_slice(&samples[(y*width+x)*channels..(y*width+x+1)*channels]);}filtered.push(0);filtered.extend(pack(&row,pass_width,1,channels,depth)?);}}let mut compressor=flate2::write::ZlibEncoder::new(Vec::new(),flate2::Compression::default());compressor.write_all(&filtered).map_err(|error|error.to_string())?;let compressed=compressor.finish().map_err(|error|error.to_string())?;let mut output=bytes[..8].to_vec();let mut wrote=false;for(kind,mut data,_)in chunk_scan(&bytes)?{if &kind==b"IHDR"{data[12]=1}if &kind==b"IDAT"{if !wrote{append_chunk(&mut output,kind,&compressed);wrote=true;}continue}append_chunk(&mut output,kind,&data);}Ok(output)}

/// 🔑️ Independent structural revision over the admitted owned fields.
pub fn revision(snapshot:&Json)->Result<String,String>{
 struct Hash(u64);impl Hash{fn raw(&mut self,values:&[u8]){for value in values{self.0=(self.0^u64::from(*value)).wrapping_mul(0x100000001b3)}}fn scalar(&mut self,value:u64){self.raw(&value.to_le_bytes())}fn string(&mut self,value:&str){self.scalar(value.len()as u64);self.raw(value.as_bytes())}}
 let mut hash=Hash(0xcbf29ce484222325);let image=snapshot.get("image").ok_or("owned PNG image")?;hash.string(&snapshot.str("schema"));for key in ["width","height","bitDepth"]{hash.scalar(n(image,key));}hash.scalar(color(&image.str("colorType"))?as u64);hash.scalar(u64::from(yes(image,"interlace")));let samples=values(image,"samples")?;hash.scalar(samples.len()as u64);for value in samples{hash.scalar(u64::from(value));}
 hash.scalar(u64::from(present(image,"palette").is_some()));if let Some(Json::Array(values))=present(image,"palette"){hash.scalar(values.len()as u64);for value in values{hash.raw(&[n(value,"r")as u8,n(value,"g")as u8,n(value,"b")as u8]);}}
 hash.scalar(u64::from(present(image,"transparency").is_some()));if let Some(value)=present(image,"transparency"){match value.str("colorType").as_str(){"indexed"=>{hash.scalar(3);let alpha=values(value,"alpha")?;hash.scalar(alpha.len()as u64);hash.raw(&alpha.into_iter().map(|value|value as u8).collect::<Vec<_>>());},"grayscale"=>{hash.scalar(0);hash.scalar(n(value,"gray"));},"rgb"=>{hash.scalar(2);for key in ["r","g","b"]{hash.scalar(n(value,key));}},_=>return Err("owned PNG transparency".into())}}
 hash.scalar(u64::from(present(image,"gamma").is_some()));if let Some(Json::Number(value))=present(image,"gamma"){hash.scalar(*value as u64);}
 for(key,fields)in [("chromaticities",&["whiteX","whiteY","redX","redY","greenX","greenY","blueX","blueY"][..]),("physicalDims",&["ppuX","ppuY"][..]),("timestamp",&["year","month","day","hour","minute","second"][..])]{if key=="physicalDims"{hash.scalar(u64::from(present(image,"srgb").is_some()));if let Some(Json::String(value))=present(image,"srgb"){hash.scalar(match value.as_str(){"perceptual"=>0,"relativeColorimetric"=>1,"saturation"=>2,"absoluteColorimetric"=>3,_=>return Err("owned PNG sRGB".into())});}}hash.scalar(u64::from(present(image,key).is_some()));if let Some(value)=present(image,key){for field in fields{hash.scalar(n(value,field));}if key=="physicalDims"{hash.scalar(u64::from(yes(value,"unitIsMeter")));}}}
 hash.scalar(u64::from(present(image,"background").is_some()));if let Some(value)=present(image,"background"){match value.str("colorType").as_str(){"indexed"=>{hash.scalar(3);hash.scalar(n(value,"index"));},"grayscale"=>{hash.scalar(0);hash.scalar(n(value,"gray"));},"rgb"=>{hash.scalar(2);for field in ["r","g","b"]{hash.scalar(n(value,field));}},_=>return Err("owned PNG background".into())}}
 let texts=image.array("textChunks");hash.scalar(texts.len()as u64);for value in texts{hash.string(&value.str("keyword"));hash.string(&value.str("value"));hash.scalar(u64::from(yes(&value,"compressed")));hash.scalar(match value.str("kind").as_str(){"text"=>0,"zText"=>1,"iText"=>2,_=>return Err("owned PNG text kind".into())});hash.string(&value.str("languageTag"));hash.string(&value.str("translatedKeyword"));}
 let ancillary=image.array("ancillaryChunks");hash.scalar(ancillary.len()as u64);for value in ancillary{hash.raw(&values(&value,"kind")?.into_iter().map(|value|value as u8).collect::<Vec<_>>());let data=values(&value,"data")?;hash.scalar(data.len()as u64);hash.raw(&data.into_iter().map(|value|value as u8).collect::<Vec<_>>());hash.scalar(u64::from(yes(&value,"afterRaster")));}Ok(format!("{:016x}",hash.0))
}

/// 🎨️ Applies the owned mutation independently and materializes its result once.
pub fn apply(input:&[u8],spec:&Json)->Result<Vec<u8>,String>{
 let mut snapshot=reading(input)?;let kind=spec.str("kind");let params=spec.get("params").ok_or("PNG mutation parameters missing")?;
 if matches!(kind.as_str(),"change-gamma"|"patch-pixels"|"paint-native-samples")&&params.str("revision")!=revision(&snapshot)?{return Err("PNG mutation names a stale owned revision".into())}
 match kind.as_str(){"change-gamma"=>{let Json::Object(fields)=&mut snapshot else{unreachable!()};let image=&mut fields.iter_mut().find(|(key,_)|key=="image").ok_or("PNG image missing")?.1;let gamma=params.get("gama").cloned().unwrap_or(Json::Null);if matches!(gamma,Json::Number(0.0)){return Err("PNG gamma must be positive".into())}set(image,"gamma",gamma)?;},"patch-pixels"|"paint-native-samples"=>{let image=snapshot.get("image").ok_or("PNG image missing")?;let profile=color(&image.str("colorType"))?;let channels=sample_count(profile);let rectangle=if kind=="patch-pixels"{params}else{params.get("region").ok_or("PNG region missing")?};let x=n(rectangle,"x")as usize;let y=n(rectangle,"y")as usize;let width=n(rectangle,"width")as usize;let height=n(rectangle,"height")as usize;let image_width=n(image,"width")as usize;if width==0||height==0||x+width>image_width||y+height>n(image,"height")as usize{return Err("PNG paint exceeds owned image".into())}let paint=if kind=="patch-pixels"{if profile!=png::ColorType::Rgba||n(image,"bitDepth")!=8{return Err("PNG RGBA patch profile differs".into())}["red","green","blue","alpha"].map(|key|n(params,key)as u16)}else{let value=params.get("paint").ok_or("PNG paint missing")?;let expected=match profile{png::ColorType::Indexed=>"indexed",png::ColorType::Grayscale=>"grayscale",png::ColorType::GrayscaleAlpha=>"grayscale-alpha",png::ColorType::Rgb=>"rgb",png::ColorType::Rgba=>"rgba"};if value.str("profile")!=expected{return Err("PNG native paint profile differs".into())}["first","second","third","fourth"].map(|key|n(value,key)as u16)};let mut samples=values(image,"samples")?;for row in y..y+height{for column in x..x+width{let at=(row*image_width+column)*channels;samples[at..at+channels].copy_from_slice(&paint[..channels]);}}let Json::Object(fields)=&mut snapshot else{unreachable!()};let image=&mut fields.iter_mut().find(|(key,_)|key=="image").ok_or("PNG image missing")?.1;set(image,"samples",integers(samples))?;if kind=="paint-native-samples"{let carried=params.get("result").ok_or("PNG completed paint result missing")?;if revision(carried)?!=revision(&snapshot)?{return Err("PNG carried native paint differs from independently recomputed result".into())}}},_=>return Err(format!("PNG oracle does not implement {kind}"))}encode(&snapshot)
}
