/** 🤖️ Generated by `bun ./📜️script.ts surface-schema` (surface-schema-projection) — do not edit.
 * @see ✏️s/🔌️plugins/🀄️wfc/🗿️artifacts/🧊️3d/🏅️standards/🔖️1/🪆️subsets/✳️any/✏️editor/🎚️config/🦀️.rs */
export interface Wfc3dConfig {
  /** @state config */
  cameraX: number;
  /** @state config */
  cameraY: number;
  /** @state config */
  cameraZoom: number;
  /** @state config */
  activeTileId: string;
}
