grammar Stdio_ply_snapshot;
document: 'semio' 'stdio.ply.dsl' 'v1' snapshot EOF;
snapshot: 'schema' '=' text 'format' '=' format 'comments' '=' '[' text* ']' 'elements' '=' '[' element* ']' 'values' '=' '[' value* ']';
format: 'ascii' | 'binaryLittleEndian' | 'binaryBigEndian';
element: '{' 'name' '=' text 'count' '=' INT 'properties' '=' '[' property* ']' 'rows' '=' '[' row* ']' '}';
property: '{' 'name' '=' text 'form' '=' ('scalar'|'list') propertyField* '}';
propertyField: ('scalar-kind'|'count-kind'|'value-kind') '=' scalarKind;
scalarKind: 'char'|'uchar'|'short'|'ushort'|'int'|'uint'|'float'|'double';
row: '{' 'values' '=' ids '}';
value: '{' 'kind' '=' (scalarKind|'list') valueField* 'list-values' '=' ids '}';
valueField: ('integer-value'|'float32-ieee754-bits'|'float64-ieee754-bits') '=' INT;
ids: '[' INT* ']';
text: IDENT|TEXT;
INT: '-'? [0-9]+;
IDENT: [a-zA-Z_] [a-zA-Z0-9_.-]*;
TEXT: '"' ('\\' . | ~["\\])* '"';
WS: [ \t\r\n]+ -> skip;
