import {test,expect} from "bun:test";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
const root=resolve(import.meta.dir,"../../../../../../../..");
const base=resolve(root,"✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any");
test("semantic constructors accept identity facts without hash or spelling",()=>{const source=readFileSync(resolve(base,"🧬️schema/🦀️.rs"),"utf8");expect(source.includes("DefaultHasher")).toBe(false);expect(source.includes("create_drawing_id")).toBe(false);expect(source).toContain("identity: DrawingIdentity");console.log("[DEBUG] Draw constructor identity facts accepted");});

import {createHash} from "node:crypto";
import {encodeIdentityPreimage,commitIdentity} from "../../../../../../../../✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any/🚪️io/💾️binary/🪪️identity/🟦️.ts";
import {encodeIdentityText} from "../../../../../../../../✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any/🚪️io/📝️text/🪪️identity/🟦️.ts";
const law=JSON.parse(readFileSync(resolve(import.meta.dir,"🔣️.json"),"utf8"));
test("neutral identity vectors equal independent crypto SHA256",()=>{for(const row of law.cases){const parts=row.parts.map((part:number[])=>Uint8Array.from(part));const preimage=encodeIdentityPreimage(row.kind,parts,{maximumBytes:65536});expect(Array.from(preimage)).toEqual(row.preimage);const independent=Array.from(createHash("sha256").update(preimage).digest());const commitment=commitIdentity(row.kind,parts,{maximumBytes:65568});expect(independent).toEqual(row.digest);expect(commitment.digest).toEqual(independent);expect(encodeIdentityText(commitment,{maximumBytes:76})).toBe(row.text);}console.log("[DEBUG] Draw identity neutral7 preimage/digest/text independent crypto accepted");});
test("physical identity limits cancellation and malformed facts refuse",()=>{const kind="layer";expect(()=>encodeIdentityPreimage(kind,[],{maximumBytes:12})).toThrow();expect(()=>encodeIdentityPreimage(kind,Array(65).fill(new Uint8Array()),{maximumBytes:65536})).toThrow();expect(()=>encodeIdentityPreimage(kind,[new Uint8Array(65536)],{maximumBytes:65536})).toThrow();expect(()=>encodeIdentityPreimage("unknown" as any,[],{maximumBytes:65536})).toThrow();expect(()=>commitIdentity(kind,[new Uint8Array(512)],{maximumBytes:65536,onProgress:n=>n<269})).toThrow();expect(()=>encodeIdentityText({kind,digest:[1]},{maximumBytes:72})).toThrow();expect(()=>encodeIdentityText({kind,digest:Array(32).fill(256)},{maximumBytes:72})).toThrow();const valid={kind,digest:Array(32).fill(0)} as const;expect(()=>encodeIdentityText(valid as any,{maximumBytes:69})).toThrow();expect(()=>encodeIdentityText(valid as any,{maximumBytes:70,onProgress:n=>n===0})).toThrow();console.log("[DEBUG] Draw physical identity9 refusal categories accepted");});

test("current native identity sources parse without touching files",()=>{const manifest=readFileSync(resolve(import.meta.dir,"../draw-identity-owner-manifest-current.md"),"utf8");const files=[...manifest.matchAll(/`([^`]+\.rs)`/g)].map(match=>resolve(root,match[1]!));for(const path of files){const parsed=Bun.spawnSync(["rustfmt","--emit","stdout","--edition","2021","--config","skip_children=true",path],{stdout:"ignore",stderr:"pipe"});expect(parsed.exitCode).toBe(0);}console.log(`[DEBUG] Draw native identity syntax ${files.length} source owners accepted`);},30000);

import {applyPatch} from "fast-json-patch";
import {DrawingIdentity,cloneDrawingLayerNode,parseDrawingIdentity,parseDrawingIdentityAssignment,parseDrawingIdentityCommitment} from "../../../../../../../../✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/🪪️identity/🟦️.ts";
test("neutral pure clone assignments match independent JSON patch and preserve source",()=>{const row=law.clone;const source=structuredClone(row.source);const clone=cloneDrawingLayerNode(source,row.suffix,row.identities);const oracle=applyPatch(structuredClone(source),[{op:"replace",path:"/id",value:"copied-group"},{op:"replace",path:"/name",value:"Group copy"},{op:"replace",path:"/children/0/id",value:"copied-child"},{op:"replace",path:"/children/1/id",value:"copied-boolean"},{op:"replace",path:"/children/1/children/0",value:"copied-child"}],true,false).newDocument;expect(clone).toEqual(oracle);expect(clone).toEqual(row.expected);expect(source).toEqual(row.source);for(const refusal of law.cloneRefusals)expect(()=>cloneDrawingLayerNode(source,row.suffix,refusal.identities)).toThrow();console.log("[DEBUG] Draw clone exact census/remap independent JSON patch and6 refusal categories");});

import {diff as duplicateDiff} from "../../../../../../../../✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/🧱️structure/🧬️schema/🧬️mutations/📋️duplicate-layer/🔺️diff/🟦️.ts";
import {inverse as duplicateInverse} from "../../../../../../../../✏️s/🔌️plugins/🖍️draw/🗿️artifacts/🖍️drawing/🏅️standards/🔖️1/🪆️subsets/🧱️structure/🧬️schema/🧬️mutations/📋️duplicate-layer/↩️inverse/🟦️.ts";
test("duplicate forward inverse use one admitted assignment payload",()=>{const row=law.clone;const payload={layerId:row.source.id,identities:row.identities};const delta=duplicateDiff(payload,row.source,{index:0},1,[]);expect(delta.layers.inserted[0]!.layer).toEqual(row.expected);expect(duplicateInverse(payload,row.source,[])).toEqual([{layerId:"copied-group"}]);expect(duplicateInverse(payload,undefined,[])).toEqual([]);expect(()=>duplicateDiff(payload,row.source,{index:0},1,["copied-child"])).toThrow();expect(()=>duplicateInverse(payload,row.source,["copied-child"])).toThrow();console.log("[DEBUG] Draw duplicate forward/inverse exact target facts, child collision refusal");});

import {semioSchemaAjvV1} from "../../../../../../../../🧰️framework/🔨️modules/🧬️schema/🔮️oracles/✅️validator/🟦️.ts";
import {validateJsonSchemaSubset} from "../../../../../../../../🧰️framework/🔨️modules/🧬️schema/✅️validator/🟦️.ts";
test("neutral identity records match independent Ajv and first-party schema",()=>{const schema=JSON.parse(readFileSync(resolve(base,"🧬️schema/🪪️identity/🔣️.json"),"utf8"));for(const row of law.recordCases){const contract=row.kind==="identity"?schema:{...schema,...schema.definitions[row.kind]};expect(Boolean(semioSchemaAjvV1().compile(contract)(row.value))).toBe(row.accepted);expect(validateJsonSchemaSubset(contract,row.value).length===0).toBe(row.accepted);const parser=row.kind==="identity"?parseDrawingIdentity:row.kind==="assignment"?parseDrawingIdentityAssignment:parseDrawingIdentityCommitment;let accepted=false;try{parser(row.value);accepted=true;}catch{}expect(accepted).toBe(row.accepted);}console.log("[DEBUG] Draw identity12 neutral records independent Ajv agrees with first-party schema");});

test("identity admission seals direct constructors and requires original operation facts",()=>{const model=readFileSync(resolve(base,"🧬️schema/🪪️identity/🦀️.rs"),"utf8");expect(model).not.toContain("pub key:");expect(model).not.toContain("impl From<");expect(model).toContain("pub fn admit(");const creation=readFileSync(resolve(base,"🚪️io/📝️text/🪪️identity/➕️creation/🦀️.rs"),"utf8");expect(creation).not.toContain("Option<&");expect(creation).not.toContain("map_or(0");});
test("original editor duplicate submits admitted DuplicateLayer and checks every target",()=>{const receiver=readFileSync(resolve(base,"✏️editor/🎮️commands/🎛️edit-selection/🦀️.rs"),"utf8");const duplicate=receiver.slice(receiver.indexOf('"duplicate" =>'),receiver.indexOf('"group" =>'));expect(duplicate).toContain("mutations::duplicate_layer(");expect(duplicate).toContain("for identity in &identities");expect(duplicate).toContain("previous.identities.iter()");expect(duplicate).not.toContain("document.clone()");expect(duplicate).not.toContain("mutations::create_layer(");});
test("identity production receivers preserve caller lifetime control",()=>{for(const name of ["➕️add-layer","🎛️edit-selection","📥️import-image"]){const receiver=readFileSync(resolve(base,`✏️editor/🎮️commands/${name}/🦀️.rs`),"utf8");expect(receiver).not.toMatch(/(?:callback|observer)\s*=\s*\|[^|]*\|\s*true/);}const retained=readFileSync(resolve(base,"✏️editor/📋️clipboard/🧵️job/🦀️.rs"),"utf8");expect(retained).not.toContain("let mut callback=|_|true");});

test("neutral lifetime cancellation matches platform AbortController and independent crypto",()=>{for(const row of law.lifetimeCases){const original=new AbortController();if(row.cancelBefore)original.abort();let accepted=false;try{const result=commitIdentity("layer",[new Uint8Array(512)],{maximumBytes:65536,onProgress:completed=>{if(row.cancelAt!==null&&completed>=row.cancelAt)original.abort();return !original.signal.aborted;}});const bytes=encodeIdentityPreimage("layer",[new Uint8Array(512)],{maximumBytes:65536});expect(result.digest).toEqual(Array.from(createHash("sha256").update(bytes).digest()));accepted=true;}catch{}expect(accepted).toBe(row.accepted);}console.log("[DEBUG] neutral original lifetime3 platform AbortController/crypto witnesses accepted");});

test("direct TypeScript identity construction is checked and immutable",()=>{for(const row of law.recordCases){if(row.kind!=="identity"||typeof row.value.key!=="string")continue;const key=row.value.key;let accepted=false;try{const identity=DrawingIdentity.admit(key);expect(identity.key).toBe(key);expect(Object.isFrozen(identity)).toBe(true);expect(JSON.parse(JSON.stringify(identity))).toEqual({key});accepted=true;}catch{}expect(accepted).toBe(key.length>0);}expect(()=>new (DrawingIdentity as any)("")).toThrow();console.log("[DEBUG] actual sealed TypeScript identity factory/direct constructor spelling agrees with neutral records");});


test("original IO route preserves both caller native controls before generic publication",()=>{const path=resolve(root,"🧰️framework/🛍️products/💻️os/🔨️modules/🚪️io/🦀️.rs");const source=readFileSync(path,"utf8");const body=source.slice(source.indexOf("pub mod io_mechanism"));expect(body).toContain("control: &mut IoRunControl");expect(body).toContain("(entry.run)(&current, control)");expect(body).not.toContain("IoPayload::Binary(outcome.value.encode_pack())");expect(body).not.toContain("S::decode_pack(&parent)");const svg=readFileSync(resolve(base,"🚪️io/📥️import/🧩️deserializers/🗿️artifacts/🎨️svg/🔖️1.1/✳️any/🦀️.rs"),"utf8");expect(svg).not.toContain("let mut callback=|_|true");expect(svg).toContain("control.encode");});

test("neutral original IO ownership and lifetime policy agrees with platform Buffer AbortController",()=>{for(const row of law.ioControlCases){const original=new AbortController();if(row.cancelBefore)original.abort();let accepted=false;try{if(original.signal.aborted)throw Error("Canceled");const decodeBytes=Buffer.concat([Buffer.from(row.decodeBefore),Buffer.from(row.body)]);if(decodeBytes.length>row.decodeMaximum)throw Error("OwnershipLimit");const encodeBytes=Buffer.concat([Buffer.from(row.encodeBefore),Buffer.from(row.body)]);if(encodeBytes.length>row.encodeMaximum)throw Error("OwnershipLimit");expect(Array.from(encodeBytes.subarray(row.encodeBefore.length))).toEqual(row.body);expect(decodeBytes.length).toBe(row.decodeOwned);expect(encodeBytes.length).toBe(row.encodeOwned);accepted=true;}catch(error){expect((error as Error).message).toBe(row.refusal);}expect(accepted).toBe(row.accepted);}console.log("[DEBUG] original IO neutral3 cumulative limits/cancellation independent Buffer AbortController");});
