import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, posix, resolve } from "node:path";

const ticket = dirname(import.meta.dir), root = resolve(ticket, "../../../../../../.."), require = createRequire(join(root, "package.json")), output = join(ticket, "🗑️generated/runtime-direction"), signal = new AbortController();
process.once("SIGINT", () => signal.abort()); process.once("SIGTERM", () => signal.abort());
const sha = (source: string) => createHash("sha256").update(source).digest("hex"), physical = (path: string) => existsSync(join(root, path)) ? readFileSync(join(root, path), "utf8") : null;

/** 🗒️ Retains the original note smoke predicates under their defining composition. */
async function execute(command: string, epoch: string) {
  const fixtureSource = readFileSync(join(import.meta.dir, "🧫️fixtures/🔣️.json"), "utf8"), schemaSource = readFileSync(join(import.meta.dir, "🧬️schema/🔣️.json"), "utf8"), fixture = JSON.parse(fixtureSource), { default: Ajv } = await import("ajv"), validate = new Ajv({ strict: true }).compile(JSON.parse(schemaSource)), { validateJsonSchemaSubset } = await import(join(root, "🧰️framework/🔨️modules/🧬️schema/✅️validator/🟦️.ts"));
  assert.equal(validate(fixture), true); assert.deepEqual(validateJsonSchemaSubset(JSON.parse(schemaSource), fixture), []); assert.deepEqual(require("json5").parse(fixtureSource), fixture);
  const hostile = [{ ...fixture, load: "manifest_for" }, { ...fixture, profiles: [...fixture.profiles].reverse() }, { ...fixture, descriptorPath: "../foreign" }, { ...fixture, foreign: true }];
  for (const input of hostile) { assert.equal(validate(input), false); assert.ok(validateJsonSchemaSubset(JSON.parse(schemaSource), input).length); }
  const frames: any[] = [], capture = (path: string) => { const source = physical(path); assert.notEqual(source, null); const frame = { path, source, sha256: sha(source!) }; frames.push(frame); return source!; }, rows: any[] = [], diff = require("diff");
  const add = (path: string, after: string | null) => { const before = physical(path), forward = diff.createPatch(path, before ?? "", after ?? ""), inverseEdit = diff.createPatch(path, after ?? "", before ?? ""); assert.equal(diff.applyPatch(before ?? "", forward, { fuzzFactor: 0 }), after ?? ""); assert.equal(diff.applyPatch(after ?? "", inverseEdit, { fuzzFactor: 0 }), before ?? ""); rows.push({ path, before, current: before, after, authored: after, inverse: before, beforeHash: before === null ? null : sha(before), afterHash: after === null ? null : sha(after), forward, inverseEdit }); };
  const original = capture(fixture.originalLaw), start = original.indexOf("//#region 🔖️NativeManifestSmoke"), end = original.indexOf("//#endregion 🔖️NativeManifestSmoke", start) + "//#endregion 🔖️NativeManifestSmoke".length;
  assert.ok(start >= 0 && end > start); const region = original.slice(start, end), rootSource = capture(fixture.owner + "/🦀️.rs"), manifestPath = fixture.owner + "/📦️packages/🦀️rust/Cargo.toml", manifestSource = capture(manifestPath), providerPath = "🧰️framework/🛍️products/💻️os/🔨️modules/🏃️run/🦀️.rs", provider = capture(providerPath), graph = capture("🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/🖥️host/🦀️.rs");
  const sourcePaths = [fixture.owner + "/📦️packages/🦀️rust/🦀️.rs", fixture.owner + "/📦️packages/🦀️rust/📜️script.ts", fixture.owner + "/📦️packages/🦀️rust/📋️project.json", "🌎️hub/Cargo.toml", "🧰️framework/🛍️products/💻️os/🔨️modules/🏃️run/📦️packages/🦀️rust/Cargo.toml", "🧰️framework/🛍️products/💻️os/🔨️modules/🏃️run/📦️packages/🦀️rust/🦀️.rs"];
  for (const path of sourcePaths) capture(path);
  assert.ok(provider.includes("    async fn manifest_for(")); assert.ok(!provider.includes("pub async fn manifest_for(")); assert.ok(provider.includes('pub async fn hot_reload_plugin(&mut self, plugin_id: &str) -> Result<(), RunError>')); assert.ok(provider.includes("self.manifest_for(plugin_id).await.map(|_| ())")); assert.ok(graph.includes("pub async fn manifest(&self, plugin_id: &str) -> Result<Option<PluginManifest>, PluginGraphError>"));
  const lawPath = fixture.owner + "/" + fixture.law, fixturePath = fixture.owner + "/" + fixture.fixture, schemaPath = fixture.owner + "/" + fixture.schema, pathe = require("pathe"), relative = posix.relative(posix.dirname(lawPath), fixturePath); assert.equal(relative, pathe.relative(pathe.dirname(lawPath), fixturePath)); assert.equal(posix.normalize(posix.join(posix.dirname(lawPath), relative)), fixturePath);
  const controls = fixture.profiles.map((profile: string) => { const path = posix.join(fixture.componentDirectory, profile, fixture.componentName); assert.equal(path, pathe.join(fixture.componentDirectory, profile, fixture.componentName)); return { profile, path, present: existsSync(join(root, path)) }; });
  assert.ok(existsSync(join(root, fixture.descriptorPath))); const descriptorBytes = readFileSync(join(root, fixture.descriptorPath)), binaryFrames = [{ path: fixture.descriptorPath, base64: descriptorBytes.toString("base64"), sha256: createHash("sha256").update(descriptorBytes).digest("hex") }], descriptor = capture(fixture.owner + "/🔣️.json"), descriptorValue = JSON.parse(descriptor), manifestDefinition = capture("🧰️framework/🔨️modules/🛂️manifest/🦀️.rs"); assert.equal(descriptorValue.manifest.pluginId, fixture.pluginId); assert.ok(descriptorValue.manifest.apps.length); assert.ok(descriptorValue.manifest.dependencies === undefined || descriptorValue.manifest.dependencies.length === 0); assert.ok(manifestDefinition.includes("pub dependencies: Vec<PluginDependency>"));
  if (command === "red") { const gaps = [{ kind: "general-provider-specific-law", path: fixture.originalLaw }, { kind: "missing-owned-law", path: lawPath }, { kind: "private-runtime-load-at-original-law", method: "manifest_for" }]; assert.equal(physical(lawPath), null); mkdirSync(output, { recursive: true }); writeFileSync(join(output, "hubnote-red-" + epoch + ".json"), JSON.stringify({ at: new Date().toISOString(), gaps, fixtureSource, schemaSource, frames, controls, sourceWrites: 0 }, null, 2), { flag: "wx" }); console.error("[DEBUG] Hub-owned note smoke closure RED " + JSON.stringify(gaps)); process.exitCode = 1; return; }
  assert.equal(command, "stage"); signal.signal.throwIfAborted(); const redPath = join(output, "hubnote-red-2.json"), redSource = readFileSync(redPath, "utf8"), red = JSON.parse(redSource); assert.equal(red.fixtureSource, fixtureSource); assert.equal(red.schemaSource, schemaSource); assert.equal(red.gaps.length, 3);
  let law = region.replace("//#region 🔖️NativeManifestSmoke\n", "").replace("//#endregion 🔖️NativeManifestSmoke", ""); law = law.replace(/    \/\/ 🚫️async:[\s\S]*?    \/\/ tokio\)\.\n/u, "");
  law = law.replace('    let descriptor_path = repo_root.join("' + fixture.descriptorPath + '");', '    let contract: serde_json::Value = serde_json::from_str(include_str!(' + JSON.stringify(relative) + ')).expect("note smoke contract");\n    let descriptor_path = repo_root.join(contract["descriptorPath"].as_str().expect("descriptor path"));');
  law = law.replace('    let candidate_wasm_paths = ["component-dev", "component-release"].map(|profile| repo_root.join("' + fixture.componentDirectory + '").join(profile).join("' + fixture.componentName + '"));', '    let candidate_wasm_paths = contract["profiles"].as_array().expect("component profiles").iter().map(|profile| repo_root.join(contract["componentDirectory"].as_str().expect("component directory")).join(profile.as_str().expect("component profile")).join(contract["componentName"].as_str().expect("component name")));');
  law = law.replace('    let manifest = host.manifest_for("note").await.expect("note must load natively from its committed descriptor, zero live describe() calls");', '    host.hot_reload_plugin("note").await.expect("note must load natively from its committed descriptor, zero live describe() calls");\n    let manifest = host.plugin_graph().manifest("note").await.expect("registered note manifest query").expect("loaded note manifest");');
  law = '//! 🗒️ Committed note descriptor smoke law owned by the note composition.\nuse std::{collections::HashMap, path::PathBuf, sync::Arc};\nuse semio_framework_os_run::{InMemoryBlobStore, WasmtimeNodeHost};\n\n' + law;
  const mount = '\n#[cfg(all(test, not(target_arch = "wasm32")))]\n#[path = ' + JSON.stringify(fixture.law) + ']\nmod committed_descriptor_tests;\n'; assert.ok(!rootSource.includes("mod committed_descriptor_tests")); assert.ok(!manifestSource.includes("semio-framework-os-run"));
  const providerManifest = posix.relative(posix.dirname(manifestPath), "🧰️framework/🛍️products/💻️os/🔨️modules/🏃️run/📦️packages/🦀️rust"); assert.equal(providerManifest, pathe.relative(pathe.dirname(manifestPath), "🧰️framework/🛍️products/💻️os/🔨️modules/🏃️run/📦️packages/🦀️rust"));
  const manifestAfter = manifestSource + '\n[target.\'cfg(not(target_arch = "wasm32"))\'.dev-dependencies]\nsemio-framework-os-run = { path = ' + JSON.stringify(providerManifest) + ', package = "semio-framework-os-run" }\n'; assert.deepEqual(Bun.TOML.parse(manifestAfter), require("@iarna/toml").parse(manifestAfter));
  add(fixturePath, fixtureSource); add(schemaPath, schemaSource); add(lawPath, law); add(fixture.owner + "/🦀️.rs", rootSource + mount); add(manifestPath, manifestAfter); add(fixture.originalLaw, original.slice(0, start) + original.slice(end));
  const loaded = require("web-tree-sitter"), Parser = loaded.Parser ?? loaded.default ?? loaded; await Parser.init(); const parser = new Parser(); parser.setLanguage(await (Parser.Language ?? loaded.Language).load(join(dirname(require.resolve("tree-sitter-wasms/package.json")), "out/tree-sitter-rust.wasm")));
  const oldTree = parser.parse(original), afterTree = parser.parse(rows.at(-1).after), regionTree = parser.parse(region), lawTree = parser.parse(law); for (const tree of [oldTree, afterTree, regionTree, lawTree]) assert.equal(tree.rootNode.hasError(), false);
  const oldFns = oldTree.rootNode.descendantsOfType("function_item"), regionFns = regionTree.rootNode.descendantsOfType("function_item"), newFns = lawTree.rootNode.descendantsOfType("function_item"); assert.equal(regionFns.length, 2); assert.equal(newFns.length, 2); assert.equal(newFns[0].text, regionFns[0].text); assert.deepEqual(afterTree.rootNode.descendantsOfType("function_item").map((node: any) => node.text), oldFns.filter((node: any) => !regionFns.some((leaf: any) => leaf.text === node.text)).map((node: any) => node.text));
  const assertions = (tree: any) => tree.rootNode.descendantsOfType("macro_invocation").filter((node: any) => /^(assert|assert_eq)!/u.test(node.text)).map((node: any) => node.text); assert.deepEqual(assertions(lawTree), assertions(regionTree)); assert.equal(assertions(lawTree).length, 8);
  const ownerTree = parser.parse(rootSource), ownerAfterTree = parser.parse(rootSource + mount); assert.equal(ownerTree.rootNode.hasError(), false); assert.equal(ownerAfterTree.rootNode.hasError(), false); assert.deepEqual(ownerAfterTree.rootNode.descendantsOfType("function_item").map((node: any) => node.text), ownerTree.rootNode.descendantsOfType("function_item").map((node: any) => node.text));
  const controlResults = { assertions: assertions(lawTree), retiredFunctions: regionFns.map((node: any) => node.childForFieldName("name").text), remainingOriginalFunctions: oldFns.length - 2, profilePaths: controls, schemaHostileRefusals: hostile.length, red: { path: redPath, source: redSource, sha256: sha(redSource) }, independent: ["Ajv", "JSON5", "pathe", "@iarna/toml", "tree-sitter-rust"] }; for (const tree of [oldTree, afterTree, regionTree, lawTree, ownerTree, ownerAfterTree]) tree.delete(); parser.delete();
  for (const row of rows) assert.equal(physical(row.path), row.before); for (const frame of frames) assert.equal(physical(frame.path), frame.source); assert.deepEqual(readFileSync(join(root, fixture.descriptorPath)), descriptorBytes); mkdirSync(output, { recursive: true }); const path = join(output, "hubnote-source-" + epoch + ".json"); writeFileSync(path, JSON.stringify({ at: new Date().toISOString(), fixtureSource, schemaSource, rows, frames, binaryFrames, controls: controlResults, sourceReady: true, sourceWrites: 0, nativeReady: false, publicRuntimeOnly: true, originalRoute: { script: fixture.owner + "/📦️packages/🦀️rust/📜️script.ts", project: "@semio-tech/note-plugin", command: "test", request: [], filters: [] }, scope: "Hub-owned original committed note smoke law; exact eight assert macros and original remaining law/helper bodies conserved. Public reload and registered-manifest query retain private host implementation; component absence retains original early return and supplies no native publication identity proof." }, null, 2), { flag: "wx" }); console.error("[DEBUG] Hub note source controls " + JSON.stringify({ ...controlResults, red: { path: redPath, sha256: sha(redSource) } })); console.log(JSON.stringify({ path, rows: rows.length, assertions: controlResults.assertions.length, sourceReady: true, nativeExecuted: false }));
}

const [command, epoch] = process.argv.slice(2); assert.ok(epoch); await execute(command, epoch);
