/** 🧪️ Hand-authored fixture specs for the `stdio.gltf` top-level `move-*` leaves. Each `before`
 * carries the referrer whose index `repair(<family>, Move(index, position))` has to rewrite. */
import type { Spec } from "./🛠️emit-gltf-fixture.ts";

const snap = (doc: Record<string, unknown>, buffers: unknown[] = []) => ({ schema: "stdio.gltf", document: { asset: { version: "2.0" }, ...doc }, buffers, sourceForm: "json" });
const opDiff = (leaf: string, touchedPaths: string[], payload: unknown, operation: unknown) => ({ id: `s.stdio.gltf.mutation.${leaf}.v1`, version: 1, touchedPaths, payload, operation });
/** ↔️ The two-slot touched-path list every single-lane move leaf emits for `0 → 1`. */
const swapPaths = (collection: string) => [`document/${collection}/0`, `document/${collection}/1`];
const SWAP = { kind: "move", index: 0, position: 1 };
const MOVE_0_TO_1 = { index: 0, position: 1 };

const A_ACCESSOR = { componentType: 5126, count: 3, type: "VEC3" };
const B_ACCESSOR = { componentType: 5126, count: 3, type: "VEC2" };
const PERSPECTIVE = { type: "perspective", perspective: { yfov: 0.5, znear: 0.5 } };
const ORTHOGRAPHIC = { type: "orthographic", orthographic: { xmag: 1.0, ymag: 1.0, zfar: 2.0, znear: 0.5 } };

export const SPECS: readonly Spec[] = [
  {
    leaf: "move-accessor",
    case: "swaps-the-position-and-texcoord-accessors",
    module: "move_accessor",
    api: "collection",
    payloadType: "GltfMoveAccessorPayload",
    diffType: "GltfMoveAccessorDiff",
    doc: "`operation()` is a bare `Move { index, position }` — no item payload at all, because a move neither\ncreates nor destroys. `repair(Accessors, Move(0, 1))` rewrites the primitive's attribute map in\nplace: `POSITION` 0→1 and `TEXCOORD_0` 1→0, while the attribute ORDER in the map is untouched.",
    before: snap({ meshes: [{ primitives: [{ attributes: { POSITION: 0, TEXCOORD_0: 1 } }] }], accessors: [A_ACCESSOR, B_ACCESSOR] }),
    after: snap({ meshes: [{ primitives: [{ attributes: { POSITION: 1, TEXCOORD_0: 0 } }] }], accessors: [B_ACCESSOR, A_ACCESSOR] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-accessor", swapPaths("accessors"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-accessor` reorders the collection and rewrites both attribute indices that pointed into it.",
      `assert_eq!(snapshot.document.accessors[0].kind, crate::artifacts::gltf::engine::GltfAccessorType::Vec2, "{CASE}: the VEC2 accessor must end up first");`,
      `assert_eq!(snapshot.document.meshes[0].primitives[0].attributes, vec![("POSITION".to_string(), 1usize), ("TEXCOORD_0".to_string(), 0usize)], "{CASE}: repair must renumber both attributes while preserving the map's own ordering");`,
    ],
    inverse: [
      "The inverse is the mirrored move that puts VEC3 back at index 0.",
      `assert_eq!(restored.document.meshes[0].primitives[0].attributes, vec![("POSITION".to_string(), 0usize), ("TEXCOORD_0".to_string(), 1usize)], "{CASE}: the inverse must restore both attribute indices");`,
    ],
    delta: [
      "The delta is two indices — it must never restate either accessor value.",
      `assert_eq!(produced.touched_paths, vec!["document/accessors/0".to_string(), "document/accessors/1".to_string()], "{CASE}: a move declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert!(matches!(decoded.operation, crate::artifacts::gltf::schema::mutations::move_accessor::diff::GltfMoveAccessorOperation::Move { index: 0, position: 1 }), "{CASE}: the committed operation must be a bare move, carrying no accessor value");`],
  },
  {
    leaf: "move-animation",
    case: "promotes-the-bob-clip-ahead-of-the-spin-clip",
    module: "move_animation",
    api: "collection",
    payloadType: "GltfMoveAnimationPayload",
    diffType: "GltfMoveAnimationDiff",
    doc: "Animations have no inbound references, so `repair(…, Animations, …)` is a no-op and the move is a\npure list rotation. `validate()` still refuses `index == position` with\n`gltf.mutation.no-observable-change`, which is why this fixture moves 0 to 1 rather than 0 to 0.",
    before: snap({ animations: [{ name: "spin" }, { name: "bob" }] }),
    after: snap({ animations: [{ name: "bob" }, { name: "spin" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-animation", swapPaths("animations"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-animation` rotates the clip list and cascades nowhere.",
      `assert_eq!(snapshot.document.animations[0].name.as_deref(), Some("bob"), "{CASE}: 'bob' must end up first");`,
      `assert_eq!(snapshot.document.animations[1].name.as_deref(), Some("spin"), "{CASE}: 'spin' must be pushed to index 1, not dropped");`,
    ],
    inverse: [
      "The inverse rotates the pair back so 'spin' leads again.",
      `assert_eq!(restored.document.animations[0].name.as_deref(), Some("spin"), "{CASE}: the inverse must restore the original clip order");`,
    ],
    delta: [
      "The delta is two indices; no clip body appears in it.",
      `assert_eq!(produced.touched_paths, vec!["document/animations/0".to_string(), "document/animations/1".to_string()], "{CASE}: move-animation declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.payload.position, 1, "{CASE}: the committed diff must echo the destination index");`],
  },
  {
    leaf: "move-buffer",
    case: "swaps-the-two-buffers-and-their-byte-lanes",
    module: "move_buffer",
    api: "collection",
    payloadType: "GltfMoveBufferPayload",
    diffType: "GltfMoveBufferDiff",
    doc: "The only move leaf that moves two lanes: `buffers_op(…, Move)` for the descriptors plus an explicit\n`remove`/`insert` on `snapshot.buffers`. `touched_paths()` accordingly names four slots. `validate()`\nalso carries the `gltf.mutation.buffer-alignment` guard, and `repair(Buffers, Move(0, 1))` rewrites\nthe REQUIRED `bufferView.buffer` references of BOTH views.",
    before: snap({ bufferViews: [{ buffer: 0, byteLength: 1 }, { buffer: 1, byteLength: 2 }], buffers: [{ byteLength: 1 }, { byteLength: 2 }] }, [[1], [2, 3]]),
    after: snap({ bufferViews: [{ buffer: 1, byteLength: 1 }, { buffer: 0, byteLength: 2 }], buffers: [{ byteLength: 2 }, { byteLength: 1 }] }, [[2, 3], [1]]),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-buffer", ["document/buffers/0", "document/buffers/1", "buffers/0", "buffers/1"], MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-buffer` moves descriptor and bytes in lockstep and retargets both bufferViews.",
      `assert_eq!(snapshot.buffers, vec![vec![2u8, 3], vec![1u8]], "{CASE}: the raw-byte lane must follow the descriptor move exactly");`,
      `assert_eq!((snapshot.document.buffer_views[0].buffer, snapshot.document.buffer_views[1].buffer), (1, 0), "{CASE}: repair(Buffers, Move(0, 1)) must rewrite both required buffer references");`,
    ],
    inverse: [
      "The inverse moves both lanes back and restores the original buffer references.",
      `assert_eq!(restored.buffers, vec![vec![1u8], vec![2u8, 3]], "{CASE}: the inverse must restore the original byte-lane order");`,
    ],
    delta: [
      "The delta declares four slots — two descriptor lanes and two byte lanes — and carries no bytes.",
      `assert_eq!(produced.touched_paths.len(), 4, "{CASE}: move-buffer is the only move leaf with a four-slot touched-path list");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.touched_paths, vec!["document/buffers/0".to_string(), "document/buffers/1".to_string(), "buffers/0".to_string(), "buffers/1".to_string()], "{CASE}: descriptor slots come before byte slots in the committed path list");`],
  },
  {
    leaf: "move-buffer-view",
    case: "swaps-the-two-windows-and-renumbers-both-accessors",
    module: "move_buffer_view",
    api: "collection",
    payloadType: "GltfMoveBufferViewPayload",
    diffType: "GltfMoveBufferViewDiff",
    doc: "`repair(BufferViews, Move(0, 1))` renumbers every `accessor.bufferView` and `image.bufferView`; both\naccessors here take the swap. `document/buffers` is untouched — moving a window does not move bytes,\nwhich is what separates this leaf from `move-buffer`.",
    before: snap({ accessors: [{ bufferView: 0, componentType: 5126, count: 1, type: "SCALAR" }, { bufferView: 1, componentType: 5126, count: 1, type: "SCALAR" }], bufferViews: [{ buffer: 0, byteLength: 4 }, { buffer: 0, byteOffset: 4, byteLength: 4 }], buffers: [{ byteLength: 8 }] }, [[0, 0, 0, 0, 1, 1, 1, 1]]),
    after: snap({ accessors: [{ bufferView: 1, componentType: 5126, count: 1, type: "SCALAR" }, { bufferView: 0, componentType: 5126, count: 1, type: "SCALAR" }], bufferViews: [{ buffer: 0, byteOffset: 4, byteLength: 4 }, { buffer: 0, byteLength: 4 }], buffers: [{ byteLength: 8 }] }, [[0, 0, 0, 0, 1, 1, 1, 1]]),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-buffer-view", swapPaths("bufferViews"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-buffer-view` swaps the windows and renumbers both accessors, leaving the byte lane alone.",
      `assert_eq!(snapshot.document.buffer_views[0].byte_offset, 4, "{CASE}: the window that started at byteOffset 4 must end up first");`,
      `assert_eq!((snapshot.document.accessors[0].buffer_view, snapshot.document.accessors[1].buffer_view), (Some(1), Some(0)), "{CASE}: repair(BufferViews, Move(0, 1)) must swap both accessor references");`,
      `assert_eq!(snapshot.buffers, vec![vec![0u8, 0, 0, 0, 1, 1, 1, 1]], "{CASE}: moving a window must never rewrite the raw-byte lane");`,
    ],
    inverse: [
      "The inverse swaps the windows back and restores both accessor references.",
      `assert_eq!(restored.document.buffer_views[0].byte_offset, 0, "{CASE}: the inverse must put the byteOffset-0 window back first");`,
    ],
    delta: [
      "The delta names the two window slots and nothing in `document/buffers`.",
      `assert_eq!(produced.touched_paths, vec!["document/bufferViews/0".to_string(), "document/bufferViews/1".to_string()], "{CASE}: move-buffer-view is single-lane, unlike move-buffer");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.id, "s.stdio.gltf.mutation.move-buffer-view.v1", "{CASE}: the committed diff must carry move-buffer-view's own canonical descriptor id");`],
  },
  {
    leaf: "move-camera",
    case: "swaps-the-perspective-and-orthographic-cameras",
    module: "move_camera",
    api: "collection",
    payloadType: "GltfMoveCameraPayload",
    diffType: "GltfMoveCameraDiff",
    doc: "`repair(Cameras, Move(0, 1))` rewrites `node.camera` on every node; both nodes here hold a binding,\nso both are swapped. The camera objects themselves are moved by value and never re-encoded into the\ndelta.",
    before: snap({ nodes: [{ camera: 0 }, { camera: 1 }], cameras: [PERSPECTIVE, ORTHOGRAPHIC] }),
    after: snap({ nodes: [{ camera: 1 }, { camera: 0 }], cameras: [ORTHOGRAPHIC, PERSPECTIVE] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-camera", swapPaths("cameras"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-camera` swaps the two cameras and rewrites both node bindings.",
      `assert!(matches!(snapshot.document.cameras[0].projection, crate::artifacts::gltf::schema::snapshot::GltfCameraProjection::Orthographic(_)), "{CASE}: the orthographic camera must end up first");`,
      `assert_eq!((snapshot.document.nodes[0].camera, snapshot.document.nodes[1].camera), (Some(1), Some(0)), "{CASE}: repair(Cameras, Move(0, 1)) must swap both node.camera bindings");`,
    ],
    inverse: [
      "The inverse swaps them back so the perspective camera leads again.",
      `assert!(matches!(restored.document.cameras[0].projection, crate::artifacts::gltf::schema::snapshot::GltfCameraProjection::Perspective(_)), "{CASE}: the inverse must put the perspective camera back first");`,
    ],
    delta: [
      "The delta is two indices — moving a WEAK entity still does not restate its value.",
      `assert_eq!(produced.touched_paths, vec!["document/cameras/0".to_string(), "document/cameras/1".to_string()], "{CASE}: move-camera declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.payload.index, 0, "{CASE}: the committed diff must echo the source index");`],
  },
  {
    leaf: "move-image",
    case: "swaps-the-albedo-and-normal-images",
    module: "move_image",
    api: "collection",
    payloadType: "GltfMoveImagePayload",
    diffType: "GltfMoveImageDiff",
    doc: "`repair(Images, Move(0, 1))` rewrites `texture.source` on every texture. Both textures here source\nan image, so both are swapped.",
    before: snap({ textures: [{ source: 0 }, { source: 1 }], images: [{ uri: "albedo.png" }, { uri: "normal.png" }] }),
    after: snap({ textures: [{ source: 1 }, { source: 0 }], images: [{ uri: "normal.png" }, { uri: "albedo.png" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-image", swapPaths("images"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-image` swaps the two images and rewrites both texture sources.",
      `assert_eq!(snapshot.document.images[0].uri.as_deref(), Some("normal.png"), "{CASE}: the normal map must end up first");`,
      `assert_eq!((snapshot.document.textures[0].source, snapshot.document.textures[1].source), (Some(1), Some(0)), "{CASE}: repair(Images, Move(0, 1)) must swap both texture.source references");`,
    ],
    inverse: [
      "The inverse swaps them back so the albedo image leads again.",
      `assert_eq!(restored.document.images[0].uri.as_deref(), Some("albedo.png"), "{CASE}: the inverse must put the albedo image back first");`,
    ],
    delta: [
      "The delta is two indices; the image URIs never appear in it.",
      `assert_eq!(produced.touched_paths, vec!["document/images/0".to_string(), "document/images/1".to_string()], "{CASE}: move-image declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.id, "s.stdio.gltf.mutation.move-image.v1", "{CASE}: the committed diff must carry move-image's own canonical descriptor id");`],
  },
  {
    leaf: "move-material",
    case: "swaps-the-glass-and-steel-materials",
    module: "move_material",
    api: "collection",
    payloadType: "GltfMoveMaterialPayload",
    diffType: "GltfMoveMaterialDiff",
    doc: "`repair(Materials, Move(0, 1))` rewrites `primitive.material` across every mesh primitive. Both\nprimitives here are bound, so both take the swap.",
    before: snap({ meshes: [{ primitives: [{ attributes: {}, material: 0 }, { attributes: {}, material: 1 }] }], materials: [{ name: "glass" }, { name: "steel" }] }),
    after: snap({ meshes: [{ primitives: [{ attributes: {}, material: 1 }, { attributes: {}, material: 0 }] }], materials: [{ name: "steel" }, { name: "glass" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-material", swapPaths("materials"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-material` swaps the two materials and rewrites both primitive bindings.",
      `assert_eq!(snapshot.document.materials[0].name.as_deref(), Some("steel"), "{CASE}: 'steel' must end up first");`,
      `assert_eq!((snapshot.document.meshes[0].primitives[0].material, snapshot.document.meshes[0].primitives[1].material), (Some(1), Some(0)), "{CASE}: repair(Materials, Move(0, 1)) must swap both primitive.material bindings");`,
    ],
    inverse: [
      "The inverse swaps them back so 'glass' leads again.",
      `assert_eq!(restored.document.materials[0].name.as_deref(), Some("glass"), "{CASE}: the inverse must put 'glass' back first");`,
    ],
    delta: [
      "The delta is two indices; neither material body appears in it.",
      `assert_eq!(produced.touched_paths, vec!["document/materials/0".to_string(), "document/materials/1".to_string()], "{CASE}: move-material declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.payload.position, 1, "{CASE}: the committed diff must echo the destination index");`],
  },
  {
    leaf: "move-mesh",
    case: "swaps-the-hull-and-deck-meshes",
    module: "move_mesh",
    api: "collection",
    payloadType: "GltfMoveMeshPayload",
    diffType: "GltfMoveMeshDiff",
    doc: "`repair(Meshes, Move(0, 1))` rewrites `node.mesh` on every node. Both nodes here hold a binding, so\nboth are swapped; nothing inside either mesh is touched.",
    before: snap({ nodes: [{ mesh: 0 }, { mesh: 1 }], meshes: [{ name: "hull" }, { name: "deck" }] }),
    after: snap({ nodes: [{ mesh: 1 }, { mesh: 0 }], meshes: [{ name: "deck" }, { name: "hull" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-mesh", swapPaths("meshes"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-mesh` swaps the two meshes and rewrites both node bindings.",
      `assert_eq!(snapshot.document.meshes[0].name.as_deref(), Some("deck"), "{CASE}: 'deck' must end up first");`,
      `assert_eq!((snapshot.document.nodes[0].mesh, snapshot.document.nodes[1].mesh), (Some(1), Some(0)), "{CASE}: repair(Meshes, Move(0, 1)) must swap both node.mesh bindings");`,
    ],
    inverse: [
      "The inverse swaps them back so 'hull' leads again.",
      `assert_eq!(restored.document.nodes[0].mesh, Some(0), "{CASE}: the inverse must restore the original node.mesh binding");`,
    ],
    delta: [
      "The delta is two indices; neither mesh body appears in it.",
      `assert_eq!(produced.touched_paths, vec!["document/meshes/0".to_string(), "document/meshes/1".to_string()], "{CASE}: move-mesh declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.id, "s.stdio.gltf.mutation.move-mesh.v1", "{CASE}: the committed diff must carry move-mesh's own canonical descriptor id");`],
  },
  {
    leaf: "move-node",
    case: "swaps-the-two-scene-root-nodes",
    module: "move_node",
    api: "collection",
    payloadType: "GltfMoveNodePayload",
    diffType: "GltfMoveNodeDiff",
    doc: "`repair(Nodes, Move(0, 1))` is the widest move cascade: `scene.nodes`, `node.children`,\n`skin.skeleton`/`skin.joints` and every animation channel target are remapped. Here it shows up as\nthe scene root list flipping from `[0, 1]` to `[1, 0]` — the ROOT LIST ORDER is preserved, only the\nnumbers change, which is what distinguishes this leaf from `move-scene-root-node`.",
    before: snap({ scenes: [{ nodes: [0, 1] }], nodes: [{ name: "a" }, { name: "b" }] }),
    after: snap({ scenes: [{ nodes: [1, 0] }], nodes: [{ name: "b" }, { name: "a" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-node", swapPaths("nodes"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-node` swaps the two nodes and renumbers — but does not reorder — the scene root list.",
      `assert_eq!(snapshot.document.nodes[0].name.as_deref(), Some("b"), "{CASE}: node 'b' must end up first");`,
      `assert_eq!(snapshot.document.scenes[0].nodes, vec![1usize, 0], "{CASE}: repair(Nodes, Move(0, 1)) renumbers the root list in place — the entries keep their positions");`,
    ],
    inverse: [
      "The inverse swaps the nodes back and restores the `[0, 1]` root list.",
      `assert_eq!(restored.document.scenes[0].nodes, vec![0usize, 1], "{CASE}: the inverse must restore the original root-list numbering");`,
    ],
    delta: [
      "The delta is two indices; the scene rewrite is a repair effect, not a second edit.",
      `assert_eq!(produced.touched_paths, vec!["document/nodes/0".to_string(), "document/nodes/1".to_string()], "{CASE}: move-node declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert!(matches!(decoded.operation, crate::artifacts::gltf::schema::mutations::move_node::diff::GltfMoveNodeOperation::Move { index: 0, position: 1 }), "{CASE}: the committed operation must be a bare move, carrying no node value");`],
  },
  {
    leaf: "move-sampler",
    case: "swaps-the-linear-and-clamped-samplers",
    module: "move_sampler",
    api: "collection",
    payloadType: "GltfMoveSamplerPayload",
    diffType: "GltfMoveSamplerDiff",
    doc: "`repair(Samplers, Move(0, 1))` rewrites `texture.sampler` on every texture. The committed snapshots\ncarry `magFilter` 9729 and `wrapS` 33071 precisely because both are NON-default and therefore survive\nthe wire round trip — a pair of REPEAT samplers would both serialize to `{}` and prove nothing.",
    before: snap({ textures: [{ sampler: 0 }, { sampler: 1 }], samplers: [{ magFilter: 9729 }, { wrapS: 33071 }] }),
    after: snap({ textures: [{ sampler: 1 }, { sampler: 0 }], samplers: [{ wrapS: 33071 }, { magFilter: 9729 }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-sampler", swapPaths("samplers"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-sampler` swaps the two samplers and rewrites both texture bindings.",
      `assert_eq!(snapshot.document.samplers[0].wrap_s, 33071, "{CASE}: the CLAMP_TO_EDGE sampler must end up first");`,
      `assert_eq!((snapshot.document.textures[0].sampler, snapshot.document.textures[1].sampler), (Some(1), Some(0)), "{CASE}: repair(Samplers, Move(0, 1)) must swap both texture.sampler bindings");`,
    ],
    inverse: [
      "The inverse swaps them back so the linear sampler leads again.",
      `assert_eq!(restored.document.samplers[0].mag_filter, Some(9729), "{CASE}: the inverse must put the linear sampler back first");`,
    ],
    delta: [
      "The delta is two indices; neither sampler body appears in it.",
      `assert_eq!(produced.touched_paths, vec!["document/samplers/0".to_string(), "document/samplers/1".to_string()], "{CASE}: move-sampler declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.payload.index, 0, "{CASE}: the committed diff must echo the source index");`],
  },
  {
    leaf: "move-scene",
    case: "demotes-the-first-scene-and-slides-the-default-pointer",
    module: "move_scene",
    api: "collection",
    payloadType: "GltfMoveScenePayload",
    diffType: "GltfMoveSceneDiff",
    doc: "`repair(Scenes, Move(0, 1))` touches exactly one thing: the OPTIONAL `document/scene` pointer. With\nthe default scene at 1 and a `0 → 1` move, the `from < to && value > from && value <= to` branch of\n`remap` fires and slides it down to 0. Nothing else in a glTF document indexes `document/scenes`.",
    before: snap({ scene: 1, scenes: [{ name: "a" }, { name: "b" }] }),
    after: snap({ scene: 0, scenes: [{ name: "b" }, { name: "a" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-scene", swapPaths("scenes"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-scene` rotates the scene list and slides the default-scene pointer with it.",
      `assert_eq!(snapshot.document.scene, Some(0), "{CASE}: the default scene must slide from 1 down to 0 when scene 0 moves past it");`,
      `assert_eq!(snapshot.document.scenes[0].name.as_deref(), Some("b"), "{CASE}: scene 'b' must end up first");`,
    ],
    inverse: [
      "The inverse rotates the pair back and returns the default pointer to 1.",
      `assert_eq!(restored.document.scene, Some(1), "{CASE}: the inverse must slide the default-scene pointer back to 1");`,
    ],
    delta: [
      "The delta is two scene indices — the default-pointer slide is a repair effect the delta does not restate.",
      `assert_eq!(produced.touched_paths, vec!["document/scenes/0".to_string(), "document/scenes/1".to_string()], "{CASE}: move-scene declares only the two scene slots, not document/scene");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.id, "s.stdio.gltf.mutation.move-scene.v1", "{CASE}: the committed diff must carry move-scene's own canonical descriptor id");`],
  },
  {
    leaf: "move-skin",
    case: "swaps-the-two-skins-and-rewrites-both-node-bindings",
    module: "move_skin",
    api: "collection",
    payloadType: "GltfMoveSkinPayload",
    diffType: "GltfMoveSkinDiff",
    doc: "`repair(Skins, Move(0, 1))` rewrites `node.skin` only. The skins' own `joints` hold NODE indices and\nare therefore left alone — the two joint lists stay `[0]` and `[1]` even though the skins swap places.",
    before: snap({ nodes: [{ skin: 0 }, { skin: 1 }], skins: [{ joints: [0] }, { joints: [1] }] }),
    after: snap({ nodes: [{ skin: 1 }, { skin: 0 }], skins: [{ joints: [1] }, { joints: [0] }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-skin", swapPaths("skins"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-skin` swaps the two skins, rewrites both node bindings and leaves every joint index alone.",
      `assert_eq!(snapshot.document.skins[0].joints, vec![1usize], "{CASE}: the joint lists travel WITH their skin and are never renumbered by a skins move");`,
      `assert_eq!((snapshot.document.nodes[0].skin, snapshot.document.nodes[1].skin), (Some(1), Some(0)), "{CASE}: repair(Skins, Move(0, 1)) must swap both node.skin bindings");`,
    ],
    inverse: [
      "The inverse swaps the skins back and restores both node bindings.",
      `assert_eq!(restored.document.skins[0].joints, vec![0usize], "{CASE}: the inverse must put the [0]-jointed skin back first");`,
    ],
    delta: [
      "The delta is two indices; neither skin body appears in it.",
      `assert_eq!(produced.touched_paths, vec!["document/skins/0".to_string(), "document/skins/1".to_string()], "{CASE}: move-skin declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.payload.position, 1, "{CASE}: the committed diff must echo the destination index");`],
  },
  {
    leaf: "move-texture",
    case: "swaps-the-albedo-and-normal-textures",
    module: "move_texture",
    api: "collection",
    payloadType: "GltfMoveTexturePayload",
    diffType: "GltfMoveTextureDiff",
    doc: "`repair(Textures, Move(0, 1))` walks every `textureInfo` slot on every material. Both materials here\nbind a `baseColorTexture`, so both indices are swapped; the drop-to-`None` branch of that arm can only\nfire on a deletion, never on a move.",
    before: snap({ materials: [{ pbrMetallicRoughness: { baseColorTexture: { index: 0 } } }, { pbrMetallicRoughness: { baseColorTexture: { index: 1 } } }], textures: [{ name: "albedo" }, { name: "normal" }] }),
    after: snap({ materials: [{ pbrMetallicRoughness: { baseColorTexture: { index: 1 } } }, { pbrMetallicRoughness: { baseColorTexture: { index: 0 } } }], textures: [{ name: "normal" }, { name: "albedo" }] }),
    mutation: MOVE_0_TO_1,
    diff: opDiff("move-texture", swapPaths("textures"), MOVE_0_TO_1, SWAP),
    outcome: { status: "applied" },
    apply: [
      "`move-texture` swaps the two textures and rewrites both baseColorTexture bindings.",
      `assert_eq!(snapshot.document.textures[0].name.as_deref(), Some("normal"), "{CASE}: the normal texture must end up first");`,
      `assert_eq!(snapshot.document.materials[0].pbr_metallic_roughness.as_ref().and_then(|pbr| pbr.base_color_texture.as_ref()).map(|info| info.index), Some(1), "{CASE}: repair(Textures, Move(0, 1)) must renumber the first material's baseColorTexture, never clear it");`,
    ],
    inverse: [
      "The inverse swaps them back so the albedo texture leads again.",
      `assert_eq!(restored.document.textures[0].name.as_deref(), Some("albedo"), "{CASE}: the inverse must put the albedo texture back first");`,
    ],
    delta: [
      "The delta is two indices; the material rewrites are repair effects.",
      `assert_eq!(produced.touched_paths, vec!["document/textures/0".to_string(), "document/textures/1".to_string()], "{CASE}: move-texture declares its source AND destination slot");`,
    ],
    canonicalDiff: [`assert_eq!(decoded.id, "s.stdio.gltf.mutation.move-texture.v1", "{CASE}: the committed diff must carry move-texture's own canonical descriptor id");`],
  },
];
