[package]
name = "semio-s-kernel-flow-extension-logic"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
name = "flow_extension_logic"
crate-type = ["rlib", "cdylib"]
path = "../../../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🌊️flow/⚡️implementations/🦀️rust/🧩️extensions/🧠️logic/📦️lib.rs"

[features]
default = ["standalone-wasm"]
standalone-wasm = ["dep:wasm-bindgen"]

[dependencies]
flow_extension_sdk = { path = "../../../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🌊️flow/⚡️implementations/🦀️rust/🧩️extensions/🕸️wasm", package = "semio-s-kernel-flow-extension-wasm" }
neural_engine = { path = "../../../../../🧠️neural/⚙️engine/📦️packages/🦀️rust", package = "semio-framework-os-kernel-neural-engine" }
serde_json = "1.0.140"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen = { version = "0.2.106", optional = true }
