[package]
name = "fsm"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["rlib", "cdylib"]
path = "../../../../../../../✏️s/🔌️plugin/🖍️draw/🔨️module/🔄️fsm/⚡️implementation/🦀️rust/📦️lib.rs"

[features]
default = ["macros", "serde"]
macros = ["dep:fsm_macros"]
serde = ["dep:serde", "dep:serde_json"]
testing = []

[dependencies]
fsm_macros = { path = "../../✨️macros/⚡️implementation/🦀️rust", optional = true, package = "fsm_macros" }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.140", optional = true }
thiserror = "2.0.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.106"
js-sys = "0.3.83"

[dev-dependencies]
