[package]
name = "draw-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:draw"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "draw"
ports = { react = 6064, wgpu = 6164 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
draw = { path = "../../rs", package = "draw" }
fsm = { path = "../../fsm/rs", package = "fsm" }
semio-framework-os = { path = "../../../../../framework/product/os/core/rs" }
semio-framework-plugin = { path = "../../../../../framework/plugin/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22"

