syntax = "proto3";
package semio.s.fem.fem3d.diff;

// 🧬️ Fem3d diff schema
message Fem3dDiff {
  // @state artifact
  optional Fem3dNodesDelta nodes = 1;
  // @state artifact
  optional Fem3dElementsDelta elements = 2;
  // @state artifact
  optional Fem3dMaterialsDelta materials = 3;
  // @state artifact
  optional Fem3dSectionsDelta sections = 4;
  // @state artifact
  optional Fem3dSolidsDelta solids = 5;
  // @state artifact
  optional Fem3dSupportsDelta supports = 6;
  // @state artifact
  optional Fem3dLoadCasesDelta load_cases = 7;
  // @state artifact
  optional Fem3dCombinationsDelta combinations = 8;
  // @state artifact
  optional Fem3dAnalysisPatch analysis = 9;
}

message Fem3dNodeRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dNodeInsertion {
  uint64 index = 1;
  FemNode row = 2;
}

message Fem3dNodeRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dNodesModification {
  string id = 1;
  FemNode patch = 2;
}

message Fem3dNodesDelta {
  repeated Fem3dNodeRemoval removed = 1;
  repeated Fem3dNodeInsertion inserted = 2;
  repeated Fem3dNodeRelocation moved = 3;
  repeated Fem3dNodesModification modified = 4;
}

message Fem3dElementRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dElementInsertion {
  uint64 index = 1;
  FemElement row = 2;
}

message Fem3dElementRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dElementsModification {
  string id = 1;
  FemElement patch = 2;
}

message Fem3dElementsDelta {
  repeated Fem3dElementRemoval removed = 1;
  repeated Fem3dElementInsertion inserted = 2;
  repeated Fem3dElementRelocation moved = 3;
  repeated Fem3dElementsModification modified = 4;
}

message Fem3dMaterialRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dMaterialInsertion {
  uint64 index = 1;
  FemMaterial row = 2;
}

message Fem3dMaterialRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dMaterialsModification {
  string id = 1;
  FemMaterial patch = 2;
}

message Fem3dMaterialsDelta {
  repeated Fem3dMaterialRemoval removed = 1;
  repeated Fem3dMaterialInsertion inserted = 2;
  repeated Fem3dMaterialRelocation moved = 3;
  repeated Fem3dMaterialsModification modified = 4;
}

message Fem3dSectionRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dSectionInsertion {
  uint64 index = 1;
  FemSection row = 2;
}

message Fem3dSectionRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dSectionsModification {
  string id = 1;
  FemSection patch = 2;
}

message Fem3dSectionsDelta {
  repeated Fem3dSectionRemoval removed = 1;
  repeated Fem3dSectionInsertion inserted = 2;
  repeated Fem3dSectionRelocation moved = 3;
  repeated Fem3dSectionsModification modified = 4;
}

message Fem3dSolidRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dSolidInsertion {
  uint64 index = 1;
  FemSolid row = 2;
}

message Fem3dSolidRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dSolidsModification {
  string id = 1;
  FemSolid patch = 2;
}

message Fem3dSolidsDelta {
  repeated Fem3dSolidRemoval removed = 1;
  repeated Fem3dSolidInsertion inserted = 2;
  repeated Fem3dSolidRelocation moved = 3;
  repeated Fem3dSolidsModification modified = 4;
}

message Fem3dSupportRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dSupportInsertion {
  uint64 index = 1;
  FemSupport row = 2;
}

message Fem3dSupportRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dSupportsModification {
  string id = 1;
  FemSupport patch = 2;
}

message Fem3dSupportsDelta {
  repeated Fem3dSupportRemoval removed = 1;
  repeated Fem3dSupportInsertion inserted = 2;
  repeated Fem3dSupportRelocation moved = 3;
  repeated Fem3dSupportsModification modified = 4;
}

message Fem3dLoadCaseRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dLoadCaseInsertion {
  uint64 index = 1;
  FemLoadCase row = 2;
}

message Fem3dLoadCaseRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dLoadCasesModification {
  string id = 1;
  Fem3dLoadCasePatch patch = 2;
}

message Fem3dLoadCasesDelta {
  repeated Fem3dLoadCaseRemoval removed = 1;
  repeated Fem3dLoadCaseInsertion inserted = 2;
  repeated Fem3dLoadCaseRelocation moved = 3;
  repeated Fem3dLoadCasesModification modified = 4;
}

message Fem3dLoadCasePatch {
  optional string name = 1;
  optional bool self_weight = 2;
  optional Fem3dLoadsDelta loads = 3;
}

message Fem3dLoadRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dLoadInsertion {
  uint64 index = 1;
  FemLoad row = 2;
}

message Fem3dLoadRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dLoadsModification {
  string id = 1;
  FemLoad patch = 2;
}

message Fem3dLoadsDelta {
  repeated Fem3dLoadRemoval removed = 1;
  repeated Fem3dLoadInsertion inserted = 2;
  repeated Fem3dLoadRelocation moved = 3;
  repeated Fem3dLoadsModification modified = 4;
}

message Fem3dCombinationRemoval {
  string id = 1;
  uint64 index = 2;
}

message Fem3dCombinationInsertion {
  uint64 index = 1;
  FemCombination row = 2;
}

message Fem3dCombinationRelocation {
  string id = 1;
  uint64 from = 2;
  uint64 to = 3;
}

message Fem3dCombinationsModification {
  string id = 1;
  FemCombination patch = 2;
}

message Fem3dCombinationsDelta {
  repeated Fem3dCombinationRemoval removed = 1;
  repeated Fem3dCombinationInsertion inserted = 2;
  repeated Fem3dCombinationRelocation moved = 3;
  repeated Fem3dCombinationsModification modified = 4;
}

message Fem3dAnalysisPatch {
  optional uint32 modal_count = 1;
  optional uint32 buckling_count = 2;
  optional double deformation_scale = 3;
}
