/** 📦️ Explicit persisted OPC package entities shared by Office owners. */
import type {OpcPackage,OpcRelationship} from "../🟦️.ts";
import {artifactSqliteCheckpoint,artifactSqliteInteger,artifactSqliteText,artifactSqliteTextBytes,artifactSqliteValueBudget,artifactSqliteValueByteLengthControlled,artifactSqliteOrderedRowsControlled,type ArtifactSqliteOptions} from "../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import type{SqliteDatabase,SqliteRow,SqliteValue}from"../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
/** 🗂️ Individually declared OPC table vocabulary. */
export interface OpcSqliteTables{readonly package:string;readonly part:string;readonly defaultType:string;readonly overrideType:string;readonly relationshipOwner:string;readonly relationship:string}
function rowsLimit(rows:number,options:ArtifactSqliteOptions):void{if(!Number.isSafeInteger(rows)||rows>(options.maxRows??1_000_000))throw new Error("OPC row limit");}
/** 📏️ Counts the actual package entities and scalar fields before any byte buffer copy. */
export async function measureOpcPackage(package_:OpcPackage,options:ArtifactSqliteOptions={}):Promise<{rows:number;bytes:number}>{
 let rows=1,bytes=8+artifactSqliteTextBytes(package_.comment);const check=()=>{rowsLimit(rows,options);artifactSqliteValueBudget(bytes,options);};check();
 for(const part of package_.parts){rows++;bytes+=24+artifactSqliteTextBytes(part.path)+artifactSqliteTextBytes(part.contentType)+part.bytes.length;check();for(let ordinal=0;ordinal<part.bytes.length;ordinal++){if(ordinal%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",ordinal,part.bytes.length,ordinal%65536===0);const byte=part.bytes[ordinal]!;if(!Number.isInteger(byte)||byte<0||byte>255)throw new Error("OPC intrinsic octet is invalid");}if(rows%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",rows,0);}
 for(const pairs of [package_.contentTypes.defaults,package_.contentTypes.overrides])for(const pair of pairs){rows++;bytes+=24+artifactSqliteTextBytes(pair[0])+artifactSqliteTextBytes(pair[1]);check();if(rows%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",rows,0);}
 for(const owner in package_.relationships){if(!Object.hasOwn(package_.relationships,owner))continue;rows++;bytes+=16+artifactSqliteTextBytes(owner);check();if(rows%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",rows,0);for(const relationship of package_.relationships[owner]!){if(relationship.targetMode!=="internal"&&relationship.targetMode!=="external")throw new Error("OPC relationship mode is invalid");rows++;bytes+=24+artifactSqliteTextBytes(relationship.id)+artifactSqliteTextBytes(relationship.relType)+artifactSqliteTextBytes(relationship.target)+8;check();if(rows%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",rows,0);}}
 await artifactSqliteCheckpoint(options,"projectSnapshot",rows,rows);return{rows,bytes};
}
async function intrinsic(bytes:readonly number[],options:ArtifactSqliteOptions):Promise<Uint8Array>{if(bytes.length>65536)await artifactSqliteCheckpoint(options,"projectSnapshot",0,bytes.length);const output=new Uint8Array(bytes.length);for(let start=0;start<bytes.length;start+=65536){const end=Math.min(start+65536,bytes.length);for(let index=start;index<end;index++)output[index]=bytes[index]!;if(bytes.length>65536)await artifactSqliteCheckpoint(options,"projectSnapshot",end,bytes.length);}return output;}
function table(database:SqliteDatabase,name:string):readonly SqliteRow[]{const found=database.tables.find(table=>table.name===name);if(!found)throw new Error("OPC declared table missing");return found.rows;}
/** 🏗️ Appends only the six explicit typed OPC relations, reusing the existing XML rows. */
export async function projectOpcPackage(package_:OpcPackage,database:SqliteDatabase,tables:OpcSqliteTables,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const owned=new Map<string,SqliteRow[]>();for(const name of [tables.package,tables.part,tables.defaultType,tables.overrideType,tables.relationshipOwner,tables.relationship]){if(table(database,name).length)throw new Error("OPC projection tables must be empty");owned.set(name,[]);}
 const forecast=await measureOpcPackage(package_,options);let count=forecast.rows,bytes=forecast.bytes;for(const existing of database.tables){for(const row of existing.rows){count++;rowsLimit(count,options);for(const value of row.values){bytes+=await artifactSqliteValueByteLengthControlled(value,options,"projectSnapshot",bytes);artifactSqliteValueBudget(bytes,options);}}}rowsLimit(count,options);artifactSqliteValueBudget(bytes,options);
 let completed=0;const push=async(name:string,values:SqliteValue[]):Promise<bigint>=>{for(const value of values)await artifactSqliteValueByteLengthControlled(value,options,"projectSnapshot");const rows=owned.get(name)!;const rowid=BigInt(rows.length+1);rows.push({rowid,values:[rowid,...values]});if(++completed%256===0)await artifactSqliteCheckpoint(options,"projectSnapshot",completed,forecast.rows);return rowid;};
 const id=await push(tables.package,[package_.comment]);for(const[ordinal,part]of package_.parts.entries())await push(tables.part,[id,BigInt(ordinal),part.path,part.contentType,await intrinsic(part.bytes,options)]);
 for(const[name,pairs]of [[tables.defaultType,package_.contentTypes.defaults],[tables.overrideType,package_.contentTypes.overrides]]as const){for(const[ordinal,pair]of pairs.entries())await push(name,[id,BigInt(ordinal),pair[0],pair[1]]);}
 for(const owner in package_.relationships){if(!Object.hasOwn(package_.relationships,owner))continue;const parent=await push(tables.relationshipOwner,[id,owner]);for(const[ordinal,relationship]of package_.relationships[owner]!.entries())await push(tables.relationship,[parent,BigInt(ordinal),relationship.id,relationship.relType,relationship.target,relationship.targetMode]);}
 await artifactSqliteCheckpoint(options,"projectSnapshot",forecast.rows,forecast.rows);return{tables:database.tables.map(table=>owned.has(table.name)?{name:table.name,sql:table.sql,rows:owned.get(table.name)!}:table)};
}
async function entities(database:SqliteDatabase,name:string,columns:number,options:ArtifactSqliteOptions):Promise<readonly SqliteRow[]>{const rows=table(database,name),keys=new Set<bigint>();for(const[position,row]of rows.entries()){if(position%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",position,rows.length);if(row.values.length!==columns||row.rowid<=0n||artifactSqliteInteger(row,0)!==row.rowid||keys.has(row.rowid))throw new Error("OPC entity identity or columns are invalid");keys.add(row.rowid);}return rows;}
async function octets(value:SqliteValue|undefined,options:ArtifactSqliteOptions):Promise<number[]>{if(!(value instanceof Uint8Array))throw new Error("OPC part requires intrinsic bytes");if(value.length>65536)await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,value.length);const result:number[]=new Array(value.length);for(let start=0;start<value.length;start+=65536){const end=Math.min(start+65536,value.length);for(let index=start;index<end;index++)result[index]=value[index]!;if(value.length>65536)await artifactSqliteCheckpoint(options,"reconstructSnapshot",end,value.length);}return result;}
/** 🧱️ Reads literal package identities and dense ordered relationships without archive normalization. */
export async function reconstructOpcPackage(database:SqliteDatabase,tables:OpcSqliteTables,options:ArtifactSqliteOptions={}):Promise<OpcPackage>{
 const packages=await entities(database,tables.package,2,options);if(packages.length!==1||packages[0]!.rowid!==1n)throw new Error("OPC graph requires one package");const parent=1n;const result:OpcPackage={comment:artifactSqliteText(packages[0]!,1),parts:[],contentTypes:{defaults:[],overrides:[]},relationships:Object.create(null)};
 const partRows=await entities(database,tables.part,6,options);for(const row of partRows)if(artifactSqliteInteger(row,1)!==parent)throw new Error("OPC part package dangling");for(const row of await artifactSqliteOrderedRowsControlled(partRows,2,options))result.parts.push({path:artifactSqliteText(row,3),contentType:artifactSqliteText(row,4),bytes:await octets(row.values[5],options)});
 for(const[name,pairs]of [[tables.defaultType,result.contentTypes.defaults],[tables.overrideType,result.contentTypes.overrides]]as const){const rows=await entities(database,name,5,options);for(const row of rows)if(artifactSqliteInteger(row,1)!==parent)throw new Error("OPC content type package dangling");for(const row of await artifactSqliteOrderedRowsControlled(rows,2,options))pairs.push([artifactSqliteText(row,3),artifactSqliteText(row,4)]);}
 const owners=new Map<bigint,string>();for(const row of await entities(database,tables.relationshipOwner,3,options)){const name=artifactSqliteText(row,2);if(artifactSqliteInteger(row,1)!==parent||Object.hasOwn(result.relationships,name))throw new Error("OPC owner dictionary duplicate or dangling");owners.set(row.rowid,name);result.relationships[name]=[];}
 const groups=new Map<bigint,SqliteRow[]>();for(const row of await entities(database,tables.relationship,7,options)){const owner=artifactSqliteInteger(row,1);if(!owners.has(owner))throw new Error("OPC relationship owner dangling");const rows=groups.get(owner)??[];rows.push(row);groups.set(owner,rows);}
 for(const[owner,rows]of groups){const target=result.relationships[owners.get(owner)!]!;for(const row of await artifactSqliteOrderedRowsControlled(rows,2,options)){const mode=artifactSqliteText(row,6);if(mode!=="internal"&&mode!=="external")throw new Error("OPC target mode invalid");const relationship:OpcRelationship={id:artifactSqliteText(row,3),relType:artifactSqliteText(row,4),target:artifactSqliteText(row,5),targetMode:mode};target.push(relationship);}}
 return result;
}
