/// <reference path="./🗄️.d.ts" />
import sql from "./🗄️.sql" with {type:"text"};
import {parseBinary32,binary32Value,type Binary32} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
/** 🎧️ Individually authored WAV sample domains and RIFF chunk relationships. */
import type {WavSnapshot,WavData,WavChunkRef,RiffChunk} from "../🟦️.ts";
import {ArtifactSqliteProjection,artifactSqliteCheckpoint,artifactSqliteTables,artifactSqliteInteger,artifactSqliteText,artifactSqliteDocument,artifactSqliteDocumentReference,artifactSqliteOrderedRowsControlled,type ArtifactSqliteOptions} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {sqliteOperation,type SqliteDatabase,type SqliteRow} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
/** 🏛️ The individually handwritten canonical WAV relational schema. */
export const WAV_SQLITE_SCHEMA:string=sql;

const integer=(value:number,maximum=4294967295,minimum=0):bigint=>{if(!Number.isSafeInteger(value)||value<minimum||value>maximum)throw new Error("WAV integer exceeds its native field width");return BigInt(value);};
const field=(row:SqliteRow,column:number,maximum=4294967295,minimum=0):number=>{const value=artifactSqliteInteger(row,column);if(value<BigInt(minimum)||value>BigInt(maximum))throw new Error("WAV integer exceeds its native field width");return Number(value);};
const numericClass=(value:number):string=>Number.isNaN(value)?"nan":value===Infinity?"positive_infinity":value===-Infinity?"negative_infinity":Object.is(value,-0)?"negative_zero":"finite";
const checkpoint=async(options:ArtifactSqliteOptions,position:number,total=0):Promise<void>=>{if(position%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",position,total);};
async function entities(rows:readonly SqliteRow[],options:ArtifactSqliteOptions):Promise<Set<bigint>>{const ids=new Set<bigint>();for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);const row=rows[position]!;if(row.rowid<=0n||artifactSqliteInteger(row,0)!==row.rowid||ids.has(row.rowid))throw new Error("WAV entities require unique positive aliased identifiers");ids.add(row.rowid);}return ids;}
async function ordered(rows:readonly SqliteRow[],options:ArtifactSqliteOptions):Promise<SqliteRow[]>{await entities(rows,options);for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);artifactSqliteDocumentReference(rows[position]!,1);}return artifactSqliteOrderedRowsControlled(rows,2,options);}
async function groups(rows:readonly SqliteRow[],parents:ReadonlySet<bigint>,options:ArtifactSqliteOptions):Promise<Map<bigint,SqliteRow[]>>{await entities(rows,options);const groups=new Map<bigint,SqliteRow[]>();for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);const row=rows[position]!,owner=artifactSqliteInteger(row,1);if(!parents.has(owner))throw new Error("WAV octet has an unknown chunk owner");const children=groups.get(owner);if(children)children.push(row);else groups.set(owner,[row]);}for(const[owner,children]of groups){await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,children.length);groups.set(owner,await artifactSqliteOrderedRowsControlled(children,2,options));}return groups;}
async function writeOctets(out:ArtifactSqliteProjection,table:string,owner:bigint,bytes:readonly number[]):Promise<void>{for(let ordinal=0;ordinal<bytes.length;ordinal++)await out.insert(table,[owner,BigInt(ordinal),integer(bytes[ordinal]!,255)]);}
async function readOctets(rows:readonly SqliteRow[],options:ArtifactSqliteOptions):Promise<number[]>{const values:number[]=[];for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);values.push(field(rows[position]!,3,255));}return values;}
function readFloat(row:SqliteRow):Binary32{const word=parseBinary32({bits:field(row,3)});const sample=binary32Value(word);if(artifactSqliteText(row,4)!==numericClass(sample))throw new Error("WAV sample numeric class disagrees with its IEEE754 bits");if(Number.isFinite(sample)){const query=row.values[5];const exact=typeof query==="number"?query===sample:typeof query==="bigint"&&Number.isInteger(sample)&&BigInt(sample)===query;if(!exact)throw new Error("WAV query sample disagrees with its IEEE754 bits");}else if(row.values[5]!==null)throw new Error("WAV non-finite sample requires NULL query value");return word;}

/** 📤️ Exports full owned WAV state without first encoding the RIFF wire. */
export async function wavSnapshotToSqliteDatabase(snapshot:WavSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 options=sqliteOperation(options);
 const out=await ArtifactSqliteProjection.create(WAV_SQLITE_SCHEMA,options);await out.insert("wav_document",[snapshot.schema]);await out.insert("wav_format",[integer(snapshot.fmt.audioFormat,65535),integer(snapshot.fmt.channels,65535),integer(snapshot.fmt.sampleRate),integer(snapshot.fmt.byteRate),integer(snapshot.fmt.blockAlign,65535),integer(snapshot.fmt.bitsPerSample,65535),integer(snapshot.fmtPadByte,255)]);
 if(snapshot.fmt.ext!==undefined){await out.insert("wav_format_extension",[],1n);await writeOctets(out,"wav_format_extension_byte",1n,snapshot.fmt.ext);}
 await out.insert("wav_data",[snapshot.data.kind,integer(snapshot.dataPadByte,255)]);
 switch(snapshot.data.kind){
  case "pcm16":for(let ordinal=0;ordinal<snapshot.data.value.length;ordinal++)await out.insert("wav_pcm16_sample",[1n,BigInt(ordinal),integer(snapshot.data.value[ordinal]!,32767,-32768)]);break;
  case "pcm8":await writeOctets(out,"wav_pcm8_sample",1n,snapshot.data.value);break;
  case "raw":await writeOctets(out,"wav_raw_data_byte",1n,snapshot.data.value);break;
  case "float32":{for(let ordinal=0;ordinal<snapshot.data.value.length;ordinal++){const word=parseBinary32(snapshot.data.value[ordinal]!);const sample=binary32Value(word);await out.insert("wav_float32_sample",[1n,BigInt(ordinal),BigInt(word.bits),numericClass(sample),Number.isFinite(sample)?sample:null]);}break;}
  default:throw new Error("WAV data has an unknown sample kind");
 }
 const chunks:bigint[]=[];for(let ordinal=0;ordinal<snapshot.otherChunks.length;ordinal++){const chunk=snapshot.otherChunks[ordinal]!;const id=await out.insert("wav_other_chunk",[1n,BigInt(ordinal),chunk.fourcc,integer(chunk.padByte,255)]);chunks.push(id);await writeOctets(out,"wav_other_chunk_byte",id,chunk.data);}
 for(let ordinal=0;ordinal<snapshot.chunkOrder.length;ordinal++){const reference=snapshot.chunkOrder[ordinal]!;let format:bigint|null=null,data:bigint|null=null,other:bigint|null=null,auxiliaryIndex:string|null=null;switch(reference.kind){case"format":format=1n;break;case"samples":data=1n;break;case"other":{const index=reference.value;if(typeof index!=="bigint"||index<0n||index>18446744073709551615n)throw new Error("WAV chunk reference requires an unsigned64 word");other=index<BigInt(chunks.length)?chunks[Number(index)]!:null;auxiliaryIndex=index.toString();break;}default:throw new Error("WAV chunk reference has an unknown kind");}await out.insert("wav_chunk_order",[1n,BigInt(ordinal),reference.kind,format,data,other,auxiliaryIndex]);}return out.finish();
}

/** 📥️ Restores typed samples and references with complete ownership and ordinal validation. */
export async function wavSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<WavSnapshot>{
 options=sqliteOperation(options);
 await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,0);const[documents,formats,extensions,extensionBytes,dataRows,pcm16,pcm8,float32,raw,chunks,chunkBytes,orderRows]=await artifactSqliteTables(database,WAV_SQLITE_SCHEMA,options);const document=artifactSqliteDocument(documents!),fmt=artifactSqliteDocument(formats!),data=artifactSqliteDocument(dataRows!);if(extensions!.length>1||(extensions!.length===1&&(extensions![0]!.rowid!==1n||artifactSqliteInteger(extensions![0]!,0)!==1n)))throw new Error("WAV format has an unknown extension owner");const extRows=await ordered(extensionBytes!,options);if(extensions!.length===0&&extRows.length!==0)throw new Error("WAV extension octets lack their optional extension");const ext=extensions!.length===0?undefined:await readOctets(extRows,options);
 const kind=artifactSqliteText(data,1);for(const[rows,selected]of [[pcm16!,"pcm16"],[pcm8!,"pcm8"],[float32!,"float32"],[raw!,"raw"]]as const){if(selected!==kind&&rows.length!==0)throw new Error("WAV data contains rows of another sample kind");}
 let samples:WavData;switch(kind){case"pcm16":{const rows=await ordered(pcm16!,options),value:number[]=[];for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);value.push(field(rows[position]!,3,32767,-32768));}samples={kind,value};break;}case"pcm8":samples={kind,value:await readOctets(await ordered(pcm8!,options),options)};break;case"raw":samples={kind,value:await readOctets(await ordered(raw!,options),options)};break;case"float32":{const rows=await ordered(float32!,options),value:Binary32[]=[];for(let position=0;position<rows.length;position++){await checkpoint(options,position,rows.length);value.push(readFloat(rows[position]!));}samples={kind,value};break;}default:throw new Error("WAV data has an unknown sample kind");}
 const chunkRows=await ordered(chunks!,options),chunkIds=new Set<bigint>();for(let position=0;position<chunkRows.length;position++){await checkpoint(options,position,chunkRows.length);chunkIds.add(chunkRows[position]!.rowid);}const bytes=await groups(chunkBytes!,chunkIds,options);const otherChunks:RiffChunk[]=[],identities:bigint[]=[];for(const row of chunkRows){await checkpoint(options,otherChunks.length,chunkRows.length);identities.push(row.rowid);const pad=field(row,4,255);otherChunks.push({fourcc:artifactSqliteText(row,3),data:await readOctets(bytes.get(row.rowid)??[],options),padByte:pad});}
 const chunkOrder:WavChunkRef[]=[];for(const row of await ordered(orderRows!,options)){await checkpoint(options,chunkOrder.length,orderRows!.length);const kind=artifactSqliteText(row,3);let reference:WavChunkRef;if(kind==="format"&&row.values[4]===1n&&row.values[5]===null&&row.values[6]===null&&row.values[7]===null)reference={kind};else if(kind==="samples"&&row.values[4]===null&&row.values[5]===1n&&row.values[6]===null&&row.values[7]===null)reference={kind};else if(kind==="other"&&row.values[4]===null&&row.values[5]===null){const text=artifactSqliteText(row,7);if(!/^(?:0|[1-9][0-9]{0,19})$/u.test(text))throw new Error("WAV auxiliary chunk index requires a canonical unsigned64 decimal");const value=BigInt(text);if(value>18446744073709551615n)throw new Error("WAV auxiliary chunk index exceeds unsigned64");const expected=value<BigInt(identities.length)?identities[Number(value)]!:null;if(row.values[6]!==expected)throw new Error("WAV auxiliary index disagrees with its resolved chunk relationship");reference={kind,value};}else throw new Error("WAV chunk reference does not select exactly one declared chunk");chunkOrder.push(reference);}
 const fmtPadByte=field(fmt,7,255),dataPadByte=field(data,2,255);const result:WavSnapshot={schema:artifactSqliteText(document,1),fmt:{audioFormat:field(fmt,1,65535),channels:field(fmt,2,65535),sampleRate:field(fmt,3),byteRate:field(fmt,4),blockAlign:field(fmt,5,65535),bitsPerSample:field(fmt,6,65535),...(ext===undefined?{}:{ext})},data:samples,fmtPadByte,dataPadByte,otherChunks,chunkOrder};await artifactSqliteCheckpoint(options,"reconstructSnapshot",1,1);return result;
}
