[package]
name = "trinity_jack_shell"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[[bin]]
name = "trinity_jack_shell"
path = "bin.rs"


[lints]
workspace = true
[dependencies]
trinity_jack = { path = "../../rs", package = "trinity_jack" }
trinity_ram = { path = "../../../ram/rs", package = "trinity_ram" }
vcs = { path = "../../../../../../../framework/product/os/module/vcs/rs", package = "semio-framework-os-kernel-vcs" }
store = { path = "../../../../../../../framework/product/os/module/store/rs", package = "semio-framework-os-kernel-store" }
thiserror = "2.0.12"
