/** 🌀️ Explicit typed support for the two actual procedural owned snapshot pairs. */
import{ArtifactSqliteProjection,type ArtifactSqliteOptions}from"../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import{encodeIeee754Cells,type Binary64}from"../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import type{SqliteDatabase,SqliteValue}from"../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import type{ProceduralSnapshot,NeuralDictionary,GenerationValue,FlowTree,FlowUi}from"./🧬️model/🟦️.ts";
export type{ProceduralSnapshot,NeuralDictionary,NeuralValue,GenerationValue,CameraJson,WidgetLayout,SynapseSpec,FlowTree,FlowNeuron,NodeChrome,FlowNodeGui,FlowChannelRef,FlowPreviewGui,FlowUi,Widget,FlowHostSnapshot,FormGeneration,GenerationPlayState}from"./🧬️model/🟦️.ts";
export{reconstructProceduralSnapshot}from"./📥️reconstruction/🟦️.ts";
function columns(t:string):readonly{index:number;width:64}[]{switch(t){case"generation_host":return[{index:2,width:64},{index:3,width:64},{index:4,width:64}];case"generation_slider_widget":case"generation_gui_slider":return[{index:2,width:64},{index:3,width:64},{index:4,width:64},{index:5,width:64}];case"generation_host_layout":case"generation_gui_node":return[{index:4,width:64},{index:5,width:64}];case"generation_neural_value":return[{index:4,width:64}];case"generation_gui":return[{index:1,width:64},{index:2,width:64},{index:3,width:64}];case"generation_gui_preview":return[{index:8,width:64},{index:9,width:64}];case"generation_value":return[{index:5,width:64}];default:return[];}}
function compare(a:string,b:string):number{for(let i=0,j=0;i<a.length&&j<b.length;){const x=a.codePointAt(i)!,y=b.codePointAt(j)!;if(x!==y)return x-y;i+=x>65535?2:1;j+=y>65535?2:1;}return a.length-b.length;}
function boolean(v:boolean):bigint{if(typeof v!=="boolean")throw Error("procedural boolean differs");return v?1n:0n;}
function integer(v:bigint,unsigned=false):bigint{if(typeof v!=="bigint"||v<(unsigned?0n:-9223372036854775808n)||v>(unsigned?18446744073709551615n:9223372036854775807n))throw Error("procedural native integer width differs");return v;}
type NativeCell=SqliteValue|Binary64;
async function ieee(p:ArtifactSqliteProjection,t:string,cells:readonly NativeCell[],id?:bigint):Promise<bigint>{return p.insert(t,encodeIeee754Cells([0n,...cells],columns(t)).slice(1),id);}
async function keys<T>(p:ArtifactSqliteProjection,v:Readonly<Record<string,T>>):Promise<string[]>{let count=0;for(const key in v){if(!Object.hasOwn(v,key))continue;if(++count%256===0)await p.checkpoint();p.checkRowsAdditional(count);}await p.checkpoint();const keys=Object.keys(v).sort(compare);await p.checkpoint();return keys;}
async function dictionary(p:ArtifactSqliteProjection,root:NeuralDictionary):Promise<bigint>{const id=await p.insert("generation_neural_dictionary",[]),pending:[bigint,NeuralDictionary][]=[[id,root]];while(pending.length){const[owner,d]=pending.pop()!;await p.checkpoint();const names=await keys(p,d);for(let i=0;i<names.length;i++){const key=names[i]!,v=d[key]!;let kind:string=v.kind,b:SqliteValue=null,n:SqliteValue=null,f:NativeCell=null,s:SqliteValue=null,child:SqliteValue=null;switch(v.kind){case"null":break;case"boolean":b=boolean(v.value);break;case"integer":n=integer(v.value);break;case"decimal":f=v.value;break;case"string":s=v.value;break;case"dictionary":child=await p.insert("generation_neural_dictionary",[]);pending.push([child,v.value]);break;default:throw Error("procedural neural value kind differs");}const value=await ieee(p,"generation_neural_value",[kind,b,n,f,s,child]);await p.insert("generation_neural_entry",[owner,BigInt(i),key,value]);}}return id;}
async function scalar(p:ArtifactSqliteProjection,v:GenerationValue):Promise<bigint>{let b:SqliteValue=null,u:SqliteValue=null,n:SqliteValue=null,f:NativeCell=null,s:SqliteValue=null,bytes:SqliteValue=null;switch(v.kind){case"null":case"array":case"object":break;case"boolean":b=boolean(v.value);break;case"unsigned":u=integer(v.value,true).toString();break;case"integer":n=integer(v.value);break;case"float":f=v.value;break;case"string":s=v.value;break;case"bytes":if(!(v.value instanceof Uint8Array))throw Error("procedural byte primitive differs");bytes=v.value;break;default:throw Error("procedural generation value kind differs");}return ieee(p,"generation_value",[v.kind,b,u,n,f,s,bytes]);}
async function answer(p:ArtifactSqliteProjection,root:GenerationValue):Promise<bigint>{const id=await scalar(p,root),pending:[bigint,GenerationValue][]=[[id,root]];while(pending.length){const[owner,v]=pending.pop()!;await p.checkpoint();if(v.kind==="array"){p.checkRowsAdditional(v.values.length);for(let i=0;i<v.values.length;i++){const value=v.values[i]!,id=await scalar(p,value);await p.insert("generation_array_element",[owner,BigInt(i),id]);if(value.kind==="array"||value.kind==="object")pending.push([id,value]);}}else if(v.kind==="object"){p.checkRowsAdditional(v.members.length);for(let i=0;i<v.members.length;i++){const[key,value]=v.members[i]!,id=await scalar(p,value);await p.insert("generation_object_member",[owner,BigInt(i),key,id]);if(value.kind==="array"||value.kind==="object")pending.push([id,value]);}}}return id;}
async function tree(p:ArtifactSqliteProjection,root:FlowTree):Promise<bigint>{const id=await p.insert("generation_tree",[]),pending:[bigint,FlowTree][]=[[id,root]];while(pending.length){const[owner,t]=pending.pop()!;p.checkRowsAdditional(t.neurons.length+t.synapses.length);await p.checkpoint();for(let i=0;i<t.neurons.length;i++){const n=t.neurons[i]!,params=await dictionary(p,n.params);let child:SqliteValue=null;if(n.tree!==null){child=await p.insert("generation_tree",[]);pending.push([child,n.tree]);}await p.insert("generation_tree_neuron",[owner,BigInt(i),n.id,n.kind,params,child]);}for(let i=0;i<t.synapses.length;i++){const s=t.synapses[i]!;await p.insert("generation_tree_synapse",[owner,BigInt(i),s.id,s.from,s.to,s.fromPort,s.toPort]);}}return id;}
async function expanded(p:ArtifactSqliteProjection,t:string,owner:bigint,paths:readonly string[]):Promise<void>{p.checkRowsAdditional(paths.length);let previous:string|undefined;for(let i=0;i<paths.length;i++){const v=paths[i]!;if(previous!==undefined&&compare(previous,v)>=0)throw Error("procedural expanded set must be sorted unique paths");previous=v;await p.insert(t,[owner,BigInt(i),v]);}}
async function gui(p:ArtifactSqliteProjection,ui:FlowUi):Promise<bigint>{const camera=ui.camera,id=await ieee(p,"generation_gui",[camera.x,camera.y,camera.zoom]),names=await keys(p,ui.nodes);for(let i=0;i<names.length;i++){const name=names[i]!,n=ui.nodes[name]!,node=await ieee(p,"generation_gui_node",[id,BigInt(i),name,n.layout.x,n.layout.y,n.chrome.kind]),c=n.chrome;switch(c.kind){case"plain":await p.insert("generation_gui_plain",[boolean(c.preview)],node);break;case"slider":await ieee(p,"generation_gui_slider",[c.label,c.min,c.max,c.step,c.value],node);break;case"note":await p.insert("generation_gui_note",[c.text],node);break;case"image":await p.insert("generation_gui_image",[c.src],node);break;case"variable":await p.insert("generation_gui_variable",[c.name,c.schema],node);break;default:throw Error("procedural chrome kind differs");}}p.checkRowsAdditional(ui.previews.length);for(let i=0;i<ui.previews.length;i++){const v=ui.previews[i]!,preview=await dictionary(p,v.preview),row=await ieee(p,"generation_gui_preview",[id,BigInt(i),v.id,v.source?.neuron??null,v.source?.channel??null,v.mode,preview,v.layout?.x??null,v.layout?.y??null]);await expanded(p,"generation_gui_expanded",row,v.expanded);}return id;}
/** 📤️ Emits only authored domain tables, retaining exact primitive widths and relationship order. */
export async function projectProceduralSnapshot(s:ProceduralSnapshot,sql:string,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{const p=await ArtifactSqliteProjection.create(sql,options),host=s.hostSnapshot,g=s.generation;p.checkRowsAdditional(2+host.widgets.length+host.synapses.length+g.generations.length);await ieee(p,"generation_host",[host.schema,host.camera.x,host.camera.y,host.camera.zoom],1n);await p.insert("generation_document",[1n,g.selectedGenerationId??null,g.previewText??null],1n);for(let i=0;i<host.widgets.length;i++){const w=host.widgets[i]!,kind={neuron:"neuron",inputSlider:"input_slider",inputNote:"input_note",inputImage:"input_image",variable:"variable",outputPreview:"output_preview",outputAction:"output_action",outputExport:"output_export",cluster:"cluster"}[w.kind];if(kind===undefined)throw Error("procedural widget kind differs");const id=await p.insert("generation_widget",[1n,BigInt(i),w.id,kind]);switch(w.kind){case"neuron":{const params=await dictionary(p,w.params);await p.insert("generation_neuron_widget",[w.neuronKind,params,boolean(w.preview)],id);p.checkRowsAdditional(w.inputPorts.length+w.outputPorts.length);for(const[direction,ports]of[["input",w.inputPorts],["output",w.outputPorts]]as const)for(let j=0;j<ports.length;j++)await p.insert("generation_widget_port",[id,direction,BigInt(j),ports[j]!]);break;}case"inputSlider":await ieee(p,"generation_slider_widget",[w.label,w.value,w.min,w.max,w.step],id);break;case"inputNote":await p.insert("generation_note_widget",[w.text],id);break;case"inputImage":await p.insert("generation_image_widget",[w.src],id);break;case"variable":await p.insert("generation_variable_widget",[w.name,w.schema],id);break;case"outputPreview":{const preview=await dictionary(p,w.preview);await p.insert("generation_preview_widget",[preview],id);await expanded(p,"generation_widget_expanded",id,w.expanded);break;}case"outputAction":await p.insert("generation_action_widget",[w.action],id);break;case"outputExport":await p.insert("generation_export_widget",[w.format],id);break;case"cluster":{const graph=await tree(p,w.tree),ui=await gui(p,w.flow);await p.insert("generation_cluster_widget",[w.name,graph,ui],id);break;}}}for(let i=0;i<host.synapses.length;i++){const v=host.synapses[i]!;await p.insert("generation_host_synapse",[1n,BigInt(i),v.id,v.from,v.to,v.fromPort,v.toPort]);}const layout=await keys(p,host.layout);for(let i=0;i<layout.length;i++){const name=layout[i]!,v=host.layout[name]!;await ieee(p,"generation_host_layout",[1n,BigInt(i),name,v.x,v.y]);}for(let i=0;i<g.generations.length;i++){const v=g.generations[i]!,id=await p.insert("generation_preset",[1n,BigInt(i),v.id,v.name]),names=await keys(p,v.values);for(let j=0;j<names.length;j++){const key=names[j]!,value=await answer(p,v.values[key]!);await p.insert("generation_answer",[id,BigInt(j),key,value]);}}return p.finish();}
