[package]
name = "semio-framework-os-kernel-math-graph-trees"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_trees"
crate-type = ["rlib"]
path = "📦.rs"

[dependencies]
mathematical_graph = { path = "..", package = "semio-framework-os-kernel-math-graph" }
mathematical_graph_components = { path = "../components", package = "semio-framework-os-kernel-math-graph-components" }
mathematical_random = { path = "../../random", package = "semio-framework-os-kernel-math-random" }
mathematical_algebra = { path = "../../algebra", package = "semio-framework-os-kernel-math-algebra" }
