[package]
name = "mathematical_graph_connectivity"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph = { path = "../../rs" }
mathematical_graph_flow = { path = "../../flow/rs" }
mathematical_graph_components = { path = "../../components/rs" }
