[package]
name = "sequence-plugin"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[package.metadata.component]
package = "semio:sequence"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "sequence"
ports = { react = 6077, wgpu = 6177 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"

[dependencies]
sequence_core = { path = "../../core/rs" }
mathematical_graph_port_directed_dag = { path = "../../../mathematical/graph/port/directed/dag/rs" }
semio-framework-plugin = { path = "../../../framework/plugin/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

