use super::*;
use serde_json::{Value,json};
fn neutral(value:Value)->Value{match value{Value::Number(n)=>json!(n.as_f64().unwrap()),Value::Array(items)=>Value::Array(items.into_iter().map(neutral).collect()),Value::Object(fields)=>Value::Object(fields.into_iter().map(|(key,value)|(key,neutral(value))).collect()),other=>other}}
#[test]
fn mounted_vector_view_preserves_shared_records_and_borrows_paths(){let cases:Value=serde_json::from_str(include_str!("../../🧫️fixtures/🔣️.json")).unwrap();let rows:Value=serde_json::from_str(include_str!("../../../📋️prepare/🧫️fixtures/🎬️vector/🔣️.json")).unwrap();for sample in cases.as_array().unwrap(){let row=rows.as_array().unwrap().iter().find(|row|row["name"]==sample["name"]).unwrap();let doc=serde_json::from_value(row["document"].clone()).unwrap();let mut job=crate::schema::scene_preparation::DocumentVectorJob::new(&doc,crate::editor::drawing::geometry_session::limits(),crate::editor::drawing::geometry_session::algorithms()).unwrap();while !job.advance(7).unwrap().done{}let plan=job.result().unwrap();let views=nodes(&plan,None).unwrap();let records:Value=serde_json::from_str(&semio_framework_pack_json::to_json_string(&views)).unwrap();assert_eq!(neutral(records),neutral(sample["expected"].clone()),"{}",sample["name"]);for view in &views{let node=plan.nodes.iter().find(|node|node.id==view.id).unwrap();if let DocumentSceneContent::Path{segments,..}=&node.content{assert_eq!(view.segments.as_ptr(),segments.as_ptr());}}eprintln!("[DEBUG] Complete native canvas projection {} preserved every shared record and borrowed its path buffer",sample["name"]);}}

#[test]
fn mounted_vector_view_refuses_missing_assets_and_unresolved_algorithms(){let invalids:Value=serde_json::from_str(include_str!("../../🧫️fixtures/⚠️invalid/🔣️.json")).unwrap();let rows:Value=serde_json::from_str(include_str!("../../../📋️prepare/🧫️fixtures/🎬️vector/🔣️.json")).unwrap();for row in invalids.as_array().unwrap(){let source=rows.as_array().unwrap().iter().find(|source|source["name"]==row["source"]).unwrap();let document=serde_json::from_value(source["document"].clone()).unwrap();let mut plan=if row["action"]=="prepare-only"{let mut job=crate::schema::scene_preparation::DocumentSceneJob::new(&document,crate::editor::drawing::geometry_session::limits()).unwrap();while !job.advance(7).unwrap().done{}job.result().unwrap()}else{let mut job=crate::schema::scene_preparation::DocumentVectorJob::new(&document,crate::editor::drawing::geometry_session::limits(),crate::editor::drawing::geometry_session::algorithms()).unwrap();while !job.advance(7).unwrap().done{}job.result().unwrap()};if row["action"]=="remove-assets"{plan.assets.clear();}let error=nodes(&plan,None).err().expect("invalid completed scene must be refused");assert!(error.to_string().contains(row["error"].as_str().unwrap()));}eprintln!("[DEBUG] Native canvas refused missing actual assets and unresolved algorithm owners explicitly");}

#[test]
fn mounted_vector_view_bounds_share_affine_stroke_image_text_and_curve_cases(){
 let rows:Value=serde_json::from_str(include_str!("../../🧫️fixtures/📐️bounds/🔣️.json")).unwrap();
 for row in rows.as_array().unwrap(){let record=&row["record"];let segments:Vec<PathSegment>=serde_json::from_value(record["segments"].clone()).unwrap();let transform=serde_json::from_value(record["transform"].clone()).unwrap();let stroke:Option<StrokeStyle>=record.get("stroke").map(|value|serde_json::from_value(value.clone()).unwrap());let asset=RasterSceneAsset{id:"bounds-asset".into(),mime:"image/png".into(),data:std::sync::Arc::new("AA==".into())};let text=record.get("text").map(|value|(value["content"].as_str().unwrap(),value["size"].as_f64().unwrap()));let image=record.get("image").map(|value|(&asset,value["width"].as_f64().unwrap(),value["height"].as_f64().unwrap()));
 let node=PreparedSceneNode{id:"bounds",groups:&[],transform,segments:Cow::Borrowed(&segments),fill:None,stroke:stroke.as_ref(),opacity:1.0,blend_mode:"normal",visible:true,fill_rule:None,text,image};
 let actual=node.bounds();if row["bounds"].is_null(){assert!(actual.is_none());}else{for (index,value) in actual.unwrap().iter().enumerate(){assert!((*value-row["bounds"][index].as_f64().unwrap()).abs()<1e-10,"{}",row["name"]);}}
 }
 let node=PreparedSceneNode{id:"hidden",groups:&[],transform:[1.0,0.0,0.0,1.0,0.0,0.0],segments:Cow::Borrowed(&[]),fill:None,stroke:None,opacity:1.0,blend_mode:"normal",visible:false,fill_rule:None,text:None,image:None};
 assert_eq!(bounds(None,&[node]),[0.0,0.0,1024.0,1024.0]);eprintln!("[DEBUG] Native complete-picture bounds matched shared affine stroke, image, Unicode multiline fallback and cubic-extrema cases");
}

#[test]
fn mounted_vector_selection_bounds_respect_visible_paint_and_actual_authored_lock_ancestry(){
 let cases:Vec<Value>=serde_json::from_str(include_str!("../../🧫️fixtures/📐️selection/🔣️.json")).unwrap();let rows:Vec<Value>=serde_json::from_str(include_str!("../../../📋️prepare/🧫️fixtures/🎬️vector/🔣️.json")).unwrap();
 fn configure(layer:&mut crate::DrawingLayerNode,row:&Value){let id=crate::schema::layer_id(layer).to_string();let base=crate::schema::layer_base_mut(layer);if row["locked"].as_array().unwrap().iter().any(|value|value==&id){base.locked=true;}if row["hidden"].as_array().unwrap().iter().any(|value|value==&id){base.visible=false;}if row["zeroOpacity"].as_array().unwrap().iter().any(|value|value==&id){base.opacity=0.0;}if let crate::DrawingLayerNode::Group(group)=layer{if row["ordinary"]==true{group.isolation=false;group.base.opacity=1.0;group.base.blend_mode="normal".into();}for child in &mut group.children{configure(child,row);}}}
 for row in cases{let source=rows.iter().find(|source|source["name"]==row["source"]).unwrap();let mut document:crate::DrawingSnapshot=serde_json::from_value(source["document"].clone()).unwrap();for layer in &mut document.layers{configure(layer,&row);}let selected:Vec<String>=serde_json::from_value(row["selected"].clone()).unwrap();for grant in [1,7,4096]{let mut job=crate::schema::scene_preparation::DocumentVectorJob::new(&document,crate::editor::drawing::geometry_session::limits(),crate::editor::drawing::geometry_session::algorithms()).unwrap();while !job.advance(grant).unwrap().done{}let plan=job.result().unwrap();let before=plan.nodes.iter().map(|node|node.source_path.as_ptr()).collect::<Vec<_>>();let actual=selection_bounds(&plan,&selected).unwrap();assert_eq!(neutral(json!(actual)),neutral(row["expected"].clone()),"{}",row["name"]);assert_eq!(before,plan.nodes.iter().map(|node|node.source_path.as_ptr()).collect::<Vec<_>>());let mut paint=crate::schema::scene_paint::scene::ScenePaintJob::new(plan,0.001,crate::schema::scene_paint::scene::PaintedSceneLimits{max_nodes:1024,max_segments:65536,max_points:262144,max_contours:65536,max_work:1000000000});while !paint.advance(grant).unwrap().done{}let(mut cleanup,prepared)=paint.into_retirement();while !cleanup.advance(grant).unwrap().done{}let prepared=prepared.unwrap();let tree=crate::editor::drawing::modes::edit::windows::canvas::render(Some(&prepared),1,&document,&Default::default(),&Default::default(),"selectDirect",&selected,&[]).unwrap();let scene:semio_framework_plugin::Canvas2dScene=match &tree.component{semio_framework_plugin::Component::Surface(surface)=>semio_framework_ui_scene::decode(surface).unwrap(),_=>panic!("canvas must assemble the actual typed scene surface")};let records:Vec<Value>=serde_json::from_str(&scene.layers_json).unwrap();assert_eq!(records.iter().filter(|record|record["id"].as_str().is_some_and(|id|id.starts_with("overlay:transform-handle:"))).count(),if actual.is_some(){9}else{0},"{}",row["name"]);assert_eq!(records.iter().filter(|record|record["id"]=="overlay:selection-bounds").count(),usize::from(actual.is_some()));semio_framework_plugin::artifact_app_laws::project_and_retire_fixture_tree(semio_framework_plugin::built_to_component_tree(tree)).unwrap();let mut cleanup=crate::schema::scene_paint::scene::PreparedSceneCloseJob::new(prepared);while !cleanup.advance(grant).unwrap().done{}println!("[DEBUG] Actual canvas selection {} grants={} worldExtrema={actual:?} consumes complete authored ancestry without copying source paths",row["name"],grant);}}
}
