import {Database} from 'bun:sqlite';
import assert from 'node:assert/strict';
import Ajv2020 from 'ajv/dist/2020';
import {parseBinary64} from '../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts';
const root='✏️s/🔌️plugins/🗄️stdio/🗿️artifacts/🧿️semio/🏅️standards/🔖️v1/🪆️subsets/📑️document/🚪️io/🪶️sqlite/📸️snapshot/';
const sql=await Bun.file(root+'🗄️.sql').text(),metadata=await Bun.file('🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧬️schema/🗄️.sql').text();
const plain=(text:string)=>({text,style:{bold:false,italic:false,underline:false,size:null,font:null,color:null,link:null}});const text='English Deutsch\u0000文';const full={schema:'s.stdio.semio.document',styles:[{id:'',name:'root',basedOn:null},{id:'child',name:'child',basedOn:''}],images:[{id:'image-🖼',mime:'image/png',bytes:[0,255,127]}],blocks:[{kind:'paragraph',style_id:'',runs:[{text,style:{bold:true,italic:true,underline:true,size:{bits:'bff8000000000000'},font:'',color:'#ff0000',link:'https://example.test'}},plain('')]},{kind:'heading',level:255,style_id:'child',runs:[]},{kind:'list',ordered:true,items:[{blocks:[{kind:'pageBreak'}]},{blocks:[]}]},{kind:'table',rows:[{cells:[{blocks:[{kind:'paragraph',style_id:null,runs:[plain('cell')]}]},{blocks:[]}]}]},{kind:'code',language:'',text},{kind:'quote',blocks:[{kind:'quote',blocks:[]}]},{kind:'image',image_id:'image-🖼',alt:'',width:{bits:'0000000000000000'},height:null},{kind:'pageBreak'}]};const empty={schema:full.schema,styles:[],images:[],blocks:[]};
function census(source:typeof full|typeof empty,encoding?:string){const db=new Database(':memory:');db.exec(sql);if(encoding)db.exec(metadata);const insert=(table:string,values:any[])=>db.query('INSERT INTO '+table+' VALUES ('+values.map(()=>'?').join(',')+')').run(...values);const ins=(name:string,v:any[])=>insert('semio_document_'+name,v);ins('collection',[1]);ins('document',[1,source.schema,1]);if(source.blocks.length){ins('style',[1,1,0,'','root',null]);ins('style',[2,1,1,'child','child',1]);ins('image',[1,1,0,'image-🖼','image/png',new Uint8Array([0,255,127])]);const kinds=['paragraph','heading','list','table','code','quote','image','pageBreak'];kinds.forEach((kind,i)=>{ins('block',[i+1,kind]);ins('member',[i+1,1,i,i+1])});ins('paragraph',[1,1]);ins('run',[1,1,0,text,1,1,1,-1.5,'','#ff0000','https://example.test',-4613937818241073152n,'finite']);ins('run',[2,1,1,'',0,0,0,null,null,null,null,null,null]);ins('heading',[2,255,2]);ins('list',[3,1]);ins('collection',[2]);ins('collection',[3]);ins('list_item',[1,3,0,2]);ins('list_item',[2,3,1,3]);ins('table',[4]);ins('table_row',[1,4,0]);ins('collection',[4]);ins('collection',[5]);ins('table_cell',[1,1,0,4]);ins('table_cell',[2,1,1,5]);ins('code',[5,'',text]);ins('collection',[6]);ins('quote',[6,6]);ins('image_block',[7,1,'',0,null,0n,'finite',null,null]);ins('page_break',[8]);ins('block',[9,'quote']);ins('member',[9,6,0,9]);ins('collection',[7]);ins('quote',[9,7]);ins('block',[10,'paragraph']);ins('member',[10,4,0,10]);ins('paragraph',[10,null]);ins('run',[3,10,0,'cell',0,0,0,null,null,null,null,null,null]);ins('block',[11,'pageBreak']);ins('member',[11,2,0,11]);ins('page_break',[11]);assert.equal((db.query('SELECT hex(text) bytes FROM semio_document_run WHERE id=1').get() as any).bytes,Buffer.from(text).toString('hex').toUpperCase());}
 if(encoding)insert('semio_snapshot',[1,'s.stdio.semio','v1','document',1,encoding]);
 assert.deepEqual(db.query('PRAGMA integrity_check').get(),{integrity_check:'ok'});assert.deepEqual(db.query('PRAGMA foreign_key_check').all(),[]);
 let rows=0,valueBytes=0,schemaBytes=0;const tableWidths:Record<string,number>={};
 for(const row of db.query("SELECT name,sql FROM sqlite_master WHERE type='table' ORDER BY name").all() as {name:string,sql:string}[]){schemaBytes+=Buffer.byteLength(row.name)+Buffer.byteLength(row.sql);tableWidths[row.name]=db.query('PRAGMA table_info('+row.name+')').all().length;const cells=db.query('SELECT * FROM '+row.name).values();rows+=cells.length;for(const values of cells)for(const value of values)valueBytes+=value===null?0:typeof value==='string'?Buffer.byteLength(value):typeof value==='number'||typeof value==='bigint'?8:(value as Uint8Array).length;}
 db.close();return {rows,valueBytes,schemaBytes,tableWidths};
}
const f=census(full),e=census(empty),fb=census(full,'binary'),ft=census(full,'text'),eb=census(empty,'binary'),et=census(empty,'text');assert.equal(Object.keys(f.tableWidths).length,18);assert.equal(Math.max(...Object.values(f.tableWidths)),13);assert.equal(fb.schemaBytes-f.schemaBytes,293);assert.equal(fb.valueBytes-f.valueBytes,45);assert.equal(ft.valueBytes-f.valueBytes,43);
const hydrate='const hydrate=(value:unknown):unknown=>Array.isArray(value)?value.map(hydrate):value!==null&&typeof value==="object"?("bits"in value?{bits:String((value as {bits:string}).bits).length===8?Number.parseInt(String((value as {bits:string}).bits),16):BigInt("0x"+String((value as {bits:string}).bits))}:Object.fromEntries(Object.entries(value).map(([key,item])=>[key,hydrate(item)]))):value;Object.assign(source,hydrate(source))';
const spec=[{name:'document',cap:'Document',tables:18,maxColumns:13,contract:{schemaBytes:f.schemaBytes,tableWidths:f.tableWidths,cases:[{id:'full',sourceSnapshot:full,rows:f.rows,valueBytes:f.valueBytes},{id:'metadataRetainingEmpty',sourceSnapshot:empty,rows:e.rows,valueBytes:e.valueBytes}],publicIo:{schemaBytes:fb.schemaBytes,tableWidths:fb.tableWidths,cases:[{id:'full',rows:fb.rows,valueBytes:{binary:fb.valueBytes,text:ft.valueBytes}},{id:'metadataRetainingEmpty',rows:eb.rows,valueBytes:{binary:eb.valueBytes,text:et.valueBytes}}]}},rustBody:'let mut source=fixture();if case["id"]=="metadataRetainingEmpty"{source.styles.clear();source.images.clear();source.blocks.clear();}source',hydrate}];
let words=0;const admit=(value:unknown):void=>{if(Array.isArray(value))value.forEach(admit);else if(value&&typeof value==='object'){if('bits'in value){parseBinary64(value);words++;}else Object.values(value).forEach(admit);}};
const transpiler=new Bun.Transpiler({loader:'ts'});for(const item of spec[0].contract.cases){const source=structuredClone(item.sourceSnapshot);new Function('source',transpiler.transformSync(hydrate))(source);admit(source);assert.equal(source.schema,'s.stdio.semio.document');}
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',type:'object',properties:Object.fromEntries(Object.entries(spec[0].contract).map(([key,value])=>[key,{const:value}])),required:Object.keys(spec[0].contract),additionalProperties:false};assert.equal(new Ajv2020({strict:true}).compile(schema)(spec[0].contract),true);
await Bun.write(new URL('handcrafted-native-matched-demand-specifications.json',import.meta.url),JSON.stringify(spec,null,2)+'\n');await Bun.write(new URL('handcrafted-native-matched-contract-schema.json',import.meta.url),JSON.stringify(schema,null,2)+'\n');console.log(JSON.stringify({f,e,publicIo:spec[0].contract.publicIo,actualBinary64ParserWords:words}));
