/** sourcing facet WASM facades */
export * as curate_schema from "../../🗿️artifacts/🗂️curate/🧬️schema/🟦️component.ts";
export * as curate_snapshot_schema from "../../🗿️artifacts/🗂️curate/📸️snapshot/🧬️schema/🟦️component.ts";
export * as curate_diff from "../../🗿️artifacts/🗂️curate/🔺️diff/🟦️component.ts";
export * as curate_diff_schema from "../../🗿️artifacts/🗂️curate/🔺️diff/🧬️schema/🟦️component.ts";
export * as curate_dsl from "../../🗿️artifacts/🗂️curate/🗣️dsl/🟦️component.ts";
export * as curate_pack from "../../🗿️artifacts/🗂️curate/📸️snapshot/🎒️pack/🟦️component.ts";
export * as curate_op from "../../🗿️artifacts/🗂️curate/🔧️op/🟦️component.ts";
export * as curate_spr from "../../🗿️artifacts/🗂️curate/📡️spr/🟦️component.ts";
