syntax = "proto3";
package semio.s.fem.fem3d.artifact;

// 🧬️ Fem3d artifact schema
message Fem3dArtifact {
  // @state artifact
  repeated FemNode nodes = 1;
  // @state artifact
  repeated FemElement elements = 2;
  // @state artifact
  repeated FemMaterial materials = 3;
  // @state artifact
  repeated FemSection sections = 4;
  // @state artifact
  repeated FemSolid solids = 5;
  // @state artifact
  repeated FemSupport supports = 6;
  // @state artifact
  repeated FemLoadCase load_cases = 7;
  // @state artifact
  repeated FemCombination combinations = 8;
  // @state artifact
  FemAnalysisSettings analysis = 9;
  // @state presence
  optional string result_source_id = 10;
  // @state presence
  string result_mode = 11;
  // @state presence
  uint32 result_mode_index = 12;
  // @state config
  FemCamera camera = 13;
  // @state artifact
  string solver_results_json = 14;
  // @state artifact
  string mesh_preview_json = 15;
}

