syntax = "proto3";
package semio.s.vcs.vcs.mutation;

import "✏️rename-vcs/🛰️component.proto";
import "🔢change-counter/🛰️component.proto";
import "📝change-notes/🛰️component.proto";
import "🚦change-status/🛰️component.proto";
import "🏷️add-tag/🛰️component.proto";
import "🗑️remove-tag/🛰️component.proto";

message VcsMutation {
  oneof mutation {
    RenameVcs rename_vcs = 1;
    ChangeCounter change_counter = 2;
    ChangeNotes change_notes = 3;
    ChangeStatus change_status = 4;
    AddTag add_tag = 5;
    RemoveTag remove_tag = 6;
  }
}
