[package]
name = "mathematical_graph_port_directed_normal"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
ui_styling = { path = "../../../../../ui/styling/rs" }
mathematical_graph_port_directed = { path = ".." }
mathematical_graph_normal_undirected = { path = "../../../normal/undirected" }
mathematical_core = { path = "../../../../core" }
infinite_cavas = { path = "../../../../../infinite/cavas/vello" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
