/** 🎞️ Individually authored GIF87a logical screen, palette and image relations. */
import type { GifSnapshot } from "../🟦️.ts";
import { ArtifactSqliteProjection,artifactSqliteCheckpoint,artifactSqliteTables,artifactSqliteDocument,artifactSqliteDocumentReference,artifactSqliteBoolean,artifactSqliteOrderedRows,artifactSqliteText,type ArtifactSqliteOptions } from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import type { SqliteDatabase } from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import { gifInteger,gifFlag,gifUnsigned,gifEntities,gifSingletons,gifGroups,gifWritePalette,gifReadPalette,gifReadPixels } from "../../../../../../🪶️sqlite/🟦️.ts";
/** 🏛️ Literal copy of the adjacent individually handcrafted GIF87a schema. */
export const GIF87_SQLITE_SCHEMA = "CREATE TABLE gif87_document (\n id INTEGER PRIMARY KEY CHECK (id = 1), schema TEXT NOT NULL,\n screen_width INTEGER NOT NULL CHECK (screen_width BETWEEN 0 AND 4294967295),\n screen_height INTEGER NOT NULL CHECK (screen_height BETWEEN 0 AND 4294967295),\n background_color_index INTEGER NOT NULL CHECK (background_color_index BETWEEN 0 AND 255),\n pixel_aspect_ratio INTEGER NOT NULL CHECK (pixel_aspect_ratio BETWEEN 0 AND 255)\n);\nCREATE TABLE gif87_global_palette (\n id INTEGER PRIMARY KEY REFERENCES gif87_document(id) CHECK (id = 1), sorted INTEGER NOT NULL CHECK (sorted IN (0,1))\n);\nCREATE TABLE gif87_global_color (\n id INTEGER PRIMARY KEY, palette_id INTEGER NOT NULL REFERENCES gif87_global_palette(id), ordinal INTEGER NOT NULL CHECK (ordinal >= 0),\n red INTEGER NOT NULL CHECK (red BETWEEN 0 AND 255), green INTEGER NOT NULL CHECK (green BETWEEN 0 AND 255), blue INTEGER NOT NULL CHECK (blue BETWEEN 0 AND 255)\n);\nCREATE TABLE gif87_image (\n id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES gif87_document(id), ordinal INTEGER NOT NULL CHECK (ordinal >= 0),\n left_position INTEGER NOT NULL CHECK (left_position BETWEEN 0 AND 4294967295), top_position INTEGER NOT NULL CHECK (top_position BETWEEN 0 AND 4294967295),\n width INTEGER NOT NULL CHECK (width BETWEEN 0 AND 4294967295), height INTEGER NOT NULL CHECK (height BETWEEN 0 AND 4294967295),\n interlace INTEGER NOT NULL CHECK (interlace IN (0,1))\n);\nCREATE TABLE gif87_local_palette (\n id INTEGER PRIMARY KEY REFERENCES gif87_image(id), sorted INTEGER NOT NULL CHECK (sorted IN (0,1))\n);\nCREATE TABLE gif87_local_color (\n id INTEGER PRIMARY KEY, palette_id INTEGER NOT NULL REFERENCES gif87_local_palette(id), ordinal INTEGER NOT NULL CHECK (ordinal >= 0),\n red INTEGER NOT NULL CHECK (red BETWEEN 0 AND 255), green INTEGER NOT NULL CHECK (green BETWEEN 0 AND 255), blue INTEGER NOT NULL CHECK (blue BETWEEN 0 AND 255)\n);\nCREATE TABLE gif87_pixel (\n id INTEGER PRIMARY KEY, image_id INTEGER NOT NULL REFERENCES gif87_image(id),\n x INTEGER NOT NULL CHECK (x BETWEEN 0 AND 4294967295), y INTEGER NOT NULL CHECK (y BETWEEN 0 AND 4294967295),\n color_index INTEGER NOT NULL CHECK (color_index BETWEEN 0 AND 255)\n);\n";

/** 📤️ Projects exact owned GIF87a state without native image encoding. */
export async function gifSnapshotToSqliteDatabase(snapshot:GifSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const out=await ArtifactSqliteProjection.create(GIF87_SQLITE_SCHEMA,options);
 await out.insert("gif87_document",[snapshot.schema,gifInteger(snapshot.width),gifInteger(snapshot.height),gifInteger(snapshot.backgroundColorIndex,255),gifInteger(snapshot.pixelAspectRatio,255)]);
 await gifWritePalette(out,"gif87_global_palette","gif87_global_color",1n,snapshot.gct);
 for(let ordinal=0;ordinal<snapshot.images.length;ordinal++){const image=snapshot.images[ordinal]!;const width=gifInteger(image.width),height=gifInteger(image.height);if(width*height!==BigInt(image.indices.length))throw new Error("GIF87 grid must contain one index per position");
  const id=await out.insert("gif87_image",[1n,BigInt(ordinal),gifInteger(image.left),gifInteger(image.top),width,height,gifFlag(image.interlace)]);
  await gifWritePalette(out,"gif87_local_palette","gif87_local_color",id,image.lct);
  for(let position=0;position<image.indices.length;position++)await out.insert("gif87_pixel",[id,BigInt(position%image.width),BigInt(Math.floor(position/image.width)),gifInteger(image.indices[position]!,255)]);
 }return out.finish();
}

/** 📥️ Reconstructs indexed images with explicit palette presence and unique grids. */
export async function gifSnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<GifSnapshot>{
 await artifactSqliteCheckpoint(options,"reconstructSnapshot",0,0);
 const [documents,globalRows,globalColors,imageRows,localRows,localColors,pixelRows]=await artifactSqliteTables(database,GIF87_SQLITE_SCHEMA,options);
 const document=artifactSqliteDocument(documents!);const imageIds=await gifEntities(imageRows!,options);const global=await gifSingletons(globalRows!,new Set([1n]),options);const globalEntries=await gifGroups(globalColors!,new Set(global.keys()),true,options);const local=await gifSingletons(localRows!,imageIds,options);const localEntries=await gifGroups(localColors!,new Set(local.keys()),true,options);const pixels=await gifGroups(pixelRows!,imageIds,false,options);
 const images:GifSnapshot["images"]=[];
 for(const row of artifactSqliteOrderedRows(imageRows!,2)){artifactSqliteDocumentReference(row,1);const width=gifUnsigned(row,5),height=gifUnsigned(row,6);images.push({left:gifUnsigned(row,3),top:gifUnsigned(row,4),width,height,interlace:artifactSqliteBoolean(row,7),lct:await gifReadPalette(local.get(row.rowid),localEntries.get(row.rowid),options),indices:await gifReadPixels(pixels.get(row.rowid),width,height,options)});if(images.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",images.length,imageRows!.length);}
 const result:GifSnapshot={schema:artifactSqliteText(document,1),width:gifUnsigned(document,2),height:gifUnsigned(document,3),gct:await gifReadPalette(global.get(1n),globalEntries.get(1n),options),backgroundColorIndex:gifUnsigned(document,4,255),pixelAspectRatio:gifUnsigned(document,5,255),images};await artifactSqliteCheckpoint(options,"reconstructSnapshot",imageRows!.length,imageRows!.length);return result;
}
