[package]
name = "semio-framework-os-kernel-math-graph-io"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_io"
crate-type = ["rlib"]
path = "../../../../🕸️graph/🔌️io/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
mathematical_graph = { path = "../../../../🕸️graph/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-graph" }
