/** 🧫️ Explicit test-only construction of the neutral procedural domain corpus. */
import {binary64,type Binary64} from "../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts";
import type{ProceduralSnapshot,NeuralValue,NeuralDictionary,GenerationValue,FlowTree,FlowUi,NodeChrome,Widget,WidgetLayout,SynapseSpec}from"../../🧬️model/🟦️.ts";
type ObjectValue=Record<string,unknown>;
function object(v:unknown):ObjectValue{if(v===null||typeof v!=="object"||Array.isArray(v))throw Error("fixture object differs");return v as ObjectValue;}
function array(v:unknown):unknown[]{if(!Array.isArray(v))throw Error("fixture array differs");return v;}
function text(v:unknown):string{if(typeof v!=="string")throw Error("fixture TEXT differs");return v;}
function number(v:unknown):number{if(typeof v!=="number")throw Error("fixture number differs");return v;}
function bool(v:unknown):boolean{if(typeof v!=="boolean")throw Error("fixture boolean differs");return v;}
function strings(v:unknown):string[]{return array(v).map(text);}
function word(v:unknown):Binary64{return binary64(number(v));}
function camera(v:unknown):{x:Binary64;y:Binary64;zoom:Binary64}{const r=object(v);return{x:word(r.x),y:word(r.y),zoom:word(r.zoom)};}
function layout(v:unknown):WidgetLayout{const r=object(v);return{x:word(r.x),y:word(r.y)};}
function dictionary(v:unknown):Record<string,NeuralValue>{const result:Record<string,NeuralValue>=Object.create(null);for(const[key,value]of Object.entries(object(v)))result[key]=neural(value);return result;}
function neural(v:unknown):NeuralValue{if(v===null)return{kind:"null"};if(typeof v==="boolean")return{kind:"boolean",value:v};if(typeof v==="string")return{kind:"string",value:v};if(typeof v==="number")return Number.isInteger(v)?{kind:"integer",value:BigInt(v)}:{kind:"decimal",value:binary64(v)};return{kind:"dictionary",value:dictionary(v)};}
function synapse(v:unknown):SynapseSpec{const r=object(v);return{id:text(r.id),from:text(r.from),to:text(r.to),fromPort:text(r.fromPort),toPort:text(r.toPort)};}
function tree(v:unknown):FlowTree{const r=object(v);return{neurons:array(r.neurons).map(v=>{const n=object(v);return{id:text(n.id),kind:text(n.kind),params:dictionary(n.params),tree:n.tree===null?null:tree(n.tree)};}),synapses:array(r.synapses).map(synapse)};}
function chrome(v:unknown):NodeChrome{const r=object(v);switch(r.kind){case"plain":return{kind:"plain",preview:bool(r.preview)};case"slider":return{kind:"slider",label:text(r.label),min:word(r.min),max:word(r.max),step:word(r.step),value:word(r.value)};case"note":return{kind:"note",text:text(r.text)};case"image":return{kind:"image",src:text(r.src)};case"variable":return{kind:"variable",name:text(r.name),schema:text(r.schema)};default:throw Error("fixture chrome differs");}}
function gui(v:unknown):FlowUi{const r=object(v),nodes:Record<string,{layout:WidgetLayout;chrome:NodeChrome}>=Object.create(null);for(const[key,value]of Object.entries(object(r.nodes))){const n=object(value);nodes[key]={layout:layout(n.layout),chrome:chrome(n.chrome)};}return{camera:camera(r.camera),nodes,previews:array(r.previews).map(v=>{const p=object(v),source=p.source===null?null:object(p.source);return{id:text(p.id),source:source===null?null:{neuron:text(source.neuron),channel:text(source.channel)},mode:text(p.mode),preview:dictionary(p.preview),expanded:strings(p.expanded),layout:p.layout===null?null:layout(p.layout)};})};}
function widget(v:unknown):Widget{const r=object(v),id=text(r.id);switch(r.kind){case"neuron":return{kind:"neuron",id,neuronKind:text(r.neuronKind),params:dictionary(r.params),inputPorts:strings(r.inputPorts),outputPorts:strings(r.outputPorts),preview:bool(r.preview)};case"inputSlider":return{kind:"inputSlider",id,label:text(r.label),value:word(r.value),min:word(r.min),max:word(r.max),step:word(r.step)};case"inputNote":return{kind:"inputNote",id,text:text(r.text)};case"inputImage":return{kind:"inputImage",id,src:text(r.src)};case"variable":return{kind:"variable",id,name:text(r.name),schema:text(r.schema)};case"outputPreview":return{kind:"outputPreview",id,preview:dictionary(r.preview),expanded:strings(r.expanded)};case"outputAction":return{kind:"outputAction",id,action:text(r.action)};case"outputExport":return{kind:"outputExport",id,format:text(r.format)};case"cluster":return{kind:"cluster",id,name:text(r.name),tree:tree(r.tree),flow:gui(r.flow)};default:throw Error("fixture widget differs");}}
function answer(v:unknown):GenerationValue{const r=object(v);switch(r.kind){case"null":return{kind:"null"};case"boolean":return{kind:"boolean",value:bool(r.value)};case"unsigned":return{kind:"unsigned",value:BigInt(text(r.value))};case"integer":return{kind:"integer",value:BigInt(text(r.value))};case"float":return{kind:"float",value:{bits:BigInt(`0x${text(r.bits)}`)}};case"string":return{kind:"string",value:text(r.value)};case"bytes":{const hex=text(r.hex);return{kind:"bytes",value:Uint8Array.from(hex.match(/../g)??[],v=>parseInt(v,16))};}case"array":return{kind:"array",values:array(r.values).map(answer)};case"object":return{kind:"object",members:array(r.members).map(v=>{const m=object(v);return[text(m.key),answer(m.value)]as const;})};default:throw Error("fixture answer differs");}}
/** 🌀️ Decode only this fixed neutral fixture, with exact decimal boundaries instead of rounded JSON numbers. */
export function proceduralSnapshotFixture(input:unknown):ProceduralSnapshot{const corpus=object(input),h=object(corpus.hostSnapshot),g=object(corpus.generation),words=strings(corpus.words).map(v=>({bits:BigInt(`0x${v}`)})),integerWords=object(corpus.integerWords),widgets=array(h.widgets).map(widget),layouts:Record<string,WidgetLayout>=Object.create(null);for(const[key,value]of Object.entries(object(h.layout)))layouts[key]=layout(value);const neuron=widgets[0];if(neuron?.kind!=="neuron")throw Error("fixture first neuron differs");(neuron.params as Record<string,NeuralValue>).int={kind:"integer",value:BigInt(text(integerWords.minimum))};const slider=widgets[1];if(slider?.kind!=="inputSlider")throw Error("fixture slider differs");slider.value=words[3]!;slider.min=words[4]!;slider.max=words[5]!;slider.step=words[6]!;const cluster=widgets[8];if(cluster?.kind!=="cluster"||!cluster.tree.neurons[0]?.tree?.neurons[0])throw Error("fixture nested tree differs");(cluster.tree.neurons[0].tree.neurons[0].params as Record<string,NeuralValue>).value={kind:"integer",value:BigInt(text(integerWords.maximum))};const generations=array(g.generations).map(v=>{const p=object(v);return{id:text(p.id),name:text(p.name),values:Object.create(null) as Record<string,GenerationValue>};});for(const v of array(corpus.answers)){const a=object(v);generations[1]!.values[text(a.key)]=answer(a);}return{hostSnapshot:{schema:text(h.schema),camera:{x:words[0]!,y:words[1]!,zoom:words[2]!},widgets,synapses:array(h.synapses).map(synapse),layout:layouts},generation:{generations,selectedGenerationId:text(g.selectedGenerationId),previewText:text(g.previewText)}};}
