import {lstat,opendir,readlink} from "node:fs/promises";
import {createHash} from "node:crypto";
import {join,resolve} from "node:path";
import {readPhysicalFileV1,observePhysicalFileV1,type PhysicalFileClaimV1,type FileObservationControlV1} from "../🟦️.ts";

/** 🌲️ One exact physical child identity independent of compiler or application schemas. */
export type CurrentPhysicalEntryV1=Readonly<{path:string;kind:"file"|"directory"|"symlink"|"other";symlinkTarget:string|null}>;

/** 🚪️ Complete current-byte authority supplied by the physical owning composition. */
export interface CurrentPhysicalPortV1 {readonly control:FileObservationControlV1;read(path:string):Promise<string|Uint8Array|undefined>;digest(path:string):Promise<string|undefined>;directoryEntries(path:string):Promise<readonly CurrentPhysicalEntryV1[]|undefined>;checkpoint():Promise<void>;recheck():Promise<void>;}

/** 📁️ Owns cumulative asynchronous file and directory observations without retaining source bodies. */
export class CurrentPhysicalOwnerV1 implements CurrentPhysicalPortV1 {
 private work=0;private bytes=0;private readonly files=new Map<string,PhysicalFileClaimV1>();private readonly directories=new Map<string,string>();private readonly fileIdentities=new Map<string,readonly bigint[]>();private readonly missing=new Set<string>();
 constructor(private readonly root:string,readonly control:FileObservationControlV1){if(!control||![control.maxBytes,control.maxWork,control.chunkBytes].every(Number.isSafeInteger)||control.maxBytes<0||control.maxWork<1||control.chunkBytes<1||control.chunkBytes>1048576||typeof control.cancelled!=="function"||typeof control.remainingMs!=="function"||typeof control.onProgress!=="function")throw Error("Current physical authority refused");this.check();}
 private check():void{if(this.control.cancelled())throw Error("Current observation cancelled");const time=this.control.remainingMs();if(!Number.isFinite(time)||time<=0)throw Error("Current observation deadline");if(this.work>this.control.maxWork||this.bytes>this.control.maxBytes)throw Error("Current observation budget");}
 private admit(units:number,bytes=0):void{this.check();if(!Number.isSafeInteger(units)||units<0||!Number.isSafeInteger(bytes)||bytes<0||units>this.control.maxWork-this.work||bytes>this.control.maxBytes-this.bytes)throw Error("Current observation budget");this.work+=units;this.bytes+=bytes;}
 private progress():void{this.control.onProgress({phase:"read",bytes:this.bytes,totalBytes:this.bytes,work:this.work});this.check();}
 async checkpoint():Promise<void>{this.admit(1);if(this.work%128===0){this.progress();await new Promise<void>(done=>setImmediate(done));this.check();}}
 private path(path:string):string{const value=resolve(this.root,path);if(value.length>256||value.includes("\0"))throw Error("Current physical path refused");return value;}
 private async kind(path:string):Promise<"file"|"directory"|undefined>{await this.checkpoint();try{const stat=await lstat(path);this.check();if(this.missing.has(path))throw Error("Current physical absent input appeared");return stat.isFile()&&!stat.isSymbolicLink()?"file":stat.isDirectory()&&!stat.isSymbolicLink()?"directory":undefined;}catch(error){this.check();if((error as {code?:string}).code==="ENOENT"|| (error as {code?:string}).code==="ENOTDIR"){if(!this.missing.has(path)){this.admit(1,64+path.length*2);this.missing.add(path);}return;}throw error;}}
 private observation():FileObservationControlV1{let work=0,bytes=0;return{maxBytes:this.control.maxBytes-this.bytes,maxWork:this.control.maxWork-this.work,chunkBytes:this.control.chunkBytes,cancelled:()=>this.control.cancelled(),remainingMs:()=>this.control.remainingMs(),onProgress:event=>{this.admit(event.work-work,event.bytes-bytes);work=event.work;bytes=event.bytes;this.progress();}};}
 private async file<T>(path:string,observe:(control:FileObservationControlV1)=>Promise<T>):Promise<T>{await this.checkpoint();const before=await lstat(path,{bigint:true});this.check();const identity=[before.dev,before.ino,before.size,before.mtimeNs,before.ctimeNs],previous=this.fileIdentities.get(path);if(!before.isFile()||before.isSymbolicLink()||previous&&previous.some((value,index)=>value!==identity[index]))throw Error("Current physical identity changed");const value=await observe(this.observation());await this.checkpoint();const after=await lstat(path,{bigint:true});this.check();if(!after.isFile()||after.isSymbolicLink()||[after.dev,after.ino,after.size,after.mtimeNs,after.ctimeNs].some((value,index)=>value!==identity[index]))throw Error("Current physical identity changed during read");if(!previous)this.admit(1,80);this.fileIdentities.set(path,Object.freeze(identity));return value;}
 private retain(claim:PhysicalFileClaimV1):void{const previous=this.files.get(claim.path);if(previous&&(previous.sha256!==claim.sha256||previous.byteLength!==claim.byteLength))throw Error("Current physical bytes changed");if(!previous)this.admit(1,128+claim.path.length*2);this.files.set(claim.path,claim);}
 async read(path:string):Promise<Uint8Array|undefined>{const absolute=this.path(path);if(await this.kind(absolute)!=="file")return;const read=await this.file(absolute,control=>readPhysicalFileV1(absolute,control));this.check();this.retain(read.claim);return read.bytes;}
 async digest(path:string):Promise<string|undefined>{const absolute=this.path(path),kind=await this.kind(absolute);if(kind==="file"){const claim=await this.file(absolute,control=>observePhysicalFileV1(absolute,control));this.check();this.retain(claim);return claim.sha256;}if(kind==="directory"){const entries=await this.directoryEntries(absolute);if(!entries)return;const source=JSON.stringify(entries.map(entry=>[entry.path.slice(absolute.length+1),entry.kind,entry.symlinkTarget]));this.admit(1,Buffer.byteLength(source));return createHash("sha256").update(source).digest("hex");}return;}
 async directoryEntries(path:string):Promise<readonly CurrentPhysicalEntryV1[]|undefined>{
  const absolute=this.path(path);if(await this.kind(absolute)!=="directory")return;await this.checkpoint();const before=await lstat(absolute,{bigint:true});this.check();await this.checkpoint();const handle=await opendir(absolute,{bufferSize:1}),rows:CurrentPhysicalEntryV1[]=[];
  try{for(;;){await this.checkpoint();const entry=await handle.read();this.check();if(!entry)break;const child=join(absolute,entry.name);await this.checkpoint();const stat=await lstat(child);this.check();let symlinkTarget:string|null=null;if(stat.isSymbolicLink()){await this.checkpoint();symlinkTarget=await readlink(child);this.check();}this.admit(1,64+child.length*2+(symlinkTarget?.length??0)*2);rows.push({path:child,kind:stat.isSymbolicLink()?"symlink":stat.isDirectory()?"directory":stat.isFile()?"file":"other",symlinkTarget});}
   this.admit(1,rows.length*16);for(let width=1;width<rows.length;width*=2){const sorted:CurrentPhysicalEntryV1[]=[];for(let start=0;start<rows.length;start+=width*2){let left=start,right=Math.min(start+width,rows.length),middle=right,end=Math.min(start+width*2,rows.length);while(left<middle||right<end){await this.checkpoint();sorted.push(right>=end||left<middle&&Buffer.compare(Buffer.from(rows[left]!.path),Buffer.from(rows[right]!.path))<=0?rows[left++]!:rows[right++]!);}}for(let index=0;index<rows.length;index++){await this.checkpoint();rows[index]=sorted[index]!;}}
   await this.checkpoint();const after=await lstat(absolute,{bigint:true});this.check();if(!after.isDirectory()||before.dev!==after.dev||before.ino!==after.ino||before.mtimeNs!==after.mtimeNs||before.ctimeNs!==after.ctimeNs)throw Error("Current directory changed");const source=JSON.stringify(rows.map(entry=>[entry.path.slice(absolute.length+1),entry.kind,entry.symlinkTarget]));this.admit(1,Buffer.byteLength(source));const sha256=createHash("sha256").update(source).digest("hex"),previous=this.directories.get(absolute);if(previous&&previous!==sha256)throw Error("Current directory roster changed");this.directories.set(absolute,sha256);return rows;
  }finally{await handle.close();}
 }
 async recheck():Promise<void>{for(const [path,claim]of this.files){await this.checkpoint();const current=await this.file(path,control=>observePhysicalFileV1(path,control));if(current.sha256!==claim.sha256||current.byteLength!==claim.byteLength)throw Error("Current physical bytes changed before transfer");}for(const [path,sha256]of this.directories){await this.checkpoint();const entries=await this.directoryEntries(path);if(!entries||createHash("sha256").update(JSON.stringify(entries.map(entry=>[entry.path.slice(path.length+1),entry.kind,entry.symlinkTarget]))).digest("hex")!==sha256)throw Error("Current directory changed before transfer");}for(const path of this.missing){await this.checkpoint();try{await lstat(path);this.check();throw Error("Current physical absent input appeared before transfer");}catch(error){this.check();if((error as {code?:string}).code!=="ENOENT"&&(error as {code?:string}).code!=="ENOTDIR")throw error;}}this.progress();}
}
