/** ✒️ Shared Writer ownership and independent SQL edits. */
import { Database } from "bun:sqlite";
import { expect,test } from "bun:test";
import fixture from "../../🧫️fixtures/🪶️sqlite/🔣️.json";
import { writerSnapshotToSqliteDatabase,writerSnapshotFromSqliteDatabase,validateWriterSnapshotSqliteDialect } from "../../🪶️sqlite/🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
test("Writer child reference components are independent owned text rather than a joined URI",async()=>{for(const document of fixture.referenceCases){const snapshot={...fixture.snapshot,document};const database=await writerSnapshotToSqliteDatabase(snapshot),oracle=Database.deserialize(await exportSqliteDatabase(database));try{expect(oracle.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(await writerSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(snapshot);expect(await validateWriterSnapshotSqliteDialect(snapshot,fixture.dialect,database)).toEqual([]);}finally{oracle.close();}}});
test("Writer fixed child identity and authored text remain separately queryable",async()=>{const database=await writerSnapshotToSqliteDatabase(fixture.snapshot);expect(await writerSnapshotFromSqliteDatabase(database)).toEqual(fixture.snapshot);expect(await validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database)).toEqual([]);const db=Database.deserialize(await exportSqliteDatabase(database));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(fixture.query).get()).toEqual(fixture.result);db.query("UPDATE writer_document SET text=?").run(fixture.editedText);expect(await writerSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).toEqual({...fixture.snapshot,text:fixture.editedText});}finally{db.close();}});
test("Writer actual SQL ownership edits refuse missing child and mismatched fixed parent",async()=>{for(const sql of["DELETE FROM writer_document_child","UPDATE writer_document_child SET document_id=2","INSERT INTO writer_document_child SELECT 2,document_id,child_id,target_artifact_id,target_artifact_kind,target_standard,target_subset FROM writer_document_child"]){const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{db.run("PRAGMA ignore_check_constraints=ON");db.run(sql);await expect(writerSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow();}finally{db.close();}}});

test("Writer neutral exact coordinates, fixed identity, request bounds and callback abort are controlled",async()=>{const database=await writerSnapshotToSqliteDatabase(fixture.snapshot);for(const dialect of fixture.invalidDialects)await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,dialect,database)).rejects.toThrow("subset");const db=Database.deserialize(await exportSqliteDatabase(database));try{db.query("UPDATE writer_document SET schema=?").run("foreign schema");await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow("identity");}finally{db.close();}for(const options of[{maxRows:fixture.limitedRows},{maxValueBytes:fixture.limitedValueBytes}]){await expect(writerSnapshotToSqliteDatabase(fixture.snapshot,options)).rejects.toThrow("limit");await expect(writerSnapshotFromSqliteDatabase(database,options)).rejects.toThrow("limit");}for(const operation of["project","reconstruct","guard"]){const controller=new AbortController();const options={signal:controller.signal,onProgress:()=>controller.abort()};const promise=operation==="project"?writerSnapshotToSqliteDatabase(fixture.snapshot,options):operation==="reconstruct"?writerSnapshotFromSqliteDatabase(database,options):validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database,options);await expect(promise).rejects.toMatchObject({name:"AbortError"});}});

test("Writer independent signed surrogate renumbering preserves the complete owned state",async()=>{const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{for(const sql of fixture.renumberSql)db.run(sql);expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);const database=await importSqliteDatabase(new Uint8Array(db.serialize()));expect(await writerSnapshotFromSqliteDatabase(database)).toEqual(fixture.snapshot);expect(await validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,database)).toEqual([]);}finally{db.close();}});
test("Writer independent semantic field edits refuse a mismatched original snapshot",async()=>{for(const sql of fixture.mismatchSql){const db=Database.deserialize(await exportSqliteDatabase(await writerSnapshotToSqliteDatabase(fixture.snapshot)));try{db.run(sql);expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);await expect(validateWriterSnapshotSqliteDialect(fixture.snapshot,fixture.dialect,await importSqliteDatabase(new Uint8Array(db.serialize())))).rejects.toThrow("identity");}finally{db.close();}}});
