[package]
name = "semio-s-plugin-animate-video"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "../../../../../../../✏️s/🔌️plugin/🎞️animate/🔨️module/🎥️video/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
animate_core = { path = "../../../../../../../✏️s/🔌️plugin/🎞️animate/🔨️module/🫀️core/⚡️implementation/🦀️rust", package = "semio-s-plugin-animate-core" }
mathematical_geometry = { path = "../../../../../../../🧰️framework/🔨️module/🧮️math/📐️geometry/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-geometry" }
framework_hash = { package = "semio-framework-hash", path = "../../../../../../../🧰️framework/🔨️module/#⃣hash/⚡️implementation/🦀️rust" }
vello = { version = "0.7.0", features = ["wgpu", "wgpu_default"] }
wgpu = "27.0.1"
pollster = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
image = { version = "0.25", default-features = false, features = ["png"] }
thiserror = "2.0.12"

[features]
default = []
preview-window = ["winit"]

[dependencies.winit]
version = "0.30.12"
default-features = false
features = ["rwh_06"]
optional = true
