# 🧬️ EN 1999 artifact schema.

type En1999Artifact {
  nEdKn: Float! @state(class: ARTIFACT)
  mEdKnm: Float! @state(class: ARTIFACT)
  aMm2: Float! @state(class: ARTIFACT)
  wElMm3: Float! @state(class: ARTIFACT)
  alloy: Float! @state(class: ARTIFACT)
  chi: Float! @state(class: ARTIFACT)
  iTMm4: Float! @state(class: ARTIFACT)
  lCrMm: Float! @state(class: ARTIFACT)
  thetaC: Float! @state(class: ARTIFACT)
  deltaSigmaEd: Float! @state(class: ARTIFACT)
  deltaSigmaC: Float! @state(class: ARTIFACT)
  fatigueM: Float! @state(class: ARTIFACT)
  nCycles: Float! @state(class: ARTIFACT)
  vWeldEdKn: Float! @state(class: ARTIFACT)
  weldThroatMm: Float! @state(class: ARTIFACT)
  weldLengthMm: Float! @state(class: ARTIFACT)
  betaW: Float! @state(class: ARTIFACT)
  sheetBMm: Float! @state(class: ARTIFACT)
  sheetTMm: Float! @state(class: ARTIFACT)
  sheetKSigma: Float! @state(class: ARTIFACT)
  sheetWElMm3: Float! @state(class: ARTIFACT)
  sheetMEdKnm: Float! @state(class: ARTIFACT)
  shellTMm: Float! @state(class: ARTIFACT)
  shellRMm: Float! @state(class: ARTIFACT)
  sigmaEdShellMpa: Float! @state(class: ARTIFACT)
  annex: Float! @state(class: ARTIFACT)
  selectedCheckIndex: Int @state(class: PRESENCE)
}
