[package]
name = "semio-s-kernel-mathematical-graph-bipartite"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_graph = { path = "../../rs", package = "semio-s-kernel-mathematical-graph" }
mathematical_graph_matching = { path = "../../matching/rs", package = "semio-s-kernel-mathematical-graph-matching" }
mathematical_random = { path = "../../../random/rs", package = "semio-s-kernel-mathematical-random" }
mathematical_algebra = { path = "../../../algebra/rs", package = "semio-s-kernel-mathematical-algebra" }
