type FlowConfig {
  selectedNodeIds: [String!]! @state(class: CONFIG)
  selectedEdgeIds: [String!]! @state(class: CONFIG)
  selectedHandleIds: [String!]! @state(class: CONFIG)
  previewOffNodeIds: [String!]! @state(class: CONFIG)
  camera: CameraJson! @state(class: CONFIG)
  lodMode: String! @state(class: CONFIG)
  proximityDistance: Float! @state(class: CONFIG)
  gridVisible: Boolean! @state(class: CONFIG)
  gridSnapEnabled: Boolean! @state(class: CONFIG)
  gridFactor: Float! @state(class: CONFIG)
  catalogueSectionsJson: String! @state(class: CONFIG)
  automationEnabledJson: String! @state(class: CONFIG)
  contributionsJson: String! @state(class: CONFIG)
  generationJson: String! @state(class: CONFIG)
  locale: String! @state(class: CONFIG)
}

type CameraJson {
  x: Float!
  y: Float!
  zoom: Float!
}
