syntax = "proto3";
package semio.app.flow.flow;
message FlowConfig {
  // @state config
  repeated string selected_node_ids = 1;
  // @state config
  repeated string selected_edge_ids = 2;
  // @state config
  repeated string selected_handle_ids = 3;
  // @state config
  repeated string preview_off_node_ids = 4;
  // @state config
  CameraJson camera = 5;
  // @state config
  string lod_mode = 6;
  // @state config
  double proximity_distance = 7;
  // @state config
  bool grid_visible = 8;
  // @state config
  bool grid_snap_enabled = 9;
  // @state config
  double grid_factor = 10;
  // @state config
  string catalogue_sections_json = 11;
  // @state config
  string automation_enabled_json = 12;
  // @state config
  string contributions_json = 13;
  // @state config
  string generation_json = 14;
  // @state config
  string locale = 15;
}

message CameraJson {
  double x = 1;
  double y = 2;
  double zoom = 3;
}
