[package]
name = "flow_module_logic"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
crate-type = ["rlib", "cdylib"]
path = "lib.rs"

[dependencies]
flow_module_wasm = { path = "../wasm" }
neural_engine = { path = "../../../neural/engine" }
serde_json = "1.0.140"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen = "0.2.106"
