//! 🧪️ Paid native pages expose immutable bytes through the same original header and ledger authority.
use super::*;
fn now()->Option<u64>{Some(1)}
fn observed<T>(body:impl FnOnce()->T)->(T,(usize,usize)){let(value,heap)=semio_framework_trace::observe_heap_allocations_on_this_thread(body);(value,(heap.requested_bytes,heap.released_bytes))}
#[test]
fn original_job_paged_source_preserves_header_authority_bytes_and_zero_heap_borrows(){
 let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:17,maximum_capacity_bytes:8192,maximum_release_bytes:65536,maximum_depth:9};let metadata=RetainedCloneGrant{maximum_copy_bytes:0,..grant};let operation=OperationId(99931);let generation=Generation(8);
 let((cancel,birth),heap)=observed(||CancelToken::admit_root(metadata).unwrap().unwrap());assert_eq!(heap,(birth.retained_capacity_bytes,birth.released_bytes));assert_eq!(birth.copied_bytes,0);let mut born=heap.0;let mut released=0;
 let((mut authority,birth),heap)=observed(||JobPayloadAuthority::admit(operation,generation,metadata).unwrap().unwrap());assert_eq!(heap,(birth.retained_capacity_bytes,birth.released_bytes));assert_eq!(birth.copied_bytes,0);born+=heap.0;
 let mut builder=RetainedPayloadBuilder::new(JobPayloadStream::Preview);let mut sequence=0;
 while !builder.is_initialized(){let mut receipt=Default::default();let mut cx=StepContext::with_payload_authority(operation,generation,StepBudget::new(1,2,metadata),&cancel,now,&mut sequence,&mut receipt,&authority).unwrap();let(_,heap)=observed(||builder.advance_initialization(&mut cx).unwrap());assert_eq!(heap,(0,0));assert_eq!(cx.retained_progress(),RetainedCloneProgress{copied_items:1,..Default::default()});}
 for part in [&[0,1,2][..],&[3,4][..],&[5,6,7,8][..]]{let page_grant=RetainedCloneGrant{maximum_capacity_bytes:part.len(),..grant};let mut cursor=0;while cursor<part.len(){let mut receipt=Default::default();let mut cx=StepContext::with_payload_authority(operation,generation,StepBudget::new(1,2,page_grant),&cancel,now,&mut sequence,&mut receipt,&authority).unwrap();let(_,heap)=observed(||builder.append_original(&mut cx,part,&mut cursor).unwrap());let progress=cx.retained_progress();assert!(progress.fits(page_grant));assert_eq!(heap,(progress.retained_capacity_bytes,progress.released_bytes));if heap.0>0{assert_eq!(heap.0,part.len());assert_eq!(progress.copied_bytes,0);}born+=heap.0;}}
 let mut receipt=Default::default();let mut cx=StepContext::with_payload_authority(operation,generation,StepBudget::new(1,2,metadata),&cancel,now,&mut sequence,&mut receipt,&authority).unwrap();let(sealed,heap)=observed(||builder.seal(&mut cx).unwrap());assert!(sealed);assert_eq!(heap,(0,0));assert_eq!(cx.retained_progress().copied_bytes,0);drop(cx);
 let payload=builder.published().unwrap();assert_eq!(payload.page_count(),3);let identity=payload.original_wire_identity();assert_eq!(identity,(payload as*const _ as usize,9,Some((99931,8))));let page_pointers=[payload.page(0).unwrap().as_ptr(),payload.page(1).unwrap().as_ptr(),payload.page(2).unwrap().as_ptr()];
 let((),heap)=observed(||{for _ in 0..37{assert_eq!(payload.original_wire_identity(),identity);for index in 0..9{assert_eq!(payload.original_byte_at(index),Some(index as u8));}assert_eq!(payload.original_byte_at(9),None);assert_eq!(payload.original_byte_at(usize::MAX),None);for(index,pointer)in page_pointers.iter().enumerate(){assert_eq!(payload.page(index).unwrap().as_ptr(),*pointer);}}});assert_eq!(heap,(0,0));
 while !builder.terminal_is_empty(){let(step,heap)=observed(||builder.close_step_granted(metadata).unwrap());assert!(step.progress().fits(metadata));assert_eq!(step.progress().copied_bytes,0);assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));released+=heap.1;}
 let(step,heap)=observed(||authority.close_step(metadata).unwrap());assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));assert_eq!(step.progress().copied_bytes,0);released+=heap.1;
 let mut cancel=semio_framework_async::CancelTokenRetirement::from_token(cancel);while !cancel.terminal_is_empty(){let(step,heap)=observed(||cancel.close_step(metadata).unwrap());assert_eq!(heap,(step.progress().retained_capacity_bytes,step.progress().released_bytes));assert_eq!(step.progress().copied_bytes,0);released+=heap.1;}assert_eq!(born,released);let((),heap)=observed(||{drop(builder);drop(authority);drop(cancel);});assert_eq!(heap,(0,0));println!("[DEBUG] original paged Job source pages3/2/4 bytes9 nativeHeader operation99931 generation8 repeatedRead37 heap0 metadata0 bornReleased={born} terminalDrop0");
}
