import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {closeSync,existsSync,fsyncSync,mkdirSync,openSync,readFileSync,writeFileSync,writeSync} from "node:fs";
import {dirname,join,resolve} from "node:path";
const ticket=dirname(import.meta.dir),root=resolve(ticket,"../../../../../../.."),[command,epoch="1"]=process.argv.slice(2),sha=(s:string)=>createHash("sha256").update(s).digest("hex"),out=join(ticket,"🗑️generated/browser-storage-source-law"),engine="🧰️framework/🛍️products/💻️os/🔨️modules/📺️renderer/🧑‍🎨engine",target=engine+"/🎯️targets/🧊️wgpu",path=engine+"/🧱️elements/🐚️Shell/🧪️tests/🗄️browser-prefs-persistence/🦀️.rs",read=(path:string)=>readFileSync(join(root,path),"utf8");mkdirSync(out,{recursive:true});
if(command==="stage"){
 const dest=join(out,"source-"+epoch+".json");assert.equal(existsSync(dest),false);const before=read(path),from=[
'    let embedded = wgpu_target_source("🎬️renderer-boot/🟦️.ts");',
'    assert!(embedded.contains("semioWgpuSetHostStorage?.(JSON.stringify(readWgpuHostStorageSnapshot(window)))"), "the embeddable door runs ON the page and seeds the same store itself");',
].join("\n"),to=[
'    let embedded = wgpu_target_source("🎬️renderer-boot/🟦️.ts");',
'    assert!(embedded.contains("import { mountWgpuBrowserHost, type WgpuBrowserMount, type WgpuBootProgress } from \\"../🌐️browser-host/🟦️.ts\\";"), "the embeddable door imports the same canonical page host");',
'    assert!(embedded.contains("return mountWgpuBrowserHost(root, { descriptor, locale, mountId: rootId,"), "the embeddable door hands its actual mount and descriptor to that host");',
'    assert!(host.contains("storage: hostStorage()"), "the shared host seeds the embeddable worker from the same page census");',
].join("\n");assert.equal(epoch,"2");assert.equal(before.split(from).length-1,1);const after=before.replace(from,()=>to);assert.equal(after.replace(to,()=>from),before);
 const contexts=["🚪️host-io/🟦️.ts","🎞️frame-worker/🟦️.ts","🚀️browser-boot/🟦️.ts","🌐️browser-host/🟦️.ts","🎬️renderer-boot/🟦️.ts","🧭️boot-descriptor/🟦️.ts"].map(relative=>({path:target+"/"+relative,source:read(target+"/"+relative),sha256:sha(read(target+"/"+relative))}));
 assert.ok(contexts[2]!.source.includes('import { mountWgpuBrowserHost } from "../🌐️browser-host/🟦️.ts";'));assert.ok(contexts[2]!.source.includes('await mountWgpuBrowserHost(root, { descriptor, locale, mountId: "root", pageBindings: true });'));assert.ok(contexts[3]!.source.includes("return readWgpuHostStorageSnapshot(window);"));assert.ok(contexts[3]!.source.includes("storage: hostStorage()"));assert.ok(contexts[3]!.source.includes('window.addEventListener("storage", republishHostStorage);'));assert.ok(contexts[3]!.source.includes('window.removeEventListener("storage", republishHostStorage);'));
 const baselinePath=join(ticket,"🗑️generated/product-wgpu-native-whole/epoch-7/terminal-1.json"),baseline=readFileSync(baselinePath,"utf8");for(const row of contexts)assert.ok(read(row.path)===row.source,row.path);assert.ok(read(path)===before);writeFileSync(dest,JSON.stringify({producer:{path:import.meta.path,source:readFileSync(import.meta.path,"utf8")},pairs:[{path,before,after,beforeHash:sha(before),afterHash:sha(after)}],contexts,baseline:{path:baselinePath,source:baseline,sha256:sha(baseline)},originalAssertionsRetained:11,addedBindingAssertions:2,sourceWrites:0,nativeExecuted:false,wholeRootAccepted:false,scope:"The source law follows both existing page doors into the same canonical browser host. The embedded door now imports and mounts the host, whose original census read and worker boot storage assertions remain exact. All other host-I/O, worker-before-boot, trunk, tab-event and store assertions remain byte-exact. The original obsolete inline embedded seeding assertion receives equivalent mount and host seeding checks; runtime source bodies remain unchanged. Product7 original embedded-source failure remains retained."}));console.log("[DEBUG] Browser census source law staged one exact owner cut with six page/worker/binding frames");
}else if(command==="publish"){
 const inputs=["source-"+epoch+".json","independent-source-"+epoch+".json"].map(file=>{const path=join(out,file),source=readFileSync(path,"utf8");return{path,source,value:JSON.parse(source)};}),source=inputs[0]!.value;assert.equal(inputs[1]!.value.ready,true);assert.equal(inputs[1]!.value.sourceHash,sha(inputs[0]!.source));const dest=join(out,"publication-"+epoch);assert.equal(existsSync(dest),false);for(const row of source.pairs)assert.ok(read(row.path)===row.before,row.path);for(const row of source.contexts)assert.ok(read(row.path)===row.source,row.path);mkdirSync(dest,{recursive:true});const raw=JSON.stringify({inputs:inputs.map(({value,...row})=>row),pairs:source.pairs,contexts:source.contexts,producer:{path:import.meta.path,source:readFileSync(import.meta.path,"utf8")},atomicBatchClaimed:false,nativeExecuted:false,wholeRootAccepted:false}),persist=(path:string,text:string):void=>{const fd=openSync(path,"wx");try{writeSync(fd,text);fsyncSync(fd);}finally{closeSync(fd);}};persist(join(dest,"plan.json"),raw);const journal=join(dest,"intent.jsonl");persist(journal,JSON.stringify({phase:"prepared",planHash:sha(raw),sourceWrites:0})+"\n");const fd=openSync(journal,"a");let sourceWrites=0;try{for(const row of source.pairs){for(const input of inputs)assert.ok(readFileSync(input.path,"utf8")===input.source,input.path);assert.ok(read(row.path)===row.before,row.path);writeSync(fd,JSON.stringify({phase:"intent",path:row.path,beforeHash:row.beforeHash,afterHash:row.afterHash,sourceWrites})+"\n");fsyncSync(fd);writeFileSync(join(root,row.path),row.after);assert.ok(read(row.path)===row.after,row.path);sourceWrites++;writeSync(fd,JSON.stringify({phase:"written",path:row.path,sourceWrites})+"\n");fsyncSync(fd);}for(const row of source.contexts)assert.ok(read(row.path)===row.source,row.path);writeSync(fd,JSON.stringify({phase:"completed",sourceWrites})+"\n");fsyncSync(fd);persist(join(dest,"terminal.json"),JSON.stringify({sourceWrites,planHash:sha(raw),journalHash:sha(readFileSync(journal,"utf8")),exactPostimages:source.pairs.length,retainedFrames:source.contexts.length,nativeExecuted:false,wholeRootAccepted:false,atomicBatchClaimed:false}));console.log("[DEBUG] Browser census owning source law published");}finally{closeSync(fd);}
}else throw Error("stage|publish");

