syntax = "proto3";
package semio.app.block.3d.config;
message Block3dConfig {
  // @state local-ui
  repeated string selected_ids = 1;
  // @state local-ui
  optional string active_representation_id = 2;
  // @state local-ui
  repeated string wanted_tags = 3;
  // @state local-ui
  string locale = 4;
  // @state local-ui
  repeated Block3dWindowView windows = 5;
  // @state local-ui
  optional string brush_vortex_kind_id = 6;
  // @state local-ui
  double brush_radius = 7;
  // @state local-ui
  bool brush_flip = 8;
  // @state local-ui
  optional Block3dBrushPreview brush_preview = 9;
  // @state local-ui
  optional BlockCamera3d camera = 10;
  // @state local-ui
  optional string hovered_vortex_full_id = 11;
}

message Block3dWindowView {
  bool _placeholder = 1;
}

message Block3dBrushPreview {
  bool _placeholder = 1;
}

message BlockCamera3d {
  bool _placeholder = 1;
}
