[package]
name = "remodel_geo"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
remodel_sfm = { path = "../../sfm/rs" }
remodel_dense = { path = "../../dense/rs" }
remodel_mesh = { path = "../../mesh/rs" }
remodel_image = { path = "../../image/rs" }
mathematical_algebra = { path = "../../../mathematical/algebra/rs" }
mathematical_lie = { path = "../../../mathematical/lie/rs" }
mathematical_spatial = { path = "../../../mathematical/spatial/rs" }
