//! 🧩️ Explicit nine-kind CommonMark inline records with exclusive ordered child identities.
use super::*;
#[derive(dsl::DslScalar)]
enum Kind{Text,Emphasis,Strong,Code,Link,Image,SoftBreak,HardBreak,HtmlInline}
#[derive(dsl::DslRecord)]
pub(super) struct Inline{kind:Kind,text:Option<String>,literal:Option<String>,url:Option<String>,title:Option<String>,alt:Option<String>,raw:Option<String>,inlines:Vec<u64>}
pub(super) fn project<'a>(value:&'a MdInline,pending:&mut std::collections::VecDeque<&'a MdInline>,next:&mut u64)->Inline{let mut row=Inline{kind:Kind::SoftBreak,text:None,literal:None,url:None,title:None,alt:None,raw:None,inlines:Vec::new()};match value{
 MdInline::Text{text}=>{row.kind=Kind::Text;row.text=Some(text.clone())},MdInline::Emphasis{inlines}=>{row.kind=Kind::Emphasis;row.inlines=indices(inlines,pending,next)},MdInline::Strong{inlines}=>{row.kind=Kind::Strong;row.inlines=indices(inlines,pending,next)},MdInline::Code{literal}=>{row.kind=Kind::Code;row.literal=Some(literal.clone())},MdInline::Link{text,url,title}=>{row.kind=Kind::Link;row.inlines=indices(text,pending,next);row.url=Some(url.clone());row.title=title.clone()},MdInline::Image{alt,url,title}=>{row.kind=Kind::Image;row.alt=Some(alt.clone());row.url=Some(url.clone());row.title=title.clone()},MdInline::SoftBreak=>{},MdInline::HardBreak=>row.kind=Kind::HardBreak,MdInline::HtmlInline{raw}=>{row.kind=Kind::HtmlInline;row.raw=Some(raw.clone())}}row}
pub(super) fn reconstruct(rows:Vec<Inline>)->Result<Vec<Option<MdInline>>,String>{let mut values=(0..rows.len()).map(|_|None).collect::<Vec<_>>();for(index,row)in rows.into_iter().enumerate().rev(){let Inline{kind,mut text,mut literal,mut url,mut title,mut alt,mut raw,mut inlines}=row;let inline=match kind{
 Kind::Text=>MdInline::Text{text:text.take().ok_or("CommonMark text is missing")?},Kind::Emphasis=>MdInline::Emphasis{inlines:children(&mut values,Some(index),std::mem::take(&mut inlines))?},Kind::Strong=>MdInline::Strong{inlines:children(&mut values,Some(index),std::mem::take(&mut inlines))?},Kind::Code=>MdInline::Code{literal:literal.take().ok_or("CommonMark inline code literal is missing")?},Kind::Link=>MdInline::Link{text:children(&mut values,Some(index),std::mem::take(&mut inlines))?,url:url.take().ok_or("CommonMark link URL is missing")?,title:title.take()},Kind::Image=>MdInline::Image{alt:alt.take().ok_or("CommonMark image alternative text is missing")?,url:url.take().ok_or("CommonMark image URL is missing")?,title:title.take()},Kind::SoftBreak=>MdInline::SoftBreak,Kind::HardBreak=>MdInline::HardBreak,Kind::HtmlInline=>MdInline::HtmlInline{raw:raw.take().ok_or("CommonMark inline HTML raw text is missing")?}};
 if text.is_some()||literal.is_some()||url.is_some()||title.is_some()||alt.is_some()||raw.is_some()||!inlines.is_empty(){return Err("CommonMark inline contains unrelated variant fields".into())}values[index]=Some(inline)}Ok(values)}
