//! 🧱️ Nonuniform grid, exact mesh buffers, tile permissions and durable child targets.
use crate::standards::v1::subsets::any::schema::snapshot::{Grid3dSnapshot,Grid3dTile,Grid3dTileMedia,Grid3dMesh,Grid3dColor,Grid3dRule,Grid3dDirection,Grid3dPinnedCell,Grid3dCell};
use semio_framework_os_kernel::{ArtifactSqliteSnapshot,sqlite_snapshot::{SqliteDatabase,SqliteSnapshotControl,SqliteSnapshotPhase,SnapshotEncoding,validate_sqlite_database_schema,artifact::{Cell,RowWriter,Reconstruction,FloatColumn,FloatRow}}};
use std::collections::{BTreeMap,BTreeSet};
use semio_framework_value::ValueError;
fn invalid(message:impl Into<String>)->ValueError{ValueError::new(semio_framework_value::ValueRefusalKind::InvalidValue,message)}
pub(crate)fn number(n:usize)->Result<i64,ValueError>{i64::try_from(n).map_err(|_|semio_framework_value::ValueError::new(semio_framework_value::ValueRefusalKind::WorkLimit,"grid3d ordinal overflow"))}
pub(crate)fn columns(table:&str)->&'static[FloatColumn]{match table{"wfc_grid3d_cell_size"=>&[FloatColumn::Binary64(4)],"wfc_grid3d_tile"=>&[FloatColumn::Binary64(5)],"wfc_grid3d_position"=>&[FloatColumn::Binary64(3)],_=>&[]}}
fn identity(r:FloatRow<'_>,n:usize)->Result<(),ValueError>{if r.rowid<=0||r.integer(0)?!=r.rowid||r.values.len()!=n{return Err(invalid("grid3d entity identity or column count differs"))}Ok(())}
fn word(r:FloatRow<'_>,i:usize)->Result<u32,ValueError>{u32::try_from(r.integer(i)?).map_err(|_|invalid("grid3d unsigned32 differs"))}
fn flag(r:FloatRow<'_>,i:usize)->Result<bool,ValueError>{match r.integer(i)?{0=>Ok(false),1=>Ok(true),_=>Err(invalid("grid3d boolean differs"))}}
fn rows<'a>(d:&'a SqliteDatabase,t:&str,c:&mut SqliteSnapshotControl<'_>)->Result<Vec<FloatRow<'a>>,ValueError>{let mut result=Vec::new();let mut ids=BTreeSet::new();for(i,r)in d.table(t)?.rows.iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}let r=FloatRow::new(r,columns(t))?;if !ids.insert(r.rowid){return Err(invalid("duplicate grid3d row identity"))}result.push(r);}Ok(result)}
fn ordered<'a>(mut rows:Vec<FloatRow<'a>>,ordinal:usize)->Result<Vec<FloatRow<'a>>,ValueError>{rows.sort_by_key(|r|r.integer(ordinal).unwrap_or(-1));for(i,r)in rows.iter().enumerate(){if r.integer(ordinal)?!=number(i)?{return Err(invalid("grid3d ordinals must be contiguous"))}}Ok(rows)}
fn groups<'a>(d:&'a SqliteDatabase,t:&str,n:usize,owners:&BTreeSet<i64>,c:&mut SqliteSnapshotControl<'_>)->Result<BTreeMap<i64,Vec<FloatRow<'a>>>,ValueError>{let mut map=BTreeMap::<i64,Vec<FloatRow<'a>>>::new();for(i,r)in rows(d,t,c)?.into_iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}identity(r,n)?;let owner=r.integer(1)?;if !owners.contains(&owner){return Err(invalid("grid3d relationship has unknown owner"))}map.entry(owner).or_default().push(r);}Ok(map)}
fn parse_direction(s:&str)->Result<Grid3dDirection,ValueError>{match s{"LEFT"=>Ok(Grid3dDirection::Left),"RIGHT"=>Ok(Grid3dDirection::Right),"FRONT"=>Ok(Grid3dDirection::Front),"BACK"=>Ok(Grid3dDirection::Back),"BOTTOM"=>Ok(Grid3dDirection::Bottom),"TOP"=>Ok(Grid3dDirection::Top),_=>Err(invalid("grid3d direction differs"))}}
pub(crate)fn authored_schema(c:&SqliteSnapshotControl<'_>)->Result<(),ValueError>{if Grid3dSnapshot::SQLITE_SCHEMA.len()>c.limits().max_schema_bytes{return Err(invalid("grid3d authored schema limit exceeded"))}Ok(())}
fn decimal(mut value:u64,buffer:&mut[u8;20])->&str{let mut start=buffer.len();loop{start-=1;buffer[start]=b'0'+(value%10)as u8;value/=10;if value==0{break}}std::str::from_utf8(&buffer[start..]).expect("decimal digits")}
pub(crate)fn write_rows(value:&Grid3dSnapshot,p:&mut RowWriter<'_,'_>)->Result<(),ValueError>{let mut seed=[0u8;20];
 let mut total=1usize;for n in [value.cell_sizes_x.len(),value.cell_sizes_y.len(),value.cell_sizes_z.len(),value.tiles.len(),value.rules.len(),value.pinned.len(),value.masked.len()]{total=total.checked_add(n).ok_or_else(||semio_framework_value::ValueError::new(semio_framework_value::ValueRefusalKind::WorkLimit,"grid3d entity count overflow"))?;p.check_rows(total)?;}for t in &value.tiles{total=total.checked_add(match &t.media{Grid3dTileMedia::Mesh{mesh}=>1usize.checked_add(mesh.positions.len()).and_then(|n|n.checked_add(mesh.indices.len())).and_then(|n|n.checked_add(usize::from(mesh.color.is_some()))).ok_or_else(||semio_framework_value::ValueError::new(semio_framework_value::ValueRefusalKind::WorkLimit,"grid3d mesh entity count overflow"))?,Grid3dTileMedia::MeshChild{..}=>1}).ok_or_else(||semio_framework_value::ValueError::new(semio_framework_value::ValueRefusalKind::WorkLimit,"grid3d entity count overflow"))?;p.check_rows(total)?;p.checkpoint()?;}
 p.insert_key("wfc_grid3d_document",1,&[Cell::Text(&value.schema),Cell::Text(decimal(value.seed,&mut seed)),Cell::Integer(i64::from(value.width)),Cell::Integer(i64::from(value.height)),Cell::Integer(i64::from(value.depth)),Cell::Integer(i64::from(value.periodic_x)),Cell::Integer(i64::from(value.periodic_y)),Cell::Integer(i64::from(value.periodic_z))])?;
 for(axis,sizes)in [("x",&value.cell_sizes_x),("y",&value.cell_sizes_y),("z",&value.cell_sizes_z)]{for(i,size)in sizes.iter().enumerate(){p.insert_float("wfc_grid3d_cell_size",&[Cell::Integer(1),Cell::Text(axis),Cell::Integer(number(i)?),Cell::Real(*size)],columns("wfc_grid3d_cell_size"))?;}}
 for(i,t)in value.tiles.iter().enumerate(){let kind=match &t.media{Grid3dTileMedia::Mesh{..}=>"mesh",Grid3dTileMedia::MeshChild{..}=>"mesh_child"};let id=p.insert_float("wfc_grid3d_tile",&[Cell::Integer(1),Cell::Integer(number(i)?),Cell::Text(&t.id),t.label.as_deref().map_or(Cell::Null,Cell::Text),Cell::Real(t.weight),Cell::Text(kind)],columns("wfc_grid3d_tile"))?;match &t.media{Grid3dTileMedia::Mesh{mesh}=>{p.insert_key("wfc_grid3d_mesh",id,&[])?;for(i,v)in mesh.positions.iter().enumerate(){p.insert_float("wfc_grid3d_position",&[Cell::Integer(id),Cell::Integer(number(i)?),Cell::Real(*v)],columns("wfc_grid3d_position"))?;}for(i,v)in mesh.indices.iter().enumerate(){p.insert("wfc_grid3d_index",&[Cell::Integer(id),Cell::Integer(number(i)?),Cell::Integer(i64::from(*v))])?;}if let Some(color)=mesh.color{p.insert_key("wfc_grid3d_color",id,&[Cell::Integer(i64::from(color.r)),Cell::Integer(i64::from(color.g)),Cell::Integer(i64::from(color.b)),Cell::Integer(i64::from(color.a))])?;}},Grid3dTileMedia::MeshChild{child}=>{let r=&child.target;p.insert_key("wfc_grid3d_mesh_child",id,&[Cell::Text(&child.child_id),Cell::Text(&r.artifact_id),Cell::Text(&r.dialect.artifact_kind),Cell::Text(&r.dialect.standard),Cell::Text(&r.dialect.subset)])?;}}}
 for(i,r)in value.rules.iter().enumerate(){p.insert("wfc_grid3d_rule",&[Cell::Integer(1),Cell::Integer(number(i)?),Cell::Text(&r.id),Cell::Text(&r.tile_a_id),Cell::Text(&r.tile_b_id),Cell::Text(r.direction.label()),Cell::Integer(i64::from(r.allowed))])?;}
 for(i,r)in value.pinned.iter().enumerate(){p.insert("wfc_grid3d_pin",&[Cell::Integer(1),Cell::Integer(number(i)?),Cell::Integer(i64::from(r.x)),Cell::Integer(i64::from(r.y)),Cell::Integer(i64::from(r.z)),Cell::Text(&r.tile_id)])?;}
 for(i,r)in value.masked.iter().enumerate(){p.insert("wfc_grid3d_mask",&[Cell::Integer(1),Cell::Integer(number(i)?),Cell::Integer(i64::from(r.x)),Cell::Integer(i64::from(r.y)),Cell::Integer(i64::from(r.z))])?;}
 Ok(())}
pub(crate)fn semantic(value:&Grid3dSnapshot,phase:SqliteSnapshotPhase,c:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{authored_schema(c)?;let mut p=RowWriter::borrowed(c,phase)?;write_rows(value,&mut p)?;p.finish_borrowed()}
impl ArtifactSqliteSnapshot for Grid3dSnapshot{
const SQLITE_SCHEMA:&'static str=include_str!("🗄️.sql");
fn decode_sqlite_snapshot_native(payload:&store::io_schema::IoPayload,c:&mut SqliteSnapshotControl<'_>)->Result<Self,ValueError>{crate::standards::v1::subsets::any::io::sqlite::snapshot::controlled_native::decode_sqlite_snapshot_native(payload,c)}
fn encode_sqlite_snapshot_native(&self,encoding:SnapshotEncoding,c:&mut SqliteSnapshotControl<'_>)->Result<store::io_schema::IoPayload,ValueError>{crate::standards::v1::subsets::any::io::sqlite::snapshot::controlled_native::encode_sqlite_snapshot_native(self,encoding,c)}
fn to_sqlite_database(&self,c:&mut SqliteSnapshotControl<'_>)->Result<SqliteDatabase,ValueError>{let mut p=RowWriter::new(Self::SQLITE_SCHEMA,c)?;write_rows(self,&mut p)?;p.finish()}
fn from_sqlite_database(d:&SqliteDatabase,c:&mut SqliteSnapshotControl<'_>)->Result<Self,ValueError>{
 validate_sqlite_database_schema(d,Self::SQLITE_SCHEMA,c.limits())?;c.check_database(d,SqliteSnapshotPhase::ReconstructSnapshot)?;let doc=FloatRow::new(d.table("wfc_grid3d_document")?.single_row()?,&[])?;identity(doc,9)?;if doc.rowid!=1{return Err(invalid("grid3d root identity must be one"))}let seed=doc.text(2)?.parse::<u64>().map_err(|_|invalid("grid3d seed exceeds unsigned64"))?;if seed.to_string()!=doc.text(2)?{return Err(invalid("grid3d seed requires canonical decimal"))}
 let root=BTreeSet::from([1]);let tile_rows=ordered(groups(d,"wfc_grid3d_tile",7,&root,c)?.remove(&1).unwrap_or_default(),2)?;let mut mesh_ids=BTreeSet::new();let mut child_ids=BTreeSet::new();for(i,r)in tile_rows.iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}r.text(3)?;match r.text(6)?{"mesh"=>{mesh_ids.insert(r.rowid);},"mesh_child"=>{child_ids.insert(r.rowid);},_=>return Err(invalid("grid3d tile media kind differs"))}}
 let meshes=rows(d,"wfc_grid3d_mesh",c)?;let mut seen=BTreeSet::new();for(i,r)in meshes.into_iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}identity(r,1)?;if !mesh_ids.contains(&r.rowid){return Err(invalid("grid3d mesh has wrong tile kind or owner"))}seen.insert(r.rowid);}if seen!=mesh_ids{return Err(invalid("grid3d mesh ownership is incomplete"))}
 let mut positions=groups(d,"wfc_grid3d_position",4,&mesh_ids,c)?;let mut indices=groups(d,"wfc_grid3d_index",4,&mesh_ids,c)?;let mut colors=BTreeMap::new();for(i,r)in rows(d,"wfc_grid3d_color",c)?.into_iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}identity(r,5)?;if !mesh_ids.contains(&r.rowid){return Err(invalid("grid3d color has unknown mesh"))}colors.insert(r.rowid,r);}
 let mut children=BTreeMap::new();for(i,r)in rows(d,"wfc_grid3d_mesh_child",c)?.into_iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}identity(r,6)?;if !child_ids.contains(&r.rowid){return Err(invalid("grid3d child has wrong tile kind or owner"))}children.insert(r.rowid,r);}if children.len()!=child_ids.len(){return Err(invalid("grid3d child ownership is incomplete"))}
 let mut axes=BTreeMap::<&str,Vec<FloatRow<'_>>>::new();for(i,r)in rows(d,"wfc_grid3d_cell_size",c)?.into_iter().enumerate(){if i%256==0{c.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,i,0)?;}identity(r,5)?;if r.integer(1)?!=1||!matches!(r.text(2)?,"x"|"y"|"z"){return Err(invalid("grid3d cell size owner or axis differs"))}axes.entry(r.text(2)?).or_default().push(r);}
 let rule_rows=ordered(groups(d,"wfc_grid3d_rule",8,&root,c)?.remove(&1).unwrap_or_default(),2)?;let pin_rows=ordered(groups(d,"wfc_grid3d_pin",7,&root,c)?.remove(&1).unwrap_or_default(),2)?;let mask_rows=ordered(groups(d,"wfc_grid3d_mask",6,&root,c)?.remove(&1).unwrap_or_default(),2)?;
 let mut owned=Reconstruction::new(c)?;let schema=owned.text(doc.text(1)?)?;let mut cell_sizes=[Vec::new(),Vec::new(),Vec::new()];for(i,axis)in ["x","y","z"].iter().enumerate(){for r in ordered(axes.remove(*axis).unwrap_or_default(),3)?{owned.scalar()?;cell_sizes[i].push(r.real(4)?);}}
 let mut tiles=Vec::new();for r in tile_rows{owned.scalar()?;let media=match r.text(6)?{"mesh"=>{let mut native_positions=Vec::new();for v in ordered(positions.remove(&r.rowid).unwrap_or_default(),2)?{owned.scalar()?;native_positions.push(v.real(3)?);}let mut native_indices=Vec::new();for v in ordered(indices.remove(&r.rowid).unwrap_or_default(),2)?{owned.scalar()?;native_indices.push(word(v,3)?);}let color=match colors.remove(&r.rowid){None=>None,Some(v)=>{for _ in 0..4{owned.scalar()?;}Some(Grid3dColor{r:word(v,1)?,g:word(v,2)?,b:word(v,3)?,a:word(v,4)?})}};Grid3dTileMedia::Mesh{mesh:Grid3dMesh{positions:native_positions,indices:native_indices,color}}},"mesh_child"=>{let v=children.remove(&r.rowid).ok_or_else(||invalid("grid3d child absent"))?;let target=semio_framework_artifact_reference::ArtifactRef{artifact_id:owned.text(v.text(2)?)?,dialect:semio_framework_artifact_reference::ArtifactDialect{artifact_kind:owned.text(v.text(3)?)?,standard:owned.text(v.text(4)?)?,subset:owned.text(v.text(5)?)?}};Grid3dTileMedia::MeshChild{child:store::ArtifactChild::new(owned.text(v.text(1)?)?,target)}},_=>unreachable!()};tiles.push(Grid3dTile{id:owned.text(r.text(3)?)?,label:r.optional_text(4)?.map(|s|owned.text(s)).transpose()?,weight:r.real(5)?,media});}
 let mut rules=Vec::new();for r in rule_rows{owned.scalar()?;rules.push(Grid3dRule{id:owned.text(r.text(3)?)?,tile_a_id:owned.text(r.text(4)?)?,tile_b_id:owned.text(r.text(5)?)?,direction:parse_direction(r.text(6)?)?,allowed:flag(r,7)?});}
 let mut pinned=Vec::new();for r in pin_rows{for _ in 0..3{owned.scalar()?;}pinned.push(Grid3dPinnedCell{x:word(r,3)?,y:word(r,4)?,z:word(r,5)?,tile_id:owned.text(r.text(6)?)?});}
 let mut masked=Vec::new();for r in mask_rows{for _ in 0..3{owned.scalar()?;}masked.push(Grid3dCell{x:word(r,3)?,y:word(r,4)?,z:word(r,5)?});}for _ in 0..7{owned.scalar()?;}owned.checkpoint()?;let [cell_sizes_x,cell_sizes_y,cell_sizes_z]=cell_sizes;
 Ok(Self{schema,seed,width:word(doc,3)?,height:word(doc,4)?,depth:word(doc,5)?,periodic_x:flag(doc,6)?,periodic_y:flag(doc,7)?,periodic_z:flag(doc,8)?,cell_sizes_x,cell_sizes_y,cell_sizes_z,tiles,rules,pinned,masked})
}
fn preflight_sqlite_snapshot_encoding(&self,encoding:SnapshotEncoding,c:&mut SqliteSnapshotControl<'_>)->Result<(),ValueError>{semantic(self,SqliteSnapshotPhase::EncodeNative,c)?;let component=match encoding{SnapshotEncoding::Binary=>store::semio_format::Component::Pack,SnapshotEncoding::Text=>store::semio_format::Component::Dsl};let prefix=store::semio_format::declared_envelope_prefix_len(<Self as store::ArtifactDsl>::envelope_id(),component,1)?;if prefix>c.limits().max_file_bytes{return Err(invalid("grid3d declared native frame exceeds file allowance"))}Ok(())}
fn validate_sqlite_snapshot_subset(&self,dialect:&semio_framework_artifact_reference::ArtifactDialect,d:&SqliteDatabase,c:&mut SqliteSnapshotControl<'_>)->semio_framework_os_kernel::io_schema::IoResult<()>{c.checkpoint(SqliteSnapshotPhase::ProjectSnapshot,0,1).map_err(semio_framework_os_kernel::io_schema::IoError::from_value_error)?;if dialect.artifact_kind!="s.wfc.grid3d"||dialect.standard!="1"||dialect.subset!="*"{return Err(semio_framework_os_kernel::io_schema::IoError::from_value_error(invalid("grid3d dialect differs from its owned wildcard")))}if d.table("wfc_grid3d_document").map_err(semio_framework_os_kernel::io_schema::IoError::from_value_error)?.single_row().map_err(semio_framework_os_kernel::io_schema::IoError::from_value_error)?.text(1).map_err(semio_framework_os_kernel::io_schema::IoError::from_value_error)?!=self.schema{return Err(semio_framework_os_kernel::io_schema::IoError::from_value_error(invalid("grid3d projected schema differs")))}c.checkpoint(SqliteSnapshotPhase::ProjectSnapshot,1,1).map_err(semio_framework_os_kernel::io_schema::IoError::from_value_error)?;Ok(semio_framework_os_kernel::io_schema::IoOutcome::clean(()))}
}

#[cfg(test)]
#[path = "🧪️tests/🦀️.rs"]
mod tests;


#[path = "🛬️native/🦀️.rs"]
pub(crate) mod controlled_native;
