type RewriteConfig {
  selectedNodeIds: [String!]! @state(class: CONFIG)
  beforePaneCamera: Camera! @state(class: CONFIG)
  reorganizeEpoch: Int! @state(class: CONFIG)
  activeHoverVar: String! @state(class: CONFIG)
  hoverEpoch: Int! @state(class: CONFIG)
  activeSelectVar: String! @state(class: CONFIG)
  selectEpoch: Int! @state(class: CONFIG)
  lodModeByWindow: [StringEntry!]! @state(class: CONFIG)
  locale: String! @state(class: CONFIG)
}

type StringEntry {
  key: String!
  value: String!
}

type Camera {
  x: Float!
  y: Float!
  zoom: Float!
}
