// SPDX-License-Identifier: AGPL-3.0-only
// Generated exclusively from the live Neo4j database — do not edit this file by hand.
// Refresh: `bun run generate` (see generate.neo4j.script.ts).
// technology: coda | database: coda | generated: 2026-05-15T10:09:28.442Z
//

