/** 🖼️ Full-width bitmap problem fixture and independent SQLite edits. */
import {fileURLToPath} from "node:url";
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import fixture from "../../🧫️fixtures/🪶️sqlite/🔣️.json";
import type {BitmapSnapshot} from "../../🟦️.ts";
import {WFC_BITMAP_SQLITE_SCHEMA,bitmapSnapshotToSqliteDatabase,bitmapSnapshotFromSqliteDatabase} from "../../🪶️sqlite/🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const input:BitmapSnapshot={schema:fixture.schema,seed:BigInt(fixture.seed),input:fixture.input,output:fixture.output,model:fixture.model,pinned:fixture.pinned};
test("bitmap all native widths and independent relational query/edit",async()=>{expect(WFC_BITMAP_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../../🪶️sqlite/🗄️.sql",import.meta.url)).text());const original=await bitmapSnapshotToSqliteDatabase(input);const db=Database.deserialize(await exportSqliteDatabase(original));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query("SELECT red,palette_indices_base64 FROM wfc_bitmap_palette JOIN wfc_bitmap_input ON document_id=wfc_bitmap_input.id ORDER BY ordinal").all()).toEqual([{red:4294967295,palette_indices_base64:"AAE="},{red:2,palette_indices_base64:"AAE="}]);expect(await bitmapSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE wfc_bitmap_pin SET x=7 WHERE ordinal=1").run();const edited=structuredClone(input);edited.pinned[1]!.x=7;expect(await bitmapSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(edited);}finally{db.close();}});
test("bitmap malformed relations and before-allocation control laws",async()=>{const db=await bitmapSnapshotToSqliteDatabase(input);for(const edit of [(d:any)=>d.tables[5].rows[0].values[1]=2n,(d:any)=>d.tables[2].rows[0].values[2]=9n,(d:any)=>d.tables[3].rows[0].values[3]=2n,(d:any)=>d.tables[0].rows[0].values[2]="01"]){const malformed=structuredClone(db);edit(malformed);expect(bitmapSnapshotFromSqliteDatabase(malformed)).rejects.toThrow();}expect(bitmapSnapshotToSqliteDatabase({...input,seed:18446744073709551616n})).rejects.toThrow();expect(bitmapSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();expect(bitmapSnapshotFromSqliteDatabase(db,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();c.abort();expect(bitmapSnapshotToSqliteDatabase(input,{signal:c.signal})).rejects.toThrow();const arbitrary={...input,input:{...input.input,palette:[],pixels:"invalid native scalar 🧬"},model:{...input.model,ground:null}};expect(await bitmapSnapshotFromSqliteDatabase(await bitmapSnapshotToSqliteDatabase(arbitrary))).toEqual(arbitrary);});

test("unlinked public artifact resolves its own exports in independent Bun runtime",async()=>{const root=fileURLToPath(new URL("../../../../../../../../📦️packages/🟦️typescript/",import.meta.url));const code="const artifact=await import(Bun.resolveSync(process.argv[1],process.argv[2]));if(typeof artifact.bitmapSnapshotToSqliteDatabase!==\"function\"||artifact.WFC_BITMAP_DOCUMENT_SCHEMA!==\"s.wfc.bitmap\")throw Error(\"public facet\");console.log(\"owned-package-self-reference\");";const child=Bun.spawn([process.execPath,"-e",code,"@semio-tech/wfc-bitmap",root],{stdout:"pipe",stderr:"pipe"});expect(await child.exited).toBe(0);expect(await new Response(child.stdout).text()).toBe("owned-package-self-reference\n");});
