syntax = "proto3";
package semio.s.gis.gismap;
import "✏️s/🔌️plugins/🌍️gis/🗿️artifacts/🗺️gismap/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/🛰️.proto";
import "✏️s/🔌️plugins/🌍️gis/🗿️artifacts/🗺️gismap/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/📍️feature/🛰️.proto";
message GisMapDiff { optional GisMapArtifact artifact = 1; optional GisMapFeaturesDelta positions = 2; optional GisMapFeaturesDelta routes = 3; optional GisMapFeaturesDelta regions = 4; }
message GisMapFeatureOrder { repeated string values = 1; }
message GisMapFeaturesDelta { repeated GisMapFeature added = 1; repeated string removed = 2; repeated GisMapFeaturePatchEntry patched = 3; optional GisMapFeatureOrder reordered = 4; }
message GisMapFeaturePatchEntry { string id = 1; GisMapFeaturePatch patch = 2; }
