syntax = "proto3";
package semio.s.trinity.rewriting.mutation;

import "google/protobuf/struct.proto";

message RewriteRuleLayoutPoint { double x = 1; double y = 2; }
message EditBeforeFixture { string new_before_fixture_json = 1; }
message EditLhs { string new_lhs_json = 1; }
message EditRhs { string new_rhs_json = 1; }
message ChangeParameterBinding { string key = 1; google.protobuf.Value new_value = 2; }
message RemoveParameterBinding { string key = 1; }
message ChangeRuleLayoutPoint { string key = 1; RewriteRuleLayoutPoint new_point = 2; }
message RemoveRuleLayoutPoint { string key = 1; }

message RewriteRuleMutation {
  oneof mutation {
    EditBeforeFixture edit_before_fixture = 1;
    EditLhs edit_lhs = 2;
    EditRhs edit_rhs = 3;
    ChangeParameterBinding change_parameter_binding = 4;
    RemoveParameterBinding remove_parameter_binding = 5;
    ChangeRuleLayoutPoint change_rule_layout_point = 6;
    RemoveRuleLayoutPoint remove_rule_layout_point = 7;
  }
}
