/** 🧫️ Handcrafted DWG five-style boundary values. */
import type { DwgComplexColor,DwgMaterial,DwgMaterialMap,DwgMlineStyle,DwgVisualStyle,DwgCellStyle,DwgTableStyle,DwgMLeaderStyle } from "../../../../🟦️.ts";
const finite={bits:0x3ff4000000000000n},zero={bits:0x8000000000000000n},nan={bits:0x7ff0000000000001n},infinity={bits:0xfff0000000000000n};
const color:DwgComplexColor={index:65535,value:{kind:"byColor",red:0,green:255,blue:17},name:"",bookName:undefined};
function map(projection:DwgMaterialMap["projection"],tiling:DwgMaterialMap["tiling"],source:DwgMaterialMap["source"]):DwgMaterialMap{return{blendFactor:nan,projection,tiling,source,scaleToEntity:false,useCurrentBlockTransform:true,transform:[zero,infinity,finite,nan]};}
const material:DwgMaterial={name:"material",description:"typed",ambient:{factor:zero,overrideRgb:0},diffuse:{factor:nan,overrideRgb:4294967295},specular:{factor:infinity,overrideRgb:undefined},diffuseMap:map("inherit","inherit","none"),specularMap:map("planar","tile","currentScene"),reflectionMap:map("box","crop","none"),opacityMap:map("cylinder","clamp","currentScene"),bumpMap:map("sphere","mirror","none"),refractionMap:map("inherit","mirror","none"),specularGloss:nan,opacity:zero,refractionIndex:infinity,translucence:finite,selfIllumination:nan,reflectivity:zero,enabledChannels:{diffuse:true,specular:false,reflection:true,opacity:false,bump:true,refraction:false}};
const mline:DwgMlineStyle={name:"mline",description:"typed",fillEnabled:false,displayMiters:true,startCaps:{square:true,innerArcs:false,roundOuterArcs:true},endCaps:{square:false,innerArcs:true,roundOuterArcs:false},fillColor:color,startAngle:nan,endAngle:zero,elements:[{offset:infinity,color,linetype:"byLayer"},{offset:zero,color,linetype:"byBlock"},{offset:finite,color,linetype:"continuous"}]};
const visual:DwgVisualStyle={description:"style",styleType:4294967295,extensionLightingModel:65535,internalOnly:true,properties:{faceLightingModel:{value:4294967295,operation:"inherit"},faceLightingQuality:{value:1,operation:"set"},faceColorMode:{value:2,operation:"disable"},faceModifiers:{value:65535,operation:"enable"},faceOpacity:{value:nan,operation:"inherit"},faceSpecularAmount:{value:zero,operation:"set"},faceMonochromeColor:{value:color,operation:"disable"},edgeModel:{value:3,operation:"enable"},edgeStyles:{value:4,operation:"inherit"},edgeIntersectionColor:{value:color,operation:"set"},edgeObscuredColor:{value:color,operation:"disable"},edgeObscuredLinePattern:{value:5,operation:"enable"},edgeIntersectionLinePattern:{value:6,operation:"inherit"},edgeCreaseAngle:{value:infinity,operation:"set"},edgeModifiers:{value:7,operation:"disable"},edgeColor:{value:color,operation:"enable"},edgeOpacity:{value:finite,operation:"inherit"},edgeWidth:{value:8,operation:"set"},edgeOverhang:{value:9,operation:"disable"},edgeJitter:{value:10,operation:"enable"},edgeSilhouetteColor:{value:color,operation:"inherit"},edgeSilhouetteWidth:{value:11,operation:"set"},edgeHaloGap:{value:12,operation:"disable"},edgeIsolines:{value:13,operation:"enable"},hiddenEdgePrecision:{value:false,operation:"inherit"},displaySettings:{value:14,operation:"set"},displayBrightness:{value:nan,operation:"disable"},displayShadowType:{value:15,operation:"enable"}}};
const border={overrideFlags:4294967295,borderType:0,color,lineweight:-2147483648,linetypeHandle:0n,visible:4294967295,doubleLineSpacing:nan};
const cell:DwgCellStyle={propertyOverrideFlags:4294967295,mergeFlags:0,backgroundColor:color,contentLayout:4294967295,contentFormat:{propertyOverrideFlags:0,propertyFlags:4294967295,valueDataType:0,valueUnitType:4294967295,valueFormatString:"\0",rotation:nan,blockScale:zero,alignment:4294967295,contentColor:color,textStyleHandle:undefined,textHeight:infinity},margins:{vertical:nan,horizontal:zero,bottom:infinity,right:finite,horizontalSpacing:{bits:0x4019000000000000n},verticalSpacing:nan},borders:{top:border,right:{...border,linetypeHandle:undefined}}};
const table:DwgTableStyle={description:"roles",bitFlags:4294967295,templateStyleHandle:0n,table:cell,title:cell,header:cell,data:cell};
const leader:DwgMLeaderStyle={contentType:"block",drawOrder:"contentFirst",leaderOrder:"tailFirst",maximumSegmentPoints:4294967295,firstSegmentAngle:nan,secondSegmentAngle:zero,leader:{kind:"spline",color,linetypeStyleHandle:18446744073709551615n,lineweight:-2147483648},landing:{enabled:true,gap:nan},dogleg:{enabled:false,length:zero},description:"leader",arrow:{symbolHandle:undefined,size:infinity},text:{defaultContent:"\0",styleHandle:0n,leftAttachment:"bottomOfTopNoUnderline",rightAttachment:"center",angle:"alwaysRightReading",alignment:"right",color,height:nan,frame:true,alwaysLeft:false,alignmentSpace:zero,attachmentDirection:"vertical",topAttachment:"topOfTop",bottomAttachment:"bottomLine"},block:{contentHandle:0n,color,scale:[nan,zero,infinity,finite],useScale:true,rotation:nan,useRotation:false,connection:"basePoint"},overallScale:zero,propertyOverridesChanged:true,annotative:false,breakSize:infinity};

export {material as dwgMaterialFixture,mline as dwgMlineFixture,visual as dwgVisualFixture,table as dwgTableStyleFixture,leader as dwgMLeaderFixture};
