[package]
name = "semio-framework-kernel-mathematical-cas"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_cas"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_number = { path = "../../number/rs", package = "semio-framework-kernel-mathematical-number" }
mathematical_polynomial = { path = "../../polynomial/rs", package = "semio-framework-kernel-mathematical-polynomial" }
mathematical_algebra = { path = "../../algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
mathematical_random = { path = "../../random/rs", package = "semio-framework-kernel-mathematical-random" }
