[package]
name = "semio-framework-kernel-infinite-board-normal-directed"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "infinite_board_normal_directed"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
infinite_board = { path = "../../../rs", package = "semio-framework-kernel-infinite-board" }
