import { readModelChoiceV1, assertModelChoiceJoinV1, assertAllModelChoicesV1 } from "../current-native-model-choice-inputs-1/📜️script.ts";
import { materializeCapturedNodeAliasesV1, assertCapturedNodeAliasesV1 } from "../current-native-package-alias-inputs-3/📜️script.ts";
import { readJsonFileV1, hashFileV1 } from "../native-json-inputs/📜️script.ts";
import { existsSync, readFileSync, realpathSync, statSync, lstatSync, readdirSync, mkdirSync, writeFileSync, linkSync, unlinkSync } from "node:fs";
import { dirname, resolve, relative, sep, extname } from "node:path";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { isDeepStrictEqual } from "node:util";
const ticket=resolve(import.meta.dir,".."),out=resolve(ticket,process.argv[2]==="laws"&&process.env.SEMIO_RUNTIME_SOURCE_CONTROL==="red"?"🗑️generated/current-native-origin/epoch-23-runtime-source-red":"🗑️generated/current-native-origin/epoch-23"),[command,owner]=process.argv.slice(2),controller=new AbortController(),io={signal:controller.signal},sha=(body:Buffer|string)=>createHash("sha256").update(body).digest("hex");
process.once("SIGINT",()=>controller.abort());process.once("SIGTERM",()=>controller.abort());let root=ticket;while(!existsSync(resolve(root,"nx.json")))root=dirname(root);
const bindings=new Map<string,string>(),links=new Map<string,string>(),loaded:any[]=[],gaps:any[]=[],packageBodies:any[]=[],packages=new Map<string,any>();
function bind(path:string){const actual=realpathSync(path),bytes=readFileSync(actual),hash=sha(bytes);if(bindings.has(actual)&&bindings.get(actual)!==hash)throw Error("Current runtime authority advanced "+actual);bindings.set(actual,hash);if(actual!==path)links.set(path,actual);return {path:actual,sha256:hash,byteCount:bytes.length,bytes};}
for(const path of[import.meta.path,resolve(import.meta.dir,"fixtures.json"),resolve(import.meta.dir,"source-controls.json"),resolve(ticket,"native-json-inputs/📜️script.ts"),resolve(ticket,"current-native-package-alias-inputs-3/📜️script.ts"),resolve(ticket,"current-native-package-alias-inputs-3/context-schema.json"),resolve(ticket,"current-native-package-alias-inputs-3/proof-schema.json"),resolve(ticket,"🗑️generated/current-native-package-alias-3/green/receipt.json"),resolve(ticket,"current-native-model-choice-inputs-1/📜️script.ts"),resolve(ticket,"current-native-model-choice-inputs-1/schema.json"),resolve(ticket,"current-native-model-choice-inputs-1/fixtures.json"),resolve(ticket,"🗑️generated/current-native-model-choice-1/green/receipt.json")])bind(path);const ownBindingCount=bindings.size;
export function runtimeSourceGapsV1(path:string,hash:string,context:any){const result:any[]=[],key=relative(context.snapshot,path).split(sep).join("/"),rootKey=relative(context.root,path).split(sep).join("/"),ticketKey=relative(context.ticket,path).split(sep).join("/");if(key&&!key.startsWith("../")&&!key.startsWith("node_modules/")&&context.expected.has(key)&&context.expected.get(key)!==hash)result.push({path,reason:"Actual captured first-party body differs"});if(!(command==="laws"&&process.env.SEMIO_RUNTIME_SOURCE_CONTROL==="red")&&rootKey&&!rootKey.startsWith("../")&&!rootKey.startsWith("node_modules/")&&ticketKey.startsWith("../"))result.push({path,reason:"Actual live Root-owned import outside held source is refused"});return result;}
export async function capturedAliasesGuardV1(plan:any){
 if(!plan.capturedNodeAliases?.model||!plan.capturedNodeAliases?.prepared)throw Error("Complete model/prepared captured alias proofs required");
 const projection=(rows:any[])=>rows.filter(row=>row.expected!==null&&row.path.endsWith("/package.json")).map(row=>({path:row.path,sha256:row.expected})).sort((a,b)=>Buffer.compare(Buffer.from(a.path),Buffer.from(b.path)));
 for(const[phase,rows]of[["model",plan.modelChecks],["prepared",plan.checks]]as any){const proof=plan.capturedNodeAliases[phase];if(!Array.isArray(rows)||proof.root!==plan.sourceRoot||proof.ticket!==plan.authorityTicketRoot||proof.snapshot!==plan.snapshot||proof.nodeModules!==resolve(plan.snapshot,"node_modules")||!isDeepStrictEqual(proof.requiredAliases,["@semio-tech/framework-kernel"])||!isDeepStrictEqual(proof.capturedManifests,projection(rows)))throw Error("Exact captured alias phase/manifest endpoint join required");await assertCapturedNodeAliasesV1(proof,{signal:controller.signal,progress:(event:object)=>console.log("[DEBUG] "+JSON.stringify(event))});}
 if(!isDeepStrictEqual(plan.capturedNodeAliases.model,plan.capturedNodeAliases.prepared))throw Error("Preparation changed captured package namespace");
}
async function yieldProgress(phase:string,n:number){controller.signal.throwIfAborted();if(n%128===0){console.log("[DEBUG] "+JSON.stringify({phase,owner,completed:n}));await new Promise<void>(done=>setImmediate(done));}}
function guard(){for(const[path,target]of links)if(!existsSync(path)||realpathSync(path)!==target)throw Error("Runtime physical mapping advanced");for(const[path,hash]of bindings)if(!existsSync(path)||sha(readFileSync(path))!==hash)throw Error("Runtime complete body advanced "+path);}
function write(path:string,value:any){guard();mkdirSync(dirname(path),{recursive:true});const temp=path+".writing";writeFileSync(temp,JSON.stringify(value),{flag:"wx"});linkSync(temp,path);unlinkSync(temp);}
const JSON5=(await import("json5")).default;
if(command==="laws"){
 if(process.env.SEMIO_RUNTIME_SOURCE_CONTROL==="red"){mkdirSync(out,{recursive:true});writeFileSync(resolve(out,"driver-source.json"),JSON.stringify({body:readFileSync(import.meta.path,"utf8"),bindings:[...bindings]}),{flag:"wx"});}
 Bun.plugin({name:"current-runtime-loader-law",setup(builder){builder.onLoad({filter:/runtime16-law-.*script\.ts$/},args=>({contents:readFileSync(args.path,"utf8"),loader:"ts"}));}});const controls=[];for(const row of JSON.parse(readFileSync(resolve(import.meta.dir,"fixtures.json"),"utf8"))){const path=resolve(out,"runtime16-law-"+row.id+".json");write(path,row.value);const sourcePath=resolve(out,"runtime16-law-"+row.id,"📜️script.ts");mkdirSync(dirname(sourcePath),{recursive:true});writeFileSync(sourcePath,"export default "+JSON.stringify(row.value)+";",{flag:"wx"});const actual=(await import(sourcePath)).default,native=await readJsonFileV1(path,io),external=JSON5.parse(readFileSync(path,"utf8")),bytes=readFileSync(path),hash=sha(bytes),ownHash=await hashFileV1(path,io);if(!isDeepStrictEqual(actual,row.value)||!isDeepStrictEqual(native,row.value)||!isDeepStrictEqual(external,row.value)||hash!==ownHash)throw Error("Runtime custody body oracle differs");controls.push({id:row.id,path,sha256:hash,actual,native,external,exact:true});}const Ajv=(await import("ajv/dist/2020.js")).default,sourceControls=[],sourceContext={root:resolve(out,"source-root"),ticket:resolve(out,"source-root/ticket"),snapshot:resolve(out,"source-root/ticket/snapshot"),expected:new Map([["🧰️framework/provider.ts",sha("body")]])};for(const row of JSON.parse(readFileSync(resolve(import.meta.dir,"source-controls.json"),"utf8"))){const path=resolve(sourceContext[row.base],row.path),value=runtimeSourceGapsV1(path,row.hash==="same"?sha("body"):sha("advanced"),sourceContext),expectedValue=row.reason?[{path,reason:row.reason}]:[],oracle=new Ajv({strict:true}).compile({const:expectedValue});if(!isDeepStrictEqual(value,expectedValue)||!oracle(value))throw Error("Actual runtime first-party location refusal oracle differs");sourceControls.push({...row,value,external:true});}write(resolve(out,"runtime27-laws.json"),{ready:true,bindings:[...bindings].map(([path,sha256])=>({path,sha256})),controls,sourceControls,nativeExecuted:false});process.exit(0);
}
if(command!=="capture"||!["ui","board","product"].includes(owner))throw Error("Exact runtime custody capture required");
const directory=resolve(out,owner),planPath=resolve(directory,"plan.json"),plan=await readJsonFileV1(planPath,io),snapshot=plan.snapshot,planHash=bind(planPath).sha256,lawsPath=resolve(out,"runtime27-laws.json"),laws=await readJsonFileV1(lawsPath,io);bind(lawsPath);if(!laws.ready||!isDeepStrictEqual(laws.bindings,[...bindings].slice(0,ownBindingCount).map(([path,sha256])=>({path,sha256}))))throw Error("Exact runtime custody controls required");
await capturedAliasesGuardV1(plan);assertModelChoiceJoinV1(plan,{signal:controller.signal});
const entrypoints=[resolve(snapshot,"🧰️framework/🔨️modules/🏃️process/🧪️testing/🎛️execution/🟦️.ts"),resolve(snapshot,"🧰️framework/🛍️products/🦑️repo/🔨️modules/📚️library/🟦️.ts"),resolve(snapshot,plan.ownerWitness.scriptRelative)],expected=new Map(plan.checks.map((row:any)=>[row.path,row.expected]));
function validateSource(path:string,hash:string){gaps.push(...runtimeSourceGapsV1(path,hash,{root,ticket,snapshot,expected}));}
Bun.plugin({name:"current-native-exact-runtime-body-custody",setup(builder){builder.onLoad({filter:/\.(?:tsx?)$/},args=>{controller.signal.throwIfAborted();const row=bind(args.path);validateSource(row.path,row.sha256);loaded.push({path:row.path,sha256:row.sha256,byteCount:row.byteCount});const extension=extname(args.path),loader=extension===".json"?"json":extension===".tsx"?"tsx":extension===".ts"?"ts":"js";return {contents:row.bytes.toString("utf8"),loader};});}});
Object.assign(process.env,plan.environment);process.env.NX_WORKSPACE_ROOT=snapshot;process.env.REPO_ROOT=snapshot;let importFailure:string|null=null;try{for(const path of entrypoints)await import(path);}catch(error){importFailure=String(error);console.error(error);}
const actualCache=Object.keys(createRequire(import.meta.path).cache);for(const path of actualCache)if(existsSync(path)&&statSync(path).isFile()){const row=bind(path);validateSource(row.path,row.sha256);loaded.push({path:row.path,sha256:row.sha256,byteCount:row.byteCount,actualBunCache:true});}
function packageRoot(path:string){let base=dirname(path);while(base!==dirname(base)){if(existsSync(resolve(base,"package.json")))return base;base=dirname(base);}return null;}
function findPackage(name:string,from:string){let base=from;while(base!==dirname(base)){const path=resolve(base,"node_modules",name,"package.json");if(existsSync(path))return realpathSync(dirname(path));base=dirname(base);}const direct=resolve(root,"node_modules",name,"package.json");return existsSync(direct)?realpathSync(dirname(direct)):null;}
const seeds=new Set<string>();for(const row of loaded){const base=packageRoot(row.path);if(base?.includes(sep+"node_modules"+sep))seeds.add(base);}for(const name of["nx",...JSON.parse(readFileSync(resolve(snapshot,"nx.json"),"utf8")).plugins.map((row:any)=>typeof row==="string"?row:row.plugin).filter((name:string)=>!name.startsWith("."))]){const base=findPackage(name,root);if(!base)gaps.push({name,reason:"Actual native executor package missing"});else seeds.add(base);}
async function collect(base:string){if(packages.has(base))return;const manifest=resolve(base,"package.json"),source=readFileSync(manifest,"utf8"),native=JSON.parse(source),external=JSON5.parse(source);if(!isDeepStrictEqual(native,external))throw Error("Actual dependency package JSON oracle differs");const edges:any[]=[];packages.set(base,{base,name:native.name,manifest,manifestHash:sha(source),edges});for(const[name,version]of Object.entries({...native.dependencies,...native.optionalDependencies})){const optional=Object.hasOwn(native.optionalDependencies??{},name),target=findPackage(name,base);edges.push({name,version,optional,target,exists:!!target});if(target)await collect(target);else if(!optional&&!String(version).startsWith("workspace:"))gaps.push({from:manifest,name,version,reason:"Required actual native package provider missing"});}
 const seen=new Set<string>();async function walk(path:string):Promise<void>{controller.signal.throwIfAborted();const actual=realpathSync(path);if(seen.has(actual))return;seen.add(actual);const stat=statSync(actual);if(stat.isDirectory()){if(path!==actual)links.set(path,actual);for(const name of readdirSync(actual))if(!["node_modules",".git",".cache"].includes(name))await walk(resolve(actual,name));}else if(stat.isFile()){const row=bind(path);validateSource(row.path,row.sha256);packageBodies.push({path:row.path,sha256:row.sha256,byteCount:row.byteCount});await yieldProgress("runtime-complete-physical-package-bodies",packageBodies.length);}}await walk(base);
}
for(const base of seeds)await collect(base);await capturedAliasesGuardV1(plan);assertModelChoiceJoinV1(plan,{signal:controller.signal});const ready=!importFailure&&loaded.length>0&&gaps.length===0;
write(resolve(directory,"runtime-import-custody23.json"),{at:new Date().toISOString(),owner,planHash,capturedNodeAliases:plan.capturedNodeAliases,bindings:[...bindings].map(([path,sha256])=>({path,sha256})),links:[...links].map(([path,target])=>({path,target})),entrypoints,loaded,packages:[...packages.values()],packageBodies,gaps,importFailure,ready,nativeExecuted:false,historicalAcceptanceClaimed:false,scope:"Exact actual TypeScript executor/library/owner bodies, unmodified CommonJS loaders observed through actual Bun require cache plus complete recursively declared physical external package bodies and Nx/plugin packages; static lazy optional import failure preserved separately"});console.log(JSON.stringify({owner,ready,loaded:loaded.length,packages:packages.size,packageBodies:packageBodies.length,gaps,importFailure}));process.exit(ready?0:1);
