/** 🏔️ Exact terrain words and independently editable SQL parameters. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import fixture from "../../🧫️fixtures/🪶️sqlite/🔣️.json";
import {gisTerrainSnapshotToSqliteDatabase,gisTerrainSnapshotFromSqliteDatabase,validateGisTerrainSnapshotSqliteDialect} from "../../🪶️sqlite/🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
function snapshot(word:string,mesh=true){return {exaggeration:{bits:BigInt("0x"+word)},importedFeaturesJson:fixture.importedFeaturesJson,...(mesh?{mesh:fixture.child}:{})};}
test("GIS terrain retains every native IEEE word, exact unparsed source string and independent child handle",async()=>{for(const word of fixture.words)for(const present of [false,true]){const value=snapshot(word,present),db=await gisTerrainSnapshotToSqliteDatabase(value);expect(await gisTerrainSnapshotFromSqliteDatabase(db)).toEqual(value);const sql=Database.deserialize(await exportSqliteDatabase(db));try{expect(sql.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(sql.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(sql.query("SELECT imported_features_json FROM gis_terrain_parameters").get()).toEqual({imported_features_json:fixture.importedFeaturesJson});const query=sql.query("SELECT exaggeration_numeric_class AS kind,exaggeration FROM gis_terrain_parameters").get()as{kind:string;exaggeration:number|null};if(word.includes("7ff0000000000001")||word.startsWith("fff8")){expect(query.kind).toBe("nan");expect(query.exaggeration).toBe(null);}expect(await gisTerrainSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(sql.serialize())))).toEqual(value);}finally{sql.close();}}});
test("GIS terrain accepts consistent surrogate renumbering and valid independent edits but rejects mismatched words and missing ownership",async()=>{const value=snapshot(fixture.words[2]!);const sql=Database.deserialize(await exportSqliteDatabase(await gisTerrainSnapshotToSqliteDatabase(value)));try{sql.run("UPDATE gis_terrain_document SET id=42; UPDATE gis_terrain_parameters SET id=42; UPDATE gis_terrain_mesh_child SET id=42");const db=await importSqliteDatabase(new Uint8Array(sql.serialize()));expect(await validateGisTerrainSnapshotSqliteDialect(value,fixture.dialect,db)).toEqual([]);sql.query("UPDATE gis_terrain_parameters SET imported_features_json=?").run("independently edited semantic String");const changed=await importSqliteDatabase(new Uint8Array(sql.serialize()));expect((await gisTerrainSnapshotFromSqliteDatabase(changed)).importedFeaturesJson).toBe("independently edited semantic String");await expect(validateGisTerrainSnapshotSqliteDialect(value,fixture.dialect,changed)).rejects.toThrow("identity");sql.run("UPDATE gis_terrain_parameters SET exaggeration=2");await expect(gisTerrainSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(sql.serialize())))).rejects.toThrow("IEEE");}finally{sql.close();}for(const mutation of ["DELETE FROM gis_terrain_parameters","UPDATE gis_terrain_mesh_child SET id=9","INSERT INTO gis_terrain_document VALUES(9)"]){const sql=Database.deserialize(await exportSqliteDatabase(await gisTerrainSnapshotToSqliteDatabase(value)));try{sql.run(mutation);await expect(gisTerrainSnapshotFromSqliteDatabase(await importSqliteDatabase(new Uint8Array(sql.serialize())))).rejects.toThrow();}finally{sql.close();}}});
test("GIS terrain admits budgets before copies and reports cancellation through both directions",async()=>{const value=snapshot(fixture.words[1]!),db=await gisTerrainSnapshotToSqliteDatabase(value);for(const options of [{maxRows:2},{maxValueBytes:16}]){await expect(gisTerrainSnapshotToSqliteDatabase(value,options)).rejects.toThrow("limit");await expect(gisTerrainSnapshotFromSqliteDatabase(db,options)).rejects.toThrow("limit");}const controller=new AbortController();controller.abort();await expect(gisTerrainSnapshotToSqliteDatabase(value,{signal:controller.signal})).rejects.toMatchObject({name:"AbortError"});await expect(gisTerrainSnapshotFromSqliteDatabase(db,{signal:controller.signal})).rejects.toMatchObject({name:"AbortError"});await expect(validateGisTerrainSnapshotSqliteDialect(value,{...fixture.dialect,subset:"invented"},db)).rejects.toThrow("subset");});
