[package]
name = "remodel_dense"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
remodel_image = { path = "../../image/rs" }
remodel_camera = { path = "../../camera/rs" }
mathematical_algebra = { path = "../../../framework/kernel/mathematical/algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
mathematical_spatial = { path = "../../../framework/kernel/mathematical/spatial/rs", package = "semio-framework-kernel-mathematical-spatial" }
