//! 🏭️ Independent native manufacturer fixture and declaration-owned capability obligations.
use super::Vdi3805Snapshot;
#[test]
fn sqlite_snapshot_vdi3805_native_sheet_id_refuses_every_out_of_width_word(){
 for word in[65536,u64::MAX]{assert!(serde_json::from_value::<crate::SheetId>(serde_json::json!(word)).is_err());assert!(<crate::SheetId as semio_framework_dsl_record::DslField>::from_value(&semio_framework_dsl_record::FieldValue::UInt(word)).is_err());}
}
#[test]
fn sqlite_snapshot_vdi3805_owned_native_decoder_controls_physical_and_typed_construction(){
 use store::io::IoPayload;
 let limits=SqliteDatabaseLimits::default();let snapshot=fixture();
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{
  let payload=match encoding{SnapshotEncoding::Binary=>IoPayload::Binary(store::ArtifactPack::encode_pack(&snapshot)),SnapshotEncoding::Text=>IoPayload::Text(store::ArtifactDsl::print_dsl(&snapshot))};
  let restored=Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();assert_eq!(restored,snapshot);
  assert!(Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|false,limits)).is_err());
  assert!(Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:1,..limits})).is_err());
  assert!(Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:1,..limits})).is_err());
 }
}
#[test]
fn sqlite_snapshot_vdi3805_controlled_native_binding_preserves_every_neutral_numeric_word(){
 use store::io::IoPayload;
 let words:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🔢️binary64.json")).unwrap();
 for word in words["ieee754Binary64Bits"].as_array().unwrap(){
  let mut snapshot=fixture();set_every_word(&mut snapshot,f64::from_bits(word.as_str().unwrap().parse().unwrap()));let expected=database(&snapshot);
  for payload in[IoPayload::Binary(store::ArtifactPack::encode_pack(&snapshot)),IoPayload::Text(store::ArtifactDsl::print_dsl(&snapshot))]{
   let restored=Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();
   assert_eq!(database(&restored),expected);
  }
 }
}
#[test]
fn sqlite_snapshot_vdi3805_controlled_attribute_binding_admits_before_owned_copy_and_cancels_inside_entries(){
 use semio_framework_dsl_record::DslField;
 use semio_framework_value::native_decoding::NativeDecodeProgress;
 let neutral:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🎛️control.json")).unwrap();
 let count=neutral["entityCount"].as_u64().unwrap()as usize;let cancel_at=neutral["cancelAt"].as_u64().unwrap()as usize;let length=neutral["largeTextBytes"].as_u64().unwrap()as usize;
 let attributes=crate::SheetAttributes::Generic(crate::GenericAttributes{entries:(0..count).map(|n|crate::GenericAttribute{key:n.to_string(),value:"世界".into(),unit:None}).collect()});let value=attributes.to_value();
 let mut reached=false;let mut callback=|event:NativeDecodeProgress|{if event.completed>=cancel_at{reached=true;false}else{true}};
 assert!(crate::SheetAttributes::from_value_controlled(&value,&mut semio_framework_value::NativeDecodeControl::new(1024*1024,&mut callback)).is_err());assert!(reached);
 let mut permit=|_:NativeDecodeProgress|true;let mut limited=semio_framework_value::NativeDecodeControl::new(1024,&mut permit);assert!(crate::SheetAttributes::from_value_controlled(&value,&mut limited).is_err());assert!(limited.owned_bytes()<=1024);
 let attributes=crate::SheetAttributes::Generic(crate::GenericAttributes{entries:vec![crate::GenericAttribute{key:String::new(),value:"x".repeat(length),unit:None}]});let value=attributes.to_value();
 let mut limited=semio_framework_value::NativeDecodeControl::new(65536,&mut permit);assert!(crate::SheetAttributes::from_value_controlled(&value,&mut limited).is_err());assert!(limited.owned_bytes()<=65536);
 let mut reached=false;let mut callback=|event:NativeDecodeProgress|{if event.total==length&&event.completed>=65536{reached=true;false}else{true}};
 assert!(crate::SheetAttributes::from_value_controlled(&value,&mut semio_framework_value::NativeDecodeControl::new(1024*1024,&mut callback)).is_err());assert!(reached);
}
use store::{ArtifactSqliteSnapshot,sqlite_snapshot::{export_sqlite_database,import_sqlite_database,SnapshotEncoding,SqliteDatabase,SqliteDatabaseLimits,SqliteSnapshotControl,SqliteSnapshotPhase,SqliteValue}};
fn fixture()->Vdi3805Snapshot{semio_framework_pack_json::from_json_str(include_str!("../../🧫️fixtures/🪶️sqlite/🔣️.json"), semio_framework_pack_json::JsonMemberPolicy::Reject).unwrap()}
fn database(snapshot:&Vdi3805Snapshot)->SqliteDatabase{snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap()}
fn roundtrip(snapshot:&Vdi3805Snapshot)->Vdi3805Snapshot{let bytes=export_sqlite_database(&database(snapshot),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();Vdi3805Snapshot::from_sqlite_database(&import_sqlite_database(&bytes,SqliteDatabaseLimits::default(),&mut |_|true).unwrap(),&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap()}
fn set_every_word(s:&mut Vdi3805Snapshot,v:f64){
 for p in &mut s.catalog.products{match &mut p.configuration.attributes{crate::SheetAttributes::ValveHeating(a)=>{a.kvs_m3_s=v;a.authority_min=v;a.authority_max=v;},crate::SheetAttributes::Radiator(a)=>{a.standard_output_w=v;a.heat_exponent_n=v;a.length_m=v;a.height_m=v;a.depth_m=v;},crate::SheetAttributes::PumpHeating(a)=>{a.nominal_flow_m3_s=v;a.nominal_head_m=v;a.motor_power_w=v;a.hydraulic_efficiency=v;},crate::SheetAttributes::HeatGenerator(a)=>{a.nominal_heat_output_w=v;a.flow_temp_max_c=v;a.return_temp_min_c=v;},crate::SheetAttributes::Generic(_)=>{}}}
 for g in s.geometry.values_mut(){g.bbox.min_x=v;g.bbox.min_y=v;g.bbox.min_z=v;g.bbox.max_x=v;g.bbox.max_y=v;g.bbox.max_z=v;for c in &mut g.connections{c.position=[v;3];c.direction=[v;3];if let Some(value)=&mut c.diameter_mm{*value=v;}}for value in g.parameters.values_mut(){*value=v;}}
 for c in s.curves.values_mut(){c.x_unit.si_factor=v;c.y_unit.si_factor=v;for p in &mut c.points{p.x=v;p.y=v;}}
}
#[test]
fn sqlite_snapshot_vdi3805_complete_native_fixture_agrees_with_independent_serde(){let snapshot=fixture();assert_eq!(snapshot,serde_json::from_str::<Vdi3805Snapshot>(include_str!("../../🧫️fixtures/🪶️sqlite/🔣️.json")).unwrap());assert_eq!(snapshot.catalog.products.len(),5);assert_eq!(snapshot.catalog.file.record_count,u32::MAX);assert_eq!(snapshot.catalog.products[0].sheet.0,u16::MAX);assert_eq!(snapshot.correction_as_of.month,u8::MAX);assert_eq!(snapshot.curves.values().next().unwrap().x_unit.kind,crate::VdiQuantityKind::Length);}
#[test]
fn sqlite_snapshot_vdi3805_actual_bare_factory_exposes_complete_owned_capability(){let codec=store::ArtifactCodec::bare::<Vdi3805Snapshot,crate::Vdi3805Mutation>(crate::VDI3805_DOCUMENT_SCHEMA);assert!(codec.snapshot_sqlite.is_some());}
#[test]
fn sqlite_snapshot_vdi3805_all_fields_and_empty_independent_catalogue_subjects_survive_sqlite(){let snapshot=fixture();assert_eq!(roundtrip(&snapshot),snapshot);let mut empty=snapshot;empty.catalog.products.clear();empty.catalog.extensions.fields.clear();empty.catalog.file.extensions.fields.clear();empty.edition_profile.clear();empty.index.entries.clear();empty.geometry.clear();empty.curves.clear();assert_eq!(database(&empty).tables.len(),32);assert_eq!(roundtrip(&empty),empty);}
#[test]
fn sqlite_snapshot_vdi3805_every_complete_numeric_domain_retains_all_neutral_raw_words(){let words:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🔢️binary64.json")).unwrap();for word in words["ieee754Binary64Bits"].as_array().unwrap(){let mut snapshot=fixture();set_every_word(&mut snapshot,f64::from_bits(word.as_str().unwrap().parse().unwrap()));assert_eq!(database(&roundtrip(&snapshot)),database(&snapshot));}}
#[test]
fn sqlite_snapshot_vdi3805_all_neutral_unsigned64_security_words_retain_native_width(){let choices:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🛂️choices.json")).unwrap();for text in choices["unsigned64Words"].as_array().unwrap(){let word=text.as_str().unwrap().parse::<u64>().unwrap();let mut snapshot=fixture();let mut imported=database(&snapshot);for cell in &mut imported.table_mut("vdi3805_limits").unwrap().rows[0].values[2..]{*cell=SqliteValue::Integer(word as i64);}let result=Vdi3805Snapshot::from_sqlite_database(&imported,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default()));let Ok(value)=usize::try_from(word)else{assert!(result.is_err());continue};snapshot.limits=crate::SecurityLimits{max_file_bytes:value,max_records:value,max_field_length:value,max_nesting_depth:value};assert_eq!(result.unwrap(),snapshot);let database=database(&snapshot);for cell in &database.table("vdi3805_limits").unwrap().rows[0].values[2..]{let SqliteValue::Integer(value)=cell else{panic!("unsigned word cell")};assert_eq!(*value as u64,word);}assert_eq!(roundtrip(&snapshot),snapshot);}}

#[test]
fn sqlite_snapshot_vdi3805_all_neutral_quantity_and_edition_choices_retain_exact_identity(){let choices:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🛂️choices.json")).unwrap();for value in choices["quantityKind"].as_array().unwrap(){let mut snapshot=fixture();snapshot.curves.values_mut().next().unwrap().x_unit.kind=serde_json::from_value(value.clone()).unwrap();assert_eq!(roundtrip(&snapshot),snapshot);}for value in choices["edition"].as_array().unwrap(){let mut snapshot=fixture();snapshot.edition_profile.insert(String::new(),serde_json::from_value(value.clone()).unwrap());assert_eq!(roundtrip(&snapshot),snapshot);}}

#[test]
fn sqlite_snapshot_vdi3805_shared_independent_sql_corpus_refuses_lost_native_ownership(){
 use std::{io::Write,process::{Command,Stdio}};
 let cases=include_str!("../../🧫️fixtures/🪶️sqlite/⚠️malformed.json");let edits:Vec<String>=serde_json::from_str(cases).unwrap();let bytes=export_sqlite_database(&database(&fixture()),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();
 let script="import{Database}from'bun:sqlite';const bytes=new Uint8Array(await Bun.stdin.arrayBuffer());for(const sql of JSON.parse(process.argv.at(-1))){const db=Database.deserialize(bytes);try{db.run('PRAGMA foreign_keys=OFF');db.run('PRAGMA ignore_check_constraints=ON');db.exec(sql);const out=db.serialize(),header=new Uint8Array(4);new DataView(header.buffer).setUint32(0,out.length,true);await Bun.write(Bun.stdout,header);await Bun.write(Bun.stdout,out)}finally{db.close()}}";
 let mut child=Command::new("bun").args(["-e",script,"--",cases]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let mut position=0;
 for sql in edits{let end=position+4;let length=u32::from_le_bytes(output.stdout[position..end].try_into().unwrap())as usize;position=end;let end=position+length;let refused=match import_sqlite_database(&output.stdout[position..end],SqliteDatabaseLimits::default(),&mut |_|true){Ok(database)=>Vdi3805Snapshot::from_sqlite_database(&database,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),Err(_)=>true};assert!(refused,"{sql}");position=end;}assert_eq!(position,output.stdout.len());
}
#[test]
fn sqlite_snapshot_vdi3805_independent_sqlite_queries_complete_entities_and_applies_semantic_edits(){
 use std::{io::Write,process::{Command,Stdio}};
 let mut expected=fixture();let bytes=export_sqlite_database(&database(&expected),SqliteDatabaseLimits::default(),&mut |_|true).unwrap();let script="import{Database}from'bun:sqlite';import{Buffer}from'node:buffer';const db=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()));if(db.query('PRAGMA integrity_check').get().integrity_check!=='ok'||db.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');const kinds=db.query('SELECT p.ordinal,c.attribute_kind FROM vdi3805_product p JOIN vdi3805_configuration c ON c.product_id=p.id ORDER BY p.ordinal').all();if(JSON.stringify(kinds.map(x=>x.attribute_kind))!==JSON.stringify(['valveHeating','radiator','pumpHeating','heatGenerator','generic']))throw Error('variant ownership');const fields=db.query('SELECT f.ordinal FROM vdi3805_product p JOIN vdi3805_record r ON r.product_id=p.id JOIN vdi3805_record_field f ON f.record_id=r.id ORDER BY f.ordinal').all();if(fields.length!==3||fields[2].ordinal!==2)throw Error('record ownership');const i=db.query('SELECT ordinal,product_logical_id,sheet,dn FROM vdi3805_index_entry ORDER BY ordinal').all();if(i.length!==2||i[0].sheet!==65535||i[0].dn!==65535||i[1].dn!==null)throw Error('independent index');const b=Buffer.alloc(8);b.writeDoubleBE(0.625);db.run(\"UPDATE vdi3805_valve SET kvs_m3_s=0.625,kvs_m3_s_ieee754_bits=?,kvs_m3_s_ieee754_class='finite'\",[BigInt.asIntN(64,b.readBigUInt64BE())]);db.run(\"UPDATE vdi3805_catalogue_extension SET value='Geändert 世界' WHERE map_key=''\");db.run(\"UPDATE vdi3805_curve_unit SET quantity_kind='acceleration',delta=0 WHERE axis=0\");db.run(\"UPDATE vdi3805_index_entry SET product_logical_id='another unresolved' WHERE id=1\");await Bun.write(Bun.stdout,db.serialize());db.close();";
 let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));let crate::SheetAttributes::ValveHeating(a)=&mut expected.catalog.products[0].configuration.attributes else{panic!("fixture variant")};a.kvs_m3_s=0.625;expected.catalog.extensions.fields.insert(String::new(),"Geändert 世界".into());let c=expected.curves.values_mut().next().unwrap();c.x_unit.kind=crate::VdiQuantityKind::Acceleration;c.x_unit.delta=false;expected.index.entries[0].product_id="another unresolved".into();assert_eq!(Vdi3805Snapshot::from_sqlite_database(&import_sqlite_database(&output.stdout,SqliteDatabaseLimits::default(),&mut |_|true).unwrap(),&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap(),expected);
}
#[test]
fn sqlite_snapshot_vdi3805_refuses_malformed_choices_widths_booleans_parents_ordinals_maps_words_and_mandatory_subjects(){
 let database=database(&fixture());for(table,row,column,value)in[("vdi3805_document",0,1,SqliteValue::Integer(65536)),("vdi3805_document",0,2,SqliteValue::Integer(256)),("vdi3805_document",0,3,SqliteValue::Integer(2)),("vdi3805_file",0,6,SqliteValue::Integer(4294967296)),("vdi3805_product",0,7,SqliteValue::Integer(65536)),("vdi3805_configuration",0,3,SqliteValue::Text("radiator".into())),("vdi3805_valve",0,2,SqliteValue::Integer(-1)),("vdi3805_accessory",0,4,SqliteValue::Integer(2)),("vdi3805_component",0,4,SqliteValue::Integer(4294967296)),("vdi3805_connection",1,11,SqliteValue::Integer(2)),("vdi3805_curve_unit",0,2,SqliteValue::Integer(2)),("vdi3805_curve_unit",0,4,SqliteValue::Text("unknown".into())),("vdi3805_edition",0,3,SqliteValue::Text("unknown".into())),("vdi3805_valve",0,9,SqliteValue::Text("nan".into()))]{let mut invalid=database.clone();invalid.table_mut(table).unwrap().rows[row].values[column]=value;assert!(Vdi3805Snapshot::from_sqlite_database(&invalid,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),"{table}");}
 for table in["vdi3805_catalogue","vdi3805_file","vdi3805_building_system","vdi3805_limits","vdi3805_catalogue_extension","vdi3805_file_extension","vdi3805_product_extension","vdi3805_record_extension","vdi3805_product","vdi3805_title","vdi3805_record","vdi3805_record_field","vdi3805_configuration","vdi3805_function_ref","vdi3805_valve","vdi3805_radiator","vdi3805_pump","vdi3805_heat_generator","vdi3805_generic","vdi3805_generic_entry","vdi3805_accessory","vdi3805_component","vdi3805_edition","vdi3805_index_entry","vdi3805_index_tag","vdi3805_geometry","vdi3805_connection","vdi3805_geometry_parameter","vdi3805_curve","vdi3805_curve_unit","vdi3805_curve_point"]{let mut invalid=database.clone();invalid.table_mut(table).unwrap().rows[0].values[1]=SqliteValue::Integer(99);assert!(Vdi3805Snapshot::from_sqlite_database(&invalid,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),"foreign parent {table}");}
 for table in["vdi3805_document","vdi3805_catalogue","vdi3805_file","vdi3805_building_system","vdi3805_limits","vdi3805_configuration","vdi3805_valve","vdi3805_radiator","vdi3805_pump","vdi3805_heat_generator","vdi3805_generic","vdi3805_curve_unit"]{let mut invalid=database.clone();invalid.table_mut(table).unwrap().rows.clear();assert!(Vdi3805Snapshot::from_sqlite_database(&invalid,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),"mandatory {table}");}
 for table in["vdi3805_product","vdi3805_title","vdi3805_record","vdi3805_record_field","vdi3805_function_ref","vdi3805_generic_entry","vdi3805_accessory","vdi3805_component","vdi3805_index_entry","vdi3805_index_tag","vdi3805_connection","vdi3805_curve_point"]{let mut invalid=database.clone();invalid.table_mut(table).unwrap().rows[0].values[2]=SqliteValue::Integer(99);assert!(Vdi3805Snapshot::from_sqlite_database(&invalid,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).is_err(),"ordinal {table}");}
}
#[test]
fn sqlite_snapshot_vdi3805_initial_and_nested_operations_support_cancellation_and_borrowed_native_admission(){
 let mut snapshot=fixture();assert!(snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:1,..SqliteDatabaseLimits::default()})).is_err());assert!(Vdi3805Snapshot::from_sqlite_database(&database(&snapshot),&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_value_bytes:0,..SqliteDatabaseLimits::default()})).is_err());
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap();assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,SqliteDatabaseLimits::default())).is_err());assert!(snapshot.preflight_sqlite_snapshot_encoding(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_file_bytes:1024,..SqliteDatabaseLimits::default()})).unwrap_err().to_string().contains("native encoding exceeds file byte limit"));}
 let controls:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🎛️control.json")).unwrap();snapshot.catalog.products[0].records[0].fields=vec!["任意\0field".into();controls["entityCount"].as_u64().unwrap()as usize];let cancel_at=controls["cancelAt"].as_u64().unwrap()as usize;for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let mut reached=false;assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut|event|{if event.phase==SqliteSnapshotPhase::EncodeNative&&event.completed>=cancel_at{reached=true;false}else{true}},SqliteDatabaseLimits::default())).is_err());assert!(reached);}let large=database(&snapshot);for phase in[SqliteSnapshotPhase::ProjectSnapshot,SqliteSnapshotPhase::ReconstructSnapshot]{let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{if event.phase==phase&&event.completed>=cancel_at{reached=true;false}else{true}};let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());assert!(if phase==SqliteSnapshotPhase::ProjectSnapshot{snapshot.to_sqlite_database(&mut control).is_err()}else{Vdi3805Snapshot::from_sqlite_database(&large,&mut control).is_err()});assert!(reached);}
}
#[test]
fn sqlite_snapshot_vdi3805_large_owned_text_cancels_before_projection_reconstruction_and_encoding_copy(){let mut snapshot=fixture();snapshot.catalog.file.manufacturer="x".repeat(131073);let database=database(&snapshot);for phase in[SqliteSnapshotPhase::ProjectSnapshot,SqliteSnapshotPhase::ReconstructSnapshot,SqliteSnapshotPhase::EncodeNative]{let mut reached=false;let mut callback=|event:store::sqlite_snapshot::SqliteSnapshotProgress|{if event.phase==phase&&event.total>=65536&&event.completed>=65536&&event.completed<event.total{reached=true;false}else{true}};let mut control=SqliteSnapshotControl::new(&mut callback,SqliteDatabaseLimits::default());let rejected=match phase{SqliteSnapshotPhase::ProjectSnapshot=>snapshot.to_sqlite_database(&mut control).is_err(),SqliteSnapshotPhase::ReconstructSnapshot=>Vdi3805Snapshot::from_sqlite_database(&database,&mut control).is_err(),_=>snapshot.encode_sqlite_snapshot_native(SnapshotEncoding::Text,&mut control).is_err()};assert!(rejected);assert!(reached);}}
#[semio_framework_async_macros::async_test]
async fn sqlite_snapshot_vdi3805_actual_erased_codec_and_declaration_preserve_every_owned_word(){
 use store::io::{ArtifactDialect,IoPayload,io_mechanism::{io_export_sqlite_snapshot,io_import_sqlite_snapshot}};
 semio_framework_plugin::Plugin::<semio_framework_plugin::app::NoPluginApp>::builder("norm").label("VDI3805 owned SQLite").version("0.0.1").package_id("semio:norm").artifact(crate::declaration(crate::definition().unwrap()).unwrap()).try_build().unwrap();let codec=store::document_codec(crate::VDI3805_DOCUMENT_SCHEMA).await.unwrap().unwrap();let provider=codec.snapshot_sqlite.as_ref().unwrap();let dialect=ArtifactDialect{artifact_kind:"s.norm.vdi3805".into(),standard:"1".into(),subset:"*".into()};
 let words:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🪶️sqlite/🔢️binary64.json")).unwrap();for word in words["ieee754Binary64Bits"].as_array().unwrap(){let mut snapshot=fixture();set_every_word(&mut snapshot,f64::from_bits(word.as_str().unwrap().parse().unwrap()));let expected=database(&snapshot);for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{let payload=match encoding{SnapshotEncoding::Binary=>IoPayload::Binary(<Vdi3805Snapshot as store::ArtifactPack>::encode_pack_with(&snapshot,&store::PackEncodeOptions::default()).unwrap()),SnapshotEncoding::Text=>IoPayload::Text(<Vdi3805Snapshot as store::ArtifactDsl>::print_dsl(&snapshot))};let result=(provider.export)(&codec.schema,&dialect,&payload,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;assert_eq!(result,expected);let result=(provider.import)(&codec.schema,&dialect,result,encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits::default())).unwrap().value;let restored=match result{IoPayload::Binary(bytes)=><Vdi3805Snapshot as store::ArtifactPack>::decode_pack(&bytes).unwrap(),IoPayload::Text(text)=><Vdi3805Snapshot as store::ArtifactDsl>::parse_dsl(&text).unwrap()};assert_eq!(database(&restored),expected);}}
 let snapshot=fixture();let output=io_export_sqlite_snapshot(&dialect,&snapshot,SnapshotEncoding::Binary,SqliteDatabaseLimits::default(),&mut |_|true).await.unwrap();assert_eq!(io_import_sqlite_snapshot::<Vdi3805Snapshot>(&dialect,&output.value,SqliteDatabaseLimits::default(),&mut |_|true).await.unwrap().value,snapshot);
}

#[test]
fn sqlite_snapshot_vdi3805_genuine_output_admits_exact_row_and_file_frontiers(){
 use store::{ArtifactSqliteSnapshot as _,sqlite_snapshot::{SqliteDatabaseLimits,SqliteSnapshotControl,SnapshotEncoding,export_sqlite_database}};
 use std::{io::Write,process::{Command,Stdio}};
 let snapshot=fixture();let limits=SqliteDatabaseLimits::default();let expected=snapshot.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();let rows=expected.tables.iter().map(|table|table.rows.len()).sum::<usize>();assert!(rows>0);
 let bytes=export_sqlite_database(&expected,limits,&mut |_|true).unwrap();
 let script=r#"import{Database}from'bun:sqlite';const db=Database.deserialize(new Uint8Array(await Bun.stdin.arrayBuffer()),{safeIntegers:true});if(db.query('PRAGMA integrity_check').get().integrity_check!=='ok'||db.query('PRAGMA foreign_key_check').all().length)throw Error('integrity');const tables=db.query("SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name").all();const rows=tables.reduce((n,t)=>n+Number(db.query('SELECT COUNT(*) AS count FROM "'+t.name.replaceAll('"','""')+'"').get().count),0);await Bun.write(Bun.stdout,String(rows));db.close();"#;
 let mut child=Command::new("bun").args(["-e",script]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().unwrap();child.stdin.take().unwrap().write_all(&bytes).unwrap();let output=child.wait_with_output().unwrap();assert!(output.status.success(),"{}",String::from_utf8_lossy(&output.stderr));assert_eq!(String::from_utf8(output.stdout).unwrap().parse::<usize>().unwrap(),rows);
 for encoding in[SnapshotEncoding::Binary,SnapshotEncoding::Text]{
  let payload=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:rows,..limits})).unwrap();
  let physical=match &payload{store::io::IoPayload::Binary(value)=>value.len(),store::io::IoPayload::Text(value)=>value.len()};assert!(physical>0);
  let repeated=snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,SqliteDatabaseLimits{max_rows:rows,max_file_bytes:physical,..limits})).unwrap();assert_eq!(repeated,payload);
  let restored=Vdi3805Snapshot::decode_sqlite_snapshot_native(&payload,&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap();assert_eq!(restored.to_sqlite_database(&mut SqliteSnapshotControl::new(&mut |_|true,limits)).unwrap(),expected);
  for restricted in[SqliteDatabaseLimits{max_rows:rows-1,..limits},SqliteDatabaseLimits{max_file_bytes:physical-1,..limits},SqliteDatabaseLimits{max_value_bytes:1,..limits}]{assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|true,restricted)).is_err(),"{encoding:?}: {restricted:?}");}
  assert!(snapshot.encode_sqlite_snapshot_native(encoding,&mut SqliteSnapshotControl::new(&mut |_|false,limits)).is_err());
 }
}
