/** 🧫️ Original UTF-8 clusters survive bounded canonical normalization and cancellation. */
import {test,expect} from "bun:test";
import Ajv from "ajv";
import {UnicodeDataAdmissionJob,unicodeSourceUrl} from "../../🟦️.ts";
import {UnicodeNormalizationJob} from "../🟦️.ts";
import schema from "../🧬️schema/🔣️.json";
import rows from "../🧫️fixtures/🔣️.json";
test("shared canonical normalization agrees with independent system Unicode",async()=>{expect(new Ajv({strict:true}).compile(schema)(rows)).toBe(true);const bytes=new Uint8Array(await Bun.file(unicodeSourceUrl).arrayBuffer()),admission=new UnicodeDataAdmissionJob(bytes);while(!admission.advance(4096).done){}const data=admission.result();for(const row of rows){const expected=[...row.text.normalize("NFC")].map(value=>value.codePointAt(0)!);expect(expected).toEqual(row.scalars);for(const grant of [1,7,4096]){const job=new UnicodeNormalizationJob(data,row.text,1048576,1e9);let work=0;while(true){const p=job.advance(grant);expect(p.work-work).toBeLessThanOrEqual(grant);work=p.work;if(p.done)break;expect(()=>job.result()).toThrow();}const result=job.result();expect(result.map(value=>value.scalar)).toEqual(expected);expect(result.map(value=>value.sourceAt)).toEqual(row.clusters);expect(data.bytes).toBe(bytes);const moved=job.intoRetirement();while(!moved.job.advance(1).done){}expect(moved.output).toBe(result);}}const moved=admission.intoRetirement();while(!moved.job.advance(1).done){}console.log("[DEBUG] Canonical Unicode16: shared NFC, recursive decomposition, stable ordering, composition blocking, Hangul and UTF-8 clusters matched system Unicode at grants 1/7/4096");});
test("normalization interruption withholds original private candidate",async()=>{const bytes=new Uint8Array(await Bun.file(unicodeSourceUrl).arrayBuffer()),admission=new UnicodeDataAdmissionJob(bytes);while(!admission.advance(4096).done){}const data=admission.result(),text="A\u0308 a\u0315\u0300 👩‍💻";for(const stop of [0,1,2,7,20,100,1000]){const job=new UnicodeNormalizationJob(data,text,1048576,1e9);if(stop)job.advance(stop);job.cancel();expect(()=>job.result()).toThrow();const moved=job.intoRetirement();expect(moved.output).toBeNull();while(!moved.job.advance(1).done){}expect(data.bytes).toBe(bytes);}const moved=admission.intoRetirement();while(!moved.job.advance(1).done){}console.log("[DEBUG] Seven canonical normalization interruptions retained original text/data and private candidate until explicit close");});
