//! 🕸️ Complete managed topology and intrinsic owners use the caller's admitted backing.
use crate::{LowpolyMeshState,LowpolyMeshVertex,LowpolyMeshHalfedge,LowpolyMeshFace,LowpolyMeshAttribute,LowpolyMeshMaterial,LowpolyMeshTexture,LowpolyMeshAttributeDomain as Domain,LowpolyMeshAttributeSemantic as Semantic,LowpolyMeshAttributeInterpolation as Interpolation};
use semio_framework_value::{DecodedValue,DslValue as Value,FromValue,NativeDecodeControl,Number,ValueError,ValueRefusalKind};
use store::sqlite_snapshot::{SqliteRow,SqliteValue,artifact::{FloatColumn,FloatRow}};
use super::rows::{Rows,sort};
type Result<T>=std::result::Result<T,ValueError>;
const VERTEX:&[FloatColumn]=&[FloatColumn::Binary32(3),FloatColumn::Binary32(4),FloatColumn::Binary32(5),FloatColumn::Binary32(6),FloatColumn::Binary32(7),FloatColumn::Binary32(8)];
const EDGE:&[FloatColumn]=&[FloatColumn::Binary32(7),FloatColumn::Binary32(8)];
const NUMBER:&[FloatColumn]=&[FloatColumn::Binary64(1)];
fn invalid(message:&str)->ValueError{ValueError::new(ValueRefusalKind::InvalidValue,message)}
fn index(row:&SqliteRow,column:usize)->Result<u32>{u32::try_from(row.integer(column)?).map_err(|_|invalid("managed mesh UInt32 range differs"))}
fn optional_index(row:&SqliteRow,column:usize)->Result<Option<u32>>{if row.values.get(column)==Some(&SqliteValue::Null){Ok(None)}else{index(row,column).map(Some)}}
fn flag(row:&SqliteRow,column:usize)->Result<bool>{match row.integer(column)?{0=>Ok(false),1=>Ok(true),_=>Err(invalid("managed mesh boolean range differs"))}}
fn empty()->LowpolyMeshState{LowpolyMeshState{vertices:Vec::new(),halfedges:Vec::new(),faces:Vec::new(),uv_seams:Vec::new(),attributes:Vec::new(),materials:Vec::new(),textures:Vec::new()}}
struct Build(LowpolyMeshState);
impl Drop for Build{fn drop(&mut self){for attribute in&mut self.0.attributes{for value in attribute.values.drain(..){value.retire_decoded();}}for material in self.0.materials.drain(..){material.value.retire_decoded();}}}
fn compare_text(left:&str,right:&str,control:&mut NativeDecodeControl<'_>)->Result<std::cmp::Ordering>{control.scoped_stage(|control|{let count=left.len().min(right.len());control.begin_stage(count)?;for(a,b)in left.bytes().zip(right.bytes()){control.step()?;let order=a.cmp(&b);if !order.is_eq(){return Ok(order)}}Ok(left.len().cmp(&right.len()))})}
fn sort_text(values:&mut[&str],control:&mut NativeDecodeControl<'_>)->Result<()>{
 fn sift(values:&mut[&str],mut root:usize,end:usize,control:&mut NativeDecodeControl<'_>)->Result<()>{loop{control.step()?;let Some(left)=root.checked_mul(2).and_then(|value|value.checked_add(1)).filter(|value|*value<end)else{return Ok(())};let mut child=left;if left+1<end&&compare_text(values[left],values[left+1],control)?.is_lt(){child=left+1;}if !compare_text(values[root],values[child],control)?.is_lt(){return Ok(())}values.swap(root,child);root=child;}}
 control.scoped_stage(|control|{control.begin_stage(0)?;for root in(0..values.len()/2).rev(){sift(values,root,values.len(),control)?;}for end in(1..values.len()).rev(){values.swap(0,end);sift(values,0,end,control)?;}Ok(())})
}
fn unique<'a>(names:impl ExactSizeIterator<Item=&'a str>,control:&mut NativeDecodeControl<'_>)->Result<()>{let mut ordered=control.allocate_vec(names.len())?;for name in names{control.step()?;ordered.push(name);}sort_text(&mut ordered,control)?;for pair in ordered.windows(2){control.step()?;if compare_text(pair[0],pair[1],control)?.is_eq(){return Err(invalid("managed mesh named namespace contains duplicates"))}}Ok(())}
fn octets(rows:&mut Rows<'_>,table:&str,parent:i64,control:&mut NativeDecodeControl<'_>)->Result<Vec<u8>>{let source=rows.group(table,parent,control)?;let mut output=control.allocate_vec(source.len())?;for row in source{control.step()?;output.push(u8::try_from(row.integer(3)?).map_err(|_|invalid("managed mesh octet range differs"))?);}Ok(output)}
struct Frame<'a>{rows:Vec<&'a SqliteRow>,next:usize,value:Value,object:bool}
impl Drop for Frame<'_>{fn drop(&mut self){std::mem::replace(&mut self.value,Value::Null).retire_decoded();}}
fn push<'a>(frames:&mut Vec<Frame<'a>>,frame:Frame<'a>,control:&mut NativeDecodeControl<'_>)->Result<()>{if frames.len()==frames.capacity(){let capacity=frames.capacity().max(1).checked_mul(2).ok_or_else(||ValueError::new(ValueRefusalKind::OwnershipLimit,"managed mesh intrinsic frontier overflow"))?;let mut replacement=control.allocate_vec(capacity)?;for _ in 0..frames.len(){control.step()?;}replacement.extend(std::mem::take(frames));*frames=replacement;}frames.push(frame);Ok(())}
fn intrinsic(root:i64,rows:&mut Rows<'_>,control:&mut NativeDecodeControl<'_>)->Result<Value>{
 let mut pending=Vec::new();let mut next=root;
 'enter:loop{control.step()?;let row=rows.take("lowpoly_mesh_value",next,control)?;let value=match row.text(1)?{
  "null"=>Value::Null,
  "boolean"=>Value::Bool(flag(rows.take("lowpoly_mesh_boolean",next,control)?,1)?),
  "unsigned"=>{let source=rows.take("lowpoly_mesh_unsigned",next,control)?.text(1)?;if source.is_empty()||source.len()>20||(source.len()>1&&source.starts_with('0'))||!source.bytes().all(|byte|byte.is_ascii_digit()){return Err(invalid("managed mesh unsigned decimal differs"))}Value::Number(Number::UInt(source.parse().map_err(|_|invalid("managed mesh unsigned decimal overflow"))?))},
  "signed"=>Value::Number(Number::Int(rows.take("lowpoly_mesh_signed",next,control)?.integer(1)?)),
  "float"=>Value::Number(Number::Float(FloatRow::new(rows.take("lowpoly_mesh_float",next,control)?,NUMBER)?.real(1)?)),
  "text"=>{let source=rows.take("lowpoly_mesh_text",next,control)?.text(1)?;Value::String(control.copy_text(source)?)},
  "bytes"=>{rows.take("lowpoly_mesh_bytes",next,control)?;Value::Bytes(octets(rows,"lowpoly_mesh_bytes_octet",next,control)?)},
  kind @ ("array"|"object")=>{let object=kind=="object";let children=rows.group(if object{"lowpoly_mesh_object_member"}else{"lowpoly_mesh_array_member"},next,control)?;let value=if object{Value::Object(control.allocate_vec(children.len())?)}else{Value::Array(control.allocate_vec(children.len())?)};if children.is_empty(){value}else{let first=children[0].integer(if object{4}else{3})?;push(&mut pending,Frame{rows:children,next:0,value,object},control)?;next=first;continue 'enter}},
  _=>return Err(invalid("managed mesh intrinsic variant differs")),
 };let mut value=DecodedValue::new(value,Value::retire_decoded);
 loop{let Some(mut frame)=pending.pop()else{return Ok(value.take())};control.step()?;let source=frame.rows[frame.next];if frame.object{let name=control.copy_text(source.text(3)?)?;let Value::Object(entries)=&mut frame.value else{unreachable!()};entries.push((name,value.take()));}else{let Value::Array(entries)=&mut frame.value else{unreachable!()};entries.push(value.take());}frame.next+=1;if frame.next<frame.rows.len(){next=frame.rows[frame.next].integer(if frame.object{4}else{3})?;push(&mut pending,frame,control)?;continue 'enter;}value=DecodedValue::new(std::mem::replace(&mut frame.value,Value::Null),Value::retire_decoded);}
 }
}

/// 📥️ Restore every managed field without consulting independently retained source text.
pub fn reconstruct(owner:i64,rows:&mut Rows<'_>,control:&mut NativeDecodeControl<'_>)->Result<Option<LowpolyMeshState>>{control.scoped_stage(|control|{control.begin_stage(0)?;if !rows.contains("lowpoly_mesh_state",owner){return Ok(None)}rows.take("lowpoly_mesh_state",owner,control)?;let mut build=Build(empty());
 let source=rows.group("lowpoly_mesh_vertex",owner,control)?;build.0.vertices=control.allocate_vec(source.len())?;for row in source{control.step()?;let scalar=FloatRow::new(row,VERTEX)?;let normal=if scalar.is_null(6)?{if !scalar.is_null(7)?||!scalar.is_null(8)?{return Err(invalid("managed mesh optional normal is incomplete"))}None}else{if scalar.is_null(7)?||scalar.is_null(8)?{return Err(invalid("managed mesh optional normal is incomplete"))}Some([scalar.binary32(6)?,scalar.binary32(7)?,scalar.binary32(8)?])};build.0.vertices.push(LowpolyMeshVertex{position:[scalar.binary32(3)?,scalar.binary32(4)?,scalar.binary32(5)?],normal,halfedge:optional_index(row,9)?});}
 let source=rows.group("lowpoly_mesh_halfedge",owner,control)?;build.0.halfedges=control.allocate_vec(source.len())?;for row in source{control.step()?;let scalar=FloatRow::new(row,EDGE)?;build.0.halfedges.push(LowpolyMeshHalfedge{vertex:index(row,3)?,twin:optional_index(row,4)?,next:index(row,5)?,face:optional_index(row,6)?,uv:[scalar.binary32(7)?,scalar.binary32(8)?]});}
 let source=rows.group("lowpoly_mesh_face",owner,control)?;build.0.faces=control.allocate_vec(source.len())?;for row in source{control.step()?;build.0.faces.push(LowpolyMeshFace{halfedge:index(row,3)?,smooth:flag(row,4)?,flipped:flag(row,5)?});}
 let source=rows.group("lowpoly_mesh_seam",owner,control)?;build.0.uv_seams=control.allocate_vec(source.len())?;for row in source{control.step()?;build.0.uv_seams.push(index(row,3)?);}let mut seams=control.allocate_vec(build.0.uv_seams.len())?;seams.extend_from_slice(&build.0.uv_seams);sort(&mut seams,control,|a,b|Ok(a.cmp(b)))?;for pair in seams.windows(2){control.step()?;if pair[0]==pair[1]{return Err(invalid("managed mesh seam identities are repeated"))}}
 let source=rows.group("lowpoly_mesh_attribute",owner,control)?;build.0.attributes=control.allocate_vec(source.len())?;for row in source{control.step()?;let domain=match row.text(4)?{"vertex"=>Domain::Vertex,"corner"=>Domain::Corner,"face"=>Domain::Face,"edge"=>Domain::Edge,_=>return Err(invalid("managed mesh attribute domain differs"))};let semantic=match row.text(5)?{"normal"=>Semantic::Normal,"uv"=>Semantic::Uv,"color"=>Semantic::Color,"material"=>Semantic::Material,"custom"=>Semantic::Custom,_=>return Err(invalid("managed mesh attribute semantic differs"))};let interpolation=match row.text(6)?{"linear"=>Interpolation::Linear,"nearest"=>Interpolation::Nearest,"constant"=>Interpolation::Constant,_=>return Err(invalid("managed mesh attribute interpolation differs"))};let indices=rows.group("lowpoly_mesh_attribute_index",row.rowid,control)?;let has_indices=flag(row,7)?;if !has_indices&&!indices.is_empty(){return Err(invalid("managed mesh absent indices own index rows"))}let mut output=control.allocate_vec(indices.len())?;for index_row in indices{control.step()?;output.push(index(index_row,3)?);}let name=control.copy_text(row.text(3)?)?;let samples=rows.group("lowpoly_mesh_attribute_sample",row.rowid,control)?;let values=control.allocate_vec(samples.len())?;build.0.attributes.push(LowpolyMeshAttribute{name,domain,semantic,interpolation,indices:has_indices.then_some(output),values});let target=build.0.attributes.last_mut().expect("attribute inserted");for sample in samples{target.values.push(intrinsic(sample.integer(3)?,rows,control)?);}}
 let source=rows.group("lowpoly_mesh_material",owner,control)?;build.0.materials=control.allocate_vec(source.len())?;for row in source{control.step()?;let name=control.copy_text(row.text(3)?)?;let value=intrinsic(row.integer(4)?,rows,control)?;build.0.materials.push(LowpolyMeshMaterial{name,value});}
 let source=rows.group("lowpoly_mesh_texture",owner,control)?;build.0.textures=control.allocate_vec(source.len())?;for row in source{control.step()?;let name=control.copy_text(row.text(3)?)?;let mime=control.copy_text(row.text(4)?)?;let bytes=octets(rows,"lowpoly_mesh_texture_octet",row.rowid,control)?;build.0.textures.push(LowpolyMeshTexture{name,mime,bytes});}
 unique(build.0.attributes.iter().map(|entry|entry.name.as_str()),control)?;unique(build.0.materials.iter().map(|entry|entry.name.as_str()),control)?;unique(build.0.textures.iter().map(|entry|entry.name.as_str()),control)?;
 Ok(Some(std::mem::replace(&mut build.0,empty())))
})}
