[package]
name = "flow_core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["rlib", "cdylib"]
path = "lib.rs"

[dependencies]
vcs = { path = "../../vcs/rs" }
flow_module_brep = { path = "../module/brep", default-features = false }
flow_module_draw = { path = "../module/draw", default-features = false }
flow_module_bim = { path = "../module/bim", default-features = false }
flow_module_core = { path = "../module/core", default-features = false }
flow_module_dictionary = { path = "../module/dictionary", default-features = false }
flow_module_list = { path = "../module/list", default-features = false }
flow_module_logic = { path = "../module/logic", default-features = false }
flow_module_math = { path = "../module/math", default-features = false }
flow_module_text = { path = "../module/text", default-features = false }
kernel_3d_engine = { path = "../../kernel/3d/brep/engine", features = ["parallel"] }
neural_engine = { path = "../../neural/engine", features = ["parallel"] }
mathematical_graph_port_directed_dag = { path = "../../mathematical/graph/port/directed/dag" }
infinite_cavas = { path = "../../infinite/cavas/rs" }
ui_styling = { path = "../../ui/styling/rs" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.83"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.71"
web-sys = { version = "0.3.98", features = ["HtmlCanvasElement"] }
