# Custom semio extension of the [relay specs](https://relay.dev/docs/guides/graphql-server-specification)

#region Scalars

scalar Timestamp

#endregion Scalars

#region Entities

interface Node {
  id: ID!
}

interface Entity implements Node { # Our own extension ontop of the relay specs
  id: ID!
  hash: String!
  owner: Entity
  owns: EntityConnection
}

interface EntityEdge {
  cursor: String! # an entity id
  # node: ENTITY
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String # start at this entity
  endCursor: String # end at this entity
}

interface EntityConnection {
  # edges: [ENTITYEdge]
  pageInfo: PageInfo!
  hash: String! # Our own extension ontop of the relay specs
}

union EntityConnection =
  AlternativeConnection
  | AttributeDiffConnection
  | AttributeListingConnection
  | AuthorConnection
  | BridgeConnection
  | ChangeConnection
  | CheckpointConnection
  | ConnectorConnection
  | CoordinateConnection
  | DesignConnection
  | DraftConnection
  | DiffsConnection
  | FileConnection
  | FolderConnection
  | GraphConnection
  | KitConnection
  | LocationConnection
  | LocationDiffConnection
  | LocationModificationConnection
  | OffsetConnection
  | PieceListingConnection
  | PlaneConnection
  | PlaneDiffConnection
  | PlaneModificationConnection
  | PlaceConnection
  | PlaceDiffConnection
  | PlaceModificationConnection
  | PointConnection
  | PointDiffConnection
  | PositionConnection
  | PositionModificationConnection
  | RepresentationConnection
  | SessionConnection
  | TransactionConnection
  | TypeConnection
  | VectorConnection

union DiffConnection =
  DiffsConnection
  | PlaneDiffConnection
  | PointDiffConnection
  | AttributeDiffConnection
  | LocationDiffConnection
  | PlaceDiffConnection

union DiffsOwner = Diff | Operation | Change

type DiffsEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type DiffsConnection implements EntityConnection {
  edges: [DiffsEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#region Weak // Weak entities have hash as id

# interface WeakEntity implements Entity {
#   id: ID! # hash
# }

# interface Modification implements WeakEntity {
  # FIELD: NULLABLE FIELD // if the field was modified then return the modified value
  # removeNULLABLEFIELD: Boolean // use this if the field is by default nullable to indicate that it was removed
# }

union Modification = PlaneModification | AttributeModification

union DiffOwner = Diffs | Change | Operation

interface Diff implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # DiffOwner
  owns: EntityConnection

  before: Entity!
  modification: Modification!
  after: Entity!
}

type PlaneDiff implements Diff {
  id: ID! # hash
  hash: String!
  owner: Entity # DiffOwner
  owns: EntityConnection

  before: Plane!
  modification: PlaneModification!
  after: Plane!
}

type Diffs implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # DiffsOwner
  owns: EntityConnection

  removed: EntityConnection
  diffs: DiffConnection
  added: EntityConnection
}

#region Vector

input VectorInput {
  x: Float!
  y: Float!
  z: Float!
}

union VectorOwner = Plane | PlaneModification
union VectorOwned = Plane | PlaneModification

type VectorEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type Vector implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # VectorOwner
  owns: EntityConnection # VectorOwned

  x: Float!
  y: Float!
  z: Float!
}

type VectorConnection implements EntityConnection {
  edges: [VectorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Vector

#region Point

input PointInput {
  x: Float!
  y: Float!
  z: Float!
}

union PointOwner = Plane | PlaneModification
union PointOwned = Plane | PlaneModification

type PointEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type Point implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # PointOwner
  owns: EntityConnection

  x: Float!
  y: Float!
  z: Float!
}

type PointConnection implements EntityConnection {
  edges: [PointEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Point

#region Coordinate

input CoordinateInput {
  u: Float!
  v: Float!
}

union CoordinateOwner = Position | PositionModification
union CoordinateOwned = Position | PositionModification

type CoordinateEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type Coordinate implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # CoordinateOwner
  owns: EntityConnection # CoordinateOwned

  u: Float!
  v: Float!
}

type CoordinateConnection implements EntityConnection {
  edges: [CoordinateEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Coordinate

#region Offset

input OffsetInput {
  u: Float!
  v: Float!
}

union OffsetOwner = Position | PositionModification
union OffsetOwned = Position | PositionModification

type OffsetEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type Offset implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # OffsetOwner
  owns: EntityConnection # OffsetOwned

  u: Float!
  v: Float!
}

type OffsetConnection implements EntityConnection {
  edges: [OffsetEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Offset

#region Plane

input PlaneInput {
  origin: PointInput!
  xAxis: VectorInput!
  yAxis: VectorInput!
}

#endregion Plane

union PlaneOwner = Piece | PieceModification | PlaneDiff
union PlaneOwned = Point | Vector

type Plane implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # PlaneOwner
  owns: EntityConnection # PlaneOwned

  origin: Point!
  xAxis: Vector!
  yAxis: Vector!
}

union PlaneModificationOwner = PieceModification | PositionModification | LocationModification | PlaceModification | AttributeModification | PlaneDiff
union PlaneModificationOwned = Point | Vector | Plane

type PlaneModification implements Entity { # implements Modification
  id: ID! # hash
  hash: String!
  owner: Entity # PlaneModificationOwner
  owns: EntityConnection

  origin: Point
  xAxis: Vector
  yAxis: Vector
}

#endregion Plane

#region Position

input PositionInput {
  center: CoordinateInput!
  plane: PlaneInput!
}

union PositionOwner = Piece | PositionModification | Plane | PositionDiff

type Position implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # PositionOwner
  owns: EntityConnection

  center: Coordinate!
  plane: Plane!
}

union PositionModificationOwner = PieceModification | PositionDiff

type PositionModification implements Entity { # implements Modification
  id: ID! # hash
  hash: String!
  owner: Entity # PositionModificationOwner
  owns: EntityConnection
  center: Coordinate
  plane: Plane
}

type PositionDiff implements Diff {
  id: ID! # hash
  hash: String!
  owner: Entity
  owns: EntityConnection
  before: Entity! # Position
  modification: PositionModification!
  after: Entity! # Position
}

#endregion Position

#region Location

input LocationInput {
  longitude: Float!
  latitude: Float!
  altitude: Float
}

union LocationOwner = Place | Kit | Design

type Location implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # LocationOwner
  owns: EntityConnection
  longitude: Float!
  latitude: Float!
  altitude: Float!
}

union LocationModificationOwner = PlaceModification | LocationDiff

type LocationModification implements Entity { # implements Modification
  id: ID! # hash
  hash: String!
  owner: Entity # LocationModificationOwner
  owns: EntityConnection
  longitude: Float
  latitude: Float
  altitude: Float
}

type LocationDiff implements Diff {
  id: ID! # hash
  hash: String!
  owner: Entity
  owns: EntityConnection
  before: Entity! # Location
  modification: LocationModification!
  after: Entity! # Location
}

#endregion Location

#region Attribute

input AttributeInput {
  key: String!
  value: String
  definition: String
}

union AttributeOwner = Piece | Connector | Representation | Kit | Design | Type | AttributeDiff | PositionModification | PieceModification

type Attribute implements Entity { # implements WeakEntity
  id: ID! # hash
  hash: String!
  owner: Entity # AttributeOwner
  owns: EntityConnection
  key: String!
  value: String!
  definition: String!
}

union AttributeModificationOwner = PieceModification | Connector | Representation | Kit | Design | Type | AttributeDiff

type AttributeModification implements Entity { # implements Modification
  id: ID! # hash
  hash: String!
  owner: Entity # AttributeModificationOwner
  owns: EntityConnection
  key: String
  value: String
  definition: String
}

type AttributeDiff implements Diff {
  id: ID! # hash
  hash: String!
  owner: Entity
  owns: EntityConnection
  before: Entity! # Attribute
  modification: AttributeModification!
  after: Entity! # Attribute
}

type AttributeEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type AttributeDiffConnection implements EntityConnection {
  edges: [AttributeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union AttributesDiffOwner = Diff | Operation | Change

type AttributesDiff implements Diffs {
  id: ID! # hash
  hash: String!
  owner: Entity # AttributesDiffOwner
  owns: EntityConnection
  removed: EntityConnection # Attribute
  diffs: DiffConnection # AttributeDiffConnection
  added: EntityConnection # Attribute
}

#endregion Attribute

#endregion Weak

#region Strong

# interface StrongEntity implements Entity {
#   id: ID! # uuidv7
#   hash: String!
#   owner: Entity # ENTITYKIND
#   owns: EntityConnection # ENTITYKIND
# }

union Input = RenamedKitInput | ChangedDescriptionInput | CreatedFixedPieceInput | FixedPieceInput | DraggedPieceInput

union OperationOwner = Change

interface Operation implements Entity { # implements StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: Entity # Change
  owns: EntityConnection # Input
  diff: Diff!
  input: Input
}

#region Kit

#region Place

union PlaceOwner = Kit | Checkpoint | Graph

type Place implements Entity { # implements StrongEntity
  id: ID!
  hash: String!
  owner: Entity! # PlaceOwner
  owns: EntityConnection
  name: String
  location: Location
}

union PlaceModificationOwner = PlaceDiff | Place

type PlaceModification implements Entity { # implements Modification
  id: ID! # hash
  hash: String!
  owner: Entity # PlaceModificationOwner
  owns: EntityConnection
  name: String
  location: LocationModification
  removeLocation: Boolean
}

type PlaceDiff implements Diff {
  id: ID! # hash
  hash: String!
  owner: Entity
  owns: EntityConnection
  before: Place!
  modification: PlaceModification!
  after: Place!
}

#endregion Place

#region Folder

union FolderOwner = Kit | Folder
union FolderOwned = Folder | File | Design | Type

type Folder implements Entity { # implements StrongEntity
  id: ID!
  hash: String!
  owner: Entity! # FolderOwner
  owns: EntityConnection # FolderOwned
  name: String!
  path: String!
  description: String!
}

#endregion Folder

#region File

union FileOwner = Kit | Folder

type File implements Entity { # implements StrongEntity
  id: ID!
  hash: String!
  owner: Entity! # FileOwner
  owns: EntityConnection # Nothing
  url: String!
  mime: String
  size: Int
  description: String
  created: Timestamp
  updated: Timestamp
}

#endregion File

#region Author

union AuthorOwner = Kit | Checkpoint | Graph | Session

type Author implements Entity {
  id: ID!
  hash: String!
  owner: Entity # AuthorOwner
  owns: EntityConnection
  name: String!
  email: String!
  role: String
  rank: Int
  drafts: [Draft!]!
  transactions: [Transaction!]!
  checkpoints: [Checkpoint!]!
}

#endregion Author

#region Prop

type Prop {
  id: ID!
  key: String!
  value: String!
  unit: String
  quality: Quality
}

#endregion Prop

#region Benchmark

type Benchmark {
  id: ID!
  name: String!
  min: Float
  max: Float
  minExcluded: Boolean
  maxExcluded: Boolean
}

#endregion Benchmark

#region Quality

type Quality {
  id: ID!
  key: String!
  value: String
  unit: String
  definition: String
  description: String
  benchmarks: [Benchmark!]!
}

#endregion Quality

#region Tag

type Tag {
  id: ID!
  name: String!
  order: Int
}

#endregion Tag

#region Concept

type Concept {
  id: ID!
  name: String!
  description: String
  order: Int
}

#endregion Concept

#region Stat

type Stat {
  id: ID!
  key: String!
  value: String!
  unit: String
  description: String
}

#endregion Stat

#region Type

union ConnectorOwner = Type

type Connector implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # ConnectorOwner
  owns: EntityConnection
  code: String!
  description: String
  portId: ID
  qualities: [Quality!]!
  attributes: [Attribute!]!
}

union RepresentationOwner = Type

type Representation implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # RepresentationOwner
  owns: EntityConnection
  url: String!
  description: String
  file: File
  tags: [Tag!]!
  qualities: [Quality!]!
  attributes: [Attribute!]!
}

union TypeOwner = Kit

type Type implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # TypeOwner
  owns: EntityConnection
  name: String!
  description: String
  icon: String
  image: String
  unit: String
  created: Timestamp
  updated: Timestamp
  connectors: [Connector!]!
  connector(id: ID!): Connector
  representations: [Representation!]!
  representation(id: ID!): Representation
  bestRepresentation(tagIds: [ID!]!): Representation
  authors: [Author!]!
  concepts: [Concept!]!
  tags: [Tag!]!
  qualities: [Quality!]!
  props: [Prop!]!
  attributes: [Attribute!]!
  stats: [Stat!]!
}

#endregion Type

#region Design

#region Layer

type Layer {
  id: ID!
  name: String!
  description: String
  color: String
  order: Int
  visible: Boolean
  locked: Boolean
}

#endregion Layer

#region Group

type Group {
  id: ID!
  name: String!
  description: String
  color: String
  icon: String
  pieces: [Piece!]!
}

#endregion Group

#region Piece

enum PieceConnectionKind {
  FIXED
  CONNECTED
}

union Blueprint = Type | Design

union PieceOwner = Type | Design | PieceModification | Piece

type Piece implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # PieceOwner
  owns: EntityConnection
  name: String
  description: String
  position: Position
  scale: Float
  blueprint: Blueprint!
  connectionKind: PieceConnectionKind
  flatPosition: Position!
  replaceableBlueprint: [Blueprint!]!
  parentConnection: Connection
  childConnections: [Connection!]!
  parentPiece: Piece
  childPieces: [Piece!]!
  depth: Int!
  path: [Piece!]!
  props: [Prop!]!
  attributes: [Attribute!]!
}

union PieceBridgeOwner = Design

type Connection implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # PieceBridgeOwner
  owns: EntityConnection
  connected: Side!
  connecting: Side!
  gap: Float
  shift: Float
  rise: Float
  rotation: Float
  turn: Float
  tilt: Float
  u: Float
  v: Float
  description: String
  attributes: [Attribute!]!
}

#region Operations

type CreatedFixedPieceInput {
  designId: ID!
  blueprintId: ID!
  position: Position!
  name: String
  description: String
}

type CreatedFixedPiece implements Operation & Entity {
  id: ID!
  hash: String!
  owner: Entity! # CreatedFixedPieceOwner
  owns: EntityConnection
  input: CreatedFixedPieceInput!
  diff: Diff!
  piece: Piece!
}

union CreatedFixedPieceOwner = Change

type FixedPieceInput {
  designId: ID!
  pieceId: ID!
}

type FixedPiece implements Operation & Entity {
  id: ID!
  hash: String!
  owner: Entity! # FixedPieceOwner
  owns: EntityConnection
  input: FixedPieceInput!
  diff: Diff!
  piece: Piece!
}

union FixedPieceOwner = Change

type DraggedPieceInput {
  designId: ID!
  pieceIds: [ID!]!
  offset: Offset!
}

type DraggedPiece implements Operation & Entity {
  id: ID!
  hash: String!
  owner: Entity! # DraggedPieceOwner
  owns: EntityConnection
  input: DraggedPieceInput!
  diff: Diff!
  pieces: [Piece!]!
}

union DraggedPieceOwner = Change

#endregion Operations

#endregion Piece

#region Connection

#region Side

type Side {
  id: ID!
  piece: Piece!
  port: Connector
  designPiece: Piece
  connector: Connector
}

#endregion Side

#endregion Connection

union DesignOwner = Kit

type Design implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # DesignOwner
  owns: EntityConnection
  name: String!
  description: String
  icon: String
  image: String
  place: Place
  unit: String
  created: Timestamp
  updated: Timestamp
  pieces: [Piece!]!
  piece(id: ID!): Piece
  connections: [Connection!]!
  connection(id: ID!): Connection
  layers: [Layer!]!
  groups: [Group!]!
  authors: [Author!]!
  concepts: [Concept!]!
  tags: [Tag!]!
  qualities: [Quality!]!
  props: [Prop!]!
  attributes: [Attribute!]!
  stats: [Stat!]!
  qualitySum(qualityId: ID!): Float!
  references: [Design!]!
  referencedBy: [Piece!]!
}

#endregion Design

union KitOwner = Graph | Checkpoint | Alternative

type Kit implements Entity {
  id: ID!
  hash: String!
  owner: Entity # KitOwner
  owns: EntityConnection
  checkpoint: Checkpoint
  draft: Draft
  transaction: Transaction
  name: String!
  description: String
  icon: String
  image: String
  preview: String
  remote: String
  homepage: String
  license: String
  uri: String
  created: Timestamp
  updated: Timestamp
  version: String
  design(id: ID!): Design
  designs: [Design!]!
  type(id: ID!): Type
  types: [Type!]!
  files: [File!]!
  folders: [Folder!]!
  authors: [Author!]!
  concepts: [Concept!]!
  tags: [Tag!]!
  qualities: [Quality!]!
  props: [Prop!]!
  attributes: [Attribute!]!
  stats: [Stat!]!
}

#region Operations

type RenamedKitInput {
  name: String!
}

type RenamedKit implements Operation & Entity {
  id: ID!
  hash: String!
  owner: Entity! # RenamedKitOwner
  owns: EntityConnection
  input: RenamedKitInput!
  diff: Diff!
  kit: Kit!
}

union RenamedKitOwner = Change

type ChangedDescriptionInput {
  entityId: ID!
  description: String!
}

type ChangedDescription implements Operation & Entity {
  id: ID!
  hash: String!
  owner: Entity! # ChangedDescriptionOwner
  owns: EntityConnection
  input: ChangedDescriptionInput!
  diff: Diff!
  entity: Entity!
}

union ChangedDescriptionOwner = Change

#endregion Operations

#endregion Kit

#region 🔖PlaneDiffConnection

type PlaneDiffEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaneDiffConnection implements EntityConnection {
  edges: [PlaneDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion 🔖PlaneDiffConnection

#region 🔖PointDiffConnection

type PointDiffEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PointDiffConnection implements EntityConnection {
  edges: [PointDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion 🔖PointDiffConnection

#region 🔖LocationDiffConnection

type LocationDiffEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type LocationDiffConnection implements EntityConnection {
  edges: [LocationDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion 🔖LocationDiffConnection

#region 🔖PlaceDiffConnection

type PlaceDiffEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaceDiffConnection implements EntityConnection {
  edges: [PlaceDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion 🔖PlaceDiffConnection

#region 🔖EntityRelayEdgesConnections

type AlternativeEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type AlternativeConnection implements EntityConnection {
  edges: [AlternativeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type AttributeListingEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type AttributeListingConnection implements EntityConnection {
  edges: [AttributeListingEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type AuthorEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type AuthorConnection implements EntityConnection {
  edges: [AuthorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type BridgeEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type BridgeConnection implements EntityConnection {
  edges: [BridgeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type ChangeEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type ChangeConnection implements EntityConnection {
  edges: [ChangeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type CheckpointEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type CheckpointConnection implements EntityConnection {
  edges: [CheckpointEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type ConnectorEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type ConnectorConnection implements EntityConnection {
  edges: [ConnectorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type DesignEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type DesignConnection implements EntityConnection {
  edges: [DesignEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type DraftEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type DraftConnection implements EntityConnection {
  edges: [DraftEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type FileEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type FileConnection implements EntityConnection {
  edges: [FileEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type FolderEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type FolderConnection implements EntityConnection {
  edges: [FolderEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type GraphEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type GraphConnection implements EntityConnection {
  edges: [GraphEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type KitEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type KitConnection implements EntityConnection {
  edges: [KitEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type LocationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type LocationConnection implements EntityConnection {
  edges: [LocationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type LocationModificationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type LocationModificationConnection implements EntityConnection {
  edges: [LocationModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PieceListingEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PieceListingConnection implements EntityConnection {
  edges: [PieceListingEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaneEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaneConnection implements EntityConnection {
  edges: [PlaneEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaneModificationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaneModificationConnection implements EntityConnection {
  edges: [PlaneModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaceEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaceConnection implements EntityConnection {
  edges: [PlaceEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaceModificationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PlaceModificationConnection implements EntityConnection {
  edges: [PlaceModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PositionEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PositionConnection implements EntityConnection {
  edges: [PositionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PositionModificationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type PositionModificationConnection implements EntityConnection {
  edges: [PositionModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type RepresentationEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type RepresentationConnection implements EntityConnection {
  edges: [RepresentationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type SessionEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type SessionConnection implements EntityConnection {
  edges: [SessionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type TransactionEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type TransactionConnection implements EntityConnection {
  edges: [TransactionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type TypeEdge implements EntityEdge {
  cursor: String!
  node: Entity!
}

type TypeConnection implements EntityConnection {
  edges: [TypeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion 🔖EntityRelayEdgesConnections

#endregion Entities

#region VCS

union ChangeOwner = Transaction | Draft | Checkpoint

type Change implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # ChangeOwner
  owns: EntityConnection
  description: String
  origin: String
  forwards: [Operation!]!
  backwards: [Operation!]!
  sequenceNumber: Int!
}

union TransactionOwner = Draft

type Transaction implements Entity {
  id: ID!
  hash: String!
  owner: Entity # TransactionOwner
  owns: EntityConnection
  changes: [Change!]!
}

union DraftOwner = Author

type Draft implements Entity {
  id: ID!
  hash: String!
  owner: Entity! # DraftOwner
  owns: EntityConnection
  parentCheckpoint: Checkpoint
  targetAlternative: Alternative
  openTransaction: Transaction
  finalizedTransactions: [Transaction!]!
  redoTransactions: [Transaction!]!
  changes: [Change!]!
  canUndo(steps: Int!): Boolean!
  canRedo(steps: Int!): Boolean!
}

union CheckpointOwner = Alternative | Graph | Kit | Author

type Checkpoint implements Entity {
  id: ID!
  hash: String!
  owner: Entity # CheckpointOwner
  owns: EntityConnection
  timestamp: Timestamp
  authors: [Author!]!
  root: Kit
  parentCheckpoint: Checkpoint
  message: String
  isRelease: Boolean!
  changeCount: Int!
}

union AlternativeOwner = Graph

type Alternative implements Entity {
  id: ID!
  hash: String!
  owner: Entity # AlternativeOwner
  owns: EntityConnection
  name: String!
  start: Checkpoint!
  checkpoints: [Checkpoint!]!
  store: Kit!
  draft: Draft
  transaction: Transaction
}

union GraphOwner = Session

type Graph implements Entity {
  id: ID!
  hash: String!
  owner: Entity # GraphOwner
  owns: EntityConnection
  theKit: Kit
  alternative(id: ID!): Alternative
  alternatives: [Alternative!]!
  checkpoint(id: ID!): Checkpoint
  checkpoints: [Checkpoint!]!
  release(id: ID!): Checkpoint
  releases: [Checkpoint!]!
}

union SessionOwner = Graph | Checkpoint | Alternative

type Session implements Entity {
  id: ID!
  hash: String!
  owner: Entity # SessionOwner
  owns: EntityConnection
  startedAt: Timestamp
  drafts: [Draft!]!
}

type ReadVersion {
  checkpoint: Checkpoint
  change: Change
  operation: Operation
}

type WriteVersion {
  draft: Draft
  transaction: Transaction
  checkpoint: Checkpoint
  change: Change
  operation: Operation
}

enum ConflictKind {

}

type Conflict {
  id: ID!
  authoritativeVersion: ReadVersion
  transactionVersion: WriteVersion
  reason: String!
  createdAt: Timestamp!
}

#endregion VCS

#region Schema

type Query {
  session: Session!
  wip: Graph!
  authoritative: Graph
  conflicts: [Conflict!]!
  node(id: ID!): Node
  entity(id: ID!): Entity
}

type Mutation {
  renameKit(draftId: ID!, transactionId: ID!, name: String!): ID!
  changeDescription(draftId: ID!, transactionId: ID!, description: String!): ID!
  createFixedPiece(draftId: ID!, transactionId: ID!, designId: ID!, position: PositionInput!, name: String, description: String): ID!
  fixPiece(draftId: ID!, transactionId: ID!, designId: ID!, pieceId: ID!): ID!
}

type Subscription {
  commandSucceeded: Command!
  operationSucceeded: Operation!
  operationFailed: Error!
  kitRenamed: RenamedKit!
  descriptionChanged: ChangedDescription!
  createdFixedPiece: CreatedFixedPiece!
  fixedPiece: FixedPiece!
  draggedPiece: DraggedPiece!
  error: Error!
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

#endregion Schema
