# Custom semio extension of the [relay specs](https://relay.dev/docs/guides/graphql-server-specification)

#region Scalars

scalar Timestamp

#endregion Scalars

#region Entities

interface Node {
  id: ID!
}

interface Entity implements Node { # Our own extension ontop of the relay specs
  id: ID!
  hash: String!
  # owner: ENTITY
  # ownerENTITY: OwnerENTITY
  ownerEntity: OwnerEntity
  # owns: ENTITYConnection
  ownedEntities: OwnedEntityConnection
}

interface EntityEdge {
  cursor: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String # start at this entity
  endCursor: String # end at this entity
}

interface EntityConnectionInterface {
  # edges: [ENTITYEdge]
  pageInfo: PageInfo!
  hash: String! # Our own extension ontop of the relay specs
}

#region Weak // Weak entities have hash as id

# interface WeakEntity implements Entity {
#   id: ID! # hash
# }

#region Diffs

# interface Modification implements WeakEntity {
#   FIELD: NULLABLE FIELD // if the field was modified then return the modified value
#   removeNULLABLEFIELD: Boolean // use this if the field is by default nullable to indicate that it was removed
# }

union Modification = PlaneModification | AttributeModification

union DiffOwner = Diffs | Change | Operation
union DiffOwned = PlaneDiff | PointDiff | AttributeDiff | LocationDiff | PlaceDiff

interface Diff implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Entity!
  modification: Modification!
  after: Entity!
}

union DiffsOwner = Diff | Operation | Change
union DiffsOwned = Diffs | PlaneDiff | PointDiff | AttributeDiff | LocationDiff | PlaceDiff

type Diffs implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffsOwner!
  ownerDiff: Diff
  ownerOperation: Operation
  ownerChange: Change
  ownerEntity: OwnerEntity # DiffsOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Fields
  removed: EntityConnection
  diffs: DiffConnection
  added: EntityConnection
}

type DiffsEdge implements EntityEdge {
  cursor: String!
  node: Diffs!
}

type DiffsConnection implements EntityConnectionInterface {
  edges: [DiffsEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Diffs

#region Vector

input VectorInput {
  x: Float!
  y: Float!
  z: Float!
}

union VectorOwner = Plane | PlaneModification
union VectorOwned = Plane | PlaneModification

type Vector implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: VectorOwner!
  ownerPlane: Plane
  ownerPlaneModification: PlaneModification
  ownerEntity: OwnerEntity # VectorOwner
  ownedEntities: OwnedEntityConnection # VectorOwned
  # Fields
  x: Float!
  y: Float!
  z: Float!
}

type VectorEdge implements EntityEdge {
  cursor: String!
  node: Vector!
}

type VectorConnection implements EntityConnectionInterface {
  edges: [VectorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Vector

#region Point

input PointInput {
  x: Float!
  y: Float!
  z: Float!
}

union PointOwner = Plane | PlaneModification
union PointOwned = Plane | PlaneModification

type Point implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: PointOwner!
  ownerPlane: Plane
  ownerPlaneModification: PlaneModification
  ownerEntity: OwnerEntity # PointOwner
  ownedEntities: OwnedEntityConnection # PointOwned
  # Fields
  x: Float!
  y: Float!
  z: Float!
}

type PointEdge implements EntityEdge {
  cursor: String!
  node: Point!
}

type PointConnection implements EntityConnectionInterface {
  edges: [PointEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Point

#region Coordinate

input CoordinateInput {
  u: Float!
  v: Float!
}

union CoordinateOwner = Position | PositionModification
union CoordinateOwned = Position | PositionModification

type Coordinate implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: CoordinateOwner!
  ownerPosition: Position
  ownerPositionModification: PositionModification
  ownerEntity: OwnerEntity # CoordinateOwner
  ownedEntities: OwnedEntityConnection # CoordinateOwned
  # Fields
  u: Float!
  v: Float!
}

type CoordinateEdge implements EntityEdge {
  cursor: String!
  node: Coordinate!
}

type CoordinateConnection implements EntityConnectionInterface {
  edges: [CoordinateEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Coordinate

#region Offset

input OffsetInput {
  u: Float!
  v: Float!
}

union OffsetOwner = Position | PositionModification
union OffsetOwned = Position | PositionModification

type Offset implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: OffsetOwner!
  ownerPosition: Position
  ownerPositionModification: PositionModification
  ownerEntity: OwnerEntity # OffsetOwner
  ownedEntities: OwnedEntityConnection # OffsetOwned
  # Fields
  u: Float!
  v: Float!
}

type OffsetEdge implements EntityEdge {
  cursor: String!
  node: Offset!
}

type OffsetConnection implements EntityConnectionInterface {
  edges: [OffsetEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Offset

#region Plane

input PlaneInput {
  origin: PointInput!
  xAxis: VectorInput!
  yAxis: VectorInput!
}

union PlaneOwner = Piece | PieceModification | PlaneDiff
union PlaneOwned = Point | Vector

type Plane implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: PlaneOwner!
  ownerPiece: Piece
  ownerPieceModification: PieceModification
  ownerPlaneDiff: PlaneDiff
  ownerEntity: OwnerEntity # PlaneOwner
  ownedEntities: OwnedEntityConnection # PlaneOwned
  # Fields
  origin: Point!
  xAxis: Vector!
  yAxis: Vector!
}

type PlaneEdge implements EntityEdge {
  cursor: String!
  node: Plane!
}

type PlaneConnection implements EntityConnectionInterface {
  edges: [PlaneEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union PlaneModificationOwner = PieceModification | PositionModification | LocationModification | PlaceModification | AttributeModification | PlaneDiff
union PlaneModificationOwned = Point | Vector | Plane

type PlaneModification implements Entity { # implements Modification
  # Modification
  id: ID! # hash
  hash: String!
  owner: PlaneModificationOwner!
  ownerPieceModification: PieceModification
  ownerPositionModification: PositionModification
  ownerLocationModification: LocationModification
  ownerPlaceModification: PlaceModification
  ownerAttributeModification: AttributeModification
  ownerPlaneDiff: PlaneDiff
  ownerEntity: OwnerEntity # PlaneModificationOwner
  ownedEntities: OwnedEntityConnection # PlaneModificationOwned
  # Fields
  origin: Point
  xAxis: Vector
  yAxis: Vector
}

type PlaneModificationEdge implements EntityEdge {
  cursor: String!
  node: PlaneModification!
}

type PlaneModificationConnection implements EntityConnectionInterface {
  edges: [PlaneModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaneDiff implements Diff {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Plane!
  modification: PlaneModification!
  after: Plane!
}

type PlaneDiffEdge implements EntityEdge {
  cursor: String!
  node: PlaneDiff!
}

type PlaneDiffConnection implements EntityConnectionInterface {
  edges: [PlaneDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Plane

#region Position

input PositionInput {
  center: CoordinateInput!
  plane: PlaneInput!
}

union PositionOwner = Piece | PositionModification | Plane | PositionDiff
# union PositionOwned = Nothing

type Position implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: PositionOwner!
  ownerPiece: Piece
  ownerPositionModification: PositionModification
  ownerPlane: Plane
  ownerPositionDiff: PositionDiff
  ownerEntity: OwnerEntity # PositionOwner
  ownedEntities: OwnedEntityConnection # PositionOwned
  # Fields
  center: Coordinate!
  plane: Plane!
}

type PositionEdge implements EntityEdge {
  cursor: String!
  node: Position!
}

type PositionConnection implements EntityConnectionInterface {
  edges: [PositionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union PositionModificationOwner = PieceModification | PositionDiff
# union PositionModificationOwned = Nothing

type PositionModification implements Entity { # implements Modification
  # Modification
  id: ID! # hash
  hash: String!
  owner: PositionModificationOwner!
  ownerPieceModification: PieceModification
  ownerPositionDiff: PositionDiff
  ownerEntity: OwnerEntity # PositionModificationOwner
  ownedEntities: OwnedEntityConnection # PositionModificationOwned
  # Fields
  center: Coordinate
  plane: Plane
}

type PositionModificationEdge implements EntityEdge {
  cursor: String!
  node: PositionModification!
}

type PositionModificationConnection implements EntityConnectionInterface {
  edges: [PositionModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PositionDiff implements Diff {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Entity! # Position
  modification: PositionModification!
  after: Entity! # Position
}

type PositionDiffEdge implements EntityEdge {
  cursor: String!
  node: PositionDiff!
}

type PositionDiffConnection implements EntityConnectionInterface {
  edges: [PositionDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Position

#region Location

input LocationInput {
  longitude: Float!
  latitude: Float!
  altitude: Float
}

union LocationOwner = Place | Kit | Design
# union LocationOwned = Nothing

type Location implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: LocationOwner!
  ownerPlace: Place
  ownerKit: Kit
  ownerDesign: Design
  ownerEntity: OwnerEntity # LocationOwner
  ownedEntities: OwnedEntityConnection # LocationOwned
  # Fields
  longitude: Float!
  latitude: Float!
  altitude: Float!
}

type LocationEdge implements EntityEdge {
  cursor: String!
  node: Location!
}

type LocationConnection implements EntityConnectionInterface {
  edges: [LocationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union LocationModificationOwner = PlaceModification | LocationDiff
# union LocationModificationOwned = Nothing

type LocationModification implements Entity { # implements Modification
  # Modification
  id: ID! # hash
  hash: String!
  owner: LocationModificationOwner!
  ownerPlaceModification: PlaceModification
  ownerLocationDiff: LocationDiff
  ownerEntity: OwnerEntity # LocationModificationOwner
  ownedEntities: OwnedEntityConnection # LocationModificationOwned
  # Fields
  longitude: Float
  latitude: Float
  altitude: Float
}

type LocationModificationEdge implements EntityEdge {
  cursor: String!
  node: LocationModification!
}

type LocationModificationConnection implements EntityConnectionInterface {
  edges: [LocationModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type LocationDiff implements Diff {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Entity! # Location
  modification: LocationModification!
  after: Entity! # Location
}

type LocationDiffEdge implements EntityEdge {
  cursor: String!
  node: LocationDiff!
}

type LocationDiffConnection implements EntityConnectionInterface {
  edges: [LocationDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Location

#region Attribute

input AttributeInput {
  key: String!
  value: String
  definition: String
}

union AttributeOwner = Piece | Connector | Representation | Connection | Kit | Design | Type | Concept | Tag | AttributeDiff | PositionModification | PieceModification
union AttributeOwned = Attribute

type Attribute implements Entity { # implements WeakEntity
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: AttributeOwner!
  ownerPiece: Piece
  ownerConnector: Connector
  ownerRepresentation: Representation
  ownerConnection: Connection
  ownerKit: Kit
  ownerDesign: Design
  ownerType: Type
  ownerConcept: Concept
  ownerTag: Tag
  ownerAttributeDiff: AttributeDiff
  ownerPositionModification: PositionModification
  ownerPieceModification: PieceModification
  ownerEntity: OwnerEntity # AttributeOwner
  ownedEntities: OwnedEntityConnection # AttributeOwned
  # Fields
  key: String!
  value: String!
  definition: String!
}

type AttributeEdge implements EntityEdge {
  cursor: String!
  node: Attribute!
}

type AttributeConnection implements EntityConnectionInterface {
  edges: [AttributeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union AttributeModificationOwner = PieceModification | Connector | Representation | Connection | Kit | Design | Type | Concept | Tag | AttributeDiff
union AttributeModificationOwned = AttributeModification

type AttributeModification implements Entity { # implements Modification
  # Modification
  id: ID! # hash
  hash: String!
  owner: AttributeModificationOwner!
  ownerPieceModification: PieceModification
  ownerConnector: Connector
  ownerRepresentation: Representation
  ownerConnection: Connection
  ownerKit: Kit
  ownerDesign: Design
  ownerType: Type
  ownerConcept: Concept
  ownerTag: Tag
  ownerAttributeDiff: AttributeDiff
  ownerEntity: OwnerEntity # AttributeModificationOwner
  ownedEntities: OwnedEntityConnection # AttributeModificationOwned
  # Fields
  key: String
  value: String
  definition: String
}

type AttributeDiff implements Diff {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Entity! # Attribute
  modification: AttributeModification!
  after: Entity! # Attribute
}

type AttributeDiffEdge implements EntityEdge {
  cursor: String!
  node: AttributeDiff!
}

type AttributeDiffConnection implements EntityConnectionInterface {
  edges: [AttributeDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type AttributeEdge implements EntityEdge {
  cursor: String!
  node: Attribute!
}

type DiffAttributesConnection implements EntityConnectionInterface {
  edges: [AttributeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union AttributesDiffOwner = Diff | Operation | Change
union AttributesDiffOwned = Attribute | AttributeDiff | Diffs

type AttributesDiff implements Entity {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: AttributesDiffOwner!
  ownerDiff: Diff
  ownerOperation: Operation
  ownerChange: Change
  ownerEntity: OwnerEntity # AttributesDiffOwner
  ownedEntities: OwnedEntityConnection # AttributesDiffOwned
  # Fields
  removed: EntityConnection # Attribute
  diffs: DiffConnection # AttributeDiff via DiffEdge
  added: EntityConnection # Attribute
}

#endregion Attribute

#endregion Weak

#region Strong

# interface StrongEntity implements Entity {
#   id: ID! # uuidv7
#   hash: String!
#   ownerEntity: OwnerEntity # ENTITYKIND
#   ownedEntities: OwnedEntityConnection # ENTITYKIND

# }

union Input = RenamedKitInput | ChangedDescriptionInput | CreatedFixedPieceInput | FixedPieceInput | DraggedPieceInput

union OperationOwner = Change
# union OperationOwned = Nothing

interface Operation implements Entity { # implements StrongEntity
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: OperationOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity # OperationOwner
  ownedEntities: OwnedEntityConnection # OperationOwned
  # Fields
  input: Input
  diff: Diff!
}

type OperationEdge implements EntityEdge {
  cursor: String!
  node: Operation!
}

type OperationConnection implements EntityConnectionInterface {
  edges: [OperationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#region Kit

#region Place

union PlaceOwner = Kit | Checkpoint | Graph
union PlaceOwned = Location

type Place implements Entity { # implements StrongEntity
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: PlaceOwner!
  ownerKit: Kit
  ownerCheckpoint: Checkpoint
  ownerGraph: Graph
  ownerEntity: OwnerEntity! # PlaceOwner
  ownedEntities: OwnedEntityConnection # PlaceOwned
  # Fields
  name: String
  location: Location
}

type PlaceEdge implements EntityEdge {
  cursor: String!
  node: Place!
}

type PlaceConnection implements EntityConnectionInterface {
  edges: [PlaceEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union PlaceModificationOwner = PlaceDiff | Place
union PlaceModificationOwned = LocationModification | Place

type PlaceModification implements Entity { # implements Modification
  # Modification
  id: ID! # hash
  hash: String!
  owner: PlaceModificationOwner!
  ownerPlaceDiff: PlaceDiff
  ownerPlace: Place
  ownerEntity: OwnerEntity # PlaceModificationOwner
  ownedEntities: OwnedEntityConnection # PlaceModificationOwned
  # Fields
  name: String
  location: LocationModification
  removeLocation: Boolean
}

type PlaceModificationEdge implements EntityEdge {
  cursor: String!
  node: PlaceModification!
}

type PlaceModificationConnection implements EntityConnectionInterface {
  edges: [PlaceModificationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

type PlaceDiff implements Diff {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: DiffOwner!
  ownerDiffs: Diffs
  ownerChange: Change
  ownerOperation: Operation
  ownerEntity: OwnerEntity # DiffOwner
  ownedEntities: OwnedEntityConnection # DiffOwned
  # Diff
  before: Place!
  modification: PlaceModification!
  after: Place!
}

type PlaceDiffEdge implements EntityEdge {
  cursor: String!
  node: PlaceDiff!
}

type PlaceDiffConnection implements EntityConnectionInterface {
  edges: [PlaceDiffEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Place

#region Family

union FamilyOwner = Kit
# union FamilyOwned = Nothing

type Family implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: FamilyOwner!
  ownerKit: Kit
  ownerEntity: OwnerEntity! # FamilyOwner
  ownedEntities: OwnedEntityConnection # FamilyOwned
  # Fields
  name: String!
  description: String
}

type FamilyEdge implements EntityEdge {
  cursor: String!
  node: Family!
}

type FamilyConnection implements EntityConnectionInterface {
  edges: [FamilyEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Family

#region Folder

union FolderOwner = Kit | Folder
union FolderOwned = Folder | File | Design | Type | Family

type Folder implements Entity { # implements StrongEntity
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: FolderOwner!
  ownerKit: Kit
  ownerFolder: Folder
  ownerEntity: OwnerEntity! # FolderOwner
  ownedEntities: OwnedEntityConnection # FolderOwned
  # Fields
  name: String!
  path: String!
  description: String!
  files: FileConnection!
  subFolders: FolderConnection!
  families: FamilyConnection!
  types: TypeConnection!
  designs: DesignConnection!
}

type FolderEdge implements EntityEdge {
  cursor: String!
  node: Folder!
}

type FolderConnection implements EntityConnectionInterface {
  edges: [FolderEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Folder

#region File

union FileOwner = Kit | Folder
# union FileOwned = Nothing

type File implements Entity { # implements StrongEntity
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: FileOwner!
  ownerKit: Kit
  ownerFolder: Folder
  ownerEntity: OwnerEntity! # FileOwner
  ownedEntities: OwnedEntityConnection # Nothing
  # Fields
  url: String!
  mime: String
  size: Int
  description: String
  created: Timestamp
  updated: Timestamp
}

type FileEdge implements EntityEdge {
  cursor: String!
  node: File!
}

type FileConnection implements EntityConnectionInterface {
  edges: [FileEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion File

#region Author

union AuthorOwner = Kit | Checkpoint | Graph | Session
union AuthorOwned = Draft | Transaction | Checkpoint

type Author implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: AuthorOwner!
  ownerKit: Kit
  ownerCheckpoint: Checkpoint
  ownerGraph: Graph
  ownerSession: Session
  ownerEntity: OwnerEntity # AuthorOwner
  ownedEntities: OwnedEntityConnection # AuthorOwned
  # Fields
  name: String!
  email: String!
  role: String
  rank: Int
  drafts: DraftConnection!
  transactions: TransactionConnection!
  checkpoints: CheckpointConnection!
}

type AuthorEdge implements EntityEdge {
  cursor: String!
  node: Author!
}

type AuthorConnection implements EntityConnectionInterface {
  edges: [AuthorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Author

#region Prop

union PropOwner = Piece | Type | Design | Kit
# union PropOwned = Nothing

type Prop implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: PropOwner!
  ownerPiece: Piece
  ownerType: Type
  ownerDesign: Design
  ownerKit: Kit
  ownerEntity: OwnerEntity! # PropOwner
  ownedEntities: OwnedEntityConnection # PropOwned
  # Fields
  key: String!
  value: String!
  unit: String
  quality: Quality
}

type PropEdge implements EntityEdge {
  cursor: String!
  node: Prop!
}

type PropConnection implements EntityConnectionInterface {
  edges: [PropEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Prop

#region Benchmark

union BenchmarkOwner = Quality
# union BenchmarkOwned = Nothing

type Benchmark implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: BenchmarkOwner!
  ownerQuality: Quality
  ownerEntity: OwnerEntity! # BenchmarkOwner
  ownedEntities: OwnedEntityConnection # BenchmarkOwned
  # Fields
  name: String!
  min: Float
  max: Float
  minExcluded: Boolean
  maxExcluded: Boolean
}

type BenchmarkEdge implements EntityEdge {
  cursor: String!
  node: Benchmark!
}

type BenchmarkConnection implements EntityConnectionInterface {
  edges: [BenchmarkEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Benchmark

#region Quality

union QualityOwner = Connector | Representation | Type | Design | Kit
union QualityOwned = Benchmark

type Quality implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: QualityOwner!
  ownerConnector: Connector
  ownerRepresentation: Representation
  ownerType: Type
  ownerDesign: Design
  ownerKit: Kit
  ownerEntity: OwnerEntity! # QualityOwner
  ownedEntities: OwnedEntityConnection # QualityOwned
  # Fields
  key: String!
  value: String
  unit: String
  definition: String
  description: String
  benchmarks: BenchmarkConnection!
}

type QualityEdge implements EntityEdge {
  cursor: String!
  node: Quality!
}

type QualityConnection implements EntityConnectionInterface {
  edges: [QualityEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Quality

#region Tag

union TagOwner = Kit | Type | Representation
# union TagOwned = Nothing

type Tag implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: TagOwner!
  ownerKit: Kit
  ownerType: Type
  ownerRepresentation: Representation
  ownerEntity: OwnerEntity! # TagOwner
  ownedEntities: OwnedEntityConnection # TagOwned
  # Fields
  name: String!
  order: Int
}

type TagEdge implements EntityEdge {
  cursor: String!
  node: Tag!
}

type TagConnection implements EntityConnectionInterface {
  edges: [TagEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Tag

#region Concept

union ConceptOwner = Kit | Type
# union ConceptOwned = Nothing

type Concept implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ConceptOwner!
  ownerKit: Kit
  ownerType: Type
  ownerEntity: OwnerEntity! # ConceptOwner
  ownedEntities: OwnedEntityConnection # ConceptOwned
  # Fields
  name: String!
  description: String
  order: Int
}

type ConceptEdge implements EntityEdge {
  cursor: String!
  node: Concept!
}

type ConceptConnection implements EntityConnectionInterface {
  edges: [ConceptEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Concept

#region Stat

union StatOwner = Kit | Design | Type
# union StatOwned = Nothing

type Stat implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: StatOwner!
  ownerKit: Kit
  ownerDesign: Design
  ownerType: Type
  ownerEntity: OwnerEntity! # StatOwner
  ownedEntities: OwnedEntityConnection # StatOwned
  # Fields
  key: String!
  value: String!
  unit: String
  description: String
}

type StatEdge implements EntityEdge {
  cursor: String!
  node: Stat!
}

type StatConnection implements EntityConnectionInterface {
  edges: [StatEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Stat

#region Type

union ConnectorOwner = Type
union ConnectorOwned = Attribute

type Connector implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ConnectorOwner!
  ownerType: Type
  ownerEntity: OwnerEntity! # ConnectorOwner
  ownedEntities: OwnedEntityConnection # ConnectorOwned
  # Fields
  code: String!
  description: String
  portId: ID
  qualities: QualityConnection!
  attributes: AttributeConnection!
}

type ConnectorEdge implements EntityEdge {
  cursor: String!
  node: Connector!
}

type ConnectorConnection implements EntityConnectionInterface {
  edges: [ConnectorEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union RepresentationOwner = Type
union RepresentationOwned = Attribute | File

type Representation implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: RepresentationOwner!
  ownerType: Type
  ownerEntity: OwnerEntity! # RepresentationOwner
  ownedEntities: OwnedEntityConnection # RepresentationOwned
  # Fields
  url: String!
  description: String
  file: File
  tags: TagConnection!
  qualities: QualityConnection!
  attributes: AttributeConnection!
}

type RepresentationEdge implements EntityEdge {
  cursor: String!
  node: Representation!
}

type RepresentationConnection implements EntityConnectionInterface {
  edges: [RepresentationEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union TypeOwner = Kit
union TypeOwned = Connector | Representation | Type | Piece

type Type implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: TypeOwner!
  ownerKit: Kit
  ownerEntity: OwnerEntity! # TypeOwner
  ownedEntities: OwnedEntityConnection # TypeOwned
  # Fields
  name: String!
  description: String
  icon: String
  image: String
  unit: String
  created: Timestamp
  updated: Timestamp
  connectors: ConnectorConnection!
  connector(id: ID!): Connector
  representations: RepresentationConnection!
  representation(id: ID!): Representation
  bestRepresentation(tagIds: [ID!]!): Representation
  authors: AuthorConnection!
  concepts: ConceptConnection!
  tags: TagConnection!
  qualities: QualityConnection!
  props: PropConnection!
  attributes: AttributeConnection!
  stats: StatConnection!
}

type TypeEdge implements EntityEdge {
  cursor: String!
  node: Type!
}

type TypeConnection implements EntityConnectionInterface {
  edges: [TypeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Type

#region Design

#region Layer

union LayerOwner = Design
# union LayerOwned = Nothing

type Layer implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: LayerOwner!
  ownerDesign: Design
  ownerEntity: OwnerEntity! # LayerOwner
  ownedEntities: OwnedEntityConnection # LayerOwned
  # Fields
  name: String!
  description: String
  color: String
  order: Int
  visible: Boolean
  locked: Boolean
}

type LayerEdge implements EntityEdge {
  cursor: String!
  node: Layer!
}

type LayerConnection implements EntityConnectionInterface {
  edges: [LayerEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Layer

#region Group

union GroupOwner = Design
union GroupOwned = Piece

type Group implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: GroupOwner!
  ownerDesign: Design
  ownerEntity: OwnerEntity! # GroupOwner
  ownedEntities: OwnedEntityConnection # GroupOwned
  # Fields
  name: String!
  description: String
  color: String
  icon: String
  pieces: PieceConnection!
}

type GroupEdge implements EntityEdge {
  cursor: String!
  node: Group!
}

type GroupConnection implements EntityConnectionInterface {
  edges: [GroupEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Group

#region Piece

enum PieceConnectionKind {
  FIXED
  CONNECTED
}

union Blueprint = Type | Design

type BlueprintEdge implements EntityEdge {
  cursor: String!
  node: Blueprint!
}

type BlueprintConnection implements EntityConnectionInterface {
  edges: [BlueprintEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union PieceOwner = Type | Design | PieceModification | Piece
union PieceOwned = Piece | Attribute

type Piece implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: PieceOwner!
  ownerType: Type
  ownerDesign: Design
  ownerPieceModification: PieceModification
  ownerPiece: Piece
  ownerEntity: OwnerEntity! # PieceOwner
  ownedEntities: OwnedEntityConnection # PieceOwned — Piece subtree & attrs (design-owned bridges surface via Design)
  # Fields
  name: String
  description: String
  position: Position
  scale: Float
  blueprint: Blueprint!
  # Derived Fields
  connectionKind: PieceConnectionKind

  flatPosition: Position!
  replaceableBlueprints: BlueprintConnection!
  parentConnection: Connection
  childConnections: ConnectionConnection!
  parentPiece: Piece
  childPieces: PieceConnection!
  depth: Int!
  path: PieceConnection!
  props: PropConnection!
  attributes: AttributeConnection!
}

type PieceEdge implements EntityEdge {
  cursor: String!
  node: Piece!
}

type PieceConnection implements EntityConnectionInterface {
  edges: [PieceEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union ConnectionOwner = Design
union ConnectionOwned = Side | Attribute

type Connection implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ConnectionOwner!
  ownerDesign: Design
  ownerEntity: OwnerEntity! # ConnectionOwner
  ownedEntities: OwnedEntityConnection # ConnectionOwned — endpoint sides & connection attrs
  # Fields
  connected: Side!
  connecting: Side!
  gap: Float
  shift: Float
  rise: Float
  rotation: Float
  turn: Float
  tilt: Float
  u: Float
  v: Float
  description: String
  attributes: AttributeConnection!
}

type ConnectionEdge implements EntityEdge {
  cursor: String!
  node: Connection!
}

type ConnectionConnection implements EntityConnectionInterface {
  edges: [ConnectionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#region Operations

type CreatedFixedPieceInput {
  designId: ID!
  blueprintId: ID!
  position: Position!
  name: String
  description: String
}

type CreatedFixedPiece implements Operation & Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: CreatedFixedPieceOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity! # CreatedFixedPieceOwner
  ownedEntities: OwnedEntityConnection # CreatedFixedPieceOwned
  # Fields
  input: CreatedFixedPieceInput!
  diff: Diff!
  piece: Piece!
}

union CreatedFixedPieceOwner = Change
union CreatedFixedPieceOwned = Piece

type FixedPieceInput {
  designId: ID!
  pieceId: ID!
}

type FixedPiece implements Operation & Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: FixedPieceOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity! # FixedPieceOwner
  ownedEntities: OwnedEntityConnection # FixedPieceOwned
  # Fields
  input: FixedPieceInput!
  diff: Diff!
  piece: Piece!
}

union FixedPieceOwner = Change
union FixedPieceOwned = Piece

type DraggedPieceInput {
  designId: ID!
  pieceIds: [ID!]!
  offset: Offset!
}

type DraggedPiece implements Operation & Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: DraggedPieceOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity! # DraggedPieceOwner
  ownedEntities: OwnedEntityConnection # DraggedPieceOwned
  # Fields
  input: DraggedPieceInput!
  diff: Diff!
  pieces: PieceConnection!
}

union DraggedPieceOwner = Change
union DraggedPieceOwned = Piece

#endregion Operations

#endregion Piece

#region Connection

#region Side

union SideOwner = Connection
# union SideOwned = Nothing

type Side implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: SideOwner!
  ownerConnection: Connection
  ownerEntity: OwnerEntity! # SideOwner
  ownedEntities: OwnedEntityConnection # SideOwned
  # Fields
  piece: Piece!
  port: Connector
  designPiece: Piece
  connector: Connector
}

type SideEdge implements EntityEdge {
  cursor: String!
  node: Side!
}

type SideConnection implements EntityConnectionInterface {
  edges: [SideEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Side

#endregion Connection

union DesignOwner = Kit
union DesignOwned = Piece | Connection | Layer | Group

type Design implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: DesignOwner!
  ownerKit: Kit
  ownerEntity: OwnerEntity! # DesignOwner
  ownedEntities: OwnedEntityConnection # DesignOwned
  # Fields
  name: String!
  description: String
  icon: String
  image: String
  place: Place
  unit: String
  created: Timestamp
  updated: Timestamp
  pieces: PieceConnection!
  piece(id: ID!): Piece
  connections: ConnectionConnection!
  connection(id: ID!): Connection
  layers: LayerConnection!
  groups: GroupConnection!
  authors: AuthorConnection!
  qualities: QualityConnection!
  props: PropConnection!
  attributes: AttributeConnection!
  stats: StatConnection!
  qualitySum(qualityId: ID!): Float!
  references: DesignConnection!
  referencedBy: PieceConnection!
}

type DesignEdge implements EntityEdge {
  cursor: String!
  node: Design!
}

type DesignConnection implements EntityConnectionInterface {
  edges: [DesignEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion Design

union KitOwner = Graph | Checkpoint | Alternative
union KitOwned = Design | Type | File | Folder | Author | Place | Kit | Concept | Tag | Family | Quality | Prop | Stat

type Kit implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: KitOwner!
  ownerGraph: Graph
  ownerCheckpoint: Checkpoint
  ownerAlternative: Alternative
  ownerEntity: OwnerEntity # KitOwner
  ownedEntities: OwnedEntityConnection # KitOwned
  # Fields
  checkpoint: Checkpoint
  draft: Draft
  transaction: Transaction
  name: String!
  description: String
  icon: String
  image: String
  preview: String
  remote: String
  homepage: String
  license: String
  uri: String
  created: Timestamp
  updated: Timestamp
  version: String
  design(id: ID!): Design
  designs: DesignConnection!
  type(id: ID!): Type
  types: TypeConnection!
  files: FileConnection!
  folders: FolderConnection!
  families: FamilyConnection!
  authors: AuthorConnection!
  concepts: ConceptConnection!
  tags: TagConnection!
  qualities: QualityConnection!
  props: PropConnection!
  attributes: AttributeConnection!
  stats: StatConnection!
}

type KitEdge implements EntityEdge {
  cursor: String!
  node: Kit!
}

type KitConnection implements EntityConnectionInterface {
  edges: [KitEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#region Operations

type RenamedKitInput {
  name: String!
}

type RenamedKit implements Operation & Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: RenamedKitOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity! # RenamedKitOwner
  ownedEntities: OwnedEntityConnection # RenamedKitOwned
  # Fields
  input: RenamedKitInput!
  diff: Diff!
  kit: Kit!
}

union RenamedKitOwner = Change
union RenamedKitOwned = Kit

type ChangedDescriptionInput {
  entityId: ID!
  description: String!
}

type ChangedDescription implements Operation & Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ChangedDescriptionOwner!
  ownerChange: Change
  ownerEntity: OwnerEntity! # ChangedDescriptionOwner
  ownedEntities: OwnedEntityConnection # ChangedDescriptionOwned
  # Fields
  input: ChangedDescriptionInput!
  diff: Diff!
  entity: Entity!
}

union ChangedDescriptionOwner = Change
# union ChangedDescriptionOwned = Nothing

#endregion Operations

#endregion Kit

#endregion Entities

#region VCS

union ChangeOwner = Transaction | Draft | Checkpoint
union ChangeOwned = Operation

type Change implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ChangeOwner!
  ownerTransaction: Transaction
  ownerDraft: Draft
  ownerCheckpoint: Checkpoint
  ownerEntity: OwnerEntity! # ChangeOwner
  ownedEntities: OwnedEntityConnection # ChangeOwned
  # Fields
  description: String
  origin: String
  forwards: OperationConnection!
  backwards: OperationConnection!
  sequenceNumber: Int!
}

type ChangeEdge implements EntityEdge {
  cursor: String!
  node: Change!
}

type ChangeConnection implements EntityConnectionInterface {
  edges: [ChangeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union TransactionOwner = Draft
union TransactionOwned = Change

type Transaction implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: TransactionOwner!
  ownerDraft: Draft
  ownerEntity: OwnerEntity # TransactionOwner
  ownedEntities: OwnedEntityConnection # TransactionOwned
  # Fields
  changes: ChangeConnection!
}

type TransactionEdge implements EntityEdge {
  cursor: String!
  node: Transaction!
}

type TransactionConnection implements EntityConnectionInterface {
  edges: [TransactionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union DraftOwner = Author
union DraftOwned = Change | Transaction | Checkpoint

type Draft implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: DraftOwner!
  ownerAuthor: Author
  ownerEntity: OwnerEntity! # DraftOwner
  ownedEntities: OwnedEntityConnection # DraftOwned
  # Fields
  parentCheckpoint: Checkpoint
  targetAlternative: Alternative
  openTransaction: Transaction
  finalizedTransactions: TransactionConnection!
  redoTransactions: TransactionConnection!
  changes: ChangeConnection!
  canUndo(steps: Int!): Boolean!
  canRedo(steps: Int!): Boolean!
}

type DraftEdge implements EntityEdge {
  cursor: String!
  node: Draft!
}

type DraftConnection implements EntityConnectionInterface {
  edges: [DraftEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union CheckpointOwner = Alternative | Graph | Kit | Author
union CheckpointOwned = Kit | Author | Checkpoint

type Checkpoint implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: CheckpointOwner!
  ownerAlternative: Alternative
  ownerGraph: Graph
  ownerKit: Kit
  ownerAuthor: Author
  ownerEntity: OwnerEntity # CheckpointOwner
  ownedEntities: OwnedEntityConnection # CheckpointOwned
  # Fields
  timestamp: Timestamp
  authors: AuthorConnection!
  root: Kit
  parentCheckpoint: Checkpoint
  message: String
  isRelease: Boolean!
  changeCount: Int!
}

type CheckpointEdge implements EntityEdge {
  cursor: String!
  node: Checkpoint!
}

type CheckpointConnection implements EntityConnectionInterface {
  edges: [CheckpointEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union AlternativeOwner = Graph
union AlternativeOwned = Checkpoint | Kit | Draft | Transaction

type Alternative implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: AlternativeOwner!
  ownerGraph: Graph
  ownerEntity: OwnerEntity # AlternativeOwner
  ownedEntities: OwnedEntityConnection # AlternativeOwned
  # Fields
  name: String!
  start: Checkpoint!
  checkpoints: CheckpointConnection!
  store: Kit!
  draft: Draft
  transaction: Transaction
}

type AlternativeEdge implements EntityEdge {
  cursor: String!
  node: Alternative!
}

type AlternativeConnection implements EntityConnectionInterface {
  edges: [AlternativeEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union GraphOwner = Session
union GraphOwned = Kit | Alternative | Checkpoint | Session

type Graph implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: GraphOwner!
  ownerSession: Session
  ownerEntity: OwnerEntity # GraphOwner
  ownedEntities: OwnedEntityConnection # GraphOwned
  # Fields
  theKit: Kit
  alternative(id: ID!): Alternative
  alternatives: AlternativeConnection!
  checkpoint(id: ID!): Checkpoint
  checkpoints: CheckpointConnection!
  release(id: ID!): Checkpoint
  releases: CheckpointConnection!
}

type GraphEdge implements EntityEdge {
  cursor: String!
  node: Graph!
}

type GraphConnection implements EntityConnectionInterface {
  edges: [GraphEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union SessionOwner = Graph | Checkpoint | Alternative
union SessionOwned = Draft | Graph | Checkpoint | Alternative

type Session implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: SessionOwner!
  ownerGraph: Graph
  ownerCheckpoint: Checkpoint
  ownerAlternative: Alternative
  ownerEntity: OwnerEntity # SessionOwner
  ownedEntities: OwnedEntityConnection # SessionOwned
  # Fields
  startedAt: Timestamp
  drafts: DraftConnection!
}

type SessionEdge implements EntityEdge {
  cursor: String!
  node: Session!
}

type SessionConnection implements EntityConnectionInterface {
  edges: [SessionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union ReadVersionOwner = Conflict
# union ReadVersionOwned = Nothing

type ReadVersion implements Entity {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: ReadVersionOwner!
  ownerConflict: Conflict
  ownerEntity: OwnerEntity # ReadVersionOwner
  ownedEntities: OwnedEntityConnection # ReadVersionOwned
  # Fields
  checkpoint: Checkpoint
  change: Change
  operation: Operation
}

type ReadVersionEdge implements EntityEdge {
  cursor: String!
  node: ReadVersion!
}

type ReadVersionConnection implements EntityConnectionInterface {
  edges: [ReadVersionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union WriteVersionOwner = Conflict
# union WriteVersionOwned = Nothing

type WriteVersion implements Entity {
  # WeakEntity
  id: ID! # hash
  hash: String!
  owner: WriteVersionOwner!
  ownerConflict: Conflict
  ownerEntity: OwnerEntity # WriteVersionOwner
  ownedEntities: OwnedEntityConnection # WriteVersionOwned
  # Fields
  draft: Draft
  transaction: Transaction
  checkpoint: Checkpoint
  change: Change
  operation: Operation
}

type WriteVersionEdge implements EntityEdge {
  cursor: String!
  node: WriteVersion!
}

type WriteVersionConnection implements EntityConnectionInterface {
  edges: [WriteVersionEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

union ConflictOwner = Session | Graph
union ConflictOwned = ReadVersion | WriteVersion

type Conflict implements Entity {
  # StrongEntity
  id: ID! # uuidv7
  hash: String!
  owner: ConflictOwner!
  ownerSession: Session
  ownerGraph: Graph
  ownerEntity: OwnerEntity! # ConflictOwner
  ownedEntities: OwnedEntityConnection # ConflictOwned
  # Fields
  authoritativeVersion: ReadVersion
  transactionVersion: WriteVersion
  reason: String!
  createdAt: Timestamp!
}

type ConflictEdge implements EntityEdge {
  cursor: String!
  node: Conflict!
}

type ConflictConnection implements EntityConnectionInterface {
  edges: [ConflictEdge!]!
  pageInfo: PageInfo!
  hash: String!
}

#endregion VCS

#region Unions

union EntityEdge =
  | AlternativeEdge
  | AttributeDiffEdge
  | AttributeEdge
  | AttributeEdge
  | AuthorEdge
  | BenchmarkEdge
  | BlueprintEdge
  | ChangeEdge
  | CheckpointEdge
  | ConceptEdge
  | ConflictEdge
  | ConnectionEdge
  | ConnectorEdge
  | CoordinateEdge
  | DesignEdge
  | DraftEdge
  | FamilyEdge
  | DiffsEdge
  | FileEdge
  | FolderEdge
  | GraphEdge
  | GroupEdge
  | KitEdge
  | LayerEdge
  | LocationDiffEdge
  | LocationEdge
  | LocationModificationEdge
  | OffsetEdge
  | OperationEdge
  | PieceEdge
  | PlaneDiffEdge
  | PlaneEdge
  | PlaneModificationEdge
  | PlaceDiffEdge
  | PlaceEdge
  | PlaceModificationEdge
  | PositionDiffEdge
  | PointEdge
  | PositionEdge
  | PositionModificationEdge
  | PropEdge
  | QualityEdge
  | ReadVersionEdge
  | RepresentationEdge
  | SessionEdge
  | SideEdge
  | StatEdge
  | TagEdge
  | TransactionEdge
  | TypeEdge
  | VectorEdge
  | WriteVersionEdge

union EntityConnection =
  | AlternativeConnection
  | AttributeDiffConnection
  | AttributeConnection
  | AuthorConnection
  | BenchmarkConnection
  | BlueprintConnection
  | ChangeConnection
  | CheckpointConnection
  | ConceptConnection
  | ConflictConnection
  | ConnectionConnection
  | ConnectorConnection
  | CoordinateConnection
  | DesignConnection
  | DiffAttributesConnection
  | DraftConnection
  | FamilyConnection
  | DiffsConnection
  | FileConnection
  | FolderConnection
  | GraphConnection
  | GroupConnection
  | KitConnection
  | LayerConnection
  | LocationConnection
  | LocationDiffConnection
  | LocationModificationConnection
  | OffsetConnection
  | OperationConnection
  | PieceConnection
  | PlaneConnection
  | PlaneDiffConnection
  | PlaneModificationConnection
  | PlaceConnection
  | PlaceDiffConnection
  | PlaceModificationConnection
  | PointConnection
  | PositionDiffConnection
  | PositionConnection
  | PositionModificationConnection
  | PropConnection
  | QualityConnection
  | ReadVersionConnection
  | RepresentationConnection
  | SessionConnection
  | SideConnection
  | StatConnection
  | TagConnection
  | TransactionConnection
  | TypeConnection
  | VectorConnection
  | WriteVersionConnection

union OwnerEntity =
  | Alternative
  | Attribute
  | AttributeDiff
  | AttributeModification
  | AttributesDiff
  | Author
  | Benchmark
  | ChangedDescription
  | Change
  | Checkpoint
  | Concept
  | Conflict
  | Connector
  | Connection
  | Coordinate
  | CreatedFixedPiece
  | Design
  | Diffs
  | Draft
  | DraggedPiece
  | Family
  | File
  | FixedPiece
  | Folder
  | Graph
  | Group
  | Kit
  | Layer
  | Location
  | LocationDiff
  | LocationModification
  | Offset
  | Piece
  | Plane
  | PlaneDiff
  | PlaneModification
  | Place
  | PlaceDiff
  | PlaceModification
  | Point
  | Position
  | PositionDiff
  | PositionModification
  | Prop
  | Quality
  | ReadVersion
  | RenamedKit
  | Representation
  | Session
  | Side
  | Stat
  | Tag
  | Transaction
  | Type
  | Vector
  | WriteVersion

union OwnedEntityConnection =
  | AlternativeConnection
  | AttributeDiffConnection
  | AttributeConnection
  | AuthorConnection
  | BenchmarkConnection
  | BlueprintConnection
  | ChangeConnection
  | CheckpointConnection
  | ConceptConnection
  | ConflictConnection
  | ConnectionConnection
  | ConnectorConnection
  | CoordinateConnection
  | DesignConnection
  | DiffAttributesConnection
  | DraftConnection
  | FamilyConnection
  | DiffsConnection
  | FileConnection
  | FolderConnection
  | GraphConnection
  | GroupConnection
  | KitConnection
  | LayerConnection
  | LocationConnection
  | LocationDiffConnection
  | LocationModificationConnection
  | OffsetConnection
  | OperationConnection
  | PieceConnection
  | PlaneConnection
  | PlaneDiffConnection
  | PlaneModificationConnection
  | PlaceConnection
  | PlaceDiffConnection
  | PlaceModificationConnection
  | PointConnection
  | PositionDiffConnection
  | PositionConnection
  | PositionModificationConnection
  | PropConnection
  | QualityConnection
  | ReadVersionConnection
  | RepresentationConnection
  | SessionConnection
  | SideConnection
  | StatConnection
  | TagConnection
  | TransactionConnection
  | TypeConnection
  | VectorConnection
  | WriteVersionConnection

#endregion Unions

#region Schema

type Query {
  session: Session!
  wip: Graph!
  authoritative: Graph
  conflicts: ConflictConnection!
  node(id: ID!): Node
  entity(id: ID!): Entity
}

type Mutation {
  renameKit(draftId: ID!, transactionId: ID!, name: String!): ID!
  changeDescription(draftId: ID!, transactionId: ID!, description: String!): ID!
  createFixedPiece(draftId: ID!, transactionId: ID!, designId: ID!, position: PositionInput!, name: String, description: String): ID!
  fixPiece(draftId: ID!, transactionId: ID!, designId: ID!, pieceId: ID!): ID!
}

type Subscription {
  commandSucceeded: Command!
  operationSucceeded: Operation!
  operationFailed: Error!
  kitRenamed: RenamedKit!
  descriptionChanged: ChangedDescription!
  createdFixedPiece: CreatedFixedPiece!
  fixedPiece: FixedPiece!
  draggedPiece: DraggedPiece!
  error: Error!
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

#endregion Schema
