/** 🧱️ Exact authored nonuniform grid and typed mesh/child relationships. */
import type {Grid3dSnapshot,Grid3dTile,Grid3dTileMedia,Grid3dDirection,Grid3dColor} from "../🟦️.ts";
import {ArtifactSqliteProjection,artifactSqliteTables,artifactSqliteDocument,artifactSqliteDocumentReference,artifactSqliteInteger,artifactSqliteText,artifactSqliteBoolean,artifactSqliteCheckpoint,artifactSqliteOrderedRowsControlled,type ArtifactSqliteOptions} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
import {encodeIeee754Cells,readBinary64,type Binary64} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🔢️ieee754/🟦️.ts";
import type {SqliteDatabase,SqliteRow,SqliteValue} from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
export const WFC_GRID3D_SQLITE_SCHEMA=`CREATE TABLE wfc_grid3d_document (id INTEGER PRIMARY KEY, schema_id TEXT NOT NULL, seed TEXT NOT NULL, width INTEGER NOT NULL CHECK(width BETWEEN 0 AND 4294967295), height INTEGER NOT NULL CHECK(height BETWEEN 0 AND 4294967295), depth INTEGER NOT NULL CHECK(depth BETWEEN 0 AND 4294967295), periodic_x INTEGER NOT NULL CHECK(periodic_x IN(0,1)), periodic_y INTEGER NOT NULL CHECK(periodic_y IN(0,1)), periodic_z INTEGER NOT NULL CHECK(periodic_z IN(0,1)));
CREATE TABLE wfc_grid3d_cell_size (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid3d_document(id), axis TEXT NOT NULL CHECK(axis IN('x','y','z')), ordinal INTEGER NOT NULL CHECK(ordinal>=0), size REAL, size_bits INTEGER NOT NULL, size_class TEXT NOT NULL);
CREATE TABLE wfc_grid3d_tile (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid3d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), authored_id TEXT NOT NULL, label TEXT, weight REAL, media_kind TEXT NOT NULL CHECK(media_kind IN('mesh','mesh_child')), weight_bits INTEGER NOT NULL, weight_class TEXT NOT NULL);
CREATE TABLE wfc_grid3d_mesh (id INTEGER PRIMARY KEY REFERENCES wfc_grid3d_tile(id));
CREATE TABLE wfc_grid3d_position (id INTEGER PRIMARY KEY, mesh_id INTEGER NOT NULL REFERENCES wfc_grid3d_mesh(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), coordinate REAL, coordinate_bits INTEGER NOT NULL, coordinate_class TEXT NOT NULL);
CREATE TABLE wfc_grid3d_index (id INTEGER PRIMARY KEY, mesh_id INTEGER NOT NULL REFERENCES wfc_grid3d_mesh(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), vertex_index INTEGER NOT NULL CHECK(vertex_index BETWEEN 0 AND 4294967295));
CREATE TABLE wfc_grid3d_color (id INTEGER PRIMARY KEY REFERENCES wfc_grid3d_mesh(id), red INTEGER NOT NULL CHECK(red BETWEEN 0 AND 4294967295), green INTEGER NOT NULL CHECK(green BETWEEN 0 AND 4294967295), blue INTEGER NOT NULL CHECK(blue BETWEEN 0 AND 4294967295), alpha INTEGER NOT NULL CHECK(alpha BETWEEN 0 AND 4294967295));
CREATE TABLE wfc_grid3d_mesh_child (id INTEGER PRIMARY KEY REFERENCES wfc_grid3d_tile(id), child_id TEXT NOT NULL, artifact_id TEXT NOT NULL, artifact_kind TEXT NOT NULL, standard TEXT NOT NULL, subset TEXT NOT NULL);
CREATE TABLE wfc_grid3d_rule (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid3d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), authored_id TEXT NOT NULL, tile_a_id TEXT NOT NULL, tile_b_id TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN('LEFT','RIGHT','FRONT','BACK','BOTTOM','TOP')), allowed INTEGER NOT NULL CHECK(allowed IN(0,1)));
CREATE TABLE wfc_grid3d_pin (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid3d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), x INTEGER NOT NULL CHECK(x BETWEEN 0 AND 4294967295), y INTEGER NOT NULL CHECK(y BETWEEN 0 AND 4294967295), z INTEGER NOT NULL CHECK(z BETWEEN 0 AND 4294967295), tile_id TEXT NOT NULL);
CREATE TABLE wfc_grid3d_mask (id INTEGER PRIMARY KEY, document_id INTEGER NOT NULL REFERENCES wfc_grid3d_document(id), ordinal INTEGER NOT NULL CHECK(ordinal>=0), x INTEGER NOT NULL CHECK(x BETWEEN 0 AND 4294967295), y INTEGER NOT NULL CHECK(y BETWEEN 0 AND 4294967295), z INTEGER NOT NULL CHECK(z BETWEEN 0 AND 4294967295));
`;
const SIZE=[{index:4,width:64}] as const,POSITION=[{index:3,width:64}] as const,WEIGHT=[{index:5,width:64}] as const;
function unsigned(value:number):bigint{if(!Number.isInteger(value)||value<0||value>4294967295)throw Error("grid3d unsigned32 differs");return BigInt(value);}
function word(row:SqliteRow,index:number):number{const v=artifactSqliteInteger(row,index);if(v<0n||v>4294967295n)throw Error("grid3d unsigned32 differs");return Number(v);}
function flag(value:boolean):bigint{if(typeof value!=="boolean")throw Error("grid3d boolean differs");return value?1n:0n;}
function identity(row:SqliteRow,count:number):void{if(row.values.length!==count||row.rowid<=0n||artifactSqliteInteger(row,0)!==row.rowid)throw Error("grid3d identity or field count differs");}
function direction(s:string):Grid3dDirection{switch(s){case"LEFT":case"RIGHT":case"FRONT":case"BACK":case"BOTTOM":case"TOP":return s;default:throw Error("grid3d direction differs");}}
async function groups(rows:readonly SqliteRow[],owners:ReadonlySet<bigint>,count:number,options:ArtifactSqliteOptions):Promise<Map<bigint,SqliteRow[]>>{const map=new Map<bigint,SqliteRow[]>(),ids=new Set<bigint>();for(let i=0;i<rows.length;i++){const r=rows[i]!;identity(r,count);if(ids.has(r.rowid))throw Error("duplicate grid3d identity");ids.add(r.rowid);const owner=artifactSqliteInteger(r,1);if(!owners.has(owner))throw Error("unknown grid3d relationship owner");let group=map.get(owner);if(!group)map.set(owner,group=[]);group.push(r);if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,rows.length);}return map;}
async function oneToOne(rows:readonly SqliteRow[],owners:ReadonlySet<bigint>,count:number,complete:boolean,options:ArtifactSqliteOptions):Promise<Map<bigint,SqliteRow>>{const map=new Map<bigint,SqliteRow>();for(let i=0;i<rows.length;i++){const r=rows[i]!;identity(r,count);if(!owners.has(r.rowid)||map.has(r.rowid))throw Error("grid3d one-to-one owner differs");map.set(r.rowid,r);if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,rows.length);}if(complete&&map.size!==owners.size)throw Error("grid3d one-to-one ownership is incomplete");return map;}
/** 📤️ Emits each source scalar and owned relationship into an explicitly named table. */
export async function grid3dSnapshotToSqliteDatabase(s:Grid3dSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
 const p=await ArtifactSqliteProjection.create(WFC_GRID3D_SQLITE_SCHEMA,options);if(typeof s.seed!=="bigint"||s.seed<0n||s.seed>18446744073709551615n)throw Error("grid3d seed exceeds unsigned64");p.checkRowsAdditional(1+s.tiles.length+s.rules.length+s.pinned.length+s.masked.length+s.cellSizesX.length+s.cellSizesY.length+s.cellSizesZ.length);
 await p.insert("wfc_grid3d_document",[s.schema,s.seed.toString(),unsigned(s.width),unsigned(s.height),unsigned(s.depth),flag(s.periodicX),flag(s.periodicY),flag(s.periodicZ)],1n);
 for(const [axis,sizes] of [["x",s.cellSizesX],["y",s.cellSizesY],["z",s.cellSizesZ]] as const)for(let i=0;i<sizes.length;i++)await p.insert("wfc_grid3d_cell_size",encodeIeee754Cells([0n,1n,axis,BigInt(i),sizes[i]!],SIZE).slice(1));
 for(let i=0;i<s.tiles.length;i++){const t=s.tiles[i]!;const kind=t.media.kind==="mesh"?"mesh":"mesh_child";const id=await p.insert("wfc_grid3d_tile",encodeIeee754Cells([0n,1n,BigInt(i),t.id,t.label??null,t.weight,kind],WEIGHT).slice(1));if(t.media.kind==="mesh"){const m=t.media.mesh;p.checkRowsAdditional(1+m.positions.length+m.indices.length+(m.color?1:0));await p.insert("wfc_grid3d_mesh",[],id);for(let j=0;j<m.positions.length;j++)await p.insert("wfc_grid3d_position",encodeIeee754Cells([0n,id,BigInt(j),m.positions[j]!],POSITION).slice(1));for(let j=0;j<m.indices.length;j++)await p.insert("wfc_grid3d_index",[id,BigInt(j),unsigned(m.indices[j]!)]);if(m.color){const c=m.color;await p.insert("wfc_grid3d_color",[unsigned(c.r),unsigned(c.g),unsigned(c.b),unsigned(c.a)],id);}}else if(t.media.kind==="meshChild"){const child=t.media.child,target=child.target;await p.insert("wfc_grid3d_mesh_child",[child.childId,target.artifactId,target.dialect.artifactKind,target.dialect.standard,target.dialect.subset],id);}else throw Error("grid3d media kind differs");}
 for(let i=0;i<s.rules.length;i++){const r=s.rules[i]!;await p.insert("wfc_grid3d_rule",[1n,BigInt(i),r.id,r.tileAId,r.tileBId,direction(r.direction),flag(r.allowed)]);}
 for(let i=0;i<s.pinned.length;i++){const r=s.pinned[i]!;await p.insert("wfc_grid3d_pin",[1n,BigInt(i),unsigned(r.x),unsigned(r.y),unsigned(r.z),r.tileId]);}for(let i=0;i<s.masked.length;i++){const r=s.masked[i]!;await p.insert("wfc_grid3d_mask",[1n,BigInt(i),unsigned(r.x),unsigned(r.y),unsigned(r.z)]);}return p.finish();
}
/** 📥️ Restores exact IEEE words after complete typed ownership and ordering checks. */
export async function grid3dSnapshotFromSqliteDatabase(d:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<Grid3dSnapshot>{
 const [documents,sizes,tileRows,meshRows,positionRows,indexRows,colorRows,childRows,ruleRows,pinRows,maskRows]=await artifactSqliteTables(d,WFC_GRID3D_SQLITE_SCHEMA,options);const doc=artifactSqliteDocument(documents!);identity(doc,9);const text=artifactSqliteText(doc,2);if(!/^(0|[1-9][0-9]*)$/.test(text)||text.length>20)throw Error("grid3d unsigned64 decimal differs");const seed=BigInt(text);if(seed>18446744073709551615n)throw Error("grid3d seed exceeds unsigned64");
 const roots=new Set([1n]),ordered=await artifactSqliteOrderedRowsControlled((await groups(tileRows!,roots,9,options)).get(1n)??[],2,options),meshIds=new Set<bigint>(),childIds=new Set<bigint>();for(let i=0;i<ordered.length;i++){const r=ordered[i]!;artifactSqliteText(r,3);switch(artifactSqliteText(r,6)){case"mesh":meshIds.add(r.rowid);break;case"mesh_child":childIds.add(r.rowid);break;default:throw Error("grid3d media kind differs");}readBinary64(r,5,WEIGHT);if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,ordered.length);}
 await oneToOne(meshRows!,meshIds,1,true,options);const positions=await groups(positionRows!,meshIds,6,options),indices=await groups(indexRows!,meshIds,4,options),colors=await oneToOne(colorRows!,meshIds,5,false,options),children=await oneToOne(childRows!,childIds,6,true,options);
 const axes=new Map<string,SqliteRow[]>([["x",[]],["y",[]],["z",[]]]);for(let i=0;i<sizes!.length;i++){const r=sizes![i]!;identity(r,7);artifactSqliteDocumentReference(r,1);const axis=axes.get(artifactSqliteText(r,2));if(!axis)throw Error("grid3d axis differs");axis.push(r);if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,sizes!.length);}
 const cellSizes:Binary64[][]=[];for(const axis of ["x","y","z"]){const values:Binary64[]=[];for(const r of await artifactSqliteOrderedRowsControlled(axes.get(axis)!,3,options)){values.push(readBinary64(r,4,SIZE));if(values.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",values.length,sizes!.length);}cellSizes.push(values);}
 const tiles:Grid3dTile[]=[];for(let i=0;i<ordered.length;i++){const r=ordered[i]!;let media:Grid3dTileMedia;if(meshIds.has(r.rowid)){const nativePositions:Binary64[]=[],nativeIndices:number[]=[];for(const v of await artifactSqliteOrderedRowsControlled(positions.get(r.rowid)??[],2,options)){nativePositions.push(readBinary64(v,3,POSITION));if(nativePositions.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",nativePositions.length,positionRows!.length);}for(const v of await artifactSqliteOrderedRowsControlled(indices.get(r.rowid)??[],2,options)){nativeIndices.push(word(v,3));if(nativeIndices.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",nativeIndices.length,indexRows!.length);}const v=colors.get(r.rowid),color:Grid3dColor|undefined=v?{r:word(v,1),g:word(v,2),b:word(v,3),a:word(v,4)}:undefined;media={kind:"mesh",mesh:{positions:nativePositions,indices:nativeIndices,...(color?{color}:{})}};}else{const v=children.get(r.rowid)!;media={kind:"meshChild",child:{childId:artifactSqliteText(v,1),target:{artifactId:artifactSqliteText(v,2),dialect:{artifactKind:artifactSqliteText(v,3),standard:artifactSqliteText(v,4),subset:artifactSqliteText(v,5)}}}};}const label=r.values[4]===null?undefined:artifactSqliteText(r,4);tiles.push({id:artifactSqliteText(r,3),...(label===undefined?{}:{label}),weight:readBinary64(r,5,WEIGHT),media});if(i%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",i,ordered.length);}
 const rules:Grid3dSnapshot["rules"]=[],pinned:Grid3dSnapshot["pinned"]=[],masked:Grid3dSnapshot["masked"]=[];for(const r of await artifactSqliteOrderedRowsControlled((await groups(ruleRows!,roots,8,options)).get(1n)??[],2,options)){const id=artifactSqliteText(r,3);rules.push({id,tileAId:artifactSqliteText(r,4),tileBId:artifactSqliteText(r,5),direction:direction(artifactSqliteText(r,6)),allowed:artifactSqliteBoolean(r,7)});if(rules.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",rules.length,ruleRows!.length);}for(const r of await artifactSqliteOrderedRowsControlled((await groups(pinRows!,roots,7,options)).get(1n)??[],2,options)){pinned.push({x:word(r,3),y:word(r,4),z:word(r,5),tileId:artifactSqliteText(r,6)});if(pinned.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",pinned.length,pinRows!.length);}for(const r of await artifactSqliteOrderedRowsControlled((await groups(maskRows!,roots,6,options)).get(1n)??[],2,options)){masked.push({x:word(r,3),y:word(r,4),z:word(r,5)});if(masked.length%256===0)await artifactSqliteCheckpoint(options,"reconstructSnapshot",masked.length,maskRows!.length);}
 await artifactSqliteCheckpoint(options,"reconstructSnapshot",tiles.length,tiles.length);return{schema:artifactSqliteText(doc,1),seed,width:word(doc,3),height:word(doc,4),depth:word(doc,5),periodicX:artifactSqliteBoolean(doc,6),periodicY:artifactSqliteBoolean(doc,7),periodicZ:artifactSqliteBoolean(doc,8),cellSizesX:cellSizes[0]!,cellSizesY:cellSizes[1]!,cellSizesZ:cellSizes[2]!,tiles,rules,pinned,masked};
}
