document = "semio stdio.jpg.dsl v1", newline, snapshot ;
snapshot = "schema=", text, "width=", uint, "height=", uint, "pixels=", text,
 "jfifXDensity=", uint, "jfifYDensity=", uint, "sofMarker=", uint, "arithmetic=", boolean,
 "jfifVersion=[", uint, uint, "]", "jfifDensityUnits=", text,
 "jfifThumbnail=", thumbnail, "frame=", frame,
 "quantTables=[", { quantization }, "]", "huffmanTables=[", { huffman }, "]",
 "restartInterval=", optional_uint, "otherSegments=[", { segment }, "]" ;
optional_uint = "null" | uint ;
octets = "bytes64(", text, ")" ;
thumbnail = "null" | "{height=", uint, "rgbData=", octets, "width=", uint, "}" ;
frame = "null" | "{components=[", { component }, "] height=", uint, "precision=", uint, "width=", uint, "}" ;
component = "{hSampling=", uint, "id=", uint, "quantTableId=", uint, "vSampling=", uint, "}" ;
quantization = "{id=", uint, "precision=", uint, "values=[", { uint }, "]}" ;
huffman = "{bits=[", { uint }, "] class=", text, "id=", uint, "values=", octets, "}" ;
segment = "{data=", octets, "marker=", uint, "}" ;
boolean = "true" | "false" ;
uint = digit, { digit } ;
text = '"', { scalar | escape }, '"' ;
