/** 🧫️ Explicit test-only ownership of the independent finite Serde fixture. */
import corpus from "../../🧫️fixtures/🔣️.json";
import {binary64} from "../../../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🔢️ieee754/🟦️.ts";
import type {EnergyModelSnapshot,EnergyVertex} from "../../../../../🧬️schema/📸️snapshot/🟦️.ts";
const f=binary64;
function vertex(v:readonly number[]):EnergyVertex{if(v.length!==3)throw Error("fixture vertex");return[f(v[0]!),f(v[1]!),f(v[2]!)]}
export function fixture():EnergyModelSnapshot{
 const m=structuredClone(corpus.completeModel);
 return{schema:corpus.schema,structure:{childId:"local!\0🌍",target:{artifactId:"remote!\0🌍",dialect:{artifactKind:"s.stdio.semio.value",standard:"v1",subset:"*"}}},zones:{childId:"zones-alias",target:{artifactId:"",dialect:{artifactKind:"s.stdio.semio.table",standard:"v1",subset:"*"}}},referencedModel:null,weatherLink:null,model:{
 ...m,site:{latitude_deg:f(m.site.latitude_deg),longitude_deg:f(m.site.longitude_deg),elevation_m:f(m.site.elevation_m),time_zone_hours:f(m.site.time_zone_hours),north_axis_deg:f(m.site.north_axis_deg)},ground_temperature:{building_surface_c:m.ground_temperature.building_surface_c.map(f),shallow_c:m.ground_temperature.shallow_c.map(f),deep_c:f(m.ground_temperature.deep_c)},
 zones:m.zones.map(v=>({...v,volume_m3:f(v.volume_m3)})),spaces:m.spaces.map(v=>({...v,floor_area_m2:f(v.floor_area_m2)})),surfaces:m.surfaces.map(v=>({...v,class:"Ground",outside_boundary_condition:{kind:"Interzone",partner:v.outside_boundary_condition.Interzone},vertices_m:v.vertices_m.map(vertex)})),
 fenestrations:m.fenestrations.map(v=>({...v,u_value_w_m2k:f(v.u_value_w_m2k),shgc:f(v.shgc),vlt:f(v.vlt),area_m2:f(v.area_m2),height_m:f(v.height_m),sill_height_m:f(v.sill_height_m),frame_conductance_w_k:f(v.frame_conductance_w_k),divider_conductance_w_k:f(v.divider_conductance_w_k),overhang_depth_m:f(v.overhang_depth_m),overhang_offset_m:f(v.overhang_offset_m),fin_depth_m:f(v.fin_depth_m),fin_offset_m:f(v.fin_offset_m),vertices_m:v.vertices_m.map(vertex)})),
 materials:m.materials.map(v=>({...v,roughness:"VerySmooth",thickness_m:f(v.thickness_m),conductivity_w_m_k:f(v.conductivity_w_m_k),density_kg_m3:f(v.density_kg_m3),specific_heat_j_kg_k:f(v.specific_heat_j_kg_k),thermal_absorptance:f(v.thermal_absorptance),solar_absorptance:f(v.solar_absorptance),visible_absorptance:f(v.visible_absorptance)})),
 glazing_materials:m.glazing_materials.map(v=>({...v,thickness_m:f(v.thickness_m),conductivity_w_m_k:f(v.conductivity_w_m_k),solar_transmittance:f(v.solar_transmittance),solar_reflectance_front:f(v.solar_reflectance_front),solar_reflectance_back:f(v.solar_reflectance_back),visible_transmittance:f(v.visible_transmittance),visible_reflectance_front:f(v.visible_reflectance_front),visible_reflectance_back:f(v.visible_reflectance_back),infrared_transmittance:f(v.infrared_transmittance),infrared_emissivity_front:f(v.infrared_emissivity_front),infrared_emissivity_back:f(v.infrared_emissivity_back)})),gas_materials:m.gas_materials.map(v=>({...v,gas:"Xenon",thickness_m:f(v.thickness_m)})),
 people:m.people.map(v=>({...v,people_per_area:f(v.people_per_area),sensible_fraction:f(v.sensible_fraction),latent_fraction:f(v.latent_fraction),radiant_fraction:f(v.radiant_fraction)})),lighting:m.lighting.map(v=>({...v,watts_per_area:f(v.watts_per_area),radiant_fraction:f(v.radiant_fraction),visible_fraction:f(v.visible_fraction),return_air_fraction:f(v.return_air_fraction)})),equipment:m.equipment.map(v=>({...v,watts_per_area:f(v.watts_per_area),radiant_fraction:f(v.radiant_fraction),latent_fraction:f(v.latent_fraction)})),
 thermostats:m.thermostats.map(v=>({...v,heating_throttle_range_k:f(v.heating_throttle_range_k),cooling_throttle_range_k:f(v.cooling_throttle_range_k)})),humidistats:m.humidistats.map(v=>({...v,humidifying_throttle_range:f(v.humidifying_throttle_range),dehumidifying_throttle_range:f(v.dehumidifying_throttle_range)})),
 setpoint_managers:m.setpoint_managers.map(v=>({...v,kind:{kind:"OutdoorAirReset",low_outdoor_c:f(v.kind.OutdoorAirReset.low_outdoor_c),high_outdoor_c:f(v.kind.OutdoorAirReset.high_outdoor_c),low_setpoint_c:f(v.kind.OutdoorAirReset.low_setpoint_c),high_setpoint_c:f(v.kind.OutdoorAirReset.high_setpoint_c)}})),
 ideal_loads:m.ideal_loads.map(v=>({...v,max_heating_supply_air_temp_c:f(v.max_heating_supply_air_temp_c),min_cooling_supply_air_temp_c:f(v.min_cooling_supply_air_temp_c),max_heating_capacity_w:v.max_heating_capacity_w===null?null:f(v.max_heating_capacity_w),max_cooling_capacity_w:v.max_cooling_capacity_w===null?null:f(v.max_cooling_capacity_w),outdoor_air_per_person_m3_s:f(v.outdoor_air_per_person_m3_s),outdoor_air_per_area_m3_s_m2:f(v.outdoor_air_per_area_m3_s_m2)})),
 zone_equipment:m.zone_equipment.map(v=>({...v,equipment_type:"WaterToAirHp",heating_capacity_w:f(v.heating_capacity_w),cooling_capacity_w:f(v.cooling_capacity_w)})),air_loops:m.air_loops.map(v=>({...v,design_supply_air_flow_m3_s:f(v.design_supply_air_flow_m3_s)})),plant_loops:m.plant_loops.map(v=>({...v,loop_type:"Condenser",supply_temperature_c:f(v.supply_temperature_c),return_temperature_c:f(v.return_temperature_c),design_flow_kg_s:f(v.design_flow_kg_s)})),outdoor_air_systems:m.outdoor_air_systems.map(v=>({...v,min_oa_flow_m3_s:f(v.min_oa_flow_m3_s)})),
 infiltrations:m.infiltrations.map(v=>({...v,method:"WindAndStack",design_flow_ach:f(v.design_flow_ach),flow_per_exterior_area_m3_s_m2:f(v.flow_per_exterior_area_m3_s_m2),effective_leakage_area_m2:f(v.effective_leakage_area_m2),discharge_coefficient:f(v.discharge_coefficient),stack_height_m:f(v.stack_height_m),constant_term_coefficient:f(v.constant_term_coefficient),temperature_term_coefficient:f(v.temperature_term_coefficient),velocity_term_coefficient:f(v.velocity_term_coefficient),velocity_squared_term_coefficient:f(v.velocity_squared_term_coefficient)})),
 mechanical_ventilations:m.mechanical_ventilations.map(v=>({...v,design_flow_m3_s:f(v.design_flow_m3_s),fan_total_efficiency:f(v.fan_total_efficiency),fan_delta_pressure_pa:f(v.fan_delta_pressure_pa)})),shading_surfaces:m.shading_surfaces.map(v=>({...v,vertices_m:v.vertices_m.map(vertex)})),airflow_network:{...m.airflow_network,zone_node_ids:m.airflow_network.zone_node_ids.map(v=>[v[0]!,v[1]!])},
 pv_systems:m.pv_systems.map(v=>({...v,dc_capacity_w:f(v.dc_capacity_w),area_m2:f(v.area_m2),tilt_deg:f(v.tilt_deg),azimuth_deg:f(v.azimuth_deg),module_efficiency:f(v.module_efficiency),inverter_efficiency:f(v.inverter_efficiency)})),battery_storage:m.battery_storage.map(v=>({...v,capacity_kwh:f(v.capacity_kwh),max_charge_w:f(v.max_charge_w),max_discharge_w:f(v.max_discharge_w),round_trip_efficiency:f(v.round_trip_efficiency)})),shw_systems:m.shw_systems.map(v=>({...v,heater_capacity_w:f(v.heater_capacity_w),storage_volume_m3:f(v.storage_volume_m3),setpoint_c:f(v.setpoint_c)})),solar_thermal_systems:m.solar_thermal_systems.map(v=>({...v,collector_area_m2:f(v.collector_area_m2),efficiency:f(v.efficiency),storage_volume_m3:f(v.storage_volume_m3),tilt_deg:f(v.tilt_deg),azimuth_deg:f(v.azimuth_deg)})),
 refrigeration_systems:m.refrigeration_systems.map(v=>({...v,design_load_w:f(v.design_load_w)})),water_systems:m.water_systems.map(v=>({...v,peak_flow_l_s:f(v.peak_flow_l_s)})),faults:m.faults.map(v=>({...v,fault_type:"BoilerEfficiencyDegradation",severity:f(v.severity)})),output_variables:m.output_variables.map(v=>({...v,reporting_frequency:"RunPeriod"})),sizing_objects:m.sizing_objects.map(v=>({...v,sizing_type:"OutdoorAir",design_day_type:"Heating"})),daylight_zones:m.daylight_zones.map(v=>({...v,illuminance_target_lux:f(v.illuminance_target_lux),glare_limit:f(v.glare_limit),window_transmittance:f(v.window_transmittance)})),room_air_models:m.room_air_models.map(v=>({...v,model:"UnderFloorAirDistribution"})),
 schedules:{constants:m.schedules.constants.map(v=>({...v,value:f(v.value)})),daily:m.schedules.daily.map(v=>({...v,interpolation:"Discrete",hourly_values:v.hourly_values.map(f),limits:{min:f(v.limits.min),max:f(v.limits.max)}})),weekly:m.schedules.weekly,annual:m.schedules.annual.map(v=>({...v,holiday_dates:v.holiday_dates.map(v=>[v[0]!,v[1]!,v[2]!])})),time_series:m.schedules.time_series.map(v=>({...v,values:v.values.map(f)}))}
 }};
}
