[package]
name="semio-ticket-command-caller-native"
version="0.0.0"
edition="2021"
[workspace]
[lib]
path="🦀️.rs"
[dependencies]
semio-framework-pack={path="/Users/ueli/Documents/semio/🧰️framework/🔨️modules/🎒️pack/📦️packages/🦀️rust"}
semio-framework-async={path="/Users/ueli/Documents/semio/🧰️framework/🔨️modules/⏳️async/📦️packages/🦀️rust"}
semio-framework-value={path="/Users/ueli/Documents/semio/🧰️framework/🔨️modules/🌱️value/📦️packages/🦀️rust"}
[dev-dependencies]
semio-framework-async-macros={path="/Users/ueli/Documents/semio/🧰️framework/🔨️modules/⏳️async/✨️macros/📦️packages/🦀️rust"}
serde_json="1.0.140"
