import { validateRoleInputs } from "../../../🧬️schema/🪪️stream-roles/🟦️.ts";
import { writePdfStreamRole, readPdfStreamRole } from "./🪪️stream-roles/🟦️.ts";
/** 📖️ Complete owned PDF1.7 semantic database and explicit document relationships. */
import type { PdfSnapshot } from "../../../🧬️schema/📸️snapshot/🟦️.ts";
import { PdfProjection,PdfReader,type SqliteDatabase,type ArtifactSqliteOptions } from "./🧩️entity/🟦️.ts";
import { PDF17_SQLITE_SCHEMA } from "./🧬️schema/🟦️.ts";
import { pdfDocumentNumberColumns } from "./📄️document/🔢️number/🟦️.ts";
import { writePdfPage,readPdfPage,writePdfNamedColor,readPdfNamedColor,writePdfNamedProperties,readPdfNamedProperties,writePdfIndirect,readPdfIndirect } from "./📄️document/🟦️.ts";
import { writePdfFont,readPdfFont } from "./🔤️font/🟦️.ts";
import { writePdfImage,readPdfImage } from "./🖼️resource/🟦️.ts";
import { writePdfForm,readPdfForm,writePdfState,readPdfState } from "./🖼️resource/🎚️state/🟦️.ts";
import { writePdfShading,readPdfShading,writePdfPattern,readPdfPattern } from "./🖼️resource/🌈️shading/🟦️.ts";
import { writePdfOutline,readPdfOutline,writePdfNamedDestination,readPdfNamedDestination,writePdfLabel,readPdfLabel,writePdfOpenAction,readPdfOpenAction } from "./🎯️navigation/🔖️bookmark/🟦️.ts";
import { writePdfEmbeddedFile,readPdfEmbeddedFile,writePdfOutputIntent,readPdfOutputIntent,writePdfPreferences,readPdfPreferences,writePdfEncryption,readPdfEncryption,writePdfMarkInfo,readPdfMarkInfo,pdfPageLayout,pdfPageMode } from "./📇️metadata/🟦️.ts";
import { writePdfInfo,readPdfInfo } from "./📇️metadata/📆️date/🟦️.ts";
import { writePdfAcroForm,readPdfAcroForm,writePdfOptionalContent,readPdfOptionalContent } from "./📝️form/🟦️.ts";
import { writePdfDictionary,readPdfDictionary } from "./🧩️cos/🟦️.ts";
import { artifactSqliteInteger } from "../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🧩️artifact/🟦️.ts";
export { PDF17_SQLITE_SCHEMA };
async function writeCollection<T>(out:PdfProjection,table:string,values:readonly T[],write:(out:PdfProjection,value:T)=>Promise<bigint>):Promise<void>{out.checkRowsAdditional(values.length);for(const[ordinal,value]of values.entries())await out.insert(table,[1n,BigInt(ordinal),await write(out,value)]);}
async function readCollection<T>(reader:PdfReader,table:string,read:(reader:PdfReader,key:bigint)=>Promise<T>):Promise<T[]>{const values:T[]=[];for(const child of await reader.children(table,1,2,1n)){const relation=await reader.take(table,child.rowid,4);values.push(await read(reader,artifactSqliteInteger(relation,3)));}return values;}
/** 📖️ Project every document field into its handcrafted entity and relationship tables. */
export async function pdf17SnapshotToSqliteDatabase(value:PdfSnapshot,options:ArtifactSqliteOptions={}):Promise<SqliteDatabase>{
  validateRoleInputs(value.objects,value.objects,[],value.admittedStreamRoles);
  const out=await PdfProjection.create(PDF17_SQLITE_SCHEMA,options,pdfDocumentNumberColumns);const ids=value.documentId;if(ids!=null&&ids.length!==2)throw new Error("PDF document ID requires two intrinsic byte strings");
  await out.insert("pdf_document",[value.schema,value.declaredVersion,value.acroForm==null?null:await writePdfAcroForm(out,value.acroForm),value.optionalContent==null?null:await writePdfOptionalContent(out,value.optionalContent),pdfPageLayout(value.pageLayout),pdfPageMode(value.pageMode),value.viewerPreferences==null?null:await writePdfPreferences(out,value.viewerPreferences),value.openAction==null?null:await writePdfOpenAction(out,value.openAction),value.language??null,value.markInfo==null?null:await writePdfMarkInfo(out,value.markInfo),value.metadata??null,ids==null?null:await out.bytes(ids[0]),ids==null?null:await out.bytes(ids[1]),value.encryption==null?null:await writePdfEncryption(out,value.encryption),await writePdfInfo(out,value.info),await writePdfDictionary(out,value.catalogExtra),await writePdfDictionary(out,value.trailer)],1n);
  await writeCollection(out,"pdf_document_page",value.pages,writePdfPage);await writeCollection(out,"pdf_document_font",value.fonts,writePdfFont);await writeCollection(out,"pdf_document_image",value.images,writePdfImage);await writeCollection(out,"pdf_document_form",value.forms,writePdfForm);await writeCollection(out,"pdf_document_state",value.extGStates,writePdfState);await writeCollection(out,"pdf_document_shading",value.shadings,writePdfShading);await writeCollection(out,"pdf_document_pattern",value.patterns,writePdfPattern);await writeCollection(out,"pdf_document_color",value.colorSpaces,writePdfNamedColor);await writeCollection(out,"pdf_document_properties",value.properties,writePdfNamedProperties);await writeCollection(out,"pdf_document_outline",value.outlines,writePdfOutline);await writeCollection(out,"pdf_document_destination",value.namedDestinations,writePdfNamedDestination);await writeCollection(out,"pdf_document_label",value.pageLabels,writePdfLabel);await writeCollection(out,"pdf_document_file",value.embeddedFiles,writePdfEmbeddedFile);await writeCollection(out,"pdf_document_intent",value.outputIntents,writePdfOutputIntent);await writeCollection(out,"pdf_document_object",value.objects,writePdfIndirect);await writeCollection(out,"pdf_document_role",value.admittedStreamRoles,writePdfStreamRole);return out.finish();
}
/** 📥️ Reconstruct every owned document field with exact schema, identity and relation checks. */
export async function pdf17SnapshotFromSqliteDatabase(database:SqliteDatabase,options:ArtifactSqliteOptions={}):Promise<PdfSnapshot>{
  const reader=await PdfReader.create(database,PDF17_SQLITE_SCHEMA,options,pdfDocumentNumberColumns);const row=await reader.take("pdf_document",1n,18);let documentId:PdfSnapshot["documentId"]=null;if(row.values[12]!==null||row.values[13]!==null){if(!(row.values[12] instanceof Uint8Array)||!(row.values[13] instanceof Uint8Array))throw new Error("PDF document ID requires both intrinsic byte strings");documentId=[await reader.bytes(row,12),await reader.bytes(row,13)];}
  const value:PdfSnapshot={schema:await reader.text(row,1),declaredVersion:await reader.text(row,2),pages:await readCollection(reader,"pdf_document_page",readPdfPage),fonts:await readCollection(reader,"pdf_document_font",readPdfFont),images:await readCollection(reader,"pdf_document_image",readPdfImage),forms:await readCollection(reader,"pdf_document_form",readPdfForm),extGStates:await readCollection(reader,"pdf_document_state",readPdfState),shadings:await readCollection(reader,"pdf_document_shading",readPdfShading),patterns:await readCollection(reader,"pdf_document_pattern",readPdfPattern),colorSpaces:await readCollection(reader,"pdf_document_color",readPdfNamedColor),properties:await readCollection(reader,"pdf_document_properties",readPdfNamedProperties),outlines:await readCollection(reader,"pdf_document_outline",readPdfOutline),namedDestinations:await readCollection(reader,"pdf_document_destination",readPdfNamedDestination),pageLabels:await readCollection(reader,"pdf_document_label",readPdfLabel),embeddedFiles:await readCollection(reader,"pdf_document_file",readPdfEmbeddedFile),outputIntents:await readCollection(reader,"pdf_document_intent",readPdfOutputIntent),acroForm:row.values[3]===null?null:await readPdfAcroForm(reader,artifactSqliteInteger(row,3)),optionalContent:row.values[4]===null?null:await readPdfOptionalContent(reader,artifactSqliteInteger(row,4)),pageLayout:pdfPageLayout(await reader.optionalText(row,5)),pageMode:pdfPageMode(await reader.optionalText(row,6)),viewerPreferences:row.values[7]===null?null:await readPdfPreferences(reader,artifactSqliteInteger(row,7)),openAction:row.values[8]===null?null:await readPdfOpenAction(reader,artifactSqliteInteger(row,8)),language:await reader.optionalText(row,9),markInfo:row.values[10]===null?null:await readPdfMarkInfo(reader,artifactSqliteInteger(row,10)),metadata:await reader.optionalText(row,11),documentId,encryption:row.values[14]===null?null:await readPdfEncryption(reader,artifactSqliteInteger(row,14)),info:await readPdfInfo(reader,artifactSqliteInteger(row,15)),catalogExtra:await readPdfDictionary(reader,artifactSqliteInteger(row,16)),objects:await readCollection(reader,"pdf_document_object",readPdfIndirect),trailer:await readPdfDictionary(reader,artifactSqliteInteger(row,17)),admittedStreamRoles:await readCollection(reader,"pdf_document_role",readPdfStreamRole)};await reader.finish();validateRoleInputs(value.objects,value.objects,[],value.admittedStreamRoles);return value;
}
