// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionDescriptor } from "./ActionDescriptor";

export type Keybinding = { keys: string, action: ActionDescriptor, };
