// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiKeyValueEntry } from "./UiKeyValueEntry";
import type { UiMenuRef } from "./UiMenuRef";
import type { UiPresence } from "./UiPresence";

export type UiKeyValueNode = { entries: Array<UiKeyValueEntry>, presence?: UiPresence, menu?: UiMenuRef, };
