// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowLayoutWindowNode } from "./WindowLayoutWindowNode";

export type WindowLayoutStackNode = { kind: string, size?: number, activeWindowKindId?: string, children: Array<WindowLayoutWindowNode>, };
