// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionDescriptor } from "./ActionDescriptor";
import type { IconName } from "./IconName";
import type { MeasureSelectItem } from "./MeasureSelectItem";

export type WindowMeasure = { "kind": "select", id: string, label?: string, value: string, items: Array<MeasureSelectItem>, onChange: ActionDescriptor, } | { "kind": "slider", id: string, label?: string, value: number, min: number, max: number, step?: number, 
/**
 * 🎚️ Absolute value on the fixed `[min, max]` range that is already preloaded/ready.
 * Renderers keep `max` stable and draw a highlight from the knob to this extent.
 */
ready?: number, 
/**
 * 🌀️ When true, the measure tree leaf shows a loading ring while preload continues.
 */
loading?: boolean, 
/**
 * 🌀️ When true, the measure tree leaf shows a dashed, slower waiting ring; `loading` takes precedence when both are set.
 */
waiting?: boolean, 
/**
 * 🚫️ When true, the slider is inert — used when a parent weight is zero so joint percentages cannot change anything.
 */
disabled?: boolean, 
/**
 * 🪣️ When set, this is a reveal-group id: the host must NOT dispatch `onChange` on every drag
 * value — only on gesture commit (pointer-up) — and while dragging must locally cut off
 * instances tagged with this reveal group's id instead. See `WorldInstancesLayer`'s reveal
 * cutoff store and `revealCutoffs` in `World3dScene.interaction_json`.
 */
reveal?: string, onChange: ActionDescriptor, } | { "kind": "toggle", id: string, iconId: IconName, label?: string, pressed: boolean, text?: string, onChange: ActionDescriptor, } | { "kind": "group", id: string, label: string, defaultOpen?: boolean, 
/**
 * 🎯️ When `Some(utility_id)`, this group is *utility-scoped chrome*: the shell surfaces it only while
 * `ViewState.active_utility_id == utility_id`, and renders it in the dedicated "Utility Options" rail
 * beside the utility bar — never in the always-on Measures overlay. When absent, the group is a
 * general measure and stays in the Measures overlay exactly as before. See [`partition_window_measures`].
 */
activeUtilityId?: string, 
/**
 * 🎚️ Optional header slider — when set with `on_change`, the group row hosts a weight control (e.g. object-kind probability).
 */
value?: number, min?: number, max?: number, step?: number, ready?: number, loading?: boolean, waiting?: boolean, onChange?: ActionDescriptor, children: Array<WindowMeasure>, };
