[package]
name = "semio-s-kernel-flow-module-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
name = "flow_module_core"
crate-type = ["rlib", "cdylib"]
path = "../../../../../../../../../🧰framework/🛍️product/💻os/🔨module/🌊flow/⚡️implementation/🦀rust/🔨module/🫀core/📦lib.rs"

[features]
default = ["standalone-wasm"]
standalone-wasm = ["dep:wasm-bindgen"]

[dependencies]
flow_module_wasm = { path = "../../../../../../../../../🧰framework/🛍️product/💻os/🔨module/🌊flow/⚡️implementation/🦀rust/🔨module/🕸️wasm", package = "semio-s-kernel-flow-module-wasm" }
neural_engine = { path = "../../../../../🧠neural/⚙️engine/⚡️implementation/🦀rust", features = ["parallel"], package = "semio-framework-os-kernel-neural-engine" }
serde_json = "1.0.140"
wasm-bindgen = { version = "0.2.106", optional = true }
