syntax = "proto3";
package semio.s_stdio_pdf_1_7_h.mutation;

message PdfHMutation {
  oneof mutation {
    SetInfoTitleMutation set_info_title = 1;
    SetInfoAuthorMutation set_info_author = 2;
    InsertJavascriptActionMutation insert_javascript_action = 3;
    RemoveJavascriptActionMutation remove_javascript_action = 4;
    InsertLaunchActionMutation insert_launch_action = 5;
    RemoveLaunchActionMutation remove_launch_action = 6;
    InsertSignatureFieldMutation insert_signature_field = 7;
    RemoveSignatureFieldMutation remove_signature_field = 8;
    EmbedFontFileMutation embed_font_file = 9;
    RemoveFontFileMutation remove_font_file = 10;
  }
}
