//! 🧰️ Controlled catalog, design, child and representation native materialization.
use super::{SemioKitSnapshot,SemioKitType,SemioKitPiece,SemioKitConnection,SemioKitDesign,SemioTransform,STDIO_SEMIOKIT_DOCUMENT_SCHEMA};
use crate::standards::v1::subsets::base::schema::{snapshot::native_decoding as native,child::validate_semio_child_identity,geometry::{SemioPoint3,SemioQuaternion}};
use semio_framework_value::native_decoding::NativeDecodeControl;
use store::sqlite_snapshot::{SqliteSnapshotControl,SqliteDatabaseLimits};
pub(super) fn decode(payload:&store::os_io::IoPayload,control:&mut SqliteSnapshotControl<'_>)->Result<SemioKitSnapshot,String>{native::decode(payload,STDIO_SEMIOKIT_DOCUMENT_SCHEMA,control,binary,document)}
fn binary_reference(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>)->Result<store::os_io::ArtifactRef,String>{Ok(store::os_io::ArtifactRef{artifact_id:native::text(reader,control)?,dialect:store::os_io::ArtifactDialect{artifact_kind:native::text(reader,control)?,standard:native::text(reader,control)?,subset:native::text(reader,control)?}})}
fn binary_child<S>(reader:&mut store::ByteReader<'_>,subset:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<store::ArtifactChild<S>,String>{native::entities(entities,1,limits)?;let child_id=native::text(reader,control)?;let target=binary_reference(reader,control)?;validate_semio_child_identity(&child_id,&target,subset)?;Ok(store::ArtifactChild::new(child_id,target))}
fn binary_type(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>)->Result<SemioKitType,String>{Ok(SemioKitType{id:native::text(reader,control)?,name:native::text(reader,control)?,category:native::text(reader,control)?})}
fn binary_piece(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>)->Result<SemioKitPiece,String>{Ok(SemioKitPiece{id:native::text(reader,control)?,type_id:native::text(reader,control)?,transform:super::read_transform(reader)?})}
fn binary_connection(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>)->Result<SemioKitConnection,String>{Ok(SemioKitConnection{id:native::text(reader,control)?,connecting_piece_id:native::text(reader,control)?,connecting_port:native::text(reader,control)?,connected_piece_id:native::text(reader,control)?,connected_port:native::text(reader,control)?})}
fn binary_design(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<SemioKitDesign,String>{let id=native::text(reader,control)?;let name=native::text(reader,control)?;let mut owner=native::Owned::new(SemioKitDesign{id,name,pieces:Vec::new(),connections:Vec::new()});owner.get_mut().pieces=native::binary_list(reader,control,limits,entities,|reader,control,_|binary_piece(reader,control))?;owner.get_mut().connections=native::binary_list(reader,control,limits,entities,|reader,control,_|binary_connection(reader,control))?;Ok(owner.take())}
fn binary_link(reader:&mut store::ByteReader<'_>,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<store::ArtifactLink,String>{native::entities(entities,1,limits)?;let target=binary_reference(reader,control)?;let pin=match reader.read_u8().map_err(|error|error.to_string())?{0=>store::LinkPin::Head,1=>store::LinkPin::Checkpoint{id:native::text(reader,control)?},2=>{native::entities(entities,1,limits)?;let hash=native::text(reader,control)?;let size=reader.read_varint_u64().map_err(|error|error.to_string())?;let media_type=native::text(reader,control)?;store::LinkPin::Snapshot{blob:store::BlobRef{hash,size,media_type}}},_=>return Err("Kit native invalid pin tag".into())};let role=native::text(reader,control)?;Ok(store::ArtifactLink{target,pin,role})}
pub(crate) fn binary(body:&[u8],control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioKitSnapshot,String>{let mut reader=store::ByteReader::new(body);if reader.read_u8().map_err(|error|error.to_string())?!=1{return Err("Kit native unsupported format".into())}let mut entities=0;native::entities(&mut entities,1,limits)?;let schema=native::text(&mut reader,control)?;let mut owner=native::Owned::new(SemioKitSnapshot{schema,types:Vec::new(),designs:Vec::new(),objects:Vec::new(),models:Vec::new(),properties:None,representations:Vec::new()});owner.get_mut().types=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,_|binary_type(reader,control))?;owner.get_mut().designs=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|binary_design(reader,control,limits,entities))?;owner.get_mut().objects=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|binary_child(reader,"object",control,limits,entities))?;owner.get_mut().models=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|binary_child(reader,"model",control,limits,entities))?;owner.get_mut().properties=match reader.read_u8().map_err(|error|error.to_string())?{0=>None,1=>{native::entities(&mut entities,1,limits)?;Some(binary_child(&mut reader,"value",control,limits,&mut entities)?)},_=>return Err("Kit native invalid optional child presence".into())};owner.get_mut().representations=native::binary_list(&mut reader,control,limits,&mut entities,|reader,control,entities|binary_link(reader,control,limits,entities))?;if reader.remaining()!=0{return Err("Kit native trailing bytes".into())}Ok(owner.take())}
fn text_reference(value:&str,control:&mut NativeDecodeControl<'_>)->Result<store::os_io::ArtifactRef,String>{let[id,kind,standard,subset]=native::record(value,control)?;Ok(store::os_io::ArtifactRef{artifact_id:native::hex_text(id,control)?,dialect:store::os_io::ArtifactDialect{artifact_kind:native::hex_text(kind,control)?,standard:native::hex_text(standard,control)?,subset:native::hex_text(subset,control)?}})}
fn text_child<S>(value:&str,subset:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<store::ArtifactChild<S>,String>{native::entities(entities,1,limits)?;let[id,target]=native::record(value,control)?;let child_id=native::hex_text(id,control)?;let target=text_reference(target,control)?;validate_semio_child_identity(&child_id,&target,subset)?;Ok(store::ArtifactChild::new(child_id,target))}
fn text_type(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioKitType,String>{let[id,name,category]=native::record(value,control)?;Ok(SemioKitType{id:native::hex_text(id,control)?,name:native::hex_text(name,control)?,category:native::hex_text(category,control)?})}
fn text_transform(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioTransform,String>{let[tx,ty,tz,rx,ry,rz,rw,sx,sy,sz]=native::record(value,control)?;Ok(SemioTransform{translation:SemioPoint3{x:native::float(tx,control)?,y:native::float(ty,control)?,z:native::float(tz,control)?},rotation:SemioQuaternion{x:native::float(rx,control)?,y:native::float(ry,control)?,z:native::float(rz,control)?,w:native::float(rw,control)?},scale:SemioPoint3{x:native::float(sx,control)?,y:native::float(sy,control)?,z:native::float(sz,control)?}})}
fn text_piece(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioKitPiece,String>{let[id,type_id,transform]=native::record(value,control)?;Ok(SemioKitPiece{id:native::hex_text(id,control)?,type_id:native::hex_text(type_id,control)?,transform:text_transform(transform,control)?})}
fn text_connection(value:&str,control:&mut NativeDecodeControl<'_>)->Result<SemioKitConnection,String>{let[id,a,ap,b,bp]=native::record(value,control)?;Ok(SemioKitConnection{id:native::hex_text(id,control)?,connecting_piece_id:native::hex_text(a,control)?,connecting_port:native::hex_text(ap,control)?,connected_piece_id:native::hex_text(b,control)?,connected_port:native::hex_text(bp,control)?})}
fn text_design(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<SemioKitDesign,String>{let[id,name,pieces,connections]=native::record(value,control)?;let id=native::hex_text(id,control)?;let name=native::hex_text(name,control)?;let mut owner=native::Owned::new(SemioKitDesign{id,name,pieces:Vec::new(),connections:Vec::new()});owner.get_mut().pieces=native::text_list(pieces,control,limits,entities,|value,control,_|text_piece(value,control))?;owner.get_mut().connections=native::text_list(connections,control,limits,entities,|value,control,_|text_connection(value,control))?;Ok(owner.take())}
fn text_pin(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<store::LinkPin,String>{if value=="[h]"{return Ok(store::LinkPin::Head)}let inner=value.strip_prefix('[').and_then(|value|value.strip_suffix(']')).ok_or("Kit native pin requires brackets")?;match inner.split_once(',').map(|(tag,_)|tag){Some("c")=>{let[_,id]=native::record(value,control)?;Ok(store::LinkPin::Checkpoint{id:native::hex_text(id,control)?})},Some("s")=>{native::entities(entities,1,limits)?;let[_,hash,size,media_type]=native::record(value,control)?;let size=control.scoped_stage(|control|{control.begin_stage(size.len())?;for _ in size.bytes(){control.step()?;}size.parse::<u64>().map_err(|_|"Kit native invalid blob size".to_string())})?;Ok(store::LinkPin::Snapshot{blob:store::BlobRef{hash:native::hex_text(hash,control)?,size,media_type:native::hex_text(media_type,control)?}})},_=>Err("Kit native invalid pin shape".into())}}
fn text_link(value:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits,entities:&mut usize)->Result<store::ArtifactLink,String>{native::entities(entities,1,limits)?;let[target,pin,role]=native::record(value,control)?;let target=text_reference(target,control)?;let pin=text_pin(pin,control,limits,entities)?;let role=native::hex_text(role,control)?;Ok(store::ArtifactLink{target,pin,role})}
pub(crate) fn document(body:&str,control:&mut NativeDecodeControl<'_>,limits:SqliteDatabaseLimits)->Result<SemioKitSnapshot,String>{let fields=native::fields(body,["schema","types","designs","objects","models","properties","representations"],control)?;let mut entities=0;native::entities(&mut entities,1,limits)?;let schema=native::hex_text(fields[0].ok_or("Kit native schema missing")?,control)?;let mut owner=native::Owned::new(SemioKitSnapshot{schema,types:Vec::new(),designs:Vec::new(),objects:Vec::new(),models:Vec::new(),properties:None,representations:Vec::new()});owner.get_mut().types=native::text_list(fields[1].unwrap_or("[]"),control,limits,&mut entities,|value,control,_|text_type(value,control))?;owner.get_mut().designs=native::text_list(fields[2].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|text_design(value,control,limits,entities))?;owner.get_mut().objects=native::text_list(fields[3].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|text_child(value,"object",control,limits,entities))?;owner.get_mut().models=native::text_list(fields[4].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|text_child(value,"model",control,limits,entities))?;let properties=fields[5].unwrap_or("[]");if properties!="[]"{native::entities(&mut entities,1,limits)?;owner.get_mut().properties=Some(text_child(properties,"value",control,limits,&mut entities)?)}owner.get_mut().representations=native::text_list(fields[6].unwrap_or("[]"),control,limits,&mut entities,|value,control,entities|text_link(value,control,limits,entities))?;Ok(owner.take())}
