//! 🔍️ Admitted PNG identity, ordinal and byte-parent indexes over authored borrowed rows.
use semio_framework_os_kernel::sqlite_snapshot::{SqliteDatabase,SqliteRow,SqliteTable,SqliteSnapshotControl,SqliteSnapshotPhase,ValueError,ValueRefusalKind,artifact::ordered_row_refs,transfer::reserve};
use std::cmp::Ordering;
type Result<T>=std::result::Result<T,ValueError>;
fn invalid(message:&str)->ValueError{ValueError::new(ValueRefusalKind::InvalidValue,message)}
fn tick(work:&mut usize,control:&mut SqliteSnapshotControl<'_>)->Result<()>{*work=work.checked_add(1).ok_or_else(||ValueError::new(ValueRefusalKind::WorkLimit,"PNG index work overflow"))?;if *work%256==0{control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,*work,0)?;}Ok(())}
fn sort<T>(values:&mut[T],control:&mut SqliteSnapshotControl<'_>,mut compare:impl FnMut(&T,&T)->Result<Ordering>)->Result<()>{
 fn sift<T>(values:&mut[T],mut root:usize,end:usize,work:&mut usize,control:&mut SqliteSnapshotControl<'_>,compare:&mut impl FnMut(&T,&T)->Result<Ordering>)->Result<()>{loop{let Some(left)=root.checked_mul(2).and_then(|n|n.checked_add(1)).filter(|n|*n<end)else{return Ok(())};let right=left+1;let child=if right<end&&compare(&values[left],&values[right])?.is_lt(){right}else{left};tick(work,control)?;if !compare(&values[root],&values[child])?.is_lt(){return Ok(())}values.swap(root,child);root=child;}}
 let mut work=0;control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,0,values.len())?;for root in(0..values.len()/2).rev(){sift(values,root,values.len(),&mut work,control,&mut compare)?;}for end in(1..values.len()).rev(){values.swap(0,end);sift(values,0,end,&mut work,control,&mut compare)?;}control.checkpoint(SqliteSnapshotPhase::ReconstructSnapshot,values.len(),values.len())
}
fn identity(row:&SqliteRow,width:usize)->Result<()>{if row.rowid<=0||row.values.len()!=width||row.integer(0)?!=row.rowid{return Err(invalid("PNG row identity or width"))}Ok(())}
/// 🗂️ Ordered typed entities and an independently paid identity-to-ordinal lookup.
pub(super) struct Entities<'a>{pub(super) rows:Vec<&'a SqliteRow>,identities:Vec<(i64,usize)>}
impl<'a> Entities<'a>{
 pub(super) fn new(database:&'a SqliteDatabase,name:&str,width:usize,control:&mut SqliteSnapshotControl<'_>)->Result<Self>{let rows=ordered_row_refs(database.table(name)?,2,control)?;let mut identities=reserve(rows.len(),control)?;let mut work=0;for(index,row)in rows.iter().enumerate(){tick(&mut work,control)?;identity(row,width)?;if row.integer(1)?!=1{return Err(invalid("PNG entity must own document 1"))}identities.push((row.rowid,index));}sort(&mut identities,control,|a,b|Ok(a.0.cmp(&b.0)))?;for pair in identities.windows(2){tick(&mut work,control)?;if pair[0].0==pair[1].0{return Err(invalid("PNG duplicate entity identity"))}}Ok(Self{rows,identities})}
 pub(super) fn index(&self,id:i64)->Result<usize>{self.identities.binary_search_by_key(&id,|entry|entry.0).map(|index|self.identities[index].1).map_err(|_|invalid("PNG sequence references unknown entity"))}
}
/// 🧩️ Byte rows sorted by admitted parent and contiguous child ordinal.
pub(super) struct Children<'a>{rows:Vec<&'a SqliteRow>}
impl<'a> Children<'a>{
 pub(super) fn new(table:&'a SqliteTable,parents:&Entities<'a>,control:&mut SqliteSnapshotControl<'_>)->Result<Self>{let mut rows=reserve(table.rows.len(),control)?;let mut identities=reserve(table.rows.len(),control)?;let mut work=0;for row in &table.rows{tick(&mut work,control)?;identity(row,4)?;parents.index(row.integer(1)?)?;if row.integer(2)?<0{return Err(invalid("PNG unknown byte ordinal must be nonnegative"))}rows.push(row);identities.push(row.rowid);}sort(&mut identities,control,|a,b|Ok(a.cmp(b)))?;for pair in identities.windows(2){tick(&mut work,control)?;if pair[0]==pair[1]{return Err(invalid("PNG duplicate byte identity"))}}sort(&mut rows,control,|a,b|Ok(a.integer(1)?.cmp(&b.integer(1)?).then(a.integer(2)?.cmp(&b.integer(2)?))))?;Ok(Self{rows})}
 pub(super) fn children(&self,parent:i64,control:&mut SqliteSnapshotControl<'_>)->Result<&[&'a SqliteRow]>{let mut work=0;let mut first=0;let mut end=self.rows.len();while first<end{tick(&mut work,control)?;let middle=first+(end-first)/2;if self.rows[middle].integer(1)?<parent{first=middle+1}else{end=middle}}let start=first;end=self.rows.len();while first<end{tick(&mut work,control)?;let middle=first+(end-first)/2;if self.rows[middle].integer(1)?<=parent{first=middle+1}else{end=middle}}let rows=&self.rows[start..first];for(index,row)in rows.iter().enumerate(){tick(&mut work,control)?;if row.integer(2)?!=i64::try_from(index).map_err(|_|ValueError::new(ValueRefusalKind::WorkLimit,"PNG child ordinal overflow"))?{return Err(invalid("PNG unknown bytes require contiguous ordinals"))}}Ok(rows)}
}
/// 🧮️ Checks pixel identity separately from the admitted coordinate occupancy grid.
pub(super) fn pixel_identities(table:&SqliteTable,control:&mut SqliteSnapshotControl<'_>)->Result<()>{let mut ids=reserve(table.rows.len(),control)?;let mut work=0;for row in &table.rows{tick(&mut work,control)?;identity(row,8)?;if row.integer(1)?!=1{return Err(invalid("PNG pixel must own document 1"))}ids.push(row.rowid);}sort(&mut ids,control,|a,b|Ok(a.cmp(b)))?;for pair in ids.windows(2){tick(&mut work,control)?;if pair[0]==pair[1]{return Err(invalid("PNG duplicate pixel identity"))}}Ok(())}
