type Mp4Ftyp { majorBrand: String! minorVersion: Int! compatibleBrands: [String!]! }
union Mp4Codec = Mp4CodecAvc
type Mp4CodecAvc { sps: [[Int!]!]! pps: [[Int!]!]! nalLengthSize: Int! }
type Mp4Sample { data: [Int!]! duration: Int! ctsOffset: Int! sync: Boolean! }
type Mp4Track { trackId: Int! timescale: Int! codec: Mp4Codec! width: Int! height: Int! chunkSampleCounts: [Int!]! samples: [Mp4Sample!]! }
type Mp4Snapshot {
  schema: String! @state(class: ARTIFACT)
  ftyp: Mp4Ftyp! @state(class: ARTIFACT)
  tracks: [Mp4Track!]! @state(class: ARTIFACT)
}
