[package]
name="semio-board-boundary-witness"
version="0.1.0"
edition="2021"
[workspace]
[lib]
path="🦀️.rs"
[dependencies]
semio-framework-value={path="../../../../../../../../🧰️framework/🔨️modules/🌱️value/📦️packages/🦀️rust"}
semio-framework-pack-json={path="../../../../../../../../🧰️framework/🔨️modules/🎒️pack/🔤️json/📦️packages/🦀️rust"}
semio-framework-value-derive={path="../../../../../../../../🧰️framework/🔨️modules/🌱️value/✨️derive/📦️packages/🦀️rust"}
serde={version="1",features=["derive"]}
serde_json="1.0.140"
graph={package="semio-framework-graph",path="../../../../../../../../🧰️framework/🔨️modules/🕸️graph/📦️packages/🦀️rust"}
geometry={package="semio-framework-geometry",path="../../../../../../../../🧰️framework/🔨️modules/📐️geometry/📦️packages/🦀️rust"}
ui_styling={package="semio-framework-ui-styling",path="../../../../../../../../🧰️framework/🔨️modules/🖱️ui/🎨️styling/📦️packages/🦀️rust"}
