/** 🏛️ Neutral spatial/element graphs independently inspected and edited by SQLite. */
import {Database} from "bun:sqlite";
import {expect,test} from "bun:test";
import f from "../🧫️fixtures/🔣️.json";
import type {SemioModelSnapshot,SpatialKind,ElementClass,RelationKind} from "../../../../🧬️schema/📸️snapshot/🟦️.ts";
import {SEMIO_MODEL_SQLITE_SCHEMA,semioModelSnapshotToSqliteDatabase,semioModelSnapshotFromSqliteDatabase} from "../🟦️.ts";
import {binary64,exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
const placement=()=>({translation:{x:binary64(1),y:binary64(-2),z:binary64(3)},rotation:{x:binary64(0),y:binary64(0),z:binary64(0),w:binary64(1)},scale:{x:binary64(1),y:binary64(1),z:binary64(1)}}),spatialKinds:SpatialKind[]=["site","building","storey","space"],classes:ElementClass[]=[{kind:"wall"},{kind:"slab"},{kind:"column"},{kind:"beam"},{kind:"door"},{kind:"window"},{kind:"roof"},{kind:"stair"},{kind:"furniture"},{kind:"other",name:f.otherClassName}],relations:RelationKind[]=[{kind:"aggregates"},{kind:"containedIn"},{kind:"connectsTo"},{kind:"fillsVoid"},{kind:"voidsElement"},{kind:"other",label:f.otherRelationLabel}];
const input:SemioModelSnapshot={schema:f.schema,spatial:spatialKinds.map((kind,i)=>({id:"s"+i,kind,name:"",parentId:i===0?null:"s"+(i-1),placement:placement()})),elements:classes.map((classValue,i)=>({id:"e"+i,class:classValue,placement:placement(),geometry:i%3===0?{kind:"none"}:i%3===1?{kind:"brep",brepId:f.externalGeometryId}:{kind:"mesh",meshId:f.externalGeometryId},spatialId:i%2===0?"s3":null,psets:[{name:"",properties:[{key:f.propertyKey,value:{kind:"text",value:f.propertyText}},{key:f.propertyKey,value:{kind:"number",value:binary64(f.propertyNumber)}},{key:f.propertyKey,value:{kind:"boolean",value:i%2===0}}]},{name:"",properties:[]}]})),relations:relations.map((kind,i)=>({id:"r"+i,kind,from:"s0",to:"e"+i}))};
test("Semio Model independent graph joins and edited typed properties",async()=>{expect(SEMIO_MODEL_SQLITE_SCHEMA).toBe(await Bun.file(new URL("../🗄️.sql",import.meta.url)).text());const db=Database.deserialize(await exportSqliteDatabase(await semioModelSnapshotToSqliteDatabase(input)));try{expect(db.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(db.query(f.query).all()).toHaveLength(6);expect(await semioModelSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(input);db.query("UPDATE semio_model_property SET text_value='independent' WHERE id=1").run();const edited=structuredClone(input);edited.elements[0]!.psets[0]!.properties[0]!.value={kind:"text",value:"independent"};expect(await semioModelSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(edited);}finally{db.close();}});
test("quick::Semio Model IEEE states, hierarchy cycles and exact variant fields",async()=>{for(const hex of f.float64Bits){const s=structuredClone(input),word={bits:BigInt("0x"+hex)};s.spatial[0]!.placement={translation:{x:word,y:word,z:word},rotation:{x:word,y:word,z:word,w:word},scale:{x:word,y:word,z:word}};s.elements[0]!.psets[0]!.properties[1]!.value={kind:"number",value:word};const db=Database.deserialize(await exportSqliteDatabase(await semioModelSnapshotToSqliteDatabase(s)));try{expect(await semioModelSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}}const d=await semioModelSnapshotToSqliteDatabase(input);for(const mutate of[(x:any)=>x.tables[2].rows[0].values[3]=4n,(x:any)=>x.tables[3].rows[0].values[2]="unexpected",(x:any)=>x.tables[5].rows[0].values[2]="unexpected",(x:any)=>x.tables[7].rows[0].values[7]=1n,(x:any)=>x.tables[8].rows[0].values[6]=999n]){const x=structuredClone(d);mutate(x);await expect(semioModelSnapshotFromSqliteDatabase(x)).rejects.toThrow();}const cycle=structuredClone(input);cycle.spatial[0]!.parentId="s3";await expect(semioModelSnapshotToSqliteDatabase(cycle)).rejects.toThrow();await expect(semioModelSnapshotToSqliteDatabase(input,{maxRows:1})).rejects.toThrow();await expect(semioModelSnapshotFromSqliteDatabase(d,{maxValueBytes:1})).rejects.toThrow();const c=new AbortController();c.abort();await expect(semioModelSnapshotFromSqliteDatabase(d,{signal:c.signal})).rejects.toThrow();},30000);

test("Semio Model native construction frontier independently preserves duplicate property keys and empty text",async()=>{const count=f.nativeAdmission.collectionItems,s=structuredClone(input);s.spatial=[];s.elements=[{id:"element",class:{kind:"wall"},placement:placement(),geometry:{kind:"none"},spatialId:null,psets:[{name:"",properties:Array.from({length:count},()=>({key:"",value:{kind:"text",value:""}}))}]}];s.relations=[];const db=Database.deserialize(await exportSqliteDatabase(await semioModelSnapshotToSqliteDatabase(s)));try{expect(db.query("SELECT count(*) AS n FROM semio_model_property").get()).toEqual({n:count});expect(db.query("SELECT property_key,text_value FROM semio_model_property WHERE ordinal=?").get(f.nativeAdmission.cancelAfter)).toEqual({property_key:"",text_value:""});expect(await semioModelSnapshotFromSqliteDatabase(await importSqliteDatabase(db.serialize()))).toEqual(s);}finally{db.close();}});
