[package]
name = "semio-s-kernel-flow-module-bim"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]
name = "flow_module_bim"
crate-type = ["rlib", "cdylib"]
path = "lib.rs"

[features]
default = ["standalone-wasm"]
standalone-wasm = ["dep:wasm-bindgen"]

[dependencies]
flow_module_wasm = { path = "../../wasm/rs", package = "semio-s-kernel-flow-module-wasm" }
neural_engine = { path = "../../../../neural/engine/rs", package = "semio-framework-os-kernel-neural-engine" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
js-sys = "0.3.77"
wasm-bindgen = { version = "0.2.106", optional = true }
