[package]
name = "norm_din_en_16798"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
dsl = { path = "../../../../../framework/kernel/dsl/rs", package = "semio-framework-kernel-dsl" }
norm_core = { path = "../../../../core/rs" }
serde = { version = "1.0.219", features = ["derive"] }
vcs = { path = "../../../../../framework/kernel/vcs/rs", package = "semio-framework-kernel-vcs" }
store = { path = "../../../../../s/kernel/store/rs", package = "semio-s-kernel-store" }
