[package]
name = "semio-s-kernel-geometry-3d-scene"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "kernel_3d_scene"
path = "lib.rs"

[dependencies]
mathematical_algebra = { path = "../../../../../../framework/kernel/mathematical/algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
