(* SemioPresentationDiff token grammar. *)
line   = [ token , { " " , token } ] ;
token  = "masters=" , triple | "layouts=" , triple | "slides=" , triple ;
triple = "[" , list , "];[" , list , "];[" , list , "]" ;
list   = [ item , { "," , item } ] ;
item   = { ? any char except , ; [ ] ? } ;
