# TODO Update port numbering
# Default port number for semio components: SEMIOMAJORVERSION [2] add 2 + COMPONENTTYPE [3]
# SEMIOMAJORVERSION (concatenate major version number and add 2)) e.g. 2:0.6.80
# COMPONENTTYPE: 0:Gateway,1:Assembler,2:Manager,999:GatewayProxy
#
# Default port number for extensions: 650 - OWNERID[3] + PLATFORMID[2]
# OWNERID:
# 0:usalu,1:mrdoob,2:nortikin,
# 150:ifcopenshell,151:cadquery,252:freecad,253:openscad
# 350:nrel
# 450:mcneel,451:autodesk,452:nemetschek,453:esri,454:microsoft
# 550:hypar
# Licenses after https://spdx.org/licenses/

GENERAL_FILEEXTENSIONS = ['txt','json','xml']

[SERVICES]

[SERVICES.GATEWAY]
NAME = 'gateway'
ABBREVIATION = 'g'
PORT = 2000

[SERVICES.GATEWAYRESTPROXY]
NAME = 'gatewayrestproxy'
ABBREVIATION = 'gp'
PORT = 2999

[SERVICES.ASSEMBLER]
NAME = 'assembler'
ABBREVIATION = 'a'
PORT = 2001

[SERVICES.MANAGER]
NAME = 'manager'
ABBREVIATION = 'm'
PORT = 2002

[PLATFORMS]

# Open-source

[PLATFORMS.SEMIO]
URL = 'usalu/semio'
PORT = 65000
FULL_NAME = 'semio'
NAME = 'semio'
LICENSE = 'AGPL-3.0-or-later'
ABBREVIATION = 'semio'
FILEEXTENSION = '.semio'
NORMALFILEEXTENSIONS = ['.semio','.semio.json']
SOURCE = 'https://github.com/usalu/semio'
#LEARN = 'https://usalu.github.io/semio/'
LEARN = 'https://github.com/usalu/semio'

[PLATFORMS.THREE]
URL = 'mrdoob/three'
PORT = 64900
FULL_NAME = 'Three.js'
NAME = 'three'
LICENSE = 'MIT'
ABBREVIATION = 'three'
FILEEXTENSION = '.three.json'
NORMALFILEEXTENSIONS = ['.json']
SOURCE = 'https://github.com/mrdoob/three.js/'
LEARN = 'https://threejs.org/'

[PLATFORMS.SVERCHOK]
URL = 'nortikin/sverchok'
PORT = 64800
FULL_NAME = 'Sverchok'
NAME = 'sverchok'
LICENSE = 'GPL-3.0-only'
ABBREVIATION = 'sk'
FILEEXTENSION = '.sk.json'
NORMALFILEEXTENSIONS = ['.json','.sk.json']
SOURCE = 'https://github.com/nortikin/sverchok'
LEARN = 'https://nortikin.github.io/sverchok/'

[PLATFORMS.IFCOPENSHELL]
URL = 'ifcopenshell/ifcopenshell'
PORT = 50000
FULL_NAME = 'IfcOpenShell'
NAME = 'ifcopenshell'
LICENSE = 'LGPL-3.0-only'
ABBREVIATION = 'ifcos'
FILEEXTENSION = '.ifcos'
NORMALFILEEXTENSIONS = ['.cpp','.py']
SOURCE = 'https://github.com/IfcOpenShell/IfcOpenShell'
LEARN = 'https://ifcopenshell.org/'

[PLATFORMS.CADQUERY]
URL = 'cadquery/cadquery'
PORT = 49900
FULL_NAME = 'CadQuery'
NAME = 'cadquery'
LICENSE = 'LGPL-3.0-only'
ABBREVIATION = 'cq'
FILEEXTENSION = '.cq'
NORMALFILEEXTENSIONS = ['.py','.cq.py']
SOURCE = 'https://github.com/CadQuery/cadquery/'
LEARN = 'https://cadquery.readthedocs.io/en/latest/'

[PLATFORMS.FREECAD]
URL = 'freecad/freecad'
PORT = 49800
FULL_NAME = 'FreeCAD'
NAME = 'freecad'
LICENSE = 'GPL-2.0'
ABBREVIATION = 'fc'
FILEEXTENSION = '.fc'
NORMALFILEEXTENSIONS = ['.FCMAcro','.py']
SOURCE = 'https://github.com/FreeCAD/FreeCAD'
LEARN = 'https://wiki.freecadweb.org/Main_Page'

[PLATFORMS.OPENSCAD]
URL = 'openscad/openscad'
PORT = 49700
FULL_NAME = 'OpenSCAD'
NAME = 'openscad'
LICENSE = 'GPL-2.0'
ABBREVIATION = 'oc'
FILEEXTENSION = '.scad'
NORMALFILEEXTENSIONS = ['.scad']
SOURCE = 'https://github.com/openscad'
LEARN = 'https://openscad.org/'

[PLATFORMS.JSCAD]
URL = 'jscad/jscad'
PORT = 49600
FULL_NAME = 'OpenJSCAD'
NAME = 'jscad'
LICENSE = 'Apache-2.0'
ABBREVIATION = 'jc'
FILEEXTENSION = 'jc.js'
NORMALFILEEXTENSIONS = ['.js']
SOURCE = 'https://github.com/jscad'
LEARN = 'https://openjscad.xyz/'

[PLATFORMS.FORNJOT]
URL = 'hannobraun/fornjot'
PORT = 49500
FULL_NAME = 'Fornjot'
NAME = 'fornjot'
LICENSE = '0BSD'
ABBREVIATION = 'fj'
FILEEXTENSION = '.fj.rs'
NORMALFILEEXTENSIONS = ['.rs']
SOURCE = 'https://github.com/hannobraun/Fornjot'
LEARN = 'https://fornjot.app/'

[PLATFORMS.TRUCK]
URL = ' ricosjp/truck'
PORT = 49400
FULL_NAME = 'Truck'
NAME = 'truck'
LICENSE = 'Apache-2.0'
ABBREVIATION = 'tk'
FILEEXTENSION = 'tk.rs'
NORMALFILEEXTENSIONS = ['.rs']
SOURCE = 'https://github.com/ricosjp/truck'
LEARN = 'https://github.com/ricosjp/truck'

[PLATFORMS.ENERGYPLUS]
URL = ' nrel/energyplus'
PORT = 40000
FULL_NAME = 'EnergyPlus'
NAME = 'energyplus'
# Non-standard license
LICENSE = 'EnergyPlus'
ABBREVIATION = 'ep'
FILEEXTENSION = '.ep'
NORMALFILEEXTENSIONS = ['.idf','.epJSON']
SOURCE = 'https://github.com/NREL/EnergyPlus'
LEARN = 'https://energyplus.net/'

[PLATFORMS.OPENSTUDIO]
URL = ' nrel/openstudio'
PORT = 40001
FULL_NAME = 'OpenStudio'
NAME = 'openstudio'
# Non-standard license
LICENSE = 'OpenStudio'
ABBREVIATION = 'os'
FILEEXTENSION = '.osm'
NORMALFILEEXTENSIONS = ['.osm']
SOURCE =  'https://github.com/NREL/OpenStudio'
LEARN = 'https://openstudio.net/'

# Commercial

[PLATFORMS.RHINO]
URL = 'mcneel/rhino'
PORT = 20000
FULL_NAME = 'Rhinoceros 3D'
NAME = 'rhino'
ABBREVIATION = 'rhino'
FILEEXTENSION = '.3dm'
NORMALFILEEXTENSIONS = ['.3dm']
LEARN = 'https://www.rhino3d.com/'

[PLATFORMS.GRASSHOPPER]
URL = 'mcneel/rhino/grasshopper'
FULL_NAME = 'Grasshopper 3D'
PORT = 20001
NAME = 'grasshopper'
ABBREVIATION = 'gh'
FILEEXTENSION = '.gh'
NORMALFILEEXTENSIONS = ['.gh','.ghx']
LEARN = 'https://www.grasshopper3d.com/'

[PLATFORMS.REVIT]
URL = 'autodesk/revit'
PORT = 19900
FULL_NAME = 'Revit'
NAME = 'revit'
ABBREVIATION = 'rvt'
FILEEXTENSION = '.rfa'
NORMALFILEEXTENSIONS = ['.rfa']
LEARN = 'https://www.autodesk.com/autodesk-university/class/Revit-Family-Creation-Step-Step-Introduction-Just-Beginners-2017'

[PLATFORMS.DYNAMO]
URL = 'autodesk/revit/dynamo'
PORT = 19901
FULL_NAME = 'Dynamo'
NAME = 'dynamo'
ABBREVIATION = 'dyn'
FILEEXTENSION = '.dyn'
NORMALFILEEXTENSIONS = ['.dyn']
LEARN = 'https://primer2.dynamobim.org/'

[PLATFORMS.ARCHICAD]
URL = 'graphisoft/archicad'
PORT = 19800
FULL_NAME = 'ArchiCAD'
NAME = 'archicad'
ABBREVIATION = 'ac'
FILEEXTENSION = '.gsl'
NORMALFILEEXTENSIONS = ['.gdl','.gsl']
LEARN = 'https://gdl.graphisoft.com/'

[PLATFORMS.CITYENGINE]
URL = 'esri/arcgis/cityengine'
PORT = 19600
FULL_NAME = 'ArcGIS CityEngine'
NAME = 'cityengine'
ABBREVIATION = 'ce'
FILEEXTENSION = '.rpk'
NORMALFILEEXTENSIONS = ['.rpk','.cga']
LEARN = 'https://esri.github.io/cityengine/'

[PLATFORMS.EXCEL]
URL = 'microsoft/excel'
PORT = 19500
FULL_NAME = 'Microsoft Excel'
NAME = 'excel'
ABBREVIATION = 'xl'
FILEEXTENSION = '.xlsm'
NORMALFILEEXTENSIONS = ['.xls','.xlsm']
LEARN = 'https://support.microsoft.com/en-us/office/use-the-name-manager-in-excel-4d8c4c2b-9f7d-44e3-a3b4-9f61bd5c64e4'


[PLATFORMS.HYPAR]
URL = 'hypar/hypar'
PORT = 10000
FULL_NAME = 'Hypar'
NAME = 'hypar'
ABBREVIATION = 'hpr'
FILEEXTENSION = '.hpr'
NORMALFILEEXTENSIONS = ['.json']
LEARN = 'https://docs.hypar.io/getting-started'
