DEFAULT_GATEWAY_PORT = 50001
DEFAULT_MANAGER_PORT = 50002

GENERAL_EXTENSIONS = ['txt','json','xml']

# Open source ftw!

# [[Platforms]]
# URL = 'nortikin/sverchok'
# FULL_NAME = 'Sverchok'
# NAME = 'Sverchok'
# ABBREVIATION = 'sk'
# EXTENSIONS = ['.json','.sk.json']
# LEARN = 'https://www.grasshopper3d.com/'

# [[Platforms]]
# URL = 'ifcopenshell/ifcopenshell'
# FULL_NAME = 'IfcOpenShell'
# NAME = 'ifcopenshell'
# ABBREVIATION = 'ifcos'
# EXTENSIONS = ['.cpp','.ifcos.cpp','.py','.ifcos.py']
# LEARN = 'https://ifcopenshell.org/'

# [[Platforms]]
# URL = 'cadquery/cadquery'
# FULL_NAME = 'CadQuery'
# NAME = 'cadquery'
# ABBREVIATION = 'cq'
# EXTENSIONS = ['.py','.cq.py','.cadquery.py']
# LEARN = 'https://github.com/CadQuery/cadquery/'

# [[Platforms]]
# URL = 'freecad/freecad'
# FULL_NAME = 'FreeCAD'
# NAME = 'freecad'
# ABBREVIATION = 'fc'
# EXTENSIONS = ['.FCMAcro','.py']
# LEARN = 'https://github.com/FreeCAD/FreeCAD'

# [[Platforms]]
# URL = 'openscad/openscad'
# FULL_NAME = 'OpenSCAD'
# NAME = 'freecad'
# ABBREVIATION = 'os'
# EXTENSIONS = ['.scad']
# LEARN = 'https://github.com/FreeCAD/FreeCAD'


# Commercial

# [[Platforms]]
# URL = 'mcneel/rhino'
# FULL_NAME = 'Rhinoceros 3D'
# NAME = 'Rhino3D'
# ABBREVIATION = 'rhino'
# EXTENSIONS = ['.3dm']
# LEARN = 'https://www.rhino3d.com/'

[[Platforms]]
URL = 'mcneel/rhino/grasshopper'
FULL_NAME = 'Grasshopper 3D'
NAME = 'Grasshopper'
ABBREVIATION = 'gh'
EXTENSIONS = ['.gh','.ghx']
LEARN = 'https://www.grasshopper3d.com/'

# [[Platforms]]
# URL = 'autodesk/revit'
# FULL_NAME = 'Revit'
# NAME = 'revit'
# ABBREVIATION = 'rvt'
# EXTENSIONS = ['.rfa']
# LEARN = 'https://www.autodesk.com/autodesk-university/class/Revit-Family-Creation-Step-Step-Introduction-Just-Beginners-2017'

# [[Platforms]]
# URL = 'autodesk/revit/dynamo'
# FULL_NAME = 'Dynamo'
# NAME = 'dynamo'
# ABBREVIATION = 'dyn'
# EXTENSIONS = ['.dyn']
# LEARN = 'https://primer2.dynamobim.org/'

# [[Platforms]]
# URL = 'graphisoft/archicad'
# FULL_NAME = 'ArchiCAD'
# NAME = 'archicad'
# ABBREVIATION = 'ac'
# EXTENSIONS = ['.gdl','.gsl']
# LEARN = 'https://gdl.graphisoft.com/'

# [[Platforms]]
# URL = 'microsoft/excel'
# FULL_NAME = 'Microsoft Excel'
# NAME = 'excel'
# ABBREVIATION = 'xl'
# EXTENSIONS = ['.xls','.xlsm']
# LEARN = 'https://support.microsoft.com/en-us/office/use-the-name-manager-in-excel-4d8c4c2b-9f7d-44e3-a3b4-9f61bd5c64e4'

# [[Platforms]]
# URL = 'esri/arcgis/cityengine'
# FULL_NAME = 'ArcGIS CityEngine'
# NAME = 'cityengine'
# ABBREVIATION = 'ce'
# EXTENSIONS = ['.rpk','.cga']
# LEARN = 'https://esri.github.io/cityengine/'

# [[Platforms]]
# URL = 'hypar/hypar'
# FULL_NAME = 'Hypar'
# NAME = 'hypar'
# ABBREVIATION = 'hpr'
# EXTENSIONS = ['.json','hpr.json']
# LEARN = 'https://docs.hypar.io/getting-started'
