services:

  gateway:
    image: semio-gateway:base
    container_name: semio-gateway-00
    ports:
      - 2000:2000
    restart: always
    # networks:
    #   - public
    #   - private

  gatewayrestproxy:
    image: semio-gateway-restproxy:tiny
    container_name: semio-server-00
    ports:
      - 2999:2999
    restart: always
    # networks:
    #   - public
    #   - private

  assembler:
    image: semio-assembler:base
    container_name: semio-assembler-00
    ports:
      - 2001:2001
    restart: always
    # networks:
    #   - public
    #   - private
  
  manager:
    image: semio-manager:base
    container_name: semio-manager-00
    ports:
      - 2002:2002
    restart: always
    # networks:
    #   - public
    #   - private

  grasshopper:
    image: semio-grasshopper:base
    container_name: semio-grasshopper-00
    restart: always
    ports:
      - 20000:20000
      - 6500:6500
    # networks:
    #   - private
