# import NoteArtifact, NoteBlockNode, NoteImageAsset from "../🔗️.graphql"
# import ArtifactChild from "🧰️framework/🛍️products/💻️os/🔨️modules/🏪️store/🪆️child/🧬️schema/🔗️.graphql"
# import ArtifactLink from "🧰️framework/🛍️products/💻️os/🔨️modules/🏪️store/🔗️link/🧬️schema/🔗️.graphql"
type NoteDiff {
  artifact: NoteArtifact
  schema: String
  id: String
  title: String
  blocks: NoteBlocksDelta
  gridVisible: Boolean
  gridSpacing: Float
  gridSubdivisions: Float
  gridOpacity: Float
  snapEnabled: Boolean
  snapGridSpacing: Float
  pencilWidth: Float
  eraserRadius: Float
  assets: NoteAssetsDelta
  linkedArtifact: ArtifactLink
}
type NoteAddedBlockEntry { parentId: String index: Int block: NoteBlockNode! }
type NoteBlockPatch { blockJson: String }
type NoteBlockPatchEntry { id: String! patch: NoteBlockPatch! }
type NoteBlocksDelta { added: [NoteAddedBlockEntry!]! removed: [String!]! patched: [NoteBlockPatchEntry!]! reordered: [String!] }
type NoteAssetDeltaEntry { key: String! value: NoteImageAsset }
type NoteAssetsDelta { entries: [NoteAssetDeltaEntry!]! }
