@startuml "data architecture"
skinparam linetype ortho

entity semio {
    *release : string <<PK>>
    *created_by_app : string
    *app_version : string
    *created_at : datetime
}

entity attributes {
    *id : int <<PK,generated>>
    *name : string
    *value : string
    *unit : string
    *definition : string
    ..
    representation_id : int <<FK>>
    port_id : int <<FK>>
    type_id : int <<FK>>
    piece_id : int <<FK>>
    connection_id : int <<FK>>
    design_id : int <<FK>>
    kit_id : int <<FK>>
    --
    CHECK (( (representation_id IS NOT NULL AND port_id IS NULL AND type_id IS NULL AND piece_id IS NULL AND connection_id IS NULL AND design_id IS NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NOT NULL AND type_id IS NULL AND piece_id IS NULL AND connection_id IS NULL AND design_id IS NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NULL AND type_id IS NOT NULL AND piece_id IS NULL AND connection_id IS NULL AND design_id IS NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NULL AND type_id IS NULL AND piece_id IS NOT NULL AND connection_id IS NULL AND design_id IS NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NULL AND type_id IS NULL AND piece_id IS NULL AND connection_id IS NOT NULL AND design_id IS NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NULL AND type_id IS NULL AND piece_id IS NULL AND connection_id IS NULL AND design_id IS NOT NULL AND kit_id IS NULL)
        OR (representation_id IS NULL AND port_id IS NULL AND type_id IS NULL AND piece_id IS NULL AND connection_id IS NULL AND design_id IS NULL AND kit_id IS NOT NULL)
        ))
}


entity qualities {
    *id : int <<PK,generated>>
    *key : string
    *name : string
    *description : string
    *uri : string
    *kind : int
    *can_scale : boolean
    *default_si_unit : string
    *default_imperial_unit : string
    *min : float
    *is_min_excluded : boolean
    *max : float
    *is_max_excluded : boolean
    *default_value : float
    *formula : string
    *created_at : datetime
    *updated_at : datetime
    ..
    kit_id : int <<FK>>
    --
    CHECK (kind >= 0 AND kind <= 63)
    CHECK (kind & (kind - 1) = 0 OR kind IN (0, 1, 2, 4, 8, 16))
}

entity benchmarks {
    *id : int <<PK,generated>>
    *name : string
    *icon : string
    *min : float
    *is_min_excluded : boolean
    *max : float
    *is_max_excluded : boolean
    ..
    quality_id : int <<FK>>
    --
}

entity props {
    *id : int <<PK,generated>>
    *key : string
    *value : string
    *unit : string
    *created_at : datetime
    *updated_at : datetime
    ..
    port_id : int <<FK>>
    --
}

entity stats {
    *id : int <<PK,generated>>
    *key : string
    *unit : string
    *min : float
    *is_min_excluded : boolean
    *max : float
    *is_max_excluded : boolean
    *created_at : datetime
    *updated_at : datetime
    ..
    design_id : int <<FK>>
    --
}

entity tags {
    *id : int <<PK,generated>>
    *name : string
    *order : int
    ..
    representation_id : int <<FK>>
}

entity concepts {
    *id : int <<PK,generated>>
    *name : string
    *order : int
    ..
    kit_id : int <<FK>>
    type_id : int <<FK>>
    design_id : int <<FK>>
    --
    CHECK (( (kit_id IS NOT NULL AND type_id IS NULL AND design_id IS NULL)
        OR (kit_id IS NULL AND type_id IS NOT NULL AND design_id IS NULL)
        OR (kit_id IS NULL AND type_id IS NULL AND design_id IS NOT NULL)
        ))
}

entity representations {
    *id : int <<PK,generated>>
    *url : string
    *description : string
    ..
    type_id : int <<FK>>
    --
}

entity planes {
    *id : int <<PK,generated>>
    *origin_x : float
    *origin_y : float
    *origin_z : float
    *x_axis_x : float
    *x_axis_y : float
    *x_axis_z : float
    *y_axis_x : float
    *y_axis_y : float
    *y_axis_z : float
}

entity compatible_families {
  *id : int <<PK,generated>>
  *name : string
  *order : int
  ..
  port_id : int <<FK>>
}

entity ports {
    *id : int <<PK,generated>>
    *port_id : string
    *description : string
    *family : string
    *is_mandatory : boolean
    *point_x : float
    *point_y : float
    *point_z : float
    *direction_x : float
    *direction_y : float
    *direction_z : float
    *t : float
    ..
    type_id : int <<FK>>
    --
    CHECK (t >= 0 AND t < 1)
    UNIQUE (port_id, type_id)
}

entity authors {
    *id : int <<PK,generated>>
    *name : string
    *email : string
    ..
    kit_id : int <<FK>>
}

entity author_artifact {
    *author_id : int <<PK,FK>>
    *rank : int
    type_id : int <<PK,FK>>
    design_id : int <<PK,FK>>
    --
    CHECK ((type_id IS NOT NULL AND design_id IS NULL) OR
           (type_id IS NULL AND design_id IS NOT NULL))
}

entity types {
    *id : int <<PK,generated>>
    *name : string
    *description : string
    *icon : string
    *image_url : string
    *variant : string
    *stock : float
    *is_virtual : boolean
    *can_scale : boolean
    *can_mirror : boolean
    *unit : string
    *location_longitude : float
    *location_latitude : float
    *created_at : datetime
    *updated_at : datetime
    ..
    kit_id : int <<FK>>
    --
    UNIQUE (name, variant, kit_id)
    CHECK (stock >= 0 AND stock <= 2147483647)
    CHECK (location_longitude IS NULL AND location_latitude IS NULL
    OR (location_longitude IS NOT NULL AND location_latitude IS NOT NULL))
}

entity pieces {
    *id : int <<PK,generated>>
    *piece_id : string
    *description : string
    *plane_id : int <<FK>>
    *center_x : float
    *center_y : float
    *scale : float
    mirror_plane_id : int <<FK>>
    *is_hidden: boolean
    *is_locked: boolean
    *color: string
    ..
    type_id : int <<FK>>
    design_id : int <<FK>>
    parent_piece_id : int <<FK>>
    --
    CHECK ((type_id IS NOT NULL AND design_id IS NULL AND parent_piece_id IS NULL) OR
           (type_id IS NULL AND design_id IS NOT NULL AND parent_piece_id IS NOT NULL))
    CHECK (color = '' OR color ~ '^#[0-9A-Fa-f]{6}$')
    UNIQUE (piece_id, design_id)
}

entity connections {
    *id : int <<PK,generated>>
    *connected_piece_id : int <<FK>>
    *connected_design_piece_id : int <<FK>>
    *connected_port_id : int <<FK>>
    *connecting_piece_id : int <<FK>>
    *connecting_design_piece_id : int <<FK>>
    *connecting_port_id : int <<FK>>
    *description : string
    *gap : float
    *shift : float
    *rise : float
    *rotation : float
    *turn : float
    *tilt : float
    *x : float
    *y : float
    ..
    design_id : int <<FK>>
    --
    CHECK (description IS NOT NULL OR description = '')
    CHECK (connecting_piece_id != connected_piece_id)
}

entity layers {
    *id : int <<PK,generated>>
    *name : string
    *description : string
    *color: string
    ..
    design_id : int <<FK>>
    --
    CHECK (color = '' OR color ~ '^#[0-9A-Fa-f]{6}$')
}

entity groups {
    *id : int <<PK,generated>>
    name : string
    description : string
    *color: string
    ..
    design_id : int <<FK>>
    --
    CHECK (color = '' OR color ~ '^#[0-9A-Fa-f]{6}$')
}

entity group_pieces {
    *group_id : int <<PK,FK>>
    *piece_id : int <<PK,FK>>
}

entity designs {
    *id : int <<PK,generated>>
    *name : string
    *description : string
    *icon : string
    *image_url : string
    *variant : string
    *view : string
    *can_scale : boolean
    *can_mirror : boolean
    *unit : string
    location_longitude : float
    location_latitude : float
    *created_at : datetime
    *updated_at : datetime
    ..
    kit_id : int <<FK>>
    --
    UNIQUE (name, variant, view, kit_id)
    CHECK (name != '')
    CHECK (unit != '')
    CHECK (location_longitude IS NULL AND location_latitude IS NULL
    OR (location_longitude IS NOT NULL AND location_latitude IS NOT NULL))
}

entity kits {
    *id : int <<PK,generated>>
    *name : string
    *description : string
    *icon : string
    *image_url : string
    *avatar_url : string
    *version : string
    *remote_url : string
    *homepage_url : string
    *license : string
    *created_at : datetime
    *updated_at : datetime
    --
    CHECK (name != '')
}

kits ||--o{ types
kits ||--o{ designs
kits ||--o{ authors
kits ||--o{ qualities
kits ||--o{ attributes
kits ||--o{ concepts

designs ||--o{ layers
designs ||--o{ pieces
designs ||--o{ groups
designs ||--o{ connections
designs ||--o{ stats
designs ||--o{ attributes
designs ||--o{ concepts
designs -- authors : "has" >

group_pieces -- groups
group_pieces -- pieces

types ||--o{ representations
types ||--o{ ports
types ||--o{ authors
types ||--o{ attributes
types ||--o{ concepts
types -- authors : "has" >

pieces ||--o{ planes
pieces ||--o{ attributes

connections ||--o{ attributes

representations ||--o{ tags
representations ||--o{ attributes

ports ||--o{ compatible_families
ports ||--o{ attributes
ports ||--o{ props

qualities ||--o{ benchmarks

connections -- pieces : "connected" >
connections -- pieces : "connecting" >
connections -- ports : "connected" >
connections -- ports : "connecting" >

@enduml