@startuml "data architecture"
skinparam linetype ortho

interface Artifact {
    *name : string
    *description : string
    *icon : string
    *image : string
    ..
    *createdAt : datetime
    *lastUpdatedAt : datetime
}
note left of Artifact
    description is optional
    (can be set to "").
    icon is optional
    (can be set to "").
    icon in data:uri format.
end note

entity Kit {
    *id : int <<PK,generated>> 
    ..
    *uri : string
    ..
    *version : string
    *remote : string
    *homepage : string
    *license : string
}
note left of Kit
    uri is unique.
    version="" means latest.
    remote is optional
    (can be set to "").
    homepage is optional
    (can be set to "").
    license is optional
    (can be set to "").

end note

entity Type {
    *id : int <<PK,generated>>
    ..
    *variant : string
    *unit : string
    ..
    *kitId : int <<FK>>
}
note right of Type
    name and variant
    are unique together.
    variant="" means default.
end note

entity Representation {
    *id : int <<PK,generated>>
    ..
    *url : string
    *mime : string
    *lod : string
    ..
    *typeId : int <<FK>>
}
note right of Representation
    mime, lod and tags
    are unique together.
    lod="" means default.
end note

entity Tag {
    *value : string <<PK>>
    ..
    *representationId : int <<PK,FK>>
}

entity Port {
    *id : int <<PK,generated>>
    ..
    *localId : string
    ..
    *pointX : float
    *pointY : float
    *pointZ : float
    ..
    *directionX : float
    *directionY : float
    *directionZ : float
    ..
    *typeId : int <<FK>>
}
note right of Port
    localId and typeId
    are unique together.
    localId="" means default.
end note

entity Quality {
    *id : int <<PK,generated>>
    ..
    *name : string
    *value : string
    *unit : string
    *definition : string
    ..
    typeId : int <<FK>>
    designId : int <<FK>>
}
note bottom of Quality
    Either typeId or designId
    must be set.
    value="" means true.
    unit is optional
    (can be set to "").
    definition is optional.
    (can be set to "").
end note

entity Author {
    *name : string
    *email : string
    ..
    *typeId : int <<PK,FK>>
    *designId : int <<PK,FK>>
}
note right of Authors
    Either typeId or designId
    must be set.
end note

entity Locator {
    *group : string <<PK>>
    *subgroup : string
    ..
    *portId : int <<PK,FK>>
}
note right of Locator
    subgroup is optional
    (can be set to "").
end note

entity Piece {
    *id : int <<PK,generated>>
    ..
    *localId : string
    *typeId : int <<FK>>
    ..
    planeOriginX : float
    planeOriginY : float
    planeOriginZ : float
    ..
    planeXAxisX : float
    planeXAxisY : float
    planeXAxisZ : float
    ..
    planeYAxisX : float
    planeYAxisY : float
    planeYAxisZ : float
    ..
    *centerX : int
    *centerY : int
    ..
    *designId : int <<FK>>
}
note right of Piece
    localId and designId
    are unique together.
    root plane can only be set
    when piece is root.
    Otherwise all values are null.
end note

entity Connection {
    *connectingPieceId : int <<PK,FK>>
    *connectingPieceTypePortId : int <<FK>>
    ..
    *connectedPieceId : int <<PK,FK>>
    *connectedPieceTypePortId : int <<FK>>
    ..
    *rotation : float
    *tilt : float
    *gap : float
    *shift : float
    ..
    *x : float
    *y : float
    ..
    *designId : int <<FK>>
}
note right of Connection
    gap is in normal 
    direction and optional
    (can be set to 0).
    rotation is azimuthal
    angle of normal in
    degree [0,360[
    and optional
    (can be set to 0). 
end note

entity Design {
    *id : int <<PK,generated>>
    ..
    *variant : string
    *unit : string
    ..
    *kitId : int <<FK>>
}
note right of Design
    name and variant
    are unique together.
    variant="" means default.
end note

Kit ||--o{ Design
Kit ||--o{ Type 
Tag }o--|| Representation
Representation }|--|| Type
Type ||--|{ Port
Type ||--o{ Quality
Type ||--o{ Author
Design ||--|{ Piece
Design ||--o{ Connection
Design ||--o{ Quality
Design ||--o{ Author
Port ||--o{ Locator
Type <-- Piece
Piece <-- Connection
Port <-- Connection

Artifact <|-- Kit
Artifact <|-- Design
Artifact <|-- Type

@enduml