[package]
name = "semio-framework-os-kernel-math-graph-connectivity"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_connectivity"
crate-type = ["rlib"]
path = "../../../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph/🔗connectivity/📦lib.rs"

[dependencies]
mathematical_graph = { path = "../../../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph", package = "semio-framework-os-kernel-math-graph" }
mathematical_graph_flow = { path = "../../../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph/🌊flow", package = "semio-framework-os-kernel-math-graph-flow" }
mathematical_graph_components = { path = "../../../../../../../🧰framework/🔨module/🧮math/⚡️implementation/🦀rust/🕸️graph/🧩components", package = "semio-framework-os-kernel-math-graph-components" }
