[package]
name = "semio-s-plugin-vcs"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.component]
package = "semio:vcs"

[package.metadata.semio]

[[package.metadata.semio.playground]]
variant = "vcs"
ports = { react = 6075, wgpu = 6175 }

[lib]
crate-type = ["cdylib", "rlib"]
path = "../../../../../../../✏️s/🔌️plugins/🌿️vcs/🛂️manifest/🗿️artifact/⚡️implementations/🦀️rust/📦️lib.rs"

[dependencies]
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/⚡️implementations/🦀️rust", features = ["component-guest"], package = "semio-framework-plugin" }
vcs = { path = "../../../../../../../✏️s/🔌️plugins/🌿️vcs/🎛️apps/🌿️vcs/⚡️implementations/🦀️rust", package = "semio-s-app-vcs" }
vcs_ui = { path = "../../../../../../../✏️s/🔌️plugins/🌿️vcs/🎛️apps/🌿️vcs/🔨️modules/🖱️ui/⚡️implementations/🦀️rust", package = "semio-s-app-vcs-ui" }

