import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {lstat,readdir,rmdir,unlink} from "node:fs/promises";
import {dirname,join,resolve} from "node:path";
const ticket=dirname(import.meta.dir),[command,epoch="1"]=process.argv.slice(2),base=join(ticket,"🗑️generated/product-wgpu-native-whole"),out=join(ticket,"🗑️generated/native-capacity-retirement/epoch-"+epoch),sha=(s:string)=>createHash("sha256").update(s).digest("hex"),control=new AbortController(),cancel=()=>control.abort(new Error("capacity retirement canceled"));
assert.equal(command,"retire");assert.equal(existsSync(out),false);const rows=[["3","independent-compiler-post-observation-1.json"],["4","independent-compiler-post-observation-2.json"],["5","independent-physical-source-observation-1.json"],["6","independent-physical-source-observation-1.json"]].map(([epoch,proof])=>{const root=join(base,"epoch-"+epoch!),proofPath=join(root,proof!),proofSource=readFileSync(proofPath,"utf8"),terminalPath=join(root,"terminal-1.json"),terminalSource=readFileSync(terminalPath,"utf8"),post=join(root,"compiler-post-1.json"),target=join(root,"target");assert.equal(JSON.parse(proofSource).ready,true,proofPath);assert.ok(JSON.parse(terminalSource).sourcePostUnavailable!==true);assert.ok(existsSync(post));assert.ok(existsSync(target));return{epoch,target,proof:{path:proofPath,source:proofSource,sha256:sha(proofSource)},terminal:{path:terminalPath,source:terminalSource,sha256:sha(terminalSource)},post};});
mkdirSync(out,{recursive:true});writeFileSync(join(out,"plan.json"),JSON.stringify({producer:{path:import.meta.path,source:readFileSync(import.meta.path,"utf8")},rows,scope:"Only the four explicitly nominated completed Product3–6 ticket target caches retire. Full compiler source/.d/checksum observation receipts, terminal logs, Low proofs, GUI/source inputs, all other targets and active Product7 target remain retained. No source or validation outcome is changed."}));
let files=0,directories=0,bytes=0,finished=false;process.once("SIGINT",cancel);process.once("SIGTERM",cancel);
const progress=setInterval(()=>console.log("[DEBUG] Completed native target retirement "+JSON.stringify({files,directories,bytes})),10_000);
async function retire(path:string):Promise<void>{control.signal.throwIfAborted();const stat=await lstat(path);if(!stat.isDirectory()||stat.isSymbolicLink()){assert.ok(files<500_000&&bytes+stat.size<100*1024**3);await unlink(path);files++;bytes+=stat.size;}else{for(const name of await readdir(path))await retire(join(path,name));control.signal.throwIfAborted();await rmdir(path);directories++;}if((files+directories)%512===0)await new Promise<void>(resolve=>setImmediate(resolve));}
try{for(const row of rows){assert.equal(readFileSync(row.proof.path,"utf8"),row.proof.source);assert.equal(readFileSync(row.terminal.path,"utf8"),row.terminal.source);await retire(row.target);assert.equal(existsSync(row.target),false);assert.ok(existsSync(row.post));console.log("[DEBUG] Retired completed Product native cache "+JSON.stringify({epoch:row.epoch,files,directories,bytes}));}finished=true;}finally{clearInterval(progress);process.off("SIGINT",cancel);process.off("SIGTERM",cancel);for(const row of rows){assert.equal(readFileSync(row.proof.path,"utf8"),row.proof.source);assert.equal(readFileSync(row.terminal.path,"utf8"),row.terminal.source);assert.ok(existsSync(row.post));}writeFileSync(join(out,"terminal.json"),JSON.stringify({finished,files,directories,bytes,targets:rows.map(row=>({path:row.target,removed:!existsSync(row.target)})),sourceWrites:0,proofsRetained:true,activeTargetsTouched:false,wholeRootAccepted:false}));}
