enum WavMutationTag {
  SET_FMT
  SET_DATA
  PATCH_DATA
  SET_OTHER_CHUNKS
}
input WavMutationFmt { audioFormat: Int!, channels: Int!, sampleRate: Int!, byteRate: Int!, blockAlign: Int!, bitsPerSample: Int!, ext: [Int!] }
input WavMutationData { kind: String!, value: [Float!]! }
input WavMutationRiffChunk { fourcc: String!, data: [Int!]!, padByte: Int }
input WavMutationChunkRef { kind: String!, value: Int }
input WavMutationInput {
  mutation: WavMutationTag!
  fmt: WavMutationFmt
  data: WavMutationData
  index: Int
  removeCount: Int
  moveTo: Int
  chunks: [WavMutationRiffChunk!]
  chunkOrder: [WavMutationChunkRef!]
}
