[package]
name = "semio-framework-kernel-mathematical-lie"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
name = "mathematical_lie"
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
mathematical_algebra = { path = "../../algebra/rs", package = "semio-framework-kernel-mathematical-algebra" }
