//! 🤖️ Generated by `bun ./📜️script.ts surface-schema` (surface-schema-projection) — do not edit.
//! @see 🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/🦀️.rs

/// 🧬️ presence schema of `s.stdio.gif`, projected from `NoPresence`.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct NoPresence {}
