[package]
name = "sequence_core"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["rlib", "cdylib"]
path = "lib.rs"

[dependencies]
imperative_engine = { path = "../../../imperative/engine/rs" }
imperative_module_core = { path = "../../../imperative/module/core/rs" }
neural_engine = { path = "../../../s/kernel/neural/engine/rs", package = "semio-s-kernel-neural-engine" }
infinite_board_port_directed_dag = { path = "../../../s/kernel/infinite/board/port/directed/dag/rs", package = "semio-s-kernel-infinite-board-port-directed-dag" }
mathematical_graph_manifest = { path = "../../../s/kernel/mathematical/graph/manifest/rs", package = "semio-s-kernel-mathematical-graph-manifest" }
infinite_cavas = { path = "../../../s/kernel/infinite/canvas/rs", package = "semio-s-kernel-infinite-canvas" }
vcs = { path = "../../../s/kernel/vcs/rs", package = "semio-s-kernel-vcs" }
store = { path = "../../../s/kernel/store/rs", package = "semio-s-kernel-store" }
protocol = { path = "../../../s/kernel/protocol/rs", package = "semio-s-kernel-protocol" }
dsl = { path = "../../../s/kernel/dsl/rs", package = "semio-s-kernel-dsl" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.83"
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.71"
web-sys = { version = "0.3.98", features = ["HtmlCanvasElement"] }
