import assert from "node:assert/strict";
import { lstat, readdir, readFile, writeFile, mkdir, unlink, rmdir, statfs } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
const ticket=dirname(import.meta.dir),root=resolve(ticket,"../../../../../../.."),[command,epoch]=process.argv.slice(2);
assert.equal(process.argv.length,4);assert.equal(command,"retire");assert.equal(epoch,"1");
const producer=await readFile(import.meta.path,"utf8"),input=await readFile(join(import.meta.dir,"🔣️.json"),"utf8"),schemaSource=await readFile(join(import.meta.dir,"🧬️schema.json"),"utf8"),request=JSON.parse(input),schema=JSON.parse(schemaSource);
const { validateJsonSchemaSubset }=await import(join(root,"🧰️framework/🔨️modules/🧬️schema/✅️validator/🟦️.ts")),{ observePhysicalFileV1 }=await import(join(root,"🧰️framework/🔨️modules/📁️filesystem/🧾️observation/🟦️.ts"));
assert.deepEqual(validateJsonSchemaSubset(schema,request),[]);const require=createRequire(join(root,"package.json"));assert.equal(new(require("ajv"))({strict:true}).compile(schema)(request),true);
const output=join(ticket,"🗑️generated/catalog-closed-cache-retirement-"+epoch);await mkdir(output,{recursive:false});
let cancelled=false,work=0,bytes=0,lastProgress=0,error:string|undefined;const started=Date.now(),stop=()=>{cancelled=true;},check=()=>{assert(!cancelled,"Retirement cancelled");assert(Date.now()-started<request.budgetMs,"Retirement deadline");assert(work<request.maximumWork,"Retirement work capacity");work++;};process.on("SIGINT",stop);process.on("SIGTERM",stop);
const progress=(phase:string)=>{if(Date.now()-lastProgress>2000){lastProgress=Date.now();process.stderr.write(`[DEBUG] Closed catalog Nx cache ${phase} bytes=${bytes} work=${work}\n`);}};
const base=join(ticket,"🗑️generated",request.directory),identity=(s:Awaited<ReturnType<typeof lstat>>)=>({dev:s.dev,ino:s.ino,size:s.size,mtimeMs:s.mtimeMs,ctimeMs:s.ctimeMs}),rows:any[]=[],directories:any[]=[],receipts:any[]=[],censuses:any[]=[];
const census=()=>{check();assert.notEqual(process.platform,"win32","Native Windows handle observation was not admitted");const processes=spawnSync("ps",["ax","-o","pid=,command="],{encoding:"utf8",timeout:5000,maxBuffer:4194304});assert.equal(processes.status,0,"Process census failed");const handles=spawnSync("lsof",["-nP","+D",base],{encoding:"utf8",timeout:30000,maxBuffer:4194304});censuses.push({processes,handles});assert.equal(handles.error,undefined);assert.equal(handles.signal,null);assert.equal(handles.status,1,"Owned cache has open native handles");assert.equal(handles.stdout.trim(),"");const live=processes.stdout.split(/\r?\n/u).filter(line=>line.includes("catalog-composition-deletion-inputs/📜️script.ts")||/nx(?:\.js)?\s+run\s+@semio-tech\/(?:framework-plugin-web:test-catalog|s-dev-composition:(?:catalog-check|(?:generate|check|preview)-playground-session)|framework-os-dev:(?:generate|check|preview)-playground-session)|bun.*📜️script\.ts\s+test\s+generator-preview-receiving/u.test(line));assert.deepEqual(live,[],"Catalog consumer process is live");};
const freeBefore=await statfs(ticket);
try{
 for(const relative of request.receipts){check();const path=join(ticket,"🗑️generated",relative),source=await readFile(path,"utf8"),receipt=JSON.parse(source);assert.equal(receipt.outerExitCode,0);if(relative.includes("routes"))assert.equal(receipt.routeCodes.trim().split("\n").every((line:string)=>line.endsWith(" 0")),true);receipts.push({path,source});const directory=dirname(path);for(const phase of["before","after"]){const journal=join(directory,phase+".jsonl"),body=await readFile(journal,"utf8");for(const line of body.trim().split("\n")){check();const row=JSON.parse(line);assert.equal(typeof row.source,"string");assert.equal(createHash("sha256").update(row.source).digest("hex"),row.sha256);}receipts.push({path:journal,byteLength:Buffer.byteLength(body),sha256:createHash("sha256").update(body).digest("hex")});}}
 census();assert.deepEqual((await readdir(base)).sort(),["cache","workspace-data"]);
 const walk=async(path:string):Promise<void>=>{check();const s=await lstat(path);assert(!s.isSymbolicLink(),"Cache link refused");if(s.isDirectory()){directories.push({path,dev:s.dev,ino:s.ino});for(const name of await readdir(path))await walk(join(path,name));return;}assert(s.isFile(),"Nonregular cache refused");assert(rows.length<request.maximumFiles);assert(s.size<=268435456&&s.size<=request.maximumBytes-bytes);const before=identity(s),initial=work;let observedWork=0;const claim=await observePhysicalFileV1(path,{maxBytes:Math.min(268435456,request.maximumBytes-bytes),maxWork:request.maximumWork-work,chunkBytes:1048576,cancelled:()=>cancelled,remainingMs:()=>request.budgetMs-(Date.now()-started),onProgress:event=>{observedWork=event.work;progress("observe");}});work=initial+observedWork;bytes+=claim.byteLength;assert.deepEqual(identity(await lstat(path)),before);rows.push({path,identity:before,claim,retired:false});};await walk(base);
 await writeFile(join(output,"admission.json"),JSON.stringify({producer,input,schemaSource,receipts,rows,directories,censuses,freeBefore,atomicSnapshotClaimed:false}));
 census();for(const row of rows){check();assert.equal(await readFile(import.meta.path,"utf8"),producer);assert.deepEqual(identity(await lstat(row.path)),row.identity);await unlink(row.path);row.retired=true;progress("retire");}
 for(const row of directories.reverse()){check();const s=await lstat(row.path);assert(s.isDirectory()&&!s.isSymbolicLink());assert.equal(s.dev,row.dev);assert.equal(s.ino,row.ino);await rmdir(row.path);}
 for(const receipt of receipts){const body=await readFile(receipt.path,"utf8");if(receipt.source!==undefined)assert.equal(body,receipt.source);else{assert.equal(Buffer.byteLength(body),receipt.byteLength);assert.equal(createHash("sha256").update(body).digest("hex"),receipt.sha256);}}
 assert.equal(await readFile(import.meta.path,"utf8"),producer);assert.equal(await readFile(join(import.meta.dir,"🔣️.json"),"utf8"),input);assert.equal(await readFile(join(import.meta.dir,"🧬️schema.json"),"utf8"),schemaSource);
}catch(failure){error=String(failure);process.exitCode=1;}finally{process.off("SIGINT",stop);process.off("SIGTERM",stop);const freeAfter=await statfs(ticket);await writeFile(join(output,"terminal.json"),JSON.stringify({error,producer,input,schemaSource,receipts,rows,directories,censuses,bytes,work,freeBefore,freeAfter,atomicSnapshotClaimed:false,allPlatformsAccepted:false}));await writeFile(join(ticket,"CATALOG-CLOSED-NX-CACHE-RETIREMENT.md"),"# Closed Catalog Nx Cache Retirement\n\n"+(error?"Refused/partial: "+error:"Closed: retired only the physically closed catalogue Nx cache/workspace-data tree.")+"\n\nObserved "+rows.length+" files, "+bytes+" bytes and "+work+" work with bounded byte/work/deadline/cancellation/progress authority. Native process and open-file census, exact per-file descriptor/path observation and pre-unlink identity are journaled. All source/input/full-body custody, reports, receipts and terminals remain; current copied15 and every peer/shared Native target remain untouched. No atomic or all-platform claim.\n");console.log(JSON.stringify({error,files:rows.length,retired:rows.filter(row=>row.retired).length,bytes,work,availableBytes:freeAfter.bavail*freeAfter.bsize}));}
