[package]
name = "norm_en_1995"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
norm_core = { path = "../../../core/rs" }
serde = { version = "1.0.219", features = ["derive"] }
mathematical_algebra = { path = "../../../../mathematical/algebra/rs" }
fem_core = { path = "../../../../fem/core/rs" }
norm_en_1990 = { path = "../../1990/rs" }
norm_en_1991 = { path = "../../1991/rs" }
