//! 🖼️ Texture, image and sampler entities preserve every optional reference and full filter word.
use super::*;
pub(super) fn project(write:&mut Write<'_,'_>,document:&GltfDocument)->Result<(),String>{
 write.check(document.textures.len())?;for(position,texture)in document.textures.iter().enumerate(){let [sampler_high,sampler_low]=optional_index(texture.sampler);let [source_high,source_low]=optional_index(texture.source);let [extension,extra]=write.extras(&texture.extensions,&texture.extras)?;write.insert("gltf_texture",&[Cell::Integer(1),ordinal(position)?,sampler_high,sampler_low,source_high,source_low,text(&texture.name),extension,extra])?;}
 write.check(document.images.len())?;for(position,image)in document.images.iter().enumerate(){let [high,low]=optional_index(image.buffer_view);let [extension,extra]=write.extras(&image.extensions,&image.extras)?;write.insert("gltf_image",&[Cell::Integer(1),ordinal(position)?,text(&image.uri),text(&image.mime_type),high,low,text(&image.name),extension,extra])?;}
 write.check(document.samplers.len())?;for(position,sampler)in document.samplers.iter().enumerate(){let [mag_high,mag_low]=optional_word(sampler.mag_filter);let [min_high,min_low]=optional_word(sampler.min_filter);let [s_high,s_low]=word(sampler.wrap_s);let [t_high,t_low]=word(sampler.wrap_t);let [extension,extra]=write.extras(&sampler.extensions,&sampler.extras)?;write.insert("gltf_sampler",&[Cell::Integer(1),ordinal(position)?,mag_high,mag_low,min_high,min_low,s_high,s_low,t_high,t_low,text(&sampler.name),extension,extra])?;}
 Ok(())
}
pub(super) fn reconstruct(read:&mut Read<'_,'_,'_>,document:&mut GltfDocument)->Result<(),String>{
 let rows=read.rows("gltf_texture",1,1,2)?;document.textures.reserve(rows.len());for row in rows{let mut texture=owned(GltfTexture::default());let value=texture.as_mut();value.sampler=read.optional_index(row,3)?;value.source=read.optional_index(row,5)?;value.name=read.optional_text(row,7)?;value.extensions=read.json(row,8)?;value.extras=read.json(row,9)?;document.textures.push(texture.take());}
 let rows=read.rows("gltf_image",1,1,2)?;document.images.reserve(rows.len());for row in rows{let mut image=owned(GltfImage::default());let value=image.as_mut();value.uri=read.optional_text(row,3)?;value.mime_type=read.optional_text(row,4)?;value.buffer_view=read.optional_index(row,5)?;value.name=read.optional_text(row,7)?;value.extensions=read.json(row,8)?;value.extras=read.json(row,9)?;document.images.push(image.take());}
 let rows=read.rows("gltf_sampler",1,1,2)?;document.samplers.reserve(rows.len());for row in rows{let mut sampler=owned(GltfSampler::default());let value=sampler.as_mut();value.mag_filter=read.optional_word(row,3)?;value.min_filter=read.optional_word(row,5)?;value.wrap_s=read.word(row,7)?;value.wrap_t=read.word(row,9)?;value.name=read.optional_text(row,11)?;value.extensions=read.json(row,12)?;value.extras=read.json(row,13)?;document.samplers.push(sampler.take());}Ok(())
}
