/** 🌳️ Generated by `r12-w2-f1-expression-fixtures.py` from `🔣️.json`: the closed typed expression tree of `semio-framework-expression`. */

export type LengthUnit = "mm" | "cm" | "m" | "km" | "in" | "ft";
export type AngleUnit = "deg" | "rad";
export type AreaUnit = "mm2" | "cm2" | "m2";
export type VolumeUnit = "mm3" | "cm3" | "m3" | "l";
export type UnaryOperator = "negate" | "not";
export type BinaryOperator = "add" | "subtract" | "multiply" | "divide" | "power" | "min" | "max";
export type CompareOperator = "equal" | "not-equal" | "less" | "less-equal" | "greater" | "greater-equal";
export type FunctionName = "sqrt" | "abs" | "round" | "floor" | "ceil" | "sin" | "cos" | "tan" | "atan2";

export type Expr =
  | { op: "number"; value: number }
  | { op: "length"; value: number; unit: LengthUnit }
  | { op: "angle"; value: number; unit: AngleUnit }
  | { op: "area"; value: number; unit: AreaUnit }
  | { op: "volume"; value: number; unit: VolumeUnit }
  | { op: "bool"; value: boolean }
  | { op: "text"; value: string }
  | { op: "param"; name: string }
  | { op: "unary"; operator: UnaryOperator; operand: Expr }
  | { op: "binary"; operator: BinaryOperator; left: Expr; right: Expr }
  | { op: "compare"; operator: CompareOperator; left: Expr; right: Expr }
  | { op: "and"; left: Expr; right: Expr }
  | { op: "or"; left: Expr; right: Expr }
  | { op: "if"; condition: Expr; then: Expr; otherwise: Expr }
  | { op: "call"; function: FunctionName; arguments: Expr[] };
