[package]
name = "semio-s-artifact-shooting-shooting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "shooting shooting artifact"

[package.metadata.semio]
role = "s-module"

[lints]
workspace = true

[lib]
path = "../../🦀️.rs"

[dependencies]
semio-framework-ui-contract.workspace = true
semio-framework-ui-scene = { path = "../../../../../../../🧰️framework/🔨️modules/🖱️ui/🎬️scene/📦️packages/🦀️rust", package = "semio-framework-ui-scene" }
semio-framework-job.workspace = true
semio-s-artifact-stdio-bmp = { workspace = true }
semio-s-artifact-stdio-dwg = { workspace = true }
semio-s-artifact-stdio-gif = { workspace = true }
semio-s-artifact-stdio-jpg = { workspace = true }
semio-s-artifact-stdio-json = { workspace = true }
semio-s-artifact-stdio-pdf = { workspace = true }
semio-s-artifact-stdio-png = { workspace = true }
semio-s-artifact-stdio-semio = { workspace = true, features = ["conversion-drawing"] }
semio-s-artifact-stdio-svg = { workspace = true }
semio-s-artifact-stdio-tiff = { workspace = true }
semio-s-artifact-stdio-txt = { workspace = true }
semio-framework-os = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🖥️host/📦️packages/🦀️rust", package = "semio-framework-os" }
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/📦️packages/🦀️rust", features = ["component-guest"], package = "semio-framework-plugin" }
semio-framework-dispatch-macros = { path = "../../../../../../../🧰️framework/🔨️modules/🔀️dispatch/📦️packages/🦀️rust", package = "semio-framework-dispatch-macros" }
semio-framework = { path = "../../../../../../../🧰️framework/📦️packages/🦀️rust", package = "semio-framework" }
semio-framework-os-kernel = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel" }
semio-framework-schema = { path = "../../../../../../../🧰️framework/🔨️modules/🧬️schema/📦️packages/🦀️rust", package = "semio-framework-schema" }
semio-framework-value-derive = { path = "../../../../../../../🧰️framework/🔨️modules/🌱️value/✨️derive/📦️packages/🦀️rust", package = "semio-framework-value-derive" }

[dev-dependencies]
semio-framework-plugin = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/🔨️modules/🔌️plugin/📦️packages/🦀️rust", features = ["component-guest", "artifact-app-testing"], package = "semio-framework-plugin" }
semio-framework-os-kernel = { path = "../../../../../../../🧰️framework/🛍️products/💻️os/📦️packages/🦀️rust", package = "semio-framework-os-kernel", features = ["protocol-laws"] }
serde.workspace = true
serde_json.workspace = true
semio-framework-async-macros = { path = "../../../../../../../🧰️framework/🔨️modules/⏳️async/✨️macros/📦️packages/🦀️rust" }
