(* ebnf stdio.md snapshot -- honest commonmark subset, mirrors 📖️component.grammar.semio *)
document = { block } ;
block = thematic break | fenced code block | indented code block | block quote
      | atx heading | html block | list | paragraph ;

thematic break = up to 3 spaces , 3 or more of ( "-" | "_" | "*" ) , newline ;
fenced code block = up to 3 spaces , fence , [ info string ] , newline ,
                     { code line , newline } , fence , newline ;
fence = 3 or more "`" | 3 or more "~" ;
indented code block = { "    " , code line , newline } - ;
block quote = { up to 3 spaces , ">" , [ " " ] , line , newline } - ;
atx heading = up to 3 spaces , 1 to 6 "#" , [ " " , inline run ] , newline ;
html block = ( "<" , tag name , ">" | "</" , tag name , ">" | "<!--" ) ,
             { line , newline } ;
list = { list item } - ;
list item = up to 3 spaces , ( bullet | ordinal ) , " " , block , { "  " , block } ;
bullet = "-" | "*" | "+" ;
ordinal = digit , { digit } , ( "." | ")" ) ;
paragraph = { line , newline } - , newline ;

inline run = { inline } ;
inline = image | link | code span | strong | emphasis | html inline
       | hard break | soft break | text ;
image = "!" , "[" , inline run , "]" , "(" , url , [ " " , quoted title ] , ")" ;
link = "[" , inline run , "]" , "(" , url , [ " " , quoted title ] , ")" ;
code span = 1 or more "`" , { character } , 1 or more "`" ;
strong = ( "**" | "__" ) , inline run , ( "**" | "__" ) ;
emphasis = ( "*" | "_" ) , inline run , ( "*" | "_" ) ;
html inline = "<" , [ "/" ] , tag name , { " " , attr } , ">" | "<!--" , { character } , "-->" ;
hard break = "  " , newline | "\" , newline ;
soft break = newline ;
text = character , { character } ;
