
#[test]
fn borrowed_pdf14_original_source_decodes_seven_frames_with_both_caller_controls(){
    use protocol::{OpBinary,ByteSpan,operation_bytes::{OwnedOperationBytes,OperationByteOutput,OperationByteCloseStep}};
    use semio_framework_value::{NativeDecodeControl,NativeEncodeControl,ValueRefusalKind};
    let fixture:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🫳️operation-source/📥️decode.json")).unwrap();
    let original:serde_json::Value=serde_json::from_str(include_str!("../../🧫️fixtures/🫳️operation-source/🔣️.json")).unwrap();
    let octets=|hex:&str|(0..hex.len()).step_by(2).map(|index|u8::from_str_radix(&hex[index..index+2],16).unwrap()).collect::<Vec<_>>();
    let items=fixture["maximumCloseItems"].as_u64().unwrap()as usize;let bytes=fixture["maximumCloseBytes"].as_u64().unwrap()as usize;let allocation=fixture["maximumAllocationBytes"].as_u64().unwrap()as usize;
    let prefix=fixture["originalSourcePrefix"].as_array().unwrap().iter().map(|value|value.as_u64().unwrap()as u8).collect::<Vec<_>>();let suffix=fixture["originalSourceSuffix"].as_array().unwrap().iter().map(|value|value.as_u64().unwrap()as u8).collect::<Vec<_>>();
    let source=|frame:&[u8]|{let mut source=OwnedOperationBytes::try_new(prefix.len()+frame.len()+suffix.len(),allocation).unwrap();let mut accept=|_|true;let mut control=NativeEncodeControl::new(allocation,&mut accept);for field in[prefix.as_slice(),frame,suffix.as_slice()]{source.write_bytes(field,&mut control).unwrap();}source};
    let close=|source:&mut OwnedOperationBytes|{let allocated=source.allocated_bytes();let mut released=0;for _ in 0..source.len()+256{match source.close_one(items,bytes).unwrap(){OperationByteCloseStep::Complete=>break,OperationByteCloseStep::Pending{released_items,released_bytes}=>{assert!(released_items<=items);assert!(released_bytes<=bytes);released+=released_bytes;}}}assert!(source.terminal_is_empty());assert_eq!(source.allocated_bytes(),0);assert_eq!(released,allocated);};
    let refusal=|error:protocol::ProtocolError|match error{protocol::ProtocolError::Pack(protocol::PackError::Refusal(refusal))=>refusal.kind(),other=>panic!("exact original policy refusal required: {other:?}")};
    let mut frames=original["cases"].as_array().unwrap().iter().map(|case|octets(case["frameHex"].as_str().unwrap())).collect::<Vec<_>>();assert_eq!(frames.iter().map(|frame|u64::from(frame[1])).collect::<Vec<_>>(),fixture["originalTags"].as_array().unwrap().iter().map(|value|value.as_u64().unwrap()).collect::<Vec<_>>());
    let text=vec![b'x';fixture["payloadBytes"].as_u64().unwrap()as usize];let mut large=vec![1,4];large.extend_from_slice(&0u64.to_le_bytes());large.extend_from_slice(&(text.len()as u64).to_le_bytes());large.extend_from_slice(&text);frames.push(large);
    for frame in &frames{
        let mut owner=source(frame);let pointer=owner.byte_ref(prefix.len()).unwrap()as*const u8;let allocated=owner.allocated_bytes();let span=ByteSpan::from_source(&owner).slice(prefix.len(),frame.len()).unwrap();assert!(span.contiguous().is_none());
        let mut options=protocol::codec::PackDecodeOptions::default();options.limits.max_file_len=frame.len()as u64;let mut canonical=protocol::codec::PackEncodeOptions::default();canonical.limits.max_file_len=frame.len()as u64;
        let expected_owned=match frame[1]{0=>Some(frame.len()-34),1|2|3=>Some(0),4=>Some(frame.len()-18),5=>{let case=&original["cases"][5];Some(case["identity"].as_str().unwrap().len()+case["pages"].as_array().unwrap().iter().map(|page|std::mem::size_of::<crate::standards::v1_4::subsets::base::schema::snapshot::PageDoc>()+page["text"].as_str().unwrap().len()).sum::<usize>())},6=>None,_=>unreachable!()};
        let mut accept_decode=|_|true;let mut accept_encode=|_|true;let mut decoding=NativeDecodeControl::new(expected_owned.unwrap_or(allocation),&mut accept_decode);let mut encoding=NativeEncodeControl::new(0,&mut accept_encode);let decoded=PdfMutation::decode_op_span(span,&options,&canonical,&mut decoding,&mut encoding).unwrap();assert_eq!(decoded.encode_op().unwrap(),*frame);if let Some(expected)=expected_owned{assert_eq!(decoding.owned_bytes(),expected,"only the original typed fields may be owned; no copied frame");}assert_eq!(encoding.owned_bytes(),0,"same-source canonical comparison owns no second frame");assert_eq!(owner.byte_ref(prefix.len()).unwrap()as*const u8,pointer);assert_eq!(owner.allocated_bytes(),allocated);assert!(owner.iter().eq(prefix.iter().chain(frame).chain(&suffix).copied()));
        options.limits.max_file_len-=1;let mut accept_decode=|_|true;let mut accept_encode=|_|true;let mut decoding=NativeDecodeControl::new(allocation,&mut accept_decode);let mut encoding=NativeEncodeControl::new(allocation,&mut accept_encode);assert_eq!(refusal(PdfMutation::decode_op_span(span,&options,&canonical,&mut decoding,&mut encoding).unwrap_err()),ValueRefusalKind::OwnershipLimit);assert_eq!(decoding.owned_bytes(),0);
        close(&mut owner);
    }
    for (tag,field,expected) in [(4,"segment",ValueRefusalKind::OwnershipLimit),(4,"allocation",ValueRefusalKind::OwnershipLimit),(5,"items",ValueRefusalKind::WorkLimit),(5,"depth",ValueRefusalKind::DepthLimit),(4,"canonical",ValueRefusalKind::OwnershipLimit)]{
        let frame=&frames[tag];let mut owner=source(frame);let span=ByteSpan::from_source(&owner).slice(prefix.len(),frame.len()).unwrap();let mut options=protocol::codec::PackDecodeOptions::default();let mut canonical=protocol::codec::PackEncodeOptions::default();match field{"segment"=>options.limits.max_segment_len=0,"allocation"=>options.limits.max_total_alloc=0,"items"=>options.limits.max_items=0,"depth"=>options.limits.max_depth=0,"canonical"=>canonical.limits.max_file_len=frame.len()as u64-1,_=>unreachable!()};let mut accept_decode=|_|true;let mut accept_encode=|_|true;let mut decoding=NativeDecodeControl::new(allocation,&mut accept_decode);let mut encoding=NativeEncodeControl::new(allocation,&mut accept_encode);assert_eq!(refusal(PdfMutation::decode_op_span(span,&options,&canonical,&mut decoding,&mut encoding).unwrap_err()),expected,"{field}");assert_eq!(decoding.maximum_bytes(),allocation);assert_eq!(encoding.maximum_bytes(),allocation);assert!(span.iter().eq(frame.iter().copied()));close(&mut owner);
    }
    let frame=frames.last().unwrap();let mut owner=source(frame);let span=ByteSpan::from_source(&owner).slice(prefix.len(),frame.len()).unwrap();let mut cancel=|progress:semio_framework_value::native_decoding::NativeDecodeProgress|progress.completed<fixture["cancelAt"].as_u64().unwrap()as usize;let mut accept=|_|true;let mut decoding=NativeDecodeControl::new(allocation,&mut cancel);let mut encoding=NativeEncodeControl::new(allocation,&mut accept);assert_eq!(refusal(PdfMutation::decode_op_span(span,&Default::default(),&Default::default(),&mut decoding,&mut encoding).unwrap_err()),ValueRefusalKind::Canceled);assert!(span.iter().eq(frame.iter().copied()));close(&mut owner);
    let frame=&frames[4];let mut owner=source(frame);let span=ByteSpan::from_source(&owner).slice(prefix.len(),frame.len()).unwrap();let mut accept_decode=|_|true;let mut cancel_encode=|_|false;let mut decoding=NativeDecodeControl::new(allocation,&mut accept_decode);let mut encoding=NativeEncodeControl::new(allocation,&mut cancel_encode);assert_eq!(refusal(PdfMutation::decode_op_span(span,&Default::default(),&Default::default(),&mut decoding,&mut encoding).unwrap_err()),ValueRefusalKind::Canceled);assert!(span.iter().eq(frame.iter().copied()));close(&mut owner);
    for hex in fixture["invalidFrames"].as_array().unwrap(){let frame=octets(hex.as_str().unwrap());let mut owner=source(&frame);let span=ByteSpan::from_source(&owner).slice(prefix.len(),frame.len()).unwrap();let mut accept_decode=|_|true;let mut accept_encode=|_|true;let mut decoding=NativeDecodeControl::new(allocation,&mut accept_decode);let mut encoding=NativeEncodeControl::new(allocation,&mut accept_encode);assert!(PdfMutation::decode_op_span(span,&Default::default(),&Default::default(),&mut decoding,&mut encoding).is_err());assert!(span.iter().eq(frame.iter().copied()));close(&mut owner);}
    eprintln!("[DEBUG] seven exact original PDF14 frames and8194 UTF8 body decode from sliced immutable paged source under both original controls; complete source pages retire only at unchanged1/4096 grants");
}
