input PaintIndexedRegion {
  revision: String!
  x: Int!
  y: Int!
  width: Int!
  height: Int!
  paletteIndex: Int!
}

input PaintDirectRegion {
  revision: String!
  x: Int!
  y: Int!
  width: Int!
  height: Int!
  red: Int!
  green: Int!
  blue: Int!
  alpha: Int!
}

input SetSnapshotMutation { snapshot: BmpSnapshotInput! }
input PatchSnapshotMutation { patch: SnapshotPatchInput! }
input BmpMutation @oneOf { setSnapshot: SetSnapshotMutation patchSnapshot: PatchSnapshotMutation paintIndexedRegion: PaintIndexedRegion paintDirectRegion: PaintDirectRegion }
