syntax = "proto3";
import "../📸️snapshot/🛰️.proto";
package semio.s_stdio_bmp.mutations;

message PaintIndexedRegion {
  string revision = 1;
  uint32 x = 2;
  uint32 y = 3;
  uint32 width = 4;
  uint32 height = 5;
  uint32 palette_index = 6;
}

message PaintDirectRegion {
  string revision = 1;
  uint32 x = 2;
  uint32 y = 3;
  uint32 width = 4;
  uint32 height = 5;
  uint32 red = 6;
  uint32 green = 7;
  uint32 blue = 8;
  uint32 alpha = 9;
}

message BmpMutation { oneof payload { ReplaceImage replace_image = 12; PaintIndexedRegion paint_indexed_region = 3; PaintDirectRegion paint_direct_region = 4; } }

message ReplaceImage { semio.s_stdio_bmp.snapshot.BmpImage image = 1; }
