syntax = "proto3";
import "../📸️snapshot/🛰️.proto";
import "../../../../../../../../📇️registry/🧬️contract/✏️editing/🩹️patch/🛰️.proto";
package semio.s_stdio_bmp.mutations;

message PaintIndexedRegion {
  string revision = 1;
  uint32 x = 2;
  uint32 y = 3;
  uint32 width = 4;
  uint32 height = 5;
  uint32 palette_index = 6;
}

message PaintDirectRegion {
  string revision = 1;
  uint32 x = 2;
  uint32 y = 3;
  uint32 width = 4;
  uint32 height = 5;
  uint32 red = 6;
  uint32 green = 7;
  uint32 blue = 8;
  uint32 alpha = 9;
}

message SetSnapshotMutation { semio.s_stdio_bmp.snapshot.BmpSnapshot snapshot = 1; }
message PatchSnapshotMutation { semio.stdio.editing.SnapshotPatch patch = 1; }
message BmpMutation { oneof payload { SetSnapshotMutation set_snapshot = 1; PatchSnapshotMutation patch_snapshot = 2; PaintIndexedRegion paint_indexed_region = 3; PaintDirectRegion paint_direct_region = 4; } }
