[package]
name = "norm_din_v_18599"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
path = "lib.rs"

[dependencies]
norm_core = { path = "../../../../core/rs" }
norm_din_4108 = { path = "../../../4108/rs" }
norm_din_en_16798 = { path = "../../../en/16798/rs" }
serde = { version = "1.0.219", features = ["derive"] }
vcs = { path = "../../../../../vcs/rs" }
