/** 🕓️ Compares canonical single-predecessor scheduling and actual print geometry with Graphlib and D3. */
export async function compileNativeCriticalPathControls(workDir:string):Promise<void>{
  const neutral=fixture.nativeCriticalPathControls,control=neutral.vectors,validate=new Ajv2020({strict:false}).compile(neutral.schema),{default:dagre}=await import("dagre"),failures:string[]=[],original=JSON.stringify(control),frame=[80,48]as const,padding=3;
  if(!validate(control))throw Error("Critical neutral schema "+JSON.stringify(validate.errors));
  const rowValid=new Ajv2020({strict:false,strictNumbers:true}).compile({type:"object",required:["id","pred","duration"],properties:{id:{type:"string",minLength:1},pred:{type:"string"},duration:{type:"number",minimum:0}}});
  const oracle=(entry:typeof control.cases[number])=>{
    const ids=new Set(entry.rows.map(row=>row.id));if(ids.size!==entry.rows.length||!entry.rows.every(row=>rowValid(row)&&(!row.pred||ids.has(row.pred))))return;
    const graph=new dagre.graphlib.Graph({directed:true});for(const row of entry.rows)graph.setNode(row.id,row);for(const row of entry.rows)if(row.pred)graph.setEdge(row.pred,row.id);if(!dagre.graphlib.alg.isAcyclic(graph))return;
    const times=new Map<string,{start:number;finish:number;depth:number}>();for(const id of dagre.graphlib.alg.topsort(graph)){const row=entry.rows.find(row=>row.id===id)!,parent=row.pred?times.get(row.pred):undefined,start=parent?.finish??0;times.set(id,{start,finish:start+Number(row.duration),depth:(parent?.depth??0)+1});}
    const makespan=Math.max(0,...[...times.values()].map(row=>row.finish));let selected="",best=-1;for(const row of entry.rows)if(times.get(row.id)!.finish>best){selected=row.id;best=times.get(row.id)!.finish;}const critical=new Set<string>();while(selected){critical.add(selected);selected=entry.rows.find(row=>row.id===selected)!.pred;}return{times,makespan,critical};
  };
  for(const entry of control.cases){const expected=oracle(entry);if(Boolean(expected)!==entry.valid)throw Error(entry.id+" Graphlib/AJV critical admission mismatch");if(expected){deepStrictEqual(Object.fromEntries(expected.times),entry.expected);equal([expected.makespan],[entry.makespan!],entry.id+" Graphlib makespan");}}
  const timing="\\cs_new_eq:NN\\semio_viz_test_op_lanes:\\semio_viz_dom_op_lanes:\\cs_set_protected:Npn\\semio_viz_dom_op_lanes:{\\semio_viz_test_op_lanes:\\semio_viz_probe_values:xx{critical/makespan}{\\fp_to_decimal:N\\l_semio_viz_dom_hi_fp}\\seq_map_inline:Nn\\l_semio_viz_dom_keys_seq{\\semio_viz_probe_values:xx{critical/node/##1}{\\prop_item:Nn\\l_semio_viz_dom_sum_prop{##1},\\fp_eval:n{\\prop_item:Nn\\l_semio_viz_dom_sum_prop{##1}+\\prop_item:Nn\\l_semio_viz_dom_bag_prop{##1}},\\prop_item:Nn\\l_semio_viz_dom_dep_prop{##1},\\prop_if_in:NnTF\\l_semio_viz_dom_cur_prop{##1}{1}{0}}}}";
  let matched=0;
  for(const appearance of ["light","dark"]as const){
    const language=appearance==="light"?"en":"de",directory=join(workDir,appearance),cases=control.cases.filter(entry=>entry.valid),body:{raw:string}[]=[],sources=new Map<string,string>();
    for(const entry of cases){const table={name:"critical-"+entry.id,columns:["id","pred","duration","label"],rows:entry.rows},base={chart:{width:frame[0],height:frame[1],language,theme:{appearance},margin:{top:0,right:0,bottom:0,left:0},layers:[],tables:[table],presets:[{kind:control.kind,options:{...control.options,data:"demo-activities",labels:true,width:frame[0],height:frame[1],pad:padding,node:2,arrow:1.4}}]}}as unknown as VizChartSnapshot,before=JSON.stringify(base),outcome=changeVizChartValue(base,{path:["presets","0","options","data"],value:table.name}),replay=applyVizChartDiff(base,outcome.diff),inverse=applyVizChartDiff(replay.snapshot,inverseVizChartDiff(base,outcome.diff));if(outcome.messages.length||outcome.diff.edits.length!==1||replay.messages.length||inverse.messages.length||JSON.stringify(base)!==before)throw Error("Critical canonical mutation/purity");deepStrictEqual(inverse.snapshot,base);const result=await inferVizChart(replay.snapshot);if(!result.tikz||result.diagnostics.some(diagnostic=>diagnostic.code!=="print.chart.scene-unavailable"))throw Error(entry.id+" critical inference "+JSON.stringify(result.diagnostics));sources.set(entry.id,result.tikz);body.push({raw:"\\clearpage\\SemioVizProbeBegin{critical-controls}{"+entry.id+"}"+result.tikz.replace(/(\\begin\{VizFigure\}(?:\[[^\]]*\])?\s*)/,"$1\\draw[line width=.01mm] (0,0) rectangle (80,48);\\special{pdf:literal direct /SemioVizControl"+entry.id+" BMC}\n").replace("\\end{VizFigure}","\\special{pdf:literal direct EMC}\\end{VizFigure}")});}
    const records=await compileVizProbeDocument({case:"critical-controls",scenario:appearance,documentClass:"semio",documentClassOptions:"type=paper,language="+language+",theme="+appearance,packages:["semio-viz"],geometry:true,preamble:["\\title{Critical Path Controls}","\\author{Semio}","\\date{}","\\errorcontextlines=200","\\ExplSyntaxOn"+timing+"\\ExplSyntaxOff"],body},{workDir:directory,scenario:undefined,keepWorkDir:true});
    const pdf=await getDocument({data:new Uint8Array(readFileSync(join(directory,"🧪️probe-out",appearance+".pdf"))),useSystemFonts:true}).promise,paints=new Map<string,ReturnType<typeof nativeControlPdfPaint>>();try{for(let page=1;page<=pdf.numPages;page++){const operators=await(await pdf.getPage(page)).getOperatorList();for(const entry of cases){const marker="SemioVizControl"+entry.id;if(operators.argsArray.some((args,index)=>[OPS.beginMarkedContent,OPS.beginMarkedContentProps].includes(operators.fnArray[index]!)&&String(args?.[0]?.name??args?.[0])===marker))paints.set(entry.id,nativeControlPdfPaint(operators,frame,marker));}}}finally{await pdf.destroy();}
    await Bun.write(join(directory,"actual-critical-paint.json"),JSON.stringify(Object.fromEntries(paints),null,2));
    for(const entry of cases)try{const expected=oracle(entry)!,published=records.filter(record=>record.scenario===entry.id&&record.key.startsWith("critical/node/")),paint=paints.get(entry.id);if(published.length!==entry.rows.length||!paint)throw Error("Critical activity identity/body inventory");equal(records.find(record=>record.scenario===entry.id&&record.key==="critical/makespan")!.values.map(Number),[expected.makespan],entry.id+" makespan");for(const row of entry.rows){const time=expected.times.get(row.id)!,value=published.find(record=>record.key==="critical/node/"+row.id);if(!value)throw Error("Critical stable activity ID missing "+row.id);equal(value.values.map(Number),[time.start,time.finish,time.depth,expected.critical.has(row.id)?1:0],"Graphlib timing/critical chain "+row.id);}
      const nodes=paint.paths.filter(path=>path.closed&&Math.abs(path.fillOpacity-.22)<.001),maxDepth=Math.max(1,...[...expected.times.values()].map(time=>time.depth)),counts=new Map<number,number>();for(const row of entry.rows){const depth=expected.times.get(row.id)!.depth;counts.set(depth,(counts.get(depth)??0)+1);}const maxLane=Math.max(1,...counts.values()),lanes=new Map<number,number>(),pending=[...nodes];if(nodes.length!==entry.rows.length)throw Error("Critical actual node inventory");for(const row of entry.rows){const depth=expected.times.get(row.id)!.depth,lane=(lanes.get(depth)??0)+1;lanes.set(depth,lane);const x=scaleLinear([0,maxDepth],[padding,frame[0]-padding])(depth-.5),y=scaleLinear([0,maxLane],[frame[1]-padding,padding])(lane-.5),bounds=[x-4,y-2,x+4,y+2],at=pending.findIndex(path=>path.bounds.every((value,index)=>Math.abs(value-bounds[index]!)<.04));if(at<0)throw Error("D3 full rounded activity envelope missing "+row.id);pending.splice(at,1);matched++;}const text=paint.glyphs.map(glyph=>glyph.text).join("").replace(/\s/g,"");for(const row of entry.rows)if(!text.includes(row.label.replace(/\s/g,"")))throw Error("Critical caption payload missing "+row.id);
    }catch(error){failures.push(appearance+"/"+entry.id+" "+String(error));}
  }
  if(!failures.length)for(const appearance of ["light","dark"]as const)for(const entry of control.cases.filter(entry=>!entry.valid)){const language=appearance==="light"?"en":"de",directory=join(workDir,"reject",entry.id,appearance),snapshot={chart:{width:80,height:48,language,theme:{appearance},layers:[],tables:[{name:"critical-reject",columns:["id","pred","duration","label"],rows:entry.rows}],presets:[{kind:control.kind,options:{...control.options,data:"critical-reject"}}]}}as unknown as VizChartSnapshot,result=await inferVizChart(snapshot);if(!result.tikz)throw Error("Critical reject missing canonical source");let refused=false;try{await compileVizProbeDocument({case:"critical-controls",scenario:appearance,documentClass:"semio",documentClassOptions:"type=paper,language="+language+",theme="+appearance,packages:["semio-viz"],preamble:["\\title{Critical Rejection}","\\author{Semio}","\\date{}"],body:[{raw:result.tikz}]},{workDir:directory,scenario:undefined,keepWorkDir:true});}catch(error){const log=readFileSync(join(directory,"🧪️probe-out",appearance+".log"),"utf8");if(!String(error).includes("Tectonic compilation failed")||!log.includes("Domain hierarchy"))throw error;refused=true;}if(!refused)throw Error("Critical invalid activity accepted "+entry.id);}
  if(JSON.stringify(control)!==original)throw Error("Critical neutral mutated");if(failures.length)throw Error("Critical controls:\n"+failures.join("\n"));console.log("[DEBUG] Critical "+"Graphlib scheduling and D3 rounded node envelopes"+" checked "+matched+" actual nodes and "+(control.cases.filter(entry=>!entry.valid).length*2)+" expected hard rejections");
}

