import {readJsonFileV1,writeJsonFileV1,hashFileV1} from "../native-json-inputs/📜️script.ts";
import {readFileSync,existsSync} from "node:fs";
import {resolve,dirname} from "node:path";
import {createHash} from "node:crypto";
const ticket=resolve(import.meta.dir,"..");let root=ticket;while(!existsSync(resolve(root,"nx.json")))root=dirname(root);
const [command,epoch,proofArg]=process.argv.slice(2);if(command!=="run"||epoch!=="4"||!proofArg)throw Error("Exact owning Product dispatch epoch4 admission required");
const signal=new AbortController();process.once("SIGINT",()=>signal.abort());process.once("SIGTERM",()=>signal.abort());const io={signal:signal.signal},out=resolve(ticket,"🗑️generated/product-wgpu-native-whole/epoch-"+epoch),sourcePath=resolve(out,"source-1.json"),metadataPath=resolve(out,"metadata-1.json"),admissionPath=resolve(out,"independent-plan-provider-admission-1.json"),proofPath=resolve(proofArg),codecPath=resolve(ticket,"native-json-inputs/📜️script.ts"),originalHelperPath=resolve(ticket,"product-wgpu-native-descriptor-inputs/📜️script.ts"),prePath=resolve(out,"immediate-pre-1.json"),terminalPath=resolve(out,"terminal-1.json"),sha=(bytes:string|Buffer)=>createHash("sha256").update(bytes).digest("hex"),executionPath="🧰️framework/🔨️modules/🏃️process/🧪️testing/🎛️execution/🟦️.ts";
if(existsSync(prePath)||existsSync(terminalPath))throw Error("Immutable original owning dispatch exists");const loadedRawBindings:any[]=[];for(const path of[sourcePath,metadataPath,admissionPath,proofPath,originalHelperPath,import.meta.path,codecPath])loadedRawBindings.push({path,sha256:await hashFileV1(path,io)});const source=await readJsonFileV1(sourcePath,io),metadata=await readJsonFileV1(metadataPath,io),admission=await readJsonFileV1(admissionPath,io),proof=await readJsonFileV1(proofPath,io),bindings=[{path:sourcePath,sha256:admission.sourceHash},{path:metadataPath,sha256:admission.metadataHash},{path:admissionPath,sha256:proof.originalAdmissionHash},{path:originalHelperPath,sha256:admission.helperHash},{path:import.meta.path,sha256:proof.helperHash},{path:codecPath,sha256:admission.codecHash}];
if(admission.ready!==true||proof.ready!==true||metadata.exitCode!==0||proof.sourceHash!==admission.sourceHash||proof.metadataHash!==admission.metadataHash||proof.codecHash!==admission.codecHash||admission.helperHash!==source.executor.helper.sha256||admission.codecHash!==source.executor.codec.sha256||source.original.rest.length||source.original.request.extraArgs.length||source.original.request.packages.length!==1||source.original.request.packages[0]!=="semio-framework-os-renderer-wgpu"||JSON.stringify(source.registeredArgv)!==JSON.stringify(["nx","run","@semio-tech/framework-renderer-wgpu:test-native","--skip-nx-cache","--excludeTaskDependencies"]))throw Error("Exact original all-target/default/empty-rest request differs");
async function guard(){signal.signal.throwIfAborted();for(const row of loadedRawBindings)if(await hashFileV1(row.path,io)!==row.sha256)throw Error("Exact initially loaded original/current dispatch authority advanced "+row.path);for(const row of[...bindings,...source.initialBindings])if(typeof row.sha256!=="string"||await hashFileV1(row.path,io)!==row.sha256)throw Error("Owning dispatch authority advanced "+row.path);}
function liveExecutor(){const row=source.sources.find((row:any)=>row.path===executionPath),bytes=readFileSync(resolve(root,executionPath));if(!row||sha(bytes)!==row.sha256)throw Error("Captured owning execution dependency advanced");return {path:executionPath,source:bytes.toString("base64"),encoding:"base64",sha256:row.sha256};}
await guard();const expected=[...source.providers.map((row:any)=>({path:row.path,expected:row.sha256})),{path:source.original.scriptPath,expected:source.original.scriptHash},{path:source.original.projectPath,expected:source.original.projectHash},{path:"Cargo.lock",expected:metadata.lock.afterHash}],guards:any[]=[];for(const row of expected){signal.signal.throwIfAborted();guards.push({...row,current:sha(readFileSync(resolve(root,row.path)))});if(guards.length%16===0){await new Promise<void>(done=>setImmediate(done));console.log("[DEBUG] "+JSON.stringify({phase:"owning-product-provider-check",completed:guards.length,total:expected.length}));}}if(guards.some(row=>row.current!==row.expected))throw Error("Original owning provider/script dispatch advanced");function descriptorGuard(){const row=source.descriptor.row;if(sha(readFileSync(resolve(root,row.path)))!==row.afterHash)throw Error("Actual owning descriptor advanced");}descriptorGuard();const executor=liveExecutor(),execution=await import(resolve(root,executionPath));await guard();liveExecutor();descriptorGuard();
const environment={SEMIO_TEST_LEVEL:"long",CARGO_TARGET_DIR:resolve(out,"target"),CARGO_BUILD_BUILD_DIR:resolve(out,"target"),SEMIO_TEST_ARTIFACT_DIR:resolve(out,"artifacts"),NEXTEST_SUCCESS_OUTPUT:"final",NX_WORKSPACE_ROOT_PATH:root,NX_DAEMON:"false",NX_ISOLATE_PLUGINS:"false",NX_CACHE_PROJECT_GRAPH:"false"};
await writeJsonFileV1(prePath,{at:new Date().toISOString(),source:{path:sourcePath,sha256:admission.sourceHash},metadata:{path:metadataPath,sha256:admission.metadataHash},proof:{path:proofPath,sha256:await hashFileV1(proofPath,io)},bindings,guards,liveExecutor:executor,argv:source.registeredArgv,environment,assertionsExecuted:false,scope:"Original complete registered Product WGPU owning target; current source capture retained; cancellable dispatch successor only"},io);
let exitCode=0;try{await guard();liveExecutor();await execution.runBudgetedTestCommand(process.execPath,source.registeredArgv,{cwd:root,env:{...process.env,...environment},budgetMs:0,signal:signal.signal,throwOnFailure:true});}catch(error){exitCode=1;console.error(error);}
let sourcePostUnavailable=signal.signal.aborted,postRefusal:string|null=null;if(!sourcePostUnavailable){try{await guard();liveExecutor();}catch(error){sourcePostUnavailable=true;postRefusal=String(error);}}await writeJsonFileV1(terminalPath,{owningExitCode:exitCode,sourcePostUnavailable,postRefusal,at:new Date().toISOString(),exitCode,argv:source.registeredArgv,originalCargoArgs:[],rest:[],cancelled:signal.signal.aborted,dispatchHelper:{path:import.meta.path,sha256:proof.helperHash},scope:"Actual unchanged Product WGPU test-native all-target/default long route with empty rest with original whole assertions and exact independently admitted one-field physical descriptor correction",sourceWritesOutsideTicket:false},{...io,signal:undefined});process.exit(exitCode||sourcePostUnavailable?1:0);
