syntax = "proto3";
package semio.s.norm.vdi3805.diff;

message Vdi3805ManufacturerFilePatch {
  optional string header_version = 1;
  optional string manufacturer = 2;
  optional string created = 3;
  optional string charset = 4;
  optional uint32 record_count = 5;
}

message Vdi3805ProductsPatch {
  string id = 1;
}

message Vdi3805ProductsRows {
  repeated string removed = 1;
  repeated Vdi3805ProductsPatch modified = 2;
  repeated string order = 3;
}

message Vdi3805EditionProfileEntry {
  string key = 1;
}

message Vdi3805EditionProfileRows {
  repeated Vdi3805EditionProfileEntry added = 1;
  repeated string removed = 2;
  repeated Vdi3805EditionProfileEntry modified = 3;
}

message Vdi3805IndexEntriesPatchDnValue {
  optional uint32 value = 1;
}

message Vdi3805IndexEntriesPatch {
  string id = 1;
  optional Vdi3805IndexEntriesPatchDnValue dn = 2;
  repeated string tags = 3;
}

message Vdi3805IndexEntriesRows {
  repeated string removed = 1;
  repeated Vdi3805IndexEntriesPatch modified = 2;
  repeated string order = 3;
}

message Vdi3805GeometryConnectionsRows {
  repeated string removed = 1;
  repeated string order = 2;
}

message Vdi3805GeometryEntry {
  string key = 1;
}

message Vdi3805GeometryPatch {
  string key = 1;
  optional Vdi3805GeometryConnectionsRows connections = 2;
}

message Vdi3805GeometryRows {
  repeated Vdi3805GeometryEntry added = 1;
  repeated string removed = 2;
  repeated Vdi3805GeometryPatch modified = 3;
}

message Vdi3805CurvesEntry {
  string key = 1;
}

message Vdi3805CurvesPatch {
  string key = 1;
}

message Vdi3805CurvesRows {
  repeated Vdi3805CurvesEntry added = 1;
  repeated string removed = 2;
  repeated Vdi3805CurvesPatch modified = 3;
}

message Vdi3805LimitsPatch {
  optional uint64 max_file_bytes = 1;
  optional uint64 max_records = 2;
  optional uint64 max_field_length = 3;
  optional uint64 max_nesting_depth = 4;
}

message Vdi3805Diff {
  optional Vdi3805ManufacturerFilePatch manufacturer_file = 1;
  optional Vdi3805ProductsRows products = 2;
  optional Vdi3805EditionProfileRows edition_profile = 3;
  optional bool strict_mode = 4;
  optional Vdi3805IndexEntriesRows index_entries = 5;
  optional Vdi3805GeometryRows geometry = 6;
  optional Vdi3805CurvesRows curves = 7;
  optional Vdi3805LimitsPatch limits = 8;
}
