use super::*;
use crate::value::observe_retirement_allocations;
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all="camelCase")]
struct Fixture { page_capacity:usize,cases:Vec<Case>,interruption_turns:Vec<usize> }
#[derive(Deserialize)]
#[serde(rename_all="camelCase")]
struct Case { name:String,count:usize,key:u64,expected_removed:bool }
fn grant()->RetainedOrderedMapRemoveGrant { RetainedOrderedMapRemoveGrant { retirement:RetainedCloneGrant {maximum_items:1,maximum_copy_bytes:65536,maximum_capacity_bytes:65536,maximum_release_bytes:65536,maximum_depth:64},comparison:BoundedOrdGrant{maximum_items:1,maximum_bytes:8},maximum_moved_items:32,maximum_moved_bytes:4096} }
fn close<K:BoundedOrd+RetireOwned,V:RetireOwned+Sync>(cursor:&mut RetainedOrderedMapRemoveCursor<K,V>,born:&mut usize,freed:&mut usize){
 cursor.begin_close();for _ in 0..100000 {if cursor.terminal_is_empty(){return}let copy=cursor.next_close_copy_byte_demand().unwrap();let release=cursor.next_close_release_byte_demand().unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:cursor.next_close_capacity_byte_demand(if copy>0{copy}else{release}).unwrap(),maximum_release_bytes:release,maximum_depth:cursor.next_close_depth_demand().unwrap()};let denied=[Some(RetainedCloneGrant{maximum_items:0,..grant}),copy.checked_sub(1).map(|maximum_copy_bytes|RetainedCloneGrant{maximum_copy_bytes,..grant}),grant.maximum_capacity_bytes.checked_sub(1).map(|maximum_capacity_bytes|RetainedCloneGrant{maximum_capacity_bytes,..grant}),release.checked_sub(1).map(|maximum_release_bytes|RetainedCloneGrant{maximum_release_bytes,..grant}),grant.maximum_depth.checked_sub(1).map(|maximum_depth|RetainedCloneGrant{maximum_depth,..grant})];for refused in denied.into_iter().flatten(){let(result,heap)=observe_retirement_allocations(||cursor.close_step(refused));assert_eq!(heap,(0,0));if let Ok(step)=result{assert_eq!(step.progress(),Default::default())}assert!(!cursor.terminal_is_empty())}let(step,heap)=observe_retirement_allocations(||cursor.close_step(grant).unwrap());let p=step.progress();assert!(p.fits(grant));assert_eq!(heap,(p.retained_capacity_bytes,p.released_bytes));*born+=heap.0;*freed+=heap.1}panic!("removal physical close exceeded fixture turns")
}
#[test]
fn owned_removal_matches_std_map_and_retires_original_pages_on_completion_and_cancellation(){
 let fixture:Fixture=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();assert_eq!(fixture.page_capacity,RETAINED_ORDERED_MAP_PAGE_CAPACITY);
 for case in fixture.cases {for interrupted in fixture.interruption_turns.iter().copied().map(Some).chain([None]) {
  let(map,heap)=observe_retirement_allocations(||(0..case.count as u64).map(|key|(key,())).collect::<RetainedOrderedMap<_,_>>());let original=heap.0;assert_eq!(heap.1,0);let pointer=map.pages.as_ptr();
  let (refused,heap)=observe_retirement_allocations(||RetainedOrderedMapRemoveCursor::admit(map,case.key,Default::default()));assert_eq!(heap,(0,0));let(error,map,key)=refused.err().unwrap();assert_eq!(error.kind,crate::ValueRefusalKind::WorkLimit);assert_eq!(map.pages.as_ptr(),pointer);
  let bytes=RetainedOrderedMapRemoveCursor::<u64,()>::constructor_capacity_bytes();let copy=RetainedOrderedMapRemoveCursor::<u64,()>::constructor_copy_bytes();let(admitted,heap)=observe_retirement_allocations(||RetainedOrderedMapRemoveCursor::admit(map,key,RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:bytes,maximum_depth:1,..Default::default()}));let(mut cursor,receipt)=admitted.unwrap_or_else(|_|panic!("removal admission"));assert_eq!(heap,(receipt.retained_capacity_bytes,0));let mut born=heap.0;let mut freed=0;let mut output=None;
  for turn in 0..100000 {if interrupted==Some(turn){break}let g=grant();let demand=cursor.advance_retirement_demands(g.retirement.maximum_copy_bytes).unwrap();if demand.copy_bytes>0{let denied=RetainedOrderedMapRemoveGrant{retirement:RetainedCloneGrant{maximum_copy_bytes:demand.copy_bytes-1,..g.retirement},..g};let(step,heap)=observe_retirement_allocations(||cursor.advance(denied).unwrap());assert_eq!(step.progress(),Default::default());assert_eq!(heap,(0,0));}let(step,heap)=observe_retirement_allocations(||cursor.advance(g).unwrap());let p=step.progress();assert!(p.fits(g));assert_eq!(heap,(p.retirement.retained_capacity_bytes,p.retirement.released_bytes));born+=heap.0;freed+=heap.1;if let RetainedOrderedMapRemoveStep::Complete{removed,..}=step{assert_eq!(removed,case.expected_removed);assert!(cursor.output_ready());output=cursor.take();assert!(!cursor.output_ready());break}}
  if interrupted.is_none(){let map=output.as_ref().expect("completed original map");let mut oracle=(0..case.count as u64).map(|key|(key,())).collect::<std::collections::BTreeMap<_,_>>();oracle.remove(&case.key);assert_eq!(map.iter().map(|(key,_)|*key).collect::<Vec<_>>(),oracle.keys().copied().collect::<Vec<_>>());assert_eq!(map.pages.as_ptr(),pointer);assert_eq!(map.page_count(),map.len().div_ceil(RETAINED_ORDERED_MAP_PAGE_CAPACITY));}
  close(&mut cursor,&mut born,&mut freed);if let Some(map)=output {let(mut retired,heap)=observe_retirement_allocations(||crate::retirement::controlled::ControlledRetirement::new(map).unwrap());assert_eq!(heap,(0,0));while !retired.terminal_is_empty(){let copy=retired.next_copy_byte_demand().unwrap();let release=retired.next_release_byte_demand().unwrap();let g=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:retired.next_capacity_byte_demand(if copy>0{copy}else{release}).unwrap(),maximum_release_bytes:release,maximum_depth:retired.next_depth_demand().unwrap()};let(step,heap)=observe_retirement_allocations(||retired.step(g).unwrap());let p=step.progress();assert_eq!(heap,(p.retained_capacity_bytes,p.released_bytes));born+=heap.0;freed+=heap.1}}
  assert_eq!(original+born,freed,"{} interrupted {interrupted:?}",case.name);let(_,heap)=observe_retirement_allocations(||drop(cursor));assert_eq!(heap,(0,0));
 }}
}
#[test]
fn owned_removal_string_keys_and_values_keep_exact_heap_custody(){
 let fixture:serde_json::Value=serde_json::from_str(include_str!("../🧫️fixtures/🔣️.json")).unwrap();let keys=fixture["stringKeys"].as_array().unwrap();
 for target in fixture["stringTargets"].as_array().unwrap(){
  let target=target.as_str().unwrap();let(map,heap)=observe_retirement_allocations(||keys.iter().map(|key|{let key=key.as_str().unwrap();(key.to_owned(),key.repeat(3))}).collect::<RetainedOrderedMap<_,_>>());let mut original=heap.0-heap.1;
  let(key,heap)=observe_retirement_allocations(||target.to_owned());original+=heap.0;assert_eq!(heap.1,0);let bytes=RetainedOrderedMapRemoveCursor::<String,String>::constructor_capacity_bytes();let copy=RetainedOrderedMapRemoveCursor::<String,String>::constructor_copy_bytes();let(admitted,heap)=observe_retirement_allocations(||RetainedOrderedMapRemoveCursor::admit(map,key,RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:bytes,maximum_depth:1,..Default::default()}));let(mut cursor,receipt)=admitted.unwrap_or_else(|_|panic!("string removal admission"));assert_eq!(heap,(receipt.retained_capacity_bytes,0));let mut born=heap.0;let mut freed=0;let mut output=None;
  for _ in 0..100000 {let g=RetainedOrderedMapRemoveGrant{comparison:BoundedOrdGrant{maximum_items:1,maximum_bytes:1},..grant()};let(step,heap)=observe_retirement_allocations(||cursor.advance(g).unwrap());let p=step.progress();assert!(p.fits(g));assert_eq!(heap,(p.retirement.retained_capacity_bytes,p.retirement.released_bytes));born+=heap.0;freed+=heap.1;if let RetainedOrderedMapRemoveStep::Complete{..}=step {assert!(cursor.output_ready());output=cursor.take();assert!(!cursor.output_ready());break}}
  let map=output.unwrap();let mut oracle=keys.iter().map(|key|{let key=key.as_str().unwrap();(key.to_owned(),key.repeat(3))}).collect::<std::collections::BTreeMap<_,_>>();oracle.remove(target);assert_eq!(serde_json::to_value(&map).unwrap(),serde_json::to_value(oracle).unwrap());close(&mut cursor,&mut born,&mut freed);
  let(mut retired,heap)=observe_retirement_allocations(||crate::retirement::controlled::ControlledRetirement::new(map).unwrap());assert_eq!(heap,(0,0));for _ in 0..100000{if retired.terminal_is_empty(){break}let copy=retired.next_copy_byte_demand().unwrap();let release=retired.next_release_byte_demand().unwrap();let g=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:retired.next_capacity_byte_demand(if copy>0{copy}else{release}).unwrap(),maximum_release_bytes:release,maximum_depth:retired.next_depth_demand().unwrap()};let(step,heap)=observe_retirement_allocations(||retired.step(g).unwrap());let p=step.progress();assert!(p.fits(g));assert_eq!(heap,(p.retained_capacity_bytes,p.released_bytes));born+=heap.0;freed+=heap.1}assert!(retired.terminal_is_empty());assert_eq!(original+born,freed);let(_,heap)=observe_retirement_allocations(||drop(cursor));assert_eq!(heap,(0,0));println!("[DEBUG] Owned ordered removal key={target} original={original} allocated={born} released={freed}");
 }
}
fn controlled_edit<C:RetireOwned>(cursor:C,original:usize,mut born:usize,mut freed:usize){
 let(admitted,heap)=observe_retirement_allocations(||crate::retirement::controlled::ControlledRetirement::new(cursor));let mut retired=admitted.unwrap_or_else(|_|panic!("edit cursor must have genuine controlled owner"));assert_eq!(heap,(0,0));let(result,heap)=observe_retirement_allocations(||retired.step(Default::default()).unwrap());assert_eq!(result.progress(),Default::default());assert_eq!(heap,(0,0));assert!(retired.original().is_some());
 for _ in 0..100000{if retired.terminal_is_empty(){break}let copy=retired.next_copy_byte_demand().unwrap();let release=retired.next_release_byte_demand().unwrap();let grant=RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:retired.next_capacity_byte_demand(if copy>0{copy}else{release}).unwrap(),maximum_release_bytes:release,maximum_depth:retired.next_depth_demand().unwrap()};let(step,heap)=observe_retirement_allocations(||retired.step(grant).unwrap());let p=step.progress();assert!(p.fits(grant));assert_eq!(heap,(p.retained_capacity_bytes,p.released_bytes));born+=heap.0;freed+=heap.1}assert!(retired.terminal_is_empty());assert_eq!(original+born,freed);let(_,heap)=observe_retirement_allocations(||drop(retired));assert_eq!(heap,(0,0));
}
#[test]
fn owned_removal_and_insertion_frames_close_original_edit_owners_under_controlled_retirement(){
 for turns in [0,1,17,1000]{for key in [16,40]{
  let(map,heap)=observe_retirement_allocations(||(0u64..33).map(|key|(key,())).collect::<RetainedOrderedMap<_,_>>());let original=heap.0-heap.1;let bytes=RetainedOrderedMapInsertCursor::<u64,()>::constructor_capacity_bytes();let copy=RetainedOrderedMapInsertCursor::<u64,()>::constructor_copy_bytes();let(admitted,heap)=observe_retirement_allocations(||RetainedOrderedMapInsertCursor::admit(map,key,(),RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:bytes,maximum_depth:1,..Default::default()}));let(mut cursor,receipt)=admitted.unwrap_or_else(|_|panic!("edit insert admission"));assert_eq!(heap,(receipt.retained_capacity_bytes,0));let mut born=heap.0;let mut freed=0;
  for _ in 0..turns{let g=RetainedOrderedMapInsertGrant{retirement:grant().retirement,comparison:grant().comparison,maximum_moved_items:32,maximum_moved_bytes:4096,maximum_capacity_bytes:4096};let(step,heap)=observe_retirement_allocations(||cursor.advance(g));born+=heap.0;freed+=heap.1;match step{Ok(RetainedOrderedMapInsertStep::Complete{..})|Err(_)=>break,_=>{}}}controlled_edit(cursor,original,born,freed);
  let(map,heap)=observe_retirement_allocations(||(0u64..33).map(|key|(key,())).collect::<RetainedOrderedMap<_,_>>());let original=heap.0-heap.1;let bytes=RetainedOrderedMapRemoveCursor::<u64,()>::constructor_capacity_bytes();let copy=RetainedOrderedMapRemoveCursor::<u64,()>::constructor_copy_bytes();let(admitted,heap)=observe_retirement_allocations(||RetainedOrderedMapRemoveCursor::admit(map,key,RetainedCloneGrant{maximum_items:1,maximum_copy_bytes:copy,maximum_capacity_bytes:bytes,maximum_depth:1,..Default::default()}));let(mut cursor,receipt)=admitted.unwrap_or_else(|_|panic!("edit remove admission"));assert_eq!(heap,(receipt.retained_capacity_bytes,0));let mut born=heap.0;let mut freed=0;
  for _ in 0..turns{let(step,heap)=observe_retirement_allocations(||cursor.advance(grant()).unwrap());born+=heap.0;freed+=heap.1;if matches!(step,RetainedOrderedMapRemoveStep::Complete{..}){break}}controlled_edit(cursor,original,born,freed);
 }}
}
