[package]
name = "remodel_geo"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
remodel_sfm = { path = "../../sfm/rs", package = "remodel_sfm" }
remodel_dense = { path = "../../dense/rs", package = "remodel_dense" }
remodel_mesh = { path = "../../mesh/rs", package = "remodel_mesh" }
remodel_image = { path = "../../image/rs", package = "remodel_image" }
remodel_camera = { path = "../../camera/rs", package = "remodel_camera" }
mathematical_algebra = { path = "../../../../../../framework/module/math/algebra/rs", package = "semio-framework-os-kernel-math-algebra" }
mathematical_lie = { path = "../../../../../../framework/module/math/lie/rs", package = "semio-framework-os-kernel-math-lie" }
mathematical_spatial = { path = "../../../../../../framework/module/math/spatial/rs", package = "semio-framework-os-kernel-math-spatial" }
mathematical_optimize = { path = "../../../../../../framework/module/math/optimize/rs", package = "semio-framework-os-kernel-math-optimize" }
mathematical_random = { path = "../../../../../../framework/module/math/random/rs", package = "semio-framework-os-kernel-math-random" }
