name: Generate gRPC code

on:
  push:
    paths: [src/schema/**]

jobs:
  generate-grpc-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bufbuild/buf-setup-action
      with:
        version: "1.11.0"
        github_token: ${{ github.token }}
    - uses: arduino/setup-protoc@v1
    - name: Generate code
      run: |
        cd ./src/schema/semio
        buf generate --include-imports --include-wkt
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Generated gRPC code