name: Regenerate gRPC code

on:
  push:
    branches: [main]
    paths: [src/schema/**]

jobs:
  regenerate-grpc-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gRPC python source code generator
      run: python -m pip install grpcio-tools
    - name: Regenerate gRPC server source code
      run: |
        out="src/server/gen"
        rm -r -f $out
        mkdir -p $out
        python -m grpc_tools.protoc -I src/schema/server/v1 -I src/schema/model/v1 --python_out=$out --pyi_out=$out --grpc_python_out=$out server.proto model.proto
    - name: Regenerate gRPC python extension services source code
      run: |
        out="src/extensions/extensionservices/python/adapter/gen"
        rm -r -f $out
        mkdir -p $out
        python -m grpc_tools.protoc -I src/schema/extensionservices/adapter/v1 -I src/schema/model/v1 --python_out=$out --pyi_out=$out --grpc_python_out=$out adapter.proto model.proto
        out="src/extensions/extensionservices/python/converter/gen"
        rm -r -f $out
        mkdir -p $out
        python -m grpc_tools.protoc -I src/schema/extensionservices/converter/v1 -I src/schema/model/v1 --python_out=$out --pyi_out=$out --grpc_python_out=$out converter.proto model.proto
        out="src/extensions/extensionservices/python/transformer/gen"
        rm -r -f $out
        mkdir -p $out
        python -m grpc_tools.protoc -I src/schema/extensionservices/transformer/v1 -I src/schema/model/v1 --python_out=$out --pyi_out=$out --grpc_python_out=$out transformer.proto model.proto
    - name: Install gRPC node source code generator
      run: |
        npm install -g grpc-tools
        npm install grpc_tools_node_protoc_ts --save-dev
    - name: Regenerate gRPC node extension services source code
      run: |
        out="src/extensions/extensionservices/node/adapter/gen"
        rm -r -f $out
        mkdir -p $out
        grpc_tools_node_protoc --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --ts_out=grpc_js:$out --js_out=import_style=commonjs:$out --grpc_out=grpc_js:$out -I src/schema/extensionservices/adapter/v1 -I src/schema/model/v1 adapter.proto model.proto
        out="src/extensions/extensionservices/node/converter/gen"
        rm -r -f $out
        mkdir -p $out
        grpc_tools_node_protoc --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --ts_out=grpc_js:$out --js_out=import_style=commonjs:$out --grpc_out=grpc_js:$out -I src/schema/extensionservices/converter/v1 -I src/schema/model/v1 converter.proto model.proto
        out="src/extensions/extensionservices/node/transformer/gen"
        rm -r -f $out
        mkdir -p $out
        grpc_tools_node_protoc --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --ts_out=grpc_js:$out --js_out=import_style=commonjs:$out --grpc_out=grpc_js:$out -I src/schema/extensionservices/transformer/v1 -I src/schema/model/v1 transformer.proto model.proto
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Regenerated gRPC code