/** 📏️ Neutral owned fields independently interpreted by SQLite before provider construction. */
import {expect,test} from "bun:test";
import {Database} from "bun:sqlite";
import Ajv from "ajv/dist/2020.js";
import fixture from "../🧫️fixtures/🔣️.json";

import {parseGridSettings,parseCharacterStyle,parseTextStyleRun,parseImageLink,parseLayoutDrawingChild} from "../../../../🧬️schema/🟦️.ts";
const f64=(text:string)=>({bits:BigInt("0x"+text)}),f32=(text:string)=>({bits:parseInt(text,16)});
test("Layout neutral schema and all explicit relational fields independently exist",async()=>{expect(fixture["schema"]).toEqual("layout.snapshot.sqlite/v1");expect(fixture["maximumU64"]).toEqual("18446744073709551615");expect(fixture["maximumU32"]).toEqual(4294967295);expect(fixture["columns"]).toEqual(["artifact_kind","artifact_ref"]);expect(fixture["componentNodes"]).toEqual(1024);expect(fixture["componentDepth"]).toEqual(256);expect(fixture["intrinsicBytes"]).toEqual(100000);expect(fixture["cancelAfter"]).toEqual(256);const sql=await Bun.file(new URL("../🗄️.sql",import.meta.url)).text(),db=new Database(":memory:");try{db.exec(sql);expect(db.query("SELECT count(*) AS n FROM sqlite_schema WHERE type='table'").get()).toEqual({n:43});const columns=(db.query("PRAGMA table_info(layout_image_link)").all() as {name:string}[]).map(r=>r.name);for(const column of fixture.columns)expect(columns).toContain(column);db.query("INSERT INTO layout_document(id,schema,name) VALUES(1,?,?)").run(fixture.schema,"");db.query("INSERT INTO layout_image_link(id,document_id,ordinal,native_id,path,hash,width,height,dpi,artifact_kind,artifact_ref) VALUES(1,1,0,'','','',0,0,0,?,?)").run(fixture.imageArtifactKind,fixture.imageArtifactRef);expect(db.query(fixture.query).get()).toEqual({artifact_kind:fixture.imageArtifactKind,artifact_ref:fixture.imageArtifactRef});const wide=BigInt(fixture.maximumU64);db.exec("CREATE TABLE oracle_unsigned(hi INTEGER,lo INTEGER)");db.query("INSERT INTO oracle_unsigned VALUES(?,?)").run(wide>>32n,wide&0xffffffffn);const row=db.query("SELECT hi,lo FROM oracle_unsigned").get() as {hi:number;lo:number};expect((BigInt(row.hi)<<32n)|BigInt(row.lo)).toBe(wide);}finally{db.close();}});
test("Layout canonical owned number words and unsigned intervals retain their full domains",()=>{for(let i=0;i<fixture.float64Bits.length;i++){const word=f64(fixture.float64Bits[i]!),word32=f32(fixture.float32Bits[i]!);expect(parseGridSettings({baselineGrid:word,baselineOffset:word,snapToBaseline:false})).toEqual({baselineGrid:word,baselineOffset:word,snapToBaseline:false});expect(parseCharacterStyle({id:"",name:null,fontFamily:null,fontSize:word,fontWeight:fixture.maximumU32,italic:false,color:[word32,word32,word32,word32],tracking:word})).toEqual({id:"",name:null,fontFamily:null,fontSize:word,fontWeight:fixture.maximumU32,italic:false,color:[word32,word32,word32,word32],tracking:word});}const maximum=BigInt(fixture.maximumU64);expect(parseTextStyleRun({start:maximum,end:maximum,paragraphStyleId:"",characterStyleId:null})).toEqual({start:maximum,end:maximum,paragraphStyleId:"",characterStyleId:null});});
test("Layout ImageLink and inline Drawing use their actual complete first-party owner fields",()=>{const image={id:"",path:"",hash:"",width:fixture.maximumU32,height:0,dpi:0,colorProfile:null,state:null,proxyDataUrl:null,artifactKind:fixture.imageArtifactKind,artifactRef:fixture.imageArtifactRef};expect(parseImageLink(image)).toEqual(image);const content={schema:fixture.drawingSchema,canvas:{width:f64(fixture.float64Bits[7]!),height:f64(fixture.float64Bits[1]!),background:undefined},styles:[],layers:[]},id=fixture.childIdentity;const child={handle:{childId:id[0]!,target:{artifactId:id[4]!,dialect:{artifactKind:id[1]!,standard:id[2]!,subset:id[3]!}}},content};expect(parseLayoutDrawingChild(child)).toEqual(child);});

import {layoutSnapshotToSqliteDatabase,layoutSnapshotFromSqliteDatabase} from "../🟦️.ts";
import {exportSqliteDatabase,importSqliteDatabase} from "@semio-tech/framework";
import type {LayoutArtifact} from "../../../../🧬️schema/🟦️.ts";
const owned=():LayoutArtifact=>{const word=f64(fixture.float64Bits[7]!),color=f32(fixture.float32Bits[7]!),bounds={x:word,y:word,w:word,h:word,rotation:word},rect={x:word,y:word,w:word,h:word},layers=[{id:"",name:"",visible:false,locked:true,objectIds:["","!"]}],frames=[{kind:"rect" as const,id:"",layerId:"",bounds,locked:null,visible:false,fill:[color,color,color,color] as [typeof color,typeof color,typeof color,typeof color],stroke:null},{kind:"text" as const,id:"",layerId:"",bounds,locked:true,visible:null,storyId:"",threadNext:"",columns:4294967295,inset:rect,wrapMode:""},{kind:"image" as const,id:"",layerId:"",bounds,locked:false,visible:true,linkId:""}],id=fixture.childIdentity;return{schema:fixture.schema,name:"",grid:{baselineGrid:word,baselineOffset:word,snapToBaseline:false},paragraphStyles:[{id:"",name:"",fontFamily:"",fontSize:word,fontWeight:4294967295,leading:word,tracking:word,alignment:""}],characterStyles:[{id:"",name:null,fontFamily:"",fontSize:word,fontWeight:null,italic:false,color:[color,color,color,color],tracking:null}],stories:[{id:"",content:"語\0",styleRuns:[{start:BigInt(fixture.maximumU64),end:0n,paragraphStyleId:"",characterStyleId:null}]}],links:[{id:"",path:"",hash:"",width:4294967295,height:0,dpi:1,colorProfile:null,state:"",proxyDataUrl:"",artifactKind:fixture.imageArtifactKind,artifactRef:""}],parentPages:[{id:"",name:"",width:word,height:word,layerIds:["",""],layers,frames}],spreads:[{id:"",name:"",pageIds:["","!"]}],pages:[{id:"",name:"",spreadId:"",parentPageId:"",width:word,height:word,margins:{top:word,right:word,bottom:word,left:word},columns:{count:4294967295,gutter:word},guides:[rect],layerIds:[""],layers,frames,overrides:[{objectId:"",bounds,visible:false,locked:null},{objectId:"",bounds:null,visible:null,locked:true}]}],printTarget:"",dataFields:{entries:[{questionId:"",value:{kind:"text",value:"intrinsic data field\0"}}]},backgroundDrawing:{handle:{childId:id[0]!,target:{artifactId:id[4]!,dialect:{artifactKind:id[1]!,standard:id[2]!,subset:id[3]!}}},content:{schema:fixture.drawingSchema,canvas:{width:word,height:word,background:undefined},styles:[],layers:[]}},referencedModel:{target:{artifactId:"",dialect:{artifactKind:"",standard:"!/@",subset:""}},role:"",pin:{kind:"snapshot",blob:{hash:"",size:BigInt(fixture.maximumU64),mediaType:""}}}};};
test("Layout complete owned state has inspectable relationships and independent field edits",async()=>{const input=owned(),database=await layoutSnapshotToSqliteDatabase(input),oracle=Database.deserialize(await exportSqliteDatabase(database));try{expect(oracle.query("PRAGMA integrity_check").get()).toEqual({integrity_check:"ok"});expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(oracle.query(fixture.query).all()).toEqual([{artifact_kind:fixture.imageArtifactKind,artifact_ref:""}]);expect(oracle.query("SELECT count(*) AS n FROM layout_frame").get()).toEqual({n:6});expect(oracle.query("SELECT schema FROM semio_drawing_document JOIN layout_drawing_component ON drawing_id=semio_drawing_document.id").get()).toEqual({schema:fixture.drawingSchema});expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(input);oracle.exec("UPDATE layout_story SET content='edited'");const edited=owned();edited.stories[0]!.content="edited";expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(edited);}finally{oracle.close();}});
test("Layout entity bounds, literal optional branches and cancellation are controlled",async()=>{for(const kind of ["head","checkpoint"] as const){const input=owned();input.backgroundDrawing=undefined;input.referencedModel!.pin=kind==="head"?{kind}:{kind,id:""};input.printTarget=null;input.dataFields=undefined;expect(await layoutSnapshotFromSqliteDatabase(await layoutSnapshotToSqliteDatabase(input))).toEqual(input);}const input=owned(),database=await layoutSnapshotToSqliteDatabase(input),count=database.tables.reduce((n,t)=>n+t.rows.length,0);await expect(layoutSnapshotToSqliteDatabase(input,{maxRows:count-1})).rejects.toThrow();await expect(layoutSnapshotFromSqliteDatabase(database,{maxRows:count-1})).rejects.toThrow();await expect(layoutSnapshotFromSqliteDatabase(database,{maxValueBytes:1})).rejects.toThrow();const controller=new AbortController();controller.abort();await expect(layoutSnapshotToSqliteDatabase(input,{signal:controller.signal})).rejects.toThrow();await expect(layoutSnapshotFromSqliteDatabase(database,{signal:controller.signal})).rejects.toThrow();});

test("Layout inline Drawing owns actual entities and permits interior component cancellation",async()=>{const input=owned(),word=f64(fixture.float64Bits[7]!),point={x:word,y:word};input.backgroundDrawing!.content.layers=[{id:"",name:"",visible:false,root:{kind:"group",transform:{translation:{x:word,y:word,z:word},rotation:{x:word,y:word,z:word,w:word},scale:{x:word,y:word,z:word}},children:Array.from({length:fixture.componentNodes},(_,i)=>({kind:"image" as const,at:point,width:word,height:word,mime:"",bytes:new Uint8Array(i===0?fixture.intrinsicBytes:0).fill(255)}))}}];const database=await layoutSnapshotToSqliteDatabase(input),oracle=Database.deserialize(await exportSqliteDatabase(database));try{expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(oracle.query("SELECT count(*) AS n FROM semio_drawing_image").get()).toEqual({n:fixture.componentNodes});expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(input);}finally{oracle.close();}for(const direction of["projectSnapshot","reconstructSnapshot"] as const){const controller=new AbortController();let observed=false;const options={signal:controller.signal,onProgress:(p:{phase:string;completed:number})=>{if(p.phase===direction&&p.completed>=fixture.cancelAfter){observed=true;controller.abort();}}};if(direction==="projectSnapshot")await expect(layoutSnapshotToSqliteDatabase(input,options)).rejects.toThrow();else await expect(layoutSnapshotFromSqliteDatabase(database,options)).rejects.toThrow();expect(observed).toBe(true);}const bad=structuredClone(database);bad.tables.find(t=>t.name==="layout_drawing_component")!.rows[0]!.values[6]=2n;await expect(layoutSnapshotFromSqliteDatabase(bad)).rejects.toThrow();const foreign=structuredClone(database);foreign.tables.find(t=>t.name==="layout_frame_text")!.rows[0]!.values[0]=999n;await expect(layoutSnapshotFromSqliteDatabase(foreign)).rejects.toThrow();});

import {layoutArtifactFromNativeJson,layoutArtifactNativeJson} from "../../../📝️text/📸️snapshot/🪪️native-json/🟦️.ts";
import {layoutDiffFromNativeJson} from "../../../📝️text/🔺️diff/🪪️native-json/🟦️.ts";
import documents from "../../../../🧬️schema/🧫️fixtures/🪪️document/🔣️.json";
test("Layout native JSON explicitly names finite projection and owned nonfinite refusal",()=>{expect(layoutArtifactNativeJson(layoutArtifactFromNativeJson(documents.document))).toEqual(documents.document);expect(()=>layoutArtifactNativeJson(owned())).toThrow("finite number");});

import NativeAjv from "ajv";
import nativeSchema from "../../../../🧬️schema/📸️snapshot/🔣️.json";
test("Layout borrowed inline Drawing preserves a deep typed component with independently counted relationships",async()=>{
  const input=owned(),word=f64(fixture.float64Bits[7]!),point={x:word,y:word},vector={...point,z:word},transform={translation:vector,rotation:{...vector,w:word},scale:vector};
  let root:NonNullable<LayoutArtifact["backgroundDrawing"]>["content"]["layers"][number]["root"]={kind:"image",at:point,width:word,height:word,mime:"literal\0",bytes:new Uint8Array([0,127,255])};
  for(let i=0;i<fixture.componentDepth;i++)root={kind:"group",transform,children:[root]};
  input.backgroundDrawing!.content.layers=[{id:"",name:"",visible:false,root}];
  const oracle=Database.deserialize(await exportSqliteDatabase(await layoutSnapshotToSqliteDatabase(input)));
  try{
    expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);
    expect(oracle.query("SELECT count(*) AS n FROM semio_drawing_group").get()).toEqual({n:fixture.componentDepth});
    expect(oracle.query("SELECT count(*) AS n FROM semio_drawing_child").get()).toEqual({n:fixture.componentDepth});
    const result=await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()));
    expect(result.backgroundDrawing!.handle).toEqual(input.backgroundDrawing!.handle);
    let node=result.backgroundDrawing!.content.layers[0]!.root,count=0;
    while(node.kind==="group"){expect(node.transform.translation.x).toEqual(word);expect(node.children.length).toBe(1);node=node.children[0]!;count++;}
    expect(count).toBe(fixture.componentDepth);expect(node).toEqual({kind:"image",at:point,width:word,height:word,mime:"literal\0",bytes:new Uint8Array([0,127,255])});
  }finally{oracle.close();}
});
test("Layout native JSON obeys unsigned numeric schema without inventing decimal-string wire fields",()=>{
  const validator=new NativeAjv({strict:true}).addKeyword({keyword:"x-semio-ui",metaSchema:{type:"object"}}).compile(nativeSchema.$defs.TextStyleRun);
  const maximum=BigInt(fixture.maximumU64),run={start:maximum,end:maximum,paragraphStyleId:null,characterStyleId:null};
  expect(validator({start:0,end:0,paragraphStyleId:null,characterStyleId:null})).toBe(true);
  expect(validator({...run,start:maximum.toString(),end:maximum.toString()})).toBe(false);
  const value=layoutArtifactFromNativeJson(documents.document);
  value.stories.push({id:"wide-native-boundary",content:"",styleRuns:[run]});
  expect(()=>layoutArtifactNativeJson(value)).toThrow("unsigned64");
  const invalid=structuredClone(documents.document) as unknown as {stories:{id:string;content:string;styleRuns:unknown[]}[]};
  invalid.stories.push({id:"wide-native-boundary",content:"",styleRuns:[{...run,start:maximum.toString(),end:maximum.toString()}]});
  expect(()=>layoutArtifactFromNativeJson(invalid)).toThrow("unsigned64");
});

import dictionaryFixture from "../🧫️fixtures/🧾️dictionary/🔣️.json";

import {parseLayoutArtifact} from "../../../../🧬️schema/🟦️.ts";
import type{IntrinsicValue}from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🧬️schema/🟦️.ts";
import dictionaryNativeSchema from "../../../../../../../../../../../📋️forms/🗿️artifacts/📋️forms/🏅️standards/🔖️1/🪆️subsets/✳️any/🧬️schema/🧾️dictionary/🔣️.json";
import{formDictionaryNativeJson,formDictionaryFromNativeJson}from"../../../../../../../../../../../📋️forms/🗿️artifacts/📋️forms/🏅️standards/🔖️1/🪆️subsets/✳️any/🚪️io/📝️text/📸️snapshot/🧾️dictionary/🪪️native-json/🟦️.ts";
import{parseMediaPayload}from"../../../../../../../../../../../../../🧰️framework/🔨️modules/🛂️manifest/🎞️media/🟦️.ts";
import unsignedFixture from"../🧫️fixtures/🧾️dictionary/🔢️unsigned/🔣️.json";

const dictionaryValue=(source:unknown):IntrinsicValue=>{
 const value=source as{kind:string;value?:unknown;items?:unknown[];members?:{name:string;value:unknown}[]};
 switch(value.kind){
  case"null":return{kind:"null"};
  case"boolean":return{kind:"boolean",value:value.value as boolean};
  case"unsigned":case"signed":return{kind:value.kind,value:BigInt(value.value as string)};
  case"float":return{kind:"float",value:{bits:BigInt("0x"+value.value)}};
  case"text":return{kind:"text",value:value.value as string};
  case"bytes":return{kind:"bytes",value:Uint8Array.from(value.value as number[])};
  case"array":return{kind:"array",items:value.items!.map(dictionaryValue)};
  case"object":return{kind:"object",members:value.members!.map(member=>({name:member.name,value:dictionaryValue(member.value)}))};
  default:throw Error("unrecognized neutral intrinsic kind");
 }
};
test("Layout owns optional FormDictionary and every intrinsic domain without a JSON source",async()=>{
 expect(dictionaryFixture["schema"]).toEqual("layout.form-dictionary/v1");expect(dictionaryFixture["valueKinds"]).toEqual(["null","boolean","unsigned","signed","float","text","bytes","array","object"]);expect(dictionaryFixture["tables"]).toEqual(["layout_form_dictionary","layout_dictionary_entry","layout_dictionary_value","layout_dictionary_boolean","layout_dictionary_unsigned","layout_dictionary_signed","layout_dictionary_float","layout_dictionary_text","layout_dictionary_bytes","layout_dictionary_array","layout_dictionary_member"]);expect(dictionaryFixture["refusals"]).toEqual(["duplicateQuestionId","orphanValue","sparseOrdinal","wrongScalarKind","sharedValueOwner"]);expect(dictionaryFixture["absence"]).toEqual("noDictionaryRow");expect(dictionaryFixture["empty"]).toEqual("dictionaryRowWithoutEntries");expect(dictionaryFixture["memberNull"]).toEqual("entryWithNullValue");expect(dictionaryFixture["allocation"]).toEqual("fullConcreteRequests");expect(dictionaryFixture["retirementRefund"]).toEqual(false);expect(dictionaryFixture["nativePreflight"]["schema"]).toEqual("layout.borrowed-native/v1");expect(dictionaryFixture["nativePreflight"]["encodings"]).toEqual(["binary","text"]);expect(dictionaryFixture["nativePreflight"]["scratchOwnership"]).toEqual("paidFrontiersOnly");
 const dictionary={entries:dictionaryFixture.dictionary.entries.map(entry=>({questionId:entry.questionId,value:dictionaryValue(entry.value)}))};
 expect(dictionary.entries.map(entry=>entry.value.kind)).toEqual(dictionaryFixture.valueKinds);
 const unsigned=(dictionary.entries[2]!.value as Extract<IntrinsicValue,{kind:"unsigned"}>).value,signed=(dictionary.entries[3]!.value as Extract<IntrinsicValue,{kind:"signed"}>).value;
 expect(unsigned).toBe(18446744073709551615n);expect(signed).toBe(-9223372036854775808n);
 for(const word of dictionaryFixture.floatWords){const view=new DataView(new ArrayBuffer(8));view.setBigUint64(0,BigInt("0x"+word),true);expect(view.getBigUint64(0,true).toString(16).padStart(16,"0")).toBe(word);}
 const input={...owned(),dataFields:dictionary} as Record<string,unknown>;delete input.dataFieldsJson;
 const parsed=parseLayoutArtifact(input);expect((parsed as unknown as{dataFields:typeof dictionary}).dataFields).toEqual(dictionary);
 const database=await layoutSnapshotToSqliteDatabase(parsed),oracle=Database.deserialize(await exportSqliteDatabase(database),{safeIntegers:true});
 try{
  const tables=(oracle.query("SELECT name FROM sqlite_schema WHERE type='table'").all() as{name:string}[]).map(row=>row.name);
  for(const table of dictionaryFixture.tables)expect(tables).toContain(table);
  const columns=(oracle.query("PRAGMA table_info(layout_document)").all() as{name:string}[]).map(row=>row.name);expect(columns).not.toContain("data_fields_json");
  expect(oracle.query("SELECT question_id FROM layout_dictionary_entry ORDER BY ordinal").all()).toEqual(dictionary.entries.map(entry=>({question_id:entry.questionId})));
  const wide=oracle.query("SELECT value FROM layout_dictionary_unsigned ORDER BY id LIMIT 1").get()as{value:string};expect(wide.value).toBe(unsigned.toString());
  expect(oracle.query("SELECT value FROM layout_dictionary_signed").get()).toEqual({value:signed});
  expect(oracle.query("SELECT value FROM layout_dictionary_bytes ORDER BY id LIMIT 1").get()).toEqual({value:Buffer.from([0,127,255])});
  expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);
  expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(parsed);
 }finally{oracle.close();}
 for(const dataFields of[undefined,{entries:[]}]){const input={...owned()} as Record<string,unknown>;delete input.dataFields;if(dataFields!==undefined)input.dataFields=dataFields;const actual=parseLayoutArtifact(input),database=await layoutSnapshotToSqliteDatabase(actual),oracle=Database.deserialize(await exportSqliteDatabase(database));try{expect(oracle.query("SELECT count(*) AS n FROM layout_form_dictionary").get()).toEqual({n:dataFields===undefined?0:1});expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(actual);}finally{oracle.close();}}
 const duplicate={...input,dataFields:{entries:[dictionary.entries[0],dictionary.entries[0]]}};expect(()=>parseLayoutArtifact(duplicate)).toThrow();
 const fields={entries:dictionaryFixture.floatWords.map((bits,index)=>({questionId:"word"+index,value:{kind:"float" as const,value:{bits:BigInt("0x"+bits)}}}))},allWords=parseLayoutArtifact({...owned(),dataFields:fields}),wordsDatabase=await layoutSnapshotToSqliteDatabase(allWords),wordsOracle=Database.deserialize(await exportSqliteDatabase(wordsDatabase),{safeIntegers:true});
 try{const rows=wordsOracle.query("SELECT value_ieee754_bits AS bits FROM layout_dictionary_float JOIN layout_scalar64 ON layout_scalar64.id=scalar_id ORDER BY layout_dictionary_float.id").all()as{bits:bigint}[];expect(rows.map(row=>BigInt.asUintN(64,row.bits))).toEqual(fields.entries.map(entry=>entry.value.value.bits));expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(wordsOracle.serialize()))).toEqual(allWords);}finally{wordsOracle.close();}
 const json=formDictionaryNativeJson(dictionary);expect(new NativeAjv({strict:true}).addKeyword({keyword:"x-semio-ui",metaSchema:{type:"object"}}).validate(dictionaryNativeSchema,json)).toBe(true);expect(formDictionaryFromNativeJson(JSON.parse(JSON.stringify(json)))).toEqual(dictionary);
 const valid=await layoutSnapshotToSqliteDatabase(parsed);
 for(const refusal of dictionaryFixture.refusals){
  const malformed={tables:valid.tables.map(table=>({...table,rows:table.rows.map(row=>({...row,values:[...row.values]}))}))},table=(name:string)=>malformed.tables.find(table=>table.name===name)!;
  switch(refusal){
   case"duplicateQuestionId":table("layout_dictionary_entry").rows[1]!.values[3]=table("layout_dictionary_entry").rows[0]!.values[3]!;break;
   case"orphanValue":{const values=table("layout_dictionary_value");values.rows.push({rowid:100000n,values:[100000n,"null"]});break;}
   case"sparseOrdinal":table("layout_dictionary_entry").rows[1]!.values[2]=999n;break;
   case"wrongScalarKind":table("layout_dictionary_value").rows.find(row=>row.values[1]==="boolean")!.values[1]="signed";break;
   case"sharedValueOwner":table("layout_dictionary_entry").rows[1]!.values[4]=table("layout_dictionary_entry").rows[0]!.values[4]!;break;
  }
  await expect(layoutSnapshotFromSqliteDatabase(malformed)).rejects.toThrow();
 }
});
test("Forms and Layout transport the complete dictionary as actual intrinsic media",()=>{
 expect(dictionaryFixture["schema"]).toEqual("layout.form-dictionary/v1");expect(dictionaryFixture["valueKinds"]).toEqual(["null","boolean","unsigned","signed","float","text","bytes","array","object"]);expect(dictionaryFixture["tables"]).toEqual(["layout_form_dictionary","layout_dictionary_entry","layout_dictionary_value","layout_dictionary_boolean","layout_dictionary_unsigned","layout_dictionary_signed","layout_dictionary_float","layout_dictionary_text","layout_dictionary_bytes","layout_dictionary_array","layout_dictionary_member"]);expect(dictionaryFixture["refusals"]).toEqual(["duplicateQuestionId","orphanValue","sparseOrdinal","wrongScalarKind","sharedValueOwner"]);expect(dictionaryFixture["absence"]).toEqual("noDictionaryRow");expect(dictionaryFixture["empty"]).toEqual("dictionaryRowWithoutEntries");expect(dictionaryFixture["memberNull"]).toEqual("entryWithNullValue");expect(dictionaryFixture["allocation"]).toEqual("fullConcreteRequests");expect(dictionaryFixture["retirementRefund"]).toEqual(false);expect(dictionaryFixture["nativePreflight"]["schema"]).toEqual("layout.borrowed-native/v1");expect(dictionaryFixture["nativePreflight"]["encodings"]).toEqual(["binary","text"]);expect(dictionaryFixture["nativePreflight"]["scratchOwnership"]).toEqual("paidFrontiersOnly");
 const value:IntrinsicValue={kind:"object",members:dictionaryFixture.dictionary.entries.map(entry=>({name:entry.questionId,value:dictionaryValue(entry.value)}))},payload={kind:"intrinsic" as const,schema:"form.dictionary",value};
 expect(parseMediaPayload(payload)).toEqual(payload);
 expect(value.members.find(member=>member.value.kind==="unsigned")!.value).toEqual({kind:"unsigned",value:18446744073709551615n});
 const octets=value.members.find(member=>member.value.kind==="bytes")!.value as Extract<IntrinsicValue,{kind:"bytes"}>;expect(Buffer.from(octets.value).toString("hex")).toBe("007fff");
 const json=formDictionaryNativeJson({entries:value.members.map(member=>({questionId:member.name,value:member.value}))});expect(formDictionaryFromNativeJson(JSON.parse(JSON.stringify(json)))).toEqual({entries:value.members.map(member=>({questionId:member.name,value:member.value}))});
});
test("Layout dictionary unsigned magnitudes are independently readable and editable decimal SQL values",async()=>{
 expect(unsignedFixture["schema"]).toEqual("layout.dictionary-unsigned/v1");expect(unsignedFixture["storage"]).toEqual("canonicalDecimalText");expect(unsignedFixture["accepted"]).toEqual(["0","1","9223372036854775808","18446744073709551615"]);expect(unsignedFixture["refused"]).toEqual(["","00","01","-1","+1","1.0"," 1","1 ","18446744073709551616","184467440737095516150"]);
 const value=owned();value.dataFields={entries:unsignedFixture.accepted.map((magnitude,index)=>({questionId:String(index),value:{kind:"unsigned",value:BigInt(magnitude)}}))};
 const database=await layoutSnapshotToSqliteDatabase(value),oracle=Database.deserialize(await exportSqliteDatabase(database));
 try{expect(oracle.query("SELECT value FROM layout_dictionary_unsigned ORDER BY id").all()).toEqual(unsignedFixture.accepted.map(value=>({value})));oracle.query("UPDATE layout_dictionary_unsigned SET value=? WHERE id=(SELECT min(id) FROM layout_dictionary_unsigned)").run("18446744073709551615");const edited=await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()));expect(edited.dataFields!.entries[0]!.value).toEqual({kind:"unsigned",value:18446744073709551615n});}finally{oracle.close();}
 for(const magnitude of unsignedFixture.refused){const malformed={tables:database.tables.map(table=>({...table,rows:table.rows.map(row=>({...row,values:[...row.values]}))}))},table=malformed.tables.find(table=>table.name==="layout_dictionary_unsigned")!;table.rows[0]!.values[1]=magnitude;await expect(layoutSnapshotFromSqliteDatabase(malformed)).rejects.toThrow();}
});

import changeFixture from "../🧫️fixtures/🧾️dictionary/🔺️diff/🔣️.json";

import{parseLayoutDiff}from"../../../../🧬️schema/🔺️diff/🟦️.ts";
test("Layout dictionary changes distinguish unchanged, clear, present empty and member null",()=>{
 expect(changeFixture["schema"]).toEqual("layout.dictionary-change/v1");expect(changeFixture["states"]).toEqual([{"name":"unchanged","change":null},{"name":"clear","change":{"dictionary":null}},{"name":"empty","change":{"dictionary":{"entries":[]}}},{"name":"memberNull","change":{"dictionary":{"entries":[{"questionId":"","value":{"kind":"null"}}]}}}]);
 for(const state of changeFixture.states){const change=state.change,wire=JSON.parse(Buffer.from(JSON.stringify({...documents.diff,dataFields:change}),"utf8").toString("utf8")),actual=layoutDiffFromNativeJson(wire);expect(actual.dataFields).toEqual(change);}
 expect(()=>parseLayoutDiff({...documents.diff,dataFields:{dictionary:null,extra:true}})).toThrow();
});

import{parse as parseGraphql,buildASTSchema,graphql,GraphQLScalarType,Kind}from"graphql";
import interfaceFixture from"../🧫️fixtures/🧾️dictionary/🌐️interfaces/🔣️.json";

test("Shared intrinsic interfaces own nine typed cases, complete magnitudes, words, octets and ordered members",async()=>{
 expect(interfaceFixture["schema"]).toEqual("intrinsic.value-interface/v1");expect(interfaceFixture["variants"]).toEqual(["DslNull","DslBoolean","DslUnsigned","DslSigned","DslFloat","DslText","DslBytes","DslArray","DslObject"]);expect(interfaceFixture["unsigned"]).toEqual(["0","18446744073709551615"]);expect(interfaceFixture["signed"]).toEqual(["-9223372036854775808","9223372036854775807"]);expect(interfaceFixture["refusedUnsigned"]).toEqual(["-1","00","18446744073709551616"]);expect(interfaceFixture["floatBits"]).toEqual(["0000000000000000","8000000000000000","0000000000000001","0010000000000000","7fefffffffffffff","7ff0000000000000","fff0000000000000","7ff8000000000001"]);expect(interfaceFixture["bytes"]).toEqual([0,127,128,255]);expect(interfaceFixture["members"]).toEqual(["","\u0000","repeat","repeat"]);
 const base="../../../../../../../../../../../../../🧰️framework/🔨️modules/🌱️value/🧬️schema",text=await Bun.file(new URL(base+"🔗️.graphql",import.meta.url)).text(),document=parseGraphql(text),union=document.definitions.find(definition=>definition.kind===Kind.UNION_TYPE_DEFINITION&&definition.name.value==="DslValue");
 expect(union?.kind===Kind.UNION_TYPE_DEFINITION?union.types!.map(type=>type.name.value):[]).toEqual(interfaceFixture.variants);
 const proto=await Bun.file(new URL(base+"🛰️.proto",import.meta.url)).text();expect(proto).toContain("fixed64 float_bits = 3");expect(proto).toContain("bytes bytes_value = 7");
 const schema=buildASTSchema(parseGraphql(text+"\ntype Query { value: DslValue! }")),type=schema.getType("UInt64")as GraphQLScalarType;
 type.coerceOutputValue=value=>{const text=String(value);if(!/^(0|[1-9][0-9]*)$/.test(text)||text.length>20||BigInt(text)>0xffffffffffffffffn)throw Error("unsigned magnitude");return text;};
 for(const word of interfaceFixture.floatBits){const result=await graphql({schema,source:"{value{... on DslFloat{bits}}}",rootValue:{value:{__typename:"DslFloat",bits:BigInt("0x"+word)}}});expect(result.errors).toBeUndefined();expect(result.data).toEqual({value:{bits:BigInt("0x"+word).toString()}});const bytes=Buffer.alloc(8);bytes.writeBigUInt64LE(BigInt("0x"+word));expect(bytes.readBigUInt64LE().toString(16).padStart(16,"0")).toBe(word);}
 const signed=schema.getType("Int64")as GraphQLScalarType;signed.coerceOutputValue=value=>{const text=String(value);if(!/^(0|-?[1-9][0-9]*)$/.test(text)||text.length>20||BigInt(text)<-0x8000000000000000n||BigInt(text)>0x7fffffffffffffffn)throw Error("signed magnitude");return text;};
 for(const magnitude of interfaceFixture.signed){const result=await graphql({schema,source:"{value{... on DslSigned{value}}}",rootValue:{value:{__typename:"DslSigned",value:magnitude}}});expect(result.errors).toBeUndefined();expect(result.data).toEqual({value:{value:magnitude}});}
 for(const magnitude of interfaceFixture.unsigned){const result=await graphql({schema,source:"{value{... on DslUnsigned{value}}}",rootValue:{value:{__typename:"DslUnsigned",value:magnitude}}});expect(result.errors).toBeUndefined();expect(result.data).toEqual({value:{value:magnitude}});}
 for(const magnitude of interfaceFixture.refusedUnsigned){const result=await graphql({schema,source:"{value{... on DslUnsigned{value}}}",rootValue:{value:{__typename:"DslUnsigned",value:magnitude}}});expect(result.errors?.length).toBe(1);}
 const result=await graphql({schema,source:"{value{... on DslObject{members{name value{... on DslBytes{value}}}}}}",rootValue:{value:{__typename:"DslObject",members:interfaceFixture.members.map(name=>({name,value:{__typename:"DslBytes",value:interfaceFixture.bytes}}))}}});expect(result.errors).toBeUndefined();expect(result.data).toEqual({value:{members:interfaceFixture.members.map(name=>({name,value:{value:interfaceFixture.bytes}}))}});
});

test("Layout borrowed native preflight declares prospective ceilings and actual scratch ownership",()=>{
 const expected={schema:"layout.borrowed-native/v1",encodings:["binary","text"],scratchOwnership:"paidFrontiersOnly",copiedOwnerFields:false,forecastCeilings:["maxFileBytes","maxValueBytes"],ownedAllowance:"maxAllocationBytes",literal:"é語🧾",repeat:14564,utf8Bytes:131076,cancelAfterBytes:65536};
 const contract=(dictionaryFixture as unknown as {nativePreflight?:typeof expected}).nativePreflight;
 expect(contract).toEqual(expected);if(!contract)throw Error("Layout neutral native preflight facet missing");
 const literal=contract.literal.repeat(contract.repeat);expect(Buffer.byteLength(literal,"utf8")).toBe(contract.utf8Bytes);
 const oracle=new Database(":memory:");try{oracle.exec("CREATE TABLE borrowed_dictionary_literal(value TEXT NOT NULL)");oracle.run("INSERT INTO borrowed_dictionary_literal VALUES(?)",[literal]);expect(oracle.query("SELECT length(CAST(value AS BLOB)) AS bytes FROM borrowed_dictionary_literal").get()).toEqual({bytes:contract.utf8Bytes});expect(oracle.query("SELECT value FROM borrowed_dictionary_literal").get()).toEqual({value:literal});}finally{oracle.close();}
 expect(contract.forecastCeilings).not.toContain(contract.ownedAllowance);expect(contract.cancelAfterBytes).toBeGreaterThan(0);expect(contract.cancelAfterBytes).toBeLessThan(contract.utf8Bytes);
});

test("Live Forms to Layout transport names real VCS boundaries and complete intrinsic fields",()=>{
 const expected={"schema":"forms.layout.intrinsic-vcs/v1","producer":"FormsPlayApp","consumer":"LayoutPlayApp","output":"dictionary:out","input":"fields:in","wire":"intrinsic","payloadSchema":"form.dictionary","questionIds":["null","flag","wide","signed","word","literal\u0000語","octets","ordered","unknown","word0","word1","word2","word3","word4","word5","word6","word7"],"flow":["registeredEditor","documentPackLoad","produceMedia","wirePackRoundTrip","consumeMedia","reservedImportJob","documentEmit","typedTargetSnapshot"],"failureBeforeDispatch":"unchangedRevision","completedOwner":"terminalEmpty"},contract=(dictionaryFixture as unknown as {liveVcs?:typeof expected}).liveVcs;
 expect(contract).toEqual(expected);if(!contract)throw Error("Live VCS neutral facet missing");
 expect(dictionaryFixture["schema"]).toEqual("layout.form-dictionary/v1");expect(dictionaryFixture["valueKinds"]).toEqual(["null","boolean","unsigned","signed","float","text","bytes","array","object"]);expect(dictionaryFixture["tables"]).toEqual(["layout_form_dictionary","layout_dictionary_entry","layout_dictionary_value","layout_dictionary_boolean","layout_dictionary_unsigned","layout_dictionary_signed","layout_dictionary_float","layout_dictionary_text","layout_dictionary_bytes","layout_dictionary_array","layout_dictionary_member"]);expect(dictionaryFixture["refusals"]).toEqual(["duplicateQuestionId","orphanValue","sparseOrdinal","wrongScalarKind","sharedValueOwner"]);expect(dictionaryFixture["absence"]).toEqual("noDictionaryRow");expect(dictionaryFixture["empty"]).toEqual("dictionaryRowWithoutEntries");expect(dictionaryFixture["memberNull"]).toEqual("entryWithNullValue");expect(dictionaryFixture["allocation"]).toEqual("fullConcreteRequests");expect(dictionaryFixture["retirementRefund"]).toEqual(false);expect(dictionaryFixture["nativePreflight"]["schema"]).toEqual("layout.borrowed-native/v1");expect(dictionaryFixture["nativePreflight"]["encodings"]).toEqual(["binary","text"]);expect(dictionaryFixture["nativePreflight"]["scratchOwnership"]).toEqual("paidFrontiersOnly");
 const names=contract.questionIds,oracle=new Database(":memory:");
 try{oracle.exec("CREATE TABLE live_value(ordinal INTEGER PRIMARY KEY,question_id TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,word BLOB)");for(const[index,entry]of dictionaryFixture.dictionary.entries.entries())oracle.run("INSERT INTO live_value VALUES(?,?,?,NULL)",[index,names[index]!,entry.value.kind]);for(const[index,word]of dictionaryFixture.floatWords.entries()){const bytes=Buffer.alloc(8);bytes.writeBigUInt64LE(BigInt("0x"+word));oracle.run("INSERT INTO live_value VALUES(?,?,?,?)",[index+9,names[index+9]!,"float",bytes]);}expect(oracle.query("SELECT question_id,kind FROM live_value ORDER BY ordinal").all()).toEqual(names.map((question_id,index)=>({question_id,kind:index<9?dictionaryFixture.valueKinds[index]!:"float"})));const words=oracle.query("SELECT word FROM live_value WHERE word IS NOT NULL ORDER BY ordinal").all() as {word:Uint8Array}[];expect(words.map(row=>Buffer.from(row.word).readBigUInt64LE().toString(16).padStart(16,"0"))).toEqual(dictionaryFixture.floatWords);expect(oracle.query("SELECT length(CAST(question_id AS BLOB)) AS bytes FROM live_value WHERE ordinal=5").get()).toEqual({bytes:Buffer.byteLength(names[5]!)});}finally{oracle.close();}
});

import byteOwner from "../🧫️fixtures/🧾️dictionary/💰️bytes/🔣️.json";

import {sqliteOperation} from "../../../../../../../../../../../../../🧰️framework/🔨️modules/🚪️io/🪶️sqlite-snapshot/🟦️.ts";
import topologyOwner from "../🧫️fixtures/🧱️capture/🔣️.json";

test("Layout complete relational topology is captured before actual mutable callbacks",async()=>{
 const expected={authority:"literalSqlTopologyBeforeCallback",layoutTables:43,mutations:["tableMetadata","rowOwnerArray","cellOwnerArray","literalCellReplacement","tableOwnerArray"]};expect(topologyOwner["authority"]).toEqual("literalSqlTopologyBeforeCallback");expect(topologyOwner["layoutTables"]).toEqual(43);expect(topologyOwner["mutations"]).toEqual(["tableMetadata","rowOwnerArray","cellOwnerArray","literalCellReplacement","tableOwnerArray"]);expect(topologyOwner).toEqual(expected);
 const input=owned();input.dataFields={entries:dictionaryFixture.dictionary.entries.map(entry=>({questionId:entry.questionId,value:dictionaryValue(entry.value)}))};
 const database=await layoutSnapshotToSqliteDatabase(input),oracle=Database.deserialize(await exportSqliteDatabase(database),{safeIntegers:true});
 try{expect(oracle.query("SELECT count(*) AS n FROM sqlite_schema WHERE type='table' AND name LIKE 'layout_%'").get()).toEqual({n:BigInt(expected.layoutTables)});expect(oracle.query("SELECT value FROM layout_dictionary_unsigned ORDER BY id LIMIT 1").get()).toEqual({value:"18446744073709551615"});expect(oracle.query("PRAGMA foreign_key_check").all()).toEqual([]);expect(await layoutSnapshotFromSqliteDatabase(await importSqliteDatabase(oracle.serialize()))).toEqual(input)}finally{oracle.close()}
 for(const mutation of expected.mutations){const incoming=structuredClone(database),document=incoming.tables.find(table=>table.name==="layout_document")!;let reached=false;const control=sqliteOperation({onProgress:()=>{if(reached)return;reached=true;switch(mutation){case"tableMetadata":Reflect.set(document,"name","mutated");Reflect.set(document,"sql","");break;case"rowOwnerArray":for(const table of incoming.tables)Reflect.set(table.rows,"length",0);break;case"cellOwnerArray":Reflect.set(document.rows[0]!,"values",[]);break;case"literalCellReplacement":Reflect.set(document.rows[0]!.values,1,"mutated schema");Reflect.set(document.rows[0]!.values,2,"mutated name");break;case"tableOwnerArray":Reflect.set(incoming.tables,"length",0);break;}}});expect(await layoutSnapshotFromSqliteDatabase(incoming,control)).toEqual(input);expect(reached).toBe(true);expect(control.ownedBytes).toBeGreaterThan(0)}
});
test("Layout dictionary closed owned byte contract agrees with independent octets",()=>{
 expect(byteOwner["authority"]).toEqual("sameCallerOwnedByteCopy");expect(byteOwner["pattern"]).toEqual([0,127,255]);expect(byteOwner["repeat"]).toEqual(23400);expect(byteOwner["longBytes"]).toEqual(70200);expect(byteOwner["minimumInterior"]).toEqual(32768);expect(byteOwner["cancelKind"]).toEqual("canceled");expect(Reflect.get(byteOwner,"authority")).toBe("sameCallerOwnedByteCopy");
 
 const pattern=Buffer.from(Reflect.get(byteOwner,"pattern")),bytes=Buffer.alloc(Reflect.get(byteOwner,"longBytes")).fill(pattern);expect(bytes.length).toBe(pattern.length*Reflect.get(byteOwner,"repeat"));expect(bytes.subarray(0,pattern.length).toString("hex")).toBe("007fff");
 const db=new Database(":memory:");try{db.exec("CREATE TABLE oracle(value BLOB NOT NULL)");db.query("INSERT INTO oracle VALUES(?)").run(bytes);expect(db.query("SELECT length(value) AS bytes, hex(substr(value,1,3)) AS prefix FROM oracle").get()).toEqual({bytes:Reflect.get(byteOwner,"longBytes"),prefix:"007FFF"})}finally{db.close()}
});
test("Layout dictionary restores independent bytes through exact cumulative caller backing",async()=>{
 expect(Reflect.get(byteOwner,"authority")).toBe("sameCallerOwnedByteCopy");
 const pattern=Buffer.from(Reflect.get(byteOwner,"pattern")),reference=Buffer.alloc(Reflect.get(byteOwner,"longBytes")).fill(pattern),make=(bytes:Uint8Array)=>{const value=owned();value.backgroundDrawing=undefined;value.dataFields={entries:[{questionId:"literal\0😀",value:{kind:"bytes",value:bytes}}]};return value;},resultBytes=(value:LayoutArtifact)=>{const field=value.dataFields!.entries[0]!.value;expect(field.kind).toBe("bytes");if(field.kind!=="bytes")throw Error("actual intrinsic byte owner required");return field.value;};
 const small=make(Uint8Array.from(pattern)),large=make(Uint8Array.from(reference)),smallDatabase=await layoutSnapshotToSqliteDatabase(small),database=await layoutSnapshotToSqliteDatabase(large),smallControl=sqliteOperation(),control=sqliteOperation();expect(await layoutSnapshotFromSqliteDatabase(smallDatabase,smallControl)).toEqual(small);const restored=await layoutSnapshotFromSqliteDatabase(database,control);expect(restored).toEqual(large);
 const incoming=database.tables.find(table=>table.name==="layout_dictionary_bytes")!.rows[0]!.values[1] as Uint8Array;expect(incoming instanceof Uint8Array).toBe(true);expect(resultBytes(restored)).not.toBe(incoming);incoming[0]=255;expect(resultBytes(restored)[0]).toBe(0);incoming[0]=0;expect(Buffer.from(resultBytes(restored)).equals(reference)).toBe(true);
 expect(control.ownedBytes-smallControl.ownedBytes).toBe(reference.length-pattern.length);
 const exact=sqliteOperation({maxAllocationBytes:control.ownedBytes});expect(await layoutSnapshotFromSqliteDatabase(database,exact)).toEqual(large);expect(exact.remainingBytes()).toBe(0);await expect(layoutSnapshotFromSqliteDatabase(database,exact)).rejects.toMatchObject({kind:"ownershipLimit"});
 await expect(layoutSnapshotFromSqliteDatabase(database,{maxAllocationBytes:control.ownedBytes-1})).rejects.toMatchObject({kind:"ownershipLimit"});
 const cumulative=sqliteOperation({maxAllocationBytes:control.ownedBytes*2});expect(await layoutSnapshotFromSqliteDatabase(database,cumulative)).toEqual(large);expect(await layoutSnapshotFromSqliteDatabase(database,cumulative)).toEqual(large);expect(cumulative.remainingBytes()).toBe(0);await expect(layoutSnapshotFromSqliteDatabase(database,cumulative)).rejects.toMatchObject({kind:"ownershipLimit"});
 const abort=new AbortController();let reached=false;const canceled=sqliteOperation({signal:abort.signal,onProgress:event=>{if(event.phase==="reconstructSnapshot"&&event.completed>=Reflect.get(byteOwner,"minimumInterior")&&event.completed<event.total){reached=true;abort.abort()}}});await expect(layoutSnapshotFromSqliteDatabase(database,canceled)).rejects.toMatchObject({kind:Reflect.get(byteOwner,"cancelKind")});expect(reached).toBe(true);expect(canceled.ownedBytes).toBeGreaterThanOrEqual(reference.length);expect(Buffer.from(incoming).equals(reference)).toBe(true);
});
