# 🧬️ EN 1997 snapshot schema.

type En1997Snapshot {
  vEdKn: Float! @state(class: ARTIFACT)
  hEdKn: Float! @state(class: ARTIFACT)
  footingAreaM2: Float! @state(class: ARTIFACT)
  phiDeg: Float! @state(class: ARTIFACT)
  cKpa: Float! @state(class: ARTIFACT)
  gammaKnM3: Float! @state(class: ARTIFACT)
  bM: Float! @state(class: ARTIFACT)
  dFM: Float! @state(class: ARTIFACT)
  eSMpa: Float! @state(class: ARTIFACT)
  nu: Float! @state(class: ARTIFACT)
  designApproach: Float! @state(class: ARTIFACT)
  annex: Float! @state(class: ARTIFACT)
  settlementLimitMm: Float! @state(class: ARTIFACT)
  nPileEdKn: Float! @state(class: ARTIFACT)
  alphaS: Float! @state(class: ARTIFACT)
  pileDM: Float! @state(class: ARTIFACT)
  qSKpa: Float! @state(class: ARTIFACT)
  pileLM: Float! @state(class: ARTIFACT)
  qBKpa: Float! @state(class: ARTIFACT)
  pileBaseAreaM2: Float! @state(class: ARTIFACT)
  pileNProfiles: Int! @state(class: ARTIFACT)
  zInvestigatedM: Float! @state(class: ARTIFACT)
}
