local_repository(
    name = "semio",
    path = "../..",
)

load("@semio//buf:repositories.bzl", "semio_dependencies", "semio_toolchains")

semio_dependencies()

semio_toolchains(version = "v1.5.0")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()
