[package]
name = "semio-framework-os-kernel-math-graph-dag"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"


[lints]
workspace = true
[lib]
name = "mathematical_graph_dag"
crate-type = ["rlib"]
path = "../../../../🕸️graph/🕸️dag/⚡️implementation/🦀️rust/📦️lib.rs"

[dependencies]
mathematical_graph = { path = "../../../../🕸️graph/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-graph" }
mathematical_graph_traversal = { path = "../../../../🕸️graph/🚶️traversal/⚡️implementation/🦀️rust", package = "semio-framework-os-kernel-math-graph-traversal" }
